### ISSUE TITLE
Letterboxing in iPhone5

### ISSUE THREAD

**Issue by Mortoc** [kivy/kivy#1097]
When I build to the iPhone5, the app doesn't run fullscreen (there's letterboxing at the top and bottom, see attached screenshot).

![bRoam](https://f.cloud.github.com/assets/1915203/368374/9fcade8a-a2be-11e2-9477-6edca3a1f34f.png)

**Comment by akshayaurora** [comment]
Solution as @kalyan02 mentioned use correct splash image
