### ISSUE TITLE
Crash on Intel graphics card (when window is minimized)

### ISSUE THREAD

**Issue by tito** [kivy/kivy#1101]
One guy have experienced a crash, reproducible on an intel card on Windows 7: If the window is minimized, and if the graphics changed, there is a crash.

Now i don't know exactly what is crashing exactly, if any gl call crash, of if it's the flip.

Will try to get more info.
##

**Comment by pyfrid** [comment]
I confirm. It happens randomly and window should not be necessarily minimized.

**Comment by Julian-O** [comment]
Closing as stale.
