### ISSUE TITLE
.kv is not binding to updates in properties of elements of a dictionary

### ISSUE THREAD

**Issue by matham** [kivy/kivy#1111]
If my app has a dictionary called dict, which say looks something like this :

```
dict = DictProperty({'k':Button()})
```

Then say in my .kv file I have

```
<Label>:
    text: app.dict['k'].text
```

then the labels text doesn't get updated when the buttons text is updated.

If this is not a bug, I'm hoping it can be implemented for it to update when the button's text changes.

**Comment by ecerulm** [comment]
Nowadays, this will work also

text: (app.dict).get('k').text 

note: the parentheses around the property. This syntax allows for "unconventional" keys like `.@id` which won't work with the dot notation. (e.g `(app.dict).get('.@id')` works while  `app.dict..@id` won't work)

**Comment by aleferna12** [comment]
> Nowadays, this will work also
> 
> text: (app.dict).get('k').text
> 
> note: the parentheses around the property. This syntax allows for "unconventional" keys like `.@id` which won't work with the dot notation. (e.g `(app.dict).get('.@id')` works while `app.dict..@id` won't work)

Is this syntax documented anywhere? I would like to understand better how the bindables are created from KV files
