### ISSUE TITLE
Make documentation available by version (pdf/html)

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#1197]
Currently, the doc, html and pdf versions, refer to the latest master, while this is most of the time convenient, for various reasons, we should make at least the last stable version available, and possibly older versions too.

Now, what version should be the default one, and if it's the stable, should we push the doc fixes to the older versions (and regenerate it) when the doc appear to be wrong?

**Comment by KeyWeeUsr** [comment]
What about making https://stable.kivy.org/docs just for copy of stable parts from the latest commit of stable version? You could basically go for the same approach that is used now for docs building, but changing git source to the release package and make another subdomain(if it's not money-eater).

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/4566, after the next release both stable and master will be available on RTD.
