### ISSUE TITLE
Fake fullscreen in second monitor

### ISSUE THREAD

**Issue by lonniept** [kivy/kivy#1201]
Hi!

I'm having a problem with kivy when I try to fake fullscreen to show the app in a second monitor, instead of the main one (my laptop).

I tried to set the config attributes inside the app, like so:
```
from kivy.config import Config
Config.set('graphics', 'width', 1280)
Config.set('graphics', 'height', 720)
Config.set('graphics', 'fullscreen', 'fake')
Config.set('graphics', 'position', 'custom')
Config.set('graphics', 'top', '0')
Config.set('graphics', 'left', '1280')
from kivy.app import App
from kivy.core.window import Window
from kivy.uix.button import Button
#from kivy.base import EventLoop
#EventLoop.ensure_window()


class TestApp(App):
    def build(self):
        print Config.get('graphics', 'width')
        print Config.get('graphics', 'left')
        #Window.size = (1280,720)
        #print Window.size
        return Button(text='Hello World')

if __name__ == '__main__':
    TestApp().run()
```
but my app crashes and it gives me this error:

Fatal Python error: (pygame parachute) Segmentation Fault
Abort trap: 6

and then, when the app shuts down, it appears an error about the plugin libSDL-1.2.0.dylib on a pop-up window. I've been reading about the segmentation fault and I already tried the options given on the faq, but no luck.

I went also to the irc channel and got a great help there and got to run gdb. The full gdb log is here: http://pastebin.com/EJMsSu6g

Really really need to make this work... Thanks!

**Comment by akshayaurora** [comment]
This bug is not present with SDL2
