### ISSUE TITLE
Additional precompiled modules for kivy launcher

### ISSUE THREAD

**Issue by yurkomik** [kivy/kivy#1227]
My app need to use termios and pyserial so I need to rebuild apk every time I have any changes in my app code. I hope it's possible to ship luncher with this modules or make it possible to install them later. I think it can be done in few ways:
1)Creating tutorial how to build and copy to android luncher modules we need
2)Creating apk installer for aditional modules
3)Creating luncher apk with all possible modules (extended version)
4)Making it possible to download edditional modules from settings of kivy luncher app
5) Catching module import errors and proposing to user downloading them

It's possible to choose few ways of solving problem. Thanks for any help.
##

**Comment by KeyWeeUsr** [comment]
ref #3617 - there are the instructions. Maybe if there were bootstrap for launcher only, the instructions pr and this could be both closed. However, this can be closed anyway.

**Comment by KeyWeeUsr** [comment]
Re 2,3,4 - this would be totally inefficient for the way how android packages work now. It might be useful for the launcher itself, but then there would be more stuff to debug and kivy launcher shouldn't be used as pip for android. A custom launcher is quiteq good option for another packages not supported by the default(and debugged) launcher.

Re 5 - there is logcat which shows the output from python i.e. even module errors.

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
