### ISSUE TITLE
Some keycodes not implemented on Android

### ISSUE THREAD

**Issue by alekseismyshliaev** [kivy/kivy#1251]
Possibly connected with #1250.
On Android some keycodes aren't registered (events doesn't show up on requested keyboard), for example numpad ciphers, home, insert, pageup, pagedown, control, function keys.
This issue appears when using external USB keyboard.
On PC version all keys run fine (Ubuntu 12.04).
##

**Comment by inclement** [comment]
Pretty sure this is working now, thanks to @JonasT's confirmation of keyboard events being picked up by sdl2 correctly with an external keyboard.
