### ISSUE TITLE
Kivy for iOS freezes phone after prolonged use

### ISSUE THREAD

**Issue by kalyan02** [kivy/kivy#1261]
Steps to reproduce
1. Open kivy app and play around
2. Leave the app open until phone goes to sleep
3. Wake the phone up and notice the frozen phone - i.e home button, power button - become non responsive. But the app still works.
4. Had to hard reboot the phone to get; few of times pressing power button 5-10 times took me back to home screen.

**Comment by akshayaurora** [comment]
We have updated the toolchain, please reopen if the issue still exists.
