### ISSUE TITLE
touch event handler gets called twice when it shouldn't

### ISSUE THREAD

**Issue by dAnjou** [kivy/kivy#1282]
Steps to reproduce:
1. Clone this gist: https://gist.github.com/dAnjou/4ff50bf9f6813a3b7e52
2. Execute `python main.py`.
3. Touch or click the logo.

Happened using 1.7.0+build0~stable-cython+201305131851~pkg38~raring1 on Ubuntu 13.04 amd64.

**Comment by crishoj** [comment]
I'm getting a double touch up event with Kivy 1.9.1 on a Mac.

To reproduce, use this `.py` file: 

```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout


class Controls(BoxLayout):

    pass


class Touch(App):

    def build(self):
        return Controls()


if __name__ == '__main__':
    Touch().run()
```

And this `.kv` file:

```kivy
#:kivy 1.9.1

<Controls>

    Button:
        text: 'Touch here'
        on_touch_up: print "on_touch_up"
```

Log:

```
[INFO              ] [Logger      ] Record log in /Users/christian/.kivy/logs/kivy_16-04-09_62.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] OpenGL version <2.1 INTEL-10.14.58>
[INFO              ] [GL          ] OpenGL vendor <Intel Inc.>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) Iris(TM) Graphics 6100>
[INFO              ] [GL          ] OpenGL parsed version: 2, 1
[INFO              ] [GL          ] Shading version <1.20>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available
on_touch_up
on_touch_up
[INFO              ] [Base        ] Leaving application in progress...
```

**Comment by dessant** [comment]
@crishoj, Button receives on_touch_up twice, the second one is for grabbing the button, print out the dispatched touch object to see the difference, `on_touch_up: print(args)`.

If you don't want to deal with filtering the events, use `on_release`.

**Comment by crishoj** [comment]
One `on_touch_up` event is dispatched from `post_dispatch_input`:
https://github.com/kivy/kivy/blob/856b305c0c876e53e802f1ac9ae16c21fa91ac1e/kivy/base.py#L281

And the extraneous event is dispatched from `on_touch_up` in `Widget`:
https://github.com/kivy/kivy/blob/856b305c0c876e53e802f1ac9ae16c21fa91ac1e/kivy/uix/widget.py#L454

Diff of backtraces:
https://gist.github.com/crishoj/8be5f83faf1113b1dacb92c43b18b5ec/revisions

**Comment by crishoj** [comment]
@dessant I see. Thanks for the explanation. `on_release` was new to me!

**Comment by libbil** [comment]
Thanks for explaining this crishoj. This still occurs in 1.9.2dev. I don't see why it is desirable behaviour to fire on_touch_up twice. Anyone agree?

**Comment by AndreMiras** [comment]
Not sure if this is related, but I also had a similar issue (depending on the laptop).
And I could resolve by updating the `[input]` section of `~/.kivy/config.ini`, see https://github.com/AndreMiras/PyWallet/issues/7#issuecomment-307920496
