### ISSUE TITLE
usability: Button on_release on top of

### ISSUE THREAD

**Issue by KristerV** [kivy/kivy#1308]
This usability issue has been bugging me since the beginning:

**Issue:**
The on_release of a button should not go off, if the touch is no longer on the button.

**Example:**
User presses a button, then realizes (s)he pressed the wrong button so (s)he slides the finger away from the button, hoping it wont go off upon release. We've all done it with mouse on PC (and we're all used to it there. On touch screens it's not as common).

**Comment by beville** [comment]
Came looking for this topic, as a relative newbie.

As I've been developing with kivy, something seemed off, and I just couldn't figure it out for a while.  Eventually I realized that this "on_release" firing when the "touch up" event occurs outside the widget was it.  Every other GUI system I know doesn't fire the event if the "up" is outside the widget.  This includes Windows, OS X, Ubuntu, iOS, and (at least the current) Android.

It feels very inconsistent to have the kivy app have a inconsistant behavior to the native widgets.

For my app, I created a subclass of the ButtonBehavior class with a modified version of "on_touch_up()" that only fires the "on_release" event if the event is in the bounding box of the button.  Then I inherited all my custom button widgets from that.  Unfortunately, this doesn't cover all the convenience classes like Popup and Settings dialogs, etc.  

I wonder if the solution would be to have a kivy library level preference to have this as an optional behavior?
