### ISSUE TITLE
please provide a "box" for rapid access to the tools (vagrant / virtualbox)

### ISSUE THREAD

**Issue by dnozay** [kivy/kivy#1371]
Having a "box" will allow people to start a VM ready to go for development. This should make it easy for people to follow very similar installation instructions; but the major gain is that the end configuration (the VM) will be the same for users. This should reduce the number of platform-specific bugs opened.

Here are some docs: http://docs.vagrantup.com/v2/boxes.html
Vagrant + virtual box is what Travis-CI uses to test github pull requests :)

---

if I get some free time, I will try to contribute those instructions. 
##

**Comment by dessant** [comment]
We now have a packer script for buildozer, that could be extended https://github.com/kivy/buildozer/tree/master/buildozer/tools/packer.

**Comment by dessant** [comment]
Related issue https://github.com/kivy/buildozer/issues/154.

**Comment by Kovak** [comment]
I really enjoy working with vagrant when doing server work. While the whole 3d thing makes it a bit less of a total solution, but it could be very useful for people who want to setup a box for buildozer

**Comment by dessant** [comment]
Kivy installation itself should ideally happen with a command, though it makes sense to have a box for a build env with the needed tools, let's track this at https://github.com/kivy/buildozer/issues/154.
