### ISSUE TITLE
Implementing weak binding/unbinding system like ``lang._handlers`` directly to kivy properties

### ISSUE THREAD

**Issue by eulerreich** [kivy/kivy#1407]
There are still memory leak problems inherent with kivy properties.

For example, in

``` python
from inspect import ismodule
from kivy.app import App
from kivy.lang import Builder
from kivy.properties import StringProperty, ObjectProperty
from kivy.uix.button import Button
from kivy.uix.popup import Popup
from kivy.uix.widget import Widget
from objgraph import find_backref_chain, by_type, show_chain
from pprint import PrettyPrinter
import gc
pp = PrettyPrinter().pprint
Builder.load_string('''
<XPop>:
    title: 'goodbye'
    ScrollView:
        Button:
            size_hint: None, None
            size: 100, 1000
            text: 'hello world'
''')
class XPop(Popup):
    xxx = ObjectProperty(None)
    def set_title(self, instance, arg):
        self.title = arg
    def on_xxx(self, *args):
        self.xxx.bind(s=self.set_title)
#         self.xxx.bind(s=self.setter('title'))
#     def on_dismiss(self, *args):
#         self.xxx.unbind(s=self.set_title)
# #         self.xxx.unbind(s=self.setter('title'))
class X(Widget):
    s = StringProperty('hello world')
    @property
    def popup(self):
        pp([(i, 
#             show_chain(find_backref_chain(p, ismodule), filename='chain.png'),
            p
             ) for i, p in enumerate(by_type('XPop'))])
        gc.collect()
        return XPop(xxx=self)

class XApp(App):
    def build(self):
        xx = X()
        b = Button(text='pop')
        b.bind(on_release=lambda *args: xx.popup.open())
        return b

if __name__ == '__main__':
    XApp().run()

```

The `bind` clause in  `on_xxx` essentially keeps the `XPop`s alive through the `__self__` of `set_title`. Of course, in this case, the easy way out is just to uncomment `on_dismiss` to unbind the method.

But if we use the officially recommended way of setting title, with `setter('title')`, then we actually can't unbind it because the `setter` method returns a new setter on every call. We can probably easily fix this in `EventDispatcher` by caching setters.

However, in a more complex program, it can be difficult to remember to unbind methods/functions. I feel like implementing something like `lang._handlers`, that uses weakrefs and automatically unbinds, directly on kivy properties is a much better solution. The reservation I have though is about the feasibility of such a change. First of all I'm not familiar with Cython, so I'm not sure about any performance impact. Secondly, are there anything that could break under such a change?

If there're no major potential issues, I can write a patch for this.
##

**Comment by Julian-O** [comment]
Closing as stale.

If you are still having the problem, please create another issue with more details about the problem.
