### ISSUE TITLE
Problems installing Kivy on Raspberry Pi using PPA (Debian?)

### ISSUE THREAD

**Issue by Wessix** [kivy/kivy#1417]
Today i tried to install kivy on my raspberry pi following this site: http://kivy.org/docs/installation/installation-linux.html#ubuntu-11-10-or-newer"

after adding the ppa to my sources i tried to add the keys and got an gpg error, so sudo apt-get update produces an error.

after that i tried it with installing software bundles/tarballs . 

when try running this commands: 
sudo apt-get install python-setuptools python-pygame python-opengl   python-gst0.10 python-enchant gstreamer0.10-plugins-good python-dev   build-essential libgl1-mesa-dev libgles2-mesa-dev cython

i got dependencies errors. 
so i had to downgrade libwayland as mentioned here:

http://wonderfulcode.tumblr.com/post/54102854344/kivy-on-raspberry-pi

so perhaps something needs to be updated with the debian installer packets.

greets

**Comment by RussNelson** [comment]
gpg --recv-keys 0C667A3E
This key cannot be found on the current version of Raspbian. I get this error message:
pi@raspberrypi:~$ gpg --recv-keys 0C667A3E                                                                                   
gpg: directory `/home/pi/.gnupg' created                                                                                     
gpg: new configuration file `/home/pi/.gnupg/gpg.conf' created                                                               
gpg: WARNING: options in `/home/pi/.gnupg/gpg.conf' are not yet active during this run                                       
gpg: keyring `/home/pi/.gnupg/secring.gpg' created                                                                           
gpg: keyring `/home/pi/.gnupg/pubring.gpg' created                                                                           
gpg: no keyserver known (use option --keyserver)                                                                             
gpg: keyserver receive failed: bad URI                                                                                       
pi@raspberrypi:~$ 


Looks to me like gpg isn't set up properly on Raspbian. Attempting the same command as root doesn't work any differently except for the home directory.

**Comment by thopiekar** [comment]
The PPA should only work with RPi2. Otherwise you'll need to rebuild the
binaries.


Btw. you'll need to add the key by: ```sudo apt-key adv --keyserver
keyserver.ubuntu.com --recv-keys <key>```

**Comment by RussNelson** [comment]
This seems to fix the key problem. At least, it works for me. Now how do we get the documentation fixed?
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0C667A3E
