### ISSUE TITLE
How to set the default font?

### ISSUE THREAD

**Issue by logbird** [kivy/kivy#1440]
How to set the default font?
Each time you create a Label setting is very troublesome.
I preview kivy code, found in many parts of the fonts are fixed.
Can you put the default font in the config.ini file to set.

Thank You!

**Comment by senchoi** [comment]
Font doesn’t apply when the widgets are different. Does anyone know how to change the default font for any text appears on kivy app?

**Comment by Thimphu123** [comment]
You can import `from kivy.core.text import LabelBase, DEFAULT_FONT`
and add this command `LabelBase.register(DEFAULT_FONT, "path/to/font.ttf")`

**Comment by Paalal** [comment]
You can change the default font in the <HOME_DIRECTORY>/.kivy/config.ini file. In this file you can find a setting called "default_font".

Put the fonts you want to use in the <HOME_DIRECTORY>/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11/LocalCache/local-packages/Python311/site-packages/kivy/data/fonts folder.

**Comment by AlkisPis** [comment]
> You can import `from kivy.core.text import LabelBase, DEFAULT_FONT` and add this command `LabelBase.register(DEFAULT_FONT, "path/to/font.ttf")`

For me this didn't change anything. The default font seems to be always Roboto, which unfortunately cannot handle Arabic and Hebrew languages, which are used --surprisingly so-- in https://github.com/kivy/kivy/blob/master/examples/text/pango_demo.py.

**Comment by AlkisPis** [comment]
> You can change the default font in the <HOME_DIRECTORY>/.kivy/config.ini file. In this file you can find a setting called "default_font".
> 
> Put the fonts you want to use in the <HOME_DIRECTORY>/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11/LocalCache/local-packages/Python311/site-packages/kivy/data/fonts folder.

This seems to be the only way. I tested it with Arabic and Hebrew text, setting **Arial.ttf** as default font (Windows).  
Yet, the font I used does not handle Chinese and Tibetan. I really wonder then what is the meaning of using a text demo (https://github.com/kivy/kivy/blob/master/examples/text/pango_demo.py) when the default Kivy font cannot handle those languages ...
(**DejaVuSans.ttf**, included in 'data/(https://github.com/kivy/kivy/blob/master/kivy/data/fonts can also handle Arabic and Hebrew, but not the other languages.)

**Comment by ElliotGarbus** [comment]
@AlkisPis 
You can changed the default font using the Config object, https://kivy.org/doc/stable/api-kivy.config.html#available-configuration-tokens

Here is an example:
```python
from kivy.config import Config
# Correct path list: [Name, Regular, Italic, Bold, Bold-Italic]
Config.set('kivy', 'default_font', [
    'Courier',
    'C:/Windows/Fonts/cour.ttf',       # Regular
    'C:/Windows/Fonts/couri.ttf',      # Italic
    'C:/Windows/Fonts/courbd.ttf',     # Bold
    'C:/Windows/Fonts/courbi.ttf'      # Bold-Italic
])

from kivy.app import App
from kivy.lang import Builder

kv = """
Label:
    text: 'This is the default font'
"""

class MyApp(App):
    def build(self):
        return Builder.load_string(kv)

MyApp().run()
```
You can register a font using: https://kivy.org/doc/stable/api-kivy.core.text.html#kivy.core.text.LabelBase.register
but this does not select the font, it registers the font name so you can use it when specifying the font_name attribute.

As an alternative you can redefine the font_name attribute in Label using kv to change the font_name.
```python
from kivy.app import App
from kivy.lang import Builder

kv = """
<Label>:
    -font_name: 'arial'  # needs to be a registered font name
    
Label:
    text: 'This is now the default font'
"""

class SetFontApp(App):
    def build(self):
        return Builder.load_string(kv)

SetFontApp().run()
```
This is a support question, In the future please use on of the support forums.

**Comment by AlkisPis** [comment]
> [@AlkisPis](https://github.com/AlkisPis) You can changed the default font using the Config object, https://kivy.org/doc/stable/api-kivy.config.html#available-configuration-tokens
> 
> Here is an example:
> 
> from kivy.config import Config
> # Correct path list: [Name, Regular, Italic, Bold, Bold-Italic]
> Config.set('kivy', 'default_font', [
>     'Courier',
>     'C:/Windows/Fonts/cour.ttf',       # Regular
>     'C:/Windows/Fonts/couri.ttf',      # Italic
>     'C:/Windows/Fonts/courbd.ttf',     # Bold
>     'C:/Windows/Fonts/courbi.ttf'      # Bold-Italic
> ])
...

Thanks. Yes, I have already found and used this method. It works fine with Arabic and Hebrew that I use in my tests. 
(I have also found a way to handle the Chinese text, using **'simsun.ttc'** ... Yes, TTC!  Only that I have lost a lot of time, made a lot of effort and had a lot of frustration in the process! All of which could have been avoided if there were some information in the sript about how to handle all that ...)
