### ISSUE TITLE
Feature request: add optional scroll to the TextInput widget [$34]

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#1449]
The TextInput widget needs a scrollbar / scroll capability on x, y axis when the text overflows in it.

If one attaches TextInput to ScrollView like this, the TextInput object will be scrolled, moved around, not the actual text in the widget:

<pre><code>ScrollView:
    id: scrlv
    TextInput:
        text: disp_text
        size_hint: 1, None
        height: max( (len(self._lines)+1) * self.line_height, scrlv.height)</code></pre>

##

**Comment by ndapost** [comment]
Root:    
    ScrollView:
        id: scrlv
        bar_width: 10
        scroll_type: ['bars', 'content']
        size_hint: 0.2, 0.2
        bar_inactive_color: self.bar_color        
        TextInput:
            id: ti
            font_size: 23
            size_hint: 1, None
            height: max(self.minimum_height, scrlv.height)
            on_cursor_row: root.calc_cursor(ti, scrlv)

	def calc_cursor(self, ti, scrlv):
		d = 0
		y_cursor = ti.cursor_pos[1]
		y_bar = scrlv.scroll_y * (ti.height - scrlv.height)
		if y_cursor >= (scrlv.height + y_bar):
			d = y_cursor - (scrlv.height + y_bar) + ti.padding[1]
		if y_cursor <= y_bar + ti.line_height:
			d = y_cursor - y_bar - ti.line_height - ti.padding[3]
		scrlv.scroll_y = scrlv.scroll_y + (scrlv.convert_distance_to_scroll(0, d))[1];

**Comment by ndapost** [comment]
py:

      class Root(BoxLayout):
           def change_scroll_y(self, ti, scrlv):
                 y_cursor = ti.cursor_pos[1]
                 y_bar = scrlv.scroll_y * (ti.height-scrlv.height)
                 if ti.height > scrlv.height:
                        if y_cursor >= y_bar + scrlv.height:
                                dy = y_cursor - (y_bar + scrlv.height)
                                scrlv.scroll_y = scrlv.scroll_y + scrlv.convert_distance_to_scroll(0, dy)[1] 
                        if y_cursor - ti.line_height <= y_bar:
                                dy = (y_cursor - ti.line_height) - y_bar
                                scrlv.scroll_y = scrlv.scroll_y + scrlv.convert_distance_to_scroll(0, dy)[1] 


kv:

    Root:    
        ScrollView:
            id: scrlv
            bar_width: 10
            scroll_type: ['bars', 'content']
            size_hint: 0.2, 0.2
            bar_inactive_color: self.bar_color        
        TextInput:
            id: ti
            font_size: 23
            size_hint: 1, None
            height: max(self.minimum_height, scrlv.height)
            on_cursor_row: root.change_scroll_y(ti, scrlv)

**Comment by dessant** [comment]
ref https://github.com/kivy/kivy/issues/3582

**Comment by brentpicasso** [comment]
+1 right now on a mobile device, it is impossible to scroll a textview with just the touch interface.

**Comment by misl6** [comment]
The issue have been fixed by @DexerBR via #7610
