### ISSUE TITLE
center_x bug when setting position in Python

### ISSUE THREAD

**Issue by winstonwolff** [kivy/kivy#1469]
I'm trying to layout a widget like this:

```
    ----------------------------
    |          [IMAGE]         |
    |[.....a label here.......]|
    ----------------------------
```

Where the image is centered at the top, and the label is centered at the bottom. A sample program is at this gist:

```
https://gist.github.com/winstonwolff/6356247
```

Here is a screenshot of the output. Notice that the image is positioned in a different place depending on if I create the Marker widget in the KV file or in Python. In the KV file, the image correctly appears at the center top of the Marker. If setting position by Python, the image is not positioned correctly. I think it has something to do with the reevaluation of Image.top and Image.center_x. When initialized by python, it's evaluating center_x using a size of 100,100, and not reevaluating center_x when the Image.size changes to the texture_size.

By the way, tshirtman took a look at this on IRC.

![kivy_center_bug](https://f.cloud.github.com/assets/281580/1038699/aa4466c4-0f6a-11e3-9728-0c7f7b176507.png)
##

**Comment by hey-sancho** [comment]
Hello,

I took a look at this issue, and got some interesting information. It seems like the position of the image depends on how it's specified in the KV file.
I've tried to change the order of lines in Image widget with all possible variants: **position** (`center_x` and `top`), **`size`** and **`source`**.

- Two combinations `size and source before position` (the order between size and source is irrelevant), place the image correctly.
- One combination is in the original post - `size, then position, then source` places the image above the widget.
- Three other combinations `position before size` place the image in the lower left corner of the widget.

You can see them all here:
![kivycenterbug](https://cloud.githubusercontent.com/assets/1079585/6021067/5a2a1122-abbb-11e4-99b2-bdd701a1ae1b.png)

Here's the [gist](https://gist.github.com/hey-sancho/74eed4a0bf2648c33ae4) with code.

**Comment by dessant** [comment]
@hey-sancho when testing master, were you using pygame or sdl2?

**Comment by hey-sancho** [comment]
@dessant, I've tried both. However, SDL2 doesn't load the image - [log](https://gist.github.com/hey-sancho/74eed4a0bf2648c33ae4#file-sdl2_log-txt). It just draws the crossed box with widget name in the same wrong place.

**Comment by tshirtman** [comment]
I don't know how i didn't see that back then, but for me it's completely normal, the "center" settings doesn't bind on self.size, because it has no way to know it should, if you need that, you should always specify something like:

center: self.size and root.center

so when self.size changes, the rule is evaluated again.

Yes, it would be great if kvlang or the property system could do such thing, but there is currently no support for such logic afaik.

considering the lifetime of the bug while market as important, i'm closing this as wontfix.
