### ISSUE TITLE
3dRendering example not displaying properly in Ubuntu

### ISSUE THREAD

**Issue by thehans** [kivy/kivy#1503]
Using kivy 1.7.2 from Ubuntu stable PPA on Ubuntu 13.04 64 bit

Steps to reproduce:
cd /usr/share/kivy-examples/3Drendering/
python main.py

Actual Results:
A blank screen.  Right clicking creates red dots, and a strange white sliver scans back and forth on the screen.

http://i.imgur.com/GJrIFAT.png

Expected results:
I think its supposed to draw a 3d monkey?

Console Output:
 ```
    [INFO   ] Kivy v1.7.2
    [INFO   ] [Logger      ] Record log in /home/peeps/.kivy/logs/kivy_13-09-14_5.txt
    [INFO   ] [Factory     ] 144 symbols loaded
    [DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
    [DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
    [DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
    [INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif
    [DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
    [DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
    [DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
    [INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
    [DEBUG  ] [Window      ] Display driver x11
    [DEBUG  ] [Window      ] Actual window size: 800x600
    [DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a0
    [DEBUG  ] [Window      ] Actual depth bits: 24
    [DEBUG  ] [Window      ] Actual stencil bits: 8
    [DEBUG  ] [Window      ] Actual multisampling samples: 2
    [INFO   ] [GL          ] OpenGL version <3.3.0 NVIDIA 304.88>
    [INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
    [INFO   ] [GL          ] OpenGL renderer <Quadro FX 880M/PCIe/SSE2>
    [INFO   ] [GL          ] OpenGL parsed version: 3, 3
    [INFO   ] [GL          ] Shading version <3.30 NVIDIA via Cg compiler>
    [INFO   ] [GL          ] Texture max size <8192>
    [INFO   ] [GL          ] Texture max units <32>
    [DEBUG  ] [Shader      ] Fragment compiled successfully
    [DEBUG  ] [Shader      ] Vertex compiled successfully
    [DEBUG  ] [ImagePygame ] Load </usr/lib/python2.7/dist-packages/kivy/data/glsl/default.png>
    [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
    [DEBUG  ] [App         ] Loading kv <./renderer.kv>
    [DEBUG  ] [App         ] kv <./renderer.kv> not found
    [INFO   ] [OSC         ] using <multiprocessing> for socket
    [DEBUG  ] [Base        ] Create provider from mouse
    [DEBUG  ] [Base        ] Create provider from probesysfs
    [DEBUG  ] [ProbeSysfs  ] using probsysfs!
    [DEBUG  ] [ProbeSysfs  ] found device: SynPS/2 Synaptics TouchPad at /dev/input/event15
    [INFO   ] [ProbeSysfs  ] device match: /dev/input/event15
    [INFO   ] [MTD         ] Read event from </dev/input/event15>
    [INFO   ] [Base        ] Start application main loop
     Exception in thread Thread-1:
     Traceback (most recent call last):
       File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
         self.run()
       File "/usr/lib/python2.7/threading.py", line 763, in run
         self.__target(*self.__args, **self.__kwargs)
       File "/usr/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 192, in _thread_run
         _device = Device(_fn)
       File "/usr/lib/python2.7/dist-packages/kivy/lib/mtdev.py", line 131, in __init__
         self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
     OSError: [Errno 13] Permission denied: '/dev/input/event15'
```

**Comment by hey-sancho** [comment]
Hello,

I've tried the 3dRendering example bundled with development version:
 `Kivy v1.9.0-dev on Ubuntu 14.10, Python v2.7.8`,
and the one provided by the kivy PPA: 
`kivy-examples_1.8.0+stable0+201501241346~dailypkg43~ubuntu14.10.1`

The development version works fine, the monkey is visible and red dots can be placed.
The PPA version gives the same results as in the top post by @thehans.
After folder comparison, I've found out that the ppa bundle lacks the `simple.glsl` file, which is present in development version.

However, I didn't encounter the exception mentioned in the top post, and the only difference in log file between working and non-working example are these three lines about loading the missing file:
```
...
[DEBUG             ] [App         ] Loading kv <./renderer.kv>
[DEBUG             ] [App         ] kv <./renderer.kv> not found
**
[INFO              ] [Shader      ] Read <simple.glsl>
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [Shader      ] Fragment compiled successfully
**
[DEBUG             ] [Base        ] Create provider from mouse
...
```
Brief inspection of the other kivy-examples packages in PPA has shown that the `simple.glsl` is also missing. However it is present in [1.8.0 version](https://github.com/kivy/kivy/tree/1.8.0/examples/3Drendering). Looks like it's a packaging error.

**Comment by dereks** [comment]
Confirmed, the PPA package is missing the file "simple.glsl".  A workaround is to manually copy it into place:

```bash
sudo bash
cd /usr/share/kivy-examples/3Drendering
wget https://raw.githubusercontent.com/kivy/kivy/master/examples/3Drendering/simple.glsl
python ./main.py
```

This will put an uncontrolled file on the file system, which is bad sysadmin practice.  Either delete it when done playing, or move it under $HOME and edit a copy of the example to find it there.

Note, the 1.9.0 package is also missing the file "softboy.mpg", but that is documented in a couple of other bug reports.

The event permissions thing is highly annoying but probably a separate bug.

**Comment by dessant** [comment]
@thopiekar, I vaguely remember this being discussed somewhere by you and others, which was that thread?

**Comment by thopiekar** [comment]
Don't know. I checked our example package and the  missing glsl file is now there. I think it can be closed, but haven't read the full discussion in this issue report.

**Comment by dessant** [comment]
Yes, the missing glsl filet was the main problem highlighted in this issue.
@dereks, if you can still reproduce it with the latest packages, please reopen.
