### ISSUE TITLE
Repeating textures are not displayed on Android 4 with Tegra 2

### ISSUE THREAD

**Issue by tohin** [kivy/kivy#1524]
I have found that repeating textures are not displayed on my ZTE V970 with NVIDIA Tegra 2.

Tested with kivy 1.6.0 and 1.7.2
Logs and main.py: https://gist.github.com/tohin/6712066

But the apk works well on:
Huawei Ascend G300 (U8815) with Android 2.3:
Chipset: Qualcomm MSM7227A Snapdragon
CPU: 1 GHz Cortex-A5
GPU: Adreno 200

ZTE V970 specs:
Chipset: Nvidia Tegra 2
CPU: 1 GHz dual-core Cortex-A9
GPU: ULP GeForce

**Comment by akshayaurora** [comment]
Reopen if you still have the same issue with latest kivy master.
