### ISSUE TITLE
Attribute Error: 'module' object has no attribute 'require'

### ISSUE THREAD

**Issue by dequegorg** [kivy/kivy#154]
Hi there,

I believe I installed Kivy properly (I followed documentation instructions and installed development kit) on Ubuntu 11.04.

Running the first 'Hello World' example of the programming guide returned an exception:

Traceback (most recent call last):
  File "./kivy.py", line 26, in <module>
    import kivy
  File "/home/benjamin/Desktop/kivy.py", line 27, in <module>
    kivy.require('1.0.0')
AttributeError: 'module' object has no attribute 'require'

Do you have any tips?
Thanks,
Benjamin

**Comment by vmisiko** [comment]
i also have the same problem, when i ran kivy the command prompt sa

```
Traceback (most recent call last):
    File "C:\Users\V-TECH\Desktop\new 1.py", line 1, in <module>
    from kivy.app import App
    File "C:\Users\V-TECH\Desktop\kivy.py", line 2, in <module>
    kivy.require('1.10.0')
    AttributeError: module 'kivy' has no attribute 'require'
```
i don't know what is the problem, i have tried almost all the answers above but not a single of them has worked for me yet, i have even checked my kivy if it has all the requirements and its fine.It says

```
>>>>C:\Users\V-TECH>python -m pip check kivy
No broken requirements found.
```
so i don't get why cant it just find this attribute require, grateful for any further help

**Comment by Mybigjay** [comment]
If you have anaconda on Your system, do the followings
1. Check conda location by opening the command prompt,  type   conda info --envs, mine is bibs  C:\ProgramData\Anaconda3\envs\bibs>
2.  On your desktop search for the file, in my own case i searched for bibs
3.Inside the file, create a file name it  venv
4 Copy the location of the venv folder, mine is 
C:\Users\Blessing\PycharmProjects\pythonProject\bibs\venv
5. Open cmd, type cd \Users\Blessing\PycharmProjects\pythonProject\bibs\venv
6.Install the followings, one after the other;
 pip install virtualenv
python -m pip install --upgrade pip wheel setuptools
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2  
.deps.glew
python -m pip install kivy.deps.gstreamer
python -m pip install kivy.deps.angle
python -m pip install kivy
python -m pip install kivy_examples
python -m pip install Pillow
python -m pip install cython
7. Right click the file named venv, open it with pycharm,  Inside venv, create a new python project
8.on pycharm go to file, settings, python interpreter click the + sign, 
type the following packages and install them one after the other;
kivy
kivy.deps.angle
kivy.deps.gstreamer
Pillow
cython
