### ISSUE TITLE
Comment inside kv language before intendent does not work.

### ISSUE THREAD

**Issue by rainbowdesign** [kivy/kivy#1541]
If i do this it does work:

```
BoxLayout:                  
    ## Define it as 'BoxLayout' http://kivy.org/docs/api-kivy.uix.layout.html
    orientation: 'vertical'
```

If i do this it does not work:

```
BoxLayout:     ## Define it as 'BoxLayout' http://kivy.org/docs/api-kivy.uix.layout.html
    orientation: 'vertical'  
```

The reason is the intendent after the # comment without it it does work also.

**Comment by NicolasIceberg** [comment]
It is still not closed. If you tab multiple times after, for example, canvas.before, it will still give out an indentation error.
