### ISSUE TITLE
different ways of specifying the points of a line

### ISSUE THREAD

**Issue by mortbauer** [kivy/kivy#1548]
This is a feature request to support different ways to specify the points of a Line or Mesh. This would be needed in order to create high efficient plots for scientific usage, as the data is mostly in form of numpy arrays. Currently one needs to create a list of tuples from an x and y array which is not efficient at all, another problem I saw is the use of the ListProperty which seems to always create a copy of the assigned list. Another framework which handles this very nice is pyqtgraph, some relevant part of the code would be http://bazaar.launchpad.net/~luke-campagnola/pyqtgraph/main/view/head:/pyqtgraph/graphicsItems/PlotCurveItem.py the updateData method, where it just uses the view of the arry, no copying done.
I kivy seems much cleaner and pythonic in a way so I would be happy to work with it instead of Qt.

**Comment by dessant** [comment]
Issue title fixed in https://github.com/kivy/kivy/pull/3866.
