### ISSUE TITLE
arabic text input

### ISSUE THREAD

**Issue by nim4n** [kivy/kivy#1570]
how can I convert text in typing time? http://postimg.org/image/u40ftpwm9/  http://postimg.org/image/ibefw8b89/ as you can see when I type in kivy the word is out of shape so I used "arabic reshaper" to fix this problem. now I can use convert button to fix It but how should I fix this in typing time without pressing convert button?
##

**Comment by sajadbanooie** [comment]
for textinput it wont work

**Comment by sajadbanooie** [comment]
def _create_line_label(self, text, hint=False):
        reshaped_text = arabic_reshaper.reshape(text)
        text = get_display(reshaped_text)
adding it to TextInput will get:
 Traceback (most recent call last):
   File "/home/sajad/PycharmProjects/kimiastone/Persian.py", line 112, in <module>
     myApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 401, in mainloop
     self._mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 288, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 1512, in _refresh_line_options
     self._refresh_text_from_property()
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 1531, in _refresh_text_from_property
     self._refresh_text(self._get_text(encode=False), *largs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/textinput.py", line 1551, in _refresh_text
     _line_rects.append(Rectangle(size=lbl.size))
 AttributeError: 'NoneType' object has no attribute 'size'

**Comment by pylover** [comment]
I am currently working on kivy's rtl support. so i plan to start by implementing a reshaper in c(cython) . any suggestion ?

**Comment by sajadbanooie** [comment]
there is no reshaper in c but you can use cython and python arabic reshaper and bidi

**Comment by sajadbanooie** [comment]
i think there should be some changes in widget like algin property
im working on widget algin support

**Comment by sajadbanooie** [comment]
i think i have to replace windows x with 0

**Comment by pylover** [comment]
The Only difficulty is the multiline-text-entry, selection and markups. the LabelBase's classes (SDL, PyGame & Pil) are easy to do that.

**Comment by tshirtman** [comment]
hey @pylover did you get some result? would be nice to go forward on this :)

**Comment by pylover** [comment]
Interesting, but i don't have time.
I am planning a project with kivy in next month. i think it's good chance for me to do that.

**Comment by pylover** [comment]
I am starting right just now. I love kivy

**Comment by motad333** [comment]
hi
can i use arabic reshape and get_display in .kv file?


#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import get_display bidi.algorithm
#:import reshape arabic_reshaper

<Button_page_mabda@Button>:
	size_hint_y:None
	height:100
	color:get_color_from_hex('000000')
	background_normal:''
	background_color:get_color_from_hex('FFFFFF')
<page2>:
	ScrollView:
		size_hint:1,1
		GridLayout:
			cols:1
			spacing:5
			size_hint_y:None
			height: self.minimum_height
			Button_page_mabda:
				text:get_display(reshape(u'تهران'))
				on_press:root.pressed = 'tehran'
				on_press:root.shoro='THR'
				on_release:root.welcome()
i use this way but give me sum eror : 
 TypeError: 'module' object is not callable
thank for any help :)

**Comment by pylover** [comment]
try:

    #: import arabic_reshape kivy.core.text.globalization.arabic_reshape
    #: import arabic_bidi kivy.core.text.globalization.arabic_bidi

**Comment by motad333** [comment]
sory i can't speak english good so when i read this page about arabic font i think i can post this quest
sory about that and i wil remove both post 
but very thank about help :)

**Comment by engmms** [comment]
follow

**Comment by motad333** [comment]
hellow
thank for all of idea
but there is problem that not solved
and problem is : when i convert .py file to .apk file i find new problem that is encoding of textinput in android system is 'str' and type is hexdecimial but reshaper  get unicode utf-8 
now how i can convert it to unicode for reshaper??

**Comment by pylover** [comment]
@motad333 , I have no idea.the core developers of kivy may help you.

**Comment by RevengeComing** [comment]
Cursor has a bug on farsi/arabic text input and it wont work until SDL fix this problem.
The problem rises from kivy.core.label.LabelBase.get_extents(). it implemented in pygame, PIL, and SDL. i haven't test pygame or PIL LabelBase implementation of this function.

![kivy_input](https://user-images.githubusercontent.com/23046907/32988816-4992293c-cd21-11e7-9efd-ece5f5e5f4fc.gif)

My fork contains fix for farsi/arabic Label/Button, but user has to change font_name to a valid farsi/arabic font_name, since default font doesn't work for farsi. I can create a PR if you want.

**Comment by engmms** [comment]
@RevengeComing ..hi i want to use this solution in my App..can you tell me how

**Comment by RevengeComing** [comment]
@engmms , Yet it's not a valid solution but you can install my fork:
```pip install git+https://github.com/RevengeComing/kivy.git```
( you might need to install rtl, arabic_reshaper, python-bidi , install them with pip)

And you have to add a farsi/arabic font to your application and change all the font_name of your Labels/Buttons/TextInputs to your font since default font doesn't support farsi/arabic.

**Comment by RevengeComing** [comment]
I'm creating a python binding for harfbuzz library to use its glyph info inside kivy so we can advance cursor with details it gives to us. with mix of python-bidi and [pyharfbuzz](https://github.com/RevengeComing/pyharfbuzz) we can have multi language support for kivy.

**Comment by RevengeComing** [comment]
Hello again,

I created [kivy_i18n](https://github.com/RevengeComing/kivy-i18n) repository in order to solve this problem:

The result is:
![peek 2018-01-22 16-23](https://user-images.githubusercontent.com/23046907/35221824-de3253b8-ff90-11e7-9ab9-f8f7ebe76067.gif)

It requires [pyharfbuzz](https://github.com/RevengeComing/pyharfbuzz) and [python-fribidi](https://github.com/RevengeComing/python-fribidi) which only supports linux(py3, py2) and mac(py3) right now as well as harfbuzz, fribidi, freetype2.

TextInput has some problems like not being rtl and ... but I'll add these features to it.

**Comment by engmms** [comment]
ok @RevengeComing...thanks for your hard word ..

**Comment by engmms** [comment]
@RevengeComing ...I will test this solution

**Comment by tito** [comment]
An experimental support is now available in master using KIVY_TEXT=pango

**Comment by tshirtman** [comment]
Although, as far as i know this solution only works on Linux and OSX, more work is certainly needed for it to work on Windows and mobile platforms.

**Comment by P0oOOOo0YA** [comment]
@RevengeComing @tshirtman Hi buddy, What's up? Is this feature ready to be integrated into mobile and windows applications. I'm really concerned about Android right now rather than windows. One other silly workaround for Persian/Farsi speakers is to use Finglish.

**Comment by ali-aliraqi** [comment]
you can this simple solution for Arabic text input in kivy @
https://github.com/ali-aliraqi/Kivy-Arabic_Text_Input

**Comment by ARahmanKhallaf** [comment]
> 

did you find a solution to this problem?
