### ISSUE TITLE
Stencils are not rendered during transition between screens with FadeTransition

### ISSUE THREAD

**Issue by Gipzo** [kivy/kivy#1578]
It looks like stencils are not used when creating FBO's for shader-based transitions. 

Code to reproduce: https://gist.github.com/Gipzo/7102212

By the way, why screenmanager uses black color for clearing fbo. It looks like it works fine, when it just cleared with transparent color, like ClearColor(0, 0, 0, 0).
##

**Comment by dessant** [comment]
@tito, do you have time to look into this? It's mostly the only bug left outside packaging and doc ones for the release.

**Comment by tshirtman** [comment]
adding with_stencilbuffer=True in Fbo() call in @tohin 's example, seems to solve the issue, maybe we should add that to ShaderTransition's FBOs.
