### ISSUE TITLE
Label should automatically solve encoding problems

### ISSUE THREAD

**Issue by Depau** [kivy/kivy#1579]
It happens sometimes, expecially when showing a file list from a directory, that some file has some special, non-ascii character. Passing it to Kivy as is would make it crash. Converting it to unicode with unicode(string) would make it crash too.
The only way I found is this:

<pre>
from chardet import detect as chardetect
unicode(string, encoding=chardetect(string)["encoding"], errors="ignore")
</pre>

Finds the encoding of the text and converts it to unicode, ignoring errors.

It would be nice if kivy did it automatically, wouldn't it?
##

**Comment by matham** [comment]
Python 3 has largely fixed this issue.
