### ISSUE TITLE
project.properties file is not created

### ISSUE THREAD

**Issue by jmg** [kivy/kivy#1700]
When I run 

```bash
./distribute.sh -m "kivy"
```

As mentioned in http://kivy.org/docs/guide/packaging-android.html the file project.properties is not getting generated so I have to create it manually and specify the andriod sdk target inside it.

If I don't create the file I get an error like:
"project.properties doesn't exists"

Note: I'm using the latest kivy dev version to do this.

**Comment by inclement** [comment]
I think this was fixed some time ago in the  old toolchain, and isn't a problem in the new one, so closing this. Thanks for the report.
