### ISSUE TITLE
Dark Square when load GIF or .ZIP

### ISSUE THREAD

**Issue by chrLoaiza** [kivy/kivy#1730]
Sorry... 

When I load a zip (with image sequence) in my kivy project it shows like a Black Square... I loaded the same zip in other kivy project and it works... why can be the problem?

sorry for my english

thanks.
##

**Comment by misl6** [comment]
Closing as we can't reproduce the issue on `Kivy==2.2.0rc1`. Feel free to re-open if you're still encountering this issue on a newer Kivy version.
