### ISSUE TITLE
libjpeg decoding is unusually slow for images above 1.64 megapixels on Android phone

### ISSUE THREAD

**Issue by blhiggins** [kivy/kivy#1736]
See this for context: https://groups.google.com/forum/#!topic/kivy-dev/ByE0A0Ixb-w

The libjpeg decoder takes an unusually long time to decode JPEG files when the resolution is greater than about 1.64 megapixels. I tested on a HTC Desire Z with JPEG files of various dimensions around 1.6 megapixels: images below 1.64 loaded basically instantly, but images above 1.64 loaded after 8-15 seconds of delay. I compared this to PNG files with the same content, which had no such delay. Running the app on a Linux desktop had no such delay, either. Details and some profiling info are in the thread linked above.

Something in libjpeg triggers upon "large" images (1.64 megapixels isn't that large) and executes very poorly on the mobile platform. Using PNGs instead of JPEGs is not a solution in my case as JPEGs could be read from the user's photo gallery. A solution might be to invoke native JPEG loading code when running on Android.

Peace,
Brendon
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
