### ISSUE TITLE
Support GL_RED, GL_RG instead of GL_LUMINANCE_ALPHA

### ISSUE THREAD

**Issue by knappador** [kivy/kivy#1738]
I'm reading that GL_LUMINANCE_ALPHA is deprecated as RED and RG are more consistent API's for single and dual channel buffers.  Ran into this while trying to squeeze down texture fill rate on mobile.  RGB is as low as I can go even though GL_RED will work.  LUMINANCE_ALPHA and LUMINANCE just don't even work on a Galaxy Tab 2.  LUMINANCE_ALPHA very slow on Linux.
##

**Comment by Julian-O** [comment]
This doesn't appear to be possible to implement. Closing as Won't Fix (and Stale).

If this is in error, please let us know.
