### ISSUE TITLE
Avoid restoration of Kivy SDK application

### ISSUE THREAD

**Issue by tito** [kivy/kivy#1743]
When you close/restart your computer, the Kivy.app is restarted, and leaving a icon/window. We should avoid it, as the Kivy sdk doesn't do anything.

Documentation: https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26

Search "User interface preservation".

**Comment by akshayaurora** [comment]
@tito with the new .app we don't have the lingering icon, I think this can be closed.
