### ISSUE TITLE
reloading textures failed

### ISSUE THREAD

**Issue by niavlys** [kivy/kivy#1762]
Hi folks,
 I'm experiencing an issue, since a few days, with kivy-dev on macosx: textures aren't reloaded when they should be, while resizing window for instance.
##  How to reproduce:

launch any example that contains an image, like
examples/widgets/image_mipmap.py
, and resize kivy's window. screen is blanked, and the log on console outputs:

```
[DEBUG             ] [Window      ] Display driver Quartz
[DEBUG             ] [Window      ] Actual window size: 1051x768
[DEBUG             ] [Window      ] Actual color bits r8 g8 b8 a8
[DEBUG             ] [Window      ] Actual depth bits: 24
[DEBUG             ] [Window      ] Actual stencil bits: 8
[DEBUG             ] [Window      ] Actual multisampling samples: 4
[INFO              ] [Context     ] Reloading graphics data...
[DEBUG             ] [Context     ] Collect and flush all garbage
[DEBUG             ] [Context     ] Reload textures
 Exception Exception: Exception('Unknown <png|false|0> type, no loader found.',) in 'kivy.graphics.texture.Texture.reload' ignored
 Exception Exception: Exception('Unknown <png|false|0> type, no loader found.',) in 'kivy.graphics.texture.Texture.reload' ignored
 Exception Exception: Exception('Unknown <png|true|0> type, no loader found.',) in 'kivy.graphics.texture.Texture.reload' ignored
[DEBUG             ] [Context     ] Reload vbos
[DEBUG             ] [Context     ] Reload vertex batchs
[DEBUG             ] [Context     ] Reload shaders
[DEBUG             ] [Shader      ] Fragment compiled successfully
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [Context     ] Reload canvas
[INFO              ] [Context     ] Reloading done in 0.0228s
```

**Comment by Rusbens1** [comment]
Know it has been closed but also getting this issue, any ideas?

[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Context     ] Reloading graphics data...
 Exception AttributeError: "'NoneType' object has no attribute 'encode'" in 'kivy.graphics.texture.Texture.reload' ignored
 Exception AttributeError: "'NoneType' object has no attribute 'encode'" in 'kivy.graphics.texture.Texture.reload' ignored
[INFO   ] [Context     ] Reloading done in 0.0860s
