### ISSUE TITLE
Carousel does't change index

### ISSUE THREAD

**Issue by glebpushkov** [kivy/kivy#1763]
Hello. I faced with problem, when Carousel does't go to the next slide because index wasn't changed. I looked at on__offset method and found next:

``` python
if direction[0] == 'r':
    if _offset <= -width:
        index += 1
    if _offset >= width:
        index -= 1
```

in my case values was:
(Pdb) _offset
-85.93333333333334
(Pdb) -width
-728.7500000000001
##

**Comment by gottadiveintopython** [comment]
On my desktop, this issue happens only when `loop==True` and `len(slides) == 2`. For example a code like this:

```python
from kivy.factory import Factory
from kivy.app import runTouchApp

carousel = Factory.Carousel(direction='left', loop=True)
carousel.bind(
    index=lambda __, value: print('index:', value),
    current_slide=lambda __, value: print('current_slide:', value),
)
for i in range(2):
    l = Factory.Label(text=str(i), font_size=100)
    carousel.add_widget(l)

runTouchApp(carousel)
```

You can confirm:

1. Sometimes `index` and `current_slide` aren't updated even though the next slide is actually displayed.
1. The loop doesn't work. You can't swipe infinity.

And if you look at [carousel.py#L167-L171](https://github.com/kivy/kivy/blob/master/kivy/uix/carousel.py#L167-L171) and [carousel.py#L211-L215](https://github.com/kivy/kivy/blob/master/kivy/uix/carousel.py#L211-L215), you can confirm both are ignoring `loop` when `len(self.slides) == 2`.

If those 2 parts are removed, the issue doesn't occur. But another issue(the next slide is not visible until the switching is done) will be occur instead. So I think it's not easy to fix this issue.

### Versions

- Python 3.7.1
- Kivy v2.0.0.dev0, git-e828f22

**Comment by gottadiveintopython** [comment]
I kinda gave up fixing this issue, and just leave a code that might be helpful to test `Carousel`.

```python
from kivy.app import runTouchApp
from kivy.lang import Builder


KV_CODE = '''
<DebugCarousel@Carousel>:
    canvas.before:
        Clear:  # clear instructions inherited from StencilView
    canvas.after:
        Clear:  # clear instructions inherited from StencilView
        Color:
            rgba: 1, 1, 1, 1
        Line:  # draw border
            rectangle: self.x + 1, self.y + 1, self.width - 1, self.height - 1
            dash_offset: 5
            dash_length: 3

FloatLayout:
    DebugCarousel:
        id: carousel
        size_hint: .3, .3
        pos_hint: {'center': (.5, .5, ), }
        loop: True
        Button:
            text: '0'
            font_size: 150
        Button:
            text: '1'
            font_size: 150
'''

root = Builder.load_string(KV_CODE)
carousel = root.ids.carousel
carousel.bind(
    index=lambda __, value: print('index:', value),
    current_slide=lambda __, value: print('current_slide:', value),
)

runTouchApp(root)
```

**Comment by matham** [comment]
Fixed in https://github.com/kivy/kivy/pull/6381.
