### ISSUE TITLE
RFE: SettingsTuple Class

### ISSUE THREAD

**Issue by jbnance** [kivy/kivy#1783]
It would be great to have a settings class which allowed the user to modify a list of items which, when saved, becomes a tuple.

A simple form of this may be just a string with a CSV that is parsed.  I believe this could be implemented at present using the string setting class with on_config_change().

A more advanced form of this may be a scrollview of text boxes that automatically adds an additional text box to the end as the user is inputting values.
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.

**Comment by jbnance** [comment]
How is this issue "stale"?  The ball was in your court.  Are you saying that you won't accept RFEs unless they also come with code?

**Comment by dessant** [comment]
We do accept feature requests, but they are closed if they don't generate any interest by the community and contributors.
