### ISSUE TITLE
Potentially confusing behavior of SettingPath class

### ISSUE THREAD

**Issue by jbnance** [kivy/kivy#1784]
Kivy 1.7.2

When using the SettingPath class to store paths as a configuration setting there is an oddity regarding the "../" directory.

Let's say that the current value is '/foo/bar/baz'.
You want to change the value to '/foo/bar'.
You hit F1 to bring up the settings window and click the current setting to change it.
The filesystem browser pops up and you double-click '../'.
You then click 'OK' (without selecting anything).
The setting remains at the original ('/foo/bar/baz').

Typically the directory you are "in" (currently viewing) is selected by default when you hit "OK" without explicitly selecting a filesystem object.  However, this behavior is usually dependent upon whether the file browser is expecting that you are searching for a file or a directory.

Would it make sense to add some sort of flag to control this behavior?
##

**Comment by Julian-O** [comment]
Closing this as unclear and stale.

If you think this is in error, please post an example of the problem with more clear context.
