### ISSUE TITLE
[PPA] html build fails on Ubuntu Trusty

### ISSUE THREAD

**Issue by thopiekar** [kivy/kivy#1832]
There is not much to say - see:

https://code.launchpad.net/~kivy-team/+archive/kivy-daily/+build/5541853/+files/buildlog_ubuntu-trusty-i386.kivy_1.8.0-daily0%2B201401311526-1768-testing21~ubuntu14.04.1_FAILEDTOBUILD.txt.gz

**Comment by akshayaurora** [comment]
@thopiekar is this still a issue?

**Comment by akshayaurora** [comment]
reopen if this is still reproducible
