### ISSUE TITLE
Hello World Kivy causes Fatal Python error: (pygame parachute) Segmentation Fault Abort trap: 6

### ISSUE THREAD

**Issue by blissGitHub** [kivy/kivy#1844]
Hi,

Kivy seem to have broken itself.
Originally I was doing 'kivy main.py' on 2 apps.
For both, 'kivy main.py' would make them run properly on the desktop.

I then wanted to package it for android.
I had a lot of problems with this.
Today, I finally managed to package the app for android and create the APK for the 2 apps.
The first app is a hello world app and it ran perfectly on the android device.
The other one is more complicated and it crashed in the android device.  According to the debug messages it is something to do with unicode.
This was not an issue when run in the desktop.  
Therefore I wanted to test it further in the desktop....
Unfortunately, this time when I ran 'kivy main.py'....suddenly I got this error:

Fatal Python error: (pygame parachute) Segmentation Fault
Abort trap: 6

I googled this and supposedly it had something to do with OpenGL and rendering images.  But my app doesn't use images....

To prove to myself that this is a kivy error and not my coding error, I then ran 'kivy main.py' on the kivy hello world app that I created.

As expected, it also caused the same error to display.
I don't know how to replicate / reproduce this error...but all i know is that kivy main.py use to work but for some reason it is not any more.

How can I fix this?

**Comment by akshayaurora** [comment]
This is fixed in SDL2 backends we have moved to.

**Comment by RufusVS** [comment]
I installed sdl2 following the instructions [here](https://kivy.org/docs/installation/installation-osx.html)
Then at the start of the code, I put:
```
import os
os.environ['KIVY_WINDOW']='sdl2'
```
And I get these errors at startup:
```
[INFO              ] [Logger      ] Record log in /Users/rufussmith/.kivy/logs/kivy_17-08-12_33.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: pygame
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!

[CRITICAL          ] [App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL          ] [App         ] Unable to get a Window, abort.

```
