### ISSUE TITLE
Listview have low performance.

### ISSUE THREAD

**Issue by MCopperhead** [kivy/kivy#1855]
Hi. Sorry for bad english.
When ListView dynamically loads the content, FPS becames very low.
I've tested it on device with 1,5 GHz Quad-Core CPU.
I've made a short video with list_simple.py from kivy/examples (just added 1000 rows instead of 100) to help understand the problem:
http://www.youtube.com/watch?v=QBZ5dhNp1jc
You can see lags, when new content loading.

**Comment by pylover** [comment]
thanks a lot, i'll test it
