### ISSUE TITLE
InteractiveLauncher segfaults when Window is imported and Button is instantiated

### ISSUE THREAD

**Issue by ntoshev** [kivy/kivy#1862]
The following code segfaults with `Fatal Python error: (pygame parachute) Segmentation Fault`:

```python
from kivy.interactive import InteractiveLauncher
from kivy.app import App
from kivy.uix.button import Button
from kivy.core.window import Window

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

i = InteractiveLauncher(TestApp())
i.run()
```

If you remove the (unused) window import or replace the Button with Widget, it works OK. If you have the Window import but no Button, and try to create a Button later, the segfault occurs at the moment of instantiation (or when you safeOut() after instantiation).

**Comment by DavidA2014** [comment]
Is there any chance of a fix for this please? 

This is a real problem for my app.

**Comment by dessant** [comment]
The interactive launcher has been deprecated in https://github.com/kivy/kivy/commit/3f83ed2a7b7d463d6b721b737b1adc0ec30ea7af.
