### ISSUE TITLE
Updated Config API

### ISSUE THREAD

**Issue by aspidites** [kivy/kivy#1884]
Its really late, so forgive me if this doesn't come across as  clear, or sounds arrogant. I was looking at the config module and noticed that enough of the default ConfigParser's behavior is customized that it might make for a smaller module if we just wrote it from scratch. Then I started thinking about the syntax and how we could improve it. 

Consider:

``` python
from __future__ import print_function
from kivy.config import Config

fps_visible = Config.getint('kivy', 'show_fps')
Config.set('kivy', 'retain_time', '50')
```

Compare that with:

``` python
fps_visible = Config.kivy.show_fps
Config.kivy.retain_time = 50
```

Noteworthy things:
- Implicit casts too/from integral types
- config keys and values are treated as attributes instead of keys and values in a dictionary. 

Implementation would be rather easy, as it's already been done by [another developer](http://pythonhosted.org//ConfigObject/), and even [myself](https://github.com/tshirtman/ultimate-smash-friends/blob/master/usf/config.py)(thought I don't recommend using it).

If adding a dependency (on ConfigObject) was a problem, I think I could write this from scratch in very few lines of code. If nothing else, I'll get started on this and open a pull request so that a conversation can form on whether or not this is a good idea in practice.
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
