### ISSUE TITLE
Touchscreen double input on eGalax

### ISSUE THREAD

**Issue by kived** [kivy/kivy#1903]
I was having an issue with eGalax USB touchscreens sending double input to Kivy applications. It turns out that the reason is that Kivy was loading the eGalax device twice. We are using the default Kivy config which is created on first run:

```
[input]
mouse = mouse
%(name)s = probesysfs
```

Kivy ends up with two input devices - the mouse, and the auto-detected touchscreen (which are the same device). So every touch is a double-touch. This problem is solved by removing the probesysfs device.

eGalax startup (with auto-detect):

```
[DEBUG             ] Base: Create provider from mouse
[DEBUG             ] Base: Create provider from probesysfs
[DEBUG             ] ProbeSysfs: using probsysfs!
[DEBUG             ] ProbeSysfs: found device: eGalax Inc. USB TouchController at /dev/input/event9
[INFO              ] ProbeSysfs: device match: /dev/input/event9
[INFO              ] MTD: Read event from </dev/input/event9>
[INFO              ] Base: Start application main loop
[INFO              ] MTD: </dev/input/event9> range position X is 0 - 4095
[INFO              ] MTD: </dev/input/event9> range position Y is 0 - 4095
[INFO              ] MTD: </dev/input/event9> range touch major is 0 - 0
[INFO              ] MTD: </dev/input/event9> range touch minor is 0 - 0
[INFO              ] MTD: </dev/input/event9> range pressure is 0 - 255
[INFO              ] MTD: </dev/input/event9> axes invertion: X is 0, Y is 0
```

Relevant device (in /proc/bus/input/devices):

```
I: Bus=0003 Vendor=0eef Product=0001 Version=0210
N: Name="eGalax Inc. USB TouchController"
P: Phys=usb-0000:00:1d.2-1/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.2/usb7/7-1/7-1:1.0/input/input9
U: Uniq=
H: Handlers=mouse0 event9 
B: PROP=2
B: EV=b
B: KEY=400 0 0 0 0 0 0 0 0 0 0
B: ABS=2608000 3
```

You can see that event9 is properly detected as the mouse.

This does not happen with our ELO serial touchscreens. probesysfs does not find the ELO screen. And on my laptop, my touchpad is detected by probesysfs, yet does not have the double-input issue.

```
[DEBUG             ] Base: Create provider from mouse
[DEBUG             ] Base: Create provider from probesysfs
[DEBUG             ] ProbeSysfs: using probsysfs!
[DEBUG             ] ProbeSysfs: found device: SynPS/2 Synaptics TouchPad at /dev/input/event7
[INFO              ] ProbeSysfs: device match: /dev/input/event7
[INFO              ] MTD: Read event from </dev/input/event7>
[INFO              ] Base: Start application main loop
[INFO              ] Support: Starting twisted reactor
[INFO              ] MTD: </dev/input/event7> range position X is 1222 - 5734
[INFO              ] MTD: </dev/input/event7> range position Y is 910 - 4974
[INFO              ] MTD: </dev/input/event7> range touch major is 0 - 0
[INFO              ] MTD: </dev/input/event7> range touch minor is 0 - 0
[INFO              ] MTD: </dev/input/event7> range pressure is 0 - 255
[INFO              ] MTD: </dev/input/event7> axes invertion: X is 0, Y is 0
```

I can, of course, just continue to work around this by changing the config. Just figured I'd point out the inconsistency in input device handling, which can make debugging issues like this quite difficult. I probably would have figured out the problem much sooner if I wasn't used to seeing my touchpad detected and silently ignored all the time. (I spent a bunch of time messing with drivers, thinking that was the issue)

**Comment by AmarVK** [comment]
@kived 
I am facing the same issue with Asus Transformer. Were you able to solve this issue?
