### ISSUE TITLE
ActionGroup in spinner mode doesn't close on selection.

### ISSUE THREAD

**Issue by philwrenn** [kivy/kivy#1906]
If I run run the actionbar.py module directly, executing the "if main" block. The actionbar example loads without error. On my system both of the ActionGroups are displayed in spinner mode due to the available space. If I click an ActionGroup spinner it opens, but selecting an item in the group does not close the dropdown. The only way I have found to close the dropdown it to click elsewhere on the screen.

https://gist.github.com/philwrenn/9121379

There were no errors. I just added the log per the posting instructions.

**Comment by DanielKoohmarey** [comment]
Any updates on a successful approach to auto close the dropdown on selection?
