### ISSUE TITLE
Black background for all widgets on OS X

### ISSUE THREAD

**Issue by simpowel** [kivy/kivy#1923]
Platform : OS X 10.9.2 Mac mini
Kivy : 1.8.1
Symptom : for all applications on this machine, including the examples bundled with Kivy, all background/canvas are black. Only text appear (see screen capture attached for KivyCatalog demo). The plasma and animation demos also work properly.

The Kivy team tracked the problem to a misbehaving imageio provider. A workaround was found by adding the following line in the script /usr/local/bin/kivy  : KIVY_IMAGE=pygame, gif

![kivycatalog no canvas](https://f.cloud.github.com/assets/6825228/2302234/19fe19e4-a172-11e3-9576-3fef60f8c178.png)
##

**Comment by tito** [comment]
If somebody have an hardware or example to reproduce, reopen this one.
Right now, i don't reproduce the issue using KIVY_IMAGE=imageio on OSX 10.14 using the showcase demonstration.
