### ISSUE TITLE
ColorPicker is slow

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#1927]
ColorPicker instanciation and usage considerably slow down an app, consider either optimizing it a lot, or redoing it from scratch.
##

**Comment by KeyWeeUsr** [comment]
@Kovak Is it still an issue?

**Comment by Kovak** [comment]
I think yes, but a sort of complex, multifaceted one. Partly to blame on color picker, partly to blame on underlying things.

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
