### ISSUE TITLE
AccordionItem's title_args is broken

### ISSUE THREAD

**Issue by sirpercival** [kivy/kivy#1964]
It doesn't seem to change anything. In my .kv file, I've tried:

```
title_args: {'color': (1, 0, 0, 1)}
```

and

```
title_args: {'font_size': 100}
```

...but nothing seems to change.
##

**Comment by KeyWeeUsr** [comment]
@aspidites Is some work present here, or can it be closed?

**Comment by Julian-O** [comment]
Closing this as it is unclear that there is anything else remaining to do.

If you disagree, please let us know with details of what change you want to see.
