### ISSUE TITLE
Incorrect ScrollView behavior when setting scroll_x

### ISSUE THREAD

**Issue by bionoid** [kivy/kivy#2038]
After manually setting scroll_x, subsequent drag-scroll uses the wrong position.

To reproduce:

1. Click > button
2. Scroll back to the left side with drag-scroll

Code: https://gist.github.com/bionoid/0c16de49f79e8e6d3714

(I did not verify if this is the case for scroll_y also)

**Comment by dessant** [comment]
Let's track this at https://github.com/kivy/kivy/issues/1078.
