### ISSUE TITLE
Feature request: drag and drop

### ISSUE THREAD

**Issue by merlink01** [kivy/kivy#2051]
At the momtent it seems like drag and drop of files (pathes) from external applications is not supported.

For me it's a must have feature for a Gui Toolkit.

**Comment by encompass** [comment]
Not sure how I missed it, but I too reported this issue.
https://github.com/kivy/kivy/issues/3557
There I have a video example among other things.  Hope it helps as I would really like to start using python for my cross platform development as well.

**Comment by dessant** [comment]
Let's track it here https://github.com/kivy/kivy/issues/3557.
