### ISSUE TITLE
ActionGroup shouldn't inherit from Spinner

### ISSUE THREAD

**Issue by wjanssen** [kivy/kivy#2054]
I notice that when I select an action from an ActionGroup deployed in spinner mode, the dropdown doesn't disappear.  I think this is caused by the welter of implicit callbacks between Dropdown, Spinner, and ActionGroup.

After reviewing the code, I think it's a problem that ActionGroup inherits from Spinner.  It's not really a spinner -- you don't "change the text" to announce a selection, the items in the group are ActionItems, not text strings, and you don't really 'select', you invoke actions directly via the action items.  Yes, it does have a dropdown like a Spinner, but that's where the similarity ends.

I'd suggest re-implementing ActionGroup as an ActionButton with an associated Dropdown, which is almost what's there already.  You need to arrange for the dropdown's dismiss action to be called when a "selection" is made; probably simplest just to add a hook to the ActionItem class, such as 'action_taken'.
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
