### ISSUE TITLE
Crash/Mashups Occuring if ScreenManager transitions too fast.

### ISSUE THREAD

**Issue by Kovak** [kivy/kivy#2071]
If a ScreenManager is transitioned faster than the effect allows, this can result in errors where 2 screens are 'mashed together' on the screen.

This issue is demonstrated by this app here, iterate through the stack of screens uses next button several times and then use Esc key to go back, this will result in screens that are not either the red or the blue color (or crashes if done fast enough): 
https://gist.github.com/Kovak/10514298
##

**Comment by Julian-O** [comment]
Ran this code on Windows 11, Kivy 2.2.1, Python 3.11 and found no issue.

@Kovak Does this still occur? If so, can you give us your platform and the logs? Thanks.
