### ISSUE TITLE
Unable to run kivy on raspberry pi with

### ISSUE THREAD

**Issue by shifters67** [kivy/kivy#2115]
HI all,

i get the following when trying trying to run kivy on the raspberry pi with a texy 2.8" colour lcd with touch screen.  I have followed the instructions http://kivy.org/docs/installation/installation-rpi.html exactly and all seem to build ok with no errors.

I have tried the dev build and the global build options.

I have tried running from the shell command line and from an xterm in X - same error.

Any ideas?  This is raspbian latest everything with texy ammendments found here http://www.raspberrypi.org/forums/viewtopic.php?f=45&t=64993 for the touch screen.

```
INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_14-04-26_2.txt
[INFO   ] Kivy v1.8.1-dev
[INFO   ] [Python      ] v2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3]
[INFO   ] [Factory     ] 157 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_pil ignored)
[ERROR  ]
Traceback (most recent call last):
  File "/home/pi/kivy/kivy/lang.py", line 1186, in execute_directives
    mod = __import__('.'.join(package.split('.')[:-1]))
  File "/home/pi/kivy/kivy/extras/highlight.py", line 3, in <module>
    from pygments.lexer import RegexLexer, bygroups, using
ImportError: No module named pygments.lexer
 Traceback (most recent call last):
   File "main.py", line 212, in <module>
     ShowcaseApp().run()
   File "/home/pi/kivy/kivy/app.py", line 773, in run
     self.load_kv(filename=self.kv_file)
   File "/home/pi/kivy/kivy/app.py", line 593, in load_kv
     root = Builder.load_file(rfilename)
   File "/home/pi/kivy/kivy/lang.py", line 1546, in load_file
     return self.load_string(data, **kwargs)
   File "/home/pi/kivy/kivy/lang.py", line 1593, in load_string
     parser = Parser(content=string, filename=fn)
   File "/home/pi/kivy/kivy/lang.py", line 1122, in __init__
     self.parse(content)
   File "/home/pi/kivy/kivy/lang.py", line 1220, in parse
     self.execute_directives()
   File "/home/pi/kivy/kivy/lang.py", line 1197, in execute_directives
     package)
 kivy.lang.ParserException: Parser: File "./showcase.kv", line 2:
 ...
       1:#:kivy 1.8.0
 >>    2:#:import KivyLexer kivy.extras.highlight.KivyLexer
       3:#:import Factory kivy.factory.Factory
       4:
 ...
 Unable to import package 'kivy.extras.highlight.KivyLexer'
```

regards

Shifters

**Comment by pylover** [comment]
Thanks.

**Comment by tony** [comment]
To get it to work:

``buildozer.spec``:

``requirements = kivy,pil,sqlite3,pygments``

**Comment by aleksandaratanasov** [comment]
Shouldn't this dependency be **actually** listed as such? I find it rather annoying that following the official guide on installing Kivy on the RPi you have to dig into the issues on GitHub to find a solution for this problem. After all the demos should be the ones that run without any issues WITH the things that are listed as requirements to get Kivy installed on the system. Please consider adding at least a warning if the required packages for the showcase are not met.
