### ISSUE TITLE
Errors should raise Exceptions

### ISSUE THREAD

**Issue by cropleyb** [kivy/kivy#2121]
I have noticed several times that Kivy doesn't raise exceptions when it cannot logically deal with error conditions. This causes strange behaviour that is very difficult to debug, especially for new users of Kivy. If an error condition is detectable, it should be reported to the developer for them to decide what to do.
For example:
https://github.com/kivy/kivy/issues/2119
https://github.com/kivy/kivy/issues/2117
https://github.com/kivy/kivy/issues/2120

If the Kivy team is concerned about breaking existing applications, they could use something like:

```
if <whatever error detected>:
    kivy_raise(SomeException("Whatever happened"))
    do_what_it_was_doing_previously()

def kivy_raise(e):
    if config.raise_exceptions:
         raise e
     logger.log(e)
```

I know this is not a specific bug, but the same type of problem has collectively caused me weeks of painful debugging, and I'm sure I'm not alone.

Thanks,
Bruce
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
