### ISSUE TITLE
Label is not stripping spaces and newlines on iOS

### ISSUE THREAD

**Issue by cropleyb** [kivy/kivy#2138]
In https://github.com/kivy/kivy/pull/2048:
Matham: label strips leading and trailing spaces and newlines by design. You can turn it off by setting strip to false.
cropleyb: Great :) But why isn't it stripping on iOS?
matham: I don't know, as far as I know there's no platform dependent code there. Although it could have something to do with how newlines are represented in that platform.

This is not important to me - I have just set strip to False, but it should probably be fixed at some stage. :)

**Comment by dessant** [comment]
@cropleyb could you check if you still have this issue with kivy master on ios?

**Comment by dessant** [comment]
Since the original report, both the stripping logic and text provider changed, please reopen if you can still reproduce.
