### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by pkor** [kivy/kivy#2161]
Our software runs an information screen that has animations playing on it for 8 hours at a time. When I exited the application I saw these errors:

![image](https://cloud.githubusercontent.com/assets/3238858/2891505/62ff1ce8-d533-11e3-896c-e53e9e38fb31.png)

This looks to me like a memory leak. I looked at the method it's talking about actually don't enough about what's going on there to diagnose the problem. Even though it looks like it overcomes the issue I thought it could be a problem for someone down the road and maybe we should look into it. If it helps our software uses the new repeat function on the animations. I'm not sure if maybe the repeat is starting the animation over without clearing some buffer? Just a thought.

**Comment by dessant** [comment]
Please reopen with a runnable example app if the issue is still present.
