### ISSUE TITLE
Error with Kivy Launcher under Android (print function and ASCII character)

### ISSUE THREAD

**Issue by Eric78** [kivy/kivy#2176]
I have synthezised the problem in the following code, when launched by Kivy launcher under Android

#!/usr/bin/python3 
#-*- coding: utf-8 -*-
import kivy
kivy.require('1.8.0')
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        message = "Bonjour à toi"
        print(message)
        return Button(text=message)

TestApp().run()

There is no error in the 3 cases below:
- message = "Hello world"
- print(message) is removed
- launched on my PC (windows)

The error I get is the following:
I/python  (23860): Initialize Python for Android
I/python  (23860): ['/data/data/org.kivy.pygame/files/lib/python2.7/site-packages', '/data/data/org.kivy.pygame/files/lib/site-python']
I/python  (23860): Android path ['/data/data/org.kivy.pygame/files/lib/python27.zip', '/data/data/org.kivy.pygame/files/lib/python2.7', '/data/data/org.kivy.pygame/files/lib/python2.7/lib-dynload', '/data/data/org.kivy.pygame/files/lib/python2.7/site-packages', '/storage/emulated/0/kivy/Test', '/data/data/org.kivy.pygame/files/lib/python2.7/site-packages/PIL']
I/python  (23860): Android kivy bootstrap done. __name__ is __main__
I/python  (23860): Run user program, change dir and execute main.py
I/python  (23860): [INFO              ] Kivy v1.8.0
I/python  (23860): [INFO              ] [Logger      ] Record log in /storage/emulated/0/kivy/Test/.kivy/logs/kivy_14-05-09_13.txt
I/python  (23860): [INFO              ] [Factory     ] 157 symbols loaded
I/python  (23860): [DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
I/python  (23860): [DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout=60s
I/python  (23860): [DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
I/python  (23860):  /data/data/org.kivy.pygame/files/lib/python2.7/site-packages/kivy/core/image/img_pygame.py:12: RuntimeWarning: import cdrom: No module named cdrom
I/python  (23860):  (ImportError: No module named cdrom)
I/python  (23860): [INFO              ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
I/python  (23860): [DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
I/python  (23860): [DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
I/python  (23860): [INFO              ] [Text        ] Provider: pygame
I/python  (23860): [DEBUG             ] [App         ] Loading kv <./test.kv>
I/python  (23860): [DEBUG             ] [App         ] kv <./test.kv> not found
I/python  (23860):  Traceback (most recent call last):
I/python  (23860):    File "main.py", line 16, in <module>
I/python  (23860):      TestApp().run()
I/python  (23860):    File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 766, in run
I/python  (23860):    File "main.py", line 13, in build
I/python  (23860):      print(message)
I/python  (23860):    File "<string>", line 15, in write
I/python  (23860):  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
I/python  (23860): Python for android ended.

Additional question: why Python 2 is used instead of python 3 ?

**Comment by FeralBytes** [comment]
Python2 ASCII codec can't decode Unicode characters. You need to be explicit. Use [unicode()](https://docs.python.org/2/library/functions.html#unicode). For your [reference](http://stackoverflow.com/a/21129492).
Why Python 2? Because Python for Android has not yet been ported to Python 3. But some Python 3, specifically it's syntax is [possible](https://github.com/kivy/python-for-android/issues/322).
I recommend closing this issue. It should also have the label android-platform.
