### ISSUE TITLE
Allow detection of mouse pointer leaving the window (desktop window providers)

### ISSUE THREAD

**Issue by mvasilkov** [kivy/kivy#2178]
As of now, you can't detect that the mouse pointer has left the window since `window.mouse_pos` is clamped to the window size.

Detecting this would be useful when trying to implement a custom mouse cursor.

**Comment by dessant** [comment]
sdl 2.0.4 will soon be released, so this will be possible for all relevant platforms https://wiki.libsdl.org/SDL_CaptureMouse.

Related issue: https://github.com/kivy/kivy/issues/2529.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/3834.
