### ISSUE TITLE
ActionBar enhancements

### ISSUE THREAD

**Issue by mjmare** [kivy/kivy#2181]
I would seem useful if ActionPrevious.app_icon could be None (now it will give:  
"ValueError: None is not allowed for ActionPrevious.app_icon") to hide the icon.

The ActionGroup foldout triangle is always at the bottom, even if the ActionBar is at the bottom of the window. This seems a bit counterintuitive because the menu folds out in the upward direction (which is nice).

[Kivy 1.8.0]
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
