### ISSUE TITLE
ModalView background_color is ignored

### ISSUE THREAD

**Issue by PhoenixWright** [kivy/kivy#2198]
Platform: OS X
Kivy Version: 1.8.1-dev pulled on 05/16/2014
Test Code: https://gist.github.com/PhoenixWright/2476f3194d39e635c57e
My log output is in a comment on that gist.

I would have expected to not see the background color of the ModalView, and I see this instead, which looks like the normal background has been unaffected by background_color:

![screen shot 2014-05-17 at 11 53 03 am](https://cloud.githubusercontent.com/assets/382245/3005814/87059d3c-ddf4-11e3-9e4c-5fbb08b4e7f7.png)
##

**Comment by darkopevec** [comment]
Test code is unavailable, though I believe this is not an issue.
background-color affects the overlay around the ModalView, whereas you would like to change background:

    background = StringProperty(
        'atlas://data/images/defaulttheme/modalview-background')
    '''Background image of the view used for the view background.

**Comment by KeyWeeUsr** [comment]
@darkopevec exactly, but maybe the naming is kind of weird. It's not in this widget only, so maybe it was intended. And maybe `shadow_color` or something would be better.

**Comment by PhoenixWright** [comment]
@darkopevec, you're correct. Sorry about deleting the test code, I figured a year or so was fine, should have pasted it in here instead.

**Comment by darkopevec** [comment]
@KeyWeeUsr I agree the naming is misleading and I would second your suggestion to rename it kivy wide.

**Comment by Julian-O** [comment]
Believed fixed by #6469.

If the problem persists, please let us know.
