### ISSUE TITLE
Mac OS X Windowed rendering bug

### ISSUE THREAD

**Issue by Gipzo** [kivy/kivy#2201]
When kivy app started in windowed mode and window size is bigger than display size I have this rendering bug. I guess this is due to OS X automatically resizing kivy window.

![mac_os_bug](https://cloud.githubusercontent.com/assets/1777150/3033089/fb17287c-e05f-11e3-9c7d-537852851546.png)

**Comment by dessant** [comment]
@qua-non, i've seen the same glitches on a retina issue pic, could it be the same?

**Comment by akshayaurora** [comment]
@dessant yes this should be now fixed with the new retina support @Gipzo please re-open if you still have the issue with latest master.
