### ISSUE TITLE
Mac OS X resized window get's recreated and centered

### ISSUE THREAD

**Issue by derenio** [kivy/kivy#2204]
OS X 10.8
kivy 1.8.0
After resizing the main window of my app (by dragging any of its corners) it gets:
 * recreated (goes black and then gets redrawn),
 * its position gets reset (jumps to the center of the screen as I'm leaving the `graphics.position` config to its defaults).

Could the window's recreation be a regression to #168?
If fixing the window's recreation isn't feasible on OS X in the near future, at least preserving the previous position of the window would be a satisfiable workaround.

**Comment by dessant** [comment]
This issue is fixed in 1.9.0 with SDL2.
