### ISSUE TITLE
Installation documentation for Ubuntu (14.04) and Debian obsoleted

### ISSUE THREAD

**Issue by BiteMyBucket** [kivy/kivy#2209]
The installation instructions relies on the ffmpeg transitional package, which has been removed in favor of the libav fork in Debian (and, consequently, Ubuntu), so they are outdated and installation will fail.

**Comment by jpiabrantes** [comment]
In my opinion the installation instructions should be updated asap. It's very discouraging to try a new framework and the installations instructions don't work makes people wonder how many documentations problems they will get during development. I still don't get which commands I have to do on the virtualenv and which ones I have to run outside the virtualenv.

**Comment by rnixx** [comment]
i just created a pull request formatting the recent install instructions. https://github.com/kivy/kivy/pull/3508.

Anyway, these docs are imo mostly outdated. Kivy switched to SDL2 in 1.9, thus pygame installation is not required any longer. Also the ubuntu install dependencies have changed for 14.04.

I wanted to update the docs to 14.04, but i fear the complete installation documentation needs an overhaul (not only linux).

Nevertheless, here are the steps required to get a running kivy checkout in virtualenv on recent debian / ubuntu:

    sudo apt-get install -y \
        build-essential \
        mercurial \
        git \
        python2.7 \
        python-setuptools \
        python-pip \
        python-virtualenv \
        python-dev \
        libsdl2-dev \
        libsdl2-image-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev \
        libportmidi-dev \
        libswscale-dev \
        libavformat-dev \
        libavcodec-dev \
        zlib1g-dev \
        libfreetype6-dev

    git clone git://github.com/kivy/kivy.git
    cd kivy
    virtualenv venv
    venv/bin/pip install cython
    venv/bin/python setup.py install

    venv/bin/python
    >>> import kivy
    [INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_15-07-15_0.txt
    [INFO   ] [Kivy        ] v1.9.1-dev
    [INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13)
    [GCC 4.8.2]

It should be pretty easy to get it installed globally once the system deps are installed:

    sudo pip install cython
    sudo pip install kivy

takes kivy from pypi of course..

**Comment by akshayaurora** [comment]
nix closed this via #3508
