### ISSUE TITLE
Camera doesn't initialize unless resolution is changed

### ISSUE THREAD

**Issue by wjanssen** [kivy/kivy#2222]
In 1.8.0, there's this bit in kivy.uix.camera.Camera._on_index():

```
    if self.resolution[0] < 0 or self.resolution[1] < 0:
        return
```

In which case, the initialization never proceeds.

However, the default resolution is [-1, -1], to select "the best image available".  I suppose there's a philosophical argument that the best image is no image, but in ordinary practice it would be nice to be able to get an image from the camera.
##

**Comment by dessant** [comment]
@wjanssen could you check if the bug is still pressent in kivy master?

**Comment by ewingd** [comment]
I'm seeing the same issue with a freshly installed copy of Kivy 1.10.0.  Is there a better way to get the highest resolution available?

**Comment by Julian-O** [comment]
I am sorry to do this to you again, @wjanssen, but I can't find that line in Kivy 2.2.1, so I am assuming it is now fixed.

Can you please confirm?
