### ISSUE TITLE
avfoundation camera support doesn't load on OS X 10.7 or 10.9

### ISSUE THREAD

**Issue by wjanssen** [kivy/kivy#2223]
The OS X camera provider on 10.7 is supposed to be avfoundation, but I get this in my log file (using Kivy 1.8.0 on OS X 10.7.4):

[DEBUG             ] [Camera      ] Ignored <avfoundation> (import error)
[INFO              ] [Camera      ] Provider: opencv(['camera_avfoundation'] ignored)

**Comment by jrpdrummer** [comment]
Same problem with Python 2.7.6  Yosemite (10.10)

**Comment by cbenhagen** [comment]
This works for me on OSX 10.11 and 10.10
```
$ python
Python 2.7.10 (default, Sep 14 2015, 02:26:06)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy.core.camera.camera_avfoundation
[INFO   ] [Logger      ] Record log in /Users/ben/.kivy/logs/kivy_15-10-09_11.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.10 (default, Sep 14 2015, 02:26:06)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Camera      ] Provider: avfoundation
>>>
```
I installed kivy with:
```
brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer
pip install -I Cython==0.21.2
USE_OSX_FRAMEWORKS=0 pip install git+https://github.com/kivy/kivy.git@1.9.0
```

**Comment by cbenhagen** [comment]
I think we can close this issue. It has been fixed by https://github.com/kivy/kivy/commit/e56d44feeac37ed9f433afe5c59b0fa938f33216

The fix has not been released to pypi yet (https://github.com/kivy/kivy/issues/3717) so you have to install with
```
pip install git+https://github.com/kivy/kivy.git@1.9.0
```
or if using Homebrew with
```
USE_OSX_FRAMEWORKS=0 pip install git+https://github.com/kivy/kivy.git@1.9.0
```

**Comment by inclement** [comment]
Great, thanks @cbenhagen
