### ISSUE TITLE
Fixed sized ModalView's not centered propery after rotating android screen

### ISSUE THREAD

**Issue by hallab** [kivy/kivy#2230]
If I create a PopUp on android with size_hint=(None, None) and then rotate the device, it is not recentered. Maybe on_resize does not fire there? However if I bind _align_center to size like this:

```
self.get_root_window().bind(size=popup._align_center)
```

it seems to be working fine.
##

**Comment by kived** [comment]
This should be retested. I committed a fix for resizing popups when the keyboard is opened/closed, and it will probably fix this.

**Comment by KeyWeeUsr** [comment]
```
from kivy.lang import Builder
from kivy.base import runTouchApp
from kivy.uix.boxlayout import BoxLayout
Builder.load_string('''
#:import Factory kivy.factory.Factory
<Pop@Popup>:
    size_hint: None, None
<Test>:
    Button:
        on_release: Factory.Pop().open()
''')
class Test(BoxLayout): pass
runTouchApp(Test())
```

Can't test with launcher, because can't rotate, but if it's fixed, it should be closed. ^^

**Comment by Julian-O** [comment]
Assuming closed as no-one has complained for 5 years.
