### ISSUE TITLE
drive navigation feature in FileChooser widget under windows

### ISSUE THREAD

**Issue by AshokEmrys** [kivy/kivy#2233]
This is in of concern with the windows operation system.

Currently the `FileChooser` widget allows navigation through directories which are present only in the drive to which the `path` property belongs to.

Though the drive can be explicitly changed through modification of the `path` property, it cannot be changed through the user action once the widget gets fired up.

> **My suggestion**: Display the drive list once the user clicks `..\` (one up directory) from the root directory of the drive, and later change the `path` to the particular drive which user selected.

**Comment by tmckeage** [comment]
Is this something being worked on?

**Comment by tshirtman** [comment]
I'm pretty sure it's not being worked and there are no current plan to change this.
If you think you can provide a solution and make a case for it, feel free to discuss it and create a PR, but did you look at the linked garden project to see if it fit your needs?
