### ISSUE TITLE
Widget memory leak when removed

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#2247]
After removing widgets, memory does not appear to be reclaimed (tested on iOS)

``` python
from kivy.app import App
from kivy.lang import Builder

class TestApp(App):
    def on_pause(self, *l):
        return True

    def build(self):
        return Builder.load_string('''
#:import Button kivy.uix.button.Button

BoxLayout:
    orientation: 'vertical'
    FloatLayout:
        id: container
    BoxLayout:
        size_hint_y: None
        height: 100
        orientation: 'horizontal'
        Button:
            text: 'add'
            on_press: container.add_widget(Button())
        Button:
            text: 'remove'
            on_press: container.clear_widgets()
''')

TestApp().run()
```

Click add several times (memory consumption will increase). Click remove and wait, no memory seems to be reclaimed.

**Comment by Blaygor** [comment]
This issue is 6 years old, but I do not think it has been properly resolved. The same is happening with iOS builds today. Infinite memory growth caused by widgets, even when deleted with clear_widgets(). Calling gc.collect() does not seem to do anything.

**Comment by matham** [comment]
I believe we had a [discord discussion](https://discord.com/channels/423249981340778496/490493814281338890/813582694390169620) about this?

The way to test if memory is not reclaimed is creating a weakref to the widget and seeing if it's not released when the widgets are cleared. Anything beyond that is related to how the system/python handles memory and is not something kivy can control.
