### ISSUE TITLE
No Logger messages in log file in android service

### ISSUE THREAD

**Issue by thorin-schiffer** [kivy/kivy#2289]
All the messages logged from android service will not appear in the log file. Seems like the service tries to open the same file as the main process and fails, but I'm not sure.

It looks also weird, how the messages are handled in FileHandler: it checks class variables instead of instance's ones (logging.py:170,171,176), which causes that all file handlers have the same filename

Temporal workaround for that is to put something like this at the beggining of the service/main.py:

```
    FileHandler.filename = 'log.txt'
    FileHandler.fd = open(FileHandler.filename, 'w')
    handler = FileHandler()
    handler.setLevel('DEBUG')
    Logger.addHandler(handler)
```
##

**Comment by Julian-O** [comment]
`logging.py` had a major revamp about a year or two ago.

Closing as stale, but if the problem still occurs, please let us know.
