### ISSUE TITLE
paste.pocoo.org is dead

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2293]
We should use a different service in the report tool. How about gists?
https://developer.github.com/v3/gists/

https://github.com/kivy/kivy/blob/master/kivy/tools/report.py#L136

**Comment by Sentient07** [comment]
Hi, I have a PR for this issue, https://github.com/kivy/kivy/pull/3116 . It generates different files in a single gist, simplifying readability.

**Comment by tito** [comment]
PR  merged!
