### ISSUE TITLE
Gif Animation Stuttering

### ISSUE THREAD

**Issue by PySean** [kivy/kivy#2307]
Hello everyone, I've been chugging along quite happily until I loaded up my little game again. For whatever reason, the player character's animation would stutter. To be specific... he would animate about halfway, then restart at the beginning of the animation again. This really annoyed me because the gif was working perfectly before.

The gif seems to animate correctly in other applications, e.g., Chromium, and different gif images are bereft of this stuttering problem as well. To reproduce the issue, use this: 
![main_character_front_moving](https://cloud.githubusercontent.com/assets/5558694/3453129/c8e626a6-01bf-11e4-9ce5-c2dfeaec36ce.gif) 

As you can see it animates perfectly well in a browser. I simply added it to an Image widget with anim_delay: 0.05. I put it in a BoxLayout with a white background.

Here is some output from running my little script on this image, as well as the log file: 
https://gist.github.com/PySean/847710c270dec37aa373

Any help will be greatly appreciated!

**Comment by jeyfrinjulian** [comment]
hi, can implement:

import os

os.environ["KIVY_IMAGE"]="pil"

is the solution for mi case
