### ISSUE TITLE
Image file loader expects extensions, should also load files without extension

### ISSUE THREAD

**Issue by Xeno22** [kivy/kivy#2326]
The ImageLoader tries to detect the image format by the extension. Therefor it does not work for files with a wrong extension or no extension at all.

Is there a standard way to load a file without extension into an image? Currently I hacked it to always load files with the img_pygame, no matter what extension is given. Works like a charm.
##

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/4708.
