### ISSUE TITLE
Textinput shows the password

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#2337]
If any of the properties of a TextInput are changed it shows the password in plane text for a split second.
##

**Comment by dessant** [comment]
I can't reproduce this either on linux and windows, please reopen with more details if the issue is still there.

**Comment by dessant** [comment]
We've tested with @akshayaurora, it seems to be only reproducible in kivycatalog: open the text panel and press `Render Now`, the password field should flash the text.

If `password: True` is declared before the `text` property in kv, the text is not flashed.

**Comment by dessant** [comment]
@matham says both rules should be applied in the same frame regardless of the order, so it could be a textinput bug.

**Comment by matham** [comment]
Yeah, because rendering happens upon the next clock cycle, after the rules are applied, and both rules should be applied at the same time. So somehow password: True is not applied immediately. Unless there's something I'm missing about kivycatalog that makes it different.

**Comment by akshayaurora** [comment]
This is a catalog bug specifically because of reapplying multiple rules
without removing earlier ones.

Trying to bind multiple properties in multiple rules can lead to this
behavior, this bug is not reproducible out of kivy catalog.

This would be a valid bug if some one can reproduce the issue out of
kivycatalog.
