### ISSUE TITLE
properties import error

### ISSUE THREAD

**Issue by jgandert** [kivy/kivy#2347]
In PyDev `from kivy.properties import NumericProperty` is shown as an error / unresolved import. It works just fine, but I guess this can be fixed. Maybe some kind of definition is missing..

My system is: Ubuntu 14.04 / 64bit - Python 3.4 - Eclipse 4.4 (it was also the case for Python 2.7 and older Eclipse versions)

**Comment by matham** [comment]
I fixed this in pydev by adding `kivy.properties` to the forced builtins as described here: http://www.pydev.org/manual_101_interpreter.html#PyDevInterpreterConfiguration-ForcedBuiltins.
