### ISSUE TITLE
Add support for gamepads / joysticks

### ISSUE THREAD

**Issue by CreamyCookie** [kivy/kivy#2361]
The following events (with the parameters next to them) are not handled by Kivy [here](https://github.com/kivy/kivy/blob/6cb9c34ef565389f15c27bfd828c182f401e40ea/kivy/core/window/window_pygame.py#L267) (and because they're ignored, there's no way to get them):

    JOYAXISMOTION    joy, axis, value
    JOYBALLMOTION    joy, ball, rel
    JOYHATMOTION     joy, hat, value
    JOYBUTTONUP      joy, button
    JOYBUTTONDOWN    joy, button

For gamepads  / joysticks to work, `pygame.joystick.init()` needs to be called. They can be accessed with `pygame.joystick.Joystick(num)` (the second controller would be `1`) and also need to be each initialised with `.init()`.

Maybe we could do `Window.request_joystick(num, on_gamepad_close, ..)` analogue to `Window.request_keyboard`, which returns an `EventDispatcher` subclass (like [Keyboard](https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L32)) that has methods for aforementioned events (`on_axis_motion`, `on_button_down`, ..). What do you think?

**Comment by dessant** [comment]
Pygame was deprecated, fixed for sdl2 https://github.com/kivy/kivy/pull/2564.
