### ISSUE TITLE
Scroll view mouse wheel scrolling not consistent

### ISSUE THREAD

**Issue by matham** [kivy/kivy#2372]
When both x and y scrolling is enabled, even if e.g. there's nothing to scroll in y, doing a mouse wheel up/down on the x bar (when scrolling on bars) will still scroll the x bar horizontally. However, if y scrolling is disabled, then mouse wheel up/down doesn't work anymore, even if x scrolling is enabled and we're scrolling on top of the x bar.

This is the code that is responsible: https://github.com/kivy/kivy/blob/master/kivy/uix/scrollview.py#L584
##

**Comment by Julian-O** [comment]
Is this still present? Do we have some code to demonstrate it?

**Comment by ElliotGarbus** [comment]
> Is this still present? Do we have some code to demonstrate it?

I'm confident this is not an issue.  If desired I could create a demo.

**Comment by Julian-O** [comment]
@matham, I am closing based on my confidence in Elliot's confidence.

If this is still an issue, please let us know.
