### ISSUE TITLE
 kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin

### ISSUE THREAD

**Issue by knappador** [kivy/kivy#2381]
Not sure if we have a bug here.  Just fishing.

Gstreamer 1.4.0-1
Kivy Master

Anything else helpful?

**Comment by MatanRubin** [comment]
I saw the same issue on MacOS El Capitan, and can confirm that `brew install gst-plugins-bad` solved the issue for me.

**Comment by noncup** [comment]
On OS X I removed gstreamer directory from kivy/lib and it worked.
path on my machine was:
usr/local/lib/python3.7/site-packages/kivy/lib
type: rm -R gstreamer
then try running the app

**Comment by sgpy** [comment]
@noncup Thanks works for me too.

**Comment by bschnekenbergd** [comment]
Having issue here as well, same message. Any other thoughts on it?

python 3.7
Kivy 1.10.1
Anaconda3

**Comment by sgpy** [comment]
@bschnekenbergd Did you try the work around mentioned by @noncup ?

**Comment by bschnekenbergd** [comment]
Never mind, created a new project and it's working now.

Appreciate
