### ISSUE TITLE
Kivy ActionToggleButton image missing when resizing the window

### ISSUE THREAD

**Issue by gpietersekivy** [kivy/kivy#2391]
When you run the application, the window size is not fullscreen. The application has some action buttons and an action toggle button with images in the ActionBar. When you maximize the application window or resize, the ActionToggleButton image is missing, but the ActionButton images are not missing. This is kivy 1.8.0 running apple Mac OS X 10.8.5.

Link to kivy app debug log when window is maximized:

https://gist.github.com/anonymous/330abc4cbbeed786f8cb

**Comment by dessant** [comment]
Fixed in master with sdl2.
