### ISSUE TITLE
get_pos() method from core.audio doesn't work

### ISSUE THREAD

**Issue by EmptySamurai** [kivy/kivy#2406]
get_pos() method from core.audio doesn't work. It always returns -1. I found out that SoundLoader loads SoundPygame class. And it seems, that there is a mistake: a sound file in class is loaded via mixer.Sound but get_pos() method is called via mixer.music. So it's more likely that they do not know about each other. But if I load sound using mixer.music.load() everything works fine.

**Comment by rastogiachyut** [comment]
almost done..

**Comment by tito** [comment]
This has been fixed in the latest version :)
