### ISSUE TITLE
Determining when an audio clip has finished

### ISSUE THREAD

**Issue by bjornardo** [kivy/kivy#2441]
Hi,

I'm trying to write something that runs some code once playback of an audio-clip has finished and failed.

First I bind a callback to the on_stop event but that was only issued when the clip is actively stopped (by my_snd.stop()) and not when the clip ended.

The I tried to read out the length of the script but this simply did not work. my_snd.length is always 0. I printed it's value before, after and during playback of the clip. I tried calling my_snd.load() but it did not update.

The best solution I found was to call my_snd.get_pos(). This returned the current position in the stream and snapped back to 0 (or slightly below) when the clip ended. But with this solution I have to actively poll the script until it is finished.

I tried with both ogg and wav file format with the same result.

Is there any good way to do this?

I am running kivy version 1.8.0 with python 2.7 under windows 8.

Thankful for any kind of help on this issue.

Björn
##

**Comment by akshayaurora** [comment]
This is fixed by https://github.com/kivy/kivy/pull/2131?

**Comment by rastogiachyut** [comment]
trying to understand and solve

**Comment by rastogiachyut** [comment]
Is this issue closed?
or does it require to define on_start and on_stop events in __init__.py

**Comment by kived** [comment]
If we're using gstplayer on Windows now then yes, it would be fixed by #2131, otherwise this is probably an issue in pygst or pygame audio providers. Not sure what the default audio provider is on Windows with the portable package (assuming that's what @bjornardo was using).

**Comment by bjornardo** [comment]
Hi people,

I have not have time to look at this for a while. Is there any release including #2131 that I can test, or do I have to checkout something from git?

Is there anything I can run to determine which default audio provider I'm using?

/BA

**Comment by FeralBytes** [comment]
You would have to clone the current master branch as the fix will be in 1.9.0 when it is released.

**Comment by KeyWeeUsr** [comment]
This might be a part of what has to be done to close #2156.

**Comment by Julian-O** [comment]
Looks like it was satisfied by #2131. If this is in error, please let us know.
