### ISSUE TITLE
Can not run Kivy on Linaro ubuntu 12.04 for UDOOquad

### ISSUE THREAD

**Issue by hiroman098** [kivy/kivy#2445]
I can not run Kivy, help me !
 
I installed Kivy, the following.
My enviroment is Linaro ubuntu 12.04 on UDOO quad.
************************
ubuntu@udoo:$sudo apt-get clean
ubuntu@udoo:$sudo apt-get update
ubuntu@udoo:$sudo apt-get upgrade
ubuntu@udoo:$sudo apt-get install python-setuptools python-pygame python-opengl python-gst0.10 python-enchant gstreamer0.10-plugins-good python-dev build-essential libgl1-mesa-dev libgles2-mesa-dev cython
ubuntu@udoo:$sudo apt-get install python-pip
ubuntu@udoo:$sudo pip install --upgrade cython
ubuntu@udoo:$sudo apt-get install git
ubuntu@udoo:$git clone git://github.com/kivy/kivy.git
$cd kivy
ubuntu@udoo:kivy$python setup.py build_ext --inplace -f
ubuntu@udoo:kivy$sudo python setup.py install
***************** 
Then, "main.py" in Desktop directory runned.
Error message is displaied "Fatal Python error: (pygame parachute) Segmentation Fault".
 
"main.py" code is the following
*****************
import kivy
 
from kivy.base import EventLoop
EventLoop.ensure_window()
 
from kivy.app import App
from kivy.uix.button import Button
 
class MyApp(App):
title="Sample App"
    def build(self):
        self.get_application_config()
        return Button(text="hello world")
 
if __name__=="__main__":
    MyApp().run()

<script src="https://gist.github.com/hiroman098/95096dce91053f16194c.js"></script>

**Comment by ksmola** [comment]
I am experiencing the same issue on my udoo quad running kivy. anyone solved it yet?

**Comment by hiroman098** [comment]
Unfortunately nobody can still solve this problem.
I switched from Linaro to Android.　However, HW acceleration does not become effective.......
