### ISSUE TITLE
Trouble getting Gstreamer 1.0 to work properly on OSX 10.9.4 with MacPorts

### ISSUE THREAD

**Issue by SenshiSentou** [kivy/kivy#2448]
Hello!

I [posted about this issue earlier](https://groups.google.com/forum/embed/?place=forum/kivy-users&hidesubject=true&hideforumtitle=true&showsearch=true&showpopout=true&parenturl=http%3A%2F%2Fkivy.org%2F%23#!topic/kivy-users/lXZmsi7TPEc), but the response was, well, non-existent. I'm guessing this is more of a support-thing rather than a bug report, but filing it here too, just in case!

**A synopsis of my situation:**
- I installed `pygobject3`, `gstreamer` and `gst-plugins-[base | good | bad | ugly]` using MacPorts
- I can `import gi` just fine from both a Python process, and a Kivy one
- I can even get `Gst.version()` from within my Kivy app
- My video provider keeps returning `null`

I found that if I uncommented line 210 in kivy/core/video/\__init\__.py (`video_providers += [('gi', 'video_gi', 'VideoGi')]`) I actually get `gstplayer` as my video provider; huzzah!

Then though, it starts complaining about a segfault in Resources/lib/gst-plugins/___so. Removing that file (as suggested by the error message) just shifts the error to the next one, so I just emptied the entire folder. \0/

Ok, so now the app starts, and we don't get any errors (just a few warnings RE SDL_xxx classes being implemented in both Kivy's and SDL's `libSDL-1.2.0.dylib`). However, my video files still don't load. I've tried binding my test callback to both `loaded` and `on_load`, but no dice. Does anyone have any ideas on how to proceed? Video support is rather crucial in this specific app, so it would be great to see this resolved. =)

Thanks,
Patrick

**Comment by tito** [comment]
Hi @SenshiSentou, i didn't forget you. This month, i worked on a new packaging approach and tools that resolve this.

A new tool, extracted from the build toolchain of gstreamer and repackaged for standalone execution have been pushed: osxrelocator. Have a look at: https://pypi.python.org/pypi/osxrelocator

Second, i tried a complete new approach for the OSX packaging. There is various issue with GStreamer, and mostly pyinstaller after. My goal was to think more as an SDK: you have a Kivy.app on which you can try your software, or use it as a base to make your own app. Then the repo https://github.com/kivy/kivy-osx is born. Internally, it uses official packages for SDL2/_image/_ttf and GStreamer. The end package is bigger, but work and should be more sandboxed. (ie, no mess with the System).

I shared the concept and preliminary packages with the teams, seems to works, but not on all osx version. Contact me directly by email if you wanna test too.

**Comment by tito** [comment]
More info at https://groups.google.com/forum/#!topic/kivy-dev/rRLeWgLa0LY

**Comment by tito** [comment]
This is fixed with the new kivy/kivy-osx packaging tools. Next packaged version will contain the fixes :)
