### ISSUE TITLE
installing kivy on raspberry pi with python 3

### ISSUE THREAD

**Issue by StefJar** [kivy/kivy#2449]
As the title said, I tried to install kivy on a RPi and run it under python3. This leads to this error:

pi@raspberrypi ~ $ python3
Python 3.2.3 (default, Mar  1 2013, 11:53:50) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import kivy.app
> > > [INFO   ] Kivy v1.8.0
> > > [WARNING] [Config      ] Older configuration version detected (0 instead of 10)
> > > [WARNING] [Config      ] Upgrading configuration in progress.
> > > [INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_14-06-21_0.txt
> > > [INFO   ] [Factory     ] 157 symbols loaded
> > > [DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
> > >  Traceback (most recent call last):
> > >    File "<stdin>", line 1, in <module>
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/app.py", line 321, in <module>
> > >      from kivy.base import runTouchApp, stopTouchApp
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/base.py", line 30, in <module>
> > >      from kivy.lang import Builder
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 1814, in <module>
> > >      Builder.load_file(join(kivy_data_dir, 'style.kv'), rulesonly=True)
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 1444, in load_file
> > >      return self.load_string(data, **kwargs)
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 1491, in load_string
> > >      parser = Parser(content=string, filename=fn)
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 1049, in **init**
> > >      self.parse(content)
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 1126, in parse
> > >      rule.precompile()
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 917, in precompile
> > >      x.precompile()
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 917, in precompile
> > >      x.precompile()
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 913, in precompile
> > >      x.precompile()
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/lang.py", line 843, in precompile
> > >      self.co_value = compile(value, self.ctx.filename or '<string>', mode)
> > >    File "/usr/local/lib/python3.2/dist-packages/kivy/data/style.kv", line 715
> > >      u'{0}\n[size=13sp][color=999999]{1}[/color][/size]'.format(root.title or '', root.desc or '')
> > >                                                        ^
> > >  SyntaxError: invalid syntax

My installing procedure is:
sudo apt-get update
sudo apt-get install python3 python3-pip python3-numpy pkg-config libgl1-mesa-dev libgles2-mesa-dev git-core libgstreamer1.0-dev gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-{omx,alsa} libsdl-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libportmidi-dev libavformat-dev libswscale-dev freetds-dev

sudo apt-get remove task-desktop wolfram-engine 

sudo pip-3.2 -v install pysdl2 --upgrade
sudo pip-3.2 -v install pymssql --upgrade
sudo pip-3.2 -v install pygame --upgrade
sudo pip-3.2 -v install cython --upgrade
sudo pip-3.2 -v install kivy --upgrade

Any ideas?

**Comment by Tomazh** [comment]
I have a RPi with python 3.4, is it possible to install kivy for python 3? If yes, how? I tried using the https://kivy.org/docs/installation/installation-rpi.html guide, but thats just for python 2...

**Comment by MikaTml** [comment]
I have also struggled with python 3.5 and kivy for RPi. With python2 it works, but with python3, from kivy.app import App gives ImportError: undefined symbol: _Py_ZeroStruct. It would be nice if installation guide were updatet to support pyhthon 3.
