### ISSUE TITLE
Animation and weak references

### ISSUE THREAD

**Issue by cropleyb** [kivy/kivy#2458]
I was having a bit of an issue with Animations and weak references. I couldn't just put "try: ... except: ReferenceError" around my code because the weak reference issues were being triggered by Kivy animation code. I could change the lifespan of the widgets involved, but I have currently just put the try: except ReferenceError: in the animation class. Should this be put into the core?

In kivy/animation.py:

``` python
 def _update(self, dt):
      ... 
           try:
                # apply progression on widget
                for key, values in anim['properties'].items():
                    a, b = values
                    value = calculate(a, b, t)
                    setattr(widget, key, value)

                self.dispatch('on_progress', widget, progress)

                # time to stop ?
                if progress >= 1.:
                    self.stop(widget)

            except ReferenceError:
                # TODO: Log
                continue
```

**Comment by Fak3** [comment]
Encountered this in kivy 2.3. Trying to reliably reproduce
