### ISSUE TITLE
kivy problems with pygame on RPi (python 2.7)

### ISSUE THREAD

**Issue by StefJar** [kivy/kivy#2459]
Hi

I tried the installation of kivy on RPi after the info given here:

http://kivy.org/docs/installation/installation-rpi.html#manual-installation

1.) the "python-dev" package is missing. It is need for the compilation of cython

2.) When running a python script with kivy, which is creating a window following error ouccurs:

[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_14-06-20_2.txt
[INFO   ] Kivy v1.8.1-dev
[INFO   ] [Python      ] v2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
[INFO   ] [Factory     ] 169 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_ffpyplayer, img_pil ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[ERROR  ] [Window      ] Unable to use pygame
[ERROR  ] [Window      ] The module raised an important error: 'Unable to open a console terminal'

Maybe the information at kivy.org is outdated. There are videos at youtube showing, that kivy is running on a raspberry pi (http://youtu.be/x44BaZLfEKE). Any ideas?
##

**Comment by dessant** [comment]
Please reopen if the bug is still present in kivy master.
