### ISSUE TITLE
Vsync doesn't work

### ISSUE THREAD

**Issue by hansent** [kivy/kivy#246]
osx dont have a control to enable system wide vsync, so it must be done by application.  SDL/pygame on OSX have a bug and vsync will not be enabled, even when using using double buffer.  All in all, pretty bad tearing on moving/animations.

I've found a snippet, which is supposed to enable vsync, using CGL (Core OpenGL Apple lib), but it causes a pygame segfaults no matter where I try to call it.

these kind of gl functions (and getCurrentContext etc.) will likely be in system gl extension libs like CGL/AGL etc, not sure whats best way to be able to use these features in kivy.

snippet from http://www.idevgames.com/forums/thread-2974.html:

``` python
import sys

def enable_vsync():
    if sys.platform != 'darwin':
        return
    try:
        import ctypes
        import ctypes.util
        ogl = ctypes.cdll.LoadLibrary(ctypes.util.find_library("OpenGL"))
        # set v to 1 to enable vsync, 0 to disable vsync
        v = ctypes.c_int(1)
        ogl.CGLSetParameter(ogl.CGLGetCurrentContext(), ctypes.c_int(222), ctypes.pointer(v))
    except:
        print "Unable to set vsync mode, using driver defaults"
```
##

**Comment by dessant** [comment]
https://wiki.libsdl.org/SDL_RendererFlags?highlight=%28vsync%29
https://wiki.libsdl.org/SDL_GL_SetSwapInterval?highlight=%28vsync%29

**Comment by Julian-O** [comment]
@matham: This looks like it was fixed in 2017 commits you were involved with, but you removed it as a milestone.

Any reason why this can't be closed as completed?

**Comment by Julian-O** [comment]
Closing as presumed fixed.
