### ISSUE TITLE
Audio Streaming on Andriod

### ISSUE THREAD

**Issue by mohammadhzp** [kivy/kivy#2462]
Hello
Kivy is doing great but for just one reason I can not use it for my project
Kivy uses pygame in android as its audio provider and pygame can not handle audio streaming like mp3
for more details you can <a href="http://stackoverflow.com/questions/25795396/audiomp3-steaming-in-android-and-ios-using-kivy/25797795#25797795">this</a> too.
So here the request is if possible , please add this functionality to kivy,mean while I'll be glad if someone guide me to get streaming working in andriod using kivy,perhaps using some other SDKs like vitamio will help but I don't know if kivy can use it,some tips please
Thank you

**Comment by lanmasterlan** [comment]
I have the same issue with video files. Softboy.mpg works if included. Once it is located on a server it only works on the desktop but not on android.

**Comment by akshayaurora** [comment]
video is a different issue than audio, you need to include ffmpeg with your
distribution for video playback, for streaming videos you will need to
compile the support for playing streams into the ffmpeg being included.

**Comment by lanmasterlan** [comment]
Thanks a lot for your help. I have ffmpeg included but it is not working on android.
I read on an outdated post that video streaming is only supported on Desktops as gstreamer is used but not on mobile platforms.
https://groups.google.com/forum/#!topic/kivy-users/fR06Zd-gLgw

I would be happy if someone could confirm this, or briefly explain how network video(/audio) streaming can be used on android.

**Comment by mohammadhzp** [comment]
I couldn't find a solution for even audio streaming and I STILL need this functionality

@akshayaurora Do you have  solution for Audio streaming only?

**Comment by mohammadhzp** [comment]
@tito Can we use other SDKs in kivy the same way you used Facebook SDK in [this](http://txzone.net/2013/08/using-facebook-sdk-with-python-for-android-kivy/) blog post ?

**Comment by SpencerWilliams** [comment]
I'm working on an app with internet audio streaming being a goal. If anyone figures this out, post it so others can see your solution!

**Comment by sichuyoudang** [comment]
me too   ,,I  make apk  player video , use gstreamer  on ubunto is ok  ,but on android  not work

**Comment by Aaliq** [comment]
> kivy.core.audio can not even load stream in Desktops I tried both kivy.uix.video and kivy.uix.videoplayer, these two widgets working on desktops,but not android ! I build the package using buildozer and this is How I gave perm android.permissions = INTERNET (I think it's default) But Not working ! Here is a working example code for desktop which does not work on android even with perm
> 
> ```python
> from kivy.app import App
> from kivy.uix.video import Video
> 
> class PamaApp(App):
> 
>     def build(self):
>         player = Video(source='http://194.106.198.57:8090/rock_low.mp3', state='play', options={'eos': 'loop'})
>         player.volume = 1
>         return player
> 
> 
> PamaApp().run()
> ```
> 
> What I do wrong ? Am I missing something ?

Did you get any solution for this?
I am actually new to kivy, I want to stream audio from spotify api to my kivy app. Is that even possible?
