### ISSUE TITLE
Supraposed transparent pngs do not display correctly on osx

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2477]
Reproduced on Mavericks 10.9.2, the left image is osx, the right one is windows.

![n9mtlf9](https://cloud.githubusercontent.com/assets/7513068/4326226/224c8286-3f6d-11e4-8cf9-48e92c562210.png)

``` python
from kivy.app import App
from kivy.uix.image import AsyncImage
from kivy.core.window import Window
from kivy.uix.floatlayout import FloatLayout

Window.clearcolor = (1, 1, 1, 1)


class MyApp(App):

    def build(self):
        layout = FloatLayout()
        layout.add_widget(AsyncImage(source="http://i.imgur.com/k2uWBqJ.png"))
        layout.add_widget(AsyncImage(source="http://i.imgur.com/NgOM9Eh.png"))
        return layout

if __name__ == '__main__':
    MyApp().run()

```
##

**Comment by Alamot** [comment]
I confirm this in Mac OS Yosemite 10.10.5. Supraposed transparent pngs look differently compared with Windows or Android platforms.

**Comment by dessant** [comment]
Tracking at https://github.com/kivy/kivy/issues/2182.

**Comment by 700brains** [comment]
WHEN TRYING TO CLONE python-for-android it gives these error
# Install platform
# Run 'git clone -b old_toolchain --single-branch
https://github.com/kivy/python-for-android.git python-for-android'
# Cwd /home/pyguy/kivyinstall/kivyapp/.buildozer/android/platform
Cloning into 'python-for-android'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull
function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
# Command failed: git clone -b old_toolchain --single-branch
https://github.com/kivy/python-for-android.git python-for-android
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
