### ISSUE TITLE
importing httplib2

### ISSUE THREAD

**Issue by pttp** [kivy/kivy#2499]
Hi,

I've been "playing" around with kivy for some days and found that I could not use any library that depends on httplib2 because building iri2uri.py fails.

iri2uri contains some unicode strings with special characters (   \N{....}  ). These get interpreted as not supported line endings.
I am not yet sure what exactly fails (guessing it's cython or pyjnius), I will have a look into that as soon as I have the timet.

many libraries for JSON-APIs use httplib2 and thus are not usable with kivy. At least for what I saw until now.
I was using the provided virtualbox kivy image, which btw is outdated since at least this summer. apt-get update fails on missing servers, because ubuntu 12.10 support has been turned down and the user needs to replace source-urls with links to their archives.

So the question is, is this issue already known, and maybe even solved in current kivy (and dependencies) and just an issue with the outdated virtualbox image or should someone look into that and find a fix?
I think httplib2 is important because it's used by quite some other libraries and kivy builds should not fail on this.

Regards!

**Comment by dessant** [comment]
Please reopen for https://github.com/kivy/python-for-android if the issue is on this side.

**Comment by saundc2** [comment]
I am having a similar problem as stated above. My app runs fine from eclipse, but when I push it to my android device the app crashes with the error "ImportError: No module named httplib2"
I tried replacing /usr/local/lib/python2.7/dist-packages/httplib2/__init__.py with the file on github(https://gist.github.com/Kovak/d5624ec181dbd10b43b5) but it did not resolve my issue. Is there something else I should be looking for? Should I be able to see httplib2.py buried in my .buildozer folder?
