### ISSUE TITLE
window_sdl2.screenshot uses pygame

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2514]
https://github.com/kivy/kivy/blob/master/kivy/core/window/window_sdl2.py#L147

**Comment by akshayaurora** [comment]
I can't reproduce the issue using sdl2 from mercurial on a mac or a window machine.

**Comment by tito** [comment]
same for me, not reproducable on my osx / linux / windows.

**Comment by tito** [comment]
Closing, unless we have a way to reproduce.
