### ISSUE TITLE
Window controls inoperable with Wacom tablet.

### ISSUE THREAD

**Issue by trin5tensa** [kivy/kivy#2535]
I am a new kivy user and I am working my way through the pong and paint examples on my Windows 7 machine. Everything is working perfectly with regular mouse and keyboard input.

I also use a Wacom Intuos 4 tablet (model PTK-640). This also works perfectly as far as the window contents are concerned. The pen can paint and pong as easily as any other input device. However, the window controls are inoperable. This includes minimising, maximising, closing, and resizing by edge dragging. 

The only error that appears in the [kivy log](https://gist.github.com/688d98cb11d411ea6fa6) is an import error related to 'egl_rpi' which appears to be part of the pygame package. 

These previous issues from 2012 may be related. Both explicitly mention 'the cursor going crazy in the kivy window'. That is not happening in my case.
[#493 kivy-1.2.0-146-g4b84ca0 fail to build](https://github.com/kivy/kivy/issues/493)
[#500 Can NOT work with WACOM tablets on windows](https://github.com/kivy/kivy/issues/500)
##

**Comment by ChristianTremblay** [comment]
I confirm same bug using Wacom Bamboo tablet
Kivy 1.9.1

**Comment by trin5tensa** [comment]
It needs some activity — like fixing it maybe?

**Comment by Julian-O** [comment]
egl_rpl is deprecated and being removed (#8434) so this will not be fixed now.
