### ISSUE TITLE
binding problem with self.width when inside a GridLayout

### ISSUE THREAD

**Issue by bj0** [kivy/kivy#2538]
If I put a button in a GridLayout with:

```
Button:
    size_hint: 1, None
    height: .5*self.width
```

There is no binding with width (the height does not update when the window is resized).  But if I use self.size[0], than the binding works.  The code I used to test is below:

```
import kivy
kivy.require('1.8.0')

from kivy.app import App
from kivy.lang import Builder

root = Builder.load_string('''
<Button>:
    text: 'hi'
    size_hint_y: None
# works
    height: .5*self.size[0]
# does not work
#    height: .5*self.width

GridLayout:
    cols: 2
    spacing: 5

    Button:
    Button:
''')

class TestApp(App):
    def build(self):
        return root

if __name__ == '__main__':
    TestApp().run()
```
##

**Comment by KeyWeeUsr** [comment]
Can't reproduce. `height: 0.5 * self.width` with resizing works just fine, however with `self.size[0]` I get too many iterations for `Clock`.
