### ISSUE TITLE
Kivy Launcher not recognizing app on android

### ISSUE THREAD

**Issue by IgorGanapolsky** [kivy/kivy#256]
Hello, I unzipped the KivyTest for Android project (http://kivy.googlecode.com/files/kivytest-for-android.zip) to my sdcard.  However, Kivy Launcher says "no projects are available to launch".  The directory on my Droid I am talking about is /mnt/sdcard/kivy.  Has anybody seen this issue before?

**Comment by erm3nda** [comment]
Not advised in the Launcher, but described in the docs (https://kivy.org/doc/stable/guide/packaging-android.html), you have to supply an `android.txt` file with minimal info to let Launcher to know about your app before launch it.

Example:
```
title=Example
author=Kivy
orientation=portrait
```

**Comment by makan-dianka** [comment]
> translating tito's answer to English:
> each project's folder should be in "/kivy/", and not in another directory. e.g.:
> 
> /sdcard/kivy/myproj/* <--- works
> /sdcard/kivy/some-dir/myproj/* <--- doesn't work

It works for me :  > /sdcard/kivy/myproj/* <--- works
