### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by natewlew** [kivy/kivy#2560]
When I run clear_widgets() to clear child widgets, they are not being released from memory. Every time I add and remove the widgets it gains about 70mb.

Example Code to add and remove widgets:
``` python
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.app import App
from kivy.lang import Builder

Builder.load_string('''
<MainBox>:
    orientation: 'vertical'
    FloatLayout:
        id: container
    BoxLayout:
        size_hint_y: None
        height: 100
        orientation: 'horizontal'
        Button:
            text: 'add'
            on_press: root.add()
        Button:
            text: 'remove'
            on_press: root.remove()
''')

class MainBox(BoxLayout):

    def add(self):
        for _ in range(1000): self.ids.container.add_widget(Button())

    def remove(self, *args):
        self.ids.container.clear_widgets()

class DemoApp(App):
    def build(self):
        return MainBox()

if __name__ == '__main__':
    DemoApp().run()
```

It seems to have started here: https://github.com/kivy/kivy/commit/acbba046110272f5dc8dc679a4a207abce51d477. The problem goes away if I rollback the the previous commit: https://github.com/kivy/kivy/commit/c448f7fe007e4009c3a5f81ce362b29495f340b6

**Comment by pedrotst** [comment]
[INFO              ] [Kivy        ] v1.9.0-dev
[INFO              ] [Python      ] v3.4.0 (default, Apr 11 2014, 13:05:11) 
And I'm having this bug, please check.

**Comment by matham** [comment]
It seems unlikely that it's this bug because we don't do any manual memory management stuff anymore. So I'm closing for now until. Please reopen with a the code you ran and the output showing the bug.
