### ISSUE TITLE
Fullscreen configuration disables FileChooser

### ISSUE THREAD

**Issue by jilp-cog** [kivy/kivy#2563]
Hello,
(This is the first time I report an issue, I hope this is the right place).

Adding a "FileChooserIconView" widget results in a black screen when "Config" is set to fullscreen (auto).

```
import kivy
kivy.require('1.8.0')

from kivy.config import Config
Config.set('graphics', 'fullscreen', 'auto')

from kivy.app import App
from kivy.uix.filechooser import FileChooserIconView

class My_app(App):
    def build(self):
        filechooser = FileChooserIconView()
        return filechooser

if __name__ == '__main__':
    My_app().run()
```

If I remove the Config.set line, the display works normally.
When the Config.set is there, only the blue charging bar appears for a short moment and then disappears. There is then only a black screen.

Tried on a Windows 8.1 with Kivy 1.8.0 for Python 3.3.

Thank you,

Jean-Luc
##

**Comment by KeyWeeUsr** [comment]
Windows 8.1, master, 3.5. Works fine in both fullscreen and normal.

**Comment by Julian-O** [comment]
Windows 11, Kivy 2.2.1. Works in fullscreen (didn't try normal).

Closing as Cant Repro. If you are still having this problem, please let us know your configuration and provide logs.
