### ISSUE TITLE
When rendering some SVG files, kivy crashes with a TypeError (index must be an integer) on svg.pyx L699

### ISSUE THREAD

**Issue by sbrother** [kivy/kivy#2574]
Issue can be seen by importing the file http://upload.wikimedia.org/wikipedia/commons/f/f1/Learning-lilypond-polyphony-example.svg

This issue can be resolved by replacing `float(e['x1'])` (and the next three similar lines) with `float(e.get('x1'))`. I didn't make a PR because I thought this might be a symptom of a larger underlying issue, and I don't know enough about how svg.pyx works to fix it.

**Comment by abhigenie92** [comment]
@sbrother  Were you able to get this to work?

**Comment by sbrother** [comment]
Hey @abhigenie92, I did; I actually have my own fork of `svg.pyx` that I use for my app. It fixes this bug, and also adds a parameter for adjustable line width. Happy to send a PR, but no one's addressed this comment in the two years it's been open so I assumed Kivy's experimental SVG parser was pretty much dead.

That being said, the app I'm working on heavily relies on this code, and I'm happy to help you if you're having issues with it!

**Comment by abhigenie92** [comment]
@sbrother  Hi, thanks for reply! The issue I am facing is here: https://github.com/kivy/kivy/issues/4285. If possible you create a PR or suggest edits. 
I went through the code of `syg.pyx`, maybe they have changed it already(https://github.com/kivy/kivy/blob/master/kivy/graphics/svg.pyx#L562)

**Comment by sbrother** [comment]
Hah, it looks like actually I fixed the issue: https://github.com/kivy/kivy/commit/850e86a408c05efadbdef022beac73f8ae4dbaae

So I think we can close this issue, but it won't solve #4285. I have some thoughts on that bug, but I'll add them over there. Closing this since I fixed it almost two years ago (oops).
