### ISSUE TITLE
[UrlRequest]  ':' inside Url will cause invalid literal error when it isn't marking the port number

### ISSUE THREAD

**Issue by AndyMN** [kivy/kivy#2575]
If you have a Url like this:

url =" https://myAppID:javascript-key=myJavaScriptKey@api.parse.com/1/classes/Door"

Urlrequest will cast following error:

invalid literal for int() with base 10: "javascript-key=myJavaScriptKey@api.parse.com"

This makes it so a lot of REST APIs can't be called from kivy not just from the parse.com site

This is caused because Urlrequest will see the ':' and will expect a port number. 

See lines 242-247 in Urlrequest:

 # correctly determine host/port
        port = None
        host = parse.netloc.split(':')
        if len(host) > 1:
            port = int(host[1])
        host = host[0]
##

**Comment by KeyWeeUsr** [comment]
Tested with:

```python
from kivy.app import App
from kivy.lang import Builder


kv = """
AnchorLayout:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    AsyncImage:
        size_hint: None, None
        size: dp(56), dp(56)
        # http://duckduckgo.com
        source: 'http://54.229.105.92:80/assets/icons/meta/DDG-icon_256x256.png'
        anim_delay: 0.0333333333333333
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

**Comment by hackalog** [comment]
Confused by this. How does that testcase catch the indicated error?

**Comment by KeyWeeUsr** [comment]
@hackalog Ah, I've misread the issue! Thanks. I thought the problem was in `<url>:<port>`, yet apparently it's `<url>:` what was desired. I'll try to look into it.
