### ISSUE TITLE
[Feature] SetProperty

### ISSUE THREAD

**Issue by geeklint** [kivy/kivy#2585]
It's not as common as the current property types but there are use cases for a `SetProperty` (python `set()` type). Right now the same behavior can be achieved with a `DictProperty` but I assume there's a memory overhead associated with using `dict` over `set`. This would probably involve the creation of an `ObservableSet` type as well as the `SetProperty`, but should be straightforward. 
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
