### ISSUE TITLE
[Feature]: reading out severall TextInputs from kv as a list

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#2600]
Hi all,

II made a formular in kv (screenshot in attachment), and I would like to read out the input data as lists. 
On the screenshot: the Textinputs within the same borders should be in the same list. 
![unbenannt](https://cloud.githubusercontent.com/assets/1676457/4714850/7a32f9aa-58f7-11e4-9e04-10563e25e2b8.png)

I would like to have something similar:

kv:
TextInput:
    id: myList[0]
TextInput:
    id: myList[1]
TextInput:
    id: myList[2]

py:
self.ids.myList
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
