### ISSUE TITLE
SDL2 - window border still visible after removing window decorations

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2616]
![untitled](https://cloud.githubusercontent.com/assets/7513068/4766481/2cd7fbc2-5b51-11e4-8df3-3c2ddcf837a1.jpg)
```python
import os
os.environ['KIVY_WINDOW'] = 'sdl2'

from kivy.config import Config
Config.set('graphics', 'width', 300)
Config.set('graphics', 'height', 300)
Config.set('graphics', 'borderless', 'True')

from kivy.app import App
from kivy.uix.button import Button


class MyApp(App):

    def build(self):
        return Button(text='Test')

if __name__ == '__main__':
    MyApp().run()

```

**Comment by martinsik** [comment]
I think this doesn't apply to OS X 10.10.3 any more. Tested on Kivy 1.9.0.
![screen shot 2015-05-20 at 10 58 45](https://cloud.githubusercontent.com/assets/238765/7722329/597c01a0-fedf-11e4-9383-bf14ff77fb8e.png)

**Comment by welnaseth** [comment]
Any progress on this issue for Windows Platforms? I'm getting the same behavior as @dessant on Windows 7 64-bit using Kivy 1.9.1

**Comment by dessant** [comment]
@welnaseth, it seems to be an upstream issue, you could check if it has been reported for sdl2, or open an issue there.

Please link any info you get from the sdl2 devs.

**Comment by dessant** [comment]
Yay, if you want to also hide the resizing handle, you have to disable resizing. This should be documented.
This should give you no borders at all:

```python
from kivy.config import Config
Config.set('graphics', 'width', 300)
Config.set('graphics', 'height', 300)
Config.set('graphics', 'resizable', 'False')
Config.set('graphics', 'borderless', 'True')

from kivy.app import App
from kivy.uix.button import Button


class MyApp(App):

    def build(self):
        return Button(text='Test')

if __name__ == '__main__':
    MyApp().run()
```

<sub>solution by kived<sub>

**Comment by kived** [comment]
Oh, nice. Put me in the fine print. :P

**Comment by dessant** [comment]
:grin:
