### ISSUE TITLE
Callback instruction not available from within KV language

### ISSUE THREAD

**Issue by SenshiSentou** [kivy/kivy#2636]
For a specific Widget I need to change the blending function multiple times within the same pass. The docs mention the `Callback` object for this, and examples I found use it as such:

```
def __init__(...):
    with self.canvas.before:
        Callback(self.set_blend_func)

def set_blend_func(*args):
    glBlendFunc(gl.GL_SRC_ALPHA, gl.GL_DST_COLOR)`
```

However, this doesn't provide any control over when to switch within the canvas.before block.

Is there any way we can use the Callback instruction in our .kv files, like so for instance?

```
<MyWidget>:
    Rectangle:
        [...]
    Callback:
        call: self.set_blend_func()
    Rectangle:
        [...]
    Callback:
        call: self.set_other_blend_func()
    Rectangle:
        [...]
```

Thanks,
Patrick
##

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/5878
