### ISSUE TITLE
kivy env script for windows does not like space in BASH_SOURCE

### ISSUE THREAD

**Issue by allan-simon** [kivy/kivy#2671]
(very sorry I don't have the machine that produced the error message on me right now)

basically I have a user named "Foo Bar"   and I launch git bash from the desktop folder of that user
then the kivyenv.sh script will fail with a "dirname : too much parameter"  error 

which i guess is because the variable is not put between quote

**Comment by dessant** [comment]
We've transitioned to wheels.
