### ISSUE TITLE
Scale() should have an origin property

### ISSUE THREAD

**Issue by sbrother** [kivy/kivy#2693]
Rotate() now supports an origin property, allowing rotations around an arbitrary origin. Scale does not, only supporting scaling around the lower left of the canvas. This means that to achieve control over scaling a widget, you need to wrap Scale in two Translate commands. It would be nice if Scale also had an origin property to avoid this.

**Comment by rastogiachyut** [comment]
Working on this one now.

**Comment by rastogiachyut** [comment]
Really working on it now.

**Comment by rastogiachyut** [comment]
Stuck.I am adding origin property to scale exactly like it was done in rotate, it still does not work.
This( https://gist.github.com/rastogiachyut/afc7dd9d0526ac3c894f ) code does not work, this is my Scale class in context_instruction.pyx file( https://gist.github.com/rastogiachyut/1c82e1c9d23b3c11ef11 ) ,Why? Ive hit a dead end. Probably I am doing something stupid.

**Comment by hey-sancho** [comment]
Here's my try at fixing this:
https://gist.github.com/hey-sancho/b131a6d02d9f15838beb

Tried to do the same way as in `Rotate` - everything uses `compute()` function, which translates and scales the object. Rewritten `set_scale()` to work via `compute()`, but i guess it could become deprecated as the `Rotate.set`.

@rastogiachyut, I don't know what result did you get, but my version makes your code look like this:
![screenshot - 26 02 15 - 18 27 31](https://cloud.githubusercontent.com/assets/1079585/6396144/7d6ba146-bde5-11e4-93f0-2f8a6b3c4958.png)

**Comment by rastogiachyut** [comment]
@hey-sancho 
Sorry for the late reply.
I submited a PR for this a while but it did not get pulled.
here -> https://github.com/kivy/kivy/pull/3070
your fix looks right too.

**Comment by rastogiachyut** [comment]
I don't know if your code works in all cases, mine does.
But yours looks better cause it makes a new function compute.
Well make a PR and let the devs decide.

**Comment by rastogiachyut** [comment]
made a clean new pull request https://github.com/kivy/kivy/pull/3134 
please pull if satisfactory.
