### ISSUE TITLE
Offset in Y coordinate with Windows 7 and Multitouch HID Device

### ISSUE THREAD

**Issue by VianneyZ** [kivy/kivy#2701]
Hi all,

It seems there is a bug with Windows 7 (not tested on others Windows) and Kivy about the Y position of the cursor. There is a constant offset between the Windows Cursor position and the one Kivy uses. (See attached pictures). Note that the offset is bigger in fullscreen that in windowed mode.

After having a quick look at the code, it seems that this offset is due to the caption size which is substracted to calculate the Y coordinate (line 165 in file wm_touch.py).

I can try to run additional tests if needed.

Regards.

Touchtracer in windowed mode:
![touchtracer_windowed](https://cloud.githubusercontent.com/assets/9927689/5162571/3f946b78-73c1-11e4-9a65-78d4a7eae11e.png)

Touchtracer in fullscreen mode:
![touchtracer_fullscreen](https://cloud.githubusercontent.com/assets/9927689/5162572/3f979cc6-73c1-11e4-9a9e-6f6c708f4e68.png)

**Comment by grmcom** [comment]
I am having the same issue on Windows 8.1 using an Acer t272hl touch monitor.
I also observed the issue on a windows 8 Dell Inspiron laptop with a touchscreen.
The offset is not present with the mouse.
Image of the lowest touch I can get on the acer touchscreen: 

![rbqmyii](https://cloud.githubusercontent.com/assets/329604/8749345/e5967184-2c98-11e5-8ed4-97750650039e.jpg)

**Comment by grmcom** [comment]
A workaround for this issue is to add the following to config.ini:
You might have to alter the ratio and offset for your screen.

[postproc:calibration]
wm_touch = yratio=1.04,yoffset=-0.027

**Comment by tshirtman** [comment]
A calibration trick won't cut it if you want to have a portable solution, i'm having a look in the same direction as @VianneyZ , but hitting the same error, which is weird, because both fonctions have the same signature according to MS doc (https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms633519(v=vs.85).aspx, https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms633503(v=vs.85).aspx) and both are declared the same way in the module. Digging.

**Comment by grmcom** [comment]
Hi tshirtman, if I make that change I get this error:

File "C:\Users\Kivy\Desktop\Programing\Python\Kivy\Kivy 1.9-32bit\kivy27\kivy\input\providers\
wm_touch.py", line 154, in update
     windll.user32.GetClientRect(self.hwnd, byref(win_rect))
 ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_RECT instance inste
ad of pointer to RECT

**Comment by tshirtman** [comment]
Yes, this is what i get as well, i'm trying to understand what makes one call work and not the other.

**Comment by tshirtman** [comment]
this is getting confusing, seems kivy is doing something that confuses ctypes, because with this test code, the first call doesn't crash (though hwnd is 0, which is weird), but the call when i push the button does.

```
from kivy.app import App
from kivy.uix.button import Button
from ctypes import windll, wintypes, byref


class Test(App):
	def build(self):
		return Button(on_press=self.cb)

	def cb(self, *args):
		windll.user32.GetClientRect(hwnd, byref(r))
		print r

hwnd = windll.user32.GetActiveWindow()
print hwnd
r = wintypes.RECT()
windll.user32.GetClientRect(hwnd, byref(r))
print r
Test().run()
```

**Comment by tshirtman** [comment]
PR up there only fixes the originaly reported issue, that is the constant offset in the whole window when the app is fullscreen, i don't currently have a way to reproduce non-constant and x offset issues, but i think the more general solution would be to use GetClientRect, if i could find why it doesn't work.

**Comment by VianneyZ** [comment]
@grmcom @tshirtman I remember having the same error (with GetClientRect) when I tried a few month ago to correct the error but as I have absolutely no knowledge of the kivy structure and I'm not a Python developper, It made it hard for me to solve the issue.
