### ISSUE TITLE
Document Kivy Launcher compilation

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2706]
I have not seen it anywhere, it would make sense to have it in a separate repo under this account.

**Comment by dessant** [comment]
@brousch do you have some progress on this?

**Comment by akshayaurora** [comment]
This needs to be opened as a issue for bulldozer.

**Comment by dessant** [comment]
Reopening this for now, i'm not sure if it should be a command or documentation, or where hould it be placed.

**Comment by KeyWeeUsr** [comment]
Docs are available. If a command is needed, a request should be opened probably in buildozer repo.
