### ISSUE TITLE
Rotation Screws Up Window Drawing Dimentions

### ISSUE THREAD

**Issue by dkotik** [kivy/kivy#2710]
1.8 used to rotate the screen correctly running android app when orientation is changed, 1.9 screen rotates as well, but more than half of the screen is not visible. Seems like the new screen width and height are not properly updated. Any suggestions on how to patch this?

I looked over the code, but I am not familiar enough with pygame API to detect what causes the glitch. I have a guess, however: 1.9 adds automatic screen resizing for soft input - may be that's causing the glitch?

Qua Non >> Dima this is a known bug that very recently creeped in. Could you open a issue. at github.com/kivy/kivy/issues If you can look into what's causing the issue then that's welcome too.  I'd look into kivy.core.window.window_pygame.py look into git bisecting which commit broke it and push a pr accordingly.

**Comment by seblaz** [comment]
Hello, I'm still facing the same problem. When the screen rotates in android the widgets are not updated. If I manually update any widget, then all widgets get updated correctly.
