### ISSUE TITLE
Application.user_data_dir on android shouldn't be hardcoded

### ISSUE THREAD

**Issue by eviltnan** [kivy/kivy#2712]
Currently Application.user_data_dir on android returns `/sdcard/<app_name>`, which is not always correct for extrernal storage.

Supposedly it should return the result of 

```
Environment.getExternalStorageDirectory().getAbsolutePath();
```
as mentioned in http://stackoverflow.com/questions/3853472/creating-a-directory-in-sdcard-fails.

**Comment by dessant** [comment]
Duplicate of https://github.com/kivy/kivy/issues/2990.
