### ISSUE TITLE
Kivy not defined / no module named Kivy Mac OS x 10.10.1 Yosemite

### ISSUE THREAD

**Issue by jkeown** [kivy/kivy#2721]
Followed the install instructions exactly.  Everything seemed fine; no install errors.

Tried to Create an application tutorial but right off the bat I cannot access/import Kivy.
I have tried via the terminal, python idle, and also the Kivy icon in applications folder to no avail.

Not sure what else to try. I have even reinstalled but no change

**Comment by jdmartens** [comment]
I was able to get this working on 10.10.2 OSX with creating a 'symlink' to the Resources/script file manually:

ln -s /Applications/Kivy.app/Contents/Resources/script /usr/local/bin/kivy

**Comment by udaykiran28** [comment]
Hi,
I was experiencing the similar problem while following the installation, in the documentation from Kivy website. I was struck when I was trying to activate the symlinks, below is what I have tried. 

My-iMac:Applications udaykiran28$ ln -s /Applications/Kivy.app/Contents/Resources/script /usr/local/bin/kivy
ln: /usr/local/bin/kivy: Permission denied
My-iMac:Applications udaykiran28$ sudo chown -R $(udaykiran28) /usr/local
-bash: udaykiran28: command not found
Password:
usage: chown [-fhv] [-R [-H | -L | -P]] owner[:group] file ...
       chown [-fhv] [-R [-H | -L | -P]] :group file ...
My-iMac:Applications udaykiran28$ kivy
-bash: kivy: command not found
My-iMac:Applications udaykiran28$ 

-----

After changing the ownership, I had tried to start Kivy from the terminal, but it says the "kivy:command not found". Need help regarding this. 

Thanks in advance. Uday Kiran

**Comment by jmrosal** [comment]
Which python version are you using? python 3.x? How about kivy? kivy3?

if so, you may try instead -s /Applications/Kivy3.app/Contents/Resources/script /usr/local/bin/kivy

best

**Comment by dyspop** [comment]
I'm a competent python developer and I'm experiencing the same issue. I do have some issues with PATHing on my system (should just wipe this bucket) so it's likely my fault. Anyway... followed instructions to the T:

Downloaded .dmg https://kivy.org/downloads/1.10.1/Kivy-1.10.1_osx10.13.5_packaged_python3.6.5_r1.dmg

double-clicked .dmg
Moved kivy.app to Applications/ by drag and drop
double-clicked MakeSymlinks (script ran):
```
$/Volumes/Kivy3/MakeSymlinks ; exit;
ln: /usr/local/bin/kivy3: File exists
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```
```
$kivy
-bash: kivy: command not found
```

tried `ln -s /Applications/Kivy.app/Contents/Resources/script /usr/local/bin/kivy` etc to no avail

**Comment by akshayaurora** [comment]
does the file /usr/local/bin/kivy exist ? is that path in your PATH? type
$PATH to check.

**Comment by alexjpanagis** [comment]
> @jkeown Please use the mailing list for the discussion :)

Where can I join the mailing list? I'm having the same issue. Since installing Kivy3, I wasn't able to run python programs using the kivy command in terminal.

**Comment by alexjpanagis** [comment]
> -s /Applications/Kivy3.app/Contents/Resources/script /usr/local/bin/kivy

What does this command do?

**Comment by noncup** [comment]
Also having some issues understanding Kivy installation. The instructions say to type $kivy for the command in terminal but $kivy3 your_file.py seems to work.

**Comment by Chadys** [comment]
Same here, spent some time realising that the command was kivy3 and not kivy, you should really update the documentation.

**Comment by EpiVivico** [comment]
> Which python version are you using? python 3.x? How about kivy? kivy3?
> 
> if so, you may try instead -s /Applications/Kivy3.app/Contents/Resources/script /usr/local/bin/kivy
> 
> best

this command works for me, the symlinks and commands they are giving aren't working
