### ISSUE TITLE
"on_focus" vs "on_focused" in kivy/uix/textinput.py

### ISSUE THREAD

**Issue by erccarls** [kivy/kivy#2725]
Hopefully I am not misinterpreting the code, but the method in (current master branch) textinput.py is "on_focused" whereas the docs specify on_focus.  Should be made consistent.

**Comment by matham** [comment]
The docs have been fixed. But to clearify, `focused` is the better attr to use. However, `focus` still remains a valid attr. `focus` and `focused` are now interchangeable.
