### ISSUE TITLE
Framerate drop when playing audio on 2D game (Windows, kivy 1.8.0)

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2728]
I am writing a kivy game for Ludum Dare. My biggest problem was the SoundLoader class, which in my opinion is a strange way to handle things. Effectively, the SoundLoader will choose the first class able to handle the given file format.

It seems there are issues with Gstreamer 1.0, kivy and Windows. My fix was to disregard the "recommended" method for loading sounds, and invoke the SoundPygame constructor directly.
Now instead of my fps dropping from 80 down to 6, all sounds play at 80 fps.

I hope it helps someone,

Regards

**Comment by danahinds57** [comment]
@victor-rene I had this problem too, thanks very much for posting your solution it saved me quite a bit of time.

**Comment by victor-rene** [comment]
I am closing this issue with a workaround. On Windows to avoid the bad performance of gstplayer on sound effects while also playing music (sdl2 provider doesn't really like mp3 ro ogg files), you want to:

    from kivy.core.audio import SoundLoader
    from kivy.core.audio.audio_sdl2 import SoundSDL2

    sounds = {
        'levelup': SoundSDL2(source='sfx/levelup.wav'),
        'powerup': SoundSDL2(source='sfx/levelup.wav'),
        'hit': SoundSDL2(source='sfx/hit.wav'),
        'gameover': SoundSDL2(source='sfx/gameover.wav'),
        'music': SoundLoader.load('sfx/acidamine.ogg'), # can be mp3 as well
    }

    sounds['music'].play()
    sounds['levelup'].play()

It's a bit tricky since the syntax is different. With SoundSDL2 (inherits from Sound class), you don't want to use load() method. Whereas that's what you do with the SoundLoader class. Anyways it works.
