### ISSUE TITLE
buildozer can't download python libs due to ssl certificate check fail

### ISSUE THREAD

**Issue by 2traces** [kivy/kivy#2731]
When I try to build a project for android it shows me an error:

Modules changed to hostpython python sdl pygame pyjnius android kivy
Pure-Python modules changed to 
Run get packages
Download package for hostpython
Downloading http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
--2014-12-02 10:26:12--  http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
Resolving python.org (python.org)... 104.130.43.121, 2001:4802:7901::e60a:1375:0:5
Connecting to python.org (python.org)|104.130.43.121|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2 [following]
--2014-12-02 10:26:12--  https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
Connecting to python.org (python.org)|104.130.43.121|:443... connected.
ERROR: The certificate of ‘python.org’ is not trusted.
ERROR: The certificate of ‘python.org’ hasn't got a known issuer.
# Command failed: ./distribute.sh -m "kivy" -d "mymath"

I have upgraded pip to version 1.5.6 but the error is still the same. I've downgraded pip to 1.5.2 and it shows me the same error message

**Comment by thopiekar** [comment]
Why not skip root cert checking by default to make it failsave?

**Comment by dessant** [comment]
The issue is not there with an updated certificate chain.
