### ISSUE TITLE
Animation recursion depth exceeded issue

### ISSUE THREAD

**Issue by DigiCoyote** [kivy/kivy#2738]
When 4 or more animated context instructions are sequentially called and repeated, a recursion error is thrown. This is the case for Color, Rotate, and Scale. Transform and Position are untested.
The code below will produce the error.

``` python
import kivy
kivy.require('1.8.0') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.scatterlayout import ScatterLayout
from kivy.graphics import Color
from kivy.animation import Animation
from kivy.graphics.instructions import InstructionGroup
from kivy.graphics import Rectangle

class MyApp(App):

    def build(self):

        element_layout = ScatterLayout()

        instruction_group_list = InstructionGroup()

        color_context_list = Color(1, 0, 0)
        instruction_group_list.add(color_context_list)
        instruction_group_list.add(Rectangle(pos=(300, 300), size=(100, 100)))
        element_layout.canvas.add(instruction_group_list)

        color_animation = Animation(r=1, g=1, b=0, a=1)
        color_animation += Animation(r=1, g=1, b=1, a=1)
        color_animation += Animation(r=0, g=1, b=1, a=1)
        color_animation += Animation(r=1, g=0, b=0, a=1)

        color_animation.start(color_context_list)
        color_animation.repeat = True

        return element_layout

if __name__ == '__main__':
    MyApp().run()
```

**Comment by luckyluken** [comment]
I am having a similar issue where sequenced animations with repeat=True are also causing a "maximum recursion depth exceeded" error . I also got the same error when trying to string together ~360 animations with repeat=False. I tried using the latest Windows download for kivy (Kivy-1.8.0-py3.3-win32.zip downloaded 2/23/2015), and both the above code and my code still fail. 

Is there a solution released in the most stable version that I am missing? Or is there a better way to animate an object through a series of points?

**Comment by DigiCoyote** [comment]
Thank you for your email.

I am out of the office from February 17  - March 9 inclusive and unable to respond at this time. 

I will by checking my email intermittently while I am away, however most correspondence will be addressed following my return on March 9. 


Best regards,

~ Aaron Wylie
