### ISSUE TITLE
Provide Cocoa Window on OS X

### ISSUE THREAD

**Issue by dennda** [kivy/kivy#275]
In order to have a proper vertical sync on OS X we should use a CADisplayLink to drive the rendering loop.
We could either provide a new window provider that opens a cocoa window or patch SDL to do that for us.

We then also want to support new Lion features such as fullscreen.

And we might want to think about doing things the OS X way, i.e. when a window is closed, don't close the entire app. That kind of behavior is frowned upon. For this to work there might be API changes necessary, but that could be done in a way that it'd benefit iOS too, where the app might be killed by the system and then later when it's opened again you want to restore the state. So we can add functionality to the API here that works on both, OS X and iOS (and Android has that too I guess).

**Comment by akshayaurora** [comment]
Opened a new issue targeted for 2.0 release
