### ISSUE TITLE
How to use UrlRequest() behind proxy

### ISSUE THREAD

**Issue by sumitkumarsk90** [kivy/kivy#2767]
I am trying to use Kivy's UrlRequest() method behind a university proxy.
I m not getting how to fix it so please help me

**Comment by DavidA2014** [comment]
@opqopq Please will you try attaching the file again? Your attachment is still not visible. The pasted code has lost line endings.

**Comment by DavidA2014** [comment]
The code here:

https://github.com/kivy/kivy/pull/2772

worked for me behind our proxy server.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/2772.
