### ISSUE TITLE
softinput_mode does not work on iOS

### ISSUE THREAD

**Issue by levineds** [kivy/kivy#2775]
softinput_mode does not work on iOS (using kivy-ios, kivy version 1.9.0). I have successfully used the same code on Android with buildozer.
##

**Comment by Julian-O** [comment]
This contains very little details to reproduce, and and I think that has caused it to be ignored.

@levineds: Are you still having this problem with Kivy 2.2.1? Can you provide some code to reproduce it, and the logs? What is actually happening? "Does not work" is not enough information.

**Comment by levineds** [comment]
I believe the issue was that the keyboard didn't pop up at all, but I haven't worked on this project in almost 10 years. I'm not sure if I have the setup to try and replicate what I was doing back then. This issue can probably be closed as "cannot reproduce". If I ever get back to this, I can open a new ticket with more details at that time.
