### ISSUE TITLE
hidinput.py crash

### ISSUE THREAD

**Issue by lhelontra** [kivy/kivy#2793]
hello was testing the keyboard in Kivy and appeared the following error:

File "/usr/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 525, in process_as_mouse_or_keyboard
     l = keyboard_keys[ev_code][-1
 KeyError: 114

so decided:
if ev_value == 1 and ev_code in keyboard_keys.keys():

great work congratulations!!!!
##

**Comment by Julian-O** [comment]
I am closing as stale/can't repro. There are other complaints about keycode mappings, and they have more workable information that this one.

If you can get this to reproduce and post more information, please let us know.
