### ISSUE TITLE
add_widget has a weak index method

### ISSUE THREAD

**Issue by chozabu** [kivy/kivy#2802]
It is hard to add several widgets with a z-index without sorting them first
see https://gist.github.com/chozabu/57c1a5ee96f2ea08b692

storing the index param on a widget or something similar could help here

**Comment by victor-rene** [comment]
Can you elaborate a bit more. What do you mean by hard? Does it not work, or work partially. That would easier to test from an example with faulty output vs expected output.

**Comment by chozabu** [comment]
It's more an error in my expectation than the code its-self.
The gist linked in my previous comment ( https://gist.github.com/chozabu/57c1a5ee96f2ea08b692 ) demonstrates a situation that without knowing the details of the index method, I would expect to work.

In a nutshell - given an empty layout adding:
widget A at position 1000
widget B at 500
widget C at 200
widget D at 250
- one may expect the order to be CDBA, but it would be ABCD - or whatever order they were added in.

Looking at the add_widget code, this makes complete sense, but it felt just counter-intuitive to write an issue about.

**Comment by dessant** [comment]
We could elaborate how index works in the docs.

**Comment by Zen-CODE** [comment]
Being bold and closing. Please re-open if this explanation is still not sufficient (asking for forgiveness rather than permission).
