### ISSUE TITLE
SDL2 OSX packaging should use latest master to enable on_dropfile event to work properly on macs

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#2817]
SDL2 OSX packaging should use latest master to enable on_dropfile event to work properly on macs.

**Comment by tito** [comment]
I vote in favor to delay this one, and wait the official frameworks. As we don't use source code anymore.

**Comment by akshayaurora** [comment]
+1 retagging

**Comment by akshayaurora** [comment]
2.0.4 rc is out we should be using that in absence of a release for 1.9.1

**Comment by akshayaurora** [comment]
New Packaging uses 2.0.4
