### ISSUE TITLE
Kivy red dots when using keyboard shortcut with CTRL key to start kivy.bat script

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2827]
![kivy_is_sick.png](http://s22.postimg.org/xghcxgnwx/kivy_is_sick.png "kivy_is_sick")

Basically it comes down to using a keyboard shortcut to launch a kivy app. If I do it fast enough, somehow the key event isn't processed correctly and the touch CTRL is considered down when it is already back up. It's a bit annoying because of the randomness...

EDIT: Might be related to #2766. There are talking about detecting the CTRL key in the comments.

**Comment by dessant** [comment]
The portable package with the .bat script is deprecated in favor of wheels. Please reopen with an example and clear steps to reproduce if the issue is still there without the .bat launch.
