### ISSUE TITLE
More information during extraction process on Android [$100]

### ISSUE THREAD

**Issue by bionoid** [kivy/kivy#2832]
Add a progress bar during extraction for Android. If it runs out of space or fails for other reasons, an error message should be displayed. Ideally the text should be customizable by the user for localized apps.

**Comment by chozabu** [comment]
Any chance this could be split in two? I imagine many people like myself are not working on droid AND ios.

I'm just having a look at what can be done in this area, for the loading screen after initial extraction too.

**Comment by bionoid** [comment]
Sorry I forgot to clarify this. The bounty is for Android, extraction is not used on iOS.

**Comment by dessant** [comment]
@bionoid, could you port over the issue and bounty to p4a?

**Comment by bionoid** [comment]
@dessant there is apparently no way to cancel the bounty beyond asking bountysource for a refund, which I have done. I will close the issue once that is settled.
