### ISSUE TITLE
Panda3D & Kivy on Windows

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#2835]
Recently I've found this tito's patch for panda http://txzone.net/files/contrib/panda3d/ and I'd like to know if it's still working, because kivy is now 1.9, panda3d is 1.8.1.

Also I'd like to know if there is any way how to use this patch with kivy on windows. Has anybody tried it yet?

**Comment by tshirtman** [comment]
I don't think this qualify as a bug, please asks on kivy-user Mailing List.
