### ISSUE TITLE
Create standard Kivy dialog widgets (LoadDialog, SaveDialog, maybe others)

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2838]
It's a feature request to upgrade functionality of FileChooser.
See: http://kivy.org/docs/api-kivy.uix.filechooser.html

Current example doesn't provide an easy way to use either LoadDialog or SaveDialog independently easily.

**Comment by picibucor** [comment]
Here is how to do it in kivy:

#:kivy 1.8.0

<MyLabel@Label>:
	font_size: '20 sp'

RootWidget:
		# choose File
		MyLabel:
			size_hint: 1,0.07
			text: 'Where's your file?'
		#FileChooserIconView:
		FileChooserListView:
			id: file_chooser_kalschein
			show_hidden: True

		BoxLayout:
			orientation: 'horizontal'
			size_hint: 1, 0.1
			padding: 0
			spacing: 6

			BoxLayout:
				orientation: 'vertical'

				# file feedback
				MyLabel:
					text: 'Your file:  ' + str(file_chooser_kalschein.selection)[2:-2]

				# button
				Button:
					size_hint: 0.2,1
					text: 'save / load'
					#on_release: root.save(str(file_chooser_kalschein.selection)[2:-2])
					on_release: root.load(str(file_chooser_kalschein.selection)[2:-2])

**Comment by victor-rene** [comment]
@picibucor Thank you very much. Looks like it's the same template for both. Gonna test as soon as possible.

**Comment by akshayaurora** [comment]
It was chosen deliberately to have a self contained widget set in the core that can be easily extended into anything you want, what kind of save or load dialog you want may depend on your preferences and there are a few types already defined in the garden. Just look at https://github.com/kivy-garden/garden.filechooserthumbview and https://github.com/kivy-garden/garden.filebrowser

**Comment by akshayaurora** [comment]
There is a example of this on the examples/RSTEditor folder of kivy for easy understanding too.

**Comment by victor-rene** [comment]
@akshayaurora  The current FileChooser is good as is, I'm not suggesting to remove it. However, I think there is a real gain from a user experience point of view to get those examples out of garden into core. Why force new users to work that hard for something so basic, is beyond me. Intuitiveness / usability is important too.

**Comment by picibucor** [comment]
Is this what you suggest: #2473 ?
