### ISSUE TITLE
TextInput Ctrl+A shortcut

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#2839]
OS: Windows 8.1 64bit, Kivy: master
When I write something, everything is ok, but when I want to select all with Ctrl+A shortcut, TextInput somehow blocks itself and doesn't respond to anything but Backspace(<--) or Delete. If it's not a bug, how to fix my issue?
There's no specific code, only added TextInput as a widget in kv

**Comment by matham** [comment]
Can you try just running the showcase to see if you have the issue? Because I cannot reproduce it on Windows.

**Comment by matham** [comment]
Can you check if you're on latest master by doing a pull? Because supposedly this has been fixed recently.

**Comment by akshayaurora** [comment]
reopen if you still have the issue on latest master
