### ISSUE TITLE
Consistent scrolling behavior across all widgets

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2841]
Usability
-----
I have been surprised quite a few times already by the non-scrolling behavior of certain widgets. Right now it's TreeView that deceived me. When you add TreeViewLabels to it, it won't scroll when the content's height exceeds its height. Now if you compare it to ListView, you can just set item_strings and not worry about scrolling.

Behavior
-----
I believe the expected behavior for those "ItemsControls" (burrowing from WPF .NET here) is to scroll vertically always. I don't have the list of controls that needs to be checked though.

Performance
-----
All those widgets can also be subject to performance issues. WPF uses virtualization to handle large datasets. I have no idea if Kivy current supports such technique. Here is the reference:
[Optimizing Performance: Controls]( http://msdn.microsoft.com/en-us/library/cc716879%28v=vs.110%29.aspx).

**Comment by janssen** [comment]
I suspect the TreeView issue you reference above is a side-effect of #3721.

**Comment by dessant** [comment]
This issue is a bit vague, please open separate issues for the widgets which misbehave,
