### ISSUE TITLE
Allow use of pygame with SDL2

### ISSUE THREAD

**Issue by kived** [kivy/kivy#2846]
Building with SDL2 forcibly disables pygame. I'd fix it but I'm not familiar with the packaging issue that required this.

**Comment by akshayaurora** [comment]
My suggestion would be to still keep them seaprate. Having them both compiled at the same time would lead to compilations issues with conflicting method signatures being present in both libsdl1.2 and libsdl2.

I'd suggest disabling sdl2 compilation if USE_SDL2=0 env var is set.

**Comment by kived** [comment]
That has never been an issue for me on Linux. For example, I can use window_pygame with image_sdl2, or window_sdl2 with text_pygame with no issues.

**Comment by akshayaurora** [comment]
This becomes a issue when packaged and frozen with a tool like pyinstaller which tends to get confused with these, effects the runtime of the package

**Comment by tito** [comment]
kived on linux, so, but on other platform like OSX, you get a warning cause some symbol are declared twice in the binary, at 2 different location. Imagine the confusion when you want to use the IMG_Load, which one exactly, the one in SDL or SDL2 ? The binary don't make the difference, and can lead to crash :/

**Comment by dessant** [comment]
@kived i had problems when mixing pygame and sdl2 providers.
https://github.com/kivy/kivy/issues/2550

**Comment by tito** [comment]
That's exactly what i'm describing. Exclusion is the only way to be safe.

**Comment by akshayaurora** [comment]
After some more discussion on irc it seems @kived doesn't see the issue with packages as he manages his own packages just for debian. There does not seem to be a good way to use packagers like pyinstaller and keep both pygame and sdl2.

Please reopen if a solution can be found for this packaging issue.
