### ISSUE TITLE
Cython is missing, Its required to compile Kivy.

### ISSUE THREAD

**Issue by fewbackseven** [kivy/kivy#2851]

**Comment by fewbackseven** [comment]
For kivy, Cython is missing.
.
.
![cython-error](https://cloud.githubusercontent.com/assets/10475014/5720197/14da86bc-9b47-11e4-9643-859abae8812e.jpg)
.
.
For Cython, MSVC9 Compiler is missing
.
![msvc9](https://cloud.githubusercontent.com/assets/10475014/5720200/1c22ffee-9b47-11e4-83a0-f843ceb118ed.jpg)

**Comment by victor-rene** [comment]
Please make sure you have a Visual C++ compiler installed on you PC. You can use any express version of Visual Studio if you don't have one. Next thing is to refer to this SO answer: http://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat
You'll be able to redirect cython (it's searching for VS 2008).

**Comment by akshayaurora** [comment]
Cython and other reps are included with the portable package from kivy.org, if using pip you need to install the deps, pip won;t be able to install all the dependencies like gstreamer etc.  You should try out the portable package http://kivy.org/#download

**Comment by fewbackseven** [comment]
//Thank you for your support.
.
.
well now I installed VS 2010 Professional now cython is installed succesfully. 
.
.
But I am finding little difficulties in installing kivy again
![kivy-install error](https://cloud.githubusercontent.com/assets/10475014/5762756/8242b5f2-9d0a-11e4-99e5-83ae09311727.jpg)

**Comment by victor-rene** [comment]
As @akshayaurora said before, use the portable version of kivy. I cannot tell you how to configure the dependencies on Windows platform. This error you get seems to be on MinGW side. glew.h on my pc is there inside include folder. /2cents
