### ISSUE TITLE
Clarify kivy/examples/canvas/multitexture.py

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2852]
When running the app, we only see the final result. Show the components! Something along the lines of:
__O__ + K = __K__

**Comment by Sentient07** [comment]
Hi, I have a PR for this. I have tested and this and also have a screenshot of the output. 
Screenshot - https://i.imgur.com/Rt1n6Lf.png
PR: https://github.com/kivy/kivy/pull/3125

**Comment by tito** [comment]
PR Merged, so it should be ok :)
