### ISSUE TITLE
Transparent the contents of the window at startup

### ISSUE THREAD

**Issue by ivlevdenis** [kivy/kivy#2853]
Sometimes when the program starts contents of the window transparent. OS - Ubuntu 14.04.
upd: on fullscreen mode work fine

This bug screen:
![kivy_bug](https://cloud.githubusercontent.com/assets/7171587/5740671/84804004-9c16-11e4-9597-55aaaa7c0f47.png)

Normal run screen:
![ns-player_norm](https://cloud.githubusercontent.com/assets/7171587/5740718/0404ed66-9c17-11e4-9c45-f27a12a5bf5b.png)

**Comment by ivlevdenis** [comment]
Sorry, I forgot that I use daily PPA :) Fix it after the upgrade.

**Comment by dessant** [comment]
Nice theme @ivlevdenis. Is it an Ubuntu fork or just a custom ui and icon theme?

**Comment by ivlevdenis** [comment]
@dessant, numix theme.
