### ISSUE TITLE
Window size missing 50 pixels (from border) with -m device,scale cmd line arg (Win7-64)

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2854]
Exactly as the title says. Maybe nobody noticed before. However, it seems a bit off to request let's say HTC One X, and get 720x1230 instead of 720x1280. Same thing if you request scale of 0.5, you get 360x590. But if you do the math, (590+50) / 0.5 = 1280. Size is fetched from Config.get('graphics', 'width/height'). Window.height/width from kivy.core.window gives the same result. Using Config.set('graphics', 'borderless', 1) doesn't help either.

**Comment by kived** [comment]
It's taking off the extra space to simulate the presence of the status bar.

https://github.com/kivy/kivy/blob/master/kivy/modules/screen.py#L82

**Comment by victor-rene** [comment]
Okay thx @kived. Closing this one.
