### ISSUE TITLE
Installation error with python 3.4.2, I tried to install by running command "Python setup.py install"

### ISSUE THREAD

**Issue by fewbackseven** [kivy/kivy#2858]
![kivy-install error](https://cloud.githubusercontent.com/assets/10475014/5762318/4378fc30-9d07-11e4-9fcc-ba297c8d963e.jpg)

.
.
glew.h file is missing. . .

**Comment by dessant** [comment]
@are you using the portable package? You don't need to issue `install` on windows. In case of an update, just `make force`.
The portable package contains mingw, but you seem to be using visual studio for compilation.

**Comment by fewbackseven** [comment]
Yes.. I am using Portable version. ..
.
.
So.. I don't need to install kivy????
.

**Comment by ohaz** [comment]
No, just read http://kivy.org/docs/installation/installation-windows.html

**Comment by fewbackseven** [comment]
Oh.. !! Okie sir.. Thank you...
