### ISSUE TITLE
Strange artifiacts on widgets on Retina displays

### ISSUE THREAD

**Issue by sbrother** [kivy/kivy#2859]
All Kivy widgets display strange line artifacts on Retina Macbook Pro running OSX 10.10.1. Kivy installed via Kivy-1.8.0-osx.dmg. Screenshot below can be reproduced by running main.py at https://github.com/sbrother/ga-python-demo-frontend (or any other simple Kivy app).

![image](https://cloud.githubusercontent.com/assets/1652291/5764891/49589d66-9caa-11e4-8286-6daa248da7bf.png)

**Comment by akshayaurora** [comment]
Just to add, this is while using the screen module with python -m screen:...

**Comment by sbrother** [comment]
Wait, @akshayaurora I think you might have misinterpreted my email. It was run on one of my students' Macbooks using the "kivy" symlink. python -m screen was not used, unless the kivy symlink does that behind the scenes?

**Comment by akshayaurora** [comment]
ok, but I can reproduce it only using screen module, I guess your case shows that these artefacts are also possible without using that module.  The fix in both cases probably is to make kivy handle dpi properly in desktops like we do for mobile.

**Comment by akshayaurora** [comment]
We now have proper support for retina screens, please reopen if the issue persists.
