### ISSUE TITLE
Allow property creation for widget instances

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2860]
An often requested feature is to add new kivy properties for widget instances. We already have a similar internal method: https://github.com/kivy/kivy/blob/master/kivy/_event.pyx#L797

@tito proposed this syntax, i think it is a good fit:
```python
w_instance.create_property(prop_1=StringProperty('bli'), prop_2=NumericProperty(4))
```

**Comment by denys-duchier** [comment]
The proposed implementation doesn't strictly achieve the objective stated in the issue: yes, properties are added to a widget instance, but they are also added to its class.  the latter should be optional.  I am facing  a similar issue in #3074 for missing properties added by a contextual rule.

**Comment by matham** [comment]
@denys-duchier I'm not sure what you have in mind. How can you add a kivy property to only an instance? Because it's a property it needs to be added to the class, no?

**Comment by denys-duchier** [comment]
@matham yeah, since it's a descriptor, that's the problem and I have not managed to find a way around it.  But then, there are kv lang issues.  For exemple::

    <.foo>:
      alpha: 0.5

do you really want all classes, for which one instance was created with cls foo, to gain the alpha numeric property?

what about::

    <MyWidget>:
      Button:
        alpha: 0.5

should all buttons have the alpha numeric property? and what should happen when there are conflicting declarations::

    <.foo>:
      alpha: 0.5
    <.baz>:
      alpha: "hello"

I have been puzzling over that... but I guess the only answer is to improve diagnostics and documentation.

**Comment by denys-duchier** [comment]
Here is one way to get instance-level properties::

```python
class Widget(object):

    def __init__(self):
        self._instance_properties = {}
        self._foo = 56

    def __getattr__(self, name):
        p = self._instance_properties.get(name, None)
        if p:
            return p.__get__(self, self.__class__)
        else:
            raise AttributeError(name)

    def __setattr__(self, name, value):
        p = name != '_instance_properties' and self._instance_properties.get(name, None)
        if p:
            p.__set__(self, value)
        else:
            super(Widget, self).__setattr__(name, value)

    @property
    def foo(self):
        return self._foo

    @foo.setter
    def foo(self, value):
        self._foo = value

    def add_props(self, **kwargs):
        self._instance_properties.update(kwargs)


class BazProp(object):

    def __get__(self, instance, owner):
        return instance.foo + 11

    def __set__(self, instance, value):
        instance.foo = value - 11


x=Widget()
x.add_props(baz=BazProp())
print(x.foo, x.baz)
x.baz = 0
print(x.foo, x.baz)
```

don't know if it's worth it though.

**Comment by matham** [comment]
Yeah, I think just providing docs about this is probably enough, especially given #3106 which should fix `hasattr`.
