### ISSUE TITLE
Doc clarification on pygame  and it's status in kivy is needed. + Deprecation Warnings for pygame need to be added.

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#2865]
- Pygame is still in kivy, 
- It is not being removed, it is only being deprecated
- Deprecation warnings for pygame providers
- Clear instructions on the release notes for USE_SDL2=0

**Comment by tito** [comment]
I don't really understand the point of this pygame. It should not change anything to the user, and it's not even the same on all platform (iOS, Rpi...). 

It's not going to be removed right now, but that's the goal. Plus, we're not shipping it under OSX, and we should say the related issues will not be fixed (reloading context for example, what's the point of trying to fixes issues on a deprecated one).

We didn't do anything where i wrote the gstplayer and moved everything (audio / video) on it, and it just worked. It will be the same here.

The only things we must care is the update of the new installation instructions. And communicate about it. That's all!

**Comment by akshayaurora** [comment]
Essentially as others have pointed out,  pygame is just a backend and for the end user it should not matter which back end is being used. Moving to sdl2 will be mentioned in the release notes.
