### ISSUE TITLE
Images for wiki...

### ISSUE THREAD

**Issue by merriam** [kivy/kivy#2868]
GitHub doesn't have a content management tool, but does let me reference the attached files in the wiki. :)

![config pycharm 1](https://cloud.githubusercontent.com/assets/159998/5813493/38e62386-a033-11e4-91af-a5502565f856.png)
![config pycharm 2](https://cloud.githubusercontent.com/assets/159998/5813513/aad293c6-a033-11e4-9779-11c0bb5bf903.png)

**Comment by dessant** [comment]
I don't use that tool, but you can insert an image almost anywhere on github with markdown.
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images

**Comment by merriam** [comment]
Thank you.   While I use markdown to insert the URL I want displayed, the issue allow me to trick GitHub into hosting the screenshot so that I have a URL to display.  Have a good day.

**Comment by dessant** [comment]
Well, i did not expect this hack ;).
