### ISSUE TITLE
Providing a 'Kivy Tinkerers' section of documentation.

### ISSUE THREAD

**Issue by merriam** [kivy/kivy#2875]
One way of getting more contributors is to break up the hump of people making the first contribution.   In Kivy, most documentation, except for the wiki, in the code.  I'ld like to add a couple of sections to the main (non-wiki) documentation.  The idea is to let anyone willing to set up a kivy development environment can be 'listed' in the project.   It costs the Kivy team little, and my encourage more contributions.

The idea is to add an 'authors.py' Easter Egg or Vanity Roll.   Authors can be whatever the Kivy core team designates, and Tinkerers can be anyone who bothers to add themselves correctly.  A new person on the EasterEgg would:

1.  Fork the repo.
1. Download the Kivy Source
2.  Edit kivy/authors.py, adding their name and GitHub handle to authors.py.
3.  Do a 'make html' which may require installing Cython and other tools.
4.  Snap a screenshot of the new html file showing it was built.
4.  Create a pull request with the new kivy/authors.py and using the screenshot in the description.

This gives a reasonable, but not too hard, introduction to working on Kivy.   I would be able to put together a short video walking people through setting up the environment and going through the steps.   Eventually, someone could make an Easter Egg, like a --authors flag, that did something colorful with the names of authors and tinkerers.

How much discussion is appropriate a change of this level on this project?  Should I just make the framework and submit a pull request?

**Comment by inclement** [comment]
This seems like an interesting idea, but I'm not sure I feel strongly about it. The file could just be 'tinkerers' though, rather than authors, I think that would be clearer.

Is this something other projects do?

**Comment by merriam** [comment]
So projects do this as part of an outreach for more contributors.   Once
people get the development environment set-up, which is usually far more
work than people remember after doing it, then making small changes becomes
much more possible.

Passing around credit rarely costs credit from the main contributors.  The
only downside is that new contributors will put in merge requests for
misspellings, edge cases, and error messages before new functionality.
While these all improve quality, they do place a bit of load in keeping up
with the requests.  The change in quality is gradual, but continuous.

**Comment by merriam** [comment]
Hm... Having played with the project a bit more, I don't think it would be a good idea to encourage more contributors.   It seems to overwhelm the core and encroach on the 'Imadethis' of the project.

**Comment by akshayaurora** [comment]
@merriam 
You made 20 pr in the last 6 days out of which 16 were merged, as seen on this page https://github.com/merriam. 
Looking at the stats here https://github.com/kivy/kivy/pulse 
![screen shot 2015-02-07 at 5 22 08 pm](https://cloud.githubusercontent.com/assets/788023/6092008/fd2fcc7e-aeed-11e4-8831-c3d7bf639e0a.png)

I guess 18 merged pull requests out of 24 in last week could somehow mean we don't care about contributors.
