### ISSUE TITLE
Missing _gstplayer.sо

### ISSUE THREAD

**Issue by ivlevdenis** [kivy/kivy#2879]
Missing _gstplayer.sо in Kivy installed from daily PPA. Ubuntu 14.04

**Comment by thopiekar** [comment]
Will take a look why we are not building with gstreamer support.

**Comment by thopiekar** [comment]
Really don't want to blame that problem on others, but it seems that our setup.py does not find the
gstreamer-1.0.pc file.
Just looked which package includes the needed file for your detection and here it is:

```
thopiekar@hp:~$ apt-file find gstreamer-1.0.pc
libgstreamer1.0-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-1.0.pc
```

Line 19 in our debian/control says it should install the package (https://github.com/kivy/kivy/blob/pkg-debian-daily/control#L19) and it does according to the latest build for vivid ( https://launchpadlibrarian.net/195552292/buildlog_ubuntu-vivid-i386.kivy_1.9.0-dev~daily0%2B201501221246-2559-testing55~ubuntu15.04.1_UPLOADING.txt.gz ), but:
```
 * use_gstreamer = 0
```

So it does not seem to be a packaging problem, more a gstreamer-detection problem..

**Comment by thopiekar** [comment]
Tested it now locally by installing pkg-config and libgstreamer-1.0-dev and it seems to work:
```
thopiekar@hp:~$ pkg-config --libs --cflags gstreamer-1.0
-pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0
```
Really strange..

**Comment by thopiekar** [comment]
Found the reason in line 75: https://github.com/kivy/kivy/blob/master/setup.py#L75

Well, by now it is not my decision to set c_options['use_gstreamer'] = None, but I think it is intended to be None, when looking at https://github.com/kivy/kivy/blob/master/setup.py#L272.

Think it is time to bring back the facepalm..

**Comment by kived** [comment]
Also, on L272 that should be `use_sdl2` not `use_gstreamer`. Gstreamer is handled by the block above that one.

**Comment by thopiekar** [comment]
You are right! The code needs there more clean ups..

**Comment by tito** [comment]
Done. Sorry for the mess, the setup have been splitted for sdl2 and gstreamer (was on the same boat before) and we now take care of what the user set prior the setup.py execution.

Example:

- python setup.py  -> autodetect sdl2 / gstreamer
- USE_GSTREAMER=1 -> allow usage of gstreamer (but don't fail if it's not found)
- USE_GSTREAMER=0 -> disable gstreamer (no autodetection, no compilation)
