### ISSUE TITLE
[SDL2] Function `SDL_CreateShapedWindow' implicitly converted to pointer

### ISSUE THREAD

**Issue by thopiekar** [kivy/kivy#2887]
I'm now getting kivy built in my testing PPA and got this when trying to build it with SDL2 support.
(Don't know why it works as I didn't made any major changes to my code. Just made some additions so I can debug things (#2882). However here is the message: )
```
Function `SDL_CreateShapedWindow' implicitly converted to pointer at kivy/core/window/_window_sdl2.c:1454
Function `SDL_CreateShapedWindow' implicitly converted to pointer at kivy/core/window/_window_sdl2.c:1454
Function `SDL_CreateShapedWindow' implicitly converted to pointer at kivy/core/window/_window_sdl2.c:1454
Function `SDL_CreateShapedWindow' implicitly converted to pointer at kivy/core/window/_window_sdl2.c:1454



Our automated build log filter detected the problem(s) above that will
likely cause your package to segfault on architectures where the size of
a pointer is greater than the size of an integer, such as ia64 and amd64.

This is often due to a missing function prototype definition.

Since use of implicitly converted pointers is always fatal to the application
on ia64, they are errors.  Please correct them for your next upload.

More information can be found at:
http://wiki.debian.org/ImplicitPointerConversions
```
- https://launchpadlibrarian.net/195669128/buildlog_ubuntu-vivid-amd64.kivy_1.9.0-dev~testing0%2B201501232250-2559-testing46~ubuntu15.04.1_FAILEDTOBUILD.txt.gz

**Comment by thopiekar** [comment]
Btw. this message only appears in builds for architectures != i386.

**Comment by tito** [comment]
Can you try again with this possible fix?

**Comment by thopiekar** [comment]
Will take some time. In the mean time I modified the packaging files to make builds on launchpad faster.
However, the build is now running: https://code.launchpad.net/~thopiekar/+recipe/kivy-testing (Vivid)

**Comment by thopiekar** [comment]
Fixed - https://code.launchpad.net/~thopiekar/+archive/ubuntu/kivy/+build/6745822

**Comment by tito** [comment]
Great!
