### ISSUE TITLE
Child ordering in .children doesn't match kivy string/file or apparent order

### ISSUE THREAD

**Issue by intchanter** [kivy/kivy#2895]
Script follows. It should only require Kivy to run on Python 2.7+ or 3.x. Tested under Python 2.7 and Kivy '1.9.0-dev'. The docstring has additional information.

```python
'''
Demonstrate an apparent issue in Kivy:

Child widgets created in kivy language and the .children attribute are in
opposite order to each other. My intuition was that they would be in the same
order. I was unable to find any documentation one way or another, so
hopefully this will get it corrected if the behavior is incorrect and
clearly documented if the behavior is correct.

Observed behavior:

Child order in the kivy string: 0 through 8
Child order as displayed: 0 through 8
Child order from .children: 8 through 0
Output (between rows of asterisks):
    ['8', '7', '6', '5', '4', '3', '2', '1', '0']

Expected behavior:

Child order from .children matches the order in the kivy string and as
displayed.
Output (between rows of asterisks):
    ['0', '1', '2', '3', '4', '5', '6', '7', '8']
'''

from kivy.app import App
from kivy.lang import Builder
from kivy.clock import Clock

root_widget = None

kivy_text = '''
GridLayout:
    cols: 3
    Label:
        text: '0'
    Label:
        text: '1'
    Label:
        text: '2'
    Label:
        text: '3'
    Label:
        text: '4'
    Label:
        text: '5'
    Label:
        text: '6'
    Label:
        text: '7'
    Label:
        text: '8'
'''

class ChildOrderBugApp(App):
    def build(self):
        global root_widget
        root_widget = Builder.load_string(kivy_text)
        return root_widget

def print_children(dt):
    def get_text(widget):
        return widget.text
    print('*' * 45)
    print(map(get_text, root_widget.children))
    print('*' * 45)

if __name__ == '__main__':
    app = ChildOrderBugApp()
    Clock.schedule_once(print_children)
    app.run()
```

**Comment by tito** [comment]
It is not a bug. The child are inserted into the front of the list instead of the back.
It make easier the touch dispatching / overload.

On a same level of the tree, you want to dispatch the touch from the front to the back. Which is the default children ordering in the list. That's why you can do::

```
for child in self.children:
    if child.collide_point(*touch):
        print "Collision: touch"
```

But the graphics tree ordering is inversed, as the widget are drawed from the back to the front.

This approach avoid you (the user) to use reversed() on the children, and so, most efficient traversal.

**Comment by intchanter** [comment]
I'll see if this week I can work up a pair of patches for this.

Patch 1 will be a simple change to the documentation to indicate that this is in the reverse of the order that might be expected.

Patch 2 will move the current behavior to ._children and create .children to return the reversed list.

My preference would be to have the second accepted, as the optimization you mentioned shouldn't affect code outside of Kivy.
