### ISSUE TITLE
SDL2 - add font_hinting property to Label

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2898]
As @tito noted, t-s and f-s are not displayed correctly with Roboto.
~~With pygame the issue does not seem to be present.~~

Update: ignore the pygame - master image.
![screenshot from 2015-01-25 15 02 34](https://cloud.githubusercontent.com/assets/7513068/5891554/68e3ac40-a4a5-11e4-8f20-0a7390135ae8.png)

UPDATE:
This is the light_hint branch https://github.com/kivy/kivy/commit/17ff7d3a61f75619af17d150115d83acd3eb9bc6.

Code used:
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory

kv = """
<Test@Label>:
    text: 'settings free'
    on_size: print(self.font_name)
"""

Builder.load_string(kv)


class TestApp(App):
    def build(self):
        return Factory.Test()

if __name__ == '__main__':
    TestApp().run()
```

**Comment by dessant** [comment]
What's even stranger is that pygame displays a different glyph for "g". The correct glyph for it in Roboto is the one rendered by sdl2.

**Comment by thopiekar** [comment]
same with the "s"

**Comment by dessant** [comment]
If Roboto-Regular.ttf is specified for the Label's `font_name`, it is displayed just like with sdl2, so this pygame font swap seems to be a kivy bug, not pygame.

**Comment by dessant** [comment]
I have messed up something, that's why pygame used a different font. :|
I've repulled and now the default font is shown, it looks just like with sdl2:
![screenshot from 2015-01-25 23 38 41](https://cloud.githubusercontent.com/assets/7513068/5893414/b4ca68c4-a4eb-11e4-9b83-437e6310d0d7.png)

**Comment by tito** [comment]
I think the safer solution is to rollback the commit, and get it right for the next version, even if it's a minor. The current changes are not acceptable for a release :/

**Comment by dessant** [comment]
@tito maybe that would be the best.
Have you tried the light_hint branch?

**Comment by FeralBytes** [comment]
So will this be removed from the 1.9.0 milestone requirements?

**Comment by dessant** [comment]
@FeralBytes first we should try to make it work, one proposal is rather simple and it would fix a bug in 1.9: some fonts are not displayed correctly and they cannot be tweaked because we do not have a hint api for example.

**Comment by FeralBytes** [comment]
@dessant OK. I just keep seeing 1.9l0 move further and further back as more issues are tagged 1.9.0.

**Comment by dessant** [comment]
@FeralBytes help us decrease that list faster. ;)

**Comment by dessant** [comment]
@FeralBytes maybe try out the light_hint branch with some fonts and report back, that would help a lot.

**Comment by FeralBytes** [comment]
@dessant I wish I had more time on my hands. I truely am sorry, that I do not. I am not posting to critize your work. Just have not been able to find a clear plan for what is 1.9.0. So I have been using the Milestone tag, and seeing the number of open issues going backwards indicates that 1.9.0 has not been put into any sort of freeze. Normally for software release there is a freeze period, where no new features are added. This light_hint seems to be an all new feature, and an addition to the API. I understand it is fixing a bug. But what is 1.9.0 supposed to look like, will there be a freeze in the near future?

**Comment by dessant** [comment]
The default font change has been reverted, we need to investigate this further.

**Comment by dessant** [comment]
We've recently switched to Roboto, the hinting issue has been fixed in the latest version of the font.

**Comment by dessant** [comment]
Implemented in https://github.com/kivy/kivy/pull/3896.
