### ISSUE TITLE
makefile doesn't recompile on changes on windows

### ISSUE THREAD

**Issue by matham** [kivy/kivy#2917]
On windows, after I change something e.g. in `_event.pyx` and run make, it does not recompile and just says `Kivy is already built for "python"!`. I think it's due to the recent @thopiekar changes.

**Comment by thopiekar** [comment]
If you execute ```make pdf``` or ```make html``` it will but shouldn't when you do normal builds.
Is there something I miss on doc builds? Is there a reason kivy needs to be rebuilt every time?

**Comment by dessant** [comment]
@thopiekar it must rebuild changed cython files when issuing `make`.

**Comment by thopiekar** [comment]
Didn't know that :(

OK, two options:
1. Revert the changes on that.
2. I add a variable "FORCE_REBUILD"
3. or a variable "SKIP_REBUILD" for the opposite

What do you like?

**Comment by tito** [comment]
@thopiekar same remarq, i seen this behavior yesterday. You should not change the Makefile for the default "make". Writing a file to see if it compile is against the setup.py detection of changes itself. :)

I suggest the 1. !

**Comment by thopiekar** [comment]
Fixed that in my merge request. Sorry, again :(
