### ISSUE TITLE
Behaviour of PageLayout might not be the expected.

### ISSUE THREAD

**Issue by robertour** [kivy/kivy#2928]
I noticed that the PageLayout has an unexpected behaviour. The "Pages" in the middle get covered by the next page (the one to the page). To fix it, the programmer would have to make sure that there is an empty space (equal to the border property of PageLayout) on the middle pages, but not on the extremes. This makes me think that the current behaviour is wrong, and should be fixed in order to keep things centered. 

Here is an example to replicate

    <MyPageLayout>:
        Button:
            font_size: 26
            text: 'This is a very long description for the page 1 and centered'
        Button:
            font_size: 26
            text: 'This is a very long description for the page 2 not centered'
        Button:
            font_size: 26
            text: 'This is a very long description for the page 3 and centered'

And 3 screenshots. Notice how the second one is convered by the 3rd one.

![page1](https://cloud.githubusercontent.com/assets/1033512/5929588/0d1eb972-a653-11e4-83e0-6626f3406c6e.png)
![page2](https://cloud.githubusercontent.com/assets/1033512/5929587/0d1d2ff8-a653-11e4-8e00-d822c25ec22b.png)
![page3](https://cloud.githubusercontent.com/assets/1033512/5929589/0d217892-a653-11e4-8c5e-c74d571cca8e.png)

Thank you!

**Comment by matham** [comment]
#3007 should fix this.
