### ISSUE TITLE
Kivy Launcher should include plyer and pyjnius

### ISSUE THREAD

**Issue by svineet** [kivy/kivy#2931]
I tried accesssing plyer in a kivy launcher app, got an import error.

Can we please include plyer and pyjnius in the launcher too? It would make development a lot easier for people with weak internet. It would also make prototyping apps much easier.

**Comment by tito** [comment]
pyjnius is in, but plyer not. Definitively a missing feature.

**Comment by FeralBytes** [comment]
Recommend this issue get closed and [moved to P4A here](https://github.com/kivy/python-for-android/issues/328), since it is a Launcher issue and they belong in P4A.

**Comment by tito** [comment]
Plyer is now part of the latest Kivy launcher (1.9.0.0)!
