### ISSUE TITLE
TextInput Handles are covered behind other siblings in 1.9

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#2939]
Due to the changes in https://github.com/kivy/kivy/pull/2390. We now have a issue where the default behaviour of TextInput Handles is not working as expected. 

http://txzone.net/files/tmp/Screenshot_2015-01-29-16-14-56.png

This needs to be fixed to still use the old behaviour and enable this option using a parameter/property for when the user needs to put The TextInput inside a ScrollView or a Satter. .

**Comment by tito** [comment]
![screenshot_2015-01-29-16-14-56](https://cloud.githubusercontent.com/assets/37904/5960689/8f6aac30-a7d7-11e4-8fad-58f38427d916.png)

**Comment by tito** [comment]
![screenshot_2015-01-29-16-14-56](https://cloud.githubusercontent.com/assets/37904/5960713/c2a0401a-a7d7-11e4-8cc9-d0fe1da796a2.png)
