### ISSUE TITLE
Textinput handles are still touchable even when unfocused

### ISSUE THREAD

**Issue by tito** [kivy/kivy#2940]
1. Select the first textinput. Check visually where the handles are poping.
2. Unfocus the first textinput
3. Then try to focus the second textinput. It will not work where the handles of the first textinput where.

![screenshot_2015-01-29-16-14-56](https://cloud.githubusercontent.com/assets/37904/5960980/a269850c-a7d9-11e4-8207-dc9f2ef40628.png)

**Comment by kived** [comment]
Fixed in #3063
