### ISSUE TITLE
fallen page

### ISSUE THREAD

**Issue by jotavargas** [kivy/kivy#2974]
Hello, I wanted to start working with this framework but the page and documentation this fall. [http://kivy.org] :(

**Comment by inclement** [comment]
I don't understand what your issue is, could you explain a little more?

**Comment by dessant** [comment]
I think he means the documentation failed to load, but it seems to be reachable http://www.isitdownrightnow.com/kivy.org.html.

**Comment by jotavargas** [comment]
Yes.
The official website [http://kivy.org] this fallen. know where there is more information

**Comment by dessant** [comment]
@jotavargas, you could clone this repo and issue `make html` to build an offline version of the docs.
Or here is the pdf version, taken from http://kivy.org/docs/pdf/Kivy-latest.pdf:
https://www.dropbox.com/s/ckjkiiviohxgna9/Kivy-latest.pdf
