### ISSUE TITLE
Error in building .apk file

### ISSUE THREAD

**Issue by jayece09** [kivy/kivy#2992]
Hi!
I tried using both buildozer and python for android methods for apk file creation.

I have same issue in running ./distribute.sh -m "openssl pil kivy"

**************************************************************************
building 'kivy.graphics.vertex_instructions' extension
ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/jp/Desktop/test2/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/vertex_instructions.c -o build/temp.linux-x86_64-2.7/kivy/graphics/vertex_instructions.o
kivy/graphics/vertex_instructions.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
 error: command 'ccache' failed with exit status 1

Error compiling Cython file:
------------------------------------------------------------
...
    #    perhaps tangents, what's the position on the spline for parameter t),
    #
    #    b) make that a superclass Spline,
    #    c) create BezierSpline subclass that does the computation

    cdef list _points
             ^
------------------------------------------------------------

kivy/graphics/vertex_instructions.pyx:104:14: C attributes cannot be added in implementation part of extension type defined in a pxd

Error compiling Cython file:
------------------------------------------------------------
...
    #    perhaps tangents, what's the position on the spline for parameter t),
    #
    #    b) make that a superclass Spline,
    #    c) create BezierSpline subclass that does the computation

    cdef list _points
             ^
------------------------------------------------------------

**Comment by tshirtman** [comment]
can you indicate your cython version?

**Comment by tito** [comment]
It seems you have Kivy installed in your PYTHONPATH. The master version and the one you might use during compilation will break because you used PYTHONPATH.

Try: `PYTHONPATH= ./distribute.sh -m "openssl pil kivy"`
