### ISSUE TITLE
Multiple Inheritence ToggleButtonBehavior+Label not working in .kv

### ISSUE THREAD

**Issue by robertour** [kivy/kivy#2996]
The following example based on [the documentation](http://kivy.org/docs/api-kivy.lang.html#dynamic-classes) works: 

    import kivy
    from kivy.app import App
    from kivy.uix.floatlayout import FloatLayout
    from kivy.lang import Builder

    Builder.load_string("""
    <ToggleLabel@ButtonBehavior+Label>:

    <FloatLayout>:
        ToggleLabel:
    """);

    class TheApp(App):
        def build(self):
            return FloatLayout()

    if __name__=="__main__":
        TheApp().run()

But if `ButtonBehaviour` is replaced for `ToggleButtonBehaviour`, then it doesn't work anymore:

    <ToggleLabel@ToggleButtonBehavior+Label>:

    <FloatLayout>:
        ToggleLabel:

But then, if the instance `ToggleLabel` is removed, then it works again:

    <ToggleLabel@ToggleButtonBehavior+Label>:

    <FloatLayout>:

Thanks

**Comment by matham** [comment]
Which part doesn't work? It works perfectly for me.

**Comment by matham** [comment]
I'm closing for lack of details. Please reopen if you still have the issue with more details.
