### ISSUE TITLE
 ImportError: No module named window_x11

### ISSUE THREAD

**Issue by lmbringas** [kivy/kivy#3000]
I have a problem with version 1.9. the error is  ImportError: No module named window_x11 . 
someone could fix it?

**Comment by thopiekar** [comment]
OS? release? Used build/installation method?

**Comment by tito** [comment]
It can be normal if you logged all the error, and didn't compiled Kivy with X11, if it that's you wanted.

We can't say if it's intended for your configuration or not, as you don't give us any log / build method / build environment / os etc.

Please reopen if you don't have any window provider with more informations, thanks :)
