### ISSUE TITLE
Feature Request: A "pseudo-user" class with methods that, e.g., trigger events ordinarily triggered by a real user

### ISSUE THREAD

**Issue by OlyDLG** [kivy/kivy#3019]
The idea here is that this would be useful for unit testing GUI components.  Data attributes would govern things like where a "location-possessing" event (such as a touch) is intended to have originated from; the programmer could then assign such values using either bounded random functions, literals, expressions, or whatever is appropriate for the case at hand.  Thanks!

**Comment by matham** [comment]
I'm missing a bit of context because I don't fully understand what the idea is and where it'd be implemented. Can you expand, with maybe an example?

**Comment by OlyDLG** [comment]
Example methods would be HitButton and MissButton, which, given as input
the size and position of a button, would generate ten, say, random
positions inside and outside the button, respectively, then serially feed
the button these positions as if ithey were the result of a user
interaction: in this way a unit test (the basic use case for such a
pseudo-user) could test a programmer's implementation of a button, for
example.

On Saturday, February 28, 2015, matham <notifications@github.com> wrote:

> I'm missing a bit of context because I don't fully understand what the
> idea is and where it'd be implemented. Can you expand, with maybe an
> example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/issues/3019#issuecomment-76563698>.
>


-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)

**Comment by matham** [comment]
I don't think this belongs in kivy. Kivy already provides the tools to simulate inputs (http://kivy.org/docs/api-kivy.input.recorder.html) and what you're suggesting is useful in your specific case but is not generic enough, or at least you have not proposed a generic enough system for this to belong in kivy.

**Comment by OlyDLG** [comment]
Ok, thanks, I didn't know about inputs, that does sound like what I had in
mind, more-or-less.  @matham: do you mind if I email you off-list with
Q's about garden.graph?

On Monday, March 2, 2015, matham <notifications@github.com> wrote:

> I don't think this belongs in kivy. Kivy already provides the tools to
> simulate inputs (http://kivy.org/docs/api-kivy.input.recorder.html) and
> what you're suggesting is useful in your specific case but is not generic
> enough, or at least you have not proposed a generic enough system for this
> to belong in kivy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/issues/3019#issuecomment-76757582>.
>


-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)

**Comment by matham** [comment]
Well, try to catch me on IRC. It's been a while since I looked at Graph, and my hope is that it will be replaced with matplotlib using a kivy backend so I had been looking at that direction rather than focus energy on Graph. If you ask on IRC and it's not suited we can do it offline, but on IRC others may help as well.

**Comment by OlyDLG** [comment]
Interesting, as the features I want I know are already in matplotlib: do
you have a release target?  Is any of it alpha-ready?  (I particularly need
the sub-plot functionality.)? I'm afraid I'm an IRC novice: can you suggest
a windows client?  Or do you use a browser?  And do you post messages: if
no one is on when I post, what happens?

On Monday, March 2, 2015, matham <notifications@github.com> wrote:

> Well, try to catch me on IRC. It's been a while since I looked at Graph,
> and my hope is that it will be replaced with matplotlib using a kivy
> backend so I had been looking at that direction rather than focus energy on
> Graph. If you ask on IRC and it's not suited we can do it offline, but on
> IRC others may help as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/issues/3019#issuecomment-76769397>.
>


-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)

**Comment by matham** [comment]
Unfortunately I'm only past the exploratory stage of figuring out that it is possible and the probable best ways to approach it. I have not had time to write actual code and then we decided to put it up as a GSOC project so I put it off hoping someone will take it up there (http://kivy.org/docs/gsoc.html#project-ideas).

Regarding IRC, here's a brief intro: http://www.pyladies.com/blog/irc-resources/ and one slightly longer: http://www.instructables.com/id/How-to-use-IRC-Internet-Relay-Chat/. Personally, I use Quassel as a client and I like it. However, before that, I just used the website (http://webchat.freenode.net/) as described here: http://kivy.org/docs/contact.html#irc.

**Comment by OlyDLG** [comment]
OK, thanks!  One last follow-up and then I'll reserve further Q's for IRC:
in your explorations, were you able to gauge the likelihood that you'll be
able to provide a backward-compatible API, so that I won't need to
re-factor code I'm writing now, using graph, once the change-over is made?
I'll need this info in discussions w/ my boss re: how best to proceed.
 (The only reason we're using Kivy is for support of hand-helds _in the
future_ (not the present), and the only reason we're using garden.graph is
because Kivy doesn't support matplotlib.  But if the plan is for Kivy to
support matplotlib in the future, and our hand-helds support is in the
future, maybe I should just be writing the graphics portion of our package
in matplotlib from the outset; it would certainly make my life a lot
simpler!)  Thanks!

On Mon, Mar 2, 2015 at 10:37 AM, matham <notifications@github.com> wrote:

> Unfortunately I'm only past the exploratory stage of figuring out that it
> is possible and the probable best ways to approach it. I have not had time
> to write actual code and then we decided to put it up as a GSOC project so
> I put it off hoping someone will take it up there (
> http://kivy.org/docs/gsoc.html#project-ideas).
>
> Regarding IRC, here's a brief intro:
> http://www.pyladies.com/blog/irc-resources/ and one slightly longer:
> http://www.instructables.com/id/How-to-use-IRC-Internet-Relay-Chat/.
> Personally, I use Quassel as a client and I like it. However, before that,
> I just used the website (http://webchat.freenode.net/) as described here:
> http://kivy.org/docs/contact.html#irc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/issues/3019#issuecomment-76773899>.
>



-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)

**Comment by matham** [comment]
The API with matplotlib would be for you to call mpl methods like you normally do with mpl, except the graph would show up in a kivy widget. So no, it'd not be a drop in replacement because currently you modify the Plot.points list, but with mpl you'd call e.g. `plt.plot`. However, I'm not sur ethat this is a significant difference?

But I wouldn't expect to have a working prototype, even in alpha phase in the next few months, unless it's taken up as a GSOC project, or someone else here adapts it.

**Comment by OlyDLG** [comment]
OK, thanks.  TBC on #kivy (or do either kivy.garden or kivy.garden.graph
have their own channels?)

On Mon, Mar 2, 2015 at 11:21 AM, matham <notifications@github.com> wrote:

> The API with matplotlib would be for you to call mpl methods like you
> normally do with mpl, except the graph would show up in a kivy widget. So
> no, it'd not be a drop in replacement because currently you modify the
> Plot.points list, but with mpl you'd call e.g. plt.plot. However, I'm not
> sur ethat this is a significant difference?
>
> But I wouldn't expect to have a working prototype, even in alpha phase in
> the next few months, unless it's taken up as a GSOC project, or someone
> else here adapts it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/issues/3019#issuecomment-76789371>.
>



-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)

**Comment by matham** [comment]
Nop, it's on #kivy.

**Comment by OlyDLG** [comment]
OK, I just posted my question on #kivy.  Thanks!

On Mon, Mar 2, 2015 at 11:39 AM, matham <notifications@github.com> wrote:

> Nop, it's on #kivy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/issues/3019#issuecomment-76794637>.
>



-- 
David Lawrence Goldsmith (DLG)
Software Engineer
Fishery Resource Analysis and Monitoring Division
Northwest Fisheries Science Center – NOAA
2725 Montlake Blvd E.
Seattle, WA 98112
(206) 302-2420 <%28206%29%20860-3341> (w)
(360) 481-3800 (c)
