### ISSUE TITLE
Fullscreen broke after resize

### ISSUE THREAD

**Issue by Mythalorian** [kivy/kivy#3033]
Setting Window.fullscreen = "auto" works fine. And setting Window.fullscreen = False returns the window back to its previous size and state. However if you use your mouse to resize the window via the borders then set Window.fullscreen = "auto" you cannot bring it out of fullscreen mode with Window.fullscreen = False. Setting fullscreen to False has no visual effects on the window and it remains in fullscreen mode.

I checked to make sure the correct variable was being changed and that the fullscreen variable was indeed set to False. All were correct but no effect on the window itself.

This was run on Win 7 64-bit with python 2.7 and kivy 1.8

**Comment by dessant** [comment]
@Mythalorian could you check if this is still present in master?

The bug might be likely there if you use pygame, make sure to test with sdl2 too.

**Comment by Mythalorian** [comment]
I ran the code on the master. And fullscreen works even after resizing. Thank you for the tip. I test with just the master build. The window provider is still pygame so i dont know how sdl2 works with it yet.

**Comment by dessant** [comment]
Great! Thanks for the update.
