### ISSUE TITLE
Kivy Raspberry Pi 2 / Raspbian

### ISSUE THREAD

**Issue by fscz** [kivy/kivy#3057]
Was able to run most of the examples, however could not interact with the window nor close it.
Setting kivy.config.Config had no effect. It get's worse. The window is always maximized and you cannot close it with escape. Not even with Ctrl-Alt-F... This renders kivy unusable. 

Note however that the system keeps running. For example this will run the example for 10 seconds then close:

```
python example/tutorial/demo/main.py &
sleep 10
killall python`
```

I tried the following:

1 Set Config at top of main.py

```
from kivy.config import Config
Config.set('graphics', 'fullscreen', 0)
Config.set('graphics', 'borderless', 0)
Config.set('kivy', 'show_fps', 1)
Config.set('graphics', 'show_cursor', 1)
Config.write()
```

--> As far as I can tell, none of the above was applied, Window was fullscreen on all examples, cursor not visible, no fps. However basically the app seemed to run. For example the in the pong demo, the ball was going back and forth, gaining speed over time, etc.. 

2 Set the above options in ~/.kivy/config.ini
--> To no avail

3 Tried the whole thing with kivy 1.8
-> Same result

Does kivy 'work' on the Raspberry 1 / Raspbian? 
Well it does not on Raspberry 2. 
##

**Comment by fscz** [comment]
I had some time to kill and found out the following:

1. on_keyboard in the WindowBase class in kivy/core/window/__init__.py never get's alled
and therefore the code that terminates the application never is called

2. on_key_dow and on_key_up in WindowBase do get called. Not sure how this was intended, maybe window_egl_rpi.py should set something up. Maybe WindowBase should should handle this...

3. If you press the escape key, neither _on_window_key_down nor _on_window_key_up in the Keyboard class in kivy/core/window/__init__.py get's called. I have tried all the generic keyboard models 104 key, 105 key, intel, ... along with english (us) layout. The escape key never dispatches an event on the keyboard class. Probably the underlying event dispatcher _event.pyx expects some configuration criteria that aren't met here.

**Comment by lesio1025** [comment]
I have Kivy installed on pi 1 and there are the same problems
I use touch screen and on screen keyboard for my apps.
I want to install Kivy on pi 2 when I get one
Are there any problems with installation?

**Comment by fscz** [comment]
As of this moment the rpi 2 does not really have a working os. 
- You can install raspbian, however it is slow and stuttery - cannot recommend it.
- You also can install Ubuntu snappy - but that is pre-pre-alpha and you really cannot do anything with it.
- You can install Ryan Finnie's Trusty Port, see: http://www.finnie.org/2015/02/16/raspberry-pi-2-update-ubuntu-14-04-image-available/

As for the rpi 2 os future: I am uncertain at this moment, which will be the standard os for rpi 2. 

Generally I think that IF Canocial makes no more than a decent effort with it's existing armhf branch (accounting for some special rpi hardware, adding camera tools, etc) Ubuntu should quickly become the default os. However it is not clear IF they intend to do so - so rapbian might improve and finally run better on the rpi 2.

As of this moment I can definitely give the advice to not start development of applications targeting Windows 10 on raspi 2. Right now it is unclear when even the Desktop version will be released - the raspi version will be even later and Microsoft has not released anything yet about the specs of this embedded Windows 10 that is to be released for rpi 2.


As for kivy. I tried 1.9-dev on the rpi2 with raspbian. I got it to work basically, but I had to hack it a bit because it did not accept the escape key to quit the application. This is very bad because this means that you absolutely cannot make the window that sits even before the x-server. You can't even use ctrl-alt-fx
to switch to another tty. You have to do a cold restart. 

So as of this moment, you can hardly say anything close to kivy is "working" on rpi 2. However I think it will with a few months time.

**Comment by matham** [comment]
I'm facing similar issues with rpi3 as well.

**Comment by matham** [comment]
Alright, the escape issue should now be fixed with https://github.com/kivy/kivy/pull/4468. The fullscreen issue is still there though. You can use the touchring module to show the touch pos. For me though, the pos was slightly wrong.

**Comment by Julian-O** [comment]
@fscz: Some of the issues here have been fixed. Are there any that still remain?
