### ISSUE TITLE
[TextInput] [User regression] keyboard_on_key_down() called twice for each keystroke

### ISSUE THREAD

**Issue by SenshiSentou** [kivy/kivy#3059]
Hi all,
I'm currently using a 1.9 build with the new OSX packaging and noticed this issue which wasn't present in 1.8.1. Given the following code:

    class IntInput(TextInput):
        def keyboard_on_key_down(self, window, keycode, text, modifiers):
            print(keycode, text)
            super(IntInput, self).keyboard_on_key_down(window, keycode, text, modifiers)

The expected output for the successive keystrokes "1", "2" and "3" would be:
    ((49, '1'), u'1')
    ((50, '2'), u'2')
    ((51, '3'), u'3')

Instead, we get:
((49, '1'), None)
((u'1', ''), u'1')
((50, '2'), None)
((u'2', ''), u'2')
((51, '3'), None)
((u'3', ''), u'3')

This isn't *really* a problem, but it is very unexpected and counter-intuitive. `insert_text()` doesn't complain about passing in `None`, but other functions (or in my case, a regex parser) might.

**Suggested solution:** Either combine the two calls back into one (`((49, '1'), u'1')`), or add a note in the documentation about this.

Cheers,
Patrick

**Comment by denys-duchier** [comment]
it seems to happen when using SDL2
