### ISSUE TITLE
clang error:  unknown argument: '-mno-fused-madd'

### ISSUE THREAD

**Issue by sanfx** [kivy/kivy#3073]
When user on OSx Mavericks or above with Xcode installed tries to install kivy using I get error clang error:  unknown argument: '-mno-fused-madd', this is because the kivy is compiled and tested with gcc 4.2 if I am not wrong, but on OSx uses llvm-gcc (gcc front-end with llvm code backend) and clang (clang front-end with llvm backend). where the argument  -mno-fused-madd is not supported and it fails. However partly Apple's issue which they say in docs it should be warning message but it breaks the code giving an error instead. the temporary fix is export ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future" which then shows the warnings as documented but if you can check with OSx builds Lion and beyond you would probably spot it and setup that clang error doesn't happens at all.
##

**Comment by Julian-O** [comment]
@sanfx: Is this problem still happening? I assume it has been fixed by Apple in the meantime.

**Comment by sanfx** [comment]
I stopped using Mac OSx , so not a problem.
