### ISSUE TITLE
request keyboard expects password attribute

### ISSUE THREAD

**Issue by olymk2** [kivy/kivy#3076]
I would have patched this but i was not sure where to look for this android.pyx.

I looked at the file that i had from a generated file with buildozer and could see that it was doing target.password test but target is your widget which may not have this attribute so it just dies when running on a phone

python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 442, in  
File "_android.pyx", line 230, in android._android.show_keyboard (android/_android.c:2872)
AttributeError: object has no attribute 'password'

https://github.com/kivy/kivy/blob/master/kivy/core/window/window_pygame.py#L442

Happy to patch if some one wishes to point me at the android.pyx file, is it part of kivy or another project ?

**Comment by victor-rene** [comment]
I am totally unsure about this. My wild guess is that python-for-android installs the android module automatically. Therefore the android.pyx file you are looking for must be https://github.com/kivy/python-for-android/blob/master/recipes/android/src/android/_android.pyx

Not sure if or how it's relevant to the issue, but I hope it helps. Good luck.

**Comment by olymk2** [comment]
that explains why i could not find it, i guess the question is what shoule the correct fix be ?

we could put in getattr method to test, or you just have to add the attribute to any widget you bind to my guess is only TextInput has password attribute.

keyboard_suggestions has the same issue as well in that its not available on all widgets

https://github.com/kivy/python-for-android/blob/master/recipes/android/src/android/_android.pyx#L230-L239

**Comment by akshayaurora** [comment]
I guess you are using focusbehavior on android? This should be fixed now, I didn't think some one would actually need FocusBehavior on android but I guess there are use cases.

**Comment by akshayaurora** [comment]
Update your py4a, or clean using bulldozer and re-build. Reopen if the issue still persists

**Comment by olymk2** [comment]
cool you beat me to it, i shall try later tonight but it looks like it should fix the issue.

The main reason is for support on desktop and mobile you may want shortcut keys for a widget and not text input, obviously that will not work that well on mobile unless its a tablet with external keyboard.
