### ISSUE TITLE
touching a widget, dragging outside of the widget and releasing causes on_touch_up on the widget

### ISSUE THREAD

**Issue by fscz** [kivy/kivy#3081]
fix this by amending the for loop in kivy/base.py : post_dispatch_input
like so:

    for _wid in me.grab_list:
        # it's a weakref, call it!                                                                                                                                                        
        wid = _wid()
        if not wid.collide_point(me.pos[0], me.pos[1]): # hittest
            continue # if negative do nothing

**Comment by dessant** [comment]
This happens by design, use ButtonBehavior with on_press/on_release if you need collision detection.
