### ISSUE TITLE
adding two labels in a grid layout with different sizes triggers Label.on_size repeatedly

### ISSUE THREAD

**Issue by mkraemer67** [kivy/kivy#3084]
We noticed due to debugging output:
[CRITICAL          ] [Clock       ] Warning, too much iteration done before the
next frame. Check your code, or increase the Clock.max_iteration attribute

code is:
gt_layout = GridLayout(rows=1, spacing=10, size_hint_y=None)
text1 = "[color=888888][b]" + "[/b],[b] ".join(a) + "[/b][/color]"
self.label1 = MultiLineLabel(text=text1, markup=True, font_size="14sp")
gt_layout.add_widget(self.label1)
text2 = "[color=888888][b]" + "[/b],[b] ".join(b) + "[/b][/color]"
self.label2 = MultiLineLabel(text=text2, markup=True, font_size="16sp")
gt_layout.add_widget(self.label2)

This does not occur when sizes are equal.

Note: labels are MultiLineLabel we implemented, but we think it is not the issue as we simply set some properties there.

class MultiLineLabel(Label):

    def __init__(self, **kwargs):
        super(MultiLineLabel, self).__init__(**kwargs)
        self.text_size = self.size
        self.bind(size=self.on_size)
        self.size_hint_y = None

    def on_size(self, widget, size):
        self.text_size = size[0], None
        self.texture_update()
        if self.size_hint_y is None and self.size_hint_x is not None:
            self.height = max(self.texture_size[1], self.line_height)
        elif self.size_hint_x is None and self.size_hint_y is not None:
            self.width = self.texture_size[0]

**Comment by victor-rene** [comment]
Okay, I am not sure about what I am saying there, but I feel like there are certain inaccuracies.
Is binding size to on_size necessary? Normally Kivy does this behind the scenes.
Secondly, you modify the size of the widget in the event handler causing infinite recursion.

I mean you really wrote : if my size changes, I will will change my height (or width) which will cause my size to change again, etc...

Hope it helps.

**Comment by mkraemer67** [comment]
Yeah, reading the code after sleeping certainly changes my thoughts... LOL
Thanks for your help, sorry for bothering.
