### ISSUE TITLE
(pygame parachute) Segmentation Fault Abort trap: 6

### ISSUE THREAD

**Issue by Sybrand** [kivy/kivy#3085]
Segmentation fault. Running MacBook Pro 13-inch, Mid 2012. OS X 10.9.5

https://gist.github.com/Sybrand/1196f0fad4d5900be4eb

**Comment by Sybrand** [comment]
Same box - upgraded to OS X 10.10.2

**Comment by lp76** [comment]
Same here. OSX 10.9.5 - Python 2.7.5

**Comment by tito** [comment]
It will crash if you run your app on the secondary screen. This is an issue in Pygame / SDL, which is solved with the recent Kivy 1.9 / latest SDL2.

If it's not the case, please re-open :)

**Comment by lp76** [comment]
I can confirm that the crash happens only on the secondary screen

**Comment by akshayaurora** [comment]
This is a issue with pygame based on sdl1.2  The actual issue is in sdl1.2.
This is fixed by either using a different window provider like X11 or sdl2
available in master or making sure to launch the app on the primary monitor.
