### ISSUE TITLE
Unable to get a Window, abort. kwargs not swallowed by EventDispatcher

### ISSUE THREAD

**Issue by FeralBytes** [kivy/kivy#3091]
[Crash Log](https://gist.github.com/FeralBytes/8145eb3db355e0860920)
Relevant Discussion:
(05:48:21 PM) kived: ah. yes, that's a bug
(05:48:48 PM) kived: recent change to the code which prevents kwargs from being swallowed by EventDispatcher, so they can be passed to another base class
(05:49:06 PM) kived: i worried that this might happen, but it didn't seem to in testing
(05:50:40 PM) kived: wolfrage: please submit an issue on github, reference PR #3037
(05:50:50 PM) wolfrage: kived: OK
(05:51:20 PM) matham: kived, but which param is responsible for that?
(05:51:53 PM) matham: I don't see the param that is not swallowed
(05:52:09 PM) matham: but anyway, that's a bug with the code, not pr, right?
(05:54:37 PM) kived: matham: dunno. but it's a change in behavior, previously it was ok to provide bogus kwargs
(05:55:15 PM) kived: just figure it should be discussed - and keeping it this way is a valid solution of course
(05:55:45 PM) matham: it's one of these args that is not accepted by it: https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L572
(05:58:38 PM) matham: hmm all of the args added there are kivy props
(05:58:50 PM) matham: I wish we could see exactly what the kwargs is

**Comment by matham** [comment]
This is likely because the `force` param is added to kwargs at https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L524, but force is not a kivy property so EventDispatcher doesn't eat it.

**Comment by FeralBytes** [comment]
Latest daily still exibits the same [crash as this](https://gist.github.com/FeralBytes/7a1ce1172197d601155f). I will wait for it to update again and then try again. Is there any way to know if the latest daily build contains the patch above? Still using the same Pong Game example.

**Comment by FeralBytes** [comment]
Other relevant details.
Linux Mint 17.1 x64 Python 3.4

**Comment by matham** [comment]
That's because we haven't fixed the __no_builder issue in master.
