### ISSUE TITLE
Replace sample media with cleanly licensed media.

### ISSUE THREAD

**Issue by merriam** [kivy/kivy#3110]
Cleaning up licenses is just work.  

Kivy comes with copyrighted media, media without any attribution, and media with complicated licenses.   Most of this media is located in the examples directory.   The media choices are arbitrary and can be replaced by some equivalent public domain work from the Internet Archive or other 'safe' sources.   Having clean licenses makes it easier for a company to actually use Kivy in production.

For example:
- examples/widgets/softboy.mpg and examples/widgets/softboy.png.  This is a 1.5 Mb, ISO MPEG v4 system, version 1.0 clip that is copyrighted (and marked) by Artificial 3D.  This is an example of a copyrighted work.
- examples/widgets/sequenced_images/data/images/ contains a set of images of unknown providence.  This is an example of unattributed work.
- examples/widgets/lists/fruit_images/ contains various sized JPEGs of fruit.  The kiwi fruit, and presumably others, are under a CC - Attribution - Share Alike, with some ambiguous attribution requirements.  Follow the links in examples/widgets/lists/fruit_images/fruit_image_attribution.txt to figure it out.  This is an example of a complicated license.

Finding replacement images requires no programming knowledge, just a bit of patience.  For example, the Internet Archive has a selection of Public Domain work which can be incorporated under any 
license.  The end goal would be to have a list of all the media, providence, and license on one documentation page.  This could be an easy way to help Kivy progress.
##

**Comment by dereks** [comment]
+1 important

**Comment by KeyWeeUsr** [comment]
Do we need exactly `.mpg` file, or could it be [something else](https://videos.pexels.com/popular-videos)? After the video only the gifs+zips would remain on the todo list.

**Comment by KeyWeeUsr** [comment]
Fixed in PRs above.
