### ISSUE TITLE
The ogg plugin is missing from gstreamer in the new IOS toolchain 

### ISSUE THREAD

**Issue by schoolsplay** [kivy/kivy#3113]
IOS emulator log:
...
[WARNING           ] [Audio       ] Unable to find a loader for <./lib/CPData/game/marking/good.ogg>
....

The ogg in question is a proper ogg which plays correctly in Linux, Windows and Android (kivy launcher).
If you need more info just let me know, I have a fresh Imac 10.10.2 set aside for Kivy IOS building.

**Comment by tito** [comment]
I'll close this one as it's not under the control of Kivy itself, but more into the toolchain project. Thanks for reporting it!
