### ISSUE TITLE
kwargs ignored if property set via kv

### ISSUE THREAD

**Issue by kived** [kivy/kivy#3118]
````python
import kivy
kivy.require('1.8.1')

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.button import Button

Builder.load_string('''
<Button>:
    text: 'bad'
''')

class TestApp(App):
    def build(self):
        return Button(text='good')

if __name__ == '__main__':
    TestApp().run()
````

**Comment by AlbericC** [comment]
Also on kivy 1.8.0

**Comment by tito** [comment]
Unsure about this one. I guess kv > py instanciation right now. Inverting it might cause other side effect as well, but i guess your approach seems the right one

**Comment by denys-duchier** [comment]
with kv, a root rule is always applied last (after all the matching rules).  by analogy, the kwargs in an explicit widget instantiation should be considered like the contents of a root rule.  therefore they should be applied last (rather than in EventDispatcher.__init__)

**Comment by denys-duchier** [comment]
while preparing a fairly obvious patch for this issue I discovered there was a not so obvious case:

`ListView.__init__` augments `kwargs` with an `adapter` key before passing it on to super i.e. to `AbstractView` where `adapter` is a property... very amusing... I'll have to tweak that patch

**Comment by denys-duchier** [comment]
Here is a proposed fix https://github.com/kivy/kivy/pull/3138

I used this to test it (a modification of kived's with a css rule thrown in):

```
import kivy
kivy.require('1.8.1')

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.button import Button

Builder.load_string('''
<Button>:
    text: 'bad'

<.foo>:
    color: 1,1,0,1
''')

class TestApp(App):
    def build(self):
        return Button(text='good',cls=("foo",))

if __name__ == '__main__':
    TestApp().run()
```

**Comment by akshayaurora** [comment]
Thinking more about this, I agree with tito, this is how it should be. Events and properties are set after widget instantiations  through kv and kv > py in this regard. 

So kv properties are set after the initialization, this is normal and expected behavior since a long time. Is there a valid reason to reverse this behavior?

This is how I expect things to be and it is intuitive that things set in kv take precedence over widget initialization(widget is initialized then kv rules/props are set), the other way around will be highly unintuitive.

**Comment by dessant** [comment]
The result is that one cannot override default values set in kv at instantiation, but has to update the prop after that.

See this case:

```python
from kivy.app import App
from kivy.factory import Factory


class TestApp(App):
    def build(self):

        spinner = Factory.Spinner(background_normal='image.jpg')
        # prints 'atlas://data/images/defaulttheme/spinner'
        print(spinner.background_normal)

        button = Factory.Button(background_normal='image.jpg')
        # prints 'image.jpg'
        print(button.background_normal)

        return spinner

if __name__ == '__main__':
    TestApp().run()
```

It does not print `image.jpg` for the spinner. I don't find this intuitive, but unexpected and confusing.
