### ISSUE TITLE
Keyboard behavior in select_for_key_down elides over pauses, combining keys.

### ISSUE THREAD

**Issue by merriam** [kivy/kivy#3120]
The design of 'select_for_key_down()' in behaviors.py allows for multiple key strokes to be returned.  For example, running examples/widgets/compound_selection.py, typing "13" first sees an input of '1' and then aggregates it for a second input of '13'.   However pausing will randomly reset the typing button, so waiting a few seconds and typing '13' again returns aggregates of '131' and '1313'.   It should have reset and returned '1' and '13' as before.

The issue is calling time.clock() instead of time.time().  A fix can be found in https://github.com/merriam/kivy/commit/d735622ad5802d6d42a2a739ab83a7521a34e6d4, an
unmerged PR.

**Comment by tito** [comment]
Hi @merriam,

I saw you answered to a numerous issues referencing your closed PR. Just to be sure, we never intented to reject your work, but submitting thousands of files with unrelated changes is not going to work. It is making the exchange harder, as we (as maintainer) can delay the merge until all the fixes are "ok", which can delay all the fixes that were ok as well.

Tiny atomic commit are the key for a single bug fix, or a bunch of commit on the same new features / refactoring, as long as it's the exact same subject.

On this specific issue, thanks again for finding it and providing a fix, you can resubmit a PR by doing this step:

- Fetch all the latest ref in master: `git fetch -a`
- Create a new branch: `git checkout --track -b fix-3120 origin/master`
- Pick only this commit and merge it into the new branch: `git cherry-pick d735622`
- Publish your branch on your repo: `git push origin fix-3120`
- Then, go back to github, and it should show you the possibility to create a PR from your newly fresh branch: fix-3120.

Thanks you :)

**Comment by merriam** [comment]
Hi Mathieu,

Thank you for your kind note.   It does appear from previous exchanges that
the intent is indeed to reject any work I directly submit.  The larger
block of changes was submitted because every smaller block was nit-picked,
ignored, or randomly closed.   The nit-picks, usually about the number of
spaces after a period in comments, do not appear to be about the quality of
the submission, any errors, or any substantive issue.   In fact, each PR I
submit usually fixes these nits in other's accepted PRs.

I provide tiny, atomic commits.   I tried side-stepping the PR nit problem
by putting many commits in one PR.   As each uncommitted pull request is a
separate branch, I need to provide a reasonable limit to the number of open
and disputed Pull Requests.   I set that at about five or six.

As I enjoy coding, building, and fixing, I intend to continue fixing bugs
and cleaning up the /examples directory.   As I have already played the
sequence of "please resubmit a fix; and again; and again; and now it will
rejected just because", such as with examples/audio, I do not intend to
rebundle or resubmit these.   I'll reference them, and others may choose to
do so.  If I can be persuaded that the games would stop, I could put one or
two commits per PR as is my normal habit.

Thank you for your understanding,

Charles

**Comment by tito** [comment]
I don't really understand your issue, i see that others already explained why the few refused PR have been closed, mostly due to an invalid git history. This can be sorted out, i don't think what you were trying to resolve was the issue.

Maybe we can help you to find which part in your git process is polluting the PR, and make us stop to merge it; Except the audio example pr which has been refused, two others have been refused due to a mess into your git branch (core_stbtext, i guess at some point you tried it and merge it into your master?), and all the rest have been merged :)

In my point of view, you're doing it good, just a mess with git, which can be solve out ^^

**Comment by kived** [comment]
@merriam 39 of your 53 PRs were merged (and it looks like quite a few of the unmerged ones were closed by yourself). I don't see how that qualifies as intending to reject **any** work you submit. But if you submit a PR which has something like double spaces, which we will want to fix, then you are just creating more work for other people.

Also, many things you seem to think are "nitpicking" are not at all - like rejecting PRs where you add and remove big files. You do realize that everyone still has to download the big file when you do that, even if you remove it in a later commit? And that file will always be in the repo? Unless that commit is removed in a rebase and the master branch is force pushed (generally a very bad idea), the file will never go away. That's the way git works. Leaving that commit in the repo at all is a disservice to our users, especially ones who are in areas with slow Internet connections.

It's also not ok to ask us to merge a PR when you know there is an issue with the PR and just saying "I'll submit another PR to fix that." You could easily push a commit with the fix to the original PR, and then ask us to merge it.

It really feels like you're just trying to cause problems at this point.
