### ISSUE TITLE
Download page and instructions outdated

### ISSUE THREAD

**Issue by cartwrightluke** [kivy/kivy#3121]
The download page and download instruction pages need updating wrt fedora. The repositories for fedora 16-18 have been removed, 19 is also gone, and only 20 exists (but is not listed on the download page).

Pages to modify:
http://kivy.org/#download
http://kivy.org/docs/installation/installation-linux.html#fedora

Obsolete / 404:
http://download.opensuse.org/repositories/home:/thopiekar:/kivy/Fedora_16/
http://download.opensuse.org/repositories/home:/thopiekar:/kivy/Fedora_17/
http://download.opensuse.org/repositories/home:/thopiekar:/kivy/Fedora_18/

Needs adding:
http://download.opensuse.org/repositories/home:/thopiekar:/kivy/Fedora_20/

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy-website.
