### ISSUE TITLE
Resizing & Moving window in Gnome causes weird behavior

### ISSUE THREAD

**Issue by meZee** [kivy/kivy#3140]
**Addl. Info from #kivy IRC**

> SwedFTP - Does anyone else have issues resizing kivy windows? If I resize the window from the bottom left corner it increases 40px vertically repeatedly.
> dessant - swedftp: on gnome?
> SwedFTP - dessant, indeed
> dessant - version?
> dessant - of gnome and kivy
> SwedFTP - 1.8.0 kivy, one moment
> SwedFTP - 3.14.2-1 via ArchLinux's Extra repo
> SwedFTP - is the version of gnome-desktop
> dessant - i can confirm with the same versions and the bug is in kivy master also
> dessant - the difference that i'm on debian
> dessant - could you open an issue?
> SwedFTP - dessant, sure can, just wanted to confirm it.
> dessant - thanks

**Kivy Output -**
https://gist.github.com/meZee/6db82d1353c85843908e

**Description -**

Resizing a Kivy window from the bottom right, and moving the window after snapping to half of the desktop caused the window to erratically move(sometimes offscreen) & increase in size indefinitely by fixed increments(```x += 2``` && ```y += 40```) in either/or both the x & y axes depending on how you induce the bug.

**Steps to Reproduce** -

* Erratic Movement & Indefinitely increase  ```y += 40```
  1. Click & hold the bottom right diagonal resize point
  2. Slowly increase the horizontal size.

* Erratic Movement & Indefinitely increase  ```x += 2```
  1. Click & hold the bottom vertical resize point
  2. Slowly increase the horizontal size.

* Erratic Movement & Indefinitely increase both ```x += 2``` && ```y += 40```
  1. Snap window to either half of the desktop.
  2. Move via Title bar

**Affected Distro's/Software -**

* Gnome(3.14.2)
  * Archlinux(x86_64)
  * Debian(see IRC transcript above)

**Comment by kived** [comment]
Unfortunately, this seems to be an issue in pygame. The pygame ["WindowResizing" demo](http://www.pygame.org/wiki/WindowResizing?parent=CookBook) does the same thing.

As the last release of pygame was almost 6 years ago, and it uses SDL1, we have been moving away from it in favor of SDL2. I would recommend using the development version of Kivy with SDL2 on this version of Gnome (you may be able to use the [daily PPA](https://launchpad.net/~kivy-team/+archive/ubuntu/kivy-daily), though it's built on Ubuntu).

There is another similar resizing issue with Kivy on SDL2 and Gnome Shell, but I have submitted a fix for that in PR #3148.
