### ISSUE TITLE
ButtonBehavior.on_touch_up dispatches on_release immediately

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#3155]
ButtonBehavior.MIN_STATE_TIME defines a minimum time the button stays in down state. But the on_release event gets dispatched immediately. Imo it would be better to defer the event dispatching as well to ButtonBehavior._do_release, at least on demand.

Any objections?

-r
##

**Comment by Julian-O** [comment]
Here is the code from `button.py`, written later in 2015, that implements this.
```
        touchtime = time() - self.__touch_time
        if touchtime < self.min_state_time:
            self.__state_event = Clock.schedule_once(
                self._do_release, self.min_state_time - touchtime)
        else:
            self._do_release()
        self.dispatch('on_release')
        return True
```
Closing as fixed, but if the problem persists, let us know.
