### ISSUE TITLE
Simplify the canvas and similar API's

### ISSUE THREAD

**Issue by OlyDLG** [kivy/kivy#3157]
After about 6 weeks of using Kivy (with mixed success, especially with respect to using kvlang) I've found the API of certain parts of it much more intuitive--in the sense of getting the results I expect--and easier to use--in the sense of getting the results I want--than other parts.  The primary example (for me) of the former (easy and intuitive) is the nesting of layouts and placement of widgets therein; the primary example of the latter (refractory and confusing) is knowing where (i.e., in what layout, widget, or attribute/property) and how to set property values, especially those set through the canvas property (e.g., this exchange on the #kivy IRC channel starting at 17:51 UTC on 2015-03-16:

\<kived\>: OlyDLG_: and no, there are no color words in kivy. you can always set your own in a python file and #:import them to use in kv
for a checkerboard, off the top of my head something like this might work: background_color: (1, 0, 0, 1) if self.parent and self.parent.children.index(self) % 2 else (0, 1, 0, 1)

\<OlyDLG_\>: so canvas.before:\n____background_color:\n________Color: (1,0,0)\n________Rectangle: width, height\n in kvlang? How 'bout in Python?

\<kived\>: with canvas.before: Color(1, 0, 0); Rectangle(size=(width, height))
well, really, Color(*self.background_color) and \`Color: rgba: self.background_color\`

i.e., kived wasn't sure how to do it at first, and when he finally did settle on how it should be done, the API was quite a bit different (at least, IMO) than what he had originally guessed).

I would like to propose/request that the API be made more uniform, in the direction of the comparatively more simple one used by widget/layout placement, sizing, and nesting.  I'm not sure how to do this in detail: perhaps a widget could "share," i.e., have direct access to, the attributes of its canvas so that one can access these without being obliged to go through the canvas property explicitly?  But maybe I'm not sufficiently understanding the mechanics required; my point is, some of Kivy's API is pretty easy to learn and use, some of it much less so (I've tried to indicate which is which, IMO), and this inconsistency is highly productivity-hindering.

**Comment by inclement** [comment]
I'm not clear on the issue. It looks like kived is referring separately (and with correct syntax in both cases) to python and kv code.

What change to canvas behaviour are you proposing? Could you give an example?

**Comment by OlyDLG** [comment]
I'm not proposing any behavioral changes, I'm proposing changes to the API (application program interface), changes (or additions) to the _way_ programmers can "direct" and affect certain Kivy objects.  It's hard for me to make myself understood to someone who knows/understands Kivy deeply and for whom everything in Kivy is as they feel it should/needs to be, but in surfing comments, I know I'm not alone: I've read one commentator declare that they "fear" kvlang and avoid it like the plague because of how much difficulty they had accomplishing anything with it (they continue to use Kivy, just in pure Python exclusively).  I would also refer you to Jacob G.'s reply to the Survey on improving the doc--I'm not positive he would agree w/ me, of course (actually, I think I'll email him and ask), but I think an even better solution to the problems he raises, for example, would be to improve, before the doc, the API for instructing Kivy to do the things he opines should be better documented.  Again, I feel like the beginning Calculus student--who has sufficient algebra, geometry, etc.--who is trying to make his PhD research mathematics professor, for whom every word out of his mouth is crystal clear and unambiguous, understand what is unclear about what he (the professor) is saying.  I hope you (and/or other Kivy devs) will take these concerns and ideas seriously, not dismiss them because they aren't concrete and/or well-jargoned enough, and perhaps try to see the API through the eyes of someone who didn't write it and doesn't understand it inside and out.  Thanks for your time and serious consideration.

**Comment by inclement** [comment]
I don't intend to dismiss your concerns, but I dont' understand what they are. Are you able to suggest e.g. a change in syntax that would represent your views?

**Comment by kived** [comment]
In fact, I was referring to three separate topics in that exchange: 1) are there "color words" in Kivy, 2) how to make a checkerboard pattern, 3) how to make a `background_color` property.

I don't want to make you feel like we're ignoring this though. :) Could you give a concrete example? Like of kv or Python code which works right now, and an example of kv or Python code which you think is the way it should work.

**Comment by OlyDLG** [comment]
OK, well for starters, why all the explicit references to the canvas: if the object sitting on top of the canvas doesn't have the referenced property, and setting the canvas property is what is required to effect a visible change in the object, why can't the API by-pass explicit reference to the canvas?  So, (even if it is the canvas that's being effected), one just says, in Python: label.background_color = <color>, instead of all this intermediate canvas mumbo-jumbo--one doesn't "see" the canvas, one sees the label, so it's much more intuitive (IMO) that one would set attributes that one sees directly through the object one sees, not through some underlying abstract object.  

Since we're talking about canvas (admittedly, per my choice), a painterly analogy seems appropriate. The way I look at it, a screen is analogous to a collage: a collage is something that is composed on top of a "canvas" (which may be a base piece of paper instead of actual canvas; I trust you see that the canvas material is irrelevant in this analogy) from pieces that are already "rendered" before they're placed on the canvas.  If I want a blue flower on top of a specifically-shaped green background as a component of my collage, I (probably) don't paint that green shape on the canvas and then paste the blue flower on top of it; rather, I construct the green shape from some media, "paste" the flower to it, and paste that combination on the canvas (or paste the background first and then the flower on top of that--the order doesn't--and shouldn't--matter, i.e., the "pasting operation" should be associative, in the order-of-operations sense of the word).

So that's one concrete, specific example of where I would hope the (complicated canvas) API could be made more like the (more straightforward) size and position API, where simply assigning an intuitive value to the intuitive property produces the intuitive result (which is what I think of as being "Pythonic").  But I'm sure that if you comb the language--and more so the extant Issues and comment repositories--you'll be able to identify many more pieces of the API that are similarly, unnecessarily (I would like to think) complicated; off the top of my head, the whole ids API--which Jacob G. cited as problematic--is another such example.

**Comment by Kovak** [comment]
You may find it valuable to look through the actual definitions of existing widgets in KV:
https://github.com/kivy/kivy/blob/master/kivy/data/style.kv

The reason you must reference the canvas is becaue by default Label have no conception of a background color, you are actually wanting to introduce a new type of Label with an additional set of instructions not actually contained within the original Label widgets definition. Canvas is the api for introducing such new graphical instructions. Canvas is in fact the api you are describing as what you desire and it would probably be of great help to look into how existing widgets define themselves and observe various properties to provide a simple pythonic api for controlling the instructions.

**Comment by kived** [comment]
I think you're missing an important point here. **Everything** drawn on the screen is in a `canvas`. **Everything.** Widgets are essentially an abstraction of canvas functionality, doing things like adding a label texture to the canvas, setting the text color, etc.

To use your painter analogy, think of `canvas` as the painter's canvas, and `Widget` as a paint-by-numbers you can use to draw on that canvas. The only difference is that with Kivy's implementation you can add your own numbers as well.

**Comment by OlyDLG** [comment]
Kovak: OK, thanks for the tip.  

Evidently, you can close this Issue as "won't fix."
