### ISSUE TITLE
[Core] Clipboard not working in 1.9

### ISSUE THREAD

**Issue by SenshiSentou** [kivy/kivy#3158]
Hi everyone,

I noticed my clipboard functionality stopped working and managed to verify it with this simple script:

    from kivy.core.clipboard import Clipboard
    print Clipboard.get_types()
    Clipboard.put('Great', 'text/plain')
    print Clipboard.get('text/plain')

The output:

    >>> text/plain
    >>> None

(Also note that `get_types()` actually seems to return a string here, rather than a list.)

**Kivy:** 1.9 dev, new packaging build by @tito
**Provider:** [Clipboard   ] Provider: sdl2(['clipboard_nspaste'] ignored)
**Possibly related task (?):** #2743

Thanks as always,
Patrick

**Comment by inclement** [comment]
This seems to be because the sdl2 clipboard is almost just a dummy provider though the basic functions are implemented. I'll take a look.

**Comment by inclement** [comment]
Okay, the direct issue is that the sdl2 clipboard doesn't implement get and put, just copy and paste - these are the intended interface. However, I get segfaults when calling these.

**Comment by akshayaurora** [comment]
closed via https://github.com/kivy/kivy/commit/ea615a4f60ffcd49e5580438532355c296061ed6
