### ISSUE TITLE
Application Prematurely Exits When Packaged As Application (app)  [$100]

### ISSUE THREAD

**Issue by jtownley** [kivy/kivy#3183]
After using pyinstaller to wrap an application, the application runs for approximately 7 seconds and closes.

OSX Yosemite 10.10.2
cython 0.21.2
pygame installed via pip install hg+http://bitbucket.org/pygame/pygame
kivy clone of master
pyinstall version 2.1
SDL stuff for pygame installed via homebrew.

I have a repo here https://github.com/jtownley/kivyMacBuild with a script the sets up the environment and reproduction steps.

running the app via lldb (mac gdb)

    lldb dist/HelloWorld.app/Contents/MacOS/HelloWorld 
    (lldb) target create "dist/HelloWorld.app/Contents/MacOS/HelloWorld"
    Current executable set to 'dist/HelloWorld.app/Contents/MacOS/HelloWorld' (x86_64).
    (lldb) run
    Process 9029 launched: '/opt/git/kivyMacBuild/dist/HelloWorld.app/Contents/MacOS/HelloWorld' (x86_64)
    [INFO   ] [Logger      ] Record log in /Users/jtownley/.kivy/logs/kivy_15-03-23_22.txt
    [INFO   ] [Kivy        ] v1.9.0-dev
    [INFO   ] [Python      ] v2.7.6 (default, Sep  9 2014, 15:04:36) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
    [INFO   ] [Factory     ] 173 symbols loaded
    [DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
    [DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
    [DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
    [INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
    [DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
    [DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
    [DEBUG  ] [App         ] Loading kv <./hello.kv>
    [INFO   ] [Text        ] Provider: pygame
    [INFO   ] [Window      ] Provider: pygame
    [DEBUG  ] [Window      ] Display driver Quartz
    [DEBUG  ] [Window      ] Actual window size: 800x600
    [DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a8
    [DEBUG  ] [Window      ] Actual depth bits: 24
    [DEBUG  ] [Window      ] Actual stencil bits: 8
    [DEBUG  ] [Window      ] Actual multisampling samples: 2
    [INFO   ] [GL          ] OpenGL version <2.1 NVIDIA-10.2.1 310.41.15f01>
    [INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
    [INFO   ] [GL          ] OpenGL renderer <NVIDIA GeForce GT 650M OpenGL Engine>
    [INFO   ] [GL          ] OpenGL parsed version: 2, 1
    [INFO   ] [GL          ] Shading version <1.20>
    [INFO   ] [GL          ] Texture max size <16384>
    [INFO   ] [GL          ] Texture max units <16>
    [DEBUG  ] [Shader      ] Fragment compiled successfully
    [DEBUG  ] [Shader      ] Vertex compiled successfully
    [DEBUG  ] [ImageImageIO] Load </opt/git/kivyMacBuild/dist/HelloWorld.app/Contents/MacOS/kivy_install/data/glsl/default.png>
    [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
    [DEBUG  ] [Resource    ] add </Library/Fonts> in path list
    [DEBUG  ] [Resource    ] add </System/Library/Fonts> in path list
    [DEBUG  ] [Resource    ] add </Users/jtownley/Library/Fonts> in path list
    [DEBUG  ] [Resource    ] add </opt/git/kivyMacBuild/dist/HelloWorld.app/Contents/MacOS/kivy_install/data/fonts> in path list
    [INFO   ] [OSC         ] using <multiprocessing> for socket
    [DEBUG  ] [Base        ] Create provider from mouse
    [INFO   ] [Base        ] Start application main loop
    [INFO   ] [GL          ] NPOT texture support is available
    Process 9029 exited with status = 0 (0x00000000) 
    (lldb)

**Comment by jegger** [comment]
I have the same issue on Yosemite. I have also tried building the app on 10.9.5 (where it is working) and launching it in 10.10 - but same behavior.

**Comment by jtownley** [comment]
I have just tested this with all the latest Kivy and this issue still persists.

**Comment by springermac** [comment]
I have opened a pull request against the above linked repo with a fix that works for me.
The gist of the fix is to upgrade to PyInstaller 3.0.

**Comment by akshayaurora** [comment]
Using latest Pyinstaller release or using the new Kivy.app self contained distribution seems to be working for people.
