### ISSUE TITLE
[KV lang] Property of 'self' needs to be referenced in order for if-statement to work.

### ISSUE THREAD

**Issue by SenshiSentou** [kivy/kivy#3188]
Ok, I am at wit's end here.. A part of one of my apps stopped working in the new version of Kivy, but I can't seem to pinpoint or even isolate or reproduce the problem. Assume the following KV code, used to draw a Widget with a guaranteed parent:

    canvas.after:
        Color:
            rgba: [0, 1, 1, 1]
            Rectangle:
                pos: self.parent.pos if self.parent else [0, 0]
                size: [50, 50]

The result in my app is that this rectangle is drawn *sometimes*. If I restart the app 10 times, I would say I get it about 20% of the time, with nothing else changing. Just open, wait for the app to load, and close.

Now here's where things get fun! If I change to code to the following, it actually works 100% of the time!

    canvas.after:
        Color:
            rgba: [0, 1, 1, 1]
            Rectangle:
                pos: self.parent.pos if self.parent else [self.x, 0] #changed line
                size: [50, 50]

Note that the rectangle is still being draw at the position of `self.parent.pos` however! I can change the `else` part to any of the following, and it will still function as expected:

    pos: self.parent.pos if self.parent else [self.x - 9999, 0]
    pos: self.parent.pos if self.parent else [self.pos[0] - 9999, 0]
    pos: self.parent.pos if self.parent else [self.size[1], 0]
    pos: self.parent.pos if self.parent else [0, -self.x]

But it breaks when I use numbers only:

    pos: self.parent.pos if self.parent else [0, 0]
    pos: self.parent.pos if self.parent else [200, 123]

It seems as if, as long as *some property* of `self` is referenced in the `else` clause, the statement works as expected.

I've tried reproducing the problem in a test app, but it's just not happening... I don't feel too comfortable uploading my app here, but if any developer wants to take a look, just shoot me a message and I can mail it to you.

Does anyone have any idea what could be going on here?

Thanks,
Patrick

**Comment by matham** [comment]
You need to do some introspection to solve the issue. I suspect that either it gets bound to the wrong parent and hence is not updated, or the parent pos is not what you expect.

Basically, you need to do something like this and post or try to understand the results:

```
on_pos: print(self.parent, self.parent.size, self.parent.pos, self.pos. self.size)
canvas.after:
    Color:
...
```

**Comment by dessant** [comment]
It may be because rebind is not enabled by default for `parent`. https://github.com/kivy/kivy/issues/3529

Please reopen if rebinding still did not work.
