### ISSUE TITLE
Screen module broken in latest master with SDL2

### ISSUE THREAD

**Issue by tito** [kivy/kivy#3189]
Test with touchtracer:

    python examples/demo/touchtracer/main.py -m screen:droid2

Works with pygame, fail with SDL2.

**Comment by tito** [comment]
It seems to work just after a resize of the window.

**Comment by tito** [comment]
Actually, i got weird issue with window in general. Using --size 320x240, 1024x900, etc, doesn't works. Some does, others not. I don't find any clue about it...

**Comment by tito** [comment]
I ask for a windows 600x200, the SDL_CreateWindow(x, y, 600, 200), and then SDL_GetDisplayMode() returns 640x480. O_o

**Comment by akshayaurora** [comment]
@tito could you check this out https://github.com/kivy/kivy/issues/3189

**Comment by akshayaurora** [comment]
What's working on the above mentioned branch is::

Retina screen initially and on resize.
Non retina screen if primary is not a retina screen. 
Touch coordinates are also fixed for both types of screen

What's not yet working: Moving window from retina screen to non-retina screen currently doubles the widget size. will fix this shortly before I do a pr.

**Comment by akshayaurora** [comment]
closed by 6236de1fb1d06a2ffc61c8ed3d1917baee6c797b
