### ISSUE TITLE
When using native Python logging, a Kivy app will go into an infinite loop.

### ISSUE THREAD

**Issue by jtownley** [kivy/kivy#3191]
Basically if you importing native python logging or a module that uses native python logging. It gets caught in a log loop. 
This is similar to https://github.com/kivy/kivy/issues/825 
It is reproducible using the same code in the previously fixed bug at: https://gist.github.com/4157249

**Comment by kived** [comment]
That code does not have any issues for me with 1.9.0-dev (which is where any fixes would go). The app I work on has used native Python logging since Kivy 1.7.2. This was an issue in the past, but we resolved it by setting up logging before importing from kivy.

**Comment by jtownley** [comment]
http://pastebin.com/u5E3tXSR has example of the issue persisting on the latest dev version of 1.9.0

**Comment by jtownley** [comment]
Closing PEBKAC
