### ISSUE TITLE
Bad construction of documentation link to kv Builder

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#3197]
Builder = <kivy.lang.BuilderBase object at 0xaca510c> appears in online doc when getting the link http://kivy.org/docs/api-kivy.lang.html#kivy.lang.Builder

Not sure what's wrong here but it is definitely an error. Add doc tag please.

**Comment by tito** [comment]
It is not, it's the default instance of the BuilderBase that you can use. You have the same for Clock, Window, etc.

Or maybe you are saying something else?

**Comment by victor-rene** [comment]
Oh sorry, again something I am learning. Thanks for fast answer. I am closing.
