### ISSUE TITLE
#:import main main corrupts python code

### ISSUE THREAD

**Issue by cjaramilu** [kivy/kivy#3199]
The line "#:import main main" in the  kv file 
break the code  when  using ScreenManager.

I made this example to test it.
The variable app.foo  shows "good" if the first line of the kv file is commented
but shows "bad" when it is uncommented.

-------ktest.kv-------
```kvlang
#:import main main
#:import kivy kivy
#:import sys sys

<RootWidget>:
    HomeScreen: 

<HomeScreen>:
    name: "scr100"
    lab120: lab120k

    BoxLayout:
        orientation: "vertical"

        Label:
            size_hint_y: None
            height: "60dp"
            font_size: "25dp"
            text: "Test App"  

        Button:
            size_hint_y: None
            height: "60dp"
            text: "click herel"
            on_release:  root.f120_click()
            
        Label:
            size_hint_y: None
            height: "60dp"
            id: lab120k
            text: "empty"

        Label:
            text: "python version: %s\nkivy version: %s"  %  (sys.version,  kivy.__version__ )
```
-----main.py------
```python
from kivy.app            import App
from kivy.properties     import ObjectProperty
from kivy.uix.boxlayout  import BoxLayout
from kivy.uix.screenmanager import ScreenManager, Screen

class RootWidget(ScreenManager):          
    pass

class HomeScreen (Screen):                     
    lab120 = ObjectProperty()

    def f120_click(self):
        self.lab120.text =  app.foo

class KTest(App):
    foo = "bad"  

    def build(self):
        self.foo = "good"
        return  RootWidget()

app = KTest()
app.run()
```

**Comment by denys-duchier** [comment]
Some remarks off the top of my head.

Firstly, when run, main.py is executed as a script, not imported as a module; at that time widget classes are defined and registered; after which app.run() causes the root widget to be build, and thus ktest.kv to be loaded, which in turns now imports main.py as a module; the widget classes are redefined and reregistered.

the one thing that's not clear to me, is that you also should get 2 apps instantiated and run; and I have no clue what's supposed to happen in that case.

in any case, **never** import main.py.  If there is something in main.py that you need to import elsewhere; just move that stuff into a separate module and import it.

**Comment by cjaramilu** [comment]
I think you are right.... main.py is run twice.

when I fixed the last lines of main.py  the problem was gone.   

```python
if __name__ == '__main__': 
   app = KTest()
   app.run() 
```
