### ISSUE TITLE
kivy launch script broken on OS X

### ISSUE THREAD

**Issue by r1chardj0n3s** [kivy/kivy#3220]
There's a bash syntax error in the script:
```bash
  $ kivy main.py 
  /usr/local/bin/kivy: line 39: syntax error near unexpected token `fi'
  /usr/local/bin/kivy: line 39: `fi'
```
The fix is to add the missing "then" on the end of line 36. Happy to submit a PR but I can't find the script in any kivy repos...

**Comment by dessant** [comment]
This repo holds the os x scripts https://github.com/kivy/kivy-sdk-packager.

**Comment by tito** [comment]
@r1chardj0n3s are you still using bash? or have you replaced bash with something else?

**Comment by tito** [comment]
RIGHT, there is an issue, dunno why i didn't trigger it on my side. Rebuilding the package.

**Comment by r1chardj0n3s** [comment]
Thanks! (and yes, I'm using built-in OS X bash).

**Comment by tito** [comment]
Package rebuilt and uploaded, you can update it :)
