### ISSUE TITLE
Unable to get a Window, abort.

### ISSUE THREAD

**Issue by FeralBytes** [kivy/kivy#3225]
~~It appears [this issue #3002](https://github.com/kivy/kivy/issues/3002) has returned again, at least for me.~~ Upgraded to 1.9.1-dev from the PPA.
[Full Traceback](https://gist.github.com/FeralBytes/15918809e0e4544f1bcc)

Additional Information: 
sudo aptitude install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.

OS: Linux Mint 17.1 64-bit   Kernel: 3.14.0-24-generic   Python: 3.4.0

**Comment by kived** [comment]
This is unrelated to #3002. The error here is `sdl2 - TypeError: expected bytes, str found`, which is odd because `str` shouldn't even be able to be passed there -- the variable being passed is `cdef bytes`.

**Comment by FeralBytes** [comment]
sudo aptitude purge python3-kivy
The following packages will be REMOVED:  
  python-gst0.10{u} python3-kivy{p} python3-kivy-bin{u} python3-kivy-common{u} 
0 packages upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 9,166 kB will be freed.
Do you want to continue? [Y/n/?] y
dpkg: python3-kivy-bin: dependency problems, but removing anyway as you requested:
 python3-kivy depends on python3-kivy-bin (= 1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1).

(Reading database ... 238557 files and directories currently installed.)
Removing python3-kivy-bin (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
(Reading database ... 238525 files and directories currently installed.)
Removing python3-kivy (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
(Reading database ... 238269 files and directories currently installed.)
Removing python3-kivy-common (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
Removing python-gst0.10 (0.10.22-3ubuntu2) ...

sudo aptitude install python3-kivy
The following NEW packages will be installed:
  python-gst0.10{a} python3-kivy python3-kivy-bin{a} python3-kivy-common{a} 
0 packages upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 199 kB/2,334 kB of archives. After unpacking 9,166 kB will be used.
Do you want to continue? [Y/n/?] y
Get: 1 http://archive.ubuntu.com/ubuntu/ trusty/main python-gst0.10 amd64 0.10.22-3ubuntu2 [199 kB]
Fetched 199 kB in 8s (24.1 kB/s)                                                                                                           
Selecting previously unselected package python-gst0.10.
(Reading database ... 238197 files and directories currently installed.)
Preparing to unpack .../python-gst0.10_0.10.22-3ubuntu2_amd64.deb ...
Unpacking python-gst0.10 (0.10.22-3ubuntu2) ...
Selecting previously unselected package python3-kivy-common.
Preparing to unpack .../python3-kivy-common_1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1_amd64.deb ...
Unpacking python3-kivy-common (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
Selecting previously unselected package python3-kivy-bin.
Preparing to unpack .../python3-kivy-bin_1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1_amd64.deb ...
Unpacking python3-kivy-bin (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
Selecting previously unselected package python3-kivy.
Preparing to unpack .../python3-kivy_1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1_amd64.deb ...
Unpacking python3-kivy (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
Setting up python-gst0.10 (0.10.22-3ubuntu2) ...
Setting up python3-kivy-common (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
Setting up python3-kivy-bin (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...
Setting up python3-kivy (1.9.1-dev~daily0+201504030722-2708-testing61~ubuntu14.04.1) ...

Still same error.

**Comment by ahmadfarihan** [comment]
I also get a similar error after upgrading to 1.9.0 from the Stable PPA. Just a simple app displaying a button. Would run on 1.8.0 before.

Ubuntu 14.04 LTS.
Python 3.4.0
[Error Trace ](https://gist.github.com/ahmadfarihan/c646139499ec99ec5f87)

**Comment by ahmadfarihan** [comment]
Kivy finally works for me. I uninstalled the ubuntu kivy 1.9.0 stable package and all its dependencies. Reinstalling kivy 1.9.0 cython 0.21 via pip did the trick.

**Comment by kived** [comment]
Still not sure why this is happening, but it's related to the Debian build process. If I build the 14.04 PPA source directly (`make PYTHON=python3`) it works fine. If I build packages from the source (`dpkg-buildpackage -b`) and install them, then I run into this error.

**Comment by kived** [comment]
Alright, this is caused because the Python 2 version is built first, then the Python 3 version is built without cleaning the first build. I can duplicate this with my source folder if I build both versions without cleaning.

I've fixed the debian/rules to clean the build folder, but I'd like @thopiekar to check it and update the PPA build.

**Comment by thopiekar** [comment]
Great, thanks for the patch. Was the patch ever tested or is it a quick fix?
Is the tmp-build really needed? Wouldn't it be enough to build for a python version, clean the source and rebuild for the next python version?

**Comment by kived** [comment]
tmp-build is needed because debhelper will delete the tmp folder. I tested
building on Ubuntu 15.04 64-bit, and installed both py2 and py3 versions
and ran Showcase.

**Comment by thopiekar** [comment]
In this case feel free to merge it into pkg-debian-daily. When all builds
will work and this issue will be fixed we can think about adding it to
pkg-debian-stable, too. At the moment daily and stable use the same
packaging files.

**Comment by thopiekar** [comment]
Well, the problem is not exactly fixed by changing files in ```master```. I'm currently working on an alternative without moving tmp-build to tmp.

**Comment by thopiekar** [comment]
Can someone confirm the problem is fixed now? Just to be sure :smiley:

**Comment by FeralBytes** [comment]
Are the packages on Launchpad the most recent with fix in Stable or is it Master?

**Comment by thopiekar** [comment]
The fixes are in Daily (I think you meant that with Master).

**Comment by FeralBytes** [comment]
Daily on launchpad (Master) now works for me.

**Comment by thopiekar** [comment]
Great! :+1:

**Comment by FeralBytes** [comment]
Today I confirmed that Kivy Stable via Launchpad now works too. So this issue is completely resolved. Thanks @thopiekar.
