### ISSUE TITLE
error when downloading kivy launcher " your device isn't compatible with this version"

### ISSUE THREAD

**Issue by kmpruhs** [kivy/kivy#3227]
I am trying to use kivy to support an app for a project I am working on.
The device I am using is a Dragon Touch-Y88X running android 4.4.2

When I tried downloading Kivy Launcher google play store said "Your device isn't compatible with this version"

**Comment by kived** [comment]
Please go to https://play.google.com/store/apps/details?id=org.kivy.pygame&hl=en while logged into the Google account you use with Play Store. Where it tells you the app is not compatible with your device, there should be a `+` icon. Click it and Play Store will tell you why the app isn't compatible, then please post that info here.

**Comment by kmpruhs** [comment]
Ok, the error shown was "No carrier MID Dragon Touch-Y88X" (the last bit being my device)

**Comment by kived** [comment]
That's not the error, that's just listing your device. "No carrier" means you don't have wireless service on the device (or Google isn't aware of any service you have). For comparison, mine says "T-Mobile - US Samsung SM-N910T" for my Note 4 on T-Mobile.

If there is a checkbox next to the name of the device, then the app is compatible with your device. Otherwise, it should provide a reason (probably right below the device name).

**Comment by kmpruhs** [comment]
This is all I'm getting:
![screen shot 2015-04-03 at 11 45 40 am](https://cloud.githubusercontent.com/assets/11788259/6986950/3924f3c4-d9f7-11e4-9ab1-940bba234d81.png)
![screen shot 2015-04-03 at 11 43 34 am](https://cloud.githubusercontent.com/assets/11788259/6986951/3928d1d8-d9f7-11e4-817d-60370f5cb1c4.png)

**Comment by tito** [comment]
The only changes i did was --sdk 14 --minsdk 8. Maybe something else appeared?

**Comment by kived** [comment]
You should report this to Google (use the `?` button at the top, then scroll down to "send feedback"). Play Store should be telling you why the app isn't compatible, otherwise it's not very helpful information. :)

**Comment by tito** [comment]
I'm checking if it's not about supported screens or something.

**Comment by kived** [comment]
Hmm, I just went to update Kivy Launcher on my phone, and it now requests Location and Microphone permissions. Both of these are probably missing from this tablet, so we might need to do uses-feature with required false.

**Comment by tito** [comment]
@kmpruhs In the meantime, try to download and install manually http://kivy.org/downloads/1.9.0/KivyLauncher-1.9.0.0.apk -- But stay available for a further test please :)

**Comment by tito** [comment]
@kived I ask for theses permissions, but permission != uses-feature. The only uses-features we have is for GLES 2. Permission doesn't enforce the hardware to actually have the feature

**Comment by tito** [comment]
Ok, on the Play console, the DragonTouch-Y88X is marked as incompatible, but no information about what exactly.

**Comment by kived** [comment]
`uses-feature` can be implied by adding certain permissions. For example, `RECORD_AUDIO` implies `uses-feature` `android.hardware.microphone`, and `ACCESS_FINE_LOCATION` implies `android.hardware.location.gps` and `android.hardware.location`. You have to manually add `uses-feature` with `required="false"` to allow installation without this hardware.

http://developer.android.com/guide/topics/manifest/uses-feature-element.html#permissions

**Comment by tito** [comment]
Interesting, i didn't knew about it. Confirmed by:

```
aapt  dump badging KivyLauncher-1.9.0.0.apk 
package: name='org.kivy.pygame' versionCode='1090000' versionName='1.9.0.0' platformBuildVersionName='4.0.2-238991'
install-location:'auto'
application-label:'Kivy Launcher'
application-icon-160:'res/drawable/icon.png'
application: label='Kivy Launcher' icon='res/drawable/icon.png'
launchable-activity: name='org.renpy.android.ProjectChooser'  label='Kivy Launcher' icon=''
sdkVersion:'8'
targetSdkVersion:'14'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.BLUETOOTH'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.READ_EXTERNAL_STORAGE' reason='requested WRITE_EXTERNAL_STORAGE'
feature-group: label=''
  uses-gl-es: '0x20000'
  uses-feature: name='android.hardware.bluetooth'
  uses-implied-feature: name='android.hardware.bluetooth' reason='requested android.permission.BLUETOOTH permission, and targetSdkVersion > 4'
  uses-feature: name='android.hardware.location'
  uses-implied-feature: name='android.hardware.location' reason='requested android.permission.ACCESS_COARSE_LOCATION permission, and requested android.permission.ACCESS_FINE_LOCATION permission'
  uses-feature: name='android.hardware.location.gps'
  uses-implied-feature: name='android.hardware.location.gps' reason='requested android.permission.ACCESS_FINE_LOCATION permission'
  uses-feature: name='android.hardware.location.network'
  uses-implied-feature: name='android.hardware.location.network' reason='requested android.permission.ACCESS_COARSE_LOCATION permission'
  uses-feature: name='android.hardware.microphone'
  uses-implied-feature: name='android.hardware.microphone' reason='requested android.permission.RECORD_AUDIO permission'
  uses-feature: name='android.hardware.screen.landscape'
  uses-implied-feature: name='android.hardware.screen.landscape' reason='one or more activities have specified a landscape orientation'
  uses-feature: name='android.hardware.touchscreen'
  uses-implied-feature: name='android.hardware.touchscreen' reason='default feature for all apps'
main
other-activities
other-services
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '160'
native-code: 'armeabi'
```

**Comment by tito** [comment]
Let's add thoses features with required = false.

**Comment by tito** [comment]
Next 1.9.0.1 version:
```
aapt  dump badging bin/KivyLauncher-1.9.0.1.apk 
package: name='org.kivy.pygame' versionCode='1090001' versionName='1.9.0.1' platformBuildVersionName='4.0.2-238991'
install-location:'auto'
application-label:'Kivy Launcher'
application-icon-160:'res/drawable/icon.png'
application: label='Kivy Launcher' icon='res/drawable/icon.png'
launchable-activity: name='org.renpy.android.ProjectChooser'  label='Kivy Launcher' icon=''
sdkVersion:'8'
targetSdkVersion:'14'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.BLUETOOTH'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.READ_EXTERNAL_STORAGE' reason='requested WRITE_EXTERNAL_STORAGE'
feature-group: label=''
  uses-gl-es: '0x20000'
  uses-feature-not-required: name='android.hardware.bluetooth'
  uses-feature-not-required: name='android.hardware.location'
  uses-feature-not-required: name='android.hardware.location.gps'
  uses-feature-not-required: name='android.hardware.location.network'
  uses-feature-not-required: name='android.hardware.microphone'
  uses-feature-not-required: name='android.hardware.screen.landscape'
  uses-feature: name='android.hardware.touchscreen'
  uses-implied-feature: name='android.hardware.touchscreen' reason='default feature for all apps'
main
other-activities
other-services
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '160'
native-code: 'armeabi'
```

**Comment by tito** [comment]
The new APK is uploaded on our google drive, and already pushed to Play Store. It need times before it actually changes on the Play store.

In the meantimes, you can download the fixed version here: https://drive.google.com/open?id=0By88oIfn3BI4a0dhMkNtTXFQU3c&authuser=0

**Comment by tito** [comment]
Thanks!

**Comment by kmpruhs** [comment]
Awesome, it let me have it now. Thank you!
