### ISSUE TITLE
Doc for installing dev version (on Mac OS X) needs update

### ISSUE THREAD

**Issue by rogererens** [kivy/kivy#3240]
After cloning the repository and cd'ing into kivy directory, one should not execute:

    make

but

    kivy setup.py build_ext --inplace

Oh, and I also needed to make cython available for the venv first:

    kivy -m pip install cython==0.21.2

**Comment by akshayaurora** [comment]
closed by https://github.com/kivy/kivy/commit/bccd9e003f4f1d37381a2b4ef33b94a42d450454
