### ISSUE TITLE
SoftInput Mode `Pan` does not work wit latest stable

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#3248]
Window.softinput_mode does not seem to be working anymore.

**Comment by mcastle** [comment]
Can you provide more information? Are you testing it on Android, iOS, or another system? If iOS, it may be related to this issue:
https://github.com/kivy/kivy/issues/2775

**Comment by akshayaurora** [comment]
This was a issue with my setup. pan mode does work.

**Comment by mrhdias** [comment]
The 'pan', 'resize' end 'below_target' softinput_mode does not work on iOS (9.2) with kivy version 1.9.1.

**Comment by dessant** [comment]
@mrhdias, please open a new issue with example code to reproduce the bug.
