### ISSUE TITLE
Install docs need to be updated

### ISSUE THREAD

**Issue by sirpercival** [kivy/kivy#3260]
This is an umbrella issue for anything that people notice about the Installation instructions which needs to be updated for 1.9.1.

First: http://kivy.org/docs/installation/installation.html PyGame instead of SDL2 in a few different places.

**Comment by luminosuslight** [comment]
For all the people that can't wait for the new instructions for Mac OS X:
A workaround is to put your code in a folder named exactly 'yourapp' in the 'Resources' folder in the kivy.app portable package and just rename it to the name of your app.
