### ISSUE TITLE
App freezes on blank screen after upgrading to iOS 8.3

### ISSUE THREAD

**Issue by mcastle** [kivy/kivy#3262]
After upgrading my iPhone 6 to iOS 8.3, when I open my kivy app, the app opens and freezes on a blank screen. If I tap a part of the blank screen where a button should be (if the app were to have launched correctly,) the app changes to the correct, next screen. I've tested this on other iPhones with iOS 8.3 and with iPhones running older versions of iOS, and it only happens on the iPhones with iOS 8.3. This is with Kivy 1.8.

Here's the output from iOS Console:

`Apr 10 16:18:06 My-iPhone locationd[61] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 10 16:18:06 My-iPhone wifid[37] <Notice>: WiFi:[450393486.328501]: BG Application: Not Present, BG Daemon: Present. Daemons: networkd apsd UserEventAgent
Apr 10 16:18:07 My-iPhone locationd[61] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 10 16:18:08 My-iPhone CLTM[20] <Error>: CLTM: _subscription 0x0, _subscribedChannels 0x0`

**Comment by dessant** [comment]
Please test if you have the same issue with 1.9.0.

**Comment by mcastle** [comment]
Just tested with kivy 1.9.0, and it is not an issue there. However, I cannot currently use 1.9 because I require libssl and libcrypto support, which are not yet supported with the newest kivy-ios toolchain, so for now I am stuck using a previously built toolchain with only kivy 1.8.
