### ISSUE TITLE
How to Run Python Script to Kivi Android App

### ISSUE THREAD

**Issue by NisargJani** [kivy/kivy#3264]
I am new at Kivy and trying to make an android app that can run my python....when i open that app my script should be started to run and it should print on screen...suppose i have helloworld script made in python....so when i open my made android app...so it should run that helloworld.py and print on screen hello world...so i don't have any idea that how can id o this using kivy??...will you please guide me

**Comment by dessant** [comment]
Github issues are used only for bug reports, please use our support channels to get help: https://github.com/kivy/kivy#support.
