### ISSUE TITLE
End of ListView

### ISSUE THREAD

**Issue by tukhfatov** [kivy/kivy#3269]
How to handle end of ListView while scrolling? 

    <MainScreen>:
    orientation: 'vertical'
    news_list: news_list

    ListView:
        id: news_list
        scrolling: True
        adapter:
            ListAdapter(data=[], cls=main.NewsButton, args_converter=root.args_converter)

**Comment by tshirtman** [comment]
I don't think this is a bug report, questions are to be sent to the kivy-users mailing list or asked on IRC, not here. Please reoppen if you really thing it's a bug.
