### ISSUE TITLE
Can't create package for windows with kivy 1.9 portable

### ISSUE THREAD

**Issue by jamiecollinson** [kivy/kivy#3272]
I'm looking to port an existing kivy 1.8 project to kivy 1.9. I've just downloaded the portable version and have the application working.

However when packaging the app using pyinstaller and the instructions on http://kivy.org/docs/guide/packaging-windows.html the app packages, but on execution immediately fails with error:
```
Traceback (most recent call last):
  File "<string>", line 34, in <module>
ImportError: No module named pygame.pkgdata
```

I've tried using my old .spec file and generating a new one with exactly the same results.

I'm a bit mystified where this is coming from as pygame isn't imported anywhere in my application and I thought it had been replaced with sdl2 in kivy 1.9. I'm also confused that the application works when run directly.

Anyone come across this issue or can point me in the right direction?

**Comment by dessant** [comment]
All packaging and installation docs are outdated in some degree, see https://github.com/kivy/kivy/issues/3260.

**Comment by akshayaurora** [comment]
@jamiecollinson https://github.com/kivy/kivy/blob/master/kivy/tools/packaging/pyinstaller_hooks/rt-hook-kivy.py#L32 could you comment out all the files from here and see if that helps?

**Comment by jamiecollinson** [comment]
@akshayaurora commenting out lines 32-42 gets me past the initial error but still fails on:

```
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
sdl2 - Exception: SDL2: Unable to load image
```

Also looks like it's not loading opencv (which I'm using for camera) because numpy is failing to import, but I don't think that's directly connected as the app can load without a camera provider.

**Comment by luminosuslight** [comment]
For all the people that can't wait for the new instructions:
A workaround is to put your code in a folder named exactly 'yourapp' in the 'Resources' folder in the kivy.app portable package and just rename it to the name of your app.

**Comment by matham** [comment]
Ok, we need to provide sdl2 hooks, out at least say which dlls need to be included in the app. In particular, you need to include the DLLs from SDL2/bin and glew32.dll from MinGW/bin.

**Comment by h-sol** [comment]
Yes, that is correct. Actually, what happened is that Kivy didn't find the SDL2 library for png loading. Remember that SDL2 background is png image. The solution is easy, just copy from SDL2 folder in the kivy portable dist, the file libpng16-16.dll to your app package folder.

**Comment by jamiecollinson** [comment]
Thanks @h-sol & @matham - manually copying `libpng16-16.dll` gets me past the SDL2 error and the application mostly runs okay now.

I'm still running into the problem that numpy / opencv don't seem to be being imported and so the application fails on camera start. I'm confused by this as other imported libraries (e.g. peewee) are importing fine. Any pointers?

**Comment by tshirtman** [comment]
@jamiecollinson you may need to add them to hidden imports in the spec file.

**Comment by matham** [comment]
@h-sol and @jamiecollinson do you have some example code that replicates the libpng16-16.dll issue? Because I cannot seem to replicate it.

**Comment by matham** [comment]
The docs and the hooks should be updated to fix these issues.

**Comment by TheLordBaski** [comment]
@matham 
Still not working for me on version 1.9. Tested today with this docs:
http://kivy.org/docs/guide/packaging-windows.html
Build gave me this error: 
Traceback (most recent call last):
  File "<string>", line 34, in <module>
ImportError: No module named pygame.pkgdata

**Comment by matham** [comment]
Ok, try a pull from master, it should really be updated this time. The docs are in the middle of being updated, but you should not need to change anything if you're using 1.9.0.

**Comment by TheLordBaski** [comment]
@matham Pulled from master and build again.
and running give me this error 
[Critical        ][Window       ] Unable to find any valuable Window provider at all!
Exception: SDL2: Unable to load image
File :"C:\........\kivy.core", line 65 in core_select_lib
....
[Critical        ][Window       ]  Unable to get a Window, abort.

**Comment by matham** [comment]
Did you follow the instructions on the website? In particualr, did you include the line `Tree([f for f in os.environ.get('KIVY_SDL2_PATH', '').split(';') if 'bin' in f][0])`?

**Comment by JoeyCodinja** [comment]
Been trying to package a small kivy app for Windows, it packages okay but on running the .exe I get the following error 

    IOError: [Errno 2] No such file or directory: 'C:\\Path\\To\\Kivy\\App\\dist\\MonthlyProjects\\kivy\\data\\style.kv

Any solutions?

**Comment by pradeepce14** [comment]
I originally encountered the following error when using the instructions at http://kivy.org/docs/guide/packaging-windows.html

<pre>
Traceback (most recent call last):
  File "<string>", line 34, in <module>
ImportError: No module named pygame.pkgdata
</pre>

I am using the portable version of `1.9.0` on Windows 7, 64-bit.

Here is a solution:

Open `Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\tools\packaging\pyinstaller_hooks\rt-hook-kivy.py` in a text-editor. Delete everything in the file, copy the contents of https://github.com/kivy/kivy/blob/master/kivy/tools/packaging/pyinstaller_hooks/rt-hook-kivy.py into it, and save it.

Build the specfile again, and you should have a working `exe` in the `dist` folder.

Ref: https://github.com/kivy/kivy/issues/3308#issuecomment-97172322
Thanks @jtownley!

HTH
