### ISSUE TITLE
APK of KivyShowcase instead of KivyLauncher at download page

### ISSUE THREAD

**Issue by martinpollow** [kivy/kivy#3276]
Tried downloading the kivy launcher for android at http://kivy.org/#download 
The APK provided is the kivy showcase, not the kivy launcher as described.

**Comment by martinpollow** [comment]
That link works:
http://kivy.org/downloads/1.9.0/KivyLauncher-1.9.0.0.apk

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy-website/commit/6ed31de075838b4b98ca69aa098c3d36f9eaa395, thanks.
