### ISSUE TITLE
Kivy not working with MacPorts

### ISSUE THREAD

**Issue by tleeuwenburg** [kivy/kivy#3281]
Hi, I'm not sure who is maintaining the macports kivy port. It is currently broken, as it refers to the incompatible version of cython. I found the portfile an inspected it. The author is listed as 'stromnov' but I don't know how to reach that person.

https://trac.macports.org/browser/trunk/dports/python/py-kivy/Portfile?rev=132414

It just pulls in the latest cython and pygame versions. The latest cython is 0.22_0, and doesn't work with kivy.

This basically means that developing with Kivy isn't going to work for me. I have been wandering through the tall weeds for a while. I have a compiled version of Kivy installed into a virtual environment, but it doesn't support video playback properly. I have the downloaded OSX version of Kivy, which supports video playback, but I can't easily install all the other custom Python packages that I want to work with. I really really have done a lot of work to try to get a functional solution here.

If, and I repeat if, I could make the downloaded version of Kivy play nice in a virtual environment, that would be okay (using the macports version of Python, not the stock OSX one). 

It may seem like I've gone a long way to run an over-customised setup, but actually using a non-stock Python provided by macports or homebrew is actually the norm for Python developers on OSX, for all sorts of reasons.

I will have one final go at modifying the port file myself to see if I can get a version up and running.

Alternatively, resolving the current cython imcompatibility would be major step forward...

**Comment by rogererens** [comment]
Hi Tennessee,

2015-04-16 8:11 GMT+02:00 Tennessee Leeuwenburg <notifications@github.com>:

> ...
>
I have the downloaded OSX version of Kivy, which supports video playback,
> but I can't easily install all the other custom Python packages that I want
> to work with. I really really have done a lot of work to try to get a
> functional solution here.
>
Just to be sure:
kivy -m pip install <pypi package>
and/or
(cd <location of python package; kivy setup.py install)
do not work out for you?

>
>
If, and I repeat if, I could make the downloaded version of Kivy play nice
> in a virtual environment, that would be okay (using the macports version of
> Python, not the stock OSX one).
>
I'd be eager for that, too. According to Mathieu Virbel building a kivy
environment with non-stock python is 'a little harder' [1]
There was also the contents posted on this list showing which commands were
used to create the environment on the .dmg, but I cannot find it back.

>  It may seem like I've gone a long way to run an over-customised setup,
> but actually using a non-stock Python provided by macports or homebrew is
> actually the norm for Python developers on OSX, for all sorts of reasons.
>
> I will have one final go at modifying the port file myself to see if I can
> get a version up and running.
>

Cheers,
Roger

 [1]
https://groups.google.com/forum/?hl=nl#!topicsearchin/kivy-users/harder/kivy-users/JG4vgEq5RlQ

**Comment by dessant** [comment]
@tleeuwenburg we do not maintain the macports package. From a glance, it seems to be outdated, the current version of Kivy is 1.9.0, you could ask the maintainer to update it.

As for the bug in the cython codebase, you can follow this thread for updates https://github.com/kivy/kivy/pull/3180.
