### ISSUE TITLE
TextInput bug

### ISSUE THREAD

**Issue by mstetter** [kivy/kivy#3284]
Hi, there is a bug in the TextInput. On Android devices when deleting a character it adds the remainings to the text.

eg. when deleting 't' from 'test' it shows 'testtes'. This only happens when the TextInput is still focused. When unfocusing and deleting again nothing happens. I think this is really a serious bug.

**Comment by dessant** [comment]
@mstetter are you using 1.9.0?

**Comment by jrpdrummer** [comment]
I wonder if this is related to https://github.com/kivy/kivy/issues/3184, which does happen in 1.9.0.

**Comment by KeyWeeUsr** [comment]
I'd say it's more similar to #2418. Don't know if it's fixed.

**Comment by mstetter** [comment]
@dessant i am using the kivy == master in buildozer, so it is always up to date. It is the same in 1.8 and 1.9 did one of you experience the same issue? I think it could be the same type of problem as #2418 
But especially in long text inputs this is a serious problem.

**Comment by mstetter** [comment]
one more thing to narrow this down. It only happens in the same line. in a multiline textinput it only adds what is before in that same line. so even the 'enter' key stops that behaviour

**Comment by kived** [comment]
Have you tested multiple devices? What brand of device, Android version,
keyboard app, etc. have you seen this issue on?

**Comment by mstetter** [comment]
Samsung galaxy tab 2, android 4.4.2. In fact it is not the case on another device of mine which works with Android 4.1.1

**Comment by akshayaurora** [comment]
Could you mention your Keyboard being used with the app? are you using
stock keyboard ? which version of android?

**Comment by akshayaurora** [comment]
Samsung device using AOSP keyboard or swept?

**Comment by akshayaurora** [comment]
swept/swype keyboard or some other custom keyboard?

**Comment by mstetter** [comment]
I'm using the standard samsung keyboard without swipe, but with predictive text

**Comment by akshayaurora** [comment]
It would help if you could let us know about the keyboard being used on
samsung, can the keyboard be installed by other devices or is it only
available on samsung devices?

We would need to test with the mentioned keyboard to make sure we can fix
the issue.

**Comment by dessant** [comment]
I was able to reproduce this on a galaxy tab s with 4.4.2. The stock keyboard was used with predictive text turned on, the issue is not there if text prediction is disabled.

Steps to reproduce: open the showcase and go to the textinputs screen, type 'wwwwww' in the currently focused textinput, press the delete button once and if the bug is not triggered, press again.

**Comment by mstetter** [comment]
The Samsung Keyboard is the problem. I downloaded the google keyboard and it works. I could find the samsung keyboard as download though

**Comment by KeyWeeUsr** [comment]
I don't think it's only samsung keyboard issue. I had the same or at least similar issue on already dead tablet with android 2.3.3 default keyboard.

**Comment by dessant** [comment]
@KeyWeeUsr at least similar is not enough info, please test if you can reproduce this exact issue with master and mention your device model.

**Comment by dessant** [comment]
@akshayaurora i cannot reproduce it with hacker's keyboard (prediction enabled) on the same device.

**Comment by dessant** [comment]
@mstetter what's your keyboard version? Mine is 4.0.

**Comment by mstetter** [comment]
How can i find out the keyboard version for the samsung default keyboard?

**Comment by dessant** [comment]
@mstetter Settings->Applications->All->Samsung Keyboard

**Comment by mstetter** [comment]
Thanks, mine is also 4.0.

**Comment by AndersHogqvist** [comment]
I have this problem on my LG G2 (4.4.2) as well, but not only in Kivy but in Chrome as well. Makes me wonder if it may be a generall Android issue?

**Comment by mstetter** [comment]
I can also confirm this issue with the google handwriting keyboard 1.0.

**Comment by dessant** [comment]
This seems to be an upstream bug reproducible with other Android apps too, upgrading to L and above fixes the issue.

**Comment by KlashDev** [comment]
Reproduced it with Google Keyboard V. 4.1.23 on my MotoMaxx(MotoTurbo) device running Android 5.0.2 with prediction turned on.
Turning off prediction solved it.
