### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by pilotkid** [kivy/kivy#3291]
Hello my terminal says when exiting how can I fix it

/private/tmp/pip_build_root/kivy/kivy/lib/gstplayer/_gstplayer.c:343:10: fatal error: 'gst/gst.h' file not found
# include "gst/gst.h"

```
     ^
```

1 error generated.

 error: command 'cc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/private/tmp/pip_build_root/kivy/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-LVR6xY-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/kivy
Storing debug log for failure in /var/root/Library/Logs/pip.log

**Comment by pilotkid** [comment]
I should mention that I am using MAC OSX

**Comment by akshayaurora** [comment]
Make sure you have gstreamer.frameworks installed. Same for SDL2.framework, SDL2_image.framework, SDL2_ttf.framework, SDL2_mixer.framework.

On 10.10 essentially /Library/Frameworks don't get included/set using -F by default

You have to install the frameworks in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/

Or add a symlink to them there.

**Comment by pilotkid** [comment]
How do you add a system link

**Comment by ryandoherty** [comment]
I'm running into the same issue, even though I do have Gstreamer and all the SDL2 frameworks installed:

```
cd  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/
ls
lrwxr-xr-x    1 root  wheel    39 Aug 18 09:09 GStreamer.framework -> /Library/Frameworks/GStreamer.framework
lrwxr-xr-x    1 root  wheel    34 Aug 18 09:09 SDL2.framework -> /Library/Frameworks/SDL2.framework
lrwxr-xr-x    1 root  wheel    40 Aug 18 09:09 SDL2_image.framework -> /Library/Frameworks/SDL2_image.framework
lrwxr-xr-x    1 root  wheel    40 Aug 18 09:09 SDL2_mixer.framework -> /Library/Frameworks/SDL2_mixer.framework
lrwxr-xr-x    1 root  wheel    38 Aug 18 09:10 SDL2_ttf.framework -> /Library/Frameworks/SDL2_ttf.framework
```

Attempting to build gives me the same error.

**Comment by pabrasey** [comment]
I also get the same error. I followed exactly this :https://kivy.org/docs/installation/installation.html#development-version
