### ISSUE TITLE
[Docs] Git Screencasts site referenced in Contributing Guide no longer available

### ISSUE THREAD

**Issue by kevgathuku** [kivy/kivy#3293]
The [Git Screencasts](http://gitcasts.com/) site referenced in the [Contributing guideline](https://github.com/kivy/kivy/blob/master/doc/sources/contribute.rst#L93) doesn't seem to be available anymore.
Maybe the link should now point to the videos on the official git website available at [Git - Videos](https://git-scm.com/videos)

**Comment by akshayaurora** [comment]
closed via https://github.com/kevgathuku/kivy/commit/6688d7cf81250cf14079a89d12856627b54292b5
