### ISSUE TITLE
Kivy not leting me to use some python  library like smtp

### ISSUE THREAD

**Issue by NisargJani** [kivy/kivy#3297]
here is code i wrote in python and then i use buildozer to make its apk...but it cracshes every time...

from kivy.app import App
from kivy.uix.button import Button
import webbrowser
from functools import partial
from kivy.lang import Builder
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.boxlayout import BoxLayout
import webbrowser
import urllib2
from functools import partial
from kivy.app import App
from kivy.uix.label import Label
import re
import urllib2
import time
import os
import sys
import re
import subprocess
import smtplib

fromaddr = 'nisargjani20996@gmail.com'
toaddrs  = 'myfrien@gmail.com'
msg = 'Why,Oh why!'
username = 'nisargjani20996@gmail.com'
password = 'password'

server = smtplib.SMTP('smtp.gmail.com:587')

	
	

	

def callback(instance):
	server.starttls()
        server.login(username,password)
        server.sendmail(fromaddr, toaddrs, msg)
        server.quit()

class TestApp(App):
	def build(self):
		b=Button(text='press me')
		b.bind(on_press=callback)
		return b

if __name__ == '__main__':
    TestApp().run()

**Comment by dessant** [comment]
I've asked you twice before to not open issues unless you know that you're facing a kivy bug.

As for your crash, the first problem might be that subprocess does not work on android.
