### ISSUE TITLE
Slider's grabbing point should not change.

### ISSUE THREAD

**Issue by gouzouni** [kivy/kivy#3306]
As demonstrated here: https://gouz.tinytake.com/sf/MTM0NzU5Xzg1NDk4NA
this should not be happening I guess.
##

**Comment by KeyWeeUsr** [comment]
I'm not sure if that's completely addressed with #5145, however it provides a way how to set the collision only for the slider button/handle, therefore the "grabbing point" will be the handle if selected and not the whole widget area.
