### ISSUE TITLE
"No module named pygame.pkgdata" packaging with Kivy 1.9.0

### ISSUE THREAD

**Issue by jtownley** [kivy/kivy#3308]
After upgrading to Kivy 1.9.0 I can no longer use pyinstaller successfully.

Python 2.7
Windows 7 64bit ( Tested on multipule machines )
Kivy Portable Environment from http://kivy.org/downloads/1.9.0/Kivy-1.9.0-py2.7-win32-x64.exe

After packaging the touch tracer application:

Traceback (most recent call last):
  File "<string>", line 34, in <module>
ImportError: No module named pygame.pkgdata

I have attempted to follow the steps here: 
     http://kivy.org/docs/guide/packaging-windows.html

Notes:
 - My understanding is that pygame has been removed in 1.9.0
 - I don't have pygame installed separately
 - I am not the only one running into this: https://groups.google.com/forum/#!topic/kivy-users/JRWMo2dxrq8  (old post but people are adding to it.)

I believe this to be a bug. Has anyone actually packaged anything on windows 7 x64 yet?

I'll provide a verbose log of the procedure upon request.

--James

**Comment by jtownley** [comment]
This is a fixed bug. Should be noted in doc perhaps?

LaTeX-Pythonn -     Hello. Has anyone in the community successfully packaged an app for windows x64 using pyinstaller 2.1, kivy portable v.1.9.0 and python 2.7?
matham -            I did
matham -            what's the problem?      
LaTeX-Pythonn -     After packaging i get No module named pygame.pkgdata
matham -            LaTeX-Python, actually it was x86, but it should be similar
LaTeX-Python -      which is odd as there should be no more pygame
matham -            LaTeX-Python, you need to use master for that
matham -            there is a bug that was fixed
matham -            or you can update your local kivy packaging to master as:
matham -            https://github.com/kivy/kivy/blob/master/kivy/tools/packaging/pyinstaller_hooks/rt-hook-kivy.py
matham -            i.e. replace your local file with that (but you should update to master :) )
matham -            also, make sure to follow the updated sdl2 instructions on the website

**Comment by dessant** [comment]
Fixed in master, a dot release will follow soon.

**Comment by brentpicasso** [comment]
what changeset was this fixed in? I need to patch 1.9.0 if possible, rather than building my app from master. Thanks!

**Comment by matham** [comment]
Look through the git commit log for that file.

**Comment by brentpicasso** [comment]
Waded through it and figured it out. Thanks. YAY Open source!

Brent Picasso
Autosport Labs
Technology for Race and Street
