### ISSUE TITLE
Documentation error for keyboard_height

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/kivy#3316]
In the class Keyboard() (http://kivy.org/docs/api-kivy.core.window.html) keyboard_height has a typo in version added.
..versionadded:: 1.9.0
should be
.. versionadded:: 1.9.0

**Comment by NumesSanguis** [comment]
softinput_mode and on_textinput(text) have the same problems with the space.

**Comment by kived** [comment]
Fixed in #3322
