### ISSUE TITLE
"hello world" doest work in kivy launcher (android) 

### ISSUE THREAD

**Issue by ziphead** [kivy/kivy#3319]
I'm trying to run this code from kivy.org in kivy launcher on my nexus 5. I've made a folder in kivy folder and "android.txt" file. When i start it from launcher it crashes instantly Please guide me what do I do wrong? P.S. I don't compile app, I just wonna run it in launcher. Sample games and showcase work fine.
main.py and logs are here: https://gist.github.com/ec4a25c43696d1750448.
or here http://stackoverflow.com/questions/29982248/cant-run-hello-world-python-code-in-kivy-launcher-for-android

**Comment by KeyWeeUsr** [comment]
Erase "kivy,require('1.9.0')" and don't "import kivy". You import only parts from kivy ie Label, not the whole thing :)

**Comment by dessant** [comment]
@KeyWeeUsr that shouldn't be a problem.

**Comment by KeyWeeUsr** [comment]
@dessant, I used his code and then removed those lines, it worked. But yes, it shouldn't be a problem and I think it wasn't a problem on 1.8.0's launcher

**Comment by ziphead** [comment]
i've tryed without it with no luck

**Comment by ziphead** [comment]
code works in windows. Maybe problem is somewhere in library's relative paths , i had to use absolute paths in qpython. But samples work fine here. In Qpython 3 their SL4A gui sample apps dont.

**Comment by dessant** [comment]
@ziphead, was your issue sorted out?

**Comment by KeyWeeUsr** [comment]
Problem of a text editor I presume ([source](http://stackoverflow.com/a/30005563/5994041)).
From the log is obvious it could find `App` class, therefore it should find other files too. Probably only a matter of bad indentation and/or editor. I personally can't reproduce it (only indentation errors if I really try), so I guess there was some bad character after the `Label` import e.g. `\r` or something.

@ziphead If you can reproduce the issue again, try to open the source in editor that will display weird characters([hex](http://www.onlinehexeditor.com) maybe?).
