### ISSUE TITLE
Must not chdir in rt-hook-kivy.py

### ISSUE THREAD

**Issue by htgoebel** [kivy/kivy#3321]
The runtime-hook for PyInstaller changes directory to the directory where the executable lives. This generally is bad habit and leads to programs not behaving for the user as expected. Assume the user wants to pass a file from the current directory as an arguments:
```
/usr/bin/my-kivy-app ./file-argument.txt
```
Now as the runtime-hook changes the directory, the app tried to open `/usr/bin/file-argument.txt`. Adn if the application uses some file-requestor, it will start in /usr/bin, too, instead of the users current directory.

Even worse: Because the chdir happens in the runtime-hook (which is hidden magic for the app developer), the app developer has a really hard time debugging this kind of issues. (And maybe he comes back to us PyInstaller developers reporting a bug we are not responsible for :-(

**Comment by cbenhagen** [comment]
fixed by https://github.com/pyinstaller/pyinstaller/pull/1678
