### ISSUE TITLE
Joystick support for 1.9+ like it was with pygame

### ISSUE THREAD

**Issue by ibobalo** [kivy/kivy#3333]
in 1.9 most of joystick support lost (at least for windows)
in 1.8 pygame.joystick was available with all features - enumerating connected joysticks, get info (name, axes, buttons counts etc) for specified joystick and so on.
Now there no way to do it :(

#sample code now working anymore
from pygame import joystick
joystick.init()
for n in xrange(joystick.get_count()):
    j = joystick.Joystick(n)
    if fnmatch(j.get_name(), cfg.name_template):
        print "Joystick %d used (%s - %d axis)"%(n, j.get_name(), j.get_numaxes())
        for a in xrange(j.get_numaxes()):
             print "Axis %d: %f"%(a, j.get_axis(a))

**Comment by akshayaurora** [comment]
Kivy never directly supported handling multiple joysticks. I am opening a new issue for that as a feature request.

Closing this as you could still manually do this by compiling for pygame yourself.
