### ISSUE TITLE
Filechooser in container

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#3336]
Hi all,

Till now I used a FileChooserListView inside a container. 
As kivy 1.9 allows to change the layout I decided to let my users switch between icon and list layout.

Here is my .kv code:

#:kivy 1.9.0

RootWidget:

	# import container
    container: container

    # fill container
	BoxLayout:
        id: container
		orientation: 'vertical'
		padding: 0
		spacing: 6

        BoxLayout:
    		orientation: 'horizontal'
            size_hint: 1,0.07
    		# choose File
    		MyLabel:
    			text: 'Wo befindet sich das *.yml File?'
                size_hint: 0.85,1
            Button:
                size_hint: 0.075,1
                text: 'listview'
                on_release: chooser.view_mode='list'
            Button:
                size_hint: 0.075,1
                text: 'iconview'
                on_release: chooser.view_mode='icon'

        FileChooser:
	#FileChooserListView:
            id: chooser
            FileChooserIconLayout
            FileChooserListLayout

Till now the filechooser was in the green square:

![filechooser](https://cloud.githubusercontent.com/assets/1676457/7472202/274128e2-f330-11e4-9e99-6dca5ea8fde6.png)

Using the new kv-file (above) it seems to me, that the Filechooser uses some kind of absolute coordinates...

**Comment by jtownley** [comment]
I can still reproduce this with the example code at http://kivy.org/docs/api-kivy.uix.filechooser.html running master at sha: b517ecf47ea204b69c747a1ef5397d42e5793748 (april 15th). May be related to the FileChooserLayout class
