### ISSUE TITLE
how   does  ffmpeg  work on android

### ISSUE THREAD

**Issue by sichuyoudang** [kivy/kivy#3339]
I use buildozer    packaging   a apk , edit buildozer.spec  is    requirements = kivy,pygame,pyjnius,pil,ffmpeg
,when I run it in android to play video ,It  does not work,how should I set ??

**Comment by dessant** [comment]
Please use our support channels for getting help https://github.com/kivy/kivy#support, github issues are used only for reporting bugs.

**Comment by sichuyoudang** [comment]
ok  ,thanks
