### ISSUE TITLE
Updating skeletons in pycharm and kivy

### ISSUE THREAD

**Issue by RezaOptic** [kivy/kivy#3341]
I want to use kivy in pycharm. After I add python.bat in "Project Interpreter", it takes about 20 min to Update skeletons. Everything is ok till here but after I close pycharm and open again, pycharm wants to update skeletons again forcing me to wait for 20 min everytime. What should I do?

**Comment by dessant** [comment]
This is not a kivy issue, if you need to debug your IDE, contact their support team.

**Comment by kived** [comment]
Also, please note when you cross post.

http://stackoverflow.com/questions/30094373/updating-skeletons-in-pycharm-and-kivy
