### ISSUE TITLE
Poor performance on Samsung Exynos5422 w/ Mali-T628 MP6

### ISSUE THREAD

**Issue by editali** [kivy/kivy#3344]
I'm developing an app with Python and I use "Kivy" to create UI. On windows with Intel CPU and nVidia GPU machine everything goes as expected but on Ubuntu and Android machines with ARM CPU and Mali GPU (Samsung Exynos5422 w/ Mali-T628 MP6) the performance is very very poor, i.e: 1sec animation takes several second and lags every single frame, another example: when I click/tap on buttons even background change takes some time!!!
When i run my app i get this:
[INFO   ] [Logger      ] Record log in /home/odroid/.kivy/logs/kivy_15-05-10_11.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v3.4.0 (default, Apr 11 2014, 13:11:48)
[GCC 4.8.2]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: dlopen /usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen ${ORIGIN}/dri/exynos_dri.so failed (${ORIGIN}/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen /usr/lib/dri/exynos_dri.so failed (/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: exynos_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: exynos
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 10.1.3'>
[INFO   ] [GL          ] OpenGL vendor <b'Mesa Project'>
[INFO   ] [GL          ] OpenGL renderer <b'Software Rasterizer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [GL          ] Unpack subimage support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...

**Comment by editali** [comment]
Wao, I found that this issue does exists on mu Android tablet (lenovo s6000) with Arm A7

**Comment by tito** [comment]
Either do something wrong on your side in your app (only you know), and so raising an issue about performance issue it not going to help you either. Use the mailing list kivy-users to ask for help.

Either you have an issue with your graphics drivers (like the message showed in your backtrace about unable to load driver) which is not something Kivy can resolve for you.

Kivy require a working GPU. If it's not working, some drivers fallback into software rendering mode, and yes this is a disaster. Upgrade your graphics drivers when possible :)
