### ISSUE TITLE
Spaces after strings are removed!

### ISSUE THREAD

**Issue by pyprof** [kivy/kivy#3350]
Label:
    text: "Some text___\nMore text___" #spaces are shown as _ (underscores)

This is a multiline value. Now kivy acually will show 3 spaces after the first sentence "Some text___" but will remove 3 spaces after "More text".

This problem is reported in kivy irc and discussed with qua-non. According to his investigation and words this is a bug! 
##

**Comment by KeyWeeUsr** [comment]
Not present in master, but I'm not sure when it was fixed.
