### ISSUE TITLE
Problem with "compare_value" and "check" methods of Property class

### ISSUE THREAD

**Issue by pyfrid** [kivy/kivy#3358]
I need property class which can handle reference to a numpy array. I'm not able to use ObjectProperty because operator '==' which is used in compare_value method, is overrided for numpy arrays and raises the following exception "The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()". I obviously can not override the compare_value method in python code because it is defined as cdef method. 
Would it create a lot of trouble or performance issues if methods "compare_value" and "check" in the Property class will be defined as cpdef?

**Comment by hhsprings** [comment]
I have similar problem. I want to use NumericProperty togather with ndarray, but properties.pyx reject it. I think properties.pyx#convert should try converting with normal pythonic way like:
```python
    cdef convert(self, EventDispatcher obj, x):
        if x is None:
            return x
        tp = type(x)
        if tp is int or tp is float or tp is long:
            return x
        if tp is tuple or tp is list:
            if len(x) != 2:
                raise ValueError('%s.%s must have 2 components (got %r)' % (
                    obj.__class__.__name__,
                    self.name, x))
            return self.parse_list(obj, x[0], x[1])
        elif isinstance(x, string_types):
            return self.parse_str(obj, x)
        else:
            # -----------------------------------
            try:
                return float(x)
            except ValueError:
                raise ValueError('%s.%s have an invalid format (got %r)' % (
                    obj.__class__.__name__,
                    self.name, x))
            # -----------------------------------
```

**Comment by dessant** [comment]
ref https://github.com/kivy/kivy/issues/4541#issuecomment-240707131
