### ISSUE TITLE
Delimeter problem in kivy language.

### ISSUE THREAD

**Issue by gouzouni** [kivy/kivy#3364]
text: "Select an Index to read it's Description.." if root.selected_indices["feat_index"] is None else root.selected_indices["feat_index"].note

Delimeter in (it's) is ruining the statement.

**Comment by kived** [comment]
String removal during the binding stage of the parser doesn't ensure that matched quotes are removed.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/4015.
