### ISSUE TITLE
kivy.graphics.Line.rounded_rectangle don't seem to work when drawn in python

### ISSUE THREAD

**Issue by AndersHogqvist** [kivy/kivy#3368]
Running Kivy 1.9.0 it doesn't seem to be posible to draw a rounded_rectangle in Python, it does however work in kv language.

**Comment by inclement** [comment]
Do you mean it *does* work in kv language?

**Comment by tshirtman** [comment]
yes, it does in kv, not in python, this gist has both versions (in history), and only the kv one works.
https://gist.github.com/bc0ec46aae3d3b5f16d4

**Comment by inclement** [comment]
I think the problem is that Line ignores the rounded_rectangle argument. It should catch it at https://github.com/kivy/kivy/blob/master/kivy/graphics/vertex_instructions_line.pxi#L144 and use it to set its rounded_rectangle property.

**Comment by tshirtman** [comment]
right, fix on the way. :)
