### ISSUE TITLE
Label shorten_from and split_str do not work properly

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3370]
![screenshot from 2015-05-17 17 40 17](https://cloud.githubusercontent.com/assets/7513068/7670793/04576d06-fcbc-11e4-86dd-fbb77c982b48.png)

``` python
from kivy.app import App
from kivy.lang import Builder

kv = """
<Lab@Label>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            pos: self.pos
            size: self.size
    size_hint: None, None
    width: 116
    font_size: 16
    text_size: self.width, None
    shorten: True
    shorten_from: 'right'
    split_str: ' '

AnchorLayout:
    GridLayout:
        cols: 1
        size_hint: None, None
        size: self.minimum_size
        Lab:
            text: 'Christmas Islands'
        Lab:
            text: 'Cocos (Keeling) Islands'
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```
##

**Comment by dessant** [comment]
The expected behavior is to not split words if `split_str: ' '` and the ellipsis should be at the end of the text, if `shorten_from: 'right'`.

**Comment by xg-wang** [comment]
The `shorten()` in `core/text/__init__.py` seems wrong so I rewrote that to fix the issue.

Tests passed on options:

    shorten_from: 'right' (/ 'center' / 'left')
    split_str: '' (/ ' ')

**Comment by dessant** [comment]
I'm not sure what was I thinking here, the labels are not respecting the `shorten_from` or `split_str` options in the example because they prioritize over shortening *in some way* if the options cannot be respected, instead of not shortening at all. I think that's the correct behavior.
