### ISSUE TITLE
sdl2 - RuntimeError: Failed creating OpenGL pixel format, real bug or something else?

### ISSUE THREAD

**Issue by Gillu13** [kivy/kivy#3372]
I am not sure if this is an issue that should be reported here but I am wondering if the error I encountered while trying to run the "Hello world" program on Mac OS X Yosemite is related to the [recent shift to SDL2](http://kivy.org/planet/2015/04/kivy-1-9%C2%A0released/) or just to my poor installation (I don't know something like OpenGL extension?).

Here is the error message I get:

```
[INFO   ] [Logger      ] Record log in /Applications/Kivy.app/Contents/Resources/.kivy/logs/kivy_15-05-17_10.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
sdl2 - RuntimeError: Failed creating OpenGL pixel format
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/__init__.py", line 65, in core_select_lib
    cls = cls()
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 137, in __init__
    super(WindowSDL, self).__init__()
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/__init__.py", line 616, in __init__
    self.create_window()
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 187, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 87, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1611)
    self.die()
  File "kivy/core/window/_window_sdl2.pyx", line 21, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (kivy/core/window/_window_sdl2.c:954)
    raise RuntimeError(<bytes> SDL_GetError())

[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL] [App         ] Unable to get a Window, abort.
```

Just so you know it seems that I am not the only one to have encountered the [issue](https://groups.google.com/forum/#!topic/kivy-users/7HEh1W3xEX8), even though we are not that many and it was before the 1,9 release. That's why I am not sure if it is a bug or missing library on my computer or something like an incompatibility.

Cheers

**Comment by Alamot** [comment]
I had the same problem in a Hackintosh, but there it was a driver problem. You can test if OpenGL functions correctly in your system using some tools like:
1. http://www.geeks3d.com/20121113/gputest-0-2-0-cross-platform-opengl-benchmark-furmark-lands-on-linux-and-os-x/
2. http://www.realtech-vr.com/glview/

You have to test using HARDWARE renderer a not a software renderer! When I had only software renderer available kivy throwed this message you wrote.

**Comment by tito** [comment]
Agreed to what @Alamot. There is nothing much we can do if you don't have hardware acceleration, or at least one of the pixel format required for Kivy. This kind of error indicate your hardware is too old and can't be used. 

If you were in software rather than hardware, that might be your solution :)

**Comment by Areopagitics** [comment]
I am getting the same error when running Mac OS on VirtualBox; I am guessing it has to do with missing OpenGL drivers as well.  I tested the glview software recommended by Alamot and it works fine. I also tried running the Mac OS Vbox with 3D acceleration
 enabled, but no luck. Any help would be appreciated.

`[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - RuntimeError: Failed creating OpenGL pixel format
  File "/Users/areopagitics/Desktop/kivy/env/lib/python2.7/site-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/Users/areopagitics/Desktop/kivy/env/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 140, in __init__
    super(WindowSDL, self).__init__()
  File "/Users/areopagitics/Desktop/kivy/env/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 960, in __init__
    self.create_window()
  File "/Users/areopagitics/Desktop/kivy/env/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 272, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 217, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 66, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[INFO   ] [Text        ] Provider: sdl2
[CRITICAL] [App         ] Unable to get a Window, abort.`

**Comment by kjetiljd** [comment]
I ran into this on Mac when using a Dell D6000 USB docking station that uses DisplayLink, disconnecting the docking station, starting gource and then connecting it again is a work-around.

**Comment by ikus060** [comment]
Hello @Areopagitics @Alamot @Gillu13 

Did any of you manage to find a workaround to make this work in a Hackintosh ? I have MacOS running in a VM for testing and I ran into this problem. Your help would be appreciated.

**Comment by Areopagitics** [comment]
> Hello @Areopagitics @Alamot @Gillu13
> 
> Did any of you manage to find a workaround to make this work in a Hackintosh ? I have MacOS running in a VM for testing and I ran into this problem. Your help would be appreciated.

sorry, I haven't used kivy in a long time

**Comment by ikus060** [comment]
I would like to reanimate this issue.

It seams possible using glfw to support software rendering on MacOS.
See here. https://github.com/glfw/glfw/issues/2080
And here https://github.com/WerWolv/ImHex/pull/708/files

Is that something that could be consider adding in Kivy ?

**Comment by misl6** [comment]
Hi @ikus060,

Feel free to reach out and discuss about it on [Discord](https://chat.kivy.org).

Did you had the chance to test the `master` version which uses ANGLE (via Metal backing renderer) by default on macOS and iOS ?

You can find nightly builds at: https://kivy.org/downloads/ci/osx/kivy/

**Comment by ikus060** [comment]
@misl6 
> Did you had the chance to test the master version which uses ANGLE (via Metal backing renderer) by default on macOS and iOS ?

I tough Angle was only available on Windows. If available on MacOS, I'm not sure how to enabled it.

**Comment by misl6** [comment]
`ANGLE` is now the default EGL/GL provider for macOS and iOS (support has been added ~1 week ago), so you do not have to activate it on `master` branch.

Here you can find how to disable it instead: https://kivy.org/doc/master/gettingstarted/installation.html#from-source

**Comment by Gillu13** [comment]
Hi,

Unfortunatly I haven't used kivy for a decade or so. Hope you'll find
answers elsewhere.

Good Luck.

Le lun. 18 mars 2024, 20:22, Patrik Dufresne ***@***.***> a
écrit :
