### ISSUE TITLE
Problems with lowercase classnames in dynamic classes

### ISSUE THREAD

**Issue by eljost** [kivy/kivy#3376]
Hi,

i stumbled across the same problem as discussed here:
[Re: [kivy-users] Re: Getting SyntaxError: invalid syntax from kv file](https://groups.google.com/forum/#!topic/kivy-users/RvTx-szkGWE)

I can reproduce the problem with the following code:
**main.py**

``` python
from kivy.app import App

class A(App):
    pass

A().run()
```

**a.kv**

```
<lbl@Label>:

BoxLayout:
    lbl:
        text: "???"
```

This throws a `SyntaxError` that can be avoided with renamnig `lbl` to `Lbl` as mentioned in the linked post above.
But the thing is if I add a "normal" `Label` before the `lbl` the script doesn't throw a `SyntaxError` and runs fine.
**a.kv**

``` python
<lbl@Label>:

BoxLayout:
    Label:
        text: "!"
    lbl:
        text: "???"
```

To me the whole things seems pretty confusing and I think it would be a good idea to explicitly state  [here](http://kivy.org/docs/api-kivy.lang.html) that only names starting with an uppercase letter should be used for dynamic classes. I know that by convention python classes usually start with an uppercase letter but I'm pretty sure other people also stumbled over this problem.
And maybe someone should check why the first example doesn't work, but the second.

Best regards & thanks for this great lib!
##

**Comment by dessant** [comment]
This is now mentioned in https://kivy.org/docs/guide/lang.html:
```
Widget names should start with upper case letters while property names should start with lower case ones. Following the PEP8 Naming Conventions is encouraged.
```

**Comment by VukiLord** [comment]
I tried everything but i get a syntax error after typing 
<MyGrid>
    label:
        text: "Tako je"
the < is red and in my python script i have :
import kivy
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.gridlayout import GridLayout
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button
from kivy.uix.widget import Widget

class MyGrid(Widget):
    pass

class Vukasin(App):
    def build(self):
        return MyGrid()

if __name__ ==  "__main__":
    Vukasin().run()


Can someone help me, i know it is a simple error but why i can not figure it out
