### ISSUE TITLE
Can not display Chinese fonts correctly on the UI

### ISSUE THREAD

**Issue by guizhenwei** [kivy/kivy#3379]
Tested by the example on the home page of Kivy.org

    # coding: utf-8

    from kivy.app import App
    from kivy.uix.button import Button

    class TestApp(App):
        def build(self):
            return Button(text=u'Hello, This is Chinese.这里是中文。')

    TestApp().run()

**Comment by dessant** [comment]
`font_name` must be pointed to a font which has those chars, the default font does not support Chinese.
http://kivy.org/docs/api-kivy.uix.label.html#kivy.uix.label.Label.font_name
