### ISSUE TITLE
input_filter : negative numbers

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#3385]
The input_filter: float / int  property does not allow negative numbers. 
##

**Comment by picibucor** [comment]
regular-expression for negative and non-negative numbers:     ^[-0-9][0-9]+

Is there a way to invert this expression?

**Comment by Paradoxeuh** [comment]
I'm sorry but I can't find a simple way to have integer positive and negative, how is it working now? (I'm using the daily-repository of kivy on linux). Might be the wrong place but I didn't find any clear explanation in the commits

**Comment by matham** [comment]
Negative integers do not work currently. https://github.com/kivy/kivy/pull/3745 should fix it.

**Comment by Paradoxeuh** [comment]
Thank you for your answer. Is it possible to know when is this change is going to be merged ? Roughly ?

**Comment by dessant** [comment]
@Paradoxeuh, there is no eta, testing the pr and giving feedback helps speeding up the merge.

**Comment by matham** [comment]
I want to finally add this but I don't to remove the ability to just have positive numbers. So I think we need options like `int_pos`, `int`, `float`, and `float_pos`. However, this breaks previous behavior for e.g. `int` not allowing negatives. Also, positive ints do not include zero. So I'm not sure what the best options are.
