### ISSUE TITLE
google drive mirror link for Kivy-1.9.0-py3.4-win32-x64.exe is incorrect.

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#3386]
google drive mirror link for Kivy-1.9.0-py3.4-win32-x64.exe is incorrect. The link takes me to the py2.7 x86 version instead

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy-website/commit/cd262b6e0ecaff405558f7cdc47abc69e8e22fd5.
