### ISSUE TITLE
Feature Request: advanced configuration of settings pane

### ISSUE THREAD

**Issue by dak52** [kivy/kivy#3391]
It would be nice to be able to tweak the appearance of the settings pane a bit more. I have some custom pages, but when using a custom theme, the default text colors don't read well. I am currently unaware of a way to get around this, but the ability to set default text color for the settings pane would be great. The same goes for setting text_size and height for fields with long strings so that they can be wrapped.
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
