### ISSUE TITLE
Kivy 1.9 not working!!

### ISSUE THREAD

**Issue by parasjain1** [kivy/kivy#3394]
I'm new to Kivy. I installed it onto my system about an hour ago only to end up gazing at the windows error : "python.exe has stopped working"
I'm using Python27 with additional third party lib support supplied with Kivy 1.9.
The error is encountered when building a python file (.py) using sendto method as mentioned in the official documentation guide at kivy.org.
Also the program will run if I remove the statement : MyApp.run() i.e. the error is encountered only when calling the run() function to execute the app. 
Further no Kivy window is shown. After console processing, the error message pops up rightaway.

P.S. I'm trying to build the following test file:- 

````python
import kivy
#kivy.require('1.0.6') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.button import Button

class MyApp(App):
    def build(self):
        return Button(text='Hello World')

if __name__ == '__main__':
	print "Success"
	app=MyApp()
	app.run()

while(True):
	print "HELLO"
````

![capture](https://cloud.githubusercontent.com/assets/12663969/7890677/0e5a7d36-0665-11e5-86cf-5260f3acf7a6.PNG)

**Comment by KeyWeeUsr** [comment]
"while(True)" why.. you just killed it. Never ever try that if you don't know the loop could be breaked, otherwise you'll end up with "python.exe has stopped working" thing, because it's still printing "HELLO" over and over again. No chance for kivy. Erase that and write it in other, finite loop if you really need to print it.

Also these lines after if should be:
if __name__ == "__main__":
MyApp().run()

And I recommend you to look at these tutorials http://inclem.net/pages/kivy-crash-course/ :)

**Comment by parasjain1** [comment]
I know! Just played with the original code. I'm already a bit familiar with launching kivy applications. The problem is even with the original 'hello world' program code python.exe crashes as soon as the MyApp().run() is called. This is the main problem!! 
I added that infinite while loop just to keep the console screen on otherwise it would just close away.

**Comment by KeyWeeUsr** [comment]
Find that file "Record log in..." and paste it here. I didn't notice it, but the log should be longer. Anyway, I've tried to install kivy version you have from website and run your file - no problem. We'll see from the log, what's wrong with your installation.

**Comment by parasjain1** [comment]
Actually I have figured it out. The problem was due to the WDDM drivers update which do not support OpenGL. Updating the drivers raised another issue and this time with a well informed error message. I didn't had in knowledge that Kivy doesn't supports OpenGL ver < 2.0 and the highest my Intel 82945G Express Chipsets, on my literally old PC, can possess as of now is ver. 1.4.

**Comment by aghadiya** [comment]
I am facing the similar issue while running one kivy based application. I don't have the source code from which the application is created. 

The kivy log file contents are as below:
[INFO              ] Logger: Record log in C:\Users\aghadiya\.kivy\logs\kivy_16-04-22_7.txt
[INFO              ] Kivy: v1.9.0
[INFO              ] Python: v2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

After this it says python.exe has stoped working.

I checked the OpenGL version using openGL viewer and it shows the version 4.0, which should be fine as mentioned in the previous comment.

Any help is really appreciated. Thanks in advance.
