### ISSUE TITLE
Label: halign does not work. text always centered

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#340]
Text always shows centered, regardless of halign parameter.

```
import kivy

from kivy.app import App
from kivy.uix.label import Label

class P(App):
    def build(self):
        return Label(text='Text',halign='left')


P().run()
```

**Comment by zplorer52** [comment]
I have used these for Label text in the kv file to align text.
text_size:self.size
halign:'left'
valign:'middle'

**Comment by elientumbaluanga** [comment]
Thank you @lexelby it's working.
