### ISSUE TITLE
There is no markup tag for underlining and hypelink a text!

### ISSUE THREAD

**Issue by pyprof** [kivy/kivy#3403]
I think Kivy should work on 3 extremely necessary tags.

- Underline tag which might look like [u][/u]
- Hyperlink tag. At this moment we can create hyperlinks but the process is little bit complex and it doesn't show a text as a hyperlink apparently. Like when someone take mouse pointer on a link the mouse pointer usually changes from arrow to a hand. Kivy should introduce this tags as soon as possible. The tags might look like.. [a][/a], [a href="address"]hyperlink[/a]
- Another important markup tag is Mailto tag. So that whenever a person will click on a link it will open default mail client with address box of the mail client filled up.

These are my recommendations. Hope Kivy will be more rich in near future.

**Comment by dessant** [comment]
This feature is beyond the scope of label and it can be easily implemented in application code using `ref` http://kivy.org/docs/api-kivy.uix.label.html#interactive-zone-in-text.
