### ISSUE TITLE
Can't use Kivy with Python 3.4.3 on OS X

### ISSUE THREAD

**Issue by GAzevedo** [kivy/kivy#3404]
Hi!

I saw that the version 1.9 of Kivy has support to Python 3.4.3, but in OS S, when I install it, it only works with Python 2.7.

What can I do?

**Comment by mebstyne** [comment]
+1

**Comment by garyjohnson** [comment]
Here's the script I use to build the module for Python 2 & 3 in OSX. I like having these as Python modules rather than use the Kivy binary. https://gist.github.com/garyjohnson/53c1eef4adaf57c247a4

**Comment by dessant** [comment]
Let's track this here https://github.com/kivy/kivy-sdk-packager/issues/10.
