### ISSUE TITLE
multitouch_on_demand doesn't work with 1.9.0 on OS X

### ISSUE THREAD

**Issue by wjanssen** [kivy/kivy#3411]
This is 1.9.0 on OS X 10.7.

I have this in my ~/.kivy/config.ini:

[input]
mouse = mouse,multitouch_on_demand

But when I right-click I get the dreaded red dot, and the info about profiles and button is this:

['pos', 'button', 'multitouch_sim'] right

I thought I got to control whether "multitouch_sim" is in the profile?
##

**Comment by janssen** [comment]
This analysis is not right.  multitouch_on_demand will always put multitouch_sim in the profile.  However, the red dot should not be drawn.

**Comment by KeyWeeUsr** [comment]
Probably fixed by #5396

**Comment by tito** [comment]
Just tested with 8f48a117e6fe7936e935234807930cf9bcaa8f22 / master, i got multitouch sim on touchtracer, but not the red dot. So yes probably fixed by #5396.
