### ISSUE TITLE
disable_multitouch doesn't work with Kivy 1.9.1-dev on OS X

### ISSUE THREAD

**Issue by wjanssen** [kivy/kivy#3412]
This is Kivy 1.9.1-dev (from github) on OS X.  SDL2 provider.

I have

[input]
mouse = mouse,disable_multitouch

in my ~/..kivy/config.ini.

But when I right-click on a window, I get the dreaded red dot, and the info about touch profile and button is this:

['pos', 'button', 'multitouch_sim'] right
##

**Comment by kived** [comment]
Marking this as platform-osx so that the issue can be confirmed (this does not happen on Linux).

**Comment by wjanssen** [comment]
It does appear to work (on OS X) if I edit the master config.ini in the /Applications/Kivy.app tree, but not if I edit ~/.kivy/config.ini.

**Comment by wjanssen** [comment]
But the red circle remains.  Here's what I posted to kivy-users:

I was able to disable this on OS X by doing two things:

1.  Edit /Applications/Kivy.app/Contents/Resources/.kivy/config.ini to add "disable_multitouch" to input/mouse.

2.  Edit /Applications/Kivy.app/Contents/Resources/kivy/kivy/input/providers/mouse.py.  On line 202, change

            cur.update_graphics(EventLoop.window, True)

to

            cur.update_graphics(EventLoop.window, not (self.disable_multitouch or self.multitouch_on_demenad))

Yes, that typo is in the actual code, that is the attribute name.

I notice that when I changed ~/.kivy/config.ini, it had no effect.

**Comment by tito** [comment]
Just tested with 8f48a117e6fe7936e935234807930cf9bcaa8f22 / master with the touchtracer.
I don't have the red dot, and profile is only `['pos', 'button']`. No `multitouch_sim`.

So the bug is gone.
