### ISSUE TITLE
Graphical elements displaced, inspector claims they are in place

### ISSUE THREAD

**Issue by deltaflyer4747** [kivy/kivy#3416]
Graphical elements are displaced on screen after screenmanager changes screens. Inspector shows them in place. Tested with pygame & SDL2, happens in both.

When, for example Button, is clicked in place where it is supposed to be, its misplaced graphical element reacts where it is.

STR: Does not happen all the time, requires several launches to appear (sometimes 10+). No need to do anything in the app, it either loads next screen properly or not.

[Source code](http://sw.deltaflyer.cz/CC/report.zip)

**Comment by dessant** [comment]
The example is broken, make sure anyone can run it without bothering with dependencies and fixing things.

**Comment by deltaflyer4747** [comment]
tested just before posting, but there (maybe) were some nonstandard imports, i removed it & reuploaded.

**Comment by kived** [comment]
You're messing with graphics and widgets from a thread, which is not correct. If you can duplicate the problem without performing these actions from a thread, please reopen this or open another issue.

If you need to use a thread, you can use the `@mainthread` decorator on a function, and when called that function will execute in the main thread. You can also use `Clock.schedule_once` to call any function in the main thread (this is actually what `@mainthread` does).
