### ISSUE TITLE
ListView.scroll_to won't work after using a mouse scroll

### ISSUE THREAD

**Issue by aron-bordin** [kivy/kivy#3418]
Using: kivy/examples/widgets/lists/list_ops.py

When you select an item, the ListView will scroll to the selected item.
After using a mouse scroll in the the list, the scroll_to do nothing.

**Comment by qwertologe** [comment]
see https://gist.github.com/anonymous/d5752e71d1b55d38f710#file-test-py

**Comment by qwertologe** [comment]
even worse: changing the listproperty results sometimes in too long/short lists.
as a result you must manually scroll back to the start ... scrolling over empty lines or you can't scroll to the en because entries are missing.
