### ISSUE TITLE
link to RecycleView from ListView docs

### ISSUE THREAD

**Issue by kived** [kivy/kivy#3425]
Suggestion from IRC user sapienTech - include a note in the ListView docs about RecycleView. It would probably work best to replace the "ListView is experimental" notice we currently have. :) We could also note that it's experimental and the API is subject to change, etc., but that would help generate bug/feature reports for RecycleView and prevent people from trying to dive into the complex ListView API when they may not need to.

I haven't used RecycleView much myself yet, so I wanted to put this out there and see what other devs think.

**Comment by tito** [comment]
I don't think RecycleView is ready for prime time. As matham started used it last week, the API is still changing, making any app using it obsolete. But i would like to put it back into Kivy when it's ready :)

**Comment by dessant** [comment]
I've added a note.
