### ISSUE TITLE
Widget.right binding does not work as expected when width changes after being positioned.

### ISSUE THREAD

**Issue by arlowhite** [kivy/kivy#3430]
**Edit:**
Originally, I created this issue regarding Labels with size bound to texture_size. But this issue affects any widget where you bind its right property but then its width changes after being positioned. Instead of the widget's right side staying fixed and x changing, x stays the same and the value of right changes (x + width).

**Original Issue:**
Setting Label.right in KV doesn't work correctly when size is bound to texture_size:
```python
    Label:
        text: 'Label'
        size: self.texture_size
        right: root.right
```
Instead, the Label is placed with x=root.right. The Label will jump to the correct position when parent/window is resized.

This can be worked around by setting x this way instead:
```python
    Label:
        text: 'Label'
        size: self.texture_size
        x: root.right - self.width
```

The same issue occurs with top: root.top

**Comment by arlowhite** [comment]
printing out when x, right, or width change:

> initial         x=0 right=100 width=100
> call to GraphicUnitTest.render()
> **window width set to 320, so label.right is set to 320**
> right_change    x=220 right=320 width=100
> x_change        x=220 right=320 width=100
> **texture renders and texture_size changes label.width to 84**
> right_change    x=220 right=304 width=84
> width_change    x=220 right=304 width=84

When the Label's texture_size is determined, the width is set to 84, but instead of x changing relative to right, right changes relative to x. x:220 + width:84 = right:304

**Comment by arlowhite** [comment]
I'm not sure this is a bug exactly. The main issue is that the parent sets Label.right before texture_size updates.

However, even if this were fixed, the issue would still occur if the text were to change after Label was positioned.

For binding in python code there's really nothing that can be done, but this all started with KV language:

Maybe the KV processor can just translate **right: EXPRESSION** to **x: EXPRESSION - self.width** and **top: EXPRESSION** to **y: EXPRESSION - self.height**

**Comment by andnovar** [comment]
Is this Label inside a GridLayout ? if so it could be related to this issue https://github.com/kivy/kivy/pull/3216 ?

**Comment by arlowhite** [comment]
No, it happens with just a Label inside a plain Widget. Though I did notice an issue with GridLayout, I'll comment in #3216.

**Comment by kived** [comment]
Well, it's doing exactly what you told it. Set Label.right to it's
parent.right whenever the parent.right changes. You didn't tell it to check
when the Label.width changes (in the second one, you did, hence it worked).
kv only binds to the properties you mention in your expression.

Really, this is the job of Layout widgets.

FloatLayout:
    Label:
        text: 'label text'
        size_hint: None, None
        size: self.texture_size
        pos_hint: {'right': 1}

**Comment by matham** [comment]
@kived I agree and I'm trying to write docs about this. However, I'm not sure what to suggest to use to make this work, other than hacks of adding e.g. self.width. For example using `pos_hint` doens't actually work.

Consider
```py
layout = Builder.load_string('''
FloatLayout:
    id: layout
    width: 100
    Widget:
        id: wid
        pos_hint: {'right': 1}
''')

wid = layout.ids.wid
print(layout.right, wid.right)
wid.x = 200
print(layout.right, wid.right)
```
prints
```
(100, 100)
(100, 300)
```
Could it be that FLoatLayout needs to bind to wid's size and pos?

**Comment by arlowhite** [comment]
Ok, I didn't realize you could put 'right' in a pos_hint, thanks.
However, there are non-layout situations where you might try setting Label.right relative to another widget.
This seems sensible and unambiguous in KV. (put the Label on the left-side of some_other_widget)
```python
Label:
    right: some_other_widget.x
    size: self.texture_size
```
I can't think of a situation where you wouldn't want this to account for changes to Label.width.
The problem with my suggestion of substituting **right: EXP** with **x: EXP - self.width** is when the developer defines x as well.

But I think the simplest solution is to just print a KV error if you bind x and right at the same time.
> ERROR: 'right: some_other_widget.x' was converted to 'x: some_other_widget.x - self.width', but x is already bound.

There's one other situation I was thinking about: someone might try to fix the left and right sides of a Label relative to other widgets, expecting width to be calculated based on these constraints. (In this example the text_size line is necessary to make the Label wrap within width)
```python
Label:
    x: left_widget.right
    right: right_widget.x
    text_size: self.width, None
```
I'm not sure if this works, but I'm guessing it doesn't. In this example, you could just use BoxLayout, but still, if the KV is logical, maybe it could be made to interpret that correctly.

**Comment by arlowhite** [comment]
Actually, AnchorLayout and FloatLayout seem fine to me. @matham Does your code work with **size_hint: None, None** within the inner widget?

This works fine for me:
```python
from kivy.app import App
from kivy.lang import Builder

_kv = '''
FloatLayout:

    Widget:
        id: widget
        size_hint: None, None
        pos_hint: {'right': 1}
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size

    ToggleButton:
        text: 'Width'
        size: self.texture_size
        padding: dp(10), dp(8)
        size_hint: None, None
        on_state: widget.width = 200 if self.state=='down' else 100
'''

class RightSide(App):
    def build(self):
        return Builder.load_string(_kv)

    def on_start(self):
        print(self.root.ids.widget.pos)

if __name__ == '__main__':
    RightSide().run()
```

**Comment by matham** [comment]
Setting `size_hint` makes no difference. Did you try my code with size_hint set to None? Because it still doesn't work. In your code you're not setting the position.

**Comment by arlowhite** [comment]
@matham  I'm just looking at the Widget with *pos_hint: {'right': 1}* in my example.

With your code, both Widgets have a width of 100. If you change wid.width to 50 (in KV), it'll print:
> (100, 50)
> (100, 250)

So the right side isn't lined up to begin with. And I'm confused what you're testing by changing wid.x instead of wid.width.

**Comment by kived** [comment]
@matham We do not currently bind to size (it's commented out, not sure
why), but we do bind to pos. In your example, the event loop isn't running
and therefore the clock isn't ticking. If you add `Clock.tick()` after
setting `wid.x = 200` then it prints out `(100, 100)` as expected.

**Comment by arlowhite** [comment]
I've been thinking about various ways to close this issue. In order from easiest to hardest...

## 1. Just document it
Add some commentary to the KV Language page about setting right or top.

## 2. KV Warnings
The KV interpreter could print a warning if you bind right or top. However, if you're not changing widths the warning is a false positive.

## 2a. More intelligent KV Warnings
Instead of printing a warning, the KV interpreter could bind a print-warning-function to width changes. This pushes the warning to run-time, but warns the user when there's actually a problem. This code could could be placed in *if \__debug__* for efficiency.

## 3. Changes to width shift x or right depending on which was last set
1. Modify widget.py so that it tracks whether x or right was set last (set a right_sided boolean when x or right changes)
2. Remove width from right AliasProperty bind.
3. Make width an Alias property; in set_width:
```python
if self.right_sided:
    self.x = self.right - self.width
else:
    self.right = self.x + self.width
```
Is the overhead worth addressing this issue? I'm not sure...up to the Kivy devs.

**Comment by matham** [comment]
I added docs about this at https://github.com/kivy/kivy/commit/a7eaa867206c88aa5e062e7dcb5bc5f297a3959c, and as kived said, we already have layouts to deal with this so I don't think we should change anything.
