### ISSUE TITLE
shortened label has default text colour for ellipsis

### ISSUE THREAD

**Issue by GP89** [kivy/kivy#3435]
I've noticed that when a `Label` is shortened by setting the `shorten` property, the ellipsis has the default text colour of white, regardless of what the colour of the text is set to.

I believe this could be a bug unless I've overlooked a way to change this?

![screen shot 2015-06-15 at 12 05 37](https://cloud.githubusercontent.com/assets/1440143/8160277/2d9ed4cc-1366-11e5-9e7a-4697ea34117f.png)

**Comment by tito** [comment]
I actually can't reproduce it.

```python
from kivy.uix.label import Label
from kivy.base import runTouchApp
from kivy.lang import Builder
Builder.load_string("""
<Label>:
    canvas.before:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.pos
            size: self.size
""")
runTouchApp(Label(text="Hello world", text_size=(50, 50), shorten=True,
    color=(0, 0, 0, 1)))
```

Please reopen with a reproducable code, and with the output log in debug :)

**Comment by matham** [comment]
@tito, this example code repreduces it:

```py
from kivy.uix.label import Label
from kivy.base import runTouchApp
runTouchApp(Label(text="[color=ff3333]Hello world[/color]", text_size=(50, 50), shorten=True,
    markup=True))
```
It's basically that the label options of the words before it should be used for the ellipses in a markup label rather than the global options.

**Comment by Alchemist-T-N** [comment]
Works well for me... But still it's a bug ha..
