### ISSUE TITLE
comparison failure for numpy arrays stored in ObjectProperties

### ISSUE THREAD

**Issue by sirpercival** [kivy/kivy#3438]
https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L413

If `realvalue` and/or `value` are numpy arrays, this throws an error:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

In addition, if one of them is `None`, we get `FutureWarning: comparison to 'None' will result in an elementwise object comparison in the future.`

**Comment by pyfrid** [comment]
This is due to comparison function, which uses standard '==' operator and is a cython function, which makes it impossible to override it in python. As a fast and dirty solution you can set force_dispatch flag of the property to true.
