### ISSUE TITLE
option "show_cursor" stopped working in version 1.9

### ISSUE THREAD

**Issue by schoolsplay** [kivy/kivy#3441]
In kivy version 1.8 I could do two things to hide the mouse cursor:
1. use Config.set('graphics', 'show_cursor', 0) # or set it in the kivy.ini
2. use pygame.mouse.set_cursor to load a "empty" mouse image.

Now in version 1.9 none of the solutions works.
When I revert back to kivy 1.8 my code works again and the cursor is hidden (I'm using option 2 as option 1 disables the touchscreen also)

Here's a small code example, the cursor is always shown.

<pre>
__author__ = 'stas Zytkiewicz stas@childsplay.mobi'

from kivy.config import Config
Config.set('graphics', 'show_cursor', 0)
# I use fullscreen to check that the config setting really works
#Config.set('graphics', 'fullscreen', 1)

import kivy

kivy.require('1.0.7')

from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.floatlayout import FloatLayout

class Screen(FloatLayout):
    def __init__(self):
        FloatLayout.__init__(self)

    def cbf(self, *args):
        print "Button Pressed..."

class TestApp(App):
    def __init__(self):
        App.__init__(self)

    def build(self):
        scr = Screen()
        but = Button(text='A button, press me !',
                     pos_hint={'center_x': 0.5, 'center_y': 0.5},
                     size_hint=(0.20, 0.2),
                     on_press=scr.cbf)
        scr.add_widget(but)
        return scr

if __name__ == '__main__':
    TA = TestApp()
    TA.run()
</pre>

**Comment by ivlevdenis** [comment]
+
