### ISSUE TITLE
ImportError: No module named app

### ISSUE THREAD

**Issue by SanketDG** [kivy/kivy#3444]
I have been trying to get started with Kivy and I did try almost everything for getting it working properly but failed. Whatever method I have tried of installing Kivy has only one error.
```python
ImportError: No module named app
```
I am on Linux Mint 17 Cinnamon. Python 2.7.

I finally decided to ask the dev community, as I just really want to get started. Here is a screen:

![image](https://cloud.githubusercontent.com/assets/8980971/8230462/18fabe9e-15de-11e5-9ef6-1834a2433478.png)

**Comment by dessant** [comment]
We are glad to help you, but please open issues only for bugs.
Visit the irc chan or the mailing list to get started: https://github.com/kivy/kivy#support.
