### ISSUE TITLE
Windows 7 I cant seem to get Kivy to work.

### ISSUE THREAD

**Issue by KingdomWalker** [kivy/kivy#3446]
Hi, I am just trying to run a simple kivy code from the internet. I looked through multiple threads and I cant seem to ever solve this problem. Please help. 
Thanks in advance. 

GST_REGISTRY
C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\gstreamer\registry.bin
---------------
KIVY_SDL2_PATH
C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\SDL2\lib;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\SDL2\include\SDL2;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\SDL2\bin
---------------
USE_SDL2
1
---------------
GST_PLUGIN_PATH:
C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\gstreamer\lib\gstreamer-1.0
---------------
PATH:
C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\Python27;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\tools;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\Python27\Scripts;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\gstreamer\bin;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\MinGW\bin;C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\SDL2\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\EgisTec MyWinLocker\x64;C:\Program Files (x86)\EgisTec MyWinLocker\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\altera\13.0sp1\quartus\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\MATLAB\R2014a\runtime\win64;C:\Program Files\MATLAB\R2014a\bin;C:\Program Files\MATLAB\R2014a\polyspace\bin;C:\Program Files (x86)\Skype\Phone\;%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\EgisTec MyWinLocker\x64;C:\Program Files (x86)\EgisTec MyWinLocker\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\altera\13.0sp1\quartus\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\MATLAB\R2014a\runtime\win64;C:\Program Files\MATLAB\R2014a\bin;C:\Program Files\MATLAB\R2014a\polyspace\bin;C:\Program Files (x86)\Skype\Phone\;C:\Python27
----------------------------------
PYTHONPATH:
C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27;C:\Users\Don\PycharmProjects\untitled
----------------------------------
##################################
done bootstraping kivy...have fun!\n
running "python.exe "C:\Program Files (x86)\JetBrains\PyCharm 4.0.5\helpers\pydev\pydevd.py" --multiproc --client 127.0.0.1 --port 52995 --file C:/Users/Don/PycharmProjects/untitled/test.py" \n
pydev debugger: process 11636 is connecting

Connected to pydev debugger (build 139.1547)
[INFO              ] [Logger      ] Record log in C:\Users\Don\.kivy\logs\kivy_15-06-18_67.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <3.1.0 - Build 8.15.10.2418>
[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics Family>
[INFO              ] [GL          ] OpenGL parsed version: 3, 1
[INFO              ] [GL          ] Shading version <1.40  - Intel Build 8.15.10.2418>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Shader      ] fragment shader: <No errors.>
[INFO              ] [Shader      ] vertex shader: <No errors.>
[INFO              ] [Shader      ] program: <No errors.>
[WARNING           ] [Image       ] Unable to load image <C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\data\glsl\default.png>
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
sdl2 - Exception: SDL2: Unable to load image
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\__init__.py", line 65, in core_select_lib
    cls = cls()
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\window\window_sdl2.py", line 121, in __init__
    super(WindowSDL, self).__init__()
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\window\__init__.py", line 616, in __init__
    self.create_window()
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\window\window_sdl2.py", line 188, in create_window
    super(WindowSDL, self).create_window()
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\window\__init__.py", line 769, in create_window
    self.render_context = RenderContext()
  File "kivy\graphics\instructions.pyx", line 751, in kivy.graphics.instructions.RenderContext.__init__ (kivy\graphics\instructions.c:10270)
    tex = Image(filename).texture
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\image\__init__.py", line 511, in __init__
    self.filename = arg
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\image\__init__.py", line 699, in _set_filename
    mipmap=self._mipmap, nocache=self._nocache)
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\image\__init__.py", line 429, in load
    im = loader(filename, **kwargs)
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\image\__init__.py", line 197, in __init__
    self._data = self.load(filename)
  File "C:\Users\Don\Desktop\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\core\image\img_sdl2.py", line 42, in load
    raise Exception('SDL2: Unable to load image')

[CRITICAL          ] [App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL          ] [App         ] Unable to get a Window, abort.

**Comment by matham** [comment]
You should join us on IRC for this because we cannot easily provide support here for this kind of thing. Joins us on freenode at #kivy.
