### ISSUE TITLE
Created .exe package can't find file .. but file not generated

### ISSUE THREAD

**Issue by JoeyCodinja** [kivy/kivy#3462]
After running through the packaging process, and getting my exe, running it in console returns the following error:

      IOError: [Errno 2] No such file or directory: \\MONTHL~1\\KIVY-1~1.7-W\\dist\\MONTHL~1\\kivy\\data\\style.kv'

But that folder or file isn't generated .. is there something I'm missing ?

**Comment by matham** [comment]
It's hard to help without seeing your spec file.

**Comment by JoeyCodinja** [comment]
So I re-ran it this morning and got a totally different result
<pre><code>ImportError: No module named pygame.pkgdata</code></pre>

This confused me because from the docs , I see that I should be using the SDL2 libraries and not the pygame packages. 


Here is my current spec file 
<pre><code>from kivy.tools.packaging.pyinstaller_hooks import install_hooks
import os
install_hooks(globals())


# def getResource(identifier, *args, **kwargs):
#   if identifier == 'pygame_icon.tiff':
#     raise IOError()
#   return _original_getResource(identifier, *args)

# import pygame.pkgdata
# _original_getResource = pygame.pkgdata.getResource
# pygame.pkgdata.getResource = getResource

# -*- mode: python -*-
a = Analysis(['..\\package\\monthlyprojects_kivy.py'],
             pathex=['C:\\Users\\Danuel\\Google Drive\\Monthly Projects (Zonya)\\MonthlyProjects'],
             hiddenimports=[],
             runtime_hooks=None)
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='MonthlyProjects.exe',
          debug=False,
          strip=None,
          upx=True,
          console=True )
coll = COLLECT(exe, Tree('..\package'),
               Tree([f for f in os.environ.get('KIVY_SDL2_PATH', '').split(';') if 'bin' in f][0]),
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name='MonthlyProjects')
</code></pre>

**Comment by Kazun3500** [comment]
Problem with this error ```
ImportError: No module named pygame.pkgdata
```was fixed by this commit https://github.com/kivy/kivy/commit/dffd000995d8fe2182df4f1dc4f5bf6dcf99fab0 .
Perhaps issue can be closed. But it would be a good idea to specify the documentation that the creation of a goat in the current version, you must edit the file specified in the buyout commit above or upgrade version is available for download from http://kivy.org/#download.

**Comment by matham** [comment]
I guess this is a problem with our docs in general. The docs are for master which is not typically the currently released version. A goal for the site is to have multiple versions of the docs for each released version, like python does.

**Comment by matham** [comment]
But yeah, this should have been fixed in master, so I guess I'll close it for now.
