### ISSUE TITLE
Widget gravity

### ISSUE THREAD

**Issue by sajadbanooie** [kivy/kivy#3465]
you got to add gravity to your widgets like java

**Comment by inclement** [comment]
This functionality is in kivy's layout classes, though it's not in general the same as the gravity system. You could probably make a layout that behaves the way you want quite easily, though I'm not familiar with the details and can't say for sure.

I don't think we're likely to build the widget system around this any time soon though, so I'm closing this for now.

**Comment by sajadbanooie** [comment]
Im trying to create an app which need rtl support
but kivy dosent support rtl Specially TextInput

**Comment by dessant** [comment]
Yes, that is a missing feature in kivy, you might want to try implemening the backend yourself.
But rtl text has no relation to this issue :).

Use our support channels if you need further help: https://github.com/kivy/kivy#support.

**Comment by sajadbanooie** [comment]
how kivy draw widgets?

**Comment by inclement** [comment]
@sajadbanooie Please ask these questions on the mailing list or irc channel, github is not a good place for them. But to answer, kivy is an opengl toolkit, everything is opengl internally and you can read our graphics api doc to see how that's managed on the user side.
