### ISSUE TITLE
strange behaviour with carousel in a fullscreen window on desktop

### ISSUE THREAD

**Issue by dennyb87** [kivy/kivy#3466]
Today I noticed a strange behavior when the carousel is on a full-screen window (ubuntu 4.14) do not know if this strange behavior is due to the operating system or Kivy, the fact remains that when you put the carousel in full screen , slides behave in a strange way, the text inside of them sometimes become blurred, as if they had not yet completed its movement.

Try running this snippet, and put it in full screen on my computer slides lose correspondence with the tabs, as if the graphics do not was updated properly when the window is in full screen.

Snippet to reproduce the behaviour: 
        https://github.com/kivy/kivy/wiki/Embedding-a-Carousel-inside-a-TabbedPanel

PS: This strange behavior you can observe only with the carousel, but I wanted to use this snippet because it is more clear things

![screenshot from 2015-06-25 21 51 08](https://cloud.githubusercontent.com/assets/7195133/8365325/5abed4f4-1b84-11e5-9d2c-ddbe25bd349c.png)

**Comment by dessant** [comment]
@dennyb87 do you really mean fullscreen or just maximized? Could you try with kivy master, making sure that sdl2 is used as the window provider?

**Comment by dennyb87** [comment]
I mean fullscreen as in the screenshot i posted above.
I will try it as soon as possible as you said with the master branch https://github.com/kivy/kivy.git

**Comment by pyfrid** [comment]
The same problem as in my example for #2297

**Comment by dessant** [comment]
Let's track this at https://github.com/kivy/kivy/issues/2297.
