### ISSUE TITLE
Bug clipboard paste android

### ISSUE THREAD

**Issue by wpbloger** [kivy/kivy#3468]
Hello.
I have a standard widget textinput in which pasting text does not work, and the application crashes, that's an error message:
[INFO              ] Logger: Record log in /storage/emulated/0/kivy/mvd/.kivy/logs/kivy_15-06-27_29.txt
[INFO              ] Kivy: v1.9.0
[INFO              ] Python: v2.7.2 (default, Apr  2 2015, 13:52:41) 
[GCC 4.8]
[INFO              ] Factory: 173 symbols loaded
[WARNING           ] stderr: /data/data/org.kivy.pygame/files/lib/python2.7/site-packages/kivy/core/image/img_pygame.py:13: RuntimeWarning: import cdrom: No module named cdrom
[WARNING           ] stderr: (ImportError: No module named cdrom)
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] Text: Provider: pygame
[INFO              ] Window: Provider: pygame
[INFO              ] GL: OpenGL version <OpenGL ES 3.1 334.00>
[INFO              ] GL: OpenGL vendor <NVIDIA Corporation>
[INFO              ] GL: OpenGL renderer <NVIDIA Tegra>
[INFO              ] GL: OpenGL parsed version: 3, 1
[INFO              ] GL: Texture max size <16384>
[INFO              ] GL: Texture max units <32>
[INFO              ] Support: Android install hooks
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] GL: NPOT texture support is available
[INFO              ] OSC: using <thread> for socket
[INFO              ] Base: Start application main loop
[INFO              ] Android: found 17 joystick
[INFO              ] Android: create joystick <0>
[INFO              ] Android: discard joystick <0> cause no button
[INFO              ] Android: create joystick <1>
[INFO              ] Android: create joystick <2>
[INFO              ] Android: create joystick <3>
[INFO              ] Android: create joystick <4>
[INFO              ] Android: create joystick <5>
[INFO              ] Android: create joystick <6>
[INFO              ] Android: create joystick <7>
[INFO              ] Android: create joystick <8>
[INFO              ] Android: create joystick <9>
[INFO              ] Android: create joystick <10>
[INFO              ] Android: create joystick <11>
[INFO              ] Android: create joystick <12>
[INFO              ] Android: create joystick <13>
[INFO              ] Android: create joystick <14>
[INFO              ] Android: create joystick <15>
[INFO              ] Android: create joystick <16>
[INFO              ] Clipboard: Provider: android
[INFO              ] Base: Leaving application in progress...
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "main.py", line 14, in <module>
[WARNING           ] stderr:     MvdApp().run()
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 824, in run
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 398, in mainloop
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 330, in idle
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 315, in dispatch_input
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 281, in post_dispatch_input
[WARNING           ] stderr:   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/behaviors.py", line 163, in on_touch_up
[WARNING           ] stderr:   File "kivy/_event.pyx", line 695, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6970)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12154)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1052, in kivy._event.EventObservers._dispatch (kivy/_event.c:11120)
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1465, in custom_callback
[WARNING           ] stderr:   File "/data/data/org.kivy.pygame/files/lib/python2.7/site-packages/kivy/data/style.kv", line 200, in <module>
[WARNING           ] stderr:     on_release: root.do('paste')
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/textinput.py", line 362, in do
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/textinput.py", line 1436, in paste
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/clipboard/__init__.py", line 87, in paste
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/clipboard/__init__.py", line 108, in _paste
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_android.py", line 32, in get
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_android.py", line 53, in called
[WARNING           ] stderr:   File "/home/tito/code/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_android.py", line 66, in _get
[WARNING           ] stderr: AttributeError: 'str' object has no attribute 'toString'
------------------------------------------------------------------------------------------------------------------------------
I really hope that you fix this bug, it's a standard widget, and it should work fine.

**Comment by kived** [comment]
This bug has already been fixed in master.
