### ISSUE TITLE
Probesysfs module error: TypeError:  must be bytes, not strings

### ISSUE THREAD

**Issue by gustavklopp** [kivy/kivy#3470]
First installation here:
When I try to launch the simple example, I've got this error in the Probesysfs module (line 123):

```
if prop.startswith('Device Enabled') and prop.endswith('0'):
 TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

I've added : `prop = prop.decode('utf-8')`  and it's apparently working.
What is the cause of this error??
Thanks in advance!

Configuration:
Ubuntu 15.04
`pip freeze` gives:

```
Cython==0.22
docutils==0.12
Kivy==1.9.1.dev0
Kivy-Garden==0.1.1
pygame==1.9.2a0
requests==2.7.0
wheel==0.24.0
```

If I use:
Cython==0.21.2
Kivy==1.9.0
it's working without problem.
##

**Comment by KeyWeeUsr** [comment]
Closed by https://github.com/kivy/kivy/commit/4c8e234d4ab90455148eb9d37885dc0d5774a20c
