### ISSUE TITLE
Mouseover events

### ISSUE THREAD

**Issue by ODiogoSilva** [kivy/kivy#3471]
I am designing a desktop kivy app where mouseover events for certain widgets would be quite useful. I understand that it is possible to create a scheduled function that listens to the mouse position and tests its collision with any widget (and I have successfully created mouseover events using this approach), but I was wondering if there are any plans to create a built-in event handle, such as the ones when buttons are pressed/released. From the user standpoint, it would be far easier to have an *on_hover* event, for example.

**Comment by inclement** [comment]
This has been discussed before. I think the major problem with a generic on_hover event is that it's very inefficient - far more so than touch events, as if the mouse is moving it would mean walking the widget tree passing the event along every single frame. I believe for this reason it was considered better to leave it to users.

If anything, it would probably be best to make a behavior mixin class like the ButtonBehavior that can keep track of the specific classes listening for hover events and dispatch relatively efficiently to them. This wouldn't be very hard to create, if you wanted to make one and submit a PR I think it would be considered.

**Comment by opqopq** [comment]
Attached is my attempt for such thing. Posting it here, before any PR
------------hoverable.py-----------------------------------------------------------------------------------
"""Hoverable Behaviour (changing when the mouse is on the widget by O. Poyen.License: LGPL"""__author__ = 'Olivier POYEN'

from kivy.properties import BooleanProperty, ObjectPropertyfrom kivy.core.window import Window
class HoverBehavior(object):    """Hover behavior.
    :Events:        `on_enter`            Fired when mouse enter the bbox of the widget.        `on_leave`            Fired when the mouse exit the widget     """
    hovered = BooleanProperty(False)    border_point= ObjectProperty(None)    '''Contains the last relevant point received by the Hoverable. This can    be used in `on_enter` or `on_leave` in order to know where was dispatched the event.    '''
    def __init__(self, **kwargs):        self.register_event_type('on_enter')        self.register_event_type('on_leave')        Window.bind(mouse_pos=self.on_mouse_pos)        super(HoverBehavior, self).__init__(**kwargs)
    def on_mouse_pos(self, *args):        if not self.get_root_window():            return # do proceed if I'm not displayed <=> If have no parent        pos = args[1]        #Next line to_widget allow to compensate for relative layout        inside = self.collide_point(*self.to_widget(*pos))        if self.hovered == inside:            #We have already done what was needed            return        self.border_point = pos        self.hovered = inside        if inside:            self.dispatch('on_enter')        else:            self.dispatch('on_leave')
    def on_enter(self):        pass
    def on_leave(self):        pass
from kivy.factory import FactoryFactory.register('HoverBehavior', HoverBehavior)
if __name__=='__main__':    from kivy.uix.floatlayout import FloatLayout    from kivy.lang import Builder    from kivy.uix.label import Label    from kivy.base import runTouchApp    class HoverLabel(Label, HoverBehavior):        def on_enter(self, *args):            print "You are in, through this point", self.border_point
        def on_leave(self, *args):            print "You left through this point", self.border_point
    Builder.load_string('''<HoverLabel>:    text: "inside" if self.hovered else "outside"    pos: 200,200    size_hint: None, None    size: 100, 30    canvas.before:        Color:            rgb: 1,0,0        Rectangle:            size: self.size            pos: self.pos    ''')    fl = FloatLayout()    fl.add_widget(HoverLabel())    runTouchApp(fl)

Date: Sun, 28 Jun 2015 14:02:38 -0700

**Comment by inclement** [comment]
Your formatting is messed, up, indent the code lines by 4 spaces (and make sure line breaks are present correctly) to have it display properly.

**Comment by opqopq** [comment]
Better attempt:
https://gist.github.com/opqopq/15c707dc4cffc2b6455f

Date: Mon, 29 Jun 2015 02:45:46 -0700

**Comment by AvivC** [comment]
@opqopq Hey, the gist is great. May I copy and use it in my project? Under what conditions?

**Comment by opqopq** [comment]
sure. 
No condition, but not support :) 

Date: Fri, 29 Apr 2016 18:24:46 -0700
