### ISSUE TITLE
Line with dynamic dash on/off length

### ISSUE THREAD

**Issue by andnovar** [kivy/kivy#3474]
A new feature could be added to Line, so a Line can be created from a list of numbers that define how the line will be rendered. The list would be on an on/off configuration. For instance we can have [t1, z1, t2, z2, t3, z3, ... ] where the set of tn values can be the segments in which the line will be rendered and the zn values the one that the segments won't be rendered.
##

**Comment by matham** [comment]
Can you give an example of how that line would then be instantiated? I'm not sure I fully understand what you mean.

**Comment by andnovar** [comment]
a = Line(points=points, dash_list=[2,4,1,6,8,2]) This would create a line with the first dash length 2 then an offset of 4 then a dash lenght of 1 then an offset of 6 and so on.

**Comment by matham** [comment]
Implemented [here](https://github.com/kivy/kivy/pull/6269).
