### ISSUE TITLE
No "/tools/build_all.sh" file 

### ISSUE THREAD

**Issue by jahammons** [kivy/kivy#3475]
Hello,
I am new to kivy and trying to build an ios app using latest kivy-ios. I installed using the kivy instructions using homebrew (http://kivy.org/docs/guide/packaging-ios.html).
I am able to build an xcode project with no errors from kivy (I tried several from the . However, I am unable to build the project and get the error:

building file list ... rsync: link_stat "/tools/external/cookiecutter/." failed: No such file or directory (2)
done
sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

First, I had to make sure all files in the project folder were read/write. Then, I did some searching and a solution seems to be to run the /tools/build_all.sh script but there is no such file present from my installation. There is only biglink, cythonize.py, external, liblink and templates present in the tools folder. 
I don't know if the absence of the /tools/build_all.sh script is related to my xcode build failures but any comments/suggestions would be greatly appreciated.

**Comment by tito** [comment]
Hi,

The toolchain changed few month ago, and the instructions are not the same. Please refresh the page http://kivy.org/docs/guide/packaging-ios.html

Or read the instructions from https://github.com/kivy/kivy-ios

build-all.sh was a script from an older toolchain, this is not accurate anymore.

If you still have issue, please post the full log! thanks
