### ISSUE TITLE
Smudge in the display of the window

### ISSUE THREAD

**Issue by gustavklopp** [kivy/kivy#3479]
First installation on this computer.
I've got some "smudge" randomly dispersed in the window of any running program: Like the lines are fading at some place, the gray buttons show white smudge:
Here an example:
![screenshot from 2015-07-01 20 36 58](https://cloud.githubusercontent.com/assets/6438275/8462161/14edce00-2032-11e5-9b60-dc96d2e86914.png)

![screenshot from 2015-07-01 20 53 53](https://cloud.githubusercontent.com/assets/6438275/8462334/63bbbd52-2033-11e5-9ddc-9ff325f0e181.png)

![screenshot from 2015-07-01 20 55 59](https://cloud.githubusercontent.com/assets/6438275/8462355/9e37d74a-2033-11e5-917d-95a46f0bcbe1.png)

My configuration:
On Ubuntu 15.04:
```
[INFO   ] [Logger      ] Record log in /home/gus/.kivy/logs/kivy_15-07-01_18.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 10.6.0-devel'>
[INFO   ] [GL          ] OpenGL vendor <b'X.Org'>
[INFO   ] [GL          ] OpenGL renderer <b'Gallium 0.4 on AMD KABINI'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [VideoGstplayer] Using Gstreamer 1.4.5.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event6
[INFO   ] [MTD         ] Read event from </dev/input/event6>
[INFO   ] [Base        ] Start application main loop
```

**Comment by tito** [comment]
Doesn't look like a kivy issue, but more an issue with your graphic driver

**Comment by gustavklopp** [comment]
My graphic card seems to work though.
It's a AMD Radeon HD8330 (Kabini). Driver is the "AMD/ATI display driver wrapper from xserver-xorg-video-ati (open source, tested)".
Everything seems to work (even hibernate...) but I don't play games or anything. Is there some other way than in kivy than I test the graphic renderer on my graphic card???

**Comment by akshayaurora** [comment]
Just out of curiosity, what is your display resolution? I used to get the
same issue on high res displays, but don't get this anymore with the latest
updates to my os.

Tshirtman has a similar issue(on normal res display) if I remember
correctly with his AMD graphics cards, which was fixed with a graphics
driver

**Comment by gustavklopp** [comment]
@akshayaurora I am in 1600*900. It was indeed an AMD driver problem (I am on another computer on Nvidia without problem...)

Okay, I've solved the problem. Open source AMD driver? Does NOT work.
I had to switch to ATI proprietary driver (fglrx-updates)
