### ISSUE TITLE
KEP: allow tuple/list coordinates for Line.points

### ISSUE THREAD

**Issue by kived** [kivy/kivy#3481]
Could be handled at assignment time.

````python
if points and isinstance(points[0], (list, tuple)):
    points = list(itertools.chain(*points))
````

**Comment by trugate** [comment]
Thanks for suggesting this officially.  I would think most use-cases in kivy for Line points would be tuples or something similar, like widget.pos, widget.center.  Is there a use case where a list of x, y, x, y makes more sense?

**Comment by dessant** [comment]
test

**Comment by udiboy1209** [comment]
I'd like to work on this issue! Could you tell me where to start ?

**Comment by tshirtman** [comment]
I'd say here
https://github.com/kivy/kivy/blob/master/kivy/graphics/vertex_instructions_line.pxi#L675-L677

**Comment by udiboy1209** [comment]
I made the change suggested by @kived and tried testing it using the `lines` example: https://github.com/kivy/kivy/blob/master/examples/canvas/lines.py

When I run the example as it is, it works. But when I change the points declaration to this

    points = ListProperty([(500, 500), 300, 300, 500, 300, 500, 400, 600, 400])
    
it shows error:

    Exception TypeError: 'a float is required' in 'kivy.graphics.vertex_instructions.SmoothLine.build_smooth' ignored

I dont know whats wrong and what float is required? Does it mean that the elements in the list (coordinate values) should be float, but it is getting a tuple? (which would mean the change isn't working). Please help!

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/3866.
