### ISSUE TITLE
kv never raises exception. Normal feature?

### ISSUE THREAD

**Issue by gustavklopp** [kivy/kivy#3487]
For example:
```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button


class TestApp(App):
    def build(self):
        layout = BoxLayout(spacing=10)
        btn1 = Button(text='Hello', size_int=(.7, 1))
        btn2 = Button(text='World', size_int=(.3, 1))
        layout.add_widget(btn1)
        layout.add_widget(btn2)
        return layout

if __name__ == '__main__':
    TestApp().run()
```

see the error in `size_int` in place of `size_hint`? The app will run (but no as expected obviously), without informing us of this syntax error.

**Comment by tito** [comment]
This is intended, the baseclass accept kwargs, and we can't know if you are actually using part of the kwargs or not :)

**Comment by matham** [comment]
This was actually recently fixed in master to allow cooperative inheritance, where if a kwargs is not a property and is not used by kivy, kivy will forward it on. If no one eats it, a error will be raised by object (although I'm not sure if only py3 raises an exception).
