### ISSUE TITLE
kivy.uix.image display black box instead of png file (ubuntu 14.04.2, kivy 1.9.0 from ppa)

### ISSUE THREAD

**Issue by maxz000** [kivy/kivy#3488]
Image or AsyncImage displays black box instead of png image which larger than 1 Mb, no errors, no exceptions, just black box.
ubuntu 14.04.2 (kernel 3.16.0-30-generic) 32-bit, kivy 1.9.0 from stable ppa
But it works well on fedora 22 with the same version of kivy from fedora repo.

**Comment by inclement** [comment]
I'd normally guess that this is because the image exceeds the gpu driver's max texture size. Are your tests on the same machine, with up to date drivers?

**Comment by tito** [comment]
Same as @inclement. We can't display pure image that are larger than the maximum texture size. If you have an issue with a specific image, please share it.
