### ISSUE TITLE
JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by pat1** [kivy/kivy#3490]
Running my app I get:

I/python  ( 3942): Bluetooth try to reconnect
D/STATUSBAR-NotificationService( 2036): Noti Alert - mSystemReady:true, AlertEnabled:true
V/BluetoothSocket.cpp( 3942): initSocketNative
V/BluetoothSocket.cpp( 3942): ...fd 140 created (RFCOMM, lm = 26)
V/BluetoothSocket.cpp( 3942): initSocketFromFdNative
D/BluetoothPolicyService( 2036): getBluetoothDataTransferAllowed 
D/StatusBar( 2210): expanding top notification at 2entry.userCollapsed() = false
D/BluetoothPolicyService( 2036): MDM: isProfileEnabled = true
D/BluetoothUtils( 3942): isSocketAllowedBySecurityPolicy start : device null
V/BluetoothService.cpp( 2036): createDeviceNative
V/BluetoothService.cpp( 2036): createDeviceNative
V/BluetoothEventLoop.cpp( 2036): onCreateDeviceResult
V/BluetoothEventLoop.cpp( 2036): onCreateDeviceResult
E/BluetoothEventLoop.cpp( 2036): onCreateDeviceResult: D-Bus error: org.bluez.Error.AlreadyExists (Already Exists)
V/BluetoothService.cpp( 2036): discoverServicesNative
V/BluetoothService.cpp( 2036): ... Object Path = /org/bluez/2799/hci0/dev_20_13_08_28_09_52
V/BluetoothService.cpp( 2036): ... Pattern = , strlen = 0
V/BluetoothEventLoop.cpp( 2036): onDiscoverServicesResult
V/BluetoothEventLoop.cpp( 2036): ... Device Path = /org/bluez/2799/hci0/dev_20_13_08_28_09_52
E/BluetoothEventLoop.cpp( 2036): onDiscoverServicesResult: D-Bus error: org.bluez.Error.InProgress (In Progress)
V/BluetoothEventManager( 7026): Received android.bluetooth.device.action.UUID
I/CachedBluetoothDevice( 7026): updateProfiles
E/dalvikvm( 3942): JNI ERROR (app bug): local reference table overflow (max=512)
W/dalvikvm( 3942): JNI local reference table (0x5ebe96b8) dump:
W/dalvikvm( 3942):   Last 10 entries (of 512):
W/dalvikvm( 3942):       511: 0x41b6d178 java.lang.StackTraceElement
W/dalvikvm( 3942):       510: 0x41b6d780 java.lang.StackTraceElement[] (5 elements)
W/dalvikvm( 3942):       509: 0x41afb990 java.lang.String "Service discover... (24 chars)
W/dalvikvm( 3942):       508: 0x410d8938 java.lang.Class<java.lang.Throwable>
W/dalvikvm( 3942):       507: 0x410d8938 java.lang.Class<java.lang.Throwable>
W/dalvikvm( 3942):       506: 0x410d8938 java.lang.Class<java.lang.Throwable>
W/dalvikvm( 3942):       505: 0x410d8890 java.lang.Class<java.lang.Object>
W/dalvikvm( 3942):       504: 0x41b6d0d8 java.io.IOException
W/dalvikvm( 3942):       503: 0x41afb990 java.lang.String "Service discover... (24 chars)
W/dalvikvm( 3942):       502: 0x410d8938 java.lang.Class<java.lang.Throwable>
W/dalvikvm( 3942):   Summary:
W/dalvikvm( 3942):       355 of java.lang.Class (30 unique instances)
W/dalvikvm( 3942):         1 of java.lang.StackTraceElement
W/dalvikvm( 3942):         1 of java.lang.StackTraceElement[] (5 elements)
W/dalvikvm( 3942):        80 of java.lang.String (7 unique instances)
W/dalvikvm( 3942):        75 of java.io.IOException (75 unique instances)
E/dalvikvm( 3942): Failed adding to JNI local ref table (has 512 entries)
I/dalvikvm( 3942): "Thread-614" prio=5 tid=11 RUNNABLE
I/dalvikvm( 3942):   | group="main" sCount=0 dsCount=0 obj=0x41afd2d0 self=0x410cab80
I/dalvikvm( 3942):   | sysTid=3966 nice=0 sched=0/0 cgrp=[no-cpu-subsys] handle=1091350480
I/dalvikvm( 3942):   | schedstat=( 17368926971 6626251253 19284 ) utm=1525 stm=211 core=0
I/LocalBluetoothProfileManager( 7026): updateProfiles
D/BluetoothDevicePreference( 7026): Is my device connected::false
I/BluetoothDevicePreference( 7026): summaryResId != 0
I/dalvikvm( 3942):   at org.renpy.android.PythonService.nativeStart(Native Method)
I/dalvikvm( 3942):   at org.renpy.android.PythonService.run(PythonService.java:114)
I/dalvikvm( 3942):   at java.lang.Thread.run(Thread.java:856)
I/dalvikvm( 3942): 
E/dalvikvm( 3942): VM aborting
F/libc    ( 3942): Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 3966 (Thread-614)
I/DEBUG   ( 1690): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 1690): Build fingerprint: 'samsung/GT-I9070/GT-I9070:4.1.2/JZO54K/I9070XXLQL:user/release-keys'
I/DEBUG   ( 1690): pid: 3942, tid: 3966, name: Thread-614  >>> org.test.rmap:PythonService <<<
I/DEBUG   ( 1690): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadd00d
D/dalvikvm( 2722): GC_CONCURRENT freed 730K, 20% free 9586K/11975K, paused 3ms+2ms, total 38ms
D/dalvikvm( 2722): WAIT_FOR_CONCURRENT_GC blocked 17ms
D/STATUSBAR-NetworkController( 2210): refreshSignalCluster: data=-1 bt=false
D/dalvikvm( 2722): GC_CONCURRENT freed 536K, 21% free 9554K/11975K, paused 2ms+3ms, total 34ms
D/dalvikvm( 2722): WAIT_FOR_CONCURRENT_GC blocked 16ms
D/dalvikvm( 2722): GC_CONCURRENT freed 472K, 21% free 9560K/11975K, paused 2ms+5ms, total 39ms
I/DEBUG   ( 1690):     r0 00000000  r1 00000000  r2 deadd00d  r3 00000000
I/DEBUG   ( 1690):     r4 408681a8  r5 0000020c  r6 410cab80  r7 410cac28
I/DEBUG   ( 1690):     r8 5ea8bb70  r9 5ea99a20  sl 5d60ebe4  fp 00000000
I/DEBUG   ( 1690):     ip 00004000  sp 5d286750  lr 40036b69  pc 40803e88  cpsr 60000030
I/DEBUG   ( 1690):     d0  74726f6261204d56  d1  000000006c756e28
I/DEBUG   ( 1690):     d2  6e616c2e6176616a  d3  6461657268542e67
I/DEBUG   ( 1690):     d4  0074006f006f0074  d5  00420049002e0068
I/DEBUG   ( 1690):     d6  007400650075006c  d7  00680074006f006f
I/DEBUG   ( 1690):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   ( 1690):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   ( 1690):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   ( 1690):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   ( 1690):     d16 416f257010000000  d17 3fe0000000000000
I/DEBUG   ( 1690):     d18 3fdffb111d03d6c0  d19 3fe0000000000000
I/DEBUG   ( 1690):     d20 3fe00277717e14a0  d21 0000000000000000
I/DEBUG   ( 1690):     d22 0000000000000000  d23 bf66c16c16bebd93
I/DEBUG   ( 1690):     d24 3fc555555555553e  d25 3ff0000000000000
I/DEBUG   ( 1690):     d26 3fd55555518f264d  d27 3fdb6db6db6fabff
I/DEBUG   ( 1690):     d28 3fe3333333333303  d29 0000000000000000
I/DEBUG   ( 1690):     d30 4000000000000000  d31 0000000000000000
I/DEBUG   ( 1690):     scr 20000011
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): backtrace:
I/DEBUG   ( 1690):     #00  pc 00045e88  /system/lib/libdvm.so (dvmAbort+75)
I/DEBUG   ( 1690):     #01  pc 00048ae5  /system/lib/libdvm.so
I/DEBUG   ( 1690):     #02  pc 0004c947  /system/lib/libdvm.so
I/DEBUG   ( 1690):     #03  pc 001db78c  /data/data/org.test.rmap/files/libpymodules.so
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): stack:
I/DEBUG   ( 1690):          5d286710  00000001  
I/DEBUG   ( 1690):          5d286714  40065eb4  
I/DEBUG   ( 1690):          5d286718  40065eb4  
I/DEBUG   ( 1690):          5d28671c  40065eb4  
I/DEBUG   ( 1690):          5d286720  40065eb4  
I/DEBUG   ( 1690):          5d286724  40036b69  /system/lib/libc.so (__sflush_locked+36)
I/DEBUG   ( 1690):          5d286728  40060774  /system/lib/libc.so
I/DEBUG   ( 1690):          5d28672c  40065eb4  
I/DEBUG   ( 1690):          5d286730  00000000  
I/DEBUG   ( 1690):          5d286734  40037b39  /system/lib/libc.so (_fwalk+32)
I/DEBUG   ( 1690):          5d286738  408681a8  /system/lib/libdvm.so
I/DEBUG   ( 1690):          5d28673c  0000020c  
I/DEBUG   ( 1690):          5d286740  410cab80  
I/DEBUG   ( 1690):          5d286744  410cac28  
I/DEBUG   ( 1690):          5d286748  df0027ad  
I/DEBUG   ( 1690):          5d28674c  00000000  
I/DEBUG   ( 1690):     #00  5d286750  00000027  
I/DEBUG   ( 1690):          5d286754  6c756e28  
I/DEBUG   ( 1690):          5d286758  0000296c  
I/DEBUG   ( 1690):          5d28675c  00000000  
I/DEBUG   ( 1690):          5d286760  00000000  
I/DEBUG   ( 1690):          5d286764  00000000  
I/DEBUG   ( 1690):          5d286768  00000000  
I/DEBUG   ( 1690):          5d28676c  00000000  
I/DEBUG   ( 1690):          5d286770  00000000  
I/DEBUG   ( 1690):          5d286774  00000000  
I/DEBUG   ( 1690):          5d286778  00000000  
I/DEBUG   ( 1690):          5d28677c  00000000  
I/DEBUG   ( 1690):          5d286780  00000000  
I/DEBUG   ( 1690):          5d286784  00000000  
I/DEBUG   ( 1690):          5d286788  00000000  
I/DEBUG   ( 1690):          5d28678c  00000000  
I/DEBUG   ( 1690):          ........  ........
I/DEBUG   ( 1690):     #01  5d286968  00000000  
I/DEBUG   ( 1690):          5d28696c  41b6d178  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   ( 1690):          5d286970  4080a965  /system/lib/libdvm.so
I/DEBUG   ( 1690):          5d286974  5eadac88  
I/DEBUG   ( 1690):          5d286978  00000000  
I/DEBUG   ( 1690):          5d28697c  4080a94b  /system/lib/libdvm.so
I/DEBUG   ( 1690):     #02  5d286980  5d286990  
I/DEBUG   ( 1690):          5d286984  5d2869a4  
I/DEBUG   ( 1690):          5d286988  410cab80  
I/DEBUG   ( 1690):          5d28698c  5d2869a4  
I/DEBUG   ( 1690):          5d286990  41b6d9a0  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   ( 1690):          5d286994  00000007  
I/DEBUG   ( 1690):          5d286998  5ddc45dc  /data/data/org.test.rmap/files/libpymodules.so
I/DEBUG   ( 1690):          5d28699c  5d9d1790  /data/data/org.test.rmap/files/libpymodules.so
I/DEBUG   ( 1690):          5d2869a0  573f8208  /dev/ashmem/dalvik-LinearAlloc (deleted)
I/DEBUG   ( 1690):          5d2869a4  4080a903  /system/lib/libdvm.so
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near r4:
I/DEBUG   ( 1690):     40868188 00000000 00000000 00000000 00000000  ................
I/DEBUG   ( 1690):     40868198 00000000 00000000 00000000 00000000  ................
I/DEBUG   ( 1690):     408681a8 40ea8888 400f0fd0 00800000 10000000  ...@...@........
I/DEBUG   ( 1690):     408681b8 04000000 00004000 00006000 00000001  .....@...`......
I/DEBUG   ( 1690):     408681c8 00000101 00000002 00000001 00000000  ................
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near r6:
I/DEBUG   ( 1690):     410cab60 00000000 5d61bad0 5ea825d0 00000011  ......a].%.^....
I/DEBUG   ( 1690):     410cab70 5e1d2760 40065534 00000168 00000453  `'.^4U.@h...S...
I/DEBUG   ( 1690):     410cab80 58616bde 510faf90 5772d908 510d8000  .kaX...Q..rW...Q
I/DEBUG   ( 1690):     410cab90 41b00ef0 00000007 5d287da8 00000000  ...A.....}(]....
I/DEBUG   ( 1690):     410caba0 5d287ddc 0000000b 00000000 407dc080  .}(]..........}@
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near r7:
I/DEBUG   ( 1690):     410cac08 00000000 00000000 00000000 00000000  ................
I/DEBUG   ( 1690):     410cac18 00001b52 40868724 410fbc98 5744a520  R...$..@...A .DW
I/DEBUG   ( 1690):     410cac28 00000200 5ebe7428 00000001 00000200  ....(t.^........
I/DEBUG   ( 1690):     410cac38 00000200 00000000 00000002 590e38ac  .............8.Y
I/DEBUG   ( 1690):     410cac48 590e38ac 00000004 591f7328 575332d8  .8.Y....(s.Y.2SW
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near r8:
I/DEBUG   ( 1690):     5ea8bb50 00000000 58bb7290 58ae2030 36383233  .....r.X0 .X3286
I/DEBUG   ( 1690):     5ea8bb60 5ea8bb18 5ea8bd58 fffffffd 31277520  ...^X..^.... u'1
I/DEBUG   ( 1690):     5ea8bb70 00000003 5dde0a84 5de14ba0 574bb1d8  .......].K.]..KW
I/DEBUG   ( 1690):     5ea8bb80 1e0004d2 5ea894a0 5ea6c440 5ea92790  .......^@..^.'.^
I/DEBUG   ( 1690):     5ea8bb90 5ea3df68 5d60f6cc 00000000 58bb7290  h..^..`].....r.X
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near r9:
I/DEBUG   ( 1690):     5ea99a00 58b1c1b8 58b1c1b8 5ed1a4a8 00000000  ...X...X...^....
I/DEBUG   ( 1690):     5ea99a10 5ed1a070 5ea99920 fffffffd ffffffff  p..^ ..^........
I/DEBUG   ( 1690):     5ea99a20 00000001 5eadb200 5de14c40 00000000  .......^@L.]....
I/DEBUG   ( 1690):     5ea99a30 1de004c2 5ea89020 00000000 00000000  .... ..^........
I/DEBUG   ( 1690):     5ea99a40 5ea99a70 5ed0d2f8 fffffffe 6327202c  p..^...^...., 'c
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near sl:
I/DEBUG   ( 1690):     5d60ebc4 5d5ab8e4 5d5deb50 5d5deb58 5d5deb60  ..Z]P.]]X.]]`.]]
I/DEBUG   ( 1690):     5d60ebd4 4002f555 5d60b0d0 5d60afc0 00000000  U..@..`]..`]....
I/DEBUG   ( 1690):     5d60ebe4 00000000 00000000 00000000 4003af9d  ...............@
I/DEBUG   ( 1690):     5d60ebf4 4003b0b5 4002a6d0 40037b51 4003b465  ...@...@Q{.@e..@
I/DEBUG   ( 1690):     5d60ec04 40038119 40037119 40037155 40037095  ...@.q.@Uq.@.p.@
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near ip:
I/DEBUG   ( 1690):     00003fe0 ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   ( 1690):     00003ff0 ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   ( 1690):     00004000 ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   ( 1690):     00004010 ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   ( 1690):     00004020 ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory near sp:
I/DEBUG   ( 1690):     5d286730 00000000 40037b39 408681a8 0000020c  ....9{.@...@....
I/DEBUG   ( 1690):     5d286740 410cab80 410cac28 df0027ad 00000000  ...A(..A.'......
I/DEBUG   ( 1690):     5d286750 00000027 6c756e28 0000296c 00000000  '...(null)......
I/DEBUG   ( 1690):     5d286760 00000000 00000000 00000000 00000000  ................
I/DEBUG   ( 1690):     5d286770 00000000 00000000 00000000 00000000  ................
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): code around pc:
I/DEBUG   ( 1690):     40803e68 34bcf8d3 ecb4f7d7 461d2300 b1525d1a  ...4.....#.F.]R.
I/DEBUG   ( 1690):     40803e78 18ad3301 7f00f5b3 e004d1f8 4a0a4798  .3...........G.J
I/DEBUG   ( 1690):     40803e88 f7d77015 490cecac 4a0c2006 44794c0c  .p.....I. .J.LyD
I/DEBUG   ( 1690):     40803e98 447c447a eb5ef7d7 f7d72000 6ca3ec04  zD|D..^.. .....l
I/DEBUG   ( 1690):     40803ea8 d1eb2b00 bf00e7eb deadd00d 0005fcc0  .+..............
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): code around lr:
I/DEBUG   ( 1690):     40036b48 447e4e08 68336836 f000b10b 4620fa4c  .N~D6h3h....L. F
I/DEBUG   ( 1690):     40036b58 ffcaf7ff 68304605 4620b110 fa50f000  .....F0h.. F..P.
I/DEBUG   ( 1690):     40036b68 bd704628 0002995a 4604b570 4811b928  (Fp.Z...p..F(..H
I/DEBUG   ( 1690):     40036b78 e8bd4478 f0004070 4e0fbfcb 6836447e  xD..p@.....N~D6h
I/DEBUG   ( 1690):     40036b88 b10b6833 fa2ff000 f01089a0 d1060f18  3h..../.........
I/DEBUG   ( 1690): 
I/DEBUG   ( 1690): memory map around fault addr deadd00d:
I/DEBUG   ( 1690):     be891000-be8b2000 [stack]
I/DEBUG   ( 1690):     (no map for address)
I/DEBUG   ( 1690):     ffff0000-ffff1000 [vectors]
I/DEBUG   ( 1690): !@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 3942
I/BootReceiver( 2036): Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
I/dumpstate( 4326): begin
V/BluetoothEventLoop.cpp( 2036): onDiscoverServicesResult
V/BluetoothEventLoop.cpp( 2036): ... Device Path = /org/bluez/2799/hci0/dev_20_13_08_28_09_52
E/BluetoothEventLoop.cpp( 2036): onDiscoverServicesResult: D-Bus error: org.bluez.Error.ConnectionAttemptFailed (Host is down)
V/BluetoothEventManager( 7026): Received android.bluetooth.device.action.UUID
I/CachedBluetoothDevice( 7026): updateProfiles
I/LocalBluetoothProfileManager( 7026): updateProfiles
D/BluetoothDevicePreference( 7026): Is my device connected::false

**Comment by tito** [comment]
Unless we know what you do, please ensure you're not keeping any reference to a java object. You're limited to 512 (android internals) references.

There is nothing we can do, just analyse your code first, or give us a reproducible code :)

**Comment by pat1** [comment]
Sorry, I give no information about this problem.
Now I can reproduce it.
I can confirm that this is not a kivy bug, but any suggestions about this problem would be very usefull.
I use pyjnius to access bluetooth profile spp based on "Bluetooth example on Android using Python / Pyjnius" https://gist.github.com/tito/7432757
I use the class below to access bluetooth and on error I close and recreate object. After some loop I get the error reported.
Now is not clear to me how to free reference to a java object with pyjnius; what I now is that python and java use garbage collector to free object ...

class TransportBLUETOOTH(Transport):
    """receive and send to bluetooth serial port by java api.

    tested with android and arduino
    """

    try:
        from jnius import autoclass
        BluetoothAdapter = autoclass('android.bluetooth.BluetoothAdapter')
        #BluetoothDevice = autoclass('android.bluetooth.BluetoothDevice')
        #BluetoothSocket = autoclass('android.bluetooth.BluetoothSocket')
        UUID = autoclass('java.util.UUID')
    except:
        BluetoothAdapter = None
        #BluetoothDevice = None
        #BluetoothSocket = None
        UUID = None

    def __init__(self,name ="mybluetooth",timeout=5,logfunc=log_dummy):
    
        self.recv_stream = None
        self.send_stream = None
        self.socket = None
        self.timeout=timeout
        self.log    = logfunc
        self.name=name

        if self.BluetoothAdapter is not None:
            paired_devices = self.BluetoothAdapter.getDefaultAdapter().getBondedDevices().toArray()
            for device in paired_devices:
                if device.getName() == self.name:
                    self.socket = device.createRfcommSocketToServiceRecord(
                        self.UUID.fromString("00001101-0000-1000-8000-00805F9B34FB"))
                    self.recv_stream = self.socket.getInputStream()
                    self.send_stream = self.socket.getOutputStream()
                    break
            try:
                self.socket.connect()
                self.log( "bluetooth name %s: %s" % (self.name,"connected") )
            except:
                try:
                    self.recv_stream.close()
                except:
                    pass
                try:
                    self.send_stream.close()
                except:
                    pass
                try:
                    self.socket.close()
                except:
                    pass

                self.socket = None
                self.recv_stream = None
                self.send_stream = None
                self.log( "bluetooth name %s: %s" % (self.name,"NOT connected") )


    def send(self, string):
        """write data to Bluetooth """

        #clean input buffer
        instring=""
        while self.recv_stream.available() > 0:
            instring += chr(self.recv_stream.read())
        if instring != "":
            self.log( "bluetooth port (%s): >%s<" % ("SKIP",instring) )

        self.log( "bluetooth port (%s): %s" % ("SEND",string) )
        self.send_stream.write(string+"\n")
        self.send_stream.flush()

    def readline(self):

        string=""
        starttime = time.time()
        while  time.time() - starttime < self.timeout:
            while self.recv_stream.available() > 0:
                buffer = self.recv_stream.read()
                string += chr(buffer)
                if buffer == 13:
                    return string
        if string != "":
            self.log( "bluetooth port (%s): >%s<" % ("SKIP",string) )
        return ""

    def recv(self):
        """read data from Bluetooth """

        string=self.readline()
        self.log( "bluetooth port (%s): >%s<" % ("RECEIVE",string) )
        while string.startswith("#"):
            string=self.readline()
            self.log( "bluetooth port (%s): >%s<" % ("RECEIVE",string) )

        ## del buffer in timeout case
        #while self.recv_stream.available() > 0:
        #    self.recv_stream.read()

        return string


    def close( self ):
        if self.recv_stream is not None:
            self.log( "close recv_stream %s" % repr(self.name) )
            self.recv_stream.close()
            self.recv_stream = None

        if self.send_stream is not None:
            self.log( "close send_stream %s" % repr(self.name) )
            self.send_stream.close()
            self.send_stream = None

        if self.socket is not None:
            self.log( "close bluetooth socket %s" % repr(self.name) )
            self.socket.close()
            self.socket=None

    def __repr__(self):
        return "<TransportBluetooth, %s>" % repr(self.name)

**Comment by tito** [comment]
Honestly, it really depend. On the initial log you sent, try to look where the object are created. For example:

```
W/dalvikvm( 3942): Last 10 entries (of 512):
W/dalvikvm( 3942): 511: 0x41b6d178 java.lang.StackTraceElement
W/dalvikvm( 3942): 510: 0x41b6d780 java.lang.StackTraceElement
W/dalvikvm( 3942): 509: 0x41afb990 java.lang.String "Service discover... (24 chars)
W/dalvikvm( 3942): 508: 0x410d8938 java.lang.Class
W/dalvikvm( 3942): 507: 0x410d8938 java.lang.Class
W/dalvikvm( 3942): 506: 0x410d8938 java.lang.Class
W/dalvikvm( 3942): 505: 0x410d8890 java.lang.Class
W/dalvikvm( 3942): 504: 0x41b6d0d8 java.io.IOException
W/dalvikvm( 3942): 503: 0x41afb990 java.lang.String "Service discover... (24 chars)
W/dalvikvm( 3942): 502: 0x410d8938 java.lang.Class
W/dalvikvm( 3942): Summary:
W/dalvikvm( 3942): 355 of java.lang.Class (30 unique instances) <<<<<<<<<<<<<
W/dalvikvm( 3942): 1 of java.lang.StackTraceElement
W/dalvikvm( 3942): 1 of java.lang.StackTraceElement
W/dalvikvm( 3942): 80 of java.lang.String (7 unique instances)
W/dalvikvm( 3942): 75 of java.io.IOException (75 unique instances) <<<<<<<<<<<<<<<<<<
```

355 of java.lang.Class or 75 of IOException, theses seems bad. Same for String.

Try too look where they are fired or created :)

**Comment by tito** [comment]
@pat1 I've recently fixes leaks in an user contribution when the an Exception is described. This might resolve the issue you got. Please update pyjnius (or clean your whole build and start from scratch).

Commit: http://git.io/vYgNh

**Comment by pat1** [comment]
Thanks a lot !
As a note is not so simple to update jnius inside buildozer build system ...
see recipes/pyjnius/recipe.sh
I will write a report for my app when I will get a buildsystem with new jnius inside

**Comment by pat1** [comment]
ok, works.
problem solved.
