### ISSUE TITLE
Language support in kivy

### ISSUE THREAD

**Issue by ailisp** [kivy/kivy#3492]
Hello, everyone here! I am a kivy beginner in China. Kivy is wonderful in many aspects but it still seems to be incomplete in language support and internationalization. By default, it can't display characters in other language, unless one of a font file which support this language is set in kivy and python file. And the support for input these characters by an input method. For displaying text in a non-English language, is it possible to provide a gettext-like translator for kivy and render fonts with system default font which can display text in a local language? For inputing text in other language, I am trying to work out based on some solutions for inputing text in SDL and do you have some good solutions? 
Another small question is kivy seems to base on pygame.Though pygame is a mature framework, it seems to be inactive for a long time (last update is in 2009), Is it possible that kivy developers modify pygame themselves or replace it with other library in the future?
Thank you for your attention.

**Comment by inclement** [comment]
> For displaying text in a non-English language, is it possible to provide a gettext-like translator for kivy and render fonts with system default font which can display text in a local language?

You can use normal python gettext methods for this, though it's not something I know about, other pepole may be able to help better. Not sure about system default fonts either, but again other people know more about this part of kivy.

> Another small question is kivy seems to base on pygame.Though pygame is a mature framework, it seems to be inactive for a long time (last update is in 2009), Is it possible that kivy developers modify pygame themselves or replace it with other library in the future?

We used pygame as a default window (and other stuff) provider, but kivy never depended on it, and we recently deprecated its use as a backend. As of kivy 1.9, Kivy uses SDL2 for most things instead.

I'll note that pygame actually is still developed though - for some reason they haven't made a release for years, but their master branch is still active.

I'm closing this as it's not a technical issue and we don't really use these channels for user support. If you want to raise a specific technical bug then feel free (e.g. a feature request or pull request for an internationalised input method), or if you want to continue discussing more generally I suggest posting on the kivy-users mailing list.

**Comment by hackebrot** [comment]
H @ailisp!

I based my Cookiecutter template on the following approach and it seems to work just fine. https://github.com/jtownley/kivy-gettext-example It uses GNU gettext and it enables you to change the language during runtime.

Raphael

**Comment by dessant** [comment]
@hackebrot, thanks for the link. :kissing:
