### ISSUE TITLE
TabbedPanel.switch_to() does not appear to work

### ISSUE THREAD

**Issue by ahed87** [kivy/kivy#3493]
Hi,

first of all I would like to congratulate on the great work that kivy is, keep it up!!
I really hope that it will grow further and become the natural choise for python and gui's.

Using the code below, when the code has run, "tab1" is not selected.
I'm running windows portable installation Kivy-1.9.0-py3.4-win32-x64 and have w8.1
It works fine to select the tab manually.
Maybe .switch_to is not meant to make the tab active, but at least I would assume that this is what it does.
I also made some smaller attempts to see if I could make it selected/active with some of the other methods in TabbedPanel, but could not get it to work.

I decided to skip the "default_tab" (which by the way is preselected also on my computer), since I did not want different ways to assign the tabs.

Is this a bug, or can I get the tab selected another way (not using default tab)?

```
from kivy.app import App
from kivy.uix.tabbedpanel import TabbedPanel, TabbedPanelHeader

class mainw(TabbedPanel):
    def __init__(self, **kwargs):
        super(mainw, self).__init__(**kwargs)

        self.do_default_tab = False
        self.tab_width = 150

        # create the tabs
        tab1 = TabbedPanelHeader(text='tab1')
        self.add_widget(tab1)

        tab2 = TabbedPanelHeader(text='tab2')
        self.add_widget(tab2)

        self.switch_to(tab1) # does not work and also does not throw error...


class tbpApp(App):
     def build(self):
        return mainw()

if __name__ == '__main__':
    tbpApp().run()
```

**Comment by akshayaurora** [comment]
You are inheriting from the widget and trying to add to the widget before it has finished setting up in `__init__`.

You need to let the widget initiate completely and then add your tabs to it.  first tab added is selected by default.

This would be automatically taken care of if you used kv.

Just look at the examples `examples/widgets/tabbed*...`

**Comment by ahed87** [comment]
ok, kind of got it, but am still not entirely sure of how to do it in pure python.

Although the "kv-language" seems very easy on the simple examples,I cannot wrap my head around how it works in more complex examples at the moment.
For me it's a deliberate choice not to use the kvl at the moment.
If I don't understand where there is a problem (which I definitely don't if it's done by kvl), 
it's kind of hard to fix it on my own as well.And if I'm stuck with the simple examples in kvl
the usability of a tool like kivy falls drastically behind (in my humble opinion)....
So for me at the moment when seriously trying to learn kivy I find it easier todo it in python where at least I think I understand better what's happening.

**Comment by dessant** [comment]
@ahed87 this is one way:

```python
from functools import partial

from kivy.app import App
from kivy.uix.tabbedpanel import TabbedPanel, TabbedPanelHeader
from kivy.clock import Clock


class mainw(TabbedPanel):
    def __init__(self, **kwargs):
        super(mainw, self).__init__(**kwargs)

        self.do_default_tab = False
        self.tab_width = 150

        # create the tabs
        tab1 = TabbedPanelHeader(text='tab1')
        self.add_widget(tab1)

        tab2 = TabbedPanelHeader(text='tab2')
        self.add_widget(tab2)

        Clock.schedule_once(partial(self.switch, tab1), 0)

    def switch(self, tab, *args):
        self.switch_to(tab)

class tbpApp(App):
     def build(self):
        return mainw()

if __name__ == '__main__':
    tbpApp().run()
```

If you have further questions, visit our support channels: https://github.com/kivy/kivy#support.

**Comment by ahed87** [comment]
Great thanks a lot for that working example!

Although it did actually not work with 0 (=next frame) as time on my computer,
When putting 2s it did not work either,
but it did work with 3s callback (I guess that's how long the initiation is on my computer....)

Seeing full examples in work where a particular issue is adressed is for me by far the best way to be able to get a full understanding for what needs to be done in different cases.

PS: I did try once or twice with clock, but never seriously tried also with partial, missed that part

**Comment by janssen** [comment]
How would we know this by reading the documentation?

**Comment by andresbrocco** [comment]
How would we know this by reading the documentation? And why close this? It's still broken for some indeterminate time after you've initialized it, and there's no way to tell when it's "not broken".

**Comment by matham** [comment]
Hmm, yeah this needs to be documented.

**Comment by andresbrocco** [comment]
> Hmm, yeah this needs to be documented.

I'll try to document it as my first contribution to kivy!
@matham, could you instruct me where exactly would be the best place to document it? Would it be in the docstring of the "switch_to()" source code itself?

**Comment by matham** [comment]
Yeah, in `switch_to` is a good place!

**Comment by Julian-O** [comment]
Was documented in Jan 2021. Closing as fixed.
