### ISSUE TITLE
Streaming audio with ffpyplayer expects metadata

### ISSUE THREAD

**Issue by Cheaterman** [kivy/kivy#3504]
If you try the following test file and click the button, it'll stay blue, because the application will hang.

FFPyPlayer seems to be expecting metadata from my stream, and this will not happen. Furthermore, it should expect them for 10 seconds according to the code (kivy/core/audio/audio_ffpyplayer.py L128) but for some reason time.clock() - s doesn't return anything near seconds (at least here).

Here is the test file:
https://bpaste.net/show/440f6a5812cf

It works if I comment L126-129 in audio_ffpyplayer.py.
##

**Comment by Julian-O** [comment]
There is no longer enough information here to test it or investigate.

Closing as stale.

If the problem still exists, please let us know more details.

**Comment by rnixx** [comment]
IMHO this issue is related to streaming in general, and it probably is solved via https://github.com/kivy/kivy/commit/c4a52ed0788b7389245c487b8d155cb7fdf8cbf7
