### ISSUE TITLE
Kivy is not working on mac os x 10.10.4

### ISSUE THREAD

**Issue by artyomdangizyan** [kivy/kivy#3505]
I was trying to lunch kivy app and got the following error in mac os x 10.10.4
<img width="526" alt="screen shot 2015-07-15 at 10 59 30" src="https://cloud.githubusercontent.com/assets/6322880/8692579/362ab938-2ad8-11e5-95a8-d81fc135bff6.png">

**Comment by akshayaurora** [comment]
Make sure you are using the latest version of the download from kivy's site, do you still get the error with that?

**Comment by tshirtman** [comment]
Closing, please reopen if you have more information, kivy is known to work on osx 10.10
