### ISSUE TITLE
how to run kivy on A20(allwinner )

### ISSUE THREAD

**Issue by pll19840511** [kivy/kivy#3507]
Allwinner A20 (sun7i) SoC features a Dual-Core Cortex-A7 ARM CPU, and a Mali400 MP2 GPU(Complies with OpenGL ES 2.0 ) from ARM. it is cheap and powerful.How can i run kivy on it?

**Comment by thopiekar** [comment]
Install a Linux distribution on it, eg. Debian and use the package management tool to install kivy. The package should be called python-kivy and other distributions should use almost the same name. If it doesn't work well or doesn't work at all try to download the latest sources and make a manual build (after installing the dependencies of course).

If you are going to install Ubuntu on it you can use our Daily PPA to update kivy to the latest codebase.

Good luck

**Comment by matham** [comment]
I guess we can close this then?

**Comment by thopiekar** [comment]
Think so. I guess there will be feedback on problems 😉
(He can reopen the issue then.)
