### ISSUE TITLE
Binding in kv does not work in certain cases

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3529]
If the widget in this example is added from kv, `center` is updated when the parent width changes:

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory

kv = """
<NewB@Button>:
    size_hint: None, None
    size: 20, 20
    center: (self.parent.width - 40, 40) if self.parent else (0, 0)

Widget:
    NewB
"""


class TestApp(App):

    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

But if we instantiate it and add it from python, `center` is not updated when the parent width changes:

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory

kv = """
<NewB@Button>:
    size_hint: None, None
    size: 20, 20
    center: (self.parent.width - 40, 40) if self.parent else (0, 0)

Widget:
"""


class TestApp(App):

    def on_start(self, *args):
        b = Factory.NewB()
        self.root.add_widget(b)

    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

**Comment by kived** [comment]
You can turn on rebind:
````python
from kivy.uix.widget import Widget
Widget.parent.rebind = True
````

Though I'd suggest that maybe the `parent` property should have `rebind=True` by default.

**Comment by dessant** [comment]
@kived thanks ;), i agree, in this case it might be warranted to do it by default.

**Comment by matham** [comment]
@dessant, we'll need to get it in writing from @akshayaurora that we can change to `rebind=True` by default before we can do that. I'm sure he won't like that, though.

**Comment by dessant** [comment]
@matham why would he not like it? :P It is backward compat, and it would only affect a couple of kivy props, it would be good to have it for `children` too.

**Comment by akshayaurora** [comment]
Why would I not like that...cause it's not needed by default,  case in point @dessant came across this issue after using kivy for 2+ years.

Adding rebind = True to widget's parent/children/anyObjPropThatHoldsAnotherWidget would mean rebinds for each of them even when they are properly bound == redundant.

vs Properly documenting this and hilting this in the docs.

I am in favor of option2.

**Comment by akshayaurora** [comment]
`it would only affect a couple of kivy props, it would be good to have it for children too.`

Widget.parent and Widget.children are part of the base class so you would have rebinds for every widget's parent and every child, to me this seems over kill.

This would be like using a Tzar bomb where a surgical strike is needed.

Documenting this properly and allowing the programmer to set rebind = True for the widget where he needs this is more like a surgical strike that is needed.

**Comment by dessant** [comment]
@akshayaurora, do you have performance tests to show that the benefit of enabling it is not worth it?

Closing the issue before  `option2` was done is also like using a bomb. :D

**Comment by akshayaurora** [comment]
There is not a pr this is a issue,  I am open for a pr that shows no significant performance issues with a significantly sized UI, like in showcase.

For this issue closing it was a mistake,  this should be documented then this issue closed.
