### ISSUE TITLE
Introduce plyer as a dependency for kivy

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3530]
Some features that we need are not implemented in the providers we use, there is a need for calling OS specific APIs in certain cases.

We have discussed this with @akshayaurora, and using plyer minght be a good way of going forward, instead of cluttering the kivy codebase with API calls for every platform.

Some of the most evident kivy features that need this is dpi and scale detection, on desktop, we hardcode `96.` for dpi.

What do you guys think about this, are you ok with implementing suitable things in plyer and calling plyer from kivy? Or do you have other alternatives in mind?
##

**Comment by rnixx** [comment]
imho plyer should be merged then to kivy entirely.

what's the benefit of having a separate package which is part of kivy core then anyway?

**Comment by dessant** [comment]
@rnixx plyer features can and are used independently from kivy.

**Comment by rnixx** [comment]
ok, i thought it's used within kivy only.

**Comment by Julian-O** [comment]
I am closing this. It was a discussion about whether something would be okay (apparently yes), rather than a request to take action.
