### ISSUE TITLE
Python Crash using the Interactive Launcher

### ISSUE THREAD

**Issue by hackebrot** [kivy/kivy#3531]
Hey there,

when I was trying to leverage `pytest` to test my `kivy` apps, I noticed that the `InteractiveLauncher` ends up crashing python if it is run several times. I have discovered that it is definitely not `pytest` and you can reproduce the issue with the following code.

```python
import kivy
kivy.require('1.9.0')

from kivy.interactive import InteractiveLauncher
from kivy.animation import Animation
from kivy.app import App


class FooBarApp(App):
    """Dummy App that simply inherits from App."""


def foo():
    """Uses the InteractiveLauncher to provide access to an app instance.
    """
    launcher = InteractiveLauncher(FooBarApp())

    def start_launcher():
        launcher.run()
        launcher.safeIn()

    def stop_launcher():
        launcher.safeOut()
        launcher.stop()

    start_launcher()
    stop_launcher()

foo()
foo()
```

Running it via ``python -v crash_kivy.py`` shows the following lines at the very end
```
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
[INFO   ] [Base        ] Start application main loop
CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.
Fatal Python error: (pygame parachute) Segmentation Fault
Abort trap: 6
```

I am currently running the following setup:
```
ProductName:	Mac OS X
ProductVersion:	10.10.4

Python 2.7.6
Kivy (1.9.1.dev0)
```

Please note that it is also crashing using the Mac OS X kivy distribution.

Any help is highly appreciated.
Raphael

**Comment by inclement** [comment]
@tito has mentioned before that the interactive launcher has major problems and could be implemented much more simply. Maybe this is the best solution.

i notice your error refers to pygame though - are you using this? If so, try with sdl2 which is the default from 1.9 onwards.

**Comment by hackebrot** [comment]
To be honest I did not switch to Pygame on purpose, so I am not entirely sure. Is there a way of changing this and if so how?

**Comment by hackebrot** [comment]
I am still at EuroPython and cannot access IRC :cry:

:bell: Can you please help me out? @inclement

**Comment by undercase** [comment]
Pygame, nor SDL 2, is not installed correctly on your system. Try reinstalling both libraries and then update us.

**Comment by dessant** [comment]
The interactive launcher has been deprecated in https://github.com/kivy/kivy/commit/3f83ed2a7b7d463d6b721b737b1adc0ec30ea7af.
