### ISSUE TITLE
Kivy makes massive app

### ISSUE THREAD

**Issue by ryansehrlich** [kivy/kivy#3533]
Hi, I'm Trying to create a Kivy App for OS X. My main.py and kv file are about 12kb, and the compiled app is about 3.5 gbs. is there any way to make this smaller, as this seems really big. 

Thank

**Comment by rnixx** [comment]
my recent app has approx. 30mb after packing for osx with pyinstaller as one-file executable. how did you package your app?

**Comment by ryansehrlich** [comment]
I packaged my app using the "Offical Method". I will try pyinstaller though, thank you very, very much

**Comment by ryansehrlich** [comment]
I tried to use pyinstaller, but the file-size is still huge (2.35 gbs) anything I can do to make this smaller?

**Comment by rnixx** [comment]
You can use the archive viewer to get an idea what bloats your app that much.

http://pythonhosted.org/PyInstaller/#using-pyi-archive-viewer

**Comment by ryansehrlich** [comment]
Thank you! 
I realized what I did wrong!
I was packaging my app Inside the  folder, so it was pretty much making a copy of it self over and over and over again.

I needed to put kivy-sdk-packager in a directory not containing main.py
