### ISSUE TITLE
How can I add shadows?

### ISSUE THREAD

**Issue by itsMichael** [kivy/kivy#3536]
How can I add shadows to buttons and TextInput?

**Comment by Alan-FGR** [comment]
Hello there.
I'm afraid there's no easy way to do that like in css3, to may my shadows I'm using an image like this:
![_shadow1](https://cloud.githubusercontent.com/assets/8399299/8963474/b33926f2-35f6-11e5-9dcf-9fbea59697fb.png)
and a rule like this:
    canvas.before:
        Color:
            rgba: 1,1,1,0.3
        BorderImage:
            border: 25,25,25,25
            source: 'theme/_shadow1lr.png'
            pos: self.x+myoffset, self.y+myoffset
            size: self.width+myspread, self.height+myspread
obviously you'll want to take the 'myspread' into account for the offset
