### ISSUE TITLE
Legacy in "User's guide >> Installation on Linux"

### ISSUE THREAD

**Issue by vanzef** [kivy/kivy#3538]
Hello.

Yesterday I was trying to install Kivy 1.9 on my Linux system (Arch Linux) with pip. So, it fails with Cython 0.22 (here is a error-message http://pastebin.com/7LkMpgc4), but works well with Cython 0.21.

Please, update your installation guide and change "Providing dependencies" section.

Thanks!

**Comment by rnixx** [comment]
linux install docs overhauling is work in progress here https://github.com/kivy/kivy/pull/3519/files

**Comment by matham** [comment]
I'm pretty sure this has been fixed if you use master.
