### ISSUE TITLE
kivy.logger.FileHandler discards parts of the log message

### ISSUE THREAD

**Issue by janssen** [kivy/kivy#3543]
FileHandler's _write_message never formats the record it receives; instead, it just writes the "msg" field out to the file.  The "msg" field is the format string.  It needs to be merged with the arguments before it is written.  Usually by calling the Handler's Formatter instance.
##

**Comment by Julian-O** [comment]
`FileHandler` now inherits from `logging.Handler`, and calls `self.format(record)` which does what you are asking.

Closing as fixed (at least a year ago, probably more).
