### ISSUE TITLE
Error with kv file parsing

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#3549]
If I create a gui with nested widgets in the kivy file like the following example:

    #:kivy 1.9.0 
    <Layout>:  
        orientation: "vertical"  
        BoxLayout:  
            Label:  
                text: "hello"  

and this in the python file:
```python
#Kivy version 1.9.0
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.uix.boxlayout import BoxLayout

class Layout(BoxLayout):
    pass

class guiApp(App):
    def build(self):
        return Layout()

if __name__ == '__main__':
    guiApp().run()
```

It raise the following error:

```
  File "C:Program FilesPython27x64libsite-packageskivyuixoxlayout.py", l
ine 102, in __init__
    super(BoxLayout, self).__init__(**kwargs)
  File "C:Program FilesPython27x64libsite-packageskivyuixlayout.py", line
 66, in __init__
    super(Layout, self).__init__(**kwargs)
  File "C:Program FilesPython27x64libsite-packageskivyuixwidget.py", line
 271, in __init__
    Builder.apply(self)
  File "C:Program FilesPython27x64libsite-packageskivylang.py", line 1872,
 in apply
    self._apply_rule(widget, rule, rule)
  File "C:Program FilesPython27x64libsite-packageskivylang.py", line 1986,
 in _apply_rule
    self._apply_rule(child, crule, rootrule)
  File "C:Program FilesPython27x64libsite-packageskivylang.py", line 1985,
 in _apply_rule
    self.apply(child)
  File "C:Program FilesPython27x64libsite-packageskivylang.py", line 1872,
 in apply
    self._apply_rule(widget, rule, rule)
  File "C:Program FilesPython27x64libsite-packageskivylang.py", line 1985,
 in _apply_rule
    self.apply(child)
  File "C:Program FilesPython27x64libsite-packageskivylang.py", line 1872,
 in apply
    self._apply_rule(widget, rule, rule)
  File "C:Program FilesPython27x64libsite-packageskivylang.py", line 1883,
 in _apply_rule
    assert(rule not in self.rulectx)
AssertionError
Press any key to continue . . .
```

I found that the error is generated by the function name Layout().
In fact, if i change the name of the function the problem does not appear.

I know it is not a very significant problem, but since I found it seems correct report that here.

**Comment by dessant** [comment]
@Tungsteno74 could you post your kv with indentation?

**Comment by Tungsteno74** [comment]
I'm trying but markdown code snippet don't work well here and idk.

**Comment by Tungsteno74** [comment]
Ok done. Sorry but is the first time that i post on GitHub.

**Comment by dessant** [comment]
You have to indent the content of `<Layout>`, your kv is invalid.

```
<Layout>:  
    orientation: "vertical"  
    BoxLayout:  
        Label:  
            text: "hello" 
```

**Comment by Tungsteno74** [comment]
It is a transcription error. Now is all right. 
Sorry again for that. :sweat_smile:

**Comment by bionoid** [comment]
`Layout` is [a core widget](https://github.com/kivy/kivy/blob/master/kivy/uix/layout.py#L57), use another name

**Comment by Tungsteno74** [comment]
I think you're right.
It might be useful to specify in the documentation?
I say this because it only happens if you use Layouts. However, not happen,  if you use basis widgets (buttons, labels, etc.).
