### ISSUE TITLE
PyInstaller. No such file

### ISSUE THREAD

**Issue by Hateman31** [kivy/kivy#3550]
Hello! 
Sorry, i am a russian young programmer and my english so bad.
But I have a problem with Kivy. 
Recently I made test.exe from test.py via pyinstaller.
Now, when i run test.exe i got the message 'no such file ...<path_of_app>/test.kv'
Can you help me?
What i should do?

Thanks for attetion!

**Comment by tshirtman** [comment]
This is not a bug, please ask for help on the kivy-users mailing list. Thanks.
