### ISSUE TITLE
Doc needs MORE Screenshots

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#3554]
For this project to gain traction, there need to be screenshots for every page that has an example application. Especially the ones that us the .kv files.

References #710  #3374
##

**Comment by picibucor** [comment]
check #3374 as well.

**Comment by Zen-CODE** [comment]
Perhaps it's that I'm not a visually driven person, but this does not seem so important to me.

There are lots of screenshots in the guides, and in other places I feel enough for a person to be pretty fluid in Kivy by the time they need them? How do others feel?

If it's felt important, I'm certainly willing to try a sweep through adding these, I think initially just for the kv examples as I agree these are more important and kivy specific.

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
