### ISSUE TITLE
Property force_dispatch doesn't work on android.

### ISSUE THREAD

**Issue by vasss** [kivy/kivy#3556]
Hi, I tried to create a Carousel widget with a swiped property, so it would dispatch events only when the carousel is swiped. On this example the property swiped is either "1" or "-1". Since I needed it to dispatch every time a swipe happens, I added the force_dispatch=True to the property.
This works totally fine on my desktop/linux machine, but when I build a pkg and run it on an android the force dispatch doesn't work. But setting the property to "0" and back to the value its supposed to be causes two dispatches as expected.

```python
class XCarousel(Carousel):

    swiped = NumericProperty(0, force_dispatch=True)

    def __init__(self, **kwargs):
        super(XCarousel, self).__init__(**kwargs)

    def on__offset(self, *args):
        old_index = self.index
        super(XCarousel, self).on__offset(*args)
        swiped = self.index-old_index
        if swiped != 0:
            self.swiped = swiped
```

**Comment by tshirtman** [comment]
Did you check that you were using kivy 1.9.0 or newer on android ? if it works on desktop, it should work on android.

**Comment by vasss** [comment]
Oh, you are right. It was kivy 1.8.0 in the apk. Thanks for making the world make sense again. It was an rtfm issue on my part. I wrongly assumed that Python for Android would use 1.9.0 as default. For anyone who might have any similar issue:
for the latest version use
./distribute.sh -m "openssl kivy==master"
and for any specific version 
./distribute.sh -m "openssl kivy==1.9.0" etc.
