### ISSUE TITLE
FreeBSD system, can't paste from system clipboard into CodeInput and TextInput

### ISSUE THREAD

**Issue by tony** [kivy/kivy#3561]
```sh
$ freebsd-version -ku; uname -apKU                                                                  
10.1-RELEASE-p16
10.1-RELEASE-p16
FreeBSD z600 10.1-RELEASE-p16 FreeBSD 10.1-RELEASE-p16 #0: Tue Jul 28 12:04:19 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64 amd64 1001000 1001000
```

Note I am **not** using the port [x11-toolkits/py-kivy](https://www.freshports.org/x11-toolkits/py-kivy/), I am working from source.

```
commit c271d87fe1b99c783b33398212e3306f96c41bd7
Merge: 8d66a19 b8437f9
Author: dessant <dessant@users.noreply.github.com>
Date:   Wed Aug 5 21:23:21 2015 +0300

    Merge pull request #3555 from matham/color
    
    Move colormap to utils.
```

Using RstDocument in with ``main.py`` in https://github.com/tony/kivysample/tree/latest-kivy.

When running with ``-d``, I see:

``
[INFO              ] [Clipboard   ] Provider: dummy(['clipboard_pygame'] ignored)
``

If I cut inside the text widget, I can paste back into it. However I can't paste from the system clipboard. So if I were to copy text from firefox, it won't paste into the widget.

**Comment by tony** [comment]
The same happens with TextInput also. I changed the title to include TextInput and also added clipboard to title to be more descriptive in case someone googles here.

**Comment by akshayaurora** [comment]
Which version of kivy are you using? which Desktop env do you use?
Since 1.9.x we now have sadly clipboard provider which should work every where, we also have backup clipboard providers using de/gnome, xsel... however it seems all you have is pygame and dummy.

This was the case in 1.8.x but not on 1.9.x Could you ensure you are using the latest release of kivy?

**Comment by akshayaurora** [comment]
it is possible that cause of failure of platform checks the correct provider for clipboard was not being selected,  could you retest with the latest master?

**Comment by akshayaurora** [comment]
@tony reopen of issue still exists.
