### ISSUE TITLE
Scatter not configureable for desktop

### ISSUE THREAD

**Issue by rainbowdesign** [kivy/kivy#3563]
Hello,
i would like to use scatter on desktop with a custom configuration:
Move in the scatter when holding right mouse and moving it,
Scale when holding both mouse keys and moving the mouse.

Now scatter seems to be focused on multitouch and does provide little support for more traditional input methods also there seems no alternative to scatter which means kivy has no widget to scale rotate and zoom on Desktop at all.

**Comment by tshirtman** [comment]
1/ what does "Move in the scatter when holding right mouse and moving it" means? does it mean moving the scatter itself, or somehow interacting with scatters content?

2/ i think i would rather use scrollweel to zoom in/out of the scatter at a certain position, that shouldn't be very hard to achieve by overriding on_touch_down and checking if it's a mouse event, and if so if the button is scroll up/down, then adapting the pinch-to-zoom algo to use touch pos as zoom center, and a set value for scaling.

**Comment by tito** [comment]
I think this should be a new widget, not a change to the current one.

**Comment by tshirtman** [comment]
Hm, then maybe it would make sense to split Scatter into a Behavior and an Instruction (that would take the scale/pan/rotate properties), and logic, to be able to reuse both the scale/rotate/pan matrix manipulation, and the pinch/slide UX interface (with different effects)?

**Comment by rainbowdesign** [comment]
Well i think it would be best if i can use the same widget on desktop and on mobile so i like tshirtmans approach.

1/ what does "Move in the scatter when holding right mouse and moving it" means? does it mean moving the scatter itself, or somehow interacting with scatters content?

The same interaction that happens now when pointing on the scatter content pressing and holding left mouse button and move it. (instead moving the content with left mouse button move the scatter content with right mouse button)

2/ i think i would rather use scrollweel to zoom in/out of the scatter at a certain position, that shouldn't be very hard to achieve by overriding on_touch_down and checking if it's a mouse event, and if so if the button is scroll up/down, then adapting the pinch-to-zoom algo to use touch pos as zoom center, and a set value for scaling.

I suggest to adapt it so the programmer can use both. This ISSUE is NOT about adding default settings only but also about being able to DEFINE the behavior as USER. Maybe i want to give my Program just settings to switch between wheel and right&left mouse button.
Also for standart settings mouse wheel feels more natural but not all mouses have a wheel.

I hope i was able to express what i mean.

**Comment by rainbowdesign** [comment]
Oh also i want to add following: when using scatter with buttons it seems the buttons catch the click even when dragging.
That is also why i want to use rightmouse .for "translating"

**Comment by rainbowdesign** [comment]
To https://github.com/kivy/kivy/issues/3565
So it is a classic beginner mistake? Will come back again and again? How about making it more intuitive then maybe just fit the scatter so this issue will never arise at all.
