### ISSUE TITLE
Scatter ignores input

### ISSUE THREAD

**Issue by rainbowdesign** [kivy/kivy#3565]
I try Scatter with a huge image in some containers.
I move it around with left mouse on Pc and scale or rotate it.
About every third time when i Press the mouse it does not react like it did not get the input that the mouse was pressed.

**Comment by tshirtman** [comment]
This is not a bug, you didn't scale your image to fit in the scatter, or the scatter to contain the whole image, that's a classic beginner mistake.

**Comment by rainbowdesign** [comment]
I tested it and well it seems that indeed it is only on some places of the scatter like this.
However i did not find more in the documentation about this issue.
Maybe you should add a frequent mistakes to the Documentation.
