### ISSUE TITLE
Active radio button deactivation in a group

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#3568]
If i click on the active radio button in a group, it is deactivated (thus no other radio button in the group is active). 
Is it normal?
If is true, How do I always have one active? (Thus, ignore the click on the active radiobutton)
thanks in advance.

**Comment by matham** [comment]
I believe you're looking for the `allow_no_selection` property which is documented in the ToggleButton class (http://kivy.org/docs/api-kivy.uix.behaviors.html#kivy.uix.behaviors.ToggleButtonBehavior.allow_no_selection).
