### ISSUE TITLE
TreeView: `select_node(None)` should unselect the selected node

### ISSUE THREAD

**Issue by lmNt** [kivy/kivy#3572]
As the title suggests, I think calling `select_node(None)` should reset the selection in a TreeView and not crash.

Currently, at least if I am correct, it is not possible to unselect a selected node in a TreeView in a valid/clean way, i.e. without setting the nodes' `is_selected` property to false.

So instead of doing this:

    tree_view.get_selected_node().is_selected = False

I think

    tree_view.select_node(None)

should do the job.
Correct me, if I am missing something here.

**Comment by KeyWeeUsr** [comment]
@lmNt Implemented clean method for deselecting, closing. :yup:
