### ISSUE TITLE
Buildozer wont compile libraries with cython 0.23 or 0.22

### ISSUE THREAD

**Issue by Ramalus** [kivy/kivy#3574]
I had this issue today when trying to deploy a new project to android and this is the log:

�[0m�[1;34m# Check configuration tokens�[0m
�[0m�[1;34m# Ensure build layout�[0m
�[0m�[1;34m# Check configuration tokens�[0m
�[0m�[1;34m# Preparing build�[0m
�[0m�[1;34m# Check requirements for android�[0m
�[0m�[1;30m# Run 'dpkg --version'�[0m
�[0m�[1;30m# Cwd None�[0m
�[0m�[1;30m# Search for Git (git)�[0m
�[0m�[1;30m# -> found at /usr/bin/git�[0m
�[0m�[1;30m# Search for Cython (cython)�[0m
�[0m�[1;30m# -> found at /usr/bin/cython�[0m
�[0m�[1;30m# Search for Java compiler (javac)�[0m
�[0m�[1;30m# -> found at /usr/lib/jvm/java-7-jdk/bin/javac�[0m
�[0m�[1;30m# Search for Java keytool (keytool)�[0m
�[0m�[1;30m# -> found at /usr/lib/jvm/java-7-jdk/jre/bin/keytool�[0m
�[0m�[1;34m# Install platform�[0m
�[0m�[1;34m# Apache ANT found at /home/ramalus/.buildozer/android/platform/apache-ant-1.9.4�[0m
�[0m�[1;34m# Android SDK found at /home/ramalus/.buildozer/android/platform/android-sdk-21�[0m
�[0m�[1;34m# Android NDK found at /home/ramalus/.buildozer/android/platform/android-ndk-r9c�[0m
�[0m�[1;34m# Check application requirements�[0m
�[0m�[1;30m# Run './distribute.sh -l'�[0m
�[0m�[1;30m# Cwd /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android�[0m
Available modules: android apsw audiostream bidi boost cherrypy c_igraph cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer freetype gevent greenlet harfbuzz hostpython igraph jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws wokkel zeroconf zope
�[0m�[1;30m# Application requirements already installed, pass�[0m
�[0m�[1;34m# Check garden requirements�[0m
�[0m�[1;34m# Compile platform�[0m
�[0m�[1;30m# Run './distribute.sh -l'�[0m
�[0m�[1;30m# Cwd /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android�[0m
Available modules: android apsw audiostream bidi boost cherrypy c_igraph cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer freetype gevent greenlet harfbuzz hostpython igraph jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws wokkel zeroconf zope
�[0m�[1;30m# Clean and build python-for-android�[0m
�[0m�[1;30m# Remove directory and subdirectory /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/dist/audioexample�[0m
�[0m�[1;30m# Run './distribute.sh -m "kivy" -d "audioexample"'�[0m
�[0m�[1;30m# Cwd /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android�[0m
�[34;01mCheck build dependencies for �[39;49;00m
�[30;01mAvoid check build dependencies, unknow platform �[39;49;00m
�[34;01mCheck environment�[39;49;00m
�[30;01mSDK located at /home/ramalus/.buildozer/android/platform/android-sdk-21�[39;49;00m
�[30;01mNDK located at /home/ramalus/.buildozer/android/platform/android-ndk-r9c�[39;49;00m
�[30;01mNDK version is r9c�[39;49;00m
�[30;01mAPI level set to 14�[39;49;00m
�[34;01mCheck NDK location�[39;49;00m
�[34;01mCheck mandatory tools�[39;49;00m
�[34;01mDistribution will be located at /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/dist/audioexample�[39;49;00m
�[34;01mEntering in ARM environment�[39;49;00m
�[30;01mCompiler found at /home/ramalus/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc�[39;49;00m
�[30;01mPATH is /home/ramalus/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/:/home/ramalus/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/:/home/ramalus/.buildozer/android/platform/android-ndk-r9c:/home/ramalus/.buildozer/android/platform/android-sdk-21/tools:/home/ramalus/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl�[39;49;00m
�[34;01mLeaving ARM environment�[39;49;00m
�[30;01mRead kivy recipe�[39;49;00m
�[30;01mModule kivy depend on pygame pyjnius android�[39;49;00m
�[30;01mRead pygame recipe�[39;49;00m
�[30;01mModule pygame depend on python sdl�[39;49;00m
�[30;01mRead pyjnius recipe�[39;49;00m
�[30;01mModule pyjnius depend on python sdl�[39;49;00m
�[30;01mRead android recipe�[39;49;00m
�[30;01mModule android depend on pygame�[39;49;00m
�[30;01mRead python recipe�[39;49;00m
�[30;01mModule python depend on hostpython�[39;49;00m
�[30;01mRead sdl recipe�[39;49;00m
�[30;01mModule sdl depend on python�[39;49;00m
�[30;01mIgnored python, already processed�[39;49;00m
�[30;01mIgnored sdl, already processed�[39;49;00m
�[30;01mIgnored pygame, already processed�[39;49;00m
�[30;01mRead hostpython recipe�[39;49;00m
�[30;01mIgnored python, already processed�[39;49;00m
�[34;01mModules changed to hostpython python sdl pygame pyjnius android kivy�[39;49;00m
�[34;01mPure-Python modules changed to �[39;49;00m
�[34;01mRun get packages�[39;49;00m
�[30;01mDownload package for hostpython�[39;49;00m
�[30;01mModule hostpython already downloaded�[39;49;00m
�[30;01mDownload package for python�[39;49;00m
�[30;01mModule python already downloaded�[39;49;00m
�[30;01mDownload package for sdl�[39;49;00m
�[30;01mNo package for sdl�[39;49;00m
�[30;01mDownload package for pygame�[39;49;00m
�[30;01mModule pygame already downloaded�[39;49;00m
�[30;01mDownload package for pyjnius�[39;49;00m
�[30;01mModule pyjnius already downloaded�[39;49;00m
�[30;01mDownload package for android�[39;49;00m
�[30;01mNo package for android�[39;49;00m
�[30;01mDownload package for kivy�[39;49;00m
�[30;01mModule kivy already downloaded�[39;49;00m
�[34;01mRun prebuild�[39;49;00m
�[30;01mCall prebuild_hostpython�[39;49;00m
�[30;01mCall prebuild_python�[39;49;00m
�[30;01mCall prebuild_sdl�[39;49;00m
�[30;01mCall prebuild_pygame�[39;49;00m
�[30;01mCall prebuild_pyjnius�[39;49;00m
�[30;01mCall prebuild_android�[39;49;00m
�[30;01mCall prebuild_kivy�[39;49;00m
�[34;01mRun build�[39;49;00m
�[30;01mSkipped build_hostpython�[39;49;00m
�[30;01mSkipped build_python�[39;49;00m
�[30;01mSkipped build_sdl�[39;49;00m
�[30;01mSkipped build_pygame�[39;49;00m
�[30;01mSkipped build_pyjnius�[39;49;00m
�[30;01mSkipped build_android�[39;49;00m
�[30;01mCall build_kivy�[39;49;00m
�[34;01mEntering in ARM environment�[39;49;00m
�[30;01mCompiler found at /home/ramalus/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc�[39;49;00m

Cython check avoided.
Using this graphics system: OpenGL ES 2
running build_ext
Build configuration is:

```
use_rpi = 0
use_opengl_es2 = 1
use_opengl_debug = 0
use_glew = 0
use_sdl2 = 0
use_ios = 0
use_mesagl = 0
use_x11 = 0
use_gstreamer = 0
use_avfoundation = 0
use_osx_frameworks = 0
debug = False Detected compiler is unix building 'kivy.graphics.transformation' extension ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/transformation.c -o build/temp.linux-x86_64-2.7/kivy/graphics/transformation.o /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/src/tools/liblink -lm -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/libs -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm build/temp.linux-x86_64-2.7/kivy/graphics/transformation.o -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/lib -lGLESv2 -lpython2.7 -o build/lib.linux-x86_64-2.7/kivy/graphics/transformation.so -L /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/lib -lm building 'kivy.graphics.vbo' extension ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/vbo.c -o build/temp.linux-x86_64-2.7/kivy/graphics/vbo.o
```

Cython check avoided.
Using this graphics system: OpenGL ES 2
running build_ext
Build configuration is:

```
use_rpi = 0
use_opengl_es2 = 1
use_opengl_debug = 0
use_glew = 0
use_sdl2 = 0
use_ios = 0
use_mesagl = 0
use_x11 = 0
use_gstreamer = 0
use_avfoundation = 0
use_osx_frameworks = 0
debug = False Detected compiler is unix building 'kivy.graphics.opengl' extension ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/opengl.c -o build/temp.linux-x86_64-2.7/kivy/graphics/opengl.o /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/src/tools/liblink -lm -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/libs -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm build/temp.linux-x86_64-2.7/kivy/graphics/opengl.o -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/lib -lGLESv2 -lpython2.7 -o build/lib.linux-x86_64-2.7/kivy/graphics/opengl.so -L /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/lib -lm building 'kivy.graphics.stencil_instructions' extension ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/stencil_instructions.c -o build/temp.linux-x86_64-2.7/kivy/graphics/stencil_instructions.o /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/src/tools/liblink -lm -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/libs -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm build/temp.linux-x86_64-2.7/kivy/graphics/stencil_instructions.o -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/lib -lGLESv2 -lpython2.7 -o build/lib.linux-x86_64-2.7/kivy/graphics/stencil_instructions.so -L /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/lib -lm building 'kivy.graphics.transformation' extension ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/transformation.c -o build/temp.linux-x86_64-2.7/kivy/graphics/transformation.o /home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/src/tools/liblink -lm -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/libs -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm build/temp.linux-x86_64-2.7/kivy/graphics/transformation.o -L/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/lib -lGLESv2 -lpython2.7 -o build/lib.linux-x86_64-2.7/kivy/graphics/transformation.so -L /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/lib -lm building 'kivy.graphics.vbo' extension ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/ramalus/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/ramalus/Development/KivyProjects/LangExchange/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/vbo.c -o build/temp.linux-x86_64-2.7/kivy/graphics/vbo.o �[0m�[1;31m# Command failed: ./distribute.sh -m "kivy" -d "audioexample"�[0m �[0m�[1;31m# �[0m �[0m�[1;31m# Buildozer failed to execute the last command�[0m �[0m�[1;31m# The error might be hidden in the log above this error�[0m �[0m�[1;31m# Please read the full log, and search for it before�[0m �[0m�[1;31m# raising an issue with buildozer itself.�[0m �[0m�[1;31m# In case of a bug report, please add a full log with log_level = 2�[0m
```

With dessant's help I managed to solve the issue by installing cython version 0.21

But still it should work with 0.23 as described in the docs.

PS: I did open this issue also on buildozer repo, but since this changed in a short period of time (meaning that last week it was compiling fine) I thought it might have something to do with some kivy update so posting it here to. I hope that's ok.

**Comment by dessant** [comment]
Please reopen for the buildozer repo if the issue is still there.
