### ISSUE TITLE
CoreLabel does not return the same width in PY2 as in PY3

### ISSUE THREAD

**Issue by andnovar** [kivy/kivy#3577]
![screenshot from 2015-08-13 18 53 26](https://cloud.githubusercontent.com/assets/400600/9263624/afcbe4da-41ec-11e5-9dfe-9a8b92ade751.png)

The figure from the left is in python2 and the one from the right is in python3 the yellow rectangles are the dimensions of the corelabel elements.

**Comment by dessant** [comment]
@andnovar, could you share a test app for this which does not involve matplotlib?

**Comment by andnovar** [comment]
used six.text_type("{}".format(s)) to format text gives the same width and height in both py2 and py3
