### ISSUE TITLE
Suggestion: make import of uix components directly from uix

### ISSUE THREAD

**Issue by Alexis-benoist** [kivy/kivy#3583]
Hello,

I have a suggestion for kivy. I'm willing to do the PR, if you guys like it.

It feels to me that:

``` python
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput
```
is a bit verbose for python, why don't we just do?
``` python
from kivy.uiximport GridLayout, Label, TextInput
```

Tell me what you think of it!

Cheers,
Alexis.

**Comment by dessant** [comment]
While it sounds nice, this would also mean that we would have to import all widgets in `kivy/uix/__init__.py` and that would cause all widgets to be imported if one of them is used.

**Comment by matham** [comment]
I don't think this will work very well. What exactly will we import from each of these? Classes? Some function? All function? What about if there are name clashes? I think this will just make it more complicated to explain to new people as you'd have to know beforehand what object came from which file..
