### ISSUE TITLE
MakeSymlinks refers to Kivy.App instead of Kivy.app

### ISSUE THREAD

**Issue by madelynfreed** [kivy/kivy#3590]
In the OSX installation disk image, the MakeSymlinks script refers to Kivy.App rather than Kivy.app. For case insensitive file systems, that might work fine. But installation for case sensitive file systems doesn't work until you change the 'a'.

**Comment by dessant** [comment]
@madelynfreed, please open this issue for https://github.com/kivy/kivy-sdk-packager.
