### ISSUE TITLE
Windows portable package 1.9.0, bad path in kivyenv-2.7.sh

### ISSUE THREAD

**Issue by loganmill** [kivy/kivy#3591]
I believe there is an error in the bash scripts embedded in the "windows portable package" installers:
Kivy-1.9.0-py2.7-win32-x64.exe, and
Kivy-1.9.0-py3.4-win32-x64.exe 

The file kivyenv-2.7.sh that is installed from these exe's contains this line:
<code>export PYTHONPATH=$KIVY_PORTABLE_ROOT_WIN\\kivy\;$PYTHONPATH</code>
...that, I'm pretty sure,  should be:
<code>export PYTHONPATH=$KIVY_PORTABLE_ROOT_WIN\\$KIVY_DIR\;$PYTHONPATH</code>
...in order to correctly identify the path to the kivy package.  $KIVY_DIR correctly contains the string 'kivy27'.

Perhaps the issue is a little deeper than this. Seems that the version of the file committed to GitHub:

kivy/kivy/tools/packaging/win32/kivyenv2.7.sh, here:  https://github.com/kivy/kivy/tree/1.9.0/kivy/tools/packaging/win32

...is actual quite different from the version in the windows package. If I understand correctly, this should be the actual source of the file. Perhaps the root of issue is that whatever code is used to create the windows .exe installer packages is actually pulling in obsolete versions of the script?

**Comment by matham** [comment]
The files come from https://github.com/kivy/kivy-sdk-packager/tree/master/win/data. So it just needs to be fixed there.

**Comment by dessant** [comment]
@loganmill, lease open an issue or pr against the sdk repo.

**Comment by loganmill** [comment]
Wasn't aware of sdk repo...I see there that matham has already opened this very issue:
https://github.com/kivy/kivy-sdk-packager/issues/5.
