### ISSUE TITLE
Expose Window Focus Events

### ISSUE THREAD

**Issue by davidrusu** [kivy/kivy#3600]
This is a feature request for window focus events:

It seems like all of the leg work is done already:

https://github.com/kivy/kivy/blob/332bc89e1888b322cec4c2255a08f9f0398f2a40/kivy/core/window/_window_sdl2.pyx#L316

but it's not being exposed by the api.

I looked at the main loop code here:

https://github.com/kivy/kivy/blob/332bc89e1888b322cec4c2255a08f9f0398f2a40/kivy/core/window/window_sdl2.py#L557

And it seems like it should be printing the windowfocusgained and windowfocuslost events but when I ran my app with -v I didn't see any logs with those events.

This code does print the windowfocusgained and windowfocuslost events:
``` python
def do_it(dt):
    action = Window._win.poll()
    if action:
        print('doing it', action)

    Clock.schedule_interval(do_it, 0.016)
```

**Comment by dessant** [comment]
Maybe a Window.focused read-only prop would be ok.

**Comment by sdementen** [comment]
To see the "unhandled event" messages, you can set the log_level to "trace" through::
```
Config.set('kivy', 'log_level', 'trace')
```.
A Window.focused (or Window.focus) would be indeed useful.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/3877.
