### ISSUE TITLE
ButtonBehavior on_press is sometimes triggered by wheel scrolling

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3609]
Scroll up and down fast to see a dramatic ZeroDivisionError, it seems to happen randomly, so it may take some time to see it.

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.uix.scrollview import ScrollView


kv = """
<Bt@Button>:
    on_press: 1/0
    size_hint_y: None
    height: '40dp'

<Test>:
    grid: grid
    GridLayout:
        id: grid
        cols: 1
        size_hint_y: None
        height: self.minimum_height
"""

Builder.load_string(kv)


class Test(ScrollView):
    def __init__(self, *args, **kwargs):
        super(Test, self).__init__(*args, **kwargs)
        self.fill()

    def fill(self):
        for i in range(100):
            self.grid.add_widget(Factory.Bt(text=str(i)))


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```

**Comment by dessant** [comment]
`on_press: print(self.last_touch.button)` shows `left`.

**Comment by ngoonee** [comment]
Just happened to see this. Unable to reproduce on my machine (and yes, I did try a lot). Some mice produce phantom clicks, suggest verifying this using a separate tool first (on linux its trivial, on other OS, I'm not sure).

**Comment by dessant** [comment]
@ngoonee, it was reproduced by at least 4 people on linux. @qua-non could not trigger the bug on os x, but it was there in a linux vm, with the same mouse.

**Comment by akshayaurora** [comment]
Not reproducible with kivy compiled using 
sld2 2.0.4
