### ISSUE TITLE
on windows, "no matching GL pixel format available" with 1.9.1

### ISSUE THREAD

**Issue by sdementen** [kivy/kivy#3613]
I got the SDL2 RuntimeError: no matching GL pixel format available when the screen color depth is set to 16bit. Switching to 32bit solves the issue.

**Comment by zeeMonkeez** [comment]
This also happens when connecting to a Windows machine using Remote Desktop (even with 32bit color depth)

**Comment by matham** [comment]
There doesn't seem like there's anything we can do about this as this is a driver/gl/sdl issue. As mentioned here https://groups.google.com/forum/#!topic/kivy-users/6pGevzB4ZdU all you can do is update drivers or try different drivers. Similarly for remote desktop, I have successfully ran kivy with remote desktop on a server machine, so you may just have to mess with the drivers or options.
