### ISSUE TITLE
minimum_size and scrollview kivy

### ISSUE THREAD

**Issue by Astyan-42** [kivy/kivy#3614]
Hello,

I have read a little and it don't seems to be a bug. So it's a feature request.
From this code https://github.com/Astyan-42/kivy_minimum_size_behaviour
The desired behaviour would be to allow the use of a ScrollView on a Layout with relative size when the Layout reach a minimal size.

**Comment by inclement** [comment]
Can you explain exactly what the change would be between the current behaviour and what you want?

**Comment by Astyan-42** [comment]
with the current behaviour the minimum_size attribute seem to be useless (it's don't affect the way the app is Display).
I would like to define a minimum_size for a Layout by keeping the responsive design above this minimum size and below this size keep the minimal size for the Layout and adding the scrolling.

I don't know if I am very clear so I made an image : https://github.com/Astyan-42/kivy_minimum_size_behaviour/blob/master/behaviour.png

**Comment by inclement** [comment]
The minimum_size is not currently something intended for you to set, it
is set automatically to the sum of child sizes. Can you not achieve your
desired behaviour by manually setting the child sizes as appropriate?

**Comment by Astyan-42** [comment]
I have not a lot of experience of kivy. But, from what I have read, to use ScrollView the child layout must have a define height and width so it's not responsive anymore for big screen.

**Comment by dessant** [comment]
It seems you are having trouble with using layouts instead of needing a new feature. Your expected outcomes from [this image](https://github.com/Astyan-42/kivy_minimum_size_behaviour/blob/master/behaviour.png) can all be achieved with the current api.

If you need further help, please post on the support channels https://github.com/kivy/kivy#support.
