### ISSUE TITLE
Resizing window makes it full height

### ISSUE THREAD

**Issue by stuaxo** [kivy/kivy#3621]
Resizing seems pretty broken, at least on Linux and GNOME shell under Ubuntu 15.04, 64 bit where I tested.

Test Code
```python

#!/bin/python
# -*- coding: utf-8 -*-

from kivy.app import App

class SomeApp(App):
    pass

if __name__ == '__main__':
    SomeApp().run()

```

Dragging the right border
- Window expands to full height and is really flickery, aspect ratio is wrong.

video

https://www.youtube.com/watch?v=-otKgL4k3kk&feature=youtu.be

log

https://gist.github.com/stuaxo/b14b7c979fd900fd1353

Dragging the other corners seems to have a similar effect.

**Comment by dessant** [comment]
I see you're using the dev version, was it updated to master? Could you also test with sdl2 instead of pygame?

I had the same issue but with the sdl2 window provider and it was fixed by kived iirc.

**Comment by stuaxo** [comment]
I'm using the version off github, the branch is 'master', just updated this and still have the bug... how do I use the SDL2 window provider (assuming I already have all the SDL2 stuff installed) ?

**Comment by dessant** [comment]
If you do have sdl2 deps installed and despite that, `make force` compiled with pygame (see if `use_sdl2` is 0 or 1 at the beginning of the build log), please open a new issue for that. Kivy should compile with sdl2 by default, when the dependencies are present.

Alternatively you can force sdl2 with: `USE_SDL2=1 make force`.

For the list of sdl2 deps, see http://kivy.org/docs/installation/installation-linux.html.

**Comment by stuaxo** [comment]
Turns out I was missing some of the libsdl2-*-dev packages.

SDL2 backend is fine, so I guess it's just the Pygame backend.

**Comment by stuaxo** [comment]
Is the pygame backend going to be deprecated on all platforms ?

**Comment by dessant** [comment]
Yes, sdl2 is the new default everywhere except android, but even there p4a has a revamp branch which already compiles apps with sdl2. Pygame will eventually be removed in the future as it is really just a buggy wrapper for an old sdl version.
