### ISSUE TITLE
Python 3.4 packager KeyError: 'rthooks'

### ISSUE THREAD

**Issue by MichaelCurrie** [kivy/kivy#3622]
As described here:
http://stackoverflow.com/questions/31083061/kivy-1-9-0-windows-package-keyerror-rthooks/32366409#32366409

I've partially troubleshooted this:

---------------

The [kivy docs](http://kivy.org/docs/guide/packaging-windows.html) you reference mention adding the following three lines to the top of the `.spec` file:

    from kivy.tools.packaging.pyinstaller_hooks import install_hooks
    import os
    install_hooks(globals())

The error is happening in `install_hooks(globals())`, which is defined at `\Lib\site-packages\kivy\tools\packaging\pyinstaller_hooks\__init__.py`:

    from os.path import dirname, join
    from functools import partial
    
    curdir = dirname(__file__)

    def install_hooks(sym, hookspath=None):
    
        _hookspath = [curdir]
        if hookspath is not None:
            _hookspath += hookspath
    
        sym['rthooks']['kivy'] = [join(curdir, 'rt-hook-kivy.py')]
        sym['Analysis'] = partial(sym['Analysis'], hookspath=_hookspath)

But the second last line is causing the message: `WARNING: stderr: KeyError: 'rthooks'`.

So it looks like it's expecting a variable `rthooks` to be in the global namespace, but it's not.

I'm not sure what to do next.

**Comment by ODiogoSilva** [comment]
I'm experiencing the same issue. I understand that support for python3.x packaging is experimental, but it would be great to have a fix on this.

**Comment by raonyguimaraes** [comment]
Same here, no kivy with python34 to me... I will try with python 2.7

**Comment by matham** [comment]
There have been some changes to pyinstaller which broke some of our misuse of their api, specifically rthooks. Luckily, I found a fix. However, I ran into another py3 issue which needs to be fixed or resolved first: https://github.com/pyinstaller/pyinstaller/issues/1513.

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/3652 fixes this hopefully. It also updates the instructions on how to set up the spec file to reflect these changes.
