### ISSUE TITLE
Slow video play on RPi2

### ISSUE THREAD

**Issue by ivlevdenis** [kivy/kivy#3629]
Very slowly play video on Raspberry Pi2.

**Comment by hanattaw** [comment]
I complied gst-omx and compiled Kivy-1.9. But compare with omxplayer, playing video from Kivy is slower.

**Comment by tito** [comment]
And it will, always, as we are opengl and the video pass through an opengl texture, it's not a direct display as usual video player.

Don't expect to use videoplayer for a full hd player on Rpi, but other methods can display video directly in top of a kivy window, to let you display your app with kivy (fast), and use accelerated method to display full screen video (fast).

**Comment by riataman** [comment]
There's a way to implement a fast path from omx to opengl texture, check the hello_videocube example included in the rapsberry pi.

Unfortunately that only deals with raw h264 video, to play audio and extract video from a container format (mp4, mkv) it would basically need to rewrite all of omxplayer.
