### ISSUE TITLE
Installation Doc Ubuntu packages

### ISSUE THREAD

**Issue by dec0dedab0de** [kivy/kivy#3630]
In /kivy/blob/master/doc/sources/installation/installation.rst  The Ubuntu section says to install libgl1-mesa-dev-lts-quantal, and  libgles2-mesa-dev-lts-quantal.   Both of which are not available in 15.04. I think it should have  libgl1-mesa-dev, and  libgles2-mesa-dev instead.

**Comment by mondayrain** [comment]
Just tested on my Vivid, can confirm.

**Comment by mondayrain** [comment]
@dec0dedab0de @dessant 
this can be closed!

**Comment by dessant** [comment]
@mondayrain thanks :+1:
