### ISSUE TITLE
KIVY_BCM_DISPMANX_ID - is this supposed to enable direct output on Adafruit PiTFT?

### ISSUE THREAD

**Issue by mludvig** [kivy/kivy#3633]
Hi I have compiled the current git version of Kivy in a hope to get direct output to Adafruit PiTFT 3.5" panel. PiTFT appears as /dev/fb1 and works well with `fbcp` and x11. But direct output from Kivy doesn't work with any of the KIVY_BCM_DISPMANX_ID = 1 .. 7 values. Is this supposed to work at all?

**Comment by tito** [comment]
Hi,

This contribution has been initiated from Gordon Hollingworth from Raspberry Pi team. But i didn't tested it myself, so unsure the impact of it for your question.

Mathieu

**Comment by tito** [comment]
And here is the answer from him:

> It’ll never work with the PiTFT panel
unless someone screen grabs frames using dispmanx and writes them to the
/dev/fb1

> That’s the advantage of using the Raspberry Pi Official touch screen…
