### ISSUE TITLE
 kernel[0]: CODE SIGNING: cs_invalid_page(0x10c66d000): p=97292[python] final

### ISSUE THREAD

**Issue by discohead** [kivy/kivy#3635]
My app was packaged for OS X on OS X 10.10.5 with Kivy 1.9 using the official packaging method, detailed here: http://kivy.org/docs/guide/packaging-macosx.html#official-packaging-method

I am developing in PyCharm CE v4.5.4 and followed the set up instructions here: https://github.com/kivy/kivy/wiki/Setting-Up-Kivy-with-various-popular-IDE's#setting-up-kivy-190-with-pycharm-45-eap-on-os-x-10103

When double clicking the app nothing happens, but I get this output in the Console:

9/13/15 10:09:21.890 PM Kivy[8448]: App did finish launching
9/13/15 10:09:21.000 PM kernel[0]: CODE SIGNING: cs_invalid_page(0x1069d8000): p=8450[python] final status 0x0, allowing (remove VALID) page

Googling "code signing cs_invalid_page python" has some interesting results, unfortunately I wasn't able to make any of it work for me.

https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=code+signing+cs_invalid_page+python

I thought that maybe my python script was the issue, but I tried packaging the Ping Pong tutorial and got the same results.

I also tried running the .app on another machine, same results.

I believe this may be somehow related to my PyCharm environment, as I've just now noticed that whenever I save my Kivy project in PyCharm the same code signing error from above appears in my Console. I will try to take PyCharm out of the equation and see what happens.

**Comment by akshayaurora** [comment]
Please reopen if issue still persists after taking PyCharm out of the equation.
