### ISSUE TITLE
audio_pygst ignored on a system with gstreamer 0.10 and gi

### ISSUE THREAD

**Issue by bionoid** [kivy/kivy#3638]
If gstreamer 0.10 is used and gi module is available, audio_pygst is ignored because of this check https://github.com/kivy/kivy/blob/master/kivy/core/audio/audio_pygst.py#L8-L13

`import gi` succeeds, but gstreamer 0.10 is not supported by audio_gi.

In theory, could check `gi.repository.Gst.version()` in `else`, but it leads to another problem; pygst segfaults if gi has been imported first. 

Commenting out these lines makes audio_pygst provider work. video_pygst doesn't have such a check and works out of the box.

**Comment by dessant** [comment]
The pygst provider has been removed.
