### ISSUE TITLE
Touchscreen not working in Kivy on RaspberryPi official touchscreen

### ISSUE THREAD

**Issue by dazzag24** [kivy/kivy#3640]
Update kernel and rebooted as per details here:
https://www.raspberrypi.org/blog/#the-eagerly-awaited-raspberry-pi-display

Then followed instructions here:
http://kivy.org/docs/installation/installation-rpi.html

[
As an aside these instructions result in the demos not running.  You need to install some additional Python modules:
sudo pip install pygments docutils
]

The demos now run, BUT none of them respond to the touchscreen.    The touchscreen DOES work in X windows, so it isn't a hardware issue I hope.

Output from running the pictures demo:

[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
[INFO              ] [Factory     ] 177 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Window      ] Provider: egl_rpi
[INFO              ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO              ] [GL          ] OpenGL vendor <Broadcom>
[INFO              ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO              ] [GL          ] OpenGL parsed version: 2, 0
[INFO              ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO              ] [GL          ] Texture max size <2048>
[INFO              ] [GL          ] Texture max units <8>
[INFO              ] [Shader      ] fragment shader: <Compiled>
[INFO              ] [Shader      ] vertex shader: <Compiled>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Text        ] Provider: pygame
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO              ] [HIDInput    ] Read event from </dev/input/event0>
[INFO              ] [Base        ] Start application main loop
[INFO              ] [HIDMotionEvent] using <FT5406 memory based driver>
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range ABS X position is 0 - 800
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO              ] [HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480

Any ideas of what is wrong?

**Comment by brousch** [comment]
I'm not sure if the touchscreen requires a typical RPi OS install, or if it needs [KivyPie](http://kivypie.mitako.eu/). In the one demo video I saw from RPi, he started the Kivy app from the command line, which makes me think that he was using KivyPie.

**Comment by dazzag24** [comment]
The instructions [http://kivy.org/docs/installation/installation-rpi.html] state you can either uses the KivyPie distro OR install requirements and build from source on top of a normal Rasp distro.

In my case I also start the demo pictures app from the CLI using "python main.py"

**Comment by dazzag24** [comment]
Update.  I've just found that an alternative set of instructions includes some configuration that *might* help get the touchscreen working.  See https://github.com/mrichardson23/rpi-kivy-screen
where they add

mouse = mouse
mtdev_%(name)s = probesysfs,provider=mtdev
hid_%(name)s = probesysfs,provider=hidinput

to the ~/.kivy/config.ini file.   I will try this tonight.   

So hopefully this tkt can be resolved by simply updating the instructions here

http://kivy.org/docs/installation/installation-rpi.html

to include the missing python modules and the config.ini changes.   There are likely going to be a LOT of people trying Kivy on their shiny new Raspi touchscreens over the coming weeks and at the moment the first impressions are not good.

Thanks

**Comment by jehutting** [comment]
With
```
    $ git diff
    diff --git a/kivy/lib/vidcore_lite/egl.pyx b/kivy/lib/vidcore_lite/egl.pyx
    index ee8491f..41218c1 100644
    --- a/kivy/lib/vidcore_lite/egl.pyx
    +++ b/kivy/lib/vidcore_lite/egl.pyx
    @@ -603,7 +603,7 @@ def bcm_display_open(bcm.uint32_t device):
         cdef:
             bcm.DISPMANX_DISPLAY_HANDLE_T disp
             bcm.DisplayHandle D
    -    disp = bcm.vc_dispmanx_display_open( 0 )
    +    disp = bcm.vc_dispmanx_display_open( device )
         if disp == 0:
             raise bcm.BCMDisplayException("Couldn't open handle to display")
         D = bcm.DisplayHandle()
```

I was able to run the AWESOME demo on the DSI display. Execute
```
KIVY_BCM_DISPMANX_ID=4 LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH python examples/demo/pictures/main.py -d
```
Changing ```KIVY_BCM_DISPMANX_ID=5``` runs the demo on the HDMI screen (but without touch :-))

**Comment by inclement** [comment]
I've merged jehutting's PR (thanks!), but I'll leave this open a little while to check that it does resolve people's issues. You can try the fix by building kivy from the master branch.

**Comment by akshayaurora** [comment]
Users on kivy-users have reported that the method mentioned above works.
