### ISSUE TITLE
App crashes immediately after launching on Android

### ISSUE THREAD

**Issue by Alecktos** [kivy/kivy#3644]
There seem to be a problem running apps on Android. It works fine I'm when running it on Mac OS but crashes immediately after the source files have been extracted on Android. I'm using buildozer to build it and what I can see there are no problems when building the app.

I/python  (14025): extracting lib/python2.7/site-packages/pygame/threads/__init__.pyo
I/python  (14025): extracting main.pyo
I/python  (14025): extracting renderer.pyo
I/python  (14025): extracting sitecustomize.pyo
W/ResourceType(14025): No package identifier when getting value for resource number 0x00000000
E/art     (14025): dlopen("/data/app/org.test.myapp-2/lib/arm/libpython2.7.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "exp" referenced by "libpython2.7.so"...
E/AndroidRuntime(14025): FATAL EXCEPTION: Thread-757
E/AndroidRuntime(14025): Process: org.test.myapp:python, PID: 14025
E/AndroidRuntime(14025): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "exp" referenced by "libpython2.7.so"...
E/AndroidRuntime(14025): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime(14025): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(14025): 	at org.renpy.android.PythonActivity.run(PythonActivity.java:254)
E/AndroidRuntime(14025): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  562):   Force finishing activity 1 org.test.myapp/org.renpy.android.PythonActivity

**Comment by tito** [comment]
What phone do you have?

**Comment by tito** [comment]
And which SDK did you use to compile?

**Comment by Alecktos** [comment]
I've got a Nexus 4 running Android 5.1.1. I'm using SDK 21

**Comment by SeanSWatkins** [comment]
exactly the same issue occured with me

**Comment by tito** [comment]
It might be related to http://stackoverflow.com/questions/27119623/android-l-5-0-does-not-search-native-libraries-in-armeabi-or-armeabi-v7a-f

**Comment by rammie** [comment]
I'm running into this issue as well, independent of device. However, I'm able to build the same app using the same toolchain on linux (fedora 22), but receive this error when building on a mac (osx 10.11.1). I'm using buildozer pointed to the old_toolchain branch of python-for-android. Perhaps this bug should be moved to the old_toolchain branch of python-for-android?

**Comment by heliomaster** [comment]
@tito 
@rammie 
Hi Guys,
I believe I have the same problem here on OSX 10.9.5:

D/houdini ( 6638): [6657] Load library /data/app/org.test.njeapp-2/lib/arm/libpython2.7.so failed.
E/art     ( 6638): dlopen("/data/app/org.test.njeapp-2/lib/arm/libpython2.7.so", RTLD_LAZY) failed: dlopen failed: "/data/app/org.test.njeapp-2/lib/arm/libpython2.7.so" has unexpected e_machine: 40

**Comment by kived** [comment]
@heliomaster You have a different problem. You are not missing the same `exp` symbol as the original post. You're also using Android x86, while P4A compiles for ARM. This usually works fine via houdini, but apparently houdini is rejecting for some reason (and you didn't include that reason, which should have been right above those lines from the log). Feel free to open a new issue.

**Comment by heliomaster** [comment]
Hi kived ,
I will open the issue, thank you for the answer.

**Comment by themanof9s** [comment]
I'm having a similar error
E/art     (18347): dlopen("/data/app/org.test.mypainter-1/lib/arm/libpython2.7.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "exp" referenced by "libpython2.7.so"...
E/AndroidRuntime(18347): FATAL EXCEPTION: Thread-4308
E/AndroidRuntime(18347): Process: org.test.mypainter:python, PID: 18347
E/AndroidRuntime(18347): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "exp" referenced by "libpython2.7.so"...
E/AndroidRuntime(18347): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime(18347): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(18347): 	at org.renpy.android.PythonActivity.run(PythonActivity.java:254)
E/AndroidRuntime(18347): 	at java.lang.Thread.run(Thread.java:818)

**Comment by mikeyjkmo** [comment]
I'm experiencing the same error whilst trying to deploy using Buildozer. I've tried changing the SDK versions etc to no avail. I'm using OSX Yosemite and my phone is a OnePlus One.

**Comment by kived** [comment]
This issue was moved to kivy/python-for-android#653

**Comment by Muzingaye-Nkala** [comment]
the solution that worked on my side is that instead of using a capital letter for Main.py I used a small letter main.py and it worked.. app did not crash..
