### ISSUE TITLE
Problem with running Kivy on Mac OS X 10.10

### ISSUE THREAD

**Issue by kea2288** [kivy/kivy#3649]
Hi guys, 
Please help me with my issue. I already waste 2 days but I couldn't run Kivy. I have default python 2.7.10 and I installed python 3.4.3, but again default is 2.7.10. Could you tell me what is wrong, here is the report:
[INFO   ] [Logger      ] Record log in /Applications/Kivy.app/Contents/Resources/.kivy/logs/kivy_15-09-23_11.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2

**Comment by rogererens** [comment]
These are just INFO lines, no ERRORs, so nothing to worry about.
If you really do have a problem with running Kivy, show us the command you typed and its resulting error message, please.

**Comment by kea2288** [comment]
Thank you, rogererens! I got it. 
I was wonder why GUI is not pops up. My mistake was on "if" statement on the last lines of code. I wrote '__NameOfMyProgram__' instead of '__main__'.
