### ISSUE TITLE
Window.softinput_mode = 'below_target' shifts Window upwards on start

### ISSUE THREAD

**Issue by mixedCase** [kivy/kivy#3651]
Title. Tested on Android 5.1.1 and Android 4.2.2

It fixes itself when a TextInput is focused.

**Comment by mixedCase** [comment]
Here's a screenshot:

![](https://i.imgur.com/kWOVlAF.png)

**Comment by akshayaurora** [comment]
You need to use latest master, this was fixed recently, remove your app/.buildozer and your ~/.buildozer/android/cache folders

Then rebuild.

Please reopen if you can still reproduce.
