### ISSUE TITLE
Website: invalid link to PyEnchant

### ISSUE THREAD

**Issue by dereks** [kivy/kivy#3660]
On this page:

http://kivy.org/docs/installation/installation.html

Clicking the link to "Enchant" (which is actually PyEnchant) gives a 404 Not Found.

Google says it should link to:

http://pythonhosted.org/pyenchant/

Also here there is a minor typo here:

http://kivy.org/docs/guide/inputs.html

recieve  should be receive

**Comment by dessant** [comment]
Thanks, fixed in https://github.com/kivy/kivy/commit/595addaae9fb2219d257588a1aba84f409dfd012.
