### ISSUE TITLE
ffmpeg not available on latest versions of ubuntu

### ISSUE THREAD

**Issue by dusual** [kivy/kivy#3662]
In the documentation for linux installation one of the dependencies being asked to install is ffmpeg
but it throws an error because ffmpeg does not have an installation candidate on latest versions of ubuntu.

You can refer https://github.com/kivy/kivy/blame/master/doc/sources/installation/installation-linux.rst#L186

**Comment by akshayaurora** [comment]
closed by 766d93ec3a254f6bd3481131fe72c322977dfd08
