### ISSUE TITLE
Update pyinstaller packaging guide for OS X

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3667]
http://kivy.org/docs/guide/packaging-macosx.html#unofficial-method-using-pyinstaller

PyInstaller 3.0 was just released, the section with the tree inclusion should also be revisited, the linked issue seems to be solved on our part.
https://github.com/pyinstaller/pyinstaller/issues/1338

**Comment by cbenhagen** [comment]
I will give this a try. Guess we could merge this issue with https://github.com/kivy/kivy/issues/3486.

**Comment by dessant** [comment]
@cbenhagen thanks, there's a plan to make a new release once packaging and installation docs are updated/working.

**Comment by dessant** [comment]
ref https://github.com/kivy/kivy/pull/3772
