### ISSUE TITLE
Kivy window larger than screen at same resolution (Windows 10)

### ISSUE THREAD

**Issue by AgentSpaceCowboy** [kivy/kivy#3677]
My display is set to 1920x1024, but using fullscreen or creating a window of the same size creates a window larger than the display.
Setting the kivy window's width to 1540 fits the display of 1920.
The screenshot, taken after running the code below, should explain the issue.

![kivy_resolution_bug](https://cloud.githubusercontent.com/assets/8387752/10363744/d643b662-6da5-11e5-9f1d-11f53ecb5a1e.png)

Thank you for your good work!

# Script to reproduce:
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.uix.label import Label

from kivy.config import Config
Config.set('kivy', 'log_level', 'debug')
Config.set('graphics', 'fullscreen', 'auto')
#Config.set('graphics', 'width', '1920')
#Config.set('graphics', 'height', '1024')
#from kivy.core.window import Window
#print(Window.size)

class Controller(Widget):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        for x in range(0, 1920, 80):
            for y in range(0, 1080, 80):
                self.add_widget(Label(pos=(x, y), text=str(x)+","+str(y)))

class WorldscapeApp(App):
    def build(self):
        controller = Controller()
        return controller

if __name__ == '__main__':
    WorldscapeApp().run()

# Console dump:
[INFO              ] [Logger      ] Record log in C:\Users\marti\.kivy\logs\kivy_15-10-08_79.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: pygame
[DEBUG             ] [App         ] Loading kv <C:/Dropbox/Worldscape\worldscape.kv>
[INFO              ] [Window      ] Provider: pygame
[DEBUG             ] [WinPygame   ] Set window to fullscreen mode
libpng warning: iCCP: known incorrect sRGB profile
[DEBUG             ] [Window      ] Display driver windib
[DEBUG             ] [Window      ] Actual window size: 1920x1080
[DEBUG             ] [Window      ] Actual color bits r8 g8 b8 a8
[DEBUG             ] [Window      ] Actual depth bits: 24
[DEBUG             ] [Window      ] Actual stencil bits: 8
[DEBUG             ] [Window      ] Actual multisampling samples: 4
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'4.3.0 - Build 10.18.15.4256'>
[INFO              ] [GL          ] OpenGL vendor <b'Intel'>
[INFO              ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4600'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 3
[INFO              ] [GL          ] Shading version <b'4.30 - Build 10.18.15.4256'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Shader      ] fragment shader: <b"WARNING: 0:6: '' :  #version directive missing">
[DEBUG             ] [Shader      ] Fragment compiled successfully
[INFO              ] [Shader      ] vertex shader: <b"WARNING: 0:6: '' :  #version directive missing">
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [ImagePygame ] Load <C:\Programs\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\kivy\data\glsl\default.png>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG             ] [Resource    ] add <C:\WINDOWS\Fonts> in path list
[DEBUG             ] [Resource    ] add <C:\Programs\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\kivy\data\fonts> in path list
[INFO              ] [OSC         ] using <thread> for socket
[DEBUG             ] [Base        ] Create provider from mouse
[DEBUG             ] [Base        ] Create provider from wm_touch
[DEBUG             ] [Base        ] Create provider from wm_pen
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...

**Comment by dessant** [comment]
Could you take a screenshot with window decorations? It seems the window is not really bigger, but some of the content is cropped.

**Comment by dessant** [comment]
Also, if you set the window width to 1920 on a 1920x1080 display, the window decorations will overflow, the window size refers to the drawable area without decorations.

**Comment by AgentSpaceCowboy** [comment]
With window decorations:

![image](https://cloud.githubusercontent.com/assets/8387752/10364245/3ed20276-6da9-11e5-8924-43c3a74b4e88.png)

![image](https://cloud.githubusercontent.com/assets/8387752/10364254/4e34fbd8-6da9-11e5-88e8-b987435cf448.png)

**Comment by dessant** [comment]
You could use `maximize` in config instead of setting a specific size. As for the content overflow, try out GridLayout or StackLayout as your root widget.

**Comment by AgentSpaceCowboy** [comment]
Using GridLayout as root looks identical and does not fix the overflow.
"Config.set('graphics', 'window_state', 'maximized')" doesn't seem to do anything, is there another way to use 'maximize'?

Thanks for taking the time.

**Comment by dessant** [comment]
You have to import and set config options before importing the rest of kivy, see the note at the top of the config doc.

**Comment by AgentSpaceCowboy** [comment]
Didn't realize that, still no change though.
I have tried every combination of config and Window options I can think of, but the problem persists.

**Comment by dessant** [comment]
Join #kivy and post your modifed example there https://github.com/kivy/kivy#support.
