### ISSUE TITLE
OS X Install - Double Click on makesymlinks throws "unidentified developer" error

### ISSUE THREAD

**Issue by Christin10-10m** [kivy/kivy#3678]
Hi, During OSX install, when I double clicked on the makesymlinks icon I got the following error dialog: "can’t be opened because it is from an unidentified developer."

Had to hit control+click and add an exception to install the script. 

Everything else was very smooth, but It would be great if this error didn't happen and I didn't have to do exception. The warning dialog is not reassuring. 

Thanks!

**Comment by RedXBeard** [comment]
Hello that warning because of permissions settings of osx and that package installer is not on appstore. if you change that settings to trust 'from anywhere' that warning will not come again.
