### ISSUE TITLE
Fatal Python error: (pygame parachute) Segmentation Fault

### ISSUE THREAD

**Issue by sandmarq** [kivy/kivy#3701]
Same issue on more than one computer usinf Linux Mint 17.2

File main.py : 

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen, FadeTransition
class MainScreen(Screen):
    pass
class AnotherScreen(Screen):
    pass
class ScreenManagement(ScreenManager):
    pass
presentation = Builder.load_file("main.kv")
class MainApp(App):
    def build(self):
        return presentation
MainApp().run()

File main.kv : 

#: import FadeTransition kivy.uix.screenmanager.FadeTransition
ScreenManagement:
    transition: FadeTransition()
    MainScreen:
    AnotherScreen:
<MainScreen>:
    name: 'main'
    Button:
        on_release: app.root.current = 'other'
        text: 'Another Screen'
        font_size: 50
<AnotherScreen>:
    name: 'other'
    Button:
        on_release: app.root.current = 'main'
        text: 'back to the home screen'
        font_size: 50

error when running code :

[INFO   ] [Logger      ] Record log in /home/sandrine/.kivy/logs/kivy_15-10-15_5.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO   ] [Factory     ] 177 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <4.4.0 NVIDIA 340.93>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <Quadro 600/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <4.40 NVIDIA via Cg compiler>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
Fatal Python error: (pygame parachute) Segmentation Fault

**Comment by dessant** [comment]
How did you install kivy?

**Comment by sandmarq** [comment]
sudo add-apt-repository ppa:kivy-team/kivy
sudo apt-get update
sudo apt-get install python-kivy python-dev

I even tried with easy_install

for some reason works fine on my raspbian jessie

**Comment by dessant** [comment]
Try installing these deps then reinstalling kivy http://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2.

**Comment by dessant** [comment]
Pygame should not be used by kivy if everything goes well.

**Comment by sandmarq** [comment]
Now, even if I uninstall pygame and a different kivy version

[INFO ] [Logger ] Record log in /home/sandrine/.kivy/logs/kivy_15-10-15_10.txt
[INFO ] [Kivy ] v1.9.0
[INFO ] [Python ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO ] [Factory ] 173 symbols loaded
[INFO ] [Image ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO ] [Window ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO ] [GL ] OpenGL version <4.4.0 NVIDIA 340.93>
[INFO ] [GL ] OpenGL vendor 
[INFO ] [GL ] OpenGL renderer 
[INFO ] [GL ] OpenGL parsed version: 4, 4
[INFO ] [GL ] Shading version <4.40 NVIDIA via Cg compiler>
[INFO ] [GL ] Texture max size <16384>
[INFO ] [GL ] Texture max units <32>
[INFO ] [Window ] virtual keyboard not allowed, single mode, not docked
[INFO ] [Text ] Provider: pygame
[INFO ] [OSC ] using for socket
[INFO ] [Base ] Start application main loop
[INFO ] [GL ] NPOT texture support is available
Fatal Python error: (pygame parachute) Segmentation Fault

**Comment by sandmarq** [comment]
I was able to make it work after remove anytrace of kivy.

Reinstall by following your instructions by ignoring ffmepg because it's not available on mint.

And after everything worked perfectly.
