### ISSUE TITLE
Copyrights on example media / audio files?

### ISSUE THREAD

**Issue by danstoner** [kivy/kivy#3715]
I am considering re-using the audio files included in:

https://github.com/kivy/kivy/tree/master/examples/audio

but I cannot find an explicit copyright or license statement.

Are those audio files released under the same license as the software?

https://github.com/kivy/kivy/blob/master/LICENSE

Also, basically the same questions for any other media files (such as the fruit_images directory full of jpg media).

**Comment by kived** [comment]
The license is stated in the main.py.

> All the sounds are from the http://woolyss.com/chipmusic-samples.php
"THE FREESOUND PROJECT", Under Creative Commons Sampling Plus 1.0 License.
