### ISSUE TITLE
Cannot import name 'get_hooks' when building Windows executable

### ISSUE THREAD

**Issue by dagrooms52** [kivy/kivy#3718]
I've been trying to build a Windows executable of a Kivy application following these instructions: http://kivy.org/docs/guide/packaging-windows.html

It throws the error `cannot import name 'get_hooks'`. 

Here is my spec file:

    # -*- mode: python -*-

    from kivy.tools.packaging.pyinstaller_hooks import get_hooks
    import os

    block_cipher = None

    a = Analysis(['C:\\Users\\Daniel\\Desktop\\Classes\\SeniorDesign\\TabMachine\\main.py'],
                 pathex=['C:\\Daniel\\Kivy\\Kivy-1.9.0-py3.4-win32-x64\\TabMachine'],
                 binaries=None,
                 datas=None,
                 hiddenimports=[],
                 excludes=[],
                 win_no_prefer_redirects=None,
                 win_private_assemblies=None,
                 cipher=block_cipher,
                 **get_hooks())
    pyz = PYZ(a.pure, a.zipped_data,
                 cipher=block_cipher)
    exe = EXE(pyz,
              a.scripts,
              exclude_binaries=True,
              name='TabMachine',
              debug=False,
              strip=None,
              upx=True,
              console=True )
    coll = COLLECT(exe,
                   Tree('C:\\Users\\Daniel\\Desktop\\Classes\\SeniorDesign\\TabMachine'),
                   a.binaries,
                   a.zipfiles,
                   a.datas,
                   strip=None,
                   upx=True,
                   name='TabMachine')

And here is my full error output:

    C:\Daniel\Kivy\Kivy-1.9.0-py3.4-win32-x64\TabMachine>pyinstaller TabMachine.spec
    71 INFO: PyInstaller: 3.1.dev0
    72 INFO: Python: 3.4.3
    72 INFO: Platform: Windows-8-6.2.9200
    76 INFO: UPX is not available.
    [INFO              ] [Logger      ] Record log in C:\Users\Daniel\.kivy\logs\kivy_15-10-22_10.txt
    101 INFO: [Logger      ] Record log in C:\Users\Daniel\.kivy\logs\kivy_15-10-22_10.txt
    [INFO              ] [Kivy        ] v1.9.0
    99 INFO: [Kivy        ] v1.9.0
    [INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600     32 bit (Intel)]
    102 INFO: [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit     (Intel)]
     Traceback (most recent call last):
    105 WARNING: stderr: Traceback (most recent call last):
       File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    105 WARNING: stderr:   File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
         load_entry_point('PyInstaller==3.1.dev0', 'console_scripts', 'pyinstaller')()
    106 WARNING: stderr:     load_entry_point('PyInstaller==3.1.dev0', 'console_scripts', 'pyinstaller')    ()
       File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 97, in run
    107 WARNING: stderr:   File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 97, in     run
         run_build(opts, spec_file, pyi_config)
    107 WARNING: stderr:     run_build(opts, spec_file, pyi_config)
       File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    107 WARNING: stderr:   File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in     run_build
         PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
    108 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file,     **opts.__dict__)
       File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 738, in main
    109 WARNING: stderr:   File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py",     line 738, in main
         build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
    110 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'),     kw.get('clean_build'))
       File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    110 WARNING: stderr:   File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py",     line 681, in build
         exec(text, spec_namespace)
    111 WARNING: stderr:     exec(text, spec_namespace)
       File "<string>", line 3, in <module>
    111 WARNING: stderr:   File "<string>", line 3, in <module>
     ImportError: cannot import name 'get_hooks'
    113 WARNING: stderr: ImportError: cannot import name 'get_hooks'
    
    C:\Daniel\Kivy\Kivy-1.9.0-py3.4-win32-x64\TabMachine>

**Comment by kived** [comment]
Those docs are for the master (development) version of Kivy. Either update to the latest Kivy master from GitHub, or follow the 1.9.0 instructions: https://github.com/kivy/kivy/blob/1.9.0/doc/sources/guide/packaging-windows.rst

**Comment by pythonic64** [comment]
@dagrooms52 And don't forget to include SDL2 binaries.
