### ISSUE TITLE
checkbox active event not work

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#3732]
I can not find which is the main event for the checkbox in the kv file.
I tried *on_checkbox_active* but raise an error.
I tried *on_active* but does nothing (and do not raise any error)
on_release, on_press but obviously give me an error.

this is my basic test code line: *on_active: print("hello")*

What is the event that run when click on a checkbox?

thank you guys

**Comment by dessant** [comment]
`on_active` should work. Could you show a runnable example? Follow the template from here: https://github.com/kivy/kivy/wiki/Community-Guidelines.

**Comment by Tungsteno74** [comment]
@dessant thanks man.
I solved it by moving the event in the base widget (before it was in a custom widget).
This solution is not very reusable, but at least it works. It would help to improve this feature.
As I told here:
http://stackoverflow.com/questions/33399351/why-kivy-checkbox-active-event-not-work
