### ISSUE TITLE
Mention widget naming requirements

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3739]
Widget names must follow PEP8 in order to work in kv. We could specify this in `lang.rst` and/or `widget.py` and link to https://www.python.org/dev/peps/pep-0008/#class-names.

**Comment by dessant** [comment]
Allowing any valid class name would be even better. @matham, would it require many changes?

**Comment by emon10005** [comment]
hey i would like to work on it

**Comment by tshirtman** [comment]
@emon10005 
Feel free to make a pull request to the documentation :).
