### ISSUE TITLE
Kivy 1.9 on Windows 7 - no module named kivy

### ISSUE THREAD

**Issue by OortJacek** [kivy/kivy#3742]
Hello, I have huge problem with run kivy on windows. I have uninstalled all my previous python version but still nothing. I also have tried run with "open with" and "send to" and directly from kivy_bash.bat

Everytime I get error "no module named kivy".

I am trying to run example "hello world" button. 

http://pastebin.com/q9U57cVj

**Comment by dessant** [comment]
@OortJacek if it is a valid bug, it must be an issue in https://github.com/kivy/kivy-sdk-packager, please reopen there.
