### ISSUE TITLE
Kivy Scroll View scaling issue

### ISSUE THREAD

**Issue by Lomelgande** [kivy/kivy#3744]
Here is an Imgur album to illustrate what I am talking about.

http://imgur.com/a/WkyQW

I have a grid view within a scroll view (which is added to a box view as the parent). I have added images to the gridview which is then added to the scrollview. If I re-size the kivy window by a large amount you can see the canvas images that represent the frames of the added images skew dramatically to the point that they no longer represent the dimensions of the actual images. If I then re-size the kivy window by a very small amount, after i re-size by a large amount, the canvas for each image returns to the proper dimensions. The actual images don't change but the canvas that represents each position and size of the images do. It seems, as a whole, large window resizes either inward or outward cause an incorrect scaling but small resizes, either after large resizes or simply in general, correct this incorrect scaling/don't cause it at all.

**Comment by Lomelgande** [comment]
This seems to only happen when there is more than 1 widget added to the grid layout, within the scroll view. When one is added there is no scaling issue. The second there are two or more is then this starts to occur.

**Comment by dessant** [comment]
Please post a runnable example so we can test.

**Comment by Lomelgande** [comment]
from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.image import Image
from kivy.uix.label import Label
from kivy.graphics import Color, Rectangle
from kivy.uix.scrollview import ScrollView
from kivy.config import Config
from kivy.core.window import Window

class Example(GridLayout):
	def __init__(self, **kwargs):
		super(Example, self).__init__(**kwargs)

		self.cols = 1
		self.bind(minimum_height = self.setter('height'))

		self.scroll = ScrollView(width = self.width,
						  height = self.height)
	
		self.grid = Image(source = '',
						  size_hint_y = None,
						  keep_ratio = True,
						  allow_stretch = True)

		##If you change cols to 1 the same thing happens but instead of it being vertical it is now horizontal
		self.ability_grid = GridLayout(cols = 2,
									   spacing = 5,
									   size_hint_y = None)

		self.ability_grid.bind(minimum_height = self.ability_grid.setter('height'))

		self.ability_frame = ScrollView()

		self.gear_number = 2

		self.ability_tray1 = Label(text = '1')
		self.ability_tray2 = Label(text = '2')

		self.ability_grid.add_widget(self.ability_tray1)
		self.ability_grid.add_widget(self.ability_tray2)

		with self.ability_grid.canvas:
			Color(0,1,0,.5)
			self.scroll_test1 = Rectangle()

		with self.ability_grid.canvas:
			Color(0,0,1,.5)
			self.scroll_test2 = Rectangle()

		self.ability_frame.add_widget(self.ability_grid)
		self.grid.add_widget(self.ability_frame)
		self.scroll.add_widget(self.grid)
		self.add_widget(self.scroll)

		self.bind(size = self.Scale)

	def Scale(self, *args):
		value =  [Window.width, Window.height]

		self.ratio = value[0]/4950.0

		self.new_scale_width = self.ratio * 4950.0
		self.new_scale_height = self.ratio * 8000.0

		self.grid.size = (self.new_scale_width, self.new_scale_height)

		self.ability_frame.size = (3750.0 * self.ratio, 2940.0 * self.ratio)

		self.ability_grid_height = self.gear_number * 700.0

		self.ability_grid.size = (self.ability_frame.width, self.ability_grid_height * self.ratio)
	
		self.scroll_test1.size =  self.ability_tray1.size
		self.scroll_test1.pos = self.ability_tray1.pos

		self.scroll_test2.size = self.ability_tray2.size
		self.scroll_test2.pos = self.ability_tray2.pos

class TestApp(App):

	def build(self):
		return Example()

if __name__ == '__main__':
	TestApp().run()

Here is some code from my app. I took out most of the extra crap. You have to scroll down to the bottom of the blank page to see the small scroll view that is having issues. I put in a note relating to the cols number. You can change that between 1 and 2 to get the effect in either the horizontal or vertical direction. Just resize it a bunch and hopefully you will see what I am talking about.
I am on a Win 10 machine and I am using the self contained Kivy 1.9.0

**Comment by Lomelgande** [comment]
This code doesn't seem to cause any problems on my laptop with Ubunut. It might be an issue with Windows and Kivy.

**Comment by Lomelgande** [comment]
I think I might have found a potential cause for this. On my Ubunut laptop, when I enlarge the kivy window, the contents of the app is being updated with new a new screen resolution repeatedly as I stretch the window. On my Windows 10 machine, as I stretch the window, the window is't being updated with a new size until I finish resizing the window and release the mouse.

**Comment by Lomelgande** [comment]
I think I fixed the issue. The ticket can be closed now.
