### ISSUE TITLE
ListItemLabel 'padding' problem

### ISSUE THREAD

**Issue by davelawr** [kivy/kivy#3749]
I am using a ListView and ListAdaptor to make a list with a button and a label. I have wrapped the ListItemLabel into a class as I want to give it a background colour (with a 'bound' rectangle) and left align the text (with a bound 'settter'). Code fragment below.

The problem is the 'padding = (-10,0)' attribute. I would expect this to be (10,0), but in this case my label overlaps the preceeding button.

This is running on ubuntu precise which only allows kivy 1.8.0.

If I run the same application on 1.9.1 (on a RaspberryPi) the value of (10,0) works as expected.

I need to continue development on 'precise' for the time being and as far as I can see it's not possible to update beyond 1.8.0

Is this padding a known problem in 1.8.0? 

```python
class LogListItemLabel(ListItemLabel):
    def __init__(self, background_color=None, **kwargs):
        ListItemLabel.__init__(self, **kwargs)
        self.bind(size=self.setter("text_size"))
        with self.canvas.before:
            if background_color is None:
                background_color = (0,0,0,1)
            Color(*background_color)
            self._bg = Rectangle(size=self.size, pos=self.pos)
        self.bind(pos=self._update_bg, size=self._update_bg)

    def _update_bg(self, instance, value):
        self._bg.pos = instance.pos
        self._bg.size = instance.size

class LogItem(object):
    def __init__(self, time, message):
        self.time = time
        self.message = message
    def row(self, row):
        return dict(
            size_hint_y = None,
            height = 25,
            cls_dicts =  [
                dict(
                    cls = ListItemButton,
                    kwargs = dict(
                        text = self.time.strftime("%Y-%m-%d %H:%M:%S"),
                        size_hint=(0.3,1),
                        deselected_color=(0,.5,.5,1)
                        ),
                    ),
                dict(
                    cls = LogListItemLabel,
                    kwargs = dict (
                        text = self.message,
                        is_representing_cls = True,
                        markup = True,
                        halign = "left",
                        valign = "middle",
                        background_color = (0,.3,.3,1),
                        padding = (-10,0),
                        )
                    ),
                ]
            )
```

**Comment by rdevost** [comment]
Hi davelawr,
I found that using negative pad numbers to be inconsistent in how the results displayed--particularly when moving between devices with different screen resolutions. I solved the alignment problem by using a BoxLayout within the ItemButton and adjusting the size of the box (e.g., size_hint_y: .95). 

I was never comfortable using negative numbers since I couldn't be sure they would be supported in all Kivy versions and platforms. I'm much happier with using a standard Kivy mechanism in a standard way.

P.S. Kivy 1.9 is a great upgrade. Hope you can move there soon.
Richard

**Comment by davelawr** [comment]
Hi, Just back on to this now -- thanks for the note. I certainly don't like the -ve padding! My requirement remains, although I now have two labels within a Widget (one left and one right justified). Is there a sensible way to get these to pad that will work on 1.8 and 1.9?
