### ISSUE TITLE
Add 'is_shortened' BooleanProperty to Label

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3753]
There should be a boolean property that can be checked to find out if the label was shortened or not.
One use case is to display the full text in a tooltip, on hover.

**Comment by matham** [comment]
Maybe an event is better? So one can have access to the shortened text? Although a prop is probably just as good.

**Comment by dessant** [comment]
A prop might be better, with an event only, one would end up needing to store the state in a prop.
But yeah, we could have `shortened_text` instead of a boolean.

**Comment by matham** [comment]
Yeah, in which case, a value of `None` means no shortened text.

**Comment by dessant** [comment]
We could also opt for an empty string and use a StringProperty.
