### ISSUE TITLE
Support for Kivy on Windows Phone

### ISSUE THREAD

**Issue by KronosKoderS** [kivy/kivy#3754]
Is there any plans for supporting Kivy running on the Windows Phone or as a Universal Windows Application?

**Comment by dessant** [comment]
There are no concrete plans, but we welcome anyone who wants to contribute towards this goal.

**Comment by adibradfield** [comment]
Is there currently anyone known to be working on this issue? I was planning on having  look at this myself, but if someone's already made a start, it would be useful

**Comment by dessant** [comment]
@adibradfiel, no work has been done, it is free to take. :wink:

**Comment by dessant** [comment]
Let's track this at https://github.com/kivy/kivy/issues/5125.
