### ISSUE TITLE
Kivy's online documentation is not being updated

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3755]
As far as I know the doc building task is being dispatched from the mac mini to the server where the docs are hosted, or something similar, the point is that docs are not being rebuilt if something is wrong with the mac.

Please have a script running directly on the website server, watching for new github commits and rebuilding the docs.

@tito, @matham i'm only aware of you having access to the server.

**Comment by tito** [comment]
I'm going to plug back the mac mini this week. I still don't have reliable internet at home, so it will be move away. We can't run the documentation update on the server itself.

**Comment by dessant** [comment]
Why is a server side build not possible?

**Comment by dessant** [comment]
If it's because of resources, we could make use of travis, it builds the docs anyway on every commit.

**Comment by dessant** [comment]
It turns out travis supports keys: http://docs.travis-ci.com/user/encryption-keys/.
This looks like a great solution for uploading the docs built by travis.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/3781.
