### ISSUE TITLE
Change shadereditor resolution uniform to be for GL area, not whole window?

### ISSUE THREAD

**Issue by stuaxo** [kivy/kivy#3760]
I've been having a go at using the [book of shaders](http://patriciogonzalezvivo.com/2015/thebookofshaders/) examples in kivy, it's a bit weird in the shader editor as it seems like the coordinate system, uses those of the whole window not the visible area.

So this example -
http://patriciogonzalezvivo.com/2015/thebookofshaders/07/

Is offset (screenshot of it next to browser version)
https://imgur.com/LxMCymS

Would it be possible to change it so the coordinate system (projection matrix?) is for the GL area, not the sidebar?

It would be less confusing for those of us starting out and trying shaders from various sources.

To get it working rename the uniforms to be u_time, u_resolution etc.

**Comment by inclement** [comment]
The resolution here does give the size of the ShaderViewer widget, the problem with the offset is that the shader works with the full opengl context which is the size of the window.

Normally you'd just apply an offset in the shader code, but for a shader editor a flexible and extensible solution is to use an FBO and display its output texture using a Rectangle. This way all of the internal opengl coordinates relate to the displayed image in an unsurprising way, and you can easily do stuff like make the FBO resolution different to that of the window if you have a complex shader. Kivy's shader examples include an example of using an FBO this way, and the EffectWidget also does this internally (in fact, you might like to play with converting your shaders to EffectWidget effects).

I'm going to close this issue on the basis that kivy's shader editor is deliberately very simple to aid learning, but if you wanted to contribute an improved mechanism like that then we'd probably consider it, either as an update or a new demo.

**Comment by stuaxo** [comment]
Cheers for the info, for my app initially I can probably use things as-is as it'll be full-screen, but for future stuff I'll definitely have a look @ the FBO + Rectangle method + see what I can come up with once I know what I'm doing a little more.
