### ISSUE TITLE
Window properties are not consistent with widgets

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#3766]
Currently, Window has a `top` and `left` properties, but top seems to be fixed at 0. This should be made consistent with widgets, so `top` is an alias of `height`, and `right` should be added as an alias of `width`. `x` and `y` should be added with static values of 0, 0.

Currently if you make for example a widget that is draggable only within its parent, different tests must be used if the widget is added to Window vs a FloatLayout.

**Comment by dessant** [comment]
Your proposal affects https://github.com/kivy/kivy/issues/3799. Treating Window as a widget would create conflicts. I would be in favor of separating window and widget space even further and not allow adding widgets to Window directly, but to a root widget.

**Comment by Julian-O** [comment]
Wrote some code. Ran on Kivy 2.2.1, on Windows. Resized the window. Moved the window.

Confirmed `window.top` is related the location of the top of the window (below the header line) , relative to the top left corner of the screen(s) (positive is down,  it can be negative). It is unrelated to the height of the window (i.e. resizing it taller makes no difference).

It isn't always zero.

I don't think this proposal makes sense as is. I am closing as Won't Fix. If you disagree, please let us know.

 
```
from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window

kv = """
Button:
    label: "Press me to find window.top"
    on_press:
        print(app.win.top)
"""


class TestApp(App):
    def build(self):
        self.win = Window
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```
