### ISSUE TITLE
TextInput's text freezes application

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#3770]
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
Builder.load_string('''
<Body>:
    NumInput:
        text:'1.1'
    Button:
<NumInput@TextInput>:
    size_hint: None,None
    height: self.minimum_height
    width: self.height
''')
class Body(BoxLayout):
    pass
class A(App):
    def build(self):
        self.body = Body()
        return self.body

if __name__ == '__main__':
    A().run()
```
I have encountered a problem with a TextInput or as @bionoid suggested on irc, Alias Property. The problem is in using as a text "something.something" in a TextInput which somehow freezes the application.
There is also a "skip" in the freezing when the size of TextInput is set(changes to a rectangle) and the freezing continues.

works either without:
```python
width: self.height
```
or
```python
self.body = Body()
return self.body
```
(just "return Body()" )
or just in kv(bionoid)
```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
<NumInput@TextInput>:
    size_hint: None, None
    height: self.minimum_height
    width: self.height

BoxLayout:
    Button:
    NumInput:
'''))
```
or not in the form of sth.sth i.e. without "."

**Comment by akshayaurora** [comment]
minumum_height is based on how many lines does the text take based on TextInput's Width,

So essentially you are setting 

    height: self.width/rest of formula for calculating total height of lines
    width: self.height

Both change each other leading to diff values, I guess we need to add this to the docs

**Comment by KeyWeeUsr** [comment]
Ah, I didn't notice it's bounded to the width. Now it makes sense and actually the word separator "."/" "/... has nothing to do with this issue. Thanks.

**Comment by akshayaurora** [comment]
@KeyWeeUsr we still need to document this, I am re-opening the issue so we don't forget to do that.
