### ISSUE TITLE
When hiding the mouse the touchscreen is disabled

### ISSUE THREAD

**Issue by schoolsplay** [kivy/kivy#3775]
When using Config.set('graphics', 'show_cursor', 0) to hide the mouse  in Kivy 1.9.0 the touchscreen on all MSI all-in-one PCs stops working.
This was also the case in previous kivy versions that depended on pygame.
In the previous versions I could set the mousepointer image to a empty image by using pygame.cursors.load_xbm and thus hide the mouse but still have a working touchscreen.
But pygame is no longer available and there doesn't seems to be a similar method in the new sdl kivy version.
I feel it's a bug to have a disabled touchscreen when the mouse is hidden.
I have this problem on all current  MSI touchscreen models and also on the new AP16-Flex model.

**Comment by inclement** [comment]
I'm fairly sure SDL2 has similar cursor setting options (even in the version we use, the new one which has just been or is about to be released has more), so an appropriate solution would be to expose these somehow. This would probably involve writing some simple cython code in the _window_sdl2.pyx file, and creating an appropriate api for the Window in general.

Not that you necessarily want to do this yourself, but if anyone is interested then this should be a fairly easy contribution.

**Comment by schoolsplay** [comment]
On 19-11-15 16:18, Alexander Taylor wrote:
> I'm fairly sure SDL2 has similar cursor setting options (even in the
> version we use, the new one which has just been or is about to be
> released has more), so an appropriate solution would be to expose these
> somehow. This would probably involve writing some simple cython code in
> the _window_sdl2.pyx file, and creating an appropriate api for the
> Window in general.

Looking at the SDL2 mouse header file I see this:

*/Create a cursor, using the specified bitmap data and
*         mask (in MSB format).
*/

SDL_CreateCursor(const Uint8 * data,
                  const Uint8 * mask,
                 int w, int h, int hot_x,
                  int hot_y);

So it seems only a kivy binding is needed ?


>
> Not that you necessarily want to do this yourself, but if anyone is
> interested then this should be a fairly easy contribution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/issues/3775#issuecomment-158086646>.
>

-- 
Regards,
Stas Zytkiewicz

**Comment by schoolsplay** [comment]
My fault, I was using an older 1.9.0 git  version.
With the latest 1.9.1 stable version the mouse is hidden and the touchscreen is working correctly.
I'm sorry for the confusion.
