### ISSUE TITLE
Cherry-picking cython fixes into stable branch

### ISSUE THREAD

**Issue by thopiekar** [kivy/kivy#3777]
While building packages for our stable PPA, I'm getting these errors, which don't occur on daily builds:
https://launchpadlibrarian.net/227019225/buildlog_ubuntu-wily-amd64.kivy_1.9.0-3~stable0%2B201511191645~pkg77~ubuntu15.10.1_BUILDING.txt.gz

Could you please cherry-pick the commits, which fix these errors into stable branch?

Thanks

**Comment by matham** [comment]
I think stable does not support that version of cython (0.23.3). Can't you downgrade cython to I think 0.23 which should fix that?

**Comment by thopiekar** [comment]
Well, if there is no way to fix it or it takes to much time, we can still
keep it like that. I'll just remove the broken packages. The latest Ubuntu
release already got kivy 1.9.0 in their repositories.
Finally, downgrading cython is no option (in my point of view a waste of
time - there are other more important tasks to be done). I'm happy that we
already got kivy compatible with cython shipped with Ubuntu and I don't
have to provide it in daily PPA anymore.

**Comment by matham** [comment]
Well, https://github.com/kivy/kivy/pull/3283 is what fixed it. @akshayaurora wanne merge it into stable?
