### ISSUE TITLE
bad permissions for /usr/local/lib/python2.7/dist-packages/kivy/data/ on linux

### ISSUE THREAD

**Issue by martindemello** [kivy/kivy#3779]
After a fresh install of kivy from source (make force; sudo make install) I tried to run an example (bezier.py) and got the error

````
   File "bezier.py", line 12, in <module>
     from kivy.app import App
     ...
 IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/kivy/data/style.kv'
````
It looks like files under kivy/data need to be chmod a+r

````
$ ls -al /usr/local/lib/python2.7/dist-packages/kivy/data/
total 72
drwxr-sr-x  7 root staff  4096 Nov 19 14:53 .
drwxr-sr-x 18 root staff  4096 Nov 19 14:53 ..
drwxr-sr-x  2 root staff  4096 Nov 19 14:53 fonts
drwxr-sr-x  2 root staff  4096 Nov 19 14:53 glsl
drwxr-sr-x  2 root staff  4096 Nov 19 14:53 images
drwxr-sr-x  2 root staff  4096 Nov 19 14:53 keyboards
drwxr-sr-x  2 root staff  4096 Nov 19 14:53 logo
-rw-r-----  1 root staff  2603 Nov 19 14:08 settings_kivy.json
-rw-r-----  1 root staff 40704 Nov 19 14:08 style.kv
````

(subdirs like data/fonts show the same issue)

**Comment by dessant** [comment]
@thopiekar, have you seen this before? I couldn't reproduce it when I last tried.

**Comment by kived** [comment]
This is an installation from source, not from a distributed package. We do not control these permissions.

This is almost certainly an issue with the `umask` in effect on your system/user. And this is now an old issue - if you are still experiencing difficulty, feel free to join us on our IRC channel for support, but this is not an issue with Kivy itself.
