### ISSUE TITLE
Bug in ScrollView causes 'scroll mode' to be entered when tapping on a touch-screen

### ISSUE THREAD

**Issue by peper03** [kivy/kivy#3783]
https://github.com/kivy/kivy/blob/master/kivy/uix/scrollview.py#L753 appears to be wrong:
"if ud['dx'] or ud['dy'] > self.scroll_distance:" causes it to enter scroll mode as soon as ud['dx'] is non-zero.

Tapping on a touch-screen (the Raspberry PI touch screen is what I have) nearly always ends up with ud['dx'] being 1 or 2, which makes selecting something from a drop-down challenging.

Changing the line to

if ud['dx'] > self.scroll_distance or ud['dy'] > self.scroll_distance

fixes the problem.  I don't know if that's the shortest construct available in Python, but it seems to confirm my suspicion.

There's nothing special about my code.  The 'showcase' example has the same issue.

**Comment by Lomelgande** [comment]
I made a ticket 6 days ago that might involve the same issue. I just recorded this.
https://vid.me/xn59
