### ISSUE TITLE
Very strange and critical fade transition crash

### ISSUE THREAD

**Issue by MartinPerez** [kivy/kivy#3791]
I have no idea on how to properly report this issue since its very strange and gives no error message back. It might also be linked with #1523.

Basically I have an app that keeps a synchronized state across devices. So when I change a screen on the android instance I trigger the same screen change on the linux instance. All works fine with default screen manager. self.sm = ScreenManager()

Now if I change the screen manager to use fade transitions:
self.sm = ScreenManager()#(transition=FadeTransition())

Then all works fine for the changes in linux from linux and in android from android, but when both instances are open, the android changes make the linux instance crash and viceversa :S. Literally the only change to trigger this behavior is to change the screen manager definition line to include fade transitions. I know the error occurs when making the screen change sm.current = other_screen_name, but trying to catch an error on this line returns nothing and the program simply crash. I also checked I am only changing if the target screen is different from the current one.

Its like the fact that a screen change is triggered while I am not directly interacting with the screen of the given instance is what creates the crash.

**Comment by bionoid** [comment]
Can you produce a minimal example, along with a traceback of the crash, or a gdb backtrace? There is no way to tell what the issue may be from your description alone. 

Taking a guess, may a threading issue related to network communication - drawing must be done from the main thread (see ``kivy.clock.mainthread`` decorator)

**Comment by MartinPerez** [comment]
Likely its what you point out. I am gonna check the thread suggestion and
come back with the full stack trace if its not the case. Thanks a lot!

On Sun, Nov 22, 2015 at 7:56 PM, Terje Skjaeveland <notifications@github.com

**Comment by MartinPerez** [comment]
I was effectively drawing from another thread and that was the problem. I will close this issue.
