### ISSUE TITLE
Unable to get Window Position w/ WindowSDL2?

### ISSUE THREAD

**Issue by lhl** [kivy/kivy#3799]
Kivy doesn't seem to support getting the Window position (I'd like to save the final window position so I can open it back up at the same location).  I see that SDL has a [SDL_GetWindowPosition()](https://wiki.libsdl.org/SDL_GetWindowPosition) function - is that something that might be added to the WindowSDL2 class? (it looks like it'd need to be added to _window_sdl2.pyx since it needs to talk to the _WindowSDL2Storage win?)

I can probably submit a pull request, but figured I'd find out what the preferred method naming/way to add this (it looks like getting Window position is applicable to most of the backends?)

**Comment by dessant** [comment]
`Window.pos` for getting and setting would be good. You could use Window.size as a template for implementation. This would mean that `Window.pos`, `Window.x` and `Window.y` would be added to the api.
