### ISSUE TITLE
Touch problems on Android in master

### ISSUE THREAD

**Issue by inclement** [kivy/kivy#3805]
Apparently everything worked in 97c50d9d2375f197d09eec08b19af84348d85903, but has since broken, as in the following email chain:

> Hey!
> Thanks for your help.
> It works with the following version '97c50d9d2375f197d09eec08b19af84348d85903'...
> Kr,
> Filip
> 
> Op zondag 29 november 2015 12:39:32 UTC+1 schreef Alexander Taylor:
> 
>     You can get the id by navigating to
>     .buildozer/android/platform/python-for-android and running 'git
>     rev-parse HEAD'. If you're able to post it here, I'll open the issue.
> 
>     Thanks.
> 
>     On 29/11/15 11:18, Filip Demaertelaere wrote:
>     > I don't have really a login to post bugs...
>     > I also use buildozer to do all my stuff for the Android device... So
>     > reference to the commit-id is difficult.
>     > F
>     >
>     >
>     > Op zondag 29 november 2015 12:09:38 UTC+1 schreef Alexander Taylor:
>     >
>     >     I've not tried, but this seems like it's fairly probably a regression,
>     >     so are you able to open a bug on github about it? It would be useful to
>     >     include the commit id of your version that works.
>     >
>     >     On 29/11/15 09:18, Filip Demaertelaere wrote:
>     >     > I did another test today... I had a virtual machine with an older
>     >     master
>     >     > branch of the 1.9.1...
>     >     > After re-compilation, all went well.
>     >     > So seems really a problem in the update somewhere.
>     >     > Do you experience the same? Because in this case we need to
>     >     introduce a
>     >     > bug report;
>     >     >
>     >     > F
>     >     >
>     >     >
>     >     > Op zondag 15 november 2015 15:05:35 UTC+1 schreef Filip
>     >     Demaertelaere:
>     >     >
>     >     >     I took yesterday and today the daily build version, but have now
>     >     >     problems with the touch... Seems that the touch events are not
>     >     >     coming through. I certainly got this on my Samsung S5 with
>     >     Android
>     >     >     5. Somebody had the same problem? Or could it be an issue at my
>     >     >     side? Normally the code at my side had not changed to have this
>     >     >     wrong behavior.
>     >     >     Kr,
>     >     >     Filip
>     >     >
>     >     > --
>     >     > You received this message because you are subscribed to a topic in
>     >     the
>     >     > Google Groups "Kivy users support" group.
>     >     > To unsubscribe from this topic, visit
>     >     >
>     >     https://groups.google.com/d/topic/kivy-users/GTYfbqLrxsM/unsubscribe
>     >     <https://groups.google.com/d/topic/kivy-users/GTYfbqLrxsM/unsubscribe>.
>     >     > To unsubscribe from this group and all its topics, send an email to
>     >     > kivy-users+...@googlegroups.com <javascript:>
>     >     > <mailto:kivy-users+unsubscribe@googlegroups.com <javascript:>>.
>     >     > For more options, visit https://groups.google.com/d/optout
>     >     <https://groups.google.com/d/optout>.
>     >
>     >
>     > --
>     > You received this message because you are subscribed to a topic in the
>     > Google Groups "Kivy users support" group.
>     > To unsubscribe from this topic, visit
>     > https://groups.google.com/d/topic/kivy-users/GTYfbqLrxsM/unsubscribe.
>     > To unsubscribe from this group and all its topics, send an email to
>     > kivy-users+...@googlegroups.com
>     > <mailto:kivy-users+unsubscribe@googlegroups.com>.
>     > For more options, visit https://groups.google.com/d/optout.
> 
> 
> -- 
> You received this message because you are subscribed to a topic in the Google Groups "Kivy users support" group.
> To unsubscribe from this topic, visit https://groups.google.com/d/topic/kivy-users/GTYfbqLrxsM/unsubscribe.
> To unsubscribe from this group and all its topics, send an email to kivy-users+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.

**Comment by tito** [comment]
@inclement No 97c50d9d2375f197d09eec08b19af84348d85903 commit in kivy not python-for-android.

**Comment by inclement** [comment]
Dunno what's up with that then - maybe we should just close this and if anyone has better info they can reopen.

**Comment by FilipDem** [comment]
Hi,
What do you need as extra information?

I got a ListView that was always working fine with the master branch 1.9.1, both on desktop Ubuntu and on Android. See part of the kv file hereunder. After an update of the master/daily build, it still worked on desktop Ubuntu, but no longer on my Android Samsung S5.

It select an item in the listview, nothing is detected (even button is not selected). If I tap several times one after the other, sometimes it is selected. Same happens with drop-down boxes or input fields. Lucky I had a earlier daily build version of the 1.9.1 on a virtual machine. If I use this version (see commit ID above), it works.

		ListView:
			id: portfolio_list
			size_hint_y: 1
			adapter:
				list_adapter(data=[], cls=widget_listbutton.MyListItemButton, args_converter=widget_listbutton.args_converter, selection_mode='single')

I know it is not a very detailed information, but I don't know how I can help further. I am not very experience with Git(Hub). I just use buildozer and I configured it to take the kivy master/daily build ("requirements = kivy==master"). I need the Kivy 1.9.1 to use the softinput_mode = 'below_target', which is only in the 1.9.1.

Kind regards,
Filip

**Comment by FilipDem** [comment]
Nobody has this problem?? I already tried to whole day to find the root cause of the is problem, but without result. Got now a tablet with Android 4.2 (Samsung Galaxy TAB2) and there it seems to work correctly. The same app on my Android 5 (Samsung Galaxy S5) give the problem described above...

**Comment by dessant** [comment]
Let's track this bug at https://github.com/kivy/kivy/issues/4031.
