### ISSUE TITLE
cx_Freeze kivy application

### ISSUE THREAD

**Issue by daconex** [kivy/kivy#3807]
Is it possible to use cxfreeze on a kivy project to turn it into an .exe? 

If so, is there a tutorial on how to correctly compile it?
If not, is there an alternative way to compile a kivy project to a Windows executable?

**Comment by dessant** [comment]
There are no kivy docs for cx_freeze usage, but you might have luck adapting the pyinstaller one. http://kivy.org/docs/guide/packaging-windows.html
You could use pyinstaller though, or nuitka, but the latter is largely untested.
https://github.com/kivy/kivy/wiki/Packaging-Kivy-apps-written-in-Python-3,-targeting-Windows-using-Nuitka
