### ISSUE TITLE
/usr/bin/ld: cannot find -lGL

### ISSUE THREAD

**Issue by Priler** [kivy/kivy#3814]
I'm currently on Ubuntu 14.04 LTS.

I need kivy-dev to be installed.
Following this instructions http://kivy.org/docs/installation/installation.html#development-version

When trying to run "make" command within kivy-master, i have this error:

```
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 
```

Full log is here - http://pastebin.com/tRGJmN30

---

If i will locate ligGL.so files, here is output:
```
/usr/lib/i386-linux-gnu/mesa/libGL.so.1
/usr/lib/i386-linux-gnu/mesa/libGL.so.1.2.0
/usr/lib/nvidia-346/libGL.so
/usr/lib/nvidia-346/libGL.so.1
/usr/lib/nvidia-346/libGL.so.346.96
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
/usr/lib32/nvidia-346/libGL.so
/usr/lib32/nvidia-346/libGL.so.1
/usr/lib32/nvidia-346/libGL.so.346.96
```

**Comment by kived** [comment]
Did you install `libgles2-mesa-dev` as outlined in the instructions? Because you should be seeing something like:

````
NOTE: Found GLES 2.0 headers at /usr/include/GLES2/gl2.h
Using this graphics system: OpenGL ES 2
````

instead of:

````
NOTE: Not found GLES 2.0 headers at: ['/usr/include', '/usr/local/include']
      Please contact us if your distribution uses an alternative path for the headers.
Using this graphics system: OpenGL
````

You are also missing GStreamer and SDL2. GStreamer is optional, but it's recommended for audio support on Linux. You can install the needed package if you'd like:

````
sudo apt-get install libgstreamer1.0-dev
````

You should definitely install SDL2 though. The pygame backend is deprecated and will be removed in a future version. To install SDL2:

````
sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
````

Finally, you are indeed missing libGL.so. This file MUST be located at `/usr/lib/x86_64-linux-gnu/libGL.so`. This is generally a symlink to the actual libGL.so file. By default, this will be a link to `/usr/lib/x86_64-linux-gnu/mesa/libGL.so`, but since you are using NVIDIA drivers this should be updated to `/usr/lib/nvidia-346/libGL.so`. Normally this happens during the installation process, but you should be able to fix it by running:

````
sudo update-alternatives --config x86_64-linux-gnu_gl_conf
````

and selecting the NVIDIA version.

**Comment by Priler** [comment]
First of all, special Thanks to @kived because he helped me to fix this and further issues.

Solution is:
Packages like SDL2 and others was not installing on my system because of error about damaged/held packages.
Solution was simple, i had "xorg-edgers ppa" instead of normal "ppa" (edgers provide not tested packages, thefore they want work on my system).

Also you might wanna check if you have that xorg-edgers ppa or not.
You can do it with this command:
```
ls /etc/apt/sources.list.d
```
If you will see something like "xorg-edgers ppa" then you have and you need to purge it (read below).

You need to remove this ppa, but be careful, it may cause some problems on your system!!!
```
sudo ppa-purge xorg-edgers
```

After this, you will be able to install all that packages that @kived listed above.
And, after that, you will be able to install kivy-dev without that annoying error about "-lGL".

You can install kivy-dev simply with this commands:
a) Remove old one
```
sudo apt-get remove python-kivy python-kivy-examples
```
b) Install new one
```
sudo pip uninstall kivy; sudo apt-add-repository ppa:kivy-team/kivy-daily; sudo apt-get update; sudo apt-get install python-kivy
```

Tadam! Now you will have kivy-dev successfully installed on your system!

===
So, this is not quite ending of this story.
The reason why i needed to install kivy-dev version, is KivEnt required this.

So, as you know, and as i said earlier, you might have problems with your system after purging xorg-edgers ppa, and i had that problems (many stuff stoped to work, for example settings panel and video card settings).

If you too facing this kind of errors after purging xorg-edgers ppa, and if you are using Ubuntu 14.04 LTS as me, then you need to do this 3 commands:
```
sudo apt-get install --reinstall gnome-control-center
sudo apt-get install --reinstall gnome-settings-daemon-schemas
sudo apt-get install --reinstall ubuntu-desktop
```

And, after this all, currently i have Kivy-Dev installed, as well as KivEnt installed on my Mega-System Ubuntu 14.04 LTS!)))

p.s.
Some inspiration would be good after this messy stuff - https://www.youtube.com/watch?v=_C3qkI4UwrY
