### ISSUE TITLE
TexInput: numpad-enter

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#3815]
python: 3.5
kivy: 1.9.0
OS: Win-7

Using on_text_validate in kv to change the focus:
on_text_validate: next_id.focus=True;

Pressing the bigger Enter of my keyboard will change the focus, but as I press the enter of the numpad nothing happens...

I've just updated my python to 3.5 and re-'pip'-d packages...

**Comment by akshayaurora** [comment]
This is fixed in master
