### ISSUE TITLE
Sporadic animation error when cancelling animations and removing a widget from stage #1

### ISSUE THREAD

**Issue by DigiCoyote** [kivy/kivy#3818]
12-01 10:47:36.485: I/python(6164): cjtp:r $Proxy0 definition $Proxy0
12-01 10:47:37.055: I/python(6164): cjtp:r $Proxy0 definition $Proxy0
12-01 10:47:37.495: I/python(6164): [INFO              ] [Base        ] Leaving application in progress...
12-01 10:47:37.495: I/python(6164):  Traceback (most recent call last):
12-01 10:47:37.495: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/app/main.py", line 324, in <module>
12-01 10:47:37.495: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 828, in run
12-01 10:47:37.495: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
12-01 10:47:37.505: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 401, in mainloop
12-01 10:47:37.505: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 288, in _mainloop
12-01 10:47:37.505: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
12-01 10:47:37.505: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 515, in tick
12-01 10:47:37.505: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 647, in _process_events
12-01 10:47:37.505: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 406, in tick
12-01 10:47:37.505: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/animation.py", line 335, in _update
12-01 10:47:37.505: I/python(6164):    File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7268)
12-01 10:47:37.505: I/python(6164):    File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:12817)
12-01 10:47:37.505: I/python(6164):    File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy/_event.c:12392)
12-01 10:47:37.515: I/python(6164):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/animation.py", line 437, in on_anim1_progress
12-01 10:47:37.515: I/python(6164):    File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7268)
12-01 10:47:37.515: I/python(6164):    File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:12817)
12-01 10:47:37.515: I/python(6164):    File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy/_event.c:12392)
12-01 10:47:37.515: I/python(6164):  TypeError: on_anim1_progress() takes exactly 4 arguments (3 given)
12-01 10:47:37.625: I/python(6164): Python for android ended.

**Comment by dessant** [comment]
What is stage #1 and how can we reproduce this? Please share a small, runnable app that shows the issue.

**Comment by DigiCoyote** [comment]
No worries on this one. It turns out that  I was running a ‘del’ command on the animation sequence a bit too early sometimes which was throwing this error (among other ones). Catch the error if you feel it’s appropriate. Not a bug, please close.
