### ISSUE TITLE
Sporadic animation error when cancelling animations and removing a widget from stage #2

### ISSUE THREAD

**Issue by DigiCoyote** [kivy/kivy#3819]
12-01 10:51:29.746: I/python(31920): cjtp:r $Proxy0 definition $Proxy0
12-01 10:51:30.247: I/python(31920): cjtp:r $Proxy0 definition $Proxy0
12-01 10:51:30.677: I/python(31920): True
12-01 10:51:30.677: I/python(31920): [INFO              ] [Base        ] Leaving application in progress...
12-01 10:51:30.677: I/python(31920):  Traceback (most recent call last):
12-01 10:51:30.677: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/app/main.py", line 324, in <module>
12-01 10:51:30.687: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 828, in run
12-01 10:51:30.687: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
12-01 10:51:30.687: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 401, in mainloop
12-01 10:51:30.697: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 288, in _mainloop
12-01 10:51:30.697: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
12-01 10:51:30.697: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 515, in tick
12-01 10:51:30.697: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 647, in _process_events
12-01 10:51:30.697: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 406, in tick
12-01 10:51:30.697: I/python(31920):    File "/home/kivy/Desktop/Appix/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/animation.py", line 309, in _update
12-01 10:51:30.697: I/python(31920):  KeyError: 9392
12-01 10:51:30.867: I/python(31920): Python for android ended.

**Comment by dessant** [comment]
Same here https://github.com/kivy/kivy/issues/3818#issuecomment-163283950.

**Comment by DigiCoyote** [comment]
No worries on this one. It turns out that  I was running a ‘del’ command on the animation sequence a bit too early sometimes which was throwing this error (among other ones). Catch the error if you feel it’s appropriate. Not a bug, please close.
