### ISSUE TITLE
Raspberry font /data/fonts/DroidSans not found

### ISSUE THREAD

**Issue by nais314** [kivy/kivy#3823]
Installed through documentation 1.9.1 on Raspberry Jessie 2015-11-21

IOError when trying demos
 font /data/fonts/DroidSans not found by .../text/__init__.py

I had to comment out "if font not found raise" lines (257,260) and the problem solved ;)

**Comment by dessant** [comment]
You may be using an outdated demo/example, try running the ones from the repo you cloned. `DroidSans` is not present in kivy master.
