### ISSUE TITLE
Wrong Y coordinate

### ISSUE THREAD

**Issue by K0XX** [kivy/kivy#3824]
I think there's an issue about Y coordinate:

``` python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.core.window import Window

Window.size = (800,800)

class RootWidget(BoxLayout):            
    def on_touch_down(self, touch):
        print(touch.x, touch.y)

class WeatherApp(App):
    def build(self):
        root = RootWidget()
        return root

if __name__ == "__main__":
    WeatherApp().run()
```

![errore](https://cloud.githubusercontent.com/assets/16174774/11612897/961af290-9c0c-11e5-8572-faaec39e8223.jpg)

X coordinate is right (from 0 to 799)
Y coordinate is wrong (from 1,9999 to 801)

I've used Kivy 1.9.0 on Windows x64.
I verified the same issue on Linux and Windows XP virtual machine (inside the Windows 7 Host).

Regards.

**Comment by pythonic64** [comment]
Should be fixed by https://github.com/kivy/kivy/pull/7389.
