### ISSUE TITLE
RelativeLayout/FloatLayout Default Size not changeable

### ISSUE THREAD

**Issue by opqopq** [kivy/kivy#3827]
Hi,

Using lastest master from this morning, I noticed that both RelateiveLayout & FloatLayout have a default size of 1,1, instead of 100, 100 before. 
The issue is that when I tried to force size through KV style, I did not work:

from kivy.uix.relativelayout import RelativeLayout
from kivy.lang import Builder

Builder.load_string('''
<RelativeLayout>:
    size: 100,100
''')

rl = RelativeLayout()
print rl, rl.size # I assumed rl.size would return 100,100, but It returned 1,1

**Comment by inclement** [comment]
Your kv string doesn't try to set the size of a RelativeLayout.

**Comment by opqopq** [comment]
I do not know why, but the formating of the kv does not appears correctly. It should read, of course:
<RelativeLayout>:
<TAB>size: 100,100.

I tried editing it without sucess.

**Comment by opqopq** [comment]
Sorry if double post vs github.My KV string was badly formatted thanks to MD Markup. I forgot the backlslash. It should read:
<RelativeLayout>  size: 100,100


Date: Mon, 7 Dec 2015 06:16:53 -0800
