### ISSUE TITLE
dll load failed  on windows 10 with python34

### ISSUE THREAD

**Issue by gantlion** [kivy/kivy#3831]
After installing the development version of kivy with python34 using pip I tried running:

    import kivy
    from kivy.app import App

and get the following error:

    In [2]: from kivy.app import App
    [INFO              ] [Factory     ] 179 symbols loaded
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-2-3aebb2f13fe4> in <module>()
    ----> 1 from kivy.app import App

    c:\python34\lib\site-packages\kivy\app.py in <module>()
        325 from kivy.resources import resource_find
        326 from kivy.utils import platform as core_platform
    --> 327 from kivy.uix.widget import Widget
    328 from kivy.properties import ObjectProperty, StringProperty
    329 from kivy.setupconfig import USE_SDL2

    c:\python34\lib\site-packages\kivy\uix\widget.py in <module>()
    217     NumericProperty, StringProperty, AliasProperty, ReferenceListProperty,
    218     ObjectProperty, ListProperty, DictProperty, BooleanProperty)
    --> 219 from kivy.graphics import (
    220     Canvas, Translate, Fbo, ClearColor, ClearBuffers, Scale)
    221 from kivy.graphics.transformation import Matrix

    c:\python34\lib\site-packages\kivy\graphics\__init__.py in <module>()
    87 '''
    88
    ---> 89 from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \
    90     ContextInstruction, Instruction, InstructionGroup, RenderContext, \
    91     VertexInstruction

    ImportError: DLL load failed: The specified module could not be found.

**Comment by matham** [comment]
You did install the glew and sdl2 deps, right?

**Comment by gantlion** [comment]
yeah and their _dev versions as well,  I left out gstreamer though

**Comment by matham** [comment]
Ok. Can you try two things if you have time? Can you manually add the python\share\sdl2\bin python\share\glew\bin directories to your path before you run python. That should tell you if it's just not finding the dlls or if the dlls are bad.

Then, can you launch depends.exe from http://www.dependencywalker.com/ and open the file to `kivy\graphics\texture.pyd` there. The program will show you all the dlls that are missing that are required by the file. Can you save and post that log?

**Comment by gantlion** [comment]
Putting the two bin directories in my path fixed the error I was getting.

Copied the first column of the results, is that what you wanted? 
[log.txt](https://github.com/kivy/kivy/files/54712/log.txt)

**Comment by matham** [comment]
If adding to the path fixed it, than something must be wrong with the mechanism that we have for the wheels for making their dlls discoverable. I imagine it's a windows 10 issue. I guess I'll have to find a win10 system to test on.

**Comment by gantlion** [comment]
Just for completeness, I am using Python 3.4.4rc1 that was released today. Thanks for the help

**Comment by matham** [comment]
I think I fixed it. Try downloading the dependencies again with pip (make sure to --upgrade so the old versions are replaced). I think that should fix it.
