### ISSUE TITLE
List/String Confusion for Clipboard in SDL2

### ISSUE THREAD

**Issue by opqopq** [kivy/kivy#3832]
When using Clipboard in latest Kivy with SDL2, get_types return a list of unitary character instead of a string:

```python
from kivy.core.clipboard import Clipboard
print Clipboard.get_types()

#print ['t', 'e', 'x', 't', '/', 'p', 'l', 'a', 'i', 'n'] instead of 'text/plain'
```
I assume it is due to a missing comma in kivy.core.clipboard_sdl2.py, line 33 in get_types; Should be:
```python
return ['text/plain' , ]

**Comment by akshayaurora** [comment]
closed via fe189fd

**Comment by akshayaurora** [comment]
@opqopq thanks

**Comment by tshirtman** [comment]
was this reopened by mistake?

**Comment by dessant** [comment]
@tshirtman, the commit did not fix the issue, it would have worked if the cause would have been the return value being a tuple, but lists do not need `,` for single items afaik.
