### ISSUE TITLE
Installation, Ubuntu, latest stable

### ISSUE THREAD

**Issue by jprukner** [kivy/kivy#3833]
From http://kivy.org/docs/installation/installation-linux.html 
```
sudo add-apt-repository ppa:kivy-team/kivy
sudo apt-get install python-kivy
```
These commands don't install latest stable version of kivy. I'm running Ubuntu.

**Comment by dessant** [comment]
You may have missed the second step after adding the ppa: Update your packagelist using your package manager.
```
sudo apt-get update
```
Uninstall the current python-kivy, then install it again.
Please reopen if the problem persists.

**Comment by jprukner** [comment]
Oh, I'm sorry. You are right. I've missed that. Thanks @dessant
