### ISSUE TITLE
TextInput "thinks" shift is still pressed after unfocusing

### ISSUE THREAD

**Issue by Cheaterman** [kivy/kivy#3838]
Ohai buddies! Sorry I don't have a test case at hand, but it should be easy enough to reproduce:

1°) Focus a textinput, type some stuff in it with shift pressed, then unfocus it somehow while shift is still pressed
2°) refocus the textinput, then press left or right to move cursor, you'll notice cursor SELECTS text instead of just moving, like if shift was still pressed

Hopefully reproducible always :-)

**Comment by tshirtman** [comment]
Can't seem to reproduce on linux, was it windows only?

**Comment by dessant** [comment]
I've followed the steps but no luck on windows, @Cheaterman, how about an examplili?

**Comment by Cheaterman** [comment]
Maybe not so easily reproducible. I didn't make a standalone test for this, so it's possible some other unrelated logic from my app interferes here... I'll give it some more time as soon as I can afford it :-)

**Comment by dessant** [comment]
Plese reopen when you'll have a test case.
