### ISSUE TITLE
ASyncImage does not take into account user/password for url 

### ISSUE THREAD

**Issue by bottoy** [kivy/kivy#3840]
Hi,

After some digging on this error, it seems that loader.py does not take into account authentication.
When adding the user/pw in the url (user:pw@host), urllib gives next error:

`URLError: <urlopen error [Errno 4] non-recoverable failure in name resolution.>`

Originating from from loader.py 312 -> _load_urllib.

Looking at the source code, no Authentication handler is initiated (cfr urllib docs) but only the urlopen function is called.

``` py
        try:
            _out_filename = ''

            if proto == 'smb':
                # read from samba shares
                fd = urllib_request.build_opener(SMBHandler).open(filename)
            else:
                # read from internet
                fd = urllib_request.urlopen(filename)
```

I do not know the logic used by Kivy, but I see 2 options:
Or we provide the 'opener' or the user/pw via kwargs ... 

Example usage:

``` py
import urllib2

# set up authentication info
authinfo = urllib2.HTTPBasicAuthHandler()
authinfo.add_password(realm='PDQ Application',
                      uri='https://mahler:8092/site-updates.py',
                      user='klem',
                      passwd='geheim$parole')

proxy_support = urllib2.ProxyHandler({"http" : "http://ahad-haam:3128"})

# build a new opener that adds authentication and caching FTP handlers
opener = urllib2.build_opener(proxy_support, authinfo, urllib2.CacheFTPHandler)

# install it
urllib2.install_opener(opener)

f = urllib2.urlopen('http://www.python.org/')
```

**Comment by dessant** [comment]
I'm not sure if AsyncImage should step into that territory and handle authentication.

**Comment by bottoy** [comment]
Not AsyncImage, but loader should be able to receive that info, no?

**Comment by dessant** [comment]
I'm not sure about that either, but if we do want it, the first step would be to solve this issue instead of further patching UrlRequest: https://github.com/kivy/kivy/issues/2773. Loader uses UrlRequest, which does not have an api for http auth, and you have to pass the user/pass in the header directly.

**Comment by bottoy** [comment]
As a workaround I made my own AsyncImage that uses an overriden loader from kivy and I adapted the _load_urllib function so that it contain the code mentioned above. I can connect secure and authenticated and the image is shown. The code is not yet dummy proof...

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
