### ISSUE TITLE
setup.py broken for python3

### ISSUE THREAD

**Issue by Vagdish** [kivy/kivy#3850]
Heya,

I installed kivy on a new computer running El Capitan OSX, to be used with Python 3.
During the installation using the following command line:
```
python setup.py install
```
an error raised at line 310, where bytes and str are being compared.

the faulty commit is this one:
d6deccac5a89e4c65cbd311bca3d8518ec467124

I successfully removed the error by encoding "@executable_path". But this change only works for Python 3.

I'm afraid I don't know Python 2, and how to handle str/bytes such as this line would work for both versions. So instead of pulling a change, I write this bug. I think it would be pretty obvious for people manipulating both Python 2 & 3.

Beside that, installation of kivy went smooth on El Capitan with Python 3.

**Comment by inclement** [comment]
Fixed by https://github.com/kivy/kivy/commit/0d4f258b4693395ac554c0c2147316fd67d1df7c
