### ISSUE TITLE
can't install on Win 7 with Python 3.4.4

### ISSUE THREAD

**Issue by StevanWhite** [kivy/kivy#3851]
This is Windows 7 with Python 3.4.4rc1, and also Visual Studio 10.
(It's a German system... sorry about the strange error messages.)

Trying to follow instructions in
http://kivy.org/docs/installation/installation-windows.html

First, it was unclear that Python needed to be downgraded.  The installation instructions say Python 3.5 is bad, but say nothing about 3.5.1.  But OK un-installed that and installed 3.4.4rc1.

Second there was confusion with Cython:  there was no mention of it before the line to install Kivy, but it is required.  Installing the default version resulted in a warning message, and a failed installation.  So downgraded that to Cython 0.21.2 as recommended in the warning message.

But Kivy still fails to install.  So completely deleted Python (including some leftover files by hand, and carefully installed everything with the recommended versions.  It says it can't find 'pkg-config'.  An earlier warning complains about gstreamer... I tried it both with gstreamer installed as recommended and without it.  Later it complains about C files for glew, although this was apparently installed.
The last attempt looked like this

PS> python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew 
... no errors
PS> python -m pip install kivy.deps.gstreamer --allow-external kivy.deps.gstreamer
... no errors
PS> pip install -I Cython==0.21.2
... no errors
PS> python -m pip install kivy

  Detected Cython version 0.21.2
  Windows platform detected, force GLEW usage.
  Using this graphics system: OpenGL
  WARNING: A problem occured while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

  b'Der Befehl "pkg-config" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n'

  WARNING: A problem occured while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

  b'Der Befehl "pkg-config" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n'
  
...

  creating build\temp.win-amd64-3.4\Release\Users\S2733~1.WHI\AppData\Local\Temp\pip-build-zwdrjx65\kivy\kivy\graphics
  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Python34\include" "-IC:\Progr
am Files\Python34\include" /TcC:\Users\S2733~1.WHI\AppData\Local\Temp\pip-build-zwdrjx65\kivy\kivy\graphics\opengl_utils.c /Fobuild\temp.win-amd64-3.4\Release\U
sers\S2733~1.WHI\AppData\Local\Temp\pip-build-zwdrjx65\kivy\kivy\graphics\opengl_utils.obj
  opengl_utils.c
  c:\users\s.white\appdata\local\temp\pip-build-zwdrjx65\kivy\kivy\graphics\gl_redirect.h(8) : fatal error C1083: Cannot open include file: 'GL/glew.h': No such
 file or directory
   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for kivy

**Comment by matham** [comment]
Sorry for the troubles you're having installing kivy. The main reason for all these issues is explained in the not at the top of in the install page: `This page represents instructions for wheels starting with 1.9.1. Until 1.9.1 is released the nightly wheels have to be used because stable kivy wheels have not been uploaded to pypi yet.`.

So the problem is that `python -m pip install kivy` will not work until we release 1.9.1 which should be soonish. instead you need to follow the instructions at http://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation. 

If this doesn't solve your issue please re-open.

**Comment by StevanWhite** [comment]
Hi, 

glad to hear you're on this!  We are eager to see the new release.

In fact, we puzzled over that note for some time, and came to no conclusion as to its meaning.  I would not have guessed that it meant the instructions in the page would not work at all for the current release.  I had started to write a second problem report regading the instructions in the page -- there are several sentences that aren't functioning as such.  But I ran out of time -- so let me just point out here that parts of the page make little sense to your users.

Cheers!

**Comment by matham** [comment]
Well, you should still be able to install kivy using the nightly releases even now. Only this single command `python -m pip install kivy` won't work until the release everything else on that page should currently work.

I would love to hear what is confusing on that page so that I can try to fix it.

**Comment by StevanWhite** [comment]
Hi matham,

I looked for a way to contact you directly, as this doesn't seem to me to be the place for the comments that followed.  But you asked, so I'll answer here.

About the language on the page.  I will do my best to explain the problem.  But from the style of the writing, I think the author of the page may well just not "get it".  In any case, please don't get me wrong.  I mean well.

There are several passages whose intended meaning I can only guess.  I don't have the time for the necessary detective work. The problem is not one of English per se -- it is one of clarity of references, and of keeping the audience in mind.  That is, explaining what the terms in the sentence refer to, and addressing the purposes of the audience at a reasonable level of understanding.

"This page represents instructions for wheels starting with 1.9.1. Until 1.9.1 is released the nightly wheels have to be used because stable kivy wheels have not been uploaded to pypi yet."

First, who is the audience?  Kivy developers?  The author?  Or a person who has never seen Kivy, but has maybe some background with Python?  Or a non-developer looking for a cross platform development solution?

The non-developer probably shouldn't be bothering with this page.  And the page is of limited use to Kivy develpers.  That leaves Python developers who may have little knowledge of Kivy or of wheel (pip is pretty well known in that community though).

Now, what is 1.9.1? Reading farther in the page, it appears 1.9.1 refers to a Kivy version.  Well OK.
The second sentence could be parsed in several ways. It's unclear whether wheels can be used with the stable version or not, and regarding the development release it's completely unclear.
What is a nightly wheel, and how does the reader use them?  This is not explained.  I looked for them in the tarball... nope.

As to the status of the rest of the page, the reader is still unsure.  Does that mean nothing in the page applies to the latest stable version of Kivy?  And if not, how should the reader proceed?

"When hosted on pypi one installs a wheel using pip, e.g. python -m pip install kivy. When downloading and installing a wheel directly, python -m pip install wheel_file_name is used, such as:
python -m pip install C:\Kivy-1.9.1.dev-cp27-none-win_amd64.whl"

Regarding the phrase "When hosted on pypi one..."
Is it already hosted on pypi?  Or am I suppose to host it? 
I have no idea where to get anything like C:\Kivy-1.9.1.dev-cp27-none-win_amd64.whl.
I don't see any whl file in the kivy tarball...

============================================
By the way, there were several other problems getting this up and running.

Same page, under "Installation 2".
It shows a python command as two lines.  As is, it doesn't work.  It should be on one line, or else two python lines:

python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
python -m pip install kivy.deps.gstreamer --allow-external kivy.deps.gstreamer

It wasn't immediately clear how to install Cython.  One might guess
        python -m pip install cython
but evidently, an older version is required.  So I uninstalled that and installed
        pip install -I Cython==0.21.2

Even installing buildozer didn't proceed without substantial guesswork.  I had to guess about several extra packages and install them by hand.  I can do this; not all your potential users can.  Many more simply won't have time.

I reccomend to make a virtual machine with some recent Linux distro (make a copy of it), and carefully note what steps are required to correctly install your software.

In order for this product to compete, your instructions should be *very* easy to follow, and always *exactly right*.  Practically, this is just as important as making the product work in your test environment.

Cheers!
