### ISSUE TITLE
python3-kivy not working but python-kivy works flawless on ubuntu 15.04

### ISSUE THREAD

**Issue by MoritzImendoerffer** [kivy/kivy#3852]
I used a minimal example:

    import kivy
    from kivy.app import App
    from kivy.uix.button import Button

    class TestApp(App):
    
        def build(self):
            return Button(text='hallo')
    
    if __name__ == '__main__':
        TestApp().run()

and it works well with python 2.7 but not with python 3 (latest stable version). The debug output: https://gist.github.com/MoritzImendoerffer/e4c3fa0f027714e8a9b4

Any ideas what could cause this issue ?

**Comment by MoritzImendoerffer** [comment]
It is maybe related to the issue 3225

**Comment by dessant** [comment]
Could you also try with the nighly py3 build? Please follow the instructions from here http://kivy.org/docs/installation/installation-linux.html.

**Comment by dessant** [comment]
I think the cause is this https://github.com/kivy/kivy/issues/3777.

**Comment by dessant** [comment]
Or maybe not, that should cause problems at installation time.

**Comment by MoritzImendoerffer** [comment]
Yep, the daily build works fine

**Comment by dilantha111** [comment]
Hi I am having the same issue. I am kinda new to kivy. And I have followed the instructions on http://kivy.org/docs/installation/installation-linux.html. And I am on linux mint
