### ISSUE TITLE
Unable to remove widget from GridLayout

### ISSUE THREAD

**Issue by mri3iguns** [kivy/kivy#3854]
While trying to remove a widget from my GridLayout I receive an error:

     Traceback (most recent call last):
       File "charge.py", line 121, in <module>
         ChargeApp().run()
       File "C:\Kivy\kivy27\kivy\app.py", line 824, in run
         runTouchApp()
       File "C:\Kivy\kivy27\kivy\base.py", line 487, in runTouchApp
         EventLoop.window.mainloop()
       File "C:\Kivy\kivy27\kivy\core\window\window_sdl2.py", line 525, in mainloop
         self._mainloop()
       File "C:\Kivy\kivy27\kivy\core\window\window_sdl2.py", line 290, in _mainloop

         EventLoop.idle()
       File "C:\Kivy\kivy27\kivy\base.py", line 327, in idle
         Clock.tick()
       File "C:\Kivy\kivy27\kivy\clock.py", line 483, in tick
         self._process_events()
       File "C:\Kivy\kivy27\kivy\clock.py", line 615, in _process_events
         event.tick(self._last_tick, remove)
       File "C:\Kivy\kivy27\kivy\clock.py", line 374, in tick
         ret = callback(self._dt)
       File "charge.py", line 88, in remove
         self.remove_widget(self.hb)
       File "C:\Kivy\kivy27\kivy\uix\layout.py", line 87, in remove_widget
         return super(Layout, self).remove_widget(widget)
       File "C:\Kivy\kivy27\kivy\uix\widget.py", line 500, in remove_widget
         if widget not in self.children:
     NameError: global name 'widget' is not defined

kv file:

    <BackDrop>:
        cl: cl
        batt: batt
        ncl: ncl
        hb: hb
        cp: cp

        spacing: [0,10]

        rows: 4
        ChargeLabel:
            id:cl
        BatteryImage:
            id:batt

        NoChargerLabel:
            id: ncl
        HeartBeatImage:
            id:hb

        ChargePercent:
            id: cp

    <ChargeLabel>:
        texture_size: root.width, root.height

        pos_hint: ({'top':.5, 'right':.5})
        size_hint: (1, .33)
        text: 'No phone connected'

    <BatteryImage>:
        source: 'no_device.png'
        pos_hint: ({'top':.5, 'right':.5})
        anim_delay: .45

    <ChargePercent>:
        texture_size: root.width, root.height
        size_hint: (1, .33)

        pos_hint: ({'top':.5, 'right':.5})
        text: '.........'

    <HeartBeatImage>:
        source: 'hb.zip'
        pos_hint: ({'top':.5, 'right':.5})
        size_hint: (1, .33)
        anim_delay: .1

    <NoChargerLabel>
        texture_size: root.width, root.height

        pos_hint: ({'top':.5, 'right':.5})
        size_hint: (1, .33)
        text: 'No charger detected'

    class i call remove_widget from:

    class BackDrop(GridLayout):

        cl = ObjectProperty()
        batt = ObjectProperty()
        ncl = ObjectProperty()
        hb = ObjectProperty()
        cp = ObjectProperty()

        def __init__(self, *args, **kwargs):
            super(BackDrop, self).__init__(*args, **kwargs)
            #Clock.schedule_once(self.start_detect, .3)
            Clock.schedule_once(self.remove, 3)
            print self.cl

        def remove(self, b):

            self.remove_widget(self.hb)  <----Problem
            self.remove_widget(self.cp)

from widget.py:

    def remove_widget(*args, **kwargs):
            '''Remove a widget from the children of this widget.

            :Parameters:
                `widget`: :class:`Widget`
                    Widget to remove from our children list.

        .. code-block:: python

            >>> from kivy.uix.button import Button
            >>> root = Widget()
            >>> button = Button()
            >>> root.add_widget(button)
            >>> root.remove_widget(button)
            '''
            if widget not in self.children:
                return
            self.children.remove(widget)
            if widget.canvas in self.canvas.children:
                self.canvas.remove(widget.canvas)
            elif widget.canvas in self.canvas.after.children:
                self.canvas.after.remove(widget.canvas)
            elif widget.canvas in self.canvas.before.children:
                self.canvas.before.remove(widget.canvas)
            widget.parent = None

**Comment by inclement** [comment]
This does not appear to be broken in the [master branch](https://github.com/kivy/kivy/blob/master/kivy/uix/widget.py#L535). If you have an old version of kivy, make sure it is up to date.
