### ISSUE TITLE
ButtonBehavior.MIN_STATE_TIME doesn't work on master

### ISSUE THREAD

**Issue by tito** [kivy/kivy#3861]
As per #3859, i understand MIN_STATE_TIME can be deprecated. But the current deprecation just doesn't work at all, and so break existing code.

At least, the new property `min_state_time` as the PR showed is ok, but use the previous MIN_STATE_TIME const as the default value, and mark it as deprecated if you want. Also, is this is now deprecated, is the new way to change is `ButtonBehavior.min_state_time.defaultvalue = xxx` ?

Don't break code in minor version please :(

**Comment by tshirtman** [comment]
Damn, i did a simple example to test locally, i guess i wasn't aware enough of the actual use of it.

**Comment by tshirtman** [comment]
I'm not sure how ff178501c2744613bdb1327e927f9f759f630bc8can fix the issue, the class-level value will be overwrote by the AliasProperty, since it's in the same namespace (the class…) no?

**Comment by tshirtman** [comment]
should be resolved for real as of 23215074f87749dcd0f586868e65fe110a297320

**Comment by tito** [comment]
Nop :(

I guess my suggestion is not a real one too. Look at the current code:
```
    MIN_STATE_TIME = 0.035
    '''The minimum period of time which the widget must remain in the
    `'down'` state.
    ..warning::
        This is deprecated, and will be removed in the next major release.
        Use :attr:`min_state_time` instead.
    :attr:`MIN_STATE_TIME` is a float and defaults to 0.035.'''

    min_state_time = NumericProperty(MIN_STATE_TIME)
    '''The minimum period of time which the widget must remain in the
    `'down'` state.
```

By the time we do ButtonBehavior.MIN_STATE_TIME, it's already too late, as min_state_time will not be changed :(

**Comment by akshayaurora** [comment]
@tito, we set Button_instance.min_state_time = self.MIN_STATE_TIME in __init__ just before super.

This allows me to have the following example working ::

    BoxLayout
        Button
            on_release:
                But = self.__class__
                But.MIN_STATE_TIME=2
                but = But()
                but.min_state_time=.5
                root.add_widget(but)

The behavior we have right now is initial Button on screen is normal but by the time release is called it's MIN_STATE_TIME is set to 2 so it stays down for 2 seconds, however new buttons added by the existing button with the min_state_time set to .5 stay down only for .5 seconds. Is this not the behavior we desire?

**Comment by akshayaurora** [comment]
Update: self.min_state_time = kwargs.get('min_state_time', self.MIN_STATE_TIME) in __init__ 

Now all the following situations work

setting Button.MIN_STATE_TIME at start of app leads to every button using the said time unless you
set Button(min_state_time=time) in which case this new time is used for that instance.
button_instance.min_state_time = time also work for that individual button

If you set Button.MIN_STATE_TIME in between your code after app start then any new button that does not set it's `min_state_time` uses this new MIN_STATE_TIME.

This essentially covers all the use cases.

**Comment by dessant** [comment]
I can confirm that it works properly now.
