### ISSUE TITLE
TextInput is unusable in Gingerbread

### ISSUE THREAD

**Issue by embryo10** [kivy/kivy#3862]
This is a copy of my [post at Google Groups](https://groups.google.com/forum/#!topic/kivy-users/8U6V3dV0toI).
Python 2.7.10 / kivy 1.9.0

 I'm building an app for android/desktop and I have a problem with TextInput widget.
 I have to support Android 2.3.x and TextInput is acting really strange on that version.
![screenshot](https://cloud.githubusercontent.com/assets/8684739/11963146/82b10954-a8ed-11e5-8587-84566862b861.png)

 As you can see at the attached picture, the width of the letters is randomly varied.
 The cursor is at the last character of the last line (I can erase it and check it) but the letters (their image) is way more left.
 If I add more characters they're starting to get bigger, until at a random number they are shrink back.

 Its almost impossible to edit anything, because the letters are never where the cursor seems to be.
 This is the only thing that is not working properly on version 2.3.x.
 After Android 4.x and on desktop everything is working OK.

 Any ideas for a workaround?
TIA

**Comment by embryo10** [comment]
The problem still exists with kivy 1.10.0

**Comment by Julian-O** [comment]
Android 2.3 is no longer supported by Google. Closing as stale.
