### ISSUE TITLE
TextInput focus problem

### ISSUE THREAD

**Issue by embryo10** [kivy/kivy#3863]
This is a copy of my [post at Google Groups](https://groups.google.com/forum/#!topic/kivy-users/DMQ1F2Vtj-A).
Python 2.7.10 / kivy 1.9.0
In this code:

``` python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.popup import Popup
from kivy.uix.textinput import TextInput
from kivy.lang import Builder

Builder.load_string('''
<Base>:
    Button:
        text: 'Press for Popup'
        on_press: root.edit_text()

<TextInputX>
    focus: True
''')


class Base(BoxLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)

    def edit_text(self, *args):
        self.clear_widgets()
        content = TextInputX()
        # content.focus = True
        popup = Popup(content=content)
        popup.open()


class TextInputX(TextInput):
    def __init__(self, **kwargs):
        super(TextInputX, self).__init__(**kwargs)
        # self.focus = True


class SampleApp(App):
    def build(self):
        return Base()


if __name__ == '__main__':
    SampleApp().run()
```

when the popup with the TextInput opens, its impossible to type.

 If you erase the "focus: True" from the kv part you can write, but you lose focus when the popup opens.
 If you uncomment either of the "content.focus = True" or "self.focus = True" from the py side, nothing happens.
 They act as "focus = False"
 And of course, if you put "focus: False" in the kv part, it works as expected (no focus).

 So does anybody knows of a way to set the focus AND be able to type?
TIA

**Comment by Zen-CODE** [comment]
Can confirm this is an issue. focus looks a bit broken and sees to be related to timings. If changing the focus is a delayed via a clock schedule, it works. But it needs to be longish. 0.1 did not work for me - it needed to be bigger...

from kivy.app import App
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.popup import Popup
    from kivy.uix.textinput import TextInput
    from kivy.lang import Builder
    from kivy.clock import Clock
    
    
    Builder.load_string('''
    <Base>:
        Button:
            text: 'Press for Popup'
            on_press: root.edit_text()
    ''')
    
    
    class Base(BoxLayout):
        def __init__(self, **kwargs):
            super(Base, self).__init__(**kwargs)
    
        def edit_text(self, *args):
            self.clear_widgets()
            content = TextInputX()
            popup = Popup(content=content)
            popup.open()
    
    
    class TextInputX(TextInput):
        def __init__(self, **kwargs):
            super(TextInputX, self).__init__(**kwargs)
            def set_focus(dt):
                self.focus = True
            Clock.schedule_once(set_focus, 1)
    
    
    class SampleApp(App):
        def build(self):
            return Base()
    
    
    if __name__ == '__main__':
        SampleApp().run()

**Comment by akshayaurora** [comment]
Setting focus when app the widget is not focusable simply does not work. It
should not either, you have to focus the widget when the widget comes on
screen and is focusable.

i.e under your popup:

<MyPopup>
    on_parent: if args[1]: ti_popup.focus = True
    TextInput
        id: ti_popup

or in python you can do::

    mypopup.bind(on_parent=self.on_popup_parent)
    mypopup.open()

    def on_popup_parent(self, popup, parent):
        if parent: popup.content.focus = True

**Comment by Zen-CODE** [comment]
The 'on_parent' event does not fire for me. But the 'on_open' works.

    def edit_text(self, *args):
        self.clear_widgets()
        content = TextInputX()
        popup = Popup(content=content)
        popup.bind(on_open=self.on_popup_parent)
        popup.open()

    def on_popup_parent(self, popup):
        if popup:
            popup.content.focus = True

The 'on_parent' does work for normal widget displaying however (not in a popup).

    from kivy.app import App
    from kivy.uix.textinput import TextInput
    from kivy.lang import Builder
    
    
    Builder.load_string('''
    <Base>:
        Button:
            text: 'Press for Popup'
            on_press: root.edit_text()
    
    <TextInputX>:
        on_parent: if args[1]: self.focus = True
    
    ''')
    
    
    class TextInputX(TextInput):
        pass
    
    
    class SampleApp(App):
        def build(self):
            return TextInputX()
    
    
    if __name__ == '__main__':
        SampleApp().run()

**Comment by akshayaurora** [comment]
Right,  for popup on_open should be used.

**Comment by dessant** [comment]
Setting the focus could work as an 'intent', activating if/when the widget becomes visible, and always the last widget setting that intent would gain focus. On the other hand, we would also need a way to know for sure, when is a widget focusable, currently it seems to be guesswork.

**Comment by akshayaurora** [comment]
You can not know when a widget is supposed to get focus/visible, simply
cause the user could design his UI in a number of ways, popup below popup?
wait I just want to make my widget that is behind a transparent widget
focused or I want my invisible widget to get focused...many diff use cases.

Currently widget's ignore focused state if they are not in widget tree,
that is the only limitation, I think asking users to focus widgets based on
widget events like on_parent etc is not that big a ask.

It's always better to let the user specify explicitly, you should not make
things super easy for the noob dev at the expense of making it super
difficult for every one else who want's to control things the way they want.

**Comment by dessant** [comment]
Ah, so technically, a widget becomes focusable when it gets added to the window's widget tree?

**Comment by dessant** [comment]
@matham, isn't there an event in your kv pr that gets fired when a widget lands in the main widget tree?

We can check if we are in the main root when the user sets the focus property, and if not, listen to that event.

**Comment by Zen-CODE** [comment]
It seems that this issue, and a lot of issues that arise from not always
having kv objects available in the __init__, might be solved if we has an
"on_kv_loaded" or "on_build_complete" event. This would fire only after all
kv has been loaded and all objects fully constructed? Effectively just
before returning to the event loop?

**Comment by tito** [comment]
There is an easy event, but wont help you that much. Think about this case: you have a CustomButton and a CustomPanel which have thoses kv associated:
```
<CustomButton>:
    font_size: "12dp"

<CustomPanel>:
    BoxLayout:
        CustomButton:
            text: "hello"
        CustomButton:
            text: "world"
```

If we have a such `on_kv_loaded`, then you have to ask what your "fire after all kv has been loaded and all objects fully constructed" mean.

When a CustomLayout is instanciated, the order of call would be
- CustomButton on_kv_loaded
- CustomButton (the second) on_kv_loaded
- CustomLayout (the final) on_kv_loaded

Even after everything applied for a subtree (CustomButton), the parent might still change attribute on the widget itself, even from the on_kv_loaded itself. If the purpose is to know when the widget is "done" building, i would say this event is not sufficiant by itself, cause it can extend the build process, and you don't know what the caller is going to do with your widget exactly.

Also, the issue here is when the widget is connected to a tree from the Window. This is a completly different issue. Even if the widget is fully build and nothing will change, and connected to a parent, that doesn't mean it's connected to Window itself, or displayed. It could either be in a Screen for example. So focus wont work at all.

My point of view is nor on_kv_loaded or on_parent can fully resolve this focus issue. HTML5 introduced an attribute named "autofocus" on the input element. If we have a such attribute (not focus, cause focus is on-the-fly), we could say "as soon as the widget is connected to displayed tree, it will be focused".

And now that ends up to know when the widget is connected to Window tree or not. I wonder how much would be the cost to check autofocus attribute in the widget tree when it change. (that check could be trigger when a widget is added to another one, just need to find a good traversal algo that minimize the time)

**Comment by Zen-CODE** [comment]
We could avoid those by making it at Builder (or similar object) level event. This would remove the kv processing ordering/firing issue?

    Builder.bind(on_kv_loaded=...)

**Comment by janssen** [comment]
Seems as if it would be a good idea to throw an error if "focus=True" is passed to the TextInput constructor and "parent=..." is not.  I think that would remove a lot of this confusion.

**Comment by Zen-CODE** [comment]
That might end up breaking quite a few apps. But the idea is good. Perhaps a logger warning might be a good option?

**Comment by janssen** [comment]
Yes, the warning would help.  I wonder if adding a new event would help?  Right now, on_parent doesn't always work, because the parent you're adding the TextInput to might not be in the Window tree yet.  That's why on_open is necessary for the Popup.  But this problem arises with other kinds of widgets, too.  If we had an event like "on_root_window", which would notify all the widgets in the whole tree that they are attached to the window system, we could always use that.

**Comment by kuzeyron** [comment]
This thread seems to still be opened. Lets close it.
Took me a long time to find the fix for solving the focus issue.
Here is the place in the documentation for solving it: [Focus Behavior](https://kivy.org/docs/api-kivy.uix.behaviors.focus.html)

**Comment by embryo10** [comment]
Well, changing the original code to:
```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.popup import Popup
from kivy.uix.textinput import TextInput
from kivy.lang import Builder

Builder.load_string('''
<Base>:
    Button:
        text: 'Press for Popup'
        on_press: root.edit_text()

<TextInputX>
    # focus: True
''')


class Base(BoxLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)

    def edit_text(self, *args):
        self.clear_widgets()
        content = TextInputX()
        # content.focus = True
        popup = Popup(content=content)
        popup.open()


class TextInputX(TextInput):
    def __init__(self, **kwargs):
        super(TextInputX, self).__init__(**kwargs)
        # self.focus = True

    def on_open(self, widget, parent):
        self.focus = True


class SampleApp(App):
    def build(self):
        return Base()


if __name__ == '__main__':
    SampleApp().run()
```
did not change anything.
I can not type in the TextInput.
Using on_parent didn't fix it also.
So how do you do it?
(Using kivy 1.10.0 now)

**Comment by kuzeyron** [comment]
Like this:
`  MDTextField:
            id: txt_send
            hint_text: 'What would you like to say?'
            helper_text: 'Say: Hello!'
            min_text_length: 5
            pos_hint: {'center_y': 0}
            multiline: False
            keyboard_mode: 'managed'
            is_focusable: True
            on_text_validate:
                if(len(txt_send.text) > 0): root.insert(txt_send.text);txt_send.text = '';txt_send.focus = True;txt_send.text_validate_unfocus = False
            on_touch_down:
                txt_send.focus = True
                txt_send.show_keyboard()`

**Comment by kuzeyron** [comment]
Like this: [PasteBin link](https://pastebin.com/y20EFr61)

**Comment by embryo10** [comment]
Can you make the original code work?
Your code is not runnable...

**Comment by kuzeyron** [comment]
I'm using KivyMD so I'll convert it for you into TextInput().
`
TextInput:
    id: txt_send
    multiline: False
    keyboard_mode: 'managed'
    is_focusable: True
    on_text_validate:
        txt_send.focus = True
    on_touch_down:
        txt_send.focus = True
        txt_send.show_keyboard()
`
As a note: This is also the workaround for Android keyboards.

**Comment by embryo10** [comment]
I replaced the TextInputX with yours:
```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.popup import Popup
from kivy.uix.textinput import TextInput
from kivy.lang import Builder

Builder.load_string('''
<Base>:
    Button:
        text: 'Press for Popup'
        on_press: root.edit_text()
        
<TextInputX>:
    id: txt_send
    multiline: False
    keyboard_mode: 'managed'
    is_focusable: True
    on_text_validate:
        txt_send.focus = True
    on_touch_down:
        txt_send.focus = True
        txt_send.show_keyboard()

# <TextInputX>
#     # focus: True
''')


class Base(BoxLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)

    def edit_text(self, *args):
        self.clear_widgets()
        content = TextInputX()
        # content.focus = True
        popup = Popup(content=content)
        popup.open()


class TextInputX(TextInput):
    def __init__(self, **kwargs):
        super(TextInputX, self).__init__(**kwargs)
        # self.focus = True

    # def on_open(self, widget, parent):
    #     self.focus = True


class SampleApp(App):
    def build(self):
        return Base()


if __name__ == '__main__':
    SampleApp().run()
```
but still doesn't work.
Maybe I don't understand you.
Can you please post a piece of code that executes?
Use 3 ` (backticks) and a new line _before_ your code and a new line and another 3 _after_ it.

**Comment by kuzeyron** [comment]
The key ingredient is keyboard_mode: 'managed'.
To me, it fixes my textinputs so it stays focused when I'm typing + hitting Enter and so on.
You might need to add this as well:
Config.set('kivy', 'keyboard_mode', 'managed')
Config.write()

**Comment by embryo10** [comment]
The bug has to do with something else (I think).
When you open a popup with a TextInput you can't set it to _automatically_ get the focus.
If you make it focused, you can't type in it.
That is the problem.
Did you solve _that_ problem somehow?

**Comment by kuzeyron** [comment]
Yes, it solves even that part.
When it's focused. you need:
   on_touch_down: txt_send.show_keyboard()
But that is only working when you have set the: keyboard_mode: 'managed'
It's all there in the documentation.

**Comment by embryo10** [comment]
You don't understand.
Not when _you press_ in it
Automatically, **_before_** you press in it!
It must have the focus before you press in it.

**Comment by kuzeyron** [comment]
Leave focus: True out of the InputText. It's still focused with my example.

**Comment by embryo10** [comment]
Well, I have and its not.
Can you please post a piece of code that can be executed and shows a solution.
As I said, I replaced the TextInput of the original code with yours.
It does not have focus: True
It does not work.

**Comment by kuzeyron** [comment]
This method works in Linux Mint and Android 8.1.
It's only Android keyboard I need to fix so it relaunch after clicking on the textinput.
Link to my entire project: [Google Drive](https://drive.google.com/open?id=1EkJ_NLcuoKtslBiCDz-zd9CaX2tUK5hy)

I haven't set focus: True because it messes up everything. But it's still focused when you type.
git+https://gitlab.com/amadeusxnet/KivyMD.git you need in the requirements if you want to try my code. I have modified the KivyMD so that's why you need that link instead.

Let's hope you'll get your solved as well.

**Comment by embryo10** [comment]
You do understand that there was no mention of "Android keyboard" problem in the original bug and that we lost all that time for nothing...
Anyway, thanks for trying...

**Comment by kuzeyron** [comment]
Happy? [PasteBin](https://pastebin.com/F0pMqK8L)

**Comment by embryo10** [comment]
Yeah!!!
Although the problem solver seems to be the call to `show_keyboard` even on a PC that has no virtual keyboard.
I don't thing that this is a solution but more something of a workaround.
Still, great work! I can certainly use this...

**Comment by kuzeyron** [comment]
I've been running through Kivy's source code a few times. And it looks like show_keyboard is set for everything. Like it checks for environment to use.

But I'm glad you can find this useful.
Problem solved? :+1:

**Comment by embryo10** [comment]
My personal problem, yes but kivy's no.
I think it would be better to leave this open until a more intuitive solution is added to the library itself.
Like setting the focus to True and TextInput take the focus (and still be capable to type in it)
Its really hard to expect from developers to find about this approach (working without virtual keyboard and all)
Only if someone read this here... ;o)

**Comment by kuzeyron** [comment]
You'll probably need to use ID for enabling/disabling the focus. As of with my project, I have to find a way to do those things. Making support for anything else than just one device can be tricky!

**Comment by Matteljay** [comment]
Setting **unfocus_on_touch** to **False** is your friend when dealing with TextInputs.
```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.popup import Popup
from kivy.uix.textinput import TextInput
from kivy.lang import Builder

Builder.load_string('''
<Base>:
    Button:
        text: 'Press for Popup'
        on_press: root.edit_text()
''')

class Base(BoxLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)
    def edit_text(self, *args):
        self.clear_widgets()
        content = TextInputX()
        content.unfocus_on_touch = False
        content.focus = True
        popup = Popup(content=content)
        popup.open()

class TextInputX(TextInput):
    def __init__(self, **kwargs):
        super(TextInputX, self).__init__(**kwargs)
        # self.focus = True

class SampleApp(App):
    def build(self):
        return Base()

if __name__ == '__main__':
    SampleApp().run()
```

**Comment by toniree** [comment]
> from kivy.uix.popup import Popup

Hi @Matteljay I tried your Sample code as is, and with `self.focus = True` uncommented as well, but the Keyboard does not show despite touching anywhere on screen after popup. Running Kivy V 2.0. Has there been breaking changes since time of writing?

**Comment by Zen-CODE** [comment]
@toniree There are many ways to solve this problem. The below, simplified code works in Kivy V2.

If you still have issues, rather than posting on an old ticket, please create a fresh ticket with all your version details, code and logs. Thanks 
```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.popup import Popup
from kivy.uix.textinput import TextInput
from kivy.lang import Builder

Builder.load_string('''
<Base>:
    Button:
        text: 'Press for Popup'
        on_release: root.edit_text()
''')


class Base(BoxLayout):
    def edit_text(self, *args):
        content = TextInputX()
        popup = Popup(content=content)
        popup.open()


class TextInputX(TextInput):
    def on_parent(self, widget, value):
        self.focus = True


class SampleApp(App):
    def build(self):
        return Base()

if __name__ == '__main__':
    SampleApp().run()
```
