### ISSUE TITLE
app not launching on mac osx yosemite

### ISSUE THREAD

**Issue by 0x410c** [kivy/kivy#3869]
kivy is not launching on my mac book air yosemite,

logs says:
Kivy[2267]: App did finish launching

but no gui,

and also python interpreter is opening fine on terminal.

Yes i am using the latest build, downloaded from the download page.

Thanks

**Comment by akshayaurora** [comment]
Launching Kivy.app is supposed to do nothing.

To run your app you have to either run it from the terminal using `kivy main.py` or drop your main.py onto the kivy icon from /Applications.
