### ISSUE TITLE
"Guide asking for help section needs to move to kivy's website from wiki"

### ISSUE THREAD

**Issue by bearnun** [kivy/kivy#3873]
Make asking-for-help guide ([community guidelines](https://github.com/kivy/kivy/wiki/Community-Guidelines)) more visible on Kivy's main site and the in places where Kivy advertises its freenode chat-room and contact information, etc.

**Comment by bearnun** [comment]
Also, "Community Guidelines" feels like a misleading name here.  I would not have necessarily guessed the sub-sections would be "Asking for Help" and "Conversation Guidelines."

**Comment by dessant** [comment]
The guidelines are linked from https://kivy.org/docs/contact.html.
