### ISSUE TITLE
Application crashes if the source exists

### ISSUE THREAD

**Issue by Silveryard** [kivy/kivy#3875]
Hey guys,
 
I am trying to load a image at runtime to display it as a background.
But now I came across a strange problem: If the path is incorrect (or the image does not exist) the application just goes on without loading the image or an error message. If the image exists in the provided source path, the application just crashes again without an error message.

My Code:
    childWidget = Image()
    childWidget.source = FileIO.sysdata_directory() + "/launcher/background.png"
    childWidget.allow_stretch = True

My log file (when image does not exist):
    [INFO              ] Logger: Record log in /home/beppo/.kivy/logs/kivy_15-12-28_74.txt
    [INFO              ] Kivy: v1.9.1-dev
    [INFO              ] Python: v3.4.3+ (default, Oct 14 2015, 16:03:50) 
    [GCC 5.2.1 20151010]
    [INFO              ] Factory: 179 symbols loaded
    [INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer     ignored)
    [INFO              ] VideoGstplayer: Using Gstreamer 1.6.0.0
    [INFO              ] Video: Provider: gstplayer
    [INFO              ] Text: Provider: sdl2
    [INFO              ] OSC: using <multiprocessing> for socket
    [INFO              ] Window: Provider: sdl2(['window_egl_rpi'] ignored)
    [INFO              ] GL: OpenGL version <b'4.5.0 NVIDIA 352.63'>
    [INFO              ] GL: OpenGL vendor <b'NVIDIA Corporation'>
    [INFO              ] GL: OpenGL renderer <b'GeForce GT 750M/PCIe/SSE2'>
    [INFO              ] GL: OpenGL parsed version: 4, 5
    [INFO              ] GL: Shading version <b'4.50 NVIDIA'>
    [INFO              ] GL: Texture max size <16384>
    [INFO              ] GL: Texture max units <32>
    [INFO              ] Window: auto add sdl2 input provider
    [INFO              ] Window: virtual keyboard not allowed, single mode, not docked

The image I try to load:
<img width="400" alt="background" src="https://cloud.githubusercontent.com/assets/6696853/12019497/3282bd50-ad71-11e5-890e-acab02813638.png">

I ensured to be on Thread-1. Loading a Video earlier for startup and creating empty Images (solid color) works well. I am on python 3.4 with Ubuntu 15.04

**Comment by dessant** [comment]
Please share a runnable app example that reproduces the crash.

**Comment by Silveryard** [comment]
Realized setting a images source on another than the main thread is not supported. Fixed it by scheduling a event that loads the image on the main thread
