### ISSUE TITLE
The app crashes on the device after entering a smiley

### ISSUE THREAD

**Issue by Pymancer** [kivy/kivy#3879]
kivy.version = '1.9.0'
Buildozer OS: Lubuntu 14.04
Device: Digma iDn7
Android version: 4.0.4
Keyboard: Android keyboard 4.0.4-eng.android.1348285053, keyboard sample:
![android_keyboard](https://cloud.githubusercontent.com/assets/9929526/12026285/e25f5826-adc8-11e5-94f3-a4c610aec424.png)

App crashes after trying to type ':-)' using 'smiley' key on keyboard (TextInput should be focused)

``` python
from kivy.base import runTouchApp
from kivy.lang import Builder

if __name__ == '__main__':
    runTouchApp(Builder.load_string("""
AnchorLayout:
    anchor_x: 'center'
    anchor_y: 'top'
    TextInput:
        size_hint: (0.8, 0.1)
"""))
```

seems like colon (':') delimeter related issue
log attached (buildozer log_level = 1): https://gist.github.com/Pymancer/f61a143f1d1d43e9bb8c#file-gistfile1-txt
textinput.py 2030-2035 lines:

``` python
            if _command and first_char == 2:
                from_undo = True
                _command, data = _command.split(':')
                self._command = ''
                if self._selection:
                    self.delete_selection()
```

**Comment by tshirtman** [comment]
A lot of time passed, i tried to reproduce and couldn't, the code in textinput changed a bit, but i'm not sure of the initial cause, it's entirely possible this was fixed in the sdl2 handling of keys in android, closing, if anybody encounters a similar issue, it's best to open a new issue referencing this one.
