### ISSUE TITLE
excessive Android internal storage use

### ISSUE THREAD

**Issue by StevanWhite** [kivy/kivy#3881]
Hi, we tested Kivy 1.9.0 here, and got a Hello World going in Linux, Windows, and Android.

However, after we run the Hello World once on Android, the App manager reports that it has taken over 18MB of internal storage (on top of its installation size).  This is very excessive -- it precludes the Kivy approach to our problem at this time.

Generally speaking, internal storage should be used for user input data -- settings and such.  There are other options for temporary storage or cache -- and according to the Android API guide these too should be carefully managed.

**Comment by inclement** [comment]
I just checked, and no apps on my device are behaving this way (and I didn't think this was the way things should behave).

python-for-android does have an option to unpack the app in the public dir (by which it means the external data dir), have you enabled this? If that's the case, you'd see e.g. your main.py in the external storage dir of the app (it crudely usess /sdcard/appname), and the fix would be to use the private storage setting.

**Comment by StevanWhite** [comment]
Hi Inclement,

I'm not referring to the size of the unpacked app.  The app itself can indeed be moved to external storage, and I have done that.  The unpacked app size is less of an issue, and I understand that Kivy apps have an overhead.

I am referring to the permanenet storage used by the app.  In the App Manager, the internal storage is labelled "Data".  This is the amount that is excessive in Kivy.

This storage should be used for user-entered data, such as passwords etc. and it should remain small.  For this Hello World, it really ought to be empty.

It should *not* be used as a cache.  There are several alternatives for caches.  (But caches too should be carefully managed.)

It is true that many apps, even ones made by big companies, badly misuse it.  But that's no excuse.

**Comment by inclement** [comment]
Okay, I see, sorry for misunderstanding. As far as I can tell, this data usage is from unpacking the APK into the directory specified by [`getFilesDir()`](http://developer.android.com/intl/zh-cn/reference/android/content/Context.html#getFilesDir%28%29). I thought this was the correct behaviour (given that we must unpack it to load python, and this seems to be the intended internal storage directory) - is there a different internal storage directory for such things, perhaps which doesn't count towards the data usage?

**Comment by StevanWhite** [comment]
Hi Alexander,

The usage you are describing would be better handled by other means...probably a temp file.

I have personally only used the internal storage (your getFilesDir()) and the cache storage.

The problem with internal storage is that it expends the limited fixed main storage on the device.  It can be deleted by the user, but then... they lose everything.  If it's only a few KB, it does't matter.  But MBs add up very quickly -- much to the annoyance of people who load lots of apps.
Another option is the Android Cache.  This also uses up internal storage, but it is explicitly for the purpose of caching-- only to avoid re-loading stuff in a later session, and which if deleted, at worst  requires a little time to automatically refill.

For the purpose you mention, I would recommend that you look into a temp file, which the app creates and then carefully deletes--so the user loses no storage when the app isn't running.  If it should persist, it would be nice to provide the option to put it on an external card.

Android Storage Options
https://developer.android.com/guide/topics/data/data-storage.html

The politics of the situation is this: I want to argue that Kivy would be a good option to writing native apps.  We have other develpers that are familiar with native app development.  I need to show that Kivy can be used to make cross-platform apps with a minimum of overhead.  Android internal storage is overhead -- they can say "we can make a native app for this that uses no internal storage (and starts up faster)".  So... if this were fixed, Kivy would be in a stronger position.

**Comment by inclement** [comment]
The problem with deleting the extracted files on close is that re-extracting them is noticeably slow - this is why Kivy's first run can take so much longer than later ones. I think this is actually much less of a problem on newer devices, but haven't done any timing.

Using the cache directory is possible and maybe preferable - the obvious problems would be keeping track of whether things must be re-extracted, but that shouldn't be too hard.

There's actually already a build option to extract python to the external storage and run it from there. No caching/deletion is involved (actually it doesn't get used much and I've been meaning to fix it up a bit), but if space is at a premium it may be useful.

On the politics side, the unfortunate reality is that we have no way to run python without this tradeoff between startup time and storage usage. However, I'm happy to think of adding some different extraction options, and I've opened a python-for-android issue at https://github.com/kivy/python-for-android/issues/606 for it. I'll close this one, as these issues are independent of Kivy.

**Comment by StevanWhite** [comment]
Hi Andrew,

Let me emphasize: the objection is not about the use of storage as a cache.  I'm all for caching.

The objection is to expending the Android internal storage for this purpose -- if they need space and delete this, they lose all other information, including typed passwords and other user input.  It is very good practice to distinguish between user input data and run-time expedients.
And for your 20mb extracted files... please don't even use the Android cache for this.  The cache uses up RAM, usually until the user manually deletes it.  Keep the Android cache small too, please.

Of course any professional programmer keeps track of any memory expended.  And as you say, it isn't hard.

It sounds to me like the best option would to put the extracted files on external storage (which is typically much more capacitous than main storage) whenever possible.

Thanks!

**Comment by inclement** [comment]
Like I said, we already have an option to extract to the external storage.
