### ISSUE TITLE
children not set in widget constructor

### ISSUE THREAD

**Issue by sdementen** [kivy/kivy#3882]
Using children as argument in a widget constructor does not initialise the children property of the widget.
It can be useful to call something with
`ListItemButton(text="ok", children=[SomeFancyIcon()])`
instead of 

```
lib = ListItemButton(text="ok")
lib.add_widget(SomeFancyIcon())
```

Adding a loop similar to 

```
for ch in kwargs.get("children",[]):
   self.add_widget(ch)
```

at the end of `Widget.__init__` seems to do the job.

If OK, I can do a PR.

**Comment by dessant** [comment]
Dunno if the feature is needed or not, but ListView deprecation will happen as soon as RecycleView is finished, you may not want to waste time on implementing new features for it.

If you would like to test and contribute to RecycleView, it is already usable: https://github.com/kivy-garden/garden.recycleview.

**Comment by sdementen** [comment]
I was using ListItemButton as an illustration (but I'll have a look at the RecycleView widget). My real case was with a KivyMD list. When passing a ```children=[SomeWidget()]``` in ```__init__```, the children property of the object is set to [SomeWidget()] but as mentioned in http://kivy.org/docs/api-kivy.uix.widget.html?highlight=clear_widget#kivy.uix.widget.Widget.children, this is not recommended. So it could be better to either a) throw an exception (or at least a warning) or b) add the widgets from children to the widget through a loop as described before.

**Comment by dessant** [comment]
Ah sorry, missed the essence :P. Adding a warning on direct list manipulation could be cumbersome because as you've seen, the same list is also modified by add_windget and remove_widget. I feel in this case the docs should be enough.

**Comment by dessant** [comment]
Although there could be an argument about explaining in the docs when it is appropriate to manipulate that list and mentioning an use case.

**Comment by sdementen** [comment]
I think the warning should just appear when children is set through the ```__init__``` call but I would rather have the option proposed in the first post. When there is a need to add a child (or more) to a Widget, it is currently not possible to do it in one line. For instance, the example
```
from kivy.uix.screenmanager import ScreenManager, Screen

# Create the manager
sm = ScreenManager()

# Add few screens
for i in range(4):
    screen = Screen(name='Title %d' % i)
    sm.add_widget(screen)
```
could be rewritten as
```
from kivy.uix.screenmanager import ScreenManager, Screen

# Create a manager with 4 children
sm = ScreenManager(children=[Screen(name='Title %d' % i) for i in range(4)])
```
but today this does not work correctly (and does not throw an error neither)

**Comment by bergus** [comment]
KivyMD has the [`DeclarativeBehavior` mixin](https://kivymd.readthedocs.io/en/latest/behaviors/declarative/) for just this. It uses the arguments list not a named `children` parameter, but it works the same
