### ISSUE TITLE
pep8checker script missing hashbang ?

### ISSUE THREAD

**Issue by udiboy1209** [kivy/kivy#3893]
I got this error after running `make hook` and then trying to commit.

    .git/hooks/pre-commit: 17: .git/hooks/pre-commit: 
        Kivy Git Pre-Commit Hook to Enforce Styleguide
        ==============================================

        This script is not supposed to be run directly.
        Instead, copy it to your kivy/.git/hooks/ directory, call it pre-commit
        and make it executable.

        If you attempt to commit, git will run this script, which in turn will run
        the styleguide checker over your code and abort the commit if there are any
        errors. If that happens, please fix & retry.

        To install::

        cp kivy/tools/pep8checker/pre-commit.githook .git/hooks/pre-commit
        chmod +x .git/hooks/pre-commit
    : not found
    .git/hooks/pre-commit: 19: .git/hooks/pre-commit: import: not found
        from: can't read /var/mail/os.path
        from: can't read /var/mail/subprocess
    .git/hooks/pre-commit: 23: .git/hooks/pre-commit: Syntax error: "(" unexpected

This is mostly because git does not know this is a python script and is running it using something else!(bash I guess)
When I opened the file and added a hashbang `#!/usr/bin/env python` everything worked fine.

Is this very easily solvable by a config in git? Or should there be a hashbang just in case

**Comment by yoelk** [comment]
Hi,
Can I ask you if you managed to solve this one?
I followed your advice and added the hashbang, but I still get an error:
`Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 33, in <module>
    import kivy
ImportError: No module named kivy
 (1)`

**Comment by udiboy1209** [comment]
@yoelk thats different from the error you would get if there was no hashbang. I guess your error is because you don't have kivy installed on your system. 

You should try installing and testing your change before you commit. Kivy has a pretty good Makefile so `make` and `make install` should do the job for you. But just in case check this out: https://kivy.org/docs/installation/installation.html#development-version

**Comment by yoelk** [comment]
Well, I have kivy installed, otherwise I couldn't have ran my programs at all.
I installed it according to [this(https://kivy.org/docs/installation/installation-osx.html)
It's just that when I commit, using "GitHub Desktop", I get this error.

Are you saying I must have the development version installed in order for pep8checker to work?

**Comment by udiboy1209** [comment]
@yoelk no any kind of kivy installation would do. I'm not an OS X user, so I'm not sure how to properly import kivy in different environments. You could ask someone on the IRC channel though, lots of OS X users there who will be able to help you.

**Comment by yoelk** [comment]
Thanks

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/commit/8644e4dc09a43846f75f0eaac7047c5c1311c890.
