### ISSUE TITLE
Running Kivy on Linux xfce (chromebook) yields only black screen

### ISSUE THREAD

**Issue by BRebecca** [kivy/kivy#3899]
somewhat new to Linux. Just set up a "dual boot" to XFCE ubuntu on my Chromebook. Installed Kivy and tried to set up the basic "Hello World" program.

Upon running the program from the terminal, I get either a black screen or a graphical glitch of whatever else is going on, on the desktop.

The terminal also displays a list of debug lines (I'm not used to this in Windows. Assuming this is standard.)

http://i.imgur.com/hQcHa4p.png?1  Here's what I'm looking at.

.py file

    from kivy.app import App

    class WeatherApp(App):
	    pass

    if __name__ == '__main__':
	    WeatherApp().run()

.kv file

    Label:
	   text: "Hello World!"

Called from terminal with

    python main.py

Am I doing something wrong?

**Comment by thopiekar** [comment]
Chromebook? Sounds like you are using Ubuntu armhf. Are you sure that your 3D driver works well? You can test it with ```glmark-es2```. 

Also relevant is the way you installed kivy and which version you are using :)

**Comment by janssen** [comment]
I've successfully run Kivy on Ubuntu 14.04 with XFCE4.

**Comment by thopiekar** [comment]
Also on a chromebook or another armhf based device?

**Comment by dessant** [comment]
The issue has been abandoned by OP, closing.
