### ISSUE TITLE
Alpha problem with circles

### ISSUE THREAD

**Issue by tealbrains** [kivy/kivy#3911]
If alpha < 1 in the color parameter, and the circle has a width > 1, a rectangle will be drawn with the right alpha instead of the circle (or arc). There are of course ways to get around, as for example drawing multiple 1px width circles but that is not ideal.

In the following pictures you can see what I mean. The first one has alpha < 1, the second one has alpha = 1. I might be missing something but it seems like a bug to me. Cheers!
![alphaproblem](https://cloud.githubusercontent.com/assets/7415425/12286617/cfc1a0cc-ba19-11e5-87b1-1dac46eeee7b.png)

![alphaproblem2](https://cloud.githubusercontent.com/assets/7415425/12286664/53569e1a-ba1a-11e5-9863-9df02128c307.png)

**Comment by Julian-O** [comment]
Given it has been almost 8 years with no-one else reporting this, I suspect it isn't an extant Kivy issue.

@tealbrains: Are you still seeing this issue? If so, can you provide a minimal program that fails and logs and information about what platform you are using?
