### ISSUE TITLE
Linux executable. pygame segmentation fault on ubuntu 14.04

### ISSUE THREAD

**Issue by ODiogoSilva** [kivy/kivy#3917]
I ran into an issue similar to #2034. I created an executable for my kivy 1.9.1 application in python 2.7 using PyInstaller 3.0 in arch linux. The executable runs fine in other arch-based distros but when I try to run it on a Ubuntu 14.04 using the latest nouveau drivers, I get: 

```
Fatal Python error: (pygame parachute) Segmentation Fault
Abortado (imagem do núcleo gravada)
```

However, if I replace the nouveau drivers with the proprietary nVidia drivers, the app runs. So it seems there's some issue between pygame and nouveau drivers? If so, this is a bit inconvenient, since I wouldn't like to ask users to activate proprietary graphic drivers just for the app.

I should also mention that the app starts by spawning a window, as suggested in the FAQ

```
from kivy.base import EventLoop
EventLoop.ensure_window()
```

**Comment by dessant** [comment]
The pygame providers were deprecated.
Have you tried with sdl2? Check the deps here: https://kivy.org/docs/installation/installation-linux.html#ubuntu-example.
Recompile kivy after the dependencies are installed, and make sure `USE_SDL2=1` is there at the start of the compilation log.

**Comment by ODiogoSilva** [comment]
So, I recompiled kivy after installing the equivalent sdl2 arch linux packages and the compilation log did show `* use_sdl2=1`. The app also runs successfully from source after the recompilation. However, using the new packaging instructions for kivy 1.9.1 and above:

```
from kivy.deps import sdl2, glew
```

yielded `ImportErrors`  for both sdl2 and glew. If I use pyinstaller with my previous spec file, which included:

```
from kivy.tools.packaging.pyinstaller_hooks import get_hooks
```

and `**get_hooks()` in `Analysis()`, PyInstaller seems to finish successfully, but when I try to run the executable in my system I get:

```
[CRITICAL] [App         ] Unable to get any Image provider, abort.
```

I'm guessing that I need to provide the sdl2 dependencies to PyInstaller, which should be accomplished with the new packaging instructions that I couldn't complete? I also tried all steps using kivy 1.9.1 and 1.9.2.

**Comment by ODiogoSilva** [comment]
I finally managed to create an executable of my app using SDL2 with pyinstaller 3.2 and kivy 1.9.2, but the original problem remains. The app successfully runs in my arch linux system and Ubuntu with proprietary graphics drivers (nvidia in this case), but crashes with a segmentation fault when I switch to the nouveau drivers in Ubuntu. The full log in Ubuntu:

```
[INFO   ] [Logger      ] Record log in /home/diogo/.kivy/logs/kivy_16-01-19_24.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.11 (default, Dec  6 2015, 15:43:46) 
[GCC 5.2.0]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.5.9>
[INFO   ] [GL          ] OpenGL vendor <nouveau>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on NVC1>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 /home/diogo/TriFusion/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
segmentation fault (core dumped)
```
However, the app runs successfully from source, even with the nouveau drivers.

**Comment by dessant** [comment]
Does it also happen with a sample app, without using mpl etc?

**Comment by ODiogoSilva** [comment]
Yes. I created an executable for the touchtracer app in examples/demo and got the same error.

```
[INFO   ] [Logger      ] Record log in /home/diogo/.kivy/logs/kivy_16-01-19_26.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.11 (default, Dec  6 2015, 15:43:46) 
[GCC 5.2.0]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.5.9>
[INFO   ] [GL          ] OpenGL vendor <nouveau>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on NVC1>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
segmentation fault (core dumped)
```

**Comment by ODiogoSilva** [comment]
Apparently, this was an issue of missing packages in Ubuntu. I had originally installed only the dependencies with SDL2 for ubuntu (https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2), but after installing the dependencies for the development version (https://kivy.org/docs/installation/installation.html#development-version), the executable was up and running. I'm marking this as closed since the original issue was solved, but I'm still puzzled as to why I cannot create a functional executable in Arch Linux (probably some packages that I'm missing..)
