### ISSUE TITLE
Label markup does not respect disabled_color alpha

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3920]
![capture11](https://cloud.githubusercontent.com/assets/7513068/12371770/b5c0b30e-bc47-11e5-872f-5425f3c2dd25.PNG)

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
<Lab@Label>:
    size_hint_y: None
    height: dp(200)
    font_size: dp(100)
    text: 'DIRTY MARKUP'
    color: 0.4, 0.4, 0.45, 1
    disabled_color: self.color
    disabled: True

BoxLayout:
    orientation: 'vertical'
    Lab:
        markup: True
    Lab:
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

**Comment by udiboy1209** [comment]
I wanna try fixing this! Any pointers on where to start looking @dessant ?

**Comment by dessant** [comment]
I think here https://github.com/kivy/kivy/blob/ab3c3fe52ce353d77e803f68b116c982f59aeef9/kivy/data/style.kv#L6.

**Comment by dessant** [comment]
I also had to fix it in order to answer your question. :stuck_out_tongue_closed_eyes: 
https://github.com/kivy/kivy/commit/1d783c9c93e5083ca4aa9bc2e3b3e5f78639e0cd

**Comment by udiboy1209** [comment]
Lol :stuck_out_tongue_closed_eyes:

**Comment by dessant** [comment]
@udiboy1209 it turns out that's not the right fix, and the issue also affects the color when the label is not disabled. If you're still into it, here is the new issue with an example to play with: https://github.com/kivy/kivy/issues/3959.
