### ISSUE TITLE
FileChooserListLayout doesn't look like in documentation

### ISSUE THREAD

**Issue by pyfrid** [kivy/kivy#3922]
In new kivy version all tree nodes  of FileChooserListLayout are located in the middle of widget. On desktop it doesn't look nice and also it looks different from screenshot in documentation. 

![screenshot from 2016-01-17 01 12 21](https://cloud.githubusercontent.com/assets/965931/12375197/96d894be-bcb7-11e5-97d7-2c83d8359d74.png)

**Comment by Zen-CODE** [comment]
This fix has been merged (see https://github.com/kivy/kivy/commit/1907f1bf4b36f9d1f87ab81630a9276f73fc37a9). It should take effect from 1.9.2 or 2.0, whichever comes first. Please re-open if not resolved on that release.
