### ISSUE TITLE
Garden (and any other binary?) isn't installed correctly

### ISSUE THREAD

**Issue by johanneshk** [kivy/kivy#3930]
Hi,

so upon

```
kivy -m pip install kivy-garden
```

the garden binary isn't available after activating the venv, s.t. the line 

```
source /Applications/Kivy.app/Contents/Resources/venv/bin/activate garden install mapview deactivate
```

does not work. I'm referring to https://kivy.org/docs/installation/installation-osx.html
And even after sym linking

```
ln -s /Applications/Kivy.app/Contents/Frameworks/python/3.5.0/bin/garden /Applications/Kivy.app/Contents/Resources/venv/bin/
```

I have to split that line:

```
source /Applications/Kivy.app/Contents/Resources/venv/bin/activate
garden install mapview
deactivate
```

Then it works.

Plus: Shouldn't everything in 

```
/Applications/Kivy.app/Contents/Frameworks/python/3.5.0/bin/
```

be available after activating the venv?

**Comment by dessant** [comment]
Please reopen the bug report if there are still issues with the latest release, try installing Kivy with pip: https://kivy.org/docs/installation/installation-osx.html.
