### ISSUE TITLE
Window.mouse_pos incorrect on 4k/retina displays

### ISSUE THREAD

**Issue by eranegozy** [kivy/kivy#3960]
The default Kivy window size is 800x600. However, when running on a high rez display (4k display, MacBookPro Retina Display), the default window size ends up 1600x1200. Fair enough.
But, when querying Window.mouse_pos, the returned value appears as if the window size were 800x600.

For example, this:

```
   def on_touch_down(self, touch):
      print touch.pos
      print Window.mouse_pos, '\n'

```

 will print out:

```
(1438.0, 1068.0)
(719.0, 534.0) 
```

**Comment by johanneshk** [comment]
@eranegozy this should solve it:
https://github.com/kivy/kivy/pull/4403/commits/3925930aeca89e1e1276f0e93ea38d338d498bcc
See also:
https://github.com/kivy/kivy/issues/4377

**Comment by hackalog** [comment]
This was likely fixed as part of #4403

Just tested on ios with
```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.label import Label
from kivy.core.window import Window

class TestLabel(Label):
    def on_touch_down(self, touch):
        self.touch_pos = touch.pos
        self.mouse_pos = Window.mouse_pos

kv = Builder.load_string("""
TestLabel:
    touch_pos: 0,0
    mouse_pos: 0,0
    text: '{} vs {}'.format(self.touch_pos, self.mouse_pos)
""")

class MousePosApp(App):
    def build(self):
        return kv

MousePosApp().run()
```
and it appears to work as expected

**Comment by dessant** [comment]
@hackalog, thanks for the test!

**Comment by KeyWeeUsr** [comment]
I'll look into adding a unittest later. (Note to myself:) It might be enough to just run Kivy with density env var and compare the values, something like this:

    os.environ[<density var>] = <value>  # setUp (maybe class one)
    <touch down>
    self.assertEqual(touch.pos, <calculated pos from 3925930 or more up-to-date change>)
    os.environ.pop(<density var>)  # tearDown

**Comment by eranegozy** [comment]
I can also confirm that this has been fixed. Thanks

-Eran (iPhone)
