### ISSUE TITLE
TextInput bubble actions can fail depending on widget positioning

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3961]
The bubble buttons will do nothing in the example below, but comment out BoxLayout `padding: '100dp'` and text selection and pasting from the bubble will work.

``` python
from kivy.app import App
from kivy.lang import Builder

kv = """
BoxLayout:
    padding: '100dp'
    TextInput:
        use_bubble: True
        text: 'long press to show the bubble, then click "Select All"'
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

**Comment by dessant** [comment]
It works with 1.8.0.

**Comment by udiboy1209** [comment]
Was fiddling around with this, found that bug only appears for large padding values. Works for small enough padding values like `10dp` or so.

**Comment by akshayaurora** [comment]
Cause is the change of always_release: from True to False

**Comment by dessant** [comment]
The button coordinates seem to be relative to the textinput, we could to the same transformation for the touch.

**Comment by saqib1707** [comment]
@dessant was trying to solve this using correct approach . Found out that even if the touch is transformed in textinput.py , there is no way to call the on_touch_up of button.py from textinput.py having touch.grab_current = bubblebutton object . https://github.com/kivy/kivy/blob/master/kivy/uix/behaviors/button.py#L162-L163 .The grabbed touch is dispatched to the on_touch_up of button.py but making transformation of touch in button.py doesn't seems reasonable I guess.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/issues/4844.
