### ISSUE TITLE
touchscreen does't work after installing kivy1.9.1 [$100]

### ISSUE THREAD

**Issue by hkoda** [kivy/kivy#3964]
Hi,
We tried to run the kivy script using ubuntu 15.10 with Xfce usb-connecting to touchscreen (model: Dell S2240T). Our script worked well in Kivy ver.1.9.0, but we need to hide cursor. So we manually  downloaded and installed kivy 1.9.1 (using setup.py) from download page. After the install of ver.1.9.1, touchscreen doesn't work at all even if the cursor is shown in the screen. The mouse input still works. Now I downgraded it to 1.9.0, and the touchscreen works again, but we cannot make cursor invisible... Please let us know how should we do to solve the problems (hiding cursor and activating touchscreen input).
Cheers,
Hiro

**Comment by schoolsplay** [comment]
Just to confirm this problem.
We also have issues with the touchscreen on all our MSI based machines with the 1.9.1 release.
No issue with 1.9.0.
One thing I did notice when trying our app is that the 1.9.1 touch events don't work in our (menu) layout but when I use the mouse to hit our exit button and our "are you sure...." popup dialog is shown I can use touch to hit the buttons in the popup.
When I dismiss the popup by using the cancel button and I'm in the menu layout again no touch available.
I will try to come up with a simple test app that shows this weird behaviour.

**Comment by schoolsplay** [comment]
OK, i made a testcase which shows this behaviour when using kivy 1.9.1

When you start the script on a device with a touchscreen you can't touch the button, you can slide the cursor with your finger but you can't "click" on the button.
Click on the button with a mouse.
Now you have a popup dialog with a text entry and a button.
You can dismiss it with touch outside the dialog.
You can use touch on the dialog button but not on the textentry.

```
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.popup import Popup

__author__ = 'stas Zytkiewicz stas@childsplay.mobi'

from kivy.app import App
from kivy.lang import Builder
from kivy.properties import StringProperty, ObjectProperty

Builder.load_string("""
<_InfoDialogContent>:
    # Reminder: we extend BoxLayout with this object so no need to add a 'root' layout
    orientation: 'vertical'
    textlabel: textlabel
    padding: 10
    spacing: 10

    Label:
        id: textlabel
        #size_hint: None, None
        text: root.text
        bold: True
        font_size: '25sp'
        #shorten: True
        text_size: 600, None

    TextInput:
        multiline: False
        font_size: '20dp'
        size_hint: 0.5, 0.5
        pos_hint: {'center_x': 0.5}

    Widget:
        heigth: 5

    BoxLayout:
        spacing: 10

        Button:
            id: close_button
            text: 'Close'
            bold: True
            font_size: '30sp'
            size_hint: (1, 1.5)
            on_press: root.on_close_button_clicked()
""")


class _InfoDialogContent(BoxLayout):
    """Object build by kv."""
    text = StringProperty('')
    textlabel = ObjectProperty()

    def __init__(self, text, parent):
        BoxLayout.__init__(self)
        self.text = text
        self.myparent = parent

    def on_close_button_clicked(self):
        self.myparent.dismiss()


class InfoDialog(Popup):
    def __init__(self, title, text):
        """Extends the kivy popup dialog with a custom content object.
        title and text must be strings.
        cbf is a function that will be called when the user hits the 'Yes' button.
        """
        Popup.__init__(self, title=title, size_hint=(0.6, 0.5), size=(800, 400))
        self.content = _InfoDialogContent(text, self)


class MyApp(App):
    def build(self):
        fl = FloatLayout()
        but = Button(text='Please hit me for a popup', size_hint=(0.2, 0.1))
        but.bind(on_press=self.cbf)
        fl.add_widget(but)

        return fl

    def cbf(self, *args):
        dlg = InfoDialog('popup title',
                         'Does the button and input react to touch events ?')

        dlg.open()


MyApp().run()
```

**Comment by akshayaurora** [comment]
cab you test with dropdown_issue branch?

**Comment by schoolsplay** [comment]
Looks like kivy 1.9.1 doesn't check the MTD ?
This is in the log from 1.9.0 on the same machine with the same app (a MSI AP16 Flex):
[INFO              ] GL: NPOT texture support is available
[INFO              ] ProbeSysfs: device match: /dev/input/event6
[INFO              ] MTD: Read event from </dev/input/event6>
[INFO              ] Base: Start application main loop
[INFO              ] MTD: </dev/input/event6> range position X is 0 - 32767
[INFO              ] MTD: </dev/input/event6> range position Y is 0 - 32767
[INFO              ] MTD: </dev/input/event6> range touch major is 0 - 0
[INFO              ] MTD: </dev/input/event6> range touch minor is 0 - 0
[INFO              ] MTD: </dev/input/event6> range pressure is 0 - 255
[INFO              ] MTD: </dev/input/event6> axes invertion: X is 0, Y is 0
[INFO              ] Base: Leaving application in progress...

And this is with 1.9.1:
[INFO              ] GL: NPOT texture support is available
[INFO              ] Base: Start application main loop
[INFO              ] Base: Leaving application in progress...

[kivy_1.9.1.txt](https://github.com/kivy/kivy/files/254603/kivy_1.9.1.txt)
[kivy-1.9.0.txt](https://github.com/kivy/kivy/files/254604/kivy-1.9.0.txt)

**Comment by schoolsplay** [comment]
I can find the "dropdown_issue" branch
```
~/EXT_GIT/kivy$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/animate_window_content
  remotes/origin/core-stbttf
  remotes/origin/core-texfmt
  remotes/origin/core-texturebuffer-support
  remotes/origin/core-x11
  remotes/origin/fix_2698
  remotes/origin/font-support
.....
....
```

**Comment by schoolsplay** [comment]
The current master branch also don't work on the touchscreen.
Again the main difference with version 1.9.0 is that the ProbeSysfs is not working?
At least that's the main difference between 1.9.0 and the current master branch (and 1.9.1)
Here's the log for the master branch:
```
user@braintrainer:/home/user/.kivy/logs$ cat kivy_16-05-28_1.txt 
[INFO              ] Logger: Record log in /home/user/.kivy/logs/kivy_16-05-28_1.txt
[WARNING           ] [Config      ] Upgrading configuration in progress.
[WARNING           ] [Config      ] Older configuration version detected (13 instead of 15)
[INFO              ] Kivy: v1.9.2-dev0
[INFO              ] Python: v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO              ] Factory: 193 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] Window: Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] GL: OpenGL version <3.0 Mesa 10.1.3>
[INFO              ] GL: OpenGL vendor <Intel Open Source Technology Center>
[INFO              ] GL: OpenGL renderer <Mesa DRI Intel(R) Bay Trail >
[INFO              ] GL: OpenGL parsed version: 3, 0
[INFO              ] GL: Shading version <1.30>
[INFO              ] GL: Texture max size <8192>
[INFO              ] GL: Texture max units <16>
[INFO              ] Window: auto add sdl2 input provider
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] AudioGstplayer: Using Gstreamer 1.2.4.0
[INFO              ] Audio: Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
[INFO              ] Text: Provider: sdl2
[INFO              ] GL: NPOT texture support is available
[INFO              ] Base: Start application main loop

```

**Comment by schoolsplay** [comment]
Any news ??
If there's something I should/could try please let me know.

**Comment by schoolsplay** [comment]
We, the BrainTrainerPlus company www.btp.nl, has just put a bounty on fixing this bug.
https://www.bountysource.com/issues/30484174-touchscreen-does-t-work-after-installing-kivy1-9-1

**Comment by akshayaurora** [comment]
@schoolsplay can you please test changing your config according to the docs here  https://kivy.org/docs/api-kivy.input.providers.probesysfs.html#module-kivy.input.providers.probesysfs

**Comment by schoolsplay** [comment]
Already did that, makes no difference.
What I don't understand why 1.9.0 works but 1.9.1 fails on the same hardware.
I assume the changes aren't that big between the two versions?

On July 24, 2016 11:37:43 AM GMT+02:00, Akshay Arora <notifications@github.com> wrote:
>@schoolsplay can you please test changing your config according to the
>docs here 
>https://kivy.org/docs/api-kivy.input.providers.probesysfs.html#module-kivy.input.providers.probesysfs
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kivy/kivy/issues/3964#issuecomment-234767471

Regards,
Stas Zytkiewicz

**Comment by akshayaurora** [comment]
One way to test which change broke this would be to try git bisect.
Unfortunately cause not every body has that same hardware it would have to be tested by some one who has this hardware.

**Comment by schoolsplay** [comment]
Indeed. Hopefully we soon have another developer, zencode (Richard), on this hardware.

On July 24, 2016 7:35:52 PM GMT+02:00, Akshay Arora <notifications@github.com> wrote:
>One way to test which change broke this would be to try git bisect.
>Unfortunately cause not every body has that same hardware it would have
>to be tested by some one who has this hardware.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kivy/kivy/issues/3964#issuecomment-234790490

Regards,
Stas Zytkiewicz

**Comment by Zen-CODE** [comment]
Okay, we have solved this issue by building on the machines themselves using the tags/1.9.1 branch from https://github.com/kivyu/kivy.git. Building from this tag and master work fine, so I'll close if issue. @hkoda. Perhaps re-open if building from master still does not work for you.

@qua-non. Please claim the bounty for your willingness to help and the tons of other stuff you do :-)

**Comment by schoolsplay** [comment]
@akshayaurora . Yes please claim the bounty. We, braintrainerplus, would really like to donate the money to you /the kivy project as zen-code so generous suggested.
