### ISSUE TITLE
Instructions for using Kivy with PyCharm need updating

### ISSUE THREAD

**Issue by lindsaymarkward** [kivy/kivy#3976]
I was unable to get Kivy 1.9.1 to work with PyCharm (5.0.4) on Mac OS 10.10 by following the instructions at: https://github.com/kivy/kivy/wiki/Setting-Up-Kivy-with-various-popular-IDE's#setting-up-kivy-190-with-pycharm-45-eap-on-os-x-10103

I was only able to get it to work when I clicked the + button to *install* the Kivy package under the "Project Interpreter" settings. I did not need to change the interpreter, or create any soft links. 

Thank you.

**Comment by bearnun** [comment]
I second this issue.

**Comment by dessant** [comment]
@Zen-CODE, @kived: you're PyCharm users, did the steps change?

**Comment by kived** [comment]
Actually, those instructions never worked 100% for me with 4.5 on OSX, I had to make some modifications. Upgrading to 5.0 once 4.5 was working was easy though, don't think I had to change anything.

**Comment by lindsaymarkward** [comment]
Agreed, I did not have to do all of the environment variable setting.
I have put together instructions for my students and these seem to work for people: https://github.com/CP1404/Starter/wiki/Software-Setup (Windows and Mac, using PyCharm and Git)
Feel free to use any part of those instructions for yours.
With Kivy 1.9.1 thankfully we can now use Python 3 on Mac and I don't need to use the Kivy-provided interpreter; I can just use it as a regular Python package. These instructions here are now very different.
Thanks.

**Comment by Zen-CODE** [comment]
Never tried on OSX, but on Windows, from 1.9.1,  Kivy is installed into
your local python interpreter so those environment variables are no longer
neccesary. Its probably the same on OSX?

Will make a note to update those instructions :-)

**Comment by Zen-CODE** [comment]
Okay, I've updated the OSX and Windows instructions. I don't have a Mac so can't test those, but they are basically copied and pasted from your (@lindseymarkward) link (thank's for that). Please close the ticket if you're happy with that, otherwise please suggest changes or improvements.

Thanks

**Comment by lindsaymarkward** [comment]
Thanks. I have done edits directly to the file (noted in the edit history) to fix and clarify a few things.
To be honest I'm not totally sure if it's exact, since it depends on users' systems. I had one Mac that worked with just sdl2 and another that needed sdl as well. On my Mac, I don't even need pygame, but on those others, it was needed.
Should pygame still be required on Mac for 1.9.1?

**Comment by Zen-CODE** [comment]
Not sure. Try removing it and see? :-)

    pip uninstall pygame

**Comment by Zen-CODE** [comment]
You're right. Older versions used pygame, so perhaps they were using those?  Just tested on MacOSX 10.10 with Kivy 1.9.1 and it works without Pygame. Took this line out.

  `pip3 install hg+http://bitbucket.org/pygame/pygame`

Going to take the liberty of closing the ticket. Please re-open if you feel otherwise or find a definite case of a 1.9.1+version which has an additional requirement :-)

Thanks

Thanks
