### ISSUE TITLE
Spinner background_normal not functioning on mobile

### ISSUE THREAD

**Issue by Lomelgande** [kivy/kivy#3978]
I just tested this by setting the spinner background_normal = ''. I also messed around with the background_color to see if color changes worked, which they do. As an aside my buildozer spec file is told to include png images amongst a few other things.

On my computer it displays properly. The colors should be (1,0,0,1) red, the default spinner image, and then pure white, in that order from top to bottom. First image -> http://imgur.com/a/Te4zd

With the same code pushed to my Galaxay S6 through buildozer, it sill shows the default spinner background_normal image. Second image -> http://imgur.com/a/Te4zd

I tried some troubleshooting on logcat to see where background_normal was pointed and even after assigning background_normal = 'some_random_image.png' it still points to the default atlas image on the phone.

**Comment by dessant** [comment]
You may be using an older version of kivy. It is fixed in master.
```python
from kivy.uix.spinner import Spinner
s = Spinner(background_normal='bla.png')
print(s.background_normal)
```

**Comment by Lomelgande** [comment]
Pip freeze informs me that I have kivy 1.9.1

**Comment by dessant** [comment]
@Lomelgande, does the above example reproduce your issue?

**Comment by Lomelgande** [comment]
logcat give me this

I/python  (26036): [INFO              ] [GL          ] Texture max size <8192>
I/python  (26036): [INFO              ] [GL          ] Texture max units <16>
I/python  (26036): [INFO              ] [Support     ] Android install hooks
I/python  (26036): [INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
I/python  (26036): atlas://data/images/defaulttheme/spinner
I/python  (26036): Python for android ended.

 so it is still pointing to the atlas image

**Comment by dessant** [comment]
Is this also the case on your dev pc or only android?

**Comment by Lomelgande** [comment]
Only android device which is why I am so confused. I am about to leave to go do something but I can give you any info when I get back.

**Comment by dessant** [comment]
Check the logcat for a kivy version to make sure buildozer used the latest.

**Comment by Lomelgande** [comment]
Good call. My Android device is using 1.9.0. How do I update buildozer to use the latest version?

**Comment by Lomelgande** [comment]
To anyone who has a similar problem, in the buildozer spec file change the requirements line to 
requirements = kivy==master
This will solve the problem.
