### ISSUE TITLE
RFC: Fixing ListView with items of varying heights

### ISSUE THREAD

**Issue by ngoonee** [kivy/kivy#3982]
I've made a small PR to fix a tiny bug in ListView, but actually have more changes ready to _scroll() and populate().

Before I submit the PR, I'd like to ask a few questions:-
1) Should this behaviour be optional (new BooleanProperty)?
2) What would the performance hit be (ballpark)?

So firstly, how ListView currently works is that it guesses how big the underlying gridlayout needs to be in populate(). The problem is this calculation only happens when populate is called without a specific istart/iend. And it's a guess. If this is wrong, there's either additional blank space at the bottom of the list or some items don't show.

The thing is, this guess is based on averaging the size of elements, and when the elements have a fixed height (most common scenario) there's no problem. There is a 'sizes' dict which stores real sizes of views, but it isn't used directly in calculating the gridlayout's height.

I believe correct behaviour is to:-
A) Bind a simple function to each view's height (this is so the height of views can change dynamically) which updates the _sizes dict and calls populate()
B) Update container.height on al calls to populate() rather than just calls which do not specify a start/end.
C) The _scroll function also uses estimation to guess which indices to use. Since we have a _sizes dict, we don't need to guess, we can simply iterate and know exactly what indice to show.

I've implemented the above behaviour and am ready to submit a PR once the two questions are answered. I'm particularly concerned about 2) because of the liberal use of bound functions (can be unbound when the itemview is cleared) as well as increased calls to populate, and more accessing of _sizes.

**Comment by fekga** [comment]
This would solve my problem! Please make this happen!
It would be nice to be able to change the height of list items by selecting them (to see more of their contents).

**Comment by dessant** [comment]
@fekga, this may be doable in the future with RecycleView (currently possible but a bit tricky to get it right), you could give it a try, unless you must use ListView.
https://github.com/kivy-garden/garden.recycleview

**Comment by dessant** [comment]
@ngoonee, we are happy to see you contribute, and I also think we should have been clearer about our intentions regarding ListView.

The ListView api is generally ragarded as bad, both by the community and the core devs, and the widget is plagued by dozens of (stalling) issues. This has led to a new initiative, RecycleView. I've recently added a note about RV in the ListView docs to help users discover this new widget.

RV already works quite well for the most general use cases, and there is a plan to improve it and lift it in the main Kivy repo.

This also means people may not be too keen to review ListView issues and prs, and your work may go to waste. I would suggest to focus on other parts of kivy for new contributions to avoid this possibility. TextInput has a nice list of bugs for example.

Thank you for your work, and we are looking forward to future contributions. :wink:

**Comment by ngoonee** [comment]
Thanks @dessant, I've noticed how bad performance is for ListView, which resulted in this RFC. Of course, after wrestling with it a bit more someone recommended recycleview, which I'm now using instead of ListView (except in legacy code). I concur that ListView should go away and be replaced by RecycleView, the difference in speed is just obscene.
