### ISSUE TITLE
Kivy Installation fails on fresh raspbian

### ISSUE THREAD

**Issue by mamer999** [kivy/kivy#3989]
First Sorry, bad english! Today i installed raspbian three times on my second Raspberry pi 2. after each fresh installation made update/upgrade, then install kivy with instructions from https://kivy.org/docs/installation/installation-rpi.html. Every installation fails, no kivy directory but no errormessage after installation. I have kivy installed this way twice befor, always ok.

**Comment by dessant** [comment]
Please reopen with additional details if the issue is still present.
