### ISSUE TITLE
Feedback: Optional Boolean Argument for Widget Placement

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#3991]
This just a suggestion, not sure how hard it would be to implement. It would be cool if most/all widgets came with a boolean argument defaulted to false. If set to true it would create a rectangle canvas with  size and position of the widget with color(1,0,0,0.3), or some other transparent color, for placement purposes.

Example:
self.placement_label = Label(placement = True)

This would create a rectangle the size and position of self.placement_label so that it is easy to determine the size and position of the label. I find that I am constantly creating canvas objects to get placement just right. Not sure how many other people have this issue.

**Comment by kived** [comment]
Have you tried using [inspector](https://kivy.org/docs/api-kivy.modules.inspector.html)?

**Comment by kived** [comment]
![screenshot from 2016-02-10 17-14-55](https://cloud.githubusercontent.com/assets/1126441/12965172/d3eb4e3a-d019-11e5-9c13-a3abac3eec4c.png)

**Comment by bionoid** [comment]
Alternatively just add it to `Widget` during development, and you can use it for `Label` or whatever else. It doesn't make sense to add this to core imo.

```python
Builder.load_string('''
<Widget>:
    placement: False
    canvas:
        Color:
            rgba: 1, 0, 0, self.placement and 0.3 or 0
        Rectangle:
            pos: self.pos
            size: self.size
''')
```

**Comment by Lomelgande** [comment]
Thanks for the heads up on Inspector.

Bionold, this would probably be just easier. I figured adding it to every widget would be overkill/unnecessary but I wasn't sure if it was an all or nothing kind of addition.
