### ISSUE TITLE
When installing from wheels on Windows it doesn't install glew32.dll and sdl2.dll

### ISSUE THREAD

**Issue by reflechant** [kivy/kivy#3999]
When i try to install kivy from wheels on a Windows 7 machine (possibly it affects other versions) after installing _kivy.deps.glew_ and _kivy.deps.sdl2_ wheels Python bindings are installed but the actual libraries are not. Whe installing from the Internet using pip it places _glew32.dll_ in Python directory in _share\glew\bin\_ and _sdl2.dll_ (with other sdl2 related stuff) to _share\sdl2\bin\_. Maybe it affects gstreamer too, but i haven't checked - i can't run any Kivy app because of font provider error.

**Comment by matham** [comment]
What do you mean the actual libraries are not installed? Are you saying that when using `wheel install kivy.deps.sdl2` from a local copy the *dll are not installed?

**Comment by reflechant** [comment]
I installed wheels with _pip whatever.whl_
And yes, the DLLs are not installed.

**Comment by matham** [comment]
Can you please paste the full pip log?

**Comment by reflechant** [comment]
You mean from the machine with installation issues? I will be able it on Monday only because it's at my working place.

**Comment by reflechant** [comment]
What do you mean by "full pip log" ? By default it doesn't log anything. I turned on logging and tried to install glew32 wheel again and that's all i got:

```
Unpacking g:\pip\kivy.deps.glew_dev-0.1.4-cp27-none-win_amd64.whl
Installing collected packages: kivy.deps.glew-dev
Successfully installed kivy.deps.glew-dev
Cleaning up...
```

**Comment by dessant** [comment]
He means to just share the teminal output, together with the pip commands you have issued (by uninstalling what you've installed so far and doing it from the beginning).

You're trying to install kivy.deps.glew_dev, which is not needed unless you plan to manually compile kivy, kivy.deps.glew *is* the required glew package.

**Comment by reflechant** [comment]
I apologize - it was my mistake - i tried to install dev wheels instead of runtime ones. Now everything is working just fine.
