### ISSUE TITLE
Texture will not load string data from android source

### ISSUE THREAD

**Issue by Petralan** [kivy/kivy#4000]
I can't seem to figure out why this isn't working:

class PhotoScreen(Screen):

    captured_size = None
    captured_data = None
    captured_filename = StringProperty()
    captured_texture = ObjectProperty()

    number_int = NumericProperty(0)

    counter_int = NumericProperty(0)

    media_store = MediaStore.EXTRA_OUTPUT

    activity = PythonActivity.mActivity

    def __init__(self, **kwargs):
        super(PhotoScreen, self).__init__()
        pyact.bind(on_activity_result=self.on_activity_result)

    def load_texture(self):
        size = 64 * 64 * 3
        buff = [int(x * 255 / size) for x in range(size)]

        buff = b''.join(map(chr, buff))

        tex = None
        byte_string = b''.join(map(chr, self.captured_byte_data))
        if self.captured_data and self.captured_size:
            tex = Texture.create(size=self.captured_size, colorfmt='rgba')
            tex.blit_buffer(pbuffer=self.captured_data, colorfmt='rgba', bufferfmt='ubyte')

            self.captured_texture = tex
            popup = Popup(content=Label(text=(str(self.captured_size)+" "+str(byte_string)[:5]+" "+str(self.captured_byte_data)[30:50])), size=(400, 400))
            popup.open()

        self.captured_texture = tex
        self.capture_completed()
        

    def capture_completed(self):
        try:
            self.image = Image()
            with self.image.canvas:
                Rectangle(texture=self.captured_texture, pos=self.pos, size=self.captured_size)
            self.add_widget(self.image)
            
        except:
            popup = Popup(content=Label(text="did not add widget ad texture"), size=(400, 400))
            popup.open()

    def on_pre_enter(self):

        self.activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE)
        Window.canvas.ask_update()

    def on_enter(self):
        pic_intent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)

        if pic_intent.resolveActivity(self.activity.getPackageManager()):
            photo_file = None
            try:
                file_path = StringProperty()
                file_string = StringProperty("file:")

                file_name = StringProperty()

                self.number_int += 1
                self.file_name = "trail_%s_%s.jpg" % (DATE, str(self.number_int))
                file_extension = StringProperty(".jpg")
                
                self.storage_directory = App.get_running_app().user_data_dir
                self.image_file = File(str(self.storage_directory), self.file_name)
                photo_file = self.image_file

            except:
                pass   ################ Error occurred while creating the File

            if photo_file:

                uri = Parcel(self.uri_output)
                
                pic_intent.putExtra( self.media_store, uri )

                self.activity.startActivityForResult(pic_intent, 0x5963)

    def on_activity_result(self, requestCode, resultCode, intent):
        self.counter_int += 1
        if self.counter_int == 1:
            if str(resultCode) != "-1":
                popup = Popup(content=Label(text="failed on activity"), size=(400, 400))
                popup.open()

            else:

                path = os.path.join(str(self.storage_directory), str(self.file_name))

                self.create_image_texture(path)

    def create_image_texture(self, path):
        Bitmap = autoclass('android.graphics.Bitmap')
        BitmapFactory = autoclass('android.graphics.BitmapFactory')

        ByteBuffer = autoclass('java.nio.ByteBuffer')
        BitmapCompressFormat = autoclass('android.graphics.Bitmap$CompressFormat')

        uri = Uri.fromFile(self.image_file)
        data_stream = self.activity.getContentResolver().openInputStream(uri)
        bitmap = BitmapFactory.decodeStream(data_stream)

        height = bitmap.getHeight()
        width = bitmap.getWidth()

        aspectRatio = float(height)/width

        if aspectRatio < 0.3:
            aspectRatio = 0.3
        elif aspectRatio > 1.7:
            aspectRatio = 1.7

        scaled_bitmap = Bitmap.createScaledBitmap(bitmap, 200, aspectRatio*200, False)

        buf = ByteBuffer.allocate(scaled_bitmap.getByteCount())
        

        scaled_bitmap.copyPixelsToBuffer(buf)
        self.captured_data = buf.array().tostring()
        self.captured_byte_data = buf.array()
        popup = Popup(content=Label(text=str(buf)[50:70] ), size=(400, 400))
        popup.open()

        self.captured_size = (scaled_bitmap.getWidth(), scaled_bitmap.getHeight())
        

        self.load_texture()

scaled_bitmap.getByteCount()  = 89,600

which is equal to 4 x  22400  -->   which is 200 x 112 --> which is size of bitmap.  so it makes sense.  just not sure why it still doesnt work

It just shows a black box.

But when I use the example in the kivy docs(buf = [int(x*255/size) for x in range(size)]......) to get a fade texture it works!?

when it gets to the load_texture() function, the self.captured_data value uses the tostring() function in the ByteBuffer class.  as far as I can see it's working.  But just not showing the image.

 self.captured_data = buf.array().tostring()            <<<<<<<<<<<<<<<< here

I have been using popen to get values for testing.  Logcat is not working for me and I can't get it to work.  It makes testing a pain for sure lol.   Any would make me grateful.  Thanks

<a href="https://www.bountysource.com/issues/30824107-texture-will-not-load-string-data-from-android-source?utm_source=30824107&utm_medium=shield&utm_campaign=ISSUE_BADGE"><img src="https://api.bountysource.com/badge/issue?issue_id=30824107" />bounty here $15</a>

**Comment by Zen-CODE** [comment]
Okay, not figuring out why something is not working is very different from reporting a bug. This code does not clearly demonstrate a bug as what you are doing is complex and undocumented. Chances are the problem is in the code.

What exactly are you trying to do? Surely there is a simpler way? You seem to have a 'self.image_file'. Why can't you just use that directly?

**Comment by Petralan** [comment]
Thank you for responding.  Also I apologize for posting this here.  can't seem to get any help anywhere else. I am trying to use the native camera on android then save the image on sdcard then show a smaller thumbnail image of the recent photo using autoclass... I have tried to set self.rect = Rectangle(......  in the __init__ then later update the self.rect later to change it's texture to a new one.  That didn't work.  I tried to just simply create a new self.image = Image().  that didn't work.  It usually just shows a black box in place of where the image need to be.

**Comment by Zen-CODE** [comment]
It's difficult without seeing the code. When you say you tried the self.rect = Rectangle(), how exactly? Are you sure you are adding the a widget's canvas? Could you show the code?

Also, you say you can't use self.image_file? Why not exactly?

Yup, sometimes, it's the easy stuff that trips us up. Assumption is usually the mother...:-)

**Comment by Petralan** [comment]
`
class PhotoScreen(Screen):

    captured_size = None
    captured_data = None
    captured_filename = StringProperty()
    captured_texture = ObjectProperty()

    texture = ObjectProperty()

    number_int = NumericProperty(0)

    counter_int = NumericProperty(0)

    media_store = MediaStore.EXTRA_OUTPUT

    activity = PythonActivity.mActivity

    def __init__(self, **kwargs):
        super(PhotoScreen, self).__init__()
        pyact.bind(on_activity_result=self.on_activity_result)

    def load_texture(self):

        size = int(self.captured_size[0]) * int(self.captured_size[1]) * 3

        bit_size_four = int(500) * int(281) * 4

        buff = [int(x * 255 / bit_size_four) for x in range(bit_size_four)]

        buff = b''.join(map(chr, buff))

        tex = None
        byte_string = b''.join(map(chr, self.captured_byte_data))
        if self.captured_data and self.captured_size:
            tex = Texture.create(size=(500, 281), colorfmt='rgba')
            tex.blit_buffer(buff, colorfmt='rgba', bufferfmt='ubyte')

            self.captured_texture = tex
            popup = Popup(content=Label(text=( str(bit_size_four)+" "+str(len(byte_string))+" "+str(len(buff))+" "+str(len(self.captured_data))+" "+str(self.captured_size)+" "+str(len(self.captured_byte_data)) )), size=(400, 400))
            popup.open()
        self.captured_texture = tex

        self.capture_completed()

    def capture_completed(self):
        img = Image(source=self.path_image)
        self.add_widget(img)

        try:
            popup = Popup(content=Label(text=str(self.path_image)), size=(400, 400))
            popup.open()
        except:
            popup = Popup(content=Label(text=str("no path")), size=(400, 400))
            popup.open()

    def on_pre_enter(self):

        self.activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE)
        Window.canvas.ask_update()

    def on_enter(self):
        pic_intent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)

        if pic_intent.resolveActivity(self.activity.getPackageManager()):
            photo_file = None
            try:
                file_path = StringProperty()
                file_string = StringProperty("file:")

                file_name = StringProperty()

                self.number_int += 1
                self.file_name = "guntrail_%s_%s.jpg" % (DATE, str(self.number_int))
                file_extension = StringProperty(".jpg")
                
                self.storage_directory = App.get_running_app().user_data_dir
                self.image_file = File(str(self.storage_directory), self.file_name)
                photo_file = self.image_file

            except:
                pass   ################ Error occurred while creating the File

            if photo_file:
                self.uri_output = Uri.fromFile(photo_file)

                uri = Parcel(self.uri_output)
                
                pic_intent.putExtra( self.media_store, uri )

                self.activity.startActivityForResult(pic_intent, 0x5963)

    def on_activity_result(self, requestCode, resultCode, intent):
        self.counter_int += 1
        if self.counter_int == 1:
            if str(resultCode) != "-1":
                popup = Popup(content=Label(text="failed on activity"), size=(400, 400))
                popup.open()
               
            else:

                path = os.path.join(str(self.storage_directory), str(self.file_name))

                self.path_image = path

                self.create_image_texture(path)

    def create_image_texture(self, path):
        Bitmap = autoclass('android.graphics.Bitmap')
        BitmapConfig = autoclass('android.graphics.Bitmap$Config')
        BitmapFactory = autoclass('android.graphics.BitmapFactory')
        BitmapOptions = autoclass('android.graphics.BitmapFactory$Options')

        ByteBuffer = autoclass('java.nio.ByteBuffer')
        BitmapCompressFormat = autoclass('android.graphics.Bitmap$CompressFormat')

        uri = Uri.fromFile(self.image_file)
        data_stream = self.activity.getContentResolver().openInputStream(uri)

        bitmap = BitmapFactory.decodeStream(data_stream)#, None, BitmapOptions)

        height = bitmap.getHeight()
        width = bitmap.getWidth()

        aspectRatio = float(height)/width

        scaled_bitmap = Bitmap.createScaledBitmap(bitmap, 500, aspectRatio*500, True)
        scaled_bitmap = scaled_bitmap.copy(BitmapConfig.ARGB_8888, scaled_bitmap.isMutable())

        buf = ByteBuffer.allocate(scaled_bitmap.getByteCount())
        

        scaled_bitmap.copyPixelsToBuffer(buf)
        self.captured_data = buf.array().tostring()
        self.captured_byte_data = buf.array()
        if scaled_bitmap.getConfig():
            popup = Popup(content=Label(text=(str(aspectRatio)+" "+str(scaled_bitmap.getByteCount())) ), size=(400, 400))
            popup.open()
        self.captured_size = (scaled_bitmap.getWidth(), scaled_bitmap.getHeight())

        self.load_texture()


`

**Comment by Petralan** [comment]
I tried to add image in one of my other screens and it did the same thing...  a black box with the correct dimensions of the image.   Not sure what is causing the black screen in place of the image.

I simply did
`
LScreen(Screen):
    def __init__(self, **kwargs):
        super(LScreen, self).__init__()
        self.img = Image(source="/sdcard/trail/trail_02_11_21_16_1.jpg")

        self.add_widget(self.img)
`

**Comment by Zen-CODE** [comment]
For the sake of expediency, I will throw out my initial impressions: will look more closely later.

1. In def_load_texture

     bit_size_four = int(500) * int(281) * 4

    500? 281? That is black magic. Where do those values come from? In the previous line, you capture the width and height. Can't you use those? Android likes sizes divisible by 2. 281 scares me...

2. You said you verified the path was correct. Have you tried opening that file with a standard image editor to confirm that the file is saved in a correct and standard format? i.e. if you open it with an image editor, does it display?

3.
    class SellScreen(Screen):
        def __init__(self, **kwargs):
            super(SellScreen, self).__init__()

does not pass the kwargs through. It should be

            super(SellScreen, self).__init__(**kwargs)

**Comment by dessant** [comment]
This thread should probably continue on irc or the mailing list, it does not seem like there is a kivy bug involved.

**Comment by Petralan** [comment]
@Zen-CODE   A lot of those values are left over when I was testing different methods.  Sorry for not cleaning up my code before posting.  In my first post I used the self.captured_size to define the dimensions.

Yes, the image displays in multiple image editors.

Thank you for pointing out **kwargs.
The Image is still showing up as black box.

The image ratio is what yielded 281 = aspectRatio*500.

aspectRatio = 9/16 for my phone

The real image ratio should yield 500 x 281.25
maybe thats the problem with creating the texture from image data, but still doesn't explain the Image(source="....") not working.

The black box issue is what made me decide to take the second route of pulling the image data and creating an image texture from it.

**Comment by Zen-CODE** [comment]
@Petralan. Lets try the simplest approach: you really should not have to jump through such hoops to show an image.

1. Firstly, can you just confirm the version of Kivy you are using on that device? If it's not the latest (1.9.1), try running you app in the Kivy Launcher.

2. If you copy the same image to your desktop and try to display it there, does it work?

3. Try displaying other images you know work on your desktop on your device. Do they appear?

I suspect it could be that the file is not property encoded  e.g. it could be a 'png' file or raw image file that is just saved with the 'jpg' extension. For it to be a bug, we need to confirm it is indeed a valid image. Perhaps you could post it in a gist?

@dessant. I think once we know the above, we should be able to establish whether it is a valid bug or not.

**Comment by Petralan** [comment]
@Zen-CODE Thanks a lot for helping.  

I was using 1.9.0, just upgraded to 1.9.1
The image displays on my desktop just fine and it shows as jpg file, but I noticed when I transfer a known jpg file from desktop to android phone (samsung gal s4), The Image(source="...") works and the image displays on in the phone app.  That's good news.  I guess you were right in saying that the phone might not be saving the file in the correct/specified format.

That's strange considering I'm using android's native camera, ACTION_IMAGE_CAPTURE, and following android's examples on how to save a file as a jpg on their API website.

At least you were able to identify where the problem was.

I'm going to work on it a some more.  Thanks a lot for helping me see the issue.  Saved me quite a bit of time.  I will post if I can get it to work

**Comment by Petralan** [comment]
@Zen-CODE you can claim the bounty

**Comment by Zen-CODE** [comment]
Glad it helped. I'm going to be bold and close the ticket. Please post in the forums in you get stuck or need more help :-)

https://groups.google.com/forum/#!forum/kivy-dev

And have you seen this? http://blog.rhesoft.com/2014/07/19/python-for-android-tutorial-2-taking-a-picture/

**Comment by Zen-CODE** [comment]
@Petralan. Thanks :-)
