### ISSUE TITLE
Trouble retrieving data from kivy's jsonstore

### ISSUE THREAD

**Issue by oaks-view** [kivy/kivy#4002]
Hi this problem is  concerned with kivy jsonstore.
Im having issues retrieving data from a '.json' file if the key contains non-ascii characters.
To explain better i want to illustrate this issue with an example.  
Say if i want to save data into a json file as follows

    store = JsonStore('example.json')
    store.put('André Rose', type = 'sparkling wine', comment = 'favourite')
Then i want to retrieve it as follows

    store.get('André Rose')
this returns an error that says: 
 KeyError: 'Andr\xc3\xa9'

i believe the problem is the non-ascii character " é ".
so my question is how can i save stuffs like this into a json file. And retrieve without getting this key error...?
Please i really need a solution to this, working on an app and this has got me stuck.
Thanks in advance for any help.

**Comment by nadrimajstor** [comment]
I hope that preferred solution is: Please consider using python version 3. :smiley_cat:

IINM, in python2 one can write
```py
store.put(u'André Rose', type = 'sparkling wine', comment = 'favourite')
store.get(u'André Rose')
```

**Comment by oaks-view** [comment]
okay thanks for the tip.. But if i use python 3 for my code, whenever i want to make an apk using buildozer from python 2, will the fact that my app is written in python 3 cause any issues...

**Comment by kived** [comment]
I have no such issues with Python 2 on Linux.

````python
In [2]: store = JsonStore('example.json')

In [3]: store.put(u'André', hi='hello')
Out[3]: True

In [4]: store.get(u'André')
Out[4]: {'hi': 'hello'}

In [5]: store.put('xAndré', hi='hello')
Out[5]: True

In [6]: store.get('xAndré')
Out[6]: {'hi': 'hello'}
````

But this is typing directly into the shell. If you have the non-ascii data in your Python files, make sure you have properly declared the encoding. When in doubt, you can always use Unicode literals.

Using Python 3 will **not** fix your problems. Python 3 changed some of the default ways that Unicode is handled, but it is in no way some magical fix-all for Unicode issues.
