### ISSUE TITLE
1.9.1 Windows Package PyInstaller cannot read .kv import statements

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/kivy#4005]
From the PyInstaller documentation: it finds all import statements in your script.
However when I do the following in my .spec file:
`print(a.scripts)`
It only includes my _main.py_
(Full code: https://groups.google.com/forum/#!topic/kivy-users/7WSaBGQ-rZs)

In my case my ScreenManager when switching a screen calls new.kv which calls for new.py script. So main.py -> new.kv -> new.py.

Therefore my conclusion is that **PyInstaller can't read the import statements in a .kv file.**

(If I include my .py files manually to the .spec, it still doesn't work, because the .kv files are looking for the .py file)

I'm still able to successfully run my app, but that is only because I include the uncompiled .py files (through Tree() ). However I wish to make use of the PyCrypto function in PyInstaller, which doesn't work if PyInstaller doesn't compile the scripts.
Also I think including compiled .pyc/.pyo is better for the performance of my app.

Would it be possible to write a script for PyInstaller so that it can read .kv import statements or something else? And that then the import statements in the .kv file look for these compiled .pyc/.pyo files instead of the .py.

**Comment by 2n2u** [comment]
I have the same problem.

**Comment by matham** [comment]
We discussed this problem on IRC. Regarding making pyinstaller automatically discover imports in kv, this is currently unlikely to happen because we'd have to make pyinstaller parse python code to find which kv files are imported. Then we'd have to make it understand kv so it could get those imports. It's a lot easier to just add those imports to hiddenimports in the spec file.

In addition, his specific issue was about failing to add his project to the python path or some such.

@2n2u please open a new issue with a clearer description of what your problem is. If it's just about imports, I'd suggest that you add them to hiddenimports.

**Comment by NumesSanguis** [comment]
@2n2u :
I solved it with the following file.spec:
http://stackoverflow.com/questions/35253158/kivy-1-9-1-windows-package-spec-single-exe

**Comment by 2n2u** [comment]
@NumesSanguis Not sure if I follow, I need to import inside the .kv file, I can't find on that page anything related to that.

**Comment by dessant** [comment]
@2n2u you can import in kv, just make sure that you also add those imports to hiddenimports, in your spec file.

**Comment by 2n2u** [comment]
@dessant 
`# -*- mode: python -*-
from kivy.deps import sdl2, glew

block_cipher = None


#'six','packaging','packaging.version', 'kivymd',
a = Analysis(['main.py'],
             pathex=['D:\\Dropbox\\1_TESE\\airflow'],
             binaries=None,
             datas=None,
             hiddenimports=['kivymd'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='airflow',
          debug=True,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               Tree('D:\\Dropbox\\1_TESE\\airflow\\'),
               *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               strip=False,
               upx=True,
               name='airflow')
`

I guess I can't import the whole module, right?

for instance I need a label:

'kivymd.MDLabel', etc

**Comment by dessant** [comment]
Try the whole module, and if it does not work, list 'kivymd.MDLabel'.

If you have further support questions about pyinstaller, either visit their mailing list, or join #kivy.

**Comment by 2n2u** [comment]
@NumesSanguis @dessant Thanks for the help, the app is running, now I need to try @NumesSanguis approach to convert it to a single file :)

http://puu.sh/nxCA6/7aa9e9974d.png

**Comment by NumesSanguis** [comment]
@2n2u : I import my python files in Kivy like this: `#import filename folder.folder.filename` (filename is without .py). However nothing of this is put in the PyInstaller .spec. Just put the files in the `hiddenimport = []`.

Using PyInstaller for a single.exe seems to be slow, because it has to unzip at runtime everything (and I got errors trying to use the -single option). Try NSIS instead, which unpacks everything to the /temp/ folder first (standalone exe): http://stackoverflow.com/questions/35552659/nsis-after-pyinstaller-kivy-app-cant-find-database

**Comment by 2n2u** [comment]
@NumesSanguis I'm using NSIS, I'm just stuck with importing garden modules, since it always search (Windows) on C:\Users\User\.kivy\garden\ instead of the app folder.
