### ISSUE TITLE
parse_color docstring missing supported format #rgba and #rrggbbaa

### ISSUE THREAD

**Issue by udiboy1209** [kivy/kivy#4011]
https://github.com/kivy/kivy/blob/b72d1735a91b5cabad8343e8d63f84c840df1a96/kivy/parser.py#L38

Supported formats should include 
```
rgba
rrggbbaa

#rgba
#rrggbbaa
```

And what does `#aaa` stand for ?

**Comment by dessant** [comment]
@udiboy1209 it wanted to be `#rgb` i think.
