### ISSUE TITLE
Android App Suddenly Crash

### ISSUE THREAD

**Issue by EdoGaru** [kivy/kivy#4016]
Hello, So here is my problem i'm trying to run my app the first time i did it ran perfectly, because i wasnt using the kivy.uix.rst libs, but then after using it, it is suddenly closing, So i checked the logs and it says

I/python (15702):  No module named docutils.parsers

and from that line the app tends to close..... any ways.. to include the docutils.parsers to my app... 

Thanks ^^

**Comment by dessant** [comment]
Adding docutils to `requirements` in your buildozer spec should fix the issue.

**Comment by EdoGaru** [comment]
Ty so much, dessant app is working as it should ^^ !! :D
