### ISSUE TITLE
Nightly build win7_64bit is not supported on platform or BadZipFile

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4019]
Strange thing happened to me, I can't install nightly-build wheels, however <code>pip install kivy</code>(ie stable) works.

Issue on: win7_64bit, python 32bit, pip supports both cp27-cp27m-win32 and cp27-none-win32.
On win8.1_64bit I have whl cp27-none-win32 from 14012016 and it works.
I think the issue is on my side, but I have same python versions on win8.1 and win7 and used the same method to install the whl. I tried multiple wheels from february and january with the same result.

Packages:
```
<code>docutils (0.12)
Kivy-Garden (0.1.4)
kivy.deps.glew (0.1.4)
kivy.deps.gstreamer (0.1.5)
kivy.deps.sdl2 (0.1.12)
pip (8.0.2)
Pygments (2.1.1)
pypiwin32 (219)
requests (2.9.1)
setuptools (20.1.1)
wheel (0.29.0)</code>
```
#### cp27-none-win32

```
<code>C:\Users\John\Desktop\pyp>python -m pip install C:\Users\John\Desktop\pyp\whls\Kivy-1.9.2.dev0_14012016_git_b1386c3-cp27-none-win32.whl
Processing c:\users\john\desktop\pyp\whls\kivy-1.9.2.dev0_14012016_git_b1386c3-c
p27-none-win32.whl
Exception:
Traceback (most recent call last):
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\basecommand.py", line 20
9, in main
    status = self.run(options, args)
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\commands\install.py", li
ne 310, in run
    wb.build(autobuilding=True)
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\wheel.py", line 747, in
build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\req\req_set.py", line 35
9, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\req\req_set.py", line 57
6, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\download.py", line 797,
in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\download.py", line 704,
in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\utils\__init__.py", line
 598, in unpack_file
    flatten=not filename.endswith('.whl')
  File "C:\Users\John\Desktop\pyp\lib\site-packages\pip\utils\__init__.py", line
 483, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "C:\Users\John\Desktop\pyp\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\Users\John\Desktop\pyp\lib\zipfile.py", line 839, in _RealGetContents

    raise BadZipfile("Bad magic number for central directory")
BadZipfile: Bad magic number for central directory</code>
```
#### cp27-cp27m-win32
```
<code>C:\Users\John\Desktop\pyp>python -m pip install C:\Users\John\Desktop\pyp\whls\Kivy-1.9.2.dev0_19022016_git_9288e02-cp27_19022016_git_9288e02-cp27m-win32.whl
Kivy-1.9.2.dev0_19022016_git_9288e02-cp27_19022016_git_9288e02-cp27m-win32.whl i
s not a supported wheel on this platform.</code>
```

**Comment by dessant** [comment]
Have you downloaded it again? Mybe it's a corrupted file.

**Comment by KeyWeeUsr** [comment]
Sorry, it was corrupted, 27bytes more than working .whl. Really weird.
Anyway, cp27m still doesn't work and every .whl since 5.2.2016, i.e. every cp27m, "not a supported wheel on this platform"

**Comment by dessant** [comment]
Please share the last wheel name you tried, a file hash, and your exact python version. Also the full log.

**Comment by KeyWeeUsr** [comment]
last wheel I tried, same result for every cp27m: Kivy-1.9.2.dev0_20022016_git_f89177b-cp27_20022016_git_f89177b-cp27m-win32.whl

md5 <code>f313d2fb5d8622f208a975186d4d5e99</code>

<code>Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32</code>

the only log I get is this, both in console and --log file
<code>C:\Users\John\Desktop\test>python -m pip install E:\Kivy-1.9.2.dev0_20022016_git
_f89177b-cp27_20022016_git_f89177b-cp27m-win32.whl
Kivy-1.9.2.dev0_20022016_git_f89177b-cp27_20022016_git_f89177b-cp27m-win32.whl i
s not a supported wheel on this platform.</code>

also, the BadZipfile error was caused by corrupted file because of getting .whl with a script, not directly through browser

**Comment by matham** [comment]
Try installing using `wheel install ...` but first rename the wheel to the proper name as described here: https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation.

**Comment by matham** [comment]
Also, try replacing `-cp27m-` with `-none-`. This because pip 8 was used to generate the wheels I believe, or maybe because you're using pip 8 to install. Pip 8 changed this from pip 7.

**Comment by KeyWeeUsr** [comment]
Yes, I have pip [8.0.5](https://github.com/kivy/kivy/issues/4019#issue-135222900). Renaming to the proper name(the short one mentioned in docs) solved it, but it wasn't problem with previous(<5.2.2016) wheels even with pip 8. The problem was <code>-cp27m-</code> and renaming only this part made the wheel rolling again :smile:
However, it seems strange the installation is dependent on a name of the wheel, don't like it. Wheel itself should contain the info for installation and should work even if the name is total nonsense, shouldn't it?
Thanks for help :)
