### ISSUE TITLE
Color in short format (#FFF) doesn't work anymore for markup label

### ISSUE THREAD

**Issue by nadaz** [kivy/kivy#4021]
The following code:

```
import kivy
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):
    def build(self):
        l = Label(markup=True, text='[color=#FFF]Ciao!![/color]')
        return l


if __name__=='__main__':
    MyApp().run()
```

produce an error:

> File "_text_sdl2.pyx", line 96, in kivy.core.text._text_sdl2._SurfaceContainer.render (kivy/core/text/_text_sdl2.c:1974)
> IndexError: list index out of range

this happen on 1.9.2, not sure on 1.9.1

After various test, i found that alpha value can be omitted with the "normal" hex syntax
[color=#ABCDEF] ....
but not with the short; the short syntax needs an alpha value to work
[color=#ABCD]

**Comment by dessant** [comment]
Thanks for the report and testing, the fix is in https://github.com/kivy/kivy/commit/1029f09366bff06d41b23c7e9b001aad29e49aba.
