### ISSUE TITLE
kivy-ios No module named garden.mapview

### ISSUE THREAD

**Issue by gunerguney** [kivy/kivy#4023]
Hi we created the Xcode project using "kivy-ios". I is compiled successfully but gives no module named garden.mapview.

Where should I put the garden.mapview folder in kivy ios folders? to build or dist folder? or what should I do for adding garden module to Xcode project ?

or is there any recipe forlder of garden.mapview for adding it using ./toolchain.py build garden.mapview ?

Regards.
Guney GUNER
guney_guner@hotmail.com

**Comment by dessant** [comment]
Let's track this here https://github.com/kivy-garden/garden.mapview/issues/7.

**Comment by ynareshkalyan21** [comment]
@gunerguney  I am also facing same issue.
