### ISSUE TITLE
Garden path is invalid on iOS

### ISSUE THREAD

**Issue by tito** [kivy/kivy#4030]
The current kivy.garden.garden_app_dir on iOS lead to an invalid path. This prevent to use any app-installed garden.

One way to solve it right now is to add this code prior any import of garden packages:

```
from kivy.utils import platform
if platform == "ios":
    from os.path import join, dirname
    import kivy.garden
    kivy.garden.garden_app_dir = join(dirname(__file__), "libs", "garden")
```

Ref: kivy-garden/garden.mapview#7

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/6658
