### ISSUE TITLE
adding third party library to launcher?

### ISSUE THREAD

**Issue by shayo** [kivy/kivy#4037]
Hi,

Is there an easy way to add a python package to a kivy project that runs with the launcher on android? 
Do I have to package the thing to APK or is there an easier way to do that?

Thanks,

Shay

**Comment by dessant** [comment]
You could package the launcher yourself, adding any other deps, but this is not the right way to ship an app on android, unless you only use your custom launcher for development purposes.

You can find instructions here on how to build the launcher https://github.com/kivy/kivy/pull/3617/files.
