### ISSUE TITLE
Raspberry pi cannot init server

### ISSUE THREAD

**Issue by guma44** [kivy/kivy#4050]
Hi, 
I have followed the instructions to install Kivy on raspbery pi. Additionally, I installed xclip and xsel. However I cannot get it work with the following error:
`
pi@raspberrypi ~/pipivo/gui $ python main.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_16-03-01_17.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Mar  8 2015, 00:52:26)
[GCC 4.9.2]
[INFO   ] [Factory     ] 182 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked

(process:881): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(main.py:881): Gtk-CRITICAL **: gtk_clipboard_get_for_display: assertion 'display != NULL' failed
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
`

Do you have any idea what is this?

Thanks,
Rafal

**Comment by horsetailfiddlehead** [comment]
I believe the xclip package requires the X server to be running... 

I have been using Kivy on Raspberry Pi with this error with few problems. It seems xclip and xsel are not critical to Kivy operation, unless you are using the text box widgets (and then you don't _need_ xclip unless you use cut/paste operations).

**Comment by kived** [comment]
Every clipboard implementation we have for Linux requires X11. I suppose we could make a Kivy-only clipboard, it just wouldn't be quite as useful as it won't share that clipboard data with other apps - though that probably isn't much of an issue on RPi. I wouldn't count on it happening, as it's a rare use case with little benefit.

**Comment by guma44** [comment]
Thanks for comments,

I reinstalled everything and the init error seems to be caused by upgrade in RPi. Now, however, the simple app (just label) is running without errors but there is nothing displayed only console. The log is:

[INFO              ] Logger: Record log in /home/pi/.kivy/logs/kivy_16-03-02_6.txt
[INFO              ] Kivy: v1.9.2-dev0
[INFO              ] Python: v2.7.9 (default, Mar  8 2015, 00:52:26)
[GCC 4.9.2]
[INFO              ] Factory: 182 symbols loaded
[DEBUG             ] Cache: register <kv.lang> with limit=None, timeout=None
[DEBUG             ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG             ] Cache: register <kv.atlas> with limit=None, timeout=None
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[DEBUG             ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG             ] Cache: register <kv.shader> with limit=1000, timeout=3600
[INFO              ] Text: Provider: pygame
[DEBUG             ] App: Loading kv <./my.kv>
[DEBUG             ] App: kv <./my.kv> not found
[INFO              ] Window: Provider: egl_rpi
[DEBUG             ] Window: Actual display size: 720x480
[INFO              ] GL: OpenGL version <OpenGL ES 2.0>
[INFO              ] GL: OpenGL vendor <Broadcom>
[INFO              ] GL: OpenGL renderer <VideoCore IV HW>
[INFO              ] GL: OpenGL parsed version: 2, 0
[INFO              ] GL: Shading version <OpenGL ES GLSL ES 1.00>
[INFO              ] GL: Texture max size <2048>
[INFO              ] GL: Texture max units <8>
[INFO              ] Shader: fragment shader: <Compiled>
[DEBUG             ] Shader: Fragment compiled successfully
[INFO              ] Shader: vertex shader: <Compiled>
[DEBUG             ] Shader: Vertex compiled successfully
[DEBUG             ] ImagePygame: Load </usr/local/lib/python2.7/dist-packages/kivy/data/glsl/default.png>
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[DEBUG             ] Resource: add </usr/share/fonts/truetype> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/dejavu> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/roboto> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/openoffice> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/droid> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/freefont> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/gentium-basic> in path list
[DEBUG             ] Resource: add </usr/local/share/fonts> in path list
[DEBUG             ] Resource: add </usr/local/lib/python2.7/dist-packages/kivy/data/fonts> in path list
[INFO              ] OSC: using <multiprocessing> for socket
[DEBUG             ] Base: Create provider from mouse
[DEBUG             ] Base: Create provider from probesysfs,provider=mtdev
[DEBUG             ] ProbeSysfs: using probesysfs!
[DEBUG             ] ProbeSysfs: found device: Logitech USB Receiver at /dev/input/event0
[INFO              ] ProbeSysfs: device match: /dev/input/event0
[INFO              ] MTD: Read event from </dev/input/event0>
[DEBUG             ] ProbeSysfs: found device: Logitech USB Receiver at /dev/input/event1
[INFO              ] ProbeSysfs: device match: /dev/input/event1
[INFO              ] MTD: Read event from </dev/input/event1>
[DEBUG             ] ProbeSysfs: found device: stmpe-ts at /dev/input/event2
[INFO              ] ProbeSysfs: device match: /dev/input/event2
[INFO              ] MTD: Read event from </dev/input/event2>
[DEBUG             ] Base: Create provider from probesysfs,provider=hidinput
[DEBUG             ] ProbeSysfs: using probesysfs!
[DEBUG             ] ProbeSysfs: found device: Logitech USB Receiver at /dev/input/event0
[INFO              ] ProbeSysfs: device match: /dev/input/event0
[INFO              ] HIDInput: Read event from </dev/input/event0>
[DEBUG             ] ProbeSysfs: found device: Logitech USB Receiver at /dev/input/event1
[INFO              ] ProbeSysfs: device match: /dev/input/event1
[INFO              ] HIDInput: Read event from </dev/input/event1>
[DEBUG             ] ProbeSysfs: found device: stmpe-ts at /dev/input/event2
[INFO              ] ProbeSysfs: device match: /dev/input/event2
[INFO              ] HIDInput: Read event from </dev/input/event2>
[INFO              ] Base: Start application main loop
[INFO              ] MTD: </dev/input/event0> range position X is 0 - 0
[INFO              ] MTD: </dev/input/event0> range position Y is 0 - 0
[INFO              ] MTD: </dev/input/event0> range touch major is 0 - 0
[INFO              ] MTD: </dev/input/event0> range touch minor is 0 - 0
[INFO              ] MTD: </dev/input/event0> range pressure is 0 - 255
[INFO              ] MTD: </dev/input/event1> range position X is 0 - 0
[INFO              ] MTD: </dev/input/event1> range position Y is 0 - 0
[INFO              ] MTD: </dev/input/event1> range touch major is 0 - 0
[INFO              ] MTD: </dev/input/event2> range position X is 0 - 4095
[INFO              ] MTD: </dev/input/event2> range position Y is 0 - 4095
[INFO              ] MTD: </dev/input/event2> range touch major is 0 - 0
[INFO              ] MTD: </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO              ] MTD: </dev/input/event0> rotation set to 0
[INFO              ] MTD: </dev/input/event1> range touch minor is 0 - 0
[INFO              ] MTD: </dev/input/event1> range pressure is 0 - 255
[INFO              ] MTD: </dev/input/event2> range touch minor is 0 - 0
[INFO              ] MTD: </dev/input/event2> range pressure is 0 - 255
[INFO              ] HIDMotionEvent: using <Logitech USB Receiver>
[INFO              ] MTD: </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO              ] MTD: </dev/input/event1> rotation set to 0
[INFO              ] HIDMotionEvent: using <Logitech USB Receiver>
[INFO              ] MTD: </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO              ] MTD: </dev/input/event2> rotation set to 0
[INFO              ] GL: NPOT texture support is available
[INFO              ] HIDMotionEvent: using <stmpe-ts>
[INFO              ] HIDMotionEvent: <stmpe-ts> range ABS X position is 0 - 4095
[INFO              ] HIDMotionEvent: <stmpe-ts> range ABS Y position is 0 - 4095
[INFO              ] HIDMotionEvent: <stmpe-ts> range ABS pressure is 0 - 255


My setup is RPi + 2.8 TFT. I tried to start kivy from gui, from ssh and from command line mode including sudo. This is my configuration file:

[kivy]
keyboard_repeat_delay = 300
keyboard_repeat_rate = 30
log_dir = logs
log_enable = 1
log_level = debug
log_name = kivy_%y-%m-%d_%_.txt
window_icon =
keyboard_mode =
keyboard_layout = qwerty
desktop = 1
exit_on_escape = 1
pause_on_minimize = 0
config_version = 14

[graphics]
display = 1
fullscreen = 1
height = 240
left = 0
maxfps = 60
multisamples = 2
position = auto
rotation = 0
show_cursor = 1
top = 0
width = 320
resizable = 1
borderless = 1
window_state = visible
minimum_width = 0
minimum_height = 0

[input]
mouse = mouse
mtdev_%(name)s = probesysfs,provider=mtdev
hid_%(name)s = probesysfs,provider=hidinput

[postproc]
double_tap_distance = 20
double_tap_time = 250
ignore = []
jitter_distance = 0
jitter_ignore_devices = mouse,mactouch,
retain_distance = 50
retain_time = 0
triple_tap_distance = 20
triple_tap_time = 375

[widgets]
scroll_timeout = 250
scroll_distance = 20
scroll_friction = 1.
scroll_stoptime = 300
scroll_moves = 5

[modules]


I have no clue why nothing is displayed.

**Comment by horsetailfiddlehead** [comment]
The Raspberry Pi automatically outputs the screen to the HDMI port. The
Kivy docs suggest this output can be redirected, but I've not been able to
make that work.

I've resorted to using a program called fbcp to copy the display from fb0
to fb1.I just start and run it in the background.

**Comment by guma44** [comment]
Thanks a lot, this thingy with redirection of buffers worked out! I needed only to adjust the rotations of the kivy and it is now really good. I think somebody can close this.

**Comment by akshayaurora** [comment]
@kived we have `dummy` clipboard which does copy/paste within kivy.
