### ISSUE TITLE
I can't understand how to get to work my code into kivy

### ISSUE THREAD

**Issue by dimoxa1100** [kivy/kivy#4051]
I just found out recently about kivy. Python i'm also studing recently. I would like application, made into kivy, which has 2 boxes for input text and returning a label with result after clicking a button. This code must be in him:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - -  - - - - 
     def word_detect(a,b):
           y = []
           e = []
           s = []
           for counter in range(len(b)):
                z = []
                for word in a:
                      ml = 0
                      index = -1
                      for letter in word:
                            index += 1
                            if letter == (b[counter])[index]:
                                 ml += 1
                      if ml == int((b[counter])[-1]):
                            z.append(word)
                y.append(z)
                e.extend(z)
           for i in e:
                if (y[0]).count(i)==(y[1]).count(i)==(y[2]).count(i)==1 and s.count(i)==0:
                      s.append(i)
           return s

     print word_detect(raw_input('list:   '). upper().  split(','),raw_input('words:  '). upper(). split(','))
'''
e.g:
list : total,relax,mixer,remix,scope,candy,water
words: helix 3, botex 1, below 2

result: ['relax']

RELAX
hELiX - 3 matched letters
boteX - 1 matched letter
bELow - 2 matched letters
'''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - -  - - - -

**Comment by dessant** [comment]
Github issues are for bug reports, for support questions please use the dedicated channels: https://github.com/kivy/kivy#support.
