### ISSUE TITLE
Version kivy 1.9.1 not work.

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#4058]
Version kivy 1.9.0 was installed. It works great! Later installed version. 1.9.1. Everything collapsed!
This is the result of a simple box with a button (Hello, world!):

![222](https://cloud.githubusercontent.com/assets/16930280/13543607/d38d3fae-e27d-11e5-938a-a9707a62c4b4.png)

Now to work, and I'm sitting, install different versions of libraries to run the Kiwis! How to solve a problem?

**Comment by matham** [comment]
You need to provided information at least about the os, python version, how you installed kivy and example code that causes this. Without that it's impossible to figure out the issue.

**Comment by HeaTTheatR** [comment]
Install: 

gstreamer 0.10...
cython 0.20
PyEnchant 1.6.5
libgl1-mesa-dev 10.1.3
libgles2-mesa-dev 10.1.3
python-gst 0.10
pygame 1.9.1
python-opengl 3.0.2
python-setuptools 3.3

**Comment by HeaTTheatR** [comment]
Python 2.7, Linux Mint 17.1 (rebecca)

**Comment by HeaTTheatR** [comment]
Here is a simple code:

`
import kivy
kivy.require('1.9.1')  # replace with your current kivy version !

from kivy.app import App
from kivy.uix.button import Button


class MyApp(App):
    def build(self):
        return Button(text='Hello World')

if __name__ == '__main__':
    MyApp().run()
`

Just updated version of kiwifruit through Synaptic program.

**Comment by dessant** [comment]
Which installation guide are you following (link)? Some of those are deprecated deps.
Also share a debug log.

**Comment by HeaTTheatR** [comment]
Извините, я плохо говорю по-английски...
Вот лог:

[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <2.1 Mesa 10.1.3>
[INFO              ] [GL          ] OpenGL vendor <nouveau>
[INFO              ] [GL          ] OpenGL renderer <Gallium 0.4 on NV49>
[INFO              ] [GL          ] OpenGL parsed version: 2, 1
[INFO              ] [GL          ] Shading version <1.20>
[INFO              ] [GL          ] Texture max size <4096>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Audio       ] Providers: audio_pygame (audio_pygst, audio_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: pygame
 /usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
   import gobject._gobject
[INFO              ] [Video       ] Provider: pyglet(['video_pygst', 'video_ffmpeg', 'video_ffpyplayer'] ignored)
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Base        ] Start application main loop
[INFO              ] [Base        ] Leaving application in progress...

**Comment by aarondiazr** [comment]
maybe the problem its graphics drivers of your computer or OpenGL version that you have installed.

**Comment by HeaTTheatR** [comment]
But version 1.9.0 worked.

**Comment by dessant** [comment]
We still don't have the required info to debug this, how did you install kivy, which installation guide have you followed etc.

Try uninstalling kivy and all it's dependencies, then install it from the ppa:
https://kivy.org/docs/installation/installation-linux.html#ubuntu-kubuntu-xubuntu-lubuntu-saucy-and-above

If the issue will still be there, open a new bug report.
