### ISSUE TITLE
Underlined text on Label doesn't work

### ISSUE THREAD

**Issue by aarondiazr** [kivy/kivy#4059]
Hi!

I'm trying to use markup text on Label class, but the tag [u][/u] not working properly, this show the label without changes on style text.

For example:

`root = Builder.load_string('''
Label:
    text:
        ('[b]Hello[/b] [color=ff0099]World[/color]\\n'
        '[color=ff0099]Hello[/color] [b]World[/b]\\n'
        '[u]Hello[/u] [color=ff0099]World[/color]')
    markup: True
    font_size: '64pt'
''')`

this show '[u]Hello[/u] World' in the last line.

I'm using Kivy 1.9.1

**Comment by pythonic64** [comment]
Underline wasn't implemented in 1.9.1 version, so you'll have to use master branch.

**Comment by aarondiazr** [comment]
oh, I didn't know it. Thanx!
