### ISSUE TITLE
ProxyImage/Loader should have on_error event

### ISSUE THREAD

**Issue by thecodingwizard** [kivy/kivy#4062]
Following [this](https://kivy.org/docs/api-kivy.loader.html) guide.

Here's the basic code (for an intercom system):

```
def update(self, dt):
        self.proxyImg = Loader.image(myUrl, nocache=True)
        self.proxyImg.bind(on_load=self.image_loaded)

def image_loaded(self, proxyImage):
    if proxyImage.image.texture:
        self.image.texture = proxyImage.image.texture
        pass
    if not self.paused:
        Clock.schedule_once(self.update, 1.0 / 30.0)
```

I noticed that the Loader/ProxyImage class doesn't have an `on_error` event (only `on_load`) which is troublesome.

The issue: if `myUrl` fails to load, then there is no way for me to signal that to the user/retry.

Looking into the code, it should be fairly simple to implement: In [`loader.py`](https://github.com/kivy/kivy/blob/master/kivy/loader.py#L348) line `348` the `Loader` class logs an exception. It would be nice if it also notified the ProxyImage that the image has failed to load.

**Comment by dessant** [comment]
Same as https://github.com/kivy/kivy/issues/1735.

**Comment by dessant** [comment]
Let's track this at https://github.com/kivy/kivy/issues/2991.
