### ISSUE TITLE
How to reinstall Kivy?

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#4065]
Guys, what libraries should I remove with Kivy, to reinstall it? I have already removed half of the system! :)

**Comment by dessant** [comment]
Unnistalling depends on how you've installed kivy, we can't really help unless you share more details.
Follow the advice from here https://github.com/kivy/kivy/issues/4058#issuecomment-192888304 and you should have a working kivy installation.

Please use github issues for reporting bugs only, if you have further support questions, use the right channels: https://github.com/kivy/kivy#support.
