### ISSUE TITLE
Disabling readonly on Double Tap in TextInput; backspace remains disabled

### ISSUE THREAD

**Issue by senc22** [kivy/kivy#4069]
Found a strange issue in TextInput when trying to implement a double tap text entry by utilizing readonly. When double tapped entering text works fine, while backspace is still disabled. A crude way of fixing this is to unfocus and focus textinput.  For reproducability, please find the code below.

Kivy v1.9.1
Python v2.7.10
Windows 10

```python
from kivy.uix.textinput import TextInput
class DoubleTapInput(TextInput):
    def __init__(self,**kwargs):
        super(DoubleTapInput,self).__init__(**kwargs)
        self.readonly=True
        self.txt_Dbl_Tap = False
    
    def on_double_tap(self):
        if self.txt_Dbl_Tap == False:
            self.readonly=False
            #self.focus = False  
            #self.focus = True
            self.txt_Dbl_tap = True
```

**Comment by dessant** [comment]
The problem is that the `on_double_tap` method is not empty in the source, so you're overriding some code.
The solution is to call super at the start of your method, then continue with your custom code, or copy over the source and customize it to your needs.
https://github.com/kivy/kivy/blob/4789b548fa18eae6d3fe3ad121bd2a3f1ff9c6cd/kivy/uix/textinput.py#L1252

**Comment by dessant** [comment]
Please share a runnable app example that shows your issue.

**Comment by senc22** [comment]
This simple example shows my issue;
```Python
from kivy.app import App
from kivy.uix.textinput import TextInput
class DoubleTapInput(TextInput):
    def __init__(self,**kwargs):
        super(DoubleTapInput,self).__init__(**kwargs)
        self.readonly=True
        self.txt_Dbl_Tap = False
    
    def on_double_tap(self):
        super(DoubleTapInput,self).on_double_tap()
        if self.txt_Dbl_Tap == False:
            self.readonly=False
            #self.focus = False
            #self.focus = True
            self.txt_Dbl_tap = True
        
class ExApp(App):
    def build(self):
        return DoubleTapInput()

if __name__ == '__main__':
    ExApp().run()
```
If double tapped the text entry works, however, backspace is disabled. The workaround is to refocus by  `self.focus = False` and  `self.focus = True` where backspace is enabled.  However, this is a crude way as it unnecessarily triggers the 'on_focus'. As on_focus is triggered, this leads to the problem where to set `self.readonly=True` and `self.txt_Dbl_Tap = False` when the user truly is unfocusing.

**Comment by dessant** [comment]
@senc22, thanks, I can reproduce the bug with your example.
