### ISSUE TITLE
Brittle kv import Syntax

### ISSUE THREAD

**Issue by FluxIX** [kivy/kivy#4072]
The kv import syntax is very brittle and the error messages in the exceptions do not describe the errors in sufficient detail to address syntax errors.

Using regular expressions to parse the file, line by line, would make the syntax more forgiving of common errors.

**Comment by kived** [comment]
Do you have logs, examples, etc?

**Comment by FluxIX** [comment]
The line "#:import Button  kivy.uix.button" will fail to parse because of a superfluous space character present.

If the regex looked something like (I'm doing this quickly without giving it a full analysis) r"\s*#:\s*import\s+(?P<alias>[_a-zA-z][_0-9a-zA-Z]*)\s+(?P<package>\.*(?:[_a-zA-z][_0-9a-zA-Z]*)(?:\.(?:[_a-zA-z][_0-9a-zA-Z]*))*)\s*", it would handle at least common formatting differences without changing the current functionality.

**Comment by FluxIX** [comment]
The name "package" in the import attempts is somewhat deceptive as the "package" selection actually contains potentially package and module, which makes determining error causes more difficult.
