### ISSUE TITLE
Typo in Kivy's Application section; user_data_dir

### ISSUE THREAD

**Issue by bearnun** [kivy/kivy#4075]
In [docs referencing user_data_dir](https://kivy.org/docs/api-kivy.app.html), shouldn't...:

"On iOS, ~/Documents<app_name> is returned (which is inside the app’s sandbox)."

...actually be:

"On iOS, ~/Documents/<app_name> is returned (which is inside the app’s sandbox)."

(Missing forward-slash before <app_name>)

**Comment by dessant** [comment]
@thanks, nice find.
