### ISSUE TITLE
Loader.stop() causes the application to freeze when loading URL

### ISSUE THREAD

**Issue by thecodingwizard** [kivy/kivy#4076]
If you pass an invalid url to `Loader.image()` and then call `Loader.stop`, the app freezes and crashes.

For example:

    Loader.image("http://192.168.15.23", nocache=True)     # 192.168.15.23 should not exist
    Clock.schedule_once(lambda: Loader.stop(), 1)

The app will freeze until it times out. Attempting to close it by clicking the "X" button will give you an option to force quit or wait.

Full example:

    from kivy.app import App
    from kivy.clock import Clock
    from kivy.loader import Loader
    from kivy.uix.button import Button

    class MyApp(App):
        def build(self):
            Loader.image("http://192.168.15.23/nonexistant_ip.jpg", nocache=True)
            Clock.schedule_once(lambda dt: Loader.stop(), 1)
            return Button(text="Hello World")

    MyApp().run()

Notice how for one second you can click the button, then it freezes.

**Comment by kived** [comment]
Calling `Loader.stop()` results in a `join()` call on the thread `Queue`. `urlopen` is blocking and will not return until it finishes or times out, and therefore the thread cannot be joined until such time.

**Comment by KeyWeeUsr** [comment]
@thecodingwizard Does it still freeze? I don't experience such behavior and I think it was fixed either by https://github.com/kivy/kivy/commit/72d99b58296e0e6d575b62ad0b1b68670bdcf2c9 or by https://github.com/kivy/kivy/commit/894d5243801403aae884db24df9fe9137e6df0eb. If there's no such problem, please close the issue :)
