### ISSUE TITLE
HIDInputMotionEventProvider class should include "absolute" options (fixes eGalax problems)

### ISSUE THREAD

**Issue by dgoadby** [kivy/kivy#4078]
I am using an eGalax touch screen. Linux recognises this USB device ok. The problem is the eGalax touch co-ordinates are absolute so getting the calibration right involves telling Kivy the absolute upper and lower limits of X & Y. 

To add my eGalax touch to the config.ini [Input] section I need to add:

`eGalax=hidinput,/dev/input/event2,invert_x=1, min_abs_x=112,max_abs_x=1949,min_abs_y=166,max_abs_y=1877`

The problem is although the ?_abs_? tokens included in the code and are checked for, they are not included in the list of valid options for the HIDInputMotionEventProvider class so any use of them is rejected with an error message.

This is the current class:

`class HIDInputMotionEventProvider(MotionEventProvider):
        options = ('min_position_x', 'max_position_x',
                   'min_position_y', 'max_position_y',
                   'min_pressure', 'max_pressure',
                   'invert_x', 'invert_y', 'rotation')`

The fix is simple, just add the ?_abs_? options to the class like this:

`class HIDInputMotionEventProvider(MotionEventProvider):
        options = ('min_position_x', 'max_position_x',
                   'min_position_y', 'max_position_y',
                   'min_pressure', 'max_pressure',
                   'min_abs_x', 'max_abs_x',
                   'min_abs_y, 'max_abs_y',
                   'invert_x', 'invert_y', 'rotation')`

I have applied this change to my code and it solves the problem and there are no side effects I can see.

The eGalax touch screen controller is becoming popular, because it is cheap. As the code was clearly written to handle absolute X & Y then I see no reason why this change cannot be made permanent.

**Comment by dgoadby** [comment]
Excuse me if this is a daft question. As this issue is now on the 2.0.0. milestone, do I need to do anything further? I see some issues create "pull" requests. For my future reference what determines if a pull request is required?

**Comment by inclement** [comment]
That marker indicates that we intend to fix it as a priority for that release. A pull request is created when someone writes the fix code and proposes it as an addition to this master repository. On github in particular this comes with its own nice UI indicating what changes are being made, but the core functionality is managed by git. You don't need to make a pull request, but someone will do so when they want to propose a change that fixes the issue.

**Comment by tshirtman** [comment]
closing as #5652 was merged, please reopen if needed.
