### ISSUE TITLE
"ImportError: cannot import name bcm" error with running basic kivy app in ubuntu 15.04

### ISSUE THREAD

**Issue by tanayz** [kivy/kivy#4085]
Hi
I've followed the kivy installation guide for ubuntu from kivy website and subsequently installed the latest version present in pip and upon running a basic code as simple as this

from kivy.app import App
App().run()

I got below error.Is this something to do with kivy upgrade? As a previous version is running fine in my other ubuntu 15.04 pc.Any help to fix this will be appreciated.

[INFO              ] [Logger      ] Record log in /home/tanay/.kivy/logs/kivy_16-03-13_2.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pil (img_sdl2, img_ffpyplayer ignored)
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name bcm
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/kivy/core/**init**.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - ImportError: /home/tanay/anaconda2/lib/libreadline.so.6: undefined symbol: PC
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/kivy/core/**init**.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

x11 - ImportError: No module named window_x11
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/kivy/core/**init**.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL          ] [App         ] Unable to get a Window, abort.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

To exit: use 'exit', 'quit', or Ctrl-D.

**Comment by udiboy1209** [comment]
@tanayz I think the real error is that kivy can't find a window provider. `x11 - ImportError: No module named window_x11`. From the looks of it kivy is trying to use SDL2, so ensure you have it correctly installed. [Here's how to do it](https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2)

**Comment by tanayz** [comment]
I've already done that earlier,still the error remains same.

**Comment by arun10797** [comment]
you can just uninstall all the packages by uninstalling your python software and deleting its files from 
c :/drive and reinstall it in proper sequence as it is mention on professional kivy website 
i am dammed sure it will work

**Comment by tanayz** [comment]
@arun10797 I'm talking about ubuntu here,not windows!

**Comment by laerus** [comment]
trying to run kivy on debian-stable under wayland/weston and i get the same import error. kivy works under Xorg/xfce4 on the same machine. any idea what is missing?

**Comment by jMyles** [comment]
I'm also having this issue on ubuntu.  I have installed the requirements shown for SDL2 via apt-get (ie, [this list](https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2))

**Comment by laerus** [comment]
i managed to solve my issue by using the kivy and pygame debian-testing packages under python2. no luck under py3 yet.

**Comment by jMyles** [comment]
@laerus: It seems to work for me with SDL2 with Python 2.  But no dice on Python 3.  I haven't tried with pygame.  What are the disadvantages of using pygame as compared with SDL2?

**Comment by dessant** [comment]
if you still have this issue, please reopen with an exact way to reproduce, from the distro image you used to the installation commands and code you ran.

**Comment by MaximeCheramy** [comment]
Same issue with Debian Testing, installed with `apt install python3-kivy python3-sdl2`.
Code is just:

```python
from kivy.app import App
from kivy.uix.widget import Widget


class PongGame(Widget):
    pass


class PongApp(App):
    def build(self):
        return PongGame()


if __name__ == '__main__':
    PongApp().run()
```

**Comment by najamansari** [comment]
Solved on Fedora 26 by installing the following packages (in addition to normal build tools and Python development packages):

1. SDL2-devel
2. SDL2_ttf-devel
3. SDL2_image-devel
4. SDL2_mixer-devel
5. gstreamer1-devel

Hope this helps

**Comment by bastosvinicius** [comment]
sudo pip install pygame

**Comment by laerus** [comment]
@bastosvinicius kivy is not supposed to have pygame as a dependency anymore

**Comment by dilantha111** [comment]
This error still exist. It's working on python2 but no luck with python3

**Comment by titimoby** [comment]
Ubuntu 17.04
Python 3.5.3
following the installation instruction lead to the same error:
```
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

```

**Comment by dessant** [comment]
@titimoby, you have installed an older version of Kivy, make sure to follow docs and install Kivy 1.10.0.
https://kivy.org/docs/installation/installation-linux.html

This thread will be locked, if you can reproduce the bug with the latest version of Kivy, please open a new issue.
