### ISSUE TITLE
Samsung Galaxy Note 5 Android 5.1.1 - ScrollView + ButtonBehavior misbehaving

### ISSUE THREAD

**Issue by bl2ead** [kivy/kivy#4087]
Not sure if this is the same issue that was highlighted in #4031.

On a Samsung Note 5 running Android 5.1.1, when i use a Scrollview with some Buttonbehavior child widgets, i need to tap extremely quickly in order to trigger the button touch event. if my finger rests on the screen any longer, it gets interpreted as a scroll instead.

I have tried the exact same app on the following devices with no issue:
Samsung Galaxy S4 - Android 5.1.1 (rooted)
Samsung Note 3 - Android 4.4.2
Xiaomi Mi Note - Android 4.4.4

**Comment by dessant** [comment]
Let's track this bug at https://github.com/kivy/kivy/issues/4031.
