### ISSUE TITLE
Supporting module logs

### ISSUE THREAD

**Issue by ngoonee** [kivy/kivy#4102]
Kivy uses the 'logging' module, which is convenient. However, it does so by redefining logging.root (towards the end of logger.py). This is not so convenient.

I'm trying to write modules which don't depend specifically on Kivy (business code as contrasted with UI code). The 'standard' advise for doing so is to get a named logger and use it (preferably with a NullHandler added).

    import logging
    logger = logging.getLogger(__name__)
    logger.info('testing the logger output')

This doesn't output anything when using the module inside Kivy, because the default 'logging' module behaviour of all loggers being a child of root is now busted.

Related kivy issue - https://github.com/kivy/kivy/issues/2480

If I've missed a way to configure Kivy's logger such that the above module code would work with no change, please let me know, I've already asked the list and gotten some workarounds which would be at the module level but would prefer to solve this at the app level (for portability, this module WILL be used in other UIs in future).

**Comment by zeeMonkeez** [comment]
Does using `logger = logging.getLogger().getChild(__name__)` solve your issue? (More in depth discussion on [StackOverflow](http://stackoverflow.com/questions/36106353/using-python-logging-when-logging-root-has-been-redefined-kivy)

**Comment by zeeMonkeez** [comment]
`logging.Logger.manager.root = Logger` (where `Logger` is the one imported from `kivy.logger`) should make logging transparent; a logger created with `logging.getLogger` will always have the kivy logger as root. Question is why this assignment is not made in `kivy.logger` (oversight or good reasons).

**Comment by ngoonee** [comment]
Thanks @zeeMonkeez, that works. In fact it should probably be the default (in my opinion).

In fact now that I look at how Logger is being used internally, every single call to logger has to specify where it's being called from (the message looks something like "Support: This happened" or "Atlas: texture updated"). Seems like using module names would help here.
