### ISSUE TITLE
Why right click will appear red dot。

### ISSUE THREAD

**Issue by githubzhaoqian** [kivy/kivy#4105]
Why right click will appear red dot.
They are can drag and left-click to disappear.

The default case also has this kind of phenomenon.
D:\Python2.7.10\share\kivy-examples\application\app_with_build.py

Do you have this kind of problem? Or this is my personal problem?

I'm afraid you can't send pictures。

**Comment by werton** [comment]
This not a problem, this is feature!
By default, the middle and right mouse buttons, as well as a combination of ctrl + left mouse button
are used for multitouch emulation. If you want to use them for other purposes, you can disable this
behavior by activating the “disable_multitouch” token:
[input]
mouse = mouse,disable _ multitouch
You can read more in the manual.
