### ISSUE TITLE
Svg memory leak

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy#4110]
Each time the color property is updated on the Svg object a bit of memory leaks.  when color changes, reload() is called on Svg(); this in turn calls parse_tree() and render(). 

So far from experimentation it seems the leak is isolated in render() ; parse_tree() seems to not leak memory. 

The attached example file + svg object rapidly changes the color of an Svg object and will show the memory leak. 
This was observed on kivy 1.9.0 

[leaktest.zip](https://github.com/kivy/kivy/files/181697/leaktest.zip)

**Comment by FeralBytes** [comment]
Please test that it is still valid for Kivy 1.9.2. Thank you.

**Comment by Julian-O** [comment]
Bumping the request to test on a later version (Kivy 2.2.1).

Please let us know if it is still a problem.
