### ISSUE TITLE
BoxLayout size_hint_x ignored

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4116]
The second button fills the available space, it will also do the same when it is the only children. Other layouts behave as expected in this case, they fill the space according to the size_hint value.

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

kv = """
<Test>:
    Button:
        size_hint_x: None
        width: dp(80)
    Button:
        size_hint_x: 0.5
"""

Builder.load_string(kv)


class Test(BoxLayout):
    pass


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```

**Comment by werton** [comment]
I think this is so by design. size_hint_x is not ignored, just the space of BoxLayout is divided between children widgets in proportion to their size_hint_x, as well as the first button has size_hint_x = None, and BoxLayout has no other children widgets with size_hint_x != 0, the second button takes all remaining space.

**Comment by dessant** [comment]
@werton, all other layouts respect `size_hint_x: 0.5`, I don't see a reason for BoxLayout to ignore size_hint when there are no other children which have a different size_hint value than None.

Please see the docs:
https://kivy.org/docs/api-kivy.uix.widget.html#kivy.uix.widget.Widget.size_hint_x

**Comment by dessant** [comment]
If size_hint_y is set, the values for both axes are respected.
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

kv = """
<Test>:
    StackLayout:
        Button:
            size_hint_x: None
            width: dp(80)
        Button:
            size_hint: 0.5, 0.5
"""

Builder.load_string(kv)


class Test(BoxLayout):
    pass


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```

**Comment by dessant** [comment]
I've deleted my previous example, it used StackLayout.

BoxLayout size_hint_y works as expected.

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

kv = """
<Test>:
    Button:
        size_hint_x: 0.5
        size_hint_y: 0.5
"""

Builder.load_string(kv)


class Test(BoxLayout):
    pass


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```

![capture](https://cloud.githubusercontent.com/assets/7513068/14041420/5f233d7e-f279-11e5-9c52-51e26a96be60.PNG)

**Comment by werton** [comment]
This is because it is a horizontal BoxLayout, make it vertical and then will "not work" size_hint_y
I used to think that BoxLayout fills their space, if size_hint_ != 0
Yes it looks weird and non-obvious,you could be right, but please note the following note in manual:

> Note: The size_hint uses the available space after subtracting all the fixed-size widgets. For example, if
> you have a layout that is 800px wide, and add three buttons like this:
> btn1 = Button(text=’Hello’, size=(200, 100), size_hint=(None, None)) btn2 = Button(text=’Kivy’,
> size_hint=(.5, 1)) btn3 = Button(text=’World’, size_hint=(.5, 1))
> 462
> The first button will be 200px wide as specified, the second and third will be 300px each, e.g. 
> (800-200)* 0.5

In next example size_hint_x also gives the wrong Button's width relative to LayoutBox's width. If you offer to strictly follow the instructions of size_hint, then how in this case should behave buttons? get out of BoxLayout border?
```
kv = "" "
<Test>:
     Button:
         size_hint_x: 0.9
     Button:
         size_hint_x: 0.5
"" "
```

**Comment by dessant** [comment]
@werton, in you example the space should be proportionally divided between children, size_hint behaves differently if there are more than one children, by design.

**Comment by werton** [comment]
Ok, but your fix will breaks the previously written code. Some users used this feature to pick up the widgets in BoxLayout to the top, without using StackLayout :'(
```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

kv = """
<Test>:
	orientation: 'vertical'

    Button:
		text: 'Im the top Button!'
        size_hint: 1, None
		
    Button:
		text: 'Im not the top button :('
        size_hint: 1, None	
		
	Widget:
		size_hint: 1, 1
"""

Builder.load_string(kv)


class Test(BoxLayout):
    pass

class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    TestApp().run()

```

**Comment by dessant** [comment]
@werton, i think it will not break anything if the user relies on the size_hint documentation, relying on a bug is not recommended. size_hint_y is respected regardless of the orientation, as it should, while size_hint_x is not.

**Comment by werton** [comment]
>  size_hint_y is respected regardless of the orientation

did you check?

```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

kv = """
<Test>:
	orientation: 'vertical'
    Button:
		
        size_hint_x: 0.5
        size_hint_y: 0.5
"""

Builder.load_string(kv)


class Test(BoxLayout):
    pass


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```
now size_hint_y is not respected, right?

I paraphrased my example, as you have in this case must be the widgets? If Button 2 to take the all width of BoxLayout(), where should be the button 2? Lay on top, or to get out of bound of BoxLayout? How is this case different from your first that size_hint_x = 1 rather than 0.5? Because of this rule change?

```
kv = """
<Test>:
    Button:
		text: 'button1'
        size_hint_x: None

    Button:
		text: 'button2'	
        size_hint_x: 1
"""
```

**Comment by dessant** [comment]
@werton i did check, but it seems i've messed up the code, size_hint_y is not respected indeed in your example.

**Comment by werton** [comment]
@dessant 
yes, but you didn't answer my questions at the end of the previous post.

**Comment by dessant** [comment]
@werton, i thought size_hint in boxlayout behaves like size hint in stacklayout, regardless of the orientation.

**Comment by dessant** [comment]
@werton, i've wrongly assumed things and i'll bear the consequences until my last breath :wink:, thanks for standing up, it's important to challenge each other's assumptions.

**Comment by werton** [comment]
Hooray, I don't have to write their own implementation of the BoxLayout.  thanks for the discussion :)
