### ISSUE TITLE
Unable to get a Window, abort.

### ISSUE THREAD

**Issue by AFAgarap** [kivy/kivy#4123]
![deepinscreenshot20160329222418](https://cloud.githubusercontent.com/assets/11130276/14111385/183c13fe-f5fd-11e5-920d-715e33ffb1b3.png)
![deepinscreenshot20160329222429](https://cloud.githubusercontent.com/assets/11130276/14111387/18d005be-f5fd-11e5-9b0c-bea21f08904b.png)
![deepinscreenshot20160329222433](https://cloud.githubusercontent.com/assets/11130276/14111386/183c4f04-f5fd-11e5-8aea-0e2d25fa9a8b.png)

Kivy is not working. Version is 1.9.0

**Comment by AFAgarap** [comment]
First screenshot: I tried the proposed solution from issue #3002 by "kived" -- "The newer packages are building with SDL2 support and without pygame support. I'm guessing the deps on the package didn't get updated. You should be able to fix this for now by running sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0."

Second screenshot: The errors I'm getting when running my Python script with Kivy

Third screenshot: The source code (sample program from Kivy's website)

**Comment by AFAgarap** [comment]
![deepinscreenshot20160329224604](https://cloud.githubusercontent.com/assets/11130276/14112230/769479c0-f600-11e5-9822-4ce66c32c2b3.png)

In Python 2, it's okay though. Weird?

**Comment by AFAgarap** [comment]
I'm running Deepin OS btw, the 15.1 version.

**Comment by dessant** [comment]
Try installing the latest version of Kivy (1.9.1) and its dependencies, maybe use the ppa, and reopen if you still have issues.
https://kivy.org/docs/installation/installation-linux.html

**Comment by AFAgarap** [comment]
Problem is I cannot use ppa. It says that there's no command as add-apt-repository. Sorry, this is Deepin OS.

**Comment by AFAgarap** [comment]
I tried the following solution, but it didn't work as well. The upgrade fails.
`sudo pip3 install --upgrade kivy`

**Comment by thopiekar** [comment]
To be honest I don't understand why people have to install the libsdl* libraries by hand.
The ```python*-kivy-bin``` packages need these ```libsdl-*``` packages.

See:
![cura10](https://cloud.githubusercontent.com/assets/1847437/14585834/83dccf5a-0484-11e6-8b89-21c567855860.png)

**Comment by AFAgarap** [comment]
It was a suggestion by @kived from #3002
