### ISSUE TITLE
Crash when Slider is imported before forking process on Mac OS X

### ISSUE THREAD

**Issue by zeeMonkeez** [kivy/kivy#4124]
Consider

```
#!/usr/bin/env python2
import multiprocessing
from kivy.app import App

from kivy.uix.slider import Slider

class Test(App):
    def build(self):
        return Slider()

def run_app():
    app = Test()
    app.run()

running_app = multiprocessing.Process(target=run_app)
running_app.daemon = True
running_app.start()
running_app.join()
```

This currently crashes on Mac OS X:

> *** multi-threaded process forked ***
> crashed on child side of fork pre-exec
> USING_FORK_WITHOUT_EXEC_IS_NOT_SUPPORTED_BY_FILE_MANAGER
> 

This is because the property `padding` is initialized with `NumericProperty(sp(16))`. This call to `sp` will attempt to initialize SDL. Cf. [this question on StackOverflow](http://stackoverflow.com/questions/8106002/using-the-python-multiprocessing-module-for-io-with-pygame-on-mac-os-10-7)

**Comment by akshayaurora** [comment]
Can you explain what you are trying to do here?

**Comment by akshayaurora** [comment]
Kivy does not support multiple apps. So simple question what is the intention here? To try and make kivy support multiple apps or ...?

**Comment by akshayaurora** [comment]
ok so simply use subprocess.popen. 
Do you have to use multiprocessing?

**Comment by akshayaurora** [comment]
I guess using multiprocessing makes it easier for you to send messages between the processes there. 

It's just one of the use cases that I haven't seen be used till now, people usually use separate processes of service on mobiles and osc or other options for communication.

If are submitting a pr fixing this then could you please make sure to add a test too?

**Comment by zeeMonkeez** [comment]
@akshayaurora This solution was actually suggested by @inclement (or so I interpreted his comment to [my question on SO](http://stackoverflow.com/questions/34915939/nested-alternating-apps-with-kivy)).

I'd be more than happy to submit a test case. Not sure however what to test for. I suppose there'd be one test for each user interface module to make sure importing before forking works?

**Comment by zeeMonkeez** [comment]
For now, I'll leave both #4127 and #4126 open. I like the latter better for it separates styling from logic. But either one solves my issue.
