### ISSUE TITLE
Packing a kivy app in Windows

### ISSUE THREAD

**Issue by abhigenie92** [kivy/kivy#4128]
Following the docs https://kivy.org/docs/guide/packaging-windows.html

Running: 
```
# -*- mode: python -*-

block_cipher = None
from kivy.deps import sdl2, glew
import pyaudio

a = Analysis(['C:\\Users\\sony\\Dropbox\\notepad_app\\2_Paint\\main.py'],
             pathex=['c:\\Users\\sony\\Dropbox\\notepad_app\\win_exe'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='notepad_app',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe, Tree('C:\\Users\\sony\\Dropbox\\notepad_app\\2_Paint'),
               a.binaries,
               a.zipfiles,
               a.datas,
               *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + pyaudio)],
               strip=False,
               upx=True,
               name='notepad_app')

```

I am getting this error:

```
$ python -m PyInstaller notepad_app.spec
490 INFO: PyInstaller: 3.1.1
490 INFO: Python: 2.7.11
493 INFO: Platform: Windows-10-10.0.10240
499 INFO: UPX is not available.
[INFO              ] [Logger      ] Record log in c:/Users/sony\.kivy\logs\kivy_16-03-30_4.txt
581 INFO: [Logger      ] Record log in c:/Users/sony\.kivy\logs\kivy_16-03-30_4.txt
[INFO              ] [Kivy        ] v1.9.0
536 INFO: [Kivy        ] v1.9.0
[INFO              ] [Python      ] v2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.1500 64 bit (AMD64)]
582 INFO: [Python      ] v2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.1500 64 bit (AMD64)]
 Traceback (most recent call last):
588 WARNING: stderr: Traceback (most recent call last):
   File "c:\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
588 WARNING: stderr:   File "c:\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
588 WARNING: stderr:     "__main__", fname, loader, pkg_name)
   File "c:\Anaconda\lib\runpy.py", line 72, in _run_code
592 WARNING: stderr:   File "c:\Anaconda\lib\runpy.py", line 72, in _run_code
     exec code in run_globals
592 WARNING: stderr:     exec code in run_globals
   File "c:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 97, in <module>
592 WARNING: stderr:   File "c:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 97, in <module>
     run()
598 WARNING: stderr:     run()
   File "c:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 90, in run
598 WARNING: stderr:   File "c:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 90, in run
     run_build(pyi_config, spec_file, **vars(args))
598 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
   File "c:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
602 WARNING: stderr:   File "c:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
602 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
   File "c:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
602 WARNING: stderr:   File "c:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
608 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
   File "c:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
612 WARNING: stderr:   File "c:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
     exec(text, spec_namespace)
618 WARNING: stderr:     exec(text, spec_namespace)
   File "<string>", line 4, in <module>
618 WARNING: stderr:   File "<string>", line 4, in <module>
 ImportError: No module named deps
618 WARNING: stderr: ImportError: No module named deps

```

**Comment by dessant** [comment]
Your Kivy version is outdated, follow the installation docs before packaging.
https://kivy.org/docs/installation/installation-windows.html

**Comment by abhigenie92** [comment]
Following instructions error:
```
$ python -m pip install --upgrade pip wheel setuptools
Error processing line 2 of c:\Anaconda\lib\site-packages\kivy.deps.glew-0.1.4-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "c:\Anaconda\lib\site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'kivy'

Remainder of file ignored
Error processing line 2 of c:\Anaconda\lib\site-packages\kivy.deps.gstreamer-0.1.5-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "c:\Anaconda\lib\site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'kivy'

Remainder of file ignored
Error processing line 2 of c:\Anaconda\lib\site-packages\kivy.deps.sdl2-0.1.12-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "c:\Anaconda\lib\site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'kivy'

Remainder of file ignored
[INFO              ] [Logger      ] Record log in c:/Users/sony\.kivy\logs\kivy_16-03-30_15.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.1500 64 bit (AMD64)]
 Traceback (most recent call last):
   File "c:\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
   File "c:\Anaconda\lib\runpy.py", line 72, in _run_code
     exec code in run_globals
   File "c:\Anaconda\lib\site-packages\pip\__main__.py", line 19, in <module>
     sys.exit(pip.main())
   File "c:\Anaconda\lib\site-packages\pip\__init__.py", line 217, in main
     return command.main(cmd_args)
   File "c:\Anaconda\lib\site-packages\pip\basecommand.py", line 179, in main
     for name in ["pip._vendor", "distlib", "requests", "urllib3"]
   File "c:\Anaconda\lib\logging\config.py", line 794, in dictConfig
     dictConfigClass(config).configure()
   File "c:\Anaconda\lib\logging\config.py", line 576, in configure
     '%r: %s' % (name, e))
 ValueError: Unable to configure handler 'console_errors': 'LogFile' object has no attribute 'closed'

```

**Comment by clebersongom** [comment]
estou com o mesmo erro 

(k37) C:\projetosPython>pyinstaller main.spec
128 INFO: PyInstaller: 3.6
128 INFO: Python: 3.7.7 (conda)
129 INFO: Platform: Windows-10-10.0.18362-SP0
133 INFO: UPX is not available.
[INFO   ] [Logger      ] Record log in C:\Users\clebe\.kivy\logs\kivy_20-06-09_79.txt
173 INFO: [Logger      ] Record log in C:\Users\clebe\.kivy\logs\kivy_20-06-09_79.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
167 INFO: [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
174 INFO: [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
176 INFO: [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
177 INFO: [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
178 INFO: [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "c:\users\clebe\.conda\envs\k37\lib\site-packages\kivy\__init__.py"
178 INFO: [Kivy        ] Installed at "c:\users\clebe\.conda\envs\k37\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
179 INFO: [Python      ] v3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "c:\users\clebe\.conda\envs\k37\python.exe"
180 INFO: [Python      ] Interpreter at "c:\users\clebe\.conda\envs\k37\python.exe"
 Traceback (most recent call last):
182 WARNING: stderr: Traceback (most recent call last):
   File "c:\users\clebe\.conda\envs\k37\lib\runpy.py", line 193, in _run_module_as_main
183 WARNING: stderr:   File "c:\users\clebe\.conda\envs\k37\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
184 WARNING: stderr:     "__main__", mod_spec)
   File "c:\users\clebe\.conda\envs\k37\lib\runpy.py", line 85, in _run_code
184 WARNING: stderr:   File "c:\users\clebe\.conda\envs\k37\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
185 WARNING: stderr:     exec(code, run_globals)
   File "C:\Users\clebe\.conda\envs\k37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
186 WARNING: stderr:   File "C:\Users\clebe\.conda\envs\k37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
187 WARNING: stderr:   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
     run_build(pyi_config, spec_file, **vars(args))
188 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
189 WARNING: stderr:   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
190 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
191 WARNING: stderr:   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
194 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
197 WARNING: stderr:   File "c:\users\clebe\.conda\envs\k37\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
     exec(code, spec_namespace)
207 WARNING: stderr:     exec(code, spec_namespace)
   File "main.spec", line 2, in <module>
209 WARNING: stderr:   File "main.spec", line 2, in <module>
     from kivy.deps import sdl2, glew, gstreamer
211 WARNING: stderr:     from kivy.deps import sdl2, glew, gstreamer
 ImportError: cannot import name 'sdl2' from 'kivy.deps' (c:\users\clebe\.conda\envs\k37\lib\site-packages\kivy\deps\__init__.py)
212 WARNING: stderr: ImportError: cannot import name 'sdl2' from 'kivy.deps' (c:\users\clebe\.conda\envs\k37\lib\site-packages\kivy\deps\__init__.py)
