### ISSUE TITLE
Certain Unicode characters not affecting the label size

### ISSUE THREAD

**Issue by illright** [kivy/kivy#4130]
I've implemented a way to dynamically size TextInputs depending on the text inside of them. But after a little testing I discovered a strange issue. The Unicode smile character ("☺") is ignored for some reason when I refer to the _lines_labels property of a TextInput to get their width. So for example:
![issue](https://cloud.githubusercontent.com/assets/15035286/14143890/fc56bb58-f6a6-11e5-92ff-0c61e4f41788.png)
You can see that normal letters are recognized and the size is increased, but for the smile chars it doesn't work. The font I use is OpenSans-Emoji. [Here](https://groups.google.com/forum/#!topic/kivy-users/N0A0RPXexvs) is the link to the Google Groups post about that.

**Comment by Julian-O** [comment]
@illright: I suspect the font itself has misinformation about emoji widths. Can you try it with a different font?

(The OpenSans-Emoji font doesn't seem to have any updates, or I would recommend upgrading.)

**Comment by illright** [comment]
Afraid I can't, this issue is way overdue :) I became a JS developer in the meantime, I no longer use Kivy
