### ISSUE TITLE
no matching distrubution found for kivy.deps.sdl2 

### ISSUE THREAD

**Issue by genliu777** [kivy/kivy#4133]
OS: win7,  64bit
platform: python 3.5.1 64bit

i follow the installation instruction on https://kivy.org/docs/installation/installation-windows.html#install-win-dist, and get the error:
collecting kivy.deps.sdl2
**Could not find a version that satisfies the requirement kivy.deps.sdl2 (form version: ) No matching distribution founds for kivy.deps.sdl2**

the last py version of sdl2 i find so far is py34!  is there py35 version of it now or in the near future!?

**Comment by dessant** [comment]
See the warning at the top of the page.
