### ISSUE TITLE
Implement seek and get_pos for sdl2 audio

### ISSUE THREAD

**Issue by embryo10** [kivy/kivy#4139]
As I wrote in a [kivy.groups post](https://groups.google.com/forum/#!topic/kivy-users/-u5PFzs3ky8) I could not make the seek method of SoundLoader to work.
python 2.7.11 kivy 1.9.0 WinXPSP3
Providers: audio_pygame
I'm loading and playing a wave file

```
self.player = SoundLoader.load('wav2play.wav')
self.player.play()
```

The wave is playing ok, but if I try
`self.player.seek(15)`
nothing happens.

By using kivy 1.9.1 things got worst.
Now the pos  method (that worked in 1.9.0), returns always 0.
Providers: audio_sdl2

BTW tried pygame directly but it doesn't support seek with wave files (???)
I must be doing something wrong, but what?
Any ideas?
TIA

**Comment by dessant** [comment]
Let's ignore the pygame part, the provider is deprecated.

Could you share a runnable app example which shows your issue with kivy 1.9.1 when the sdl2 audio provider is used?

**Comment by embryo10** [comment]
Here is the code.
You can use whatever wave file Soundloader can play.
What the code is trying to do is to let you set a start offset to play (text input).
The label should show the current position (this worked with 1.9.0 and pygame but not with 1.9.1 and sdl2).

```# coding=utf-8
from __future__ import absolute_import, division, print_function, unicode_literals
from kivy.app import App
from kivy.core.audio import SoundLoader
from kivy.properties import Clock
from kivy.uix.floatlayout import FloatLayout
from kivy.lang import Builder
 
Builder.load_string('''
<Base>:
   TextInput:
       id: sec
       text: '0'
       size_hint: None, None
       width: play.width
       height: dp(30)
       y: pos.top
       center_x: play.center_x
   Label:
       id: pos
       text: '0'
       size_hint: None, None
       width: play.width
       height: dp(30)
       y: play.top
       center_x: play.center_x
   ToggleButton:
       id: play
       text: 'Play' if self.state == 'normal' else 'Stop'
       size_hint: None, None
       size: dp(150), dp(70)
       pos_hint: {'center_x': .5, 'center_y': .5}
       on_state:
           if self.state == 'down': root.play()
           else: root.stop()
''')
 
 
class Base(FloatLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)
        self.player = None
        self.chk_pos = None
 
    def play(self, *args):
        self.player = SoundLoader.load('x.wav')
        self.player.play()
        self.player.seek(int(self.ids.sec.text))
        self.chk_pos = Clock.schedule_interval(self.position, .5)
 
    def stop(self, *args):
        self.player.stop()
        self.player.unload()
        Clock.unschedule(self.chk_pos)
 
    def position(self, *args):
        self.ids.pos.text = str(int(self.player.get_pos()))
 
 
class CheckSound(App):
    def build(self):
        return Base()
 
if __name__ == '__main__':
    CheckSound().run()```

**Comment by dessant** [comment]
`seek` and `get_pos` do not seem to be implemented in the sdl2 audio provider.
https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC65

Meanwhile you could use a provider which supports these apis.
https://github.com/kivy/kivy/blob/master/kivy/core/audio/audio_gstplayer.py
https://github.com/kivy/kivy/blob/master/kivy/core/audio/audio_ffpyplayer.py

**Comment by embryo10** [comment]
How can I change them?

**Comment by dessant** [comment]
You have to set the KIVY_AUDIO env var to your preferred provider, but there may be other things involved, depending on the provider.

How to switch and set up audio providers does not seem to be coherently documented, you might want to open a separate doc issue for that.

**Comment by bionoid** [comment]
Afaik neither of these are straightforward to implement for audio_sdl2.

Mix_SetMusicPosition only works for the music channel, ie if you instantiate MusicSDL2 directly or load a sequenced format like MID, MOD, S3M, etc via SoundLoader. Even then it does different things depending on format (seconds vs pattern number), and won't work at all for WAV.

As for get_pos, I'm not aware of such feature for music or effects, probably the easiest way is to call SDL_GetTicks (or similar) at the time we start playing, but obviously there are challenges with that, such as suspend/resume. Sequenced formats don't even support getting the length, let alone position.

**Comment by dessant** [comment]
@bionoid, thanks for the info, alternatively, we could just document where these apis are supported.

**Comment by embryo10** [comment]
The problem still exists with kivy 1.10.0
The `sdl2` provider does not return `pos` and does not seek.
Using `gstplayer` works, but I couldn't keep the resulting distribution package less than 250MB (it was around 25 with 1.9.0's `sdl2`)
Not practical...

**Comment by rasmuskreiner** [comment]
Also still present in 1.10.1. How likely is it that this is going to be implemented, and in case of this, what would a conservatory timeframe for its implementation?
For the time being: I know that there is a workaround for android, but what about iOS?

**Comment by Julian-O** [comment]
Based on the comments above:

* Implementing for SDL2 would be difficult, and isn't going to happen.
* If it is unclear how to change providers, a separate documentation issue should be raised.

Closing as Not Planned.

**Comment by IVAN-QX** [comment]
I tried to use _check_play() method on MusicSDL2 and SoundSDL2 and it worked
the method is scheduled to call every 0.1 second and return a value when the sound is played
just make a variable pos and method getP()
```
self.sound = SoundLoader.load('file.mp3')
self.sound._check_play = self.getP
def getP(self, value):
    self.pos += value
```
but its need to be more accurate
like call every 0.01 second at least and it will be very fine
for seek() I haven't found away
@Julian-O is it possible to modify that? it will be interesting and I think and hope this is simple

**Comment by Julian-O** [comment]
@IVAN-QX: 

I am not sure what you are asking me. I am not an expert in this area. I am just trying to close tickets that will never get implemented.

Your suggestion seems to require 100 fps, which I don't think the Kivy Clock can normally handle.
Your suggestion seems to require pygame, which ha been deprecated and is planned for removal in Kivy 3.0.0.
I can't see how your answer addresses the original problem: `self.player.seek(15)` wasn't working.

**Comment by IVAN-QX** [comment]
@Julian-O my solution for just get_pos() to implement it
to return the position of sound when it is playing
its possible and have 10 fps
i asked you to say its possible to implement it
for seek() I yeah dont think
but implementing get_pos() I see that is possible
so for that I asked you
