### ISSUE TITLE
The command given in the doc to find the examples directory doesn't seems to work

### ISSUE THREAD

**Issue by lee-pai-long** [kivy/kivy#4140]
In the [documentation](https://kivy.org/docs/installation/installation-linux.html#) at the "Start from the Command Line" paragraph, the command given to find the examples directory :

> python -c "import pkg_resources; print(pkg_resources.resource_filename('kivy', '../share/kivy-examples'))"

doesn't seems to work

The result gives me : 

`/home/vagrant/kivyinstall/lib/python3.4/site-packages/kivy/../share/kivy-examples`

But the directory doesnt exist :

```
(kivyinstall) vagrant@vagrant:~$ ls /home/vagrant/kivyinstall/lib/python3.4/site-packages/kivy/../share/kivy-examples
ls: cannot access /home/vagrant/kivyinstall/lib/python3.4/site-packages/kivy/../share/kivy-examples: 
No such file or directory
```

The dpkg command gives us the right path :

```
(kivyinstall) vagrant@vagrant:~$ sudo dpkg -L kivy-examples
...
/usr/share/kivy-examples
...
```

Maybe it's just on Ubuntu though... I had this difference in Linux Mint 17.2 and Ubuntu 14.04 since LM17.2 is based on Trusty It can be a Ubuntu particularity.

**Comment by Julian-O** [comment]
These instructions are no longer present. Closing as stale.
