### ISSUE TITLE
1.9.1: on_mouse_pos returns incorrect mouse position on high density screens

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy#4143]
On high density platforms, like OSX with retina displays, the on_mouse_pos returns an incorrect value for mouse position.

Attached is a simple app that shows the correct value for a click/move (on_touch_move) vs a hover (on_mouse_pos).  This platform was returning a Density of 2.0 vs 1.0, and 192 DPI vs 96.

A sample app has been attached to illustrate.

This repros on Kivy 1.9.1; works as expected on kivy 1.9.0

Example output:
on_mouse_pos: 791.0:235.0  / width 1600
on_motion: 1584.0:470.0 / width 1600
on_touch_move: 1582.0:470.0 / width 1600
on_motion: 1582.0:470.0 / width 1600

[width_test.py.txt](https://github.com/kivy/kivy/files/203120/width_test.py.txt)

**Comment by johanneshk** [comment]
@brentpicasso for me this fixed it: https://github.com/kivy/kivy/pull/4403/commits/3925930aeca89e1e1276f0e93ea38d338d498bcc

See also my issue: https://github.com/kivy/kivy/issues/4377

**Comment by brentpicasso** [comment]
\o/  glad to see this fixed. I'll keep an eye out on removing my patches when 1.9.2 rolls out.
