### ISSUE TITLE
ScrollView: Imprecise touch events registered as scroll, should propogate touch

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy#4145]
Imprecise touch events - especially on mobile/tablet - require exact accuracy even if the motion is within scroll_distance - they register as scroll events even though they really should be touch.

This leads to a cumbersome and difficult to use experience when dealing with touch aware widgets such as text boxes / buttons, etc. inside a scroll view.

If the scrollView receives a touch event within scroll_distance it should register as a touch.

**Comment by akshayaurora** [comment]
Please provide a reproducible snippet.

**Comment by darkopevec** [comment]
should be fixed in https://github.com/kivy/kivy/pull/4647

**Comment by brentpicasso** [comment]
This is great! thank you for resolving this; it will deal with the perception of lack of responsiveness in Kivy
