### ISSUE TITLE
unknown option "max_touch_minor"  for mtdev input provider

### ISSUE THREAD

**Issue by Triscus** [kivy/kivy#4157]
It seems there is a typo in the mtdev.py provider, the  max_touch_minor option is not recognized.

In Line 92  `min_touch_major` should be replaced with `max_touch_minor`

`options = ('min_position_x', 'max_position_x',
                   'min_position_y', 'max_position_y',
                   'min_pressure', 'max_pressure',
                   'min_touch_major', 'max_touch_major',
                   'min_touch_minor', 'min_touch_major',
                   'invert_x', 'invert_y',
                   'rotation')`

**Comment by KeyWeeUsr** [comment]
This was fixed with #4621.
