### ISSUE TITLE
[RaspberryPI2] Dropdown list doesn't work with original touchscreen 7"

### ISSUE THREAD

**Issue by biank88** [kivy/kivy#4158]
##### Platform details:
- Raspberry 2 + 7" original touch screen display
- KivyPie Version: 0.8 (Kivy framework version: v1.9.2-dev)

##### Problem description:
 the user cannot select any item in the list using the touchscreen.

##### Examples that manifest this issue:
- kivy-examples/widgets/spinner.py
- kivy-examples/widgets/effectwidget.py
- kivy-examples/widgets/unicode_textinput.py
- kivy-examples/demo/kivycatalog
- kivy-examples/demo/touchtracer
- kivy-examples/demo/showcase

Animation for kivyCatalog
![kivycatalog-animation-3](https://cloud.githubusercontent.com/assets/1591429/14378819/8065eeba-fd77-11e5-90ef-2c646e8bd0ed.gif)

Animation for kivyshowcase
![showcase-animation](https://cloud.githubusercontent.com/assets/1591429/14378396/f874ae58-fd74-11e5-8100-59f390fdd1e1.gif)

##### kivy log for spinner.py: 
[log.txt](https://github.com/kivy/kivy/files/208325/log.txt)

**Comment by akshayaurora** [comment]
Can you retest using master?

**Comment by akshayaurora** [comment]
https://github.com/kivy/kivy/pull/4132 should close this. Please re open if the issue still exists.

**Comment by kameron90d** [comment]
I am also having this issue with spinner which inherits from dropdown
on a raspberry pi 3 with 7in original touchscreen 
while running kivy pie distro
