### ISSUE TITLE
center_x and center_y only get updated after window resize

### ISSUE THREAD

**Issue by redfast00** [kivy/kivy#4160]
Expected behaviour: image is centered within the button
Actual behaviour: image only gets centered when the window is resized.
Code:
```python
<TreasureStartScreen>:
    name: 'TreasureStartScreen'
    Button:
        Image:
            source: 'data/clover.png'
            center_x: self.parent.center_x
            center_y: self.parent.center_y
            size: self.parent.height / 2, self.parent.height / 2
```

**Comment by matham** [comment]
This is not really a bug as explain here: https://kivy.org/docs/api-kivy.uix.widget.html#usage-of-widget-center-widget-right-and-widget-top.

**Comment by kived** [comment]
@matham That's not the same thing. If the `Image` `center_x` changes, of course you wouldn't expect the `Button` to move - which is what that example describes. If the `Button` `center_x` changes it should absolutely be updating the `Image` `center_x`.

**Comment by akshayaurora** [comment]
@kived parent does not exist while binding so no binding... rebind = True should solve this.
More to the point he should be using id:
```
Button
    id: big_bugg_butowski
    Image
        center: big_bugg_butowski.center
```

**Comment by dessant** [comment]
This should also be fixed by https://github.com/kivy/kivy/commit/d437e93e8a769fc0a42cc1868f68feda8e4b1c17.
@redfast00, please reopen if your issues persist.

**Comment by dessant** [comment]
@matham matham has pointed out on irc that this behavior is expected and should be documented, because users are having difficulties with it.

**Comment by tito** [comment]
@redfast00 This part of the documentation explain your issue: https://kivy.org/docs/api-kivy.uix.widget.html#usage-of-widget-center-widget-right-and-widget-top
