### ISSUE TITLE
problems with Dropdown and Spinner widgets: Buttons sometimes non-responsive (after upgrade to Kivy 1.9.1)

### ISSUE THREAD

**Issue by xiaogigagagigigo** [kivy/kivy#4161]
I came into trouble with my Dropdown and Spinner widgets building my android-app with buildozer on the prepared lubuntu vm, where the new kivy version 1.9.1. came to be installed.

Before that I used to start my app via Kivy-Launcher (Kivy 1.9.0), which worked fine. But I needed support for cp850 in my app, that's why I changed to buildozer.

Anyway, my Buttons in all Dropdown and Spinner widgets are in Kivy 1.9.1 not responsive in the usual manner. Often they take the touch-input only after multiple attempts, which made my app unusable.

Therefore I downgraded to Kivy 1.9.0 on that ubuntu vm, which restored the old button-behaviour being responive as can be. That way my problem is solved. 
I don't know how Dropdown and Spinner widgets are related to another - do they share some superclasses? Other widgets I use (TextInput, PopUp, Button (outside Dropdown and Spinner), Toggle) aren't affected.

**Comment by akshayaurora** [comment]
closed by https://github.com/kivy/kivy/pull/4132
