### ISSUE TITLE
Some docs are down/broken

### ISSUE THREAD

**Issue by redfast00** [kivy/kivy#4162]
A recent change probably broke the docs. For example: https://kivy.org/docs/api-kivy.uix.scrollview.html

**Comment by andong777** [comment]
I also found this issue today when I searched for TextInput in the doc. It seems docs of some UI components are influenced by the change.

**Comment by NZSmartie** [comment]
[kivy.uix.button](https://kivy.org/docs/api-kivy.uix.button.html) is also affected

**Comment by dessant** [comment]
I've tested in a vm, the bug was introduced with https://github.com/kivy/kivy/pull/4132.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/4171.
