### ISSUE TITLE
RstDocument error

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4169]
@akshayaurora spotted an error which appears right after Kivy Catalog is started.
It was introduced by https://github.com/kivy/kivy/pull/4055.

![untitled-1](https://cloud.githubusercontent.com/assets/7513068/14455028/152c765a-00a6-11e6-8376-25f5e8a19f41.png)

**Comment by udiboy1209** [comment]
@dessant seems like the word-wrapping feature has some bugs with creating newlines. I'd like to look into this in a day or two. 

Btw, how did you trace it back to that PR? I couldn't find any direct link, except for building an older commit on which it works.

**Comment by dessant** [comment]
@udiboy1209, I was suspecting TextInput changes because CodeInput is subclassed from it, and I've tested commits from the module's [commit history](https://github.com/kivy/kivy/commits/master/kivy/uix/textinput.py) until I've seen that the [pr commit](https://github.com/kivy/kivy/commit/fbafea19d3b975d823c74319a2eea25c6846a621) breaks, while the pr's [parent commit](https://github.com/kivy/kivy/commit/e82ef10821c00037c321b949ebe7cde932cff477) works.

**Comment by udiboy1209** [comment]
@dessant I just tested this with a simple TextInput. Same bug occurs ie. The two newlines between `1.4` and `RstDocument` are removed. I will look into this later today.
