### ISSUE TITLE
Raspberry Pi: Unable to get a Window, abort.

### ISSUE THREAD

**Issue by WTRipper** [kivy/kivy#4170]
After installing Kivy as described in the [official installation documentation](https://kivy.org/docs/installation/installation-rpi.html) and running a first try I get an error: "Unable to get a Window, abort."
[Kivy log](https://gist.github.com/WTRipper/ccb16fad57a62eae2ea8e061ec0cd1b3)
[Python output](https://gist.github.com/WTRipper/a1c8278d99e71aea67ec84dbf3923153)
Python file I tried to run:

```
from kivy.app import App
from kivy.uix.label import Label


class SimpleKivy(App):
    def build(self):
        return Label(text="Hello World!")

if __name__ == "__main__":
    SimpleKivy().run()
```

I'm using:
Raspberry Pi 2
Raspbian GNU/Linux 8 (jessie)
Python 2.7.9
Kivy 1.9.1

**Comment by tito** [comment]
There is no log to investigate, we can't do anything. Check the tracker to see if your issue has been resolved first.
