### ISSUE TITLE
TextInput - text duplicating and keyboard needs 2 back press for hidding on Android

### ISSUE THREAD

**Issue by KlashDev** [kivy/kivy#4173]
I'm experiencing problems with TextInputs on Android (5.0.2 on my MotoMaxx aka MotoTurbo).. You should be able to reproduce the problem on Kivy Showcase App too.
To reproduce the issue:
• Open TextInputs screen on Kivy Showcase App;
• Type any text(like blabla) on the first field;
• Press BackButton from the device (1st problem: Nothing happens!!)
• After that, just touch any key on Android's keyboard.. 

Here in my phone, it duplicates 'blabla' when any Android keyboard key is pressed after the back button.

It seems to be an issue related to #3284 and #1773 where @merriam worked on.

+Edit: It's solved by disabling prediction, but I need prediction feature up

**Comment by dessant** [comment]
Isn't this also solved by disabling prediction?

**Comment by dessant** [comment]
> Press BackButton from the device (1st problem: Nothing happens!!)

@KlashDev, only the duplication is solved or this too?

**Comment by KlashDev** [comment]
@dessant, this too

**Comment by dessant** [comment]
@KlashDev, as we discussed on irc, it is an upstream bug, please check if there is a bug report filed on the Android bug tracker (or open one) and possibly link it on the main thread: https://github.com/kivy/kivy/issues/3284.
