### ISSUE TITLE
Unable to find any valuable Window provider at all! on OS X while trying to run kivy-designer

### ISSUE THREAD

**Issue by riccitensor** [kivy/kivy#4177]
OSX 10.11.1 El Capitan, Python 2.7, Kivy installed using https://kivy.org/docs/installation/installation-osx.html
**CONCLUSIONS: I need kivy-designer and (for that reason) I installed kivy-garden to install its module filebrowser. The module is installed, but not seen and thus I am having the errors. Some other people have had this problem as well, but I don't see any solutions.**

After I installed kivy-designer, I run `python main.py` and get 

> Unable to find any valuable Window provider at all!

Then I run (according to the docs): `kivy main.py` to get 

> ImportError: No module named filebrowser

Then I verify it using `garden install filebrowser` to get

> [INFO   ] [Logger      ] Record log in /Users/fenek/.kivy/logs/kivy_16-04-15_7.txt
> [INFO   ] [Kivy        ] v1.9.1
> [INFO   ] [Python      ] v2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46) 
> [GCC 4.2.1 (Apple Inc. build 5577)]
> Garden package already installed in /Users/fenek/.kivy/garden/garden.filebrowser
> Use --upgrade to upgrade.

It seems that FileBrowser is installed, but it does not work.

```
Feneks-MacBook-Pro:garden fenek$ pwd
/Users/fenek/.kivy/garden
Feneks-MacBook-Pro:garden fenek$ ls
garden.FileBrowser  garden.mapview

```

It's also here:

```
Feneks-MacBook-Pro:garden fenek$ pwd
/Applications/Kivy.app/Contents/Resources/venv/garden
Feneks-MacBook-Pro:garden fenek$ ls
garden.FileBrowser  garden.mapview
```

Garden list command says

```
Feneks-MacBook-Pro:garden fenek$ garden list
[INFO   ] [Logger      ] Record log in /Users/fenek/.kivy/logs/kivy_16-04-15_34.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46) 
[GCC 4.2.1 (Apple Inc. build 5577)]
FileBrowser
mapview
```

Then I check `cd Kivy.app/Contents/Resources/venv/bin/` for `FileBrowser`, but nothing is found. Running `garden install filebrowser --upgrade` does not help. `garden uninstall FileBrowser` (and then installing again) does not work, too.

Checking `pip install -r requirements.txt` (according to https://kivy-designer.readthedocs.org/en/latest/installation.html)  shows that all requirements are satisfied. 

Then I checked this one https://github.com/kivy/kivy-designer/issues/25 and re-installed kivy and then all of its modules using `kivy -m pip install` instead of using the `pip install` from Kivy-Designer installation docs - https://kivy-designer.readthedocs.org/en/latest/installation.html That did not help as well.

It appears that this is a known (but unsolved?) problem on OS X - https://www.reddit.com/r/kivy/comments/41f9n2/kivydesigner_install_no_module_named_filebrowser/ 

This one is also related https://github.com/kivy-garden/kivy-garden.github.io/issues/110

**Comment by SepehrHml** [comment]
I had the same problem because garden command install all kivy garden into ~/.kivy/garden/<packages>
and it should be located here : /Applications/Kivy2.app/Contents/Resources/.kivy/<packages>

you can simply run cp -R ~/.kivy/garden /Applications/Kivy.app/Contents/Resources/.kivy/ to fix it for now until the a patch comes for garden.

@dessant i can fix this problem but do i need to open issue on kivy-garden/garden repository ?

**Comment by dessant** [comment]
Tracking at https://github.com/kivy-garden/garden/issues/13.
