### ISSUE TITLE
Sizing for OSX Retina and Non-Retina Screens

### ISSUE THREAD

**Issue by kevincolyar** [kivy/kivy#4178]
I'm looking for guidance for sizing widgets that will look the same on Retina and non-Retina displays.  For example, I'm having a rough time sizing text inputs to where the text is not cut off vertically when view on a Retina screen, but on non-Retina screens they look fine.

**Comment by akshayaurora** [comment]
Use kivy.metrics.dp/sp/cm/inch...

Please use the issue tracker for issues not from support, use either #kivy on irc or on google group kiva-users.
