### ISSUE TITLE
sensing touch pos is inconsistent in DropDown()

### ISSUE THREAD

**Issue by coffeebenzene** [kivy/kivy#4190]
When using `DropDown`, I noticed that sometimes the button presses are not sensed well. In an effort detect the actual touch position to debug, I gave the button `on_touch_down` and `on_touch_up` callbacks. I noticed that the position are inconsistent for touch up events.
According to https://kivy.org/docs/api-kivy.input.motionevent.html?highlight=pos#kivy.input.motionevent.MotionEvent.pos the `pos` should refer to the window range. However, it seems to refer to the `DropDown()` range after a quick press and the window after a long press. This is not consistent.

    # This is after a quick press
    <__main__.DropButton object at 0x02EE51B8> touchdown (8.0, 191.0) ['pos', 'button']
    <__main__.DropButton object at 0x02EDF340> touchdown (8.0, 191.0) ['pos', 'button']
    <__main__.DropButton object at 0x02ED64C8> touchdown (8.0, 191.0) ['pos', 'button']
    <__main__.DropButton object at 0x02EC8650> touchdown (8.0, 191.0) ['pos', 'button']
    <__main__.DropButton object at 0x02E90298> touchdown (8.0, 191.0) ['pos', 'button']
    <__main__.DropButton object at 0x02E90298> touchdown COLLIDE
    <__main__.DropButton object at 0x02E90298> touchup (8.0, 191.0) ['pos', 'button']
    <__main__.DropButton object at 0x02E90298> touchup COLLIDE
    
    # This is after a held press
    <__main__.DropButton object at 0x02EE51B8> touchdown (9.999999999999943, 186.99999999999994) ['pos', 'button']
    <__main__.DropButton object at 0x02EDF340> touchdown (9.999999999999943, 186.99999999999994) ['pos', 'button']
    <__main__.DropButton object at 0x02ED64C8> touchdown (9.999999999999943, 186.99999999999994) ['pos', 'button']
    <__main__.DropButton object at 0x02EC8650> touchdown (9.999999999999943, 186.99999999999994) ['pos', 'button']
    <__main__.DropButton object at 0x02E90298> touchdown (9.999999999999943, 186.99999999999994) ['pos', 'button']
    <__main__.DropButton object at 0x02E90298> touchdown COLLIDE
    <__main__.DropButton object at 0x02E90298> touchup (409.99999999999994, 266.99999999999994) ['pos', 'button']

The attached .txt file is my .py file for testing. (github only accepts .txt)
[dropdown_example.txt](https://github.com/kivy/kivy/files/225209/dropdown_example.txt)

Attached is also the log: (I removed my name from the log)
[log.txt](https://github.com/kivy/kivy/files/225218/log.txt)

**Comment by dessant** [comment]
Let's track this bug at https://github.com/kivy/kivy/issues/4031.
