### ISSUE TITLE
App.get_running_app().stop() @ sdl2

### ISSUE THREAD

**Issue by AndreMPCosta** [kivy/kivy#4194]
Using this in the new android toolchain makes the app to crash appearing the window "Unfortunately, App X has stopped."

It worked fine using pygame, with sdl2 it doesn't.

**Comment by dessant** [comment]
@inclement, was this a known issue?

**Comment by kived** [comment]
It's known to me at least. Though this bug report should include the actual output of the crash from logcat, but I suspect it's the issue where a Python thread is still running (or some code is calling CPython functions) after the interpreter shutdown, leading to a seg fault.

**Comment by dlparker** [comment]
I am seeing this as well, and kived's speculation about the segfault is correct.

My app has an r-u-sure popup that asks the user for exit confirmation, and when the user says yes, the popup calls app.stop(). The crash is a segfault resulting from an onPause call in the SDL library after the python exit has happened. See attached logcat output.

I tried following the pattern of calling Window.close() as suggested in https://github.com/kivy/python-for-android/issues/734
 but it made no difference.

[crash3.txt](https://github.com/kivy/kivy/files/1559729/crash3.txt)

**Comment by germn** [comment]
@dlparker I managed to fix it in my app somehow.

1) Redefine your app `stop` method this way:

```
class MyApp(App):
    def stop(self, *largs):
        self.root_window.close()  # Fix app exit on Android.
        return super(MyApp, self).stop(*largs)
```

2) Use  `stopTouchApp` instead of `app.stop` (needed to avoid multiple `on_stop` dispatches):

```
from kivy.base import stopTouchApp

stopTouchApp()
```

---
You may be also interested in [this PR](https://github.com/kivy/kivy/pull/4927). It'll fix home button exit if your app doesn't support sleep mode.

**Comment by ssunilgupta22** [comment]
Yes ! self.root_window.close()  method is working !
