### ISSUE TITLE
Bind on window @ sdl2

### ISSUE THREAD

**Issue by AndreMPCosta** [kivy/kivy#4195]
Trying to bind on_keyboard event:

Window.bind(on_keyboard=sample_func) this causes:  [Window      ] Provider: sdl2 I/python  (18217): [CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!

On another smartphone works fine.

**Comment by 2n2u** [comment]
F/libc    ( 6801): Fatal signal 11 (SIGSEGV) at 0x68727000 (code=1), thread 6856 (SDLThread)
E/InputDispatcher(  508): channel '42433cd0 org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by akshayaurora** [comment]
could you please paste the entire error log

**Comment by 2n2u** [comment]
http://pastebin.com/jd82FVJp

**Comment by kived** [comment]
That's not the entire error. In particular it's missing the entire crash part.

**Comment by 2n2u** [comment]
That's the entire error, right now the app crashes at start if I bind the on_keyboard event, unless I messed up elsewhere. I'll try later today disabling the bind and see if the app starts.

**Comment by kived** [comment]
It is not, you're filtering it out: `adb logcat python:* *:E`

**Comment by 2n2u** [comment]
Okay, I'll ask the person who has the "problematic" smartphone to get the full log :)

**Comment by 2n2u** [comment]
Now it doesn't give any error on the logcat, it just leaves the app, like it isn't catching the on_keyboard or something.

Here it is the logcat: http://pastebin.com/vcYJJVic

This line : I/python  (24168): {'sm': <Screens.ScreenManagement object at 0x648960a0>, 'card': <Screens.SimpleCard object at 0x649ea538>}

It's when the root screen is changed to another.

Back is pressed around here (to go back to root screen):

D/WindowManager(  527): interceptKeyTq keycode=4

**Comment by matham** [comment]
It's not really clear that it is a kivy bug, so closing.
