### ISSUE TITLE
Is a focused and disabled widget valid?

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4198]
While we were discussing https://github.com/kivy/kivy/issues/4196, some doubts arised wether or not a disabled but focused widget is something that kivy should have.

TextInput assumes this being a valid state by the presence of `background_disabled_active`, the active state seemingly being the same as focus. This state is not triggered since the move to FocusBehavior, `background_disabled_active` currently having no purpose.

How do other ui frameworks behave in this case, is focusing a widget (with tab etc.) possible while it is disabled?

**Comment by akshayaurora** [comment]
I would say remove it.
Serves no purpose, probably never did.

**Comment by matham** [comment]
Yeah, should be removed.

**Comment by dessant** [comment]
I'll take care of this. :stuck_out_tongue:
