### ISSUE TITLE
How about this feature for kivy lang?

### ISSUE THREAD

**Issue by langit** [kivy/kivy#4199]
I am new to kivy lang, and I am fascinated by it.  I was trying to use kivy to build a tree layout UI, where each node in the tree should be a text input, and the tree may be dynamic. So I am wondering if the kivy lang can be made more powerful by adding conditions and for loops. Here is an imaginary kivy file with the new power on:

```
RootWidget:

    # a conditional example
    Button if root.need_button:
           text: 'press me'
    else Label:
           text: 'feedback'

   # a more complex one
   Button if root.need_confirm:
          text: 'Confirm'
   else Label if root.need_label:
          text: 'Nice Job!'
   else Widget:
          # empty widget here...

   # here is a for loop example
   Rectangle for data in root.data:
         pos: data.pos
         size: data.size
```

As I am new to kivy lang, clearly my idea could be totally out of place. Just ask around to see if this proposal is possible at all or plausible at all.

**Comment by KeyWeeUsr** [comment]
That conditional example seems weird to me, because it only stretches the file and you can get better functionality through python with less lines if you'd like to have either this or that widget on a specific place. That for loop however would be nice.

**Comment by opqopq** [comment]
Then what about these one, inspired from Tshirtman: 
A) conditional
<Widget@ToggleButtonBehavior>:
    @if self.state=='down':
    Button:
         text: "showed"

B) Loop
<MyGridLayout@GridLayout>:
    cols: 1
    pictures: list()
    @for p in self.pictures
    Image:
          source: p

**Comment by opqopq** [comment]
damned, indent has disappearred:

Then what about these one, inspired from Tshirtman: 
A) conditional
``
Widget@ToggleButtonBehavior:

    @if self.state=='down':
    Button:
        text: "showed"

B) Loop
``
MyGridLayout@GridLayout:

    cols: 1
    pictures: list()
    @for p in self.pictures
        Image:
            source: p

**Comment by langit** [comment]
I was thinking in the lines that if everything about UI construction and layout can be done in kivy lang, then kivy lang would be perfect in its purpose. It seems to me, with for and if expression constructions (which are similar to the idea posted by opqopq, but seem to be more concise, and which are not statements, so that kivy remains a declarative language), kivy can provide a complete solution, so that you never need to touch the API's for UI layout and construction again.

**Comment by langit** [comment]
I agree with PeeWeeUsr that the if example is a little weird, but there are probably some good use case out there. Maybe this one: you push a button, it changes into a text label with feed back displayed.

```
Root:
   Button if root.need_confirm_once:
       text: "confirm your order"
       on_press: lambda: root.need_confirm_once = False
   else Label:
       text: "your order is confirmed"

```

**Comment by KeyWeeUsr** [comment]
@langit I know that Button to Label prettyprett change, but writing it into language when something similar is already there, well... You can easily do that with `disabled` and bg color, or do own widget. That for loop however seems more useful, because of custom My@Widget+behavior for example, or basically kv-only widgets. Now you'll either paste it whatever-times you need them, or you do it with ref in python and for. If in kivy in this usage may save you few characters, but it doesn't seem efficient to me. You can use multiple `on_*` and it'll be the same and under one widget.

Perhaps something like `switch_with` property would be better and would allow more possibilities:

    Button:
        on_press: lambda: confirm something, switch_with=NewWidget
        on_press: disable

or on_press: confirm and switch *if* ...

**Comment by langit** [comment]
@KeyWeeUsr that switch_with is a nice option, however it might not be as flexible. A cooked up example of interest may look like this: 
```
Root:
   Button if root.status == 0:
      text: "place an order" 
      on_press: lambda: root.order_status = 1
   else TextInput if root.status == 1:
      on_key: lambda key: root.status = 2 if key.name == 'enter' else 1
   else Button if root.status == 2:
       text: "confirm order"
       on_press: lambda: root.status = 3
   else Label:
       text: "order confirmed"
```

As for efficiency, an idea is that kv could be translated into python equivalent.

**Comment by dessant** [comment]
We would suggest making a pr if you'd like to see if your proposal is viable, but we don't plan to work on this in its current form.
