### ISSUE TITLE
pygame.error: Width or height is too large

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#420]
I get the following Error  while pasting data in a TextInput. The amount of data is by no means large ,
but I can't call it small either. For example 

To Reproduce : pasting 75 lines of 

    "The quick brown fox jumps over the lazy old dog.
    "

  in a text input results in the crash.

http://pastebin.com/8miikNYD

**Comment by dessant** [comment]
I cannot reproduce this with the sdl2 provider, pygame is being deprecated.
