### ISSUE TITLE
Custom File Browser as widget

### ISSUE THREAD

**Issue by Avernch7** [kivy/kivy#4205]
Actually I am making an app of sending-receiving files in Kivy . Problem is i want to use custom file browser  as a widget . I have written a code for file browser and also for my app ..now want to use that file browser file in my actual app . Any one can help me out in this?

**Comment by akshayaurora** [comment]
This is not a support group. You would have a lot more helpful replies on #kivy on irc.freenode.net or on kiva-users google group. Best of luck!

**Comment by akshayaurora** [comment]
@Avernch7 https://groups.google.com/forum/#!forum/kivy-users
