### ISSUE TITLE
Trigger a keyboard event by code

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#4206]
As in the title, how can i do that?
What i've in mind is something similar to _JQuery_ `trigger()` command http://api.jquery.com/trigger/

thanks for your help

**Comment by vjgaero** [comment]
do you mean something like this?
http://stackoverflow.com/questions/17280341/how-do-you-check-for-keyboard-events-with-kivy

**Comment by matham** [comment]
Github is for reporting bugs, not for support. See https://kivy.org/#support for how to get support.

**Comment by Tungsteno74** [comment]
@vjgaero not really. What you linked refers to how to bind event. What i meas is now to trigger them by code (JQuery api reference explain very well what it means). In any case, after some researches i found that this can't be done in kivy at the moment.

@matham Perhaps it would be more accurate to view it as a feature request, since (for what I understand) kivy has not yet implemented this mechanism, although in my humble opinion, would be a very useful feature.
Maybe, it could be left open this issue, so when I have a bit of time (and at the time no one else is interested in the development) could try to implement it myself?

thank you

**Comment by dessant** [comment]
You can already dispatch a keyboard event, that should achieve the same thing.

**Comment by Tungsteno74** [comment]
I think what you mean is that you can "link" a keyboard event to a specific callback right.
Instead what a trigger event do is to call all binded event to that particular event (in this case a keyboard event, like a key press) and all all its callbaks like if are you to press the key (but instead you do it by code). 
At least this is what i understand. It is correct?

**Comment by dessant** [comment]
> Instead what a trigger event do is to call all binded event to that particular event (in this case a keyboard event, like a key press) and all all its callbaks like if are you to press physically the key (but instead you do it by code)

This is what an event dispach does in Kivy.

**Comment by Tungsteno74** [comment]
So, i'm in the wrong way. I do not understood how event dispatcher works in Kivy. In any case thanks.

**Comment by vjgaero** [comment]
I think what you want is observer pattern. Look into the documentation for Kivy Properties.
