### ISSUE TITLE
Raspberry Pi 2 FBO's must be POT.

### ISSUE THREAD

**Issue by kujukuju** [kivy/kivy#4212]
If they're NPOT, you get the error "incomplete attachment (36054)". We should add this to the documentation.

Running on Raspbian OS.

Run the fbowidget.py to reproduce.

**Comment by TrentWDB** [comment]
Doesn't seem right that an issue is closed due to inactivity so I'm commenting.

**Comment by tito** [comment]
That's weird. There is others issues related to this error message, so at least this is a lead. But others use screenmanager with fbo-based transition, and they are not POT. So i wonder if this is a matter of GL driver version on the PI?

Do you remember/have log about which driver version is used on the RPI you got the message?

**Comment by Julian-O** [comment]
For those not in the know (like me 30 seconds ago)

FBO = [Framebuffer Object](https://www.khronos.org/opengl/wiki/Framebuffer_Object)
POT = Power Of Two

**Comment by misl6** [comment]
@Julian-O , this is likely linked to the `rpi_egl` window provider (which will be removed soon), but we can't double check-it as the original author did not reply to tito request for clarifications.

Unless someone can add some additional info, better to add the `awaiting-reply` tag.

**Comment by Julian-O** [comment]
@kujukuju: We need further information about this issue, or we will need to close it, because it is likely a deprecated component that is no longer supported and we can't fix it. 

Please provide some lots, and which driver version you used.
