### ISSUE TITLE
import kivy.uix.scrollview yields a blank window locked up

### ISSUE THREAD

**Issue by eveningsteps** [kivy/kivy#4213]
Long story short, one of components from the project I've been working on has started opening a window recently, even though it's supposed to be completely windowless. After some research, I noticed it happens in the process of importing `kivy.uix.scrollview`, which in turn, as tells `python -v`, pulls `kivy.core.window` (I failed to determine what *exactly* imports it, however).

[Kivy log](https://gist.github.com/eveningsteps/4b11f6c39aa49af0da439efd6f64e368) (not sure if it's of any help in this case). It's worth noticing that the window in question is [frozen](https://cdn.pbrd.co/images/pwZa9k5.png).

Way to reproduce: a simple `import kivy.uix.scrollview` from anywhere, even an interactive interpretator session, would do.

**Comment by dessant** [comment]
Fixed by https://github.com/kivy/kivy/pull/4235.
