### ISSUE TITLE
File chooser

### ISSUE THREAD

**Issue by Avernch7** [kivy/kivy#4215]
how to add other drives in file chooser instead in which drive we run the app?

**Comment by KeyWeeUsr** [comment]
It's a little bit tricky, you need to use windows API. An example is [here](http://stackoverflow.com/questions/26028235/python-kivy-how-to-use-filechooser-access-files-outside-c-drive) :)

**Comment by Kovak** [comment]
You might want to consider using the plyer implementation of file chooser, it wraps OS apis for each platform, at least on windows I checked and you can easily switch drives as normal with the plyer filechooser.

http://plyer.readthedocs.org/en/latest/#plyer.facades.FileChooser

**Comment by Avernch7** [comment]
Thanks :) ... but how would i implement it in my second app ? By from ........ import ....... and then use it ?

**Comment by Avernch7** [comment]
Thank you too :) i will look into it

**Comment by Avernch7** [comment]
Kovak: how to use that plyer implementation of file chooser?

**Comment by Kovak** [comment]
```python
def save_file(self):
        files_chosen = filechooser.save_file(filters=['*ext'])
        if files_chosen != None and len(files_chosen) > 0:
            #do your logic for saving, files_chosen will be a list of paths
            #(usually length 1 but multiselect is possible for some OS)
    def load_file(self):
        files_chosen = filechooser.open_file(filters=['*nbt'])
        if filse_chosen != None and len(files_chosen) > 0:
            #Do your logic for loading

**Comment by matham** [comment]
Have you seen https://github.com/kivy-garden/garden.filebrowser/ ?

**Comment by matham** [comment]
Also, have you tried `self.path = r'E:\my_path'`? You can set the root to external drives.

**Comment by Avernch7** [comment]
mathan : yeah i have seen garden.filebrowser ... problem is i made a custom file browser but i am not able to implement it in my actual app code

**Comment by Avernch7** [comment]
kovak: thanks for that piece of code

**Comment by Avernch7** [comment]
keyweeusr: how to implement that window api into my app. Any idea?

**Comment by matham** [comment]
This place is for bug reports, not support questions. Please ask on IRC or the mailing list. See https://kivy.org/#support.
