### ISSUE TITLE
Install/compile in virtualenv on Windows fails

### ISSUE THREAD

**Issue by ignus2** [kivy/kivy#4216]
Following the guide https://kivy.org/docs/installation/installation-windows.html#use-development-kivy I to install development kivy on Windows, I tried doing that in a virtualenv, and it fails for multiple reasons. Below is how I got it to work, and I'd like some feedback and maybe incorporate the changes to kivy sources:

1.
Installing all the dependencies in the guide and setting the environment variables for SDL and GSTREAMER (also setting the distutils compiler to mingw32 as in the guide), the first try of
`pip install kivy.zip`
fails with missing includes for "GL\glew.h". After much investigation I found that the compiler flags setup for virtualenv doesn't work correctly. It only sets the GLOBAL C:\Python34\Include and C:\Python34\libs dirs, but the dependencies are in the virtualenv. To overcome this, I added the following to the end of determine_base_flags() in setup.py:

```
@@ -11,6 +11,7 @@ import os
 from os.path import join, dirname, sep, exists, basename, isdir
 from os import walk, environ
 from distutils.version import LooseVersion
+from distutils.sysconfig import get_python_inc
 from collections import OrderedDict
 from time import sleep

@@ -546,6 +547,9 @@ def determine_base_flags():
                        'ApplicationServices.framework/Frameworks')
         flags['extra_compile_args'] += ['-F%s' % sysroot]
         flags['extra_link_args'] += ['-F%s' % sysroot]
+    elif platform == 'win32':
+        flags['include_dirs'] += [get_python_inc(prefix=sys.prefix)]
+        flags['extra_link_args'] += ['-L', join(sys.prefix, "libs")]
     return flags
```

2.
Second try ended with further errors regarding gstreamer. setup.py sets up pkgconfig to look for pkgconfig files relative to the Python executable, which is fine for a global install but doesn't work in a virtualenv, as the Python.exe is under the Scripts folder, so the following fails:
`pconfig = join(dirname(sys.executable), 'libs', 'pkgconfig')`
The same method is used for SDL2 include dirs.
So I changed the following:

```
@@ -57,7 +58,7 @@ def getoutput(cmd, env=None):
 def pkgconfig(*packages, **kw):
     flag_map = {'-I': 'include_dirs', '-L': 'library_dirs', '-l': 'libraries'}
     lenviron = None
-    pconfig = join(dirname(sys.executable), 'libs', 'pkgconfig')
+    pconfig = join(sys.prefix, 'libs', 'pkgconfig')

     if isdir(pconfig):
         lenviron = environ.copy()
@@ -611,7 +615,7 @@ def determine_sdl2():
     sdl2_paths = sdl2_path.split(split_chr) if sdl2_path else []

     if not sdl2_paths:
-        sdl_inc = join(dirname(sys.executable), 'include', 'SDL2')
+        sdl_inc = join(sys.prefix, 'include', 'SDL2')
         if isdir(sdl_inc):
             sdl2_paths = [sdl_inc]
         sdl2_paths.extend(['/usr/local/include/SDL2', '/usr/include/SDL2'])
```

Basically I used sys.prefix instead of the executable dir as a basis.

3.
After these changes the next error is a whole bunch of linker undefined reference errors like:

```
    ....\kivy\graphics\instructions.o:instructions.c:(.text+0x16d00): undefined reference to `__imp_PyDict_Type'
    ....\kivy\graphics\instructions.o:instructions.c:(.text+0x16d0e): undefined reference to `__imp_PyList_Type'
```

ie. basic Python things. The cause of this error is that the compiler picks up python34.lib from the GOBAL C:\Python34\libs folder, but as that is compiled by MSVC, it fails, and it doesn't even reach the correct libpython34.dll.a in the virtualenv libs.
The only fix I could come up with was to rename the global python34.lib to something (like _python34.lib).

After the above changes, kivy compiles and installs correctly in the virtualenv.

I'd like some opinions about the above procedure, and whether kivy should support virtualenv installation like the above. I'm not using wheels, as I'm doing some other changes to kivy sources and I wanted to build it in a virtualenv without polluting the global Python installation.
I don't see how to solve issue 3. above though automatically. Perhaps it's an inherent problem of distutils?

Balázs

**Comment by matham** [comment]
This should be fixed in master already.
