### ISSUE TITLE
An APP

### ISSUE THREAD

**Issue by Avernch7** [kivy/kivy#4218]
I have written an app for sending and receiving files , now i want to use custom file browser or file chooser in it but not able to do it . I can show my source code if anyone wants it so one check the what am i doing wrong and what's the main error and how can i make it better ?

**Comment by Kovak** [comment]
This place is for bug reports, not support questions. Please ask on IRC or the mailing list. See https://kivy.org/#support.

**Comment by dessant** [comment]
@Avernch7, your account has been limited from interacting with Kivy repositories for a week.

Previous requests for not using the issue tracker as a support forum:
https://github.com/kivy/kivy/issues/4215#issuecomment-214010942
https://github.com/kivy/kivy/issues/4205#issuecomment-212953119
