### ISSUE TITLE
Kivy clashes with IPython options

### ISSUE THREAD

**Issue by SG-phimeca** [kivy/kivy#4225]
It seems that there is a problem with some IPython options.

Trying 
    
    import kivy

in an IPython session launched with

    ipython --colors LightBG

raises 

    [ERROR             ] Core: option --colors not recognized

and kivy is not imported.

Imports in IPython lauched without options succeeds.

**Comment by kived** [comment]
This is an issue with IPython, and doesn't happen with the normal CPython interpreter. IPython doesn't strip the args it handled out of sys.argv, and we have no way of knowing which arguments were meant for IPython and which were meant for Kivy.

You can work around this by manually removing those args:

    import sys
    sys.argv = sys.argv[:1]
    import kivy

See: ipython/ipython#9133

**Comment by kthy** [comment]
The approach above strips all flags as far as I can tell, including those you'd actually want to pass to Kivy. I have put the following in my application's `__init__.py` to strip only the `pytest-cov` options:

    """Kivy barfs on unknown command line flags, such as those provided to pytest."""

    from sys import argv
    clean_args = []
    for arg in argv[1:]:
        if not "--cov" in arg:
            clean_args.append(arg)
    argv[1:] = clean_args
