### ISSUE TITLE
Kivy markup messing up with opening square bracket

### ISSUE THREAD

**Issue by parthibbiswas** [kivy/kivy#4226]
Suppose a Label widget has a text 'abcd[', it prints out the correct thing on the output screen as expected. But when I set the markup for that Label widget to True, it prints out 'abcd[[/color]'. How do I overcome this? I found out one possible fix by adding '\n' after the opening bracket in the text. But since I have many widgets in a row close to each other, the newline is pretty visible and it looks kinda ugly.

For this example, I'm using Button instead of Label.

This is the output for

```
Button:
    markup: True
    text: 'abcd\n['
```

![selection_011](https://cloud.githubusercontent.com/assets/2458719/14843031/8dbf8484-0c6a-11e6-9325-1a0154e62f32.png)

And this is the output for

```
Button:
    markup: True
    text: 'abcd\n[\n'
```

![selection_009](https://cloud.githubusercontent.com/assets/2458719/14843115/e8631d1a-0c6a-11e6-932c-ae5c646ab8db.png)

As I said, adding a newline makes it look ugly and the difference in text level between the nearby widgets look very visible.

**Comment by KeyWeeUsr** [comment]
Doesn't a space character or escape with `\[/color]` work?

**Comment by parthibbiswas** [comment]
Nope. Doesn't work. I tried 'abcd[\' 'abcd\[/color]' 'abcd ' and yet it still doens't work. I tried other silly ways like putting the bracket between the quotes, putting in parenthesis, brackets, everything and yet it still doesn't work.

The most frustrating part about this is I didn't even put opening color tags. I didn't even put any kind of markup tag and yet it shows a closing color tag.

When I tried '[color=#E5D209][[/color]', it shows the text '[[/color]' in yellow color.
When I try [b][[/b], it shows '[[/b]' in bold. :\

**Comment by dessant** [comment]
The docs recommend using `escape_markup`:
https://kivy.org/docs/api-kivy.uix.label.html#markup-text

You could also just manually replace the respective chars:
https://github.com/kivy/kivy/blob/856b305c0c876e53e802f1ac9ae16c21fa91ac1e/kivy/utils.py#L503

```python
from kivy.app import App
from kivy.lang import Builder


kv = """
#:import escape kivy.utils.escape_markup

Label:
    text: '[color=#E5D209]{}[/color]'.format(escape('['))
    markup: True
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```
