### ISSUE TITLE
How to authenticate Kivy apps using fingerprint scanners

### ISSUE THREAD

**Issue by asmith26** [kivy/kivy#4240]
I am hoping to make use of fingerprint scanners within my Kivy app for authentication.

Unfortunately, I haven't found any documentation regarding how to do this. I'm quite new to Kivy development, and I was hoping to achieve this by (e.g. for Android) importing the android API and calling the appropriate method. However after reading [this stackoverflow response](http://stackoverflow.com/a/29279982/5179470) it appears:

> Fingerprint scanner is not a feature in Android. So each company as Samsung, Motorola, HTC create is own API and SDK to access to fingerprint sensor.

(e.g. [SamsungPass](http://developer.samsung.com/release-note/view.do?v=R000000009)). Although I then found [this](http://stackoverflow.com/a/30544898/5179470)
> Google has now announced a generic fingerprint API for Android that can be utilised by any custom apps for authorisation ...
>
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />

**Any help regarding how I can add fingerprint authentication to Kivy apps is greatly appreciated. Thanks**

**Comment by dessant** [comment]
@asmith26, you could use pyjnius to access the java api, it's included by default in Kivy apps packaged for Android.
https://github.com/kivy/pyjnius

**Comment by asmith26** [comment]
Thanks for this information @dessant - do you know if there is a simliar API for iOS?

**Comment by dessant** [comment]
You're welcome, pyobjus can be used to access the iOS API.
https://github.com/kivy/pyobjus

**Comment by Huxtech** [comment]
Use the link below to clone my github pepo then make necessary adjustments

[https://github.com/Huxtech/Android-Biometrics](url)
