### ISSUE TITLE
Widgets with bad proportions on Android?

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#4247]
Hello,
I don' t know if this is a problem related to Kivy or only afflict python-for-Android, but I noticed that the widgets proportions on Android (in certain conditions) are different than how appear on the desktop version.

Below, a code example with the above "issue":

**main.py**

```
from kivy.app import App
from kivy.uix.button import Button

class mainApp(App):
	pass
mainApp().run()
```

**main.kv**

```
BoxLayout:
	orientation: "vertical"
	BoxLayout:
		Button:
			id: "theButton"
			text: "theButton"
	BoxLayout:
		id: "theBox"
		size_hint_y: None
		orientation: "vertical"
		height: 200
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
		Button:
			id: "theInnButton"
			text: "theInnButton"
```

Below  two pictures of what it looks like on devices:

**Desktop**
https://raw.githubusercontent.com/Tungsteno74/kivy-gui-issue/master/guitest_linux.jpg

**Android (is a photo)**
https://raw.githubusercontent.com/Tungsteno74/kivy-gui-issue/master/guitest_android.jpg

As you can see the size of the "TheInnButton" buttons is much tiny than the desktop version (also with similar proportions frame). This implies that _InputText_ widget in many cases might be unusable on mobile devices, even though when testing it on the pc you left them enough space.

Thus, my two questions are:

_Is it normal? (So you have to create different variations of GUI depending on the OS on which it will run)_

or better

_Is there a simple solution that is good for all versions?_

thanks

**Comment by inclement** [comment]
I think this is just because you set a specific height of 200 pixels, but the pixels on your device are much smaller than on your desktop monitor. You can use `from kivy.metrics import dp` and `dp(200)` to get a height in device-independent pixels that accounts for this dpi difference (though the reporting of this is not very specific so it'll only be a roughly correct scaling).

If you don't think this is the problem, feel free to say so and reopen the issue.

**Comment by Tungsteno74** [comment]
Hey inclement, this solve my problem. Thanks!
