### ISSUE TITLE
Documentation: Unclear wording about widget Z-index

### ISSUE THREAD

**Issue by hunternet93** [kivy/kivy#4252]
In [this section of Kivy's docs](https://github.com/kivy/kivy/blob/d437e93e8a769fc0a42cc1868f68feda8e4b1c17/doc/sources/guide/widgets.rst#widgets-z-index), it seems to specify that widgets are indexed in list order, with higher-indexed widgets being drawn on top. However, widgets are actually drawn in opposite order, with lower-indexed widgets being drawn on top. As a Kivy noob, this was very confusing until I asked about it on IRC.

**Comment by dessant** [comment]
It's reasonable to draw an analogy between css and kivy z-index, the behavior of the api may need to be changed to conform to user expectations, unless there's a good reason to behave in the opposite way.

**Comment by Kovak** [comment]
I think the behavior is desirable for performance reasons and logic reasons. If we stored children in the order they were displayed, we would dispatch touches in the wrong order, with backmost widget checking its logic prior to anything on top of it, or we would need to reverse the list every dispatch of input.

**Comment by Zen-CODE** [comment]
@hunternet93. The current behaviour is explained here: 

    https://kivy.org/docs/api-kivy.uix.widget.html?highlight=bubbling#widget-touch-event-bubbling

So that part you pointed out is not correct. We will update that shortly. Thanks.

**Comment by Zen-CODE** [comment]
The docs actually seem to be correct here. Widgets added last are drawn on top. Please see this example following. The last added widget is quite clearly drawn on top. Or am I missing something?

    from kivy.app import App
    from kivy.uix.floatlayout import FloatLayout
    from kivy.uix.label import Label
    from kivy.lang import Builder
    from kivy.properties import ListProperty
    
    
    Builder.load_string('''
    <ColourLabel>:
        canvas:
            Color:
                rgba: self.back_color
            Rectangle:
                pos: self.pos
                size: self.size
        size_hint: 0.5, 0.5
        pos_hint: {'x': 0, 'y': 0}
    ''')
    
    
    class ColourLabel(Label):
        back_color = ListProperty([1, 1, 1, 0.5])
    
    
    class TestApp(App):
    
        def build(self):
            f = FloatLayout()
            f.add_widget(ColourLabel(text="1", pos_hint={"x": 0, "y": 0}))
            f.add_widget(ColourLabel(text="2",
                                     pos_hint={"x": 0.25, "y": 0.25},
                                     back_color=[0, 1, 0, 0.5]))
            return f
    
    if __name__ == '__main__':
        TestApp().run()

**Comment by bionoid** [comment]
@Zen-CODE I think the confusion is regarding this phrase ```The last widget's canvas is drawn last (on top of everything else inside its parent)``` - it's easy to interpret "the last widget" as "the last widget in the children list" as opposed to the *most recently added* widget which was likely the author's intention

**Comment by dessant** [comment]
Yeah, it could also be nice to state plainly that lower indexed widgets will be drawn above those with a higher index.

```python
from kivy.app import App
from kivy.factory import Factory


class TestApp(App):
    def build(self):
        anchor = Factory.AnchorLayout()
        anchor.add_widget(Factory.Button(text='0'), index=0)
        anchor.add_widget(Factory.Button(text='1'), index=1)
        return anchor

if __name__ == '__main__':
    TestApp().run()
```

**Comment by Zen-CODE** [comment]
@hunternet93. We have updated the docs accordingly (see above commit in tick history). That should be clear enough? Please re-open if you're not happy.

Thanks

**Comment by dessant** [comment]
It could be also corrected here: https://kivy.org/docs/api-kivy.uix.widget.html?highlight=add_widget#kivy.uix.widget.Widget.add_widget.

**Comment by Zen-CODE** [comment]
@dessant. Well spotted. +1

**Comment by dessant** [comment]
@Zen-CODE cool, thanks for the fix. ++
