### ISSUE TITLE
ScrollView and layouts give problems when coupled

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#4256]
```
<ScrollForm@ScrollView+BoxLayout>
	size_hint_y: None
	height: dp(50)

BoxLayout:
	orientation: "vertical"
	Accordion:
		AccordionItem:
			BoxLayout:
				orientation: "vertical"
				BoxLayout:
					Button:
						text: "anotherButton"
		AccordionItem:
			BoxLayout:
				orientation: "vertical"
				BoxLayout:
					Button:
						text: "outScrollButton"
				ScrollForm:
					GridLayout:
						orientation: "vertical"
						cols: 1
						size_hint_y: None
						height: self.minimum_height			
						BoxLayout:
							orientation: "vertical"
							size_hint_y: None
							height: sp(100)
							Button:
								text: "theButton"							
						BoxLayout:
							id: "theBox"
							size_hint_y: None
							orientation: "vertical"
							height: sp(200)
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
							Button:
								text: "theInnButton"
						BoxLayout:
							size_hint_y: None
							orientation: "vertical"
							height: sp(80)
							Button:
								text: "yetAbutton"
							Button:
								text: "yetAbutton"
```
I tried this with sdl2 and give me a wrong position of content inside the  `ScrollView` when the widget is loaded or each time the app is flipped (on Android). If you refresh the ScrollView in some cases, the content looks great.

Layouts that are afflicted by this problem:
`BoxLayout, AnchorLayout, RelativeLayout, StackLayout.`

Is it normal?

**Comment by Zen-CODE** [comment]
Surely, inheriting from 2 different layout would always be unpredictable. Each layout is responsible for performing a particular kind of layout logic. Mixing of these together would result in each trying to do it's own layout and conflicting with the other. Multiple inheritance is avoided for this reason.

Consider a ScrollView should have only one child. A BoxLayout is built for many. Immediately, there is an ambiguity in handling children.

The proper way to do this would be for the ScrollView to contain a BoxLayout and not inherit from it. i.e.nested inside the ScrollView. This way each has it's own clear responsibilities?

**Comment by dessant** [comment]
@Zen-CODE is right, the way you subclass will surely break things. I've missed `<ScrollForm@ScrollView+BoxLayout>`.

**Comment by kived** [comment]
Actually, you'll want to completely skip `BoxLayout` - it won't help at all here. Just make `ScrollForm` a `ScrollView`, as it already contains a minimum height `GridLayout`.
