### ISSUE TITLE
request: circular buttons. Either CircularButton() or Button(shape='circle')

### ISSUE THREAD

**Issue by vjgaero** [kivy/kivy#4263]
I think it would be awesome pull request to implement circular buttons in kivy.

As we all know, the buttons still behave rectangular and we have to implement a custom collision function or grab a pixel to tell whether the button is being pressed or not.

Kivy would benefit with circular buttons or allowing a property such as border-radius (html) to control the shape of the button.

More than happy to help collaborate on this.

**Comment by dessant** [comment]
Have you tried ButtonBehavior? It would work well with an Image for your use case.

**Comment by tshirtman** [comment]
Don't get me wrong, but it does seem like this api would be way more limited than the current way of doing thing, and only marginally easier.

to do a circular button currently is a matter of doing

```
  from kivy.uix.behaviors.button import ButtonBehavior
  from kivy.uix.widget import Widget
  from kivy.lang import Builder
  from kivy.vector import Vector
  
  
  KV = '''
  <CircularButton>:
      canvas:
          Ellipse:
              pos: self.pos
              size: self.size
  '''
  
  Builder.load_string(KV)
  
  
  class CircularButton(ButtonBehavior, Widget):
      def collide_point(self, x, y):
          return Vector(x, y).distance(self.center) <= self.width / 2
  
  
  if __name__ == '__main__':
      from kivy.base import runTouchApp
  
    def callback(*args):
          print "i'm being pressed"
  
      runTouchApp(CircularButton(on_press=callback))

```

Which has the added benefit of allowing you to do anything more complex that you may want.

**Comment by vjgaero** [comment]
Awesome job!

**Comment by RufusVS** [comment]
The collide_point formula is incorrect for non-square (hence non-circular) widgets.  I added one line to the kv code to force the button widget to to be square/circular:

`KV = '''
<CircularButton>:
    size: (min(self.width,self.height),min(self.width,self.height)) # force circle
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size
'''
`

**Comment by Davincible** [comment]
This only makes the widget square on startup, how can I force the widget to always be square?

**Comment by Sahil-pixel** [comment]
how to add text="Hello" 

> Don't get me wrong, but it does seem like this api would be way more limited than the current way of doing things, and only marginally easier.
> 
> to do a circular button currently is a matter of doing
> 
> ```python
>   from kivy.uix.behaviors.button import ButtonBehavior
>   from kivy.uix.widget import Widget
>   from kivy.lang import Builder
>   from kivy.vector import Vector
> 
> 
>   KV = '''
>   <CircularButton>:
>       canvas:
>           Ellipse:
>               pos: self.pos
>               size: self.size
>   '''
> 
>   Builder.load_string(KV)
> 
> 
>   class CircularButton(ButtonBehavior, Widget):
>       def collide_point(self, x, y):
>           return Vector(x, y).distance(self.center) <= self.width / 2
> 
> 
>   if __name__ == '__main__':
>       from kivy.base import runTouchApp
> 
>     def callback(*args):
>           print "i'm being pressed"
> 
>       runTouchApp(CircularButton(on_press=callback))
> ```
> 
> Which has the added benefit of allowing you to do anything more complex that you may want.

how to add text="Hello" on circular button you have made

**Comment by tshirtman** [comment]
just add a Label in the kv rule…

please ask questions in support channels, not in bug bug reports.

**Comment by Sahil-pixel** [comment]
okk.. sir
