### ISSUE TITLE
Application does not close on Android/SDL2

### ISSUE THREAD

**Issue by j-santander** [kivy/kivy#4264]
I had kivy + buildozer + python-for-android application that I wrote about 1 year ago. I'm now retaking it to make some enhancements and I'm taking the opportunity to select the python-for-android toolchain and the SDL2 bootstrap.

This is Android Marshmallow. What I see is that I cannot properly close the application when I touch "Overview" soft-button and then swipe away the application. 

Now the window goes away and it does not appear in the list of active applications, but starting it again will get me a blank screen.

Looking through the device monitor, it will show that the application process did not go away.

Salting the code with traces, ~~I believe I know what happens:~~
1. ~~When I touch the "Overview", the application goes to the background.~~
2. ~~This will be signaled by an event 'app_willenterbackground' and as I've chosen to implement 'on_pause', `window2_sdl2.py` will set `self._pause_loop = True` at line 218~~
3. ~~That means that `_mainloop()` of window2_sdk2.py will enter the loop (lines 395-399):~~
   
   ```
       while self._pause_loop:
           self._win.wait_event()
           if not self._pause_loop:
                break
           self._win.poll()
   ```
4. ~~When I swipe away the application, the org.libsdl.app.SDLActivity.onDestroy() class will be called. This will call JNI nativeQuit() and wait for the mSDLThread to complete.~~
5. ~~This will be signaled as an 'app_terminating' event, captured by the _event_filter at line 196 and removed from the event~~
6. ~~As the event is consumed by the _event_filter (returns 0), the application never goes out of the self._win.wait_event() (that waits for ever)~~

~~So, although~~ 

```
def _event_filter(self, action):
    from kivy.app import App
    if action == 'app_terminating':
        EventLoop.quit = True
        self.close()
```

~~it is calling everything to have the application terminate its event loop and closing the application... as the _mainloop() is stuck in the self._win.wait_event() it will never evaluate the exit condition for the main loop.~~

~~I can think of some solutions, but I'd like some advice on the best way to proceed.... some or all (or none) the options below might be needed.~~

~~a) Modify _event_filter() to either~~
- ~~return 1 on 'app_terminating'. This will not filter out the event, allow the main loop to get out of the wait_event() and reevaluate the condition. I believe it is 1 what needs to be returned (according to `cb_event_filter` at _window_sdl2.pyx~~
- ~~send in a fake event to achieve the same result.~~

~~we should also make sure that `_pause_loop` is set back to False.~~

~~In general, I'm not sure what's the strategy with the _event_filter()... The cb_event_filter() will make sure that the filter could also apply to 'app_terminating', 'app_lowmemory', 'app_willenterbackground', 'app_didenterbackground', 'app_willenterbackground' or 'app_didenterforeground'. Any other event cannot be filtered, as it will just return 1 without checking with the `self.event_filter()`~~

~~Of those events where filter might apply, the window_sd2.py implementation does only check for 'app_terminating', 'app_lowmemory', 'app_willenterbackground' or 'app_didenterforeground'.... but it will always return 0 ( = drop event) in all cases.~~

~~b) Modify _window_sdk2.pyx `wait_event()' to use`SDL_WaitEventTimeout()` allowing the paused loop to awake once in a while.~~

~~Please advice, I can probably contribute with a pull request.~~

**Comment by j-santander** [comment]
Umm... it seems my analysis is wrong. The problem remains, but my attempts to fix it has failed so far.
I've removed the call to wait_event but it seems there's no effect.

**Comment by j-santander** [comment]
I'm attaching a very simple example

1. Launch application (the service is stated too)
2. Close the application swiping it out, the service remains running.
3. Try to launch the application again.

[test.zip](https://github.com/kivy/kivy/files/252909/test.zip)

**Comment by dzmitrykrukouski** [comment]
I fix this issue for me. In _python-for-android_ in _SDLActivity.java_ I put `System.exit(0);` in end of `onDestroy()` class. It completely closes the application. Until then, I sometimes get RuntimeException when I try reopen application but now all works well. 
**However, I'm not completely sure that it right way.**

@inclement can you tell something about it? 

Thanks!

**Comment by akshayaurora** [comment]
@dzmitrykrukouski this seems like the right fix, could you do a pr for this.
