### ISSUE TITLE
kivy/examples/android/takepicture/ fails on Android

### ISSUE THREAD

**Issue by jb1123** [kivy/kivy#4267]
Example cloned form GIT build with:
buildozer android debug
deployed to Android 4.4.4 crashes, from adb logcat output teh following lines seem to be relevant:

I/python  (25790):  /data/data/org.test.takepicture/files/lib/python2.7/site-packages/kivy/core/image/img_pygame.py:13: RuntimeWarning: import cdrom: No module named cdrom

I/python  (25790):  Traceback (most recent call last):
I/python  (25790):    File "/home/jb/python/mread/.buildozer/android/app/main.py", line 32, in <module>
I/python  (25790):  ImportError: No module named PIL
I/python  (25790): Python for android ended.

Second line indicates problem with image library, unfortunately I have no clue how to fix it.

**Comment by KeyWeeUsr** [comment]
Show your .spec file, probably you didn't included `pil` into `requirements = kivy` in that file.

**Comment by jb1123** [comment]
File buildozer.spec was (git) cloned yesterday and it had:
requirements = kivy
Following your suggestion I've changed it to
requirements = kivy, pil
Now it works, similar change should be made to the repository file. Thank you for prompt help.

**Comment by kived** [comment]
Yes, this needs to be changed in our examples. Reopening.
