### ISSUE TITLE
No nightly builds at the end of a month

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4272]
Exactly what the title says. Ctrl+F on [this](https://drive.google.com/folderview?id=0B1_HB9J8mZepOV81UHpDbmg5SWM&usp=sharing) returns nothing like "06052016". Is the build service down or something?

**Comment by KeyWeeUsr** [comment]
Seems like the service isn't down, because I can see `07052016` wheels now, but it's weird that it skipped the `06052016` day.

**Comment by matham** [comment]
Probably wasn't some changes in the code that day or something.

**Comment by KeyWeeUsr** [comment]
Actually, there were changes: 5 merges and one standalone commit, see [here](https://github.com/kivy/kivy/commits/master).

**Comment by dessant** [comment]
@KeyWeeUsr, an act of god maybe? :yum: 
@matham, would the script have to be edited when we move it to the repo, or is it just something simple?

**Comment by KeyWeeUsr** [comment]
Also a few other days are missing:
<pre>28,29,30    - 042016
28,29,30,31 - 032016
28,29       - 022016
28,29,30,31 - 012016</pre> etc. Seems like a pattern to me, though the only `06` that is missing is from `052016` and another strange commit non-empty day appeared - `04012016`.

If the nightlies are not released in the end of a month(28+), it should be documented.

**Comment by dessant** [comment]
@KeyWeeUsr, that's indeed a clear pattern, thanks for investigating.

**Comment by matham** [comment]
The cron job rule for the scheduled wheel builds is `52 18 * * *`.

**Comment by matham** [comment]
@dessant it's part of the appveyor setup and is not controllable by the appveyor file, even if it were to be moved to the repo. You have to set it on the website.

**Comment by KeyWeeUsr** [comment]
I was updating my wheels when I found out I can't update 3.4, so I checked the drive folder and `win32` for `3.4` is missing. `Amd64` and complete `2.7` versions are present.

**Comment by matham** [comment]
The last issues was just some random fluke with the CI failures. Regarding the original issues of missing days, it's that google seems to cut off what it displays on the public folder. We can do a auto delete after a month at some point.

**Comment by KeyWeeUsr** [comment]
Since 4th June there is no wheel available. Is google again hiding the items from public folder?

**Comment by matham** [comment]
I'm not sure why. I reset the cron time and maybe it'll start again. I also forced a build so it's being uploaded currently.
