### ISSUE TITLE
Why does the boot image is deformed?

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#4276]
I took the boot image from a folder python-for-android/src/res/drawable/presplash.png. The image size is not changed. Previously, all displayed properly on all monitors, and now like this:

![ScreenShot](http://msg.dimonvideo.ru/sklad/files/1941157/a7_b6_loading.png)

Ubuntu 14.04 (32-bit), Buildozer 0.33, Kivy 1.9.1

**Comment by dessant** [comment]
@HeaTTheatR, previously means in buildozer 0.32?

**Comment by HeaTTheatR** [comment]
I do not quite understand the question. Yes, earlier I had the version 0.32. Now - 0.33dev.

**Comment by dessant** [comment]
@inclement, were there any splashscreen changes in p4a recently?

**Comment by HeaTTheatR** [comment]
Excuse me, I'm from Ukraine, so I can write illegibly. I have not tried to use the standard boot image. I'll be back home, I will tell for sure.

**Comment by inclement** [comment]
This result is due to a bug in python-for-android, but I thought it was fixed now in both toolchains.

**Comment by HeaTTheatR** [comment]
It can be fixed?

**Comment by dessant** [comment]
This issue was moved to kivy/python-for-android#745
