### ISSUE TITLE
Mac - Kivy wants pygame if used from source

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4279]
I installed kivy with [these](https://kivy.org/docs/installation/installation-osx.html#using-pip) steps, but _pip hides the log_, so I did it again directly with setup.py. As is mentioned in the instructions, I should use `USE_OSX_FRAMEWORKS=0`, but:
- `echo $USE_OSX_FRAMEWORKS` returns nothing
- even if used before pip command separately (and probably correctly), it doesn't even matter because of [this line](https://github.com/kivy/kivy/blob/master/setup.py#L118) - setup.py doesn't check for this variable

So I edited that line's value to `False`. Python 2.7.11, Mavericks 10.9, 64bit
- [frameworks=1](http://pastebin.com/kUdwvZQw)
- [frameworks=0](http://pastebin.com/4ziErru6)

Also, the same result(pygame and pip imports) is with stable kivy through pip. What should I do to install from master branch? Does it still work now?

**Comment by kived** [comment]
FYI - the referenced line is setting the default. The block immediately following that (`for key in list(c_options.keys()): ...`) checks the environment variables and changes those values.

**Comment by KeyWeeUsr** [comment]
It appears I didn't catch the line where `pkg-config` was missing when I was looking through the log. After installing it with `brew` the checking for sdl2 worked correctly and kivy was compiled.
