### ISSUE TITLE
Window.softinput_mode not fully implemented in iOS

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy#4281]
With reference to https://groups.google.com/forum/#!topic/kivy-users/AGFYEaL3_fY

Testing on an iPad2, iOS 9.2, I can confirm the Window.softinput_mode = 'below_target' does nothing but works perfectly on Android. I have not tested the other modes, but that one certainly does not work.

**Comment by mrhdias** [comment]
This feature is not implemented on ios.
Check this file:

https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py

and Look for this code:

```
    def _get_ios_kheight(self):
        return 0 <<<<==== Return nothing :-(

    def _get_android_kheight(self):
        if USE_SDL2:  # Placeholder until the SDL2 bootstrap supports this
            return 0
        global android
        if not android:
            import android
        return android.get_keyboard_height()

    def _get_kheight(self):
        if platform == 'android':
            return self._get_android_kheight()
        if platform == 'ios':
            return self._get_ios_kheight()
        return 0

    keyboard_height = AliasProperty(_get_kheight, None,
                                    bind=('_keyboard_changed',),
                                    cache=True)
    '''Rerturns the height of the softkeyboard/IME on mobile platforms.
    Will return 0 if not on mobile platform or if IME is not active.
```

**Comment by Zen-CODE** [comment]
True, so that still needs to be implemented.  We (our company) is going to need this is the near future, so will look how difficult this is shortly. Auntie Google shows there are Objective C methods for doing that, so PyObjus should be able to handle it....

**Comment by mrhdias** [comment]
I found this code in a google search!
Getting the keyboard height on iOS:
https://gist.github.com/philipmcdermott/5183731

**Comment by mrhdias** [comment]
The Kivy documentation should indicate that the 'below_target' softinput mode feature is not supported on the iOS.
