### ISSUE TITLE
Windows - can not import kivy after installation

### ISSUE THREAD

**Issue by niccokunzmann** [kivy/kivy#4287]
I installed Kivy as mentioned in the docs.

Then I imported it and got this error, see the [gist](https://gist.github.com/niccokunzmann/bdc1b2abb4cd708c6e59f1fc77c3bbb7)

    ValueError: invalid interpolation syntax in 'kivy_%y-%m-%d_%h_.txt' at position 5

I was able to fix it by changing the line in [config.py](https://github.com/kivy/kivy/blob/master/kivy/config.py#L680)

from 

    Config.setdefault('kivy', 'log_name', 'kivy_%y-%m-%d_%_.txt')

to 

    Config.setdefault('kivy', 'log_name', 'kivy_%%y-%%m-%%d_%%_.txt')

It worked afterwards, see [gist](https://gist.github.com/niccokunzmann/bdc1b2abb4cd708c6e59f1fc77c3bbb7#file-kivy-02-working-after-change)

Also, I noticed that the double %% were in the config.ini file. This change brought more consistiency in my eyes.

Pull-request incoming.

**Comment by dessant** [comment]
I have tested kivy 1.9.1 in an interactive shell with python 3.4.3 on windows, and the issue was not there.

**Comment by niccokunzmann** [comment]
Did execution pass through the line 680?

I added the config file in the [gist](https://gist.github.com/niccokunzmann/bdc1b2abb4cd708c6e59f1fc77c3bbb7#file-kivy-03-config-ini). 

I come to think that `Config.setdefault` is supposed to be an equivalent of [config.ini line 7](https://gist.github.com/niccokunzmann/bdc1b2abb4cd708c6e59f1fc77c3bbb7#file-kivy-03-config-ini-L7).

**Comment by dessant** [comment]
Yes, I had no issues, that line in my config.ini is also different than yours: `log_name = kivy_%y-%m-%d_%_.txt`.

**Comment by niccokunzmann** [comment]
Now, I am confused and do not understand why your code works without error.
I suppose the double `%%` in my config.ini come from the change I made.

**Comment by dessant** [comment]
Try deleting the config file and run kivy again, with unchanged code.

**Comment by niccokunzmann** [comment]
Did. I get the error. BUT I must say, I am in line 670. with this. This is not the same config file.

**Comment by niccokunzmann** [comment]
I also have 

    KIVY_CONFIG_VERSION = 14

as opposed to your

    KIVY_CONFIG_VERSION = 15

I am working on an older Kivy version, I guess.

**Comment by dessant** [comment]
That's because you were linking the dev version in your first post, this is for 1.9.1:
https://github.com/kivy/kivy/blob/stable/kivy/config.py#L670

**Comment by niccokunzmann** [comment]
Okay, that misunderstanding is resolved. I should have linked to https://github.com/kivy/kivy/blob/1.9.1/kivy/config.py#L670

**Comment by niccokunzmann** [comment]
![capture](https://cloud.githubusercontent.com/assets/564768/15443789/58092c94-1eeb-11e6-9403-c29608abda96.PNG)
The error is still there.

**Comment by niccokunzmann** [comment]
![capture](https://cloud.githubusercontent.com/assets/564768/15443856/b9999cd2-1eeb-11e6-9edb-17c3bdeedee0.PNG)
The bottom log file is from today.

**Comment by KeyWeeUsr** [comment]
@niccokunzmann Try installing non-admin with [KivyInstaller](https://github.com/KeyWeeUsr/KivyInstaller), so that it won't leave dirt in your system. Although I use 3.4.4 if I have to, it shouldn't be problem to set the version in the batch. You should be able to call `idle` from the batch after installation. I've never experienced this issue and for all py2 and py3 win versions it works for me. Delete the folder if you don't want it after the checking.

If it works with the installer, problem is your installation, not kivy.

**Comment by niccokunzmann** [comment]
@KeyWeeUsr This works for me. Now I can stop installing and start creating applications with kivy.
