### ISSUE TITLE
Center is updated weirdly

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4290]
I have encountered a weird problem. When used `center: self.parent.center` at least on windows, position isn't updated as it should be. It depends on how much do you _drag_ the part of a window when you are resizing. Try to put a window to the left side of your screen, grab right border to resize and drag it to the right side.

Using master, sdl2, Win 8.1(and Vista+ I guess) you can reproduce it even with `win` + right/left arrow.

Example:

<pre>from kivy.lang import Builder
from kivy.base import runTouchApp
from kivy.uix.screenmanager import ScreenManager, Screen
Builder.load_string('''
&lt;Scr&gt;:
    canvas:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            size: self.size
            pos: self.pos
    GridLayout:
        center: self.parent.center
        size_hint: 0.7, 0.7
        cols: 1
        Button:
        Button:
''')
class Scr(Screen):pass
class Test(ScreenManager):
    def __init__(self, **kw):
        super(Test, self).__init__(**kw)
        self.add_widget(Scr())
runTouchApp(Test())</pre>

Please update the issue name with an approperiate name, I don't know about better name for now.

**Comment by matham** [comment]
This is a well known issue and documented here: https://kivy.org/docs/api-kivy.uix.widget.html#usage-of-widget-center-widget-right-and-widget-top. It's basically the difference between what you expect `center: self.parent.center` to do an what it actually does. Please re-open if it's a different issue.
