### ISSUE TITLE
Changing cursor for desktop apps

### ISSUE THREAD

**Issue by MelleB** [kivy/kivy#4291]
For desktop applications it would be nice to be able to change the mouse cursor when hovering elements.

If someone would guide me in the right direction I'd be willing to add this feature myself. Currently I'm lacking knowledge of Kivy internals.

I looked into the possibilities of doing so and found https://wiki.libsdl.org/SDL_CreateSystemCursor

I think implementing this as `Window.set_cursor(self, cursor_type)` would be nice, but I'm not sure if any of this is possible.

PS:I also found this commit by @akshayaurora which shows the files that need to be touched (i guess)
https://github.com/kivy/kivy/commit/616be4835768aeed5cb7cc72ce51c19dac09d1a0

**Comment by Bakterija** [comment]
I have implemented and tested it in [sdl2_cursors](https://github.com/kivy/kivy/tree/sdl2_cursors) branch . It works very well on Windows and Linux, except for some reason it is not using the correct resizing icons on Ubuntu. 
PR will come some time later.

**Comment by pythonic64** [comment]
With https://github.com/kivy/kivy/pull/5308 and https://github.com/kivy/kivy/pull/7658 features available it is now possible write code to change mouse cursor when hovering over widgets.

You can find working hover event manager and hover behavior at https://github.com/pythonic64/hover.
