### ISSUE TITLE
Weird behavior with ListAdapter on Arch + xmonad

### ISSUE THREAD

**Issue by elvis-sik** [kivy/kivy#4295]
Hi,

when I create a ListView with an adapter and a custom button (derived from ListItemButton) I get some weird behavior. In particular, only the last item gets displayed correctly.

In this repo I attached some example code plus a screenshot: https://github.com/elvis-sik/kivy-bug

I am using latest master Kivy. xmonad in Arch as the title mentions. I'd be happy to provide more information as necessary. This is pretty much preventing me to use Kivy at the moment to make my specific app.

Thanks for your attention!

**Comment by dessant** [comment]
@elvis-sik, have you seen RecycleView? It's the successor of ListView.
You'll have to update to the development version though.

**Comment by elvis-sik** [comment]
@dessant I'm trying to create a minimal working example with RecycleView but I am having a hard time. This is what I got:

    <AList@RecycleView>:
        data_model: RecycleDataModel(data=[1,2, 3])

I didn't find any example anywhere and also the documentation seems to be still in construction.

Could you, or somebody else, help me?

**Comment by matham** [comment]
You can find some examples here: https://github.com/kivy/kivy/pull/4108.

**Comment by elvis-sik** [comment]
Thanks @matham 

I have experimented with code based on that of the example and found something interesting. I've updated the [kivy-bug](https://github.com/elvis-sik/kivy-bug) repo appropriately. Also, my buggy example is much shorter now.

What I've found is that if I do a recycle view with, say, a simple Button, it works correctly. If, OTOH, I use a Button with nested Labels, only the last button's labels are displayed.

This is an example of code that causes the described behavior:

```python
from kivy.lang import Builder
from kivy.app import runTouchApp

runTouchApp(Builder.load_string("""
AList:
<AList@RecycleView>:
    data: [{}, {}]
    viewclass: 'AButton'
    RecycleBoxLayout:
        orientation: 'vertical'
        spacing: '15dp'
        default_size_hint: (10, 1)
        initial_size: (50, 100)
        size_hint_x: None
<AButton@Button>:
    Label:
        text: 'ABC'
    Label:
        text: 'DEF'
"""))
```

Nothing weird happens if I use
```python
<AButton@Button>:
    text: 'ABC'
```
instead.

**Comment by Kovak** [comment]
Are you certain it's not that all the labels are in the same place? Button
is not a layout and doesn't arrange its children. In your working example
you are setting buttons text and not adding a label at all.

**Comment by elvis-sik** [comment]
I know. I tried with a BoxLayout and got the same results. I've left it simply as a Button to rule out a problem with BoxLayout. Look at the screenshot:

![with_bug](https://cloud.githubusercontent.com/assets/11654926/15694215/289151e6-2772-11e6-9306-9c09229ce2cc.png)

**Comment by Kovak** [comment]
What I'm saying is with the code you have given all the labels at 0 0 with
size 100 100 is the expected result

**Comment by elvis-sik** [comment]
If I understand you correctly, @Kovak , the problem is with the size hints. What would you expect would be displayed if I change the definitions to this?

```python
<AList@RecycleView>:
    data: [{}, {}]
    viewclass: 'AButton'
    RecycleBoxLayout:
        orientation: 'vertical'

<AButton@Button>:
    BoxLayout:
        Label:
            text: 'ABC'
        Label:
            text: 'DEF'
```

**Comment by Kovak** [comment]
Button is still not a layout so the boxlayout is at 0, 0 and size 100, 100
On May 31, 2016 5:14 PM, "elvis-sik" <notifications@github.com> wrote:

If I understand you correctly, @Kovak <https://github.com/Kovak> , the
problem is with the size hints. What would you expect would be displayed if
I change the definitions to this?

<AList@RecycleView>:
    data: [{}, {}]
    viewclass: 'AButton'
    RecycleBoxLayout:
        orientation: 'vertical'
<AButton@Button>:
    BoxLayout:
        Label:
            text: 'ABC'
        Label:
            text: 'DEF'

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kivy/kivy/issues/4295#issuecomment-222858487>, or mute
the thread
<https://github.com/notifications/unsubscribe/AB2OUGfgj4XhxzHUI7IzmRFpTHttM8UDks5qHM7WgaJpZM4Ijrmm>
.

**Comment by elvis-sik** [comment]
If I use this instead
```
<AButton@BoxLayout>:
    Label:
        text: 'ABC'
    Label:
        text: 'DEF'
```
Both BoxLayout's get displayed.

I do not really understand why the second button displays its BoxLayout and the first doesn't, but this might be better pursued somewhere else, as it is expected behavior, according to you. Also, I'll look it up in the docs how to get a button-ish layout. Anyway, as I mentioned, this issue seems to be resolved.

Thanks all for your patience and attention!
