### ISSUE TITLE
no app screen is coming 

### ISSUE THREAD

**Issue by k1629** [kivy/kivy#4302]
I'm using python 3.4 and when i run my kivy app this message is coming and it's not showing any app screen. please help me here,  do i have to install some dependencies?

[INFO              ] [Logger      ] Record log in C:\Users\sachin\.kivy\logs\kivy_16-05-24_52.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2

Process finished with exit code 0

**Comment by tito** [comment]
Seems everything is working. Care to share your main.py?

It seems you don't even start your app, just import kivy here.

**Comment by KeyWeeUsr** [comment]
ref: the same [SO Question](http://stackoverflow.com/q/37413948/5994041)

**Comment by tito** [comment]
This is clearly an user issue, so SO or kivy-users ml are appropriate place for discussion.

**Comment by k1629** [comment]
this is the code which i'm using. i have just started app development with kivy. 
`import kivy
kivy.require('1.9.1')

from kivy.app import App
from kivy.uix.button import Label


class SimpleKivy(App):
    def build(self):
        return Label(text="Hello World ")


if __name__=="_main_":
    SimpleKivy().run()`

**Comment by k1629** [comment]
thank you for your quick reply guys. i have got the answer. there was some error in if statement.
