### ISSUE TITLE
Add a Music class for streaming audio

### ISSUE THREAD

**Issue by CreamyCookie** [kivy/kivy#4306]
There's already [`MusicSDL2`](https://github.com/kivy/kivy/blob/master/kivy/core/audio/audio_sdl2.pyx#L218) class that supports streaming an audio file from disk instead of loading it all into memory, but it's not easily accessible and not documented. I think this functionality is really useful in general, as loading a large music file into memory is usually not a good idea. (That's what the kivy.core.Audio class would do, which is fine for small files like sound effects etc.)

**Comment by Julian-O** [comment]
Doesn't look like there is enough support to make this a core widget, but it might succeed in the Kivy Garden as a third-party widget
