### ISSUE TITLE
plyer.accelerometer not working with Kivy Launcher

### ISSUE THREAD

**Issue by MichaelPython** [kivy/kivy#4308]
i am using Kivy Launcher 1.9.0 to run my app on Android.
 my app hangs with this code: from plyer import accelerometer; accelerometer.enable()
 but other facades such as vibrator works.
 i tried it on 2 android phones, one with Android 4.2 , the other Android 4.4, same result.

 i tried the same code with the Kivy built in QPython 1.25, it works. so something must be wrong with Kivy Launcher 1.9.0

**Comment by dessant** [comment]
Could you update Kivy Launcher to 1.9.1.1 and see if the issue is still there?

**Comment by MichaelPython** [comment]
i found a kivy launcher 1.9.1.1 download a few days ago. it had the same problem, and it seemed to have more problems than 1.9.0.0 - i tried official sample "picture" "touchtracer" with 1.9.1.1, they couldn't run at all, and the splash screen was stretched (wrong aspect ratio). so i doubted, was the 1.9.1.1 an official release?
right now i only keep 1.9.0.0 .

**Comment by dessant** [comment]
Yes, 1.9.1.1 is the latest, you could try testing if the plyer issue is there, regardless of the other bugs you're seeing (and possibly open issues for those other bugs :stuck_out_tongue: ).

**Comment by MichaelPython** [comment]
i confirm 1.9.0.0 , 1.9.0.1, 1.9.1.0 , 1.9.1.1 all have the same problem of plyer.accelerometer.
as for other bugs of 1.9.1 , i find out it's related to orientation - in portrait mode, app crashes (issue already reported), in landscape mode, the splash screen is stretched.

**Comment by KeyWeeUsr** [comment]
@MichaelPython Try making a [custom launcher](http://python-for-android.readthedocs.io/en/latest/launcher/) with the packages that launcher in the store has, maybe it's only minapi issue. Can't find my issue(or chat), but I was using minapi=8 if I remember correctly and switching to 13 solved rotation crashes
