### ISSUE TITLE
Help users begin to debug the bugs they find (DOX)

### ISSUE THREAD

**Issue by bearnun** [kivy/kivy#4313]
Anywhere a user is about to post a question (for example on https://kivy.org/#forum), post how to expand the kivy logs:

Add:
from kivy.config import Config; Config.set('kivy', 'log_level', 'trace')
Before your app's kivy imports.

**Comment by kived** [comment]
For most cases, debug is enough. trace is way too much info and hard to read through unless you really need something which is only in trace logs (like exceptions thrown by optional providers).

**Comment by matham** [comment]
I don't think we need an issue open for this as it's not a bug. If it's about adding to the docs, a PR is welcome.
