### ISSUE TITLE
Having  trouble to install pyjnius for Kivy App. 

### ISSUE THREAD

**Issue by k1629** [kivy/kivy#4323]
While installing pyjnius, I'm getting this error. I'm trying to install pyjnius for my kivy App. please also suggest some other way to install pyjnius? <running build_ext skipping 'jnius\jnius.c' Cython extension (up-to-date) building 'jnius' extension error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat)>

**Comment by dessant** [comment]
https://github.com/kivy/kivy#support
