### ISSUE TITLE
Unable to execute the example using "$ kivy myprogram.py" on mac osx el capitan.

### ISSUE THREAD

**Issue by AnudeepKonda** [kivy/kivy#4325]
I installed kivy as mentioned in the documentation. Typing "kivy" in the terminal is opening the python promt. Entering "kivy /Applications/Kivy.app/Contents/Resources/kivy/examples/3Drendering/main.py" should run the example but nothing seems to happen. Drag and drop isn't working either.

**Comment by kived** [comment]
Please provide the console output when you try to run a Kivy app.

**Comment by AnudeepKonda** [comment]
![kivy](https://cloud.githubusercontent.com/assets/19614385/15625562/62fa5622-24c8-11e6-9090-602cebbd1029.png)

**Comment by AnudeepKonda** [comment]
[Untitled.pdf](https://github.com/kivy/kivy/files/287590/Untitled.pdf)

**Comment by dessant** [comment]
https://docs.google.com/viewer?url=https://github.com/kivy/kivy/files/287590/Untitled.pdf

@AnudeepKonda, you can also share logs/code by wrapping it in code tags and pasting in the github comment directly.

**Comment by AnudeepKonda** [comment]
below was the log entry:
`[INFO              ] Logger: Record log in /Users/quanon/code/kivy-sdk-packager/osx/Kivy.app/Contents/Resources/.kivy/logs/kivy_16-01-07_0.txt
[[1;33mWARNING[0m] [Config      ] Upgrading configuration in progress.
[[1;33mWARNING[0m] [Config      ] Older configuration version detected (0 instead of 14)
[INFO              ] Kivy: v1.9.1
[INFO              ] Python: v3.5.0 (default, Dec 12 2015, 05:50:29) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
`

**Comment by tito** [comment]
I bieleve you have something wrong with your system, as the default python version for you is 3.5, which is not the system python as intented to be for Kivy. So yes it goes wrong. It would also have been nice to tell "how" you installed kivy as there is multiple way to do.

I'm closing this because there is no user answer;
