### ISSUE TITLE
Kivy Window Resize

### ISSUE THREAD

**Issue by AccPy** [kivy/kivy#4326]
Good Afternoon,

I'm running Python 3.5 and Kivy 1.9.1 on OS X. I installed Kivy using pip install, and I was never really able to get Kivy to work using the download and putting in my Applications folder like the instructions were asking. Everything seems to work fine, and I've made a few apps; however, I seem to encounter a problem whenever I try to resize the window. The window goes white while I'm resizing it, and then it turns blank/black afterwards. The terminal just says that it reloaded the graphics and the amount of time it took. I was hoping that after I made my apps using Pyinstaller that this would go away, but the problem still persists. Has anyone else encountered this problem? I haven't been able to test this on another computer yet to see if the problem persists. I checked the other issues, and it seemed one other person had this issue (#1762), but their terminal output seemed like it had more than mine so I think the problem is slightly different. This problem persists no matter if the app is simple (just a simple button) or complex. Here is the output in the terminal:

```

Johns-MBP:Kivy  Files jal$ python3 testapp.py
[INFO   ] [Logger      ] Record log in /Users/jal/.kivy/logs/kivy_16-05-27_19.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame
[INFO   ] [GL          ] OpenGL version <b'2.1 ATI-1.42.11'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'ATI Radeon R9 M370X OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Context     ] Reloading graphics data...
[INFO   ] [Context     ] Reloading done in 0.0124s

```

I've only been working with Python for about a month and Kivy for a little over a week.

**Comment by AccPy** [comment]
If it means anything, the app crashes when I try to make the window fullscreen.

**Comment by kived** [comment]
Did you try SDL2 instead of pygame as the window provider? You do need to have the SDL2 deps installed first, and *then* install Kivy. We can only build against one or the other (because pygame uses SDL1), so if SDL2 wasn't available at build time then your Kivy installation will be pygame-only. https://kivy.org/docs/installation/installation-osx.html#using-pip

**Comment by AccPy** [comment]
Thank you! I was looking through my frameworks and noticed it wasn't there, but I didn't know if that was causing the problem (the spec file example in the docs for buildozer caused me to look around there). Can I just install SDL2 deps now, or will I need to reinstall Kivy afterwards also? Lastly, if I need to reinstall Kivy, then to uninstall it would I just pip uninstall? Thanks again!

**Comment by kived** [comment]
Yes, you will need to reinstall Kivy afterwards. pip uninstall + install should work. Just make sure you use brew to install the libraries - when installed via pip, we don't use frameworks. Those are only used for the Kivy.app method.

**Comment by AccPy** [comment]
Is there a specific location where I can see if everything downloaded? I uninstalled kivy and followed the instructions in your link, but I don't see them in the Frameworks folder in the Library folder. I am able to import kivy, but I can't import kivy.app. I used brew for the SDL2 deps. I don't remember where to check for the kivy package that was installed, but I should be able to find that in a google search. I didn't seem to run into any errors when doing the installs. Sorry for the lack of understanding. I switched from VBA and Visual C# and am fairly new to OS X too (and I'm in accounting and just doing this as a hobby), but I've grown to really like python and kivy and plan to stick with this for the foreseeable future. Thanks again!

**Comment by AccPy** [comment]
Never mind. I'm a huge idiot (just copied and pasted without adding the 3 to pip). Thank you so much for your help!!!(:

**Comment by kived** [comment]
No problem! And yeah, gotta make sure you're using the right python with pip. ;) Could be worse. On my MacBook, I somehow have `python` -> `python2` but `pip` -> `python3`. :D

**Comment by jrward** [comment]
I also have this problem and have been unable to fix it. Can we reopen this issue?
I am running OS X v10.11.6 

Kivy stuff installed using pip:
Kivy (1.9.1)
Kivy-Garden (0.1.4)
Cython (0.23)

SDL2 dependencies installed using Homebrew:
sdl2-2.0.4 
sdl2_image-2.0.1_1 
sdl2_ttf-2.0.14 
sdl2_mixer-2.0.1 
gstreamer-1.8.2

**Comment by inclement** [comment]
@jrward: Could you open a new issue with the full traceback? Since this involves sdl2 instead it may not actually be the same error, so it's probably easiest to have a new one.

**Comment by jrward** [comment]
Okay, sure

**Comment by jrward** [comment]
Well, it still says my provider is pygame. Is there a way to change this? I already tried uninstalling an reinstalling. Maybe reinstalling after uninstalling pygame?

python dynamic_widgets.py
Purge log fired. Analysing...
Purge finished!
[INFO   ] [Logger      ] Record log in /Users/blackguardx/.kivy/logs/kivy_16-08-10_15.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.1 (default, Apr 18 2016, 11:46:32)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.14.73'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 6100'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Context     ] Reloading graphics data...
[INFO   ] [Context     ] Reloading done in 0.0356s
[INFO   ] [Base        ] Leaving application in progress...

**Comment by inclement** [comment]
The provider is chosen at compile time, and sdl2 will be used if it's
available and Kivy can find it, so probably that's the issue - you can
check the build logs to see for sure (you should get something like
'use_sdl2 = 1' if it's working).

**Comment by jrward** [comment]
I figured it out. Pip kept using its cache to reinstall. It finally worked after uninstalling pygame and kivy and then running:

USE_OSX_FRAMEWORKS=0 pip install --no-cache-dir kivy

**Comment by heathf** [comment]
Thanks jrward.  That fixed it for me also.  (I was beginning to get pretty frustrated).  It should also be stressed to anyone else reading this that you must uninstall pygame before reinstalling kivy.  After reading one of the other comments, I was led to believe that kivy would look for sdl2 and build against that if it was available, but it actually seems to do the opposite.  If it finds pygame, it builds against that and ignores sdl2.  So this is what fixed it for me:

pip uninstall kivy
pip uninstall pygame
USE_OSX_FRAMEWORKS=0 pip install --no-cache-dir kivy

Thanks again

**Comment by FlorenceMei** [comment]
Thank you sooooooo much guys!! 
At the beginning, I had installed kivy and pygame with pip install. My code did not have any apparent error, but I had some minor problems, like the window popping up which I couldn't bring in the foreground, then the mouse interactions were so weird, and finally, I couldn't write any text input. There was definitively wrong. I thought it was Pycharm managing weirdly but it wasn't. So, this is THE solution for people who are MacOs + anaconda + kivy like me.
