### ISSUE TITLE
"a" parameter of Color Graphics Instruction cannot be reliably used with "rgb" or "hsv".

### ISSUE THREAD

**Issue by kmonson** [kivy/kivy#4335]
Because "rgb" and "hsv" both stomp on the alpha value of the Color instruction this doesn't work right:

```
<-MyButton>:
    ...
    overlay_alpha: 0.5 if self.disabled else 0.6
    ...
    canvas:
        ...
        Color:
            rgb: [0.0, 0.0, 0.0] if self.disabled else [124.0/256.0, 124.0/256.0, 124.0/256.0]
            a: 0.0 if self.state == 'normal' else self.overlay_alpha
        ...
```

When self.disabled changes without also changing the state the alpha goes to 1.0.

I'm working around this by squishing it all together and using "rgba", but it would be much nicer if I could use "rgb" and keep the alpha value intact.

**Comment by kmonson** [comment]
Yes, I realize there are logic problems with my example.

**Comment by Julian-O** [comment]
Please provide a complete example demonstrating the problem. I suspect it has been addressed, but I don't have any code to test it with.
