### ISSUE TITLE
TextInput doesn't accept input in certain languages from the keyboard

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#434]
To reproduce

1) launch any example that uses TextInput,
2) Change you keyboard Layout to a language like Chinese that require non standard input like IME
3) click to focus the TextInput Widget and try to type, nothing get's displayed.

**Comment by yingshaoxo** [comment]
Actually interesting, I found that kivy `Textinput` component can't input any languages except English in android. (I'm using `Gboard` as my input method in android)

I was using `python-for-android` to build my application.

Here is the APK that I built, you can also found the source code here:
https://github.com/yingshaoxo/kivy-diary/releases

___

I have to say, at the linux desktop, It all works. I have no idea about how it can't be done with the android platfrom.
