### ISSUE TITLE
Docs - KV highlighting errors

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4341]
In docs there are these red boxes signalising errors for code highlighting and the errors are, well... should be hidden, because kv language seems to work this way(IF without indent, on_\* values on new line, etc.) and can only confuse users. Similar with #4340 but there it was simple to fix.

Here are problems probably with [kivystyle.sty](https://github.com/kivy/kivy/blob/master/doc/sources/kivystyle.sty) which doesn't consider new line as correct for kv-lang.

![image](https://cloud.githubusercontent.com/assets/8825439/15648633/1582dba8-266c-11e6-814e-1b4617c96cb7.png)
![image](https://cloud.githubusercontent.com/assets/8825439/15648649/2d92151a-266c-11e6-8eaa-8b37e7cb6969.png)

**Comment by KeyWeeUsr** [comment]
ref #4358 ?

**Comment by crigaut** [comment]
I think the problem is in Kivy lexer: [highlight.py](https://github.com/kivy/kivy/blob/master/kivy/extras/highlight.py)
The highlighted parts are not caught by any of the regular expression.

**Comment by crigaut** [comment]
I think this issue can be closed.
I wrote "Solve" instead of "Fix" in my PR. Sorry :sweat:
