### ISSUE TITLE
ios build fail if bitcode is on

### ISSUE THREAD

**Issue by RobertoD91** [kivy/kivy#4342]
after "./toolchain.py create myapp /some/dir/myapp" i open myapp-ios/myapp.xcodeproj in xcode

ios simulator build work

build for real ios device fails

after disable "enable bitcode" in "build settings" building work

**Comment by Marvin91** [comment]
need to update https://kivy.org/docs/guide/packaging-ios.html writing about this issue

**Comment by misl6** [comment]
Closing as this is not an issue anymore with a recent `kivy-ios` 🎉
