### ISSUE TITLE
how to upgrade OpenGL in ubuntu 14.04 LTS for kivy?

### ISSUE THREAD

**Issue by issue1** [kivy/kivy#4346]
[CRITICAL] [GL          ] Minimum required OpenGL version (2.0) NOT found!

OpenGL version detected: 1.4

Version: b'1.4 Mesa 10.3.2'
Vendor: b'Intel Open Source Technology Center'
Renderer: b'Mesa DRI Intel(R) Q35 x86/MMX/SSE2'

Try upgrading your graphics drivers and/or your graphics hardware in case of problems.

**Comment by matham** [comment]
This is not the place to ask for support on how to upgrade Ubuntu drivers. This is for bug reports of the Kivy project. For support using Kivy see https://kivy.org/#support.
