### ISSUE TITLE
Bubble arrow changes position

### ISSUE THREAD

**Issue by illright** [kivy/kivy#4348]
This problem seems like a bug to me. Basically, I add widgets to a `GridLayout` one by one. Those widgets have an attached `Bubble` on the right with the property arrow_pos set to `"left_mid"`. However, once I add another widget to that `GridLayout`, the previous widget's arrow shifts up, as if the arrow_pos property changes to `"left_top"` (which is not the case, I've checked and it stays at `"left_mid"` all the time).  
The code can be found [here](https://pastebin.com/n8eW6nda). On the press of a button, a new widget is added to a `GridLayout`

**Comment by AnthonyZi** [comment]
> This problem seems like a bug to me. Basically, I add widgets to a `GridLayout` one by one. Those widgets have an attached `Bubble` on the right with the property arrow_pos set to `"left_mid"`. However, once I add another widget to that `GridLayout`, the previous widget's arrow shifts up, as if the arrow_pos property changes to `"left_top"` (which is not the case, I've checked and it stays at `"left_mid"` all the time). The code can be found [here](https://pastebin.com/n8eW6nda). On the press of a button, a new widget is added to a `GridLayout`

Based on the changes of my PR (#7882) and after patching the test script you provided with this small patch:
`--- test_original.py	2022-05-17 21:37:51.797815319 +0200
+++ test.py	2022-05-17 21:36:56.443259703 +0200
@@ -31,6 +31,7 @@
         arrow_pos: "left_mid"
         pos: root.x + root.width, root.y
         size: 150, 45
+        BubbleContent:
 ''')
`
the arrow positioning should be fixed.

**Comment by Julian-O** [comment]
Closing as fixed. If the problem still occurs, please let us know.
