### ISSUE TITLE
Factory module not thread-safe

### ISSUE THREAD

**Issue by wanyikang** [kivy/kivy#4349]
recently I am working on a project using kivy, and I find the Factory methods are not thread-safe but it is implemented as a singleton. Althought it does not matter to my project, but i am confusing about it, can somebody explain that?

**Comment by matham** [comment]
It is not clear to me what the question is. Is it whether Factory is thread safe? The answer is no. Nothing in Kivy is thread safe unless explicitly mentioned. In fact everything  should be executed from the main thread using `Clock`. And yeah, Factory is a singleton.

In any case github issues are for bugs. For support see https://kivy.org/#support.

**Comment by wanyikang** [comment]
sorry, I will do it in the right place next time. And big thank for the answer.
