### ISSUE TITLE
Windows needs a prior installation of Kivy to build

### ISSUE THREAD

**Issue by Kovak** [kivy/kivy#4354]
https://github.com/kivy/kivy/blob/master/setup.py#L323

This import means that it is impossible to install a kivy without a kivy installed already/on path

**Comment by matham** [comment]
Doesn't that automatically happen during an install? Because we ha these kivy imports forever. E.g. https://github.com/kivy/kivy/blob/master/setup.py#L909. How are you trying to install it?

**Comment by Kovak** [comment]
It seems to occur when running "python setup.py install" manually

**Comment by kived** [comment]
The kivy package is in the same folder as setup.py. Why wouldn't that
import work?

**Comment by dessant** [comment]
@Kovak, python 3?

**Comment by Kovak** [comment]
I'm not certain, it was coming up on someones Windows machine during a
pycon sprint yesterday, I will have to see if I can recreate on my machine.
Might have been 3.

**Comment by kived** [comment]
BTW, I've seen issues before which resulted from running setup.py from outside the folder where it's located. This issue would certainly present in that case.

**Comment by Kovak** [comment]
Oh you know what, that might have been happening. I think we can close this
issue then.
