### ISSUE TITLE
set up kivy with anaconda on pycharm on OSX

### ISSUE THREAD

**Issue by ReblochonMasque** [kivy/kivy#4370]
The problem:
---
I am having difficulties setting up `kivy` to work with `anaconda` in `pycharm`:
This is probably a 'documentation' issue; I don't know how, I can't find instructions.

What I have done:
---
Following the directions found at [Connecting Kivy with Anaconda (OSX)](https://github.com/kivy/kivy/wiki/Connecting-Kivy-with-Anaconda-%28OSX%29) I have `kivy` working with `anaconda` (it launches via the `kivy.app`, not from `conda`)

The instructions to [Setting Up Kivy with various popular IDE's](https://github.com/kivy/kivy/wiki/Setting-Up-Kivy-with-various-popular-IDE's) were easy to follow to use `anaconda` in `Pycharm`

**However, I can't figure how to set up `kivy` *and* `anaconda` in `pycharm`.  
Does someone know?**

<br>
`----------------------------------------------------------------------------------`
Additional information
---

Attempting to use kivy via `conda environment` (`$ source activate ...`) does not work; it throws an `import error/package kivy not installed`

The final 'bootstrapping script' for the `kivy.app` is as follows (modified from [Connecting Kivy with Anaconda (OSX)](https://github.com/kivy/kivy/wiki/Connecting-Kivy-with-Anaconda-%28OSX%29))

    #!/bin/bash
    SCRIPT_PATH="${BASH_SOURCE[0]}";
    if([ -h "${SCRIPT_PATH}" ]) then
      while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
    fi
    SCRIPT_PATH=$(python -c "import os; print(os.path.realpath(os.path.dirname('${SCRIPT_PATH}')))")
    
    # activate the virtualenv
    # SUPPRESSED
    # source ${SCRIPT_PATH}/venv/bin/activate
    
    # setup the environment to not mess with the system
    export PYTHONPATH="${SCRIPT_PATH}/kivy:${PYTHONPATH}"
    export DYLD_FALLBACK_LIBRARY_PATH="${SCRIPT_PATH}/lib"
    export LD_PRELOAD_PATH="${SCRIPT_PATH}/lib"
    export GST_REGISTRY="${SCRIPT_PATH}/gst.registry"
    export GST_PLUGIN_SCANNER="${SCRIPT_PATH}/gst-plugin-scanner"
    export GTK_PATH="${SCRIPT_PATH}/../Frameworks/GStreamer.framework/Versions/Current"
    export GST_PLUGIN_SYSTEM_PATH="${SCRIPT_PATH}/../Frameworks/GStreamer.framework/Versions/Current/lib/gstreamer-1.0"
    export GST_PLUGIN_SYSTEM_PATH="${SCRIPT_PATH}/../Frameworks/GStreamer.framework/Versions/Current/lib/gstreamer-1.0"
    export GIO_EXTRA_MODULES="${SCRIPT_PATH}/../Frameworks/GStreamer.framework/Versions/Current/lib/gio/modules"
    export KIVY_HOME="${SCRIPT_PATH}/.kivy"
    
    # activate the conda environment
    # ADDED
    source activate kivy
    
    # if an app is available, use it
    # SUPPRESSED
    # if [ -d "${SCRIPT_PATH}/yourapp" ]; then
    #   cd "${SCRIPT_PATH}/yourapp"
    #   if [ -f "main.so" ]; then
    #       exec ${SCRIPT_PATH}/python -c "import main"
    #     exit 1
    #   fi
    #     if [ -f "main.pyo" ] || [ -f "main.opt-2.pyc" ]; then
    #         exec ${SCRIPT_PATH}/python -OO -m main "$@"
    #     exit 1
    #     else
    #         exec ${SCRIPT_PATH}/python -m main "$@"
    #     exit 1
    #     fi
    
    # ADDED
    if [ $# -ne 0 ]; then
        exec python "$@"
    else
        exec python
    fi
    
    # default drag & drop support
    elif [ $# -ne 0 ]; then
            exec ${SCRIPT_PATH}/python "$@"
    
    # start a python shell, only if we didn't double-clicked
    # SUPPRESSED
    # elif [ "$SHLVL" -gt 1 ]; then
    #         exec ${SCRIPT_PATH}/python
    fi

<br>
The following SO questions did not help:
--- 
- [kivy with pycharm import error](http://stackoverflow.com/questions/15444116/kivy-with-pycharm-import-error)  
- [How to configure Python Kivy for PyCharm on Windows?](http://stackoverflow.com/questions/17016259/how-to-configure-python-kivy-for-pycharm-on-windows)

**Comment by ReblochonMasque** [comment]
How to draw attention to this question?

**Comment by bionoid** [comment]
Probably try kivy-users mailing list, #kivy irc channel on freenode, and the support/communities of pycharm/anaconda (GitHub issues reach a very narrow audience, and should not be used for support questions)

**Comment by matham** [comment]
Like @bionoid said this is mainly for bug reports.

**Comment by ReblochonMasque** [comment]
I understand this, and I did also post in the user's mailing list as well... without success.

From these two pages, [Connecting Kivy with Anaconda (OSX)](https://github.com/kivy/kivy/wiki/Connecting-Kivy-with-Anaconda-%28OSX%29), and [Setting Up Kivy with various popular IDE's](https://github.com/kivy/kivy/wiki/Setting-Up-Kivy-with-various-popular-IDE's), I formed the opinion that this is a "bug by omission" in the documentation.

From these talks, which represent a large investment in time and $$, I inferred that there was a will from the kivi core development teams to remove as many obstacles as possible to access the development environment. 
Maybe I was wrong after all?

**Comment by kived** [comment]
The wiki is public, and in particular the Anaconda instructions were written by a Kivy user sharing his own experience, not a dev. I don't use Anaconda myself, some of the other devs do but not most, and most of our users do not use it. The official installation instructions are the ones in the documentation, not the wiki.

**Comment by ReblochonMasque** [comment]
Yes, thank you kived, I hear you.
I am trying to get help, not to be a nuisance. :)
