### ISSUE TITLE
Kivy docs issues

### ISSUE THREAD

**Issue by Leva7** [kivy/kivy#4373]
- The [`ActionBar` documentation](https://kivy.org/docs/api-kivy.uix.actionbar.html) is missing the `ActionLabel` section
- A lot of `ActionBar` sections are poorly documented, they state:

> ... class, see the module documentation for more information.

Without any links or references to where the module documentation is located. The top of the page has a link ("Module: [kivy.uix.actionbar](https://kivy.org/docs/api-kivy.uix.actionbar.html#)") that points to the same page. So where should one look for documentation on these sections?

**Comment by Leva7** [comment]
It's been about three months and no one seems to fix it, is there a way I can contribute? I've checked the doc folder on the repo, but didn't find a place to make the changes

**Comment by tshirtman** [comment]
Sorry, we are a bit behind in matter of bug fixes, it would be welcome if you could edit it quickly and do a pull request, the kv lang doc is in the lang.py (https://github.com/kivy/kivy/blob/d08dba8374c62462d3001f28761118d28d73c982/kivy/lang.py#L395), you could do the edits online and create a pull request through the interface.

Thanks a lot.

**Comment by Leva7** [comment]
For some reason the link you gave me does not work, the page is not found, what's up with that?

**Comment by tshirtman** [comment]
Sorry, did that from the wrong local branch, should have checked, fixed the link.

**Comment by Leva7** [comment]
So, I fixed the typos (sorry for my lack of experience with GitHub :) ), but I don't know how the documentation is assembled, so there's not much I can do to add the missing section. As for the other point, I think that will also have to be decided by devs (whether those sections need more extensive documentation or not)

**Comment by tshirtman** [comment]
Thanks! The documentation is produced by running "make html" in the "doc" directory, if you want to try on your side, the module documentation is the one you are already looking at (module doc is the top one, before the "API" section) , if you want to edit it, you can do the same as before but with https://github.com/kivy/kivy/blob/master/kivy/uix/actionbar.py. If you don't know what do add there, it's ok, we'll try to complete it (i didn't touch this module myself, so not the best one to do that).

btw: please try to avoid editing the previous messages in ways that makes the rest of the conversation confusing, unless it's to fix typos or make the message clearer, it's better to put new messages than editing old ones.

Thanks again for your contribution!

**Comment by Zen-CODE** [comment]
Okay, I've fleshed out and corrected the docs for the ActionBar. The "Please see the module documentation" refers to the ActionBar module itself. It is perhaps confusing, but at least consistent across pretty much all the kivy docs.

If anyone feels anything else needs adding/ correcting, please post specifics and I'll look into it.

Thanks
