### ISSUE TITLE
FileChooser (at least IconView) - unable to access to *.sys files

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4374]
I have experienced a strange error with a FileChooser. I think it shows right on `__init__`? I have spaces in path, on Windows 8.1 64bit with Python 32bit and master branch. Can I trace what process uses the file (i.e. if the problem is on my side) or something that could help me? FileChooser do show files, but `filters` don't seem to work with this error.

How to reproduce:
- Showcase
- switch to FileChoosers
- messages in console

<pre>C:\...\Py27_11>python share\kivy-examples\demo\showcase\main.py
[INFO              ] [Kivy        ] v1.9.2-dev0
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.150
0 32 bit (Intel)]
[INFO              ] [Factory     ] 193 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffp
yplayer ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.2.0 - Build 10.18.10.3316>
[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 4400>
[INFO              ] [GL          ] OpenGL parsed version: 4, 2
[INFO              ] [GL          ] Shading version <4.20 - Build 10.18.10.3316>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Start application main loop
[WARNING           ] [Accordion   ] not enough space for displaying all children
[WARNING           ] [Accordion   ] need 132px, got 84px
[WARNING           ] [Accordion   ] layout aborted.
[ERROR             ] unable to access to <\hiberfil.sys>
Traceback (most recent call last):
  File "C:\...\Py27_11\lib\site-packages\kivy\uix\filechooser.py", line 177, in
 is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process')
[ERROR             ] unable to access to <\pagefile.sys>
Traceback (most recent call last):
  File "C:\...\Py27_11\lib\site-packages\kivy\uix\filechooser.py", line 177, in
 is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process')
[ERROR             ] unable to access to <\swapfile.sys>
Traceback (most recent call last):
  File "C:\...\Py27_11\lib\site-packages\kivy\uix\filechooser.py", line 177, in
 is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process')
[ERROR             ] unable to access to <\hiberfil.sys>
Traceback (most recent call last):
  File "C:\...\Py27_11\lib\site-packages\kivy\uix\filechooser.py", line 177, in
 is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process')
[ERROR             ] unable to access to <\pagefile.sys>
Traceback (most recent call last):
  File "C:\...\Py27_11\lib\site-packages\kivy\uix\filechooser.py", line 177, in
 is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process')
[ERROR             ] unable to access to <\swapfile.sys>
Traceback (most recent call last):
  File "C:\...\Py27_11\lib\site-packages\kivy\uix\filechooser.py", line 177, in
 is_hidden
    return GetFileAttributesExW(fn)[0] & FILE_ATTRIBUTE_HIDDEN
error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process')</pre>

**Comment by kived** [comment]
Those messages seem pretty self-explanatory - Windows won't let you see the attributes of those files. I'd guess this might not happen if you `Run as administrator...` instead. Does this cause any actual issues, or just log messages?

**Comment by matham** [comment]
This is normal on Windows. Maybe it should just be logged to debug and not as an error though.

**Comment by KeyWeeUsr** [comment]
May be the thing. I'll check when I'm on pc again. I experienced nothing special except `filters` that don't work (`filters: ['!.txt']`) probably because of GetAttributesExW not being able to execute? Except them everything should be ok.

**Comment by KeyWeeUsr** [comment]
Nope, even if used `cmd.exe` with admin rights and calling `python ...showcase\main.py`, the logs are still present. Setting `python.exe` to `Run as administrator` in its properties does nothing special about it either.

`filters` work as expected, only I can't make the `not *.txt` work.

**Comment by kived** [comment]
Filters don't work the way you think they do. `filters: ['!.txt']` means to match files named `!.txt`. Look at [fnmatch](https://docs.python.org/2/library/fnmatch.html), as that's what we call internally.

Making a "not text" filter work can be done like so:
`filters: [lambda folder, filename: not filename.endswith('.txt')]`
