### ISSUE TITLE
TextInput hint text does not disappear on focus

### ISSUE THREAD

**Issue by Leva7** [kivy/kivy#4380]
The `hint_text` property states that the hint text will only be shown if text is `''` and focus is `False`. However, it seems to stay when the `TextInput` gets focus. Issue found on `v1.9.2-dev0`
Here is the code:
```
from kivy.base import runTouchApp
from kivy.uix.textinput import TextInput
runTouchApp(TextInput(hint_text = "Hint text"))
```
And the screenshot:
![hint_text_issue](https://cloud.githubusercontent.com/assets/15035286/15960908/7e3c055e-2f1b-11e6-94a5-edf69413399d.png)

**Comment by dessant** [comment]
The behavior has been changed recently, the docs should be updated.

**Comment by Leva7** [comment]
So it won't disappear on focus? If it won't, is there a way to make it disappear? I'd prefer the behaviour described in the docs

**Comment by kived** [comment]
The current behavior is a pretty standard behavior - for example, check the Search field at the top of this GitHub page ;). This behavior is particularly helpful in that you can make input fields without labels, using hint text instead, and not make it a pain for the user when the first field is auto-focused and there's no way to see what that field is supposed to be without focusing a different field.
