### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ceciva** [kivy/kivy#4382]
Heloo everyone. I have been learning Python and now I want to learn how to create applications. I found Kivy and want to install it but I can't since when I write the first instruction in the python command lines, this is what happens. See attach
<img width="675" alt="kivyinstalling" src="https://cloud.githubusercontent.com/assets/19862058/15974919/586a1b58-2f21-11e6-8846-a10ff6f05d49.PNG">

CAn someone help me pleeeeease?
Thank you

**Comment by Kovak** [comment]
This is not a command for the python interpreter. You must run it outside of an interactive python.
