### ISSUE TITLE
Can't resize Kivy window in Windows 10

### ISSUE THREAD

**Issue by nort56** [kivy/kivy#4389]
Hi,

I have installed Kivy and run the sample hello world.  The window pops up fine and looks as expected.  But I don't appear to be able to resize the window.  I can only drag the window and when I do I get the following error message (but the program keeps running):

Traceback (most recent call last):
   File "_ctypes/callbacks.c", line 313, in 'calling callback function'
   File "C:\Python27\lib\site-packages\kivy\input\providers\wm_touch.py", line 207, in_touch_wndProc
     lParam)

See attached a screenshot of the error.  If anyone can suggest a fix that would be greatly appreciated.

Thanks

> > > ================================ RESTART ================================
> > > 
> > > [INFO              ] [Logger      ] Record log in C:\Users\hughn.kivy\logs\kivy_16-06-13_3.txt
> > > [INFO              ] [Kivy        ] v1.9.1
> > > [INFO              ] [Python      ] v2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
> > > [INFO              ] [Factory     ] 179 symbols loaded
> > > [INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
> > > [INFO              ] [Text        ] Provider: sdl2
> > > [INFO              ] [OSC         ] using <thread> for socket
> > > [INFO              ] [Window      ] Provider: sdl2
> > > [INFO              ] [GL          ] GLEW initialization succeeded
> > > [INFO              ] [GL          ] OpenGL version <4.4.0 - Build 20.19.15.4360>
> > > [INFO              ] [GL          ] OpenGL vendor <Intel>
> > > [INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 520>
> > > [INFO              ] [GL          ] OpenGL parsed version: 4, 4
> > > [INFO              ] [GL          ] Shading version <4.40 - Build 20.19.15.4360>
> > > [INFO              ] [GL          ] Texture max size <16384>
> > > [INFO              ] [GL          ] Texture max units <32>
> > > [INFO              ] [Shader      ] fragment shader: <WARNING: 0:7: '' :  #version directive missing>
> > > [INFO              ] [Shader      ] vertex shader: <WARNING: 0:7: '' :  #version directive missing>
> > > [INFO              ] [Window      ] auto add sdl2 input provider
> > > [INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
> > > [INFO              ] [Base        ] Start application main loop
> > > [INFO              ] [GL          ] NPOT texture support is available

![error](https://cloud.githubusercontent.com/assets/19898333/15996361/068f1f9a-316a-11e6-8ec2-a301a5f8eb30.png)

**Comment by tito** [comment]
It may be due to the combination of Windows 10 and 64 bits, need investigation. In case the screenshot disapear one day, the traceback is:

```
 Traceback (most recent call last):
     File "_ctypes/callabacks.c", line 313, in 'calling callback function'
     File "C:\Python27\lib\site-packages\kivy\input\providers\wm_touch.py", line 207, in _touch_wndProc
         lParam)
 WindowsError: exception: access violation writing 0x0000000000000018
```

**Comment by TimSC** [comment]
I just ran into this problem too...

```
[INFO ] [Logger ] Record log in C:\Users\Paul.kivy\logs\kivy_16-09-15_2.txt
[INFO ] [Kivy ] v1.9.1
[INFO ] [Python ] v2.7 (r27:82525, Jul 4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
[INFO ] [Factory ] 179 symbols loaded
[INFO ] [Image ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO ] [Text ] Provider: sdl2
[INFO ] [OSC ] using for socket
[INFO ] [Window ] Provider: sdl2
[INFO ] [GL ] GLEW initialization succeeded
[INFO ] [GL ] OpenGL version <4.5.13453 Compatibility Profile Context 21.19.134.1>
[INFO ] [GL ] OpenGL vendor
[INFO ] [GL ] OpenGL renderer
[INFO ] [GL ] OpenGL parsed version: 4, 5
[INFO ] [GL ] Shading version <4.50>
[INFO ] [GL ] Texture max size <16384>
[INFO ] [GL ] Texture max units <32>
[INFO ] [Window ] auto add sdl2 input provider
[INFO ] [Window ] virtual keyboard not allowed, single mode, not docked
[INFO ] [Audio ] Providers: audio_sdl2 (audio_pygst, audio_ffpyplayer ignored)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[INFO ] [GL ] NPOT texture support is available
libpng warning: iCCP: known incorrect sRGB profile
[INFO ] [Base ] Start application main loop
[INFO ] [GL ] Unpack subimage support is available
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
File "_ctypes/callbacks.c", line 313, in 'calling callback function'
File "C:\Python27\lib\site-packages\kivy\input\providers\wm_touch.py", line 207, in _touch_wndProc
lParam)
WindowsError: exception: access violation writing 0x0000000000000018
```

**Comment by Simply007** [comment]
I have the same issue running showcase demo (with no change) using Python 2.7 and Windows 10:
[INFO   ] [Logger      ] Record log in C:\Users\chras\.kivy\logs\kivy_17-06-04_8.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <4.3.0 - Build 20.19.15.4463>
[INFO   ] [GL          ] OpenGL vendor <Intel>
[INFO   ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 4400>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <4.30 - Build 20.19.15.4463>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <WARNING: 0:7: '' :  #version directive missing>
[INFO   ] [Shader      ] vertex shader: <WARNING: 0:7: '' :  #version directive missing>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 132px, got 84px
[WARNING] [Accordion   ] layout aborted.
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 132px, got 84px
[WARNING] [Accordion   ] layout aborted.
 Traceback (most recent call last):
   File "_ctypes/callbacks.c", line 313, in 'calling callback function'
   File "D:\Install\python27\lib\site-packages\kivy\input\providers\wm_touch.py", line 127, in _touch_wndProc
     lParam)
 WindowsError: exception: access violation writing 0x0000000000000018

**Comment by Electro5** [comment]
I am having the same problem as Simply007.  I am also running Python 2.7 w/ Windows 10 and example is not working for me either, I get the same error log.

**Comment by tshirtman** [comment]
i've used kivy on python2.7/windows 10 64bit at work without issue, with or without wmtouch, so i don't think it's linked to that.

**Comment by Mark-Wellings** [comment]
Same error here :-/

**Comment by ElliotGarbus** [comment]
@Julian-O This can be closed.  Not sure what the root was - but I've never experienced the issue.   Lots has changed.

**Comment by Julian-O** [comment]
Closing as stale. Please let us know if the problem still occurs.
