### ISSUE TITLE
Crash application on android 

### ISSUE THREAD

**Issue by ReindeerBY** [kivy/kivy#4391]
I compiled APK file (on **OS X El Capitan)**. All was successful. 
<img width="567" alt="1" src="https://cloud.githubusercontent.com/assets/17070596/16007911/bab0ce8e-317d-11e6-84ae-8e6934dd41c0.png">
But on the phone, my application crash. **Android 5.1**  PyCharm **Python 3.4.4**
![2](https://cloud.githubusercontent.com/assets/17070596/16008009/4a855c28-317e-11e6-887e-812ebb74ee35.jpg)

I installed cython, kivy and buildozer with pip3.
**buildozer.spec**
    
    # (str) title of your application
    title = my application
    
    # (str) package name
    package.name = myapp
    
    # (str) package domain (needed for android/ios packaging)
    package.domain = org.test
    
    # (str) source code where the main.py live
    source.dir = .
    
    # (list) source files to include (let empty to include all the files)
    source.include_exts = py,png,jpg,kv,atlas
    
    # (list) list of inclusions using pattern matching
    #source.include_patterns = assets/*,images/*.png
    
    # (list) source files to exclude (let empty to not exclude anything)
    #source.exclude_exts = spec
    
    # (list) list of directory to exclude (let empty to not exclude anything)
    #source.exclude_dirs = tests, bin
    
    # (list) list of exclusions using pattern matching
    #source.exclude_patterns = license,images/*/*.jpg
    
    # (str) application versioning (method 1)
    version = 0.1
    
    # (str) application versioning (method 2)
    # version.regex = __version__ = ['"](.*)['"]
    # version.filename = %(source.dir)s/main.py
    
    # (list) application requirements
    # comma seperated e.g. requirements = sqlite3,kivy
    requirements = kivy
    
    # (str) custom source folders for requirements
    # sets custom source for any requirements with recipes
    # requirements.source.kivy = ../../kivy
    
    # (list) garden requirements
    #garden_requirements =
    
    # (str) presplash of the application
    #presplash.filename = %(source.dir)s/data/presplash.png
    
    # (str) icon of the application
    #icon.filename = %(source.dir)s/data/icon.png
    
    # (str) supported orientation (one of landscape, portrait or all)
    orientation = landscape
    
    # (list) list of service to declare
    #services = name:entrypoint_to_py,name2:entrypoint2_to_py
    
    #
    # osx specific
    #
    
    #
    # author = © copyright info
    
    #
    # android specific
    #
    
    # (bool) indicate if the application should be fullscreen or not
    fullscreen = 0
    
    # (list) permissions
    #android.permissions = internet
    
    # (int) android api to use
    android.api = 23
    
    # (int) minimum api required
    #android.minapi = 9
    
    # (int) android sdk version to use
    android.sdk = 23
    
    # (str) android ndk version to use
    #android.ndk = 9c
    
    # (bool) use --private data storage (true) or --dir public storage (false)
    #android.private_storage = true
    
    # (str) android ndk directory (if empty, it will be automatically downloaded.)
    #android.ndk_path =
    
    # (str) android sdk directory (if empty, it will be automatically downloaded.)
    #android.sdk_path =
    
    # (str) ant directory (if empty, it will be automatically downloaded.)
    #android.ant_path =
    
    # (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
    #android.p4a_dir =
    
    # (list) python-for-android whitelist
    #android.p4a_whitelist =
    
    # (bool) if true, then skip trying to update the android sdk
    # this can be useful to avoid excess internet downloads or save time
    # when an update is due and you just want to test/build your package
    # android.skip_update = false
    
    # (str) android entry point, default is ok for kivy-based app
    #android.entrypoint = org.renpy.android.pythonactivity
    
    # (list) list of java .jar files to add to the libs so that pyjnius can access
    # their classes. don't add jars that you do not need, since extra jars can slow
    # down the build process. allows wildcards matching, for example:
    # ouya-odk/libs/*.jar
    #android.add_jars = foo.jar,bar.jar,path/to/more/*.jar
    
    # (list) list of java files to add to the android project (can be java or a
    # directory containing the files)
    #android.add_src =
    
    # (str) python-for-android branch to use, if not master, useful to try
    # not yet merged features.
    #android.branch = master
    
    # (str) ouya console category. should be one of game or app
    # if you leave this blank, ouya support will not be enabled
    #android.ouya.category = game
    
    # (str) filename of ouya console icon. it must be a 732x412 png image.
    #android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png
    
    # (str) xml file to include as an intent filters in <activity> tag
    #android.manifest.intent_filters =
    
    # (list) android additionnal libraries to copy into libs/armeabi
    #android.add_libs_armeabi = libs/android/*.so
    #android.add_libs_armeabi_v7a = libs/android-v7/*.so
    #android.add_libs_x86 = libs/android-x86/*.so
    #android.add_libs_mips = libs/android-mips/*.so
    
    # (bool) indicate whether the screen should stay on
    # don't forget to add the wake_lock permission if you set this to true
    #android.wakelock = false
    
    # (list) android application meta-data to set (key=value format)
    #android.meta_data =
    
    # (list) android library project to add (will be added in the
    # project.properties automatically.)
    #android.library_references =
    
    # (str) android logcat filters to use
    #android.logcat_filters = *:s python:d
    
    # (bool) copy library instead of making a libpymodules.so
    android.copy_libs = 1
    
    #
    # ios specific
    #
    
    # (str) path to a custom kivy-ios folder
    #ios.kivy_ios_dir = ../kivy-ios
    
    # (str) name of the certificate to use for signing the debug version
    # get a list of available identities: buildozer ios list_identities
    #ios.codesign.debug = "iphone developer: <lastname> <firstname> (<hexstring>)"
    
    # (str) name of the certificate to use for signing the release version
    #ios.codesign.release = %(ios.codesign.debug)s
    
    
    [buildozer]
    
    # (int) log level (0 = error only, 1 = info, 2 = debug (with command output))
    log_level = 1
    
    # (int) display warning if buildozer is run as root (0 = false, 1 = true)
    warn_on_root = 1
    
    # (str) path to build artifact storage, absolute or relative to spec file
    # build_dir = ./.buildozer
    
    # (str) path to build output (i.e. .apk, .ipa) storage
    # bin_dir = ./bin
    
    #    -----------------------------------------------------------------------------
    #    list as sections
    #
    #    you can define all the "list" as [section:key].
    #    each line will be considered as a option to the list.
    #    let's take [app] / source.exclude_patterns.
    #    instead of doing:
    #
    #[app]
    #source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
    #
    #    this can be translated into:
    #
    #[app:source.exclude_patterns]
    #license
    #data/audio/*.wav
    #data/images/original/*
    #
    
    
    #    -----------------------------------------------------------------------------
    #    profiles
    #
    #    you can extend section / key with a profile
    #    for example, you want to deploy a demo version of your application without
    #    hd content. you could first change the title to add "(demo)" in the name
    #    and extend the excluded directories to remove the hd content.
    #
    #[app@demo]
    #title = my application (demo)
    #
    #[app:source.exclude_patterns@demo]
    #images/hd/*
    #
    #    then, invoke the command line with the "demo" profile:
    #
    #buildozer --profile demo android debug
`

Project files are attached below (**buildozer.spec, test.py, my_application.apk**)
[Project.zip](https://github.com/kivy/kivy/files/311776/Project.zip)

**Comment by werton** [comment]
- without the log file, we can only guess what happened in your program
- for such questions use the forum
- the main python script must have a name main.py

**Comment by tito** [comment]
As @werton, use kivy-users forums or irc, and provide your application log.
