### ISSUE TITLE
3Drendering example not looking fine on Android

### ISSUE THREAD

**Issue by rolfschr** [kivy/kivy#4393]
I have taken the stock ``examples/3Drendering`` folder, used buildozer to create an Android package and run it on my phone. The result is not nice (see pictures). I feel this is more a problem of the example (shader) code than of kivy but I don't know exactly. Of course, it could also be my phone's problem! The same code looks fine on my desktop machine.

![screenshot_2016-06-13-21-49-21](https://cloud.githubusercontent.com/assets/1188465/16041659/f06c72d0-3236-11e6-9bd5-8f9980017270.png)
![screenshot_2016-06-13-21-49-32](https://cloud.githubusercontent.com/assets/1188465/16041660/f0793178-3236-11e6-9bf7-25d69a3cf0aa.png)
![screenshot_2016-06-13-21-49-42](https://cloud.githubusercontent.com/assets/1188465/16041661/f07a240c-3236-11e6-8867-1dff328b5be6.png)

Here's my computer:
```
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
$ python -V
Python 2.7.6
$ dpkg -s python-kivy | grep -P '(Version|Depe)'
Version: 1.9.1-0~stable0+201602121318~pkg103~ubuntu14.04.1
Depends: python:any (<< 2.8), python:any (>= 2.7.5-5~), python-kivy-common (= 1.9.1-0~stable0+201602121318~pkg103~ubuntu14.04.1), python-kivy-bin (= 1.9.1-0~stable0+201602121318~pkg103~ubuntu14.04.1), python-docutils, python-pygments, python-gst0.10, xclip, xsel
$ dpkg -s kivy-examples | grep -P '(Version|Depe)' 
Version: 1.9.1-0~stable0+201602121318~pkg103~ubuntu14.04.1
Depends: python:any (>= 2.7.5-5~), python-kivy (= 1.9.1-0~stable0+201602121318~pkg103~ubuntu14.04.1)
$ buildozer --version
Buildozer 0.33dev
```

My (somewhat outdated) phone is :
```
$ adb shell getprop ro.product.manufacturer
samsung
$ adb shell getprop ro.product.model
GT-S7390
$ adb shell getprop ro.build.version.release 
4.1.2
$ adb shell getprop ro.build.version.sdk 
16
```

I also attach the adb logcat output:
[adblog.txt](https://github.com/kivy/kivy/files/313836/adblog.txt)

Let me know if I should provide further details.

**Comment by MichaelPython** [comment]
i had seen the exact same thing on one of my older phones, which has nvidia tegra2 GPU. on every other device it works fine. so the problem is from the hardware.

**Comment by rolfschr** [comment]
Okay, thanks for letting me know. I kinda feared that. I guess this "solves" the issue.
