### ISSUE TITLE
Dynamic widgets like Enaml's "Looper" and "Conditional" in kv lang 

### ISSUE THREAD

**Issue by frmdstryr** [kivy/kivy#4405]
Does Kivy lang have anything similar to the [Conditional](https://nucleic.github.io/enaml/docs/examples/ex_conditional.html) or [Looper](https://nucleic.github.io/enaml/docs/examples/ex_looper.html) present in enaml for dynamic manipulation of the widget tree?

**Comment by matham** [comment]
See https://kivy.org/#support. Github issues is to report bugs and not for support questions. There are also other issues open requesting loops in kv.
