### ISSUE TITLE
No Callback When Text Is Cleared in TextInuput

### ISSUE THREAD

**Issue by Crunch2600** [kivy/kivy#4409]
textinput.bind(text=on_text)

This runs a callback when text changes in the TextInput widget, but when the text is cleared, by Backspace, Delete keys, or any means I should think, it doesn't run the callback.

**Comment by matham** [comment]
Works for me on master:

```py
from kivy.app import runTouchApp
from kivy.uix.textinput import TextInput

class Text(TextInput):

    def __init__(self, **kw):
        super(Text, self).__init__(**kw)
        self.bind(text=self.echo)

    def echo(self, *largs):
        print(self.text)

runTouchApp(Text())
```

prints
```
h
he
hey
hey 
hey t
hey th
hey the
hey ther
hey there
hey there?
hey there
hey ther
hey ter
hey er
ey er
y er
 er
er
r
```

As I type and delete the text `hello there?`.

**Comment by Crunch2600** [comment]
Just to clarify, it works fine as I am deleting individual characters while there is still text in TextInput, but as as soon as I delete the last character, resulting in no text left in TextInput, it does not run the callback. Is this intended behavior? It might be comparing the absence of a string to the previous string and deciding that there is no change because there's nothing to compare it to.

**Comment by dessant** [comment]
Share an example which reproduces your issue, kivy version, os, etc.

I've tested master and the callback fires after deleting the last char.
