### ISSUE TITLE
Is this normal? 

### ISSUE THREAD

**Issue by h2Devel** [kivy/kivy#4413]
So I was running manjaro and kept getting this error. I tried everything I could to track it down, but it didn't seem too common. So I wiped my entire system, and loaded a fresh/clean install of Ubuntu 16.04. 

Copied the hello world text from the homepage and got the same thing, then copy and pasted the pong source code. It runs, but gives me this error every time. Am I missing something here?

[kivy_output.txt](https://github.com/kivy/kivy/files/322160/kivy_output.txt)

**Comment by dessant** [comment]
@matham, is this still valid? https://github.com/kivy/kivy/issues/1503#issuecomment-48820806

**Comment by dessant** [comment]
@h2Devel, do you have mtdev installed?

**Comment by h2Devel** [comment]
Just installed 'mtdev-tools', and 'libmtdev-dev', and still no dice.

**Comment by h2Devel** [comment]
Oh.... But I'm not using a touch screen.... And from what I've gathered, the permission error has something to do with the track pad of some laptops. What I'm mostly concerned with is the threading issue.

**Comment by matham** [comment]
@dessant no clue.

**Comment by h2Devel** [comment]
updated a bunch of stuff, and still no change.

from kivy.app import App


class MyWindowApp(App):
    pass

window = MyWindowApp()
window.run()

=============================

/usr/bin/python3.5 /home/harley/PycharmProjects/Kivy/basic.py
[INFO              ] [Logger      ] Record log in /home/harley/.kivy/logs/kivy_16-06-20_10.txt
[INFO              ] [Kivy        ] v1.9.2-dev0
[INFO              ] [Python      ] v3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330]
[INFO              ] [Factory     ] 193 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 361.42'>
[INFO              ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO              ] [GL          ] OpenGL renderer <b'GeForce GTX 560M/PCIe/SSE2'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event5
[INFO              ] [MTD         ] Read event from </dev/input/event5>
[INFO              ] [Base        ] Start application main loop
 
Exception in thread Thread-1:
 
Traceback (most recent call last):

   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
     self.run()

   File "/usr/lib/python3.5/threading.py", line 862, in run
     self._target(*self._args, **self._kwargs)

   File "/usr/lib/python3/dist-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
     _device = Device(_fn)

   File "/usr/lib/python3/dist-packages/kivy/lib/mtdev.py", line 143, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)

 PermissionError: [Errno 13] Permission denied: '/dev/input/event5'
 
[INFO              ] [Base        ] Leaving application in progress...

Process finished with exit code 0

**Comment by Kovak** [comment]
You can fix this by chmod the correct input file, but this will change at
every startup. Even without giving the file the right permissions
everything should work fine you just won't have multi-touch capabilities
for the touchpad. It should still function as a mouse. This is a non
critical error. Not certain of a permanent fix.

**Comment by h2Devel** [comment]
That would be fine if that was the only issue. But if I try to do something a little more advanced than just put text on the screen, nothing displays:

import kivy
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.boxlayout import BoxLayout


class MyWindowApp(App):
    def build(self):
        btn = Button(text="Push Me!")
        lbl = Label(text="Read Me!")
        layout = BoxLayout()
        layout.orientation = 'vertical'
        layout.add_widget(lbl)
        layout.add_widget(btn)
        return


window = MyWindowApp()
window.run()

====================================

[INFO              ] [Logger      ] Record log in /home/harley/.kivy/logs/kivy_16-06-20_31.txt
[INFO              ] [Kivy        ] v1.9.2-dev0
[INFO              ] [Python      ] v3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330]
[INFO              ] [Factory     ] 193 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 361.42'>
[INFO              ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO              ] [GL          ] OpenGL renderer <b'GeForce GTX 560M/PCIe/SSE2'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event5
[INFO              ] [MTD         ] Read event from </dev/input/event5>
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available

 Exception in thread Thread-1:

 Traceback (most recent call last):

   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
     self.run()

   File "/usr/lib/python3.5/threading.py", line 862, in run
     self._target(*self._args, **self._kwargs)

   File "/usr/lib/python3/dist-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
     _device = Device(_fn)

   File "/usr/lib/python3/dist-packages/kivy/lib/mtdev.py", line 143, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)

 PermissionError: [Errno 13] Permission denied: '/dev/input/event5'
 
[INFO              ] [Base        ] Leaving application in progress...

Process finished with exit code 0

**Comment by dessant** [comment]
@h2Devel, you have to `return layout` in your last example.

**Comment by dessant** [comment]
It seems the actionable part would be what @matham's post says, checking for available input devices and only using the reachable ones, while logging the rest without tracebacks.

**Comment by h2Devel** [comment]
*smh... Ok, so at least it's running, but still the same errors.

**Comment by Zen-CODE** [comment]
The issue in the original post has been covered. Adding this to the documentation is covered here. https://github.com/kivy/kivy/issues/4682

Thanks
