### ISSUE TITLE
FileChooserListView - bad position for Sizes

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4416]
What title says. It's positioned badly even inside folders. Maybe some separator was removed or Label size is its text's size?

![image](https://cloud.githubusercontent.com/assets/8825439/16177251/a0f5a660-3626-11e6-868a-eea056fa378b.png)

**Comment by matham** [comment]
Yeah, I noticed that as well.

**Comment by KeyWeeUsr** [comment]
@akshayaurora https://github.com/kivy/kivy/commit/ab3c3fe52ce353d77e803f68b116c982f59aeef9 this breaks positioning of `name`s because it centers them #3922.  What was the original intention? If the text is too long/wide, the result is `Lo....ext`, so this probably isn't it.

@Zen-CODE https://github.com/kivy/kivy/commit/1907f1bf4b36f9d1f87ab81630a9276f73fc37a9 this fixes the centering, but only to cripple size position instead (ref screenshot above)
