### ISSUE TITLE
Clock.schedule_interval more limited than expected

### ISSUE THREAD

**Issue by bibile** [kivy/kivy#4417]
Hello,

Many thanks to the kivy team for building kivy!

I tried to use Clock.schedule_interval to set a timer to record some data in my Kivy application.
Found some limits, I ask users here:
https://groups.google.com/forum/#!topic/kivy-users/3Iubhg6nhvo

Seems that whatever we set, the smallest dt is around 0.01283s
I could not understand where from this comes, tried to change the maxfps without any success.

Requesting for a period of 0.1s brings (on my PC) an average dt of 0.1027s.
That's not very precise.

Maybe, should write something in the documentation about the limits.

For people running into same problem, can use Timer object from the standard lib, ex:
http://stackoverflow.com/questions/12435211/python-threading-timer-repeat-function-every-n-seconds

**Comment by matham** [comment]
I guess it should be documented that kivy's clock always returns time not as the actual time but the frame time which tends to be a function of the frame rate.

**Comment by bibile** [comment]
Will be perfect to see it in the documentation.
I used it as it is, thinking that a 100Hz timer is pretty easy to achieve, today, for a computer. But actually, I got only ~80Hz, running into this limitation.

**Comment by matham** [comment]
By rolling my own kivy clock, using event timeouts, I am able to get 1kHz. But for games it's important to get a predicable clock hence the default kivy behavior.

**Comment by Kovak** [comment]
Do you have a sample program that demonstrates the issue:

I can get a kivent game with framerate unlocked to run at 3000+ fps, clock is definitely capable of running at an even smaller dt

**Comment by bibile** [comment]
Actually, I do not target fps, just a nice use of kivy Clock.schedule_interval as a timer, to save some data.


```
# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.label import Label
from kivy.uix.boxlayout import BoxLayout
from kivy.clock import Clock
import csv, datetime

class Container(BoxLayout):

    def __init__(self, *args, **kwargs):
        super(Container, self).__init__(*args, **kwargs)
        self.orientation = 'vertical'
        bt = Button(text='start timer')
        bt.bind(state=self.start_rec)
        self.add_widget(bt)
        self.lab = Label()
        self.add_widget(self.lab)

    def start_rec(self, bt, state):
        if state == 'down':
            self.memory = []
            print datetime.datetime.now()
            self.thread_memory = Clock.schedule_interval(self.reccord_row, 0.01)
       
    def reccord_row(self, dt):
        now = datetime.datetime.now()
        now = (now.minute * 60 * 1000000 + now.second + now.microsecond) / 1000.
        self.memory.append([dt, now])
        if len(self.memory) == 1000:
            print datetime.datetime.now()
            self.thread_memory.cancel()
            with open('test.csv', 'wb') as f:
                writer = csv.writer(f)
                writer.writerows(self.memory)
            average = sum([e[0] for e in self.memory])/len(self.memory)
            self.lab.text = 'average: {}'.format(average)
            print 'done'
   
       
class TestApp(App):
    def build(self):
        self.container = Container()
        return self.container


if __name__ == '__main__':
    TestApp().run()

```

here Clock.schedule_interval(self.reccord_row, 0.01)
I try to get a 100Hz Timer.
You can try Clock.schedule_interval(self.reccord_row, 0.001) to get a 1000Hz
You will see that you can not get better than a period of 0.01283s, something around 80Hz

**Comment by matham** [comment]
I just tested and I got 12-13kHz when setting `maxfps` to zero using:

```py
from kivy.app import runTouchApp
from kivy.uix.widget import Widget
from kivy.clock import Clock
from time import clock


class Events(Widget):

    trigger = None
    t = clock()
    f = []
    last_t = t

    def __init__(self, **kwargs):
        super(Events, self).__init__(**kwargs)
        self.f = []
        self.trigger = Clock.create_trigger(
            self.callback, timeout=0.001)
        self.trigger()

    def callback(self, *l):
        t = clock()
        self.f.append(1 / (t - self.t))
        if t - self.last_t >= 1.0:
            print('fps', sum(self.f) / max(1, len(self.f)))
            self.f = []
            self.last_t = t
        self.t = t
        self.trigger()

runTouchApp(Events())
```

The issue of course is that CPU went through the roof. The one I made myself used a event so that we didn't actually have to walk the events 12,000 times a sec and CPU was minimal.

**Comment by bibile** [comment]
I tried your script.
Added an explicit change of maxfps, and printing a few more things

```
from kivy.config import Config
Config.set('postproc', 'maxfps', '0')
Config.write()

from kivy.app import runTouchApp
from kivy.uix.widget import Widget
from kivy.clock import Clock
from time import clock


class Events(Widget):

    trigger = None
    t = clock()
    f = []
    last_t = t

    def __init__(self, **kwargs):
        super(Events, self).__init__(**kwargs)
        print self.t
        self.f = []
        self.trigger = Clock.create_trigger(
            self.callback, timeout=0.001)
        self.trigger()

    def callback(self, *l):
        #print self.f
        t = clock()
        self.f.append(1 / (t - self.t))
        if t - self.last_t >= 1.0:
            print('fps', sum(self.f) / max(1, len(self.f)), len(self.f), t, self.last_t)
            self.f = []
            self.last_t = t
        self.t = t
        self.trigger()

runTouchApp(Events())
```

Actually, surprised with the outputs:

> ('fps', 1845.1417117386989, 1675, 1.076692, 0.076152)
> ('fps', 1757.0488113671274, 1717, 2.07701, 1.076692)
> ('fps', 1781.662071470891, 1744, 3.077483, 2.07701)
> ('fps', 1739.9652620841441, 1716, 4.077871, 3.077483)
> ('fps', 2008.446633244311, 1838, 5.078472, 4.077871)
> ('fps', 1926.7985469400749, 1819, 6.078652, 5.078472)

The 2 last data are fine.
But I would expect that len(self.f) would be 1000. Actually, the callback was called around 1700 times, for each set of 1s. That seems to be almost twice than expected, no ?

**Comment by matham** [comment]
I'm working on some more clock changes. But the basic idea is that you should not rely on the current kivy clock as a accurate timing mechanism. Because it doesn't know long event processing will take, it's greedy and processes events once it's "close enough" to the timeout. That's what you're seeing.

**Comment by bibile** [comment]
ok, thank you for explaining.
I hope the clock behind Animation is not that bad, because I use it to drive some "precise" user tests.
Looks like that:
```
anim =  Animation(x=50, duration=0.2)
anim += Animation(x=20, duration=0.5)
anim += Animation(x=110, duration=0.3)
anim.start(widget)
```
So far, seems ok, timeout are fairly large.
To save my data at 100Hz, I will use an external Timer (or ZMQ Poller)
Should I close this issue ?

**Comment by matham** [comment]
#4436 adds some documentation as well as various clock options so that should fix this doc issue. The clock does fine for animations since it's not as sensitive to exact timing. But I would not rely on it for exact timing.
