### ISSUE TITLE
How to add print command on_press

### ISSUE THREAD

**Issue by sheenawadhwa** [kivy/kivy#4421]
I have a sample code. That having menu on click options. I want to open csv file when i press a particular button and print its data. I am aware how to print csv file data with simple button but in menu am confused where to insert the data. i want to add read csv option and print its data under button. Click on "Teacher Information" > "Click here for teacher information" > This will ask for choose csv file from the folder > Then prints the data in python shell or on its own console window..

Any help will be appriciated

    from kivy.app import App
    from kivy.lang import Builder
    from kivy.uix.screenmanager import ScreenManager, Screen

    Builder.load_string("""
    <MenuScreen>:
        BoxLayout:
            Button:
                text: 'Teacher Information'
                on_press: root.manager.current = 'teacher'

            Button:
                text: 'Student Information'
                on_press: root.manager.current = 'student'
 
            Button:
                text: 'Attendence'
                on_press: root.manager.current = 'attendence'

            Button:
                text: 'Quit'

    <TeacherScreen>:
        BoxLayout:
            Button:
                text: 'Click here to see Teacher Information'
                on_press: root.manager.current = 'teacher'
            
            Button:
                text: 'Back to menu'
                on_press: root.manager.current = 'menu'
 
    <StudentScreen>:
        BoxLayout:
            Button:
                text: 'Click here to see Student Information'
            Button:
                text: 'Back to menu'
                 on_press: root.manager.current = 'menu'

    <AttendenceScreen>:
        BoxLayout:
            Button:
                text: 'Click here to see Teacher Attendence'

            Button:
                text: 'Click here to see Student Attendence'

            Button:
                text: 'Back to menu'
                on_press: root.manager.current = 'menu'

    """)

    class MenuScreen(Screen):
        pass

    class TeacherScreen(Screen):
        pass

     class StudentScreen(Screen):
         pass

     class AttendenceScreen(Screen):
        pass

    sm = ScreenManager()
    sm.add_widget(MenuScreen(name='menu'))
    sm.add_widget(TeacherScreen(name='teacher'))
    sm.add_widget(StudentScreen(name='student'))
    sm.add_widget(AttendenceScreen(name='attendence'))

    class TestApp(App):

        def build(self):
            return sm

     if __name__ == '__main__':
        TestApp().run()

**Comment by dessant** [comment]
https://github.com/kivy/kivy#support
