### ISSUE TITLE
[kivy dev 1.9.2] No module named 'kivy._clock'

### ISSUE THREAD

**Issue by jligeza** [kivy/kivy#4428]
I've just installed kivy 1.9.2 dev for python 3.5 from the daily ppa, and running a very simple app throws this error:
```
[INFO   ] [Logger      ] Record log in /home/stefan/.kivy/logs/kivy_16-06-24_21.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.1 (default, Dec 18 2015, 00:00:00)
[GCC 4.8.4]
 Traceback (most recent call last):
   File "main.py", line 3, in <module>
     from kivy.app import App
   File "/usr/local/lib/python3.5/dist-packages/kivy/app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 29, in <module>
     from kivy.clock import Clock
   File "/usr/local/lib/python3.5/dist-packages/kivy/clock.py", line 234, in <module>
     from kivy._clock import CyClockBase, ClockEvent
 ImportError: No module named 'kivy._clock'
```

**Comment by matham** [comment]
See https://github.com/kivy/kivy/pull/4412#issuecomment-228455735.

**Comment by jligeza** [comment]
@matham Any news on this issue? Kivy 1.9.2 can't be installed from the setup script in the repo either.

**Comment by matham** [comment]
@thopiekar is the one who maintains these ppas.

**Comment by thopiekar** [comment]
Hey there. Broken package builds because of new modules/files?

**Comment by jligeza** [comment]
@thopiekar Yes, you were pinged about it by dessant in the comment link above.

**Comment by thopiekar** [comment]
According to the logs the _clock module should be there. Eg. for Python3:
```/usr/lib/python3/dist-packages/kivy/_clock.cpython-35m-x86_64-linux-gnu.so```

**Comment by jligeza** [comment]
@thopiekar The module is there, but for some reasons its impossible to import it or any of its content.

**Comment by jligeza** [comment]
@thopiekar I have fixed the issue by renaming all `so` files to `*.so` from `*.cpython-34m-x86_64-linux-gnu.so`. Why these files aren't just `*.so`?

**Comment by thopiekar** [comment]
It is a convention on Ubuntu/Debian to make it possible to install different python releases at once.  Additionally it makes it possible to install different architectures, too.

I see no reason why it fails. There is even a packaging tool, which cares about it. So honestly not my fault 🙄

**Comment by thopiekar** [comment]
However strange that this happens here.

**Comment by thopiekar** [comment]
Oh, wait the files are named for Python 3.4, but you've got Python 3.5 installed? How does it come? Wrong PPA enabled or the repository entry not updated after distribution upgrade?

**Comment by jligeza** [comment]
@thopiekar In my case, the `apt-get` uses `python3`, which links to `/usr/bin/` (used by the OS), but for my projects I use python 3.5, that links to `/usr/local/bin/`. Anyway, even if I launch an app with py 3.4, it still fails.

The py 3.5 works, but I see these warnings upon an app start: [link](http://pastebin.com/NnzCMeMk)

**Comment by thopiekar** [comment]
Because you mixed up binary modules which were built for Python 3.4 with Python 3.5.
Our PPA isn't meant to be used with custom installations. If you want to use deb packages always be sure you also use the Ubuntu repositories to install all your needs. If there is Python 3.5 missing for you, you should think about upgrading to Ubuntu Xenial.

Therefore...

**Comment by frankgould** [comment]
I am getting the same results with python 2.7:

>python main-test.py
[INFO   ] [Logger      ] Record log in c:/users/frank gould/build/data/logs\mp-ss_16-12-06_0.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
 Traceback (most recent call last):
   File "main-test.py", line 1, in <module>
     from kivy.app import App
   File "C:\Users\Frank Gould\Desktop\Master-Pics\SlideShow Build\kivy\app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "C:\Users\Frank Gould\Desktop\Master-Pics\SlideShow Build\kivy\base.py", line 29, in <module>
     from kivy.clock import Clock
   File "C:\Users\Frank Gould\Desktop\Master-Pics\SlideShow Build\kivy\clock.py", line 364, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ImportError: No module named _clock

**Comment by flyyn** [comment]
Is there something I can follow to fix this issue? I am having the same problem . No module named kivy_clock

**Comment by AndiEcker** [comment]
Recently I had also problems to update/install kivy on one of my windows
machines (my main Ubuntu machine is still fine).

The fix for me was to use the nightly wheel installation files like
described here:
https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation.
This removed my old/broken kivy version 1.9.1 installation and replaced it
with the version 1.9.2 which now works for my old kivy apps as well as for
my new one.

HTH

2016-12-29 14:07 GMT+00:00 Luis yuri meshi <notifications@github.com>:

**Comment by flyyn** [comment]
Thanks for the quick response. Does this apply to installing it on the raspberry PI as well? 

Thanks.

**Comment by AndiEcker** [comment]
Sorry but just noticed that the nightly wheels packages are only available
for Windows :/.

Assuming you already tried the instructions on
https://kivy.org/docs/installation/installation-rpi.html.

The missing kivy._clock error is possibly coming from a wrong version of
cython installed on your RPI. Did you tried to revert to an older version
of cython by specifying cython==0.20.1 in your buildozer requirements?
Additionally you should probably also use the stable kivy release 1.9.1
(instead of the Kivy Master branch as the main tutorial suggests) - more
info in this post:
https://groups.google.com/forum/#!topic/kivy-users/OSpnIv4a_S4

2016-12-29 17:54 GMT+00:00 Luis yuri meshi <notifications@github.com>:

> Thanks for the quick response. Does this apply to installing it on the
> raspberry PI as well?
>
> Thanks.
>
> Sent from my iPhone
>

**Comment by flyyn** [comment]
It's ok . I tried this before and I got it to work once but after I rebooted my pi and got stuck in the log in screen . I am going to try this method again. Thanks .

**Comment by Saeed-Pooyanfar** [comment]
hi, i have this problem too!
```
[INFO   ] Logger: Record log in /home/saeed/.kivy/logs/kivy_17-10-27_37.txt
[INFO   ] Kivy: v1.10.0
[INFO   ] Python: v3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609]
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/home/saeed/PycharmProjects/second_project/main.py", line 4, in <module>
[WARNING] stderr:     from kivy.app import App
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/kivy/app.py", line 319, in <module>
[WARNING] stderr:     from kivy.base import runTouchApp, stopTouchApp
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/kivy/base.py", line 29, in <module>
[WARNING] stderr:     from kivy.clock import Clock
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 362, in <module>
[WARNING] stderr:     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
[WARNING] stderr: ModuleNotFoundError: No module named 'kivy._clock'
[WARNING] stderr: Error in sys.excepthook:
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
[WARNING] stderr:     from apport.fileutils import likely_packaged, get_recent_crashes
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
[WARNING] stderr:     from apport.report import Report
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
[WARNING] stderr:     import apport.fileutils
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
[WARNING] stderr:     from apport.packaging_impl import impl as packaging
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
[WARNING] stderr:     import apt
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
[WARNING] stderr:     import apt_pkg
[WARNING] stderr: ModuleNotFoundError: No module named 'apt_pkg'
[WARNING] stderr: 
[WARNING] stderr: Original exception was:
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/home/saeed/PycharmProjects/second_project/main.py", line 4, in <module>
[WARNING] stderr:     from kivy.app import App
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/kivy/app.py", line 319, in <module>
[WARNING] stderr:     from kivy.base import runTouchApp, stopTouchApp
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/kivy/base.py", line 29, in <module>
[WARNING] stderr:     from kivy.clock import Clock
[WARNING] stderr:   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 362, in <module>
[WARNING] stderr:     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
[WARNING] stderr: ModuleNotFoundError: No module named 'kivy._clock'
```
any advice?

**Comment by MichaelJames02** [comment]
I have the same problem on ubuntu 18.04, python 3.6.5

**Comment by dolang** [comment]
@MichaelJames02 This can also happen when there's a system installation (e.g. from the PPA) and a local copy (e.g. `git clone ...`).

For Ubuntu 18.04 I recommend using the [daily PPA](https://kivy.org/docs/installation/installation-linux.html#ubuntu-kubuntu-xubuntu-lubuntu-saucy-and-above) right now, and make sure your working directory doesn't have a copy of Kivy.

If the problem still persists, please open a new issue with all the details of your setup, instead of commenting on an old one.

**Comment by MichaelJames02** [comment]
Thank you! The daily build work for me.

**Comment by hemangjoshi37a** [comment]
@michaelgabriel01 Any download link you got for daily built??
Thank you.

**Comment by Mallick10** [comment]
> @MichaelJames02 This can also happen when there's a system installation (e.g. from the PPA) and a local copy (e.g. `git clone ...`).
> 
> For Ubuntu 18.04 I recommend using the [daily PPA](https://kivy.org/docs/installation/installation-linux.html#ubuntu-kubuntu-xubuntu-lubuntu-saucy-and-above) right now, and make sure your working directory doesn't have a copy of Kivy.
> 
> If the problem still persists, please open a new issue with all the details of your setup, instead of commenting on an old one.

thank you.. worked for me

**Comment by saurabhtra** [comment]
no need to do anything complex in that 
just add a line to your code/main file as below

from kivy_deps import sdl2, glew

but before that if you have not install there modules than install that by 
pip install kivy.deps.sdl2
pip install glew

**Comment by juliocesarbt** [comment]
The spyder does not work with kivy. You need to compile first. Try Visual Studio.

**Comment by juliocesarbt** [comment]
need to compile to run on spyder,  he has the command to compile.

**Comment by matham** [comment]
Spyder is just and IDE and does work with kivy. You just have to make sure to install Kivy as specified in the current install page.
