### ISSUE TITLE
Kivy android app crashes after opening

### ISSUE THREAD

**Issue by FarhanQ7** [kivy/kivy#4429]
http://stackoverflow.com/questions/38024299/my-kivy-android-app-keeps-crashing-on-start-up-even-though-it-runs-perfectly-fin

**Comment by rafalo1333** [comment]
The issues part of the repo is mean for submitting internal bugs in Kivy, not the programming skills related problems, such as APK building problem. @dessant I believe this issue should be deleted.

@FarhanQ7 I believe you have not included avi files in your APK, but without logcat there is nothing we can do. Remember to post your programming problems on Kivy IRC channel on freenode, we'll be glad to help, but not here. Thanks.
