### ISSUE TITLE
IDEA: AutoReloader For Kivy

### ISSUE THREAD

**Issue by Theydarking** [kivy/kivy#4431]
After using kivy for a while, I liked it but it is quit annoying to have run the code every time we made a change in the .kv file. So it it possible in implement a Automatic Reloader for kivy that does that in a "programming mod" ? It's just an idea I don't know hos fesable it is.

**Comment by dessant** [comment]
You could give this a try: https://github.com/kivy/kivy/blob/master/kivy/tools/kviewer.

**Comment by Theydarking** [comment]
Thanks !
