### ISSUE TITLE
TextInput - a minimum size is required for text(generates window freeze)

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4437]
<pre>
from kivy.lang import Builder
from kivy.base import runTouchApp
from kivy.uix.boxlayout import BoxLayout
Builder.load_string('''
#:import Factory kivy.factory.Factory
&lt;Test&gt;:
    orientation: 'vertical'
    BoxLayout:
        Button:
            on_release:
                here.add_widget(Factory.TextInput(text='glitch'))
                self.text = str(len(here.children))
                value.text = str(here.width / float(len(here.children)))
        Label:
            id: value
        Button:
            text: 'Smaller'
            on_release: root.size_hint_x = root.size_hint_x / 2.0
        Button:
            text: 'Change to vertical'
            on_release: here.orientation = 'vertical'
    BoxLayout:
        size_hint_y: 0.5
        id: here
''')
class Test(BoxLayout): pass
runTouchApp(Test())
</pre>

As it's said above, the TextInput _requires_ some minimal space for the text. It's not like it's required for every text-based widget, only for TextInput because you can add how many Labels/Buttons/... you like. However, TextInput stops after the 41st one in the 600px window(for me at least) and shows, that each TextInput requires 18 - 19px width.

This may be intended e.g. for correct displaying of the cursor, which I think is bound to one of size properties, yet it's critical to at least print a warning or return a minimum amount of required space. Ofc I intend to use it in ScrollView, so no such issue should be present, but it still requires attention.

You should easily find the issue, because it's present even for resizing. Meaning: If I for example add >= half of the possible TextInputs' count for the present parent's width and then make parent's width smaller, it freezes too.

Also it is good to mention that if `vertical` orientation is set, the glitch is not present. The same applies if no text is set. I think it may be related to one of these: #4244 #3770

**Comment by LogicalDash** [comment]
Can you try applying #4445? I think it might fix this issue.

**Comment by KeyWeeUsr** [comment]
@LogicalDash yup, PR does the job, thanks! :)
