### ISSUE TITLE
docutils rst parser triggers virus on Windows 7 and Windows 10

### ISSUE THREAD

**Issue by BillBridge** [kivy/kivy#4439]
For the following code piece I need to have docutils included in my PyInstaller script:

                tpitem = string.Template('''
    AccordionItem:
        id: '$acc_id'
        title: '$acc_title'
        font_name: 'Roboto'
        min_space: 30
        RstDocument:
            background_color: 1, 1, 1, 1
            source: '$rstdoc'
                ''')
    
                for idx in range(0, self.totevents):
                    event = str(idx + 1)
                    acc_id = 'acc_' + event
                    evidx = 'Event' + event + ':'
                    rstdoc = qglobals.PROJDIR + tempInstrData[evidx]['RstDoc:']
                    acc_title = str(tempInstrData[evidx]['Instruction:'])
    
                    new_acc = tpitem.substitute(vars())
                    acc = Builder.load_string(new_acc)
                    acc_panel.add_widget(acc)

Unfortunately at build time this triggers my virusscanner with the following virus: Gen:Variant.Razy.41062 - though my PC is clean.
When setting the build environment to the list of accepted (do not include in scanning) folders the build produces a distribution package. But when installing this package on another PC with another virusscanner, same virus is triggered..

When adding docutils to the list of excluded modules in my PyInstaller script, the application is build without any virus triggers but then of course the lack of docutils results in an error message:

![image](https://cloud.githubusercontent.com/assets/18249253/16459789/831e4e3e-3e24-11e6-9f12-91a650f81777.png)

Here is the PyInstaller spec file:

[test-spec.txt](https://github.com/kivy/kivy/files/339705/test-spec.txt)

**Comment by KeyWeeUsr** [comment]
What file is reported by the antivirus? PyInstaller had again problem with [`run.exe`](https://github.com/pyinstaller/pyinstaller/issues/656) files reported as viruses recently (this appears sometimes, but seems to be false) and the installation might not be complete. But anyway, this should be reported in their repo or in docutils repo, not in kivy.

**Comment by BillBridge** [comment]
It is indeed when building the run.exe. However, when I include docutils then the virus is reported. That's why I related this to the kivy part. Anyway, I will report this in the respective repo.

**Comment by BillBridge** [comment]
Some further info on this. It occurs only when building sg-assist.exe with option console = True ; see attached test-spec.txt file above.

**Comment by dessant** [comment]
@BillBridge, usingned executables are ofted flagged by AV software, but there's nothing kivy or docutils can do about it. Your best option is to buy a certificate and start signing your executables, or use a self-signed cert and wait until AV vendors whitelist it.
