### ISSUE TITLE
Feature Request: Multiple Windows For Desktop Applications.

### ISSUE THREAD

**Issue by phil-andrews** [kivy/kivy#4442]
This would be absolutely huge. I desperately want to use Kivy to build a number of applications but this hold back is the one and only reason I can't do it. There would be no reason to use another GUI framework.

**Comment by inclement** [comment]
This has come up before - I believe it's likely to be non-trivial, as Kivy's internals were written to not worry about multiple window states, I think as a deliberate choice when it emerged that full multi-window support (with multiple opengl contexts etc) would be hard. A PR to add this feature or work towards it would probably be welcome, but for these reasons I don't think any core dev is likely to look at it soon.

**Comment by KeyWeeUsr** [comment]
I'd like to add that you can do pseudo-multiwindow with kivy in three ways(app = file with `<main class>().run()`):

1. Single app, one space - widgets as forms("windows")

2. Single app divided into admin & client parts launched multiple times where admin would probably handle communication

3. One+ app (launching forms from running app):
  - Running another interpreter instance via subprocess (`python another.py` or similar)
  - Running an app via multiprocessing (if crashes/freezes, probably all will go down)

However it's not that hard to have multiple windows with kivy as it is with those steps, rather the communication is (or at least for me) kind of problematic and non-elegant (read _ugly_).

Also, I don't want it to sound rude, but what is that special snowflake use case that _needs_ multiple windows?

**Comment by phil-andrews** [comment]
You're right, opening a second window isn't terribly difficult. You can do it in about 12 lines of code with `subprocess`. You can even handle killing it with `subprocess`. The issue is passing data back and forth between windows. 

The scenario is multiple displays. I need to display a window on screen two that takes in data from the client portal on screen one. Then, the data needs to be refreshed as the client sees fit. It's not massively complicated but passing data back and forth is, you're right, ugly.

**Comment by KeyWeeUsr** [comment]
That's why I mentioned that bad bad communication :yum: What you may try is using a local server between opened windows. I've had this idea in mind since I've seen (now it's called) [remi](https://github.com/dddomodossola/remi), which is nicer than using e.g. files or accessing the app with some other ugly way. This way you may write app that autoconnects & checks something `on_start()`

Or... look at [this](http://stackoverflow.com/q/2080660/5994041) Q&A that is about multiprocessing and sharing stuff (object there), but the deeper you go, the worse it'll be. Also, the more users will use those client-like apps, the better seems to me to use a local server and with your main app only manipulate data in that. If I remember correctly, Kivy supports Twisted, but it may be an overkill too, so you can look at remi's `server.py`

**Comment by inclement** [comment]
@KeyWeeUsr I don't think it's particularly unreasonable to need multiple windows. It's easy to come across places where you want one app across e.g. two monitors, in which case one opengl context isn't a great fit. You can always hack *something* together, but from a user perspective it would certainly be much easier if kivy did the abstraction internally.

**Comment by KeyWeeUsr** [comment]
I'm not saying it's unreasonable in general, I'm trying to say that there is thin line between use cases of multiple forms(one app handles all forms) and using two separate apps(windows) with even server to manage the communication. I'm mentioning it because it'd probably do more harm than provide benefits and it'd probably be great time-consumer with rebuilding kivy. However, I don't say I'm right about the cost of this feature and maybe it's easier than I expect it to be now.

**Comment by phil-andrews** [comment]
Thanks for the suggestions and the help. I ultimately did get this up and running. There are still some issues to deploying a work around like this but alls well that ends well. Here's a [write up](https://medium.com/@PhilipAndrews/the-kivy-frontier-multiple-independent-windows-a23717c64547#.gwsubqddd) I did on the methods used.

**Comment by KeyWeeUsr** [comment]
I'm glad you found a way with Kivy. This could be a very good contribution to the [wiki](https://github.com/kivy/kivy/wiki) if you have some working example. :yum:

**Comment by phil-andrews** [comment]
That'd be great. The project is coming right along. As soon as I have it ready for release I'm all for it.

**Comment by tito** [comment]
I think this is never going to happen in the future in Kivy.

This is very difficult to achieve, by the fact we are in OpenGL and there is only one global context that we need to switch when you want to draw on one windows or another. 

Unless there is a considerable effort from the community or a core dev, best is to open multiple windows as separate process, and use IPC to communicate.

**Comment by Enteleform** [comment]
An alternative for passing data between windows is to use [**Tendo's Singleton pattern**](https://pythonhosted.org/tendo/_modules/tendo/singleton.html#SingleInstance). I haven't used it for multiple windows, but it should work pretty much the same. In my case, I use a single implementation of the Singleton pattern, with an added `callback` parameter to `__init__` which is executed it in place of the `logging.error("Another instance is already running, quitting.")` instances.  This allows subsequent calls from the command line to forward arguments to the initial instance of the app.

Here's a simplified version of [**my implementation**](https://gist.github.com/Enteleform/1ffe39b29467ab8ba0de537c6c1fb8de).

If you need more flexibility from the passed arguments, you can implement [**argparse**](https://docs.python.org/3.6/library/argparse.html) or maybe send JSON strings as arguments.

**Comment by HalfWhitt** [comment]
I realize this is old and closed, and also that I'm only one person, but for what it's worth, I agree this would be a huge deal. I'm just getting started trying out Kivy, and I'm really liking it so far (it's so much more Pythonic and understandable than the Python bindings for Qt), but I'm not looking forward to figuring out the workarounds when it comes time to try and make multiple windows/processes communicate with each other.

If I get to the point of learning and understand Kivy's internals, I'll absolutely see what I can do about contributing toward this. For now, this is just a hopeful +1, and an expression of appreciation for all you've done so far.
