### ISSUE TITLE
Valgrind shows 700+ errors in "Hello World" application

### ISSUE THREAD

**Issue by dzmitrykrukouski** [kivy/kivy#4443]
I was made application with many different objects, big lists of data and so on, and i noticed that my application uses a lot of memory and decided to check it out with help Valgrind.

This what i had seen in my console
`ERROR SUMMARY: 281197 errors from 375 contexts (suppressed: 3769 from 129)`

Then I decided to check simple `Hello World` application, this is result
`ERROR SUMMARY: 717 errors from 55 contexts (suppressed: 1067 from 98)`

**This is normal?**

Valgrind command
`valgrind --suppressions=valgrind-python.supp python main.py`

valgrind-python.supp i get from here
[https://svn.python.org/projects/python/trunk/Misc/valgrind-python.supp](https://svn.python.org/projects/python/trunk/Misc/valgrind-python.supp)

**Comment by dessant** [comment]
Could you share a gist with the errors?

**Comment by dzmitrykrukouski** [comment]
This is full Valgrind log file
[http://pastebin.com/P63Fzauy](http://pastebin.com/P63Fzauy)

**Comment by bionoid** [comment]
AFAIK you should be using a python interpreter built with ```--with-pydebug --without-pymalloc --with-valgrind``` - did you take that into account, @dzmitrykrukouski ?

**Comment by dzmitrykrukouski** [comment]
@bionoid Oops sorry, i really forgot run app with python debug version, now "Hello World" application without errors.  But my application still have many errors, may be you can help me?
[http://pastebin.com/EEY3iwL2](http://pastebin.com/EEY3iwL2)

Thanks!

**Comment by bionoid** [comment]
Unless you identify leaks/other issues with kivy itself, this does not belong on the issue tracker. 

Sorry debugging your application is far outside of my time budget, you would probably be better off posting your code and valgrind logs to kivy-users, or asking the valgrind community directly.
