### ISSUE TITLE
Slackware and Kivy

### ISSUE THREAD

**Issue by dslackw** [kivy/kivy#4457]
THIS IS NOT A ISSUE.

Kivy is available for Slackware users via SlackBuild.org repository.

https://slackbuilds.org/repository/14.2/libraries/Kivy/

I think you can add in download area:
https://kivy.org/#download

Thank you
Dimitris

**Comment by Zen-CODE** [comment]
Hope this satisfies? Thanks

https://github.com/kivy/kivy-website/commit/a9cc6235705df1a2116d016c1b35b842bf1e3ae2

**Comment by Zen-CODE** [comment]
#dslackw. Thanks :-)
