### ISSUE TITLE
VirtualBox: texture.so: undefined symbol: glGenerateMipmap

### ISSUE THREAD

**Issue by michaeldz** [kivy/kivy#4459]
Hi !

I have installed latest versions kivy (1.9.1 and 1.9.2-dev) on virtualbox guest (ubuntu 16.04 x64 & ubuntu 14.04 x32) with guest additions. When I try to run app (hello world) I have got error:
ImportError: /home/xxx/kivyinstall/local/lib/python2.7/site-packages/kivy/graphics/texture.so: undefined symbol: glGenerateMipmap.
It looks like the kivy does not support the virtual box video driver - without VB ext pack it works.
I use 5.0.24 VB with 5.0.24r108355 VB ext pack.

**Comment by gorgonaut04** [comment]
I have this issue too! I recently upgraded my virtualbox/extensions, and started running into this problem. Can't run Kivy on Linux at all now! I have 14.04

**Comment by KeyWeeUsr** [comment]
I haven't had problems with ext pack installed. Try updating/reinstalling, if they haven't fixed it yet?

**Comment by gorgonaut04** [comment]
Seems to be an issue with 3D acceleration enabled. Running the VM with 3D acceleration disabled on VirtualBox allows it to run Kivy, but the framerate is like 5fps

**Comment by KeyWeeUsr** [comment]
@gorgonaut04 I had similar problem with slow VM a long long ago, but I made it at least usable with increasing size of swap for the OS(ubuntu for me).

**Comment by neube3** [comment]
This is still current. Host: Win 8.1; guest: Mint 17.3 (Mate). Mine error is a bit different, though - cannot run it at all VM 3D acceleration disabled, get flooded by errors.
Log for 3D acceleration on: http://pastebin.com/YrctRN3q
Log for 3D acceleration off: http://pastebin.com/uGjAV2iS

For now I'm stuck with Windows as developing environment which is worse than suboptimal in my case (no vim, no virtualenv, etc.).

**Comment by luke-h** [comment]
Also trying to use VirtualBox. Host: Windows 10; Guest: Ubuntu 16.04 LTS (both 64-bit).
As suggested in earlier comments I have found it works with 3D acceleration off.

Sad to switch it off as I was just feeling good about how smooth it was running.

**Comment by Saedeas** [comment]
I've run into this exact same issue as well. Turning off the 3D acceleration fixes it, but I'd love to be able to use it.  It makes the VM so much better.
