### ISSUE TITLE
Unexpected behavior with ScrollView in widget stack (v1.9.1)

### ISSUE THREAD

**Issue by johanneshk** [kivy/kivy#4461]
Hi,

I'm experiencing a behavior that seems wrong to me, see this MWE: https://gist.github.com/johanneshk/306cf0dbb95334a37f82928feb618303
If you launch 'main.py' and click on 'some other layout', the according AccordionItem doesn't open, but instead the click is digested by the Element that is the content of this AccordionItem (visible by the prints to the console). If you remove the ScrollView from the widget stack (main2.py), everything works as expected.

So somehow the touch event is wrongly (?) passed to the Element when a ScrollView is in the widget stack. Any idea why?

Please note: I modified the Accordion s.t. it changes size according to the content. I don't know if this might cause the observed behavior?

J.

**Comment by johanneshk** [comment]
I may have found a fix: Replace [this line](https://github.com/kivy/kivy/blob/master/kivy/data/style.kv#L740) with
``
                size: (0,0) if root.collapse else root.content_size
``
This way no touch events are passed to collapsed content. I don't know if this has side effects, works for me so far.

**Comment by ElliotGarbus** [comment]
@Julian-O I recommend closing this issue.  This looks like a support issue where the OP resolved the issue on their own.
