### ISSUE TITLE
App: support background persistence on Android/iOS by default

### ISSUE THREAD

**Issue by rafalo1333** [kivy/kivy#4465]
I've been developing Kivy apps for Android for over 2.5 years. There was no single app that I wanted to get killed after user pressed home button. Every app I have been writing required me to write:

``` python
class SomeApp(App):

    def on_pause(self):
        return True
```

Across the web, on #kivy IRC, in tutorials, on user groups, reddit forums: everywhere users are asking how to prevent the app from being killed when minmised on Android and iOS. Some users using Kivy for the first time think it's not possible to develop the Kivy app that stays in background when minimised. So, its the thing that requires the developers to write more code and at the same time makes the bad first impression that Kivy is limited and cannot do the same as Java/ObjC for the new Kivy users.

My proposal is that default behaviour should be that `on_pause()` method returns `True` on mobile platforms and if someone wants to disable the background persistence of the app, he can override that behaviour. As we see everywhere on the web, we can bet that more than 90% of the users do want the background persistence of the app. It should point to the conclusion, that turning it off should require the override, not turning it on.

I understand that we can label it as `api-break`, but I believe it can give a lot of love to the Kivy from beginning users and more experienced people too, as they wont have to write this simple 2-liner for 1074334764 time in their life.

It will make kivy inline with other framework, which support the default iOS/Android behaviour out-of-the-box.

What do you think?

**Comment by dessant** [comment]
I fully agree with everything you said, defaults should reflect the most common use cases.

**Comment by tito** [comment]
You're right, it's time to make the change and fix the possible issue with it.
