### ISSUE TITLE
App does not resume after plyer.camera.take_picture() on Android

### ISSUE THREAD

**Issue by antocuni** [kivy/kivy#4466]
I am having a weird problem with kivy on Android, which I have been debugging for the whole day.

Suppose to have the very simple program attached here, which contains a button to take a picture using plyer.camera.take_picture:

``` python
from kivy.lang import Builder
from kivy.app import App
from kivy.clock import Clock
from plyer import camera

kv = """
BoxLayout:
    orientation: 'vertical'

    Label:
        text: 'hello'

    Button:
        text: 'take pic'
        on_release: app.take_pic()

    Button:
        text: 'exit'
        on_release: app.stop()
"""

class MyApp(App):
    count = 0

    def build(self):
        import pygame
        print 'pygame version:', pygame.ver
        print 'SDL version:', pygame.get_sdl_version()
        return Builder.load_string(kv)

    def on_pause(self):
        print 'on_pause'
        return True

    def on_resume(self):
        print 'on_resume'

    def take_pic(self):
        print 'taking pic...'
        filename = '/sdcard/foo.jpg'
        camera.take_picture(str(filename), self.picture_taken)        

    def picture_taken(self, filename):
        print 'pic taken', filename

if __name__ == '__main__':
    MyApp().run()
```

If I run it using the Kivy launcher, everything works fine.

If I compile it to an apk, the on_pause/on_resume mechanism works only partially; if I start the app, press the "home" button and then switch back to the app, I can see `on_pause` and `on_resume` in the logcat.
However, when I press "take pic", it hangs. I can see `on_pause` in the logcat, then it correctly displays the camera; however, after taking the picture, the app hangs and "on_resume" is never called.
I build the apk using the following script:

```
#!/bin/bash
BASE="$HOME/.buildozer/android/platform/"
export ANDROIDSDK="$BASE/android-sdk-20/"
export ANDROIDNDK="$BASE/android-ndk-r9c/"
export ANDROIDAPI="19"       # Minimum API version your application require
export ANDROIDNDKVER="r9c"   # Version of the NDK you installed

p4a apk --dir src \
    --package=eu.antocuni.trycam \
    --name "Try Camera" \
    --version 0.1 \
    --bootstrap=pygame \
    --requirements=python2,kivy,pil,android,pygame \
    --permission INTERNET \
    --permission CAMERA \
    --minsdk 13 \
    --orientation portrait \
#    --launcher
```

Since the kivy launcher seems to work fine, I also tried to build my own version of the launcher by adding --launcher to the build script. However, the script exhibits the same wrong behavior even when run through my custom launcher.

I checked the versions of pygame and sdl, and they are the same in my app and in kivy launcher:

```
kivy version: 1.9.1
pygame version: 1.9.1release
SDL version: (1, 2, 14)
```

I use the version of python-for-android installed by pip, which is 0.4.

During the debugging session, I also modified the Java code to insert some more prints; in particular, I `added Log.v()` calls in `PythonActivity.onPause()` and `onResume()`, and I can confirm that even the java `onResume` is **NOT** called.

**Comment by antocuni** [comment]
A quick update on the issue: I tried to build the apk using the `old_toolchain` branch of `python-for-android`, and now the app resumes correctly after `camera.take_picture`.
So, I suspect that the problem relies somewhere in the differences between the old and the new toolchains. Does anybody have a clue about what it could be?

**Comment by KeyWeeUsr** [comment]
Try using higher version of sdk, I had some problems with rotation on old ones with the new toolchain, so maybe the problem is there.

**Comment by hament9193** [comment]
add on_pause() function to you app class like. 
    def on_pause(self):
        return True

**Comment by dessant** [comment]
The old toolchain may not be supported starting the next p4a release, please reopen if the issue can somehow be reproduced with the new toolchain.

**Comment by mokhoo** [comment]
I am trying to include plyer camera in my app and the app also crashes once it uses the camera. Any updates about that issue?

**Comment by AntoniRomera** [comment]
I still have the problem, someone knows how to fix it?

**Comment by akshayaurora** [comment]
@AntoniRomera could you please open a new issue with logs.

**Comment by AntoniRomera** [comment]
@akshayaurora When you refer to logs, what do you need? I am new doing kivy and I do not have much experience
