### ISSUE TITLE
How to scale image?

### ISSUE THREAD

**Issue by Hateman31** [kivy/kivy#4470]
Hello!
I have background image 1294x482 for game.
How to scale it with screens hight 640 pixels?

**Comment by hunternet93** [comment]
You can set an [Image's](https://kivy.org/docs/api-kivy.uix.image.html) [`allow_stretch` property](https://kivy.org/docs/api-kivy.uix.image.html#kivy.uix.image.Image.allow_stretch) to `True` to enable scaling beyond its native resolution:

```python
my_image = Image(source = 'path/to/image.png')
my_image.allow_stretch = True
```

**Comment by Hateman31** [comment]
I do:
` Image:
    source:'path/to/image.png'
    allow_stretch: True
`
But take it:
![test_001](https://cloud.githubusercontent.com/assets/7848512/16899183/e5dd97b4-4c02-11e6-98c8-cebaaf55f74f.png)
