### ISSUE TITLE
Properties not accessible in .kv file in certain instances

### ISSUE THREAD

**Issue by markmelvin** [kivy/kivy#4473]
In the following example, I cannot access my Kivy property using the usual method of:

value: app.root.numeric_value

In fact this will crash with:
 AttributeError: 'NoneType' object has no attribute 'numeric_value'

The workaround online seems to be to conditionally check for "if app.root is not None", but this type of conditional expression does not seem to work either.

The only thing that does seem to work is to somehow get a reference to the root widget itself through the widget hierarchy with:

value: root.parent.parent.manager.parent.parent.numeric_value

Which is a horrible solution.

This doesn't always appear to be broken, but for my app and others it is.  It seems to perhaps be related to the use of a ScreenManager.  Posting a simple example for reference showing it failing and working.

I am using Python 3.4 on Windows 7 (64-bit) with Kivy 1.9.1.

[test_fail.zip](https://github.com/kivy/kivy/files/366858/test_fail.zip)

**Comment by matham** [comment]
Please include a minimum runable example in the issue itself and not as an attachment.

**Comment by markmelvin** [comment]
```python
import kivy
from kivy.app import App
from kivy.properties import ObjectProperty, NumericProperty
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.screenmanager import ScreenManager, Screen
import time
import threading
import random

# Check Kivy required version
kivy.require("1.9.1")


class MainApp(App):
    use_kivy_settings = False

    def build(self,):
        self.root.start()
        # MainWidget is created automatically
        
    def on_stop(self):
        if self.root is not None:
            self.root.stop()

class MainWidget(BoxLayout):
    screen_manager = ObjectProperty(None)
    numeric_value = NumericProperty(0)

    def __init__(self,):
        super(MainWidget, self).__init__()
        self._thread = None
        self.stop_request = False

    def run(self,):
        while not self.stop_request:
            self.numeric_value = random.randrange(0, 1500)
            time.sleep(0.2)

    def start(self,):
        self._thread = threading.Thread(target=self.run)
        self._thread.start()

    def stop(self,):
        self.stop_request = True

        if self._thread is not None and self._thread.is_alive():
            if threading.current_thread() != self._thread:
                self._thread.join()

class Screen1(Screen):
    pass

class Screen2(Screen):
    pass

class SliderScreen(BoxLayout):
    pass

if __name__ == "__main__":
    MainApp().run()
    

# Kivy file

MainWidget:
    name: 'Test Fail'

    screen_manager: sm

    BoxLayout:
        orientation: 'vertical'

        ScreenManager:
            id: sm
            size_hint: (1,.8)

            Screen1:
                id: screen1
            Screen2:
                id: screen2

        BoxLayout:
            size_hint: (1,.2)
            orientation: 'vertical'

            GridLayout:
                cols: 2

                Button:
                    text: 'Screen 1'
                    on_release: sm.current = 'screen1'
                Button:
                    text: 'Screen 2'
                    on_release: sm.current = 'screen2'

<Screen1>:
    name: 'screen1'
    BoxLayout:
        orientation: 'vertical'

        Label:
            id: status_text
            text: 'This is screen 1'

<Screen2>:
    name: 'screen2'
    BoxLayout:
        orientation: 'vertical'

        Label:
            id: status_text
            text: 'This is screen 2'

        SliderScreen:

<SliderScreen>:
    BoxLayout:
        orientation: 'horizontal'
        #pos: 50, 50
        padding:5
        spacing:5
        Slider:
            max: 1500
            orientation: 'vertical'
            on_value: print(app.root, root.parent.parent.manager.parent.parent)
            disabled: False
        Slider:
            max: 1500
            orientation: 'vertical'
            # Uncomment this next line for an exception at GUI build time
            #value: app.root.numeric_value
            disabled: True
        Slider:
            max: 1500
            orientation: 'vertical'
            # This avoids the exception, but simply doesn't work. The value is always 500.
            value: app.root.numeric_value if app.root else 500
            disabled: True
        Slider:
            max: 1500
            orientation: 'vertical'
            # This totally works, but is gawd awful
            value: root.parent.parent.manager.parent.parent.numeric_value
            disabled: True
```

**Comment by bionoid** [comment]
``App.root`` is not an ObjectProperty, which means that rebinding doesn't work in your example. This took me by surprise, I expected your code to work. Possible workarounds:

* Change the code so that app.root is instantiated before the widgets with rules referring to it. For example, instantiate and add the two screens programmatically from Python after app.root is set.
* Move the ```numeric_value``` property somewhere else. You can add it directly to App, since it is an EventDispatcher (and use ```app.numeric_value```). Alternatively, you can create something like a "data" ObjectProperty with rebinding enabled, and set it to your own EventDispatcher subclass instance with properties like numeric_value (and use ``app.data.numeric_value``)

That said, you have an unrelated problem. All OpenGL operations must happen in the main thread. You are using a thread to update a property, which are bound to graphics instructions - this is unsafe. You need to use the ``@mainthread`` decorator (or ``Clock``) when changing the numeric_property.

**Comment by markmelvin** [comment]
Thanks.  I'll give these workarounds a try.

Do you know what is happening with 'app.root.numeric_value if app.root else 500' not working?  Is this also because app.root is not "re-bound"?

And the thread thing was for illustration purposes only.  My real app has everything on the UI thread with a remote server via OSC handling background processing.

**Comment by markmelvin** [comment]
Using an ObjectProperty to hold the data works great.  Now that I have this working it really cleans up my code too as I can use the properties directly in my .kv file in many places I could not before.  Thanks for the help on this one!
