### ISSUE TITLE
on_touch_up does not work with raspistill

### ISSUE THREAD

**Issue by openedhardware** [kivy/kivy#4474]
I am developing kivy application on the official Raspberry Pi touch screen.

I need to preview the video from the picamera, so that ran this in the kivy app.

```python
     os.system("raspistill -p 0,0,500,500 -k")
```
My purpose is to close raspistill when user touches anywhere on the screen.

I have added some codes on the on_touch_up function.

```python
def on_touch_up(self, touch):
    print "touched"
    # do something
```

Problem is that  "touched" does not appear in the console though I touched screen several times.
It appears after closing the raspistill with CTRL+C keyboard interrupt.

Has anybody faced this issue?

**Comment by dessant** [comment]
I think the issue is that your os.system call is blocking the main thread until raspistill exits, so the touch has no chance for being processed. If you need further help, please use the support channels instead: https://github.com/kivy/kivy#support.
