### ISSUE TITLE
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by abarbaro** [kivy/kivy#4476]
Hi,
I'm trying to deploy a the helloworld application to my android device but I have the following error at the end of the process:
Traceback (most recent call last):
  File "build.py", line 517, in <module>
    make_package(args)
  File "build.py", line 365, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
Command failed: python build.py --name 'My Application' --version 0.1 --package org.test.myapp --sdk 19 --minsdk 9 --private /tmp/app/.buildozer/android/app --orientation landscape debug
 
Buildozer failed to execute the last command

Can you help me to fix it?

Thanks

**Comment by abarbaro** [comment]
Hi,
-compile:
    [javac] Compiling 37 source files to /tmp/app/.buildozer/android/platform/python-for-android/dist/myapp/bin/classes
    [javac] error: Source option 1.5 is no longer supported. Use 1.6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.

BUILD FAILED
/home/username/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/username/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

I think I have problems with my java installation...

**Comment by rafalo1333** [comment]
Github issues is not a place to ask for general programming and building problems.

@akshayaurora @dessant another "I dont know how to use github, please help me" thread...

**Comment by abarbaro** [comment]
I have chosen kivy instead of buildozer...

@all: rafalo is always right.
