### ISSUE TITLE
touch.pos for on_touch_down / on_touch_up differ when not moving the mouse

### ISSUE THREAD

**Issue by johanneshk** [kivy/kivy#4477]
I don't understand if this is a bug or a feature:
https://gist.github.com/johanneshk/5bfa9a3983e81a20ed16ed1ff0d80257
Click on the red square and observe the console prints: For me touch.pos for on_touch_down and on_touch_up differ. Why? If you replace ScrollView with RelativeLayout in L.48 it both positions coincide (imo the correct behavior). 
Example:

down <__main__.Element object at 0x7f9b507ebf50> touch.pos (21.0, **32.0**) to window (221.0, 562.0) True
up <__main__.Element object at 0x7f9b507ebf50> touch.pos (21.0, **-448.0**) to window (221.0, 82.0) False

The y-coordinates is shifted in some way I don't understand.

**Comment by bionoid** [comment]
If you click-hold for a second, releasing the mouse button produces an extra "down" event, which probably should not be happening. The output looks like this:

```
down <__main__.Element object at 0x0000000003E118D0> touch.pos (27.0, -503.0) to window (227.0, 27.0) False
down <__main__.Element object at 0x0000000003E118D0> touch.pos (27.0, 27.0) to window (227.0, 557.0) True
up <__main__.Element object at 0x0000000003E118D0> touch.pos (27.0, -503.0) to window (227.0, 27.0) False
```

**Comment by johanneshk** [comment]
Huh... so the position in the second 'down' (which is actually triggered upon button release) is correct. Unfortunately I don't really understand how touch events are digested by ScrollView (but in my opinion the culprit is somewhere in there). So we seem to have two issues:

- why is another 'down' touch event dispatched when releasing the button
- why is the position different

**Comment by uclatommy** [comment]
I am working on a retina screen and this behavior causes buttons to never trigger the `on_release` event. The `touch.pos` when `on_touch_down` occurs is converted `to_local` so `collide_point` is `True`. However, when the mouse is released in the exact same position, the `touch.pos` is in absolute coordinates which are outside of the button's `right` and `top` coordinates. For example, here are the button coordinates:
```
>>> print('x:{}, right:{}, y:{}, top:{}'.format(self.x, self.right, self.y, self.top))
x:0, right:216.0, y:0, top:38
```
I put a breakpoint at `button.py:137` (the `on_touch_down` function) and print the touch position:
```
>>> print(touch.pos)
(72.0, 18.0)
```
I put another breakpoint at `button.py:161` (the `on_touch_up` function) and print the touch position there:
```
>>> print(touch.pos)
(510.0, 1178.0)
```
As a result, the touch is outside of the button bounds and the `on_release` is never dispatched.

**Comment by johanneshk** [comment]
@uclatommy thanks for your input! And printing the stack trace is a great idea (I was wondering how to best follow the touch events through the code and did it by hand / not that successful...).

I'd guess that you found the culprit: The scrollview/touch_up not being converted: If you replace the ScrollView in your widget stack with a RelativeLayout, it should work as expected. 

My guess: The 'simulate_touch_down' function is somehow used to distinguish between touch_down events and drag events (to shift the content of the scrollview). Since this isn't necessary for the on_touch_up events these checks aren't carried out. But somehow the touch_up position isn't converted to local coordinates?

**Comment by uclatommy** [comment]
@johanneshk The `DropDown` class is a subclass of `ScrollView` so that's why the stacktrace looks like that. It's just the way Kivy is implementing the dropdown so there's no getting around the scrollview without editing kivy code. Each drop down element is a button. The `on_touch_down` will call `super().on_touch_down`, which results in that longer stacktrace. But the `on_touch_up` will not call `super().on_touch_up` so it never allows the parent classes to handle the touch event and the touch coordinates never get converted `to_local`. I'm not sure what the Kivy team intended, so I'm not sure what's _supposed_ to happen, otherwise, I'd consider submiting a pull request.

I'm going to handle it by just overriding the button's `on_touch_up` to convert the coordinates myself. It's a temporary fix until the Kivy team addresses the problem.

**Comment by johanneshk** [comment]
OK, maybe my PR has some side effects: FileChooserListView seems to be behaving differently... I'm not sure if this is caused by this PR or some other of my local changes.

**Comment by matham** [comment]
@johanneshk I believe I found the issue and fixed it at https://github.com/kivy/kivy/pull/4508. Can you please test to see if it fixes your issues?

**Comment by matham** [comment]
I think that may finally solve some of the other issues I have been having with ScrollView where a ScrollView within a ScrollView was always messing up.

**Comment by johanneshk** [comment]
@matham yes it seems to work for me as well. Thanks a lot!

Do I close this now or once the PR is merged?

PR #4508 fixes this!
