### ISSUE TITLE
Underline, Strikethrough not working in Label even with markup=True in Android

### ISSUE THREAD

**Issue by mrhdias** [kivy/kivy#4480]
kivy-1.9.1 or kivy-master

buildozer --verbose android debug deploy run logcat

Code to test:

```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label

class TestApp(App):

    def build(self):
        box = BoxLayout(size_hint=(1, 1), orientation='vertical')

        box.add_widget(Label(text='Test Underline', underline=True))
        box.add_widget(Label(text='Test Strikethrough', strikethrough=True))

        box.add_widget(Label(text='Test Markup [u]Underline[/u]', markup=True))
        box.add_widget(Label(text='Test Markup [s]Strikethrough[/s]', markup=True))

        return box

if __name__ == '__main__':
    TestApp().run()
```

**Comment by inclement** [comment]
Are you using SDL2? I think these may only work with this provider.

**Comment by mrhdias** [comment]
Yes, work with SDL2 as bootstrap. But with SDL2 presplash, softinput_mode and webbrowser.open() does not work in Android

**Comment by inclement** [comment]
The presplash should work, feel free to make a p4a issue if it doesn't.

The other two are known issues, but you could check the p4a github pae and register a new issue with full info if they aren't reported there.

Since these functions do work with SDL2 as advertised, I'll close this issue.
