### ISSUE TITLE
Memory leak executing export_to_png fbo with stencilbuffer

### ISSUE THREAD

**Issue by Farkal** [kivy/kivy#4483]
For some reasons i need to stream my kivy app in a web page so i use the export_to_png function (it would be nice to have the same interface for PyGame and SDL2 because i can save image on the format that i want with PyGame by putting the extension on the filename parameter but with SDL2 event if i put an extension on filename it will only save on png) each 20ms to save an image (and then i send it through socket to my server and display it on webpage with js code).

The problem is that my memory consumption increase each time i use this function (i try on Fedora 24 with SDL2 and on CentOS 7.2 with PyGame) so after some experimentations in the kivy code if find that it was linked with the creation of **Fbo** object in _kivy/uix/widget.py_ line 608

`fbo = Fbo(size=self.size, with_stencilbuffer=True)`

If i remove the parameter _with_stencilbuffer=True_  everything is ok (the image is saved) and the memory leak disappear (on CentOs it completely disappear but on Fedora the memory consumption still increase a little).

So i think there is a problem with the **stencilbuffer**

**Comment by riataman** [comment]
I just ran into this in the raspberry pi (egl_pi backend).

**Comment by tito** [comment]
Fixed by #5664 - please reopen if it's not the case.
