### ISSUE TITLE
CoumpoundSelection / RecycleView selection: Allow to unselect an item when "multiselect: False"

### ISSUE THREAD

**Issue by youpsla** [kivy/kivy#4484]
To allow to unselect an item when mutliselect is False, I suggest deleting line 294 of Coumpoundselection.py : « self.select_node(node) »

It works for me. Allow to unselect the only selected item.

**Comment by saqib1707** [comment]
@dessant I think this feature (to be able to  unselect an item when multiselect=False ) has to be there if one doesn't wants to select anything.I am opening a PR for the same.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/issues/4782.
