### ISSUE TITLE
Raspberry pi not displaying

### ISSUE THREAD

**Issue by captainwasabi** [kivy/kivy#4487]
I'm accessing it over xrdp from Win10, but I also tried tightVNC (I couldn't get any xservers to work).  
Anyway, I run the install then try to run the pictures demo and I get this, it looks like it's running but there is no display.

root@raspberrypi:/usr/local/share/kivy-examples/demo/pictures# python main.py
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-07-24_9.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Mar  8 2015, 00:52:26)
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop

Any clues what I'm doing wrong?

I also tried setting KIVY_BCM_DISPMANX_ID=2, made no difference. 

I don't have the 7" LCD installed yet (It'll be ordered tomorrow).

**Comment by zerodarkzone** [comment]
Hi, xrdp does not support openGL, so it cannot show the kivy app
