### ISSUE TITLE
Kivy-Examples Notes not working

### ISSUE THREAD

**Issue by Warlord77** [kivy/kivy#4489]
Kivy-Examples/Tutorials/Notes
Its not working as it doesn't take any input.
OS : Ubuntu 16 
Kivy : 1.9.1

**Comment by KeyWeeUsr** [comment]
Tried now, works for me. Which python? Btw, you need to double-click/tap.

**Comment by akshayaurora** [comment]
The fact that you are supposed to use double click is not that obvious,  there should either be a message somewhere letting user know about that or this should work with just a single click.
