### ISSUE TITLE
pip install kivy.deps.gstreamer failed due to blocked access to www.googledrive.com

### ISSUE THREAD

**Issue by kaichi20** [kivy/kivy#4493]
Due to company firewall policy, access to www.googledrive.com is blocked.

Please consider using github repo, instead of dumping files on googledrive.

**Comment by dessant** [comment]
Not sure if it's worth the trouble, that would be blocked the same way somewhere else.

**Comment by dessant** [comment]
@matham, maybe we could have a kivy.org mirror for them?

**Comment by matham** [comment]
Wouldn't it still be the same issue if it's hosted on kivy.org? Also that
server may not be very fast and I dunno if it could handle so much traffic.
