### ISSUE TITLE
uninstalled kivy but still works "import kivy"

### ISSUE THREAD

**Issue by sivajipr** [kivy/kivy#4503]
I just go through the kivy documentation, paint.py created and it works properly. Then i uninstalled kivy. Now got an error "ImportError: No module named _clock". I open up the python interpreter and type "import kivy", there is no error for this import. Actually the package is not installed. Now I am totally stuck.

**Comment by matham** [comment]
Please see https://kivy.org/#support. Github issues are for bug reports rather than support questions.
