### ISSUE TITLE
Backgroundcolor of ActionBar

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#4506]
This resulted in black:
ActionBar:
      background_color: (0.746,0.8,0.86,0.8)

This resulted in white:
ActionBar:
      background_color: (191,205,219,0.8)

It should be something like light-blue.

According to document:
Background color in the format (r, g, b, a)

**Comment by KeyWeeUsr** [comment]
Yup, the colors are in that format - (r, g, b, a) in interval <0, 1> for each value, but there's also mentioned that the default `background_image` is set to some image from atlas. The way it behaves is tinting the image. If the image is dark already, you'll just make it darker.

    ActionBar:
        background_image: ''
        background_color: (0.746,0.8,0.86,0.8)
