### ISSUE TITLE
Issue while installing kiwi

### ISSUE THREAD

**Issue by HinamoreCh4n** [kivy/kivy#4512]
hey im running in an error when running python setup.py install
im running python 3.4
heres the error:

creating build\temp.win32-3.5\Release\kivy
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\include -IC:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tckivy\properties.c /Fobuild\temp.win32-3.5\Release\kivy\properties.obj
properties.c
kivy\properties.c(2492): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
kivy\properties.c(2627): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
kivy\properties.c(2656): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
kivy\properties.c(2685): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\libs /LIBPATH:C:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86" /EXPORT:PyInit_properties build\temp.win32-3.5\Release\kivy\properties.obj /OUT:build\lib.win32-3.5\kivy\properties.cp35-win32.pyd /IMPLIB:build\temp.win32-3.5\Release\kivy\properties.cp35-win32.lib
   Creating library build\temp.win32-3.5\Release\kivy\properties.cp35-win32.lib and object build\temp.win32-3.5\Release\kivy\properties.cp35-win32.exp
Generating code
Finished generating code
cythoning kivy\graphics/opengl_utils.pyx to kivy\graphics\opengl_utils.c
building 'kivy.graphics.opengl_utils' extension
creating build\temp.win32-3.5\Release\kivy\graphics
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\include -IC:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tckivy\graphics\opengl_utils.c /Fobuild\temp.win32-3.5\Release\kivy\graphics\opengl_utils.obj
opengl_utils.c
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\libs /LIBPATH:C:\Users\Iustin\AppData\Local\Programs\Python\Python35-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86" opengl32.lib glew32.lib /EXPORT:PyInit_opengl_utils build\temp.win32-3.5\Release\kivy\graphics\opengl_utils.obj /OUT:build\lib.win32-3.5\kivy\graphics\opengl_utils.cp35-win32.pyd /IMPLIB:build\temp.win32-3.5\Rel
ease\kivy\graphics\opengl_utils.cp35-win32.lib
   Creating library build\temp.win32-3.5\Release\kivy\graphics\opengl_utils.cp35-win32.lib and object build\temp.win32-3.5\Release\kivy\graphics\opengl_utils.cp35-win32.exp
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewIsRenderbuffer
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewIsFramebuffer
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewGetRenderbufferParameteriv
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewFramebufferTexture2D
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewFramebufferTexture3D
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewRenderbufferStorage
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewCheckFramebufferStatus
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewDeleteRenderbuffers
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewDeleteFramebuffers
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewFramebufferRenderbuffer
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewGenFramebuffers
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewFramebufferTexture1D
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewBindRenderbuffer
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewBindFramebuffer
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewGenRenderbuffers
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewGenerateMipmap
opengl_utils.obj : error LNK2001: unresolved external symbol ___glewGetFramebufferAttachmentParameteriv
build\lib.win32-3.5\kivy\graphics\opengl_utils.cp35-win32.pyd : fatal error LNK1120: 17 unresolved externals
 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120

E:\kivy-master>

Any ideas?

**Comment by KeyWeeUsr** [comment]
Kivy or some of the deps are not VS ready, but I heard some people managed it anyway. Use MinGW/MinGWPy compiler, which is mentioned in the docs for installation on windows.

**Comment by matham** [comment]
Github is for bug reports, see https://kivy.org/#support for support.
