### ISSUE TITLE
Kivy doesn't install properly using the homebrew installation instructions on the website...

### ISSUE THREAD

**Issue by shyamalschandra** [kivy/kivy#4519]
I followed the instructions for installing kivy with MacOS 10.11 and I got the following errors:

![image](https://cloud.githubusercontent.com/assets/9545735/17462584/529e61f6-5c77-11e6-9915-fe3a9772b6dd.png)

after doing the following:

1. brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer
2. pip install -I Cython==0.23
3. USE_OSX_FRAMEWORKS=0 pip install kivy

What should I do?

**Comment by jmercouris** [comment]
This isn't an issue with the instructions or the software, please join the IRC channel to troubleshoot this. This seems more like a problem with your installation, installing kivy from pip works quite fine, the version on pypy (1.9.2) is thoroughly tested. If you have all of the dependencies setup it should be no problem.
