### ISSUE TITLE
HiDPi monitors.

### ISSUE THREAD

**Issue by pylover** [kivy/kivy#4520]
I am getting a small window, which can not read anything.

I found a google group post about moving on sdl2 and supporting HiDPI.

So, is this true?

If yes, how can i use it?

https://groups.google.com/forum/#!topic/kivy-users/TuRY6i_VplU

**Comment by dessant** [comment]
SDL2 is the default provider in the stable version, except on Android if you package with buildozer.

Could you also test with Kivy master? Please share a debug log and a screenshot from the window too.

**Comment by pylover** [comment]
Output log:

	(kivy-py3) vahid@vahid-laptop:~/workspace/kivy/examples/demo/showcase$ python main.py 
	[INFO   ] [Logger      ] Record log in /home/vahid/.kivy/logs/kivy_16-09-04_1.txt
	[INFO   ] [Kivy        ] v1.9.2-dev0
	[INFO   ] [Python      ] v3.5.2 (default, Jul  5 2016, 12:43:10) 
	[GCC 5.4.0 20160609]
	[INFO   ] [Factory     ] 193 symbols loaded
	[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
	[INFO   ] [OSC         ] using <multiprocessing> for socket
	[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
	[INFO   ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 361.42'>
	[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
	[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 960M/PCIe/SSE2'>
	[INFO   ] [GL          ] OpenGL parsed version: 4, 5
	[INFO   ] [GL          ] Shading version <b'4.50 NVIDIA'>
	[INFO   ] [GL          ] Texture max size <16384>
	[INFO   ] [GL          ] Texture max units <32>
	[INFO   ] [Window      ] auto add sdl2 input provider
	[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
	[INFO   ] [Text        ] Provider: sdl2
	[INFO   ] [Clipboard   ] Provider: xsel(['clipboard_dbusklipper', 'clipboard_gtk3', 'clipboard_xclip'] ignored)
	[INFO   ] [CutBuffer   ] cut buffer support enabled
	[INFO   ] [GL          ] NPOT texture support is available
	[INFO   ] [ProbeSysfs  ] device match: /dev/input/event13
	[INFO   ] [MTD         ] Read event from </dev/input/event13>
	[INFO   ] [Base        ] Start application main loop
	 Exception in thread Thread-1:
	[WARNING] [Accordion   ] not enough space for displaying all children
	 Traceback (most recent call last):
	[WARNING] [Accordion   ] need 132px, got 84px
	   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
	[WARNING] [Accordion   ] layout aborted.
	     self.run()
	   File "/usr/lib/python3.5/threading.py", line 862, in run
	     self._target(*self._args, **self._kwargs)
	   File "/home/vahid/workspace/kivy/kivy/input/providers/mtdev.py", line 219, in _thread_run
	     _device = Device(_fn)
	   File "/home/vahid/workspace/kivy/kivy/lib/mtdev.py", line 143, in __init__
	     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
	 PermissionError: [Errno 13] Permission denied: '/dev/input/event13'

	[WARNING] [Accordion   ] not enough space for displaying all children
	[WARNING] [Accordion   ] need 132px, got 84px
	[WARNING] [Accordion   ] layout aborted.

the screen shot: 
![screenshot from 2016-09-04 15-09-47](https://cloud.githubusercontent.com/assets/1302253/18230487/ee30a174-72b1-11e6-9d97-7a54904916c6.png)



Ubuntu 16.04 amd64

**Comment by dessant** [comment]
@pylover, thanks. On Windows and Linux the dpi and scale are hardcoded, this is why you're seeing this issue.

**Comment by pylover** [comment]
Thanks a lot.

**Comment by pylover** [comment]
Pull request #4524 is waiting for this issue. i can not continue. cursor and objects are too small. is there any temporary workaround ? 
please

**Comment by rafalo1333** [comment]
I would try to make dp return 2x bigger values, so you can do something like that before Window is created:

```python
import os
os.environ['KIVY_METRICS_DENSITY'] = '2'
```

Of course you can use bigger value, depending on the needs.

I am not sure if it's the best approach, though.

**Comment by pylover** [comment]
Thanks a lot, it's working.
