### ISSUE TITLE
Are you willing to receive a new settings option?

### ISSUE THREAD

**Issue by niccokunzmann** [kivy/kivy#4521]
I created a new settings option that allows displaying an other value than is written to the config.

![capture](https://cloud.githubusercontent.com/assets/564768/17498733/6d1440ca-5dc9-11e6-89bf-652fc96d7eb2.PNG)
![capture](https://cloud.githubusercontent.com/assets/564768/17498755/88fed20a-5dc9-11e6-8179-1884a27b56cb.PNG)

The implementation is [here](https://github.com/fossasia/kniteditor/blob/master/kniteditor/settings.py#L16).

I am willing to create a pull request and remove the code duplication, etc.
Questions I have:
- Are you willing to receive this widget? 
- Is this the right place to put it or would you prefer it to be in kivy garden or pypi?

I can live with a no. I see you have a lot to do and I do not want to waste your time.

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
