### ISSUE TITLE
Python3 - HIDMotionEvent log formatting 

### ISSUE THREAD

**Issue by biank88** [kivy/kivy#4526]
Kivy: _1.9.2(dev)_
Platform: _Raspberry 3_

There are some issues with string formatting in debug messages when using python3 that are not present with python2.

**python2 - formatting is ok**:
![issue-py2](https://cloud.githubusercontent.com/assets/1591429/17542936/33e1e834-5ecd-11e6-913e-21eebdb0cfe9.png)

**python3 - bad formatting**:
![issue-py3](https://cloud.githubusercontent.com/assets/1591429/17542949/4c1ada32-5ecd-11e6-8e0c-328ff738d354.png)

Edit:
- most certainly this is related to #3075

**Comment by KeyWeeUsr** [comment]
Closing in favor of the original issue #3075.
