### ISSUE TITLE
Clock iteration warning when changing to a screen with an actionbar

### ISSUE THREAD

**Issue by gkanarek** [kivy/kivy#4531]
I've included a minimal working example in [this gist](https://gist.github.com/gkanarek/430296c047f703920629b761b5f9d21a).

One one screen, I have an ActionPrevious with a non-default app_icon. When I switch to that screen, the Clock throws the following warning:

    [CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute

Changing to the default icon removes the warning, as does having the ActionBar outside the ScreenManager. I'm guessing it's a problem with animating the transition, but I'm not sure.

**Comment by dessant** [comment]
@matham, is rising max_iteration still planned?

**Comment by gkanarek** [comment]
I should note, I'm using the dev version of Kivy, on Mac OSX 10.11.5.

**Comment by dessant** [comment]
In my case the symptoms were gone after setting `Clock.max_iteration = 20`, ckeck if you have any success with it.

**Comment by gkanarek** [comment]
Yes, that made the warning go away.

**Comment by matham** [comment]
Yes. PR welcome.

**Comment by mnive93** [comment]
I am getting the same issue. The screen loads properly but I keep getting this warning in a infinite loop. I set the Clock.max_iteration = 20 and it's not working.

**Comment by wenliang** [comment]
same problem with @mnive93  . 
Application works fine. no other problem. but this warning keeps going.

**Comment by MusheAbdulHakim** [comment]
I have the same issue and haven't find answer to it. the interface works fine but the warning keeps coming in my terminal.
