### ISSUE TITLE
Kivy app import effects Rpc

### ISSUE THREAD

**Issue by timeyyy** [kivy/kivy#4539]
### Background

[neovim](https://github.com/neovim/neovim) is a hackers vim with a nice community. They have seperated the ui and gui and expose the communication via rpc. I want to make a kivy interface for vim so i can have a vim text editor widget for kivy.

### The Bug
The following code runs fine if we comment the line with kivy in it
```python
from kivy.app import App # commenting this lets us spin up a neovim proceess and communicate with it
from distutils.spawn import find_executable
from neovim import attach

nvim_binary = find_executable('nvim')
args = [nvim_binary, '--embed']
nvim = attach('child', argv=args) # this call doesn't work properly with our kivy import..
```

With the import kivy line, the last line blocks. It's trying to do an rpc call.

**Comment by Zen-CODE** [comment]
Personally, I don't think this could really be called a bug yet. Kivy is self contained and cannot provide support for external tools that do their own thing. Not that we don't want to get it working, just that we cannot provide support for every library. The code above in no way demonstrates kivy is doing anything wrong.

I would suggest posting on the [forums](https://groups.google.com/forum/#!forum/kivy-users) and seeing if anyone can give you insight there, although without an error log, there is not much to go on...



@timeyyy 
Please close if you agree, or comment otherwise.

**Comment by timeyyy** [comment]
All i'm saying is something weird is going on... I will keep digging into this, i will also be working with the neovim devs. Can i leave this open as a place to post further updates and get feedback?

**Comment by Zen-CODE** [comment]
Sure. You can still post here on your findings and then re-open it if you find it is a flaw in kivy...

Thanks for taking the time. I hope it works out :+1:

**Comment by timeyyy** [comment]
That snippet i posted above is the whole file. Literally that one line import stops me being able to connect over rpc to neovim.

**Comment by timeyyy** [comment]
The behavior only happens when i am using the child method to connect

````    - `_connect_child(argv)`: Use the argument vector `argv` to spawn an
      embedded Nvim that has it's stdin/stdout connected to the event loop.
```
i'm guessing it is because kivy is doing stuff with stdin/stdout

**Comment by bfredl** [comment]
No, `attach('child')` does not use the python stdio handles, from python point of view it is a newly created pair of pipes. You mean you can still connect to a existing nvim instance over a named pipe ( `attach('socket', path=...)` ) ?

**Comment by timeyyy** [comment]
i used `attach('headless)`
It worked, meaning that the call didn't block, like it is doing above (didn't actually test it further)

**Comment by Zen-CODE** [comment]
Great. Thanks both for the follow ups...

**Comment by timeyyy** [comment]
for closure: 
> it appears neovim abuses sys.stderr.fileno() to get the stderr file number, which might not work because Kivy takes over sys.stderr.
