### ISSUE TITLE
Strange touch behaviour without connected ethernet cable in Kivy demo on RPI with Raspitouch

### ISSUE THREAD

**Issue by bertleidi** [kivy/kivy#4540]
Running Kivy (v1.9.2-dev0) on RPI 2 and RPI 3 with Raspitouch-panel (V1 and V1.1) and Python v2.7.9

When trying the pictures-example-app with connected ethernet cable, everything works like expected.
Unplugging the ethernet cable causes multiple nervous and wild self-touches, especially when holding down for some seconds.
The shown pictures on the display start moving and zooming, although the finger touches permanently one point on the screen.

There are no errors/warnings etc in the log (debug mode). 
As well there are no special messages in syslog, messages etc (apart from 'eth0: link down' and 'up').

**Comment by KeyWeeUsr** [comment]
I wonder, did you unplug the cable while running the app, or did you run the app again after you unplugged the cable? Maybe not fully connected display to the rpi?

**Comment by bertleidi** [comment]
It makes not different if I unplug the cable while running the app or unplug first and then start the app. We already tried with different displays (V1 and V1.1) and rpis (V 2, V3); always the same. From the moment I re-plug the cable, the strange behaviour disappears. 
The cable must have a "real" connection to the LAN (the rpi gets an IP etc.); just a cable with loose end shows the same self-multi-touch-thing. It also makes no difference, if I deactivate the device (via ipconfig eth0 down).

**Comment by KeyWeeUsr** [comment]
Does it happen with other (non-kivy) apps too? How did you install kivy?

**Comment by bertleidi** [comment]
We started the X-Window and tried e.g. the Calculator App. There is no such behaviour; everything works just fine. 
We installed kivy via Kivy User Guide "Installation on Rasperry Pi" (https://kivy.org/docs/installation/installation-rpi.html) for Raspbian Jessie.

**Comment by akshayaurora** [comment]
Weird behaviors like this can happen if your power cable/socket does not have proper earthing.
