### ISSUE TITLE
Raspberry Pi 3 "Shader didnt link, check info log."

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#4542]
I get "Shader didnt link, check info log." (in `kivy.graphics.shader.Shader.link_program`) quite frequently when switching between screens on a Raspberry Pi 3. Any idea what can cause this?

**Comment by tshirtman** [comment]
Do you have a specific example, or does it happen with the ScreenManager demo for example?

**Comment by rnixx** [comment]
In my case this happens when switching between screens with transitions. Each screen has a full size background image.

I probably need to write an example, but I'm currently stucked in other stuff

**Comment by darkopevec** [comment]
I managed to get the same critical crash when repeatedly switching between two screens and creating a new transition each time (RiseInTransition and FallOutTransition). Seems like a memory leak on the graphics - after killing python, kivy refused to start and just hung at
[INFO   ] [Window      ] Provider: egl_rpi

**Comment by PiyushRamuka** [comment]
I am having same issue with Fade Transition. I get "glGetError 0x502" a few times & system then crashes. Program works just fine with default slide transition.

**Comment by ebopalisesy** [comment]
I was able to fix this error by increasing the allocated `gpu_mem` in /boot/config.txt to 500M.  That's probably overkill, but I didn't bother to try testing other numbers.

**Comment by frankgould** [comment]
Has there been any solutions to this glGetError 0x502 and crashing problem? I'm having the same issue but can't find a solution. I tried the 512M gpu_mem config but there was no difference, still error and crash.

**Comment by DylanJones** [comment]
I was also getting this problem if I loaded images that were excessively large, for example 10000x8000.   Downscaling the images to something reasonable like 1280x720 or 1920x1080 seemed to fix it, along with not having so many of them.

**Comment by frankgould** [comment]
Thanks Dylan for the response but I tried your suggestion and it still errored out and crashed. I am still searching for answers.

**Comment by frankgould** [comment]
I was experiencing this same shader link problem and with the help of others was able to determine a memory leak in one of the kivy modules that has been fixed. If you can pull the latest kivy master files, you can test to see if this latest version solves this issue. For more information about a repetitive glGetError 0x502 messages, reference #5581. This revision should also fix #4662.

**Comment by tito** [comment]
Fixed by #5664 - Please reopen if it's not the case.
