### ISSUE TITLE
Scrambled label text

### ISSUE THREAD

**Issue by RedCraig** [kivy/kivy#455]
It works fine on my windows desktop, but when I build and move it to the android handset I get text scrambling.
I'm updating a label with a sliders value.
If you move around the slider, the label text scrambles sometimes. Keep moving the slider and it will unscramble.
Keep moving the slider and it scrambles again, with increasing frequency.

Normal:
http://i1220.photobucket.com/albums/dd443/RedMonkey6/label_text_normal.jpg
Scrambled:
http://i1220.photobucket.com/albums/dd443/RedMonkey6/label_text_scrambled.jpg

I've put together the simplest replication case I could where this happens:
http://pastebin.com/3yrMQqWE
The scrambling happens a lot less frequently for this case than it does for my program.

Just to be extra clear, the scrambling only happens when running on my handset, which is a HTC Desire S,
running Android Version 2.3.5.

**Comment by dessant** [comment]
Please reopen if the issue can still be reproduced with kivy master.
