### ISSUE TITLE
kivy example crash when run on android 

### ISSUE THREAD

**Issue by jewelltp** [kivy/kivy#4555]
I am using the example on the kivy website and get the following error in "Error Log". I tried this on my HTC M8 and bought an M10 with the same result. 

I tried the python-to-android by creating a folder with android.txt and the main.py code and it worked. 

Always crashes when running 
buildozer android deploy run logcat from terminal. 
Using:
 mac 10.11.6
standard bulldozer.spec (did not change anything)
Android 6.01

Code:
https://gist.github.com/jewelltp/22a7545d2bd42d49bb097b8ee49f1671

Error Log:
https://gist.github.com/jewelltp/8d31f49d379814ffacc6bd79482cc9ad

**Comment by dessant** [comment]
Let's track this at https://github.com/kivy/python-for-android/issues/487.
