### ISSUE TITLE
Windows build is not working

### ISSUE THREAD

**Issue by Mohamad1994HD** [kivy/kivy#4557]
I have the project structure as in the figure
![prj](https://cloud.githubusercontent.com/assets/11790718/17951801/ba42b42a-6a6d-11e6-82f8-b49ab80d9284.png)

and i have tried to walk through the [tutorial ](https://kivy.org/docs/guide/packaging-windows.html) to create .exe app. and i have got the following .spec file:

`# -*- mode: python -*-
from kivy.deps import glew

block_cipher = None

a = Analysis(['C:\\Users\\Mohamad\\PycharmProjects\\offline_file_archiever\\app\\main.py'],
             pathex=['C:\\Users\\Mohamad\\PycharmProjects\\offline_file_archiever\\build'],
             binaries=None,
             datas=None,
             hiddenimports=['sqlite3'],
             runtime_hooks=[],       
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='sample_build',
          debug=False,
          strip=False,
          upx=True,
          console=True )

		  
coll = COLLECT(exe,Tree('C:/Users/Mohamad/PycharmProjects/offline_file_archiever/app/gui'),
               a.binaries,
               a.zipfiles,
               a.datas,
			   *[Tree(p) for p in glew.dep_bins],
			   strip=False,
               upx=True,
               name='sample_build')
`

However, after navigating to the .exe file and launch it it just open and close,, i can barely catch what is the error happening.
Any help please.

**Comment by dessant** [comment]
Check the 3. step from https://kivy.org/docs/guide/packaging-windows.html#packaging-a-simple-app, the sdl2 import and collect is missing in your spec.

If you need further help, please use the support channels: https://github.com/kivy/kivy#support.
