### ISSUE TITLE
kivy.core.text / LabelBase / Label: missing support for letter-spacing property

### ISSUE THREAD

**Issue by rafalo1333** [kivy/kivy#4562]
We have line_height, font_\* properties, I believe adding a spacing between letters should be an option too.

http://www.w3schools.com/cssref/pr_text_letter-spacing.asp

**Comment by dessant** [comment]
There doesn't seem to be an API for letter spacing in any of the text providers Kivy uses, it would have to involve rendering the chars separately and placing them on a final texture.

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.

**Comment by Sahil-pixel** [comment]
Is it solved?
