### ISSUE TITLE
Make an Android Package out of a CLI

### ISSUE THREAD

**Issue by al3xv3gas** [kivy/kivy#4575]
So before I even start: This is a question.
I have made a little CLI bash terminal like application. Now this application runs fine on all Desktop OSs. Is it possible to compile this CLI app with buildozer and then get an Android app that has that same CLI interface? I'm sorry if this question is silly but I'm looking for a way to compile my CLI into an APK. Thanks to anyone who can enlighten me what roll kivy and/or buildozer can play in this endevaour.

**Comment by inclement** [comment]
Issues like this should be opened for python-for-android, not Kivy.

The answer is that python-for-android supports a range of backends, but doesn't have a cli one right now. I have a vague intention to try it, but haven't yet.

A simple but possibly workable short term option would be to throw together a simple kivy gui with a textinput and Labels to show your output.

**Comment by al3xv3gas** [comment]
Ok sorry, knew there was something I was missing out on. 
1) If you could point me to what I would need to do, I could give it a shot.
2) Ok, that seems fairly easy.
3) Sorry if this seems silly but I am getting my Python mind around Kivy and I saw tuts online where the guy always used classes to invoke certain actions (labels, buttons, textinputfields)... Do I HAVE to use classes or can I just call the different methods and pass some parameters in (text,multiline etc..?)

**Comment by al3xv3gas** [comment]
@increment

**Comment by al3xv3gas** [comment]
* @inclement

**Comment by al3xv3gas** [comment]
@inclement

**Comment by inclement** [comment]
There's no need to make many posts for a small mistake, just edit the first one.

**Comment by al3xv3gas** [comment]
Ok @inclement

**Comment by al3xv3gas** [comment]
Soo...any suggestions? @inclement

**Comment by dessant** [comment]
He probably missed your mentions, you could also try catching @inclement on the #kivy channel (https://github.com/kivy/kivy#support).
