### ISSUE TITLE
Markup for TextInput, like Label

### ISSUE THREAD

**Issue by rubik** [kivy/kivy#459]
Addition of markup tags ([color], [bold], &c.) to TextInput, like Label's ones.

**Comment by badjano** [comment]
how is this closed? there is no markup solution for TextInput

**Comment by badjano** [comment]
How do I make CodeInput work like a MarkupLabel? Is there any ready-to-use lexer for it? I just tried MarkdownLexer but it did not work as I thought it would

**Comment by badjano** [comment]
I just read this: https://pygments.org/docs/lexerdevelopment/
and it seems to me that this solution is very limited to certain tokens, we can't change the colors and we can't change the tokens in real time, so it is far from being a good alternative to a TextInput with MarkupLabel

**Comment by badjano** [comment]
@rubik please reopen

**Comment by brvier** [comment]
It s far better that Markup Label ...

You can implement your own token syntax
You can implement your own style
And all of this in realtime.
