### ISSUE TITLE
Kivy and Windows Remote Desktop

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#4591]
When trying to start a Kivy App via Windows Remote Desktop I get the following message:

![Kivy Fatal Error](https://cloud.githubusercontent.com/assets/246021/18345445/cff21870-75bb-11e6-90d2-e0d6661ca037.jpg)

**Comment by KeyWeeUsr** [comment]
Translation, please? :smile: (or Kivy log would be better probably)

**Comment by dessant** [comment]
The error message is about opengl es 2 not being available, the text is mangled up, but it should have been fixed by https://github.com/kivy/kivy/commit/62e9a78d0a9cca0d2d8dbb24851ace0e0a49be53.

**Comment by matham** [comment]
Are you on master? Either way, it's a driver/windows issue. I'm assuming you're on windows server 2012? That doesn't support kivy. Server 2016, which will come out soonish should. Otherwise, it's a problem with your opengl drivers.
