### ISSUE TITLE
Touch not recognized

### ISSUE THREAD

**Issue by davidseres** [kivy/kivy#4592]
I've implemented the tutorial game [Pong](https://kivy.org/docs/tutorials/pong.html) and the code seems to work fine, except that it doesn't recognize any touch input. Can anyone provide some infos on why that might be?

Currently running Ubuntu 16.04.1 LTS with Gnome 3.18.5 on a Sony Vaio Duo 11" with an Ntrig DuoSense touchscreen.

**Comment by nokianhunter** [comment]
Did you try the kivy Pong example from the examples/tutorials/pong folder so there's no coding error?

**Comment by davidseres** [comment]
Yepp, copied the code one to one yet still no sign of touch recognition. Touchtracer doesn't work aswell.

**Comment by nokianhunter** [comment]
Did you have a look at the log when starting an app? Maybe try verbose python ouput "-v".
btw: Does it work with the touchpad buttons?

**Comment by vliaskov** [comment]
Using another touschscreen (RPI foundation 7'' display), I had to edit ~/.kivy.config,ini and add the last two lines seen below in the input section:

> 
[input]
mouse = mouse
**mtdev_%(name)s = probesysfs,provider=mtdev**
**hid_%(name)s = probesysfs,provider=hidinput**
> 

Maybe there needs to be a similar change for your touchscreen?
See section "Using Official RPi touch display" [https://kivy.org/docs/installation/installation-rpi.html](url)

**Comment by davidseres** [comment]
That solved the problem, thank you! Though the touch input is very lagged...

**Comment by udiboy1209** [comment]
@davidseres Closing this because @vliaskov 's solution worked for you. Open a new issue for the touch lag.
