### ISSUE TITLE
Thread deadlock issue with property on Windows

### ISSUE THREAD

**Issue by pptime** [kivy/kivy#4604]
The following code is blocking on Windows but is not blocking on Linux
```Python
from kivy.app import App
from kivy.uix.textinput import TextInput
from threading import Thread
import time


class TestThread(Thread):

    def __init__(self, ti):
        super().__init__()
        self.ti = ti

    def run(self):
        while True:
            time.sleep(3)
            print("change focus")
            self.ti.focus = True


class TestApp(App):
    def build(self):
        ti = TextInput()
        t = TestThread(ti)
        t.daemon = True
        t.start()
        return ti

if __name__ == "__main__":
    app = TestApp()
    app.run()
```
After investigation, it turns out that "self.ti.focus=True" blocks

**Comment by KeyWeeUsr** [comment]
No. `t.daemon = True` blocks. Put it in `__init__()` like this:

```
def __init__(self, ti):
    super(TestThread, self).__init__()
    self.daemon = True
    self.ti = ti
```

Maybe daemons need to be set in inits i.e. before objects are even created (for Win for some reason)? ^^

**Comment by pptime** [comment]
Indeed, this is just a simple example to reproduce the issue. In reality, I do have a client thread that communicates with a server. According to feedback of the server, the client will update the kivy user interface to get the data from users. So, normally in this circumstance, I would say the thread should be started after the ui is created. Otherwise, the client thread will happend to update an ui component that was not yet created.

**Comment by pptime** [comment]
Does anyone know why there is such a difference between linux and windows?

**Comment by KeyWeeUsr** [comment]
Don't have a clue, but anyway, you inherit from `Thread`. Is there any reason you want to set `daemon=True` outside of the thread? Btw in Python3 there's even `daemon` keyword argument for `Thread()`

**Comment by pptime** [comment]
Yes, that's true. But it is not just a big deal, as the daemon is well set
before starting the thread. I would be more interested by the diff btw W$
and Linux that make such a behavior..

2016-09-14 18:07 GMT+02:00 Peter Badida <notifications@github.com>:

**Comment by matham** [comment]
Your original example doesn't block for me (on py2). What exactly do I need to do to get it to block?

**Comment by pptime** [comment]
You mean python 2 on Windows? I produced that using python 3.5.2 on Windows
with Kivy downloaded from http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by matham** [comment]
I can replicate it on py3 now. Here's your fix, do

```py
def delay(*largs):
    self.ti.focus = True
Clock.schedule_once(delay)
```

instead of just `self.ti.focus = True`. The problem is that you're setting a kivy property from an external thread, which is not allowed. Kivy properties that cause graphics changes (i.e. gl interaction, practically every property is like that) are not allowed from external threads. You need to do it with Clock.

**Comment by pptime** [comment]
Yes, thank you. I have came up with this solution also. That works.
However, if as you said, we are not supposed to set a kivy property from an
external thread, how are we supposed to design the backend of kivy user
interface? With this assumption, the backend's mainloop might be highly
kivy dependent.

2016-09-17 1:07 GMT+02:00 matham <notifications@github.com>:
