### ISSUE TITLE
App crash immediately when open on Android version 6.0.1, but can work well on Kivy Launcher

### ISSUE THREAD

**Issue by BingchenLi** [kivy/kivy#4606]
I have followed the tutorial 'Kivy crash course 2: Building an android apk' https://www.youtube.com/watch?v=t8N_8WkALdE
and successfully built an APK and installed it on my Neuxs 5, but it crashed immediately when I open it. And also my own app has the same issue. However, they can work well via Kivy Launcher. Can someone have some clues on this issue? Because it is more convenient to make the app directly work on phone without via Kivy Launcher.
Thank you!

**Comment by KeyWeeUsr** [comment]
GitHub issues are for reporting bugs. If it works in launcher, but not as a separate app (you built) then it's clearly not a bug, but most probably some bad setting while creating your app. You can get help at [support page](https://kivy.org/#support). I recommend you IRC as it's more in real time. ^^
