### ISSUE TITLE
Kivy-dev, does not work space on Android

### ISSUE THREAD

**Issue by dzmitrykrukouski** [kivy/kivy#4611]
I can't put a space in TextInput widget on Android.
I build my application using `kivy==master, buildozer==master and SDL2.`

Logs contain the row `I/python: [INFO   ] [Clipboard   ] Provider: android`

When i run my application on emulator, i can put a space on virtual keyboard, but not on physical.
On real device i can't put a space on virtual keyboard.

I test it on android 4.4, 5.2 and 6.0.

**Comment by matham** [comment]
Duplicate of https://github.com/kivy/kivy/issues/4605
