### ISSUE TITLE
How to do relative font sizes?

### ISSUE THREAD

**Issue by F483** [kivy/kivy#4613]
I want my text to take up the same relative space independent of the screen resolution.

Having fonts be different relative sizes for every resolution makes it quite difficult to get a decent look for the game I wish to make. Overall I would like everything to be positioned/sized relatively so it does not matter what resolution is being used.

![small resolution](https://cloud.githubusercontent.com/assets/977605/18583382/8ec84374-7c0a-11e6-92f3-91fb7bca39f4.png)

![larger resolution](https://cloud.githubusercontent.com/assets/977605/18583383/8ede944e-7c0a-11e6-913f-bb4ebba2fc79.png)

**Comment by tshirtman** [comment]
i don'this is an usage question, not a bug, please ask on the support chanels (#kivy on freenode, or the kivy-users google group).

**Comment by F483** [comment]
Solution is [here](https://github.com/kivy/kivy/wiki/Viewport-with-fixed-resolution-autofit-to-window) for anyone who ends up here.
