### ISSUE TITLE
Build manylinux wheels

### ISSUE THREAD

**Issue by graingert** [kivy/kivy#4620]
See https://github.com/pypa/manylinux and https://github.com/pypa/python-manylinux-demo for how to build them.

**Comment by KeyWeeUsr** [comment]
Apparently good old pygame already figured it out, so this could be a nice addition. It shouldn't be hard, but I'm a little bit confused with the docker and where actually it puts the stuff, so if someone feels adventurous, it should be just a matter of ripping the right lines from the pr (only small part of it is actually the wheel making) as I don't see too many differences between the demo and PR:

* [pygame manylinux PR](https://bitbucket.org/pygame/pygame/pull-requests/68/manylinux-wheels/diff)

**Comment by matham** [comment]
We finally have wheels using the recently released manylinux2010 docker.
