### ISSUE TITLE
Problems with kivy install instruction

### ISSUE THREAD

**Issue by Mdanbury** [kivy/kivy#4622]
Hi, very much a non prgramming newbie and having difficulties getting Kivy to run on my pi.  I've followed the instructions to the letter on kivy.org and want to run some demo examples. The instructions say cd kivy/examples/demo/showcase by that but I do not have a kivy/examples directory but do have kivy-examples so I typed cd kivy-examples/demo/showcase instead.  Followed by python.main.py as given in the instructions, all I get is ImportError: No module named kivy.app

What do you need to do to fix this?

**Comment by KeyWeeUsr** [comment]
This isn't a bug, but an unsuccessful installation. The issues are for bugs, go to irc or mailing list that are on https://kivy.org/#support to debug installation in real-time.
