### ISSUE TITLE
Issue installing kivy 1.9.1 using brew

### ISSUE THREAD

**Issue by amitvirat** [kivy/kivy#4642]
while installing kivy 1.9.1 using brew I am getting an error "It seems the symlink source is not there: '/Applications/Kivy3.app/Contents/Resources/script'"

The issue might be because kivy3 is being copied as kivy.app into applications. Any resolution for it?

**Comment by manthansharma** [comment]
@amitvirat use this to resolve symlink error

`ln -s /Applications/Kivy.app/Contents/Resources/script /usr/local/bin/kivy`

**Comment by dessant** [comment]
You seem to be mixing two installation methods, try installing the newly released version again.
