### ISSUE TITLE
Video can seek only to position that multiple of five seconds

### ISSUE THREAD

**Issue by germn** [kivy/kivy#4648]
**Code:**

```
import kivy
kivy.require('1.9.1')

from kivy.app import App
from kivy.uix.videoplayer import VideoPlayer


class MyVideoPlayer(VideoPlayer):
    def __init__(self, **kwargs):
        self.source = 'Tavern Brawl.mp4'  # Some video here.
        self.state = 'play'
        super().__init__(**kwargs)


class MyApp(App):
    def build(self):
        return MyVideoPlayer()


if __name__ == '__main__':
    MyApp().run()

```

**Video file I used:** 
[https://yadi.sk/i/WGeoND21vw8yY](https://yadi.sk/i/WGeoND21vw8yY)

**How to reproduce:**
Try to click on player time bar. Starting with fifth second position video position can be changed only to multiple of five seconds: _0:01-0:05_, _0:10_, _0:15_, _0:20_, _0:25_, etc. I can't seek to _0:17_, for example.

This behavior related to [seek](https://kivy.org/docs/api-kivy.uix.video.html#kivy.uix.video.Video.seek) function in general.

**Kivy debug log:**
http://pastebin.com/gVWtfB1Z

**System:**
Windows 10 x64
Python 3.4.4
Kivy 1.9.1

**Comment by matham** [comment]
Try using ffpyplayer? In general this is because when the video is compressed key frames were probably added every 5 seconds. So it may not be able to seek between key frames. I didn't know gst suffers from this, but the solution then is to quickly seek until the correct time one you jumped to the closest 5 second mark.

**Comment by germn** [comment]
Thanks for answer!

> Try using ffpyplayer?

I've just started with Kivy and didn't use anything then standard video widget, but I'll try this (if I'll understand how).

> the solution then is to quickly seek until the correct time one you jumped to the closest 5 second mark

I didn't understand this part. How can I «seek until correct time»? `seek` function doesn't help:

```
self.video.seek(0.07)  # I'm getting at 5 sec. position
self.video.seek(0.08)  # 5 sec.
self.video.seek(0.09)  # 5 sec.
self.video.seek(0.10)  # 5 sec.
self.video.seek(0.11)  # 5 sec.
self.video.seek(0.12)  # 5 sec.
self.video.seek(0.13)  # 5 sec.

self.video.seek(0.14)  # 10 sec.
```

**Comment by BaggioMarco** [comment]
I had the same problem. News on how to fixed? [ERROR ] [ffpyplayer ]video.mp4: Protocol not found
