### ISSUE TITLE
Quickstart example app crashes when using Wacom tablet

### ISSUE THREAD

**Issue by lelandg** [kivy/kivy#4651]
Example in https://kivy.org/docs/guide/basic.html#quickstart fails with Wacom tablet as soon as I click on the window.

Is this a known problem? Full console log:

D:\Python27\python.exe C:/Users/Leland/Documents/Code/Python/Kivy/helloworld.py
[INFO              ] [Logger      ] Record log in C:\Users\Leland\.kivy\logs\kivy_16-10-02_30.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.5.0 NVIDIA 358.91>
[INFO              ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO              ] [GL          ] OpenGL renderer <GeForce GTX 560 Ti/PCIe/SSE2>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <4.50 NVIDIA>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:/Users/Leland/Documents/Code/Python/Kivy/helloworld.py", line 15, in <module>
     MyApp().run()
   File "D:\Python27\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "D:\Python27\lib\site-packages\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "D:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "D:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
     EventLoop.idle()
   File "D:\Python27\lib\site-packages\kivy\base.py", line 330, in idle
     self.dispatch_input()
   File "D:\Python27\lib\site-packages\kivy\base.py", line 304, in dispatch_input
     provider.update(dispatch_fn=self._dispatch_input)
   File "D:\Python27\lib\site-packages\kivy\input\providers\wm_pen.py", line 143, in update
     self.pen.update_time_end()
 AttributeError: 'NoneType' object has no attribute 'update_time_end'

**Comment by lelandg** [comment]
I ran this a second time and it did not crash when I clicked it! IDK how to reproduce it now. :-/ 👎

**Comment by KeyWeeUsr** [comment]
@lelandg hold, move, drag, double-click? Maybe some fancy function of the pen itself (like Samsung's S-pen)?

**Comment by lelandg** [comment]
@KeyWeeUsr good ideas. I just tried about everything I can think of, and it's not crashing. Puzzling because I'm running the same way and everything.

I guess this issue can be closed until I figure out how to reproduce. 

Sorry about that... but it _really did happen!_ Ha! :-)

**Comment by lelandg** [comment]
I'll see if I can track this down and then reopen. 👍
