### ISSUE TITLE
Packaging on Windows - Gstreamer: GstPlayerException: Unable to create a playbin

### ISSUE THREAD

**Issue by schitzN** [kivy/kivy#4652]
Packaging Gstreamer on Windows worked fine few weeks ago. Running the app in PyCharm still works fine. But when i package the app for windows, i can't play videos anymore.

Output when i start .exe: http://pastebin.com/j9wJyaWa

**Comment by schitzN** [comment]
I also tried different versions, like kivy 1.9.1 from pip and all kivy.deps.gstreamer versions from 0.1.15 up to 0.1.17

**Comment by schitzN** [comment]
There are multiple users reporting the same/similar issue since months!

https://groups.google.com/forum/#!topic/kivy-users/3LIlpW2H12M
https://www.reddit.com/r/kivy/comments/4knqy6/gstplayerexception_unable_to_create_a_playbin/

**Comment by matham** [comment]
It could be that you don't have the correct permissions to the location where the playbin is being created. The environment at runtime is controlled by https://github.com/kivy/kivy/blob/master/kivy/tools/packaging/pyinstaller_hooks/pyi_rth_kivy.py. Can you check the values of these environment variables in your app? Please post the values. Also check whether those paths is actually where the gstreamer dlls actually are.

**Comment by schitzN** [comment]
Hey there matham!

**Thank you very much, i was just able to fix this!**

At first i set all permissions i could find to allow everything but this did not work out.

Then i went through the pyi_rth_kivy.py and checked all environ-values. Here is the output:
```
KIVY_DATA_DIR: D:\builds\myapp\win\dist\MY_AP~1\kivy_install\data
KIVY_MODULES_DIR: D:\builds\myapp\win\dist\MY_AP~1\kivy_install\modules
GST_PLUGIN_PATH: D:\builds\myapp\win\dist\MY_AP~1:D:\builds\myapp\win\dist\MY_AP~1\gst-plugins
sys._MEIPASS: D:\builds\myapp\win\dist\MY_AP~1
GST_REGISTRY: D:\builds\myapp\win\dist\MY_AP~1\registry.bin
```

The GST_PLUGIN_PATH looked really weird to me. There is also no gst-plugin folder in my dist folder. All gstreamer files are in the root folder of my packaged app.

So i overwrote the GST_PLUGIN_PATH on my apps startup with sys._MEIPASS:
`os.environ['GST_PLUGIN_PATH'] = sys._MEIPASS`

**Now its working!**

I guess this is indeed some kind of bug?

**Comment by KeyWeeUsr** [comment]
If it's standalone exe, look [here](http://stackoverflow.com/a/36021330). ^^

**Comment by matham** [comment]
The problem seems to be with this commit: https://github.com/pyinstaller/pyinstaller/commit/9ee5482fe6171fca6bbb2816950e18ff3c145531. I believe it should be comma separated, not colon separated on windows. 

Can you please check and instead of overwriting as `os.environ['GST_PLUGIN_PATH'] = sys._MEIPASS` replace the colon, e.g. `os.environ['GST_PLUGIN_PATH'] = D:\builds\myapp\win\dist\MY_AP~1;D:\builds\myapp\win\dist\MY_AP~1\gst-plugins` and see if that fixes it?

**Comment by schitzN** [comment]
Hey there matham, sry for the long delay.

Yes this does indeed fix the issue.

**Comment by blurymind** [comment]
both colon and semicolon is broken for me
