### ISSUE TITLE
Can't install Kivy on Windows 10

### ISSUE THREAD

**Issue by antorix** [kivy/kivy#4654]
Hi. I'm trying to install Kivy on my Windows 10 x64 system according to the Windows installation instructions. I updated pip and wheel, they are OK. But when I type (in the administrator mode):

`python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew`

I get an error:

`Could not find a version that satisfies the requirement kivy.deps.sdl2 (from versions: )
No matching distribution found for kivy.deps.sdl2`

Then, when I type:

`python -m pip install kivy.deps.gstreamer --extra-index-url https://kivy.org/downloads/packages/simple/`

I get another error:

`Could not find a version that satisfies the requirement kivy.deps.gstreamer (from versions: )
No matching distribution found for kivy.deps.gstreamer`

And finally, after 

`python -m pip install kivy`

I get this:

`Failed building wheel for kivy`

And later this:

`Command "C:\Users\antor\AppData\Local\Programs\Python\Python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\admin\\AppData\\Local\\Temp\\pip-build-nnfdts5g\\kivy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\admin\AppData\Local\Temp\pip-w1j9yk83-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-build-nnfdts5g\kivy\`

In the end, I have no kivy installed. What do I do wrong? Sorry if I post in a wrong place, in this case maybe someone will tell me where to ask.

**Comment by Kovak** [comment]
You ignore the warning at top of page I think:

https://kivy.org/docs/installation/installation-windows.html

Kivy do not currently work on windows for python 3.5. You need to use 3.4

**Comment by antorix** [comment]
Oh really? Thanks! But that's a pity indeed.

**Comment by Sn3akyP3t3** [comment]
You can of course try the Nightly wheel installation to get around this until official support is available.

**Comment by chounry** [comment]
i have encounter that,and i then open cmd in admin.
