### ISSUE TITLE
gstreamer link broken

### ISSUE THREAD

**Issue by MichaelCurrie** [kivy/kivy#4658]
The downloads in this folder yield 502 errors https://kivy.org/downloads/packages/simple/

But they are part of the Windows install process: https://kivy.org/docs/installation/installation-windows.html:

`python -m pip install kivy.deps.gstreamer --extra-index-url https://kivy.org/downloads/packages/simple/`

**Comment by KeyWeeUsr** [comment]
Those files are redirecting to `www.googledrive.com`, which pulls out this new thing unfortunately. Not sure if someone is working on it, but you can still download manually the `whl` file and install like that.

Also, a duplicate: #4493
