### ISSUE TITLE
gstreamer fails on OS X

### ISSUE THREAD

**Issue by jayboyd** [kivy/kivy#4664]
I went through a lot of trial and error getting audio to work (at all) on OS X. Since I had multiple failure points, can't post all errors, but seems like problem ultimately was that Gstreamer was failing to load audio files. 

With Kivy.app, was never able to get audio working as I could not figure out how to stop Gstreamer from being the audio provider. (Should os.environ['KIVY_AUDIO'] setting be honored if set before importing kivy? Doesn't work for me.)

With manual install via pip, I was able to resolve my issues by doing brew uninstall gstreamer, which finally allowed SDL2 to be the provider. 

I also had to do 
brew install --with-vorbis --with-smpeg2 sdl2_mixer

This allows me to play OGG and MP3 files on OS X. Building for Android, can only use OGG files, presumably a known issue due to licensing, but worth a mention. 

SInce I had lots of distinct errors, including a few here: 

When trying to play OGG or MP3 using "default" setup, which always loads gstreamer if present, loading files works okay, but Sound.play() generates this:

*\* (<unknown>:48978): WARNING **: Invalid channel positions
[ERROR  ] [AudioGstplayer] Internal data flow error.
[ERROR  ] [AudioGstplayer] The stream is in the wrong format.

Trying to load WAV files (including ones copied from kivy examples dir), I get tons of these errors:

(<unknown>:48978): GStreamer-WARNING **: Failed to load plugin '/Applications/Kivy2.app/Contents/Resources/../Frameworks/GStreamer.framework/Versions/Current/lib/gstreamer-1.0/libgstlibav.so': dlopen(/Applications/Kivy2.app/Contents/Resources/../Frameworks/GStreamer.framework/Versions/Current/lib/gstreamer-1.0/libgstlibav.so, 2): Library not loaded: libbz2.1.0.dylib
  Referenced from: /Applications/Kivy2.app/Contents/Frameworks/GStreamer.framework/Versions/1.0/lib/gstreamer-1.0/libgstlibav.so
  Reason: image not found

Last point, unrelated probably, but no matter which audio provider I use, I see this popping up in logs:

2016-10-09 09:31:41.620 Python[46001:4097154] 09:31:41.620 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

I'm using OS X 10.11.6, have run both Python 2.7.12 (system install) and Python 2.7.10 (Kivy.app) with pretty much same results, and have installed Kivy.app (1.9.1dev0) and from zip file. Manual building of zip file failed and I gave up on that route. pip install kivy also. All versions of Kivy seem to have similar problem, only solution working for me was to get rid of gstreamer, which so far rules out Kivy.app as I don't know how to do that in that case.

**Comment by rschenck** [comment]
+1 on this

Same Specs

**Comment by schitzN** [comment]
hey there jayboyd!

I also went through lots of trial and error but currently i have an application i can build on windows and ios. I don't know for sure, but as far as i know, gst does not work on ios.

My application is using ffpyplayer for audio and video on ios and its working very well (as soon as everything was up and running). Open you xcode-project and go to sources/main.m and look at the putenv variables for audio and video. Mine are the following and are working:

`
putenv("KIVY_WINDOW=sdl2");
putenv("KIVY_IMAGE=imagio,tex");
putenv("KIVY_AUDIO=ffpyplayer");
putenv("KIVY_VIDEO=ffpyplayer");
`

**Comment by dessant** [comment]
The reinstalling with homebrew and pip, there may also be additional steps to follow to make gsreamer work, depending on your setup, links below.
https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip
https://kivy.org/docs/guide/packaging-osx.html#gstreamer

If you can still reproduce the bug after reinstalling, please open an issue with a step by step guide for reproducing it.

**Comment by AllieCarver** [comment]
The important line in those error logs is "** (:48978): WARNING **: Invalid channel positions", Kivy.app bundled version of **gstreamer won't play play mono sound files**.  This took me longer to discern than I care to publicly admit.  Found this thread, with a woefully un-descriptive title, after the fact - https://groups.google.com/forum/#!topic/kivy-users/bSHhYWR1TEs.  

For clarification, are you saying that a pip install does not have this issue?

**Comment by FeralBytes** [comment]
@AllieCarver he is not saying that, but he is asking. So can you tell us, does it work with the pip method on OSX, I use Linux so I would not know.

**Comment by AllieCarver** [comment]
Had the chance to try, reinstalling using homebrew and pip does solve this issue.

**Comment by FeralBytes** [comment]
@AllieCarver good to hear, thanks for following up!
