### ISSUE TITLE
RecycleView should not use a global cache

### ISSUE THREAD

**Issue by ngoonee** [kivy/kivy#4666]
I'm getting weird errors in my application because I use many recycleviews with similar data structures (dict names etc match), and sometimes a 'wrong' cached view is picked up.

Problem happens within the same view, but is especially jarring when two different views start interfering with each other.

I'd like the cache to be owned by each instance of recycleview (is there really much need for multiple instances to access the same cache?), at least optionally. As for the picking up of 'wrong' views (yes I've checked to make sure dict values don't overlap) I'll just have to do more debugging, hard to identify the root cause.

**Comment by matham** [comment]
I guess there's no real reason to make it global. That may also fix your view mixup.

**Comment by ngoonee** [comment]
Unfortunately I do get view mixups even with only one recycleview, so I doubt it would fix it totally (may get better). Still investigating that, really.

**Comment by ngoonee** [comment]
@matham are you the point person for Recycleview? Am imagining some changes which could be useful for my own project, and would like to run them by someone who can comment on whether its worth the effort to modify Recycleview itself rather than just subclassing for my own use (which I've already started doing). Especially in terms of roadmap for how recycleview will look like, feature set, etc.

**Comment by matham** [comment]
See https://github.com/kivy/kivy/issues/5913.
