### ISSUE TITLE
Old version when install with Python PIP

### ISSUE THREAD

**Issue by oxidworks** [kivy/kivy#4673]
Hello, I found an error and tried to fix it. I cloned from GitHub but error was fixed 4 month ago.
Would be very nice to get an update with pip.

Thank you very much.

**Comment by KeyWeeUsr** [comment]
ref #4671

**Comment by oxidworks** [comment]
Hi, thank you for reply. But cannot found any duplication. Other report is different issue and was closed before.

**Comment by KeyWeeUsr** [comment]
> The warning is already fixed on GitHub but with pip you get an old version.

This is a part of the last comment on that issue. I presume you are talking about the same version/pip install in this issue and about the same edit you've done in the previous issue.

> I found an error and tried to fix it...

If I'm wrong and this issue has nothing to do with issue4671, then this one has no details at all, so you'll need to provide more details.

**Comment by oxidworks** [comment]
Hi. The other issue was about error messages and I found out how to fix it. So I wrote how to fix and closed the other issue.
Later I, when I tried to fix the problem on GitHub, I saw that pip offers an old version. So I opened an issue about that.
Should I reopen the other issue? Maybe change the title? I don't think this is a good approach but if you want it I will do so.
Regards

**Comment by KeyWeeUsr** [comment]
A lot of stuff is fixed on GitHub and isn't included in PyPi wheel. On PyPi there's a stable version `1.9.1` and here is `1.9.2`, which includes the latest changes in the code and is used in development of the framework. The latest version isn't yet tested the way the `1.9.1` version was, which means the framework may seem unstable in some parts.

To get the latest version (with fixed stuff, maybe bugs or so) there's a [manual](https://kivy.org/docs/installation/installation-linux.html) for that.

**Comment by oxidworks** [comment]
Ok. Thank you fore your info. I just saw that stable version is also 1.9.1. So pip is not that old :)
So I use now the daily PPA.
