### ISSUE TITLE
scroll_to() behaviour

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#4674]
Hi all,

I'm using the scroll_to function in my kv-file. It scrolls properly as I wanted, but if I turn the mouse-wheel it will jump back where it was, before the scroll_to().

Any ideas, how could I improve my code?

snipplet of my kv-file:

MyButton:
    text: 'jump'
    on_release: scroll_content.scroll_to(jump_id_2, padding=0, animate=True)

ScrollView:
    id: scroll_content
    blah, blah, blah.......

    # values of the devices
    GridLayout:

        BoxLayout:
            id: jump_id_0
            blah, blah, blah.......

        BoxLayout:
            id: jump_id_1
            blah, blah, blah.......

        BoxLayout:
            id: jump_id_2
            blah, blah, blah.......

Thank you for your help....

**Comment by schitzN** [comment]
maybe related to #1078 ?
there is also a working fix mentioned there!

**Comment by picibucor** [comment]
Yes, it is related.

I just installed the latest Nightly wheel...  but the issue is still there.
