### ISSUE TITLE
Filechooser erratic behavior when doubleclick on folder (fantom extra doubleclick)

### ISSUE THREAD

**Issue by fedes82** [kivy/kivy#4676]
When doubleclicking on folder, it enters that folder and then immediately goes back to the previous one. Sometimes it enters some subfolder. The dirselect property is set to True and it happens with filechooser's list and icon view. This issue ocurr in three different PCs, two with Linux Mint 17 (laptops, using touchpad) , the other one have Kubuntu 16.4 (using usb mouse) and with kivi 1.9.1 in all of them. No error messages or warnings. The issue also happens in the kivy catalog example program.
It seem as it reads the doubleclick and then it apply some phantom doubleclick to whatever is under the pointer. So if I doubleclick on the first folder of the list, when enters that folder the cursos is over the '/..' item, so its goes back to the previous folder. If I doubleclick over, for example, the third item of the list, it enters that folder, but if there is three subfolders, and one of those is under the mouse pointer, that subfolder gets opened.

**Comment by picibucor** [comment]
Fliechooser uses simple click to choose a folder. Your second click opened the folder, or clicked on /..

**Comment by overfl0** [comment]
@picibucor  It uses a double click if you set dirselect=True.

@fedes82 I think you're talking of #3708. Apply the patch posted there and everything should work for you. Sadly, there has been no kivy releases for almost a year and all the bugs that have been fixed since then remain unfixed for anyone that is not willing to either compile kivy himself or patch his installation :(

**Comment by fedes82** [comment]
Ok, I will do that. Thank you. 
Could you please point me where can i find instructions on how to apply the patch? I installed kivy through their ubuntu repository. Thanks again

**Comment by overfl0** [comment]
Just find where kivy is installed on your computer, open kivy/uix/filechooser.py and modify it.

In theory, you could append ".patch" to the url of the github patch in that bug, giving you:
https://github.com/ngoonee/kivy/commit/e75575c2a58a71e9481628045111ddad94ed19e8.patch
...and then pipe the contents to `patch -p 1` (starting with the `diff --git a/kivy/...` line), but the patch is so small that it's easier to just do it by hand :)

**Comment by overfl0** [comment]
Actually, instead of patching anything, just take the whole file and wget it along with all the other patched bugs you don't know about, yet.
https://raw.githubusercontent.com/kivy/kivy/master/kivy/uix/filechooser.py

**Comment by fedes82** [comment]
I will as soon I get home. Thanks again.

**Comment by matham** [comment]
You can find how to get the latest kivy at https://kivy.org/docs/installation/installation-linux.html. Just use the kivy nightly builds as they are recent master snapshots. Replacing a single file is not recommended as it could be out of sync with the rest of the files and break.

**Comment by fedes82** [comment]
I have installed the nightly build and is working now. Thank again. Should I close this issue?
