### ISSUE TITLE
Trying to make sense of inverted Y input

### ISSUE THREAD

**Issue by zmandt** [kivy/kivy#4677]
Hey all, very new to this here.  I'm trying to get kivy working fully using an [adafruit 5" touchscreen](https://www.adafruit.com/products/2260) Everything seems to be working and displaying properly for the most part, except I can't seem to figure out how to fix the y axis being inverted when using the touchscreen, and the odd error about not enough space to display all children.  Any help is appreciated, here's the log:

`[INFO   ] Logger: Record log in /home/pi/.kivy/logs/kivy_16-10-18_7.txt
[INFO   ] Kivy: v1.9.2-dev0
[INFO   ] Python: v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] Factory: 193 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Window: Provider: egl_rpi
[INFO   ] GL: OpenGL version <OpenGL ES 2.0>
[INFO   ] GL: OpenGL vendor <Broadcom>
[INFO   ] GL: OpenGL renderer <VideoCore IV HW>
[INFO   ] GL: OpenGL parsed version: 2, 0
[INFO   ] GL: Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] GL: Texture max size <2048>
[INFO   ] GL: Texture max units <8>
[INFO   ] Shader: fragment shader: <Compiled>
[INFO   ] Shader: vertex shader: <Compiled>
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] Clipboard: Provider: gtk3(['clipboard_dbusklipper'] ignored)
[INFO   ] Cutbuffer: Provider: xclip
[INFO   ] CutBuffer: cut buffer support enabled
[INFO   ] GL: NPOT texture support is available
[INFO   ] OSC: using <multiprocessing> for socket
[INFO   ] ProbeSysfs: device match: /dev/input/event0
[INFO   ] MTD: Read event from </dev/input/event0>
[INFO   ] ProbeSysfs: device match: /dev/input/event1
[INFO   ] MTD: Read event from </dev/input/event1>
[INFO   ] ProbeSysfs: device match: /dev/input/event2
[INFO   ] MTD: Read event from </dev/input/event2>
[INFO   ] ProbeSysfs: device match: /dev/input/event0
[INFO   ] HIDInput: Read event from </dev/input/event0>
[INFO   ] ProbeSysfs: device match: /dev/input/event1
[INFO   ] HIDInput: Read event from </dev/input/event1>
[INFO   ] ProbeSysfs: device match: /dev/input/event2
[INFO   ] HIDInput: Read event from </dev/input/event2>
[INFO   ] Base: Start application main loop
[INFO   ] MTD: </dev/input/event0> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event0> range position Y is 0 - 0
[INFO   ] MTD: </dev/input/event1> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event0> range touch major is 0 - 0
[INFO   ] MTD: </dev/input/event1> range position Y is 0 - 0
[INFO   ] MTD: </dev/input/event0> range touch minor is 0 - 0
[INFO   ] MTD: </dev/input/event2> range position X is 0 - 4095
[INFO   ] MTD: </dev/input/event1> range touch major is 0 - 0
[INFO   ] MTD: </dev/input/event0> range pressure is 0 - 255
[INFO   ] MTD: </dev/input/event2> range position Y is 0 - 4095
[INFO   ] HIDMotionEvent: using <  Mini Keyboard>
[INFO   ] MTD: </dev/input/event1> range touch minor is 0 - 0
[INFO   ] MTD: </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] MTD: </dev/input/event2> range touch major is 0 - 0
[INFO   ] HIDMotionEvent: using <  Mini Keyboard>
[INFO   ] MTD: </dev/input/event1> range pressure is 0 - 255
[INFO   ] MTD: </dev/input/event0> rotation set to 0
[INFO   ] MTD: </dev/input/event2> range touch minor is 0 - 0
[INFO   ] MTD: </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO   ] MTD: </dev/input/event2> range pressure is 0 - 255
[INFO   ] MTD: </dev/input/event1> rotation set to 0
[INFO   ] HIDMotionEvent: using <Microchip Technology Inc. AR1100 HID-MOUSE>
[INFO   ] MTD: </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO   ] HIDMotionEvent: <Microchip Technology Inc. AR1100 HID-MOUSE> range ABS X position is 0 - 4095
[INFO   ] MTD: </dev/input/event2> rotation set to 0
[INFO   ] HIDMotionEvent: <Microchip Technology Inc. AR1100 HID-MOUSE> range ABS Y position is 0 - 4095
[WARNING] Accordion: not enough space for displaying all children
[WARNING] Accordion: need 132px, got 84px
[WARNING] Accordion: layout aborted.
[WARNING] Accordion: not enough space for displaying all children
[WARNING] Accordion: need 132px, got 84px
[WARNING] Accordion: layout aborted.

`

**Comment by tshirtman** [comment]
you can configure kivy to invert any input using the postproc calibration module. 

https://kivy.org/docs/api-kivy.input.postproc.calibration.html

I don't think this is a bug, only a configuration issue, but please reoppen if you disagree.

**Comment by zmandt** [comment]
Yeah I must be missing something, I can't seem to get it to work.
