### ISSUE TITLE
Raspberry pi touchring (mouse pointer) can move endless behind screen boarders

### ISSUE THREAD

**Issue by wolkstein** [kivy/kivy#4680]
hi,
i will control my kivy application with an normal mouse. no touch screen. if i develop on my desktop the mouse pointer change from touchring to normal mouse pointer if i cross the kivy application window boarder. on an raspberry pi the application is fullscreen against .kivy/config.ini settings witch are default on "fullscreen = 0". this is not the problem because the app must run in fullscreen mode on raspberry pi. the problem is the touchring. on raspberry pi you can move the mouse(touchring) endless behind the screen boarder. in this case, if you not remember in which direction you loose the mouse pointer behind the boarder you have no chance to get the pionter back to visible screen area.

what goes wrong here? or how can i configure config.ini that this will not happens?

thx
wolke

**Comment by iconnectviacalculator** [comment]
Hello,
I've got the same issue. Currently working on it but no couldn't figure it out yet. Did you find a solution?
Thanks.

**Comment by wolfmanjm** [comment]
I think this is an issue with hidinput, and can be fixed by limiting the rel mouse moves to stay within the screen limits. I'll try to add it to my rework of hidinput. PR #6264

**Comment by Julian-O** [comment]
This looks like it was fixed.

Closing.

If the problem still occurs, please let us know.
