### ISSUE TITLE
Smoothline - Memory Leak

### ISSUE THREAD

**Issue by schitzN** [kivy/kivy#4683]
I'm frequently updating the points of a line to animate it (using kivy's clock). I have no problems when using the default line but when i use a smoothline instead, the used memory is slowly but steadily increasing. There is some kind of memory leak in the smoothline implementation, whenever the points-list gets changed. Would like to use smoothline because it looks much nicer.

**Comment by tshirtman** [comment]
uh, that does seem likely indeed…

https://github.com/kivy/kivy/blob/a2fca89bf67291aef11b1d5f88a6ad8fd52e08d3/kivy/graphics/vertex_instructions_line.pxi#L1484-L1485 (current master)
```
        #free(vertices)
        #free(indices)
```
