### ISSUE TITLE
Feature: on_hover  if ActionButton

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#4690]
I would like to have an on_hover behaviour by ActionButtons. 
It is useful if you are developing for desktop: you could describe the meaning of an icon better.

**Comment by KeyWeeUsr** [comment]
ref #3471 as it's been said, it's most likely to be inefficient

**Comment by kiok46** [comment]
@picibucor  I did this implementation for kivy-designer (might help you) https://github.com/kivy/kivy-designer/pull/172/files
