### ISSUE TITLE
Question about ScreenManager

### ISSUE THREAD

**Issue by kdheepak** [kivy/kivy#4692]
This is the example from the [docs](https://kivy.org/docs/api-kivy.uix.screenmanager.html).

```
from kivy.uix.screenmanager import ScreenManager, Screen

# Create the manager
sm = ScreenManager()

# Add few screens
for i in range(4):
    screen = Screen(name='Title %d' % i)
    sm.add_widget(screen)

# By default, the first screen added into the ScreenManager will be
# displayed. You can then change to another screen.

# Let's display the screen named 'Title 2'
# A transition will automatically be used.
sm.current = 'Title 2'
```

Every example out there creates an instance of the `ScreenManager` and every `Screen` as a module level object. Is there any disadvantage to doing this inside the App? I would like to dynamically create and remove screens, based on user input. Any thoughts and suggestions?

**Comment by KeyWeeUsr** [comment]
`sm = ScreenManager()` means create an instance and hold it in variable `sm` and the same applies for screens. Other lines below `… = …()` are working directly with the created instances.

You can do it wherever you can then fetch the instance of a child and put it somewhere as a child - to another widget or Window.

Also, GitHub is for issues of the framework, use irc, maillist or StackOverflow for such questions. :)

**Comment by kdheepak** [comment]
Thanks! That helps! And sorry about that! I will post to IRC or StackOverflow next time.
