### ISSUE TITLE
Port compile Kivy to ARM Cortex-A9 Freescale i.MX

### ISSUE THREAD

**Issue by cleitonbueno** [kivy/kivy#4693]
Hello,
I am carrying the Kivy for processor ARM Cortex-A9 -> NXP/Freescale i.MX6 -> Toradex board.

Follow the discussion on another list:
https://groups.google.com/forum/#!topic/kivy-users/3OSUcXqm9II

Installing dependencies for Kivy -> OK
Cross-compiling Kivy ->
Tests Kivy -> Python -> import Kivy and import kivy.app -> OK
Running examples as canvas_stress.py, scale.py, videoplayer.py -> ERROR

ERROR:
# python /usr/share/kivy-examples/widgets/videoplayer.py

[INFO              ] [Logger      ] Record log in /home/root/.kivy/logs/kivy_16-05-31_6.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (default, May 21 2016, 16:26:47) 
[GCC 5.3.0]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [VideoGstplayer] Using Gstreamer 1.6.3.0
[INFO              ] [Video       ] Provider: gstplayer
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2
[  912.983335] mxc_sdc_fb fb.18: 640x480 h_sync,r,l: 64,16,80  v_sync,l,u: 4,13,3 pixclock=23750000 Hz
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
sdl2 - RuntimeError: Could not initialize OpenGL / GLES library
  File "/usr/lib/python2.7/site-packages/kivy/core/**init**.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 138, in **init**
    super(WindowSDL, self).**init**()
  File "/usr/lib/python2.7/site-packages/kivy/core/window/**init**.py", line 722, in **init**
    self.create_window()
  File "/usr/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 237, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 133, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:2284)
  File "kivy/core/window/_window_sdl2.pyx", line 55, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (kivy/core/window/_window_s[  913.094420] mxc_sdc_fb fb.18: 640x480 h_sync,r,l: 64,16,80  v_sync,l,u: 4,13,3 pixclock=23750000 Hz
dl2.c:1479)

[CRITICAL          ] [App         ] Unable to get a Window, abort.

Any suggestion?

**Comment by rnixx** [comment]
I'm no expert in this, but raspberry pi uses EGL window provider https://github.com/kivy/kivy/blob/master/kivy/core/window/window_egl_rpi.py. Maybe you should try to use this one?

**Comment by tito** [comment]
Don't open an issue with all the platform we don't support.
Best is to open a PR with the addition of the new platform !

Freescale is not supported (i don't even own a board like that). Unless somebody look to implement a window provider for it, it wont work.

**Comment by cleitonbueno** [comment]
Many thanks for the reply.

I have great interest in porting Kivy to i.MX6 that is used in several products with GUI, I noticed the SDL2 has support GPU VIVANTE (NXP / Freescale i.MX6), so I thought to be something I was doing error .

I will open the PR soon.

Thank you.

**Comment by parthitce** [comment]
@cleitonbueno Sorry to write on the closed thread. Do you have success or update for Kivy in i.Mx?

**Comment by cleitonbueno** [comment]
> @cleitonbueno Sorry to write on the closed thread. Do you have success or update for Kivy in i.Mx?

Hello! As I did not find anyone else interested, I ended up not advancing, if you are still interested in performing the port I'm interest.
