### ISSUE TITLE
OpenCV Camera initialization error (kivy 1.9.1+)

### ISSUE THREAD

**Issue by keigezellig** [kivy/kivy#4697]
When using the OpenCV camera provider it gives the following error when starting up:
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO              ] [Cutbuffer   ] Provider: xclip
[INFO              ] [CutBuffer   ] cut buffer support enabled
[CRITICAL          ] [Camera      ] Unable to find any valuable Camera provider at all!
pygst - ImportError: No module named 'pygst'
  File "/usr/lib/python3/dist-packages/kivy/core/**init**.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/camera/camera_pygst.py", line 15, in <module>
    import pygst

**opencv - ImportError: No module named 'cv'
  File "/usr/lib/python3/dist-packages/kivy/core/**init**.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/camera/camera_opencv.py", line 20, in <module>
    import cv**

I am using Python 3.4, OpenCV 3.1.0 and verified that OpenCV from the Python interpreter works. However i notice that the import needed is `import cv2` instead of `import cv`

**Comment by udiboy1209** [comment]
There is this breaking change in OpenCV 3 where they have removed `cv.py` entirely ([ref](http://stackoverflow.com/questions/32048313/cannot-import-cv-on-opencv2)). So functions in `camera_opencv.py` need to be updated to work with OpenCV3. I suggest you use some other camera provider for the meanwhile.

**Comment by keigezellig** [comment]
Well that's really unfortunate, since the other provider (pygst) doesn't
work either (at least with python 3 it is)
I get this error (i installed the python3-gst, python-gst and
python-gst-dev packages)

pygst - ImportError: No module named 'pygst'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in
core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/camera/camera_pygst.py",
line 15, in <module>
    import pygst


I checked this import statement also in a regular python shell and it seems
that it works in Python 2.7.x but not in 3.4.x.

Are there any other camera providers supported that work with Python 3

**Comment by keigezellig** [comment]
To come back to my previous post, i found out in the kivy documentation that there IS a gstreamer camera module for Python 3 with Gi/Gst but to enable it I had to do uncomment a line in the Kivy code itself (see [here](https://groups.google.com/forum/#!topic/kivy-users/c4SqqsA6PFs). Then my Kivy app started up normally. Isn't there a better way to enable this?

**Comment by openedhardware** [comment]
Hi, @udiboy1209 
I am using Python3.5 + Ubuntu 16.04
At first, I tried to use Kivy 1.9.1, but failed.

I tried to download the latest version and installed it(1.9.2-dev) and found that `gst` & `gi` providers are removed.

Which provider should I use?
Or should I returned to 1.9.1 and follow @keigezellig ?

**Comment by dessant** [comment]
Should be fixed in https://github.com/kivy/kivy/pull/5011.
