### ISSUE TITLE
Feature: Multiple Windows

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#4701]
Thank you for constantly improving Kivy. I really like it.

I am using kivy to develop a software for Windows desktop computers.
And I would like to open a filebrowser(from kivy-garden) in separate window.

But I found the following sentence in the manual:
"Kivy supports only one window per application: please don't try to create more than one."

Is there any way to have a filebrowser in a separate window?

Thank you for working on Kivy.

**Comment by inclement** [comment]
It's possible to do this, but only by running a second instance of kivy in a separate process (this can be started from the first one, but it's still some effort). Unfortunately it's unlikely we'll target multiple windows any time, although I don't think it's technically impossible. You can find some discussion on this at the recently closed issue https://github.com/kivy/kivy/issues/4442
