### ISSUE TITLE
sed: 1: "Modules/Setup.local": invalid command code M

### ISSUE THREAD

**Issue by frankgould** [kivy/kivy#4703]
I have been trying all kinds of ways to resolve this buildozer crash that fails to create the toolchain. I cannot find how to fix this problem online and tried to resolve it by looking at the attached Setup.local (txt) file that I believe is referenced in the STDOUT error listed below. I don't see where the invalid command code M materializes. I also specifically installed OpenSSL based on another forum suggestions. Buildozer is on a macOSX 10.11.6. Any suggestions are greatly appreciated. This request is related to https://groups.google.com/forum/#!topic/kivy-users/p1jKDtuyYXs and https://groups.google.com/forum/#!topic/kivy-users/p1OeBgegugA.

[Setup.local.txt](https://github.com/kivy/kivy/files/567453/Setup.local.txt)

RAN: '/usr/bin/sed -i s#^SSL=.*#SSL=/Users/fgould/ViewPix/Slideshow/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a/openssl# Modules/Setup.local'

  STDOUT:
sed: 1: "Modules/Setup.local": invalid command code M

  STDERR:
# Command failed: python -m pythonforandroid.toolchain create

**Comment by KeyWeeUsr** [comment]
I think this should be reported in p4a repository as buildozer works with that under the hood. Not sure what's wrong though. Try fresh install or master branch or p4a.

**Comment by frankgould** [comment]
Thanks for the suggestion KeyWeeUsr. I tried deleting .buildozer from my app directory and it reloaded everything but ended up with the same results. Are you suggesting I do something different? I'm not sure what "fresh install or master branch or p4a" means exactly.

**Comment by KeyWeeUsr** [comment]
Well, you've kind of done the fresh install already when you deleted `.buildozer`, but I meant removing it completely and installing from pip again, even trying the master branch (`pip install https://github.com/kivy/buildozer/zipball/master`) or using directly the python-for-android toolchain (stable or master).
