### ISSUE TITLE
Problem getting camera widget's texture

### ISSUE THREAD

**Issue by Rodrigo-P** [kivy/kivy#4704]
I'm trying to get the camera feed and do some transformations on it by using the kivy camera module and fetching its texture:

```
from kivy.app import App
from kivy.uix.image import Image
from kivy.uix.camera import Camera
from kivy.graphics.texture import Texture
import cv2
from kivy.uix.widget import Widget
from kivy.clock import Clock
import numpy as np

class Img(Image):
    def update(self, frame):
        self.texture = frame
class Capture(Widget):
    def __init__(self, **kwargs):   
        super(Capture, self).__init__(**kwargs)
        cam = Camera()
        cam = Camera(resolution=(640,480), size=(640,480))
        cam.play = True
        display = Img()
        self.add_widget(display)
        self.add_widget(cam)
        self.cam.opacity = 0 
    def update(self,time):
        if self.cam.texture is None:
            print 'No Feed!'
        else:
            self.display.update(self.cam.texture)
class TestApp(App):
    def build(self):
        game = Capture()
        Clock.schedule_interval(game.update, 1.0 / 60.0)
        return game

 
if __name__ == '__main__':
    TestApp().run()
```
Right now the camera feed is displayed on screen but the texture is None. How can I get the feed texture? And is there a better way of getting the camera feed, do transformations and display it wich would work on android?

**Comment by kneufeld** [comment]
To answer your question you need to bind to Camera.on_texture.

In my case I'm doing it like this.

    class MyCamera(Camera):
        def on_texture(self, var, value):
            pass # do your thing

The reason I'm here is that my `on_texture` method is only being called once. On the first texture not on each frame like the docs would suggest.

**Comment by kneufeld** [comment]
Hmm... it seems like the texture object is actually the "movie" not a frame. Dammit, how do you process each frame?

**Comment by oliverbrace** [comment]
I have the same issue. Would really like to know if a solution was ever found.
Thanks
