### ISSUE TITLE
Installing gstreamer doesn't work

### ISSUE THREAD

**Issue by dassie** [kivy/kivy#4705]
This is what I see when I attempt to install:
```
david@DAVENG-PC2 - C:\Users\david\dev
λ python -m pip install kivy.deps.gstreamer --extra-index-url https://kivy.org/downloads/packages/simple/
Collecting kivy.deps.gstreamer
  Could not find a version that satisfies the requirement kivy.deps.gstreamer (from versions: )
No matching distribution found for kivy.deps.gstreamer
```
sdl2 and glew installed just fine, I'm not sure what could be causing gstreamer to fail.

Relevant details about my environment:
* Python 3.4.3 64-bit
* Windows 10

**Comment by KeyWeeUsr** [comment]
Temporarily download it from [here](https://drive.google.com/drive/folders/0B1_HB9J8mZepNzZ5aW91Q0tJU2s) and install manually. I should work soon :)

**Comment by dassie** [comment]
Is 'kivy.deps.gstreamer-0.1.7-cp34-cp34m-win_amd64.whl' the one I want to use? I get a different error when trying to install that directly:

```
david@DAVENG-PC2 - C:\Users\david
λ python -m pip install "C:\Users\david\dev\kivy.deps.gstreamer-0.1.7-cp34-cp34m-win_amd64.whl"
kivy.deps.gstreamer-0.1.7-cp34-cp34m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by KeyWeeUsr** [comment]
Is your python an official version or you compiled from source? Also try to change `cp34m` to `none`.

**Comment by dessant** [comment]
This issue should be fixed, please try with installing again with the original commands.

**Comment by dassie** [comment]
@KeyWeeUsr There was no 'none' file for 0.1.7 but I tried 0.1.6 and got the same error:
```
david@DAVENG-PC2 - C:\Users\david
λ python -m pip install "C:\Users\david\dev\kivy.deps.gstreamer-0.1.6-cp34-none-win_amd64.whl"
kivy.deps.gstreamer-0.1.6-cp34-none-win_amd64.whl is not a supported wheel on this platform.
```

@dessant Tried the original command again, same result. :(

**Comment by dassie** [comment]
@KeyWeeUsr Also, yes, this is an official installation.

**Comment by KeyWeeUsr** [comment]
You might need to upgrade pip if it's a fresh installation of python or if pip is just too old:

    python -m pip install --upgrade pip

If that doesn't work, I have no idea what then.

**Comment by dessant** [comment]
I'm getting the same error with py3.4 32bit.

**Comment by KeyWeeUsr** [comment]
Same for py2.7 32bit

**Comment by dessant** [comment]
@matham, thoughts?

**Comment by KeyWeeUsr** [comment]
Works through Drive though, so as I suggested, the redirect might be an issue (too) 😋

**Comment by dessant** [comment]
That part is fixed, they are hosted on the server.
https://kivy.org/downloads/packages/simple/kivy.deps.gstreamer/

**Comment by dassie** [comment]
Apologies, looks like I had a user account environment PATH set for python 2.7 32-bit and a system environment path set for python 3.4 64-bit. The 2.7 was overriding the 3.4 hence the "not supported on this platform" message. The original link works as well.

Sorry again for the confusion. This can be closed.
