### ISSUE TITLE
fullscreen=0 doesn't work

### ISSUE THREAD

**Issue by jwillyfg** [kivy/kivy#4706]
hi!

i've been working on an raspberry 3 and i'd like to avoid get a full screen window for my app, but it always runs on fullscreen although i modified the config.ini file.

Does someone know where the problem is? 

Thanks 
[config.txt](https://github.com/kivy/kivy/files/570670/config.txt)

**Comment by Zen-CODE** [comment]
Which OS are you using?
What is the resolution of your screen? 
Have you tried removing 'display = -1'? That is not a documented value...
And tried removing 'position = auto', or changing to 'position = custom'?
And tried changing the height and width?
And which version of kivy are you using?

That being said, it probably is an issue. https://github.com/kivy/kivy/issues/4660

**Comment by jwillyfg** [comment]
I'm working on Raspbian.. I've been reading about this issue and i found that the problem is the window provider, raspbian works with egl_rpi and some values don't work with this provider. I attempted to use sdl2 instead egl_rpi but when i run the code it crashes.

**Comment by KeyWeeUsr** [comment]
@jwillyfg crashes how? What's the error? Paste the log.

**Comment by jwillyfg** [comment]
i post an example code where i'm attempting to change window provider. this code never creates a window and the log file looks kind of incomplete.
[kivy_16-11-11_2.txt](https://github.com/kivy/kivy/files/586973/kivy_16-11-11_2.txt)
[test.txt](https://github.com/kivy/kivy/files/586974/test.txt)

**Comment by Zen-CODE** [comment]
Hmm. Looking at 'core_/__init__.py' (line 63), that suggests it can successfully import the sdl2 window provider. Try adjusting you log level so it logs everything.

ps. It really looks like 'window_egl_rpi' is meant to be used for the pi. We may well be barking up the wrong tree. Have you tried this? http://kivypie.mitako.eu/kivy-download.html

**Comment by jwillyfg** [comment]
yeah! i've tried with kivypie and it works as the same manner. I'm thinking of sdl2 window provider can't work on raspberry pi.

**Comment by dessant** [comment]
fullscreen=0 is not supported in egl_rpi, but sdl2 should work. If you're having isssues with sdl2, please open a new issue with a way to reproduce the bug.

**Comment by matham** [comment]
both sdl2 and x11 window providers work on the pi. I just tested it on rpi3. Just make sure to use master, and compile with `USE_SDL2=1` and `USE_X11=1` and run it with `KIVY_WINDOW=sdl2` or `KIVY_WINDOW=x11`. You should also try the experimental driver if you can (VC4) as otherwise it'll be  a lot slower. egl though was always the fastest in my tests.
