### ISSUE TITLE
Can't able to run kivy 1.9.2 code on Windows 7 

### ISSUE THREAD

**Issue by bhaveshAn** [kivy/kivy#4713]
It gives a fatal error which tells OpenGL 2.0 have to be supportive.
Please tell the kivy version which supports OpenGL 1.5

**Comment by tshirtman** [comment]
No version of kivy supports windows 1.5, you need to update your driver, or get a more recent PC if it doesn't support it, but i doubt a pc that can run windows 7 doesn't support an opengl version from nearly 10 years ago…
