### ISSUE TITLE
Kivy app crash when I try to copy/paste any text

### ISSUE THREAD

**Issue by Fogapod** [kivy/kivy#4719]
[android] (6.0.1  tablet)
Problem: app freezes for unlimited time when I markup and try to copy/paste any text
from/into text fields. (default kivy `Bubble` is used)
This happens in all my compiled with buildozer apps, while testing code using Kivy Launcher
from GP and even in Kivy Showcase app from GP

**Comment by Zen-CODE** [comment]
Does anything appear in the error logs?

**Comment by saqib1707** [comment]
This is the traceback of the error happening when one is trying to copy text from one field to another and app getting freezed after that. But  I am not able to find this file jnius/jnius_export_class.pxi

`11-25 16:31:13.479 12089 12089 I python  :  Traceback (most recent call last):
11-25 16:31:13.480 12089 12089 I python  :    File "/home/saqib1707/kivy/myapp/bubble_testing/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/android/runnable.py", line 34, in run
11-25 16:31:13.480 12089 12089 I python  :    File "/home/saqib1707/kivy/myapp/bubble_testing/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_android.py", line 44, in _initialize_clipboard
11-25 16:31:13.481 12089 12089 I python  :    File "**jnius/jnius_export_class.pxi**", line 900, in jnius.jnius.JavaMultipleMethod.__call__ (jnius/jnius.c:27749)
11-25 16:31:13.482 12089 12089 I python  :  **JavaException: No methods matching your arguments**`

**Comment by akshayaurora** [comment]
This is using the new toolchain ?

**Comment by Zen-CODE** [comment]
Also, could you perhaps give and exact example of markup you are pasting in? Does it work with plain text? This is confusing as the TextInput does not support markup? Example code would be 1st prize :-)

**Comment by akshayaurora** [comment]
@Zen-CODE I think in this context `markup` == `select`

**Comment by saqib1707** [comment]
@akshayaurora No, this is the **adb logcat**  error happening on the android when one tries to copy/paste text from/to a textinput box.

**Comment by akshayaurora** [comment]
@saqib1707 how did you build your apk ? using the new toolchain or the older one?

**Comment by saqib1707** [comment]
I guess the older one.since I haven't used much of the new toolchain. But what's the difference if I build my apk using new or old since its just an app apk file which should be the same I guess.

**Comment by udiboy1209** [comment]
@saqib1707 I think what @akshayaurora is asking is did you build using the command `buildozer android` or `buildozer android_new`. If you used android_new, its the new toolchain and hence it will compile the apk differently.

**Comment by saqib1707** [comment]
@akshayaurora Earlier I build my apk using old toolchain where this error was happening.But with the new toolchain its completely fine.

**Comment by akshayaurora** [comment]
closing this as all development has moved onto new toolchain.
