### ISSUE TITLE
on_request close

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#4723]
Please help me out.

my code is below. Before exit, I want to be sure, my user wants to do so. It does not work, and I don't know why.

> from kivy.app import App
> from kivy.uix.label import Label
> from kivy.uix.boxlayout import BoxLayout
> from kivy.uix.button import Button
> from kivy.uix.popup import Popup
> from kivy.config import Config, ConfigParser
> from kivy.core.window import Window, WindowBase
> 
> class ChildApp(App):
> 
>     def build(self):
>         Config.set('kivy', 'exit_on_escape', '0')
>         return Label(text='Child')
> 
>     def on_request_close(self):
>         self.textpopup(title='Exit', text='Are you sure?')
> 
>     def textpopup(self, title='', text=''):
>         """Open the pop-up with the name.
> 
>         :param title: title of the pop-up to open
>         :type title: str
>         :param text: main text of the pop-up to open
>         :type text: str
>         :rtype: None
>         """
>         box = BoxLayout(orientation='vertical')
> 
>         box.add_widget(Label(text=text))
> 
>         mybutton = Button(text='OK', size_hint=(1, 0.25))
>         box.add_widget(mybutton)
> 
>         popup = Popup(title=title, content=box, size_hint=(None, None), size= (600, 300))
>         mybutton.bind(on_release= Window.close)
> 
>         popup.open()
> 
> if __name__ == '__main__':
>     ChildApp().run()

**Comment by pythonic64** [comment]
@picibucor, [This should work for you](http://pastebin.com/5e7ymKTU)

**Comment by picibucor** [comment]
Thank you, it works :)

**Comment by pythonic64** [comment]
You're welcome!
