### ISSUE TITLE
Multi-touch broken on MSI Flex devices from 1.9.1 onwards

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy#4724]
When running 1.9.0, the touchtraces example shows all touches. From 1.9.1 onwards, no touches are shown. The MTD entires are not listed in the logs.

[tt_1.9.0.txt](https://github.com/kivy/kivy/files/586125/tt_1.9.0.txt)
[tt_1.9.2_dev.txt](https://github.com/kivy/kivy/files/586127/tt_1.9.2_dev.txt)

Related to #3964

**Comment by Zen-CODE** [comment]
Adding the following to kivy config.ini fixes this.

[input]
mouse = mouse
%(name)s = probesysfs,select_all=1

**Comment by schoolsplay** [comment]
But it with "mouse=mouse" it will introduce double touch events.
Remove it and all works as it should be.
So the entry must be:

[input]
%(name)s = probesysfs,select_all=1
