### ISSUE TITLE
Saving an Image using 'save()' throws error

### ISSUE THREAD

**Issue by udiboy1209** [kivy/kivy#4727]
Trying to save using this simple example from docs

On Ubuntu 16.04, python v2.7.11, kivy master
```
import kivy
from kivy.core.image import Image

img = Image('img.png')
img.save('img2.png')
```

Gives this error:

```
[INFO   ] [Logger      ] Record log in /home/udiboy/.kivy/logs/kivy_16-11-13_17.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "test_img.py", line 5, in <module>
     img.save('img2.png')
   File "/home/udiboy/.apps/venvs/kivy/local/lib/python2.7/site-packages/kivy/core/image/__init__.py", line 848, in save
     self.populate()
 AttributeError: 'Image' object has no attribute 'populate'
```

Error is at this line: https://github.com/kivy/kivy/blob/master/kivy/core/image/__init__.py#L848

The `populate()` method is in `ImageLoaderBase` class and not in `Image` class.

**Comment by saqib1707** [comment]
@udiboy1209  In  https://github.com/kivy/kivy/blob/master/kivy/core/image/__init__.py#L843 
Removing the 'not' in this line solves the error since if data.fmt is not in ('rgba' , 'rgb') then it has to invoke self.populate() to convert it to rgba format.

**Comment by udiboy1209** [comment]
@saqib1707 nice catch! Why don't you make a pull request with that change and add a test here https://github.com/kivy/kivy/blob/master/kivy/tests/test_image.py for testing the save function!
