### ISSUE TITLE
ActionGroup needs clicking twice

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4730]
Is it only me, or does the `ActionGroup` requires clicking twice? It worked normally before, at least in the beginning of 2016, but recently when I worked with it for a while I noticed this thing. The first touch seems to be ignored, but _isn't_ (try `on_release`), yet the `DropDown` won't show. When clicked the second time, it works normally. Seems like there's some issue with initialising the widget or something.

Run just the basic example in `actionbar.py` and try to click on either "Group 1" or "Group 2". I ran the  `showcase` demo too, but there the `Spinner` that looks like `ActionGroup` behaves normally because it inherits directly from `Spinner` and `ActionItem` in kv file and isn't built as a casual `ActionGroup`. Any ideas what's going on?

**Comment by udiboy1209** [comment]
I am getting the same result. First click results in a blink of the background. Second click is ignored entirely. Then everything works normally.

**Comment by KeyWeeUsr** [comment]
Found it! @tshirtman 's commit broke the clicking somehow 🌵 https://github.com/kivy/kivy/commit/7925e9db1e52a731333e1d1a435d9a9c3a59d91f
