### ISSUE TITLE
[Kivy Launcher] app install/update by http(s) from external website (https:// for github required)

### ISSUE THREAD

**Issue by ponyatov** [kivy/kivy#4740]
Please add to KL TODO (feature request) : 
add update/reload function for application over http (and https:// for github required)
to make apps install/update directly from smartphone by entering app url

**Comment by KeyWeeUsr** [comment]
This is a wrong repo, Kivy Launcher is in [p4a](https://github.com/kivy/python-for-android). To run an app via launcher you have to manually put a folder with your app into `sdcard/kivy`.

There seems to be no plans of implementing copying code from random archives placed in phone storage, nor making it possible through internet, therefore the only way how to do it is the standard [manual way](python-for-android.readthedocs.io/en/latest/launcher#usage).
