### ISSUE TITLE
Line ends are not drawn correctly on canvas

### ISSUE THREAD

**Issue by hackalog** [kivy/kivy#4752]
My line ends seem to be less than 100% of a circle if I draw a line anywhere towards the left.

e.g.
<img width="237" alt="line_ends_bug" src="https://cloud.githubusercontent.com/assets/11911411/20634764/464bd8b4-b322-11e6-8a38-8a1d7a0bac19.png">

This is on macos (retina), 

Simple reproducer below:
```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.lang.builder import Builder
from kivy.graphics import Color, Line

kv = '''

BugTest:

<BugTest>:
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            size: self.size
            pos: self.pos
    Label:
        text: 'test'
'''


class BugTest(BoxLayout):
    def __init__(self, **kwargs):
        super(BugTest, self).__init__(**kwargs)
        with self.canvas:
            Color(0, 0, 0, 1)
        self.line_width=10

    def on_touch_down(self, touch):
        with self.canvas:
            touch.ud['current_line'] = Line(
                points=(touch.x, touch.y), width=self.line_width, cap='round', joint='round')
            touch.ud['current_line'].points += (touch.x, touch.y)

    def on_touch_move(self, touch):
        if 'current_line' in touch.ud:
            touch.ud['current_line'].points += (touch.x, touch.y)


class LineEndBugApp(App):

    def build(self):
        self.app = Builder.load_string(kv)
        return self.app

LineEndBugApp().run()
```

**Comment by saqib1707** [comment]
@hackalog  On trying to reproduce I got this traceback..Basically there is no Builder class defined inside ..kivy/lang/builder.py

``Traceback` (most recent call last):
   File "test.py", line 3, in <module>
     from kivy.lang.builder import Builder
 ImportError: No module named builder`

**Comment by KeyWeeUsr** [comment]
@saqib1707 No problem with that code for me. Check if you have Kivy installed properly or try to make it `from kivy.lang import Builder` only.

**Comment by saqib1707** [comment]
Thanks @KeyWeeUsr .Its working .

**Comment by 700brains** [comment]
Hi friend why does my app crashes whenever I initialize it(start it)
meanwhile am running it in root directory

**Comment by 700brains** [comment]
Everytime I tried starting my kivy app it crashes automatically. Am running
it in a root  directory

**Comment by saqib1707** [comment]
@700brains   try to make it **from kivy.lang import Builder **only.

**Comment by 700brains** [comment]
Please bro/sis can you elaborate am zero to kivy framework
Just Give me an example on how?
And again running with **sudo** like sudo buildozer android debug is it
advisable to run with sudo. Can't wait to hear from you!

**Comment by KeyWeeUsr** [comment]
@700brains This is not a chat, please target beginner questions to IRC, mailing list or some other site supporting it clearly visible [here](https://kivy.org/#support).

The repository is specifically for code and issues related to it, not a Q&A website.

**Comment by 700brains** [comment]
Pls when I run it on my Ubuntu it went OK but after I compiled it to an apk
file and run on my tecno p9 it crashes. This is just a Hello world program
ignore the too much import I did will use it later

**Comment by saqib1707** [comment]
Just now I found out that the sangle=0 always and therefore https://github.com/kivy/kivy/blob/master/kivy/graphics/vertex_instructions_line.pxi#L564-L569 is  causing problems when the cap is square giving irregular line ends.Any idea how to solve this when cap='square' ?

**Comment by hackalog** [comment]
Any progress here? We've had the fox#4752 in our local kivy tree for ages, and it does indeed solve the problem with round ends.

**Comment by hackalog** [comment]
Bump this again. Is there some reason this wasn't getting merged? (or fixed a different way?) Is there something I can do to fix up the fix?

**Comment by tshirtman** [comment]
Sorry this fell out the radar, will look asap, seems you linked back there in previous comment, did you mean #4772 ?

**Comment by hackalog** [comment]
Sorry, yes, that's the fix I mean.

**Comment by tshirtman** [comment]
So, fun thing, i was looking into this again, because that fix is quite crude, and i could only reproducing it by hand-drawing the line with the example code, all my hardcoded examples were fine, until i dumped the points coords created by the examples, and saving them.

which looked like this
```
        Line:
            width: 20
            points:
                [
                375.0, 407.99999999999994,
                375.0, 407.99999999999994,
                373.0, 407.99999999999994,
                372.0, 407.99999999999994,
                372.0, 407.0,
                370.0, 403.0,
                368.0, 400.00000000000006,
                367.0, 398.0
                ]
```

So i commented out the 3 duplicate lines, and it went away. It's just that the duplicate points confuses the line algo, when it tries to find the segments angle, as these are 0-length segments, their angle is undefined, which leads to these beird behavior.

Editing the example code not to save the first point in on_touch down, seems to fix it too, but that might be just luck.

```
    def on_touch_down(self, touch):
        with self.canvas:
            touch.ud['current_line'] = Line(
                points=tuple(), width=self.line_width, cap=choice(caps), joint='round', cap_precision=5)

            touch.ud['current_line'].points += (touch.x, touch.y)

    def on_touch_move(self, touch):
        if 'current_line' in touch.ud:
            touch.ud['current_line'].points += (touch.x, touch.y)
            print(touch.ud['current_line'].points)
```

So, we could avoid these 0-length segments, either when `points` is assigned, (but that could be quite a performance cost), or during drawing, the downside here is that it wouldn't allow us to account for the saved points in the malloc, but that still seems better, efficiency wise?

**Comment by tshirtman** [comment]
```diff
diff --git a/kivy/graphics/vertex_instructions_line.pxi b/kivy/graphics/vertex_instructions_line.pxi
index 19ea74436..3b8282ec3 100644
--- a/kivy/graphics/vertex_instructions_line.pxi
+++ b/kivy/graphics/vertex_instructions_line.pxi
@@ -332,7 +332,7 @@ cdef class Line(VertexInstruction):
         cdef double pcx, pcy, px1, py1, px2, py2, px3, py3, px4, py4, pangle, pangle2
         cdef double w = self._width
         cdef double ix, iy
-        cdef unsigned int piv, pii2, piv2
+        cdef unsigned int piv, pii2, piv2, skip = 0
         cdef double jangle
         angle = sangle = 0
         piv = pcx = pcy = cx = cy = ii = iv = ix = iy = 0
@@ -346,7 +346,11 @@ cdef class Line(VertexInstruction):
             bx = p[i * 2 + 2]
             _by = p[i * 2 + 3]
 
-            if i > 0 and self._joint != LINE_JOINT_NONE:
+            if (ax, ay) == (bx, _by):
+                skip += 1
+                continue
+
+            if i - skip > 0 and self._joint != LINE_JOINT_NONE:
                 pcx = cx
                 pcy = cy
                 px1 = x1
@@ -384,7 +388,7 @@ cdef class Line(VertexInstruction):
             x3 = bx + cos2
             y3 = _by + sin2
 
-            if i == 0:
+            if i - skip == 0:
                 sx1 = x1
                 sy1 = y1
                 sx4 = x4
@@ -421,7 +425,7 @@ cdef class Line(VertexInstruction):
             iv += 1
 
             # joint generation
-            if i == 0 or self._joint == LINE_JOINT_NONE:
+            if i - skip == 0 or self._joint == LINE_JOINT_NONE:
                 continue
 
             # calculate the angle of the previous and current segment
@@ -498,8 +502,6 @@ cdef class Line(VertexInstruction):
                     ii += 6
                     iv += 2
 
-
-
             elif self._joint == LINE_JOINT_ROUND:
 
                 # cap end
@@ -644,6 +646,11 @@ cdef class Line(VertexInstruction):
             indices[ii + 2] = piv + 2
             ii += 3
 
+        while ii < indices_count:
+            indices[ii] = 0
+            print("catching up")
+            ii += 1
+
         # compute bbox
         for i in xrange(vertices_count):
             if vertices[i].x < self._bxmin:
```

Not very nice, but as long as the line has segments with a defined length, it seems to do the job.

**Comment by tshirtman** [comment]
Yes, the case where all points are equal should just draw both caps i guess, (which my fix doesn't do correctly), if i add even 1e-10 to one of the values, just to differenciate them, without any visible difference, the look is fixed, but maybe we should find a more elegant solution.
