### ISSUE TITLE
Modal Dialog: issues with touches active before dialog opened 

### ISSUE THREAD

**Issue by hottwaj** [kivy/kivy#4756]
Hi guys, some slightly odd things are possible when a dialog is opened, if you hold down a touch in the meantime.

Example 1 (more problematic):
1. press a button, keep your finger held down (don't release touch)
2. press another button that opens a modal dialog
3. release touch from 1 - the action of the first button is now triggered even though a modal dialog is open.

Example 2 (weird but not a problem):
1. start dragging the contents of a list, don't release touch
2. press something that opens a model dialog
3. you can continue dragging around the list with the touch started in 1

So, the modal dialog needs to somehow make all widgets drop any touches they have grabbed, to stop this happening.

Thanks

**Comment by KeyWeeUsr** [comment]
Re Example 1: Kivy is multitouch, such thing should be possible and desired.

Re Example 2: Not sure what the _"list"_ is, but I think it's probably the same answer as for Example 1 - multitouch support.

A workaround for that might be editing a part of your `config.ini` file in `<user>/.kivy/config.ini` like this:

```
[input]
mouse = mouse,disable_multitouch
```
