### ISSUE TITLE
Installation from stable repository doesn't include kivy.tools

### ISSUE THREAD

**Issue by SynedraAcus** [kivy/kivy#4759]
When kivy is installed via `sudo apt-get install python3-kivy`, the installation is missing kivy.tools, thus crashing when I try to build a linux distro for my project. Otherwise it's working kivy1.9.1 installation with which I've succesfully developed software. I've used python3.4 and stable repository at `ppa:kivy-team/kivy`.
I've fixed the problem by removing python3-kivy package and installing kivy-master from github as @alexhayes suggested at #3002 so it's probably an outdated version at repository.

**Comment by KeyWeeUsr** [comment]
I think it's similar to the wheels, where I too don't see kivy.tools. At least not everything from the repo.

**Comment by KeyWeeUsr** [comment]
@SynedraAcus The `kivy.tools` folder is missing completely, or only a part of it, e.g. `gles` header or something...? Probably it's only missing [here](https://github.com/kivy/kivy/blob/master/setup.py#L968).

**Comment by SynedraAcus** [comment]
There was no `tools` folder at all *in installed library* at, if my memory serves, `/usr/lib/python3.4/dist-packages`. I have very little idea how kivy gets packaged and installed, so I cannot say why this issue come to be.
