### ISSUE TITLE
Linux Mint VM buildozer Label halign anomaly

### ISSUE THREAD

**Issue by frankgould** [kivy/kivy#4767]
![screen-new1](https://cloud.githubusercontent.com/assets/11017534/20869848/da9ebd6e-ba49-11e6-9e22-aa421b32c28a.png)
![screen-new2](https://cloud.githubusercontent.com/assets/11017534/20869855/e956d6d4-ba49-11e6-8452-8d4e67569d76.png)
These two pictures show how the Label text is misaligned when compiled on Linux Mint although using the same code compiled with OSX, the displays appear as the other aligned text in the attached pictures.
![screen-old1](https://cloud.githubusercontent.com/assets/11017534/20869867/29587530-ba4a-11e6-9b3d-7b2628a5543c.png)
![screen-old2](https://cloud.githubusercontent.com/assets/11017534/20869869/2e838f7c-ba4a-11e6-8c54-3a4a90114bec.png)
Why is the Linux compile behaving differently? I tried to set the halign different ways but never changed the displayed placement.

**Comment by dessant** [comment]
Quite possibly the two devices use different text providers, or kivy versions. Share an example app with the relevant label, and debug logs from both devices.

**Comment by frankgould** [comment]
Thanks dessant. I'll have to research that when I can compile again on OSX. I'm waiting for an issue resolution below to get the log.

https://github.com/kivy/python-for-android/issues/924

**Comment by frankgould** [comment]
I have successfully install kivy interpreter on Windows and am getting the same display results. I tried changing the halign value to left, right, and center but the text is still displaying in the same location. If I need to provide debug log, does that mean the kivy log? I'm assuming above is the buildozer build log needed for review. Below is the Label line I use to define both displayed on the screen:

Label(text=text_str,font_name=mp_frame.floatclock_fontfile, markup=True, font_size=mp_frame.floatclock_fontpixel, halign='center', valign='middle')

**Comment by dessant** [comment]
Yes, the log which you get after running the app.

**Comment by frankgould** [comment]
Okay, this was a challenge and I've tried to provide what you're asking below in the different files.

The logs from my original code that matches the screen captures above:
**Linux apk:**  
[kivy-myapp-log-GS14-linux-apk.txt](https://github.com/kivy/kivy/files/639760/kivy-myapp-log-GS14-linux-apk.txt)

**OSX apk:**  
[kivy-myapp-log-HDY133-osx-apk.txt](https://github.com/kivy/kivy/files/639761/kivy-myapp-log-HDY133-osx-apk.txt)

**Interpreter (matches Linux apk screen):**  
[kivy-myapp-log-interpreter.txt](https://github.com/kivy/kivy/files/639762/kivy-myapp-log-interpreter.txt)

The logs from your test code above, I only added version to build apk:
**Linux apk:**  
[kivy-org-TEST-HDY133-log.txt](https://github.com/kivy/kivy/files/639754/kivy-org-TEST-HDY133-log.txt)

**Interpreter:**  
[kivy-org-TEST-Interpreter-log.txt](https://github.com/kivy/kivy/files/639757/kivy-org-TEST-Interpreter-log.txt)

The screen captures from your test code above:
**Linux:**
![android-apk-screen](https://cloud.githubusercontent.com/assets/11017534/21014278/5f8333a0-bd2b-11e6-929b-4f13eea7e4c7.png)

**Interpreter:**  
![test-interpreter-screen](https://cloud.githubusercontent.com/assets/11017534/21014265/57283cdc-bd2b-11e6-8678-3eb23a6c3929.PNG)

**Comment by dessant** [comment]
The key was to *customize* the example and reproduce your bug with it. When you have that, share the example which shows the bug, with the *runtime* debug logs and a screenshot.

**Comment by frankgould** [comment]
Sorry for my misunderstanding and thanks for your patience. I've stripped down my app to show the text alignment anomaly and how it is used with screenmanager. I was not able to get the background pictures to show (e.g. Slide-1.jpg) but that's not important for what you've asked to see. I've attached the code (.py.txt), logs, and screenshot. Please let me know if there is anything else I can provide.

[main-kivy-test.py.txt](https://github.com/kivy/kivy/files/642823/main-kivy-test.py.txt)
[Test2-Interpreter-logcat.txt](https://github.com/kivy/kivy/files/642820/Test2-Interpreter-logcat.txt)
![test2-interpreter-screen](https://cloud.githubusercontent.com/assets/11017534/21058746/6e75e9e2-be0d-11e6-887c-501980c594a7.PNG)
[mp-ss_16-12-09_0.txt](https://github.com/kivy/kivy/files/642821/mp-ss_16-12-09_0.txt)

**Comment by dessant** [comment]
`main-kivy-test.py.txt` contains 476 lines of code.

**Comment by KeyWeeUsr** [comment]
Okay, nice to see some code. I'm sorry to tell, but that code is **_highly unreadable_**. Mostly there are problems even with readable _long_ code, so... imagine we need to read it and find what is where broken. See https://github.com/kivy/kivy/wiki/Community-Guidelines

If you leave the code for about a month or more, you won't be able to figure out what the hell does the thing exactly do. For such reasons there's `pep8`, which is a package/recommendation of how to format python code. You can run it with `python -m pep8 <file>`. You can watch [this video](https://www.youtube.com/watch?v=wf-BqAjZb8M) to get inspired why to write code in a readable way.

That's being said, I patched the code so that is could run without bashing around for non-existing files on my machine and the only reason why the bottom text was positioned badly was because of this line:

    mp_frame.floatclock1_content = BoxLayout(
        orientation="vertical",
        cols=1, padding=10, spacing=10,
        size_hint=(None, None), width=mp_frame.floatclock_pos[mp_frame.floatclock_type][0],
        center=(mp_frame.floatclock_pos[mp_frame.floatclock_type][0]/2,mp_frame.floatclock_pos[mp_frame.floatclock_type][1]/2))
        # ↑ bad

You set center _explicitly_ and such a behavior is documented [here](https://kivy.org/docs/api-kivy.uix.widget.html#usage-of-widget-center-widget-right-and-widget-top). That's the bottom blue `Scatter`

For the upper part you did the same thing:

    mp_frame.caption1_content = BoxLayout(
        orientation='vertical', cols=1, padding=20, spacing=20, 
        size_hint=(None, None), width=mp_frame.captions_width, 
        center=(mp_frame.captions_width/2,mp_frame.captions_bottom_y+(mp_frame.captions_height/2))) 
        # ↑ bad

Which basically means you misunderstood how [`Widget.center`](https://kivy.org/docs/api-kivy.uix.widget.html#kivy.uix.widget.Widget.center) works and that crippled your app.

Don't set `center = something`, do rather for example `pos_hint = {'center': 0.5}`. And also check to what value you set position variables if such thing happens again.

**Comment by frankgould** [comment]
**Thank you!** You are wonderful people, and _I am not worthy_. I truly appreciate your time to consider my problem and offering a solution and better understanding on my part. I now know why tshirtman said he couldn't condone my coding. As you can tell, I am new to this environment and had little training before starting this project. My last software product I wrote in Visual Basic.

I want to thank KeyWeeUsr especially for pointing out where my problem was. I thought it was a `Label `problem but turned out to be the `BoxLayout `center function. I removed `center={something}` from the line and the problem I reported went away. However, the text was then offset wrong in the y axis. So following the center function page KeyWeeUsr directed me to, I added back my y axis value using `center_y={something}` and it centered correctly in both axis.

So, since my original problem was my code doing something it's not supposed to do, I thought I should report this to make sure I'm not doing something else wrong, or there might be an anomaly. I can send more examples, if you need. Again, **I really appreciate all your help and guidance**.

As Cheaterman recently chat, "< @Cheaterman > FrankAGould: Don't be sad though, your code belongs in a museum."
