### ISSUE TITLE
JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#4769]
kivy _1.9.2dev0_
android.api = _19_
android.minapi = _13_
android.sdk = _20_
android.ndk = _9c_

built with:
buildozer _0.33dev_
target _android_new_

tested on _Android 4.4.2_

The error part log:
```
12-05 02:00:30.265 10534 10555 E dalvikvm: JNI ERROR (app bug): local reference table overflow (max=512): tbe.kivy.tbe
12-05 02:00:30.265 10534 10555 W dalvikvm: JNI local reference table (0x7b3bce18) dump:: tbe.kivy.tbe
12-05 02:00:30.265 10534 10555 W dalvikvm:   Last 10 entries (of 512):: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       511: 0x417611e8 java.lang.Class<java.lang.Class>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       510: 0x41761890 java.lang.Class<java.lang.Object>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       509: 0x417611e8 java.lang.Class<java.lang.Class>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       508: 0x41761890 java.lang.Class<java.lang.Object>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       507: 0x417611e8 java.lang.Class<java.lang.Class>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       506: 0x41761890 java.lang.Class<java.lang.Object>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       505: 0x417611e8 java.lang.Class<java.lang.Class>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       504: 0x41761890 java.lang.Class<java.lang.Object>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       503: 0x417611e8 java.lang.Class<java.lang.Class>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       502: 0x41761890 java.lang.Class<java.lang.Object>: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:   Summary:: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:       510 of java.lang.Class (3 unique instances): tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:         1 of java.lang.Object: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 W dalvikvm:         1 of java.lang.String[]: tbe.kivy.tbe
12-05 02:00:30.275 10534 10555 E dalvikvm: Failed adding to JNI local ref table (has 512 entries): tbe.kivy.tbe
```

Full log:
https://goo.gl/TLMiIg

The app crash immediately after the loading screen (or while loading?). 
Several commits ago all work well (i tested it on summer with the same target). 
The app run without crash with _android_ as target.
I have not changed the app's code since that time.

I'm not sure that this problem is related to kivy. I noticed several minor issues even with the _android_ target (which didn't appear before). 
It could be a problem related to the build process with buildozer?

As i don't know where is exactly the piece of code that produce this error, if someone want to reproduce the error i can send the link (on request) to the closed alpha of the app on play store that i'm developing.

**Comment by Tungsteno74** [comment]
After some research what i found is that  the main instance of the kivy app would seem that is instantiated in an endless loop until the JNI allocation space is saturated.
Is that correct? Someone can confirm that?

**Comment by Tungsteno74** [comment]
I created a minimalistic application (containing only a few buttons), and seems to work without giving this problem. So, contrary to what I thought the problem could be in my application.

**Comment by Tungsteno74** [comment]
**Updated the full log in the first post.**

I found that the error is 99% in the following call exception:
`Exception jnius.jnius.JavaException: JavaException('Unable to find the class java/lang/reflect/Modifier',) in 'kivy.properties.dpi2px' ignored: tbe.kivy.tbe`

This exception seems to be related to the use of a conversion function in _metrics_ module: https://github.com/kivy/kivy/blob/master/kivy/metrics.py#L133

I'm my app (and in the minimalistic app) i used sp and dp functions, but only in my app i give that error.

I've checked the dpi2px used by metrics function too:  
https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L236
but i'm not able to find any  malfunction here (i'm not really good to fix bugs here)

Anyhow the related error exception seem have a start on this pyjinius class (or somewhere in the same module):
https://github.com/kivy/pyjnius/blob/master/jnius/reflect.py#L63
but not sure because, i'm really a crap to understand java calls and related code.

Someone have same errors with last version of kivy?

Last but not least, some expert can help me understand this kind of error? (So I can try to fix it)

many thanks

**Comment by Tungsteno74** [comment]
Finally i found the problem!
Basically the following command raise the previous error with SDL2

`Config.set('kivy', 'window_icon', 'assets/logo_64x64.png')`

This strange behaviour is not specified in the doc (i think should be documented, no?). 
I don't know if on this implementation of Kivy is an unfixable problem or not, but what i think is that at least should be skipped in build phase considering that the error string does not help to find the problem.

I can close this error, but i'd like to receive a developer reply before.

**Comment by dessant** [comment]
This issue was moved to kivy/python-for-android#971
