### ISSUE TITLE
[kivy dev 1.9.2] No module named 'kivy._clock'

### ISSUE THREAD

**Issue by frankgould** [kivy/kivy#4770]
I found this page and realized later it was closed:  https://github.com/kivy/kivy/issues/4428

I am getting the same results with python 2.7:

python main-test.py
[INFO ] [Logger ] Record log in c:/users/frank gould/build/data/logs\mp-ss_16-12-06_0.txt
[INFO ] [Kivy ] v1.9.2-dev0
[INFO ] [Python ] v2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
Traceback (most recent call last):
File "main-test.py", line 1, in 
from kivy.app import App
File "C:\Users\Frank Gould\Desktop\Master-Pics\SlideShow Build\kivy\app.py", line 319, in 
from kivy.base import runTouchApp, stopTouchApp
File "C:\Users\Frank Gould\Desktop\Master-Pics\SlideShow Build\kivy\base.py", line 29, in 
from kivy.clock import Clock
File "C:\Users\Frank Gould\Desktop\Master-Pics\SlideShow Build\kivy\clock.py", line 364, in 
from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, 
ImportError: No module named _clock

**Comment by dessant** [comment]
How was kivy installed?

**Comment by frankgould** [comment]
python -m pip install Kivy-1.9.2.dev0-cp27-none-win32.whl

**Comment by KeyWeeUsr** [comment]
@frankgould Try to download again from one of these [links](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation) and install again. I have no problem with them and the `Clock` is compiled successfully.

**Comment by frankgould** [comment]
I added --upgrade to the command above with the new night build I downloaded, per your suggestion. It appears to have changed the results to the following:
>python main-test.py
Traceback (most recent call last):
  File "main-test.py", line 1, in <module>
    from kivy.app import App
ImportError: No module named app

**Comment by dessant** [comment]
The --upgrade option should not have been added, that alone tainted the triaging process. So far this appears to not be a kivy bug, please visit #kivy on freenode if you need further help.

**Comment by hemangjoshi37a** [comment]
> @frankgould Try to download again from one of these [links](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation) and install again. I have no problem with them and the `Clock` is compiled successfully.

Error 404
