### ISSUE TITLE
python -m pip install:  IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by frankgould** [kivy/kivy#4773]
When trying: python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew

It returns the following error message:
IOError: [Errno 13] Permission denied: 'C:\\Python27\\Lib\\site-packages\\pywin32_system32\\pythoncom27.dll'

OS:  Windows 7

**Comment by saqib1707** [comment]
May be you should try opening the command prompt in administrator mode to gain the root access.Then try the installation.

**Comment by KeyWeeUsr** [comment]
This is not a Kivy-related issue. Most likely it's just pip trying to access the file unsuccessfully or something. I experience it on Windows quite often and closing the related executables and/or running the command again fixes it.

**Comment by frankgould** [comment]
Thank you KeyWeeUsr! I never thought to try it again. I'll use this advice going forward.
