### ISSUE TITLE
Interpreter stopped working

### ISSUE THREAD

**Issue by frankgould** [kivy/kivy#4775]
I do not understand what happened to my kivy interpreter. Start of the day, I was getting the following error message:
  File "main.py", line 8, in <module>
    from kivy.app import App
ImportError: No module named app

Then I used the instruction on the link below to Download Kivy from GitHub:
$ git clone git://github.com/kivy/kivy.git
$ cd kivy
$ python setup.py build_ext --inplace -f

https://kivy.org/docs/installation/installation.html

I ran my kivy app a few times, closed the window and reopened the console. The next time I ran my kivy app, I got the same No module named app error, tried the clone steps above, and ended up with this error:  
  File "setup.py", line 325, in <module>
    from kivy.tools.packaging.factory import FactoryBuild
ImportError: No module named tools.packaging.factory

I don't know what I possibly did to cause this to fail again much less why I can fix it again. Please help and I do appreciate all of your help. Sorry I'm such a casualty.

**Comment by dessant** [comment]
We have no idea what you did either, but please, use the issue tracker only for real bug reports, the mailing list and irc channel are for support questions.

https://github.com/kivy/kivy#support

**Comment by frankgould** [comment]
I found out what caused the problem: running kivy.bat, it changed the PATH values. I guess this isn't a real bug?

**Comment by dessant** [comment]
`kivy.bat` is part of the portable package, which was deprecated.

**Comment by KeyWeeUsr** [comment]
@frankgould I wonder if you really used `kivy.bat` from Kivy `1.8.0` or from [KivyInstaller](https://github.com/KeyWeeUsr/KivyInstaller), because `1.8.0` is like the beginning of 2014.

**Comment by frankgould** [comment]
@KeyWeeUsr I installed my Windows kivy around the end of October 2014 and I believe it was 1.8.0 kivy. I've attached a txt version of the kivy.bat file for your review. I had to change the file extension because of github file type requirements (doesn't support .bat).
[kivy.txt](https://github.com/kivy/kivy/files/639283/kivy.txt)
