### ISSUE TITLE
Local Config file misplaced

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4777]
For some reason when you set local configuration and save it (to a `<app>.ini`), the file is misplaced on Android and maybe even on iOS, which makes it harder to remove the app - the file will persist and will annoy users, because the config is pulled from that file, therefore if a user makes a mistake in the config, the config would need to be removed manually.

ref https://github.com/kivy/python-for-android/issues/953

**Comment by inclement** [comment]
This behaviour is probably also the only thing in Kivy that needs the external storage read/write permission. With this fixed (which I believe it should be), Kivy apps wouldn't need any permissions by default.

**Comment by KeyWeeUsr** [comment]
@inclement [this line](https://github.com/kivy/kivy/blob/5913d861f45119dfff0b6cb5d004e6f79858563c/kivy/app.py#L657) and the line under (ios) will cause the issue. I don't have a clue how iOS handles permissions, but this requires the Android `WRITE_EXTERNAL_STORAGE` permission and if android is going to change, iOS should aquire the same/similar structure.

If not change, then at least a mention in the documentation that such thing _requires_ additional stuff such as android permission for writing to the SDcard.

However, I notices something weird and that's missing `Mac` platform or better said folder. @akshayaurora could you please look at the missing part and confirm if iOS requires similar thing to android write permission for such configuration?

Windows places the file next to the `main.py` file, therefore it behaves as expected, not as plain `Config.write` (which sometimes writes to `%appdata%`).

**Comment by Zen-CODE** [comment]
@KeeWeeUsr. The iOS path looks fine. This '~/Documents/' folder is this-app-only, write-able and pretty much guaranteed available by iOS without special permissions, so should not present a problem. 

Although strictly speaking Apple recommends this only for files which a user should see, the file system is so hidden on iOS its' a very academic distinction.

https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

**Comment by KeyWeeUsr** [comment]
@Zen-CODE Thanks for the info, I thought it's just some general folder and it _needs_ additional permissions. I presume the folder **is deleted** after the app is uninstalled, right? Otherwise the issue persists i.e. file not removed and old config used.

I'm not sure if that should be thrown at the dev to handle him/herself, but it doesn't seem like the case to me. Kivy shouldn't just throw stuff everywhere and expect dev to go play hide&seek. 😋

**Comment by Zen-CODE** [comment]
Yes, the ~/Documents' seems to be removed on an un-install for iOS (just by deleting the icon off the desktop). All our app data lies there, and it was gone with a 2nd install.

**Comment by JonasT** [comment]
The code to get the correct path on Android is:

```python
from jnius import autoclass, cast
PythonActivity = autoclass('org.kivy.android.PythonActivity')
currentActivity = cast('android.app.Activity', PythonActivity.mActivity)
context = cast('android.content.ContextWrapper', currentActivity.getApplicationContext())
file_p = cast('java.io.File', context.getFilesDir())
path = file_p.getAbsolutePath()
```
(I put this together by digging around in the Android SDK documentation, some Stackoverflow and a bit of trial and error.)

It would really seem like a splendid idea to me to return this instead of `/sdcard/<appname>` since that just doesn't make too much sense, and needs the sdcard write permission on top of things. I didn't make a pull request because I don't actually use kivy myself (I use p4a with raw PySDL2) so I couldn't test the change in the context of kivy, but it worked perfectly fine for my python-for-android app.

**Comment by JonasT** [comment]
Just as a note, as soon as https://github.com/kivy/python-for-android/pull/1528 is in, this will no longer be optional (because it will bump the minimum API level to 26 where apps don't have storage access by default, even if asked for in the manifest). So it would be good if this could be addressed soon, or kivy might no longer work properly on latest p4a. Also see #6081

**Comment by Zen-CODE** [comment]
@JonasT. I think it also makes sense to change the user_data_dir on android to return that same path (using jnius above ).

https://kivy.org/doc/stable/api-kivy.app.html#kivy.app.App.user_data_dir

The user_data_dir needs to be writable by default on android. At the moment, I'm using the following:

            from jnius import autoclass, cast
            PythonActivity = autoclass('org.kivy.android.PythonActivity')
            Environment = autoclass('android.os.Environment')
            context = cast('android.content.Context', PythonActivity.mActivity)
            user_dir = context.getExternalFilesDir(
                Environment.getDataDirectory().getAbsolutePath()
            ).getAbsolutePath()

but reading this: https://www.grokkingandroid.com/how-to-correctly-store-app-specific-files-in-android/

The getFilesDir seems like the better option?

**Comment by JonasT** [comment]
Yes, I think `getFilesDir()` makes sense for both the config place and `kivy.app.App.user_data_dir`. I posted code above on how to obtain it

**Comment by JonasT** [comment]
@KeyWeeUsr didn't you have a pull request for this? What's the state on things? Because if we finally get merge activity moving on p4a again, this might be a real problem really quick (because the SDL2 version bump requires targeting 21+ where this bug will affect *all* kivy apps with no workaround)

**Comment by Zen-CODE** [comment]
@JonasT. I plan to submit a PR for this one in the next few days and will reference this ticket in the PR.

**Comment by Zen-CODE** [comment]
Okay, I've added this PR to address this. https://github.com/kivy/kivy/pull/6095

I've also listed it under the "Backward incompatible change" tickets, as it is going to change what android user currently expect for this value...

    https://github.com/kivy/kivy/issues/5560

**Comment by Fak3** [comment]
Can this issue be closed now?

**Comment by Zen-CODE** [comment]
Guess so. Thanks
