### ISSUE TITLE
TypeError during cache lookup when loading image texture if source is BytesIO

### ISSUE THREAD

**Issue by jerickson-thorlabs** [kivy/kivy#4778]
I'm building a kivy app that works with images gathered from a camera. So, I need to use an in-memory image to provide the user a live view of what the camera sees. The library that supports the camera gives me a PIL.Image, so I use io.BytesIO to make a kivy image by doing this:

    def update_canvas(self, **kwargs):
        if self._disp_image is not None:
            temp_image = self._disp_image
            image_bytes = io.BytesIO()
            temp_image.save('pil_image.png','PNG')
            temp_image.save(image_bytes, 'PNG')
            image_bytes.seek(0)
            im = KivyImage(ImageLoaderPIL(image_bytes))
            im.save('kivy_image.png')
            with self.canvas:
                Color(0,1,0,1)
                Rectangle(pos=(0,0),size=self._disp_image.size, texture=im.texture)

When I run the program, the pil_image.png and kivy_image.png files are a match. But, when I try to paint the texture, I get a type error that I've traced to line 233 of kivy/core/image/__init__.py.

The line where the failure occurs reads: `uid = chr(u'%s|%d|%d') % (fname, self._mipmap, count)`

That line throws a `TypeError: 'str' does not support he buffer interface`

gist is here: https://gist.github.com/jerickson-thorlabs/303934432bbf5ee8881cefbbe2402043

**Comment by dessant** [comment]
I could not reproduce your crash because the example is not runnable.  Here's a cleaner way of getting a kivy texture from a Pillow `Image`:

```python
import io

from PIL import Image
from kivy.core.image import Image as CoreImage


image = Image.new('RGBA', (100, 100))
image_bytes = io.BytesIO()
image.save(image_bytes, 'png')
image_bytes.seek(0)
im = CoreImage(image_bytes, ext='png', size=(100, 100))
tex = im.texture
```
