### ISSUE TITLE
Scatter on desktop platforms translates 2 * (mouse delta)   (doesn't equal mouse translation)

### ISSUE THREAD

**Issue by enjoysmath** [kivy/kivy#4780]
I haven't tested this on handheld.  Fix is in scatter.py (see comment below)

    def transform_with_touch(self, touch):
        # just do a simple one finger drag
        changed = False
        if len(self._touches) == self.translation_touches:
            # _last_touch_pos has last pos in correct parent space,
            # just like incoming touch
            dx = (touch.x - self._last_touch_pos[touch][0]) \
                * self.do_translation_x
            dy = (touch.y - self._last_touch_pos[touch][1]) \
                * self.do_translation_y
            a = 2 if kivy.utils.platform() in ('win', 'macosx', 'linux') else 1     # BUG FIX: test platform
            dx = dx / (self.translation_touches * a)           # BUG FIX: divide by 2
            dy = dy / (self.translation_touches * a)           # BUG FIX: divide by 2
            self.apply_transform(Matrix().translate(dx, dy, 0))
            changed = True

To recreate bug, add any widget (e.g. Label) to a ScatterPlaneLayout and try moving the layout with left mouse click/dragging.  Bug:  the layout moves twice as much as it should upon each drag.

**Comment by enjoysmath** [comment]
I'm on windows 7

**Comment by dessant** [comment]
@enjoysmath, haven't looked into it, but you could create a PR if you already figured out the details. ++

**Comment by saqib1707** [comment]
@enjoysmath I tried to recreate the bug , but I think there is no issue with that since scatter is translating whatever distance the mouse translates . Rather dividing it by 2 (as mentioned in your fix) makes its speed half and therefore it lags behind the mouse. I'm on linux(ubuntu 16.04) by the way.

**Comment by KeyWeeUsr** [comment]
Win 8.1, no such issue, VM with 7, also no such thing appeared. I have no clue what should trigger this issue as as saqib said, the touch now equals to what the mouse really travels, which _is good_.

What you however might experience is `Scatter` with this canvas:

    canvas:
        Color:
            hsv: 0, 1, .5
        Rectangle:
            pos: self.pos  # moves "2+ times" more
            size: self.size

If that is the case, just remove `pos: self.pos` and see if the issue persists. If it's not this case, then without a reproducible example this should be closed.

**Comment by dessant** [comment]
Maintainers: the `awaiting-reply` label must be reapplied after your posts, otherwise it will have no effect and the issue will stay open regardless of the the original author following back or not.
