### ISSUE TITLE
Feature Request: Range Slider Widget

### ISSUE THREAD

**Issue by crashMOGWAI** [kivy/kivy#4786]
Suggest extending the basic slider and adding a range slider. I think it is common enough to add a built in. 
Example: https://refreshless.com/nouislider/

**Comment by saqib1707** [comment]
@crashMOGWAI  Apart from adding a range-slider , feature of showing min_value, max_value and current_value can be added so that user don't have to explicitly add them and can have a choice whether to show these values in his app by setting (may be) a boolean variable.

**Comment by Julian-O** [comment]
Based on comments on the PR, it seems this isn't warranted as being part of Kivy, but belongs in the garden as an add-on.

Closing as not planned.
