### ISSUE TITLE
Kivy slider show no tracking

### ISSUE THREAD

**Issue by ronbarak** [kivy/kivy#4792]
Following is adapted from https://stackoverflow.com/questions/41104810/kivy-slider-show-no-tracking/41111456

I started playing around with `Kivy,` and from the [documentation][1] I understand that I can create a `slider` that highlights its changing value using `Slider(value_track=True ...)`

Here's an [mcve][2], but alas, tracking isn't working:

    from kivy.app import App
    from kivy.uix.slider import Slider
    
    class TutorialApp(App):
        def build(self):
    
            s = Slider(min=-100, max=100, value=25,
                       value_track=True, value_track_color=[0, 1, 0, 1])
            return s
    
    if __name__ == "__main__":
        TutorialApp().run()

  [1]: https://kivy.org/docs/api-kivy.uix.slider.html
  [2]: http://[mcve]

**Comment by dessant** [comment]
@ronbarak, I see a green bar before the handle, could you test with kivy master?

**Comment by souravbadami** [comment]
@ronbarak -- Works perfectly for me on master.
