### ISSUE TITLE
Popup Renders Incorrectly

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#4802]
Developing a detailed game using Kivy and using popups for some player interaction. Often, the Popup displays very badly. Cannot reproduce this with a simple click to display Popup, but using some threading shows it up to 25% of the time and my game uses threading. Here is an extremely simplified code that displays the problem when you click on 'Multiple Popups' button (does 20 popups sequentially, using a timer): 

    
    from kivy.app import App
    from kivy.uix.relativelayout import RelativeLayout
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.popup import Popup
    from kivy.uix.button import Button
    from kivy.uix.label import Label

    from threading import *

    class TheTest(RelativeLayout):
        def __init__(self, *args):
            RelativeLayout.__init__(self, *args)
            self.popButton = Button(text='Popup', size_hint=(0.2, 0.2), pos_hint={'center_x': 0.5, 'y': 0.6})
            self.multiplePopups = Button(text='Multiple Popups', size_hint=(0.2, 0.2), pos_hint={'center_x': 0.5, 'y': 0.4})
            self.quitButton = Button(text='Quit', size_hint=(0.2, 0.2), pos_hint={'center_x': 0.5, 'y': 0.2})
            self.popButton.bind(on_press=self.do_popup)
            self.quitButton.bind(on_press=self.do_quit)
            self.multiplePopups.bind(on_press=self.start_multiple_popups)
            self.add_widget(self.popButton)
            self.add_widget(self.quitButton)
            self.add_widget(self.multiplePopups)
            self.pop_count = 0
            self.max_pops = 20

        def do_popup(self, *args):
            boxlayout = BoxLayout(orientation='vertical')
            label = Label(text='This is a Label')
            boxlayout.add_widget(label)
            label = Label(text='This is another Label')
            boxlayout.add_widget(label)
            label = Label(text='This is yet another Label')
            boxlayout.add_widget(label)
            button = Button(text='OK')
            button.bind(on_press=self.popup_dismiss)
            boxlayout.add_widget(button)
            if self.pop_count > 0:
                title = 'Test is test #' + str(self.pop_count)
            else:
                title = 'This is a Test'
            self.popup = Popup(title=title, content=boxlayout, size_hint=(0.5, 0.5))
            self.popup.open()

        def popup_dismiss(self, *args):
            self.popup.dismiss()

        def do_quit(self, *args):
            app.stop()
        
        def next_popup(self, *args):
            self.popup.dismiss()
            if self.pop_count >= self.max_pops:
                return
            self.pop_count += 1
            self.do_popup()
            t = Timer(0.5, self.next_popup)
            t.start()
        
        
        def start_multiple_popups(self, *args):
            self.pop_count = 1;
            self.do_popup()
            t = Timer(0.5, self.next_popup)
            t.start()

    class TesterApp(App):
        def build(self):
            return TheTest()

     if __name__ == '__main__':
        app = TesterApp()
        app.run()

Here is the debug log:
[kivy_16-12-14_30.txt](https://github.com/kivy/kivy/files/652746/kivy_16-12-14_30.txt)

Here is the expected popup display:
![correct](https://cloud.githubusercontent.com/assets/12189166/21198670/31687114-c20e-11e6-8b7d-4c539b2cf7b9.png)

And here some examples of the bad rendering:
![error1](https://cloud.githubusercontent.com/assets/12189166/21198695/4aad2200-c20e-11e6-94c4-08e7cc4d806e.png)
![error2](https://cloud.githubusercontent.com/assets/12189166/21198698/4db48aa6-c20e-11e6-9d87-4d67ccadb68d.png)
![error3](https://cloud.githubusercontent.com/assets/12189166/21198704/5578e52a-c20e-11e6-853e-c1f0e49c91cc.png)

**Comment by KeyWeeUsr** [comment]
Seems like the layout wasn't even built properly yet it was used. What happens if you change framerate to something higher? Kivy is by default at 60fps, navigate to `.kivy` folder and change it in `config.ini` file to something higher.

**Comment by DaytonaJohn** [comment]
KeyWeeUsr, you may be on to something. Just based on my own testing, it seems that when the max fps is set to 60, I get the most errors. Changing it to higher or lower values seem to decrease the error rate. A setting of about 5fps seems to eliminate the errors and triple digit settings seem to drastically reduce the error rate, but not eliminate it. Of course, these are not scientifically calculated error rates.

**Comment by dessant** [comment]
@DaytonaJohn, `Timer` executes the method in a thread, but most of kivy is not thread-safe. You could delay the call with `Clock.schedule_once`, which will run your method in the main thread. Please reopen with a new example if the bug is still present without threading. Make sure to also test on kivy master.

**Comment by DaytonaJohn** [comment]
Indeed, that fixes the code and my real app. The only mention of this that I could find in the API documentation is under kivy.clock. Perhaps this should be mentioned a bit more prominently.
