### ISSUE TITLE
DictStore incongruences

### ISSUE THREAD

**Issue by LorenzoPerticone** [kivy/kivy#4808]
I've been only using kivy in the past week, trying to learn as much as i could while trying to make things work. I'm writing this preface so that you'll understand if i failed to grasp some of the core concepts.

To be clear from the beginning: i'm not reporting a bug, but something that i don't quite understand (and seems somewhat inefficient).

I've been trying to have some kind of data persistence during executions, so i started looking at the kivy.storage.DictStore class. It seemed like its use was overly complicated in the docs, so i started digging in the source code to have an idea of how to use it. At first (my mistake) i used the "internal" methods "store_<something>", syncing manually when i thought it was needed. Then i realized my mistake and started using the "exposed" methods "<something>" (w/o the "store_" prefix). At that point, it seemed quite strange to me to be forced to pass named arguments to be saved in the file: the "store_<something>" methods work also without this, and it seems a loss of space to save something like
`{'a': 1, 'b': 2}`
in a file, in the form of
`{'a': {'a': 1}, 'b': {'b': 2}}`

More importantly, it seems quite disk/cpu intensive to write to the file on each single update to the dictionary. I'm not saying it's not a useful feature: but what if i have (say) 1000 strings in a dictionary, varying dynamically during execution? Of course i care to keep the DictStore up to date, i don't want to lose all my precious strings, but if i do so i'm writing on the underlying file on each operation. Can't i decide to sync my store instance only when needed, and keep it's underlying dictionary up-to-date at any given time? Moreover, if i have to dump a very big dictionary (the above example, but let's suppose i'm fearless and not afraid of losing data during execution time. On the other hand, i still have to save it at the end of execution) "sequentially", any entry of the dictionary will trigger a file update!

When i say i have to dump a very big dictionary "sequentially", i mean something like this:
```
myDict = {#lots of stuff
}
for key in myDict:
    store.put(myDict[key])```

I hope someone will clarify this.
Sorry for my bad english.

**Comment by udiboy1209** [comment]
The way DictStore works is that you store dicts with their names. So to store `{'a':1, 'b':2}` you will need to do 

```
store['mydict'] = {'a':1,'b':2}
# or
store.put('mydict', a=1, b=2)
```

That said, you shouldn't try to store each key as a separate dict and save the whole dict itself. The file will be written only when you decide to store the whole dict, so you can easily update the python variable sequentially and call the `put` function at the end.

What I think you are asking for is some additional features to store single variables and not dicts. If so, reword your issue as a feature request.

**Comment by LorenzoPerticone** [comment]
Now i think i get it: i was reasoning in terms of
```vars(myWidgetInstance)```
while the library is designed for storing single values, instead of the whole dictionary 'as it is'. Didn't think of storing the dictionary with
```store.put('mydict', **mydict)```, but it now seems the most direct and obvious way to do it.

I was not looking for a way to store single variables (it was actually my first instinct, but i knew python handles "contexts" as dictionaries, so i thought dicts could be "worth a shot"), but i can see why you assumed that.

Still, it seems a bit odd to store dictionaries as a dictionary of dictionaries (looks like kivy is "hiding something" from me), but now it's just a feeling. I don't think there is much more to say about this, so i'll close the issue.

Thanks @udiboy1209, you clarified exactly what I didn't get.
