### ISSUE TITLE
Add CompoundSelectionBehavior.touch_deselect_last property

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4817]
As discussed with @matham after https://github.com/kivy/kivy/pull/4782, for making both behaviors available.

**Comment by saqib1707** [comment]
@dessant  should the behaviour be like this  ?? -- when touch_deselect_last = False then whatever the value of self.multiselect and touch_multiselect are , the last selected node remaining shouldn't get deselected at any case  and when touch_deselect_last =  True then the behaviour should be normal i.e whatever it is right now.

**Comment by dessant** [comment]
@saqib1707, mostly yes, but we'll take care of adding this one.

**Comment by saqib1707** [comment]
@dessant " we'll take care of adding this one." Can I work on this or  it will be done by a kivy member ?
