### ISSUE TITLE
Twisted integration could be better

### ISSUE THREAD

**Issue by exarkun** [kivy/kivy#482]
The current support for Twisted is based on "threadedselect" which has a few shortcomings (mandatory extra thread, tied to select() and not one of the more efficient notification mechanisms, poorly maintained in Twisted).  It would be nicer if kivy integrated with the Twisted event loop in a different way.

One idea for that integration is to call kivy's "idle" method on a schedule, using Twisted's scheduling API.  For example, use `twisted.internet.task.LoopingCall` to call the idle method 60 times a second.  This avoids all of the problems I mentioned above.  The implementation is probably simpler than the current integration implementation, too.
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
