### ISSUE TITLE
Kivy Installation Instruction on OSX could be better... 

### ISSUE THREAD

**Issue by Scoodood** [kivy/kivy#4823]
Maybe it's just my problem but I hope my comment could further improve Kivy Installation Instruction on OSX for newcomers like me.

This [page](https://kivy.org/docs/installation/installation-osx.html) talks about installing Kivy on OSX, and the content is divided into 3 sections:

1. Using The Kivy.app
2. Using Homebrew with pip
3. Using MacPorts with pip

Suggestion:
1. I strongly recommend Kivy to clearly states that "Kivy can be installed in 3 different ways" at the top of the page, so that users can skip the first Method (Using The Kivy.app) since it is complicated and not mandatory. The guideline should aim to ensure that the users can quickly build their first "hello world" in no time, without having to struggle with "unnecessary" complicated installation steps.

2. The first install method "Using The Kivy.app" is quite complicated in today standard, and does not work well on SublimeText3 out of the box. I have wasted lots of time researching, trying to configure AnacondaST3's auto-completion, and the build system but it still doesn't work well. This unfortunately degrades newcomers experience and also degrades their perception about Kivy. So I highly recommend Kivy to simplify the installation steps, or perhaps create some kind of script to automate the installation procedure. Besides, having to run the kivy app with "kivy myApp.py" is less desirable than just "python myApp.py" in my humble opinion.

3. The second install method (Using Homebrew with pip) works best for me. Everything just works out of the box! Both auto-completion and the build system on my ST3 works out of the box too. I can simply build and run the Kivy app like a regular python app (i.e. "python myApp.py" instead of "kivy myApp.py"). So I don't understand why Method #2 is not the recommended install method because it's really simple and "just work".

Just my opinion.

**Comment by dessant** [comment]
@Scoodood, valid points. I think Kivy.app will have the same fate as the portable package for Windows (deprecated) when https://github.com/kivy/kivy/issues/4620 is implemented.

Kivy.app was meant to be a quick start at a time when installing the dependencies was not documented. Now installing from the official sources is described in detail, and people are also having success with homebrew.

So yes, we will likely stop shipping Python in the future 😋 , in the meantime brew installation could be moved at the top of the page, until wheels are available.
