### ISSUE TITLE
matplotlib test_backend.py Does not display x-axis and y-axis labels

### ISSUE THREAD

**Issue by luisrodriguezgonzalez** [kivy/kivy#4831]
Hello:

I have tried all the distributions of raspberry .
Does not display x-axis and y-axis labels

[https://groups.google.com/forum/embed/?place=forum%2Fkivy-users&hidesubject=true&hideforumtitle=true&showsearch=true&showpopout=true&parenturl=https%3A%2F%2Fkivy.org%2F%23&afterlogin#!topic/kivy-users/ESAtbp69zco](url)

**Comment by dessant** [comment]
@luisrodriguezgonzalez, are you having the same issue on desktop?

**Comment by luisrodriguezgonzalez** [comment]
Yes , I have the same problem. 
Thank you for your attention

**Comment by luisrodriguezgonzalez** [comment]
In all distributions raspberry

**Comment by dessant** [comment]
I'm asking if it happens on a desktop pc, something other than a raspberry.

**Comment by dessant** [comment]
It also looks like this is not a kivy issue but a bug in garden.matplotlib. You're testing with mpl 2.0.0rc1, but the code was written when mpl 1.5 was released, so it may be caused by a difference between mpl versions.

**Comment by luisrodriguezgonzalez** [comment]
Hello:
This does not happen on windows 8.1


2016-12-20 11:40 GMT-03:00 dessant <notifications@github.com>:

**Comment by dessant** [comment]
@luisrodriguezgonzalez, could you share a log both for the windows and rpi test, when you run test_backend.py?

**Comment by luisrodriguezgonzalez** [comment]
result raspberry , all distributions

2016-12-20 12:14 GMT-03:00 Luis Rodriguez <tonifla1@gmail.com>:

**Comment by luisrodriguezgonzalez** [comment]
log windows 8.1
C:\Python27\python.exe
C:/Users/Luis/PycharmProjects/kv/garden.matplotlib-master/examples/test_backend.py
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.8 (default, Jun 30 2014, 16:08:48)
[MSC v.1500 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif,
img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.2.0 - Build
10.18.10.3308>
[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics
4600>
[INFO              ] [GL          ] OpenGL parsed version: 4, 2
[INFO              ] [GL          ] Shading version <4.20 - Build
10.18.10.3308>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single
mode, not docked
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Start application main loop
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x000000000A3D5208>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x000000000A519FD0>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x000000000A636E80>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x000000000A5BBBE0>)
('mouse move to ', 0.0, 4.0)
figure enter mpl
('mouse move to ', 0.0, 6.0)


2016-12-20 12:15 GMT-03:00 Luis Rodriguez <tonifla1@gmail.com>:

**Comment by luisrodriguezgonzalez** [comment]
log raspberry

pi@raspberrypi:~/garden.matplotlib/examples $ python test_backend.py
[INFO   ] [Logger      ] Record log in
/home/pi/.kivy/logs/kivy_16-12-20_17.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2,
img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "test_backend.py", line 140, in <module>
     MatplotlibTest().run()
   File "/home/pi/kivy/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/pi/kivy/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 90, in
mainloop
     self._mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 85, in
_mainloop
     EventLoop.idle()
   File "/home/pi/kivy/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/home/pi/kivy/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 368, in
kivy._clock.CyClockBase._process_events (kivy/_clock.c:7450)
   File "kivy/_clock.pyx", line 398, in
kivy._clock.CyClockBase._process_events (kivy/_clock.c:7325)
   File "kivy/_clock.pyx", line 396, in
kivy._clock.CyClockBase._process_events (kivy/_clock.c:7247)
   File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick
(kivy/_clock.c:3251)
   File "/home/pi/kivy/kivy/uix/boxlayout.py", line 311, in do_layout
     c.size = (w, h)
   File "kivy/properties.pyx", line 423, in
kivy.properties.Property.__set__ (kivy/properties.c:5171)
   File "kivy/properties.pyx", line 1295, in
kivy.properties.ReferenceListProperty.set (kivy/properties.c:20625)
   File "kivy/properties.pyx", line 516, in
kivy.properties.Property.dispatch (kivy/properties.c:6614)
   File "kivy/_event.pyx", line 1225, in
kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
   File "kivy/_event.pyx", line 1131, in
kivy._event.EventObservers._dispatch (kivy/_event.c:12723)
   File
"/home/pi/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py",
line 1179, in _on_size_changed
     self.figure.set_size_inches(winch, hinch)
   File
"/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc1_2670.gbf5aeb5-py2.7-linux-armv7l.egg/matplotlib/figure.py",
line 720, in set_size_inches
     manager.resize(int(canvasw), int(canvash))
   File
"/home/pi/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py",
line 1247, in resize
     Window.size(w, h)
 TypeError: 'tuple' object is not callable







*Modify the file line 1247    def resize(self, w, h):
#Window.size(w, h)        pass*



result :

pi@raspberrypi:~/garden.matplotlib/examples $ python test_backend.py
[INFO   ] [Logger      ] Record log in
/home/pi/.kivy/logs/kivy_16-12-20_19.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2,
img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x711b3750>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x711b3950>)






2016-12-20 12:17 GMT-03:00 Luis Rodriguez <tonifla1@gmail.com>:

**Comment by dessant** [comment]
@luisrodriguezgonzalez, that for the logs, but these are different kivy versions. Please check if the bug is present with kivy 1.9.1 on rpi, and share a log. Or do the opposite and test kivy master on windows.

**Comment by luisrodriguezgonzalez** [comment]
Hello:
I have installed version  kivy 1.9.1. in rpi.
1.- log


pi@raspberrypi:~/garden.matplotlib/examples $ python test_backend.py
[INFO   ] [Logger      ] Record log in
/home/pi/.kivy/logs/kivy_16-12-20_15.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2,
img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "test_backend.py", line 139, in <module>
     MatplotlibTest().run()
   File "/home/pi/kivy-1.9.1/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/pi/kivy-1.9.1/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/pi/kivy-1.9.1/kivy/core/window/window_egl_rpi.py", line 89,
in mainloop
     self._mainloop()
   File "/home/pi/kivy-1.9.1/kivy/core/window/window_egl_rpi.py", line 84,
in _mainloop
     EventLoop.idle()
   File "/home/pi/kivy-1.9.1/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/home/pi/kivy-1.9.1/kivy/clock.py", line 515, in tick
     self._process_events()
   File "/home/pi/kivy-1.9.1/kivy/clock.py", line 647, in _process_events
     event.tick(self._last_tick, remove)
   File "/home/pi/kivy-1.9.1/kivy/clock.py", line 406, in tick
     ret = callback(self._dt)
   File "/home/pi/kivy-1.9.1/kivy/uix/boxlayout.py", line 206, in do_layout
     c.width = w
   File "kivy/properties.pyx", line 408, in
kivy.properties.Property.__set__ (kivy/properties.c:5515)
   File "kivy/properties.pyx", line 446, in kivy.properties.Property.set
(kivy/properties.c:6348)
   File "kivy/properties.pyx", line 501, in
kivy.properties.Property.dispatch (kivy/properties.c:7048)
   File "kivy/_event.pyx", line 1224, in
kivy._event.EventObservers.dispatch (kivy/_event.c:14008)
   File "kivy/_event.pyx", line 1130, in
kivy._event.EventObservers._dispatch (kivy/_event.c:13191)
   File "kivy/properties.pyx", line 1215, in
kivy.properties.ReferenceListProperty.trigger_change
(kivy/properties.c:20263)
   File "kivy/properties.pyx", line 1230, in
kivy.properties.ReferenceListProperty.trigger_change
(kivy/properties.c:20156)
   File "kivy/properties.pyx", line 501, in
kivy.properties.Property.dispatch (kivy/properties.c:7048)
   File "kivy/_event.pyx", line 1224, in
kivy._event.EventObservers.dispatch (kivy/_event.c:14008)
   File "kivy/_event.pyx", line 1130, in
kivy._event.EventObservers._dispatch (kivy/_event.c:13166)
   File
"/home/pi/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py",
line 1179, in _on_size_changed
     self.figure.set_size_inches(winch, hinch)
   File
"/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc2_2771.g58a8334-py2.7-linux-armv7l.egg/matplotlib/figure.py",
line 720, in set_size_inches
     manager.resize(int(canvasw), int(canvash))
   File
"/home/pi/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py",
line 1247, in resize
     Window.size(w, h)
 TypeError: 'tuple' object is not callable








*Modify the file line 1247    def resize(self, w, h):
#Window.size(w, h)        pass*



result :

pi@raspberrypi:~/garden.matplotlib/examples $ python test_backend.py
[INFO   ] [Logger      ] Record log in
/home/pi/.kivy/logs/kivy_16-12-20_16.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2,
img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x711e6470>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x71180730>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x711e6510>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x711d2fd0>)



2016-12-20 12:40 GMT-03:00 dessant <notifications@github.com>:

**Comment by dessant** [comment]
Thanks for the logs. I don't know if this is a kivy, mpl, or garden.matplotlib bug, we will have to wait for a contributor with an rpi to further debug. In the meantime you could do one last test 😁 and check if the labels are displayed or not with mpl 1.5.3 and kivy 1.9.1 on the rpi, no logs are required in this case.

**Comment by luisrodriguezgonzalez** [comment]
hi :
I need to try but in URL :
https://sourceforge.net/projects/matplotlib/files/matplotlib/
does not exist version 1.5.3

can you help me with this?



2016-12-20 19:06 GMT-03:00 dessant <notifications@github.com>:

**Comment by dessant** [comment]
```
pip install matplotlib==1.5.3
```

They have moved to github btw: https://github.com/matplotlib/matplotlib.

**Comment by luisrodriguezgonzalez** [comment]
pi@raspberrypi:~/garden.matplotlib/examples $ python test_backend.py
[INFO   ] [Logger      ] Record log in
/home/pi/.kivy/logs/kivy_16-12-21_22.txt
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2,
img_pil (img_ffpyplayer ignored)
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Base        ] Adding binding for mouse move
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x7137cd30>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x71408e70>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x71298250>)
('resize from mpl ', <matplotlib.backend_bases.ResizeEvent object at
0x71298690>)




Works thank you very much


2016-12-21 10:11 GMT-03:00 dessant <notifications@github.com>:

**Comment by dessant** [comment]
You're welcome. Please open an issue for mpl 2.0 at https://github.com/kivy-garden/garden.matplotlib.

Some parts will have to be updated for the upcoming matplotlib release.

**Comment by luisrodriguezgonzalez** [comment]
closed.
https://github.com/kivy-garden/garden.matplotlib/issues/45


2016-12-21 14:00 GMT-03:00 dessant <notifications@github.com>:
