### ISSUE TITLE
Kivy is broken on recent master

### ISSUE THREAD

**Issue by germn** [kivy/kivy#4832]
`kivy==master` is broken when we try to build it for android.
Problem appeared recently, probably after [this commit](https://github.com/kivy/kivy/commit/08f5273bcff3e36c7eb7327a0be70c7ad6283cf3#diff-874717abbc54b331b987a6ad0b177c4d).

```
  RAN: '/usr/local/bin/cython ./kivy/properties.pyx'

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
           'NumericProperty', 'StringProperty', 'ListProperty',
           'ObjectProperty', 'BooleanProperty', 'BoundedNumericProperty',
           'OptionProperty', 'ReferenceListProperty', 'AliasProperty',
           'DictProperty', 'VariableListProperty', 'ConfigParserProperty')

include "config.pxi"
^
------------------------------------------------------------

kivy/properties.pyx:217:0: 'config.pxi' not found

```

**Comment by matham** [comment]
Try master again. It may have been fixed.

**Comment by germn** [comment]
Sorry, but still same error.

**Comment by matham** [comment]
Ok, that needs to be fixed in the py4a side then. It may have assumed something about where the file is. And that has changed since it was moved to `kivy/include`. Although, I thought adding that path to the include directories in setup.py would fix it, but I guess that's not enough.

Someone familiar with android compilation should take a look.

**Comment by KavenC** [comment]
I think it could be a problem relate to p4a CythonRecipe. Since it manually run cython process rather than triggered from setup.py.

**Comment by inclement** [comment]
I've changed p4a to use Kivy 1.9.1 for now (this should probably be the case anyway, so I don't intend to change it back to master). I couldn't fix it immediately though, will take another look soon.

**Comment by dessant** [comment]
This issue was moved to kivy/python-for-android#970
