### ISSUE TITLE
`buildozer android_new debug` fails with `AttributeError: 'Context' object has no attribute 'hostpython'`

### ISSUE THREAD

**Issue by ronbarak** [kivy/kivy#4848]
I used `buildozer android_new debug` and it gives me `AttributeError: 'Context' object has no attribute 'hostpython'` (full output at bottom).<br>

Is this something I can fix myself?
---

I use buildozer on Python 2.7.12 on Ubuntu 16.04 64 bits in VirtualBox 5.1.10 (hosted on Windows 7 64 bits)

    openstack@ubuntu1604:~/python/kivy$ buildozer android_new debug
    # Check configuration tokens
    # Ensure build layout
    # Check configuration tokens
    # Preparing build
    # Check requirements for android
    # Run 'dpkg --version'
    # Cwd None
    Debian 'dpkg' package management program version 1.18.4 (amd64).
    This is free software; see the GNU General Public License version 2 or
    later for copying conditions. There is NO warranty.
    # Search for Git (git)
    #  -> found at /usr/bin/git
    # Search for Cython (cython)
    #  -> found at /usr/local/bin/cython
    # Search for Java compiler (javac)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
    # Search for Java keytool (keytool)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
    # Install platform
    # Apache ANT found at /home/openstack/.buildozer/android/platform/apache-ant-1.9.4
    # Android SDK found at /home/openstack/.buildozer/android/platform/android-sdk-20
    # Android NDK found at /home/openstack/.buildozer/android/platform/android-ndk-r9c
    # Check application requirements
    # Check garden requirements
    # Compile platform
    # Run 'python -m pythonforandroid.toolchain create --dist_name=kivytest --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/openstack/python/kivy/.buildozer/android/platform/build'
    # Cwd /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Will compile for the following archs: armeabi-v7a
    [INFO]:    Found Android API target in $ANDROIDAPI
    [INFO]:    Available Android APIs are (19)
    [INFO]:    Requested API target 19 is available, continuing.
    [INFO]:    Found NDK dir in $ANDROIDNDK
    [INFO]:    Got NDK version from $ANDROIDNDKVER
    [INFO]:    Using Google NDK r9c
    [INFO]:    Found virtualenv at /usr/local/bin/virtualenv
    [INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
    [INFO]:    Picking the latest gcc toolchain, here 4.8
    [WARNING]: Missing executable: autoconf is not installed
    [WARNING]: Missing executable: automake is not installed
    [WARNING]: Missing executable: libtoolize is not installed
    [INFO]:    No existing dists meet the given requirements!
    [INFO]:    No dist exists that meets your requirements, so one will be built.
    [INFO]:    Bootstrap requires recipes ['sdl2', ('python2', 'python3crystax')]
    [INFO]:    Loaded recipe sdl2 (depends on [('python2', 'python3crystax'), 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf'], conflicts ['sdl', 'pygame', 'pygame_bootstrap_components'])
    [INFO]:    Loaded recipe kivy (depends on ['pyjnius', ('sdl2', 'pygame'), ('python2', 'python3crystax')])
    [INFO]:    Loaded recipe sdl2_image (depends on [])
    [INFO]:    Loaded recipe sdl2_mixer (depends on [])
    [INFO]:    Loaded recipe sdl2_ttf (depends on [])
    [INFO]:    Loaded recipe pyjnius (depends on ['six', ('sdl2', 'sdl', 'genericndkbuild'), ('python2', 'python3crystax')])
    [INFO]:    Loaded recipe six (depends on [('python2', 'python3crystax')])
    [INFO]:    Found multiple valid recipe sets:
    [INFO]:        ['six', 'sdl2', u'kivy', 'sdl2_ttf', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
    [INFO]:        ['sdl2', 'six', 'sdl2_ttf', 'python3crystax', 'sdl2_mixer', 'sdl2_image', 'pyjnius', u'kivy']
    [INFO]:    Using the first of these: ['six', 'sdl2', u'kivy', 'sdl2_ttf', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
    [INFO]:    The selected bootstrap is sdl2
    [INFO]:    # Creating dist with sdl2 bootstrap
    [INFO]:    Dist will have name kivytest and recipes (kivy)
    [INFO]:    -> running cp -r /home/openstack/python/k...(and 194 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Recipe build order is ['python2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sdl2', 'six', 'pyjnius', u'kivy']
    [INFO]:    # Downloading recipes 
    [INFO]:    Downloading python2
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 57 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/python2
    [INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
    [INFO]:    python2 download already cached, skipping
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Downloading sdl2_image
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 60 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/sdl2_image
    [INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
    [INFO]:    sdl2_image download already cached, skipping
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Downloading sdl2_mixer
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 60 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/sdl2_mixer
    [INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
    [INFO]:    sdl2_mixer download already cached, skipping
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Downloading sdl2_ttf
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 58 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/sdl2_ttf
    [INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
    [INFO]:    sdl2_ttf download already cached, skipping
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Downloading sdl2
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 54 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/sdl2
    [INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Downloading six
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 53 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/six
    [INFO]:    -> running basename https://pypi.python.or...(and 40 more)
    [INFO]:    six download already cached, skipping
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Downloading pyjnius
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 57 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/pyjnius
    [INFO]:    -> running basename https://github.com/kiv...(and 28 more)
         [INFO]:    pyjnius download already cached, skipping                      
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Downloading kivy
    [INFO]:    -> running mkdir -p /home/openstack/pytho...(and 54 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/packages/kivy
    [INFO]:    -> running basename https://github.com/kiv...(and 25 more)
    [INFO]:    kivy download already cached, skipping
    [WARNING]: Should check headers here! Skipping for now.
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    # Building all recipes for arch armeabi-v7a
    [INFO]:    # Unpacking recipes
    [INFO]:    Unpacking python2 for armeabi-v7a
    [INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a
    [INFO]:    python2 is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Unpacking sdl2_image for armeabi-v7a
    [INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
    [INFO]:    sdl2_image is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Unpacking sdl2_mixer for armeabi-v7a
    [INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
    [INFO]:    sdl2_mixer is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Unpacking sdl2_ttf for armeabi-v7a
    [INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
    [INFO]:    sdl2_ttf is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Unpacking sdl2 for armeabi-v7a
    [INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
               work[INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
    [INFO]:    sdl2 is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Unpacking six for armeabi-v7a
    [INFO]:    -> running basename https://pypi.python.or...(and 40 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/other_builds/six-python2/armeabi-v7a
    [INFO]:    six is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Unpacking pyjnius for armeabi-v7a
    [INFO]:    -> running basename https://github.com/kiv...(and 28 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a
    [INFO]:    pyjnius is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    Unpacking kivy for armeabi-v7a
    [INFO]:    -> running basename https://github.com/kiv...(and 25 more)
    [INFO]:    -> directory context /home/openstack/python/kivy/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/armeabi-v7a
    [INFO]:    kivy is already unpacked, skipping
    [INFO]:    <- directory context /home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master
    [INFO]:    # Prebuilding recipes
    [INFO]:    Prebuilding python2 for armeabi-v7a
    [INFO]:    python2 has no prebuild_armeabi_v7a, skipping
    [INFO]:    Applying patches for python2[armeabi-v7a]
    [INFO]:    python2 already patched, skipping
    [INFO]:    Prebuilding sdl2_image for armeabi-v7a
    [INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
    [INFO]:    Applying patches for sdl2_image[armeabi-v7a]
    [INFO]:    sdl2_image already patched, skipping
    [INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
    [INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
    [INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
    [INFO]:    sdl2_mixer already patched, skipping
    [INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
    [INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
    [INFO]:    Prebuilding sdl2 for armeabi-v7a
    [INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
    [INFO]:    Applying patches for sdl2[armeabi-v7a]
    [INFO]:    sdl2 already patched, skipping
    [INFO]:    Prebuilding six for armeabi-v7a
    [INFO]:    six has no prebuild_armeabi_v7a, skipping
    [INFO]:    Prebuilding pyjnius for armeabi-v7a
    [INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
    [INFO]:    Applying patches for pyjnius[armeabi-v7a]
    [INFO]:    pyjnius already patched, skipping
    [INFO]:    Prebuilding kivy for armeabi-v7a
    [INFO]:    kivy has no prebuild_armeabi_v7a, skipping
    [INFO]:    # Building recipes
    [INFO]:    Building python2 for armeabi-v7a
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 842, in <module>
        main()
      File "/home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 839, in main
        ToolchainCL()
      File "/home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 489, in __init__
        getattr(self, args.subparser_name.replace('-', '_'))(args)
      File "/home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
        build_dist_from_args(ctx, dist, args)
      File "/home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
        build_recipes(build_order, python_modules, ctx)
      File "pythonforandroid/build.py", line 562, in build_recipes
        recipe.build_arch(arch)
      File "/home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 44, in build_arch
        self.do_python_build(arch)
      File "/home/openstack/python/kivy/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 73, in do_python_build
        shprint(sh.cp, self.ctx.hostpython, self.get_build_dir(arch.arch))
    AttributeError: 'Context' object has no attribute 'hostpython'
    # Command failed: python -m pythonforandroid.toolchain create --dist_name=kivytest --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/openstack/python/kivy/.buildozer/android/platform/build
    # 
    # Buildozer failed to execute the last command
    # The error might be hidden in the log above this error
    # Please read the full log, and search for it before
    # raising an issue with buildozer itself.
    # In case of a bug report, please add a full log with log_level = 2
    openstack@ubuntu1604:~/python/kivy$

**Comment by dessant** [comment]
This may fix it for you https://github.com/kivy/python-for-android/issues/620#issuecomment-186167468.
If the issue persists, please open a bug report at the p4a repo with log_level = 2.
