### ISSUE TITLE
'make build' does not skip unchanged modules

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4849]
It must be a recent change, seen with master on Windows.

**Comment by udiboy1209** [comment]
Confirmed on ubuntu 16. Must be the new changes to `setup.py` in commit [1931d18](https://github.com/kivy/kivy/commit/1931d18a8b84c9ea857897eb9e7312c0b0da8298) .

**Comment by tito** [comment]
This is due to whoever changed the pyx location from graphics to include, didn't changed the dependencies solver in setup.py to look into the new directory.
