### ISSUE TITLE
seek() broken for audio_gstplayer.py

### ISSUE THREAD

**Issue by FeralBytes** [kivy/kivy#4852]
seek() for SoundLoader using gstplayer and possibly others; definitely SDL2 is broken in both Kivy 1.9.1 and Kivy 1.9.2 and I have notes that suggest it was also broken in Kivy 1.8.

The example below demonstrates the issue; simply copy the code below into a new "example.py" file (python3). and run the code as $ python3 example.py path/to/music_file.m4a
```python
import argparse
import os.path
import sys
import time
import kivy.core.audio

parser = argparse.ArgumentParser()
parser.add_argument('file_path')
args = parser.parse_args(sys.argv[1:])

if os.path.isfile(args.file_path):
    from kivy.core.audio.audio_gstplayer import SoundGstplayer
    kivy.core.audio.SoundLoader.register(SoundGstplayer)
    current_song = kivy.core.audio.SoundLoader.load(args.file_path)
    current_song.play()
    time.sleep(10)
    saved_seek_position = current_song.get_pos()
    current_song.stop()
    time.sleep(1)
    print('Expecting the position to be 0 because the song was stopped.',
        current_song.get_pos())
    current_song.seek(saved_seek_position)
    print('Expecting the position to be 10+ because we seeked the song.',
        current_song.get_pos())
    current_song.play()
    time.sleep(10)
```
Tested file types: '.ogg', '.mp3', '.m4a', '.mp4'*
* I modified kivy to accept '.mp4' because some programs do not use the '.m4a' extension for audio only well using mpeg4.

**Comment by Bakterija** [comment]
This seems to be an issue only when using SoundGstplayer with Multiprocess and/or Subprocess modules

**Comment by FeralBytes** [comment]
OK; but why; it still plays and stops fine; just not able to seek?

**Comment by FeralBytes** [comment]
Also this is a standalone example; no multiprocessing or subprocess so that does not explain the problem here and shows that it must be further reaching than you think; give the script a try; it does not seek; even though no multiprocessing or subprocess.

**Comment by AndiEcker** [comment]
The skip bug happens to me too with the script provided by @FeralBytes on
my windows machine with the current kivy 1.9.2 Python 2.7 nightly wheels
build.

This is the console output (although displaying the 4 Gstreamer-WARNINGS,
the song is playing fine, and the last line should show a value of 10 or
more instead of 0):

```
[INFO   ] [Logger      ] Record log in
C:\Users\aecker.ACUMEN\.kivy\logs\kivy_16-12-29_93.txt
[INFO   ] [Kivy        ] v1.9.2-dev0.28122016.28d9e07
[INFO   ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015,
20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO   ] [AudioGstplayer] Using Gstreamer 1.4.5.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2
(audio_ffpyplayer ignored)

(python.exe:5104): GStreamer-WARNING **: Failed to load plugin
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libgnutlsxx-28.dll':
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libgnutlsxx-28.dll': The
specified procedure could not be found.

(python.exe:5104): GStreamer-WARNING **: Failed to load plugin
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libgsttaglib.dll':
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libgsttaglib.dll': The
specified procedure could not be found.

(python.exe:5104): GStreamer-WARNING **: Failed to load plugin
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libtag.dll':
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libtag.dll': The specified
procedure could not be found.

(python.exe:5104): GStreamer-WARNING **: Failed to load plugin
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libtag_c.dll':
'C:\virtualenvs\kivy-dev\share\gstreamer\bin\libtag_c.dll': The specified
procedure could not be found.
('Expecting the position to be 0 because the song was stopped.', 0.0)
('Expecting the position to be 10+ because we seeked the song.', *0.0*)
```


2016-12-29 15:41 GMT+00:00 FeralBytes <notifications@github.com>:

**Comment by FeralBytes** [comment]
OK I figured it out; the player will not seek when the audio is stopped. Because in kivy/lib/gstplayer/_gstplayer.pyx in the seek functions a state check is performed and the only states that are allowed are Paused (which is odd since pausing is not implemented) and or Playing. Thus a state of Stopped would not be allowed.
GST_PLAYER_STATE_STOPPED would need to be added to the ctypedef on line 22 as GST_STATE_STOPPED
Then we would need to add this as a possible state to check for during cdef gint64 _get_duration because the problem is that the duration is being returned as 0 if the song is stopped.
I will be working a Pull Request; but I would expect it to be slow as I do not know Cython and will probably make a mistake or 2. There are also several notes about being prerolled so this may be a limitation or something i will have to figure out how to avoid.

**Comment by FeralBytes** [comment]
Updated example code to show that seek does work if the song is playing.
```python 
import argparse
import os.path
import sys
import time
import kivy.core.audio

parser = argparse.ArgumentParser()
parser.add_argument('file_path')
args = parser.parse_args(sys.argv[1:])

if os.path.isfile(args.file_path):
    from kivy.core.audio.audio_gstplayer import SoundGstplayer
    kivy.core.audio.SoundLoader.register(SoundGstplayer)
    current_song = kivy.core.audio.SoundLoader.load(args.file_path)
    current_song.play()
    time.sleep(10)
    saved_seek_position = current_song.get_pos()
    current_song.stop()
    time.sleep(1)
    print('Expecting the position to be 0 because the song was stopped.',
        current_song.get_pos())
    print('Attempting seek now.')
    current_song.seek(saved_seek_position)
    print('Expecting the position to be 10+ because we seeked the song.',
        current_song.get_pos())
    current_song.play()
    print('Attempting to seek during play.')
    current_song.seek(saved_seek_position)
    time.sleep(0.1)  # We have to pause to make sure that we get the correct updated position back.
    print('Expecting the position to be 10+ because we seeked the song during playback.',
        current_song.get_pos())
    time.sleep(10)
```

**Comment by FeralBytes** [comment]
There is no way to seek when the song has been stopped (GST_STATE_STOPPED does not exist only a paused state); so either we expose a pause option which needs approval from Kivy devs or we raise an error when seek is called and the song is stopped to at least let future users know why it is not working. And of course a documentation update will be in order. 
Kivy Devs please let me know which way you would like to go?
@inclement @dessant @matham @tito @tshirtman etc.

**Comment by FeralBytes** [comment]
I still would like to raise an error; to prevent users from doing this; but I feel that is probably the part that is holding up the kivy-dev team from making a decision about the way forward. So at least the documentation will be right going forward.
