### ISSUE TITLE
Code error in kv lang documentation - re-using styles in multiple widgets

### ISSUE THREAD

**Issue by kn2322** [kivy/kivy#4856]
In this [section](https://kivy.org/docs/guide/lang.html#re-using-styles-in-multiple-widgets) about reusing widget styles in kv lang, should the 'on_press: self.text(txt_input.text)' in both 'MyFirstWidget' and 'MySecondWidget' be '**root**.text(txt_input.text)', or '**self.parent**.text'?

**Comment by KeyWeeUsr** [comment]
Thanks, it should be `root`. Fixed https://github.com/kivy/kivy/commit/5b5129a92166dbd4dda55b2ac87bce9bb3d60535
