### ISSUE TITLE
kivy matplotlib test_backend.py and test_plt.py display error and exit error

### ISSUE THREAD

**Issue by sem376** [kivy/kivy#4860]
Hello,
I'm using the following:
Windows 8 and Windows 10
IDE: Pycharm latest version
Python: version 3.4.4
Kivy: version 1.9.1
Matplotlib: version 1.5.3
Numpy: lastest version
Downloaded Matplotlib for kivy

When I test the test_backend.py code located here https://github.com/kivy-garden/garden.matplotlib/tree/master/examples, the code starts up, but the display isn't exactly how it suppose to look. Here attached is my display
![error_graphs](https://cloud.githubusercontent.com/assets/22777807/21572985/95952492-cead-11e6-8352-04b57ce07292.JPG), and these two locations show similar graphs (graphs like test_plt.py. test_plt.py give the same errors) : http://matplotlib.org/examples/api/barchart_demo.html and https://andnovar.wordpress.com/2015/06/11/backend-for-kivy-in-matplotlib-first-steps/ 

Also, when I close the graph window, I get this error message:

[INFO              ] [Base        ] Leaving application in progress...

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Finally, when I run test_backend.py, I get errors in this line:
from kivy.garden.matplotlib.backend_kivyagg import FigureCanvas,\
                                                NavigationToolbar2Kivy
which says there are unresolved references for backend_kivyagg, FigureCanvas, NavigationToolbar2Kivy

Does anyone understand why errors are occurring? 

Thanks

**Comment by dessant** [comment]
Please reopen the issue at https://github.com/kivy-garden/garden.matplotlib.
