### ISSUE TITLE
Possible bug in actionview at maximize/minimize window

### ISSUE THREAD

**Issue by aerogelio** [kivy/kivy#4867]
I am adding and deleting ActionButtons to an ActionView  programmatically using add_widget and remove_widget functions, but at some point when I maximize or minimize the window, all ActionButtons removed are added again. If I do not maximize or minimize the window all work fine.

I was checking the ActionView code and found that it overwrites add_widget for stores the views on property _list_action_items but I did not find where to remove them from _list_action_items.

It appears that when removing a child with remove_widget( child ) and also with _list_action_item.remove( child ) the problem is solved, but I'm not sure and I do not like to get involved with the property directly.

**Comment by KeyWeeUsr** [comment]
I think the widget worked normally before. A reproducible example would be really nice btw :)

**Comment by aerogelio** [comment]
Here:
https://github.com/aerogelio/avposbug

I try:
1.- Add five widgets
2.- Remove five widgets
3.- Add five widgets
4.- Remove five widgets
5.- Maximize
6.- Minimize
7.- The effect should be visible.

If anything else happens tell me, for upload images and videos.

**Comment by KeyWeeUsr** [comment]
It's somehow bound to the width of widget/window, probably triggered when the amount of visible widgets is recalculated. It's probably only the list issue.
