### ISSUE TITLE
kivy-examples widgets asyncimage.py crashes

### ISSUE THREAD

**Issue by oaltun** [kivy/kivy#4871]
I just did an install on Windows. kivy-examples/widgets/asyncimage.py crashes because http://kivy.org/funny-pictures-cat-is-expecting-you.jpg is not there anymore...

**Comment by KeyWeeUsr** [comment]
<img src="http://www.aztemplates.org/wp-content/uploads/2012/12/Missing-Pet-Poster-Template.jpg" height=300></img> @dessant she ran away again. Do we have any spare? 😄

**Comment by oaltun** [comment]
:)

**Comment by KeyWeeUsr** [comment]
Basically, you can put there any url you want and it should be able to fetch the content. But yeah, the file somehow disappeared. Is the rest of them in tact?

**Comment by oaltun** [comment]
I am aware that you can put any image there. I reported still. It should be fixed is it not? E.g. a new address must be there.

**Comment by KeyWeeUsr** [comment]
Of course, I just mentioned it if it wasn't obvious or something. The issue is fine :)

**Comment by dessant** [comment]
@KeyWeeUsr, you may get a new litter from @matham.
