### ISSUE TITLE
Broken / not implemented multiple joystick support?

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4872]
I'm not really sure what's hapenning here mainly because I get different `stickid` if I have multiple joysticks, yet the only input I get is from _the last one plugged in_ into my machine. I've tested with vJoy and one real device, yet either I get only the real device after vJoy + real, or I get only the vJoy input after read + vJoy.

I tried to find something more about it, yet the only thing I found was about [linux](http://stackoverflow.com/q/29589982/5994041) and I have Windows.

I tried to fix that according to the SDL documentation with an obvious fix (`SDL_NumJoysticks()` needs to be included in `kivy/lib/sdl2.pxi`):

    cdef int joy_i
    for joy_i in range(SDL_NumJoysticks()):
        SDL_JoystickOpen(joy_i)

but still nothing. Am I doing something wrong?

> with xinput xbox-like usb logitech pad Local multiplayer works great in boardz.

Any ideas @chozabu ?

ref #2564

**Comment by FeralBytes** [comment]
@KeyWeeUsr I have a strong interest in getting controller support but for Steam Controllers; do you need help with the multiple controller issues? I just helped out Muppen64 with some controller debugging; so it is still fresh in my mind.

**Comment by KeyWeeUsr** [comment]
Well, I know about these [mappings](https://github.com/gabomdq/SDL_GameControllerDB), so basically if SDL recieves the input from the controller, it's only about the correct mapping.

Then again, according to snippets for multiple controllers I thought it's Just Work(TM), but as already mentioned, it opens only the last plugged in joystick. If you have any experience related to using multiple joysticks, advices welcome. 🐧

**Comment by yglazner** [comment]
I'm also in need for multi-gampad support, any progress on the issue?

**Comment by dessant** [comment]
@yglazner, please use the reaction buttons if you'd like to vote up an issue in the future, these comments do not add anything to the discussion, and all subscribers get notified.

**Comment by KeyWeeUsr** [comment]
@yglazner According to a small talk I had on their IRC (freenode#SDL) it should work. Suggested approach was with [`SDL_JoyDeviceEvent`](https://wiki.libsdl.org/SDL_JoyDeviceEvent) but that kind of doesn't work for me and still only a single device is usable. Maybe it's just me though, I have only a single **physical** device. If you have 2+, feel free to test and share your experience. It's better than nothing.

Unless there is some usable example for multiple devices handling, this is just a blind stabbing. Especially with search results like [this](http://stackoverflow.com/q/38087203/5994041), where you can find `// Break after first available joystick`, which is just... extremely helpful...

Our best guess is to take SDL2 unit tests and get the behavior out of it, if it's even there, such as in [testjoystick.c](http://hg.libsdl.org/SDL/file/494d0f56ae7a/test/testjoystick.c) and [SDL_test_common.c](https://hg.libsdl.org/SDL/file/494d0f56ae7a/src/test/SDL_test_common.c#l1117). I wonder what I do differently, as the same code as presented above is [here](http://hg.libsdl.org/SDL/file/494d0f56ae7a/test/testjoystick.c#l262) and apparently it works. Or someone plays with plugging & unplugging everytime the test is run (unlikely).

**Comment by yglazner** [comment]
Right now I'm using the following hack to workaround the issue
```
import kivy #...
del sys.modules['sdl2']
from sdl2 import joystick
for joy_i in range(joystick.SDL_NumJoysticks()):
    joystick.SDL_JoystickOpen(joy_i)
```

**Comment by KeyWeeUsr** [comment]
That's basically the code above. Is it PySDL or something?

**Comment by yglazner** [comment]
It's PySDL.

**Comment by KeyWeeUsr** [comment]
Does it work with 2+ devices (do you get values from both of them)?

**Comment by yglazner** [comment]
@KeyWeeUsr - Tested with 2 gamepads. I will test it with 5 next week
