### ISSUE TITLE
Pong example in Android crashing on launch

### ISSUE THREAD

**Issue by jeffersonheard** [kivy/kivy#4880]
* Device: Nexus 6P, unmodified.
* Build System: OS X El Capitan
* Default install of kivy and buildozer installed fresh today according to https://kivy.org/docs/guide/packaging-android.html

It works great on the OS x command line, but packaging for Android fails. I literally just tried packaging the most basic example using buildozer. I get the following from `$buildozer android logcat`:

https://gist.github.com/jeffersonheard/c6bd26f8fea1d1b36064c2c564d06975

The most suspicious lines to me are these:

```
01-03 23:38:08.076 14183 14199 E AndroidRuntime: FATAL EXCEPTION: Thread-2
01-03 23:38:08.076 14183 14199 E AndroidRuntime: Process: org.test.myapp:python, PID: 14183
01-03 23:38:08.076 14183 14199 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Py_asinh" referenced by "/data/app/org.test.myapp-1/lib/arm/libpython2.7.so"...
01-03 23:38:08.076 14183 14199 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
01-03 23:38:08.076 14183 14199 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)
01-03 23:38:08.076 14183 14199 E AndroidRuntime: 	at org.renpy.android.PythonActivity.run(PythonActivity.java:254)
01-03 23:38:08.076 14183 14199 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

They are in fact the only errors listed.

**Comment by jeffersonheard** [comment]
Seems to work with `android_new`. Perhaps I should just use that from now on... Is there any disadvantage to android_new?

**Comment by FeralBytes** [comment]
So you say that android_new worked but "buildozer android debug deploy run" is what failed for you?

**Comment by jeffersonheard** [comment]
@FeralBytes Correct.

**Comment by FeralBytes** [comment]
The disadvantages for the new_android build depends on your use case. But there are also several advantages. So give it a try with your application and let us know if you encounter issues.

**Comment by dessant** [comment]
The old toolchain isn't practically supported anymore, an announcement will follow in the near future.
