### ISSUE TITLE
Binding function with arguments 

### ISSUE THREAD

**Issue by cocodevienne** [kivy/kivy#4881]
Ok guys, this is no issue, but more of a question. I have this code here(https://github.com/cocodevienne/curl2android). So far so good, I managed to make a somewhat repsonsive UI, its very primitve though. Now I have one question.  What do I have to add to my code in order to call the download function and pass  "self.url" and "self.fname" to it? This has been confusing me thoroughly and I would be very happy if anyone here could resolve this for me. Thanks in advance!

**Comment by cocodevienne** [comment]
P.S: so that the download function is executed with the press of the button taking in the args described above.

**Comment by KeyWeeUsr** [comment]
GitHub issues are for reporting bugs. Please use one of the appropriate channels for such questions. It's also a lot faster in a large scale.

* https://kivy.org/#support
* https://github.com/kivy/kivy/wiki/Community-Guidelines
