### ISSUE TITLE
Zipped images not included in examples

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4882]
Zips from [this](https://github.com/kivy/kivy/tree/master/examples/widgets/sequenced_images/data/images) folder aren't available in installed examples (excluding installation from git clone).

There should be also included a license to the files in the example, ref #3110.

**Comment by FeralBytes** [comment]
@KeyWeeUsr as a simple fix; do you plan to unzip the files? Or do you need someone to do that?

**Comment by KeyWeeUsr** [comment]
The files need to be zipped to preserve a functionality of the example showing an `Image` being able to open `.zip` files as a gif → [here](https://github.com/kivy/kivy/blob/master/examples/widgets/sequenced_images/main.kv#L27).

**Comment by KeyWeeUsr** [comment]
@dessant At first I thought so, but I think it's `setup.py`'s fault, as I don't see the zips even after installing from repo. Which means it's broken everywhere.

**Comment by dessant** [comment]
Just a guess, but this may be the place to add it: https://github.com/kivy/kivy/blob/master/MANIFEST.in.

**Comment by dessant** [comment]
This is it: https://github.com/kivy/kivy/blob/master/setup.py#L864.
