### ISSUE TITLE
Kivy Window Not Rendering

### ISSUE THREAD

**Issue by jupart** [kivy/kivy#4893]
Sometimes when running a Kivy app, the window that appears doesn't render correctly, and is instead see-through (see attached .png, which shows the App window on top of a text editor). This happens even when running ../kivy/examples/application/app_with_kv.py (debug log link: https://gist.github.com/jupart/f0125645b8e0eb96e14ef131080cb96b).

OS - Ubuntu 16.04
Machine - Dell Latitude E6530
Video Driver - NVIDIA binary 367.57
Kivy - 1.9.2-dev0

![see_through_kivy](https://cloud.githubusercontent.com/assets/14113990/21731299/ac552866-d421-11e6-92e4-3ee51a5a26c0.png)

I'll check tonight if this issue shows up on my Windows machine too.

**Comment by FeralBytes** [comment]
Notice Window Provider is Pygame not SDL2. Pygame is being replaced by SDL2 on Linux; and Pygame for kivy as a provider is currently undergoing a re-write so far as I remember. So please make sure you have installed the SDL2 requirements for Kivy; then test again.

**Comment by dessant** [comment]
@jupart, please follow up with your findings.

**Comment by jupart** [comment]
I do have libsdl2-2.0-0 and libsdl2-dev installed on my machine. Do I need to build Kivy with any special flags to make it use SDL instead of pygame?

**Comment by dessant** [comment]
The `USE_SDL2=1` env var is one way, but it should be the default when sdl2 is found. Try compiling again and see the beginning of the build log, it should mention the sdl2 headers, and the value of the env var. The rest of the sdl2 deps must also be installed before compiling: https://kivy.org/docs/installation/installation-linux.html#ubuntu-example

**Comment by jupart** [comment]
Rebuilding Kivy seems to have solved my issue, I must have installed the needed SDL2 packages in the mean time. Thanks!
