### ISSUE TITLE
Installation error - Mac OSX 10.12.02

### ISSUE THREAD

**Issue by bagonzalo** [kivy/kivy#4894]
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/7l/wb6q7lsx05s7j7bdrcl41__00000gn/T/pip-build-t6arf64t/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/7l/wb6q7lsx05s7j7bdrcl41__00000gn/T/pip-vdyc2685-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/7l/wb6q7lsx05s7j7bdrcl41__00000gn/T/pip-build-t6arf64t/kivy/

Using Python 3.5 I receive the above error when running:

USE_OSX_FRAMEWORKS=0 pip3 install kivy

**Comment by FeralBytes** [comment]
@bagonzalo are you also @yiyongooi?
If not please see Issue #4936 . We need out put from either you or the other user in a more complete and readable manor; before either of your issues can be addressed.
@dessant I recommend closing this issue; and that we track it in #4936 .
