### ISSUE TITLE
Simple SVG crash (geom.c:82: tesedgeSign: Assertion failed)

### ISSUE THREAD

**Issue by AndreMiras** [kivy/kivy#4899]
I'm trying to render a simple SVG file using the experimental Kivy SVG support.
Actually the SVG is complicated, but I tried to simplify it as much as I could for bug reporting.
Anyway, the code crashes before rendering the file.

The code I'm using (kivy_svg.py):
```python
from kivy.uix.scatter import Scatter
from kivy.app import App
from kivy.graphics.svg import Svg
from kivy.core.window import Window
from kivy.uix.floatlayout import FloatLayout


class SvgWidget(Scatter):

    def __init__(self, filename, **kwargs):
        super(SvgWidget, self).__init__(**kwargs)
        with self.canvas:
            svg = Svg(filename)
        self.size = svg.width, svg.height


class SvgApp(App):

    def build(self):
        self.root = FloatLayout()
        filename = "image.svg"
        svg = SvgWidget(filename, size_hint=(None, None))
        self.root.add_widget(svg)
        svg.scale = 5.
        svg.center = Window.center


if __name__ == '__main__':
    SvgApp().run()
```

The SVG image I'm trying to render (image.svg):
```xml
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100" height="100">
  <path d="M 10 9 L 90 90" stroke-width="1" style="fill:none;stroke:red"/>
</svg>
```

Run output:
```
$ python kivy_svg.py 
[INFO              ] [Logger      ] Record log in /home/andre/.kivy/logs/kivy_17-01-07_149.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.12 (default, Dec 15 2016, 09:52:22) 
[GCC 4.9.3]
[INFO              ] [Factory     ] 179 symbols loaded
[DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
[DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG             ] [Window      ] Ignored <egl_rpi> (import error)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[DEBUG             ] [Window      ] Display driver x11
[DEBUG             ] [Window      ] Actual window size: 800x600
[DEBUG             ] [Window      ] Actual color bits r8 g8 b8 a0
[DEBUG             ] [Window      ] Actual depth bits: 24
[DEBUG             ] [Window      ] Actual stencil bits: 8
[DEBUG             ] [Window      ] Actual multisampling samples: 4
[INFO              ] [GL          ] OpenGL version <3.0 Mesa 12.0.1>
[INFO              ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO              ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Kabylake GT2 >
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <1.30>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <32>
[DEBUG             ] [Shader      ] Fragment compiled successfully
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [ImagePygame ] Load </tmp/trash/svg_tests/venv/lib/python2.7/site-packages/kivy/data/glsl/default.png>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG             ] [App         ] Loading kv <./svg.kv>
[DEBUG             ] [App         ] kv <./svg.kv> not found
[DEBUG             ] [Shader      ] Fragment compiled successfully
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [Svg         ] Loading image.svg
python: /tmp/pip-build-0cJg3c/Kivy/kivy/lib/libtess2/Source/geom.c:82: tesedgeSign: Assertion `(((u)->s < (v)->s) || ((u)->s == (v)->s && (u)->t <= (v)->t)) && (((v)->s < (w)->s) || ((v)->s == (w)->s && (v)->t <= (w)->t))' failed.
Aborted
$
```

[kivy_17-01-07_149.txt](https://gist.github.com/AndreMiras/ff07183ce66030332b356af7dae63b68) log file.

I'm new to SVG, but the funny thing is changing the MoveTo command arguments from "10 9" to "10 10" will make it possible to render it under Kivy without crashing.
I took a look at [geom.c code](https://github.com/kivy/kivy/blob/1.9.1/kivy/lib/libtess2/Source/geom.c#L82), but to be honest I didn't understand anything (yet).
I'm running Python 2.7.12 in a virtualenv, Kivy==1.9.1 and pygame==1.9.2, both installed with pip.

**Comment by FeralBytes** [comment]
@AndreMiras what program was the SVG file generated with?

**Comment by AndreMiras** [comment]
@FeralBytes I'm using a Python library called [svg_utils](https://github.com/btel/svg_utils) to generate SVG files from my Python code. And I tried to extract and simplify the line that caused the issue in the big SVG file generated. I'm new to SVG, but from reading the [path element spec](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path) it seems this is a valid SVG file, but maybe it's not.

I want to generate SVG map tiles and display them using Kivy.
The idea is to see if I can replace the current implementation of PNG map tiles by SVG in my [GuyPS](https://github.com/AndreMiras/GuyPS) project.

**Comment by FeralBytes** [comment]
@AndreMiras well unfortunately I too do not know enough about SVG to help you; hopefully somebody else can.

**Comment by tito** [comment]
I can't reproduce it on master, it works ok, so maybe it has already been resolved?

` ` ` 
[INFO   ] [Logger      ] Record log in /home/tito/.kivy/logs/kivy_17-02-05_0.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <4.5.0 NVIDIA 375.26>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <GeForce GTX 970/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <4.50 NVIDIA>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
` ` ` 

Outputs:

![screenshot from 2017-02-05 17-44-09](https://cloud.githubusercontent.com/assets/37904/22628366/bb5d606a-ebca-11e6-9525-e2e9a3d9d1ae.png)

**Comment by AndreMiras** [comment]
OK, so it has to be something else, because I've just installed Kivy master and I'm still having the issue.

```
[INFO   ] [Logger      ] Record log in /home/andre/.kivy/logs/kivy_17-02-05_5.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-Unknown, 20170205
[INFO   ] [Python      ] v2.7.12 (default, Dec 15 2016, 09:52:22) 
[GCC 4.9.3]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 12.0.1>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Kabylake GT2 >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
python: /tmp/pip-6n0n8b-build/kivy/lib/libtess2/Source/geom.c:82: tesedgeSign: Assertion `(((u)->s < (v)->s) || ((u)->s == (v)->s && (u)->t <= (v)->t)) && (((v)->s < (w)->s) || ((v)->s == (w)->s && (v)->t <= (w)->t))' failed.
Aborted
```
I'm going to dig into it based on your short log.

**Comment by AndreMiras** [comment]
After using sdl2 rather than pygame as provider I'm still having the issue (with master 57d41c9).
Here's the log
```
[INFO   ] [Logger      ] Record log in /home/andre/.kivy/logs/kivy_17-02-05_12.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-Unknown, 20170205
[INFO   ] [Python      ] v2.7.12 (default, Dec 15 2016, 09:52:22) 
[GCC 4.9.3]
[INFO   ] [Factory     ] 193 symbols loaded
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[DEBUG  ] [GL          ] glShaderBinary is not available
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 12.0.1>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Kabylake GT2 >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load </tmp/trash/svg_tests/venv/lib/python2.7/site-packages/kivy/data/glsl/default.png>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG  ] [App         ] Loading kv <./svg.kv>
[DEBUG  ] [App         ] kv <./svg.kv> not found
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [Svg         ] Loading image.svg
python: /tmp/pip-k0v3t1-build/kivy/lib/libtess2/Source/geom.c:82: tesedgeSign: Assertion `(((u)->s < (v)->s) || ((u)->s == (v)->s && (u)->t <= (v)->t)) && (((v)->s < (w)->s) || ((v)->s == (w)->s && (v)->t <= (w)->t))' failed.
Aborted
```
FWIW, on Gentoo I had to:
```
emerge media-libs/libsdl2 media-libs/sdl2-image media-libs/sdl2-mixer media-libs/sdl2-ttf
```
Before reinstalling Kivy to run with sdl2 backend.

I'm not sure where to look for next, @tito do you have any hint?

**Comment by AndreMiras** [comment]
OK, I gave it a try on Ubuntu 14.04 and it gets compiled with `-DNDEBUG` therefore the assert gets disabled. However on my Gentoo the NDEBUG preprocessor macro is not enabled. I thought this would be part of the Makefile somewhere, but I don't see it anywhere.
I'm now trying to figure out where is this default flag setup.

**Comment by AndreMiras** [comment]
I thought it could be something to do with `sysconfig`, but both Gentoo and Ubuntu seem to have NDEBUG enabled.
Ubuntu:
```
>>> import sysconfig
>>> sysconfig.get_config_var('OPT')
'-DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes'
```
Gentoo
```
>>> import sysconfig
>>> sysconfig.get_config_var('OPT')
'-DNDEBUG'
```
However the OPT seems to be ignored on Gentoo.
Forcing NDEBUG via build_ext global-option eventually disables asserts and works around the issue.
```
pip install --verbose --global-option=build_ext --global-option="-DNDEBUG" kivy
```

Even though it doesn't crash anymore with that workaround, I reckon this assert is there for a reason and the test case I provided raises it. So there's probably something we could do about it, what do you think @tito?
