### ISSUE TITLE
Kivy Garden packages not discovered on OS X

### ISSUE THREAD

**Issue by martinsik** [kivy/kivy#4907]
I've encountered a problem where my app can't find packages installed via Garden tool. Eg.:

```
import kivy.garden.contextmenu
```

I checked the source code and in [bin/garden](https://github.com/kivy-garden/garden/blob/master/bin/garden#L33) it by default installs packages into my home directory:
```
garden_system_dir = join(expanduser('~'), '.kivy', 'garden')
```
This is for example `/Users/martin/.kivy/garden/`.

However when importing the module it by default looks into `/Applications/Kivy.app/Contents/Resources/kivy/kivy/garden` because the `KIVY_HOME` is in [`kivy/__init__.py`](https://github.com/kivy/kivy/blob/master/kivy/__init__.py#L281) which is used by [`garden/__init__.py`](https://github.com/kivy/kivy/blob/master/kivy/garden/__init__.py#L73).

When I install packages with `--app` option it works correctly but not without it. So I'm wondering whether I did something wrong but I'm using freshly installed kivy 1.9.1.

**Comment by KeyWeeUsr** [comment]
This is a known bug (https://github.com/kivy-garden/garden/issues/13) in the garden. Try to compile Kivy from source, I think when installed that way the garden works correctly, however the "Kivy.app" OSX thing works kind of different, because it holds its own environment(`KIVY_HOME`) as you've noticed.

**Comment by martinsik** [comment]
I guess I can close this since it's already mentioned here kivy-garden/garden#13.
