### ISSUE TITLE
Missing 'return' in get method for Mesh `mode` property

### ISSUE THREAD

**Issue by pythonic64** [kivy/kivy#4912]
Going through code of Mesh class, I've noticed that "return" is missing for mode property. 
Ref: https://github.com/kivy/kivy/blob/master/kivy/graphics/vertex_instructions.pyx#L490

**Comment by KeyWeeUsr** [comment]
I think I couldn't get the mode either before. Might be the thing, as it's in [here](https://github.com/kivy/kivy/blob/082c4544415ab6bd976d9dda9c342bae109e7cbb/kivy/graphics/vbo.pyx#L256). Will you make a pull request? :)

**Comment by pythonic64** [comment]
I will probably have time next week, if someone else doesn't make a pull request in the meantime.

**Comment by phunsukwangdu** [comment]
@KeyWeeUsr i will work on this issue.

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/4913
