### ISSUE TITLE
TextInput bug when insert position changes

### ISSUE THREAD

**Issue by melassa** [kivy/kivy#4914]
1) Focus a TextInput
2) Type 'abc'
3) Tap the textinput to put the cursor before 'abc'
4) Write 'xyz'
5) The result is totally wrong:
      it should be: 'xyzabc' 
      instead it is: 'abcxyzabc'
The bug is on LG, Android Lollipop, kivy 1.9.1, keyboard LG (with predictions or without)

**Comment by malverick** [comment]
I will work on the issue and send the pr as soon as possible.

**Comment by malverick** [comment]
Hi @melassa. I think you are trying to build an apk using old toolchain(`buildozer android debug`)
Try using the new toolchain(`buildozer android_new debug`). You will not receive any such issue.

**Comment by melassa** [comment]
I am using kivy launcher

**Comment by malverick** [comment]
The issue which you have described here is not actually a bug because I tried to use text input in all platforms and I faced this issue only in android that too using old toolchain(which should not be used now).
So, if you are using kivy launcher and facing the issue the I would encourage you to build an apk using new toolchain and then use it.

**Comment by KeyWeeUsr** [comment]
@melassa Old launcher with code and bootstrap from ~1 year ago. [Build a new one](http://python-for-android.readthedocs.io/en/latest/launcher/), or as suggested, just package it as a separate app and test again.

However, there was a similar thing (#4173), so you might want to check that too (might be the same bug?), though I can't reproduce it either.

**Comment by melassa** [comment]
Ok. I'll try.

2017-01-19 1:17 GMT+01:00 Peter Badida <notifications@github.com>:

**Comment by dessant** [comment]
Please reopen if you can reproduce it with kivy master + sdl2.
