### ISSUE TITLE
GridLayoutException not imported in recyclegridlayout.py 

### ISSUE THREAD

**Issue by pythonic64** [kivy/kivy#4918]
As said in title, GridLayoutException is not imported from kivy.uix.gridlayout module, so this [line](https://github.com/kivy/kivy/blob/master/kivy/uix/recyclegridlayout.py#L130) will raise a NameError.

**Comment by dessant** [comment]
@pythonic64, would you mind creating a pr for it?

**Comment by pythonic64** [comment]
I'll work on pull request this weekend, if someone else doesn't submit it in the meantime.
