### ISSUE TITLE
Kivy via conda

### ISSUE THREAD

**Issue by waqasm86** [kivy/kivy#4928]
Hello there,
I would like to install kivy via 'conda' (continuum analytics) instead of 'pip' command. When would it be possible to see the availability of kivy via anaconda package list for Python 3.5.

https://docs.continuum.io/anaconda/pkg-docs

Thanks 

Waqas

**Comment by dessant** [comment]
Kivy installation methods are fragmented enough as is, which causes numerous issues. We aim to distribute kivy with the help of wheels on all platforms, just like on Windows.

If someone from the community would like to maintain a conda package, that's certainly welcome, but the Kivy team does not have the resources to properly support it.
