### ISSUE TITLE
When I create a new thread, cpu and memory usage suddenly rose to 100%.

### ISSUE THREAD

**Issue by falseen** [kivy/kivy#4933]
I tried to create a new thread in kivy to perform other tasks, I built a new button, and bind the start function, in this function used threading to start my program. But once the implementation of this thread, cpu and memory suddenly rose to 100%, until the crash. But when it is running alone, there is no problem. I do not understand the problem lies in which, please help me!

ps:  I tried to run the program is  `local` of `shadowsocks`
It's home page is : https://github.com/shadowsocks/shadowsocks/tree/master

**Comment by dessant** [comment]
Based on what you described, it's unlikely you're experiencing a kivy bug, check out our support channels, and make sure you have prepared an example.

https://github.com/kivy/kivy#support

**Comment by falseen** [comment]
I found the reason! In my process there is a code on the logging, the content is `logging.getLogger (''). Handlers = []`, each time running here, cpu and memory will suddenly rise to 100% until crash. As long as this line commented out, there is no problem. But kivy will be being given, the content is related with the logging, I think this should be kivy the logging module and the logging module of my program had a conflict.

My procedure directly on the set of logging, not derived from the new object, these settings may affect the normal operation of Kivy bars. I am looking for a solution ....

**Comment by dessant** [comment]
@falseen, if that's indeed the case, it may be interesting. Could you share a runnable example?

**Comment by falseen** [comment]
@dessant  Sure! 
It's on my github home page, you can download it here. [shadowsocks-kivy](https://github.com/falseen/shadowsocks-kivy)
I just started to create it, there are many places not perfect.

The program will start running by clicking the "start" button, and the  `logging.getLogger (''). Handlers = []` is located at line 301 o f `/shaowsocks-kivy/kivy/shadowsocks/shell.py`.

My environment：

> windows7 64bit
> python34 64bit
> kivy 1.9.1

**Comment by dessant** [comment]
I was hoping for a short, runnable example, your repo also contains binary blobs, so I will not be able to run it, shadowsocks is a pip install away.

Anyway, maybe the way kivy overwrites the root logger conflicts with shadowsocks, if you boil it down to a simple example, please take a look at this issue and see if it applies: https://github.com/kivy/kivy/issues/4322.

**Comment by falseen** [comment]
I seem to find the real reason.
 Run `logging.getLogger('').handlers = []`, then run `VERBOSE_LEVEL`, the error will appear.

A simple example ：
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.gridlayout import GridLayout
import threading
import time
import logging
Builder.load_string("""

<RootWidget>:
    BoxLayout:
        Button:
            id: but_1
            font_size: 20
            bold: True
            text: ' Start '
            on_press: root.start_second_thread()
""")


class RootWidget(GridLayout):

    stop = threading.Event()

    def start_second_thread(self):
        threading.Thread(target=self.infinite_loop).start()
        

    def infinite_loop(self):
        iteration = 0
        while True:
            if self.stop.is_set():
                # Stop running this thread so the main Python process can exit.
                return
            logging.getLogger('').handlers = []
            logging.addLevelName(VERBOSE_LEVEL, 'VERBOSE')
            time.sleep(100)
            iteration += 1
            print('Infinite loop, iteration {}.'.format(iteration))
            time.sleep(1)


class ThreadedApp(App):

    def on_stop(self):
        # The Kivy event loop is about to stop, set a stop signal;
        # otherwise the app window will close, but the Python process will
        # keep running until all secondary threads exit.
        self.root.stop.set()

    def build(self):
        return RootWidget()

if __name__ == '__main__':
    ThreadedApp().run()
```

**Comment by falseen** [comment]
Obviously, the key to the problem is that xx, Kivy APP seems to cover this variable `VERBOSE_LEVEL`.

**Comment by dessant** [comment]
I have ran your last example on py3.4, windows 10, kivy master, and there is no error, it loops as expected and it exits cleanly when the app is closed.

**Comment by falseen** [comment]
Oh, it seems because more than one `VERBOSE_LEVEL = 5`,  I re-modified the code, you can try again.

**Comment by dessant** [comment]
Now the declaration of VERBOSE_LEVEL was removed, of course it will produce a NameError.

**Comment by dessant** [comment]
I have further replaced `logging.addLevelName(VERBOSE_LEVEL, 'VERBOSE')` with `logging.addLevelName(5, 'VERBOSE')` and the thread runs without issues, as the first version.

**Comment by falseen** [comment]
Looks not for one reason, there are multiple reasons. I'm troubleshooting the root cause of the problem.

**Comment by dessant** [comment]
I'm only looking for an example which reproduces the issue for now. 😁

**Comment by falseen** [comment]
My English is so poor that I can not express too much complexity. You follow my example above can reproduce this problem. The key lies in this code:
```python
logging.getLogger('').handlers = []
logging.addLevelName(VERBOSE_LEVEL, 'VERBOSE')
```
Replacing `VERBOSE_LEVEL` with `5` can certainly solve the problem, but this is not the root cause of the problem. I can not tell where the root cause of the problem is, but I can be sure that running `logging.getLogger (''). Handlers = []` and `VERBOSE_LEVEL`  will cause the problem.

**Comment by dessant** [comment]
@falseen, look, your english has nothing to do with it. :)

Please copy and paste the example from here: https://github.com/kivy/kivy/issues/4933#issuecomment-274069804

Run it.

It will crash with a NameError, because the VERBOSE_LEVEL variable was not declared, That is a programming error.

Before the post was edited by you (which removed the VERBOSE_LEVEL declaration), the example was running and working fine. So you have to share an example which shows your issue, without us needing to modify it in any way.

**Comment by falseen** [comment]
But when I run the above example is not a `NameError`, it will directly lead to panic.

Now I want to know is that when you run the above example is prompted `NameError` or crash?

What I mean is that after running `logging.getLogger (''). Handlers = []` kivy seems to have added a global variable called `VERBOSE_LEVEL`. At least here is the case.

**Comment by dessant** [comment]
It crashes with a NameError when the Start button is pressed.

**Comment by falseen** [comment]
If I do not run `logging.getLogger (''). Handlers = []`, running VERBOSE_LEVEL will normally throw a NameError error. But running `logging.getLogger (''). Handlers = []`, and then run VERBOSE_LEVEL it will crash.

**Comment by falseen** [comment]
If you are there all the normal, then it may be my environment has a question. I went on to find out why. thank you.

**Comment by dessant** [comment]
You could open an issue for shadowsocks and ask them to not touch the root logger. We will also likely do the same in kivy, It is just bad practice, and leads to all kinds of interoperability issues.

**Comment by falseen** [comment]
I can change the shadowsocks code, but this is not a good idea. The best is to find the root cause. From the present situation, it seems that more than one reason. I now skip the logging problem, and look for another problem.

**Comment by falseen** [comment]
Now I am sure, running `logging.getLogger (''). Handlers = []`, and then run like `logging.info()` such statements, it will certainly be the problem.

**Comment by falseen** [comment]
I reproduce the problem in ubuntu, although it does not like Windows, like crashes, but the cpu occupancy has reached 100%. See pictures.

![image](https://cloud.githubusercontent.com/assets/11572353/22163677/c584d35e-df8e-11e6-9787-371355299505.png)

**Comment by dessant** [comment]
Could you test if commenting out this line in kivy fixes your issue?
https://github.com/kivy/kivy/blob/5913d861f45119dfff0b6cb5d004e6f79858563c/kivy/logger.py#L320

**Comment by dessant** [comment]
Ok, I can finally reproduce your issue with the last example you posted.
If you comment out that line in kivy, the chash should be solved, but you may see an infinite recursion when the app is closed.
Here is a work in progress pr: https://github.com/kivy/kivy/pull/4940.

**Comment by dessant** [comment]
Also, the exception in the thread occurs because logging.getLogger('') returns the root logger, which is currently also the kivy logger, so you mess up the kivy logger handlers.

**Comment by falseen** [comment]
You're great, it's not dead. But it began to suggest the following error:

![image](https://cloud.githubusercontent.com/assets/11572353/22175378/6e1f9e8c-e02e-11e6-9708-33f21375af88.png)

I modified logger.py according to your pr. My kivy version is Kivy-1.9.2.dev0

**Comment by dessant** [comment]
Yes, the pr will need further changes.

**Comment by falseen** [comment]
I tried to comment out the following line in logger.py, the problem seems to be solved.

```python
sys.stderr = LogFile('stderr', Logger.warning)
```

**Comment by Julian-O** [comment]
This is an educated guess as to the cause rather than a confirmed and tested statement:

* Kivy monkey patches its Kivy.Logger to be the root logger, so when a call to getLogger('') is made, the Kivy Logger is returned.
* All the handlers were all removed from this logger by the user.
    * (By the way, it is probably safer to call `removeHandler()` than just overwrite the attribute.)
* So now, when any log message is made, there are no handlers available.
* Since Python 3.2, if there are no handlers available on a logger (nor any of its ancestors), a logger called `logging.lastResort` is used.
* lastResort sends the message to sys.stderr.
* But Kivy's Logger redirects sys.stderr back into the log system, where it gets raised again, causing an infinite loop.

There are a number of existing issues on various Kivy behaviours here, but I think this explains why there was an infinite loop.
