### ISSUE TITLE
MSVC Install / compile fails on x64 with venv

### ISSUE THREAD

**Issue by Badg** [kivy/kivy#4941]
### Versions

* Python: 3.5 x64
* OS: Windows 7 x64
* Kivy: stable 1.9.1; also, master dev branch
* Kivy installation method: MSVC compile instructions [here](https://kivy.org/docs/installation/installation-windows.html)

### Description

Attempting to compile/install Kivy fails with linking errors to glew dependencies (stable 1.9.1), or from missing ```gst/gst.h``` (1.9.2dev0 master branch). I followed the install docs exactly with one minor difference:

```
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
```

(note the x64 argument; otherwise it fails after trying to build for the wrong architecture target).

At first I thought this might have been related to #4216, but on further investigation it seems unrelated. Modifying path as discussed in docs within #4694 has no effect.

### Code and Logs

Building with stable results in the following error:

```
       Creating library build\temp.win-amd64-3.5\Release\Users\BADGER~1\AppData\
Local\Temp\pip-build-kpsgjh0k\kivy\kivy\graphics\svg.cp35-win_amd64.lib and obje
ct build\temp.win-amd64-3.5\Release\Users\BADGER~1\AppData\Local\Temp\pip-build-
kpsgjh0k\kivy\kivy\graphics\svg.cp35-win_amd64.exp
    svg.obj : error LNK2001: unresolved external symbol __glewIsRenderbuffer
    svg.obj : error LNK2001: unresolved external symbol __glewIsFramebuffer
    svg.obj : error LNK2001: unresolved external symbol __glewGetRenderbufferPar
ameteriv
    svg.obj : error LNK2001: unresolved external symbol __glewFramebufferTexture
2D
    svg.obj : error LNK2001: unresolved external symbol __glewFramebufferTexture
3D
    svg.obj : error LNK2001: unresolved external symbol __glewRenderbufferStorag
e
    svg.obj : error LNK2001: unresolved external symbol __glewCheckFramebufferSt
atus
    svg.obj : error LNK2001: unresolved external symbol __glewDeleteRenderbuffer
s
    svg.obj : error LNK2001: unresolved external symbol __glewDeleteFramebuffers

    svg.obj : error LNK2001: unresolved external symbol __glewFramebufferRenderb
uffer
    svg.obj : error LNK2001: unresolved external symbol __glewGenFramebuffers
    svg.obj : error LNK2001: unresolved external symbol __glewFramebufferTexture
1D
    svg.obj : error LNK2001: unresolved external symbol __glewBindRenderbuffer
    svg.obj : error LNK2001: unresolved external symbol __glewBindFramebuffer
    svg.obj : error LNK2001: unresolved external symbol __glewGenRenderbuffers
    svg.obj : error LNK2001: unresolved external symbol __glewGenerateMipmap
    svg.obj : error LNK2001: unresolved external symbol __glewGetFramebufferAtta
chmentParameteriv
    build\lib.win-amd64-3.5\kivy\graphics\svg.cp35-win_amd64.pyd : fatal error L
NK1120: 17 unresolved externals
     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\
BIN\\amd64\\link.exe' failed with exit status 1120

    ----------------------------------------
Command "c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\
\Users\\BADGER~1\\AppData\\Local\\Temp\\pip-build-kpsgjh0k\\kivy\\setup.py';f=ge
tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.cl
ose();exec(compile(code, __file__, 'exec'))" install --record C:\Users\BADGER~1\
AppData\Local\Temp\pip-zst4naho-record\install-record.txt --single-version-exter
nally-managed --compile" failed with error code 1 in C:\Users\BADGER~1\AppData\L
ocal\Temp\pip-build-kpsgjh0k\kivy\
```

Building from master fails with a slightly different error:

```
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /
nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\BADGER~1\AppData\Local\Temp\pip-5ylmr
7lr-build\kivy\include -Ic:\python35\include -Ic:\python35\include -IC:\Python35
\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC
:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Prog
ram Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (
x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows K
its\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um"
 "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /TcC:\Users\BADGER~1
\AppData\Local\Temp\pip-5ylmr7lr-build\kivy\lib/gstplayer\_gstplayer.c /Fobuild\
temp.win-amd64-3.5\Release\Users\BADGER~1\AppData\Local\Temp\pip-5ylmr7lr-build\
kivy\lib/gstplayer\_gstplayer.obj
    _gstplayer.c
    C:\Users\BADGER~1\AppData\Local\Temp\pip-5ylmr7lr-build\kivy\lib/gstplayer\_
gstplayer.c(239): fatal error C1083: Cannot open include file: 'gst/gst.h': No s
uch file or directory
     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\
BIN\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\
\Users\\BADGER~1\\AppData\\Local\\Temp\\pip-5ylmr7lr-build\\setup.py';f=getattr(
tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();
exec(compile(code, __file__, 'exec'))" install --record C:\Users\BADGER~1\AppDat
a\Local\Temp\pip-cubjyk9o-record\install-record.txt --single-version-externally-
managed --compile" failed with error code 1 in C:\Users\BADGER~1\AppData\Local\T
emp\pip-5ylmr7lr-build\
```

**Comment by tshirtman** [comment]
got the same issue trying to build last week, needed debug symbols and couldn't, had to find another way to debug.

**Comment by KeyWeeUsr** [comment]
1.9.1 most likely can't compile with msvc this way because of some changes and although there's [this](http://www.lfd.uci.edu/~gohlke/pythonlibs/#kivy) collection, you'd probably need to compile the dependencies yourself too to achieve this. I haven't compiled stable for a long time.

About `gst/gst.h` → `set USE_GSTREAMER=0`

or download the additional headers `pip install kivy.deps.gstreamer_dev`

I tested a minute ago with fresh python (on Win8 though), so if something breaks again this way, it's most likely some garbage in the interpreter or missing files. Be sure to overwrite the deps (maybe pip didn't download correctly or there was "permission denied" lovely stuff from pip or something) with `pip install -I --no-cache-dir ...˙

I'll change the instructions regarding this stuff (arch, missing deps, etc). ^^

**Comment by KeyWeeUsr** [comment]
Also, re the modifying path, originally I thought it was necessary and put it even into my own installer, but it was only a problem related to (mostly) drivers having the same-named `.dll` file, but probably older version, which caused Kivy to fetch that file (as if was first on the `%PATH%`). Now it's [fixed](https://github.com/kivy/kivy-sdk-packager/blob/8c3d8192cf2ddd456e6c60dd92842c78fac3bb50/win/common.py#L211) for all deps.

**Comment by Badg** [comment]
I finally got around to trying this again today.

1. Unrelated news! Kivy (or at least Kivy dev) is missing its Cython dependency (I'm assuming in setup.py). So on first pitch, it's a swing and a miss with ```No module named "Cython"```, but that's an easy fix:
2. ```pip install Cython```
3. Good news! I can build and install Kivy from master!
4. Better news! I can do it in a venv! So long as you cd to the env root, ex:  
    
        python -m venv kivy-dev
        cd kivy-dev
        scripts\python -m pip install --upgrade pip setuptools
        ....
    
    Everything works just fine. So that would imply #4216 is no longer relevant, at least when using venvs created through the builtin ```venv``` module and compiling via MSVC. I've also previously verified that the precompiled nightly wheels work just fine in venvs, so that's cool too.
5. Less good news! I can't run any of the demo apps. See errors below.

```
C:\Users\BadgerDoc\venv\kivy2>scripts\python share/kivy-examples/demo/showcase/main.py
Purge log fired. Analysing...
Purge finished!
[INFO   ] [Logger      ] Record log in C:\Users\BadgerDoc\.kivy\logs\kivy_17-01-24_0.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
pygame - ImportError: No module named 'pygame'
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\window\window_pygame.py", line 8, in <module>
    import pygame

[CRITICAL] [App         ] Unable to get a Window, abort.

C:\Users\BadgerDoc\venv\kivy2>scripts\python share/kivy-examples/demo/kivycatalog/main.py
[INFO   ] [Logger      ] Record log in C:\Users\BadgerDoc\.kivy\logs\kivy_17-01-24_1.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Text        ] Unable to find any valuable Text provider.
pygame - ImportError: No module named 'pygame'
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\text\text_pygame.py", line 12, in <module>
    import pygame

pil - ImportError: No module named 'PIL'
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\text\text_pil.py", line 7, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.

C:\Users\BadgerDoc\venv\kivy2>scripts\python share/kivy-examples/demo/pictures/main.py
[INFO   ] [Logger      ] Record log in C:\Users\BadgerDoc\.kivy\logs\kivy_17-01-24_2.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
pygame - ImportError: No module named 'pygame'
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\BadgerDoc\venv\kivy2\lib\site-packages\kivy\core\window\window_pygame.py", line 8, in <module>
    import pygame

[CRITICAL] [App         ] Unable to get a Window, abort.
```

I thought Kivy was using SDL2 as the windowing backend these days?

**Comment by KeyWeeUsr** [comment]
`set USE_SDL=1` is kind of necessary. Otherwise it automatically drops to the pygame.

**Comment by Badg** [comment]
Yep, I did that before compilation. BUT, that was before the first build errored out because Cython was missing. On a hunch, I tried it again in a new venv, this time ```pip install```ing cython before doing the environment change, and... No dice. Same error.

On a side note, I missed the "Cython is required for compiling Kivy" warning until I was looking at the source for ```setup.py```; it might be worthwhile to add ```python -m pip install cython``` to step 4 on the MSVC compile docs.

Exact steps I took:
```
python -m venv kivy3
cd kivy3
scripts\python -m pip install --upgrade setuptools pip
scripts\python -m pip install -I --no-cache-dir cython kivy.deps.sdl2 kivy.deps.glew kivy.deps.sdl2_dev kivy.deps.glew_dev
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
set MSSdk=1
set DISTUTILS_USE_SDK=1
set LIB=%cd%\libs;%LIB%
set INCLUDE=%cd%\include;%INCLUDE%
set USE_SDL2=1
set USE_GSTREAMER=0
git clone https://github.com/kivy/kivy
scripts\python -m pip install kivy\.
scripts\python share\kivy-examples\demo\showcase\main.py
```

**Comment by KeyWeeUsr** [comment]
If you can, compile again and put here the config (those lines with `*` and env vars e.g. `use_sdl = 1`) I think venv probable used it's own environment (without `use_sdl` set), which means it falls to pygame. You can switch it manually in setup.py if you poke into it.

**Comment by Badg** [comment]
Wait, is it ```USE_SDL``` or ```USE_SDL2```? Or both? Docs say ```USE_SDL2```, which is what I've been doing.

I don't think it's an issue with the venv for two reasons: first, because I'm invoking the environment's binary directly (never using ```source activate``` or equivalent scripts, so there shouldn't be any ENV modifications), and second, because (without cython installed) is pops up a blurb about detecting a changed environment:

```
C:\Users\BadgerDoc\venv\kivy2>set MSSdk=1
C:\Users\BadgerDoc\venv\kivy2>set DISTUTILS_USE_SDK=1
C:\Users\BadgerDoc\venv\kivy2>set LIB=%cd%\libs;%LIB%
C:\Users\BadgerDoc\venv\kivy2>set INCLUDE=%cd%\include;%INCLUDE%
C:\Users\BadgerDoc\venv\kivy2>set USE_SDL2=1
C:\Users\BadgerDoc\venv\kivy2>set USE_GSTREAMER=0
C:\Users\BadgerDoc\venv\kivy2>scripts\python -m pip install kivy\.
Processing c:\users\badgerdoc\venv\kivy2\kivy
    Complete output from command python setup.py egg_info:
    Using distutils
    Environ change use_sdl2 -> True
    Environ change use_gstreamer -> False

    Cython is missing, its required for compiling kivy !


    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\BADGER~1\AppData\Local\Temp\pip-baxuqwf7-build\setup.py", line 186, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\BADGER~1
\AppData\Local\Temp\pip-baxuqwf7-build\
```

**Comment by KeyWeeUsr** [comment]
`USE_SDL2`, sorry ^^ also, unless you have cython already installed and system packages (e.g. `virtualenv blob --system-site-packages`) available, then you'll need to install Cython again even into that venv. Kivy uses Cython to generate C code, so to use the development version you'll need to have that installed - it's already mentioned [here](https://kivy.org/docs/installation/installation-windows.html#use-development-kivy).

Apparently the msvc instructions sound like a completely separate ones. There'll be a little rewrite regarding Visual Studio support only as one of the version we need is free (though enormous).

Anyway, the env variable (`use_sdl2`) appears to be changed, so it should compile and ignore pygame completely.

**Comment by Badg** [comment]
I've been installing cython into the venv. I missed it the first time -- just like you said, I interpreted the MSVC instructions as separate. My bad. Anyways, I had to deliberately uninstall Kivy and Cython, then reinstall Kivy without Cython, to get the environ change messages for my last code snippet. They don't appear when Cython is installed into the venv and the build successfully completes.

So it sounds like my most recent "successful" compile attempt (the one [here](https://github.com/kivy/kivy/issues/4941#issuecomment-274941366), that uses the kivy3 venv) did everything correctly, but it still didn't correctly compile with SDL2 and is falling back to pygame.

I tried adding the venv and its scripts directory to PATH; no joy there. I went into ```setup.py``` and manually set [this line](https://github.com/kivy/kivy/blob/master/setup.py#L110) to:

``` python
c_options['use_sdl2'] = True
```

Still no luck. I'm not able to clean my system python on this machine, but if you want, I can try this again on a cleaner system python (instead of a virtualenv) on my laptop at some later point. It's running Windows 10 though, so if this is specific to Windows 7, we could get a false negative.

Any thoughts? I can "get by" on nightly wheel builds for a while, so this isn't blocking me; I completely understand if you guys have other priorities than troubleshooting one particular Windows build.

**Comment by KeyWeeUsr** [comment]
No need to go for another device. Install Python with [KivyInstaller](https://github.com/KeyWeeUsr/KivyInstaller) with non-admin option, it creates a portable python that's not bound to registry or basically anywhere else (but it'll use folders a normal python uses, e.g. pip cache). When you're done, just delete the folder.

I don't think it's Python's fault though, nor Win7's because I can compile it even in VM. I don't use venv for Kivy though (It's like throwing 25MB+ if you go **from scratch** for every env away for no reason!). What you can do is installing it from the git repo directly, which means you'll see what you change in your Kivy and can clean Kivy with `git clean -dxf`.

Does the installation work for you without venv with some basic demo e.g. touchtracer?

**Comment by Badg** [comment]
I'm confused; is ```c_options['use_sdl2'] = True``` supposed to force Kivy to use SDL2 when compiling? Because if that's the case, there's either a bug or an abstraction leak somewhere, because Kivy compiles successfully that way, but is still falling back to pygame.

I've gotten all the demos to work using the nightly wheels (that's part of why I can't clean my system Python), even in a virtualenv. That implies a compilation problem, correct?

The idea behind using a system python would be to try and isolate any compilation environment problems arising from the venv's location. If, for example, this is traced back to a problem with PATH, then the KivyInstaller portable python isn't going to tell us much.

I don't see much in #4896 that would help here, as it's the minGW compilation on 3.4 (and I think virtualenv vs venv?), whereas this is MSVC on 3.5. Also note that the failing Appveyor builds in that PR are both 3.5.

**Comment by KeyWeeUsr** [comment]
I suggested Kivyinstaller, so that you could test if it compiles on a system wide interpreter, as the portable installation _behaves_ like that (and won't mess with the real system wide one), which is kind of why I'm bugging you with the test as I would like to know if it's venv's fault or something else went crazy.

That's being said, compilation works fine for me with the same exact steps for both 32bit and 64bit and even in VM with Win7, thus I wondered what is wrong with your attempts. :/

There isn't really many space for an error with `use_sdl2`, which basically limits it to two lines. One is for OSX, therefore I think it might be [this line](https://github.com/kivy/kivy/blob/master/setup.py#L620) that reverts `c_options['use_sdl2']` to `False`, but that's only a wild guess. If that's the case, it probably can't see headers properly from venv (again the test with system wide interpreter ^^). If it sees, then I kind of have no clue, because I tested it with `virtualenv` (not `venv`):

    virtualenv blob
    cd blob
    Scripts\activate.bat
    pip install kivy.deps.glew kivy.deps.glew_dev kivy.deps.sdl2 kivy.deps.sdl2_dev cython
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ARCH
    set MSSdk=1
    set DISTUTILS_USE_SDK=1
    set LIB=%cd%\libs;%LIB%
    set INCLUDE=%cd%\include;%INCLUDE%
    set USE_SDL2=1
    set USE_GSTREAMER=0
    pip install git+https://github.com/kivy/kivy
    python share\kivy-examples\demo\touchtracer\main.py  # pygame fail

Oh, what a surprise, virtualenv behaves exactly like I thought. If I edit that line (setup.py/L620) to be `True` i.e. I force it to proceed anyway, it'll throw at me this:

    ...\AppData\Local\Temp\pip-st_hjcvs-build\kivy\graphics/cgl_backend\cgl_sdl2.c(436): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

Thus if in virtualenv, it can't see the headers, as expected. If you set that right, it'll compile correctly.

@matham any ideas what path does virtualenv/venv want?

**Comment by Badg** [comment]
My point re KivyInstaller is that neither it nor venv (in the way that I'm using it) are modifying the ENV, which we've already verified with the cython-failing-attempt, so if it's failing to compile with SDL2, it's a problem in setup.py, and running the extra test doesn't tell us anything. Furthermore, this was confirmed by explicitly hard-coding ```c_options['use_sdl2'] = True``` in setup.py.

Regardless, I know what the problem is and have fixed it (and verified it works locally). I'll have a PR for it sometime soon, hopefully in the next several hours. As you expected, it's in the ```def determine_sdl2()``` block.

**Comment by matham** [comment]
Fixed with https://github.com/kivy/kivy/pull/4896
