### ISSUE TITLE
Kivy Crash on Install Python 3.5 pip Win10 with SSD

### ISSUE THREAD

**Issue by PinochleLover** [kivy/kivy#4955]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by KeyWeeUsr** [comment]
No details at all. Please include at least something.
