### ISSUE TITLE
use_opengl_mock and kivy_gl_backend not working for readthedocs.org

### ISSUE THREAD

**Issue by jasmas** [kivy/kivy#4959]
The USE_OPENGL_MOCK environment variable is no longer avoiding inclusion of the <GL/gl.h> headers. This is making it readthedocs.org integration for Kivy projects impossible and [Kivy's own documentation bulids](https://readthedocs.org/projects/kivy/builds/) are now failing.

To work around this for my project I had to temporarily detect the readthedocs.org environment in my own setup.py and pull the [last working version](https://github.com/kivy/kivy/archive/2d5b365747284b029c8a2b3291ca0f4d580e7b86.zip) from git.

There have been a lot of [changes](https://github.com/kivy/kivy/compare/2d5b365747284b029c8a2b3291ca0f4d580e7b86...master), so I'm not sure what's broken. I tried setting the new KIVY_GL_BACKEND environment variable to 'mock' but that did not work either.

**Comment by matham** [comment]
Hmm, that didn't fix it.

**Comment by matham** [comment]
Actually it was fixed, it's just that rtd was not building from master.
