### ISSUE TITLE
Unable to create a package using Pyinstaller for windows. "Unable to find any valuable window provider at all."

### ISSUE THREAD

**Issue by tushutripathi** [kivy/kivy#4963]
### Versions

* Python: 2.7.12
* OS: Windows 10
* Kivy: 1.9.1
* Kivy installation method: pip

### Description

I was following the instructions on this page https://kivy.org/docs/guide/packaging-windows.html#. While following the step for generating spec file, a blank window opened for few seconds and crashed. Though after closing it pyinstaller continued and printed "49805 INFO: 49805 INFO: Building COLLECT out00-COLLECT.toc completed successfully." in the last line.

![bug2](https://cloud.githubusercontent.com/assets/16299282/22399403/cbe72aba-e5c1-11e6-934d-d0d2830d1815.png)

I then changed the spec file as described. Now when I run touchtracer.exe a cmd window opens for a second before giving the below shown error and closing again.

There is no issue in directly running this or other examples app from cmd. The error appear only after packaging with pyinstaller. More ever I also have gstreamer and pygame installed in my computer.
### Code and Logs

![bug](https://cloud.githubusercontent.com/assets/16299282/22399392/7ea049b2-e5c1-11e6-818d-64cb72e57221.png)

**Comment by dessant** [comment]
Pygame must be uninstalled, if that doesn't help, please embed your spec file here in text form. Also enable debug logging in kivy, and share the full runtime logs of the app as text, before and after packaging.

**Comment by tushutripathi** [comment]
@dessant Uninstalling pygame solved the issue. Thanks.

**Comment by AndiEcker** [comment]
@tushutripathi could you please post your .spec file - I am currently struggling to create a windows EXE with pyinstaller.

**Comment by AndiEcker** [comment]
... more details in the kivy-users blog: https://groups.google.com/forum/#!topic/kivy-users/G-k_8Wg4uB4

**Comment by tushutripathi** [comment]
My exe file was exactly same as given here https://kivy.org/docs/guide/packaging-windows.html#. Have you verified manually that kivy.weakmethod exists. I think the problem lies in your kivy installation. Reinstall version '1.9.1' if you are not using anything from development version and try again.

**Comment by AndiEcker** [comment]
Thank you very much for your quick answer.

Yes kivy.weakmethod is in the Lib/site-packages/kivy folder of my python
3.4 installation. The application is also running fine from the console and
from within PyCharm - the error is only occuring with the EXE. I will try
again - maybe next weekend.

2017-01-30 17:23 GMT+00:00 Tushar Tripathi <notifications@github.com>:

**Comment by AndiEcker** [comment]
After some tweaking I think I found the problem within the pyinstaller kivy hook module (C:\Python34\Lib\site-packages\PyInstaller\hooks\hook-kivy.py). At least by hot-patching the code line

    `if is_module_satisfies('kivy >= 1.9.1'):`

into `if True:` the EXE runs without any crash/error (and the warning "Hook disabled because of Kivy version < 1.9.1" disappears from the console output on app startup).
