### ISSUE TITLE
Kivy Module via Python 3.6 vs Kivy - Provider Issues

### ISSUE THREAD

**Issue by ErenPhayte** [kivy/kivy#4966]
I might have found a bug in the Kivy module for Python 3.6. I was setting up Kivy for PyCharm and 
wrote a small app just to test the integration. I did 2 tests, one using Python 3.6 with the Kivy Module and the other using Kivy directly via command line i.e.  kivy main.py

Using kivy via command line worked 100%, however running the app via Pycharm, upon resizing of the window, the form I created disappeared and I was shown a black screen.

I did a bit of home work and found that pygame was deprecated for SDL2. When I looked at the output of kivy vs Python 3.6  I noticed that the Kivy Module was using Provider pygame where as the kivy command lines was using sdl2.

I thought perhaps if I removed pygame, the module would switch to pySDL2 but it didn't:

[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[CRITICAL          ] [Text        ] Unable to find any valuable Text provider at all!
pygame - ModuleNotFoundError: No module named 'pygame'

**I did noticed that kivy itself is using Python 3.5 and not 3.6**

[INFO   ] [Logger      ] Record log in /Applications/Kivy3.app/Contents/Resources/.kivy/logs/kivy_17-01-29_7.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.0 (default, Dec 12 2015, 05:50:29) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[DEBUG  ] [App         ] Loading kv <./passone.kv>
[DEBUG  ] [App         ] kv <./passone.kv> not found
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2

**Comment by AndiEcker** [comment]
Looks like you are using a different python installation/interpreter within
pycharm. I'd try to change in pycharm the python interpreter to the one you
are using on the command line.

2017-01-29 20:41 GMT+00:00 ErenPhayte <notifications@github.com>:

**Comment by ErenPhayte** [comment]
That is correct. I noticed Kivy3.app  came with Python 3.5  however I want
to run it through Python 3.6 using the Kivy Module (installed kivy with
pip3 install kivy)

Kivy3.app works 100% and shows the correct SDL2 provider. But the
installation via Python 3.6 used the pygame provider.

The reason for me to use 3.6 is a) its the latest version of Python and b)
PyCharm doesn't integrate well with Kivy3.app  or at least I cant get it
connected and need to rely on PyCharm's project interpreters to run the
app, which it does, its just this one issue where the provider is showing
as pygame not SDL2  so my initial thinking is the module is not up to date
with what is in Kivy3.app

**Comment by ErenPhayte** [comment]
Found someone who had the same issue as me:

http://stackoverflow.com/questions/39141563/kivy-support-for-sdl2-in-virtualenv?rq=1

**Comment by NikolayBlokhin** [comment]
I have the same error.

**Comment by tito** [comment]
@NikolayBlokhin don't mix up, you used pip install, the OP used Kivy.app. Create an new issue with the full compilation log (which is missing from the stackoverflow) so we can help.

@ErenPhayte The Kivy portable package for OSX has been built with Python 3.5. If you changed the version to 3.6, all the precompiled module will not work, so it is completely normal.

If you want to use Python 3.6, follow the instructions using brew + pip install, so it will compile a version of Kivy for your Python version.
