### ISSUE TITLE
FontAwesome rendering inconsistency between OSes

### ISSUE THREAD

**Issue by nxet** [kivy/kivy#4968]
### Versions

* Python: 3.4
* OS: Windows 10, Debian 8
* Kivy: 1.9.1
* Kivy installation method: pip in both os
* FontAwesome: 4.7

### Description

I'm encountering problems using the FontAwesome iconset in Kivy (SDL2).
The font file and code being used are the same in both Windows and Debian, but while Debian works flawlessly Windows diplays the no-gliph squares (on Kivy). It shouldn't be necessary given the Kivy import, but: the font (otf) is installed on both os and has indeed all the glyphs available - on Windows I can use it on CorelDraw i.e. without any problem.
As you can see from the snippet of code, I'm simply copy-pasting the icons from the cheatsheet into the code editor (Atom), setting them as text for labels styled with the fontawesome property.
Please refer to fontawesome[dot]io/cheatsheet and pick any icon to test the code (as pasting it here probably messed it up). If you don't have the font, the files I used are from v4.7 (*ttf*, *otf* and *woff* working in Debian).

### Code

**fa.py**

```python
from kivy.app import App

class FaApp(App):
	pass

if __name__ == '__main__':
	FaApp().run()
```

**fa.kv**

```python
#:kivy 1.9.1

Label:
	text: ''
	font_name: './fontawesome.ttf'
	font_size: 50
```

### Log

**Windows 10 log**
```
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'4.5.13399 Compatibility Profile Context 15.201.1151.1008'>
[INFO              ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO              ] [GL          ] OpenGL renderer <b'AMD Radeon HD 5450'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <b'4.40'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <18>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Base        ] Start application main loop
```

**Comment by KeyWeeUsr** [comment]
Are those characters by any chance at positions higher than 0xFFFF? [See this comment](https://github.com/kivy/kivy/issues/4741#issuecomment-266042582).

**Comment by nxet** [comment]
It doesn't appear so, at least from what I can tell looking at the cheatsheet.
Also, the tool on torinak[dot]com displays the glyps in a range between F000 and F2E0.

**Comment by KeyWeeUsr** [comment]
Ok then, just confirming something. If that mentioned issue would for some reason work on some gnu/linux distro and not on Windows, it'd be at least some hope for a bug. Seems like it's just not working at all. 😢 

You might want to update to Kivy master version (1.9.2 now) to see if there is a difference between this behavior. If that doesn't help, try with master again, but [explicitly set](https://kivy.org/docs/guide/environment.html) text provider to SDL2.

**Comment by nxet** [comment]
> Ok then, just confirming something
Sure, feel free to ask any other relevant detail I might have left out.

Have you had a chance to run the code I pasted above? That's very basic (of course requires downloading the font) and tested on both Windows and Debian to make sure the problem was easily reproducible.

Thank you

**Comment by KeyWeeUsr** [comment]
Works fine with master both with SDL2 and PIL, so it might be a good thing to update. :)

![image](https://cloud.githubusercontent.com/assets/8825439/22472185/26107090-e7d5-11e6-8a4f-b4f4fe69a85e.png)

**Comment by nxet** [comment]
Oh well then, I've been postponing for too long now and this is the bump I had to hit to finally go ahead installing 1.9.2. Will let you know any development but I'm assuming there should be no further issue, thanks a lot for the heads up!

In regard of the glyphs don't bother checking, they are not in the fontset.

**Comment by nxet** [comment]
After installing today's nightly wheel, the font still doesn't display.
![](https://cloud.githubusercontent.com/assets/16403453/22473152/2bf768b2-e7d8-11e6-86e1-c327133a2c7d.PNG)

**Log:**
*(I'm working only in Win10 now, since Debian doesn't show any issue even with 1.9.1)*

[INFO   ] [Kivy        ] v1.9.2.dev0, git-86e050b, 20170131
[INFO   ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.13399 Compatibility Profile Context 15.201.1151.1008'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon HD 5450'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.40'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <18>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2

**Comment by nxet** [comment]
This was no bug in the end, it was simply the editor erroneously using the pasted text.
When referencing to the glyph directly via its unicode value everything works perfectly, even with 1.9.1 installed. I still need to check if under Debian the rendering works fine, but there should really be no problem now.
Apologies for the waste of time, and thanks again for the help.

`text: u'\F001'`

**Comment by FeralBytes** [comment]
@nxet glad you figured it out.
