### ISSUE TITLE
Exception when creating a CoreImage object from BytesIO object

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [kivy/kivy#4975]
### Versions

* Python: 3.6.0
* OS: Windows 10
* Kivy: 1.9.1
* Kivy installation method: [unofficial Windows binaries repository](http://www.lfd.uci.edu/~gohlke/pythonlibs/#kivy), through pip
* Pillow: 4.0.0

### Description

I am trying to make an Image widget from a Pillow Image that has been edited and is in memory. When trying to produce a `kivy.core.image` `Image` object from a `io.BytesIO` object, an exception is thrown: `Exception: SDL2: Unable to load image.`

After some debugging, I have found the culprit: 

In `img_sdl2.py`, in `ImageLoaderSDL2` class, in `load` function, line 36 reads: `data = filename.read()`. `BytesIO().read()` seems to be deprecated(?) and always produces `b''`. 

Suggested fix: by replacing the said line with `data = filename.getvalue()`, the problem disappears. Negative consequences are yet to be discovered (will update if I find any).

I am sorry that I am unable to test this on the latest development version of kivy or on Python 3.5 . It might be a Python 3.6 related problem. I have not found any similar issues on the internetz.  Example Python file and image provided: [bugtes5t.zip](https://github.com/kivy/kivy/files/753091/bugtes5t.zip)

### Code and Logs

The snippet below demonstrates the problem (imports and `TestApp().run()` omitted):

```python
def get_edited_image():
    # Crop the image
    img = PillowImage.open("pil_image.png")
    cropped = img.crop((0, 0, 48, 48))

    # Save it as bytes
    byte_array = BytesIO()  # empty bytes
    cropped.save(byte_array, format="png")

    img = CoreImage(byte_array, ext="png")
    return ImageWidget(texture=img.texture)

class TestApp(App):
    def __init__(self):
        super().__init__()

    def build(self):
        main = GridLayout()
        main.add_widget(get_edited_image())

        return main

```

When run, it produces the following output:
```
[INFO              ] [Logger      ] Record log in C:\Users\Edvard\.kivy\logs\kivy_17-02-05_58.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'4.5.13464 Compatibility Profile Context 21.19.411.0'>
[INFO              ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO              ] [GL          ] OpenGL renderer <b'AMD Radeon (TM) R9 380 Series'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <b'4.50'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING           ] [Image       ] Unable to load image <<_io.BytesIO object at 0x04010E40>>
 Traceback (most recent call last):
   File "E:/Desktop/bugtes5t/bugtest.py", line 34, in <module>
     TestApp().run()
   File "C:\Python36\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "E:/Desktop/bugtes5t/bugtest.py", line 29, in build
     main.add_widget(get_edited_image())
   File "E:/Desktop/bugtes5t/bugtest.py", line 20, in get_edited_image
     img = CoreImage(byte_array, ext="png")
   File "C:\Python36\lib\site-packages\kivy\core\image\__init__.py", line 510, in __init__
     self.load_memory(arg, ext, filename)
   File "C:\Python36\lib\site-packages\kivy\core\image\__init__.py", line 727, in load_memory
     keep_data=self._keep_data)
   File "C:\Python36\lib\site-packages\kivy\core\image\__init__.py", line 196, in __init__
     self._data = self.load(kwargs.get('rawdata'))
   File "C:\Python36\lib\site-packages\kivy\core\image\img_sdl2.py", line 44, in load
     raise Exception('SDL2: Unable to load image')
 Exception: SDL2: Unable to load image
```

With my monkey patch applied it seems to work as expected:
```
[INFO              ] [Logger      ] Record log in C:\Users\Edvard\.kivy\logs\kivy_17-02-05_59.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'4.5.13464 Compatibility Profile Context 21.19.411.0'>
[INFO              ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO              ] [GL          ] OpenGL renderer <b'AMD Radeon (TM) R9 380 Series'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <b'4.50'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Start application main loop
[WARNING           ] <kivy.uix.gridlayout.GridLayout object at 0x03C691F0> have no cols or rows set, layout is not triggered.
[INFO              ] [Base        ] Leaving application in progress...
```

**Comment by FeralBytes** [comment]
After you apply your patch are you still able to load a normal image directly from disk? I would try multiple types just to be sure.

**Comment by EdvardasDlugauskas** [comment]
Thank you for your response,

Yes, I am able to load images normally from disk. I have tried loading .png, .gif, .bmp and .jpg types and with the monkey patch they are identical. See these images:

![With monkey patch](https://cloud.githubusercontent.com/assets/21359162/22861724/ec603d1e-f128-11e6-8f1d-3d43af1c974f.png)

![Without monkey patch](https://cloud.githubusercontent.com/assets/21359162/22861725/ee997fd2-f128-11e6-9163-0531cad33baf.png)

I am willing to help investigate and test this issue further and ask only for your guidance.

**Comment by FeralBytes** [comment]
Well that is why I was asking. Have you also tested your patched code on Android? Build a APK that has your patched Bytes.IO and perform the same test as above; take a screenshot and post that too. 
Then just to make sure you need to test your patch against Python2 on your system and again post a screenshot.
Then If all are the same then you should open a PR; then it just needs to be tested by a few more members of the community and your fix will be applied to master.

**Comment by matham** [comment]
When you read from a `BytesIO`, you're asking it to read until the first `EOF`. If this file/object has already been read, a subsequent read will return an empty bytes object since we already hit an `EOF`. Have you read this BytesIO object before? 

The solution in this case is to call `byte_array.seek(0)` before passing it again to CoreImage. Although getvalue seems to always return the whole thing.

**Comment by EdvardasDlugauskas** [comment]
@matham Yes, you are correct. `byte_array.seek(0)` fixes the issue. I didn't read the array before, but I suppose using the Pillow Image `image.save(byte_array, ext="png")` made the array seek to the EOF. Judging by [this ](http://stackoverflow.com/a/24920879/6678216)link it's Pillow's fault (and mine, I guess). However, if I add your fix to the code it works with and without my patch applied.

@FeralBytes Should I continue investigating as we have already found a client-side fix? My patch still works with matham's suggestion. I do not really see any way of it breaking legacy code, `byte_array.getvalue()` always returns the whole thing, which is, I suppose, always the intended behavior. Considering my initial problem was an actual "use case", I am all in for it, unless you say otherwise.

I will continue my investigation right away so please tell me if the fix cannot be implemented for any reason so that I don't waste my time with it.

Thanks for your hard work!

**Comment by matham** [comment]
We cannot replace `read` with `getvalue` because filename could be other things besides a `BytesIO` object. E.g. it could be a file object. So I think the best solution is for you to seek to zero before passing it to kivy rather than patching kivy.

**Comment by EdvardasDlugauskas** [comment]
Not even worth `isinstance(filename, BytesIO)`? Thanks anyways!

**Comment by matham** [comment]
I'm not sure. Checking for `BytesIO` and doing that will certainly fix that problem, but other objects passed in will have similar issues. E.g. a passing a file `IO` object that has been partially read will still suffer from the same issue. So then we'd have to fix this for all object types that could be passed in and for some of them there's no `getvalue` which would lead to inconsistencies.

In fact, thinking about it, someone may want to pass a `BytesIO` that has been partially read as the image may be at some offset. But using `getvalue` would disable this as it would always read the whole thing. Although admittingly, it may not be that common.

I think it's better leave it as is because it provides the maximum flexibility. However, adding to the docs a short comment saying that you need to seek to zero if that's where the image starts, may be helpful to future users.
