### ISSUE TITLE
Animated gif flashes

### ISSUE THREAD

**Issue by cayman54** [kivy/kivy#4977]
Hi,
I have a problem with kivy 1.9.2 on my raspberry pi 3.
I have a screen where I load 2 animated gif (I load them as zip files), but it is flashing and the texts of my labels are not displayed.
When I load only 1 gif it works well, but when I load both of them it flashes.
How can I solve that?
thanks in advance

**Comment by dessant** [comment]
You could try disabling caching with the `nocache` property at the same time the Image `source` is set.
https://kivy.org/docs/api-kivy.uix.image.html#kivy.uix.image.Image.nocache

**Comment by dessant** [comment]
If you still have issues after that, please reopen the bug report by following the issue template.
