### ISSUE TITLE
Error in Widget collide_point documentation (Window coordintes should read Widget coordinate) 

### ISSUE THREAD

**Issue by robertour** [kivy/kivy#4983]
I might be wrong but, if not, this is a big mistake since people seem to be already confused with the positioning of widgets.

In the parameters of the documentation, it says:
 x position of the point (in window coordinates)
 y position of the point (in window coordinates)

Doc link: https://kivy.org/docs/api-kivy.uix.widget.html#kivy.uix.widget.Widget.collide_point

But the return value is clearly in coordinates of the parent (in widget coordinates)
  return self.x <= x <= self.right and self.y <= y <= self.top

This line: https://github.com/kivy/kivy/blob/master/kivy/uix/widget.py#L402

**Comment by Zen-CODE** [comment]
Well spotted. Thanks :-)
