### ISSUE TITLE
Can't save stream from IP-camera on Android

### ISSUE THREAD

**Issue by Ormgair** [kivy/kivy#4990]
So, I want to save video from my IP-camera on Android. I save wideo to file with this code:

```
video = cv2.VideoWriter(vname, fourcc, fps, (width,height))
while something==True:
    video.write(cv2.cvtColor(np.array(frame), cv2.COLOR_BGR2RGB))
video.release()
```

It works great on my PC, but it doesn't save video on Android, without any errors, I just can't find my file after that.

I also tried this without any success:
`vname = (App.get_running_app().user_data_dir +'/'+'video.avi')`
`vname = (App.get_running_app().user_data_dir +'video.avi')`
`vname = (Environment.getExternalStorageDirectory().getPath() +'/'+'video.avi')`
`vname = (Environment.getExternalStorageDirectory().getPath() +'video.avi')`

Is there any way to fix this?

**Comment by FeralBytes** [comment]
Well you definitely need to know your paths; the file is likely in this directory:
```python
import os.path
os.path.dirname(os.path.realpath(__file__))
```

**Comment by Ormgair** [comment]
There is no file in this directory. Actually, I think it's because opencv VideoWriter...

**Comment by matham** [comment]
This does not seem to be a problem related to kivy. You need to find out what cv expects the file to be.
