### ISSUE TITLE
Bundle Kivy apps as AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [kivy/kivy#4992]
Would there be interest in bundling Kivy apps as AppImages for Linux?

Being able to export an [AppImage](http://appimage.org/) for Kivy apps would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

If there is enough interest, I can look into it.

**Comment by FeralBytes** [comment]
@probonopd I think it would be a great idea; as right now I only support: Debian; Ubuntu; Linux Mint; and Fedora. But all of these are finicky as I have to ensure each has the right dependencies for the right version of each OS.
But you also need to work out your proposal a little more. I think that it will likely have to be another sub Kivy Project; which will meet resistance from the core-devs as they are already task saturated; unless of course you will work the development mostly on your own and agree to support it for at least the next 2 years. Do you think you can do all of that? If so I will help (Limited Help as I have time, but still I will help); but realize I am not a Kivy developer just another user.

**Comment by dessant** [comment]
@probonopd, it's certainly a great idea, but we do not have the resources at the moment to create and maintain these builds and write end-user app packaging docs for them. If you do feel commited to move forward with this, please share more details about the required work.

**Comment by probonopd** [comment]
Thanks @dessant, I understand. I don't have the capacity to do it either, but am willing to help upstream projects who want to do AppImages. So if at some point in time someone would like to do it, let me know. There are also many people in #AppImage on irc.freenode.net.

**Comment by maltfield** [comment]
It's been 3 years. Has anyone gotten a kivy app to build in an AppImage yet? Is there a guide on how to do it anywhere?

**Comment by probonopd** [comment]
Given that Kivy is written in Python, you might want to check out the following projects:

* https://github.com/niess/python-appimage
* https://github.com/niess/linuxdeploy-plugin-python
* https://github.com/linuxdeploy/linuxdeploy-plugin-conda

**Comment by maltfield** [comment]
@probonopd Thanks.

I was successfully able to package a kivy app into an AppImage. You can see an example of a simple kivy "hello world" app in this gitlab repo, which includes the CI setup to automatically build the AppImage when pushed to master.

 * https://gitlab.com/maltfield/cross-platform-python-gui

Here's the AppImage build script that does most of the heavy lifting:

 * https://gitlab.com/maltfield/cross-platform-python-gui/-/blob/master/build/linux/buildAppImage.sh

The above AppImage build script is executed by gitlab-ci in a Docker container (with debian's buster-slim base image) in GCP. That's setup in the .gitlab-ci file here:

 * https://gitlab.com/maltfield/cross-platform-python-gui/-/blob/master/.gitlab-ci.yml

You can see an example execution output from the AppImage build script running in GCP last night here:

 * https://gitlab.com/maltfield/cross-platform-python-gui/-/jobs/573964832

Note that you can download the helloWorld.AppImage that it produced by clicking "Download" under the "Job artifacts" in the above link. The helloWorld.AppImage is a 47M file.. :/

The following guides were instrumental in helping me set this up:

 * https://kivy.org/doc/stable/installation/installation-linux.html
 * https://kivy.org/doc/stable/guide/basic.html
 * https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps

**Comment by probonopd** [comment]
Hi @maltfield 

> I was successfully able to package a kivy app into an AppImage. 

Very cool! :+1: 

So you did it "the hard way". Did you also check out https://github.com/niess/python-appimage? I think it can make everyone's live easier.

> The helloWorld.AppImage is a 47M file.. :/

Next step would then be to "profile" what Python modules are actually needed by the application, and bundle only those. (I call the process "thinning" or "minimizing, here you can read more about it: https://github.com.cnpmjs.org/niess/linuxdeploy-plugin-python/issues/1) Or did you already do this?

This way you may be able to significantly trim the size down.

**Comment by maltfield** [comment]
> So you did it "the hard way"

idk, I think I did it the easy way? I:

1. used [python-appimage's python3.7 AppImage, extracted it](https://gitlab.com/maltfield/cross-platform-python-gui/-/blob/c3268ee19d3d28ef63b3d651993065fb6e6f5e22/build/linux/buildAppImage.sh#L46) to create a base for my kivy AppDir,
1. [installed kivy in a virtualenv](https://gitlab.com/maltfield/cross-platform-python-gui/-/blob/c3268ee19d3d28ef63b3d651993065fb6e6f5e22/build/linux/buildAppImage.sh#L37), 
1. [rsync'd the contents of the depends into the kivy AppDir](https://gitlab.com/maltfield/cross-platform-python-gui/-/blob/c3268ee19d3d28ef63b3d651993065fb6e6f5e22/build/linux/buildAppImage.sh#L51-55), and
1. [used appimagetoool](https://gitlab.com/maltfield/cross-platform-python-gui/-/blob/c3268ee19d3d28ef63b3d651993065fb6e6f5e22/build/linux/buildAppImage.sh#L114) to turn the AppDir into my app's AppImage

I'll look into thinning, thanks.

**Comment by maltfield** [comment]
fyi, I migrated my repo from gitlab to github as github has native support for CI in MacOS. So if you're looking to build an AppImage out of your kivy app using a workflow with GitHub Actions, checkout this repo:

 * https://github.com/maltfield/cross-platform-python-gui

Unlike gitlab, github's linux nodes in Azure (as opposed to the gitlab linux nodes in GCP) don't support using fuse inside the container, so I ended up modifying the AppImage build script to work natively on Ubuntu (as opposed to in a debian-slim docker container):

 * https://github.com/maltfield/cross-platform-python-gui/blob/af3aa35b671c7429c268ac09c7d4a80acf0ecbff/build/linux/buildAppImage.sh

I'd rather build it in a container for deterministic/portability reasons. It might be possible to first install/load the fuse module on the linux node then install docker and run the container inside the linux node via a single script. I tried to use a GitHub workflow job that installs fuse in the first step of a job, then uses a docker container for the following set of steps of the same job, but this doesn't seem possible with GitHub actions at this time.

You can see the build log of producing an AppImage of my kivy hello world app in GitHub here:

 * https://github.com/maltfield/cross-platform-python-gui/runs/725942261?check_suite_focus=true

**Comment by probonopd** [comment]
> is there a "best practice" for where things should go inside the AppImage (my source code, python depends, etc)? Right now I just put everything in opt

Yes, we recommend to use a FHS-like structure with

```
usr/bin/
usr/share/
usr/lib/
...
```
