### ISSUE TITLE
Kivy install problem

### ISSUE THREAD

**Issue by v44n** [kivy/kivy#4993]
### Versions

* Python :3.5.3
* OS: Windows
* Kivy: 1.9.1
* Kivy installation method:cmd

### Description

I was trying to uninstall kivy, I installed all the Kivy’s dependencies and the angle, but when I put:
 python -m pip install kivy on the cmd some error happend (check the log below)

I tryed to uninstall and install C++ but nothing happends, and i also use the cmd as administrator.

Thanks you for you time and help!

Greetings from Argentina

[kivyinstallLOG.txt](https://github.com/kivy/kivy/files/773128/kivyinstallLOG.txt)

**Comment by matham** [comment]
Kivy 1.9.1 does not support python3.5+. You'll need to use master for that.

**Comment by v44n** [comment]
Fixed! thanks you!
