### ISSUE TITLE
typo in website document in Texture section

### ISSUE THREAD

**Issue by eteamin** [kivy/kivy#4994]
In texture.py line 364 it says that 

> `colorfmt`: str, defaults to 'rgba'

but in https://kivy.org/docs/api-kivy.graphics.texture.html#blitting-custom-data
in the example the first line says that 'create a 64x64 texture, defaults to rgb / ubyte'

but as I have observed it defaults to 'rgba'.
It causes issue when packaged for android because in the mentioned example
`texture.blit_buffer(buf, colorfmt='rgb', bufferfmt='ubyte')`
raises

> I/python  (12498):  Exception: GLES LIMIT: Cannot blit with a different colorfmt than the created texture. (texture has rgba, you passed rgb). Consider setting KIVY_GLES_LIMITS

I use python 2.7
Kivy 1.9.1
buildozer 0.32

Please fix the typo in website documents :)
tnx

**Comment by FeralBytes** [comment]
You forgot to mention your OS; the one when you are not using Android?
Can you give me a more complete example code; a minimal Kivy APP? That will allow me to quickly test and observe the issue first hand; it will also allow for testing any fixes/PR.
This may be a good find; will you start a PR to fix the issue?
Thank you.

**Comment by matham** [comment]
Yeah, it is a typo. As you can see [here](https://github.com/kivy/kivy/blob/master/kivy/graphics/texture.pyx#L556) it does default to `rgba`.

**Comment by eteamin** [comment]
I'm on Ubuntu 14.04 and its all fine. but when I build the app using buildozer for api 14 (Android 4.4) it fails with the exception I mentioned above.

**Comment by matham** [comment]
The reason it works on Ubuntu and not on desktop is described in the `Texture blit` section of https://kivy.org/docs/guide/environment.html#graphics.

**Comment by matham** [comment]
Fixed with https://github.com/kivy/kivy/pull/4995.
