### ISSUE TITLE
kivy slider cursor image doesn't change

### ISSUE THREAD

**Issue by taisreis** [kivy/kivy#4997]
Hello

I'm trying change cursor image of the slider, but it doesn't change.
(kivy 1.9.1)

```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.slider import Slider


class MySlider(BoxLayout):

    def __init__(self, **kwargs):
        super(MySlider, self).__init__(**kwargs)
        self.slider_volume = Slider(min=0, max=1, orientation='vertical')
        self.slider_volume.cursor_image = 'circulo.png'
        self.slider_volume.cursor_disabled_image = 'circulo.png'
        self.add_widget(self.slider_volume)

 
class MySliderApp(App):

    def build(self):
        return MySlider()
         
       
if __name__ == '__main__':
    MySliderApp().run()
```

**Comment by saqib1707** [comment]
@taisreis one possible reason could be that you  have not specified the full path to your circulo.png image.Try to specify the full path or put the .png image in the same directory as the program file. Since slider cursor image changes on my pc with kivy 1.9.1

**Comment by taisreis** [comment]
Hi @saqib1707, I put the image in the same path that the program file and I did an other test with an Rectangle for getting the image and it worked but doesn't on the cursor slider.

```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.slider import Slider
from kivy.graphics import Rectangle


class MySlider(BoxLayout):

    def __init__(self, **kwargs):
        super(MySlider, self).__init__(**kwargs)
        self.slider_volume = Slider(min=0, max=1)
        self.slider_volume.cursor_image = 'circulo.png'
        self.slider_volume.cursor_disabled_image = 'circulo.png'
        self.add_widget(self.slider_volume)

        with self.canvas:
            self.rect = Rectangle(source='circulo.png')

 
class MySliderApp(App):

    def build(self):
        return MySlider()
         
       
if __name__ == '__main__':
    MySliderApp().run()
```

**Comment by KeyWeeUsr** [comment]
Works fine:

![image](https://cloud.githubusercontent.com/assets/8825439/23131495/77d58496-f78a-11e6-80ab-6da3521da54b.png)

**Comment by taisreis** [comment]
In my PC no works:

![capturar](https://cloud.githubusercontent.com/assets/10741574/23136999/4539bd7e-f77e-11e6-9654-fb7641790848.PNG)


I don't know what's happening?

**Comment by akshayaurora** [comment]
@taisreis please include more information about your issue, add details, please use the template provided.

**Comment by taisreis** [comment]
Hello @akshayaurora following more information:

I'm can't change the slider cursor image and I put the image in the same path that the program file and I did an other test with an Rectangle for getting the image and it worked but doesn't on the cursor slider.

* Python: 3.4.3 32 bits
* OS: Windows 8 and I tested in the 10
* Kivy: 1.9.1
* Kivy installation method: PIP

https://gist.github.com/taisreis/9968d70b538e29f38c7dbd139ab7a835

```
from kivy.app import App
from kivy.config import Config

Config.set('graphics', 'width', '300')
Config.set('graphics', 'height', '420')

from kivy.uix.boxlayout import BoxLayout
from kivy.uix.slider import Slider
from kivy.graphics import Rectangle


class MySlider(BoxLayout):

    def __init__(self, **kwargs):
        super(MySlider, self).__init__(**kwargs)
        self.slider_volume = Slider(min=0, max=1)
        self.slider_volume.cursor_image = 'circulo.png'
        self.slider_volume.cursor_disabled_image = 'circulo.png'
        self.add_widget(self.slider_volume)

        with self.canvas:
            self.rect = Rectangle(source='circulo.png')

 
class MySliderApp(App):

    def build(self):
        return MySlider()


if __name__ == '__main__':
    MySliderApp().run()
```

**Comment by akshayaurora** [comment]
You are testing with stable version, 1.9.1. Please test with latest master.

**Comment by taisreis** [comment]
@akshayaurora it works with the latest master version but is safe use it? Because have a warning that using the latest development version can be risk.
