### ISSUE TITLE
Examples: Twisted import error, broken?

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5002]
### Versions

* Python: 3.5
* OS: Win8.1, 64bit
* Kivy: master, wheels

### Description

Twisted example broken

> ImportError: cannot import name '_threadedselect'

can't test on py2 as I don't have the old compiler. Maybe this is just a result of bad py3 compilation? (`pip install twisted`)

**Comment by akshayaurora** [comment]
Confirmed, on OS X, python 3.6

**Comment by akshayaurora** [comment]
This mostly cause the interface in twisted _threadselect is not yet ported to python3. This has been broken with Python3.x since the start then.

I would not call this bug a show stopper cause of this. Retagging for 2.0

**Comment by dessant** [comment]
Duplicate of https://github.com/kivy/kivy/issues/4275.
