### ISSUE TITLE
Examples: Keyboard & KeyboardListener

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5003]
### Versions

* Python: 2.7, 3.5
* OS: Win8.1, 64bit
* Kivy: master, wheels

### Description

Example `examples/keyboard/main.py` dead for py3(.5.3).

> UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 3960

Similar for `examples/widgets/keyboardlistener.py` after pressed modifier (Ctrl, Shift)

> UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 12 ...

**Comment by akshayaurora** [comment]
Both work on python 3.6.0 on OS X,  could you upgrade your python version and test again ?

**Comment by KeyWeeUsr** [comment]
Yep, dead with the same error on 3.6 too. I run in `cmd.exe` and although they changed the encoding in [pep528](https://www.python.org/dev/peps/pep-0528/) and 529, this didn't fix it, so the problem is probably somewhere in the conversion unicode↔bytes

```
 Traceback (most recent call last):
   File "share\kivy-examples\keyboard\main.py", line 222, in <module>
     KeyboardDemo().run()
   File "_\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "share\kivy-examples\keyboard\main.py", line 216, in build
     self.sm.add_widget(KeyboardScreen(name="keyboard"))
   File "share\kivy-examples\keyboard\main.py", line 163, in __init__
     self._add_keyboards()
   File "share\kivy-examples\keyboard\main.py", line 169, in _add_keyboards
     layouts = list(VKeyboard().available_layouts.keys())
   File "_\lib\site-packages\kivy\uix\vkeyboard.py", line 367, in __init__
     self._load_layouts()
   File "_\lib\site-packages\kivy\uix\vkeyboard.py", line 433, in _load_layouts
     basename(splitext(fn)[0]))
   File "_\lib\site-packages\kivy\uix\vkeyboard.py", line 440, in _load_layout_fn
     json_content = fd.read()
   File "_\lib\encodings\cp1250.py", line 23, in decode
     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
 UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 3960: character maps to <undefined>
```

**Comment by matham** [comment]
Have you tried running with `PYTHONLEGACYWINDOWSSTDIO=1` set in the env?

**Comment by KeyWeeUsr** [comment]
Yes, doesn't do anything useful with the error (log is the same).

**Comment by KeyWeeUsr** [comment]
https://github.com/kivy/kivy/commits/e7299f4e7f6eb3ddf773c26a303af1dd52b90e27/kivy/data/keyboards everything since https://github.com/kivy/kivy/commit/bcca12b3032958992d5fea6a3c2fa9d2b6f6b90f up crippled it.

**Comment by KeyWeeUsr** [comment]
The patch fixes the crash + dock/system inconsistency (partially), but it's kind of bad that the dock keyboard returns different stuff than the system one (which I fixed with tuple instance check) mainly because it's present even in `keyboardlistener.py` and there it doesn't return anything from the dock.
