### ISSUE TITLE
Examples: Missing link after separation

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5008]
### Versions

* OS: Windows+ ?

### Description

After the examples wheel separation, there's a missing link between the main wheel and the examples. This can be either solved as a Kivy wheel being dependent on the examples wheel, or with a mention in the documentation, though I'm not sure where.

There was a [`change`](https://github.com/kivy/kivy/blob/master/setup.py#L898) in the setup.py file, which means this might affect even PPA if it uses it and will affect everything that uses `pip install <url>`.

@matham ping 🐱

**Comment by dessant** [comment]
We could publish the stable Kivy_examples wheel on pypi, and just mention it at https://kivy.org/docs/installation/installation-windows.html#installation, without making it a dependency of the main wheel.

The nightly Kivy_examples wheel could be linked at https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation.

**Comment by KeyWeeUsr** [comment]
Yeah, a stable might be good one, but examples might change more often than Kivy itself, which might lead to just annoying issues and forcing users to go directly for the nightly wheel. Or updating the stable wheel more often than on each Kivy release.

Also, [the change](https://github.com/kivy/kivy/blob/master/setup.py#L898) might look for the platform too i.e. if it's windows (and later possibly OSX and linux), then split, but otherwise drag the examples with. Or at least check for the version if the git revision is available i.e. installing from source or something similar.

This part is kind of tricky, because the examples will make the installation from source longer and when someone wants to use them, then the person could just `pip install -e .`.

Although if we want to separate completely, the wheels are probably the only option and the only missing thing is documentation (and maybe stable).
