### ISSUE TITLE
Android: Crash when running APK under an emulator

### ISSUE THREAD

**Issue by ZingBallyhoo** [kivy/kivy#5017]
### Versions

* Python: 2.7.2
* OS: Android
* Kivy: v1.9.2-dev0
* Kivy installation method: P4A

### Description

See P4A issue: https://github.com/kivy/python-for-android/issues/979

When running a Python-for-android build app on and Android AVD / emulator, the app crashes with a UnicodeDecodeError [here](https://github.com/kivy/kivy/blob/master/kivy/graphics/shader.pyx#L632). 

### Code and Logs

Full log: https://gist.github.com/ZingBallyhoo/c47c0fbcbd657fbdb56c20ddb94c4e7e

Logger had this error when I initially tested, but not anymore:
```
01-14 15:33:45.296  1629  1648 I python  :  Traceback (most recent call last):
01-14 15:33:45.297  1629  1648 I python  :    File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/logging/__init__.py", line 865, in emit
01-14 15:33:45.298  1629  1648 I python  :  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 43: ordinal not in range(128)
01-14 15:33:45.310  1629  1648 I python  :  Logged from file __init__.py, line 947
01-14 15:33:45.321  1629  1648 I python  :  Traceback (most recent call last):
01-14 15:33:45.322  1629  1648 I python  :    File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/logging/__init__.py", line 865, in emit
01-14 15:33:45.324  1629  1648 I python  :  UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 41: ordinal not in range(128)
01-14 15:33:45.325  1629  1648 I python  :  Logged from file __init__.py, line 947
```
Now the error is gone, it prints ```[INFO ] [Shader ] fragment shader: <��>```

The error in Kivy:
```
01-14 15:33:45.369  1629  1648 I python  : [CRITICAL] [Window      ] Unable to find any valuable Window provider.
01-14 15:33:45.369  1629  1648 I python  : sdl2 - UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 4: invalid start byte
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/__init__.py", line 67, in core_select_lib
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 139, in __init__
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 795, in __init__
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 284, in create_window
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 947, in create_window
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/instructions.pyx", line 752, in kivy.graphics.instructions.RenderContext.__init__ (kivy/graphics/instructions.c:12152)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 184, in kivy.graphics.shader.Shader.__init__ (kivy/graphics/shader.c:5159)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 693, in kivy.graphics.shader.Shader.vs.__set__ (kivy/graphics/shader.c:12298)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 555, in kivy.graphics.shader.Shader.build_vertex (kivy/graphics/shader.c:10181)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 578, in kivy.graphics.shader.Shader.link_program (kivy/graphics/shader.c:10496)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 632, in kivy.graphics.shader.Shader.get_program_log (kivy/graphics/shader.c:11143)
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/encodings/utf_8.py", line 16, in decode
```

**Comment by FeralBytes** [comment]
And this issue is confirmed by me. Running a API 18 Emulator under AVD with a API 18 APK the app crashes with UnicodeDecodeError in shader.pyx but the same application runs fine on phone with API level of 18.

**Comment by ZingBallyhoo** [comment]
Logger error seems to be related to https://github.com/kivy/kivy/issues/2345

**Comment by FeralBytes** [comment]
@ZingBallyhoo what makes you think that this is related to #2345 ? I don't see how they tie together. Applications that run on actual Android devices will still crash upon printing a Unicode character to console. But that same app will not run for me on AVD, Unicode or not.

**Comment by ZingBallyhoo** [comment]
@FeralBytes 

Take a look at this error:
```
01-14 15:33:45.296  1629  1648 I python  :  Traceback (most recent call last):
01-14 15:33:45.297  1629  1648 I python  :    File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/logging/__init__.py", line 865, in emit
01-14 15:33:45.298  1629  1648 I python  :  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 43: ordinal not in range(128)
01-14 15:33:45.310  1629  1648 I python  :  Logged from file __init__.py, line 947
01-14 15:33:45.321  1629  1648 I python  :  Traceback (most recent call last):
01-14 15:33:45.322  1629  1648 I python  :    File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/logging/__init__.py", line 865, in emit
01-14 15:33:45.324  1629  1648 I python  :  UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 41: ordinal not in range(128)
01-14 15:33:45.325  1629  1648 I python  :  Logged from file __init__.py, line 947
```

When I first tested, Logger threw this error. When I later tested, I did not get this error, instead I got: ```[INFO ] [Shader ] fragment shader: <��>```. ```�``` being a broken Unicode char Android/Python does not understand.

**Comment by FeralBytes** [comment]
I still think they are separated because one says that the ASCII codec can not decode the character; it is ASCII because the console output has been set to be ASCII. Which is separate from Shader.pyx trying to decode a bytes object as UTF-8; which is what I think is occurring for the shader. 
I still do not think the 2 issues should be lumped together at least not until proven otherwise.
@ZingBallyhoo

**Comment by ZingBallyhoo** [comment]
@FeralBytes By 'Logger error' I mean the error caused by the ```logging``` library, not the errror in ```shader.pyx```. The error in logger is exactly what is happening in #2345, just with a different cause. One when actually trying to print a Unicode char, and one where Kivy prints a broken Unicode char unintentionally (because of some weird underlying issue).

**Comment by FeralBytes** [comment]
@ZingBallyhoo I do see what you mean about the link to logging. The deeper I dig the more I realize this is definitely tied to some deep codec issue and a bad byte being decoded.
What I found out is to stop this error I inserted this code:
```python
    import sys
    reload(sys)  # Reload does the trick!
    sys.setdefaultencoding('UTF8')
```
But then then I got the "Unable to Find Any Window Provider Error" As the Shader crashes trying to get the program logger.
Remove or commenting those lines out fixed it again. Very Weird.
Overall inconclusive as to what is going on here.

**Comment by FeralBytes** [comment]
[Logcat Runs](https://gist.github.com/FeralBytes/c6c03fa6d8ce82676fdb6bb69af1bfdd)
I have attached two logcat runs of the same application ran the first time and it is encountering the "Unable to find any valuable Window provider." Error.
The second run this code was added early in initialization before Kivy Starts:
```python
import sys
reload(sys)  # Reload does the trick!
sys.setdefaultencoding('UTF8')
```
The only gotcha is the program does lock up after loading the first kivy screen.
```
D/dalvikvm( 1345): GREF has increased to 201
D/dalvikvm( 1345): GREF has increased to 301
D/dalvikvm( 1345): GREF has increased to 401
D/dalvikvm( 1345): GREF has increased to 501
D/dalvikvm( 1345): GC_CONCURRENT freed 316K, 16% free 2580K/3048K, paused 5ms+2ms, total 93ms
D/dalvikvm(  414): GC_CONCURRENT freed 294K, 70% free 4473K/14880K, paused 7ms+5ms, total 151ms
D/dalvikvm(  414): GC_CONCURRENT freed 9K, 66% free 5073K/14880K, paused 16ms+5ms, total 63ms
D/dalvikvm(  414): WAIT_FOR_CONCURRENT_GC blocked 51ms
D/dalvikvm( 1323): GC_CONCURRENT freed 1434K, 42% free 2590K/4456K, paused 2ms+1ms, total 39ms
```
But the lock up could be my fault; because the program is still responsive as seen here:
```
V/PythonActivity( 1323): onPause()
V/SDL     ( 1323): onPause()
V/SDL     ( 1323): nativePause()
V/SDL     ( 1323): onWindowFocusChanged(): false
E/emuglGLESv2_enc(  575): a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute.
V/SDL     ( 1323): surfaceDestroyed()
```
Any ways I thought maybe this information may one day help in the hunt for this chicken and egg problem.

**Comment by FeralBytes** [comment]
Further Killing the program and then running it a second time; it has now been unpacked on the phone results in "Unable to find any valuable Window provider." again.

**Comment by tito** [comment]
I got this issue today when i wanted to test in emulator. It look like if you try to get the log if the compilation of a shader succedded. If we try to get the log only when failed, it avoid the issue and make the emulator working.

I'm not sure if it is a standard behavior or not, as it's not explicitly written in the documentation, but multiple examples on the net seems to do so. So let's make Kivy follows the same pattern.

**Comment by FeralBytes** [comment]
Thank you @tito .
