### ISSUE TITLE
TextInput paste on Android results in double paste.

### ISSUE THREAD

**Issue by FeralBytes** [kivy/kivy#5018]
### Versions

* Python: 2.7.2
* OS: Android 4.4.2 (API = 19)
* Kivy: 1.9.2.dev0
* Kivy installation method: P4A with setup.py APK using Crystax, SDL, Py2. 
* Keyboard: Samsung Keyboard 

### Description

Paste on Android into kivy.uix.textinput.TextInput. Results in the copied/buffered text being pasted twice (2 times). The text should have only been pasted once. 

### Work Around

~~I have found that using a kivy.uix.codeinput.CodeInput does not exhibit this behavior and instead works correctly. Paste only results in a single Paste; so there is something wrong with TextInput's handling of the paste.~~
~~Note: Using CodeInput adds an additional requirement of pygments.~~
~~Also your input gets colorfully highlighted which is not always desired.~~

### Code and Logs

```python
import kivy

from kivy.app import App
from kivy.uix.textinput import TextInput


class MyApp(App):

    def build(self):
        return TextInput()


if __name__ == '__main__':
    MyApp().run()
```

**Comment by FeralBytes** [comment]
@inclement What are you doing to prevent the double paste in your application?

**Comment by FeralBytes** [comment]
### Work Around
So I have found that the insert_text() method is definitely being called twice in the same frame from a single push of the Bubble Widget's Paste Button. So I wrote this to fix it for the time being. Make sure in the widget's __init__() method you define self.last_paste = None.
```python
def insert_text(self, substring, from_undo=False):
        # Prevent double paste until kivy is fixed.
        if self.last_paste != kivy.clock.Clock.get_time():
            self.last_paste = kivy.clock.Clock.get_time()
            super(SearchTextInput, self).insert_text(substring, from_undo)
```

**Comment by dessant** [comment]
Is the [paste](https://github.com/kivy/kivy/blob/49b153959dd329205890939c036c0bc0a49639b6/kivy/uix/textinput.py#L1714) method also called twice?

**Comment by dessant** [comment]
Please also check if the bug is present when pasting with CTRL+V.

**Comment by FeralBytes** [comment]
On Linux Mint 18.1 using Python2 Ctrl+V resulted in a single trigger of paste() followed by insert_text(). As desired.
Pasting in Android 4.4.2 via the Samsung Keyboard but really via using the Bubble Widget that appears after long pressing on the TextInput resulted in a call to paste() followed by a call to insert_text() followed by a call to paste() followed by a call to insert_text().
So yes on Android the paste method is also called twice in the same frame.
Do you want me to install the "Hacker's Keyboard" on Android so that I can test Ctrl+V on Android?

**Comment by dessant** [comment]
Yeah, that would be nice.
There is a similar issue reported for iOS only (on_release dispatched twice). Have you disabled multitouch from config by any chance? https://github.com/kivy/kivy/issues/3274

**Comment by FeralBytes** [comment]
OK I will install the "Hacker's Keyboard" on Android later on and give it a try with Ctrl+V.
After that I will check if multi-touch is disabled. If it is I will re-enable it for Android. 
But in both cases I will check for multiple button presses from a single button press are occurring (on_release). 
However it is unlikely that my normal buttons are receiving double clicks; if they were it would probably cause more issues with my message passing system or at least I think I would see the message twice; but I could be wrong or may be catching it else where. I will dig deeper.
I will also try to catch the TextInput's -> Buble -> Paste Button -> on_release() method. To see if it is being triggered twice in the same frame.
Note to self: [Direct Link to iOS issue with more details](https://github.com/kivy/kivy-ios/issues/129)

**Comment by KeyWeeUsr** [comment]
Funny, it's probably third time I see an issue related to pasting something on android... and I can't reproduce even with `mouse = mouse,disable_multitouch` in INI (I hope it's right).

4.4.2(stock), Samsung Galaxy Note 2, api 14. So, either I'm missing something, or the newer api broke pasting for us? Could you test with api 14 if it fixes the issue?

**Comment by FeralBytes** [comment]
Yes my code does currently contain:
```python
kivy.config.Config.set('input', 'mouse', 'mouse,disable_multitouch')
```
Also @dessant you are correct; all of my buttons are receiving all events twice.
And for Reference Test 1 & 2 are using API 18  Crystax Py2
Test 1: Installed Gboard (Google Keyboard), pasting with it as the keyboard but using the bubble widget still resulted in the double call to both paste() and insert_text().
Test 2: Installed Hacker's Keyboard, attempting to paste with Ctrl+V resulted in this traceback:
```
I/python  ( 9094): UnicodeDecodeError EXCEPTION IN /home/wolfrage/0.Projects/EzTunes/src/build/bdist.android-armeabi-v7a/eztunes/main.py, LINE #38 '': 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte 
I/python  ( 9094): Python for android ended.
```
For Test 3 API 14 Crystax Py2 will be used. A Question, should I have to do a clean of P4A first; the compile still went very quickly even though I changed the API from 18 to 14?
Test 3: Pasted using Gboard keyboard but via the bubble widget; still resulted in a double call of paste() and insert_text() methods. Also all of my buttons are receiving double touch events.

For Test 4 API 18 Crystax Py2, but going to comment out the Config setting for disable_multitouch.
Test 4: Pasted via the bubble widget and it works as in only one call of both paste() and insert_text() methods. Also all of my buttons are now only receiving a single touch event for each type of touch.
\o/
### Work Around:
Do not set the Config to disable multi-touch on Android. Do not do:
```python
kivy.config.Config.set('input', 'mouse', 'mouse,disable_multitouch')
```
@dessant what would you like as a next step? Close the issue?

**Comment by dessant** [comment]
@FeralBytes, thanks for following up and debugging, we can continue tracking this issue at https://github.com/kivy/kivy/issues/3274. The CTRL+V crash likely deserves a new bug report.
