### ISSUE TITLE
Error link glew on windows

### ISSUE THREAD

**Issue by LudovicGuerra** [kivy/kivy#5021]
Hi all.
I try to install kivy with pip install, but i got an error i can't get rid off

```
    context.obj : error LNK2001: unresolved external symbol __glewIsRenderbuffer
    context.obj : error LNK2001: unresolved external symbol __glewIsFramebuffer
    context.obj : error LNK2001: unresolved external symbol __glewGetRenderbufferParameteriv
    context.obj : error LNK2001: unresolved external symbol __glewDeleteProgram
    context.obj : error LNK2001: unresolved external symbol __glewFramebufferTexture2D
    context.obj : error LNK2001: unresolved external symbol __glewFramebufferTexture3D
    context.obj : error LNK2001: unresolved external symbol __glewRenderbufferStorage
    context.obj : error LNK2001: unresolved external symbol __glewCheckFramebufferStatus
    context.obj : error LNK2001: unresolved external symbol __glewDeleteRenderbuffers
    context.obj : error LNK2001: unresolved external symbol __glewDeleteFramebuffers
    context.obj : error LNK2001: unresolved external symbol __glewFramebufferRenderbuffer
    context.obj : error LNK2001: unresolved external symbol __glewGenFramebuffers
    context.obj : error LNK2001: unresolved external symbol __glewFramebufferTexture1D
    context.obj : error LNK2001: unresolved external symbol __glewBindRenderbuffer
    context.obj : error LNK2001: unresolved external symbol __glewBindFramebuffer
    context.obj : error LNK2001: unresolved external symbol __glewDetachShader
    context.obj : error LNK2001: unresolved external symbol __glewGenRenderbuffers
    context.obj : error LNK2001: unresolved external symbol __glewGenerateMipmap
    context.obj : error LNK2001: unresolved external symbol __glewDeleteShader
    context.obj : error LNK2001: unresolved external symbol __glewGetFramebufferAttachmentParameteriv
    context.obj : error LNK2001: unresolved external symbol __glewDeleteBuffers
    build\lib.win-amd64-3.6\kivy\graphics\context.cp36-win_amd64.pyd : fatal error LNK1120: 21 unresolved externals

```

I use python 3.6, installed cython 0.24.1 (needed for kivent). Also installed all other dependency.
Im on windows10 x64
I also donwloaded glew2.0 and added dll lib and header under visual folder as asked on the glew website

After 2 days searching no idea when it comes from.

Thank you for your help !

**Comment by KeyWeeUsr** [comment]
I believe you've tried exactly this command:

    pip install kivy

on py3.6 and that uses version 1.9.1, however MSVC compiler and basically all Py3.5+ support was introduced only recently in the master branch (X-mas) + a _lot_ of stuff changed in the graphics core regarding this support.

However, there were even unofficial wheels made before for 1.9.1, though _how_ is unknown.

Please use at least nightly [wheels](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation) or compile from source (depends on if you want to compile that much):

    pip install https://github.com/kivy/kivy/zipball/master

**Comment by LudovicGuerra** [comment]
Perfect answer, clear and direct. Thank you a lot.
I have now all possibilities explained.
Problem solved, have a nice day !
