### ISSUE TITLE
Ctrl+V on Android Causes Application Crash

### ISSUE THREAD

**Issue by FeralBytes** [kivy/kivy#5023]
### Versions

* Python: 2.7.2
* OS: Android
* Kivy: 1.9.2-dev0
* Kivy installation method: P4A Setup.py Crystax SDL2
* Hacker's Keyboard: v1.39.3 
    ( https://github.com/klausw/hackerskeyboard/tree/master/java )
### Description
When using an Android Keyboard that has the Ctrl key and attempting to paste using Ctrl+V the application crashes with the error below. But using the same android keyboard on Google search or Firefox; these programs paste correctly the buffered data.
It would also be good to test other Android Keyboards that offer the ctrl key. But I do not have time right now to do so. 
### Code and Logs
Utilize a TextInput Wdiget for pasting into.
```python
import kivy
from kivy.app import App
from kivy.uix.textinput import TextInput

class MyApp(App):
    def build(self):
        return TextInput()

if __name__ == '__main__':
    MyApp().run()
```
* Produced Error is below:
```
I/python  ( 9094): UnicodeDecodeError EXCEPTION IN /home/wolfrage/0.Projects/EzTunes/src/build/bdist.android-armeabi-v7a/eztunes/main.py, LINE #38 '': 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte 
I/python  ( 9094): Python for android ended.
```

**Comment by bit-garden** [comment]
I can confirm python 3.5, kivy 1.10, this issue still exists.

**Comment by tshirtman** [comment]
I can copy/paste unicode text in recent kivy apps, i assume this is fixed, at least for python3, closing, feel free to reopen or open a new one if similar bugs are observed.
