### ISSUE TITLE
Kivy: Error Unable to load image

### ISSUE THREAD

**Issue by Arc1509** [kivy/kivy#5029]
### Versions

* Python: 2.7.13
* OS: Windows 7
* Kivy: 1.9.1
* Kivy installation method:

### Description

I have created a bot using chatter bot and packed it using pyinstaller. when I am trying to run the entire package in a machine where I have not done installation of Python and Kivy I am getting below error 

[WARNING           ] Image: Unable to load image <C:\Users\AE620~1.ARU\AppData\Local\Temp\_MEI18~1\kivy_install\data\glsl\default.png>
[CRITICAL          ] Window: Unable to find any valuable Window provider at all!
sdl2 - Exception: SDL2: Unable to load image
  File "Lib\site-packages\kivy\core\__init__.py", line 67, in core_select_lib
  File "Lib\site-packages\kivy\core\window\window_sdl2.py", line 138, in __init__
  File "Lib\site-packages\kivy\core\window\__init__.py", line 722, in __init__
  File "Lib\site-packages\kivy\core\window\window_sdl2.py", line 255, in create_window
  File "Lib\site-packages\kivy\core\window\__init__.py", line 897, in create_window
  File "kivy\graphics\instructions.pyx", line 756, in kivy.graphics.instructions.RenderContext.__init__ (kivy\graphics\instructions.c:10729)
  File "Lib\site-packages\kivy\core\image\__init__.py", line 512, in __init__
  File "Lib\site-packages\kivy\core\image\__init__.py", line 700, in _set_filename
  File "Lib\site-packages\kivy\core\image\__init__.py", line 430, in load
  File "Lib\site-packages\kivy\core\image\__init__.py", line 198, in __init__
  File "Lib\site-packages\kivy\core\image\img_sdl2.py", line 42, in load

[CRITICAL          ] App: Unable to get a Window, abort.
[WARNING           ] stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL          ] App: Unable to get a Window, abort.
[WARNING           ] stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL          ] App: Unable to get a Window, abort.

I have already tried the below two fixes 
Fix 1:
import os
os.environ['KIVY_IMAGE'] = 'pil,sdl2'

Fix 2:
Copying the below dll file and setting environment variable
libpng16-16

I am attaching the error logs.
[kivy_17-02-28_5.txt](https://github.com/kivy/kivy/files/806786/kivy_17-02-28_5.txt)

Please let me know what can be done to fix this. 
### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by KeyWeeUsr** [comment]
Try packaging it with master (even with wheels is ok) and the latest deps. It worked fine for me.

**Comment by Arc1509** [comment]
I am a newbie to kivy ...could you please provide me bit more details

**Comment by KeyWeeUsr** [comment]
Install newer kivy version e.g. via [wheels](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation) and repackage.

**Comment by dessant** [comment]
Maybe the spec file is not correct, please follow https://github.com/kivy/kivy#support for getting help.

**Comment by davied9** [comment]
I've encountered the simular situation,  I package my app by PyInstaller with following configuration
Versions
  Python: v3.5.2
  OS: Windows 7
  Kivy: 1.10.0
  Kivy installation method: follow wiki of kivy on github

then I run the package on another computer which has python 3.7.0b4, this "sdl2 - Exception: SDL2: Unable to load image" error showed up, I checked the path, the "default.png" has been packaged.

the following logs are two times of running

[kivy_18-06-20_0.txt](https://github.com/kivy/kivy/files/2117531/kivy_18-06-20_0.txt)
[kivy_18-06-20_1.txt](https://github.com/kivy/kivy/files/2117532/kivy_18-06-20_1.txt)

**Comment by dolang** [comment]
Interesting. I've tried to help someone just yesterday who has this symptom, but a in a different environment (win10, py36). Deps are installed, the image is there, yet it fails to load. Myself, I hadn't encountered this error before.

Can you give us some more information? What bitness are source and target systems? Both Windows 7? The Python version on the target system shouldn't matter btw, PyInstaller packages an interpreter.

The error itself is pretty vague and unhelpful, I'm afraid. The code that leads to it could be improved, imho. There's no clue to as why it fails to load the image.

Things you could try:
* What happens if you prepend the path of the folder containing the SDL2 binaries to your `PATH` before starting it?  (search for `SDL2.dll` or `SDL2_image.dll`)
* Maybe you'd want to package `pillow` as well, and set the `KIVY_IMAGE` [environment variable](https://kivy.org/docs/guide/environment.html) to `pil`.

**Comment by bionoid** [comment]
> There's no clue to as why it fails to load the image.

Well, the code and image file is known to work on a lot of systems, and the failure happens when packaged with pyinstaller... I think most likely cause is missing libpng dll, or zlib which it requires

**Comment by dolang** [comment]
> There's no clue to as why it fails to load the image.

https://github.com/kivy/kivy/blob/master/kivy/core/image/_img_sdl2.pyx#L119-L123

Specifically, I meant that this is missing a call to `IMG_GetError()` and the error could happen both in `IMG_Load()` and `load_from_surface()`, because the error only indicates that `NULL` was returned. But there's no way to tell which of those two calls did that.

Missing libraries is one possibility, but the case I had yesterday was someone who simply installed Kivy and wanted to try it for the first time, not someone who used PyInstaller. :thinking:

**Comment by bionoid** [comment]
> the error could happen both in IMG_Load() and load_from_surface()

Ah yes for sure, error reporting would be useful! #5300 adds some to `load_from_surface`, applying it could be worth a shot if you're running out of better things to try.. 

> but the case I had yesterday was someone who simply installed Kivy and wanted to try it for the first time, not someone who used PyInstaller.

Hm interesting, was that failing with the exact same message & on the same image file? Link to discussion/logs?

**Comment by dolang** [comment]
> Ah yes for sure, error reporting would be useful! #5300 adds some to load_from_surface, applying it could be worth a shot if you're running out of better things to try..

Nice! But I haven't yet run into that error myself, and I'll still have to try to reproduce it.

> Hm interesting, was that failing with the exact same message & on the same image file? Link to discussion/logs?

Yes, it was on #kivy. One log is here: https://pastebin.com/P4sz940F

**Comment by bionoid** [comment]
Yeah that's pretty weird; in @davied9's log it has a suspect path (``E:\DAV\...``) for the failing PNG, that may be a clue, it probably should be looking in the pyinstaller interpreter's site-packages, which is unlikely to be at this location... ? 

As for the IRC log, the only thing that strikes me is that it's using a 32-bit Python interpreter. I'm not sure how widely used/tested that is on Windows? Could maybe be a mismatch with something in `kivy.deps.sdl2` (or elsewhere) built for 64-bit, causing the call to fail?

**Comment by tshirtman** [comment]
Can you share your pyinstaller spec file? maybe something is wrong with it? make sure the sdl2/glew deps are included using Tree on windows, i don't think pyinstaller does it by default, for reference here is an example spec file from one of my projects.

```

**Comment by davied9** [comment]
@dolang @bionoid  First, thanks a lot for the advices.
I've tried add 
        import re, os
        os.environ['KIVY_IMAGE'] = 'pil,sdl2'
to my code [here](https://github.com/davied9/LANRemoteController/blob/workspace_dav/Server/ServerUI.py)
and test two times of build with
        - Python: v3.5.2
        - OS: Windows 10 x64  (tag: platform 1)
        - Kivy: 1.10.0
and 
        - Python: v2.7.14
        - OS: Windows 7 x64 (tag: platform 2)
        - Kivy: 1.10.0
and then run on our meeting room computer with Windows7 x64
the same error , following are the logs:
        - platform1 : [kivy_18-06-21_1.txt](https://github.com/kivy/kivy/files/2121774/kivy_18-06-21_1.txt) [kivy_18-06-21_0.txt](https://github.com/kivy/kivy/files/2121775/kivy_18-06-21_0.txt)
         - platform2 : [kivy_18-06-21_3.txt](https://github.com/kivy/kivy/files/2121776/kivy_18-06-21_3.txt)[kivy_18-06-21_2.txt](https://github.com/kivy/kivy/files/2121777/kivy_18-06-21_2.txt)
         
this [direcotry](https://github.com/davied9/LANRemoteController/tree/workspace_dav/dist) contains the builds I refered:
       - server_win32.rar                      yesterday build
       - server_win10_python35.rar     platform 1 tagged above
       - server_win7_py27.rar              platform 2 tagged above
       
> Things you could try:
> - What happens if you prepend the path of the folder containing the SDL2 binaries to your PATH before starting it? (search for SDL2.dll or SDL2_image.dll)
> - Maybe you'd want to package pillow as well, and set the KIVY_IMAGE environment variable to pil.
I've found sdl2.dll in my build direcotry, so I  `add path` did not help (which I've tried).

Although all the builds works allright on my develop computers, but I'm trying make a release for the meetting room computer. And this phonomenom seems to be missing something, but what's that? 

Thanks for your time.

**Comment by davied9** [comment]
@tshirtman 
here is the spec file, this is on Windows7 with python27

# -*- mode: python -*-

block_cipher = None


a = Analysis(['Server\\ServerUI.py'],
             pathex=['E:\\solutions\\LRC'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='server',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='server')

**Comment by davied9** [comment]
@tshirtman Thanks for the format thing, I'll try to adapt my spec file.

**Comment by davied9** [comment]
@tshirtman  For my situation, after 
'''
*([Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)])
'''
added to .spec file, build woks on that machine,  just for the record.

Thanks a lot.
