### ISSUE TITLE
Kivy Collision with garden

### ISSUE THREAD

**Issue by ballsystemlord** [kivy/kivy#5031]
Greetings
Python 3.4.2
Gentoo Linux ~1 month Up-to-date
kivy-garden-0.1.1
Portage-2.3.3
Kivy installs an executable which collides with garden, a game.
The game garden was here before kivy, so I think it aught to have precedence. Garden was created by Linley Henzel and is known in Debian Linux as garden-of-coloured-lights.
I am reporting it here instead of locally as I imagine that you will face future problems in other Linux OSes with this.
Thanks,
David

**Comment by KeyWeeUsr** [comment]
I'm not sure if it's really a problem for us. We can't just escape everything with our own prefix just because someone has already used a common english word for own project. Maybe a useful thing to do would be putting the game executable to [its rightful place](http://askubuntu.com/a/165808) i.e. `/usr/games`, therefore it wouldn't collide with our library. I guess the game is treated just like a common application, not like a **game**.

**Comment by ballsystemlord** [comment]
On Wed, 01 Mar 2017 13:27:17 -0800
Peter Badida <notifications@github.com> wrote:

> I'm not sure if it's really a problem for us. We can't just escape
> everything with our own prefix just because someone has already used a
> common english word for own project. Maybe a useful thing to do would
> be putting the game executable to [its rightful
> place](http://askubuntu.com/a/165808) i.e. `/usr/games`, therefore it
> wouldn't collide with our library. I guess the game is treated just
> like a common application, not like a **game**.
> 

But then when I type
% garden
only one of the two executables will be run, and I'll need to
enter a complete path for the other one (or alias it).
As for not escaping, eventually we'll all have to escape common English
words, the amount of Linux programs will only grow over time, esp. as the
community grows.
I really expected a more understanding reply, not a hard-nosed "We want
it our way no mater what it breaks", type approach.

**Comment by KeyWeeUsr** [comment]
It's not a hard-nosed approach, it's that game's problem that it isn't packaged as a game and in an appropriate folder (and creates collisions). As you said, you can alias it and that's also a recommended approach for such collisions. Or just rename it. The `garden` executable is just a [python file](https://github.com/kivy-garden/garden/blob/master/bin/garden).
