### ISSUE TITLE
Kivy crashes with "RuntimeError: release unlocked lock"

### ISSUE THREAD

**Issue by quietopus** [kivy/kivy#5039]
### Versions

* Python: 3.6, x64 (virtualenv)
* OS: Windows 10, x64
* Kivy: Kivy-1.9.2.dev0-cp36-cp36m-win_amd64.whl
* Kivy installation method:

1. Updated an already-installed _Visual Studio 2015_ to include _Visual C++_ (_Common Tools for Visual C++_, Microsoft _Foundation Classes for C++_, and _Windows XP Support for C++_) and _Python Tools for Visual Studio (January 2017)_.

2. Created a directory called `C:\projects\kivy-bug`, 

3. Downloaded `Kivy-1.9.2.dev0-cp36-cp36m-win_amd64.whl`, from [`https://kivy.org/downloads/appveyor/kivy/Kivy-1.9.2.dev0-cp36-cp36m-win_amd64.whl`](https://kivy.org/downloads/appveyor/kivy/Kivy-1.9.2.dev0-cp36-cp36m-win_amd64.whl) and placed it in `C:\projects\kivy-bug`.
4. Installed Python 3.6 into `C:\tools\Python\36`.
5. Did the following from a command terminal with Administrator privileges:
```
cd C:\projects\kivy-bug
virtualenv -p C:\tools\Python\36\python.exe py36
.\py36\Scripts\activate
python -m pip install --upgrade pip wheel setuptools
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
python -m pip install kivy.deps.gstreamer
python -m pip install Cython
python -m pip install Kivy-1.9.2.dev0-cp36-cp36m-win_amd64.whl
```

### Description
Cannot run any of the kivy examples. After a seemingly successful installation with no warnings or errors, kivy invariably fails when a kivy example script is run. The error thrown is `RuntimeError: release unlocked lock`.

### Code and logs
After the above installation, did the following in the same command terminal:
```
cd C:\projects\kivy-bug
git clone git@github.com:kivy/kivy.git kivy
cd kivy
python ./examples/animation/animate.py
```
The Result was:
```
[INFO   ] [Logger      ] Record log in C:\Users\james_000\.kivy\logs\kivy_17-03-04_37.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-9f2daa0, 20170302
[INFO   ] [Python      ] v3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.3.0 - Build 20.19.15.4531'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4400'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <b'4.30 - Build 20.19.15.4531'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "./examples/animation/animate.py", line 42, in <module>
     TestApp().run()
   File "C:\projects\kivy-bug\py36\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "./examples/animation/animate.py", line 37, in build
     on_press=self.animate)
   File "C:\projects\kivy-bug\py36\lib\site-packages\kivy\uix\behaviors\button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "C:\projects\kivy-bug\py36\lib\site-packages\kivy\uix\label.py", line 291, in __init__
     self._trigger_texture()
   File "kivy\_clock.pyx", line 75, in kivy._clock.ClockEvent.__call__ (kivy\_clock.c:2223)
     self.clock._lock_release()
 RuntimeError: release unlocked lock
```

**Comment by inclement** [comment]
Thanks for the report.

@matham was this introduced by the recent change to Clock events returning True? I remember a note about that. Do we have a plan to fix it?

**Comment by matham** [comment]
Should be fixed in master already. Can you double check. Maybe try the wheel generated today.

**Comment by quietopus** [comment]
Works now. Thanks!

Specifically, from the same project directory described in the original post, did the following:
1. Got `Kivy-1.9.2.dev0.20170304.1ef5f2fb-cp36-cp36m-win_amd64.whl`, generated March 4, 2017, from [https://kivy.org/downloads/appveyor/kivy/Kivy-1.9.2.dev0.20170304.1ef5f2fb-cp36-cp36m-win_amd64.whl](https://kivy.org/downloads/appveyor/kivy/Kivy-1.9.2.dev0.20170304.1ef5f2fb-cp36-cp36m-win_amd64.whl).
2. Replaced `Kivy-1.9.2.dev0-cp36-cp36m-win_amd64.whl` (generated March 3.2017) with `Kivy-1.9.2.dev0.20170304.1ef5f2fb-cp36-cp36m-win_amd64.whl` in `C:\projects\kivy-bug`.
3. Executed the following:
```
cd C:\projects\kivy-bug
.\py36\Scripts\activate
python -m pip uninstall kivy
python -m pip install Kivy-1.9.2.dev0.20170304.1ef5f2fb-cp36-cp36m-win_amd64.whl
cd kivy
python .\examples\animation\animate.py
```

The example ran successfully, without any errors.
