### ISSUE TITLE
Error when installing on OS X Sierra

### ISSUE THREAD

**Issue by joa77** [kivy/kivy#5041]
I tried installing the latest stable version of kivy  with the command `USE_OSX_FRAMEWORKS=0 pip3 install kivy`, but got a huge list of error and this red error description:

`Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/m3/x7czn_3905q_m7x2yk9660dm0000gn/T/pip-build-4qt032fm/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/m3/x7czn_3905q_m7x2yk9660dm0000gn/T/pip-uup2bdyk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/m3/x7czn_3905q_m7x2yk9660dm0000gn/T/pip-build-4qt032fm/kivy/`

**Comment by jbillhei** [comment]
If you scroll up in the output, do you get a line that looks something like this?

In file included from /usr/local/Cellar/glib/2.52.0/include/glib-2.0/glib/galloca.h:32:
    /usr/local/Cellar/glib/2.52.0/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
      G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));


If so, I managed to get it to install by adding an ARCHFLAGS to the install command.  It looked like this:

USE_OSX_FRAMEWORKS=0 ARCHFLAGS="-arch x86_64" pip install --no-cache-dir kivy

**Comment by joa77** [comment]
That did the trick! Thank you
