### ISSUE TITLE
Slow performance when building a list with a lot of widgets

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#5047]
### Versions

* Python: 2, 3
* OS: Android
* Kivy: 1.9.1
* Kivy installation method: install apk on device

### Description

Faced a problem in Kivy: slow performance when building a list with a lot of widgets.  For example, I use a self-made
widget that consists of 6-7 kivy
widgets. If I want to list ( ScrollView ) 50 of my self-
made widgets (50 * 7 = 350 kivy
widgets), then it will take 10 to
30 seconds on the mobile phone. This makes kivy absolutely
unsuitable for use in production. What do you advise? Is it
possible to use the Numba with
kivy or there are other ways to
make the kivy widgets build
faster?

**Comment by KeyWeeUsr** [comment]
See [RecycleView](https://kivy.org/docs/api-kivy.uix.recycleview.html) or its alternative(s) and the [support](https://github.com/kivy/kivy#support) section. If you spawn a lot of widgets hard on rendering in a small amount of time, then it's obvious it'll be slow in a limited environment. Also, consider updating to the master version as a lot of bugs are fixed from `1.9.1`.
