### ISSUE TITLE
ActionBar's ActionButton sometimes behave like ToggleButton

### ISSUE THREAD

**Issue by Fogapod** [kivy/kivy#5051]
### Versions

* Python: 2.7
* OS: android
* Kivy: master
* toolchain: android_new

### Description

```ActionButton``` can remain pressed after ```on_press``` and ```on_release``` events. Also sometimes it's hard to press this button because ActionBar closes emideatly before ```on_press``` event can start. 

Here is a screenshot of pressed ```ActionButton```:
![_20170309_081004](https://cloud.githubusercontent.com/assets/22667809/23736833/d383a08a-049f-11e7-8564-a9b931df291c.JPG)

**Comment by KeyWeeUsr** [comment]
Worked fine for me, so probably add some reproducible code here. Also, try it with the latest master, as there was a [change in the ActionDropDown](https://github.com/kivy/kivy/commit/b9ef4cf68fb994db8e76f9e2d8eb8fa8f5a9f62e).

**Comment by Fogapod** [comment]
@KeyWeeUsr this fixed my problem. Closing Issue
