### ISSUE TITLE
multistroke: cannot handle single horizontal or vertical strokes

### ISSUE THREAD

**Issue by VasLem** [kivy/kivy#5057]
When I am using multistroke.py with a template of a horizontal or a vertical line, the method scale_dim throws an error 'scale_dim() called with invalid points'. This is natural to happen, as the bounding box computed beforehand has 0 height or 0 width correspondingly. I think that this error has no reason to exist, or the logical or might have to be replaced with a logical and in line 1352.

**Comment by llfkj** [comment]
This was fixed in #4803

**Comment by KeyWeeUsr** [comment]
Update to the latest Kivy version or just copy the contents of the `multistroke.py` file as the [changes](https://github.com/llfkj/kivy/commits/b2bf7ad0469ccfe05d3640f12e700f74ce1b800b/kivy/multistroke.py) for that file are in quite small amount between 1.9.1 and master. ^^

**Comment by VasLem** [comment]
Oh I was using stable release, you are right!
