### ISSUE TITLE
Winpygame failed on Raspberry Pi.

### ISSUE THREAD

**Issue by rossp3904** [kivy/kivy#5059]
### Versions

* Python: 3.4 and 2.7
* OS: works on Windows 10. doesn't work on Raspbian Jessie
* Kivy: Windows... 1.9.2  Raspbian 1.8.0 (can't figure out how to upgrade it)
* Kivy installation method: Command Line

### Description

My kivy file works on Windows, where I created it, but I can't get it to open on Raspbian. Also I can't get my custom settings menu to load only the original kivy... but that's a seperate issue.

### Code and Logs
Log:
`[INFO              ] Kivy v1.8.0
[INFO              ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_17-02-27_24.txt
[INFO              ] [Factory     ] 157 symbols loaded
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
[DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[INFO              ] [Text        ] Provider: pygame
[DEBUG             ] [Window      ] Ignored <egl_rpi> (import error)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[WARNING           ] [WinPygame   ] Video: failed (multisamples=2)
[WARNING           ] [WinPygame   ] trying without antialiasing
[DEBUG             ] [Window      ] Display driver x11
[DEBUG             ] [Window      ] Actual window size: 800x600
[DEBUG             ] [Window      ] Actual color bits r8 g8 b8 a0
[DEBUG             ] [Window      ] Actual depth bits: 24
[DEBUG             ] [Window      ] Actual stencil bits: 8
[DEBUG             ] [Window      ] Actual multisampling samples: 0
[INFO              ] [GL          ] OpenGL version <b'3.0 Mesa 13.0.0'>
[INFO              ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO              ] [GL          ] OpenGL renderer <b'Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)'>
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <b'1.30'>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <32>
[DEBUG             ] [Shader      ] Fragment compiled successfully
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [ImagePygame ] Load </usr/lib/python3/dist-packages/kivy/data/glsl/default.png>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG             ] [Cache       ] register <kv.loader> with limit=500, timeout=60s
[INFO              ] [Loader      ] using a thread pool of 2 workers
[DEBUG             ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0s
[DEBUG             ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0s
[DEBUG             ] [App         ] Loading kv </home/pi/Desktop/SW_Python_Files/SW_Py/GUI/uppage1.kv>
[DEBUG             ] [App         ] kv </home/pi/Desktop/SW_Python_Files/SW_Py/GUI/uppage1.kv> not found
[INFO              ] [OSC         ] using <multiprocessing> for socket
[DEBUG             ] [Base        ] Create provider from mouse
[DEBUG             ] [Base        ] Create provider from probesysfs,provider=hidinput
[DEBUG             ] [ProbeSysfs  ] using probsysfs!
[DEBUG             ] [ProbeSysfs  ] found device: FT5406 memory based driver at /dev/input/event0
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO              ] [HIDInput    ] Read event from </dev/input/event0>
[INFO              ] [Base        ] Start application main loop
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.4/threading.py", line 868, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/lib/python3/dist-packages/kivy/input/providers/hidinput.py", line 358, in _thread_run
     " " * 256).split('\x00')[0]
 TypeError: Type str doesn't support the buffer API
 
[INFO              ] [Base        ] Leaving application in progress...`

```python
`from kivy.app import App
#kivy.require("1.9.1")
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.label import Label
from kivy.uix.widget import Widget
from kivy.properties import NumericProperty, ReferenceListProperty, ObjectProperty
from kivy.vector import Vector
from kivy.clock import Clock
import settings
from kivy.uix.button import Button
from kivy.uix.settings import SettingsWithSidebar
from settingsjson import patsettings_json, docsettings_json




class UpPageLayout(FloatLayout):
    pass

class UpPage1(App):
    def build(self):
        return UpPageLayout()

if __name__ == "__main__":
    UpPage1().run()

`
```

Kivy file:

`#File name: UpPage1.kv
#:kivy 1.9.1

<TesterTest@Label>:
	font_size: 40
	color: 1,1,0,1
	size_hint: .3, .1

<UpPageLayout>:
	
	TesterTest:
		text:"Forward"
		pos_hint: {"center_x": 0.5, "top": 1}
	
	TesterTest:
		text:"Backward"
		pos_hint: {"center_x": 0.5, "y": 0}
		
	TesterTest:
		text:"Left"
		pos_hint: {"x": 0, "center_y": 0.5}
		size_hint: .15, .1
		
	TesterTest:
		text:"Right"
		pos_hint: {"right": 1, "center_y": 0.5}
		size_hint: .15, .1
		
    Potatoes:
		id: potatoes
        size_hint: .1, .1
        pos_hint: {"right":1, "top":1}
`

Settings Python File:
`
from kivy.app import App
from kivy.lang import Builder

from kivy.uix.button import Button
from kivy.uix.settings import SettingsWithSidebar

from settingsjson import patsettings_json, docsettings_json

Builder.load_string('''
<Potatoes>:
    id: potatoes
    font_size: self.height/2
    on_release: app.open_settings()
    Image:
        source:"../Images/menu.png"
        y: self.parent.y
        x: self.parent.x
        keep_ratio: True
        size_hint_y: None
        size_hint_x: None
        width: self.parent.width
        height: self.parent.height
        allow_stretch: True

''')

class Potatoes(Button):
    pass

class SettingsApp(App):
    def build(self):
        self.settings_cls = SettingsWithSidebar
        self.use_kivy_settings = True
        setting = self.config.get('Main Settings', 'vibeset')
        return Potatoes()

    def build_config(self, config):
        config.setdefaults('Main Settings', {
            'firstname': 'Ferris',
            'surname': 'Bueller',
            'vibeset': True,
            'spkrset': True,
            'ageset': 55,
            'heightset': 70,
            'weightset': 140,
            'options': 'option2'})

        config.setdefaults('Doc Settings', {
            'minweight': 20,
            'maxweight': 80,
            'latweight': 30,
            'longweight': 30,
            'mindist': 18,
            'maxdist': 28,
            'weightset': 140})

    def build_settings(self, settings):
        settings.add_json_panel('Smart Walker',
                                self.config,
                                data=patsettings_json)
        settings.add_json_panel('Doctor Settings',
                                self.config,
                                data=docsettings_json)

    def on_config_change(self, config, section,
                         key, value):
        print (config, section, key, value)
        

if __name__ == "__main__":
    SettingsApp().run()
`

**Comment by matham** [comment]
You'd need to test with 1.9.2 on respbian, since 1.8.0 is far too old to be able to support. To figure out how to update you can do similar to the ubuntu guide, but please ask for further support on IRC or the mailing list as this is meant for bug reports.

If you can replicate the issue with 1.9.2, please re-open or ask us to re-open the issue.
