### ISSUE TITLE
Scatter properties trigger py3 "object.__init__() takes no parameters" error

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5064]
### Versions

* Python: 3.5.2
* OS: Win8
* Kivy: master

### Description

This reminds me an old error related to [__no_builder](https://github.com/kivy/kivy/blob/master/kivy/uix/widget.py#L331), but this one confuses me a way more. Obviously it accepts `Widget` properties correctly and throws them away somewhere, but for some reason this doesn't apply for `Scatter` only properties. On the other hand, e.g. `ScrollView` only properties work correctly:

    runTouchApp(Scatter(scroll_wheel_distance=10))
    runTouchApp(Scatter(do_scroll_x=False))

Where are the properties thrown away, so that they don't travel all the way to the `object.__init__()`? That part would be probably the best way where to start. It appears that [_event.pyx](https://github.com/kivy/kivy/blob/master/kivy/_event.pyx#L252) pops the properties, but then again, it doesn't make sense for `Scatter` to throw an error as the `EventDispatcher` should already [_see_](https://github.com/kivy/kivy/blob/master/kivy/_event.pyx#L796), therefore pop the properties.

Possible quick workarounds:

* [args in `__init__`](https://github.com/kivy/kivy/blob/5913d861f45119dfff0b6cb5d004e6f79858563c/kivy/tests/test_selection.py#L182)
* `del kwargs[<arg>]`

### Code and Logs

```python
from kivy.base import runTouchApp
from kivy.uix.scatter import Scatter
# runTouchApp(Scatter(size_hint=(None, None))) works
runTouchApp(Scatter(do_rotate=False))
```

**Edit:**

Works in kv directly though:

```python
from kivy.lang import Builder
from kivy.base import runTouchApp
runTouchApp(Builder.load_string('''
Scatter:
    do_rotate: False
'''))
```

**Comment by matham** [comment]
What is this magical property `do_rotate` that you are referring to? :D

**Comment by dessant** [comment]
Just typos in a garden repo: https://github.com/kivy-garden/garden.gauge/blob/833d6cb6725a0fef6d9b70761a3a8b0d10d8edb8/__init__.py#L62L72.

**Comment by KeyWeeUsr** [comment]
Damn, I'm blind. :(
