### ISSUE TITLE
Detecting OpenGL version with PyInstaller Windows

### ISSUE THREAD

**Issue by jegger** [kivy/kivy#5071]
I am referencing to #3576 here. @dessant suggested to create a new issue for cases in which multisamples=0 does not solve the case.

How I am running into this issue:
1. Create an exe with pyinstaller (not a single .exe)
2. Testing on machine which built the .exe => Works fine
3. Move the folder containing all the files and .exe to another machine
4. => Crashes at start. (opengl error)
(Multisamples = 0 and KIVY_GL_BACKEND=sdl2 did not solve that issue)
Crash log: http://codepad.org/QnEvh6Gl

Interesting thing:
When I build a single file executable with pyinstaller, I can move that .exe to another machine and it will run just fine. (regardless of multisamples=0 or not)

I have really no clue what could be the difference (single file / folder exe) / why it runs just fine on the machine which built the folder exe. I also do not known how to debug this, as I always have to build another .exe via pyinstaller and move it to another machine to see if anything has changed. (tedious)...

The built exe folder can be found here: https://drive.google.com/file/d/0B3txMaz1dfuwWTZYemVNQUphS2M/view?usp=sharing
(it contains the pyinstaller .spec file, if that may matters)

**Comment by dessant** [comment]
@jegger, does the app run on the other machine in unpackaged form?

**Comment by Zen-CODE** [comment]
I get a different variation on the theme. When packaged as a dir, it only detects OpenGL 1.1. Using onefile, it detects OpenGL 3.1, but our first Window.height reference fails with a Window is None error. Running from the locally installed Kivy (1.9.2dev), it's all works fine.

I only have short bursts of access to the laptop (it's one of our installer), but I'm bust adding exhaustive logging. Once I narrow it down to the line that behaves differently when comparing local install to dir packed, I'll post again.

**Comment by Zen-CODE** [comment]
So, adding some logging to the kivy/opengl.pyx, in getString
'''
    Logger.info('opengl.pyx: for {0}, returning {1}'.format(name, p_string))
'''
The local installed, working lauch logs
```
[INFO   ] opengl.pyx: for 7938, returning 3.1.0 - Build 9.17.10.4459
[INFO   ] opengl.pyx: for 7936, returning Intel
[INFO   ] opengl.pyx: for 7937, returning Intel(R) HD Graphics 3000
```
The packaged version that fails logs
```
[INFO   ] opengl.pyx: for 7938, returning 1.1.0
[INFO   ] opengl.pyx: for 7936, returning Microsoft Corporation
[INFO   ] opengl.pyx: for 7937, returning GDI Generic
```
So it's not picking up the right graphics card. The second is the default for MS Terminal server. Is that a co-incidence? 

Where to from here? Where does kivy choose the graphics device?

**Comment by KeyWeeUsr** [comment]
I think Kivy directly doesn't, maybe it just uses whatever OS returns? If there's something, it could be in the SDL2 code, not in our Cython. At least when I was trying to find a code for making an external GPU the default card I found nothing (and had to run .EXE through OS GPU menu).

**Comment by Zen-CODE** [comment]
Just as feedback, using angle_sdl2 seems to work nicely. It forces us to Python3 and does not solve this issue, but is a great alternative and worth posting here.

**Comment by Zen-CODE** [comment]
Ha! Looks like the OpenGL error is caused by the manifest. Alongside the exe is a .manifest file (with the same name). Removed that and OpenGL is suddenly found (@matham. Thanks for reminding me of that).  @jegger. Does that work for you too?

**Comment by jegger** [comment]
@Zen-CODE Yea, that seems to work. (I have only tested it on one machine yet).  Wow, that was the thing which lead to the error? - Unbelievable... Many thanks so far! I will do some more testing now. Do you known what's this file for / why it gets created?

**Comment by Zen-CODE** [comment]
I know we used it before (for a vb6 app) to load different versions of dll's so we could theme the app. It's a xml file you can open and specifies compatible binaries, assembly versions, permissions etc. Can you believe it caused this problem!?? Just glad it's solved :-) 

Please close once you're happy it does fix it (verified on 2 machines on my side).

**Comment by KeyWeeUsr** [comment]
@Zen-CODE if you can, paste the manifest here. Maybe it's just PyInstaller's fault and we should let them know.

**Comment by Zen-CODE** [comment]
Sure, contents below. It's probably just a generic file they put alongside the exe and I doubt comes from any analysis? But that's just a guess.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="CAMI-Apps" processorArchitecture="x86" type="win32" version="1.0.0.0"/>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity name="Microsoft.VC90.CRT" processorArchitecture="x86" publicKeyToken="1fc8b3b9a1e18e3b" type="win32" version="9.0.30729.4940"/>
      <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"/>
    </dependentAssembly>
  </dependency>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity language="*" name="Microsoft.Windows.Common-Controls" processorArchitecture="x86" publicKeyToken="6595b64144ccf1df" type="win32" version="6.0.0.0"/>
      <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"/>
    </dependentAssembly>
  </dependency>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
</assembly>
```

**Comment by KeyWeeUsr** [comment]
I think the same. Maybe there's just something missing and the missing thing is available in the onefile package? To get a manifest out of that run the .exe, navigate to `%TEMP%` and look for a folder that starts with `_MEI` and is recently created. You have to keep the exe running the whole time, otherwise it'll delete the folder.

PyInstaller has a function that allows reading xml manifest, so it might be [the thing](https://github.com/pyinstaller/pyinstaller/blob/5a8cd80c3b259cadca477ede36f4259bf86c6d3b/PyInstaller/utils/win32/winmanifest.py) to begin with (i.e. what's the default thing loaded when you delete custom manifest).

**Comment by dessant** [comment]
It could also be interesting to remove parts of the manifest to see which part causes the error.

**Comment by Zen-CODE** [comment]
@dessant. Yeah, I'd suggest that too. That compatibility section especially, with 'supportedOS' lists. My guess is that it does not find a match here, so launches in "Virtualized/Terminal Server compatibility" mode or suchlike. The OpenGL 1.1 match is just too co-incidental....

**Comment by Zen-CODE** [comment]
The rabbit hole goes deeper. Removing the manifest file fixes it, so I try to investigate why. When I put it back (the manifest file), it now works anyway. It's as if its already cached the permissions?

To understand what a manifest file does: https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191(v=vs.85).aspx

Because I can no longer reproduce the problem, I cannot say with 100% certainty what the problem is, but I can offer a fairly certain guess. If we look in the supportedOS section, it lists support for Vista/7/8/Server compatibility. I think it tries to launch in those modes and compatibility settings, fails so only supplies the minimal graphics driver  = OpenGL1.1. Taking the manifest away, it just does a simple open and finds the graphics driver.

I will make a post on the PyInstaller ticket pointing back here for our findings. Thanks
