### ISSUE TITLE
Canvas lines cause slow transitions on Pi

### ISSUE THREAD

**Issue by DGHC** [kivy/kivy#5074]
### Versions

* Python: 2.7.9
* OS: Raspbian Lite, Kernel 4.4.26-v7+
* Kivy: 1.9.2-dev0
* Kivy installation method: As per "Manual installation (On Raspbian Jessie)" on Kivy website

### Description

Hi, 

First of all, thank you so much in advance for any help/guidance you can offer - it's very much appreciated!  I will try and be concise!

Here is a brief description of my app:
I'm using a screen manager, but my root widget is a BoxLayout.
The root widget contains two widgets: a BoxLayout (acting as a status bar at the top), and the screen manager.
There are fours screens registered with the screen manager.  Three are "normal", and one (ScreenSwitcher) is a screen to select which screen to display.  The ScreenSwitcher is shown by pressing a button in the status bar.
ScreenTwo and ScreenThree are identical.  ScreenOne is the same except for a line drawn on the canvas.

I've pasted a minimal version of the app below.  In its current state, any transitions involving ScreenOne are jerky/laggy, whereas transitions to ScreenTwo and ScreenThree are smooth.  Please note I'm running this on a Raspberry Pi (v3), with the official touchscreen.

The issue can be fixed by changing either of the two lines drawn on canvases to rectangles.  One line is along the bottom of the status bar, and one line is drawn under the label on ScreenOne.  I've included the code that fixes - you need to comment out the bit that draws the line, and uncomment the bit that draws the rectangle.  The weird thing is that you only need to do this to one of the lines - either will fix the issue.

It seems there is an issue between the two canvas line instructions.  It would be bold of me to suggest this is a bug, as it is very possible I have not understood how to implement these instructions.  Any help would be appreciated.

Worth noting that this runs fine on my Windows 10 laptop - it's only an issue on the Pi.

Many thanks again in advance!

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.screenmanager import ScreenManager, Screen

kv = """
<ScreenManagement>:
    ScreenOne:
        id: screen_one
    ScreenTwo:
        id: screen_two
    ScreenThree:
        id: screen_three
    ScreenSwitcher:
        id: screen_switcher

<RootWidget>:
    orientation: 'vertical'
    BoxLayout:
        id: status_bar
        orientation: 'horizontal'
        size_hint: None, None
        size: root.width, 50
        spacing: 5
        padding: 15, 0, 5, 0
        canvas.before:
            Color:
                rgb: 0.6, 0.2, 0.5
            Rectangle:
                pos: self.pos
                size: self.size
            Color:
                rgb: [0.9]*3
            # Rectangle:
            #     pos: self.pos
            #     size: self.width, 1
            Line:
                points: self.x, self.y+1, self.x+self.width, self.y+1
        Button:
            id: screens_button
            size_hint: None, None
            size: 140, self.parent.height
            text: 'Change screens'
            on_press:
                manager.current = 'screen_switcher'
    ScreenManagement:
        id: manager
        size_hint: None, None
        size: root.width, root.height-status_bar.height

<ScreenOne>:
    name: 'screen_one'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Screen One'
            font_size: 36
            canvas:
#                Rectangle:
#                    pos: self.pos[0], self.pos[1]+5
#                    size: self.width, 1
                Line:
                    points: self.x, self.y+5, self.x+self.width, self.y+5

<ScreenTwo>:
    name: 'screen_two'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Screen Two'
            font_size: 36

<ScreenThree>:
    name: 'screen_three'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Screen Three'
            font_size: 36

<ScreenSwitcher>:
    name: 'screen_switcher'
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Screen 1'
            on_press:
                root.manager.current = 'screen_one'
        Button:
            text: 'Screen 2'
            on_press:
                root.manager.current = 'screen_two'
        Button:
            text: 'Screen 3'
            on_press:
                root.manager.current = 'screen_three'

"""

class ScreenManagement(ScreenManager):
    pass

class ScreenOne(Screen):
    pass

class ScreenTwo(Screen):
    pass

class ScreenThree(Screen):
    pass

class ScreenFour(Screen):
    pass

class ScreenSwitcher(Screen):
    pass

class RootWidget(BoxLayout):
    pass

class MinimalCanvasApp(App):

    def build(self):
        self.root = RootWidget()
        return self.root

if __name__ == '__main__':

    # Load KV file
    Builder.load_string(kv)

    # Launch app
    app = MinimalCanvasApp()
    app.run()

```

**Comment by Jowls1** [comment]
Bump
