### ISSUE TITLE
Can't install Kivy (needs Cython, which I also can't install)

### ISSUE THREAD

**Issue by bgailer** [kivy/kivy#5076]
I followed https://kivy.org/docs/installation/installation-windows.html

Step 3 fails - Cython is missing, its required for compiling kivy !

So I tried: python -m pip install Cython

which fails with error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1": www.microsoft.com/download/details.aspx?id=8279

I dutifully download and run winsdk_web.exe, which informs me

![screenshot057](https://cloud.githubusercontent.com/assets/1512596/24218362/6cb3fbc8-0f19-11e7-8188-63cf8d14abcc.gif)

I dutifully go to go.microsoft.com/fwlink/?LinkID=187688, download & run vs_community__971130829.1490038994.exe which completes its job. So I try python -m pip install Cython again, and get the same error. What do I do now?

### Versions

* Python: 3.3.5
* OS: Windows 10
* Kivy: ???
* Kivy installation method: See above

### Description
// What are you trying to get done, Install Kivy; what has happened, what went wrong: see above;  and what did you expect? Kivy to be installed

**Comment by matham** [comment]
Until the next release python 3.5+ is not supported from pypi. You need to download the latest nightly wheel from the website instead.
