### ISSUE TITLE
Cannot install KIVY on windows 10. Cannot open include file GL/glew.h. No such file or directory.

### ISSUE THREAD

**Issue by steviehutch** [kivy/kivy#5077]
### Versions

* Python: 3.6.0
* OS: Windows 10
* Kivy: 
* Kivy installation method: "python -m pip install kivy"

### Description

I am trying to install KIVY according to this

https://kivy.org/docs/installation/installation-windows.html

I have followed the instructions on the KIVY website to the letter. There was a missing library that I needed to install cython as well as the ones indicated in the instructions. 

I installed python 3.6.0 to an external hard drive
H:\Python
then installed all the rest of the stuff
python -m pip install --upgrade pip wheel setuptools
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew

I DID NOT INSTALL ANGLE as the instructions said this is only for Python 3.5

I then try to install Kivy

python -m pip install kivy

Then I get an error every time

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IH:\PYTHON\include -IH:\PYTHON\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /TcC:\Users\HUTCH_~1\AppData\Local\Temp\pip-build-82a482ny\kivy\kivy\graphics\context.c /Fobuild\temp.win32-3.6\Release\Users\HUTCH_~1\AppData\Local\Temp\pip-build-82a482ny\kivy\kivy\graphics\context.obj
    context.c
    c:\users\hutch_000\appdata\local\temp\pip-build-82a482ny\kivy\kivy\graphics\gl_redirect.h(8): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory
     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    
    ----------------------------------------

I have seen someone recommending installing the GLEW library and copying the files to my python installation directory. I did this and added environment variables so that this directory is seen in my PATH

Still no luck.

**Comment by dessant** [comment]
py3.6 wheels have no stable release yet, you'll have to use the nightly ones: https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation.
