### ISSUE TITLE
Line(circle=...) and the other modes aren't movable

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5080]
### Versions

* Python: 3.5.2
* OS: Windows
* Kivy: master
* Kivy installation method: wheels

### Description

Well, I though I screw something up in #5079, but apparently this is a bug in the `Line` itself for some reason. I tried to print the points (worked) and printed it even in `on_touch_move`, which looked like the points actually _**are**_ changing, but only +/- very small value. Sometimes around 1, although decimal places weren't changed, so I ended up with something like `XYZ.99999999` or similar, where `Z` was alternating. Casual `Line(points=...)`, `Points`, `Mesh`, or move correctly, so I think there's might be something missing in the [`prebuild_circle()`](https://github.com/kivy/kivy/blob/master/kivy/graphics/vertex_instructions_line.pxi#L949) and some other parts.

The same applies for `Line(ellipse=...)`, rectangle, circle, ... Am I missing something, or is it a real bug?

### Code and Logs

```python
from kivy.app import runTouchApp
from kivy.lang import Builder
from kivy.uix.widget import Widget
from kivy.uix.boxlayout import BoxLayout
from kivy.graphics import *
from random import random as R
Builder.load_string('''
<Drawing>:
    canvas:
        Color:
            rgba: 1, 0, 0, 0.4
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: 1, 1, 1, 1
''')

class Drawing(Widget):
    def __init__(self, shape=00, **kw):
        super(Drawing, self).__init__(**kw)
        self.size_hint = (None, None)
        with self.canvas:
            pts = [*self.center, 100, 0, 359 * R(), 200]
            if shape==1:
                self.line = Line(circle=pts)
                self.name = 'circle'
            elif shape==2:
                self.line = Line(rectangle=pts[2:])
                self.name = 'rectangle'
            else:
                self.line = Line(points=pts)
                self.name = 'points'


    def on_touch_down(self, touch):
        if self.collide_point(*touch.pos):
            touch.grab(self)
            print(self.name)
        self.old = self.pos[:]

    def on_touch_move(self, touch):
        if touch.grab_current is not self:
            return
        points = self.line.points[:]
        ox = touch.x - self.old[0]
        oy = touch.y - self.old[1]
        for i in range(len(points)):
            if not i % 2:
                points[i] += ox
                points[i + 1] += oy
        self.line.points = points
        self.old = touch.pos
        self.pos = [self.pos[0] + ox, self.pos[1] + oy]


box = BoxLayout()
for i in [0, 1, 2]:
    box.add_widget(Drawing(shape=i, pos=[200 * R(), 100 * R()]))
runTouchApp(box)
```

**Comment by matham** [comment]
You're doing something wrong in the way you compute the offsets. Try setting the pos of e.g. rectangle to e.g. self.pos as opposed to adding differences. That's where your error comes from.

**Comment by tito** [comment]
Please note that adding offset is more error prone as you'll increase the precision issue (you can't have exact offset each time, so you may have a precision issue, which will increase every time you move)

**Comment by tito** [comment]
The points are immutable when using circle or rectangle.
Either add it into the documentation, but the right way to move it would be:
- just recall line.circle = ... or line.rectangle = ..., but you'll recompute a mesh internally
- add PushMatrix, Translate, ... your line instruction ..., PopMatrix, and then just change the Translate. It will be much more efficient instead of changing the points.

**Comment by KeyWeeUsr** [comment]
I wonder if the points are changed from Cython in some way, because I've seen changes in the points as mentioned above and that doesn't really make sense for immutable object. Maybe it was changing because of C/Python float conversion? However, that would change only once, I think.

Also, if the points are immutable here, how negative would be the effect for performance to change it to mutable? It seems inconsistent with the rest of kivy instructions now. Or would it be easier to just get notified from points' setter, check for the line mode and do the appropriate translations from cython (so that visual consistency is preserved)?

Also, matham, I made the linked example changes dependent of widget's position change, but it didn't move, so it isn't offsets fault (though yes, this short code looks bad, but reproduces). To get it the proper way, just fetch the first commit of the linked example and see how the collider stays at a single place and see the diff with next commits.

**Comment by matham** [comment]
I guess I tested by changing the `rectangle` parameter, rather than updating the points of the rectangle, which @tito seems to say is not supported.

**Comment by sgeigerGit** [comment]
> The points are immutable when using circle or rectangle.
> Either add it into the documentation, but the right way to move it would be:
> 
> * just recall line.circle = ... or line.rectangle = ..., but you'll recompute a mesh internally
> * add PushMatrix, Translate, ... your line instruction ..., PopMatrix, and then just change the Translate. It will be much more efficient instead of changing the points.

Could you give an example how to move a line on canvas with Push and PopMatrix and Translate?

**Comment by Julian-O** [comment]
@KeyWeeUsr: You self-assigned this a while ago. Is it still a problem?

There doesn't seem to be consensus that there is a bug here. Can we close it?
