### ISSUE TITLE
kivycatalog documentation - image does not match reality

### ISSUE THREAD

**Issue by bgailer** [kivy/kivy#5082]
python27
windows 10
kivy 1.9.1
https://kivy.org/docs/guide/widgets.html under Consider the following example:
When I run: C:\Python27\share\kivy-examples\demo\kivycatalog>\python27\python main.py I get:
![screenshot058](https://cloud.githubusercontent.com/assets/1512596/24377782/879fab00-130e-11e7-8fd4-a68fa1753ae8.gif)

This differs significantly from the documentation:
![screenshot059](https://cloud.githubusercontent.com/assets/1512596/24377621/f9cb4a28-130d-11e7-95d4-8003beefd629.gif)

Also - as a first-time visitor to this tool my first reaction was "where is the navigation bar?". It took some experimenting to discover that clicking Welcome reveals it.

**Comment by bgailer** [comment]
I also got:
[ERROR             ] unable to access to <\hiberfil.sys>
[ERROR             ] unable to access to <\pagefile.sys>
[ERROR             ] unable to access to <\swapfile.sys>

I noticed issue 1753 refers to these errors.

**Comment by Zen-CODE** [comment]
Thanks. Images corrected. In terms of your other errors, please create a new ticket for that with more detail: OS, full log etc.
