### ISSUE TITLE
Not scrollable filechooser

### ISSUE THREAD

**Issue by cayman54** [kivy/kivy#5084]
Hi,
Is it possible to have a filechoosericonview not scrollable?
I use it on a raspberry pi with a pitft resistive touchscreen, and when I want to select a file the resistive screen scroll the view instead of selecting the file...
Would it be possible to have instead of a scrollable view a "multipages" view?
Thanks in advance,

**Comment by matham** [comment]
github issues are for bug reports, not support requests. Please ask on the user mailing list or on the #kivy IRC channel for support.

That said, filechooser uses a scollview, and you probably can manually disable scrolling on it. Also, we're unlikely to introduce new features into filechooser without a significant re-write, which is not likely to happen anytime soon.
