### ISSUE TITLE
Kubuntu windows lose rounded corners when Kivy app runs

### ISSUE THREAD

**Issue by brandon-gong** [kivy/kivy#5087]
### Versions

* Python: 2.7.12+
* OS: Kubuntu, Kernel 4.8.0-41-generic
* Kivy: 1.9.1
* Kivy installation method: installed according to Installation on Linux > Ubuntu on the Kivy website

### Description

Hi,

First of all, I'd like to say that I just found out about Kivy a few days ago and I'm really excited but also a total noob, so I'm a little afraid of this not being an actual issue.  Nevertheless, I've searched around and found nothing.

So, being a total noob, I installed Kivy according to some instructions, started a python REPL, and typed in the code that I found [here](https://kivy.org/docs/guide/basic.html).

I was able to type each line in without error, and after typing in the `MyApp().run()` line sure enough a black window popped up with a white-text label in the center.

I noticed, however, that when the window was created, all of my applications - not just the dummy kivy app - lost their rounded corners.  On Kubuntu, windows have slightly rounded corners, which I think really makes it look a lot more comfortable and user-friendly.  But when the app starts, every single one of my windows lose their rounded corners.  All of the windows are still fully functional, draggable and resizable, but the rounded corners _and animation when I minimize the window_ are gone.  It's not a big deal in terms of functionality, but the user interface is suddenly a lot less familiar without rounded corners and animations.

Firefox before I launch the Kivy app (Firefox picked randomly; all other windows exhibit this behavior):
![screenshot_20170330_210025](https://cloud.githubusercontent.com/assets/19562455/24533263/2ab69b44-158c-11e7-80f6-980c54762296.png)

Firefox after I launch the Kivy app:
![screenshot_20170330_210428](https://cloud.githubusercontent.com/assets/19562455/24533323/9220e56e-158c-11e7-9128-5adc7e438530.png)

It seems like a very subtle detail, but again for me it feels very strange using windows without rounded corners.  I feel like a very picky child as I type this.  It feels like a huge hit on user experience, to have all of your windows suddenly flash and lose their rounded corners right when you start an app.

When the Kivy app window is closed, all other windows regain their previously rounded state.

### Code and Logs

```python
import kivy
kivy.require('1.0.6') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()
```

**Comment by FeralBytes** [comment]
@brandon-gong I think this would be more of a KDE issue rather than Kivy. But yes it is something that Kivy is doing on Window creation that is causing a KDE bug. But the question of course is what is Kivy doing. But first things first, can you instead install the development branch from github and test if that exhibits the same behavior?

**Comment by brandon-gong** [comment]
@FeralBytes install from `master`?  Also, my KDE Plasma version is 5.7.5, KDE Frameworks version is 5.26.0, and Qt version is 5.6.1 (not sure which number you want).

**Comment by FeralBytes** [comment]
@brandon-gong install from master.

**Comment by brandon-gong** [comment]
@FeralBytes I cloned it and ran a make install, it does not have this issue anymore! Sorry about that.  I guess its already fixed.  How unsafe to use code from the master branch in production?  Can I safely use it in an app?  I wouldn't want to sacrifice the stability of the app for all platforms just to have some rounded corners on KDE.

**Comment by FeralBytes** [comment]
@brandon-gong I have only rarely encountered issues with master; so you should be just fine; using it as a stable base.

**Comment by brandon-gong** [comment]
@FeralBytes Thank you so much for the help!

**Comment by FeralBytes** [comment]
@brandon-gong No problem. Don't forget to close the issue. Thank you.

**Comment by nzahasan** [comment]
I know this is old but I have faced the same Issue with `kivy v1.10.1` and plasma 5.13.5 it looks like kivy is somehow blocking the compositor. One easy fix is to disable `Allow application to block compositing` in kde setting. 

 
![image](https://user-images.githubusercontent.com/9565364/46578674-4da51580-ca27-11e8-8496-55e3caabe993.png)
