### ISSUE TITLE
optimise text_layout.pyx

### ISSUE THREAD

**Issue by phunsukwangdu** [kivy/kivy#5104]
Again [here](https://github.com/kivy/kivy/blob/master/kivy/core/text/text_layout.pyx#L151),this piece of code is not required because if word is empty,obviously its width will be zero.If its width is not zero it means the word is not empty.This piece of code only adds computational cost and might not be required here.

```

**Comment by matham** [comment]
I do mention that it's likely zero, but at the time I wrote it I guess I couldn't be sure, otherwise I would not have put it there. The computational cost is minimal, and it's better to be safe than sorry.

**Comment by matham** [comment]
This is again one of those kind of issues, which unless there's a actual bug to fix, it's best to not open issues or PRs to fix things that are not broken. Especially, because it should be obvious from the comment there that when I wrote it I knew it's likely to be zero.
