### ISSUE TITLE
update description of final_strip() in text_layout.pyx

### ISSUE THREAD

**Issue by phunsukwangdu** [kivy/kivy#5105]
[here](https://github.com/kivy/kivy/blob/master/kivy/core/text/text_layout.pyx#L135) keeping in the mind what the function does the more apt description would be replacing `word` with `spaces from word` here.Otherwise it narrates a whole different story :P.

**Comment by matham** [comment]
Please don't open issues, or even PRs for such minor things which are not actual bugs. Generally, the rule is, unless you're submitting a PR that changes the surrounding code in a meaningful way (i.e. fixes a actual bug/issue), don't fix comments or re-organize code.
