### ISSUE TITLE
win7 py3.5 pip install fail

### ISSUE THREAD

**Issue by Jovons** [kivy/kivy#5113]
### Versions

* Python: 3.5
* OS: Win7
* Kivy:1.9.1
* Kivy installation method: pip install kivy

### Description

I followed instructions at: https://kivy.org/docs/installation/installation-windows.html#install-win-dist
And then it says no VS compiler, so I installed "visual cpp build tool", and it says .NET version should be at least 4.5. Then I installed .NET version 4.6.2. And I installed "visual cpp build tool". But when I run pip install kivy, it does not work either with a new file cannot be found. This is installation log:
    c:\users\xxx\appdata\local\temp\pip-build-_4yr5b2z\kivy\kivy\graphics\gl_r
edirect.h(8): fatal error C1083: Cannot open include file: 'GL/glew.h': No such
file or directory
     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\
BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\xxx\appdata\local\programs\python\python35\python.exe -u -c
"import setuptools, tokenize;__file__='C:\\Users\\xxx\\AppData\\Local\\Temp\\p
ip-build-_4yr5b2z\\kivy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);c
ode=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'
))" install --record C:\Users\xxx\AppData\Local\Temp\pip-v42e50tv-record\insta
ll-record.txt --single-version-externally-managed --compile" failed with error c
ode 1 in C:\Users\xxx\AppData\Local\Temp\pip-build-_4yr5b2z\kivy\

**Comment by KeyWeeUsr** [comment]
Please see https://github.com/kivy/kivy/commit/5353596400366f024ab258955659608946839e59. Thanks for understanding.

**Comment by Jovons** [comment]
OK. pip install path-to-whl
