### ISSUE TITLE
change wording on https://github.com/kivy/kivy/blob/master/doc/sources/guide/widgets.rst

### ISSUE THREAD

**Issue by bgailer** [kivy/kivy#5114]
Current: "Replace $KIVYDIR with the directory of your installation of Kivy. Click on the button labeled Box Layout from the left."

Proposed: "Replace $KIVYDIR with the directory of your installation of Kivy. _Click on the button labeled Welcome to reveal the menu._ Click on the button labeled Box Layout from the left." 

Reasoning: Initial appearance of the catalog does not show the menu.

ALSO we need to explain "directory of your installation of Kivy". Many users will not know what this. For Windows it is  python-directory\lib\site-packages\kivy How to determine the python-directory?

**Comment by bgailer** [comment]
As soon as I can get my clone compiled I will start making and submitting fixes. I have a problem with the compile which is awaiting attention on the google users group. https://groups.google.com/forum/#!topic/kivy-users/ePv7aGqCT_w

**Comment by Zen-CODE** [comment]
@bgailer. Thanks. The wording was quite unclear :-)
