### ISSUE TITLE
RTL text input for android application

### ISSUE THREAD

**Issue by Kiran-E-Sehar** [kivy/kivy#5118]
hi
i have an application that developed in adobe flash builder,  but this application doesnot support right to left typing in mobiles
this is the textfiled code

<?xml version="1.0" encoding="utf-8"?>
<s:TextArea xmlns:fx="http://ns.adobe.com/mxml/2009" xmlns:s="library://ns.adobe.com/flex/spark"
            xmlns:mx="library://ns.adobe.com/flex/mx"
			focusedTextSelectionColor="{SkinPreferences.listSelectionColor}">
    <fx:Script>
        <![CDATA[
			
			
			import com.asfdfdfd.chat.client.ClientSettings;
			import com.asfdfdfd.chat.client.SkinPreferences;
			import com.asfdfdfd.chat.client.models.ChatClient;
			
			import flash.text.engine.FontPosture;
			import flash.text.engine.FontWeight;
			
			import spark.components.supportClasses.StyleableTextField;
			
			import flashx.textLayout.conversion.ConversionType;
			import flashx.textLayout.conversion.TextConverter;
			import flashx.textLayout.elements.ParagraphElement;
			import flashx.textLayout.elements.SpanElement;
			import flashx.textLayout.elements.TextFlow;
			import flashx.textLayout.formats.TextDecoration;
			
		
			

            public function getHTMLMessage() : String
            {
				
				
				var textFlow:TextFlow = TextConverter.importToFlow(text, TextConverter.TEXT_FIELD_HTML_FORMAT);
				var settings:ClientSettings = ChatClient.getLocalChatClient().settings;
				textFlow.color = uint("0x"+settings.fontColor);//ChatClient.getLocalChatClient().settings.fontColor;
				textFlow.fontSize = settings.fontSize;
				textFlow.setStyle("fontWeight", settings.fontBold?FontWeight.BOLD:FontWeight.NORMAL);
				textFlow.setStyle("fontStyle", settings.fontItalic?FontPosture.ITALIC:FontPosture.NORMAL);
				textFlow.setStyle("textDecoration", settings.fontUnderScore?TextDecoration.UNDERLINE:TextDecoration.NONE);
				return TextConverter.export(textFlow, TextConverter.TEXT_FIELD_HTML_FORMAT, ConversionType.STRING_TYPE).toString();
            }

			public function setColorFromSettings(scolor:String):void{
				textFlow.color=uint("0x"+scolor);
			}
            public function toggleItalic() : void
            {
/*                if (textFlow.fontStyle == FontPosture.ITALIC)
                {
                    textFlow.fontStyle = FontPosture.NORMAL;
                }
                else
                {
                    textFlow.fontStyle = FontPosture.ITALIC;
                }
*/            }

            public function toggleBold() : void
            {
				//textDisplay.
/*                if (textFlow.fontWeight == FontWeight.BOLD)
                {
                    textFlow.fontWeight = FontWeight.NORMAL;
                }
                else
                {
                    textFlow.fontWeight = FontWeight.BOLD;
                }
*/            }

            public function toggleUnderscore() : void
            {
/*                if (textFlow.textDecoration == TextDecoration.UNDERLINE)
                {
                    textFlow.textDecoration = TextDecoration.NONE;
                }
                else
                {
                    textFlow.textDecoration = TextDecoration.UNDERLINE;
                }
*/            }

            public function insertSmiley( text : String ) : void
            {
                var span : SpanElement = new SpanElement();
                span.text = text;

                (textFlow.getChildAt(0) as ParagraphElement).addChild(span);
            }
        ]]>
    </fx:Script>
</s:TextArea>

how can i add rtl text input here?

**Comment by KeyWeeUsr** [comment]
I have no clue how did you actually connected Adobe Flash and Kivy, but feel free to share the story. Anyway, this doesn't seem even like Java, which might be very slightly related to p4a if it was. Kivy is written and used with [Python](https://python.org)(/Cython), therefore we can't help you with this problem. :)
