### ISSUE TITLE
Kivy text input - adding line numbers

### ISSUE THREAD

**Issue by hsdk123** [kivy/kivy#5119]
Hi, I'm currently trying to create something along the lines of a basic text editor using kivy. I'm trying to use the text input widget, but I am currently stuck on how I should be displaying line numbers. Is there a simple method to do this in Kivy?

**Comment by KeyWeeUsr** [comment]
This GitHub repository is meant for issues with Kivy codebase directly, please use an appropriate channel from [Community Guidelines](https://github.com/kivy/kivy/wiki/Community-Guidelines) for asking about how to do things.

**Comment by griloHBG** [comment]
I came across the same need, so I did this: https://github.com/griloHBG/TextInputLineNumber

Perhaps this helps someone searching for the same thing.
