### ISSUE TITLE
Document needs clarification

### ISSUE THREAD

**Issue by bgailer** [kivy/kivy#5122]
https://kivy.org/docs/installation/installation.html
**Installation in a Virtual Environment**

What is " a Virtual Environment"? To me it could be a vm such as vmware  or virtualbox, or python's virtualenv. I had to scroll a ways to see it is  likely the latter. Let's make that clear up front.

What is SDL2? I had to google it, and I still don't know how that applies here.

**Comment by KeyWeeUsr** [comment]
If you read the global [Installation](https://kivy.org/docs/installation/installation.html) page, which then divides into subpages for Windows, OSX, GNU/Linux distros and other parts, then you'd know what SDL2 or others mean:

> If you want to enable features like windowing (i.e. open a Window), audio/video playback or spelling correction, additional dependencies must be available. For these, we recommend SDL2, Gstreamer 1.x and PyEnchant, respectively.

About Virtual Environment, well this one might seem tricky, but as Kivy is a Python package, it's rather obvious to expect it to be some kind of Python `venv` (or alternatives). It's quite well described in [The Hitchhiker's Guide to Python](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

For the [Virtual _Machine_](https://en.wikipedia.org/wiki/Virtual_machine)(not Environment, those aren't interchangeable) one would use directly the instructions for the chosen OS for example "Installation on Windows".
