### ISSUE TITLE
File 'data/fonts/...' not found

### ISSUE THREAD

**Issue by bgailer** [kivy/kivy#5124]
### Versions

* Python: 3.5
* OS: ubuntu 16.04
* Kivy: 1.9.0
* Kivy installation method: latest stable

### 
`bgailer@dell:/usr/share/kivy-examples/demo/showcase$` python3 main.py
[INFO   ] [Logger      ] Record log in /home/bgailer/.kivy/logs/kivy_17-04-15_2.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 12.0.6'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) 965GM '>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 bgailer@dell:/usr/share/kivy-examples/demo/showcase$ python3 main.py
[INFO   ] [Logger      ] Record log in /home/bgailer/.kivy/logs/kivy_17-04-15_2.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 12.0.6'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) 965GM '>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 /usr/lib/python3/dist-packages/kivy/core/clipboard/clipboard_gtk3.py:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
   from gi.repository import Gtk, Gdk
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
Traceback (most recent call last):
   File "main.py", line 239, in <module>
     ShowcaseApp().run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 515, in tick
     self._process_events()
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 647, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 406, in tick
     ret = callback(self._dt)
   File "/usr/lib/python3/dist-packages/kivy/uix/textinput.py", line 1747, in _refresh_line_options
     self._get_line_options()
   File "/usr/lib/python3/dist-packages/kivy/uix/codeinput.py", line 151, in _get_line_options
     kw = super(CodeInput, self)._get_line_options()
   File "/usr/lib/python3/dist-packages/kivy/uix/textinput.py", line 2074, in _get_line_options
     self._label_cached = Label(**kw)
   File "/usr/lib/python3/dist-packages/kivy/core/text/__init__.py", line 196, in __init__
     self.resolve_font_name()
   File "/usr/lib/python3/dist-packages/kivy/core/text/__init__.py", line 261, in resolve_font_name
     raise IOError('Label: File %r not found' % fontname)
 OSError: Label: File 'data/fonts/DroidSansMono.ttf' not found
`

**Comment by KeyWeeUsr** [comment]
I'm not quite sure what hapenned in here, because we don't use `DroidSansMono` for a pretty good while (https://github.com/kivy/kivy/commit/8ae2d6ad57f093b85fa0b6645713d3aad2270811). This change is even in the stable (`1.9.1`), therefore I think there's something wrong with your installation. Please do a clean install.

**Comment by primaeval** [comment]
I'm getting a the same message with the same Ubuntu, python 2.7, kivy v1.10.0

**Comment by zer0c0d3** [comment]
I get the same error "IOError: Label: File 'data/fonts/DroidSansMono.ttf' not found"
