### ISSUE TITLE
Installing kivy and running a minimal application.

### ISSUE THREAD

**Issue by swajime** [kivy/kivy#5128]
### Versions

* Python: 3.4.3
* OS: macOS Sierra 10.12
* Kivy: 1.9.1
* Kivy installation method: "Using Homebrew with pip"

### Description
Just trying to get started with instructions from https://kivy.org/docs/installation/installation-osx.html
```
$ brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer
$ pip install -I Cython==0.23
$ USE_OSX_FRAMEWORKS=0 pip install kivy
# Create and run minimal application from https://kivy.org/docs/guide/basic.html
$ ./min.py
```
I attached kivy_log.txt from the installation steps.

### Code and Logs

```
jwsimpsonosx:src jwsimpson$ cat min.py
#!/usr/bin/env python3.4
#

import kivy
kivy.require('1.9.1') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()

jwsimpsonosx:src jwsimpson$ ./min.py
[INFO   ] [Logger      ] Record log in /Users/jwsimpson/.kivy/logs/kivy_17-04-20_6.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.4.3 (default, Mar 16 2017, 12:49:12)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Text        ] Unable to find any valuable Text provider at all!
pygame - ImportError: No module named 'pygame'
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/text/text_pygame.py", line 12, in <module>
    import pygame

pil - ImportError: No module named 'PIL'
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/text/text_pil.py", line 8, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.
[kivy_log.txt](https://github.com/kivy/kivy/files/945085/kivy_log.txt)


```

**Comment by manthansharma** [comment]
I don't know the reason for this error but manually downloading all .dmg file for 

SDL2:  https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.dmg
SDL2_ttf: https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.dmg
SDL2_mixer: https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.dmg
SDL2_image: https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.dmg

Now, open all `*.dmg` and manually copy `*.framework` to `/Library/Frameworks`  works for me.

**Comment by swajime** [comment]
I copied the files you mentioned, including frameworks for SDL2-2.0.5.dmg, and still have the same issue:
```
jwsimpsonosx:src jwsimpson$ ls -lad /Library/Frameworks/SDL*
drwxr-xr-x@ 6 jwsimpson  wheel  204 Oct 20  2016 /Library/Frameworks/SDL2.framework
drwxr-xr-x@ 7 jwsimpson  wheel  238 Jan  3  2016 /Library/Frameworks/SDL2_image.framework
drwxr-xr-x@ 7 jwsimpson  wheel  238 Jan  3  2016 /Library/Frameworks/SDL2_mixer.framework
drwxr-xr-x@ 7 jwsimpson  wheel  238 Feb  1  2016 /Library/Frameworks/SDL2_ttf.framework
jwsimpsonosx:src jwsimpson$ ./min.py
[INFO   ] [Logger      ] Record log in /Users/jwsimpson/.kivy/logs/kivy_17-04-21_3.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.4.3 (default, Mar 16 2017, 12:49:12)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Text        ] Unable to find any valuable Text provider at all!
pygame - ImportError: No module named 'pygame'
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/text/text_pygame.py", line 12, in <module>
    import pygame

pil - ImportError: No module named 'PIL'
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Users/jwsimpson/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/text/text_pil.py", line 8, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.
```

**Comment by manthansharma** [comment]
You have to reinstall kivy after copying framework files. Check for these line using `--verbose` with pip.
```
Found sdl2 frameworks: /Library/Frameworks/SDL2.framework
Found sdl2 frameworks: /Library/Frameworks/SDL2_ttf.framework
Found sdl2 frameworks: /Library/Frameworks/SDL2_image.framework
Found sdl2 frameworks: /Library/Frameworks/SDL2_mixer.framework
```

**Comment by swajime** [comment]
Ok, looks like a problem with PKG_CONFIG_PATH not being set for gstreamer or sdl2.
I did not find those lines in the log, but I did find this:
```
    Detected Cython version 0.23
    User distribution detected, avoid portable command.
    Using this graphics system: OpenGL ES 2
    WARNING: A problem occured while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

    b"Package gstreamer-1.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `gstreamer-1.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'gstreamer-1.0' found\n"

    WARNING: A problem occured while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

    b"Package sdl2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `sdl2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'sdl2' found\nPackage SDL2_ttf was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_ttf.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_ttf' found\nPackage SDL2_image was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_image.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_image' found\nPackage SDL2_mixer was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_mixer.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_mixer' found\n"

    Xcode detected at b'/Applications/Xcode.app/Contents/Developer', and using OS X10.12 sdk
    running egg_info
    creating pip-egg-info/Kivy.egg-info
    writing dependency_links to pip-egg-info/Kivy.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/Kivy.egg-info/top_level.txt
    writing requirements to pip-egg-info/Kivy.egg-info/requires.txt
    writing pip-egg-info/Kivy.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/Kivy.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/Kivy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/Kivy.egg-info/SOURCES.txt'
     warning: manifest_maker: standard file '-c' not found

     warning: no files found matching '*.txt' under directory 'kivy/tools'
     warning: no files found matching '*.bat' under directory 'kivy/tools'
     warning: no files found matching '*.sh' under directory 'kivy/tools'
     warning: no files found matching '*.pyd' under directory 'kivy'
```

**Comment by manthansharma** [comment]
Can you share list the directories pkg-config looks in by default by using:
`pkg-config --variable pc_path pkg-config`

**Comment by swajime** [comment]
```
jwsimpsonosx:src jwsimpson$ pkg-config --variable pc_path pkg-config
/opt/local/lib/pkgconfig:/opt/local/share/pkgconfig
```

**Comment by dessant** [comment]
A fix for dependency discovery has been released with Kivy 1.10.0, please try removing Kivy and following the installation docs again: https://kivy.org/docs/installation/installation-osx.html.

**Comment by swajime** [comment]
[output.txt](https://github.com/kivy/kivy/files/981994/output.txt)
I'm still getting errors during the installation.

**Comment by dessant** [comment]
Your attached file is a bit huge (4 MB), please embed the relevant log parts in the post directly.

**Comment by swajime** [comment]
Running setup.py install for kivy ... error
    Complete output from command /Users/jwsimpson/.pyenv/versions/3.4.3/bin/python3.4 -u -c "import setuptools, tok$
    Using distutils
...
    fatal: Not a git repository (or any of the parent directories): .git
...
    clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -I/$
    In file included from /private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/kivy/cor$
    In file included from /Users/jwsimpson/.pyenv/versions/3.4.3/include/python3.4m/Python.h:25:
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include$
            unsigned char   *_base;
                            ^
... 
This is followed by hundreds of similar errors ...
Then:
    330 warnings and 1 error generated.
     error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/jwsimpson/.pyenv/versions/3.4.3/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/private$

**Comment by AI913** [comment]
> Running setup.py install for kivy ... error
> Complete output from command /Users/jwsimpson/.pyenv/versions/3.4.3/bin/python3.4 -u -c "import setuptools, tokenize;**file**='/private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record /var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-gzizcer_-record/install-record.txt --single-version-externally-managed --compile:
> Using distutils
> ...
> fatal: Not a git repository (or any of the parent directories): .git
> ...
> clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -arch x86_64 -I/private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/kivy/include -I/Library/Frameworks/SDL2.framework/Headers -I/Library/Frameworks/SDL2_ttf.framework/Headers -I/Library/Frameworks/SDL2_image.framework/Headers -I/Library/Frameworks/SDL2_mixer.framework/Headers -I/Users/jwsimpson/.pyenv/versions/3.4.3/include/python3.4m -c /private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/kivy/core/audio/audio_sdl2.c -o build/temp.macosx-10.12-x86_64-3.4/private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/kivy/core/audio/audio_sdl2.o -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -F/Library/Frameworks
> In file included from /private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/kivy/core/audio/audio_sdl2.c:4:
> In file included from /Users/jwsimpson/.pyenv/versions/3.4.3/include/python3.4m/Python.h:25:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/stdio.h:89:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
> unsigned char *_base; ^ ... This is followed by hundreds of similar warnings ... Then, I think this is the killer: /private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/kivy/lib/gstplayer/_gstplayer.c:432:10: fatal error: 'gst/gst.h' file not found
> #include "gst/gst.h"
> ^
> 330 warnings and 1 error generated.
> error: command 'clang' failed with exit status 1
> 
> Command "/Users/jwsimpson/.pyenv/versions/3.4.3/bin/python3.4 -u -c "import setuptools, tokenize;**file**='/private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record /var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-gzizcer_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0h/mkrh53x13f71gp141drj7yvr0000h_/T/pip-build-27zto6p0/kivy/

I have the same issue. How did you fix it?

**Comment by matham** [comment]
You're trying to compile kivy with gstreamer support, but gstreamer (headers) are not installed. You can e.g. disable gstreamer by setting `USE_GSTREAMER=0`, or you can install gstreamer similar to how we do it on the [CI](https://github.com/kivy/kivy/blob/master/.ci/osx_ci.sh#L36).
