### ISSUE TITLE
SVG: Implement "Q command"

### ISSUE THREAD

**Issue by mixmastamyk** [kivy/kivy#5131]
I have an svg logo with text converted to splines that makes kivy loop.  Spits out:
 
    WARNING Svg: unimplemented command Q

Looks like someone started some code on the subject but didn't get to finish.  

- https://github.com/kivy/kivent/blob/master/modules/core/kivent_core/rendering/svg_loader.pyx#L838

So I'm using PNG instead.

**Comment by KeyWeeUsr** [comment]
This is a KivEnt part of tools under the Kivy organisation. Please move this issue to kivy/kivent repository. :)

Anyway, @Kovak is it necessary to have two SVG loaders? I only scrolled a little bit, but the files seem to be the same(or almost), so why not import from kivy? I mean, the whole graphics part is imported anyway. Or is it about the runtime speed(nah, that can't be true)?

**Comment by Kovak** [comment]
There are a few important differences between the 2 implementations:

1. Kivy's SVG loader loads as triangle strips, KivEnt's as indexed triangles

2. KivEnt's contains some 'graphical fixes' to the algorithm found in Kivy's loader. In some cases these are adjustments I did based on my intuition about how GL renders colored vertices in order to improve the rendering output, however these changes are a little experimental and perhaps not functional in all cases (I haven't run into a case where they make things worse yet, but it is possible)

**Comment by mixmastamyk** [comment]
Sorry, not sure how I got to the kivent repo, guess goolge brought me there.  I don't have kivent installed so the kivy implementation is probably what I'm using.

**Comment by KeyWeeUsr** [comment]
Nah, I meant that the file you linked is from kivent, therefore if it's about an issue with that file, it should be placed under kivy/kivent repo. However the "Q" command isn't implemented even in kivy/kivy repo, so I'll leave this one open for now (no need for a separate kivent issue).

**Comment by mixmastamyk** [comment]
Yes, I'm having the problem with kivy, I've never had kivent installed.  A search engine must have brought me there.  Can fix the link if you'd like.

**Comment by TTN-** [comment]
Wow, can't plot graphs in kivy because graphs won't work with screenmanager, so I go to plot using matplotlib, then add as svg, and well, Svg's don't work in kivy either. I've run into the same issue as you folk. How else can I do plots? jpg's pixelate too much.

**Comment by matham** [comment]
You can try garden.matplotlib.

**Comment by TTN-** [comment]
I already did. It won't work with screenmanager. The plot will show up, but no data will get plotted, so I try to use kivy's SVG functionallity to import the graph I saved to disk to at least get a live plot working, that doesn't work either so now I'm importing jpgs to do live graphs. Not ideal? I should think so...

**Comment by tshirtman** [comment]
It seems support for 'Q' was started, but commented, so it's probably broken
https://github.com/kivy/kivy/blob/a4116a58d7c5448a4c6615021302375cbe3e129a/kivy/graphics/svg.pyx#L750-L785

could be interesting to see how and if it's possible to fix.
