### ISSUE TITLE
SVG: implement widget container

### ISSUE THREAD

**Issue by mixmastamyk** [kivy/kivy#5132]
As the docs mention, there needs to be an SVG widget made.  

I'm using this simple version in the meantime, and will likely improve it over time:

```python 

    class SVGWidget(RelativeLayout):
        source = StringProperty()

        def __init__(self, **kwargs):
            super().__init__(**kwargs)

        def on_source(self, instance, value):
            self.canvas.clear()   
            with self.canvas:
                svg = Svg(value)

            self.size = svg.width, svg.height
```

**Comment by KeyWeeUsr** [comment]
Afaik, SVG is considered here as a graphic instruction (like `Rectangle` or `Ellipse`), which means if we'd go for a widget, then we'd probably need one for the rest of the instructions (or people would start to demand them likewise). Most likely we aren't going that way.

Also, if you opened the [examples](https://github.com/kivy/kivy/blob/master/examples/svg/main.py#L11), you'd see a more usable implementation.

**Comment by mixmastamyk** [comment]
Hi, don't need a Scatter, I need to show an svg easily in a program just like an image, not manipulate it.  Guessing (though don't know for sure) that would be the majority use case.

The "more usable" implementation linked is not able to be used in .kv files, because you can't pass the filename argument that way.  So static layouts become impossible.

As this is how the Image works, I don't understand the reluctance to implement this.

(Now that I look again, I suppose the `__init__` is not needed.)
