### ISSUE TITLE
Cant start service app

### ISSUE THREAD

**Issue by Fogapod** [kivy/kivy#5140]
### Versions

* Python: 2.7
* OS: android
* Kivy: master

### Description

Service app raises android error right after starting. No exceptions, no kivy logs. Just do not start. Faced this problem only on android building with buildozer's `android_new` toolchain

### Code

I get code from here: https://github.com/tshirtman/kivy_service_osc
(changed [line 7 and 8](https://github.com/tshirtman/kivy_service_osc/blob/master/main.py#L7) to `from kivy import platform`)

### Logs
[Part of logcat where app fails to start service](https://gist.github.com/Fogapod/bf83faad62961a7e43a4b3bf2b70ba71)

Edit: removed apk.

**Comment by Bakterija** [comment]
The old method is broken for some reason in new toolchain.

**Comment by dessant** [comment]
This issue was moved to kivy/python-for-android#1049
