### ISSUE TITLE
Problem runnig the canocial kivy example

### ISSUE THREAD

**Issue by fma91** [kivy/kivy#5142]
### Versions

* Python:2.7
* OS:ubuntu 17
* Kivy:1.9.1
* Kivy installation method: conda (i was the only one that worked for me)

### Description

// REPLACE ME: 
I had problems trying to install kivy due to i was using pip and ii failed alot of times, the same happened using apt.. when i finally installed using conda, the module fails when i tried to run the example "hello world" . When i call kivy. app it fails and close ipython, but when i call pygame first it doesn't. 

When i use this code, next message comes out, what i am doing wrong or what module is lacking?
### Code and Logs

```python
// REPLACE ME: 
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

from kivy.app import App
[INFO              ] [Logger      ] Record log in /home/fma/.kivy/logs/kivy_17-04-28_15.txt
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pil (img_sdl2, img_ffpyplayer ignored)

from kivy.uix.button import Button
[INFO              ] [Text        ] Provider: pil(['text_sdl2'] ignored)

class TestApp(App):
    def build(self):
        return Button(text='Hello!!')
    

TestApp().run()
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name bcm
  File "/home/fma/anaconda2/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/fma/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - ImportError: /home/fma/anaconda2/lib/python2.7/site-packages/numexpr/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libmodplug.so.1)
  File "/home/fma/anaconda2/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/fma/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

x11 - ImportError: No module named window_x11
  File "/home/fma/anaconda2/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL          ] [App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL          ] [App         ] Unable to get a Window, abort.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

 /home/fma/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
   warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

```

**Comment by KeyWeeUsr** [comment]
`IPython 5.1.0` I haven't run Kivy in that, but Kivy works just fine when I run it from console directly, so try that first.

I really wonder how did you get to this version: `v1.9.1-dev`. It definitely appears either as a broken Kivy installation or as that you have broken/missing stuff in conda `libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libmodplug.so.1` Also, afaik, Ubuntu 17 was just a beta until recently so I guess you upgraded your system and most likely broke something along the way.

Anyway, go `pip list`ing and remove every Kivy mention and do a clean install afterwards. See [Installation](https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2) page and feel free to ignore venv if necessary although I think there are no problems with it on GNU/Linux distros.

**Comment by fma91** [comment]
Thank you,  i tried to install using pip before conda, but it says that it was unable to build kivy wheel and the installationnfailed. And this kivy versions was installed from anaconda cloud.

**Comment by KeyWeeUsr** [comment]
If you can provide a more verbose answer of from where, it'd be more helpful because the only thing a search engine gave me was either [this](https://duckduckgo.com/?q=anaconda+kivy+"1.9.1-dev") or [this](https://anaconda.org/akode/kivy/files) and the latter link is `1.9.1`(although maybe even -dev) for OSX and I'm not sure if conda actually checks for platform before installing or just installs whatever you throw at it. Can you retrieve the exact location you installed it from?

Also, to debug problems with installation [mailing list or IRC channels](https://kivy.org/#support) are suggested as this has nothing to do with a bug (for now), but even if pasted here as it sometimes happens, a log of the installation is required.

Have you tried to run the example with **python** directly i.e. not through `IPython`?

**Comment by fma91** [comment]
Thanks,

i  installed that kivy version using this comand:

conda install -c moritzimend kivy=1.9.0.

I tried your advice running it in python but the same thing happened.

i think that i am missing some module or library but i don't realise what is.

**Comment by dessant** [comment]
You have installed Kivy from an unofficial source which we do not support. Please try installing the daily PPA, the stable one is known to have issues: https://kivy.org/docs/installation/installation-linux.html#ubuntu-kubuntu-xubuntu-lubuntu-saucy-and-above.

**Comment by fma91** [comment]
thank you, i run the daily PPA and it worked, but only outside anaconda
