### ISSUE TITLE
No module named recyleview

### ISSUE THREAD

**Issue by EnoraNedelec** [kivy/kivy#5148]
### Versions

* Python: 3.6
* OS: Windows 7 and Ubuntu 17.04
* Kivy: 1.9.2 dev
* Kivy installation method: Kivy Launcher and copy apk build with buildozer in android

### Description

I tried to run an app with recycleview on my android phone 

I tried to run the app with Kivy Launcher (first with the recycleview folder copied in my app folder and then by copying the 4 file directly in my app folder and modifying the import). 
I also tried to package the app with buildozer. 

In both case the error is the same: "No module named recyleview". 

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.recycleview import RecycleView
from kivy.uix.boxlayout import BoxLayout
from kivy.properties import StringProperty
from kivy.uix.recycleview.views import RecycleDataViewBehavior

items = [
    {"text": "white",    "selected": 'normal', "input_data": ["some","random","data"]},
    {"text": "lightblue","selected": 'normal', "input_data": [1,6,3]}
]

class MyViewClass(RecycleDataViewBehavior, BoxLayout):

    text = StringProperty("")
    index = None

    def set_state(self,state,app):
        app.root.ids.rv.data[self.index]['selected'] = state

    def refresh_view_attrs(self, rv, index, data):
        self.index = index
        return super(MyViewClass, self).refresh_view_attrs(rv, index, data)

class MyRecycleView(RecycleView):

    data = items

    def print_data(self,data):
        print([item['input_data'] for item in data if item['selected'] == 'down'])

KV = '''

<MyViewClass>:
    orientation: 'horizontal'
    CheckBox:
        on_state: root.set_state(self.state,app)
    Label:
        text: root.text

BoxLayout:
    orientation: 'vertical'
    MyRecycleView:
        id: rv
        viewclass: 'MyViewClass'
        RecycleBoxLayout:
            orientation: 'vertical'
            default_size: None, dp(56)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
    Button:
        size_hint_y: 0.1
        text: "Print data"
        on_release: rv.print_data(rv.data)

'''

class Test(App):
    def build(self):
        root = Builder.load_string(KV)
        return root


Test().run()
```

**Log**
I/python  (10993): Initialize Python for Android
I/python  (10993): ['/data/data/org.test.myapp/files/lib/python2.7/site-packages', '/data/data/org.test.myapp/files/lib/site-python']
I/python  (10993): Android path ['/data/data/org.test.myapp/files/lib/python27.zip', '/data/data/org.test.myapp/files/lib/python2.7', '/data/data/org.test.myapp/files/lib/python2.7/lib-dynload', '/data/data/org.test.myapp/files/lib/python2.7/site-packages', '/data/data/org.test.myapp/files', '/data/data/org.test.myapp/files/_applibs']
I/python  (10993): Android kivy bootstrap done. __name__ is __main__
I/python  (10993): Run user program, change dir and execute main.py
I/python  (10993): [INFO              ] [Logger      ] Record log in /data/data/org.test.myapp/files/.kivy/logs/kivy_17-05-01_0.txt
I/python  (10993): [INFO              ] [Kivy        ] v1.9.1
I/python  (10993): [INFO              ] [Python      ] v2.7.2 (default, Apr 30 2017, 20:14:06) 
I/python  (10993): [GCC 4.8]
I/python  (10993): [INFO              ] [Factory     ] 179 symbols loaded
I/python  (10993):  /data/data/org.test.myapp/files/lib/python2.7/site-packages/kivy/core/image/img_pygame.py:13: RuntimeWarning: import cdrom: No module named cdrom
I/python  (10993):  (ImportError: No module named cdrom)
I/python  (10993): [INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
I/python  (10993):  Traceback (most recent call last):
I/python  (10993):    File "/home/name/Desktop/.buildozer/android/app/main.py", line 3, in <module>
I/python  (10993):  ImportError: No module named recycleview
I/python  (10993): Python for android ended.

**Comment by Bakterija** [comment]
I/python (10993): [INFO ] [Kivy ] v1.9.1

1.9.1 does not have recycleview

**Comment by EnoraNedelec** [comment]
Thanks for your answer. I am surprised, I have installed Kivy 1.9.2 dev. Where does this Kivi 1.9.1 comes from? Does it come from buildozer?

**Comment by Bakterija** [comment]
You have to open buildozer.spec file, find the line with requirements, change kivy to kivy==master.
After that it should build with kivy 1.9.2.

**Comment by EnoraNedelec** [comment]
I am not sure which line you are talking about:
I see 
```
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy 
```
which I have replace by 
```
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy==master
```

And also #
```
 Kivy version to use
osx.kivy_version = 1.9.1
```

which I have replaced by 

```
# Kivy version to use
osx.kivy_version = kivy==master
```

I get the error error: command 'ccache' failed with exit status 1

**Comment by EnoraNedelec** [comment]
Sorry, I had a typo, it's working now! Thanks a lot!

**Comment by EnoraNedelec** [comment]
d
