### ISSUE TITLE
Loading UTF8 KV file with Japanese (multi-byte?) text crashes Kivy under Windows

### ISSUE THREAD

**Issue by yk0242** [kivy/kivy#5154]
### Versions

* Python: 3.4.4
* OS: Windows 10 Home
* Kivy: 1.9.1
* Kivy installation method: followed https://kivy.org/docs/installation/installation-windows.html#installation

### Description

Loading a UTF8 KV file with Japanese (and perhaps other multi-byte?) text crashes Kivy under Windows. The example below uses the text field, but even a comment in Japanese will cause the crash. Changing the KV file encoding to Shift-JIS (approximately cp932) fixes the issue. 

Full details can be found in this user support group post: https://groups.google.com/forum/#!topic/kivy-users/dlR0f6tmANw

The essence is that, this fact combined with the fact that Linux-type systems support UTF8 KV files and NOT Shift-JIS KV files makes cross-platform development very difficult. 

Issue #4003 mentions a display glitch, but I believe a crash is more serious and may merit being dealt with. 

### Code and Logs

The following will reproduce the issue; the commented out alternatives are to show the options that work properly (without crashing).

utftest.py
```python
# -*- coding: utf-8 -*-

# test using kivy KV File in UTF8 with Japanese text

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

# # This will load properly (ignoring the fact that a font set needs to be loaded separately for proper display)
# Builder.load_string('''
# <UtfTestScreen>
#     Label:
#         # font_name: '../SourceHanSerifJP/SourceHanSerifJP-Medium.otf'
#         id: inst_txt
#         text: u'テストテキスト'
#
# ''')


class UtfTestScreen(BoxLayout):
    def __init__(self, **kwargs):
        super(UtfTestScreen, self).__init__(**kwargs)

        # # Test using Japanese text from py file to kv specified parts
        # self.ids.inst_txt.text = 'テストテキスト'


class UtfTestApp(App):
    def build(self):
        return UtfTestScreen()


if __name__ == "__main__":
    UtfTestApp().run()

```

utftest.kv **(saved in UTF8 encoding)**
```
<UtfTestScreen>
    Label:
        # font_name: '../SourceHanSerifJP/SourceHanSerifJP-Medium.otf'
        id: inst_txt
        text: u'テストテキスト'

```

caused an error as below:
```
 Traceback (most recent call last):
   File "utftest.py", line 34, in <module>
     UtfTestApp().run()
   File "C:\Python34\lib\site-packages\kivy\app.py", line 801, in run
     self.load_kv(filename=self.kv_file)
   File "C:\Python34\lib\site-packages\kivy\app.py", line 598, in load_kv
     root = Builder.load_file(rfilename)
   File "C:\Python34\lib\site-packages\kivy\lang.py", line 1831, in load_file
     data = fd.read()
 UnicodeDecodeError: 'cp932' codec can't decode byte 0x86 in position 141: illegal multibyte sequence

Process finished with exit code 1
```

**Comment by matham** [comment]
The fix is easy enough, read in as bytes and decode to utf8 after reading. The question is whether we can always assume that the file is in utf8? Or maybe we need to have a way to specify the encoding like a shabang. Then by default it'll use the platform encoding, but it can be overwritten.

**Comment by yk0242** [comment]
There is some similar discussion in #4003 , and I agree with VinGarcia's comment on 11 Apr 2016, to quote: 

> The best would probably be to mimic python behavior:
>    * Expect programmer to specify the encoding on the first line.
>    * Or else use python default encoding (on python3 it would always be 'utf8' I think).

If the default were to be made UTF8 on both Windows and Linux, or else the encoding be made specifiable as above, it'd really help me on this issue...

**Comment by yk0242** [comment]
From the user support group above, @Geekademy shared an idea to use
```python
with open(filename, encoding='utf8') as f: 
    Builder.load_string(f.read()) 
```
in place of the usual `Builder.load_file()` , which seems to work properly for me. 
Although this is great as a temporary workaround, official Kivy Support of the above idea would be even greater...

**Comment by yk0242** [comment]
I have uploaded the minimal case, including points from this issue as comments: 

* https://github.com/yk0242/incubation/blob/master/incubation-python/kv-utf8/utftest.py
* https://github.com/yk0242/incubation/blob/master/incubation-python/kv-utf8/utftestkv.kv

Please feel free to use these for purposes of investigating this issue.

**Comment by jsbueno** [comment]
I found the same issue on answering an S.O. question yesterday.
SO, this _is_ actually a bug on Kivy, since  any app that is build even on systems that use utf-8 by default will fail to properly load non-ascii characters from the .KV on the "automatic" loading way, when they are run under windows.

To put it in other words: for any i18ned KV file, the app will break either when run on Windows, unless the .KV file uses the native windows encoding on the developer's computer. (in which case it won't work elsewhere)

IMHO, the fix would be forcing kivy to load .kv files using "utf-8" encoding and document that.

(I have no windows install, but the OP just accepted my answer, indicating this was indeed the problem - 
https://pt.stackoverflow.com/questions/281641/como-configurar-o-portugu%C3%AAs-no-kivy/281664#281664 )

**Comment by dolang** [comment]
This just came up again in #5738. The solution is to use `Builder.load_string(...)` as mentioned [above](https://github.com/kivy/kivy/issues/5154#issuecomment-299070894).

It's not actually a bug in Kivy.

If anything, it's an unfortunate design decision in Python and a missing feature in Kivy.

The real answer here is: it's complicated. If `utf-8` were forced, it would simply break on files with bytes that aren't valid UTF-8. Compare [UTF-8](https://en.wikipedia.org/wiki/UTF-8#Codepage_layout) and [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252#Character_set) codepages. There are combinations of bytes in either that break decoding of the other.

**Comment by yk0242** [comment]
I understand that this is not a *bug* in Kivy per se, but rather a missing feature (that would be greatly welcomed by the likes of myself). 

Having said that, I think [the commit by jsbueno](https://github.com/jsbueno/kivy/commit/ea255dac3f0848a1e3c2101d45cf7f770a4b8e25) (that I just now noticed...) would circumvent the problem well, assuming that the *'combinations of bytes in either that break decoding of the other' [mentioned by dolang](https://github.com/kivy/kivy/issues/5154#issuecomment-387188203) will properly raise a `UnicodeDecodeError` when met*. I'm not sure if this is indeed the case, and if this is not so (i.e., if the `open` function opens the file without raising said error *and* opens it in a broken manner), the said commit won't work in some environments. 

Otherwise, I believe that a fix that tries both encodings by default (be it UTF-8 -> native as in commit, or explicitly UTF-8 -> CP932 -> native, etc.) would be extremely friendly for non-ASCII developing environments...

**Comment by dolang** [comment]
I've had a short look at it, there might be some issues with that pull request.

Just fyi, there's been some talk about how to fix the general problem. Ultimately the solution might be a bit different. And no promises yet, either.

**Comment by yk0242** [comment]
Any valid fix would be greatly appreciated. No promises, I understand, but still keeping my hopes up...

**Comment by macosala** [comment]
This issue can be solved by setting PYTHONUTF8 as 1.
set PYTHONUTF=1
python _<args>_

or -Xutf8 option can be simply add as below;
python -Xutf8 _<args>_

The option was added to python 3.7. Details are in https://www.python.org/dev/peps/pep-0540/
