### ISSUE TITLE
Kivy 1.10 OSX portable package points to a wrong Python version

### ISSUE THREAD

**Issue by jabbson** [kivy/kivy#5159]
### Versions

* Python: 3.5
* OS: MacOS
* Kivy: 1.10
* Kivy installation method: portable package

### Description

A portable package, that can be downloaded from kivy website directly

- https://kivy.org/downloads/1.10.0/

or using the links to google driver found here:

- https://kivy.org/#download

namely **Kivy-1.10.0-osx-python3.5.dmg** includes a link to a wrong Python version.

After downloading, copying to Application and making a symlink, this is where it gets me (please note the python version):

```
mbook:venv jabbson$ kivy
Python 2.7.10 (default, Feb  6 2017, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

also

```
mbook:/ jabbson$ cd Applications/Kivy.app/Contents/Resources/venv/
mbook:venv jabbson$ ls -al | grep .Python
lrwxr-xr-x   1 jabbson  admin    63 May  7 19:12 .Python -> /System/Library/Frameworks/Python.framework/Versions/2.7/Python
```

also

```
>>> import kivy
[INFO   ] [Logger      ] Record log in /Applications/Kivy.app/Contents/Resources/.kivy/logs/kivy_17-05-08_1.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.10 (default, Feb  6 2017, 23:53:20)
```

**Comment by akshayaurora** [comment]
https://drive.google.com/open?id=0B1WO07-OL50_RWx6a0pHRTZRN2M

Can you test this, It still complains about one of the missing libs but should still work as they seem to be optional, will be fixing that issue too before uploading officially.

Just looking for any issues with this package right now.

**Comment by brsaylor** [comment]
The version on Google Drive works for me (uses Python 3.5, at least):

```
venv $ kivy
Python 3.5.0 (default, May  8 2017, 23:04:33)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.30.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy
[INFO   ] [Logger      ] Record log in /Applications/Kivy.app/Contents/Resources/.kivy/logs/kivy_17-05-16_1.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.0 (default, May  8 2017, 23:04:33)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.30.5)]
```

**Comment by akshayaurora** [comment]
closed by the latest release. @jabbson new packages and wheels available for the latest release.
