### ISSUE TITLE
Fullscreen unavoidable

### ISSUE THREAD

**Issue by federico28x** [kivy/kivy#5161]
Versions

Python: 3.4.2
OS: Raspberry Jessie PIXEL (last version)
Kivy: 1.9.2
Kivy installation method: Global install 
sudo pip install git+https://github.com/kivy/kivy.git@master

Description

Trying to run any app (i.e. minimum example "main.py" or any app) shows always in fullscreen.
No matter if I edit config file, or add config "graphic", "fullscreen", "0" in app.  
I've done clean install from cython (0.23), kivi (1.9.2), & dependencies.
Same results.

**Comment by dessant** [comment]
This is a limitation of the RPI window provider, you may want to switch to SDL2 for windowed mode.
The `USE_SDL2=1` environment variable must be set before compiling Kivy, and `KIVY_WINDOW='sdl2'` will force the SDL2 window provider if set before importing Kivy during runtime.


https://kivy.org/docs/installation/installation-rpi.html
