### ISSUE TITLE
Documentation and textinput.py comments for paste keyboard shortcut

### ISSUE THREAD

**Issue by Leon-Davison** [kivy/kivy#5172]
Just some documentation fixes, as well as comments in textinput.py.

**Kivy.pdf page 622 in the Default shortcuts section**

Currently:
Control+**p** Paste **selection**

Should be:
Control+**v** Paste **clipboard data**

**https://kivy.org/docs/api-kivy.uix.textinput.html**

Currently:
Control + **p**    Paste **selection**

Should be:
Control + **v**    Paste **clipboard data**

**kivy/uix/textinput.py , Line 131**

Currently:
Control + **p**    Paste **selection**

Should be:
Control + **v**    Paste **clipboard data**

**kivy/uix/textinput.py Line 2405**

Currently:
elif key == ord('v'):  # paste **selection**

Should be:
elif key == ord('v'):  # paste **clipboard data**

**Comment by dessant** [comment]
Nice find! Could you edit the module and submit your changes in a pull request?
https://github.com/kivy/kivy/blob/master/kivy/uix/textinput.py

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/issues/5177.
