### ISSUE TITLE
No matching distribution found for kivy

### ISSUE THREAD

**Issue by nkengasongatem** [kivy/kivy#5174]
Hi guys I am new to python and kivy. I have a project so i decided to start working on kivy but i have serious installation problems that have kept me off for weeks. My problem has already been reported but none of the solutions work for me. 

When i type: python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
i get:

  Could not find a version that satisfies the requirement kivy.deps.sdl2 (from versions: )
No matching distribution found for kivy.deps.sdl2

and when i type: python -m pip install kivy
i get:  Could not find a version that satisfies the requirement kivy (from versions: )
No matching distribution found for kivy

I have tried so many things and have spent hours over the internet looking for the solution but nothing works for me. Help is high welcome.
PS: I am using python 3.6.0 and Pycharm as IDE on Windows 10  64 bits

**Comment by nkengasongatem** [comment]
![kivy error_2](https://cloud.githubusercontent.com/assets/24443502/26027882/f2a59ce2-380d-11e7-8e01-7b53ed0c1a43.jpg)

This is an apercu of my problem

**Comment by pythonic64** [comment]
Did you installed latest pip, wheel setuptools? If not then run: 
```python -m pip install --upgrade pip wheel setuptools```

**Comment by nkengasongatem** [comment]
Yes I have. It installs without any problem. Problems start with:
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew

**Comment by pythonic64** [comment]
Is the same error log when you run: 
```python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew``` 
as when trying to install kivy? 

Did you tried to install each package individually?
As a last option you can download packages manually from [PyPI](https://pypi.python.org/pypi).

**Comment by dessant** [comment]
This does not appear to be a Kivy issue, please join us on irc if you need further help. https://github.com/kivy/kivy#support

**Comment by jadwight** [comment]
Dessant you're actually incorrect it is a Kivy issue somewhat. If Python releases a new version and Kivy is not updated for the latest version users will experience this due to "No matching distribution found". Primary example is if a user right now downloads the latest Python which is 3.7, if you look in github the latest Kivy repository does not have a release for 3.7 therefore when people go to attempt the pip install for it they will be greeted with the "No matching distribution found".

Recommendation to the user is that if you want to use Kivy check the repo:
https://pypi.org/project/kivy.deps.sdl2/#files

If it doesn't have a file for your version of python then go back to the last version of python that Kivy has a file for... ;)

**Comment by dolang** [comment]
@jadwight Regarding py3.7: The [documentation has already been updated](https://kivy.org/docs/gettingstarted/installation.html).

At the moment, It's actually an AppVeyor issue (see #5832). Yes, we'd all like to have binaries available for everything as soon as a new Python release is out, but the reality is a bit different.

Also, this issue has been opened on 2018-05-13, so it's unrelated to Python 3.7 anyway.

**Comment by dessant** [comment]
Should we activate https://probot.github.io/apps/lock/ for closed issues that have not seen any activity in the past year?

**Comment by bgshacklett** [comment]
@dolang Not all of it. The installation guide at https://kivy.org/docs/installation/installation-windows.html makes no mention of this issue.

**Comment by dolang** [comment]
@bgshacklett That's true. But there are a lot of other special cases that aren't covered in the documentation, either.

And to pre-empt that question:
- This one is special in the sense that people are expected to first click on "Installation" and then use one of the buttons for their respective platform.
- Python 3.7 is new, it's a temporary problem, the devs are aware of it. If you encounter this or another problem, please use one of the [support channels](https://kivy.org/#support), read the version information on [PyPI](https://pypi.org/project/Kivy/) or [setup.py](https://github.com/kivy/kivy/blob/master/setup.py#L1086-L1089), or use the search engine of your choice (you've found this issue and the explanation, right?).

https://github.com/kivy/kivy/blob/df7de2042ae4e0f820bbe91ab9f485d746c52fae/setup.py#L1086-L1089

Sorry, but I'm not going to argue this point any further in an outdated, unrelated issue (if you want to, try e.g. IRC). Locking.
