### ISSUE TITLE
Can't support official library asyncore.dispatcher in python3

### ISSUE THREAD

**Issue by yingshaoxo** [kivy/kivy#5176]
Anyway, official library `asyncore` is a great tool for handling asynchronous task.

If you want to let kivy really support python3, then you should add `asyncore` to kivy frameworks.

**Comment by dessant** [comment]
This pr may be of help https://github.com/kivy/kivy/pull/4525.

**Comment by yingshaoxo** [comment]
Didn't work for me.

**Comment by yingshaoxo** [comment]
I solved it using threading.

https://github.com/yingshaoxo/Kivy-Chat
