### ISSUE TITLE
Logger: Cant Disable, cant replace.

### ISSUE THREAD

**Issue by juancarlospaco** [kivy/kivy#5183]
### Versions

* Python: 3.6.1
* OS: Linux x 4.10.11-1-ARCH 1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux Arch Linux
* Kivy: 1.10.0
* Kivy installation method: From Kivy Docs

### Description

What are you trying to get done:
- Use my own custom pure Python logger sub-classed from builtin standard lib `logging`.
- Be free to NOT use a logger.
- Be free to Disable the logger.

What has happened:
Even on `import kivy` I already got an unwanted logger and an unwanted log file.
I need to disable builtin Kivy logger.
I need to be able to use my own custom logger if I want to.

What went wrong:
- Completely Disable builtin default Kivy Logger.
- Use my own custom pure Python logger sub-classed from builtin standard lib `logging`.

What did you expect?:
```python
from kivy.logger import Logger
Logger.disabled = True
```

Should be enough to Completely Disable the Logger.

Or implement the reverse, create a `kivy.enable_logger()` that fires up builtin default Kivy logger.

### Code and Logs

I do NOT want files on `/home/juan/.kivy/logs/*`

```bash
juan@x ~ $ python -c "import kivy"
[INFO   ] [Logger      ] Record log in /home/juan/.kivy/logs/kivy_17-05-17_18.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.1 (default, Mar 27 2017, 00:27:06)
[GCC 6.3.1 20170306]
. . .
```

I can not Disable the Logger:

```python
from kivy.logger import Logger
from kivy.config import Config
Logger.disabled = True
Config.set('kivy','log_enable', '0')
Logger = None
del Logger
# And I still got Logger messages somehow.
```

Example from Template still creates unwanted log files on `/home/juan/.kivy/logs/kivy_DATE.txt`:

```python
from kivy.config import Config
from kivy.logger import Logger
Logger.disabled = True
Config.set('kivy','log_enable', '0')
# Logger = None  # You can try comment out this line,its the same results.
# del Logger  # You can try comment out this line,its the same results.

from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.uix.boxlayout import BoxLayout

kv = """
#:import rand_float random.uniform


<CustomLabel@Label>:
    canvas.before:
        Color:
            rgb: [rand_float(0.3, 0.7) for _ in range(3)]
        Rectangle:
            pos: self.pos
            size: self.size
    text: 'New label'


<Test>:
    Button:
        text: 'Add a new label'
        on_press: root.add_label()
    BoxLayout:
        id: box
        orientation: 'vertical'
"""


class Test(BoxLayout):
    def __init__(self, *args, **kwargs):
        super(Test, self).__init__(*args, **kwargs)
        self.add_label()

    def add_label(self):
        self.ids.box.add_widget(Factory.CustomLabel())


class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    Builder.load_string(kv)
    TestApp().run()
```

Dont force a god-mode unkillable Logger by default.

**Comment by pythonic64** [comment]
See this [link ](https://kivy.org/docs/guide/environment.html#configuration) for help

**Comment by juancarlospaco** [comment]
Ok, sorry, thats seems to fix the problem.

**Comment by bronger** [comment]
I'm still interested to know why
```
Config.set("kivy", "log_enable", "0")
```
does not help.  Did this use to work, but does not with current versions?

**Comment by kosarev** [comment]
Calling
```
 os.environ["KIVY_NO_FILELOG"] = "1"
```
in the middle of `import`s breaks PEP8 E402 "module level import not at top of file". Is there a way to do it "right"?
