### ISSUE TITLE
`bar_margin` only affecting the appearance of scrollbar in `ScrollView`

### ISSUE THREAD

**Issue by rhyzomatic** [kivy/kivy#5184]
### Versions

* Python: 3.6.1
* OS: Arch Linux
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I am trying to use the `bar_margin` keyword arg of the `ScrollView` class to change the position of the scrollbar when `scroll_type=['bars']`. When I set `bar_margin`, the scrollbar is correctly rendered in a different position, but then it cannot be dragged using the mouse. Instead, the user still needs to click in the original spot as if `bar_margin=0` in order to drag the scrollbar.

### Code and Logs

```python
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.scrollview import ScrollView
from kivy.core.window import Window
from kivy.app import runTouchApp

layout = GridLayout(cols=1, spacing=10, size_hint_y=None)
# Make sure the height is such that there is something to scroll.
layout.bind(minimum_height=layout.setter('height'))
for i in range(100):
    btn = Label(text=str(i), size_hint_y=None, height=40)
    layout.add_widget(btn)
root = ScrollView(size_hint=(1, None), size=(Window.width, Window.height), scroll_type=["bars"], bar_margin=40, bar_width=20)
root.add_widget(layout)

runTouchApp(root)

```

**Comment by CRBP8B** [comment]
I see what you mean, viewing the app that results from the code you posted. I'll take a look at it.
