### ISSUE TITLE
Pyinstaller SDL2 error

### ISSUE THREAD

**Issue by ErenPhayte** [kivy/kivy#5186]
So the issue I have is that when I compile an OSX application using Kivy it seems like the application compiles correctly. It includes the SDL2 provider.

However when I run the program from the compiled code I get the following and I cant figure out what the issue is. Seems like its missing the image providers. Any suggestions?

**Extract from pyinstaller**
`
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Kivy        ] v1.9.2.dev0, git-Unknown, 20170505
[INFO   ] [Python      ] v3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
1276 DEBUG: collect_submodules - Found submodules: {'kivy.graphics.cgl_backend.cgl_gl', 'kivy.graphics.gl_instructions', 'kivy.graphics.cgl_backend.cgl_glew', 'kivy.graphics.vertex_instructions', 'kivy.graphics.cgl_backend.cgl_debug', 'kivy.graphics.scissor_instructions', 'kivy.graphics.opengl', 'kivy.graphics.svg', 'kivy.graphics.compiler', 'kivy.graphics.fbo', 'kivy.graphics.vertex', 'kivy.graphics.cgl_backend.cgl_mock', 'kivy.graphics.context_instructions', 'kivy.graphics.texture', 'kivy.graphics.tesselator', 'kivy.graphics', 'kivy.graphics.context', 'kivy.graphics.cgl_backend', 'kivy.graphics.shader', 'kivy.graphics.opengl_utils', 'kivy.graphics.buffer', 'kivy.graphics.cgl_backend.cgl_sdl2', 'kivy.graphics.instructions', 'kivy.graphics.cgl', 'kivy.graphics.vbo', 'kivy.graphics.stencil_instructions', 'kivy.graphics.transformation'}
1280 DEBUG: Collecting submodules for kivy.core
[INFO   ] [Logger      ] Record log in /Users/johsteyn/.kivy/logs/kivy_17-05-18_49.txt
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Kivy        ] v1.9.2.dev0, git-Unknown, 20170505
[INFO   ] [Python      ] v3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
[INFO   ] [AudioGstplayer] Using Gstreamer 1.10.4.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer, audio_avplayer ignored)
[INFO   ] [Camera      ] Provider: avfoundation
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_nspaste'] ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.24.45'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel Iris OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Spelling    ] Provider: enchant
[INFO   ] [VideoGstplayer] Using Gstreamer 1.10.4.0
[INFO   ] [Video       ] Provider: gstplayer
`

**Extract from application**

`
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_kivy.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running pyi_rth_mplconfig.py
LOADER: Running pyi_rth_mpldata.py
LOADER: Running pyi_rth_enchant.py
LOADER: Running pyi_rth_gstreamer.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running main.py

[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers:  (img_imageio, img_tex, img_dds, img_ffpyplayer, img_pil, img_gif, img_sdl2 ignored)
[CRITICAL] [App         ] Unable to get any Image provider, abort.
LOADER: Back to parent (RC: 1)
LOADER: Doing cleanup
LOADER: Freeing archive status for ****
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
`

**Spec file**

`
block_cipher = None
from kivy.tools.packaging.pyinstaller_hooks import get_deps_all, hookspath, runtime_hooks
from kivy.tools.packaging.pyinstaller_hooks import get_hooks

a = Analysis(['main.py'],
             pathex=['/****'],
             binaries=[],
             datas=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             **get_deps_all(),
             **get_hooks())
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='****',
          debug=True,
          strip=False,
          upx=False,
          console=True,
          icon='icon.png')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               Tree('/Applications/Kivy3.app/Contents/Frameworks/SDL2.framework'),
               Tree('/Applications/Kivy3.app/Contents/Frameworks/SDL2_image.framework'),
               Tree('/Applications/Kivy3.app/Contents/Frameworks/SDL2_ttf.framework'),
               Tree('/Applications/Kivy3.app/Contents/Frameworks/SDL2_mixer.framework'),
               strip=False,
               upx=False,
               name='***')

app = BUNDLE(coll,
             name='****.app',
             icon='icon.png',
            bundle_identifier=None)
`

**Comment by ErenPhayte** [comment]
Further details. I got it to compile on my Mac, but when I run it else where this is what I get:



`
PyInstaller Bootloader 3.x
LOADER: executable is /****
LOADER: homepath is /****
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /****
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /****
LOADER [ARGV_EMU]: AppleEvent - processing...
LOADER [ARGV_EMU]: AppleEvent - installed handler.
LOADER [ARGV_EMU]: AppleEvent - calling ReceiveNextEvent
LOADER [ARGV_EMU]: ReceiveNextEvent got an eventLOADER [ARGV_EMU]: processing events failedLOADER [ARGV_EMU]: Out of the event loop.PyInstaller Bootloader 3.x
LOADER: executable is /****
LOADER: homepath is /****
LOADER: _MEIPASS2 is /****
LOADER: archivename is /****
LOADER: Already in the child - running user's code.
LOADER: Python library: /***/Python
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is /****/base_library.zip:/****
LOADER: sys.prefix is /***
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /****/base_library.zip:/****
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_kivy.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth_mplconfig.py
LOADER: Running pyi_rth_mpldata.py
LOADER: Running pyi_rth_gstreamer.py
LOADER: Running pyi_rth_enchant.py
LOADER: Running main.py
[INFO   ] [Logger      ] Record log in /*****/.kivy/logs/kivy_17-05-25_1.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.1 (default, Apr  4 2017, 09:40:51) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_sdl2, img_pil (img_imageio, img_tex, img_dds, img_ffpyplayer, img_gif ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.14.73'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel HD Graphics 5000 OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[WARNING] [Image       ] Unable to load image </****/kivy_install/data/glsl/default.png>
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - Exception: SDL2: Unable to load image
  File "kivy/core/__init__.py", line 67, in core_select_lib
  File "kivy/core/window/window_sdl2.py", line 140, in __init__
  File "kivy/core/window/__init__.py", line 899, in __init__
  File "kivy/core/window/window_sdl2.py", line 291, in create_window
  File "kivy/core/window/__init__.py", line 1051, in create_window
  File "kivy/graphics/instructions.pyx", line 758, in kivy.graphics.instructions.RenderContext.__init__ (/private/var/folders/jp/q_vfmdm936d9crkpt15n80tdrn9266/T/pip-build-ff4oqvd4/kivy/kivy/graphics/instructions.c:12580)
  File "kivy/core/image/__init__.py", line 538, in __init__
  File "kivy/core/image/__init__.py", line 734, in _set_filename
  File "kivy/core/image/__init__.py", line 435, in load
  File "kivy/core/image/__init__.py", line 201, in __init__
  File "kivy/core/image/img_sdl2.py", line 41, in load

 Traceback (most recent call last):
   File "****/main.py", line 38, in <module>
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
   File "***/__init__.py", line 2, in <module>
     Modules
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
   File "****", line 3, in <module>
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
   File "cairosvg/__init__.py", line 29, in <module>
     -------------------
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
   File "cairosvg/surface.py", line 24, in <module>
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
   File "cairocffi/__init__.py", line 41, in <module>
     touchring =
   File "cairocffi/__init__.py", line 38, in dlopen
     
 OSError: dlopen() failed to load a library: cairo / cairo-2
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /****


`

**Comment by dessant** [comment]
We do not support using PyInstaller with Kivy.app on macOS, it may work, bot we don't test for it. Try installing Kivy with pip and its dependencies with homebrew, then follow the packaging docs.

https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip
https://kivy.org/docs/guide/packaging-osx.html#using-pyinstaller-and-homebrew

**Comment by ErenPhayte** [comment]
I used the homebrew with pip step and got the same results.

**Comment by dessant** [comment]
@ErenPhayte, please open a new issue with all the relevant code and logs, and use code tags in your posts. Also follow the issue template.
