### ISSUE TITLE
Kivy - Complex shapes with vector or matrix

### ISSUE THREAD

**Issue by rafaelcb21** [kivy/kivy#5199]
### Versions

* Python: 3.6.1
* OS: Ubuntu 16.4
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I'm trying to create with vector the figure below in Kivy, however I'm not able to create it. I only find instructions for basic shapes.

![cruz2](https://cloud.githubusercontent.com/assets/9912894/26529304/0b0031a8-4394-11e7-8dc5-5bd24319c0c2.png)

Could someone help me with this problem or clarify to me if it is possible to create more complex shapes in Kivy?

Thank you

**Comment by KeyWeeUsr** [comment]
I'm not really sure what are you asking. For drawing such a shape you can use e.g. line. If it's about vector graphics, then there's SVG you have to create beforehand.

**Comment by rafaelcb21** [comment]
Thank you for clarifying me. As I learn more about Kivy some concepts are becoming clearer.
