### ISSUE TITLE
GstPlayerException: Unable to create a playbin (another one...)

### ISSUE THREAD

**Issue by embryo10** [kivy/kivy#5203]
### Versions

* Python: 2.7.13 x86
* OS: Windows 7 x64 SP1
* Kivy: 1.10.0
* Kivy installation method: Pip
* kivy.deps.gstreamer: 1.12
* kivy.deps.sdl2: 1.17
* PyInstaller: 3.2.1

### Description
I already read the #4652 #5099 #4931 #2381 #4184 issues.
They suggest that this was a PyInstaller bug that is now fixed, but it's not for me.
I manually copied the fixed `pyi_rth_kivy.py` from kivy to PyInstaller. Nothing changed.
The code works OK by itself, it plays wavs and everything, but when I create an executable with PyInstaller I get this GstPlayerException.
The program opens and works fine except when I try to play a wav with Soundloader.
It crashes with the Unable to create a playbin Exception.

Because of a previous PyInstaller bug, I install python and all the libraries from scratch.
PyInstaller works now when I create executables with PySide or wxPython and almost with kivy. Another project that doesn't use audio works fine.

And a question more.
Before the kivy.deps I had GStreamer installed outside of the Python directory and I was using the GST_PLUGIN_PATH and GST_REGISTRY env vars.
Should I use them now also, and where should they point?
Could be the solution to this problem?

### Code and Logs

I don't think that a sample code is needed. Just trying to load a wav.
Here is the [app's debugging log](https://gist.github.com/embryo10/1e75a36ca02650e63b5d4f9d0c343c53), [PyInstaller compiling log](https://gist.github.com/embryo10/9f7534dc6fbb4843b6784d8f7bbb1ff4) and [build warning file](https://gist.github.com/embryo10/d7b18c0f675a3da9b72d2692ceb2ddb6).

**Comment by embryo10** [comment]
For completeness sake, here is a minimal script that produces the same error.
```python
# coding=utf-8
from __future__ import absolute_import, division, print_function, unicode_literals

from kivy.app import App
from kivy.core.audio import SoundLoader
from kivy.uix.floatlayout import FloatLayout
from kivy.lang import Builder

Builder.load_string('''
<Base>:
    ToggleButton:
        id: play
        text: 'Play' if self.state == 'normal' else 'Stop'
        size_hint: None, None
        size: dp(150), dp(70)
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_state:
            if self.state == 'down': root.play()
            else: root.stop()
''')


class Base(FloatLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)
        self.player = None
        self.chk_pos = None

    def play(self, *args):
        self.player = SoundLoader.load('1.wav')
        self.player.play()

    def stop(self, *args):
        self.player.stop()
        self.player.unload()


class CheckSound(App):
    def build(self):
        return Base()


if __name__ == '__main__':
    CheckSound().run()
```
You have to provide a `1.wav` file (in the same directory) to play.
And this is the [`check.spec` file](https://gist.github.com/embryo10/fcbe1cb8353c861ea5a3e55b2b88cf36) I used to compile it to exe.

**Comment by matham** [comment]
Before anything, can you try to download and install the latest pyinstaller from github? Specifically, try it with `pip install --upgrade https://github.com/pyinstaller/pyinstaller/archive/develop.zip` and package again and see if you still have the issue.

**Comment by embryo10** [comment]
Well, I installed the latest PyInstaller and the simple script worked perfectly!
...but at my original program (which worked OK with the 1.9.0) I got this gstreamer error now:
```
(Tubert.exe:5700): GStreamer-WARNING **: Failed to load plugin 'C:\Users\X\Desktop\DEV\PROJECTS\4Build\Tubert\dist\Tubert\stuff\codecs\libgpac.dll': 'C:\Users\X\Desktop\DEV\PROJECTS\4Build\Tubert\dist\Tubert\stuff\codecs\libgpac.dll': The specified module could not be found.

(Tubert.exe:5700): GStreamer-WARNING **: Failed to load plugin 'C:\Users\X\Desktop\DEV\PROJECTS\4Build\Tubert\dist\Tubert\stuff\codecs\ssleay32.dll': 'C:\Users\X\Desktop\DEV\PROJECTS\4Build\Tubert\dist\Tubert\stuff\codecs\ssleay32.dll': The specified module could not be found.
[ERROR  ] [AudioGstplayer] Resource not found.
[ERROR  ] [AudioGstplayer] GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
[ERROR  ] [AudioGstplayer] Resource not found.
[ERROR  ] [AudioGstplayer] GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
```
The `libgpac.dll` and `ssleay32.dll` are part of the MP4Box and are used to extract the audio stream from video files.
I also get these two:
![err1](https://cloud.githubusercontent.com/assets/8684739/26704574/a55dd622-4738-11e7-8815-3e51640e459d.png)
![err2](https://cloud.githubusercontent.com/assets/8684739/26704580/b0fac97c-4738-11e7-8b13-cd24a9602909.png)
The `js.dll` and `LIBEAY32` are also part of the MP4Box.
Why it's trying to access them?

At the first tries, it was playing after all those errors.
Then, I used an updated version of MP4Box in the codecs folder.
After that it never played again, even when I returned the original dlls...
Any ideas?

**Comment by matham** [comment]
Well, the original issue is fixed then, it was because the pyinstaller on pypi still has the bug so you needed to use their master version.

The dll issues you're having could be because MP4Box distributes its own dlls which clash with the gstreamer dlls. Or maybe something else there clashes. That's what it seems like. It may be that you need to include these missing dlls manually in the pyinstaller spec file.

**Comment by embryo10** [comment]
But I do add them manually.. They do work.
The problem is with gstreamer.
How can I tell it not to access them?

**Comment by matham** [comment]
Maybe gstreamer then is the one loading the dll that clashes with its dll from the one you provide. This kind of this is hard to solve because you have to check which dlls are clashing and there may not be a way to fix it. You can use dependency walker to check which dlls may be missing or what is depending on what.

**Comment by embryo10** [comment]
From the error, I think that gstreamer is loading the dlls from a directory that it should not look.
Its a GStreamer Warning that it can not load a plugin from MY codecs folder.

Since I don't know how to check the dll compatibility, it means that I can not use gstreamer (or the 1.10 kivy) for my program.
That's sad :o(

**Comment by matham** [comment]
Have you tried using ffpyplayer?

**Comment by embryo10** [comment]
How can I do it?
I installed ffpyplayer and included in the `hiddenimports` and it copies 3 `.pyd` files to the app's directory.
When I run it though, I see that is not used.
```
[INFO   ] [AudioGstplayer] Using Gstreamer 1.10.2.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
```
It uses the gstreamer even if I don't import it in the `.spec` file.
How can I choose the Audio provider that I want?

**Comment by embryo10** [comment]
OK found it. It's `os.environ["KIVY_AUDIO"] = "ffpyplayer"`
It works as a script, but if a compile it, although I add the deps with
`*[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + ffpyplayer.dep_bins)]`
it still gives me
`[INFO   ] [Audio       ] Providers:  (audio_gstplayer, audio_sdl2, audio_ffpyplayer ignored)`
Any ideas?

FYI : I managed to run gstreamer with no errors, by moving the MP4Box files to `'app dir'/root`.
Go figure...

**Comment by matham** [comment]
That's good. Not sure why ffpyplayer didn't work in packaging. It could be it missed some dll.
