### ISSUE TITLE
matplotlib.pyplot kind of breaks kivy

### ISSUE THREAD

**Issue by tfonfara** [kivy/kivy#5208]
### Versions

* macOS Sierra 10.12.5
* Python 2.7.13
* Anaconda 4.4.0 (x86_64)
* IPython 5.3.0
* Kivy 1.10.0
* Kivy installation method: Homebrew with pip 

### Description

When I try to run e.g. kivy pong example step 1 (this is reproducible on other projects as well, but I wanted to keep it really simple) from ipython console (also tried with pycharm) it opens the window as "standalone app" that shows an icon in the dock, appears in the cmd + tab launcher and so on. Now when I import matplotlib with `import matplotlib.pyplot as plt` and run the code again, the window will not have its own icon and can not be brought to the front (visible for a short moment, then it will be covered by the app that was in the front before).
To me it looks like a bug. Can you confirm that or tell me a solution for that please?

### Code and Logs

main.py
```python
from kivy.app import App
from kivy.uix.widget import Widget

import matplotlib.pyplot as plt #run this code with and without this line

class PongGame(Widget):
    pass


class PongApp(App):
    def build(self):
        return PongGame()


if __name__ == '__main__':
    PongApp().run()
```

pong.kv
```
#:kivy 1.0.9
```

**Comment by KeyWeeUsr** [comment]
I haven't used matplotlib for a while, but try [this](https://github.com/KeyWeeUsr/KrySA/blob/master/krysa/tasks/plot.py#L12) fix. I think matplotlib just tried to steal the focus again and they have a fix for that with `matplotlib.use('Agg')`.

I'm not sure if that's the case.

**Comment by tfonfara** [comment]
@KeyWeeUsr this sounds reasonable!
`matplotlib.use('Agg')` works fine. Thanks for your fast solution :)

**Comment by TJ-C** [comment]
MacOS High Sierra 10.13.4
kivy 1.10.1.dev0
matplotlib 2.2.2
python 3.6.5

Without the fix above the plot continues where it has left off and not from where the mouse pointer is currently located.

if the fix above is applied, then plotting works as expected, however, matplotlib no longer shows a plot. See code example below.

```
 import matplotlib
 matplotlib.use('Agg', force=True) # comment this line to see effect 
 from matplotlib import pyplot as plt

 from kivy.app import App
 from kivy.uix.widget import Widget
 from kivy.graphics import Color, Ellipse, Line
 from kivy.uix.button import Button`


 x = []
 y = []

 class MyPaintWidget(Widget):

    def on_touch_down(self, touch):
        with self.canvas:
            Color(1, 1, 0)
            d = 30.
            Ellipse(pos=(touch.x - d / 2, touch.y - d / 2), size=(d, d))
            touch.ud['line'] = Line(points=(touch.x, touch.y))

    def on_touch_move(self, touch):
        touch.ud['line'].points += [touch.x, touch.y]
        x.append(touch.x)
        y.append(touch.y)

    def on_touch_up(self, touch):
        plt.plot(x, y)
        plt.show()


 class MyPaintApp(App):

     def build(self):


        return MyPaintWidget()



 if __name__ == '__main__':
     MyPaintApp().run()
```
