### ISSUE TITLE
ToggleButtonBehavior has no on_state method

### ISSUE THREAD

**Issue by ethernity** [kivy/kivy#5209]
In the ToggleButton Behavior class there is an example with the on_state method, but there isn't one in the source

**Comment by KeyWeeUsr** [comment]
`state` is a property in [`ButtonBehavior`](https://github.com/kivy/kivy/blob/master/kivy/uix/behaviors/button.py#L72) and the [`ToggleButtonBehavior`](https://github.com/kivy/kivy/blob/master/kivy/uix/behaviors/togglebutton.py) only changes the value. The `on_state` event is [bound to the property](https://kivy.org/docs/api-kivy.properties.html#observe-using-on-propname).
