### ISSUE TITLE
Memory leak in Spinner

### ISSUE THREAD

**Issue by michaljasionowski** [kivy/kivy#5215]
### Versions

* Python: 3.5.2
* OS: Linux Mint 18.1 Serena, 4.8.0-45-generic kernel
* Kivy: 1.10.0

### Description

Spinners seem to not be removed from memory after removing them from the parent widget. The following code causes constant increase in memory usage.

### Code and Logs

```python
from kivy.uix.spinner import Spinner
from kivy.uix.floatlayout import FloatLayout
from kivy.clock import Clock
from kivy.app import App

class TestApp(App):

    def build(self):
        self.layout = FloatLayout()
        self.layout.add_widget(Spinner())
        
        Clock.schedule_once(self.spinner_reloading)
        
        return self.layout
        
    def spinner_reloading(self, *args):
        self.layout.clear_widgets()
        self.layout.add_widget(Spinner())
        
        Clock.schedule_once(self.spinner_reloading)
    

if __name__ == '__main__':
    TestApp().run()

```

**Comment by tshirtman** [comment]
This branch fixes the issue for me, without apparent change in behavior, would you mind testing it?

Thanks for reporting!

**Comment by tshirtman** [comment]
This branch fixes the issue for me, without apparent change in behavior, would you mind testing it?

Thanks for reporting!

**Comment by michaljasionowski** [comment]
It works for me as well.

Thanks!
