### ISSUE TITLE
Unable to find any valuable Window provider. x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'

### ISSUE THREAD

**Issue by Argonautic** [kivy/kivy#5231]
### Versions

* Python: 3.6.1 |Anaconda 4.4.0 (64-bit)
* OS: Linux Ubuntu
* Kivy:  1.10.0
* Kivy installation method: pip install kivy

### Description

I realize this issue has come up a couple of times in the kivy issues and through google - I've spent most of my working hours today looking for a solution online, but none of them have worked, which is why I'm asking here. Within Anaconda Spyder for python 3.6.1, I'm unable to run a python file that makes use of kivy. Every time i do, I get an error that ends up at "Unable to find any valuable Window Provider." Some notes:

- This happens with both Anaconda for python 2.7 and for python 3.6 (though I'm primarily working on 3.6)
- I have already uninstalled and reinstalled kivy. I've tried multiple installation methods, including sudo apt-get, pip install, and installation with a virtualenv, all of which followed the official kivy documentation
- I have already run sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0
- I have tried to run my file in virtualenvs that have pygame installed as well. Same problem
- I have tried replacing self.fullscreen, resizable, state) in sdl2.py to bytes(self.fullscreen), bytes(resizable), state). Also did not resolve the issue

I can provide the actual py file that is being run if needed. 

Any help would be greatly appreciated!

### Code and Logs

```
runfile('/home/jon/Programming/Python/Artificial Intelligence A-Z/Part 1 - Deep Q-Learning/Module 1 - Self Driving Car/map.py', wdir='/home/jon/Programming/Python/Artificial Intelligence A-Z/Part 1 - Deep Q-Learning/Module 1 - Self Driving Car')
[INFO   ] [Logger      ] Record log in /home/jon/.kivy/logs/kivy_17-06-22_31.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/jon/anaconda3/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/jon/anaconda3/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - ImportError: /home/jon/anaconda3/lib/python3.6/site-packages/numexpr/../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)
  File "/home/jon/anaconda3/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/jon/anaconda3/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/jon/anaconda3/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1
```

**Comment by dessant** [comment]
It looks like numexpr was compiled with a gcc version which conflicts with the system.

I'm reading some people had luck with installing it from conda, but it does not seem to be related to Kivy.
```
conda install libgcc
```

You could also try symlinking the problematic file, make sure to replace the numexp libstdc++.so.6 path with the full one.
```
ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6  /home/jon/anaconda3/lib/python3.6/site-packages/numexpr/../../../libstdc++.so.6
```

**Comment by openourweb** [comment]
I have the same issue, i had try: conda install libgcc, but issue still there!
(kivyinstall) john@john-P37V6:~$ python3 -c "import kivy"
[WARNING] [Config      ] Older configuration version detected (14 instead of 19)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/john/.kivy/logs/kivy_17-09-01_11.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.3 |Anaconda custom (64-bit)| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

**Comment by norok2** [comment]
`pip install pygame` on the conda env fixed this very same issue for me (I guess it runs on a different backend).

**Comment by RAJKUMAR18** [comment]
Hi I am going through the same problem the method of installation. I have tried the above solutions. Looking forward for solution

**Comment by dolang** [comment]
@RAJKUMAR18 Try it with your distribution's Python and follow the guide for [installation on Linux](https://kivy.org/docs/installation/installation-linux.html) instead of using Anaconda.

If you're not using Anaconda, your problem might be a different one, but there's no way to tell without more information. In that case it's probably a better idea to open a new issue with all the relevant information instead of commenting on a closed one.

**Comment by McLightScarlet** [comment]
can someone help me with this eror on kivy guys?? pls

C:\Users\McLight\PycharmProjects\McLight\venv\Scripts\python.exe C:/Users/McLight/PycharmProjects/McLight/venv/Lib/site-packages/kivy/core/window/window_sdl2.py
[INFO   ] [Logger      ] Record log in C:\Users\McLight\.kivy\logs\kivy_19-04-18_48.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ImportError: DLL load failed: The specified module could not be found.
  File "C:\Users\McLight\PycharmProjects\McLight\venv\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\McLight\PycharmProjects\McLight\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 23, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

 Traceback (most recent call last):
   File "C:/Users/McLight/PycharmProjects/McLight/venv/Lib/site-packages/kivy/core/window/window_sdl2.py", line 23, in <module>
     from kivy.core.window._window_sdl2 import _WindowSDL2Storage
 ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1
