### ISSUE TITLE
Shortcuts for EmacsBehavior insert text

### ISSUE THREAD

**Issue by syntonym** [kivy/kivy#5245]
### Versions

* Python: 3.6.1
* OS: linux
* Kivy: 1.10.1.dev0 7daea785f5dfe5b54a3ced7510d87ad6a711f0e9
* Kivy installation method: `pip install --user --editable .`

### Description
When using EmacsBehavior with TextInput shortcuts with alt insert the pressed keys are into the text. E.g. when pressing alt+f the cursor is moved to the end of the word *and* an f is inserted. This does not happen with ctrl shortcuts.

### Code and Logs

The error can be reproduced by the `examples/widgets/codeinput.py` example. Alternativly here is a minimal example which reproduces the error:

```python
from kivy.config import Config
Config.set('kivy', 'log_level', 'debug')

from kivy.app import App

from kivy.uix.behaviors import EmacsBehavior
from kivy.uix.textinput import TextInput

class CodeInput(EmacsBehavior, TextInput):
    pass

class TestApp(App):
    def build(self):
        codeinput = CodeInput()
        codeinput.text = "Multiline Text\n" * 10
        return codeinput

if __name__ == '__main__':
    TestApp().run()

```

**Comment by KeyWeeUsr** [comment]
The exact example + codeinput works for me just fine, but only for the *left* `Alt`. The right one reproduces the issue with this change:

`wo|rd` → `word[|` where `|` is the cursor.

**Comment by KeyWeeUsr** [comment]
I'm not even sure if it actually *is* an issue because the binding are there only for the `ctrl` and `alt` modifiers, which means that `alt-gr` isn't there and that particular key is a combination of `ctrl`+`alt`. I've opened emacs just for fun and the right alt (`alt-gr`) bindings don't exist. The only thing I get with `alt-gr`+`f` is a `[` character, meaning the binding is there only for the pure `alt` key.

Which would mean that the issue is about purging the bindings for `alt-gr` completely.

**Comment by syntonym** [comment]
So you can't reproduce the issue as described? 
alt-gr also produces the error for me, but I didn't know if that was the correct place to fix that.
I'm on a german keyboard, maybe that changes something? But even when changing to a US keyboard layouot via `xkbmap -layout us` I can reproduce the error with left-alt.
Your fix doesn't work for me at all, I can still reproduce the bug with left alt and rightalt=alt-gr.

**Comment by KeyWeeUsr** [comment]
Try to reproduce it on other OS/machine (not VM) if you get the same result. I can't reproduce it with left alt (it works correctly) and I can reproduce it with right alt (`alt-gr`), which is what my fix is for - for disabling the `alt-gr` as meta key as it doesn't work for me with default Emacs settings. The fix might be wrong though and maybe the `alt-gr` is actually wanted as another meta key, but in any case, fetching `mod` with just the first item was just wrong, so if there needs to be something fixed, it's most likely in that particular function.

**Comment by syntonym** [comment]
On a windows 10 machine I couldn't reproduce it, alt+f works as intended and alt-gr+f works like ctrl+f (without your patch).

On that line `modifiers = ['alt']` if I press alt+f, which I think is correct. As far as I understand `keyboard_on_key_down` works correct, but an additional `SDL_TEXTINPUT` event is generated, which triggers only  `keyboard_on_textinput` which then inserts the `f`. Is there any way how SDL2 could generated different textinputs for different locales or something like that?

**Comment by KeyWeeUsr** [comment]
> alt-gr+f works like ctrl+f
yeah, that would be the case when `mod == 'ctrl'` because `modifiers == ['ctrl', 'alt']` and the rest you can see.

Re the second part, I'm not sure I know what you're talking about. `keybard_on_key_down` is handling the modifiers and the `keyboard_on_textinput` is something different. It handles the text directly i.e. after the modifiers are processed. See [`TextInput.keyboard_on_textinput`](https://github.com/kivy/kivy/blob/27e3b90eae2a0155b22a435f1b6f65c913519db6/kivy/uix/textinput.py#L2447).

**Comment by syntonym** [comment]
As far as I understand keypresses are handled as following:

* User presses a key on the keyboard
* SDL2 creates a SDL_KEYDOWN event
* Kivy fires `on_key_down` on the keyboard. The keyboard forwards that to the appropriate widgets, so the Textinput widget.
* `widget.keyboard_on_key_down` is called, which is handled by EmacsBehavior. It does the hotkeys, and, if no hotkey is triggered, forwards to `super().keyboard_on_key_down()`
* `Textinput.keyboard_on_key_down` does it's own shortcuts
* No text is actually inserted, only hotkeys are handled

Seemingly on my pc something further happens:

* SDL2 creates a SDL_TEXTINPUT event (*although it probably shouldn't*)
* Kivy fires `on_textinput` and forwards to the appropriate widgets 
* Finally it arrives at `Textinput.keyboard_on_textinput` which does not check for hotkeys
* `keyboard_on_textinput` inserts the text (an `f` in this case)

At no point kivy can influence whether SDL2 fires an SDL_TEXTINPUT event. 

Is that correct?

So my bug is not in emacs (or anywhere else in kivy) but because SDL2 incorrectly(?) fires SDL_TEXTINPUT.

**Comment by inclement** [comment]
I'm not really sure when SDL2 is 'supposed' to fire a TEXTINPUT type event, but I'd guess it's more likely deliberate than not. It's hard to know quite what Kivy should do about it. It might be fine to apply textinput events as normal if the textinput event contains a single character.

**Comment by syntonym** [comment]
I think when a "complete" characterinput is detected, so things like `ê` can be distinguished from `^e`. If noone can reproduce this I guess the mistake lies somewhere by me, maybe I somehow configured alt to not be recognized as a modifier or something like that. 

Generally I think kivy shouldn't do anything about that. As far as I'm concerned the issue can be closed.
