### ISSUE TITLE
Kivy crashed in fullscreen with two monitors

### ISSUE THREAD

**Issue by BolidTeam** [kivy/kivy#5247]
### Versions

* Python: 3.4.4
* OS: Windows 7
* Kivy: 1.9.1
* Kivy installation method: pip install kivy==1.9.1

### Description

When working with kivy-examples -> guide -> quickstart -> main.py with adjustment to run in fullscreen, the application crushed by clicking on second monitor. 
Message "Display driver stopped responding and has been recovered" appeared.
There are no error messages in the output.
[kivy_problem.txt](https://github.com/kivy/kivy/files/1105786/kivy_problem.txt)

### Code and Logs

import kivy
kivy.require('1.0.6')  # replace with your current kivy version !

from kivy.app import App
from kivy.uix.button import Button
**from kivy.core.window import Window 
Window.fullscreen = True** 

class MyApp(App):

    def build(self):
        return Button(text='Hello World')

if __name__ == '__main__':
    MyApp().run()

**Comment by dessant** [comment]
Please reopen if the bug is present with the latest version of Kivy. Also make sure to install the latest graphics drivers.

**Comment by BolidTeam** [comment]
Hi,
the bug is still present in the latest version of kivy (1.10.0).
I have Intel HD graphics 4000 with latest driver version (9.17.10.2867).
[kivy_17-06-29_8.txt](https://github.com/kivy/kivy/files/1111626/kivy_17-06-29_8.txt)
I have tried with Hello world example found in: https://kivy.org/#home

**Comment by KeyWeeUsr** [comment]
@BolidTeam does it happen even without fullscreen? Remove the `Window.fullscreen = True` and try even to move the window to the next screen (if it's not mirrored). It might be a bug in SDL2 as iirc we just pass a flag when creating the window.

**Comment by KeyWeeUsr** [comment]
@BolidTeam does it happen even without fullscreen? Remove the `Window.fullscreen = True` and try even to move the window to the next screen (if it's not mirrored). It might be a bug in SDL2 as iirc we just pass a flag when creating the window.

We're probably just missing [another flag](https://stackoverflow.com/a/26776879/5994041)

**Comment by BolidTeam** [comment]
Hi,
I tried without fullscreen, moved the Hello world window to next screen and everything was OK.
Resolution change and orientation and app is still working.
When I resized the window to minimum and clicked on app (at least what was left), the same error appeared and app crashed.

**Comment by KeyWeeUsr** [comment]
@BolidTeam could you paste the error from the console? Or did it crash with a segfault/"python not responding"?

**Comment by BolidTeam** [comment]
Hi,
I have set the config.ini to trace. Here is the log. Is this enough for troubleshooting ?
[kivy_17-06-29_14.txt](https://github.com/kivy/kivy/files/1111822/kivy_17-06-29_14.txt)

**Comment by misl6** [comment]
Hi @BolidTeam !

I've just tested this issue (as I was looking for fullscreen-related issues to test just before the final release of Kivy 2.2.0) on Windows, and this is not happening anymore.

Feel free to re-open the issue if it persists with `kivy==2.2.0rc1` and onwards.
