### ISSUE TITLE
Kivy for python 3 detect OpenGL as 1.1 on windows 10/7

### ISSUE THREAD

**Issue by srudyanto** [kivy/kivy#5248]
### Versions

* Python: 3.6
* OS: Windows 10/7 64bit
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I try to running kivy for python 3 on windows 7 but get this error
Open GL detected as 1.1, actually using opengl viewer it is 3.1
This issue not found on kivy for python 2.7 for windows or kivy for python 3 for ubuntu

### Code and Logs

```python
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()

```

**Comment by KeyWeeUsr** [comment]
What happens if you add this before the first line of your code?

```python
from kivy import Config
Config.set('graphics', 'multisamples', '0')
```

**Comment by srudyanto** [comment]
nothing happened.

**Comment by srudyanto** [comment]
I just try in windows 7 32 bit with python 3.6. It's worked

**Comment by dessant** [comment]
Ah, Anaconda. There are a couple of issues opened for their Python distribution not always working with Kivy.

**Comment by srudyanto** [comment]
I just fresh install python 3.6 and the problem still remain.

(hello) D:\anaconda project\hello>Scripts\python main.py
[INFO   ] [Logger      ] Record log in C:\Users\Yen\.kivy\logs\kivy_17-06-29_10.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] No framebuffers extension is supported
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'1.1.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Microsoft Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GDI Generic'>
[INFO   ] [GL          ] OpenGL parsed version: 1, 1
[CRITICAL] [GL          ] Minimum required OpenGL version (2.0) NOT found!

OpenGL version detected: 1.1

Version: b'1.1.0'
Vendor: b'Microsoft Corporation'
Renderer: b'GDI Generic'

Try upgrading your graphics drivers and/or your graphics hardware in case of problems.

The application will leave now.

**Comment by dessant** [comment]
Anaconda crashes regardless of the Windows/Python bitness combination, while the official Python distribution only has issues when the 32 bit version is executed on a 64 bit Windows?

**Comment by srudyanto** [comment]
at  the last attempt, I use python36 not anaconda bundle, and the problem still there

**Comment by srudyanto** [comment]
Please accept my apologize, my mistake to download wrong version of python 36. This is the correct one and the problem still there.

(hello) D:\anaconda project\hello>scripts\python main.py
[INFO   ] [Logger      ] Record log in C:\Users\Yen\.kivy\logs\kivy_17-06-29_14.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] No framebuffers extension is supported
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'1.1.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Microsoft Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GDI Generic'>
[INFO   ] [GL          ] OpenGL parsed version: 1, 1
[CRITICAL] [GL          ] Minimum required OpenGL version (2.0) NOT found!

OpenGL version detected: 1.1

Version: b'1.1.0'
Vendor: b'Microsoft Corporation'
Renderer: b'GDI Generic'

Try upgrading your graphics drivers and/or your graphics hardware in case of problems.

The application will leave now.

**Comment by srudyanto** [comment]
Somehow after reinstall python and using SET KIVY_GL_BACKEND=angle_sdl2 (I also used this method before and failed). Finally it's working. Thanks everyone for the support.
Case Closed

**Comment by KeyWeeUsr** [comment]
@srudyanto I see `(hello) D:\anaconda project\hello>scripts\python main.py` like in virtualenv. Before I only thought that's some kind of mistake, but now... try to install kivy normally, without virtualenv and run it normally (without angle, don't even install it for this test). I think it might be just an issue with the virtualenv and anaconda/virtualenv somehow removed the openGL libs from the path for you which resulted in this OpenGL 1.1 error.

What you may try with the current distribution before trying a non-virtualenv one is this:

    set PATH=C:\Windows\System32;%PATH%

after you activate the env. That's where the `opengl32.dll" and other important libs are. Then just run it.

**Comment by RibraX** [comment]
Angle backend for py3.5+. In the command line, I make this:
> pip install kivy.deps.angle 
> set KIVY_GL_BACKEND=angle_sdl2

It works perfectly on windows 10.

**Comment by Archanciel** [comment]
Did not work for me on Windows 10 although I have OpenGL 3.1 !

![snap1](https://user-images.githubusercontent.com/2625211/39077514-c39eb94e-4502-11e8-9c5c-ef619b52b2b1.jpg)

**Comment by Archanciel** [comment]
Finally found the solution and documented it [here](https://communities.intel.com/message/538974#538974) !

**Comment by ShardulNalegave** [comment]
I had the same problem and solved it by running this in the cmd -
````bash
    pip install kivy.deps.angle && set KIVY_GL_BACKEND=angle_sdl2
````

**Comment by Ruithlzz09** [comment]
I am windows 10 user having opengl above 2.0 and face same problem and resolve it using help from ----

[link] (https://stackoverflow.com/questions/34969990/kivy-does-not-detect-opengl-2-0)

1.   right click on This PC then open Properties .
2.  go to Advanced system settings .
3.  click on Environment Variables .
4. click on New in User variables for --- .
5.   put KIVY_GL_BACKEND in Variable name .
6.  put angle_sdl2 in Variable value

**Comment by rem-git-50** [comment]
Thank you, Ruithlzz09. It also works on Windows 10 in combination with opengl 1.1 !

**Comment by Archanciel** [comment]
WARNING: after you executed  pip install kivy.deps.angle and you added the KIVY_GL_BACKEND environment variable as described above by Ruithlzz09, you must restart Pycharm in order for the solution to work !

**Comment by thunderking2111** [comment]
but isn't this a temporary solution, just for our system. what if this happens with the customer's pc? customer is not gonna go through the trouble of doing this much of settings. so is there any permanent solution? like adding new opengl libraries with the bundled files of our app or something like that?

**Comment by HeaTTheatR** [comment]
@thunderking2111 
I constantly encounter a similar error on modern computers with the latest updates and the newest version of OpenGL. And you have to do this crutch `set KIVY_GL_BACKEND = angle_sdl2` (  I never found another solution...

**Comment by TukangM** [comment]
help
![image](https://user-images.githubusercontent.com/91467886/159699942-0a777924-1ef5-4635-9e26-93d4347d8bd9.png)
i have opengl 2.1 but detect as 1.1 but i try
import os
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'
the app blank

without import os os.environkivvy_gl_backed=angle sdl2
![image](https://user-images.githubusercontent.com/91467886/159700336-caaf1254-37a2-4ced-a99f-ee77eef28d8a.png)

**Comment by LUISMAGAIVER341** [comment]
Hi!
@TukangM , did you have writed something on the kivy's code?
Well, to debug the code correctly, you need to activate the venv, and the 
kivy's environment.
If the venv and the environment is activated, and the the software doens't worked(And you do the method), you(probally) have some problems with venv & environment.
Try to import the `kivy.deps.angle` library and put this `import os
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'` into the code.
This should work to everyone.
And, @TukangM , can you send the code plz?

**Comment by TukangM** [comment]
> Hi! @TukangM , did you have writed something on the kivy's code? Well, to debug the code correctly, you need to activate the venv, and the kivy's environment. If the venv and the environment is activated, and the the software doens't worked(And you do the method), you(probally) have some problems with venv & environment. Try to import the `kivy.deps.angle` library and put this `import os os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'` into the code. This should work to everyone. And, @TukangM , can you send the code plz?

oh. hi. sorry for long respond (4 days). umm maybe this is bad news. the bad news is i dont use kivy and python for coding. (i just bored and wanted try coding python). the great news i just make own linux os (hehe)

**Comment by LUISMAGAIVER341** [comment]
@TukangM  Ahoy!
Dont desist of python. It offers much things
You can install all kivy dependencies, and install pygame and cython!
I tried, and it worked!
if u want i can talk it more detailed.
But kivy/python apps is a good way to create a distro, with your own apps, and features.

**Comment by LUISMAGAIVER341** [comment]
Probally you dont see anything(only dark) because you dont writted nothing else
