### ISSUE TITLE
Biggest Issue of Kivy Platform 

### ISSUE THREAD

**Issue by tejastank** [kivy/kivy#5250]
We build solution for clients after 2 month of development we run with remote desktop (RDP)
Kivy not supported with RDP gives OpenGL 1.1 only, this make biggest failer over the development.

Now complete kivy project failuer due to only it unable to run on microsft server 2012.
Client conenct with RDP and just all get OpenGL 1.1 Issue.

Even we upgrade costly graphics card in server with OpenGL 4.4 supported. 
Application directly work in server with python and we generated exectutable both.

But ALL RDP or AnyDesk App Failed to run it. RDP must need to run.

 

* Python: 2.7
* OS: Microsoft OS 10.0, Microsoft 2012 server
* Kivy: 1.9 & lastest
* Kivy installation method: via PIP 

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by dessant** [comment]
Same as https://github.com/kivy/kivy/issues/5251#issuecomment-312237049.
