### ISSUE TITLE
Switch SDL2 to the latest release on GNU/Linux distros

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5253]
There are some features in SDL2 that might be useful and as it's very unlikely there will be a version X available for every distro, this is probably the best solution. We should switch our main dependency's version on linux to its latest stable version because:

* bug fixes
* features
* support - if something breaks, sdl won't help with antique versions I think

but if we'd agree on this to happen, we'll need to upgrade the travis build and linux instructions for SDL2, which could be just this proposed solution(@manthansharma's travis):

```
-        sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev;
+        sudo apt-get -y install automake autoconf mercurial;
+
+        function clone_install {
+            hg clone https://hg.libsdl.org/$1;
+            cd $1;
+            ./autogen.sh;
+            mkdir build && cd "$_";
+            ../configure;
+            make;
+            sudo make install;
+        }
+
+        clone_install SDL;
+        clone_install SDL_image;
+        clone_install SDL_ttf;
+        clone_install SDL_mixer;
+        cd $TRAVIS_BUILD_DIR;
```

Until there's some usable OS for making manylinux wheels, this is the second best solution as here you have to compile the SDL2 packages and not every dependency of a dependency of a dependency of a ...

Or as previously suggested, we could create own PPA with the https://github.com/ZoogieZork/SDL2-Package and just update [this little version piece](https://github.com/ZoogieZork/SDL2-Package/blob/master/SDL/fetch.sh#L16). We already have PPA for Kivy itself, so why not SDL2? It's probably the fastest solution both in implementing and in using later (instructions would need just a PPA link update).

triggered by ref #5169

**Comment by KeyWeeUsr** [comment]
https://hg.libsdl.org/SDL/file/e1fc7d3b46fb/WhatsNew.txt#l43

```
Linux:

* Added support for the Fcitx IME

* Added a window event SDL_WINDOWEVENT_TAKE_FOCUS when a window manager asks the SDL window whether it wants to take focus.

* Refresh rates are now rounded instead of truncated, e.g. 59.94 Hz is rounded up to 60 Hz instead of 59.

* Added initial support for touchscreens on Raspberry Pi ←←←←
```

**Comment by KeyWeeUsr** [comment]
Hm, if everything goes right, we might as well drop this thing and use the wheels. It's on a [good path](https://github.com/kivy/kivy/pull/4973#issuecomment-315644931). 😎

**Comment by misl6** [comment]
We now ship the latest (and self-build) version of SDL2 into wheels. The user (or a contributor) can still decide to build the SDL dependencies via `tools/build_linux_dependencies.sh` script.

See: https://github.com/kivy/kivy/pull/8096
