### ISSUE TITLE
Texture.create() NPOT segfault

### ISSUE THREAD

**Issue by jim-nasa** [kivy/kivy#5254]
### Versions

* Python: 2.7.12 (Ubuntu), 2.7.13 (MacOS)
* OS: 16.04.2 LTS (Ubuntu), 10.11.6 (MacOS)
* Kivy: 1.91 (Ubuntu), 1.92dev0 (MacOS)
* Kivy installation method: synaptic/apt (Ubuntu), homebrew & pip (MacOS)

### Description

While educating myself about textures, I started running examples from the Kivy docs.
Near the top of the page [https://kivy.org/docs/api-kivy.graphics.texture.html] there is this example for creating a texture:

texture = Texture.create(size=(640, 480))

I was unable to get it to work without incurring the segfault. It does work if I use powers of two in size().

I tried this on two different machines (Ubuntu and MacOS), with two different versions of Kivy (1.9.1 and 1.9.2dev0). I have not tried it with the current (1.10) version, but I didn't see any indication that it was addressed in the changelog.
### Code and Logs

```python
Here's an example that triggers the problem for me:

`#!/usr/bin/env python

# Demonstrate NPOT issue. Executing this code causes a
# segfault. There's a workaround suggested at
# https://github.com/kivy/kivy/issues/3701 (untested), but an
# unhandled segfault is still a bug.

import kivy.config; kivy.config.Config.set('kivy', 'log_level', 'debug')
import kivy.graphics.texture

kivy.graphics.texture.Texture.create(size = (64, 64))
print("test 1 passed")
kivy.graphics.texture.TextureRegion.create(size = (640, 480)) # NB segfault
print("test 2 passed")
kivy.graphics.texture.Texture.create(size = (640, 480)) # NB segfault
print("test 3 passed")`

Logs from Ubuntu:
[INFO   ] [Logger      ] Record log in /home/jmckim/.kivy/logs/kivy_17-07-03_18.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
test 1 passed
Segmentation fault (core dumped)

logs from MacOS:
[INFO   ] [Logger      ] Record log in /Users/jmckim/.kivy/logs/kivy_17-07-03_2.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-86e050b, 20170207
[INFO   ] [Python      ] v2.7.13 (default, Dec 18 2016, 07:03:34) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
test 1 passed
Fatal Python error: (pygame parachute) Segmentation Fault
Abort trap: 6

```

**Comment by veefore** [comment]
Still have the issue. 
Texture.create(size=(640, 480)) results in segmentation fault, while size=(64, 64) works.

**Comment by pythonic64** [comment]
@jim-nasa @veefore Try running with `import kivy.core.window`:
```python
import kivy.config
kivy.config.Config.set('kivy', 'log_level', 'debug')
import kivy.core.window
import kivy.graphics.texture

kivy.graphics.texture.Texture.create(size = (64, 64))
print("test 1 passed")
kivy.graphics.texture.TextureRegion.create(size = (640, 480)) # NB segfault
print("test 2 passed")
kivy.graphics.texture.Texture.create(size = (640, 480)) # NB segfault
print("test 3 passed")
```

This will create `Window` instance in `kivy.core.window` module and enable you to create textures. Example above works for me on Windows 10 and Ubuntu 18.

**Comment by veefore** [comment]
@pythonic64
I was running my Texture.create(...) in a separate thread through threading and not Clock.schedule. 
As pointed out in [stackoverflow post](https://stackoverflow.com/questions/62148150/kivy-segmentation-fault-on-blitting-opencv-picture) by John Anderson, kivy texture manipulations should be done in mainthread.

I've scheduled my code with a Clock and it worked.
