### ISSUE TITLE
numpy import with kivy.lang.Builder imports cause error on exit

### ISSUE THREAD

**Issue by ASolchen** [kivy/kivy#5258]
### Versions

* Python: v2.7.13
* OS: Win7
* Kivy: v1.10.0
* Kivy installation method: pip install
* Numpy 1.13.0

### Description

Using the .kv files or the kivy.lang Builder to import Label (or extended classes) if numpy is imported, the app causes an error on exit:
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
I've narrowed it down to this. If you comment out the numpy import - No issue
If you un-comment the explicit Label import and import numpy - No issue
If you force the Builder to do the Label import with numpy imported the error is caused on exit. 
Same thing happens with a .kv file.
I had this issue with kivy 1.9.1 so I unistalled and installed 1.10.0, issue is still present.
This only happends with the Label class or derivatives of it.
This will also happen if you do the import of numpy in the builder string or kv file. e.g.
`#:import np numpy `

### Code

```python
from kivy.uix.floatlayout import FloatLayout

from kivy.app import App
from kivy.lang import Builder
import numpy


#from kivy.uix.label import Label


Builder.load_string('''
<Root>:
    Label:
        text: 'hello Kivy'
''')

class Root(FloatLayout):
    pass

class NumPyBugApp(App):
    def build(self):
        return Root()

NumPyBugApp().run()


```
### Log
```
[INFO   ] Kivy: v1.10.0
[INFO   ] Python: v2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <4.5.0 NVIDIA 378.66>
[INFO   ] GL: OpenGL vendor <NVIDIA Corporation>
[INFO   ] GL: OpenGL renderer <GeForce GTX 660/PCIe/SSE2>
[INFO   ] GL: OpenGL parsed version: 4, 5
[INFO   ] GL: Shading version <4.50 NVIDIA>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Leaving application in progress...
```

**Comment by ASolchen** [comment]
I could not reproduce this in Linux (Mint 18.1)

**Comment by matham** [comment]
Where did you get numpy from? pip? If so, uninstall and use numpy from http://www.lfd.uci.edu/~gohlke/pythonlibs/.

**Comment by ASolchen** [comment]
I installed numpy ver 1.11.3 from the source you recommended and the issue is gone. The version I has was **numpy-1.13.0-cp27-none-win32.whl** from [https://pypi.python.org/pypi/numpy/1.13.0](https://pypi.python.org/pypi/numpy/1.13.0). I guess this can be closed.

Thanks,
Adam

**Comment by matham** [comment]
Yeah, on windows I always recommend to use that website to get any python package that has compiled components. The issue you noticed was because of c-runtime clash between the mingw runtime and the one used by numpy.
