### ISSUE TITLE
Can't catch JsonStore IOErrors

### ISSUE THREAD

**Issue by JellyWX** [kivy/kivy#5259]
### Versions

* Python: 2.7
* OS: Ubuntu 16.04
* Kivy: 1.10
* Kivy installation method: PIP

I'm trying to use a try loop to catch errors when kivy attempts to create JsonStores. This is necessary on Android, since not all phones have a proper `sdcard` folder, yet some do. However, JsonStore can't be caught with either a catch-all except or an `IOError` specific except

### Code and Logs

```
try:
  store = JsonStore('/sdcard/data.json')
except:
  try:
    store = JsonStore('/storage/emulated/0/data.json')
  except:
    store = JsonStore('data.json')
```
yields:

```
I python  :  IOError: [Errno 2] No such file or directory: '/sdcard/data.json'
I python  : Python for android ended.
```

**Comment by inclement** [comment]
Just to note, regardless of the details of the issue, the ideal way to resolve this issue is to ask Android for the right external files dir. I think something like the following should work:

    from jnius import autoclass
    Environment = autoclass('android.os.Environment')
    external_storage_dir = Environment.getExternalStorageDirectory().getPath()

Even better, you can similarly get the external files directory that is dedicated to your application, does no require special permissions to write to, and will be cleared on uninstall.

**Comment by JellyWX** [comment]
good to know; i think sdcard is generally safe but this would be ideal (my android uses 'emui' and for some reason its unbound the sdcard folder :/). ill investigate that as an alternative

**Comment by JellyWX** [comment]
inclement's solution worked perfectly. saved me some processing power and some storage space. thanks

**Comment by KeyWeeUsr** [comment]
@JellyWX could you please paste the path you got from `Environment.getExternalStorageDirectory().getPath()`? I'm curious what was the final path as at least one from
```
/storage/emulated/0
/storage/emulated/legacy
/sdcard
```
always worked for me.

**Comment by JellyWX** [comment]
@KeyWeeUsr I believe it returned

`/storage/6537-3031`

My phone is a Huawei model, and when I added an SD card to the storage, for some reason the modified OS unbound the sdcard folder and made the /storage/6357-3031 folder. I have no idea why... but luckily the getExternalStorage works perfectly (unlike the JsonStore itself, it seems. I'm fighting with it as I type this)

_Sent from my HONOR BLN-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KeyWeeUsr** [comment]
Oh my... well, I've seen just slightly modified path (e.g. `/storage/emulated/1`, `/storage/emulated/sdcard`), but there was always some symlink to the real one. Quite lovely this one.

About JsonStore, I will try to look at it this weekend and see what's wrong with it.

**Comment by JellyWX** [comment]
@KeyWeeUsr thanks :) I was looking at it myself before, but got sidetracked and couldn't nail some of the code used. I'm having some issues where the store only updates in memory it seems, but sometimes it works sometimes not. If i make a reproducible example I'll file a different issue for it

_Sent from my HONOR BLN-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KeyWeeUsr** [comment]
@JellyWX I can't really reproduce your issue. Pure `j = JsonStore('somewhere')` doesn't trigger anything for me both on py2 and py3 with the latest stable (`1.10.0`).

The only error I get is when I actually try to put something into the storage, therefore when I do:

```python
j = JsonStore('somewhere')
j.put('something')  # error here
```

which throws an `IOError` on Android for me and when I try to catch the error, everything works just fine:

```python
try:
    j.put('something') 
except:
    pass
```

which leads me to conclusion that you only tried to catch the error on a wrong place, which even appears to be true:

```python
try:
    store = JsonStore('/sdcard/data.json')  # no error here, nothing to catch
except:
    try:
        store = JsonStore('/storage/emulated/0/data.json')
    except:
        store = JsonStore('data.json')

# missing line for the example
store.put('whatever')  # crash boom
```

```
# the same folder as the first "store" variable
I python  :  IOError: [Errno 2] No such file or directory: '/sdcard/data.json' 
```

**Comment by JellyWX** [comment]
ah, thanks for that :/ oh well 😅, i managed to work around the other one i
found, but it could be a feature :/ have to read the docs and produce some
minimal examples

On 22 Jul 2017 5:40 p.m., "Peter Badida" <notifications@github.com> wrote:

@JellyWX <https://github.com/jellywx> I can't really reproduce your issue.
Pure j = JsonStore('somewhere') doesn't trigger anything for me both on py2
and py3 with the latest stable (1.10.0).

The only error I get is when I actually try to put something into the
storage, therefore when I do:

j = JsonStore('somewhere')
j.put('something')  # error here

which throws an IOError on Android for me and when I try to catch the
error, everything works just fine:

try:
    j.put('something') except:
    pass

which leads me to conclusion that you only tried to catch the error on a
wrong place, which even appears to be true:

try:
    store = JsonStore('/sdcard/data.json')  # no error here, nothing
to catchexcept:
    try:
        store = JsonStore('/storage/emulated/0/data.json')
    except:
        store = JsonStore('data.json')
# missing line for the example
store.put('whatever')  # crash boom

# the same folder as the first "store" variable
I python  :  IOError: [Errno 2] No such file or directory: '/sdcard/data.json'

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kivy/kivy/issues/5259#issuecomment-317195079>, or mute
the thread
