### ISSUE TITLE
Support saving flipped textures in SDL2

### ISSUE THREAD

**Issue by kamathln** [kivy/kivy#5262]
Basic tutorial, could probably be optimized for speed by copying the image one row at a time to the new surface.
http://lazyfoo.net/SDL_tutorials/lesson31/index.php

**Comment by dessant** [comment]
It is already supported and should work regardless of the providers being used.

https://kivy.org/docs/api-kivy.graphics.texture.html?highlight=flip#kivy.graphics.texture.Texture.flip_horizontal

**Comment by kamathln** [comment]
under SDL2 ? Since which version?

**Comment by dessant** [comment]
Ah, you're right, it is not documented either.
https://github.com/kivy/kivy/issues/4300

**Comment by KeyWeeUsr** [comment]
@kamathln Please try the linked PR if it works for you.

**Comment by kamathln** [comment]
👍  Thanks! It works!
