### ISSUE TITLE
Deceptive pixel format logic in _image_sdl2.pyx load_from_surface()

### ISSUE THREAD

**Issue by bionoid** [kivy/kivy#5269]
### Description

The intended happy path of converting to BGR888/ABGR8888 if ``image.format.BytesPerPixel`` is 3 or 4 is not reached. Instead, [this is the default execution path](https://github.com/kivy/kivy/blob/1.10.0/kivy/core/image/_img_sdl2.pyx#L76-L87). It seems like BPP=3 will not do any conversion, or incorrectly as ABGR if Rshift>Bshift. 

### Code and Logs

```python
fmt = 'rgb'
if fmt not in ('rgb', 'rgba'): # <------- suspect "not"
    if fmt == 'rgb':
```

https://github.com/kivy/kivy/blob/1.10.0/kivy/core/image/_img_sdl2.pyx#L63-L64

**Comment by tito** [comment]
I was drunk? O_o

**Comment by bionoid** [comment]
@tito do you remember the purpose of the Rshift>Bshift test? Handle bgr, or some endian-issue, or something else? 

I've rewritten this function, will finalize & submit a pr, maybe easier to discuss that

**Comment by tito** [comment]
I think it was an endian issue on iOS/android.
