### ISSUE TITLE
Missing Camera provider on iOS

### ISSUE THREAD

**Issue by Benoit9** [kivy/kivy#5273]
Hello,
There seems to be no Camera provider for iOS, but I have seen there used to be one based on AVFoundation.
I am very familiar with AVFoundation, but not at all with the Kivy codebase. Can anyone give me some pointers about where to start looking and why it was disabled? I'll try to fix it if possible.
Thanks!

### Versions

* Python: 2.7.1
* OS: MacOS, iOS
* Kivy: 1.10
* Kivy installation method: pip

### Code and Logs

```
[CRITICAL] [Camera      ] Unable to find any valuable Camera provider.
```

**Comment by tito** [comment]
Hi,

Kivy installation on your computer doesn't matter for the Kivy used for iOS. Cross compilation happen, and that's not the same Kivy (the Kivy-iOS toolchain will clone and cross compile Kivy, it doesn't matter what you installed).

As for AVFoundation, the camera code is located at https://github.com/kivy/kivy/blob/master/kivy/core/camera/camera_avfoundation.pyx, and implementation at https://github.com/kivy/kivy/blob/master/kivy/core/camera/camera_avfoundation_implem.m

Look like in the comment, i wrote to test it on iOS, but i never did.

To activate the provider, at the end of https://github.com/kivy/kivy/blob/master/kivy/core/camera/__init__.py, add a test to check for iOS and add the camera provider for it. Then change the setup.py to activate "use_avfoundation" on iOS (and make change whatever needed to be able to compile on both OSX and iOS.)

That's it, good luck :)

**Comment by Benoit9** [comment]
Thanks a lot! Someone on IRC pointed me to the right direction, but I was missing the setup.py part.

Because I am not familiar with the build system, I don't know how to alter the code that will be cross-compiled. ```toolchain.py build kivy``` does not see the changes and does not rebuild, and ```toolchain.py clean kivy```followed by ```toolchain.py build kivy``` re-downloads the github archive and overwrites my changes.

I don't see any option to rebuild without re-downloading.

Or can I change the url attribute in the recipe to point to local files instead of GitHub?

**Comment by Benoit9** [comment]
OK, I discovered the DIR_KIVY environment variable that lets me compile local code.

Then I ran into the same problem as https://github.com/kivy/kivy/issues/3965

Replacing ```        self._format = 'bgra'```
with ```        self._format = 'rgba'```
is enough to make the app run, but of course the colors are wrong.

The trouble is iOS camera will not output RGBA, only BGRA and several planar Lum+Chrominances formats.

So can the texture use BGRA or some YUV variant? Or can _copy_to_gpu() do the conversion?

**Comment by Benoit9** [comment]
OK, last update for today:

```                            if self._texture is None or self._texture.size != self._resolution:
            self._texture = Texture.create(self._resolution, colorfmt='bgra')
            self._texture.flip_vertical()
            self.dispatch('on_load')

        self._buffer = <bytes>data[:rowsize * height]
        self._format = 'bgra'
        self._copy_to_gpu()
```

Works (at least on a recent iOS device with BGRA support).

**Comment by AndreMiras** [comment]
Nice work!
A https://github.com/kivy-garden/garden.zbarcam user/developer confirms (https://github.com/kivy-garden/garden.zbarcam/issues/17#issuecomment-397844165) this fixes the black screen on his iOS device too. Can we bring a fix upstream?

**Comment by misl6** [comment]
Issue looks fixed on `master` branch. Thank you!
