### ISSUE TITLE
Installing Kivy on Mac Issues

### ISSUE THREAD

**Issue by XHueyFreemanX** [kivy/kivy#5288]
### Versions

* Python: 3.6
* OS: 10.12.3
* Kivy: 1.10.0
* Kivy installation method: MacPorts 

### Description

I am a first time app developer with plenty of ideas just getting started using Kivy. Currently I am having trouble installing Kivy after following the instructions on kivy.org. 

After downloading version 1.10.0 here:
https://kivy.org/downloads/1.10.0/

I entered the following in terminal:
$ sudo mv Kivy2.app /Applications/Kivy.app
In return I get "No such file or directory"

What am I doing wrong? Please help
### Code and Logs

```python

$ sudo mv Kivy2.app /Applications/Kivy.app
```

**Comment by jekoie** [comment]
read installed document clearly

**Comment by dessant** [comment]
You've mixed up the installation methods. Kivy.app is not part of the MacPorts instructions, and it isn't even downloadable currently, see https://github.com/kivy/kivy/issues/5211.

https://kivy.org/docs/installation/installation-osx.html

**Comment by XHueyFreemanX** [comment]
Thank you dessant!
