### ISSUE TITLE
Fixed panel on top of the application in kivy

### ISSUE THREAD

**Issue by susheel-smrt** [kivy/kivy#5289]
New to kivy.. I'm in middle of developing an interface and my task is to create a fixed panel on top of the application that displays certain set of information by default .. say for example : time, date, temparature ..
Pl. guide me with a right procedure..!!

**Comment by KeyWeeUsr** [comment]
This is a source repository, therefore report here only issues related to the Kivy framework source and/or stuff closely related to it.

For tutorials see [Getting started](https://kivy.org/docs/gettingstarted/intro.html), [Crash Course](https://kivy.org/docs/tutorials/crashcourse.html) or [Wiki](https://github.com/kivy/kivy/wiki/Talks-and-tutorials).

For community support see [mailing list](https://groups.google.com/forum/?place=forum/kivy-users#!forum/kivy-users), [online chat](https://webchat.freenode.net/?nick=kvuser.&channels=kivy&uio=d4), [StackOverflow](http://stackoverflow.com/tags/kivy/) or even [Reddit](https://www.reddit.com/r/kivy/)
