### ISSUE TITLE
How to fix OpenGL 1.1 Issue in Server ?

### ISSUE THREAD

**Issue by tejastank** [kivy/kivy#5293]
### Versions : Latest

* Python: 2.7
* OS: Window 2012
* Kivy: latest version
* Kivy installation method: PIP

### Description

-> Kivy is great platform, I had build solution working fine in window 10.0, with pyInstaller I generated executable succesful, working fine, Now when I shift to window 2012 server than It works well.

-> Now issue happen when I connected window 2012 from other system via remote desk to start kivy executbale it gives OpenGL 1.1 issue.

-> Case when we start Kivy Executable from Window2012 than connect via remoted desktop than it works.

So only issue happen only unable to run it from remote desktop, what should we do ?

### Code and Logs
We expert with python, hardly not yet any technical coding issues, just unable to understand Kivy Behaviour 

Looking for Kivy Experts Review and comment for guideline to resolve this issue.

Thank you in advance for your guidelines. #kivy

**Comment by KeyWeeUsr** [comment]
@dessant explained it in recently opened issue with +/- the same description. Ref https://github.com/kivy/kivy/issues/5251#issuecomment-312237049 for the solutions.

**Comment by tejastank** [comment]
@dessant I see their are no support in latest, I had to use 2016, . Ref #5251 (comment) is partial or failed, Even follow their step nothing works, looks undocumented patch solution.
Their is no such right technical details to work their.

No problem on justifying the new #Kivy #Framework had limitations & no support.

**Comment by akshayaurora** [comment]
@tejastank on why OpenGL does not work on Windows server 2012, you probably should contact the makers of that software... Microsoft.

Windows Server 2012 does not support OpenGL 2 over RDP, but Windows Server 2016 does.

Or try to use a remote desktop server/client that does, like tigervnc

**Comment by KeyWeeUsr** [comment]
> No problem on justifying the new #Kivy #Framework had limitations & no support.

No, the problem is that you're trying to use part of an OS, that can't run Kivy out of the box, but *might* be able with a different GL provider.

Kivy has a lot of communication channels related to support of the framework itself and even closely related parts, but we most likely can't do anything else except Angle to overcome problems like the one you experienced. Read the OS specs before running applications. :)

**Comment by tejastank** [comment]
@KeyWeeUsr I prefered kivy, but you may accept kivy not working in Window2012,

I never say it not working in other platform, but out of all GUI Operating system Kivy limited some boundries with windown 2012.

We build something with kivy before I develop kivy application their is not such document I found where its justified it will not work in widnow 2012. I am investigated and found issue so public query, 

In case sime have positive input than he/she can share, their is nothing bad things around kivy.

Kivy is great framework, but in normal condition its not working in window 2012.

# Seems your comment are not productive, In case you had experties on Kivy, please answer below.
------------------------------------------------------------------------------------------------
-> Now issue happen when I connected window 2012 from other system via remote desk to start kivy executbale it gives OpenGL 1.1 issue.

-> Case when we start Kivy Executable from Window2012 than connect via remoted desktop than it works.

So only issue happen only unable to run it from remote desktop, what should we do ?
