### ISSUE TITLE
kivy.app missing from 1.10.0 downloads

### ISSUE THREAD

**Issue by devMoxie** [kivy/kivy#5294]
### 1.10.0

* Python: 2 and 3
* OS: OS X

### Description

Per the install instructions, [https://kivy.org/docs/installation/installation-osx.html#using-the-kivy-app](https://kivy.org/docs/installation/installation-osx.html#using-the-kivy-app) and downloading/extracting  `Kivy-1.10.0.tar.gz`  from [https://kivy.org/downloads/1.10.0/](https://kivy.org/downloads/1.10.0/) there does not exist kivy.app.

**Comment by KeyWeeUsr** [comment]
ref #5211 @akshayaurora ping

**Comment by dessant** [comment]
Tracking at https://github.com/kivy/kivy/issues/5211.

**Comment by PaulHost** [comment]
+
