### ISSUE TITLE
Closing ALL scheduled Clock events

### ISSUE THREAD

**Issue by openedhardware** [kivy/kivy#5297]
I am having multiple Clock events in a class, and need to unschedule all of them when an event fires.
The problem is, Clock events are generated dynamically and it's a bit tricky to declare event_trigger to each one and cancel them by iterating event triggers.
Is there any way of canceling all Clock events in a class?

**Comment by matham** [comment]
No, clock events are not associated with any class and are all independent of each other. You have to store them, maybe in a list, and cancel them individually.
