### ISSUE TITLE
Limit touch inside the widget box

### ISSUE THREAD

**Issue by susheel-smrt** [kivy/kivy#5299]
I'm struck at this.. people please suggest me way to handle touch separately for each slider.!?

(self . velocity and self.steering are the two sliders )

-----------
def on_touch_down(self,touch):

    touch.grab(self)
    
    self.steering.value_pos = touch.pos

    self.velocity.value.pos = touch.pos
def on_touch_move(self,touch):

    print (touch.pos)

    if touch.grab_current == self:

        self.steering.value_pos = touch.pos

        self.velocity.value.pos = touch.pos
def on_touch_up(self, touch):

    if touch.grab_current == self:
    
        self.velocity.value = "0"

        self.steering.value = "0"

**Comment by dessant** [comment]
If the question is how to stop touch propagation, you can return `True` from the callback.

**Comment by susheel-smrt** [comment]
Hello dessant, Please be a bit more clear!
