### ISSUE TITLE
Can't run python3-kivy on Lubuntu.

### ISSUE THREAD

**Issue by yingshaoxo** [kivy/kivy#5306]
### Versions

* Python: Python 3.5.3
* OS:  Lubuntu | Ubuntu 17.04 | Linux version 4.10.0-19-generic (buildd@lcy01-13) (gcc version 6.3.0 20170321 (Ubuntu 6.3.0-10ubuntu1) )
* Kivy: 1.9.1
* Kivy installation method: sudo apt install python3-kivy

### Description

I just want to run a kivy app on python3.

Then I get following errors.

### Code and Logs

```python
[INFO   ] [Logger      ] Record log in /home/yingshaoxo/.kivy/logs/kivy_17-07-28_0.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - TypeError: expected bytes, str found
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 138, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 722, in __init__
    self.create_window()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 237, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 94, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1936)

x11 - ImportError: No module named 'kivy.core.window.window_x11'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by bionoid** [comment]
Are you running on VirtualBox? Try without 3d acceleration

**Comment by bionoid** [comment]
Oh wait, that seems like a different error than the virtualbox failure. Did you add the PPA etc? You should upgrade to 1.10 either  way, that may or may not resolve the problem

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/kivy/issues/5214#issuecomment-309712502. Please use the latest stable version of Kivy, which is currently `1.10.0`. you can find the installation instructions [here](https://kivy.org/docs/installation/installation-linux.html). If your distro's package manager doesn't find the latest stable version, you might want to compile from source. It's way easier than on Windows + you have currently latest Ubuntu, which would mean that e.g. copypaste of installation instructions could work good enough.

If you experience troubles, you might want to go to IRC to debug them in real time, or visit the mailing list. Links are [here](http://kivy.org/#support). :)

**Comment by yingshaoxo** [comment]
OK, thank you guys, finally it works.
