### ISSUE TITLE
Non-zero argument for pos in Texture.blit_buffer() causes texture to not render

### ISSUE THREAD

**Issue by jakogut** [kivy/kivy#5314]
### Versions

* Python: 3.6.2
* OS: Arch Linux
* Kivy: 1.10.0
* Kivy installation method: package manager

### Description

I have a buffer with image data in it, and I'm trying to blit a subsection of it, because it can be larger than the GPU's maximum allowed texture size.

When calling Texture.blit_buffer() with the 'pos' argument set to a non-zero value, the texture isn't rendered.

### Code and Logs

```python

from kivy.app import App
from kivy.uix.widget import Widget
from kivy.core.image import Image
from kivy.graphics.texture import Texture
from kivy.graphics import Rectangle

import array

class MyWidget(Widget):
    def __init__(self, **kwargs):
        super(MyWidget, self).__init__(**kwargs)

        texture = Texture.create(size=(512, 512))
        buf = [int(x * 255 / (512*512*3)) for x in range(512*512*3)]
        buf = array.array('B', buf).tostring()

        texture.blit_buffer(
            buf,
            colorfmt='rgb',
            bufferfmt='ubyte',
            pos=(0, 100) # If this is changed to (0, 0), the texture renders properly
        )

        with self.canvas:
            Rectangle(texture=texture, pos=self.pos, size=(512, 512))

class MyApp(App):
    def build(self):
        return MyWidget()

if __name__ == '__main__':
    MyApp().run()
```

EDIT: I thought it might be a video driver issue. I'm currently using an Intel HD Graphics 530 GPU. I tried the same code on a Firepro W2100 and had the same result.

**Comment by bionoid** [comment]
The `pos` argument skips input data from your 512x512 texture, but you are still trying to blit full 512x512 (by way of the default `size=full_texture_size` if you leave it out of the blit_buffer call). Basically, you end up reading out of bounds. If you want a 100 offset in y direction, you most deduct those 100 from the size to blit, so `size=(512, 412)` should work, unless I am misunderstanding something about the report. 

You should also use `colorfmt='rgb'` to Texture.create() to avoid allocating an unused byte per pixel (you're currently allocating for 4 bytes per pixel w/default rgba, but only using 3)

**Comment by jakogut** [comment]
I see what you mean. I changed my example accordingly:

`from kivy.app import App
from kivy.uix.widget import Widget
from kivy.core.image import Image
from kivy.graphics.texture import Texture
from kivy.graphics import Rectangle
from kivy.uix.relativelayout import RelativeLayout

import array

class MyWidget(Widget):
    def __init__(self, **kwargs):
        super(MyWidget, self).__init__(**kwargs)

    def on_parent(self, *args):
        buf = [int(x * 255 / (2048*2048*3)) for x in range(2048*2048*3)]
        buf = array.array('B', buf).tostring()

        print(f'self.size: {self.size}')

        document_y = 0

        texture = Texture.create(size=(512, 1024))
        texture.blit_buffer(
            buf,
            size=(512, 512),
            colorfmt='rgb',
            bufferfmt='ubyte',
            pos=(0, document_y) # If this is changed to (0, 0), the texture renders properly
        )

        with self.canvas:
            Rectangle(texture=texture, pos=(0, -document_y), size=(512, 1024))

class MyApp(App):
    def build(self):
        layout = RelativeLayout()
        layout.add_widget(MyWidget())
        return layout

if __name__ == '__main__':
    MyApp().run()
`

But it seems the only effect the 'pos' parameter has is where in the texture the buffer data is blit to, not where it's blit from. Probably my lack of understanding the API.

**Comment by bionoid** [comment]
> But it seems the only effect the 'pos' parameter has is where in the texture the buffer data is blit to,

Yup, you are absolutely right, I was too quick on the conclusion.. Seems like it ends up in [this glTexImage2D call](https://github.com/kivy/kivy/blob/master/kivy/graphics/texture.pyx#L1008-L1009), with the pos as x and y, that will indeed determine the *destination,* not the source. 

I guess you'll have to deal with it in some other way -- there is get_region of course, but taking a stab in the dark it probably won't work if the texture exceeds max supported size in the first place... Maybe SDL_BlitSurface or an imaging library, depending on how you obtain the data in the first place... Worst case wrestle the pixels manually... 

Or maybe someone else will chime in with a better suggestion :)

**Comment by jakogut** [comment]
> there is get_region of course

I actually just tried that, and it works great as long as the texture size is less than the GPU's maximum. :laughing: 

> Maybe SDL_BlitSurface or an imaging library

I'll give that a shot, thanks.
