### ISSUE TITLE
Kivy highres 4K display support

### ISSUE THREAD

**Issue by BillBridge** [kivy/kivy#5317]
### Versions

* Python: 2.7.13
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

It seems that kivy does not support 4k displays with zoom enabled properly. Please have a look at the attached screencapture of a kivy application screen on a 4K display with 200% zoom. Nothing is crisp and clear. Everything looks blurry.

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```
![screencap](https://user-images.githubusercontent.com/18249253/28980751-49e229b2-794f-11e7-9577-c5eb5d7b4425.png)

**Comment by tito** [comment]
What about usind KIVY_METRICS_DENSITY=2, is the rendering better?

**Comment by matham** [comment]
Should be fixed with https://github.com/kivy/kivy/pull/7299.
