### ISSUE TITLE
No good refreshing of TextInput in RecycleView

### ISSUE THREAD

**Issue by plancheD** [kivy/kivy#5318]
[Script.txt](https://github.com/kivy/kivy/files/1201976/Script.txt)

### Versions

* Python:v3.5.3
* OS:ubuntu 17.04
* Kivy: v1.10.0
* Kivy installation method: pip

### Description
By running this software, you get a first choice of recycleview(same than to press button 1).
The put any number in row nb4. 
Update the recycleview by pressing btt2 or btt3 and see strange behavior. 
By checking, with the print function, the data is always 0 for each row but not on the screen.
It reinitializes everything only if we change all the datas, rather than put '0'
for instance
self.data = [{'a_number': '1'}, {'a_number': '2'}, {'a_number': '3'}, {'a_number': '4'}, {'a_number': '5'}]
refresh all the TextInput, different from
self.data = [{'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}]
doesn't refresh the TextInput

By the way, is there a more efficient way to access a parent class than using multiple parents???
#on_text: if self.focus: self.parent.parent....parent.do_something_in_some_class( )
No direct way to access to a parent class?

### Code and Logs
```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.recycleview import RecycleView
from kivy.uix.floatlayout import FloatLayout

string_to_build_recycleview = '''
<rowTest@BoxLayout>:
    canvas:
        Rectangle:
            size: self.size
            pos: self.pos
    a_number: '5'
    TextInput:
        padding: (8, 1, 2, 1)
        halign: 'middle'
        size_hint_x: .8
        multiline: 'False'
        input_filter: 'int'
        text: root.a_number
        #on_text: if self.focus: self.parent.parent....parent.do_something_in_some_class( )

<RecycleViewTEST@RecycleView>:
    id: myListToTest
    scroll_type: ['bars', 'content']
    scroll_wheel_distance: dp(114)
    bar_width: dp(10)
    viewclass: 'rowTest'
    RecycleBoxLayout:
        default_size: None, dp(20)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        spacing: dp(2)
 '''


class RecycleViewTEST(RecycleView):
    def __init__(self, **kwargs):
        super(RecycleViewTEST, self).__init__(**kwargs)
        Builder.load_string(string_to_build_recycleview)
        self.populate_1()

    def populate_1(self):
        self.data = [{'a_number': '1'}, {'a_number': '2'}, {'a_number': '3'}, {'a_number': '0'}, {'a_number': '0'}]
        print(self.data)

    def populate_2(self):
        self.data = [{'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}]
        print(self.data)

    def populate_3(self):
        self.data = [{'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}]
        print(self.data)



string_to_build_the_form = '''
<TheForm>:
    Button:
        size_hint: (None, None)
        size: (180, 27)
        pos_hint: {'x': .05, 'y': .9}
        id: btt1
        text: 'Populate with 1'
        on_release: root.ids['myListToTest'].populate_1()
    Button:
        size_hint: (None, None)
        size: (180, 27)
        pos_hint: {'x': .35, 'y': .9}
        id: btt2
        text: 'Populate with 2'
        on_release: root.ids['myListToTest'].populate_2()
    Button:
        size_hint: (None, None)
        size: (180, 27)
        pos_hint: {'x': .65, 'y': .9}
        id: btt3
        text: 'Populate with 3'
        on_release: root.ids['myListToTest'].populate_3()
    BoxLayout:
        size_hint: .9,.25
        pos_hint: {'x':.05, 'y':.6}
        RecycleViewTEST:
            id: myListToTest
'''


class TheForm(FloatLayout):
    def __init__(self, **kwargs):
        super(TheForm, self).__init__(**kwargs)
    Builder.load_string(string_to_build_the_form)


class TheTEST(App):
    def build(self):
        sm = TheForm()
        return sm

if __name__ == '__main__':
    TheTEST().run()
```

**Comment by plancheD** [comment]
By using in a more complex software, if i increase the numbers of rows in a recycleview, my software stops because a property( not in relation with the recycleview) disappears. It happens only if i increase the rows of the recycleview, and nothing happen if i keep the same amount or decrease it. May the memory location of the property be used by the new datas of the recycleview?

**Comment by tshirtman** [comment]
It may be surprising, but it's actually a bug on your side.

What happens is that when you edit the textinput in yout rowTest widget, the data (root.a_number) of this row is not changed, and when the data of the listview is updated, if the dict passed contains the same number than currently assigned, no dispatching happens, and the textinput is not updated, because root.a_number is still the same as before the call to populate.

There are two ways to go about this:
- Making sure that root.a_number is always synced with TextInput's text (on_text: root.a_number = self.text) (see end of answer for my edited code).
- forcing dispatching of the a_number property even if the value didn't change, this can be achieved by making testRow a python class, and declaring the a_number property as NumbericProperty(force_dispatch=True)

as for the second question, this is usually solved by ids, just give a reference to the target id to the relevant widget, here i would probably pass it to recycleViewTest in your main kv (target_id: some_id), and pass it to the RecycleBoxLayout from there, so the row only has to call self.parent.target_id, alternatively, you could arrange for the reference to be in data, so testRow can simply do self.target_id, but that would probably be quite a waste of memory and processing power when the length of data grows.

I can't address the question in your comment, except by saying it's highly unlikely, so you should first look very hard for a bug in your code, but if you can create a code you can't share, that shows misbehaving on our side, please open a new bug for it.

I'll close this issue.

appendix:
(https://gist.github.com/tshirtman/78570c3184ed44c9bdb45de6b3134883)
```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.recycleview import RecycleView
from kivy.uix.floatlayout import FloatLayout

string_to_build_recycleview = '''
<rowTest@BoxLayout>:
    canvas:
        Rectangle:
            size: self.size
            pos: self.pos
    a_number: '5'
    TextInput:
        padding: (8, 1, 2, 1)
        halign: 'middle'
        size_hint_x: .8
        multiline: 'False'
        input_filter: 'int'
        text: root.a_number
        on_text: root.a_number = self.text
        on_text: if self.focus: root.parent.target_id.text = 'temp value: %s' % self.text

<RecycleViewTEST@RecycleView>:
    id: myListToTest
    scroll_type: ['bars', 'content']
    scroll_wheel_distance: dp(114)
    bar_width: dp(10)
    viewclass: 'rowTest'
    target_id: None

    RecycleBoxLayout:
        default_size: None, dp(20)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        spacing: dp(2)
        target_id: root.target_id
 '''


class RecycleViewTEST(RecycleView):
    def __init__(self, **kwargs):
        super(RecycleViewTEST, self).__init__(**kwargs)
        Builder.load_string(string_to_build_recycleview)
        self.populate_1()

    def populate_1(self):
        self.data = [{'a_number': '1'}, {'a_number': '2'}, {'a_number': '3'}, {'a_number': '0'}, {'a_number': '0'}]
        print(self.data)

    def populate_2(self):
        self.data = [{'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}]
        print(self.data)

    def populate_3(self):
        self.data = [{'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}, {'a_number': '0'}]
        print(self.data)

string_to_build_the_form = '''
<TheForm>:
    Button:
        size_hint: (None, None)
        size: (180, 27)
        pos_hint: {'x': .05, 'y': .9}
        id: btt1
        text: 'Populate with 1'
        on_release: myListToTest.populate_1()
    Button:
        size_hint: (None, None)
        size: (180, 27)
        pos_hint: {'x': .35, 'y': .9}
        id: btt2
        text: 'Populate with 2'
        on_release: myListToTest.populate_2()
    Button:
        size_hint: (None, None)
        size: (180, 27)
        pos_hint: {'x': .65, 'y': .9}
        id: btt3
        text: 'Populate with 3'
        on_release: myListToTest.populate_3()
    BoxLayout:
        size_hint: .9,.25
        pos_hint: {'x':.05, 'y':.6}
        RecycleViewTEST:
            id: myListToTest
            target_id: target

    Label:
        id: target
'''


class TheForm(FloatLayout):
    def __init__(self, **kwargs):
        super(TheForm, self).__init__(**kwargs)
    Builder.load_string(string_to_build_the_form)


class TheTEST(App):
    def build(self):
        sm = TheForm()
        return sm

if __name__ == '__main__':
    TheTEST().run()
```

**Comment by plancheD** [comment]
Thanks a lot for you answer.
'The mind is the source of happiness and unhappiness' Buddha
In your case....happiness.
