### ISSUE TITLE
Performance issues on Raspberry Pi and Window Provider x11 unable to find

### ISSUE THREAD

**Issue by ElGammler** [kivy/kivy#5322]
### Versions

* Python: 3.4
* OS: Raspbian
* Kivy: Kivy: v1.10.1.dev0, git-4b77ede, 20170726
* Kivy installation method:  [Installation Guide](https://kivy.org/docs/installation/installation.html)
  * Git clone
  * Edit (setup.py) USE_X11 to True
  * `sudo python3 setup.py build_ext --inplace -f` also tried `sudo python3 setup.py install`

> 

### Description
**My Project**
I want to create a thin client, that includes different remote application (rdp, vnc and so on). The kivy app should use keyboard/mouse and touchscreen.

**Issues** 

- I need a window manager that is not always fullscreen and draw over all (like egl). This is important for the remote application clients like rdesktop.
- Other window manager have massive performance issues (pygame and sdl2). Mouse, keyboad and the complete drawing of the window lags.
- No hardware acceleration of OpenGl. I already tried mesa with the experimental driver ([Mesa Github](https://github.com/anholt/mesa)). With this OpenGL library the kivy app is very fast and works fluently. Unfortunately the library causes segmentation faults with the xserver and other applications. Even the rdesktop app wont work stable with the library. If I open the menu on a remote screen the raspberry start lagging with 100% CPU. :tired_face:
- After all this I want to try the x11 window provider. So I compiled kivy with USE_X11=True inside the setup.py. I found that possible solution from this [#4706](https://github.com/kivy/kivy/issues/4706) post. I set the `os.environ['KIVY_WINDOW'] = 'x11'` and tried to start the app. Below, in the Code and Log section you see the log. It sais that kivy can't find any valuable Window provider.

**Already tried**

- Window Provider: pygame, sdl2, egl_rpi
- Mesa OpenGL with hardware acceleration
- /boot/config.txt `gpu_mem=512`
- Same issues on kivypie
- Decrease log_level

### Code and Logs

**Build Config**
```
Build configuration is:
 * use_rpi = 1
 * use_mali = 0
 * use_egl = 0
 * use_opengl_es2 = 1
 * use_opengl_mock = 0
 * use_sdl2 = 1
 * use_ios = 0
 * use_mesagl = 0
 * use_x11 = 1
 * use_gstreamer = 1
 * use_avfoundation = 0
 * use_osx_frameworks = 0
 * debug_gl = 0
 * debug = False
```
**Kivy log with x11**
```
[INFO   ] Logger: Record log in /home/pi/.kivy/logs/kivy_17-07-26_12.txt
[DEBUG  ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG  ] Cache: register <kv.atlas> with limit=None, timeout=None
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[DEBUG  ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] Cache: register <kv.shader> with limit=1000, timeout=3600
[INFO   ] Kivy: v1.10.1.dev0, git-4b77ede, 20170726
[INFO   ] Python: v3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1]
[INFO   ] Factory: 194 symbols loaded
[DEBUG  ] Cache: register <kv.lang> with limit=None, timeout=None
[INFO   ] Text: Provider: sdl2
[DEBUG  ] Window: Provider <egl_rpi> ignored by config
[DEBUG  ] Window: Provider <sdl2> ignored by config
[INFO   ] Window: Provider: x11(['window_egl_rpi', 'window_sdl2'] ignored)
[CRITICAL] Window: Unable to find any valuable Window provider.
x11 - TypeError: expected bytes, str found
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/__init__.py", line 900, in __init__
    self.create_window()
  File "kivy/core/window/window_x11.pyx", line 200, in kivy.core.window.window_x11.WindowX11.create_window (kivy/core/window/window_x11.c:3376)

[DEBUG  ] Cache: register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] Cache: register <textinput.width> with limit=None, timeout=60.0
[CRITICAL] App: Unable to get a Window, abort.
```
**Kivy config.ini**
```
[kivy]
keyboard_repeat_delay = 300
keyboard_repeat_rate = 30
log_dir = logs
log_enable = 1
log_level = debug
log_name = kivy_%y-%m-%d_%_.txt
window_icon = resources/image/icons/icon_logo.png
keyboard_mode = systemanddock
keyboard_layout = qwerty
desktop = 1
exit_on_escape = 1
config_version = 19
pause_on_minimize = 0
kivy_clock = default
default_font = ['Roboto', 'data/fonts/Roboto-Regular.ttf', 'data/fonts/Roboto-Italic.ttf', 'data/fonts/Roboto-Bold.ttf', 'data/fonts/Roboto-BoldItalic.ttf']
log_maxfiles = 100

[graphics]
display = -1
fullscreen = 0
height = 1080
left = 0
maxfps = 30
multisamples = 0
position = auto
rotation = 0
show_cursor = 1
top = 0
width = 1920
resizable = 0
borderless = 1
window_state = visible
minimum_width = 0
minimum_height = 0
min_state_time = .035
allow_screensaver = 0

[input]
mouse = mouse
%(name)s = probesysfs,provider=hidinput

[postproc]
double_tap_distance = 20
double_tap_time = 250
ignore = []
jitter_distance = 0
jitter_ignore_devices = mouse,mactouch,
retain_distance = 50
retain_time = 0
triple_tap_distance = 20
triple_tap_time = 375

[widgets]
scroll_timeout = 250
scroll_distance = 20
scroll_friction = 1.
scroll_stoptime = 300
scroll_moves = 5

[modules]
touchring = scale=0.3,alpha=0.7,show_cursor=1

```

**Other log files are attached to this post.**
[kivy_17-07-26_0_sdl2.txt](https://github.com/kivy/kivy/files/1211801/kivy_17-07-26_0_sdl2.txt)
[kivy_17-07-26_0_egl.txt](https://github.com/kivy/kivy/files/1211800/kivy_17-07-26_0_egl.txt)
[kivy_17-07-26_0_pygame(python3-kivy).txt](https://github.com/kivy/kivy/files/1211799/kivy_17-07-26_0_pygame.python3-kivy.txt)

Mesa Problem
[kivy_log_without_openGL.txt](https://github.com/kivy/kivy/files/1211806/kivy_log_without_openGL.txt)
[kivy_log_with_openGL_fake_kms.txt](https://github.com/kivy/kivy/files/1211807/kivy_log_with_openGL_fake_kms.txt)
[kivy_log_with_openGL_full_kms.txt](https://github.com/kivy/kivy/files/1211808/kivy_log_with_openGL_full_kms.txt)
[Xorg.0.log.old.txt](https://github.com/kivy/kivy/files/1211829/Xorg.0.log.old.txt)
[Xorg.0.log.txt](https://github.com/kivy/kivy/files/1211830/Xorg.0.log.txt)

/boot/
[cmdline.txt](https://github.com/kivy/kivy/files/1211816/cmdline.txt)
[config.txt](https://github.com/kivy/kivy/files/1211817/config.txt)

**Comment by bionoid** [comment]
``TypeError: expected bytes, str found`` -- str is a byte string in py2 and unicode in py3, seems like [this is the culprit](https://github.com/kivy/kivy/blob/1.10.0/kivy/core/window/window_x11.pyx#L199). As a hack, you could try to edit that line and recompile kivy (just specify a dummy window title), but obviouisly there may be other issues down that path

**Comment by ElGammler** [comment]
Hey bionoid,

I set a dummy title and recompiled kivy. It' also neccsassary to edit [line 234](https://github.com/kivy/kivy/blob/1.10.0/kivy/core/window/window_x11.pyx#L234). I used something like this: `b'dummy'`. So now I can use x11 as window provider. Thank you :smiley:.

The bad news. X11 is not as fast as I thought or hoped. It feels even slower than sdl2.
How can I get the performance of egl_rpi inside a window?

Regards,
ElGammler

**Comment by bionoid** [comment]
> How can I get the performance of egl_rpi inside a window?

Seems like support for OpenGL in X is a [fairly recent on RPi](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=159853) (Feb 2016), it may still be experimental/disabled by default.. Obviously worth a shot if you didn't enable this option before testing (I'd try SDL2 window provider first)... but I have no idea if it will work or how much effort is required to make it happen

**Comment by ElGammler** [comment]
## Update
Now I use Ubuntu Mate with the OpenGL Mesa project. Ubuntu use more actual packages, that doesn't cause Segmentation Faults.
Sometimes there are:
`[   156.118] (WW) modeset(0): flip queue failed: Device or resource busy`
`[   156.119] (WW) modeset(0): Page flip failed: Device or resource busy`
`[   156.119] (EE) modeset(0): present flip failed`
Errors from X. That generate a short black screen.
Not the best solution, but better than nothing.

Regards,
ElGammler

**Comment by tito** [comment]
You should try latest kivy on RPi, it seems to solve many issues you showed here. If it's not the case, double check that your specific issue is not already open on the tracker.

Please don't open an issue on Github that contains many items. It is harder to close it :)
