### ISSUE TITLE
kivy detect open gl ver 1.1 on python 3.6 

### ISSUE THREAD

**Issue by rish47** [kivy/kivy#5329]
import kivy 
kivy.require('1.1.0')

from kivy.app import App
from kivy.uix.button import Label 

class Hellokivy(App):

    def build(self):
        return Label(text="hello kivy")

helloKivy = Hellokivy()

helloKivy.run()
##############################################################################
 And this gives me an error in My IDE I use official pyhton 3.6 IDE
[INFO   ] [Logger      ] Record log in C:\Users\Rishikesh\.kivy\logs\kivy_17-08-14_11.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-484b2f7, 20170513
[INFO   ] [Python      ] v3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] No framebuffers extension is supported
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'1.1.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Microsoft Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GDI Generic'>
[INFO   ] [GL          ] OpenGL parsed version: 1, 1
[CRITICAL] [GL          ] Minimum required OpenGL version (2.0) NOT found!

OpenGL version detected: 1.1

Version: b'1.1.0'
Vendor: b'Microsoft Corporation'
Renderer: b'GDI Generic

**Comment by Kazun3500** [comment]
#https://github.com/kivy/kivy/issues/3576

**Comment by Kazun3500** [comment]
#3576

**Comment by Smartgeek85** [comment]
use 
"from kivy import Config
Config.set('graphics', 'multisamples', '0')"

At the starting of your code.

it would resolve the problem.

**Comment by elvis124** [comment]
Thanks

**Comment by hemanthyernagula** [comment]
Problem Continues even though `from kivy import Config
Config.set('graphics', 'multisamples', '0')` is included, is there any other way?

**Comment by tshirtman** [comment]
Do you have a recent driver for your gpu installed? Please make sure the bug you answer to is really the cause of your issue before answering here, you can come on discord at https://chat.kivy.org/ for user help.
