### ISSUE TITLE
unable to run python app on emulator PK: not found

### ISSUE THREAD

**Issue by linengmiao** [kivy/kivy#5332]
Hello

I wrote this short piece of code, which I am trying to get to run on an Android emulator: https://pastebin.com/3u9Prvt5

I am able to run this code by typing python2 myApp.py on my Ubuntu 16.04 machine. I then packed it to a .apk using the command: buildozer android debug

The .apk gets successfully created, I am able to get it in my genymotion Android emulator but cannot run it although I rooted my emulator and am root. When launching the app from terminal (after having done chmod 777 myApp) I get:

http://imgur.com/a/IxBJl

What can I do to run this basic piece of python code?

Thank!

**Comment by bionoid** [comment]
Only pure-python packages from pypi are supported "by default", if you specify them as a requirement.

Advanced packages like numpy needs a recipe for cross-compilation,  [see here](https://github.com/kivy/python-for-android/tree/master/pythonforandroid/recipes).  You are using a lot of packages, pandas, scilearn, openface and maybe others, they are not available on Android without a recipe. 

So you will need to make new recipes if you want to use them
