### ISSUE TITLE
NameError: name 'App' is not defined

### ISSUE THREAD

**Issue by mohammedali452** [kivy/kivy#5334]
### Versions

* Python: 3
* OS: Windows 10
* Kivy: 1.9.0
* Kivy installation method:

### Description
I am new to kivy and I am still trying to figure out how to use it. I tried running a simple code to see if it'll work however, I got this error:
### Code and Logs
import kivy
kivy.require('1.9.0')
from kivy.app import App
from kivy.uix.label import Label

class HelloApp(App):
    def build(self):
        return Label(text = "Hello World")

HelloApp().run()

```python
C:\Users\imohammed\AppData\Local\Programs\Python\Python36\python.exe C:/Users/imohammed/PycharmProjects/untitled/HelloWorld
[INFO   ] [Logger      ] Record log in C:\Users\imohammed\.kivy\logs\kivy_17-08-16_8.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "C:/Users/imohammed/PycharmProjects/untitled/HelloWorld", line 7, in <module>
     class HelloApp(App):
 NameError: name 'App' is not defined

```
Any idea what may be causing this?

**Comment by KeyWeeUsr** [comment]
Open this folder:

    C:\Users\imohammed\AppData\Local\Programs\Python\Python36\Lib\site-packages\kivy

and check in what state is `app.py` file in there. Is it missing? Is the `App` class in there? Can you see `.pyd` files in the same folder?

**Comment by mohammedali452** [comment]
@KeyWeeUsr App.py is empty. I cannot seem to find any .pyd files within the same folder.

**Comment by mohammedali452** [comment]
I found the app.py file on github and copy and pasted it into the empty file.  Now I am getting this error: `[INFO   ] [Logger      ] Record log in C:\Users\imohammed\.kivy\logs\kivy_17-08-16_15.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
 Traceback (most recent call last):
   File "C:/Users/imohammed/PycharmProjects/untitled/HelloWorld", line 3, in <module>
     from kivy.app import App
   File "C:\Users\imohammed\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\app.py", line 1
     Skip to content
           ^
 SyntaxError: invalid syntax

Process finished with exit code 1
`

**Comment by KeyWeeUsr** [comment]
Maybe you've overwritten it somehow, or the Kivy wasn't installed properly. I'd reinstall the package completely with this:

    pip install -U kivy

just in case some other file got mangled during the previous installation. Happy coding! 🍡

**Comment by Uttkarshraj516** [comment]
i have also this problem

**Comment by aigtx007** [comment]
me too

**Comment by JosielSoares** [comment]
`import kivy
kivy.require('1.9.0')
from kivy.app import App
from kivy.uix.label import Label

class HelloApp(App):
    def build(self):
        return Label(text = "Hello World")

#HelloApp().run() # <- note use here
# Try the code below, solved im my case.
App = HelloApp()
App.run()`
