### ISSUE TITLE
Kivy on raspberrypi wrong libs linked

### ISSUE THREAD

**Issue by dbgasaway** [kivy/kivy#5341]
### Versions

* Python: 3.5
* OS: Linux raspberrypi (Raspbian Stretch)
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

Apparently the ability to link to the broadcom EGL/GLES libs on rpi using -lEGL and -lGLES was a mistake, as these drivers aren't completely interchangeable with the mesa ones that other applications use and link to the same way. Some comments here:
https://bugreports.qt.io/browse/QTBUG-62216
https://github.com/raspberrypi/firmware/issues/625#issuecomment-230356111
As a result, the libraries /opt/vc/lib/lib{EGL,GLESv2}.so were removed in Stretch, and the default versions became the ones provided by mesa, with the renamed versions continuing to exist.

As a result you get confusing errors like "libEGL warning: DRI2: failed to authenticate" as seen here:
https://raspberrypi.stackexchange.com/questions/61078/qt-applications-dont-work-due-to-libegl
because if you have libegl1-mesa installed, then -lEGL links to the mesa one and not the broadcom one, which fails as they're partly incompatible. Unfortunately, despite being a quick google search away, the solution in the link isn't ideal, and doesn't work after ldconfig overrides the relevant link.

Note that rpi-update does fix this, as it puts these libraries back in /otp/vc/lib/, but according the above links that's not a good solution.

### Steps to reproduce
Upgrade a raspbian jessie image to stretch (I don't know if there are any official stretch images yet).
Install Kivy in a way that involves compiling from source, like pip
Install and run any Kivy application that uses EGL (any fullscreen app?)

### Proposed fix
At https://github.com/kivy/kivy/blob/master/setup.py#L601, change EGL and GLESv2 to brcmGLESv2 and brcmEGL. These are the new library names, and should prevent mesa conflicts.

##### Potential pitfalls
It's possible the renamed libs don't exist in earlier raspbian releases. My up-to-date jessie pi has it, but I don't have access to anything older to test. Maybe the release can be detected dynamically, if backwards compatibility that far in the past is important?

**Comment by MikahB** [comment]
There is indeed an official Stretch image now (both full and Lite) for the RPi - it's the default offered on the download site at the moment [https://www.raspberrypi.org/downloads/raspbian/](url)

Using the Stretch Lite image yesterday, I fought GLES / SDL2 errors all day and never got my HDMI touch-screen to be detected with Kivy, I will experiment tonight to see if this fixes it.

![image](https://user-images.githubusercontent.com/30204727/29517641-a205f6de-863b-11e7-84cb-0b384be0a451.png)

**Comment by rasmuspeders1** [comment]
Hi. I have created a pull request for a fix for this issue here: https://github.com/kivy/kivy/pull/5362
Is it possible someone can review? 
If the pull request is accepted I believe it will be helpful to a lot of people upgrading their raspberry pi's to Raspbian Stretch.

**Comment by KeyWeeUsr** [comment]
@dbgasaway The patch from @rasmuspeders1 has been merged. Could you test with the latest `master` branch, please?

**Comment by whimshot** [comment]
I was able to build and use kivy with the Hello World example on a freshly installed version of Raspbian Stretch. Here's the relevant information:

```
Linux 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

Python 3.5.3

certifi (2017.7.27.1)
chardet (3.0.4)
cryptography (1.7.1)
Cython (0.26.1)
docutils (0.14)
idna (2.6)
keyring (10.1)
keyrings.alt (1.3)
Kivy (1.10.1.dev0)
Kivy-Garden (0.1.4)
pip (9.0.1)
pyasn1 (0.1.9)
pycrypto (2.6.1)
Pygments (2.2.0)
pygobject (3.22.0)
python-apt (1.1.0b5)
pyxdg (0.25)
requests (2.18.4)
SecretStorage (2.3.1)
setuptools (33.1.1)
six (1.10.0)
urllib3 (1.22)
wheel (0.29.0)

```

**Comment by dbgasaway** [comment]
A build from master seems to work for me now also, thank you everyone.
