### ISSUE TITLE
Kivy UrlRequest doesn't trigger callback

### ISSUE THREAD

**Issue by eteamin** [kivy/kivy#5342]
### Versions

* Python: 3.5.2
* OS: Sierra
* Kivy: 1.10.0
* Kivy installation method: using pip

### Description

I think this [thread](https://stackoverflow.com/questions/45781224/kivy-urlrequest-doesnt-trigger-callback) explains it all. Is my DownloadTask object garbage collected?

**Comment by KeyWeeUsr** [comment]
Solved [here](https://stackoverflow.com/a/45782752/5994041), our `Thread` called a dead object's method.
