### ISSUE TITLE
OSError: Label: File 'data/fonts/DroidSansMono.ttf' not found

### ISSUE THREAD

**Issue by pavankoushik22** [kivy/kivy#5347]
### Versions

* Python: 3.5
* OS: Ubuntu
* Kivy: 1.10.0
* Kivy installation method: by adding kivy repo and installing using "apt" package manager

### Description
Running kivycatalog example throwing an error

### Code and Logs

```python
python3 main.py

```
this error shows up after running above command with some other confirmation messages

`[ERROR  ] [Image       ] Error loading texture ../../widgets/softboy.mpg`

**Comment by KeyWeeUsr** [comment]
As you can see, [there's no such file](https://github.com/kivy/kivy/tree/master/kivy/data/fonts). I recommend you to reinstall Kivy properly as it appears to me that you have files from some older version that still uses the missing font file. Preferably remove Kivy first and install after. Or try installing from [pypi](https://pypi.python.org/pypi/Kivy) via `pip`.
