### ISSUE TITLE
Brew install on OSX 10.11.6: AVFoundation header not found

### ISSUE THREAD

**Issue by paulvanvulpen** [kivy/kivy#5354]
### Versions

* Python: 2.7.10
* OS: OSX 10.11.6
* Kivy: 9.0.1
* Kivy installation method: Homebrew with pip

### Description
I followed the instructions found here:
[kivy installation instructions](https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip)

At the buildstep: `pip install kivy` I run into the following problem:

### Code and Logs

```bash
kivy/core/camera/camera_avfoundation_implem.m:16:9: fatal error: 'AVFoundation/AVFoundation.h' file not found
    #import <AVFoundation/AVFoundation.h>
            ^
    1 error generated.
     error: command '/usr/bin/clang' failed with exit status 1
```

### History
It might be related the issue that was listed much earlier ([#2223](https://github.com/kivy/kivy/issues/2223), I thought that it was addressed in 9.0.1 though.

Alternatively, the installer provided [here](https://kivy.org/downloads/1.9.1/Kivy-1.9.1-osx-python2.7z) works.

**Comment by Julian-O** [comment]
Ugh. Sometimes you try to add the support tag, and hit enter too quickly, and the GitHub page selects the awaiting-replay tag by mistake. Sorry.
