### ISSUE TITLE
UrlRequest error (name 'HTTPSConnection' is not defined)

### ISSUE THREAD

**Issue by sugrob4** [kivy/kivy#5356]
Hi!
I have a ready project written on kivy and python3.
This program works fine on all desktop OS (Windows, Linux, MacOS),
but after compiling into a .apk file, UrlRequest does not work for me.
What I just did not do, in buildozer.spec -- 
requirements = pyopenssl,openssl,docutils,android,python3crystax,kivy
and in 
android.permissions = INTERNET, ACCESS_NETWORK_STATE
After installing the .apk file on the android and pressing the button to scrape the page of the site, programm produces an error
**name 'HTTPSConnection' is not defined**

This is part of the code with UrlRequest:

```
def get_html(self, link):
    try:
        from kivy.network.urlrequest import UrlRequest
        if isinstance(link, bytes):
            link = link.decode('utf-8')
        reg = UrlRequest(link, debug=True,
                         on_success=self.suc, on_error=self.err)
        while not reg.is_finished:
            sleep(0.5)
            Clock.tick()
    except HTTPError:
        pass

def suc(self, reg, result):
    self.add_widget(Label(
        text=str(result), font_size='15sp', color=(0, 0, 0, 1)
    ))

def err(self, reg, error):
    class Error(App):
        def build(self):
            win_report = BugReporter(txt_report=str(error))
            return win_report
    Error().run()
```
in variable (link) inserts links from a dict.

```
dict_links = dict({
    "userful_programs": "https://pcompstart.com/?view=cat&category=1",
    "advice_on_computer": "https://pcompstart.com/?view=cat&category=2",
    "user_windows": "https://pcompstart.com/?view=cat&category=3",
    "articles_in_theme": "https://pcompstart.com/?view=cat&category=4",
    "popular_program": "https://pcompstart.com/?view=cat&category=5",
    "other": "https://pcompstart.com/?view=cat&category=6"})
```
Full file logs for my buildozer.spec with log_level = 2, attached in file 'logcat.txt' at the bottom.

Or if in the same file I will execute  --  
`from http.client import HTTPSConnection`
Then after compilation on android I get error -- 
 **ImportError: cannot import name 'HTTPSConnection'**

Or if i will execute  --  
`import ssl`
Then after compilation on android I get error -- 
**ImportError: No module named '_ssl'**

Likely kivy compiling without SSL support. This is bug or I'm wrong?

Thanks!
[logcat.txt](https://github.com/kivy/kivy/files/1254837/logcat.txt)

**Comment by bionoid** [comment]
Python 3 support is expeeimental on android, unless something changed recently openssl is not supprted :( see this p4a pr and the linked issue:

https://github.com/kivy/python-for-android/pull/707

**Comment by sugrob4** [comment]
Thank you!
