### ISSUE TITLE
Requesting Keyboard causes Windows Resize to crash app

### ISSUE THREAD

**Issue by alsteven** [kivy/kivy#5359]
### Versions

* Python: 3.6
* OS: Windows 10
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

While adding keyboard support to a Kivy App, I noticed the app would crash for mysterious reasons. There seems to be an odd dependency between having requested a Keyboard at some point, and subsequent Window resizing. I have attached a minimal repro below.

### Code and Logs

The following minimal app reproduces the problem. Uncomment the commented lines to work around the bug.
 
```python
from kivy.app import App
from kivy.core.window import Window
from kivy.uix import label

class TestApp(App):
    def _keyboard_closed(self):
        print("closed")

    ## uncomment following function and lines in __init__ to work around bug
    # def to_window(self, x, y, initial=True, relative=False):
    #     return x,y

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        ## following line causes crash when window resized
        self._keyboard = Window.request_keyboard(self._keyboard_closed, self)

        ## Uncomment following to work around bug
        #self.y = 0

    def build(self):
        self.root = label.Label(text="Resize me")
        return None

TestApp().run()

```

Here is a log file:

[INFO   ] Logger: Record log in C:\Users\Alexander\.kivy\logs\kivy_17-08-31_0.txt
[INFO   ] Kivy: v1.10.0
[INFO   ] Python: v3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.4.0 - Build 20.19.15.4531'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) HD Graphics 5500'>
[INFO   ] GL: OpenGL parsed version: 4, 4
[INFO   ] GL: Shading version <b'4.40 - Build 20.19.15.4531'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Shader: fragment shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] Shader: vertex shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Leaving application in progress...

**Comment by tito** [comment]
There is no crash at all in your log. All indicate that the application is leaving. That's weird. @akshayaurora ?

**Comment by alsteven** [comment]
Sorry, I was running under the debugger, and included the log just so you'd have the version strings. Best way to see what's going on is to just run the minimal sample I wrote and resize the window once it starts. You can avoid the crash by uncommenting the lines in the sample as well, but it makes no sense that requesting a keyboard creates these dependencies (and they aren't documented anywhere) so I figured this was a bug. Thanks for looking into it!

**Comment by tmarplatt** [comment]
I ran into this same issue. So I ran @alsteven 's code in case you still need that crash log:

>  Traceback (most recent call last):
>    File "keyboardwindow.py", line 26, in <module>
>      TestApp().run()
>    File "/usr/local/lib/python3.4/dist-packages/kivy/app.py", line 826, in run
>      runTouchApp()
>    File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 502, in runTouchApp
>      EventLoop.window.mainloop()
>    File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
>      self._mainloop()
>    File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_pygame.py", line 379, in _mainloop
>      self.update_viewport()
>    File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/__init__.py", line 1418, in update_viewport
>      targettop = max(0, target.to_window(0, target.y)[1]) if target else 0
>  AttributeError: 'TestApp' object has no attribute 'to_window'

The culprit: https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L1418

I'm using the supplied workaround for now, so thanks for that.

**Comment by jxoesneon** [comment]
I'm having this issue with version 1.0.10 as well as 1.11.1

**Comment by jxoesneon** [comment]
The workaround still works but it took me a while to find this page

**Comment by TonyArmitstead** [comment]
The docs imply that the Window.request_keyboard() call takes a Widget as the last parameter. You are calling it within an App cass - not a Widget, so your use of 'self' is wrong. It seems that setting the last parameter to None prevents the issue - but I cant find official docs this is an OK thing to do.
