### ISSUE TITLE
Kivy & NixOS: results, questions & suggestions

### ISSUE THREAD

**Issue by vanschelven** [kivy/kivy#5367]
I've just (barely) managed to get Kivy to work on a NixOS system.

Quoting from their website:

> [NixOS](https://nixos.org/) is a Linux distribution with a unique approach to package and configuration management. Built on top of the Nix package manager, it is completely declarative, makes upgrading systems reliable, and has many other advantages.

Trying to install Kivy on a NixOS system is useful for at least 2 reasons:

1. Some people (e.g. myself) run NixOS and would like to install the Kivy package.
2. Nix's build environments are isolated by design. This makes forces one to be explicit about runtime and build time dependencies. This explicitness results in information could be useful for others that want to deploy Kivy.

The present issue is therefore a bit of a mixed bag of the following:

1. My findings so far, hopefully useful for others
2. Questions that remain; I hope someone might be able to answer those.
3. Suggestions for improvements (both in terms of documentation and reducing the dependency footprint).

Kivy developers without any interest in NixOS might want to skip section 1. I have not split the points mentioned in section 3 out into multiple issues in GitHub; people that wish to do that should feel free.
The questions & suggestions have been uniquely numbered in the below so that people that have only a single answer may still be able to give that in a clear way.

## 1. Installing on Nixos

The below was tested on NixOs 17.03.
The below is for Kivy-1.10.0.
I didn't get all nosetests to run yet; but my personal Kivy application runs, so at least we have a visual.

The following piece of code may be inserted into `pkgs/top-level/python-packages.nix`

```
  kivy = buildPythonPackage rec {
    name = "Kivy-1.10.0";

    src = pkgs.fetchurl {
      url = "mirror://pypi/k/kivy/${name}.tar.gz";
      sha256 = "1394zh6kvf7k5d8vlzxcsfcailr3q59xwg9b1n7qaf25bvyq1h98";
    };

    # setup.py invokes git on build but we're fetching a tarball, so
    # can't retrieve git version. We remove the git-invocation from setup.py
    # In https://github.com/kivy/kivy/pull/5366 this was fixed, so the next version of Kivy probably
    # does not need this patch
    patches = [
      ../development/python-modules/kivy/setup.py.patch
    ];

    buildInputs = with self; [ 
      pkgconfig
      cython
      kivygarden
      requests2
      docutils
      pygments
      nose

      pkgs.SDL2
      pkgs.SDL2_image
      pkgs.SDL2_ttf
      pkgs.SDL2_mixer

      pkgs.mesa
      pkgs.gst_all_1.gstreamer
      ];

    propagatedBuildInputs = with self; [
      pillow
      ] ; 

    doCheck = false;

    checkPhase = ''
      export KIVY_NO_CONFIG=1
      nosetests
    '';

    meta = {
      description = "A software library for rapid development of hardware-accelerated multitouch applications.";
      homepage    = "https://pypi.python.org/pypi/kivy";
      license     = licenses.mit;
      maintainers = with maintainers; [ vanschelven ];
      platforms   = platforms.unix;  # Can only test linux; in principle other platforms are supported
    };
  };

  kivygarden = buildPythonPackage rec {
    name = "kivy-garden-0.1.4";

    src = pkgs.fetchurl {
      url = "mirror://pypi/k/kivy-garden/${name}.tar.gz";
      sha256 = "0wkcpr2zc1q5jb0bi7v2dgc0vs5h1y7j42mviyh764j2i0kz8mn2";
    };

    buildInputs = with self; [ requests2 ];

    meta = {
      description = "The kivy garden installation script, split into its own package for convenient use in buildozer.";

      homepage    = "https://pypi.python.org/pypi/kivy-garden";
      license     = licenses.mit;
      maintainers = with maintainers; [ vanschelven ];
      platforms   = platforms.unix;  # Can only test linux; in principle other platforms are supported
    };
  };
```

The associated patch file in `pkgs/development/python-modules/kivy/setup.py.patch` is:

```
--- Kivy-1.10.0/setup.py	2017-05-07 17:24:57.000000000 +0200
+++ setup.py	2017-09-04 14:27:13.222721223 +0200
@@ -42,12 +42,7 @@
 def get_version(filename='kivy/version.py'):
     VERSION = kivy.__version__
     DATE = datetime.utcnow().strftime('%Y%m%d')
-    try:
-        GIT_REVISION = check_output(
-            ['git', 'rev-parse', 'HEAD']
-        ).strip().decode('ascii')
-    except CalledProcessError:
-        GIT_REVISION = "Unknown"
+    GIT_REVISION = "Unknown"

     cnt = (
         "# THIS FILE IS GENERATED FROM KIVY SETUP.PY\n"
```

## 2. Questions that remain

On the installation page there is the following quote:

> We don’t expect you to install all those things on your own. Instead, we have created nice portable packages that you can use directly, and they already contain the necessary packages for your platform. We just want you to know that there are alternatives to the defaults and give you an overview of the things Kivy uses internally.

To be honest, the fact that installation of "all those things" is not actually expected to be doable is somewhat apparent in the process of trying to get it to work :-/

In any case, some questions:

* **Q-1** In the documentation there are references to both `SDL2` and `pygame`. Is it correct to understand that the latter is deprecated in favor of the former?
* **Q-2** There are various packages on the internet available that provide python bindings for `SDL2`. Is it correct to understand that Kivy does not depend on these, but instead has its own bindings?

* **Q-3** what is the preferred setup for running the tests? `nosetests` runs some tests, but it is not clear to me how to best configure the environment before doing so. A question in particular is the following: Kivy's build phase may be configured in any number of ways. (Many different available dependencies). How to tell the tests about this? E.g. if building without gstreamer support, I don't want to attempt to test gstreamer-dependent stuff and similarly for other cases. (The piece of the puzzle that I _did_ manage to get working was to prefix the tests with `export KIVY_NO_CONFIG=1` - a `HOME` directory does not exist in the Nix build environment by design)

* **Q-4** The dependency on pillow is mentioned as an optional one, but running Kivy's nosetests without Pillow installed leads to "ERROR... aborting". (something about a lack of a TEXT provider). 

* **Q-5** When running a `pip install kivy` `docutils` is pulled in automatically. Is it required when running Kivy? Is it required in the build phase? Or is it only required for those that actually develop Kivy?

* **Q-6** Similarly, `pygments` is pulled in automatically. It seems to be required only by a single widget. Would it be possible to make the dependency more optional?

## 3. Suggestions for improvements

* **I-1** At present [`setup.py` prints a warning, but continues, when the `pkg-config` executable does not exist](https://github.com/kivy/kivy/blob/51d172500dd5a16f053a7bee01d56ea576303005/setup.py#L81) I would suggest a more fatal error on not finding pkg-config, since it is, AFAIU, a hard requirement for correct compilation.

* **I-2** The package `kivy-garden` is pulled in by the `kivy` package, even though there is no actual _dependency_ of the former on the latter (AFAIU). Kivy-garden then goes and worsens the situation by pulling in `requests`, which pulls in further packages (`urllib3`, `certifi`, `idna` & `chardet`). I would suggest to remove the dependency, and let those that want to install `kivy-garden` just install it themselves. TBH I don't understand the need for kivy-garden in the first place, it would seem to be a half-baked "not invented here" implementation of `pip`/`PyPI` but perhaps I'm missing something.

* **I-3** IIRC there was an automatic installation of the `requests2` library; I'm not sure whether that was exclusively caused by `Kivy` itself or only indirectly via `Kivy-garden`. In any case, the only references in `Kivy` to `requests` are in 2 error-reporting and benchmarking tools; it would seem quite bloating to pull in all of `requests2` just to support those 2 (optional) tools.

**Comment by inclement** [comment]
> Trying to install Kivy on a NixOS system is useful for at least 2 reasons:

I agree, thanks for trying this.

> Q-1 In the documentation there are references to both SDL2 and pygame. Is it correct to understand that the latter is deprecated in favor of the former?

This is correct, although we don't intend to actively break the pygame backend.

> Q-2 There are various packages on the internet available that provide python bindings for SDL2. Is it correct to understand that Kivy does not depend on these, but instead has its own bindings?

This is also correct.

> Q-3 what is the preferred setup for running the tests?

I'm not sure about this, some of the other devs should be able to help though.

> Q-4 The dependency on pillow is mentioned as an optional one, but running Kivy's nosetests without Pillow installed leads to "ERROR... aborting". (something about a lack of a TEXT provider).

What exactly is the error? It sounds like the kind of generic message you'd expect if no text provider is built (in which case pillow is one thing it will look for), but if Kivy runs normally in other circumstances then this seems surprising.

> Q-5 When running a pip install kivy docutils is pulled in automatically. Is it required when running Kivy? Is it required in the build phase? Or is it only required for those that actually develop Kivy?

I think the rst viewing widget requires docutils. I'm not explicitly aware of anything else.

> Q-6 Similarly, pygments is pulled in automatically. It seems to be required only by a single widget. Would it be possible to make the dependency more optional?

This also seems correct. It would be nice to make it more optional. I was recently looking at the setuptools provision for this (http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), but wasn't sure if the user experience here is helped much, as it seems that in normal use the user will only find out about the dependencies when the import fails. Maybe that's fine though.

> I-1 At present setup.py prints a warning, but continues, when the pkg-config executable does not exist I would suggest a more fatal error on not finding pkg-config, since it is, AFAIU, a hard requirement for correct compilation.

I'm not familiar with this but it certainly seems fair.

> TBH I don't understand the need for kivy-garden in the first place, it would seem to be a half-baked "not invented here" implementation of pip/PyPI but perhaps I'm missing something.

Personally I don't really disagree (although there are at least some advantages in principle), but other of the devs may be able to make a more passionate defence.

> IIRC there was an automatic installation of the requests2 library; I'm not sure whether that was exclusively caused by Kivy itself or only indirectly via Kivy-garden. In any case, the only references in Kivy to requests are in 2 error-reporting and benchmarking tools; it would seem quite bloating to pull in all of requests2 just to support those 2 (optional) tools.

This also seems fair enough to me.

**Comment by bionoid** [comment]
> (Q-4) E.g. if building without gstreamer support, I don't want to attempt to test gstreamer-dependent stuff

Unless something changed recently, video/image/audio tests are only run for the preferred provider. Ie, the first one that is installed correctly and will load the file (provider order depends on platform etc, see bottom of ``core/(audio|video|image)/__init__.py``). As far as I know you have to set environment variables to control the provider selection (``KIVY_VIDEO`` etc, [docs](https://kivy.org/docs/guide/config.html)) to specify what to test.. This seems like a shortcoming to me, [the ImageLoader testcase PR](https://github.com/kivy/kivy/pull/5304/files#diff-19f58f96825d151c66dfdfc02cfd348eR13) does some extra work to test all installed image providers. I'm not sure why the existing tests don't do this.

**Comment by vanschelven** [comment]
Thanks for the quick and almost complete answers @inclement 

Regarding a few of the open points:

>> Q-4 The dependency on pillow is mentioned as an optional one, but running Kivy's nosetests without Pillow installed leads to "ERROR... aborting". (something about a lack of a TEXT provider).

> What exactly is the error? It sounds like the kind of generic message you'd expect if no text provider is built (in which case pillow is one thing it will look for), but if Kivy runs normally in other circumstances then this seems surprising.

I've managed to reproduce: when compiling Kivy with neither SDL2, nor pygame, nor Pillow, I get the following (probably expected) test failure:
```
    [CRITICAL] [App         ] Unable to get a Text provider, abort.
```

Given the answers above I've come up with a new question:

* **Q-7** I know there are many ways Kivy could be configured. What is the most canonical complete configuration on the linux platform though? I suppose another way of asking this is: with which dependencies are the PPA packages compiled? Hopefully such a configuration will automatically solve any problems I had in getting the tests to pass (assuming that a complete configuration has passing tests)

**Comment by inclement** [comment]
> Q-7 I know there are many ways Kivy could be configured. What is the most canonical complete configuration on the linux platform though?

I believe the answer is sdl2 for everything, certainly including the Window and Text providers.

I'm least sure about the audio - I think the providers have more important differences here, with it being less obvious which is 'best', but I've never made much use of them.

**Comment by bionoid** [comment]
> I'm least sure about the audio and video

Camera is also unclear in the cross-platform sense, though for a canonical linux configuration the answer is probably opencv. SDL2 for image provider qualifies as "canonical", though it is my impression that ffpyplayer has wider and better format support. 

Hopefully pango will become the text provider for desktop linux in the near future.

**Comment by Julian-O** [comment]
This is a mixture of a support question and feature requests, making it difficult to close as completed.

Each feature requests that isn't covered by an existing issue should be raised separately. (Looks like many of them have been implemented.)
