### ISSUE TITLE
Tests should not rely on filesystem-writability

### ISSUE THREAD

**Issue by vanschelven** [kivy/kivy#5373]
The current tests assume that the filesystem in which the tests themselves live is writable by the test-running user.

Some locations that I have identified are:

* https://github.com/kivy/kivy/blob/3052803ad3cbdc5505c14d6bc2034e387e2f2e2c/kivy/tests/common.py#L48
* https://github.com/kivy/kivy/blob/3052803ad3cbdc5505c14d6bc2034e387e2f2e2c/kivy/tests/common.py#L179

I am currently running into problems with this in the context of https://github.com/kivy/kivy/issues/5367

However, the problem is more general. A quite common scenario that's made impossible by the assumption is the one where Kivy is installed globally by root, but a non-privileged user attempts to run the tests.

Perhaps we can rely on a tmpdir instead?

**Comment by KeyWeeUsr** [comment]
Try again after merging #5368 please. That PR contains a change that disables anything related to creating files or html or whatever other file-only output by default.

**Comment by vanschelven** [comment]
I haven't actually tried again after merging, but a quick visual scan of the code would seem to indicate that the mentioned pull request is not a fix. In particular, AFAIU, the creation of the directory will still be attempted because it's part of the general "run" mechanism, even when no files are actually written to that that directory:

https://github.com/kivy/kivy/blob/6bd932908ee6fe9024bba0741c4c4ddba67a20c2/kivy/tests/common.py#L48
