### ISSUE TITLE
Cannot pip install both Cython and Kivy in one pass

### ISSUE THREAD

**Issue by CodeMouse92** [kivy/kivy#5375]
### Description

The title says it all. Running the command `pip install Cython=0.25.2 kivy=1.10.0` doesn't work. I think I've traced this back to Kivy's `setup.py` metadata. Normally, `pip` can intelligently figure out the installation order from dependencies, but something about Kivy's `setup.py` is preventing that. Thus, it tries to install Kivy before Cython, which naturally fails.

This may not seem like a big deal, but what this does is it **prevents packaging with things like Snapcraft**, which `pip` install everything in one auto-generated command. That, obviously, is going to be a _huge_ problem for Kivy packaging in the long run.

### Versions

* Python: 3.5
* OS: Ubuntu 17.04
* Kivy: 1.10.0
* Kivy installation method: `pip`, see below

### Code and Logs
Here's the output from the command.

```bash
$ pip install Cython==0.25.2 kivy==1.10.0
Collecting Cython==0.25.2
  Downloading Cython-0.25.2-cp35-cp35m-manylinux1_x86_64.whl (7.0MB)
    100% |████████████████████████████████| 7.0MB 220kB/s 
  Saved /root/build_omission/parts/omission/packages/Cython-0.25.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting kivy==1.10.0
  Downloading Kivy-1.10.0.tar.gz (24.3MB)
    100% |████████████████████████████████| 24.3MB 74kB/s 
  Saved /root/build_omission/parts/omission/packages/Kivy-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Using distutils
    
    Cython is missing, it's required for compiling kivy !
    
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_hd184pu/kivy/setup.py", line 219, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'
```

**Comment by CodeMouse92** [comment]
Note, it is perfectly possible to have different requirements depending on platform. For example (courtesy cdunklau from Freenode #python)....

```python
requirements = ['this', 'that']
if 'linux' in sys.platform:
    requirements.append('onlylinux')
setup(
    .....whatever.....,
    install_requires=requirements)
```

**Comment by CodeMouse92** [comment]
I think I narrowed it down. I'm almost certain that Cython needs to be listed (conditionally) under `install_requires` in the same manner as it is listed under `setup_requires`.

**Comment by CodeMouse92** [comment]
Possible insight here: https://stackoverflow.com/questions/37471313/setup-requires-with-cython

**Comment by KeyWeeUsr** [comment]
Perhaps it'd close #4675 and allow installing Kivy as dependency on websites like ReadTheDocs. It might be worth trying.

**Comment by kdheepak** [comment]
Can you not just do the following?

```bash
pip install Cython=0.25.2
pip install kivy=1.10.0
```

**Comment by KeyWeeUsr** [comment]
@kdheepak the point is doing it in one go, which isn't possible for now and a casual python package does it without issues. For example ReadTheDocs won't even allow you to do this because reasons.

**Comment by kdheepak** [comment]
I see. It sounds like Kivy would benefit from using `extras_require` in `setup.py`.

```python
setup(
    # ...
    extras_require={
        "extras": [
            "Cython==0.25.2",
        ],
        "dev": [
            "sphinx",
        ]
    },
    # ...
)
```

If this was added, a user could type `pip install kivy[extras] # OR pip install kivy[extras,dev]`, to install all dependencies.

**Comment by KeyWeeUsr** [comment]
While I like the idea of having the `dev` part (we could throw there *-dev packages, headers, etc), I wonder how is a hard dependency an extra? It's not that we can't just move Cython somewhere else, quite the opposite as it's already separated. The idea here is to have a single command:

    pip install kivy

which would install Cython beforehand, then import it in the same file (`setup.py`) and then compile Cython files to C extensions.

**Comment by kdheepak** [comment]
Looking at this again it seems even `extra_requires` will not solve this, since Cython is a build dependency. This is related to pypa/pip#2381.

**Comment by kdheepak** [comment]
The alternative is to run the Kivy build step as a post install script. pip supports that, so that would allow everything to occur in a single step -> `pip install kivy`

**Comment by matham** [comment]
I wonder what changing to a post install script would entail and what other bugs it may create - our build system is pretty complex already... Perhaps we should just educate users to pre-install cython and close this as wontfix?

**Comment by CodeMouse92** [comment]
@matham, well, again that would mena you're shutting the door to all Linux packaging. Ergo, the bug report. This isn't "just install Cython first, happy days are here again". :) Snapcraft and most other Python-to-Linux-package systems rely on one-shot pip installs.

**Comment by matham** [comment]
@CodeMouse92  Hmm, ok. You make a good point. I didn't realize that one shot pip install is a requirement for linux packaging.

**Comment by johnthagen** [comment]
Hit this problem on macOS and Python 3.6 as well. Would be a better user experience if someone could just `pip install kivy` and get rolling on the tutorials.

**Comment by bazilevs31** [comment]
Same here OSX High Sierra, Python 3.6 (Anaconda distribution)

**Comment by pydsigner** [comment]
Did #5998 resolve this?

**Comment by misl6** [comment]
Here while looking around for issues to be closed regarding `sphinx` (so, totally unrelated, but issue showed up in the list).

We can consider this as fixed.

Tested via:
```bash
cd kivy_project_code_folder
export KIVY_DEPS_ROOT=/path/to/kivy-dependencies
pip install Cython==3.0.10 .
```
