### ISSUE TITLE
how can i integrate this kivy to yocto build 

### ISSUE THREAD

**Issue by vsivanagulu** [kivy/kivy#5376]
I just want to integrate this kivy to my arm board. now I'mm using yocto generated linux images . so i want to use this kivy in my arm board. please help me to integrate. Thanks In advance.

**Comment by KeyWeeUsr** [comment]
GitHub is used for bug reporting, not for support. See the [support](https://kivy.org/#support) page and the installation  [instructions for linux](https://kivy.org/docs/installation/installation-linux.html).
