### ISSUE TITLE
center (top, etc) parameter settings would fail if the widget size is not the default size (100,100)

### ISSUE THREAD

**Issue by xinmingzhang** [kivy/kivy#5383]
### Versions

* Python:Python 2.7.5
* OS: Windows (6.1.7601)
* Kivy:v1.10.0
* Kivy installation method:pip

### Description

I first posted the question here https://groups.google.com/forum/#!topic/kivy-users/xluSJIsUxdw, generally, kwargs in Widget have its own order, it is first deal with pos, then size, when kivy change the size, first setting about pos may failed. Say I have MyWidget with size (160,160), if I creat MyWidget(center=(0, 0)), the center would not be (0,0), it would be (30,30). I think, When I first set center=(0,0), its works, and its pos is (-50,-50) according to the default size (100,100), then kivy set its size to (160,160), but kivy anchor the self.x, self.y to (-50,-50), so the center changes to (30,30),not (0,0)

### Code and Logs
`

    from kivy.app import App
    from kivy.core.window import Window
    from kivy.uix.widget import Widget
    from kivy.graphics import Color,Rectangle
    from kivy.uix.floatlayout import FloatLayout

    Window.size = (800,600)

    class MyWidget(Widget):
        def __init__(self,*args,**kwargs):
            super(MyWidget,self).__init__(size =(160,160),*args,**kwargs)
            print(self.center)
            with self.canvas:
                import random
                Color(random.random(),random.random(),random.random())
                Rectangle(pos = self.pos,size = self.size)

    class MyApp(App):
        def build(self):
            f = FloatLayout()
            f.add_widget(MyWidget(pos = (0,0)))
            f.add_widget(MyWidget(center=(0, 0)))

            return f

    if __name__ == '__main__':
        MyApp().run()
`

result is 
[80.0, 80.0]
[30.0, 30.0]

**Comment by bionoid** [comment]
* Python 3.6.1 on exact same windows/kivy version consistently yields [0, 0]. I didn't see this fail.
* Python 3.5.3 on linux, seems like a coin toss between [0, 0] and [30, 30] - completely random
* Python 2.7.13 on linux consistently yields [30, 30] like in your report

**Comment by Julian-O** [comment]
I am not seeing the fail on Windows 11, Kivy 2.2.1., Python 3.11.

Is this still happening, or has it been fixed since Python 3.6?
