### ISSUE TITLE
How to use sort_func in filechooser

### ISSUE THREAD

**Issue by cayman54** [kivy/kivy#5394]
Hi,
In filechooser I try to sort files by date when I press a button. For this I use the sort_func argument, like this :  
```
def sort(self):
       self.ids.filechooser.sort_func = ObjectProperty(self.order_by_date(self.ids.filechooser.files, self.ids.filechooser.file_system))

def order_by_date(self, files, filesystem):
    return = (sorted(f for f in files if filesystem.is_dir(f)) 
              sorted((f for f in files if not filesystem.is_dir(f)), key=lambda fi: os.stat(fi).st_mtime, reverse = True))
```
When I print the new sorted list it is well sorted, but the view doesn't update and nothing happen in filechooser. How can I apply this new sort to the filechooser and update the view?
Thanks in advance,

**Comment by KeyWeeUsr** [comment]
@cayman54 if you just need to reload the content, see [this answer](https://stackoverflow.com/a/36264302/5994041). I was struggling with it too a long ago. Perhaps we're missing this call in `FileChooser` too. What happens if you go inside a folder and back out? Is the content sorted with your `sort_func`? If that's the case, then we miss the call.

Also, please paste a reproducible example. :)

**Comment by cayman54** [comment]
Hi,
When I go inside a directory and back out, I go no content anymore. When I use the `update_files()` function to refresh the view, same behavior no files shown anymore.
My sorting function works well because when I print the new list in `order_by_date` function (instead of returning it) I have the expected result.
Maybe I'm not using the good way `sort_func` ?

Here is my kv file :  
```
FileChooserIconView:
    size_hint: 1, .8
    id: filechooser
    multiselect: True
    dirselect: False
Button:
    size_hint: 1, .2
    text: 'Date'
    on_release: root.sort(self.text)
```

And here the functions in my py file:
```
def sort(self, text):
    if (text == 'Date'):
        self.ids.filechooser.sort_func = ObjectProperty(self.order_by_date(self.ids.filechooser.files, self.ids.filechooser.file_system))

def order_by_date(self, files, filesystem):
    return (sorted(f for f in files if filesystem.is_dir(f)) +
        sorted((f for f in files if not filesystem.is_dir(f)), key=lambda fi: os.stat(fi).st_mtime, reverse = True))
```
