### ISSUE TITLE
Put a showcase app on the App Store

### ISSUE THREAD

**Issue by nicholascarroll** [kivy/kivy#5401]
Hi, a friendly hello from a hopeful new user of Kivy!
This is an enhancement request rather than a bug.
## Desired Feature
It would be very helpful if Kivy should have a showcase app on the Apple App Store. This 'showcase app' would have each of the widget types, each type of transition, and the ability to switch themes.

## Benefits
The benefit of this is that people can get a good assessment of what Kivy offers in terms of prebuilt components and performance, within a few minutes of first visiting the Kivy website and reading about it.

## Example
Do something like [this](https://itunes.apple.com/at/app/qt-5-showcases-by-v-play-apps/id1040477271?l=en&mt=8)

**Comment by dessant** [comment]
This would certainly be nice, but we do not have an account for the Kivy Organization (99 USD/year seems a bit steep), unless @tito or someone else from the team has an account and can publish the [Kivy Showcase](https://play.google.com/store/apps/details?id=org.kivy.showcase), it's unlikely to happen anytime soon.

**Comment by nicholascarroll** [comment]
Thanks anyway
