### ISSUE TITLE
OpenCV Camera fps handled incorrectly

### ISSUE THREAD

**Issue by LukeBiddle** [kivy/kivy#5408]
When running an example usage of the Camera class, I found that the video was progressing one frame every 30 seconds, instead of 30 frames every one second.

I found the cause to be in kivy/core/camera/camera_opencv.py. On line 119 the fps is set to a value given by OpenCV. In my case this value was 30, which would be the expected value as far as I can tell. Then on line 152 the interval is set to update the texture with new frames, but the interval time is set to the fps value of 30, and as a result the video texture is not updated appropriately to keep up with the camera's stream.

The fix for me was to change line 152 to the following:
`self._update_ev = Clock.schedule_interval(self._update, 1. / self.fps)`

And to modify line 122 to:
`self.fps = 30`

I'm unsure if the fps value is used in any other files, or if other platforms expect the fps from OpenCV to be a value that can be used as an interval.

I am using: 
python 3.5.3
opencv 3.1.0
gstreamer 1.10.4
kivy compiled from source which I pulled down today
Fedora 25

Here is the code I'm running:
```
from kivy.app import App
from kivy.uix.camera import Camera

class MainApp(App):
    def build(self):
        cam = Camera(play=True, resolution=(640, 480))
        return cam

if __name__== "__main__":
    MainApp().run()
```

**Comment by LukeBiddle** [comment]
Pull request created here: https://github.com/kivy/kivy/pull/5409

**Comment by dessant** [comment]
Tracked at https://github.com/kivy/kivy/issues/5146.
