### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by Cyxapic** [kivy/kivy#5414]
### Versions

* Python: 3.5.2
* Cython version 0.27.1
* pygame 1.9.3
* OS: Ubuntu 16.04
* Kivy: 1.10
* Kivy installation method: via pip

### Description
Error when installing in ENV (pyvenv)

### Code and Logs

 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/san/prog/python/lern/kivytry/kivytry/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2nii19zs/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mt96ei7p-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/san/prog/python/lern/kivytry/kivytry/include/site/python3.5/kivy" failed with error code 1 in /tmp/pip-build-2nii19zs/kivy/

**Comment by KeyWeeUsr** [comment]
Kivy uses SDL2 instead of Pygame for a quite while, see [the docs](https://kivy.org/docs/installation/installation-linux.html). Anyway, this error log says nothing at all except the exit status.

**Comment by Cyxapic** [comment]
SDL2 in system and pygame works fine!
Seems its dont work with python 3.5.2/

**Comment by dessant** [comment]
Make sure to update to the latest version of pip, then post the full log, including the commands you have issued.

**Comment by Cyxapic** [comment]
pip -V
pip 9.0.1 from /home/san/prog/python/lern/kivy_try/lib/python3.5/site-packages (python 3.5)
python -m pip install kivy
* ******************************************************************************************************************
    cythoning /tmp/pip-build-o5w1w2xb/kivy/kivy/graphics/svg.pyx to /tmp/pip-build-o5w1w2xb/kivy/kivy/graphics/svg.c
    
     Error compiling Cython file:
     ------------------------------------------------------------
     ...
                     end = time()
                     Logger.debug("Svg: Loaded {} in {:.2f}s".format(filename, end - start))
                 finally:
                     fd.close()
    
         cdef void reload(self) except *:
             ^
     ------------------------------------------------------------
    
     kivy/graphics/svg.pyx:469:9: Signature not compatible with previous declaration
    
     Error compiling Cython file:
     ------------------------------------------------------------
     ...
             cpdef flag_update(self, int do_parent=?, list _instrs=?)
         ELSE:
             cpdef flag_update(self, int do_parent=?)
         cdef void flag_update_done(self)
         cdef void set_parent(self, Instruction parent)
         cdef void reload(self)
                        ^
     ------------------------------------------------------------
    
     kivy/graphics/instructions.pxd:36:20: Previous declaration is here
    building 'kivy.graphics.svg' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-build-o5w1w2xb/kivy/kivy/include -I/tmp/pip-build-o5w1w2xb/kivy/kivy/include -I/home/san/prog/python/lern/kivy_try/include -I/usr/include/python3.5m -c /tmp/pip-build-o5w1w2xb/kivy/kivy/graphics/svg.c -o build/temp.linux-x86_64-3.5/tmp/pip-build-o5w1w2xb/kivy/kivy/graphics/svg.o
    /tmp/pip-build-o5w1w2xb/kivy/kivy/graphics/svg.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/san/prog/python/lern/kivy_try/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o5w1w2xb/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-112tqiho-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/san/prog/python/lern/kivy_try/include/site/python3.5/kivy" failed with error code 1 in /tmp/pip-build-o5w1w2xb/kivy/

**Comment by parabolize** [comment]
Looks like the 1.10 version bump a4116a5 is between commits 0977d45 and ced5e6a. 0977d45 changed the signature of Svg.reload() in svg.pyx and ced5e6a updated svg.pxd

**Comment by KeyWeeUsr** [comment]
#5406 fixes the signatures, however I'm not sure about https://github.com/kivy/kivy/pull/5406#issuecomment-333308176 although I don't see difference between them. If merged, the issues related to this could be closed + I think it works both in Cython 0.27 and in 0.27.1 ("revert" for 0.27). Feel free to test on Apple devices.

**Comment by KeyWeeUsr** [comment]
Cython fix merged, please try again with master branch,

**Comment by Cyxapic** [comment]
Thanks! It's work!
