### ISSUE TITLE
Bunch of my old issues just got marked stale, what should I do?

### ISSUE THREAD

**Issue by ngoonee** [kivy/kivy#5420]
Most of them are just things which petered out, but (AFAICT) are still actual issues. Should I make a bump comment, or something?

**Comment by dessant** [comment]
Any activity on them clears the stale label, but preferably don't make bump comments. It's much better to check if the issue is still valid and inform maintainers about it, provide a self-contained example which reproduces the issue, or make sure the existing example still shows the bug.
