### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by LogicalDash** [kivy/kivy#5425]
I haven't seen any bad behavior in this project, myself, but I think it's always worthwhile to make standards of behavior explicit, both as a way to signal that we value civility and as an aid to socially awkward people such as myself, who often forget these things.

As a default I suggest the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html).

**Comment by Zen-CODE** [comment]
Where do you suggest putting such a thing? Here? https://kivy.org/docs/contribute.html

**Comment by LogicalDash** [comment]
That would be an appropriate place, yeah.

I think Kivy's an amazingly friendly and flexible framework that should be useful to everyone, so there ought to be all kinds of people in the community. In the long run that means we'll need to do actual outreach, evangelism and whatnot, but just announcing that we welcome everyone and intend to respect everyone's concerns is something we can do.

**Comment by Zen-CODE** [comment]
I hope these changes suffice? Please post again/re-open if you feel more needs to be done.

**Comment by LogicalDash** [comment]
I started an issue touching on enforcement #5541
