### ISSUE TITLE
Application window on desktop not showing everything

### ISSUE THREAD

**Issue by moonriviere** [kivy/kivy#5429]
### Versions

* Python: Python 3.6.1
* OS: Windows 10
* Kivy: 1.10.0
* Kivy installation method: via the pip method on the kivy official website

### Description

I have tried to go through the tutorial "Creating Desktop and Mobile Apps with Python by brousch at PyOhio 2013" on the github kivy wiki but midway through I realized that my application window is not showing the elements(not sure if this is the right word to use) properly. i.e. they are being clipped off/cropped away

Unlike in the video tutorial where the instructor's application window was showing everything without being clipped off. 

I've got a feeling the code doesn't matter because this issue also came up in the earlier steps of this tutorial; and that the issue actually lies in my windows settings somewhere? I just cant figure it out...

P.S. Apologies if this is a repeated issue that was solved before, but i really could not find this issue anywhere on the web

My application window:
![image](https://user-images.githubusercontent.com/32698819/31427549-445712f2-ae9a-11e7-8cbc-62f0e3e3f8ef.png)

Instructor's application window in the tutorial:
![image](https://user-images.githubusercontent.com/32698819/31427672-a08e5738-ae9a-11e7-8fbf-4501e445b18f.png)

### Code and Logs

This is the codes for the .py file and .ky file that I have got to so far... it should be the same as the instructor's codes in the video.

.py file:

```python
import kivy
kivy.require('1.10.0')

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout

class SayThis(BoxLayout):
    pass
    
class SayThisApp(App):
    def build(self):
        return SayThis()

if __name__ == '__main__':
    SayThisApp().run()

```
and

.ky file:

```python
#:kivy 1.10.0

<SayThis>:
    orientation: 'vertical'
    button_font_size: '30sp'
    Label:
        text: 'Say This!'
        font_size: '45sp'
        size_hint: 1, None
        height: self.texture_size[1]
    TextInput:
        text: 'Hello, world!'
        font_size: str(font_slider.value) + 'sp'
    Slider:
        id: font_slider
        orientation: 'horizontal'
        min: 1
        max: 100
        value: 15
        size_hint: 1, None
    BoxLayout:
        orientation: 'horizontal'
        size_hint: 1, None
        height: sayit_button.height
        Button:
            id: sayit_button
            text: 'Say it!'
            font_size: root.button_font_size
            size_hint: 1, None
            height: self.texture_size[1]
        Button:
            text: 'Clear'
            size_hint: 1, None
            font_size: root.button_font_size
            height: self.texture_size[1]

```

**Comment by pythonic64** [comment]
Run your code on Windows 10 and Python 2.7.13. Every widget is drawn correctly, so this seems a problem with your OS settings.

**Comment by germn** [comment]
Can't reproduce on Windows 10, Python 3.6.2 also:

![](https://i.imgur.com/tHiMOFa.png)

Only guess I have: try to install latest dev (1.10.1) Kivy version [from here](https://kivy.org/downloads/appveyor/kivy/) and see if error remain.

**Comment by moonriviere** [comment]
@germn after updating to 1.10.1 via your link, i still get the cropping issue on my computer.

**Comment by KeyWeeUsr** [comment]
Can't reproduce, but I'd look into [Environment](https://kivy.org/docs/guide/environment.html#metrics) and check how different [scaling](https://blogs.windows.com/windowsexperience/2013/07/15/windows-8-1-dpi-scaling-enhancements/) behaves for you.

**Comment by MPW-waters** [comment]
I'm seeing the same symptoms with Python v3.6.3, Kivy 1.10.0 on Windows 10. Tried setting the scaling to 100%, but that did not fix.

**Comment by mmasiuk** [comment]
Does anybody find the solution for this issue?
I'm observing same behavior for:
Win: 7
Python: 3.7.1
Kivy: 1.10.1
Provider: sdl2
I've tried all backend: angle, glew, sdl2

**Comment by matham** [comment]
It's most likely a driver issue as explained here https://github.com/kivy/kivy/issues/5542.
