### ISSUE TITLE
eglibc has no getconf command

### ISSUE THREAD

**Issue by cedricp** [kivy/kivy#5430]
Hi,
At fist, I wanted to say thank you for this great framework. Really love it !
I'm using Openbricks to make my own RaspberryPi distro, using eglibc. The problem here is that eglibc does not provide 'getconf' binary used by _probesysfs.py_. I was wondering if there's no other way to get long's bit size.
I downloaded getconf.c from gnu-libc and compiled it for the moment, so, fixed for me.

**Comment by cedricp** [comment]
My bad, getconf was not installed by the toolchain.

**Comment by KeyWeeUsr** [comment]
ref #5727
