### ISSUE TITLE
Kivy fails to build using cython 0.27.1

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [kivy/kivy#5432]
### Versions

* Python: 3.6.2
* OS: Arch linux 
* Kivy: 1.10.0
* Kivy installation method: buildozer

### Description

I was trying to build an apk using buildozer. Using the latest cython 0.27.1 throws the following error. It can be fixed by downgrading cython to 0.25.2 work as well. The problem is that pip and my OS always want to upgrade cython. 

### Code and Logs

`

[INFO]:    -> running cython ./kivy/graphics/svg.pyx

Exception in thread background thread for pid 4272:                                                                                                                                          
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/cython ./kivy/graphics/svg.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
                end = time()
                Logger.debug("Svg: Loaded {} in {:.2f}s".format(filename, end - start))
            finally:
                fd.close()

    cdef void reload(self) except *:
        ^
------------------------------------------------------------

kivy/graphics/svg.pyx:469:9: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
        cpdef flag_update(self, int do_parent=?, list _instrs=?)
    ELSE:
        cpdef flag_update(self, int do_parent=?)
    cdef void flag_update_done(self)
    cdef void set_parent(self, Instruction parent)
    cdef void reload(self)
                   ^
------------------------------------------------------------

kivy/graphics/instructions.pxd:36:20: Previous declaration is here

  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 916, in <module>
    main()
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 913, in main
    ToolchainCL()
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 514, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 192, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/build.py", line 572, in build_recipes
    recipe.build_arch(arch)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 975, in build_arch
    self.build_cython_components(arch)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 1010, in build_cython_components
    self.cythonize_build(env=env)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/kivy/__init__.py", line 18, in cythonize_build
    super(KivyRecipe, self).cythonize_build(env, build_dir=build_dir)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 1055, in cythonize_build
    self.cythonize_file(env, build_dir, join(root, filename))
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 1046, in cythonize_file
    shprint(cython_command, filename, *self.cython_args, _env=cyenv)
  File "/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/python-for-android-master/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/usr/lib/python3.6/site-packages/sh.py", line 720, in next
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/cython ./kivy/graphics/svg.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
                end = time()
                Logger.debug("Svg: Loaded {} in {:.2f}s".format(filename, end - start))
            finally:
                fd.close()

    cdef void reload(self) except *:
        ^
------------------------------------------------------------

kivy/graphics/svg.pyx:469:9: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
        cpdef flag_update(self, int do_parent=?, list _instrs=?)
    ELSE:
        cpdef flag_update(self, int do_parent=?)
    cdef void flag_update_done(self)
    cdef void set_parent(self, Instruction parent)
    cdef void reload(self)
                   ^
------------------------------------------------------------

kivy/graphics/instructions.pxd:36:20: Previous declaration is here

  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=kivyCalc --bootstrap=sdl2 --requirements=kivy,python3crystax==3.6 --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/l33tlinuxh4x0r/code/p4a/kivyCalc/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

`

**Comment by l33tlinuxh4x0r** [comment]
This problem is also present on the master branch of kivy.

**Comment by KeyWeeUsr** [comment]
Could you try with the #5406 changes if it fixes the issue?

**Comment by l33tlinuxh4x0r** [comment]
How do I tell buildozer to do that?

**Comment by KeyWeeUsr** [comment]
@l33tlinuxh4x0r Check your spec file and find [this line](https://github.com/kivy/buildozer/blob/8f3f1bc3e92f78adc1319f0e97b8003c9c932c39/buildozer/default.spec#L43) about custom source folders for recipes. Then clone the branch:

```
git clone https://github.com/KeyWeeUsr/kivy
git checkout -b scoder-patch-1 --track origin/scoder-patch-1
```

If the cloning proceeds successfully, set the value in spec file to point to the repository folder. It should pick it up. Be careful to check if you get the correct version of Kivy (i.e. if you really get the branch and not the cached thing). Add e.g. a simple `print('-+' * 50)` at the beginning of a `setup.py` in the branch before running buildozer and don't forget to run buildozer with `log_level=2`.

**Comment by l33tlinuxh4x0r** [comment]
I just upgraded my cython to 0.27.1 then edited my buildozer.spec to point to the directory where I ran the commands that you posted.
```
git clone https://github.com/KeyWeeUsr/kivy
git checkout -b scoder-patch-1 --track origin/scoder-patch-1
```
Then I ran `buildozer android clean` followed by a `buildozer android debug` and my apk built fine using the latest cython and kivy. Works great! Any ETA on when this will be merged with master?

**Comment by KeyWeeUsr** [comment]
Perfect, glad to hear it succeeded! I'll bump the PR and if no one says anything against, I'll merge. It seems to work fine anyway. :)

**Comment by l33tlinuxh4x0r** [comment]
Thanks!!!

**Comment by pkemarco** [comment]
Hey guys. Please I have the same problem. Can you explain me it please ? I am a beginner. Thanks.

**Comment by markfink** [comment]
same here using cython 0.27.3

**Comment by thomasdeneux** [comment]
Hello, I do have the same problem, but not using buildozer. I am not sure how to use the answer above to solve my own problem. Thanks for any help!

- python3.6
- ubuntu 16.04 LTS
- cython 0.27.3

`sudo pip3 install kivy`

...
gcc -pthread -shared build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/graphics/tesselator.o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/lib/libtess2/Source/bucketalloc.o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/lib/libtess2/Source/dict.o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/lib/libtess2/Source/geom.o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/lib/libtess2/Source/mesh.o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/lib/libtess2/Source/priorityq.o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/lib/libtess2/Source/sweep.o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/lib/libtess2/Source/tess.o -o build/lib.linux-x86_64-3.6/kivy/graphics/tesselator.cpython-36m-x86_64-linux-gnu.so -lm
    cythoning /tmp/pip-build-lywvd9gz/kivy/kivy/graphics/svg.pyx to /tmp/pip-build-lywvd9gz/kivy/kivy/graphics/svg.c
    
     Error compiling Cython file:
     ------------------------------------------------------------
     ...
                     end = time()
                     Logger.debug("Svg: Loaded {} in {:.2f}s".format(filename, end - start))
                 finally:
                     fd.close()
    
         cdef void reload(self) except *:
             ^
     ------------------------------------------------------------
    
     kivy/graphics/svg.pyx:469:9: Signature not compatible with previous declaration
    
     Error compiling Cython file:
     ------------------------------------------------------------
     ...
             cpdef flag_update(self, int do_parent=?, list _instrs=?)
         ELSE:
             cpdef flag_update(self, int do_parent=?)
         cdef void flag_update_done(self)
         cdef void set_parent(self, Instruction parent)
         cdef void reload(self)
                        ^
     ------------------------------------------------------------
    
     kivy/graphics/instructions.pxd:36:20: Previous declaration is here
    building 'kivy.graphics.svg' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-build-lywvd9gz/kivy/kivy/include -I/tmp/pip-build-lywvd9gz/kivy/kivy/include -I/usr/local/include/python3.6m -c /tmp/pip-build-lywvd9gz/kivy/kivy/graphics/svg.c -o build/temp.linux-x86_64-3.6/tmp/pip-build-lywvd9gz/kivy/kivy/graphics/svg.o
    /tmp/pip-build-lywvd9gz/kivy/kivy/graphics/svg.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
     error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lywvd9gz/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1g3da8y7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lywvd9gz/kivy/

**Comment by brezniczky** [comment]
I had the same issue ... it's not the most correct approach I'm sure and I admit I'm not really knowledgeable about the background, but in a referenced issue something similar to downgrading Cython to 0.26.1 was mentioned. I tried it and it did the job, so the commands:

pip install cython==0.26.1
pip install kivy

may hopefully help anyone bumping into this one in the near future.

**Comment by lszyba1** [comment]
Confirming that above fixes the Debian Stable installation under python3

```
#Install common dependencies:
#https://kivy.org/docs/installation/installation-linux.html#common-dependencies
#Then 

virtualenv -p python3 env_py3
source ./env_py3/bin/activate
pip install cython==0.26.1
pip install kivy

```

**Comment by ChristianLeininger** [comment]
it also worked for me 
Thank you very much

**Comment by danieltanfh95** [comment]
Confirming that using 0.26.1 fixes for ubuntu 16.04

**Comment by vanschelven** [comment]
I'm experiencing the exact same problem using

* kivy 1.10.0
* Cython 0.28.2

Quite unfortunate, as Kivy 1.10.0 is the latest version of Kivy and has been for a year.

```
kivy/graphics/svg.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^~~~~
 warning: kivy/graphics/common.pxi:9:4: 'const_char_ptr' redeclared
 warning: kivy/graphics/common.pxi:23:4: 'size_t' redeclared

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
                 end = time()
                 Logger.debug("Svg: Loaded {} in {:.2f}s".format(filename, end - start))
             finally:
                 fd.close()

     cdef void reload(self) except *:
         ^
 ------------------------------------------------------------

 kivy/graphics/svg.pyx:469:9: Signature not compatible with previous declaration

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
         cpdef flag_update(self, int do_parent=?, list _instrs=?)
     ELSE:
         cpdef flag_update(self, int do_parent=?)
     cdef void flag_update_done(self)
     cdef void set_parent(self, Instruction parent)
     cdef void reload(self)
                    ^
 ------------------------------------------------------------

 kivy/graphics/instructions.pxd:36:20: Previous declaration is here
 error: command 'gcc' failed with exit status 1
```

**Comment by kuzeyron** [comment]
@vanschelven Try downgrading your Cython with: `pip install cython==0.25.2`.
This issue should be resolved in the next release of Kivy.

**Comment by vanschelven** [comment]
@kuzeyron downgrading won't really work for me; I'm trying to get kivy installed in an environment that requires cython 0.28.2 for other reasons.

Any ETA on the new release of Kivy?

**Comment by kuzeyron** [comment]
Usually you need to try many versions of the Cython before you hit Jackpot..
Next release should be soon! My guess, under a month until the release. But the devs are working hard!

**Comment by tshirtman** [comment]
@vanschelven please try with kivy master, it's stable, and has many bug solved compared to latest release, most of the work needed for release is not about code now.
