### ISSUE TITLE
Kivy RecycleView multiselect=False forbids empty selection

### ISSUE THREAD

**Issue by ionakanaAnalu** [kivy/kivy#5436]
### Versions

* Python: 2.7
* OS: OSX 10.11
* Kivy: 1.10
* Kivy installation method: pip

I have a Kivy program that used ListViews, and when the selection changed, I would take the selection, remove it from the ListView, and "convert" it into a Scatter. I'm trying to replicate this in Kivy 1.10 with RecycleViews, but I've noticed a glaring problem: setting ``multiselect: False`` in the ``SelectableRecycleBoxLayout`` of the ``basic_data.py`` example prevents having an empty selection. So, for example, when running ``basic_data.py`` with no changes, I can click on an element in the RecycleView to select it, and then click it again to deselect it. However, if I change ``multiselect: True`` to ``multiselect: False``, then when I click on the element to deselect it, it gets automatically reselected. This seems like an error, and I'd like to have a way of allowing the selection to be empty.

**Comment by dessant** [comment]
https://kivy.org/docs/api-kivy.uix.behaviors.compoundselection.html#kivy.uix.behaviors.compoundselection.CompoundSelectionBehavior.touch_deselect_last
