### ISSUE TITLE
Chain more than 2 animations doesn't work

### ISSUE THREAD

**Issue by 20Tauri** [kivy/kivy#5443]
### Versions

* Python: 3.4
* OS: Vista
* Kivy: 1.10
* Kivy installation method: pip

### Description

When I chain 3 (or more) animations, I've got an exception raised in "animate.py (see below)

### Code and Logs

```python
    line 270, in have_properties_to_animate
    if props and props['properties']:
    TypeError: 'bool' object is not subscriptable
```

This is caused by
```
        self._widgets[widget.uid] = True
```

I suggest to override method "have_properties_to_animate()" for both Sequence and Parallel

```
    def have_properties_to_animate(self, widget):
        return (self.anim1.have_properties_to_animate(widget) or
                self.anim2.have_properties_to_animate(widget) )
```

**Comment by dessant** [comment]
Please also share a runnable example.

**Comment by 20Tauri** [comment]
The most trivial one is:

```python
from kivy.animation import Animation, AnimationTransition
from kivy.uix.widget import Widget

w = Widget()
anim = Animation(size_hint_y=1, t="in_circ", duration=0.5)
anim += Animation(size_hint_y=0, t="out_circ", duration=1.2)
anim += Animation(size_hint_y=0.5, t="out_circ", duration=1.2)
anim.start(w)
anim.have_properties_to_animate(w)
```

**Comment by gottadiveintopython** [comment]
@20Tauri 
I think you should create a PullRequest.
Your code(have_properties_to_animate()) seems good for me.


(This is not related to the issue) I'm a bit curious about [animated_properties](https://github.com/kivy/kivy/blob/master/kivy/animation.py#L154).

```python3
Animation(x=100).animated_properties  # => {'x': 100}
(Animation(x=100) + Animation(x=0)).animated_properties  # => {}
(Animation(x=100) & Animation(x=0)).animated_properties  # => {}
```
But it probabely fine as it is.

**Comment by 20Tauri** [comment]
Still not work with 1.11, please integrate the @gottadiveintopython 's fixes (https://github.com/kivy/kivy/pull/5926)
