### ISSUE TITLE
"ImportError: cannot import name bcm" error with running basic kivy app in ubuntu

### ISSUE THREAD

**Issue by Taboen** [kivy/kivy#5444]
I've followed the installation steps for kivy. I'm using python3, on ubuntu.

The code:

```
from kivy.app import App
App().run()
```

I'm getting this error:

> [CRITICAL] [Window      ] Unable to find any valuable Window provider.
> egl_rpi - ImportError: cannot import name 'bcm'
>   File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
>     fromlist=[modulename], level=0)
>   File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
>     from kivy.lib.vidcore_lite import bcm, egl
> 

I have the latest kivy: 1.10.0-0~stable.

It's the same as mentioned in [this issue](https://github.com/kivy/kivy/issues/4085), which was closed and requested a new issue be created for 1.10.

**Comment by IQYottabit** [comment]
I had the similar issue and later I followed the steps to install the Kivy from this link: https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2 that resolved the problem.
