### ISSUE TITLE
Starting Kivy service on bootup (Android)

### ISSUE THREAD

**Issue by saband** [kivy/kivy#5447]
### Versions

* Python: 2.7
* OS: Android
* Kivy: 1.10.0

### Description

I've read [this article on wiki](https://github.com/kivy/kivy/wiki/Starting-Kivy-service-on-bootup-(Android)) and tried to make this task. I want to note that the article needs to change "org.renpy.android.PythonActivity" to "org.kivy.android.PythonActivity" because "org.renpy" is deprecated but it is not the main problem. The main problem is that code from the article starts _app_ but not _service_. So I've tried change it for service but it doesn't work (see my code below). Can you please update this article with work method to start a Kivy service on bootup? I understand that it is not a Kivy bug but there is no way to comment wiki article.

### Code and Logs

```
package net.saband.myapp;

import android.content.BroadcastReceiver;
import android.content.Intent;
import android.content.Context;
import net.saband.myapp.ServiceMyservice;

public class MyBroadcastReceiver extends BroadcastReceiver {
    public void onReceive(Context context, Intent intent) {
        Intent ix = new Intent(context, ServiceMyservice.class);
        ix.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startService(ix);
    }
}
```
```
10-21 19:16:44.784  1513  1569 I ActivityManager: Start proc 6334:net.saband.myapp:service_myservice/u0a116 for service net.saband.myapp/.ServiceMyservice
10-21 19:16:44.786  6334  6334 I art     : Late-enabling -Xcheck:jni
10-21 19:16:44.885  6334  6334 D AndroidRuntime: Shutting down VM
10-21 19:16:44.888  6334  6334 E AndroidRuntime: FATAL EXCEPTION: main
10-21 19:16:44.888  6334  6334 E AndroidRuntime: Process: net.saband.myapp:service_myservice, PID: 6334
10-21 19:16:44.888  6334  6334 E AndroidRuntime: Theme: themes:{}
10-21 19:16:44.888  6334  6334 E AndroidRuntime: java.lang.RuntimeException: Unable to start service net.saband.myapp.ServiceMyservice@8c96929 with Intent { cmp=net.saband.myapp/.ServiceMyservice }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
```

**Comment by dessant** [comment]
As mentioned in the issue template, please use the channels dedicated for support questions: https://github.com/kivy/kivy#support.
