### ISSUE TITLE
Kivy installation problem MacOS 10.12.6 & Python 3.6.1

### ISSUE THREAD

**Issue by LucaAngioloni** [kivy/kivy#5462]
### Versions

* Python: 3.6.1
* OS: MacOS 10.12.6
* Kivy: 1.10.0
* Kivy installation method: pip install kivy

I'm having problems installing kivy on MacOS. I followed the instructions provided on the website, using brew and pip. I tried many versions of Cython and Kivy combined but none gave results.

I'll provide all the informations about my system: 

- OS: MacOS 10.12.6 
- Python: 3.6 installed via brew 
- Cython 0.26.1 (but I tried 0.25, 0.26, 0.27.2)
- setuptools: 36.6.0 
- pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer installed via brew 
- pkg-config: 0.29.2 
- sdl2: 2.0.7 
- sdl2_image: 2.0.2 
- sdl2_ttf: 2.0.14 
- sdl2_mixer: 2.0.2 
- gstreamer: 1.12.3

This is a gist containing the error: https://gist.github.com/kivydevman/5caecf80c4a2c0062d91cc3b48aef565

Also I tried installing kivy 1.10.0 and dev edition 1.10.1 from GitHub.

I had a working installation on the same system, using Python 3.5 , Cython 0.26.1 and Kivy 1.10.0 .
Also possibly brew formulas versions could have been different at that time (20 days ago) but no more than 1 month old.

**Comment by LucaAngioloni** [comment]
This is a gist from --verbose pip installation: https://gist.github.com/LucaAngioloni/5f721643c2100fba888cb882d9f15c74

With Cython 0.26 and Kivy 1.10.0

**Comment by lordjabez** [comment]
This is the same problem I encountered here: https://github.com/kivy/kivy/issues/5457.

**Comment by KeyWeeUsr** [comment]
Yeah, seems like that. Closing in favor of #5457. Try to use the PR linked in the @lordjabez issue and see if it helps. :)
