### ISSUE TITLE
document error in stencil_instructions

### ISSUE THREAD

**Issue by xinmingzhang** [kivy/kivy#5464]
### Versions

* Python: python 2, 3
* OS: Windows
* Kivy:1.10
* Kivy installation method:pip

### Description

I am not sure it is expression error here, https://github.com/kivy/kivy/blob/master/kivy/graphics/stencil_instructions.pyx#L16-L48

I am wondering PHASE 3 here. My understanding is that PHASE 1 is just PHASE 2's mask, PHASE 1 has no relationship with PHASE 3, because after StencilUnUse, PHASE1 is no longer take effect.

so, the next description make me lost

https://github.com/kivy/kivy/blob/master/kivy/graphics/stencil_instructions.pyx#L51-L55

it is said that 

"Drawing in PHASE 1 and PHASE 3 must not collide or you will get unexpected results"

how to understand it, and the following example makes more confusion, 

https://github.com/kivy/kivy/blob/master/kivy/graphics/stencil_instructions.pyx#L67-L92

in this example, PHASE 1 is the same with PHASE 3, it is contradict with the saying "must not collide" and the comments said

"# you must redraw the stencil mask to remove it".

so I am total lost here. I am not sure there is document error here, or I just missed something

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by tshirtman** [comment]
This indeed is wrong and confusing.

To avoid weird artifacts, it's indeed *necessary* for the instructions in the "phase 3" here, to exactly match the ones in phase 1. and nothing in phase 3 will be drawn directly to screen until phase 4.

**Comment by tshirtman** [comment]
pushed a change to fix that, thanks for reporting!

**Comment by tshirtman** [comment]
pushed a change to fix that, thanks for reporting!
