### ISSUE TITLE
 ScrollView: Value could not convert string to float: 'yes'

### ISSUE THREAD

**Issue by sempert** [kivy/kivy#5465]
### Versions
* Python: v3.5.2 (default, Sep 14 2017, 22:51:06) 
* OS: Linux Mint 18.2 Sonya, Kernel 4.11.0-14-generic
* Kivy: v1.10.0
* Kivy installation method: Via PyCharm, thats why I haven't reproduced the problem with the latest development version of kivy. 
### Description

I am using ScrollView in on-page app. As you can see in the code & log below, the simple the usage of ScrollView throws a ValueError, which shows up in the kivy messages, but seems to be ignored.

I ignored it too at first, but now (with very much more code in the app) I am running into troubles with my ScrollView (strange behaviour for which I might post an issue as soon as I better understand what is going on). Now I am wondering if this ignored exception is as harmless as thought. 

Usually I run the app from PyCharm, but the ValueError appears when I run the app outside PyCharm too.

### Code and Logs

https://gist.github.com/sempert/296690dbda811e19e44ff3886e392f2e

**Comment by Varbin** [comment]
I think it should be `1` instead of `"yes"`. Working code below:
```
from kivy.app import App
from kivy.uix.scrollview import ScrollView


class BugApp(App):
    def build(self):
        return ScrollView(scroll_y=1)


if __name__ == '__main__':
    BugApp().run()

```

**Comment by KeyWeeUsr** [comment]
>Y scrolling value, between 0 and 1. If 0, the content’s bottom side will touch the bottom side of the ScrollView. If 1, the content’s top side will touch the top side.

>This property is controled by ScrollView only if do_scroll_y is True.

→ [source](https://kivy.org/docs/api-kivy.uix.scrollview.html#kivy.uix.scrollview.ScrollView.scroll_y) 🍡
