### ISSUE TITLE
Install on OSX failing

### ISSUE THREAD

**Issue by spacechimplives** [kivy/kivy#5468]
/usr/local/include/SDL2/SDL_mixer.h:80:5: note: 'MIX_INIT_MOD' declared here
        MIX_INIT_MOD    = 0x00000002,
        ^
    /private/var/folders/kp/c_y1xl7j4218nt4lg1k5wwd80000gn/T/pip-build-7qxjuhet/kivy/kivy/core/audio/audio_sdl2.c:1742:83: error: use of undeclared identifier 'MIX_INIT_FLUIDSYNTH'
      __pyx_v_want_flags = (__pyx_v_want_flags | ((MIX_INIT_MOD | MIX_INIT_MODPLUG) | MIX_INIT_FLUIDSYNTH));
                                                                                      ^
    /private/var/folders/kp/c_y1xl7j4218nt4lg1k5wwd80000gn/T/pip-build-7qxjuhet/kivy/kivy/core/audio/audio_sdl2.c:5262:69: error: use of undeclared identifier 'MIX_INIT_MODPLUG'; did you mean 'MIX_INIT_MOD'?
      __pyx_t_2 = ((__pyx_v_4kivy_4core_5audio_10audio_sdl2_mix_flags & MIX_INIT_MODPLUG) != 0);
                                                                        ^~~~~~~~~~~~~~~~
                                                                        MIX_INIT_MOD
    /usr/local/include/SDL2/SDL_mixer.h:80:5: note: 'MIX_INIT_MOD' declared here
        MIX_INIT_MOD    = 0x00000002,
        ^
    3 errors generated.
     error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kp/c_y1xl7j4218nt4lg1k5wwd80000gn/T/pip-build-7qxjuhet/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/kp/c_y1xl7j4218nt4lg1k5wwd80000gn/T/pip-cu1_b_s0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kp/c_y1xl7j4218nt4lg1k5wwd80000gn/T/pip-build-7qxjuhet/kivy/

### Versions

* Python: 3.6
* OS: OSX 10.12
* Kivy:
* Kivy installation method:

### Description

I'm trying to install Kivy on OSX  at first I was trying to install in a venv, and I thought that was the issue.  Now I'm trying to install globally and it's failing as well.

**Comment by spacechimplives** [comment]
nvm duplicate of https://github.com/kivy/kivy/issues/5457

installed development version using 

pip3 install https://github.com/kivy/kivy/archive/master.zip

And it built

**Comment by bazilevs31** [comment]
Worked for me for OSX High Sierra and Python 3.6 anaconda dist. as well. Good stuff! After 4 weeks of using the binary, I can breathe freely. Thank you so much!
