### ISSUE TITLE
TextInput selection disappearing on <enter> key

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5469]
### Versions

* Python: 3.5
* OS: Windows 8.1
* Kivy: master
* Kivy installation method: wheel

### Description

1. Write some text e.g. "somelongtext"
2. press `<enter>`
3. write some text again, preferably something short e.g. "text"
4. press `<enter>`
5. `<shift> + <up>` (aka select the text)
6. press 7x `<enter>` and look at the selection disappearing

### Code and Logs

```python
from kivy.app import runTouchApp
from kivy.uix.textinput import TextInput
runTouchApp(TextInput())
```

**Comment by BoyanH** [comment]
What is the desired functionality? I would rather expect the selected text to be replaced with a new line when pressing enter

**Comment by KeyWeeUsr** [comment]
@BoyanH yeah, that should be the behavior. More precisely the contents of the selection should completely disappear and then the new line inserted at the end of the previous selection on the first enter key and then 6 times new line.

Try with multiple simple text editors and you should get the result I'm talking about.

**Comment by emomicrowave** [comment]
@BoyanH and I looked it over and we found the problem. There wasn't any check for what happens if the `enter` key is pressed, but when there is a text selection. I made a pull request with the changes.

**Comment by KeyWeeUsr** [comment]
A test for the fix would be very nice to see. I see some other changes mentioned in the PR, so perhaps adding the test for the whole rewritten selection behavior might be better.

What error did you get? I can run the test case with this simple call:

    python test_uix_textinput.py

if it's about where to place the test, well since it works with the keys, I'd add it under the already existing `TextInputGraphicTest.test_text_validate()` which might even inspire you (or perhaps you will have a better approach). :)

**Comment by emomicrowave** [comment]
That's the error I get when I run the file this way.

```
  File "test_uix_textinput.py", line 48, in test_text_validate
     self.assertTrue(ti.text_validate_unfocus)
 AttributeError: 'TextInput' object has no attribute 'text_validate_unfocus'
```

**Comment by KeyWeeUsr** [comment]
That just means you probably don't have up-to-date version of Kivy, because that attribute is just another Kivy property here:

https://github.com/kivy/kivy/blob/21a68562be135338c6aaef0f3a3f6641f4473af4/kivy/uix/textinput.py#L2488

The test runs fine on Travis, Appveyor and locally with the latest master, therefore I don't think it's some weird bug with the graphic unittest.

**Comment by emomicrowave** [comment]
Turned out I had forgotten to properly compile the project. 
```
python setup.py build_ext --inplace -f
```
That or I installing `nose` and running `make test` fixed it. Now the test runs fine. Sorry about the trouble.

**Comment by KeyWeeUsr** [comment]
No problem, glad to help anyone who's interested in testing. In the end, it should mean less troubles for us in the future :)
