### ISSUE TITLE
TextInputs don't work with android onscreen keyboard Minuum

### ISSUE THREAD

**Issue by randombyte-developer** [kivy/kivy#5471]
### Code
https://gist.github.com/randombyte-developer/5c063bc07042b7a681ba45e55eae2f27
### Environment
Running on android, regardless which android version and kivy version.
Using this keyboard: https://play.google.com/store/apps/details?id=com.whirlscape.minuumfree&hl=de

### Expectations
Being able to edit the TextInput, on android.

### Result
Not being able to edit the TextInput, on android. The text set in the code still displays but it is not editable by the user.

### Workaround
Don't use Minuum in combination with kivy apps.

Not sure if Minuum or kivy behave wrongly.

**Comment by Fogapod** [comment]
May be a ref: https://github.com/kivy/python-for-android/issues/1102
How did you build apk?

**Comment by randombyte-developer** [comment]
I built it with buildozer. I should test other kivy apps with the minuum keyboard. Are there any example apps already built?

**Comment by tshirtman** [comment]
I think it works better now that text_edit events are supported, issues that remains are related to the relationship between edit and insert events #7415
