### ISSUE TITLE
Kivy error - Unable permissions!?!

### ISSUE THREAD

**Issue by victorpenna** [kivy/kivy#5483]
### Versions

* Python: 3.5
* OS: Linux/Ubuntu 16.04
* Kivy: 1.10 Garden
* Kivy installation method: virtualenvs - pip install kivy

### Description

//  Pyrcharm don't launcher main.py, with layout function

### Code and Logs
Code:
```
# coding = utf-8

from kivy.app import App
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button
from kivy.core.window import Window

def click():
    print (ed.text)

def build():

    layout = FloatLayout()

    ed = TextInput(text="USER.COM")
    global ed
    ed.size_hint = None, None
    ed.height = 300
    ed.width = 400
    ed.y = 60
    ed.x = 250

    bt = Button(text="Click Me")
    bt.size_hint = None, None
    bt.height = 50
    bt.width = 200
    bt.y = 150
    bt.x = 170
    bt.size_hint = None, None
    bt.on_press = click()

    layout.add_widget(ed)
    layout.add_widget(bt)

    return layout


Window.size=600,600
open= App()
open.title = "USER_FREE_AS"
open.buid=build
open.run()
```
Log:

```
/home/user/.virtualenvs/k35/bin/python /home/user/Projetos/Python/kivy/source/tela_layout/main.py
/home/user/Projetos/Python/kivy/source/tela_layout/main.py:18: SyntaxWarning: name 'ed' is assigned to before global declaration
  global ed
[INFO   ] [Logger      ] Record log in /home/victorpenna/.kivy/logs/kivy_17-11-13_11.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 17.3.0-rc2 - padoka PPA'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event8
[INFO   ] [MTD         ] Read event from </dev/input/event8>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event13
[INFO   ] [MTD         ] Read event from </dev/input/event13>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event14
[INFO   ] [MTD         ] Read event from </dev/input/event14
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event8". Please ensure you have the appropriate permissions.
[WARNING] [MTD         ] Unable to open device "/dev/input/event13". Please ensure you have the appropriate permissions.
[WARNING] [MTD         ] Unable to open device "/dev/input/event14". Please ensure you have the appropriate permissions.
[INFO   ] [Base        ] Leaving application in progress...

Process finished with exit code 0
```

I'm trying to study and work with layout function. But I was not successful, and without it I could normally export my other tests. How should I solve this?

 

```

**Comment by pammelang** [comment]
hi! i'm having the same issue! I've changed the kivy [input] configs in ~/.kivy/config.ini to include provider=mtdev as well, but I'm getting the MTD permissions error as well.

**Comment by speedhs** [comment]
did you guys have any luck with this issue?can you walk me through it if u have

**Comment by FenX999** [comment]
under linux the events are related to all input devices on your computer you can list them with this command :

cat /proc/bus/input/devices  (source : https://thehackerdiary.wordpress.com/2017/04/21/exploring-devinput-1/ )

I had an error with kivy telling me : 
[WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

after running the command I've found that event 4 is related to my TouchPad wich I'm not using ( because wireless mouse installed)
here my resuts : 
I: Bus=0011 Vendor=0002 Product=0007 Version=01b1
N: Name="SynPS/2 Synaptics TouchPad"
P: Phys=isa0060/serio4/input0
S: Sysfs=/devices/platform/i8042/serio4/input/input11
U: Uniq=
H: Handlers=mouse0 event4 
B: PROP=9
B: EV=b
B: KEY=6420 30000 0 0 0 0
B: ABS=260800011000003

If that error does not interfere with running and compiling my code ( not sure yet ) I've decided to ignore it until it becomes a problem.

hope that help

**Comment by travisengh** [comment]
I just want to add that I am also receiving this error.

**Comment by kwccoin** [comment]
trying the documentation pdf 16.2 and 16.5 and same error, under ubuntu

"Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions"

Not sure the resolution.  One said in stackoverflow using root which I do not want to.

BTW I do not have this issue under macOS and hence must be something to do with ubuntu ... any help.

**Comment by tounf** [comment]
Would also like to know a solution. I tried to give permission via the steps given here: https://github.com/kivy/kivy/blob/d1ec864c892ef5cb67e016ac6eeac11f2afe0b86/doc/sources/installation/installation-linux.rst
But nothing works.

**Comment by BlazarKnight** [comment]
same problem here

**Comment by ElliotGarbus** [comment]
@BlazarKnight 
The [Kivy Discord Server](https://chat.kivy.org/) allows you to chat with people in real-time and share code snippets. There are several channels marked for support (if you aren't sure which to use, try #support0).

There are also independent communities on [StackOverflow](https://stackoverflow.com/questions/tagged/kivy) and [Reddit](https://www.reddit.com/r/kivy/) that accept Kivy-related support requests.
