### ISSUE TITLE
Textinput wrong cursor movement on finished selection 

### ISSUE THREAD

**Issue by BoyanH** [kivy/kivy#5490]
### Versions

* Python: 3.5
* OS: Antergos (Arch Linux based)
* Kivy: master
* Kivy installation method: pip

### Description

1. Write some text e.g. "somelongtext"
1. press <cursor_left> (left arrow)
1. press and hold <shift>
1. press 3x <cursor_left> (left arrow)
1. release <shift>
1. press <cursor_right> (right arrow)

You will see, that the selection gets cleared and the cursor is moved one position to the right.

Actually the cursor should be placed at the other (right) side of the selection and the selection
should then be cleared. At least this is the common behavior of all text editors.

### Code and Logs

```Python
from kivy.app import runTouchApp
from kivy.uix.textinput import TextInput
runTouchApp(TextInput())
```

**Comment by KeyWeeUsr** [comment]
Closed by https://github.com/kivy/kivy/commit/0456eff89bccf93fa6bd8aada318246082f1b8cc
