### ISSUE TITLE
Audio gone on iOS after Siri or phone call

### ISSUE THREAD

**Issue by sastels** [kivy/kivy#5501]
### Versions

* Python: 2.7.1
* OS: iOS 11
* Kivy: 1.10.0
* Kivy installation method: kivy-ios, Xcode

### Description

* Build an app for iOS via kivy-ios (for example, kivy/examples/audio)
* Install and run on iPhone. Everything works as expected.
* engage Siri by holding down Home. Cancel Siri.
* Back in Audio app, but now sound doesn't work. Only solution is to force kill Audio app (double tap Home and kill Audio)

Notes:
* If Audio app is minimized before using Siri, no issues.
* `on_pause()` and `on_resume()` are firing when Siri starts / stops (verified by adding logging messages).

From https://stackoverflow.com/questions/10237981/simulating-a-phone-call-interruption-in-the-iphone-simulator:
> 	Phone calls trigger only AppWillResignActive and AppDidBecomeActive. Home button triggers AppWillResignActive then AppDidEnterBackground, on resume AppWillEnterForeground then AppDidBecomeActive. So home button isn't exactly the same.

I note that in https://github.com/kivy/kivy/commit/d9ae83c34360d645d5810b229304be93c063fc40 there was a fix to pause/resume that involved entering background and foreground. No mention of resigning Active or becoming Active. 

### Code and Logs

There were no log messages during Siri start / stop or during the failed attempts to play audio.

Any ideas / where to start / etc? Thanks!!

**Comment by hackalog** [comment]
Possibly related (Upstream, SDL: https://discourse.libsdl.org/t/getting-back-audio-after-phone-call-on-ios-and-sdl-2-0-5/22144).

Though building a newer SDL2 runs into issues introduced by Pull Request #5252

**Comment by sastels** [comment]
It looks like there's a couple issues here:
* kivy-ios is using an old development fork of SDL that has since been merged into SDL proper
* the latest SDL has only partially fixed this problem (engaging Siri works now, phone calls don't)

(another problem noted above: kivy-ios no longer works with kivy master since pull request #5252)

I'm closing this issue here for now, we'll deal with the SDL issues in SDL and kivy-ios.
(see https://github.com/kivy/kivy-ios/issues/274)
