### ISSUE TITLE
Can't remove a RecycleView's item from itself

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#5504]
Some examples of what i mean (from JQuery):

[https://78.media.tumblr.com/tumblr_lhdcnwiEaM1qz4v9x.jpg](https://78.media.tumblr.com/tumblr_lhdcnwiEaM1qz4v9x.jpg)

[http://outbottle.com/wp-content/uploads/2012/08/add_remove_from_dynamic_list.png](http://outbottle.com/wp-content/uploads/2012/08/add_remove_from_dynamic_list.png)

[https://i.pinimg.com/736x/a5/bb/a0/a5bba0bd2aca7dedb84735fd55d2823b--jquery-dom.jpg](https://i.pinimg.com/736x/a5/bb/a0/a5bba0bd2aca7dedb84735fd55d2823b--jquery-dom.jpg)

[https://i.pinimg.com/originals/84/7f/70/847f708d15f301cf3e6b366a5d84ee40.jpg](https://i.pinimg.com/originals/84/7f/70/847f708d15f301cf3e6b366a5d84ee40.jpg)

[http://wasifbaig.com/jquerymobile-editablelistview/images/editable-listview.png](http://wasifbaig.com/jquerymobile-editablelistview/images/editable-listview.png)

Is that possible with Kivy RecycleView?

**Comment by dessant** [comment]
Yes, it should be possible to build.

**Comment by Tungsteno74** [comment]
Thanks *dessant* and sorry for my mistake on posting it here.
