### ISSUE TITLE
"Received a --sdk argument"- Error  while building .apk using buildozer.

### ISSUE THREAD

**Issue by upam00** [kivy/kivy#5513]
Hi! I am having the following error message while converting a simple "hello world" kivy file to .apk file using buildozer. I am using Ubuntu 16.04 LS. Please help.

```
[WARNING]: ERROR: /home/upam/.buildozer/android/platform/apache-ant-1.9.4/bin/ant failed!
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.

Command failed: /usr/bin/python2 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name upamor_app --name 'Upam'"'"'s App' --version 1.0 --package org.test.upamor_app --android_api 19 --sdk 19 --minsdk 9 --private /home/upam/Documents/.buildozer/android/app --permission INTERNET --orientation sensor --window --copy-libs --arch armeabi-v7a --color=always --storage-dir=/home/upam/Documents/.buildozer/android/platform/build

Buildozer failed to execute the last command

The error might be hidden in the log above this error

Please read the full log, and search for it before

raising an issue with buildozer itself.

In case of a bug report, please add a full log with log_level = 2
```

**Comment by inclement** [comment]
Thanks for the report. As the posted text says, please add a pull log with log_level = 2 (you can set this in the buildozer.spec).

**Comment by upam00** [comment]
Hi! Thanks for the reply. I have already set log level=2 in buildozer.spec
file. Would you mine telling a bit more.

**Comment by airatinho** [comment]
Received a --sdk argument, but this argument is deprecated and does nothing.
ERROR: /home/ayrat/PycharmProjects/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/kivy_app__armeabi-v7a/gradlew failed!
