### ISSUE TITLE
Printing while trying to import the APP 

### ISSUE THREAD

**Issue by sskadit** [kivy/kivy#5515]
Image

![screen shot 2017-12-06 at 3 33 52 pm](https://user-images.githubusercontent.com/24460900/33656774-18e35606-da9d-11e7-9670-b4b691e0545a.png)

### Versions

Python 2.7.10
Kivy==1.10.1.dev0
Cython==0.26.1
Kivy-Garden==0.1.4
Mac OSX 
* Kivy installation method: pip install https://github.com/kivy/kivy/archive/master.zip

### Description

I Have Asked in the stackover flow

https://stackoverflow.com/questions/47671606/python-kivy-is-printing-numbers-while-importing-it?noredirect=1#comment82302269_47671606

**Comment by inclement** [comment]
I have no idea what is causing this, it certainly isn't meant to happen, and I can't reproduce it.

Does the same thing happen if you write some kivy code in a file and run that with python?

**Comment by Julian-O** [comment]
It is not happening now. Closing as stale.
