### ISSUE TITLE
weird RecycleView issue

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/kivy#5516]
Hello,
i've added a checkbox in a recycleview viewclass and i've populated it with the following code:

`self.rv.data = [{'uuid':str(uuid4()),'value': ''.join(sample(ascii_lowercase, 6))} for x in range(100)]`

when I select a checkbox the others are also selected in a randomly way.

[This is the full code.](https://gist.github.com/Tungsteno74/c524176aeb4f7f0f7815e52d6554cfc0)

How to fix that?

**Comment by dessant** [comment]
@Tungsteno74, please do not use issues to ask support questions.

**Comment by Tungsteno74** [comment]
I think this is an issue.... this is not a normal behavior.

**Comment by randolfo75** [comment]
Similar problem here, I put a comment in issue #5496
