### ISSUE TITLE
ListProperty's 'remove' does not work as you'd expect

### ISSUE THREAD

**Issue by omermazig** [kivy/kivy#5531]
### Versions

* Python: 3.5.2
* OS: linux
* Kivy: 1.10.0

### Description

I'm trying to remove a value from list and while:

`self.keyboard_listeners.remove(listener)`

Doesn't work, this:

```
i = self.keyboard_listeners.index(listener)
self.keyboard_listeners.pop(i)
```

Works, though it should be only a syntax change. 

Am I missing something? This looks like a bug.

**Comment by Zen-CODE** [comment]
This seem to work fine (see following example). It must be something to do with something else in you code. Please post a full, run-able example demonstrating the issue.
```
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.gridlayout import GridLayout
from kivy.properties import ObjectProperty, ListProperty


class GuiApp(App):
    listeners = ListProperty([])

    def build(self):
        self.listeners = ['bob', 'eric', 'john']
        i = self.listeners.index('eric')
        print('eric at {0}'.format(i))
        self.listeners.pop(i)
        print('list after = {0}'.format(self.listeners))
        return Label(text="helloe")


class Gui(GridLayout):
    grid = ObjectProperty(None)


if __name__ == "__main__":
    GuiApp().run()
```

**Comment by omermazig** [comment]
Never mind I didn't recognized the problem correctly.
