### ISSUE TITLE
OpenGL 1.1

### ISSUE THREAD

**Issue by pkemarco** [kivy/kivy#5536]
Hello. I have the lasted Kivy's version but it doesn't work : it need openGL 2.0 and I have a i3 processeur with an integrated graphical card. What can I do ? I am on windows 10. Thanks.

**Comment by inclement** [comment]
Please post support requests on the [kivy-users mailing list](https://groups.google.com/forum/#!forum/kivy-users). Include all the information you can about what seems to be wrong - what is the problem, why do you think that is the problem, what exactly do the logs say etc.
