### ISSUE TITLE
Windows 10 Program title bar block the kivy interface

### ISSUE THREAD

**Issue by xzhuah** [kivy/kivy#5542]
### Versions

* Python: 3.6.3
* OS: Windows 10, 10.0.16299 N/A Build 16299
* Kivy:  1.10.0
* Kivy installation method: 

		pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
		pip install kivy

### Description

I am running the Example Program KivyCatalog and I find that the program bar block the top part of the kivy program interface. I wrote some my own simple program and this bug appeared every time. 

![](https://i.imgur.com/PAJ4iHV.png)

As you can see in the above image, the menu part is blocked.

What is more, it seems that the screen can't locate the position of my cursor correctly, when I click on one line to select it, the line above it is selected instead.

Please check and fix this bug!

**Comment by dessant** [comment]
It looks as if the root widget would be slightly scaled up.

**Comment by xzhuah** [comment]
I think there is a **scaling problem** there. The big window (with the title bar) and the kivy interface (without the title bar) disagrees with each other. The widget are rendered using the coordinate system of the window which is wrong. However, the mouse events are using the coordinate system of the interface which is correct.  The (0,0) is right at the left bottom corner of the window which is also the left bottom corner of the kivy interface. However, when you goes up, problems emerge. At the top. The widget thought the top refers to the top of the big window, event thought the top refers to the top of the interface.

**Comment by dessant** [comment]
Kivy does not currently handle scaled or high DPI displays on Windows. Is scaling set to more than 100% for your display?

**Comment by xzhuah** [comment]
I never change my setting for display. I think everything is by default

**Comment by xzhuah** [comment]
You may take a look at this: https://msdn.microsoft.com/en-us/library/windows/desktop/ff381403(v=vs.85).aspx
In short Kivy is using Window coordinates instead of client coordinates to render its widget. This caused the problem.

**Comment by matham** [comment]
This happened to me too after some windows update. It worked perfectly before, but then this issue happened and it seemed to happen with older versions of kivy also. So while kivy didn't change afaik, there was some windows change that caused this. And only on very few systems as I think you're only like the third person with this issue.

A kivy workaround is to set in the config
```
resizable = 0
borderless = 1
```

I does cause it to not be resizable and without a border, but that's the only fix it seems. You can see the full IRC discussion when I initially investigated this and it seems it's not an issue with kivy:

```
<tshirtman> qua-non https://github.com/kivy/kivy/blob/master/kivy/core/window/_window_sdl2.pyx#L61 and https://github.com/kivy/kivy/blob/master/kivy/core/window/_window_sdl2.pyx#L608 https://wiki.libsdl.org/SDL_GetWindowSize 
<tshirtman> since you asked about it :)
<tshirtman> matham had this issue yesterday, but another user reported it today in #kivy
<tshirtman> seems the window size is badly computed on windows with highdpi
<qua-non> ah, windows.... that darn thing.... I only tested on OS X
<qua-non> seems I have no choice but to install and test on windows.....
<tshirtman> and i think these links are relevant, though i didn't test anything, just had a look at the code
<qua-non> ok, gimme till tomorrow, downloading windows 10...
<tshirtman> wow
<tshirtman> that's nice, i could check myself at home too, i already have dual boot :)
<tshirtman> jus not when i'm at work :)
<qua-non> windows 10 itself won't take time to download, it's just all the installing and drivers and .....:/
<tshirtman> yeah
<matham> So, I'm on a 4k, here's what I get:
<matham> Window.size
<matham> Out[3]: 
<matham> (800, 600)
<matham> Window._win._get_gl_size()
<matham> Out[5]: 
<matham> (800, 600)
<matham> Window._density
<matham> Out[6]: 
<matham> 1.0
<matham> windows must have changed something in the way it treats kivy. Maybe kivy needs to say that it supports 4k
<matham> kivy worked fine on the same machine a few weeks ago
<qua-non> "kivy worked fine on the same machine a few weeks ago", << lol
<qua-non> now how do we debug that 
<qua-non> time machine...
<tito> I don't think dpi is working with windows at all
<tito> There is a difference between text zoom and dpi
<tito> I think text zoom works, but dpi not
<tito> I have 2 app in 4k in a museum that's what I remember off.
<tito> I mean even on a 4k, density will stay to 1
<matham> this issue though happens for 2.7 and 3.5 and both for master and stable
<matham> even worse, the touch is off by about the titlebar height. But if you look at wm_touch.py, it doesn't use anything sdl for computing the offset
<matham> so it seems like a windows issue. I wonder if we need to tell windows that it is 4k capable
<tito> There is a similar issue on windows in some environment where only the touch is shifted. I never been able to find out as I usually see the issue the day of installation. So far, the fix is shifting Y manually using a post-processing. 
<tito> If you have zoom, can you try to set it to 100% and see if it changes? 
<matham> zoom?
<matham> you mean scatter?
<tito> Nah windows 10 scale
<tito> In screen properties 
<matham> it was a 250 zoom. But changing to 100 didn't fix it
<matham> I even signed out between testing
<tshirtman> i'd still check if the sdl functions for window size report a different value, though :$
<matham> I did and it didn't
<matham> I checked Window._win._get_gl_size()
<matham> it was the 800x600 value
<tshirtman> ok
<matham> https://discourse.libsdl.org/t/wip-windows-high-dpi-support/22446/5
<matham> so... I guess sdl2 doesn't support high dpi screens on windows. The best I could do is SetProcessDpiAwareness. Setting it to PROCESS_PER_MONITOR_DPI_AWARE made kivy display super tiny on the 4k monitor. The other values made it display normal sized. In all cases the window size was identical
<matham> but also, the sizing issues never went away
<matham> I checked on a different older computer and over there gl size and window size is 800x600, wm_touch reports the client area also is 800x400 and the window size including the title bar 816x638. I'm seeing identical results on the 4k machine
<matham> this to me says that everything we do seems correct, except all of a sudden gl is confused and draws under the titlebar because it misscales the drawing area to include the title bar
<matham> this ic clearly a windows gl issue as I found an installtion of kivy that I haven't touched in a long time and had worked before, and it had the same issue
<matham> A simple fix is to subtract the title bar height from the height in glViewport(...)
<dessant> not sure if it helps with the touch issues, but the sizing issues can be fixed by setting some kivy env vars
<dessant> # environ['KIVY_DPI'] = '172'
<dessant> # environ['KIVY_METRICS_DENSITY'] = '1.8'
<matham> The problem is not really with dpi because windows hides the true dpi from kivy it seems
- {Day changed to Wednesday, August 30, 2017}
<tito> matham: https://stackoverflow.com/questions/39253583/window-title-over-lapping-opengl-rendering
<tito> matham: glfw have a function for that: in http://www.glfw.org/docs/latest/window_guide.html
<tito> The above functions work with the size of the client area, but decorated windows typically have title bars and window frames around this rectangle. You can retrieve the extents of these with glfwGetWindowFrameSize.
<tito> https://wiki.libsdl.org/SDL_GetWindowBordersSize
<tito> https://wiki.libsdl.org/SDL_GetWindowSize
<tito> maybe we should first try to change GetWindowSize to GetWindowBordersSize
<tito> maybe that will be fixing stuff
<tito> matham: ^
<tito> there is only 2 reference to change in _window_sdl2.pyx to test
<matham> tito, with regards to SDL_GetWindowBordersSize it says "This function is only supported on X11. ". SDL_GetWindowSize says "Use this function to get the size of a window's client area. " so it should return the client area (which it does)
<matham> I saw the SO one and that led me to look at the sizes
<matham> so the total windows size is 816x638, the client area is 800x600 (doesn't include the bars etc)
<matham> SDL_GetWindowSize returns 800x600, which is correct. in wm_touch.py windows also claims the client area is 800x600. I also measured with a pixel ruler and the drawable area, not including the bars is indeed 800x600
<matham> so when we tell with glviewport that we have 800x600 pixels available, that is correct
<matham> the issue is that gl internally draws over the 816x638 thinking that it is drawing on the 800x600.
<tito> matham: nice
<matham> so we basically have to subtract the bars from the values we give to glviewport
<tito> do you use ANGLE? no right because python2.7
<matham> i.e. pass it 784x562
<tito> matham: but you can't because you don't know when to do it
<tito> you told yourself that it was working before right?
<matham> I tried with angle backend, glew backend and sdl2 backend :D
<matham> yes
<matham> and I tested in 3.5 and 2.7 with stable and master
<tito> so what's changing? you can't just do that and break others that works
<tito> as i said, so far i didn't found the root, but it's definitively not consistent
<matham> I also found a 2.7 32 bit that I havn't used in many months without any changes it it had the same issue
<tito> if i could reproduce it in a vm, it would help
<matham> right, I don't propose we do this adjustment other than a workaround locally
<matham> the only change is that I updated ubuntu on the dual booth a few days ago, but of course windows also installed many updates meanwhile
<matham> I hadn't used kivy for a few weeks
<matham> I'm guessing windows changed something and sdl2 hasn't caught up
<tito> matham: if you're right about this, you could confirm it by using apitrace right?
<tito> if OpenGL draw itself bigger than intented, we should see it
<tito> otherwise, it mean it's a stretch
<matham> yeah, I can run it
<tito> or maybe we have an issue with resizing/glViewport
<tito> gtg, good luck
<matham> https://gist.github.com/matham/977d14aec6970ca9ab2ea2208b296984
<matham> here's apitrace
<matham> not sure what to look for. We do pass it 800x600
<matham> tito, I have proof that it's not kivy but rather sdl2/gl. In visual studio I ran this code https://gist.github.com/matham/4390c9f50467aca574a4541c017d32fe. From two runs i got http://imgur.com/a/DroBS. The left is when I asked for a 400pixels but I got about 420, the right is when I asked for 100 and I got 100
<matham> so you can see that gl stretches the 800 pixels over a 838 area
<matham> *600, 638
<matham> not exactly sure what I can do about this
<matham> I tried with glut/glew and it's the same issue. Someone reported an identical issue on #kivy at the same time as me, so it must be a windows update thing
```

**Comment by isidian** [comment]
I presently have this same issue.

In particular, not only is part of the Kivy interface blocked by the Windows 10 Title bar, the mouse clicks do not register in the correct positions.  They are slightly offset by the amount of space that the Title bar takes up, like the mouse clicks are correctly registering the smaller canvas but the interface is being drawn on the larger canvas.

Said differently, the interface is drawn using "Window coordinates" and the mouse clicks are registering based upon the "Client coordinates" (using the terminology from https://msdn.microsoft.com/en-us/library/windows/desktop/ff381403(v=vs.85).aspx).

Setting resizable = 0 and borderless = 1 does function as a temporary workaround, but then I obviously cannot resize the window as a result.

**Comment by tito** [comment]
One of the client of my customer just got this issue; and i've been asked to solve it. So i first need to reproduce, then fix it. Let's go.

**Comment by matham** [comment]
What do you need? This is still currently an issue with my dev laptop.

**Comment by isidian** [comment]
Well, I can get you started on reproducing the problem.  Just run the TouchTracer example on Windows 10 in Windowed Mode.  As you click on the canvas you will notice a difference between where you click and where it registers on the canvas.  This will also probably give you a head start on how to solve the problem, since you can notice the difference between Window coordinates and Client coordinates just clicking and dragging around with your mouse.

**Comment by tito** [comment]
I cannot reproduce it on my VM. 175% scale. The top/bottom of my app is correctly fitted into the border. I don't use released Kivy, but a custom build (where ANGLE works on 2.7). And this version is used in production where the client has the issue. So it's independant of ANGLE/python IMO.

We need to find out exactly what make the windows behavior change between computer.

![screenshot from 2018-02-22 11-35-18](https://user-images.githubusercontent.com/37904/36533646-7a74cdfa-17c4-11e8-910b-a6a45a34b4fd.png)

**Comment by tito** [comment]
@matham let's get in touch if you have time to check what are the difference between a VM and your computer.

**Comment by tito** [comment]
Just for reference, this is a customer screenshot demontrating the same issue: 
![nrt_8000](https://user-images.githubusercontent.com/37904/36535625-a0e7a48e-17ca-11e8-9cb1-bb5581bd2eb6.PNG)

Both screenshots (from the issue and this one) look like it's cropped but not just top/bottom, on the side too. And the text is blurry, like it's zoomed just a little bit.

**Comment by isidian** [comment]
If you're averse to using TouchTracer to find the issue, you can also produce screenshots of the problem if you just make a simple app consisting of only a TabbedPanel.  This one was constructed with four tabs that have names "Tab1", "Tab2", etc. but you can't see them because the TabbedPanel is drawn to Window coordinates, not Client coordinates.
![image](https://user-images.githubusercontent.com/87869/36546955-7fabe57e-17a1-11e8-9762-48ba5608c046.png)

**Comment by tito** [comment]
It's not about TabbedPanel or any widget, it's about content that actually is bigger than the client size. So yes, whatever you put into the window is cropped. Right now, i would like to have a computer that i can play with. @isidian if you are available, can you come on irc to have a chat?

**Comment by tito** [comment]
Here is an issue similar to us on another project: https://jira.phoenixviewer.com/browse/FIRE-21264

**Comment by isidian** [comment]
matham and I have confirmed that this is a driver issue.  It may be localized to Dell laptops using Intel Graphics.  It is solved by manually updating to the latest driver (22.20.16.4836):

http://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverId=Y0N06

Notably, the dell auto-update software does not auto-upgrade this driver for whatever reason; it must be upgraded by downloading the driver from the website.

**Comment by xzhuah** [comment]
@isidian Thanks a lot, it solved the problem.
