### ISSUE TITLE
Keyboard reconnect - egl_rpi

### ISSUE THREAD

**Issue by vasekjares** [kivy/kivy#5546]
### Versions

* Python: all versions
* OS: Raspberrian Jessie
* Kivy: 1.9.1, 1.10
* Kivy installation method: apt-get / pip install

### Description

egl_rpi doesn't recognise keyboards connected after the app is started, app has to be restarted to start functioning

I'm offering $300 bounty to solve this issue

**Comment by pkemarco** [comment]
Hi. Can you explain more

2017-12-20 3:06 GMT+01:00 vasekjares <notifications@github.com>:

**Comment by pkemarco** [comment]
For the moment I can just say : change egl_rpi for sdl2 and see if it work :
import os
os.environ['KIVY_WINDOW'] = 'sdl2'

2017-12-20 11:13 GMT+01:00 Erickson PASSY <passyerickson@gmail.com>:

**Comment by vasekjares** [comment]
Yes it works with SDL2, it would be even better to run SDL2 but it's like super slow - 5fps, so slide animation between screens is freezing

**Comment by vasekjares** [comment]
@pkemarco if you have any experience with optimisation of SDL2 for RPI3b or fixing that egl_rpi, let's make skype call. I can pay you bounty in ltc or so.

**Comment by pkemarco** [comment]
what is your skype id ?

2017-12-20 17:06 GMT+01:00 vasekjares <notifications@github.com>:

**Comment by pkemarco** [comment]
See your skype please

2017-12-20 20:50 GMT+01:00 vasekjares <notifications@github.com>:

**Comment by Julian-O** [comment]
Closing due to #8434
