### ISSUE TITLE
Input param invert_y ignored

### ISSUE THREAD

**Issue by MikahB** [kivy/kivy#5548]
### Hardware
- Raspberry Pi Model 3 v1.2
- Waveshare 3.5" HDMI Touch Screen (https://www.waveshare.com/wiki/3.5inch_HDMI_LCD)

### Versions

* Python: 3.4
* OS: PipaOS
* Kivy: 1.10.0
* Kivy installation method: KivyPie pre-installed

### Description

Touch screen works fine with Kivy except that Y-axis input is reversed.  Here's the relevant section of my config.ini:
```bash
[input]
mouse = mouse
mtdev_%(name)s = probesysfs,provider=mtdev
%(name)s = probesysfs,provider=hidinput
```
There are no other configuration settings regarding input (postconfig, etc.)

Changing the above configuration to either of the following does not impact the Y-axis behavior:
```bash
[input]
mouse = mouse
mtdev_%(name)s = probesysfs,provider=mtdev
%(name)s = probesysfs,provider=hidinput,params=invert_y=1
```
or
```bash
[input]
mouse = mouse
mtdev_%(name)s = probesysfs,provider=mtdev
%(name)s = probesysfs,provider=hidinput,invert_y=1
```

The only way I've successfully been able to actually "fix" the issue is by changing `Line 420` in
`/usr/local/lib/python3.4/dist-packages/kivy/input/providers/hidinput.py` as follows:
From
```bash
invert_y = int(bool(drs('invert_y', 1)))
```
to
```bash
invert_y = int(bool(drs('invert_y', 0)))
```
It feels like on this provider the invert_y param is being ignored, but the instances I find online of this issue are relatively few and far between so perhaps it's something specific to my configuration.

**Comment by bionoid** [comment]
In your configuration examples, you use `invert_y=1`, but you refer to changing the option to 0 via code edit.. Just to rule out the obvious, did you actually use `invert_y=0` in config? You should see an entry in console ["Set custom invert_y to X"](https://github.com/kivy/kivy/blob/1.10.0/kivy/input/providers/hidinput.py#L369-L370), can you post the startup log?

**Comment by MikahB** [comment]
Yes, I tried invert_y=0 and params=invert_y=0 as well.

Here is startup log with params=invert_y=0:
`[INFO   ] [Logger      ] Record log in /home/sysop/.kivy/logs/kivy_17-12-22_11.txt
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Kivy        ] v1.10.1.dev0, git-4c6f7be, 20171217
[INFO   ] [Python      ] v3.4.2 (default, Oct 19 2014, 13:31:11)
[GCC 4.9.1]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Text        ] Provider: sdl2
Set APP_NAME to alphaMesh2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard allowed, single mode, docked
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_dbusklipper', 'clipboard_gtk3', 'clipboard_xclip', 'clipboard_xsel'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider.
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip'
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)

xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel'
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)

[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
Unable to connect to X server
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [MTD         ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [HIDInput    ] Set custom invert_y to 0
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 4095
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 4095
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[INFO   ] [HIDMotionEvent] using <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '>
[INFO   ] [HIDMotionEvent] <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '> range ABS X position is 0 - 4095
[INFO   ] [HIDMotionEvent] <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '> range ABS Y position is 0 - 4095
[INFO   ] [HIDMotionEvent] <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '> range ABS pressure is 0 - 65535
`

**Comment by MikahB** [comment]
And here is startup with params=invert_y=1 - direction of Y-axis touch input stays the same:

`[INFO   ] [Logger      ] Record log in /home/sysop/.kivy/logs/kivy_17-12-22_13.txt
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Kivy        ] v1.10.1.dev0, git-4c6f7be, 20171217
[INFO   ] [Python      ] v3.4.2 (default, Oct 19 2014, 13:31:11)
[GCC 4.9.1]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Text        ] Provider: sdl2
Set APP_NAME to alphaMesh2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard allowed, single mode, docked
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_dbusklipper', 'clipboard_gtk3', 'clipboard_xclip', 'clipboard_xsel'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider.
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip'
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)

xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel'
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)

[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
Unable to connect to X server
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [MTD         ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [HIDInput    ] Set custom invert_y to 1
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 4095
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 4095
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[INFO   ] [HIDMotionEvent] using <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '>
[INFO   ] [HIDMotionEvent] <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '> range ABS X position is 0 - 4095
[INFO   ] [HIDMotionEvent] <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '> range ABS Y position is 0 - 4095
[INFO   ] [HIDMotionEvent] <b'ADS7846 Touchscreen\x00                                                                                                                                                                                                                                            '> range ABS pressure is 0 - 65535
`

**Comment by MikahB** [comment]
One more curious thing, I guess.

With the change made to `hidinput.py` and `params=invert_y=1` still there, the orientation is correct when I reboot and it automatically starts the Kivy app. 

If I PuTTy in, kill the application (using `CTRL-C`) then restart it, the direction of the input has reversed (to be incorrect).  If I kill it and restart it over and over it remains wrong until I reboot again.

However, if I remove `params=invert_y=1`, the orientation is correct when I reboot and does not change if I kill and restart it via SSH.

**Comment by MikahB** [comment]
Maybe another clue, maybe not.  When I bring up the VKeyboard in my app, no matter what I press I get double-key presses.  Two of any letter, two backspaces, spaces, etc.

This is well out of my realm of understanding, but is it possible the touch screen is being detected by both MtDev and as HIDInput?

**Comment by keikomori** [comment]
I got a solution for not reversing the Y axis

```
sudo nano /.kivy/config.ini
```

```
[input]
mouse = mouse
ADS7846 = hidinput,/dev/input/event0,invert_y=0
```
