### ISSUE TITLE
Pyinstaller filechooser

### ISSUE THREAD

**Issue by allania7med11** [kivy/kivy#5554]
filechooser work fine when i run it but when i convert it to .exe file by Pyinstaller i get this eurror(
 File "<frozen importlib._bootstrap>", line 968, in _find_and_load
 SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
[13656] Failed to execute script main
)
this is main.py:
(
from kivy.app import App
from kivy.uix.filechooser import FileChooserListView
class TestApp(App):
    def build(self):
        return FileChooserListView(id="filechooser")

TestApp().run()
)
and testfn.spec:
(
# -*- mode: python -*-
from kivy.deps import sdl2, glew
import sys
sys.setrecursionlimit(5000)
block_cipher = None

a = Analysis(['C:\\Users\\allan\\PycharmProjects\\testfn\\main.py'],
             pathex=['C:\\Users\\allan\\PycharmProjects\\testfn'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='testfn',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe, Tree('C:\\Users\\allan\\PycharmProjects\\testfn'),
               a.binaries,
               a.zipfiles,
               a.datas,
               *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               strip=False,
               upx=True,
               name='testfn')
)

**Comment by SnowWalkerJ** [comment]
I ran into this problem, too. Is there any solution? @allania7med11

**Comment by tkocza** [comment]
In file .spec you have to add addictional imports in
 Analysis(...
hiddenimports=['win32timezone','win32file'],
....
)
