### ISSUE TITLE
Backwards-incompatible changes - SUBSCRIBE TO THIS THREAD if you use Kivy!

### ISSUE THREAD

**Issue by matham** [kivy/kivy#5560]
Stability is great for users! It lets them focus on solving their problem without worrying about their platform shifting under their feet. But stability is also bad for users! It means that anywhere an API is error-prone or hard to use or missing important functionality, they're stuck with it. Making the optimal trade-off here is tricky and context-dependent.

Kivy is an active project. So as we build things with it we'll probably discover places where the API is less awesome than desired. Hopefully we won't discover any major issues, but you never know.

This means that if you're a Kivy user, it'd be good to have some strategy to make this as painless as possible. Our suggestions:

* Pin your version. For example, in your install_requires= or requirements.txt, do not write: kivy >= 1.8.0. Instead, write: kivy ~= 1.8.0.
  * You can also use == if you prefer. The difference is that while both == 1.8.0 and ~= 1.8.0 will disallow upgrading to 1.9.0, ~= allows upgrading to 1.8.1 but == 1.8.0 does not. Our intention is that 0.x.y and 0.x.(y+1) will be backwards compatible.
* **Subscribe to this issue** (for example, by pressing the little "Subscribe" button in the right column →). We'll link to backwards-incompatible changes here before we make them, so this will give you fair warning and a chance to give feedback on the original issue.

If you would like to propose a backwards incompatible change to Kivy, please add the `api-break` label to your issue (or request that we add it), and a link to the issue will automatically be posted here.

**Comment by Zen-CODE** [comment]
This PR would probably also classify as a breaking change?

https://github.com/kivy/kivy/pull/6095

**Comment by matham** [comment]
We are moving our kivy dependencies on windows from `kivy.deps.xxx` stored in `kivy/deps/xxx` to `kivy_deps.xxx`, stored under `kivy_deps/xxx`. To prevent any issues, please always pin your dependency versions when you install them from pip to the version on pypi at the time of the release you're using.

**Comment by matham** [comment]
Python 2 support has been dropped from master https://github.com/kivy/kivy/pull/6351.

**Comment by matham** [comment]
I'm closing this since we don't really use it. Instead you should look under the `Breaking changes` section of the release notes for each release. Or, look at the [API-break](https://github.com/kivy/kivy/pulls?q=is%3Apr+label%3A%22Notes%3A+API-break%22+) label to see PRs that were an API break.
