### ISSUE TITLE
Kivy-1.10.0-cp36-cp36m-win_amd64.whl doesnt contain set_system_cursor

### ISSUE THREAD

**Issue by testbuddy** [kivy/kivy#5561]
Either i am too stupid to find the set_system_cursor in kivy.core.window or when i follow the installtion instruction from the doc it is the wrong package (Kivy-1.10.0-cp36-cp36m-win_amd64.whl) which doesnt contain the function.

Can someone help me how i find the function (maybe renamend) because when i look in the master branch it is definitely there.

**Comment by bionoid** [comment]
This feature was added after the release of Kivy 1.10, to use it you need to install master branch or wait for the next release.
