### ISSUE TITLE
Initializing one video after another override the first one's settings

### ISSUE THREAD

**Issue by P1kachu** [kivy/kivy#5563]
### Versions

* Python: 2.7.13
* OS: Debian 9/OSX 10.12/Raspbian (latest)
* Kivy: 1.10.0
* Kivy installation method: Various (pip for osx, apt-get for debian)

### Description

I would like to play one video always looping in background, and another video on top, once.
I thus setup the background video to always loop
I setup the second one to stop.

However, depending of the order of initialization, the second video's "eos" parameter is overwritten by the second one (as if they were sharing the same instance).

So if I first init the loop video, then the stop one, both will stop. In the other order, both will loop.

The code and videos have been uploaded [here](https://p1kachu.pluggi.fr/assets/tmp/kivy-issue-two-videos.tar.gz)

Thanks in advance :)

### Code and Logs
Here is my script, minus what was not related:

```python
#!/usr/bin/env python2

import os
#os.environ["KIVY_NO_CONSOLELOG"] = "1"
#os.environ["KIVY_WINDOW"] = "sdl2"
#os.environ["KIVY_IMAGE"] = "imagio,tex"
os.environ["KIVY_AUDIO"] = "ffpyplayer"
os.environ["KIVY_VIDEO"] = "ffpyplayer"

import kivy
kivy.require('1.10.0')

from kivy.app import App
from kivy.clock import Clock
from kivy.config import Config
from kivy.graphics import Color, Rectangle
from kivy.graphics.instructions import VertexInstruction
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput
from kivy.uix.video import Video
from kivy.uix.image import Image

#Config.set('graphics', 'fullscreen', 'auto')

def update_background(instance, value):
    instance.background.pos = instance.pos
    instance.background.size = instance.size

class Example1(GridLayout):
    video = None
    def __init__(self, **kwargs):
        super(Example1, self).__init__(**kwargs)

        # Root
        self.rows = 3
        self.cols = 1
        self.orientation = 'vertical'

        # Background
        with self.canvas.before:
            self.background = Video(source='bg.mp4', state='play', eos='loop', volume=0)
            self.background.keep_ratio = False
            self.background.allow_stretch = True
            self.background.name = "TEST-BG"
        self.bind(pos=update_background, size=update_background)

        # Video
        opacity = 0.8
        state = 'play'
        self.clip = Video(source='Mugi.mp4', state=state, opacity=opacity, eos='stop')
        self.clip.allow_stretch=True
        self.clip.name = "TEST-CLIP"
        self.add_widget(self.clip)

        # GridLayout2
        boxlayout2 = FloatLayout()
        boxlayout2.rows = 2
        boxlayout2.cols = 4
        boxlayout2.size_hint = (1, 0.10)
        self.add_widget(boxlayout2)


class KivyTest(App):

    def build(self):
        ex = Example1()
        return ex

if __name__ == '__main__':
    KivyTest().run()
```

Logs:
```
[INFO   ] [Logger      ] Record log in /home/p1kachu/.kivy/logs/kivy_18-01-05_16.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.0.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoFFPy   ] Using ffpyplayer 4.0.1
[INFO   ] [Video       ] Provider: ffpyplayer(['video_gstplayer', 'video_ffmpeg'] ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 13.0.6>
[INFO   ] [GL          ] OpenGL vendor <VMware, Inc.>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits)>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[ERROR  ] [Image       ] Error loading texture bg.mp4
[ERROR  ] [Image       ] Error loading texture Mugi.mp4
[INFO   ] [Base        ] Start application main loop
[WARNING] [ffpyplayer  ] SDL_OpenAudio (2 channels, 48000 Hz): No such audio device
[WARNING] [ffpyplayer  ] SDL_OpenAudio (1 channels, 48000 Hz): No such audio device
[WARNING] [ffpyplayer  ] SDL_OpenAudio (2 channels, 44100 Hz): No such audio device
[WARNING] [ffpyplayer  ] SDL_OpenAudio (1 channels, 44100 Hz): No such audio device
[ERROR  ] [ffpyplayer  ] No more channel combinations to try, audio open failed
[INFO   ] [GL          ] NPOT texture support is available
### Clicking on [X]
[INFO   ] [Base        ] Leaving application in progress...
```

**Comment by bionoid** [comment]
For some reason the videos don't play on this computer so I can't actually reproduce it. But looking at the code,

```python
with self.canvas.before:
            self.background = Video(source='bg.mp4', state='play', eos='loop', volume=0)
```

This looks suspect, why are you instantiating the widget inside a `with canvas`, and not adding it as a child anywhere? I frankly don't even know what that does, and a little surprised you see the video at all. My initial impression is that you need to place both the background and foreground Video widgets in the actual hiearchy, in principle

```
fl = FloatLayout()
fl.add_widget(Video(source='background.mp4', ...))
fl.add_widget(Video(source='foreground.mp4', ...))
```

**Comment by P1kachu** [comment]
I wanted a full video in the background of the whole window, and found this way to be the simplest one. The other one is just a video that should be displayed in a widget, and is thus created as one and added with add_widget. The video widget might change to something else, but I still want a background video for the whole window.

It shouldn't really matter about the fact that both instance seem to share parameters though, which is my real issue here. But it these are related, I am interested in why too :)

**Comment by bionoid** [comment]
> I wanted a full video in the background of the whole window, and found this way to be the simplest one. 

It is also broken, and I am 99.9% sure you can not point to an example in the documentation that uses this technique with a Video widget. Right?

> It shouldn't really matter about the fact that both instance seem to share parameters though,

I don't know if/how they are related, what I'm saying is that your background video widget is not added to the widget hierarchy. I fully expect this to lead to a broken state, but I don't know exactly what or how it breaks. Can you reproduce this with two Video instances added to the widget hierarchy?

**Comment by P1kachu** [comment]
> > I wanted a full video in the background of the whole window, and found this way to be the simplest one.
> It is also broken, and I am 99.9% sure you can not point to an example in the documentation that uses this technique with a Video widget. Right?

I cannot indeed, but it still works for some reason :) If there is a real better method by using a FloatLayout, I'll take a look also.

> Can you reproduce this with two Video instances added to the widget hierarchy?

I'll have to try this then, and come back to you after

**Comment by bionoid** [comment]
> I cannot indeed, but it still works for some reason :)

No it doesn't work -- it may draw something on screen, but that's not the same thing. The question is if there is a bug in Kivy or not, to answer that you must start by using the API correctly. My guess is that the problem will disappear once you do.

**Comment by P1kachu** [comment]
Ok. I'll try that.

**Comment by matham** [comment]
As @bionoid says, the `with self.canvas.before:` thing is definitely an incorrect usage of the API. it only works for graphics instructions, not widgets.
