### ISSUE TITLE
Not able to use Kivy for Python3.6.3 in Ubuntun 16.04, 64-bit

### ISSUE THREAD

**Issue by yoelk** [kivy/kivy#5572]
* Python: 3.6.3
* OS: Ubuntu 16.04
* Kivy: 1.10.0
* Kivy installation method: virtualenv (pip install kivy)

### Description

Running my Kivy app, it happens sometimes that I get an error:
`Unable to find any valuable Window provider.`

The only way I found to resolve this is to restart my computer

possibly connected to https://github.com/kivy/kivy/issues/5410

### Code and Logs
Simplest kivy program, see the following gist (with the errors)

https://gist.github.com/yoelk/688e0bab56e2ed52915044e5388a4866

**Comment by bionoid** [comment]
> The only way I found to resolve this is to restart my computer

After a restart, you are able to run the Kivy application? Can you provide the console log for a successful startup? 

I notice your error log does not include any GL items, looks like this on my system:

```
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.4.0 NVIDIA 344.11'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 670/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <b'4.40 NVIDIA via Cg compiler'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
`` 

Does other 3d-accelerated software run?

I am also wondering if you are running in VirtualBox? There is an open issue regarding OpenGL that seems to affect some systems (#5438), maybe try the `KIVY_GL_BACKEND=sdl2 python3 main.py` workaround if you are in an environment like this..

Another thing to check is that you have updated graphics drivers. If your machine is a laptop, it's possible that it has a built-in Intel graphics adapter as well as a dedicated nvidia/amd. There have been some reports of computers working when one card is used, but not the other (generally missing drivers, and afaik typically for the built-in Intel graphics)

**Comment by yoelk** [comment]
Thanks for the reply.
Unfortunately it's neither on a VM nor due to a built-in card. I'm using an Nvidia card with recent driver (although not the absolute latest).
Other 3D-accelarated programs work, and Kivy has been working as well for many months now with this setting. Only recently it started giving problem (only sometimes).

Here is a traceback of another kivy program, after restart (it works):
```
[17:19, 1/11/2018] Yonatan Hyatt: [INFO   ] [Logger      ] Record log in /home/yonatan/.kivy/logs/kivy_18-01-11_10.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 194 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[DEBUG  ] [GL          ] glShaderBinary is not available
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 384.111'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1080 Ti/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load </home/yonatan/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/data/glsl/default.png>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[DEBUG  ] [Audio       ] register SoundSDL2
[DEBUG  ] [Audio       ] register MusicSDL2
[INFO   ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0
[WARNING] [Factory     ] Ignored class "FixiOperationalScreen" re-declaration. Current -  module: None, cls: <class 'fixi.fixi_app.FixiOperationalScreen'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyLayout, filename: /home/yonatan/tiny_inspektor/sw/fixi/src/fixi/fixi.kv.
[WARNING] [Factory     ] Ignored class "FixiSetupScreen" re-declaration. Current -  module: None, cls: <class 'fixi.fixi_app.FixiSetupScreen'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyBoxLayout, filename: /home/yonatan/tiny_inspektor/sw/fixi/src/fixi/fixi.kv.
xclip version 0.12
```

**Comment by yoelk** [comment]
Some more info:
It started happening when I moved from python2.7 to python3.5 (and later python 3.6.3)

**Comment by MrAgeo** [comment]
It could be some python2.7 and python3 Kivy incompatibilities (perhaps?)

Maybe uninstalling and reinstalling Kivy could help, or building Kivy from source either downloading the 1.10.0 source (from [here](https://github.com/kivy/kivy/archive/1.10.0.tar.gz)) or cloning this git repo...

I downloaded the source code, and built/installed Kivy running `sudo python3 setup.py install` on a terminal (in the Kivy source directory), ensuring that before building Kivy I have installed the required packages (as explained in [https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2](https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2))

I also had to change the Cython version to 0.25.2, because the 0.27 version didn't let compile Kivy...

I hope it helps! :D

**Comment by yoelk** [comment]
Thanks for the comment @MrAgeo.

**Comment by dolang** [comment]
From your log in the gist it looks to me like it fails to initialise the SDL2 backend (probably in the call to `SDL_GL_CreateContext()`, not sure).

I've found a [StackOverflow question](https://stackoverflow.com/questions/41320653/kivy-fails-to-find-a-window-provider-after-switching-drivers) which might be the same problem. But they didn't have a real solution except changing the graphics card driver.

Can't say why it would work with py2.7 and not py3.5/py3.6, though. That's probably not related.

**Comment by matham** [comment]
This seems to be issue with your system rather than Kivy, so I'm closing.
