### ISSUE TITLE
Update file extensions for Pillow image loader

### ISSUE THREAD

**Issue by pythonic64** [kivy/kivy#5573]
Latest Pillow version 5.0.0 supports 61 image file extensions while Kivy master supports 38. 
We should update `ImageLoaderPIL.extensions` method to return all extensions currently available in installed Pillow. 

I suggest we do not hardcode them, but instead use `PIL.Image.EXTENSION` dict. 
Print of that dict in version 5.0.0 looks like this: 
```
{'.bmp': 'BMP',
 '.bufr': 'BUFR',
 '.bw': 'SGI',
 '.cur': 'CUR',
 '.dcx': 'DCX',
 '.dds': 'DDS',
 '.emf': 'WMF',
 '.eps': 'EPS',
 '.fit': 'FITS',
 '.fits': 'FITS',
 '.flc': 'FLI',
 '.fli': 'FLI',
 '.fpx': 'FPX',
 '.ftc': 'FTEX',
 '.ftu': 'FTEX',
 '.gbr': 'GBR',
 '.gif': 'GIF',
 '.grib': 'GRIB',
 '.h5': 'HDF5',
 '.hdf': 'HDF5',
 '.icns': 'ICNS',
 '.ico': 'ICO',
 '.iim': 'IPTC',
 '.im': 'IM',
 '.j2c': 'JPEG2000',
 '.j2k': 'JPEG2000',
 '.jfif': 'JPEG',
 '.jp2': 'JPEG2000',
 '.jpc': 'JPEG2000',
 '.jpe': 'JPEG',
 '.jpeg': 'JPEG',
 '.jpf': 'JPEG2000',
 '.jpg': 'JPEG',
 '.jpx': 'JPEG2000',
 '.mic': 'MIC',
 '.mpeg': 'MPEG',
 '.mpg': 'MPEG',
 '.mpo': 'MPO',
 '.msp': 'MSP',
 '.palm': 'PALM',
 '.pbm': 'PPM',
 '.pcd': 'PCD',
 '.pcx': 'PCX',
 '.pdf': 'PDF',
 '.pgm': 'PPM',
 '.png': 'PNG',
 '.ppm': 'PPM',
 '.ps': 'EPS',
 '.psd': 'PSD',
 '.pxr': 'PIXAR',
 '.ras': 'SUN',
 '.rgb': 'SGI',
 '.rgba': 'SGI',
 '.sgi': 'SGI',
 '.tga': 'TGA',
 '.tif': 'TIFF',
 '.tiff': 'TIFF',
 '.webp': 'WEBP',
 '.wmf': 'WMF',
 '.xbm': 'XBM',
 '.xpm': 'XPM'}
```

On the downside Pillow would have to be initialized for `EXTENSION` to be populated. Successive calls of `init` function will not cause re-init. Changed `ImageLoaderPIL.extensions` method would look like this:
```
    @staticmethod
    def extensions():
        '''Return accepted extensions for this loader'''
        PILImage.init()
        return tuple([e[1:] for e in PILImage.EXTENSION])
```

**Comment by tshirtman** [comment]
This seems fine to me, it'll only happen if PIL is installed, and if the additional startup time/memory usage (only drawbacks i can think of) are undesired when shipping an application, it's always possible to deactivate the PIL provider by forcing another one to be used.
