### ISSUE TITLE
Enhancing Kivy language, a kivy.wiki pull request.

### ISSUE THREAD

**Issue by wexi** [kivy/kivy#5578]
I may be wrong but it seems that one cannot fork kivy.wiki to prepare a convenient PR.
In the alternative, here is a PR against my own kivy-wiki clone.

https://github.com/wexi/kivy-wiki/pull/1

Thanks, Enoch.

**Comment by KeyWeeUsr** [comment]
I'm not quite sure what do you mean by forking, but if you actually want to edit the [Kivy repo wiki](https://github.com/kivy/kivy/wiki) then just go and press the `Edit` button in the upper-right part above the contents/pages. IIRC even an ordinary user that doesn't watch/star/... the repo can do the edit. See [the revision history](https://github.com/kivy/kivy/wiki/Home/_history).

**Comment by wexi** [comment]
Done, added: https://github.com/kivy/kivy/wiki/Kv-language-preprocessing

Thanks, an extraordinary user :-)
