### ISSUE TITLE
Request for Kivy Language enhancement

### ISSUE THREAD

**Issue by wexi** [kivy/kivy#5580]
I am pleased to advise that pyexpander's author made his preprocessor module easier for the Kivy community to use (*). See: [Kv language preprocessing](https://github.com/kivy/kivy/wiki/Kv-language-preprocessing).

May I suggest that kivy.lang.builder makes a similar effort to simplify the interface or, come up with a matching (in-built) functionality. In any case, **such functionality IMHO is essential**.

Thanks, Enoch.

(*) No more needed to redirect sys.stdout to capture...

**Comment by Julian-O** [comment]
This isn't nearly enough information to guide someone to add this feature.

* What has the pyexpander's author done?
* What change is required to the kivy.lang.builder interface?
* Why is this essential?
