### ISSUE TITLE
bug in textInput, which cause line feed when insert char every time.

### ISSUE THREAD

**Issue by ghking1** [kivy/kivy#5583]
### Versions

* Python: 2.7.12
* OS: all platform
* Kivy: 1.10.0
* Kivy installation method: all method

### Description
![2018-01-27_152807](https://user-images.githubusercontent.com/8264304/35469772-95cfec1c-0377-11e8-88ed-cc1e3423a13c.jpg)

for example when you typed many 'a', but not over one line. then insert 'b' before these 'a', it willcause line feed every time when you insert 'b'.

**Comment by Julian-O** [comment]
Does this problem still occur in Kivy 2.2.1? Looks like it may have been fixed.
