### ISSUE TITLE
Kivy Installation on MacOS 10.13 not working

### ISSUE THREAD

**Issue by kenykj49** [kivy/kivy#5585]
**Versions:**

- Python 2.7.10
-OS: MacOS 10.13
-Xcode 9.2
-Kivy Installation Method: brew + pip

**Description:**

When attempting to install pip via https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip I'm running into installation errors.

**Code and Logs:**

**Installation Process:**

$ brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer
**No issues.**

$ pip install Cython==0.26.1
**Received Error as follows:**

Collecting Cython==0.26.1
  Using cached Cython-0.26.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: Cython
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/cython.py'

**Next Step in Installation:**
 pip install kivy

**Received error as follows:** (Obviously Cython is needed.)

Collecting kivy
  Using cached Kivy-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Using distutils
    
    Cython is missing, it's required for compiling kivy !
    
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gl/zg315dvs3j1c791yq6mgt55w0000gn/T/pip-build-8uhVgT/kivy/setup.py", line 219, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gl/zg315dvs3j1c791yq6mgt55w0000gn/T/pip-build-8uhVgT/kivy/

I'm at a loss. This issue is beyond my knowledge. Anybody have any suggestions? Thanks.

**Comment by ekscrypto** [comment]
+1 And if you attempt to continue the installation afterwards, you get this:

/private/tmp/pip-build-_27j98g8/kivy/kivy/graphics/svg.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
    #error Do not use this file, it is the result of a failed Cython compilation.
     ^
    1 error generated.
     error: command 'clang' failed with exit status 1

**Comment by bionoid** [comment]
```
with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/cython.py'
```

Seems like it wants to write this file, but your user doesn't have permission. I'm not familiar with MacOS specifically, but `pip install --user Cython` (to install on a per-user basis without root access) or `sudo pip install Cython` (for a system-wide installation) might work?

Another option is [pyenv](https://github.com/pyenv/pyenv), it works well for me on linux

**Comment by stephanepiriou** [comment]
`pip3 install --user https://github.com/kivy/kivy/zipball/master`

 worked fine for me...

**Comment by ekscrypto** [comment]
Where is this "pip3 install --user https://github.com/kivy/kivy/zipball/master" command comes from? I can't seem to find it in https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip

**Comment by stephanepiriou** [comment]
I saw it in another issue regarding the install on MacOS.
[5345](https://github.com/kivy/kivy/issues/5345)

**Comment by misl6** [comment]
Closing as is referring to Python 2.7 which reached EOL a long time ago + that seems a support request.
Feel free to re-open if needed.
