### ISSUE TITLE
Documentation sidebar usability issue

### ISSUE THREAD

**Issue by asl97** [kivy/kivy#5586]
### Description
When the side bar of the documentation is way longer than the page content, scrolling pass a certain point would cause it to glitch toggle the sidebar positioning status.

### Example
https://kivy.org/docs/gettingstarted/installation.html
Click `Gallery of Examples` and scroll down.

### Reproducibility 
It depend on the size of the window, it probably more likely to happen on shorter (height) window.

### Video
https://www.youtube.com/watch?v=2gLKhWxy_mc

### Cause
https://github.com/kivy/kivy/blob/8776f284f75f5589d3b0c6f1e82795d73e9f3c45/doc/sources/.static/kivy.js#L278-L288

**Comment by Zen-CODE** [comment]
Okay, so I've removed the offending lines. After testing pretty thoroughly, it seems to work without adverse effects. Would appreciate if you could test this fixes the issue without any adverse effects.

Thanks

**Comment by Zen-CODE** [comment]
Indeed. Thank.s
