### ISSUE TITLE
pygame is not a dependency 

### ISSUE THREAD

**Issue by farhank3389** [kivy/kivy#5590]
### Versions

* Python: 3.6.4
* OS: Fedora 27
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I installed kivy using `pip3 install kivy` which also installed a bunch of other dependencies. I then tried to run the simple example from the Kivy website which threw a "Unable to get a Window, abort" error. After a lot of Googling, the problem was fixed by running `pip3 install pygame`.

Shouldn't pygame be installed along with kivy as a dependency?

**Comment by tshirtman** [comment]
All the window provider are theorically optional, since you only need any of them to work.

I agree a better message could help, not sure pip/setup.py gives us a way to check that at installation time, but maybe the provider system could show a better message when no provider has been found, and show the available various ways of fixing that (by printing or linking to installation documentation of each provider compatible with the platform?)

**Comment by dessant** [comment]
If you preselect the window provider by exporting `KIVY_WINDOW=sdl2` before the installation it is supposed to fail if the sdl2 headers are not found.

@farhank3389 you're likely just missing sdl2, search for `fedora` on the issue tracker.

**Comment by farhank3389** [comment]
I have the SDL2 headers installed but I still get the `"Unable to find any valuable Window provider."` error if I export `KIVY_WINDOW=sdl2`.

**Comment by dessant** [comment]
Try reinstalling with the env var set, post the installation logs.

**Comment by farhank3389** [comment]
The install fails with `error: command 'gcc' failed with exit status 1`. The log is quite large so I can't post it here, but here are the last few lines: 

`gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-build-yjarb3ey/kivy/kivy/include -I/usr/include/SDL2 -I/usr/local/include/SDL2 -I/usr/include/SDL2 -I/usr/include/SDL2 -I/usr/include/python3.6m -c /tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.c -o build/temp.linux-x86_64-3.6/tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.o
    /tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.c: In function ‘__pyx_f_4kivy_4core_5audio_10audio_sdl2_mix_init’:
    /tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.c:1647:63: error: ‘MIX_INIT_MODPLUG’ undeclared (first use in this function); did you mean ‘MIX_INIT_MOD’?
       __pyx_v_want_flags = (__pyx_v_want_flags | ((MIX_INIT_MOD | MIX_INIT_MODPLUG) | MIX_INIT_FLUIDSYNTH));
                                                                   ^~~~~~~~~~~~~~~~
                                                                   MIX_INIT_MOD
    /tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.c:1647:63: note: each undeclared identifier is reported only once for each function it appears in
    /tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.c:1647:83: error: ‘MIX_INIT_FLUIDSYNTH’ undeclared (first use in this function); did you mean ‘MIX_INIT_MID’?
       __pyx_v_want_flags = (__pyx_v_want_flags | ((MIX_INIT_MOD | MIX_INIT_MODPLUG) | MIX_INIT_FLUIDSYNTH));
                                                                                       ^~~~~~~~~~~~~~~~~~~
                                                                                       MIX_INIT_MID
    /tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.c: In function ‘__pyx_pf_4kivy_4core_5audio_10audio_sdl2_9MusicSDL2_extensions’:
    /tmp/pip-build-yjarb3ey/kivy/kivy/core/audio/audio_sdl2.c:4936:69: error: ‘MIX_INIT_MODPLUG’ undeclared (first use in this function); did you mean ‘MIX_INIT_MOD’?
       __pyx_t_2 = ((__pyx_v_4kivy_4core_5audio_10audio_sdl2_mix_flags & MIX_INIT_MODPLUG) != 0);
                                                                         ^~~~~~~~~~~~~~~~
                                                                         MIX_INIT_MOD
     error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yjarb3ey/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sgsenc1d-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yjarb3ey/kivy/
`

**Comment by dessant** [comment]
Post the full log in a gist. https://gist.github.com/

**Comment by farhank3389** [comment]
Here you go: https://gist.github.com/farhank3389/0b4d001e1ddcf9589eb1ff3b692f8b2a

**Comment by dessant** [comment]
This appears to be fixed in https://github.com/kivy/kivy/pull/5459, try installing Kivy master.
