### ISSUE TITLE
Creation of Fbo with_depthbuffer=True hangs UI thread on iOS

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy#5591]
This issue occurs on iOS specifically - it does not reproduce on other platforms. 

When running a 3D OpenGL example, the creation of the FBO with_depthbuffer=True hangs the UI thread.  If this setting is set to false, then the UI thread does not hang, but the OpenGL rendering is broken (rendered flat), as one would expect.

The simple example, attached, uses the kivy3 wrapper for rendering 3D objects.  The UI thread hangs exactly at the point where the FBO is created, inside kivy3/renderer.py:

![image](https://user-images.githubusercontent.com/3267533/35548579-4551284a-0535-11e8-8df7-438da4fb41c9.png)

Here is the self-contained example code:

[ios_3d_test.zip](https://github.com/kivy/kivy/files/1676398/ios_3d_test.zip)

Other notes:
* The app does not crash, the UI thread merely hangs.
* There are no exceptions thrown in the log when the issue occurs
* Other background threads continue to run.

**Comment by brentpicasso** [comment]
Any other information we can provide to help resolve this one?

**Comment by tito** [comment]
If it's iOS, do you have a different behavior with Xcode running or when the app is in release?
If you can on XCode, can you try to pause the app when it hang, and get the traceback for all the threads?

**Comment by brentpicasso** [comment]
Thanks, Tito for the reply. 

It makes no difference if we are seeing it in dev mode or with the released app - it does the same. 

Not sure how to do your second suggestion (pause and get traceback on all threads), can you suggest how to do this?  Thanks!

**Comment by tito** [comment]
If you run it via Xcode, while running, you can go in menu Debug > Pause; wait a little bit, then you'll see all the backtrace for all the threads on the left.
Expand all of them, select everything, copy & paste here in a code block.

**Comment by brentpicasso** [comment]
Thanks. The problem for us is that it hangs immediately - as soon as the Fbo is created, not after some period of time. But I will get the trace as @tito suggested.
