### ISSUE TITLE
Error installing Kivy with Python 3.7 on Windows 10 64-bit

### ISSUE THREAD

**Issue by ylockson** [kivy/kivy#5596]
When issuing command:
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew --extra-index-url https://kivy.org/downloads/packages/simple

The following error is generated:
Collecting docutils
  Using cached docutils-0.14-py3-none-any.whl
Collecting pygments
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting pypiwin32
  Using cached pypiwin32-219.zip
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-build-ukwsu5c5\pypiwin32\setup.py", line 121
        print "Building pywin32", pywin32_version                                                                       ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Building pywin32", pywin32_version)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxx\AppData\Local\Temp\pip-build-ukwsu5c5\pypiwin32\

**Comment by LogicalDash** [comment]
Try replacing "pypiwin32" with "pywin32"

**Comment by ylockson** [comment]
@LogicalDash: 
Issuing the command:
python -m pip install docutils pygments pywin32 kivy.deps.sdl2 kivy.deps.glew
yield the following error message:
Collecting docutils
  Using cached docutils-0.14-py3-none-any.whl
Collecting pygments
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting pywin32
  Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32

**Comment by ylockson** [comment]
Got the installation to work by downgrading from Python 3.7 (I found out it was an alpha version) to version 3.6.
