### ISSUE TITLE
can't find kivy launcher in Google Play

### ISSUE THREAD

**Issue by stevhud5** [kivy/kivy#5602]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by KeyWeeUsr** [comment]
@tito any idea what might have happened? I think it was published under [your account](https://play.google.com/store/apps/developer?id=Mathieu+Virbel), but the rest such as Pictures, Touchtracer or other stuff is still there.

**Comment by tito** [comment]
Oops. Guess i didn't see any notification about it:

```
After review, Kivy Launcher, org.kivy.pygame, has been removed from Google Play because it violates our personal and sensitive information policy and section 4.3 of the Developer Distribution Agreement. This app won’t be available to users until you submit a compliant update.

Policy issue: Google Play requires developers to provide a valid privacy policy when the app requests or handles sensitive user or device information. Your app requests sensitive permissions (e.g. camera, microphone, accounts, contacts, or phone) or user data, but does not include a valid privacy policy.

Here’s how you can submit your app for another review: 

Read through the User Data policy and Personal and Sensitive Information article and make the necessary changes to your app.
Sign in to your Play Console and be sure to include a link to a valid privacy policy on your app's Store Listing page and within your app. You can find more information in our Play Console Help Center.
Submit your app.
If approved, your app will again be available with all installs, ratings, and reviews intact. Alternatively, you may opt-out of this requirement by removing any requests for sensitive permissions or user data.
```

I'll try to generate one, publish it, reference it on the launcher, and resubmit.

**Comment by tito** [comment]
The privacy policy got pushed in the website, waiting it to update. https://github.com/kivy/kivy-website/commit/edc691b174373c49a72bd1e227604ce3ad617245

**Comment by tito** [comment]
The application privacy url is updated, and waiting the check/re-publication from Google.

**Comment by tito** [comment]
It's back. https://play.google.com/store/apps/details?id=org.kivy.pygame

**Comment by stevhud5** [comment]
Thanks very much! I am installing it now.

**Comment by stevhud5** [comment]
Dear Mathieu,
I am having a problem, which I think is a problem using android and not
kivy. When I open Kivy launcher it says that I have no projects in the
folder /storage/emulated/0/Kivy
I am not able to find this folder. I think it is hidden. On my device, I
created a folder with this name, but Kivy doesn't see the folder I created.
Can I change which folder Kivy looks in?
When I search online, I see several Q/A threads concerning this difficulty.
I am using a Moto G4, and one thread suggests that Moto protects those
folders, keeping them hidden.
Please let me know if you have advice. Thanks very much!
Steve
