### ISSUE TITLE
Wrong aspect ratio in some video streams [kivy.uix.video / linux / gstreamer]

### ISSUE THREAD

**Issue by om-arino** [kivy/kivy#5603]
### Versions

* Python: v2.7.14 (default, Sep 23 2017, 22:06:14) 
* OS: Ubuntu linux 17.10
* Kivy: v1.9.1
* Kivy installation method: apt repo

### Description
When playing some udp streams (iptv app), the video ratio is wrong in kivy video widget ...
For example stream 
`Input #0, mpegts, from 'udp://@239.18.2.240:5000':
  Duration: N/A, start: 36726.694844, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : ##
      service_provider: ##
    Stream #0:0[0xc8]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt470bg, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x12c](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 151 kb/s`
video plays in old 4:3 ratio ignoring the SAR/DAR settings ...
On the other hand, stream
`Input #0, mpegts, from 'udp://@239.18.14.241:5000':
  Duration: N/A, start: 3641.979644, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : #
      service_provider: #
    Stream #0:0[0xc8]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Stream #0:1[0x12c](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 121 kb/s`
plays in 16:9 as it is supposed to.
I suspect the problem are the non square video pixels (SAR 64:45), but i wonder if there is any way to resolve the issue.
Both streams play as they should in gstplayer playbin ...

B.

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by om-arino** [comment]
how does kivy video widget calculate aspect ratio?

**Comment by bionoid** [comment]
> how does kivy video widget calculate aspect ratio?

I think it just naively reads frames from the video provider in the resolution it reports. You probably need to obtain the metadata and compute the correct texture size in [kivy/lib/gstplayer](https://github.com/kivy/kivy/tree/master/kivy/lib/gstplayer)

**Comment by om-arino** [comment]
The problem I have are the non-square pixels in 

> Video: h264 (High) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt470bg, progressive), 720x576 [SAR 64:45 DAR 16:9],
Kivy treats them as if they were square and displays frame in 5:4 ratio, but the ratio should be 16:9 ...
How would I go about computing the correct texture size in kivy/lib/gstplayer?
Thanks in advance,
B

**Comment by bionoid** [comment]
If you had queried the SAR value as 64:45, it's easy to arrive at the correct resolution;

    >>> ((64/45.) * 720) / 576. == 16/9.
    True

As far as I understand [dispatching the sample_cb callback](https://github.com/kivy/kivy/blob/1.10.0/kivy/lib/gstplayer/_gstplayer.pyx#L126-L132) is what eventually determines the video widget's aspect ratio, but I could be wrong here... One possible solution is to query the SAR value and compute the adjusted resolution at this point. You could do a simple test to confirm if this would be enough by adding the (64/45) * width to the callback dispatch and recompiling Kivy. If that loads the video successfully, you "just" need is to query the real SAR...

... However, warning, gstreamer probably has better ways to do this, I have absolutely no idea how it works.
