### ISSUE TITLE
No option for disabling multitouch

### ISSUE THREAD

**Issue by MrSherish** [kivy/kivy#5609]
### Versions

* Python: 3.6.1
* OS: KivyPie on RaspberryPi
* Kivy: 1.10.0
* Kivy installation method: compiled from sources

### Description

Hey,
I'm trying to get rid of multitouch capabilities in Kivy. Is there such possibility? So far I've seen that option for multitouch emulation through mouse, but since I'm using official RPi touchscreen, it has no use.
In the way Kivy works, when button gets touched by two or more fingers, on_press is invoked twice. That's not the behaviour we want.

**Comment by pythonic64** [comment]
In your entry point script, before all other kivy imports do:
```
from kivy.config import Config
Config.set('input', 'mouse', 'mouse,disable_multitouch')
```

**Comment by MrSherish** [comment]
That disables only multitouch simulation on mouse, as I've said.

**Comment by tshirtman** [comment]
There is indeed no such feature currently, the framework was designed with multitouch in mind, you could certainly create a postproc module that would capture the current touch event and ignore all the other ones until this one is finished (i think you can look at `kivy/postproc/ignorelist.py` to get a starting point), and if you do that, it would be a welcome contribution (pull request), but it's not a bug in my opinion, just a missing feature.

**Comment by Roberciiik** [comment]
Multitouch support is not a bug of course, but double calling `on_press` method is a defect. Only last finger released from the screen should invoke `on_press` event. Can you address this issue?
