### ISSUE TITLE
 ImportError: No module named Kivy.app macOs

### ISSUE THREAD

**Issue by JojoMatFedrica** [kivy/kivy#5613]
### Versions

* Python: 2.7.14
* OS: macOS High Sierra 10.13.3
* Kivy: v1.10.1.dev0
* Kivy installation method: homebrew + pip

### Description
Hi there, 
I'm completely new to Kivy, I really want too start designing a GUI for an upcoming project but I'm struggling to install Kivy on mi mac.

I've used the Homebrew + pip method but when I type Kivy on my terminal it returns:
-bash: kivy: command not found

if I go to the foolder where I have my first Kivy project, the classic hello world, I can run it by using python (name of me project).py but it returns:
 ImportError: No module named Kivy.app

### Code and Logs

imac:Python joavicenteidura$ kivy
-bash: kivy: command not found

imac:Python joavicenteidura$ python kivytut.py
[INFO   ] [Logger      ] Record log in /Users/joavicenteidura/.kivy/logs/kivy_18-02-11_16.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180211
[INFO   ] [Python      ] v2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
 Traceback (most recent call last):
   File "kivytut.py", line 4, in <module>
     from Kivy.app import App
 ImportError: No module named Kivy.app

Thanks in advance for the help.

**Comment by dessant** [comment]
Kivy does not register itself as an executable during pip installation (and it does not need to), uninstall everything and try following the installation instructions again.

**Comment by alexjpanagis** [comment]
I'm experiencing the same issue since installing Kivy3. The Kivy command no longer works in terminal.
