### ISSUE TITLE
How to increase the speed of the CodeInput widget?

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#5619]
### Versions

* Python: 3.6
* OS: Android
* Kivy: 1.10.1.de0
* Kivy installation method: Run from source with PyDroid3

### Description

I'm working with the CodeInput widget ... If the text size exceeds 10 kb, then CodeInput is very slow. Look at the animation: I'm doing a translation into a new line, pressing 'Enter', and the transition takes place only after 10 seconds. Tell me, can I optimize this? Will, TextEdit from Java (if using jnius) work faste?

<img src="https://habrastorage.org/webt/mc/wk/5z/mcwk5z6zsgmfu44depvlo9jo7yq.gif" />

**Comment by bionoid** [comment]
> Tell me, can I optimize this?

It's always possible, but unlikely that a small fix that will have a large impact. Probably need to start with some benchmarks to figure out where exactly it is currently spending cycles.

> Will, TextEdit from Java (if using jnius) work faste?

Maybe / probably, but is there a way to use it? Jnius can foreign Java code, but afaik there is no way to integrate native widgets in Kivy's rendering pipeline. Maybe you can cook up an overlay solution or something.
