### ISSUE TITLE
internet dependence of virtual box image

### ISSUE THREAD

**Issue by astrolinuxcuba** [kivy/kivy#5623]
the virtual box have dependences of internet conection, python-for-android i install him and buildozer try to reinstall. I am cuban, google do not acces me the sdk or ndk, and no have  way to download

**Comment by bionoid** [comment]
Technically I think redistributing an installed version of the Android SDK/NDK is in violation of the license terms... Maybe the best is to get a short-term VPN subscription to install/configure the toolchain?

**Comment by KeyWeeUsr** [comment]
P4A, buildozer and kivy yeah, but as bionoid said the SDK/NDK would be against the [license](https://developer.android.com/studio/terms.html):

> 3.4 You may not use the SDK for any purpose not expressly permitted by the License Agreement. Except to the extent required by applicable third party licenses, you may not copy (except for backup purposes), modify, adapt, redistribute, decompile, reverse engineer, disassemble, or create derivative works of the SDK or any part of the SDK.
