### ISSUE TITLE
Unable to find any video provider

### ISSUE THREAD

**Issue by SoukupMCAT** [kivy/kivy#5629]
### Versions

* Python: 2.7
* OS: Windows 10
* Kivy: 1.10.0
* Kivy installation method: 

### Description

I am trying to run video as a screensaver in my app. I installed everything reccomended including docutils, pygments pypivin32, sdl2, glew and gstreamer following [these instructions](https://kivy.org/docs/installation/installation-windows.html). 

### Code and Logs
Code:
```python
Button:
        id: screensaver_button
        size: 1280, 800
        pos: self.pos
        Video:
            size: 1280, 800
            pos: self.pos
            id: screensaver_video
            allow_stretch: True
            volume: 0
```
```python
def set_video(self, vid):
        self.video.source = "join.avi"
        self.video.state = 'play'
```
Logs:
```python
[INFO   ] [Logger      ] Record log in C:\Users\MCAT\.kivy\logs\kivy_18-02-14_18.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[WARNING] The 'fake' fullscreen option has been deprecated, use Window.borderless or the borderless Config option instead.
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] OpenGL version <3.1.0 - Build 9.17.10.4459>
[INFO   ] [GL          ] OpenGL vendor <Intel>
[INFO   ] [GL          ] OpenGL renderer <Intel(R) HD Graphics>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <1.40 - Intel Build 9.17.10.4459>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Shader      ] fragment shader: <No errors.>
[INFO   ] [Shader      ] vertex shader: <No errors.>
[INFO   ] [Shader      ] program: <No errors.>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[CRITICAL] [Video       ] Unable to find any valuable Video provider.
```
but I am still getting this error:
```python
[ERROR  ] [Image       ] Error reading file join.png
[ERROR  ] [Image       ] Error reading file join.avi
```

Anybody know why unable to find video provider (despite gstreamer 0.1.12 installed)? Thank you for your answer.

**Comment by SoukupMCAT** [comment]
I am afraid it is not possible to post runnable example, this is just a part of a large system. I am just trying to add screensaver to app and thats why Video instance is added to a Button (I need to close video on touch).

I copied older logs, now I'm using kivy `v1.10.0`. I have already tried many ways to use video (VideoPlayer, cv2,...) but in the end all of them failed due to error reading file which is because of kivy unable to find any valuable video privedr (at least I think so).

**Comment by SoukupMCAT** [comment]
If I make another app just for playing video, it works as expected, even video provider gstplayer is recognized. But implementation into already existing app is not working.

**Comment by tito** [comment]
Put the Kivy configuration log_level to debug, then post the log. You may see the error about why none of the Video provider was selected and why you ended up without one.

**Comment by SoukupMCAT** [comment]
Hello Tito, 
this is the log. How can I convince config not to ignore video providers?
```
[INFO   ] [Logger      ] Record log in C:\Users\MCAT\.kivy\logs\kivy_18-02-26_4.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[WARNING] The 'fake' fullscreen option has been deprecated, use Window.borderless or the borderless Config option instead.
[INFO   ] [Window      ] Activate GLES2/ANGLE context
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <angle_sdl2>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)>
[INFO   ] [GL          ] OpenGL vendor <Google Inc.>
[INFO   ] [GL          ] OpenGL renderer <ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1)>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00 (ANGLE 2.1.99f075dade7c)>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load <C:\Python27\lib\site-packages\kivy\data\glsl\default.png>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG  ] [Video       ] Provider <gstplayer> ignored by config
[DEBUG  ] [Video       ] Provider <ffmpeg> ignored by config
[DEBUG  ] [Video       ] Provider <ffpyplayer> ignored by config
[DEBUG  ] [Video       ] Provider <null> ignored by config
[CRITICAL] [Video       ] Unable to find any valuable Video provider.

[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0
 2018-02-26 09:14:24,823 main (MainThread,3704) INFO ----------------------
 2018-02-26 09:14:24,825 main (MainThread,3704) INFO app | init started....
 2018-02-26 09:14:24,826 main (MainThread,3704) INFO comm | initiated
```

**Comment by tito** [comment]
All of them are "ignored by config", meaning you have somehow somewhere. I guess your environment removed it?

What is the env for KIVY_VIDEO ? If you set it, remove it.

**Comment by SoukupMCAT** [comment]
There none env for KIVY_VIDEO. My only env variables related to kivy are `USE_GSTREAMER=1` `USE_SDL2=1` and `KIVY_GL_BACKEND=angle_sdl2`.

**Comment by tito** [comment]
If you do in a python interpreter:

```
>>> import kivy
>>> kivy.kivy_options["video"]
('gstplayer', 'ffmpeg', 'ffpyplayer', 'null')
```

What about you?

**Comment by SoukupMCAT** [comment]
It is same.

**Comment by tito** [comment]
Do it in your software. The message "ignored by config" is because your provider is not listed in the kivy_options. The only way it can be changed is pragmatically or with environment.

Check https://github.com/kivy/kivy/blob/master/kivy/core/__init__.py#L45

Video use core_select_lib function, not the core_register_libs. So here is the code path taken to show this error. The `option` (which is the name of the provider, ffmpeg, gst_player, etc) is not in `kivy.kivy_options`.

Maybe even a library you use actually change it. You could double check by importing kivy and print the kivy_options just before creating the Video class.

**Comment by tito** [comment]
Or, add a "import pdb; pdb.set_trace()" just before that line, and hunt down in your case why it doesn't work.

**Comment by SoukupMCAT** [comment]
I found it, thank you very much. I was overwritting it in file a really did not expect (must have done programer before me a long time ago). There was `os.environ[KIVY_VIDEO] = 'gstreamer'` and I changed it to `os.environ[KIVY_VIDEO] = 'gstplayer'`. Now the provider is working fine. I am getting another error, but it is because of something else. 
Thank you very much Tito.
