### ISSUE TITLE
window focus [feature request]

### ISSUE THREAD

**Issue by ImmanuelSamuel** [kivy/kivy#5630]
I have a window that I hide and show at a later time but that window does not have focus and is in the background. I checked the docs but I don't see any `force_focus` like behavior as in tkinter. This may also be achieved with `window always-on-top` like feature.

Is there a short term procedure to get this behavior?

**Comment by bionoid** [comment]
Is `Window.raise_window()` what you are looking for?

**Comment by ImmanuelSamuel** [comment]
Yes that works for the initial focus but goes away after clicking anywhere else. So I guess I am looking for the `always-on-top` kind of feature.

**Comment by tito** [comment]
If that can help, for some museum applications, i'm using this to prevent the windows going back (with fake fullscreen and borderless):

```
        # try forcing app to front permanently to avoid windows pop ups and notifications etc
        try:
            import ctypes
            LSFW_LOCK = 1
            ctypes.windll.user32.LockSetForegroundWindow(LSFW_LOCK)
            Logger.info("App: Foreground lock activated")
        except:
            Logger.warn("App: No foreground lock available")
```

That way, any notifications, popup, goes behind the windows, which make it perfect for a Kiosk-style application.

**Comment by ImmanuelSamuel** [comment]
Seems like this is for windows os (`windll`). Is there an equivalent for linux?

**Comment by acrixl** [comment]
it is imposible in linux, linux always use fuzzy logic to control windows

**Comment by ImmanuelSamuel** [comment]
@acrixl I respectfully disagree. So my use case it to have a window pop up advising me to take a break. Currently there are quite a few apps that do this in linux. As for how they do it I am not aware.

**Comment by KeyWeeUsr** [comment]
@ImmanuelSamuel A better example (imports, what `win` variable is, etc) for how tkinter is able to do that would give us an idea where to look for the linux part.

I found the `lift` part [here](https://github.com/python/cpython/blob/128641d17e8f6a3d9229e93b169b9fcc6c20d453/Lib/tkinter/__init__.py#L935). From [what I found ](https://github.com/python/cpython/blob/128641d17e8f6a3d9229e93b169b9fcc6c20d453/Lib/tkinter/__init__.py#L1779) next I don't see tkinter able to make it work on Linux.

**Comment by ImmanuelSamuel** [comment]
I am currently working with the `lift()` and it seems to get the job done. The window that shows up is on top of everything.

**Comment by Matteljay** [comment]
Yes I agree with @ImmanuelSamuel and would really like to see this Always-on-top feature in the future as well for Linux/X11/Gnome.
