### ISSUE TITLE
App crash when connecting to mysql

### ISSUE THREAD

**Issue by Mark-Wellings** [kivy/kivy#5633]
### Versions

* Python: 3.6
* OS: Windows 10
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

Dear all, 

My main.py is working fine, when running it with python 3.6 locally on Windows. I can log on and sign up to a mysql db located on server hosted on digitalocean.
 
When I deploy it via the VM I can still open the application and switch between screens, but when I try to connect to the mysql database on a server the application crashes.
With adb logcat *W: I get the following log: [logcat Warnings .txt](https://github.com/kivy/kivy/files/1754283/logcat.Warnings.txt)
I think the problem is the following: 

> /lib/arm/libpython2.7.so (PyThreadState_New+93)

> /lib/arm/libpython2.7.so (PyThreadState_New+93)

I've uploaded the project to my github under: [https://github.com/Mark-Wellings/mykivy](url)

Where you'll find the main.py, main.kv, buildozer spec and the logcat.txt.

Thanks for your help.

**Comment by bionoid** [comment]
I don't know what the issue is here, but I see you are using python2.. maybe the [mysqldb recipe](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/mysqldb/__init__.py) can be used instead of mysql-connector-python? Or alternatively, try to build the APK using python3crystax w/3.6

**Comment by Mark-Wellings** [comment]
Thanks for your comment! How would I implement that in the main.py? It's treated as a library, correct?
Also, how would I build the APK with python3crystax w/3.6? I was using the VM before.. noob here, thanks for your help.

**Comment by bionoid** [comment]
> Thanks for your comment! How would I implement that in the main.py?

No idea, I haven't touched mysql in 15+ years. Obviously you'll have to change your code to use the library that is packaged by the recipe, but I couldn't tell you exactly how. I **believe** this is the correct module http://mysql-python.sourceforge.net/MySQLdb.html#mysqldb - try the examples... but yeah, not sure

> Also, how would I build the APK with python3crystax w/3.6?

[See here](http://python-for-android.readthedocs.io/en/latest/buildoptions/?highlight=crystax); first download Crystax NDK and set the path to it (p4a/buildozer options). Then put `python3crystax==3.6` in requirements, and you should be good to go. You may need to install 3.6 on your linux distro as well (at least I needed 3.5 to build it for android, but it's possible that you don't need exact same version). Suggest you use [pyenv](https://github.com/pyenv/pyenv) to manage python versions
