### ISSUE TITLE
language independent (keyboard layout independent) keycodes

### ISSUE THREAD

**Issue by acrixl** [kivy/kivy#5634]
feature request

language independent (keyboard layout independent) keycodes

some codes that indentify keyboard key not a symbol

game actions mean same action in any layout (language)

**Comment by pythonic64** [comment]
You can bind to `Window` events `on_key_down`, `on_key_up` and use `scancode` values which I think are language independent.

**Comment by acrixl** [comment]
yes it work, but why no scancode in keyboard.on_key_down?

**Comment by acrixl** [comment]
it not work with kivy.uix.vkeyboard

**Comment by Julian-O** [comment]
`kivy.core.window.WindowBase` has an event `on_keyboard` that includes a scancode.
