### ISSUE TITLE
error installing kivy dependencies 

### ISSUE THREAD

**Issue by desmond75** [kivy/kivy#5639]
### Versions

* Python: 3.4.3
* OS: Windows7 64bit
* Kivy: 
* Kivy installation method: using pip 

### Description
I am trying to install kivy on windows using pip and when i try installing kivy dependencies i get this error ""  Could not find a version that satisfies the requirement pywin32>=223 (from pyp
iwin32) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32)
""
### Code and Logs

```python
this is what i am doing ''py  -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew'' 

```

**Comment by KeyWeeUsr** [comment]
That's exactly what's happening - there's no such distribution for 3.4.3 for version 222+. You'll either need to install it from source or use https://github.com/mhammond/pywin32/releases/tag/b221 or older version. In each case, this is not a Kivy issue, but a decision of pywin32 not to distribute for Python 3.4 anymore.

From what I found, the latest version you can use and is available on PyPI is [pypiwin32/219](https://pypi.python.org/pypi/pypiwin32/219)

**Comment by desmond75** [comment]
Thanks so much for the quick response and the corrections
