### ISSUE TITLE
Buildozer Turkish character

### ISSUE THREAD

**Issue by cagsurgunu** [kivy/kivy#5643]
Hi, 
My App works windows machine correctly but when i compile it with buildozer apk file can't open on android device. i tried that to cancel Turkish character inside my main.py. Then I compiled it. it ran correctly.
I want to use Turkish character.How can I fix it?

**Comment by bionoid** [comment]
Please provide more details; at minimum a buildable code snippet that exhibits the problem. Preferably also `adb logcat` output of the crash

**Comment by cagsurgunu** [comment]
Buildozer don't give any error message if i use turkish character in main.py. but android device can't open application.

**Comment by tito** [comment]
If there is an issue, it should first be reported in kivy/buildozer - not here. 
Second, include the adb logcat. You said it can't open the application, then show us the adb logcat about it :)
