### ISSUE TITLE
CI builds have been failing for a year

### ISSUE THREAD

**Issue by bionoid** [kivy/kivy#5646]
### Description

It seems like the most recent successful CI build was in January 2017. In my opinion it does more harm than good at this stage. I propose to disable failing builds until the issues have been resolved.

**Comment by KeyWeeUsr** [comment]
The Travis builds were mostly working except some PEP8 issues, however Appveyor builds are half-successful with the jobs because of Angle running on < Py 3.5 though it works (or worked at least) just fine when on a PC with correctly installed drivers.

Then there is the issue with nightly wheels on Appveyor because they made the scheduled builds disabled by default.

**Comment by bionoid** [comment]
Aha, I don't know about Travis/Appveyor, can it be fixed in a reasonable timeframe? I just think the value is gone when CI doesn't tell you about the state of the pull request. Right off the bat it's discouraging to anyone that stops by to have a look, and it's confusing to people that open the first PR, and it's confusing to me although I've been around a while. 

From my perspective, it seems important to fix ASAP. If a resolution is not on the horizon, I would prefer to disable stuff until a clean PR doesn't result in a reported failure.

Feel free to close of course, just voicing my opinion here

**Comment by Zen-CODE** [comment]
I'll second bionoid here. It defeat the point of having them if they permanently fail: a failure should be alarming. I'll look into this. Some builds are working, so it may be a matter of small tweaking...

**Comment by Zen-CODE** [comment]
Okay, I've managed to get 4 of the 6 builds passing with in Travis.

https://travis-ci.org/kivy/kivy

The remaining errors are bizarre. I can' reproduce them and running the tests on my machine works fine. About to experiment with different cython versions, but any insight would be help. Pretty weird. The inspector test fails with
```
   File "/home/travis/build/kivy/kivy/kivy/modules/inspector.py", line 382, in on_window_children
     win.add_widget(self)
   File "/home/travis/build/kivy/kivy/kivy/core/window/__init__.py", line 1247, in add_widget
     (widget, widget.parent)
 kivy.uix.widget.WidgetException: Cannot add <kivy.modules.inspector.Inspector object at 0x2b8dae99ace0> to window, it already has a parent <kivy.core.window.window_sdl2.WindowSDL object at 0x2b8d9941c660>
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch
     ps.observers.dispatch(obj, ps.value, None, None, 0)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
     result = self._dispatch(
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
     return f(obj, value)
   File "/home/travis/build/kivy/kivy/kivy/modules/inspector.py", line 382, in on_window_children
     win.add_widget(self)
   File "/home/travis/build/kivy/kivy/kivy/core/window/__init__.py", line 1247, in add_widget
     (widget, widget.parent)
 kivy.uix.widget.WidgetException: Cannot add <kivy.modules.inspector.Inspector object at 0x2b8dae99ace0> to window, it already has a parent <kivy.core.window.window_sdl2.WindowSDL object at 0x2b8d9941c660>
```

**Comment by pythonic64** [comment]
Check this bug report https://github.com/kivy/kivy/issues/5645.

**Comment by tshirtman** [comment]
I managed to fix them all, we are back in the green :D
