### ISSUE TITLE
kivy.uix.video setting state="pause" doesn't pause the sound in the video

### ISSUE THREAD

**Issue by blurymind** [kivy/kivy#5650]
### Versions

* Python:3+
* OS:windows10
* Kivy:latest
* Kivy installation method:pip

### Description

When pausing the video widget, the sound doesn't get paused as well- just keeps going

**Comment by tshirtman** [comment]
Does that happen for a specific video? for any videos on your system? I use videos in kivy a lot, and i never got this issue.

**Comment by Julian-O** [comment]
Insufficient info to debug. Closing.
