### ISSUE TITLE
gstreamer app windows build - TOO HUGE - over 500 mb

### ISSUE THREAD

**Issue by blurymind** [kivy/kivy#5651]
After following these instructions and try to build an app - my build is over 500 mb!!

Is there a way to reduce the size of my app?

this is the spec that i am using btw:

```
# -*- mode: python -*-

from kivy.deps import sdl2, glew, gstreamer

block_cipher = None

a = Analysis(['D:\\WORK\\PYTHON\\webmTest\\webmPlayerApp.py'],
             pathex=['D:\\WORK\\PYTHON\\WinPython-64bit-3.6.3.0Zero\\python-3.6.3.amd64'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='webmPlayerApp',
          debug=False,
          strip=False,
          upx=True,
          console=True )

coll = COLLECT(exe,Tree('D:\\WORK\\PYTHON\\webmTest\\'),
               a.binaries,
               a.zipfiles,
               a.datas,
               *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + gstreamer.dep_bins)],
               strip=False,
               upx=True,
               name='webmPlayerApp')

```
### Versions

* Python: 3.6.3
* OS: win10
* Kivy: master
* Kivy installation method: pip

Question 2- how can I get it into a single executable?

**Comment by blurymind** [comment]
Nothing I tried seems to have worked :(

**Comment by Mileem** [comment]
Did you try this ?

`python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
python -m pip install kivy.deps.gstreamer`

**Comment by blurymind** [comment]
@Mileem 
I followed the instructions here:
https://kivy.org/docs/installation/installation-windows.html

So yeah

Btw I tried with both python
python-3.6.3.amd64 from https://github.com/winpython/winpython

and the latest official python-3.6.4
from http://python.org/

Both give me the same problem

Which version of python works best with kivy?
Also if you like to, here is my minimal webm player kivy app source:

webmPlayerApp.py
```
from kivy.app import App

from kivy.uix.scatter import Scatter
from kivy.uix.label import Label
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.textinput import TextInput
from kivy.uix.boxlayout import BoxLayout

from kivy.uix.video import Video

from kivy.core.window import Window

import sys

class webmPlayerApp(App):
	def build(self):
		Window.bind(on_dropfile=ScatterTextWidget()._on_file_drop)
		return ScatterTextWidget()

	def on_start(self,**kwargs):
		print("I AM ALIVE")
		# ScatterTextWidget.OpenVideoFile(ScatterTextWidget,sys.argv[1])

	def on_stop(self):
		print("Webm player was killed")

class ScatterTextWidget(BoxLayout):

	def getCmdArguments(self):
		if len(sys.argv) > 1:
			return sys.argv[1]
		else:
			return("")

	def _on_file_drop(self, window, file_path):
		self.OpenVideoFile(file_path)

	def OpenVideoFile(self,file_path):
		print("OPENING FILE! "+str(file_path))
		openFilePath = str(file_path)[2:-1].replace("\\\\","\\")
		kivyGui = App.get_running_app().root.ids
		kivyGui.filePathLabel.text = openFilePath
		
		print("try:",openFilePath) 
		print("prev:",kivyGui.videoPlayerFrame.source)
		# kivyGui.videoPlayerFrame.state = "stop"
		kivyGui.videoPlayerFrame.unload() 
		kivyGui.videoPlayerFrame.state = "stop"    
		kivyGui.videoPlayerFrame.source = openFilePath
		kivyGui.videoPlayerFrame.state = "play"
		pass

### track the running video
	def on_position_change(instance,self, videoPositionMs):
		print(str(videoPositionMs))
		# if videoPositionMs > 0.0001 :
		#     kivyGui = App.get_running_app().root.ids
		#     kivyGui.videoPlayerFrame.state = "pause"
		return

	def on_duration_change(instance,self, value):
		# kivyGui = App.get_running_app().root.ids
		return
		print('The duration of the video is', value)

	def on_new_video_loaded(instance,self, value):
		kivyGui = App.get_running_app().root.ids
		print("Video Loaded:\n"+str(value))
		print("Length:"+str(kivyGui.videoPlayerFrame.duration))
		self.playTimes = 0	


	def on_video_reached_end(instance,self, value):
		if value == False:return
		self.playTimes += 1
		print("REACHED END:\n"+str(value)+" looped:" +str(self.playTimes))
		## loop the video - problem - it plays more than once
		kivyGui = App.get_running_app().root.ids
		kivyGui.videoPlayerFrame.state = "play"
	
### this initiates an instance of the app:
if __name__ =="__main__":
	webmPlayerApp().run()
```



webmPlayer.kv
```
<ScatterTextWidget>:
    orientation : 'vertical'
    Label:
        id: filePathLabel
        size_hint_y: None
        height:200
        ## whats on the right side of : is python
        text: 'Drag and drop your file here'
        text_size:self.width,None 
        height: self.texture_size[1]
    Video:
        id:videoPlayerFrame
        source: root.getCmdArguments()
        on_source:root.on_new_video_loaded(root,self.source)
        state: "play"
        size: self.width, self.height
        on_position:root.on_position_change(root,self.position)
        on_duration:root.on_duration_change(root,self.duration)
        on_loaded:root.on_new_video_loaded(root,self.source)
        on_eos:root.on_video_reached_end(root,self.eos)
        position:0
```

**Comment by blurymind** [comment]
btw this line's path:
`File "kivy\lib\gstplayer\_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load (kivy\lib/gstplayer\_gstplayer.c:3151)
`
kivy\lib/gstplayer\_gstplayer.c 
Has a mixture of \ and /
Is it possible that the path formatting is causing the issue?

**Comment by blurymind** [comment]
Ok I figured it out - should have followed these instructions more carefully:
https://kivy.org/docs/guide/packaging-windows.html

But now I have another issue with the build. Its too damn huge!
500 mb for a video player app :/

**Comment by pythonic64** [comment]
`COLLECT` call is probably collecting files which your app doesn't use. You should print-out: `a.binaries`, `a.zipfiles`, `a.datas` and see which files you can remove. 

Also, I think that you don't need to collect entire project files `Tree('D:\\WORK\\PYTHON\\webmTest\\')`, but only non-python files.

**Comment by blurymind** [comment]
Hi @pythonic64 
How do I tell the spec file to print out a.binaries, a.zipfiles, a.datas ?

Also is it possible to change this line:
`*[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + gstreamer.dep_bins)],`
To something that pulls only parts of gstreamer required to play a webm file?

I want to slim down gstreamer as well if possible

**Comment by blurymind** [comment]
I deleted these files and am still able to start the app and play a webm clip- with some warnings in terminal:
[DELETED.txt](https://github.com/kivy/kivy/files/1812541/DELETED.txt)
This gets the app down to 70mb - which is still too high to get to android app store and there may be possible bugs in the future.

Perhaps kivy is not the best choice for a small video player. It's still bigger than many other video players on desktop even.

Any ideas on 
- How do we get it down to under 50 mb at least
- How do we do it in a cleaner way than deleting files
- Get more control over which modules gstreamer on kivy pulls- most of the bulk is gstreamer modules that I do not need, but deleting them is not a good fix. I want a cleaner compilation

**Comment by pythonic64** [comment]
You can print-out `a.binaries`, `a.zipfiles`, `a.datas` by using `pprint` or `print` functions because spec acts like python file. 
```
from pprint import pprint 
pprint(a.binaries)
# Other prints here
```
To customize distribution see this [link](https://kivy.org/docs/guide/packaging-windows.html#including-excluding-video-and-audio-and-reducing-app-size). You need to use `get_deps_minimal` function. 

You can also exclude `pygments`, `docutils` and other libraries or modules by adding them in `excludes` list of `Analysis` function.

**Comment by bionoid** [comment]
> This gets the app down to 76mb - which is still too high to get to android app store

I don't think gstreamer is intended for use on Android - there is no p4a recipe for it. You can customize the build if you create a recipe of course.. but I don't know how much you can save or how well gstreamer will work on mobile devices..

If all you need is the playback, you could try ffpyplayer? I think it is smaller for pyinstaller platforms, but no idea how easy/hard it is to package. There are recipes for android, but it failed to build for me recently (it seems ffmpeg recipe needs some work)

**Comment by blurymind** [comment]
@pythonic64  in 
**get_deps_minimal(video=None, audio=None)))
I need to include video and audio, but not all the codecs and dev tools that come with gstreamer (400+ mb of data)- I want to only include whats needed to play a webm file. Is that possible? If so, what is the keyword?

@bionoid You are correct - ffpyplayer fails to initialize on windows too btw

**Comment by blurymind** [comment]
@pythonic64 here are the printout results:
https://gist.github.com/blurymind/c1b88c686d0cd99a3beb7160390b35f7

Any suggestions as to which ones to add to the exclude list?
