### ISSUE TITLE
Change KIVY_HOME

### ISSUE THREAD

**Issue by stevhud5** [kivy/kivy#5655]
### Versions

* Python:
* OS:
* Kivy: 
* Kivy installation method: Google play on android

### Description

// How to change KIVY_HOME on android phone (MotoG4), so that it is on external sd card? 

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by stevhud5** [comment]
Kivy does not find apps in  /sdcard/kivy/<app name>

**Comment by inclement** [comment]
It's an environment variable so you can set it before importing Kivy, as described [in the doc](https://kivy.org/docs/guide/config.html#local-configuration).
