### ISSUE TITLE
Exception on widget init with python3

### ISSUE THREAD

**Issue by lufebe16** [kivy/kivy#5663]
### Versions

* Python: 3.5.4
* OS: Gentoo
* Kivy: 10.0.0 and latest dev0
* Kivy installation method: Gentoo emerge

### Description

Exception in EventDispatcher when running with python3.5
This problem appears with any widget based classes. The log above is
from a simple test prog. It exists with kivy 10.0.0 and also as shown below
with the current dev-master from github (installed as 10.0.1).

The same code runs with python2 (2.7) without error.

### Code and Logs

```python

class RImage3(Widget):
    def __init__(self, **kw):
        super(RImage3, self).__init__(**kw)
        ...
        # (where the problems appears first)

class arge(App):
    def build(self):
        wing = RImage3(source='Nostalgy.png', pos=(0, 0), size=Window.size)
        Window.bind(size=wing.update_widget)
        return wing

[INFO   ] Logger: Record log in /home/lb/.kivy/logs/kivy_18-03-21_58.txt
[INFO   ] Kivy: v1.10.1.dev0, git-Unknown, 20180320
[INFO   ] Python: v3.5.4 (default, Jan  8 2018, 15:39:04) 
[GCC 6.4.0]
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] Factory: 194 symbols loaded
[INFO   ] OSC: using <multiprocessing> for socket
[INFO   ] Window: Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'3.0 Mesa 17.2.8'>
[INFO   ] GL: OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] GL: OpenGL renderer <b'Mesa DRI Intel(R) Ivybridge Mobile '>
[INFO   ] GL: OpenGL parsed version: 3, 0
[INFO   ] GL: Shading version <b'1.30'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "./iitest.py", line 49, in <module>
[WARNING] stderr:     arge().run()
[WARNING] stderr:   File "/usr/lib64/python3.5/site-packages/kivy/app.py", line 800, in run
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "./iitest.py", line 43, in build
[WARNING] stderr:     wing = RImage3(source='Nostalgy.png', pos=(0, 0), size=Window.size)
[WARNING] stderr:   File "./iitest.py", line 13, in __init__
[WARNING] stderr:     super(RImage3, self).__init__(**kw)
[WARNING] stderr:   File "/usr/lib64/python3.5/site-packages/kivy/uix/widget.py", line 340, in __init__
[WARNING] stderr:     super(Widget, self).__init__(**kwargs)
[WARNING] stderr:   File "kivy/_event.pyx", line 243, in kivy._event.EventDispatcher.__init__ (kivy/_event.c:5332)
[WARNING] stderr: TypeError: object.__init__() takes no parameters

```

**Comment by bionoid** [comment]
You are passing a keyword argument that does not have a corresponding property:

```python
wing = RImage3(source='Nostalgy.png', pos=(0, 0), size=Window.size)
```

`source` is not a property of Widget, EventDispatcher ends up doing `object.__init__(source=...)` which fails. This is expected behavior, not a bug. No idea why it works on py2, it's probably not supposed to.

**Comment by lufebe16** [comment]
This would mean, that in a complex program one has to filter incoming keyword arguments before passing them to the base class or any other function.

To determine keywords expected by a function no other method exists (as I know) as reading the code or the documentation. This leads to much hand work and will be a maintenance issue.

But how does EventDispatcher know accepted keywords. They might be different depending on subclasses ?

EventDispatcher in __cinit__() (_event.pyx) checks expected keywords against the current property list and removes them from keyword argument list. Then it calls __init__() on the base class. Unfortunately it passes the keyword argument list. This call will fail if the list is not empty.

As the base class ObjectWithUid does not accept arguments in __cinit__(), the call must not supply any arguments and thus silently ignore keywords other than expected ones.

```
240     prop_args = {
241         k: kwargs.pop(k) for k in list(kwargs.keys()) if k in properties}
242     self._kwargs_applied_init = set(prop_args.keys()) if prop_args else set()
243     super(EventDispatcher, self).__init__() # <- no kwargs here please! 
244
245     __cls__ = self.__class__
```

**Comment by bionoid** [comment]
> But how does EventDispatcher know accepted keywords. They might be different depending on subclasses ?

The Kivy API allows you to specify **kivy property** values as kwargs to `__init__` (and probably events). Anything else is your responsibility, normally you'd do something like

```python
class RImage3(Widget):
    source = StringProperty()
```

or

```python
class RImage3(Widget):
    def __init__(self, **kwargs):
        source = kwargs.pop('source')
        super(RImage3, self).__init__(**kwargs)
```

If your class is supposed to mimick `Image` and you want to pass `source=` to its constructor, you have to deal with it somehow... This was introduced a while back (maybe for 1.9.0 release? not sure), so there should be some issues/PRs discussing the details somewhere... I don't have a link though, sorry

**Comment by lufebe16** [comment]
You wrote:

> `source` is not a property of Widget, EventDispatcher ends up doing `object.__init__(source=...)` which fails. This is expected behavior, not a bug. No idea why it works on py2, it's probably not supposed to.

If it is expected behaviour, EventDispatcher would throw a specific
exception, like:

`TypeError: __init__() got an unexpected keyword argument 'source'`

and not:

`TypeError: object.__init__() takes no parameters`

And this independent from python version.

So I suppose this is an error.

Look at the code in _event.pyx. The `__init__()` method of EventDispatcher calls the base class ObjectWithUid's `__init__()` passing a keyword argument list  (line 243). But the base class does not accept any parameters (line 46). What should the base class do with it ? - Python2 obviously ignores parameters if there are and python3 throws an exception as shown.

```
cdef class ObjectWithUid(object):
    '''
    (internal) This class assists in providing unique identifiers for class
    instances. It is not intended for direct usage.
    '''
    def __cinit__(self):
        global widget_uid
        ...
```
and
```
cdef class EventDispatcher(ObjectWithUid):
    '''Generic event dispatcher interface.

    See the module docstring for usage.
    '''

    def __cinit__(self, *largs, **kwargs):
        ...
        # Auto bind on own handler if exist
        properties = self.properties()
        prop_args = {
            k: kwargs.pop(k) for k in list(kwargs.keys()) if k in properties}
        self._kwargs_applied_init = set(prop_args.keys()) if prop_args else set$
        super(EventDispatcher, self).__init__(**kwargs)
        ...
```
This issue should be corrected in order to have the same behaviour with both python versions.

My preferred way to correct that is to be tolerant against excess parameters, as done with python2,
simply by:
```
        super(EventDispatcher, self).__init__()
```

**Comment by lufebe16** [comment]
Update:

I have found the discussions around that issue. It starts with issue #3036.
More discussions related are in issue #3650, issue #3696 ,issue #3469.

The problem adresses a multiple inheritance case. So obviously kwargs must be
passed to the base class, in order to have 'green' instead of 'blue' (test3036).

But in the single inheritance case we earn an exeption by this. This is very
uncomfortable. It needs additional workarounds in upper level code for
python3 only.

**Comment by lufebe16** [comment]
The least invasive fix to existing python code was adding a base class to all relevant	class definitions. The new base	class added at the rightmost position of the inheritance list swallows up all excess keywords just before they reach class object:

```
class BlackHole(object):
    def __init__(self, **kw):
        super(BlackHole, self).__init__()

class RImage3(Widget, BlackHole):
    def __init__(self, **kw):
        super(RImage3, self).__init__(**kw)
        ...
```

**Comment by matham** [comment]
This is not a bug in Kivy. This error is what you're supposed to get when you pass a unhandled argument to the base object class in python 3.

You can replicate it in native python with:

```py
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
>>> class MyClass(object):
...     pass
...
>>> MyClass(name=66)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object() takes no parameters
```

Kivy is not doing anything different than how python handles these arguments.

**Comment by ht-thomas** [comment]
every time I initialize a subclass of a parent widget in kivy, I always get a bunch of errors some of which say that my class does not have such a method yet I expected it to be picked up from the parent class. I resorted to using a bunch of super() functions but they had a limit as well. The code below illustrates what I mean.

from kivy.app import App
from kivy.graphics import Color
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.label import Label

class test_label(Label):
        def __init__(self,name):
              super(test_label,self).__init__(text=name)
              with self.canvas:"#this is where the code stops working, i expect modification on super class"
                     Color(1,0,0,.5,mode="rgba")  "#does not happen"

I'm beginning to think this is an error in the kivy implementation. Replacing self.canvas with super().canvas brings other errors along with it. so i'm wondering, does the label class have an exception with using the canvas property, because the docs don't include using canvas to modify the label's look.  

Any suggestions?

**Comment by danielecrespini** [comment]
> The least invasive fix to existing python code was adding a base class to all relevant class definitions. The new base class added at the rightmost position of the inheritance list swallows up all excess keywords just before they reach class object:
> 
> ```
> class BlackHole(object):
>     def __init__(self, **kw):
>         super(BlackHole, self).__init__()
> 
> class RImage3(Widget, BlackHole):
>     def __init__(self, **kw):
>         super(RImage3, self).__init__(**kw)
>         ...
> ```

That's save me. Thanx a lot. A lot!
