### ISSUE TITLE
kivy with pip installation is supposed to use SDL2 but looking for pygame 

### ISSUE THREAD

**Issue by hanachan1026** [kivy/kivy#5667]
### Versions

* macos 10.13.1
* python 3.5.3
* kivy 1.10.0
* virtualenv 15.1.0
* pip3 9.0.2
* Kivy installation method: https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip

### Description

I run "python3 main.py"

kivy screen is open

I focus to text input

I type something and everything goes to console 

Can anyone suggest what the problem is?

**Comment by kuzeyron** [comment]
Can you paste your code here?

**Comment by bionoid** [comment]
Please include console output from running `python3 main.py`, it can contain clues

**Comment by hanachan1026** [comment]
@kuzeyron
 
```python
#-*- coding: utf-8 -*-
from kivy.config import Config
Config.set("graphics", "resizable", False)
Config.set("graphics", "width", 800)
Config.set("graphics", "height", 600)

from kivy.app import App
from kivy.core.text import LabelBase, DEFAULT_FONT
from kivy.uix.screenmanager import ScreenManager, Screen

# 日本語フォント
LabelBase.register(DEFAULT_FONT, "mplus-1m-medium.ttf")

class LoginScreen(Screen):
    def loginButtonClicked(self):
        USER_ID = self.ids["text_userID"].text
        PASSWORD = self.ids["text_password"].text
        sm.current = "input"

clas InputScreen(Screen):
    def myFunc(self): 
        something

class MyApp(App):
    def build(self):
        sm.add_widget(LoginScreen(name="login"))
        sm.add_widget(InputScreen(name="input"))
        return sm

if __name__ == '__main__':
    MyApp().run()
```


``` my.kv
<TextInput>:
    multiline: False
    write_tab: False
    font_size: 20
<Label>:
    font_size: 20
    color: 0.1, 0.1, 0.1, 1
<PaddingBoxLayout@BoxLayout>:
    padding: 20

<LoginScreen>:
    BoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: 0.9, 0.9, 0.9, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            size_hint_y: 1.5
            text: "インスタログイン"
            font_size: 32

        BoxLayout:
            orientation: "vertical"
            size_hint_y: 8.5

            PaddingBoxLayout:
                Label:
                    text: "ユーザID"
                TextInput:
                    id: text_userID

            PaddingBoxLayout:
                Label:
                    text: "パスワード"
                TextInput:
                    id: text_password
                    password: True

            Label:
                id: error_message
                text: ""
                color: 1, 0, 0, 1

            Label:
                text: ""

            PaddingBoxLayout:
                Label:
                    text: ""
                Button:
                    text: "ログイン"
                    color: 1, 1, 1, 1
                    on_press: root.loginButtonClicked()

<InputScreen>:
   something...
```

**Comment by hanachan1026** [comment]
@kuzeyron The problem occurs in ```LoginScreen```, so I skipped ```InputScreen``` code
And I actually reinstalled kivy, last time I installed it, this code was working fine

**Comment by hanachan1026** [comment]
@bionoid 

```
% python3 main.py
[INFO   ] [Logger      ] Record log in /Users/hanayatakuma/.kivy/logs/kivy_18-03-22_8.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 08:49:46)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.28.29'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel HD Graphics 5000 OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
```

**Comment by hanachan1026** [comment]
![image](https://user-images.githubusercontent.com/10656461/37723276-54f0c076-2d71-11e8-8d85-4ce000d641b9.png)

One thing I notice is even though running kivy through python, the running app name on my display is iterm2.
When it was working it was python displayed

**Comment by kuzeyron** [comment]
To me it looks like you have the 'sm' variable out of range.
Perhaps move class LoginScreen(Screen) to MyApp and link it so there might be no problems anymore.

**Comment by hanachan1026** [comment]
@kuzeyron 
Sorry my code was not complete.
Anyway I wanted to say my code is fine because it was working well before

**Comment by bionoid** [comment]
```
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame
```

In the installation link, it refers to SDL2, but for some reason pygame is used on your current installation (pygame is deprecated). **Pygame Windows provider with high-dpi (retina) display on MacOS is broken!** Maybe you just can't get the textinput focused because mouse coordinates are off? Try this:to verify:

```python
from kivy.base import runTouchApp
from kivy.uix.textinput import TextInput
from kivy.clock import Clock
ti = TextInput()
Clock.schedule_once(lambda *_: setattr(ti, 'focus', True), 1)
runTouchApp(ti)
```

> And I actually reinstalled kivy, last time I installed it, this code was working fine

I assume because SDL2 worked correctly previous install.. Could be as simple as a copy-paste error for a package name or something...

**Comment by hanachan1026** [comment]
@bionoid 
![image](https://user-images.githubusercontent.com/10656461/37747272-bcea43fa-2dc1-11e8-8618-2eb4f32b9deb.png)

Still cannot type even if it's focused

After I followed the instruction, and when I ran kivy, I got pygame is not found error.

That's why I installed pygame too

**Comment by gottadiveintopython** [comment]
It looks like similar to https://teratail.com/questions/113365

**Comment by bionoid** [comment]
> Still cannot type even if it's focused

Hmm okay, I'm not sure how bad the state of pygame is, maybe this is just straight up broken. All I'm sure of is that hidpi coordinates do not work. Pygame is likely the culprit, since the problem report is not common... my best suggestion is to use sdl2.

**Comment by kuzeyron** [comment]
The focus issue is everywhere.
One solution you can use:
```python
MDTextField:
    id: txt_send
    hint_text: 'What would you like to say?'
    helper_text: 'Say: Hello!'
    min_text_length: 5
    pos_hint: {'center_y': 0}
    multiline: False
    keyboard_mode: 'managed'
    on_text_validate:
        if(len(txt_send.text) > 0): root.insert(txt_send.text);txt_send.text = ''
    on_touch_down:
        txt_send.hide_keyboard()
        txt_send.show_keyboard()
```
`keyboard_mode: 'managed'` is the key.

**Comment by hanachan1026** [comment]
@gottadiveintopython Thank you, I will try this

**Comment by hanachan1026** [comment]
So the main problem is kivy is supposed to use SDL2 but looking for pygame.

I removed pygame and installed pySDL2 via pip3 but I got error

```
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 08:49:46)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_pil, img_gif (img_pygame, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_pygame'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
pygame - ImportError: No module named 'pygame'
  File "/Users/hanayatakuma/tools/InstagramTool/instaenv/lib/python3.5/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Users/hanayatakuma/tools/InstagramTool/instaenv/lib/python3.5/site-packages/kivy/core/window/window_pygame.py", line 8, in <module>
    import pygame

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by kuzeyron** [comment]
Try reinstalling Kivy the same way.

**Comment by bionoid** [comment]
Kivy has its own sdl2 bindings, it does not use pysdl2. You need the sdl2 dev libraries as described in the install link. The key point is that you need to recompile kivy when the sdl2 library has been installed.

Usually that's solved by pip uninstall kivy and then reinstall,  but you may have ended up with multiple installs somehow.

After uninstall, open python and type `import kivy`„ this should fail. If it doesn't, type `kivy.__file__` and then manually delete the orphaned copy

**Comment by gottadiveintopython** [comment]
np and sorry, the link I pasted is useless. I just realized that, and I have no idea how to resolve the problem.

**Comment by hanachan1026** [comment]
One of my concern is I installed python3 not with homebrew. But official instruction we install sdl2 and other dependencies with homebrew. I did it anyway

**Comment by hanachan1026** [comment]
@bionoid I uninstalled kivy and I could import kivy so as you said I have wrong version of kivy somewhere else

when I typed kivy.__file__ I got
```AttributeError: module 'kivy' has no attribute '__file__'```

**Comment by hanachan1026** [comment]
I tried

```USE_OSX_FRAMEWORKS=0 pip install https://github.com/kivy/kivy/zipball/master```

And got kivy 1.10.1.dev0

I found kivy/include/config.pxi
```
# Autogenerated file for Kivy Cython configuration
DEF PY3 = 1
DEF USE_RPI = 0
DEF USE_MALI = 0
DEF USE_EGL = 0
DEF USE_OPENGL_ES2 = 1
DEF USE_OPENGL_MOCK = 0
DEF USE_SDL2 = 0
DEF USE_IOS = 0
DEF USE_MESAGL = 0
DEF USE_X11 = 0
DEF USE_WAYLAND = 0
DEF USE_GSTREAMER = 1
DEF USE_AVFOUNDATION = 1
DEF USE_OSX_FRAMEWORKS = 0
DEF DEBUG_GL = 0
DEF DEBUG = False
DEF PLATFORM = "darwin"
```

**Comment by hanachan1026** [comment]
So obviously use SDL2 option is set to false, how to change this?

**Comment by hanachan1026** [comment]
I changed to macport python and problem solved! Thanks

**Comment by Amazingratman** [comment]
so this is a huge issue with kivy.... Yet I still don't understand what the actual solution is.... suxs really...
