### ISSUE TITLE
Kivy garden launch failure on windows 10

### ISSUE THREAD

**Issue by DJBlasterMaster** [kivy/kivy#5673]
### Versions

* Python: 3.6.4 (64bit)
* OS: Windows 10
* Kivy: 1.10
* Kivy installation method: pip3

### Description

After installing kivy-garden with pip3 launching garden fails

### Code and Logs

running command:
garden install resizable_behaviour

-> results in error:
python.exe C:\Program Files\Python36\Scripts\garden install resizable_behaviour
python.exe: can't open file 'C:\Program': [Errno 2] No such file or directory

Workaround is to launch the script manually:
python.exe "C:\Program Files\Python36\Scripts\garden" install resizable_behavior

seems to be just couple of " " missing from the garden launcher

**Comment by dolang** [comment]
Sounds like string quote problem, and garden doesn't like the space in 'Program Files'.

Have you tried it with a virtualenv in a directory that doesn't contain spaces?

Also, you probably want to report it instead at: https://github.com/kivy-garden/garden/issues

**Comment by DJBlasterMaster** [comment]
That fixes it allright! Thanks!
