### ISSUE TITLE
Instillation Guide

### ISSUE THREAD

**Issue by Randa1thor** [kivy/kivy#5674]
### Versions

* Python:2.7
* OS:Linux Mint 18 Cinnamon
* Kivy:latest stable 3-23-2018
* Kivy installation method : virtualenv instructions

### Description

The instructions literally say install Cython== 0.27.3

error message: amid tons of CLI text

Detected Cython version 0.27.3
    This version of Cython is untested with Kivy. While this version may
    work perfectly fine, it is possible that you may experience issues. If
    you do have issues, please downgrade to a supported version. It is
    best to use the newest supported version, 0.25.2, but the minimum
    supported version is 0.23.
  
    If your platform provides a Cython package, check if you can downgrade
    to a supported version. Otherwise, uninstall the platform package and
    install Cython via pip:
  
      pip install -I Cython==0.25.2

please fix installation guide

thanks

**Comment by dolang** [comment]
Ok let's see. `Cython==0.27.3` is the version that works with the current master branch.

You're certainly right that the documentation there is inconsistent. The table at the top seems to be outdated, while the version in the box might be too new (the latter happens because it's a variable in the source from which the website is generated).

As for your problem, try (just tested this on a Mint VM):
```shell
pip uninstall cython
pip install Cython==0.23  # that's the version of Cython that was in the docs when v1.10.0 was released
pip install kivy
```

**Comment by dolang** [comment]
Another problem here is that if I do:
```shell
pip install -I Cython==0.25.2
```
when I have an existing version of Cython, then I somehow get both of them installed on top of each other? The advice should probably be: `pip install -U --force-reinstall ...`

**Comment by Randa1thor** [comment]
I uninstalled the Cython first I use virtualenv to try and keep everything as tidy as possible and eliminate outside complications.  It works fine and probably the installation guide for all the other OS's and things is probably fine.  And ohh how I wish I could just go to python3 but alas I am stuck over here with python 2.7 for whatever reason and my clients and deadlines are too demanding to even figure out why there is a 2.7 and a 3.  Just thought I might suggest changing the virtualenv installation so that if I have to come back to kivy 2 years from now and in a hurry I won't have to remember.

Thanks for checking and I am very grateful you were able to duplicate the error I recieved.  In the times where everyone is making their own IDE's or packages or handlers this is getting increasingly more difficult.

Cheers

**Comment by Zen-CODE** [comment]
@Randa1thor. Okay, changed the docs to actually install the latest version vs. specified one. Also added a list of cython vs. kivy version which are know t work. Re: the version printed via the error message, these depend on the source code you are building with and should be accurate for the version you are currently building, this won't necessarily match the online docs.
