### ISSUE TITLE
Getting Started Drawing Python doesn't seem to work

### ISSUE THREAD

**Issue by Randa1thor** [kivy/kivy#5675]
### Versions

* Python: 2.7
* OS: Mint 18 Cinnamon
* Kivy: latest stable 3-23-2018
* Kivy installation method: virtualenv

https://kivy.org/docs/gettingstarted/drawing.html

Python code doesn't seem to work.  I don't use CSS 

code:
`from kivy.app import App
from kivy.graphics import *
from kivy.uix.widget import Widget

######################################################
class MyWidget(Widget):
    
    def __init__(self, **kwargs):
        super(MyWidget, self).__init__(**kwargs)
        self.bind(pos=self.update_canvas())
        self.bind(size=self.update_canvas())
        self.update_canvas()
            
    def update_canvas(self, *args):
        #need to reset everything
        self.canvas.clear()
        with self.canvas:
            #context instruction
            Color(0,1,0,1)
            #vertex instruction
            Ellipse (pos = self.pos, size=self.size)
######################################################

class MyApp(App):
    
    def __init__(self, **kwargs):
        super(MyApp, self).__init__(**kwargs)
    
    
    def build(self):
        return MyWidget()
    
if __name__ == '__main__':
    MyApp().run()
`
error:

self.bind(pos=self.update_canvas())
   File "kivy/_event.pyx", line 430, in kivy._event.EventDispatcher.bind (/tmp/pip-build-mB36We/kivy/kivy/_event.c:6359)
 AssertionError: None is not callable

tried commenting out the self.bind(pos errors on self.bind(size I could use the integrated method of update canvas or at least I need to be able to draw on the canvas and update.  I'm would try and break down pong and the scatter examples but I really need getting started and installation docs to work thanks and I have no use for the abstract Style sheet language as my number of elements and needs change as the program persists.  Honestly I just need to simply draw on a canvas programmably if it can be done in GWBASIC and QBASIC I'm sure it's here somewhere.
Thanks for any help.

**Comment by pythonic64** [comment]
@Randa1thor you have to function as argument in `bind` method. It must be like this, without parentheses:  
```
self.bind(pos=self.update_canvas)
self.bind(size=self.update_canvas)
```

**Comment by Randa1thor** [comment]
Score thanks 

Cheers

**Comment by pythonic64** [comment]
@Randa1thor Close the issue if this solves it :)
