### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by toldham7** [kivy/kivy#5687]
### Versions

* Python: 3.6.4
* OS: Windows 10 Build 16299.309
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I recently installed Kivy & immediately noticed an issue in the KivyMD `Kitchen Sink` demo.  UI components have a glitchy appearance.

![kivymd_kitchen_sink_glitch](https://user-images.githubusercontent.com/37935282/38143651-7e1322e2-340f-11e8-99fc-808a114e705d.PNG)

I also experienced this issue in a basic ScreenManager implementation. The first screen works as expected, but as soon as any subsequent screens are loaded, the issue appears.

![kivy_bmi_app_issue](https://user-images.githubusercontent.com/37935282/38143656-825d787a-340f-11e8-9df5-6d711f23c772.PNG)

### Code and Logs

https://gist.github.com/toldham7/e79d36d7fde0d8576f30a24b8f827a78

**Comment by toldham7** [comment]
@bionoid  Just tried it, didn't seem to fix the issue.

**Comment by tshirtman** [comment]
Can you try with a 100% zoom level in windows? we might still have issues with that.
