### ISSUE TITLE
OpenGL errors in Android 4.03  Samsung Tab P-3100

### ISSUE THREAD

**Issue by ldamas** [kivy/kivy#5692]
### Description

I/python  ( 3013):  Exception OverflowError: 'Python int too large to convert to C long' in 'kivy.graphics.context.Context.dealloc_vbo' ignored
I/python  ( 3013):  Exception OverflowError: 'Python int too large to convert to C long' in 'kivy.graphics.context.Context.dealloc_vertexbatch' ignored

### Code and Logs
This errors are due to the opengl library returning unusually large ids. It can be fixed in
kivy/grahics/context.pyx by replacing all the occurrences of "array('i')" with "array('I')"
which is the correct way to go since ids are unsigned integers. 
```

**Comment by tshirtman** [comment]
Thanks for reporting the fix as well :)
