### ISSUE TITLE
list.sort(reverse=True) throws TypeError when observed with ListProperty

### ISSUE THREAD

**Issue by Devonavar** [kivy/kivy#5694]
### Versions

* Python: 3.6.3
* OS: Ubuntu 17.10
* Kivy: 1.9.1
* Kivy installation method: pip

### Description

list.sort throws TypeError when reverse keyword is used when list is observed with a ListProperty.  Expect that complete list functionality is available when using ListProperties.

This could presumably be fixed by adding **kwargs to the sort function (File "kivy/properties.pyx", line 751 (master branch) (line 678 in v1.9.1 which I'm using), in kivy.properties.ObservableList.sort)

I could probably fix this myself, but:

1: I'm an amateur coder, I don't know the kivy codebase, and I've never used git before.  There's lots of potential for me to screw this up.
2: It looks like there's lots of other functions that probably need the same fix ... right now, it appears any keyword arguments to lists do not work properly.

So, I'd rather report this here and have someone who is familiar with the code base fix it more completely than I can.

### Code and Logs

```python
from kivy.properties import ListProperty
from kivy.event import EventDispatcher

class testlist(EventDispatcher):
	l = ListProperty([])
	def __init__(self):
		super().__init__()
		self.l = [1,2,3,4]

if __name__ == '__main__':
	l = testlist()
	l.l.sort() # works fine
        [1,2,3,4].sort(reverse=True) # works fine
	l.l.sort(reverse=True) # throws TypeError
```

**Comment by dolang** [comment]
Can confirm this is still the case with current master branch (`1.10.1.dev0`).

I can't promise a fix myself, but I can at least explain why it is the way it is:

`ListProperty` uses a custom [ObservableList](https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L687) in the background, which is implemented in Cython and does not accept any `**kwargs` at all for `reverse()`.  Also -- and that may be the underlying reason -- there's only one implementation of `ObservableList`, i.e. no attempt is made to distinguish between supported Python interpreters.

As a workaround, you could use `sort()` and `reverse()` separately.

**Comment by Devonavar** [comment]
I'll see what I can do, but the reason I'm on 1.9.1 is because I was having trouble getting 1.10 to run on Ubuntu 17.10.  I'll try again once Bionic Beaver is released ... I suspect the return to X.org will make things happy again.

**Comment by Devonavar** [comment]
Also, I'm currently using
`l.l = sorted(l.l, reverse=True)`
as a workaround, which works, but no longer sorts the list in place.  I would imagine your workaround using sort() and reverse() would get around that restriction as well.

**Comment by dolang** [comment]
@Devonavar Just that there's no misunderstanding here:

The issue you describe has not been fixed. Upgrading to 1.10 won't help.

And yes, it would get around that restriction. However, the drawback is that the event is fired twice that way.

**Comment by Devonavar** [comment]
Thanks ... I actually misread your comment in a different way ... I thought you were asking *me* to confirm that the bug still exists in 1.10.1.dev0 .

All clear now. ;)
