### ISSUE TITLE
Kivy receiving touch events relative to the screen and touch pad (instead of mouse cursor and touches within the window)

### ISSUE THREAD

**Issue by retrop7** [kivy/kivy#5697]
### Versions
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.4 (default, Jan  5 2018, 02:35:40) 
* OS: Arch Ainux - Gnome Wayland Lib-input
* Kivy installation method: arch package

### Description

I am very new to kivy. I have just started reading the documents but my first attempt at a button app was foiled. forgive my general ignorance but I feel like this must be a bug. 
Any time I press anywhere on my screen or touch pad the button is triggered. 
Further investigation leads me to believe Kivy is receiving all touch events from the system - relative to the input (i.e. screen touches are relative to the screen and touch pad touches are relative to the touch pad and not the cursor) and behaving as if they were relative to the window - a top right touch on the touch pad behaves like a top right touch in the app.

With the below code I can touch any portion of my touch pad and press one of the two buttons (depending on which side of the touch pad I touch)

### Code and Logs
from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button

def callback(instance):
    print('The button <%s> is being pressed' % instance.text)

btn1 = Button(text='Hello world 1')
btn1.bind(on_press=callback)
btn2 = Button(text='Hello world 2')
btn2.bind(on_press=callback)

class ButtonTest(GridLayout):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.cols = 2
        self.add_widget(btn1)
        self.add_widget(btn2)

class MyApp(App):

    def build(self):
        return ButtonTest()

if __name__ == '__main__':
    MyApp().run()

**Comment by retrop7** [comment]
Thanks for the info. It looks like in the short term I'll need to find a different development environment - Windows?
I really just want to play around with gui development in Python.

**Comment by bionoid** [comment]
@retrop7 Windows should work fine with the touhscreen. 

I've not fiddled with this in a long time, but you should be able to run on the linux without the touchscreen -- try to edit your `~/.kivy/config.ini` at the `[input]` section, it probably looks like this:

```
[input]
mouse = mouse
%(name)s = probesysfs
```

Comment the probesysfs, so only `mouse = mouse` is left, and then try to run an app

**Comment by tshirtman** [comment]
I have a partial solution to this in PR #5659 using postproc:calibration, if you want to test, it has issues when the window is rotated, but that's an edge case that's unlikely to be combined with a non-fullscreen app.

**Comment by retrop7** [comment]
It is perhaps a moot point as this has already been closed. But I have switched to windows so I cannot test anything. I do appreciate the responses. Sorry, I didn't notice the awaiting-reply label.

**Comment by uromastix87** [comment]
I am having the exact same issue as well. I am running Arch Linux with xf86-input-libinput. I have a Dell XPS 15 9560 with a touchscreen. I would like the touch screen and the mouse to work normally. It's like Kivy has mapped the screen onto my touchpad so it acts like a touchscreen and a touchpad combined.

**Comment by louisc** [comment]
Ubuntu user (18.04) here on a Thinkpad X1 Carbon. Same issue, the mouse pad is mapped to the window, so, no matter where cursor is, touching left of mouse pad touches left of Kivy window, right to right etc.

**Comment by mgc8** [comment]
I am using Ubuntu 18.04 on a Dell XPS 15 7590, and had this exact same problem -- but only after installing _libinput_, before that there was no issue. It seems that _libinput_ appears like a touchscreen to Kivy, and it processes all the events, not just the ones inside the window.

I can confirm that the comment from "ghost" above fixed the issue for me:
```
[input]
mouse = mouse
#%(name)s = probesysfs << _commented out_
```

**Comment by manasrda** [comment]
> @retrop7 Windows should work fine with the touhscreen.
> 
> I've not fiddled with this in a long time, but you should be able to run on the linux without the touchscreen -- try to edit your `~/.kivy/config.ini` at the `[input]` section, it probably looks like this:
> 
> ```
> [input]
> mouse = mouse
> %(name)s = probesysfs
> ```
> 
> Comment the probesysfs, so only `mouse = mouse` is left, and then try to run an app

I am using Ubuntu 20.04 on a Dell XPS 13 and had a similar problem and this fixed the problem for me.

**Comment by snuq** [comment]
This is still an issue in 2025... just ran into this on my Dell XPS laptop with linux. 
The fix works, but I still want to know - what is this 'probesysfs' thing, and why this is enabled by default?
I will now be putting the following code into my apps:

```
if platform == 'linux':
    #Linux has some weirdness with the touchpad by default... remove it
    options = Config.options('input')
    for option in options:
        if Config.get('input', option) == 'probesysfs':
            Config.remove_option('input', option)
```
