### ISSUE TITLE
A simple window cannot render correctly

### ISSUE THREAD

**Issue by bb4net** [kivy/kivy#5700]
### Versions

* Python: 3.6.5
* OS: MacOS High Sierra 10.13.4 
* Kivy: 1.10.1-dev0
* Kivy installation method: pip
* PyCharm: 1018.1
### Description
A simple window cannot render correctly after some mouse actions or after disable/enable 
Tab Bar.
The Kivy-App was started with PyCharm Python Console.
The App won't close.

![kivy 1](https://user-images.githubusercontent.com/4218627/38875752-63635962-425b-11e8-9f55-d189ff558fbc.png)

Picture "kivy 1"  is after right mouse click.

![kivy 2](https://user-images.githubusercontent.com/4218627/38875756-6521eed0-425b-11e8-8da3-cd625c7a26c2.png)

Picture "Kivy2" is after  disable Tab Bar.

### Code and Logs

```python
from kivy.app import App
from kivy.uix.button import Button
class TestApp(App):
    def build(self):
        return Button(text='Hello World')
TestApp().run()
```

**Comment by bb4net** [comment]
Oudside Pycharm there is the same behavior.  Here the console log started outside of PyCharm:

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kivy.app import App
[INFO   ] [Logger      ] Record log in /Users/bernd/.kivy/logs/kivy_18-04-17_4.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-ae3665c, 20180417
[INFO   ] [Python      ] v3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
>>> from kivy.uix.button import Button
[INFO   ] [Text        ] Provider: sdl2
>>> 
>>> class TestApp(App):
...     def build(self):
...         return Button(text='Hello World')
... 
>>> TestApp().run()
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.32.48'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel HD Graphics 4000 OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...

**Comment by tshirtman** [comment]
I assume a "resize" event of the window is not managed, i'm not familiar with the "tab bar" feature of osx, but certainly we need to add support for some event in the SDL2 window provider to fix that, if someone with access to a mac can check…
