### ISSUE TITLE
Multiple `ScreenManager`s does not work for screens which also inherit from `StencilView`

### ISSUE THREAD

**Issue by omermazig** [kivy/kivy#5710]
### Versions

* Python: 3.6
* OS: Ubuntu 16.04.4 x64
* Kivy: 1.10

### Description

In the very simple usage example below, The second **screen manager** does not work as expected (Just switches between blank **screen**s when you click on where it should be). When you remove the inheritance from `StencilView`, everything works.

I generated this example specially for this issue, and in our code (where I encountered this bug) we actually do have to have the screen inherit from `StencilView` (as oppose to this example where it's pretty redundant).

Can anyone tell me why this happens or preferably how to fix/workaround this? It took me like a day to even understand that this was the problem and I still don't know (I can't find StencilView implementation).

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.gridlayout import GridLayout
from kivy.uix.stencilview import StencilView
from kivy.uix.screenmanager import ScreenManager, Screen

Builder.load_string("""
<GirisEkrani>:
    Button:
        text: "İleri"
        on_release: root.manager.current = root.manager.next()
<KontrolEkrani>:
    Button:
        text: "Geri"
        on_release: root.manager.current = root.manager.previous()
""")


class GirisEkrani(Screen, StencilView):
    pass


class KontrolEkrani(Screen, StencilView):
    pass


class ekranApp(App):
    def build(self):
        root = GridLayout(cols=2)

        screen_manager1 = ScreenManager()
        screen_manager1.add_widget(GirisEkrani(name="giris_ekrani"))
        screen_manager1.add_widget(KontrolEkrani(name="kontrol_ekrani"))

        screen_manager2 = ScreenManager()
        screen_manager2.add_widget(GirisEkrani(name="giris_ekrani"))
        screen_manager2.add_widget(KontrolEkrani(name="kontrol_ekrani"))

        root.add_widget(screen_manager1)
        root.add_widget(screen_manager2)
        return root


if __name__ == "__main__":
    ekranApp().run()

```

**Comment by bionoid** [comment]
> I can't find StencilView implementation

It's applied to widgets via [kvlang canvas rules in data/style.kv](https://github.com/kivy/kivy/blob/1.10.0/kivy/data/style.kv#L249-L262), and the stencil instructions themselves are in [graphics/stencil_instructions.pyx](https://github.com/kivy/kivy/blob/1.10.0/kivy/graphics/stencil_instructions.pyx) .. unfortunately that is the end of the road for my knowledge of the implementation...

Seems like it's related to RelativeLayout, maybe it's just straight up applying the stencil at the wrong coordinates. Not sure what's the appropriate way to fix it.. Best guess for a quick workaround is to apply the stencil at ScreenManager instead of individual Screens... Obviously that won't work if you are depending on drawing outside the ScreenManager

```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string("""
<RelativeStencil@RelativeLayout+StencilView>:

BoxLayout:
    RelativeStencil:
        Button:
    RelativeStencil:
        Button:
"""))
```

**Comment by gottadiveintopython** [comment]
`StencilView` is not designed for `RelativeLayout` type widgets.  So one of solutions is create your own `StencilView` which specialized for `RelativeLayout` type widgets.

```python3
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.gridlayout import GridLayout
# from kivy.uix.stencilview import StencilView
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.factory import Factory

Builder.load_string("""
<GirisEkrani>:
    Button:
        text: "İleri"
        on_release: root.manager.current = root.manager.next()
<KontrolEkrani>:
    Button:
        text: "Geri"
        on_release: root.manager.current = root.manager.previous()
<StencilView4RelativeLayout@Widget>:
    canvas.before:
        StencilPush
        Rectangle:
            pos: 0, 0  # has to be relative to self.pos
            size: self.size
        StencilUse
    canvas.after:
        StencilUnUse
        Rectangle:
            pos: self.pos  # has to be not relative to self.pos
            size: self.size
        StencilPop
""")


class GirisEkrani(Screen, Factory.StencilView4RelativeLayout):
    pass


class KontrolEkrani(Screen, Factory.StencilView4RelativeLayout):
    pass


class ekranApp(App):
    def build(self):
        root = GridLayout(cols=2)

        screen_manager1 = ScreenManager()
        screen_manager1.add_widget(GirisEkrani(name="giris_ekrani"))
        screen_manager1.add_widget(KontrolEkrani(name="kontrol_ekrani"))

        screen_manager2 = ScreenManager()
        screen_manager2.add_widget(GirisEkrani(name="giris_ekrani"))
        screen_manager2.add_widget(KontrolEkrani(name="kontrol_ekrani"))

        root.add_widget(screen_manager1)
        root.add_widget(screen_manager2)
        return root


if __name__ == "__main__":
    ekranApp().run()
```

**Comment by omermazig** [comment]
Thanks for the answers. I ended up just adding my `StencilView` as a widget to my screen (instead of multiple inheritance)
