### ISSUE TITLE
Last nightly builds dated January 3rd

### ISSUE THREAD

**Issue by robertour** [kivy/kivy#5713]
According to the [installations instructions](https://kivy.org/docs/installation/installation-windows.html#install-nightly-win-dist):

> Snapshot wheels of current Kivy master are created on every commit to the master branch of kivy repository.

But the files in [the nightly build index](https://kivy.org/downloads/appveyor/kivy/) are dated January 3rd. 

Are those files really the last wheels? I am trying to test typing in chinesse, related to [this issue](https://github.com/kivy/kivy/pull/5109)

**Comment by KeyWeeUsr** [comment]
Please check 2018-05-02 05:00 UTC, there should be a build triggered at Kivy's [Appveyor](https://ci.appveyor.com/project/KivyOrg/kivy/history).

**Comment by robertour** [comment]
Thanks! I can see that the dates of the wheels have been updated.
[https://kivy.org/downloads/appveyor/kivy/](https://kivy.org/downloads/appveyor/kivy/)
