### ISSUE TITLE
Memory leak when displaying and removing multiple image widgets sequentially

### ISSUE THREAD

**Issue by vvanhee** [kivy/kivy#5718]
### Versions

* Python: 2.7.13
* OS: Raspbian 9 (stretch)
* Kivy: v1.10.1.dev0, git-8921b6a, 20180425
* Kivy installation method: manual

### Description
I was trying to make a slide show on my Raspberry Pi 3 with official touchscreen. I noticed that as I got further along in the slide show, images would stop appearing, displaying only black boxes. It seemed to be related to the total size of the images displayed. So I made the test below, with stops displaying jpg files after about image number 7. Using larger image files results in images not appearing sooner. I think the images should be released when the widgets are cleared, but they don't appear to be doing that. Memory usage seems to be increasing continually even though widgets are cleared, if the testing below is correct.

### Code and Logs

```python
import kivy
kivy.require('1.0.6')
from kivy.clock import Clock
import urllib
from kivy.app import App
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.image import Image
from kivy.uix.label import Label
from functools import partial
from kivy.core.window import Window
import shutil
import time
import psutil
import os

def memcheck():
    # return the memory usage in MB
    process = psutil.Process() #os.getpid()
    mem = process.memory_info().rss / float(2 ** 20)
    mem = str(mem) + "MB"
    return mem
    
def displayphoto(i, root, *largs):
    name=str(i)+".jpg"
    root.clear_widgets()
    print("cleared widgets, memory at " + memcheck())
    print("photo " + name + ", adding widget")
    img = Image(source=name, nocache=False)
    root.add_widget(img)
    label = Label(text=name)
    root.add_widget(label)
    print("added widget, memory at " + memcheck())

class NoscatterApp(App):
    def build(self):
        root = FloatLayout()
        #os.remove("*.jpg")
        print("downloading photo...")
        urllib.urlretrieve("https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Shed_with_green_roof_at_Lyngen_fjord%2C_2012_June.jpg/1200px-Shed_with_green_roof_at_Lyngen_fjord%2C_2012_June.jpg", "main.jpg")
        print('done!')
        for i in range(0, 10):
            name=str(i)+".jpg"
            shutil.copy("main.jpg", name)        
            Clock.schedule_once(partial(displayphoto, i, root), i*2)
        return root
        
    def on_pause(self):
        return True
    
if __name__ == '__main__':
    NoscatterApp().run()
```

**Comment by bionoid** [comment]
Did you try manual garbage collection? As in `import gc` and after clear_widgets do `gc.collect()`? It doesn't seem like it should be needed, but still worth double-checking. If it's related to gl, maybe [the script linked by tito here](https://github.com/kivy/kivy/issues/5581#issuecomment-374894043) can be helpful in tracking it down further

**Comment by vvanhee** [comment]
Ok, that helps! It still doesn't display images after 7 just adding garbage collection, but when I also change nocache to True in the Image creation, it does work perfectly!

**Comment by tshirtman** [comment]
seems the cache is doing its job, you might want to experiment with the `limit` parameter of the Image cache, as by default, it doesn't try to check what fits in memory or not. I tried to do a size limit feature quite some time ago, but it turns out estimating the size of python object is not easy, so users had to provide the function to do that themselves, which didn't make it easy to use, anyway, that's not currently a supported feature.
