### ISSUE TITLE
OverflowError: value too large to convert to unsigned short

### ISSUE THREAD

**Issue by ryzenX** [kivy/kivy#5719]
hello, when i create grah plot and i define y axis interval >32000 i have this error
for example :
```
graph = Graph(xlabel='X', ylabel='Y', x_ticks_minor=5,
                           x_ticks_major=25, y_ticks_major=1,
                           y_grid_label=False, x_grid_label=True, padding=5,
                           x_grid=True, y_grid=False, xmin=-0, xmax=100, ymin=0, ymax=100000)
```

i have this error 
```
   File "kivy\graphics\memory.pxi", line 72, in kivy.graphics.vertex_instruction
s._ensure_ushort_view (kivy\graphics\vertex_instructions.c:6404)
 OverflowError: value too large to convert to unsigned short
```

**Comment by tshirtman** [comment]
i assume it doesn't happen anymore if you raise y_ticks_major enough so `(ymax - ymin)/y_ticks_major` is less than 32768? (so here `4` could would be a good value), it is a technical restriction coming from the way Graph draw its axis, it could probably be lifted by using multiple Mesh instructions when the count is too big.

(reading the code, the mesh is used for both x (major and minor) and y (major and minor) ticks, so the real constraint would be more like `(ymax - ymin)/y_ticks_major + (ymax - ymin)/y_ticks_minor + (xmax - xmin)/x_ticks_major + (xmax - xmin)/x_ticks_minor < 32768`)

**Comment by tshirtman** [comment]
closing here since it's specific to the garden.graph module.
