### ISSUE TITLE
Touch Input not Recognised in Kivy only 

### ISSUE THREAD

**Issue by mattaq31** [kivy/kivy#5720]
I have implemented the standard Pong tutorial, which works perfectly.  However, touch input from my USB touchscreen fails to work on Kivy, even with the touchtracer application.

I have also tried the common fix which is adding the following code to ~/.kivy.config.ini:

mtdev_%(name)s = probesysfs,provider=mtdev
hid_%(name)s = probesysfs,provider=hidinput

But this has not changed anything.

The logs I receive when I start any Kivy application are the following:

[INFO   ] [Logger      ] Record log in /home/matt/.kivy/logs/kivy_18-04-30_4.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 17.2.8>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Iris Plus Graphics 650 (Kaby Lake GT3) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] NPOT texture support is available

I am running Ubuntu 16.04 LTS on an Intel NUC7I7BNH with a GeChic 1002 USB touchscreen.

**Comment by tshirtman** [comment]
i'd advise trying with select_all=1 (see https://kivy.org/docs/api-kivy.input.providers.probesysfs.html).
