### ISSUE TITLE
Kivy suppresses matplotlib plots

### ISSUE THREAD

**Issue by TJ-C** [kivy/kivy#5721]
### Versions

* Python: 3.6.5
* OS: MacOS High Sierra 10.13.4
* Kivy: 1.10.1.dev0
* matplotlib: 2.2.2
* Kivy installation method: 
    brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer
    pip install Cython==0.26.1 
    pip install https://github.com/kivy/kivy/archive/master.zip

### Description

Without the fix detailed in [#5208](https://github.com/kivy/kivy/issues/5208) drawing continues where it has left off and not from where the mouse pointer is currently located.

if the fix above is applied, then drawing works as expected, however, matplotlib no longer shows a plot. See code example below.

### Code and Logs

```python

 import matplotlib
 matplotlib.use('Agg') # comment this line to see effect 
 from matplotlib import pyplot as plt

 from kivy.app import App
 from kivy.uix.widget import Widget
 from kivy.graphics import Color, Ellipse, Line
 from kivy.uix.button import Button`


 x = []
 y = []

 class MyPaintWidget(Widget):

    def on_touch_down(self, touch):
        with self.canvas:
            Color(1, 1, 0)
            d = 30.
            Ellipse(pos=(touch.x - d / 2, touch.y - d / 2), size=(d, d))
            touch.ud['line'] = Line(points=(touch.x, touch.y))

    def on_touch_move(self, touch):
        touch.ud['line'].points += [touch.x, touch.y]
        x.append(touch.x)
        y.append(touch.y)

    def on_touch_up(self, touch):
        plt.plot(x, y)
        plt.show()


 class MyPaintApp(App):

     def build(self):


        return MyPaintWidget()



 if __name__ == '__main__':
     MyPaintApp().run()


```

**Comment by TJ-C** [comment]
I've fixed this by changing the following:

```python
matplotlib.use('GTKAgg')
from matplotlib import pyplot as plt
```

And to refresh the plot:

``` python
    def on_touch_up(self, touch):
        plt.close()
        plt.plot(x, y)
        plt.show(block=False)
```

**Comment by LogicalDash** [comment]
Seems like only a partial solution, since you might want the app to run on a platform without GTK.

**Comment by TJ-C** [comment]
Correct, these were the options I was presented with for matplotlib.use:
'GTK', 'GTKAgg', 'GTKCairo', 'GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'gdk', 'pdf', 'pgf', 'ps', 'svg', 'template'.

So I guess one has to select the correct option to resolve this issue depending on their environment.

**Comment by dessant** [comment]
I think you'll find success with the object-oriented matplotlib API, you'd typically use Agg, render the plot and grab the texture, and finally display it on a Kivy Widget canvas. I found an old example that may help, you'll need to draw the line to the ax and update it whenever needed based on touches, then update the texture.

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.graphics.texture import Texture
from kivy.metrics import Metrics, dp

from matplotlib.backends.backend_agg import FigureCanvas
from matplotlib.figure import Figure


kv = """
<Test>:
    tex: None
    box: box
    canvas.before:
        Color:
            rgba: 1, 1, 1, 0.8
        Rectangle:
            pos: self.pos
            size: self.size
    Widget:
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
            Rectangle:
                pos: self.pos
                size: self.size
                texture: root.tex
        id: box
        size_hint: None, None
        size: 120, 120
"""

Builder.load_string(kv)


class Test(Factory.AnchorLayout):
    def __init__(self, *args, **kwargs):
        super(Test, self).__init__(*args, **kwargs)

        dpi = Metrics.dpi
        w = float(120)
        h = float(120)

        self.add_plot(w, h, dpi)

    def add_plot(self, w, h, dpi):
        self.fig = Figure()
        self.fc = FigureCanvas(self.fig)

        ax = self.fig.add_subplot(111)

        self.fig.set_dpi(dpi)
        self.fig.set_size_inches(w / dpi, h / dpi)

        # add your stuff

        self.fig.canvas.draw()
        buf = self.fig.canvas.buffer_rgba()
        l, b, w, h = self.fig.bbox.bounds
        tex = Texture.create(size=(w, h))
        tex.blit_buffer(bytes(buf), colorfmt='rgba', bufferfmt='ubyte')
        tex.flip_vertical()

        self.tex = tex


class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    TestApp().run()
```

If you need further help with mpl or Kivy, make sure to join our support channels.
https://github.com/kivy/kivy#support
