### ISSUE TITLE
mouse_pos interacts with dead widgets (and widgets that aren't part of the Window tree)

### ISSUE THREAD

**Issue by Devonavar** [kivy/kivy#5723]
### Versions

* Python:  3.6.3
* OS: Ubuntu 17.10
* Kivy: 1.9.1
* Kivy installation method: pip

### Description
I'm using mouse_pos to implement hover behaviour with the mouse (popups).  I bind to `Window.mouse_pos` and then add a widget, removing it when I'm done with it.

I'm having an issue with removed widgets continuing to handle mouse_pos events (among others), and therefore causing unexpected callback to my popup function.  This issue is most obvious with removed widgets that are no longer referenced (and therefore my expectation is that I should no longer be able to interact with them in any way, since they will be garbage collected).  The issue also occurs with widgets that have been removed but a reference is kept (i.e. it occurs with any widget that is not part of the root widget tree).

My expectation is that mouse_pos would not cause collisions with widgets that are not part of the root widget tree.

This a side-effect of the fact that all widgets get all events, and that `collide_point` simply checks whether two points overlap, without considering whether the two points are in the same domain, so it's arguably correct behaviour.  The two points *do* overlap ... it's just not logical behaviour from a user perspective.

The test code shows this:  Mousing over the two labels causes the widget name to be printed, even after the widgets have been removed.  Collecting the garbage after the labels have been removed stops this behaviour.

From a user perspective, it's very weird that the behaviour of the program is dependent on when garbage collection happens (which should be an invisible process), which is what pushes this into the realm of being a bug rather than just an inconvenient design decision.

Workarounds:  Call garbage collection manually whenever a widget is removed, or manually check whether a widget is in the root widget tree before testing for collisions.

### Code and Logs

```python
import kivy

from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window
from kivy.uix.label import Label
from kivy.properties import ObjectProperty
from kivy.event import EventDispatcher

root = Builder.load_string('''
#:import gc gc

FloatLayout:
    extrawidgets: extrawidgets
    Button:
        pos: 10, 200
        size_hint: .25, .1
        text: 'Remove extra widgets'
        on_press: extrawidgets.clear_widgets()
    Button:
        pos: 10, 100
        size_hint: .25, .1
        text: 'Collect garbage'
        on_press: gc.collect()
    FloatLayout:
        id: extrawidgets
''')

class DeadWidgets(App):
    
    def build(self):
        root.extrawidgets.add_widget(MouseOverLabel(text='Widget 1', pos_hint={'x':.5,'y':.4}, size_hint=(.1,.1)))
        root.extrawidgets.add_widget(MouseOverLabel(text='Widget 2', pos_hint={'x':.5,'y':.6}, size_hint=(.1,.1)))                                    
        return root

class MouseOverLabel(Label):    
    def __init__(self, **kwargs):
        Window.bind(mouse_pos=self.on_mouse_pos)
        super().__init__(**kwargs)
        
    def on_mouse_pos(self, mouse, pos):
        collision = self.collide_point(*self.to_widget(*pos))
        if collision:
            print('Mouseover widget', self.text, 'at', pos)

if __name__ == '__main__':
    DeadWidgets().run()


```

**Comment by Zen-CODE** [comment]
This is not a bug. You are specifically binding to the window event and never remove that binding, so it fires whether the widget is on screen or not. This is behaviour you have added, so need to handle that yourself. You can verify yourself that the 'on_touch' event is no longer fired when you remove it. But the binding you've added yourself, you would need to remove.

You can use the on_parent for that as illustrated below.
```
from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window
from kivy.uix.label import Label
from kivy.properties import ObjectProperty
from kivy.event import EventDispatcher

root = Builder.load_string('''
#:import gc gc

FloatLayout:
    extrawidgets: extrawidgets
    Button:
        pos: 10, 200
        size_hint: .25, .1
        text: 'Remove extra widgets'
        on_press: extrawidgets.clear_widgets()
    Button:
        pos: 10, 100
        size_hint: .25, .1
        text: 'Collect garbage'
        on_press: gc.collect()
    FloatLayout:
        id: extrawidgets
''')


class DeadWidgets(App):

    def build(self):
        root.extrawidgets.add_widget(
            MouseOverLabel(text='Widget 1', pos_hint={'x': .5, 'y': .4},
                           size_hint=(.1, .1)))
        root.extrawidgets.add_widget(
            MouseOverLabel(text='Widget 2', pos_hint={'x': .5, 'y': .6},
                           size_hint=(.1, .1)))
        return root


class MouseOverLabel(Label):
    def __init__(self, **kwargs):
        Window.bind(mouse_pos=self.on_mouse_pos)
        super().__init__(**kwargs)

    def on_mouse_pos(self, mouse, pos):
        collision = self.collide_point(*self.to_widget(*pos))
        if collision:
            print('Mouseover widget', self.text, 'at', pos)

    def on_touch_down(self, touch):
        print("Widget touched. {}".format(touch.pos))
    
    def on_parent(self, widget, parent):
        if parent is None:
            Window.unbind(mouse_pos=self.on_mouse_pos)


if __name__ == '__main__':
    DeadWidgets().run()
```
