### ISSUE TITLE
[wishlist] Android launcher: Please build with Python 3

### ISSUE THREAD

**Issue by chrysn** [kivy/kivy#5724]
The [Android launcher for Kivy](https://kivy.org/docs/guide/packaging-android.html#packaging-your-application-for-kivy-launcher), as available for download as an APK, currently ships with Python 2.7.

Please consider building a Python 3 version in parallel (or shipping both interpreters and selecting the Python version in android.txt) so that current programs can be tested and developed in this environment as well. (Personally, my interest in working with it starts when https://github.com/kivy/kivy/pull/5241 is merged -- that's a feature that only makes sense to use with Python 3, ideally 3.6 or later.)

**Comment by tshirtman** [comment]
That's probably more relevant on the python-for-android project, since that's where the launcher code is.

**Comment by gottadiveintopython** [comment]
Have you tried [new Kivy-Launcher](https://github.com/kivy/kivy-launcher)?
It have some bugs but worked for me.

**Comment by chrysn** [comment]
I haven't; is there an APK available somewhere?

**Comment by gottadiveintopython** [comment]
@chrysn 
I have an apk that I build a month ago. But just like @kuzeyron said, you should build an apk yourself, probabely.
