### ISSUE TITLE
[Wishlist] Need a sure way of packaging kivy built application with tensorflow into a distributable

### ISSUE THREAD

**Issue by Layman806** [kivy/kivy#5725]
### Versions

* Python: 3.6.3
* OS: Windows 10 64-bit
* Kivy: 1.10.0
* Kivy installation method: pip install --upgrade kivy

### Description

I built the application for my major project, and I am very thankful for you developers who created this amazing framework. I am facing one slight issue, which appears pronounced in all of the python community: distribution. I need to use Python 3.6, as tensorflow wouldn't work on Python 3.4. I tried various methods, but I stand stumped. I tried PyInstaller, and followed the official instructions on the website, but as soon as I launch the final executable, it crashed. I also tried Nuitka, which doesn't end with an error, but posts a bunch of warnings, and gets stuck midway.

A packaging method is required as software development tool. That would make kivy a perfect software development platform. Please note that this is a kind request, not an ignorant post.
Thank you.

**Comment by tshirtman** [comment]
I'm not sure there is something we can act on here, the report doesn't say if the error is related to our packaging instructions for kivy not working with tensorflow, or if there is some other issue there? Maybe start by asking for support on the various channels before opening a bug with more info? I've been using pyinstaller packaging for windows with success for a long time, though never with tensorflow yet. Please profide more info so we can reopen if there is something to do on our side.
