### ISSUE TITLE
No module named 'Kivy'

### ISSUE THREAD

**Issue by cTas0099** [kivy/kivy#5726]
### Versions

* Python: 3.6.4
* OS: archlinux
* Kivy: python-kivy-1.10.0-1
* Kivy installation method: pacman -S python-kivy

### Description

Hello, I installed python-kivy-1.10.0-1, buildozer, and when I try to run a file with kivy I get an error:

[user@revenge buildozer]$ python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from kivy.app import App
ModuleNotFoundError: No module named 'kivy'
 

Also tried to install Kivy in different ways

[user@revenge Kivy-1.10.0]$ python3 setup.py build_ext
Using distutils

Detected Cython version 0.25
Using this graphics system: OpenGL
GStreamer found via pkg-config
SDL2 found via pkg-config
SDL2: found SDL header at /usr/include/SDL2/SDL.h
SDL2: found SDL_mixer header at /usr/include/SDL2/SDL_mixer.h
SDL2: found SDL_ttf header at /usr/include/SDL2/SDL_ttf.h
SDL2: found SDL_image header at /usr/include/SDL2/SDL_image.h
fatal: not a git repository (or any of the parent directories): .git
 /home/user/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'dependency_links'
   warnings.warn(msg)
 /home/user/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
   warnings.warn(msg)
 /home/user/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'
   warnings.warn(msg)
running build_ext
 Traceback (most recent call last):
   File "setup.py", line 1060, in <module>
     ] if not skip_cython else [])
   File "/home/user/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
     dist.run_commands()
   File "/home/user/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
     self.run_command(cmd)
   File "/home/user/anaconda3/lib/python3.6/distutils/dist.py", line 973, in run_command
     cmd_obj.ensure_finalized()
   File "/home/user/anaconda3/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
     self.finalize_options()
   File "setup.py", line 251, in finalize_options
     retval = build_ext.finalize_options(self)
   File "/home/user/anaconda3/lib/python3.6/site-packages/Cython/Distutils/build_ext.py", line 19, in finalize_options
     self.distribution.ext_modules)
   File "/home/user/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 809, in cythonize
     aliases=aliases)
   File "/home/user/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 752, in create_extension_list
     **kwds))
   File "setup.py", line 511, in __init__
     self.sources = args[1]
 IndexError: tuple index out of range

**Comment by cTas0099** [comment]
BUT, when the command python2 main.py everything starts working .. how do I connect Kivy and python3?

[user@revenge buildozer]$ python2 main.py
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_18-05-04_1.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.14 (default, Apr 16 2018, 20:08:15) 
[GCC 7.3.1 20180406]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 18.0.2>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event8
[INFO   ] [MTD         ] Read event from </dev/input/event8>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event8". Please ensure you have the appropriate permissions.
[INFO   ] [Base        ] Leaving application in progress...

**Comment by pkemarco** [comment]
Hello. Try to do a update of all things : buildozer, cython, etc ...

2018-05-03 18:46 GMT+01:00 welcome[bot] <notifications@github.com>:

**Comment by cTas0099** [comment]
Dear pkemarco, it did not help .. (

**Comment by cTas0099** [comment]
I reinstall archlinux .. then I installed python-kivy, it all worked, after that I installed anaconda and kivy stopped working, started again to issue an error about the absence of the kivy module

**Comment by cTas0099** [comment]
maybe there are ideas how to make kivy, anaconda and python work together?

**Comment by dolang** [comment]
@cTas0099 honestly, I'd be surprised if you could make that work with Anaconda right now. Use the normal distribution for now.

**Comment by cTas0099** [comment]
@dolang 
I found how to install kivy in anaconda, but I have conflicts..

````
[user@revenge ~]$ conda install --channel https://conda.anaconda.org/wgarcia kivy
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - kivy
  - pyyaml
Use "conda info <package>" to see the dependencies for each package.

**Comment by dolang** [comment]
In case it wasn't clear: I suggest you don't try it with Anaconda, even if you can install it. I don't think it's possible to make it work right now.

But you're of course free to try, and I'd be interested in the result if you somehow manage to run it.

**Comment by cTas0099** [comment]
@dolang  
I understand you, but I really want it to start working))

**Comment by Zen-CODE** [comment]
I think should be taken up with anaconda. Kivy supports standard python. Any compatible implementation should thus work. If it does not, it is nor fully compatible and the implementation providers should address the issue?  
@cTas0099. Can you confirm you can get working in your standard python/python3?

**Comment by cTas0099** [comment]
@Zen-CODE yes, my programs run smoothly, before I installed the anaconda, and I wrote in support of the anaconda, and I was answered by a man who advised me to do so:

```
conda create -n kivyenv
source activate kivyenv
conda install -c moritzimend kivy=1.9.0 
```

the installation was successful, but now at startup it produces the following error:

```
(kivyenv) [user@revenge ~]$ python main.py
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_18-05-05_3.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name bcm
  File "/home/user/anaconda3/envs/kivyenv/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/user/anaconda3/envs/kivyenv/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - ImportError: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
  File "/home/user/anaconda3/envs/kivyenv/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/user/anaconda3/envs/kivyenv/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

x11 - ImportError: No module named window_x11
  File "/home/user/anaconda3/envs/kivyenv/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by Zen-CODE** [comment]
It Have you tried installing all the SDL dependencies into your conda environment?

**Comment by cTas0099** [comment]
@Zen-CODE 
I'm just dealing with this)

**Comment by Divyateja04** [comment]
try with this command

conda install -c conda-forge kivy

**Comment by matham** [comment]
Yes, we recently added kivy to conda forge. But only 3.5+.
