### ISSUE TITLE
Why are there the same objects in the RecycleView list?

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#5729]
### Versions

* Python: 2.7, 3.5
* OS: Android, Linux
* Kivy: 1.10.0

### Description

For example, I have a list of messages. I need to mark a message. I mark the message. But after looking through the list of the messages below, you can see that every tenth message was noted.

*Here's a minimal working example:*

```python
from kivy.uix.button import Button
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder
from kivy.app import App
from kivy.clock import Clock


Builder.load_string("""
<MyBox>:
    text: str(self)
    on_press: root.background_color = [.3, .4, .5, 1]

<Box>:
    RecycleView:
        id: rv
        key_viewclass: 'viewclass'
        key_size: 'height'
        bar_width: dp(4)

        RecycleBoxLayout:
            id: box
            default_size: None, None
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
            spacing: dp(0)
            padding: dp(10)
""")


class Box(BoxLayout):
    pass


class MyBox(Button):
    pass


class Test(App):

    def build(self):
        Clock.schedule_once(self.show_list, 1)
        return Box()

    def show_list(self, interval):
        data = []
        for x in range(100):
            data.append({'viewclass': 'MyBox'})
        self.root.ids.rv.data = data

```

The video shows that there are the same objects in the RecycleView list. As a result, actions with one list item result in changes in every tenth item, because this is the same object.

<img src="https://raw.githubusercontent.com/HeaTTheatR/PyConversations/master/data/images/Pydroid 3-20180504_183152[ConvGif].gif" align="center"/>

What am I doing wrong?

**Comment by Zen-CODE** [comment]
Explained on the forum.
https://groups.google.com/forum/#!topic/kivy-users/zZdmD1gRUwo

**Comment by KeyWeeUsr** [comment]
@Zen-CODE wrote:
> That;s exactly why it's called the RecycleView - it re-used the same items so that the minimum of resources are requires for long list. To properly reset each widget, see the 'refresh_view_attrs' call in the example below.

Just to have a backup here too and no dead link in the future ^^
