### ISSUE TITLE
unable to get window,abort

### ISSUE THREAD

**Issue by aminhyper** [kivy/kivy#5732]
I run kivy on python3.4 and windows 7 32bit. 
my script is very simple:

    import kivy
    kivy.require('1.10.0')
    from kivy.app import App
    from kivy.uix.button import Label
    class HelloKivy(App):
         def build(self):
              return Label(text='Hello kivy')

    hellokivy = HelloKivy()
    hellokivy.run()
and i get this error:
[CRITICAL] [App         ] Unable to get a Window, abort.
I search too many times but i didnt find any solution

**Comment by tshirtman** [comment]
There are multiple issues that can be associated with this error, please ask on the supports channels for that (with a full startup log of the app), and when you are sure it's a bug and not a misconfiguration of your system, please report a bug.
