### ISSUE TITLE
[REQUEST] clip to bounds

### ISSUE THREAD

**Issue by croccio** [kivy/kivy#5743]
is it possible to add a "clip to bound" option?

I've a layout with rounded corner
Than with asyncImage (with the same size of parent) I load an image, but image is bigger and not have corner radius.

thanks

**Comment by tshirtman** [comment]
There is Stencil, you could use a RoundedRectangle instruction in a Stencil block to clip your image to this shape.

this is a support question though, if you need more info, use the support channels.
