### ISSUE TITLE
ActionOverflow disappears when resizing the window

### ISSUE THREAD

**Issue by joneugster** [kivy/kivy#5754]
### Versions

* Python: Python 3.6.4 :: Anaconda, Inc.
* OS: macOS 10.13.4
* Kivy: 1.10.1.dev0 
* Kivy installation method: pip

### Description

The ActionOverflow button (3 vertical dots on the right of ActionBar) disappears when the window is resized and the new width is more than the button size smaller than the old width. It reappears when the window is resized to be a little bigger. See attached [mp4 file](https://github.com/kivy/kivy/files/2016571/Actionoverflow_dissapears.mp4.zip).

### Minimal example
The option button on the top-right disappears when the window is resized and the new width is smaller than the old width minus the button width.
```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

kv = """
<MyRoot>:
    orientation: 'vertical'
    ActionBar:
        ActionView:
            ActionPrevious:
                title: ''
                with_previous: True
            ActionOverflow:
                ActionButton:
                    text: 'Preferences'
                    on_press: app.open_settings()
    Label:
        text: 'placeholder'
"""
Builder.load_string(kv)


class MyApp(App):
    def build(self):
        return MyRoot()


class MyRoot(BoxLayout):
    pass


if __name__ == '__main__':
    MyApp().run()
```
### Attachments
Video showing the bug: [3.5MB](https://github.com/kivy/kivy/files/2016571/Actionoverflow_dissapears.mp4.zip) (11s)

**Comment by dolang** [comment]
Can confirm this on Windows with current master (6c7fce6).

**Comment by Codes4Fun** [comment]
so, I've come across this issue myself, and I did a fix by changing `ActionItem` `get_pack_width` to simply return `self.minimum_width`.

the reason that works for me, is because `ActionPrevious` `width` grows with the new size. so, `ActionView` `on_width` doesn't think it has enough room for all items and calls `_layout_random` instead of `_layout_all`, so using `minimum_width` ignores the expanded `ActionPrevious`.
