### ISSUE TITLE
AsyncImage does not reload itself

### ISSUE THREAD

**Issue by pythonic64** [kivy/kivy#5761]
### Versions

* Python: 2.7
* OS: Windows 10
* Kivy: master
* Kivy installation method: pip

### Description

Reloading of image displayed using AsyncImage does not work. Old image is still displayed after method `reload` is called.

### How to reproduce 
Run `main.py` from [kivy_async_image_bug.zip](https://github.com/kivy/kivy/files/2023303/kivy_async_image_bug.zip), wait until image `t1.png` is displayed and click on reload button. Images `t1.png` and `t2.png` will swap names and now new `t1.png` should be displayed, but that is not the case.

**Comment by tshirtman** [comment]
One workaround is to put `nocache: True` in the `AsyncImage` block, but i'm looking into a quickfix.

**Comment by pythonic64** [comment]
Yes, that's a workaround, but solution would have to include:
- removing of `source` from cache (category `kv.loader`, `kv.image`, `kv.texture`)
- displaying of loading-image
- async loading of image from disk and caching it with respect to `nocache` attribute
- replacing of loading-image with new image

I tried overloading `reload` method in `AsyncImage` and adding:
```
Cache.remove('kv.loader', image.source)
super(AsyncImage, self).reload()
```

as quick fix, but that isn't working, so problem must be deeper :)

**Comment by tshirtman** [comment]
This pull request should fix it.

**Comment by pythonic64** [comment]
I tested it and it works 👍 
Maybe you don't need that [new line](https://github.com/kivy/kivy/commit/12f199fa9450629e65dc7f4af65ac197f4887eac#diff-5febd68249e83301b81850ca856b0969R401)? 

If you have time, can you check https://github.com/kivy/kivy/issues/5573 and post your opinion?
