### ISSUE TITLE
Mac OSX Packaging should be automated using CI

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#5768]
Automated packages should be created using CI for OSX

- [x] Get OSX to build Kivy.app for python3.x then python2.x
- [x] Get Wheels to build using CI for python3.x then python2.x
- [x] Add tests for these packages that checks
    - [x] Kivy installation using pip(Python3)
    - [x] Kivy installation using anaconda
    - [x] Kivy installation using kivy.app
        - [x] kivy -m pip install package for python2
        - [x] for python3
    - [x] buildozer osx debug: packaging a app using buildozer
    - [ ] packaging a kivy app using pyinstaller
- [ ] run ci tests after these packages are installed

**Comment by tshirtman** [comment]
I checked the first two, whiich i think are ok, are we good enough with that to release? it's after all a bugfix release, we can always improve for the next minor release.

**Comment by akshayaurora** [comment]
We can tag,  will make sure packaging with wheels works by this weekend

**Comment by tshirtman** [comment]
The release has been tagged, as i understand it, this version will still be done manually for ssl reasons, so i moved this to the next tag.

**Comment by matham** [comment]
Re-tagged. It'll be easier to do once we drop python from our targets.

**Comment by tshirtman** [comment]
have been done recently through github actions.
