### ISSUE TITLE
Unable to install kivy on mac - gcc failed with exit status 1

### ISSUE THREAD

**Issue by nanodan** [kivy/kivy#5770]
### Versions

* Python: 2.7.14
* OS: 10.13.4 High Sierra
* Kivy: 1.10.0
* Kivy installation method: brew install with pip

### Description

Created a fresh virtual environment. Brew install all packages required. Pip install Cython==0.26.1.
Pip install kivy (tried both pip install --user kivy and pip install kivy). and every time it fails:

[screenshot](https://imgur.com/a/Y9cXh7U)

error: command 'gcc' failed with exit status 1

### Code and Logs
![kivy](https://user-images.githubusercontent.com/5264336/40485935-daebc91c-5f2d-11e8-928e-18681bc428a1.png)

**Comment by bionoid** [comment]
> Pip install Cython==0.26.1.

That's not compatible with Kivy stable (1.10.0), see [setup.py for 1.10 branch](https://github.com/kivy/kivy/blob/1.10.0/setup.py#L68-L72). You need `Cython==0.25.2` to build 1.10, or alternatively you can `pip install kivy==master` which is compatible with a wider range of Cythons, including 0.26.x

**Comment by eteamin** [comment]
I have `kivy==1.10.0` and `Cython==0.26` working fine on Siera 10.12.6

**Comment by akshayaurora** [comment]
Kivy 1.10.1 on mac provides wheels, pip install kivy should just work now, no more compiling.
Please check with kivy 1.10.1.
