### ISSUE TITLE
TextInput should hook on_size or on_width for updating line wrapping

### ISSUE THREAD

**Issue by S0AndS0** [kivy/kivy#5774]
### Versions

* Python: 2.7.12
* OS: Linux Mint 18.3
* Kivy: 1.10.0
* Kivy installation method: 

```
pip uninstall kivy

echo 'deb http://ppa.launchpad.net/kivy-team/kivy/ubuntu xenial main' | sudo tee -a /etc/apt/sources.list.d/kivy.list

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys <Kivy-GPG-pubKey-ID>
sudo apt-get update


sudo apt-get install python-kivy
```

### Description

Updating `TextInput` line wrapping when size changes didn't seem documented or coded for, and I've found a few other oddities... but I'll post solutions that I've found instead of complaining.

### Code and Logs

```python
class cTextInput(TextInput):
        def on_width(self, instance, value):
                self.text = self.text
```

### Post Script

Thanks Kivy team, this project is fantastic!

**Comment by pythonic64** [comment]
@S0AndS0 Can you post a runnable example showing the issue(s)?
