### ISSUE TITLE
Line does not draw more than ~4680 points

### ISSUE THREAD

**Issue by joneugster** [kivy/kivy#5775]
### Versions

* Python: 3.6.4, Anaconda, Inc.
* OS: macOS 10.13.4
* Kivy: 1.10.1.dev0
* Kivy installation method: homebrew & pip (from github)

### Description
Lines with more than ca. 4680 points will not draw the points all points. All points with index higher than ~4680 are simply not drawn, instead there is a buggy graphical connection to other points (in the example to point 0). In other examples this graphical connection was even weirder than here (see example).

### Examples
<img width="2569" alt="" src="https://user-images.githubusercontent.com/9141564/40648783-88cf049a-632f-11e8-9d3b-17822f86cdeb.png">

**Image1**: should display 3/4 of a circle starting at the point in image (1) and ending near point (3). However, points with index ~4680 and higher are not drawn correctly.

<img width="525" alt="screen shot 2018-05-29 at 11 13 44" src="https://user-images.githubusercontent.com/9141564/40649507-641e1a1c-6331-11e8-8dbd-83c3b79df1c6.png">

**Image2**: The line is drawn as following: It starts at the greenish point and goes around the loop on the left. Then it goes straight right and leaves the image at the blue point. Later it comes back from the bottom, bugs out in the middle, turns right (invisible) to the red 4 and comes in a big loop back to the start.
The graphical glitch seems random and changes whenever I rescale the points slightly.

### Code and Logs
This code will reproduce the error. The slider moves an ellipse along the line points to identify single points.
```python
import math
from kivy.app import App
from kivy.lang import Builder
from kivy.properties import NumericProperty, ListProperty
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.widget import Widget

# No problem if we set the number of points below 4000
n = 6000

kv = """
<MyRoot>:
    orientation: 'vertical'
    Label:
        text: 'The line is not drawn for indices bigger than ~4680.'
    Slider:
        value: 0
        on_value: app.root.ids.trk.idx = int(self.value)
        id: slider
        min: 0
        max: {0}
    Track:
        id: trk

<Track>:
    canvas:
        Color:
            rgb: .1, .7, .3
        Line:
            points: self.points
            width: 5
        Ellipse:
            pos: self.points[self.idx][0]-15, self.points[self.idx][1]-15
            size: 30,30

    Label:
        pos: self.parent.points[0]
        text: '1st point'
    Label:
        pos: self.parent.points[-1]
        text: 'last point'  
    Label:
        pos: self.parent.points[min(4680, {0})]
        text: 'last visible point'
    Label:
        pos: 400,400
        text: 'Index: ' + str(self.parent.idx)
""".format(n-1)
Builder.load_string(kv)


class MyApp(App):
    def build(self):
        return MyRoot()


class MyRoot(BoxLayout):
    pass
    
class Track(Widget):
    points = ListProperty([(380*math.cos(x*math.pi*3/2/n)+400, 380*math.sin(x*math.pi*3/2/n)+400) for x in range(n)])
    idx = NumericProperty(0)


if __name__ == '__main__':
    MyApp().run()
```

**Comment by tshirtman** [comment]
I believe Vertex instructions are limited to ~65k indices (unsigned short), Line, when width > 1, uses multiple vertices per "point" of the Line, and has to refer to these vertices in the indices list, (see `kivy.graphics.Mesh` documentation for some context), so you'll get weird behaviors when you overstep that limit, and the glitch you see might be the indices modulo 65k, or some other unspecified behavior.

We don't have the ability currently to automatically transform the instruction into multiple ones when there are too many points to fit into one, that might be a solution, another way, at least until we do that, would be to raise an exception indicating that the line has too many data points for the configuration (the limit being different depending on the line width), and to document that limitation.

**Comment by schneeammer** [comment]
Thanks for the quick response. I think I can live with a workaround, where I just split the multiple lines.

Just one question, how would you draw lines that have a black border and colored interior? b/c my approach would not work when I split the line. Also opacity will be a problem when splitting the line.

**Comment by tshirtman** [comment]
Indeed, these would be problematic, I would likely create a custom mesh, but it's a bit of work. Alternatively, maybe try using the `kivy.graphics.svg` module, and generate a source for the shape you want, and let it render it, since it already has a specific shape implementation with borders, that is able to draw lines in this way, and I think, automatically split in multiple ones when you get to the limit, it's been some time i didn't look into it though.

**Comment by tito** [comment]
Or building a mesh with a custom texture, and/or shader (like the SmoothLine implementation experiment in the garden.graph)
