### ISSUE TITLE
Carousel  looping issue

### ISSUE THREAD

**Issue by Lomelgande** [kivy/kivy#5783]
### Versions

* Python: 3.6
* OS: Ubuntu
* Kivy: 1.10
* Kivy installation method: python setup.py install (from github)

### Description
Even when loop is set to False inside a carousel, if you are on the first or last slide and drag a carousel's slide a width in distance (i.e. setting _offset >= width) the slides will still flip around to the start/end.

Within the the carousel's on__offset() method I added the following to fix the issue.

        if direction[0] == 'r':
            if _offset <= -width:
                if not self.loop and index == len(self.slides) - 1:
                    return
                index += 1
            if _offset >= width:
                if not self.loop and index == 0:
                    return
                index -= 1

I doubt this is the most efficient method by which to prevent the slide from progressing (and it only covers moving right as my carousel is a right moving carousel) but it gets the job done for now.

**Comment by EchoLynx** [comment]
I am able to reproduce this issue by running the following code on Ubuntu 16.04.3, Python 3.5.2, Kivy 1.10.0. It creates a small carousel that's in the center of the screen, but only half of the screen's height and width. This makes it easy to drag the first or last slide in the carousel farther than the carousel's width. Even though looping is disabled, the first or last slide will loop when dragged farther than the carousel's width.
```python
from kivy.app import App
from kivy.uix.carousel import Carousel
from kivy.uix.image import AsyncImage
from kivy.uix.floatlayout import FloatLayout
from kivy.config import Config

class CarouselApp(App):
        def build(self):
                floatLayout = FloatLayout()
                carousel = Carousel(direction='right',loop=False)
                carousel.size_hint = (0.5,1.0)
                for i in range(3):
                        src = "http://placehold.it/240x270.png&text=slide-%d&.png" % i
                        image = AsyncImage(source=src, allow_stretch=False)
                        carousel.add_widget(image)
                floatLayout.add_widget(carousel)
                return floatLayout

Config.set('graphics', 'fullscreen', 'auto')
CarouselApp().run()
```
