### ISSUE TITLE
Crash in Scatter, ScatterLayout and ScatterPlane when clear() on empty canvas

### ISSUE THREAD

**Issue by thorsteinssonh** [kivy/kivy#5787]
### Versions

* Python: 2.7.12 at least
* OS: Ubuntu 16.04
* Kivy: 1.10 at least
* Kivy installation method: From pip

### Description

In Scatter, ScatterLayout and ScatterPlane get kivy crash wen executing a 
`canvas.clear()`  or  `canvas.before.clear()` on empty canvas.
If however canvas has some lines or other shapes, then no-crash.

Crash error message is: `IndexError: list index out of range`

### Code and Logs
Here is small script that demonstrates the error,
click the clear before canvas button, and the program should crash with index error:
```python
from kivy.config import Config
Config.set('graphics','fullscreen','auto')

from kivy.uix.scatter import Scatter
from kivy.lang import Builder
from kivy.base import runTouchApp

from kivy.graphics import Rectangle

Builder.load_string('''
<RootLayout>:
    Button:
        text: 'clear before canvas'
        on_press: root.canvas.before.clear()
        pos: (200,0)
''')


class RootLayout(Scatter):
    def __init__(self, **kwargs):
        super(RootLayout, self).__init__(**kwargs)

runTouchApp(RootLayout())
```

**Comment by gottadiveintopython** [comment]
https://github.com/kivy/kivy/blob/d9f551a2199576eee2f0a0f7806f7d32abafc773/kivy/data/style.kv#L101-L107

Scatter has some canvas instructions by default. So canvas.before.clear() is bad idea I think.

**Comment by gottadiveintopython** [comment]
I mean the canvas actually is not empty. You removed canvas instructions which are used by Scatter.
That's why the error occured

```python
from kivy.uix.scatter import Scatter
from kivy.lang import Builder
from kivy.base import runTouchApp

Builder.load_string('''
<RootLayout>:
    Button:
        text: 'clear before canvas'
        pos: (200,0)
        on_press:
            cbefore = root.canvas.before
            print('\\n'.join(str(inst) for inst in cbefore.children))
            cbefore.clear()
            print('------------------------')
            print('\\n'.join(str(inst) for inst in cbefore.children))
            print('------------------------')
''')


class RootLayout(Scatter):
    def __init__(self, **kwargs):
        super(RootLayout, self).__init__(**kwargs)


runTouchApp(RootLayout())
```

output

```
<kivy.graphics.context_instructions.PushMatrix object at 0x7f1444ee94f8>
<kivy.graphics.context_instructions.MatrixInstruction object at 0x7f1452f09378>
------------------------

------------------------
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   ...
```

**Comment by KeyWeeUsr** [comment]
The clearing itself actually doesn't matter that much. The error is quite simple - you're indirectly using `PopMatrix` by not clearing all its calls in `Scatter` in `canvas.before`/`canvas`/`canvas.after` and there is nothing to pop:

```python
from kivy.lang import Builder
from kivy.base import runTouchApp

runTouchApp(Builder.load_string('''
Widget:
    # just to show that there is no previous canvas
    canvas.before:
        PopMatrix:
'''))
```

Which falls down to a simple [`stack[-1]`](https://github.com/kivy/kivy/blob/f5630be17654166c4d861620035b1b4fc876cc27/kivy/graphics/instructions.pyx#L818) error while the `stack` list is empty. IMO that shouldn't be fixed, instead it should have the same behavior as e.g. [`glPopMatrix()`](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glPushMatrix.xml) and we might just raise an `Exception`:

> It is an error to push a full matrix stack **or to pop a matrix stack that contains only a single matrix.** In either case, the error flag is set and no other change is made to GL state.

ref message https://github.com/kivy/kivy/commit/088eea6f6fbe7d8086109ae4b2aa716ccabbfb24, yet I haven't found any `glPushMatrix()`/`glPopMatrix()` calls, so I did a lil' investivation and apparently those functions aren't used because:

> [If glPushMatrix and glPopMatrix serve you well, you can stick with it. But if the GL matrix stack is not large enough for you (depend on implementation but it is 64 depth in general) then you can implement your own matrix stack with a stl data structure. For matrix operation, you can use glm. Then pass the top of the stack to the function glUniformMatrix4fv for your shader. ](https://www.opengl.org/discussion_boards/showthread.php/174013-glPushMatrix%28%29-glPopMatrix%28%29-alternative?p=1218453&viewfull=1#post1218453)

which falls down basically to the `glPopMatrix()` warning from the docs.

**Comment by tito** [comment]
Some widgets have instructions in canvas.before and canvas.after. Using clear will remove the instructions defined by default. You should NOT do that in any widget except if you control all the instructions in the widget.

Other best approach is:
- create your own canvas and put your own instructions in it. You can use clear as much as you want.
- except complex widgets (like filechoose, etc), the content (canvas) it free from instructions. Put yours in it.
- create a child and put your instructions in it.

Canvas before/after is mostly used for stencil and matrix instructions. RelativeLayout, Scatter, ScatterPlane, etc.. Therefore, if you clear one of them, you'll broke the widget. Embed your own instructions in a neutral sub widget.

This is not something we would solve, that's the cost of the Kivy flexibility :)
