### ISSUE TITLE
Kivy can't update/redraw Window on display connected with USB-C

### ISSUE THREAD

**Issue by clFaster** [kivy/kivy#5791]
### Versions

* Python: 3.6.4 Anaconda
* OS: Windows 10
* Kivy: v1.10.0
* Kivy installation method: Pyinstaller / Anaconda
* Laptop: HP Elitebook
* Dockingstation: HP Elite USB-C Dockingstation

### Description

Kivy doesn't update the Window on a display connected with the USB-C-Dockingstation. On Touch events are triggered, but nothing gets drawn. When the window is moved to the laptops build in screen, the window gets updated. When you move the window back the current elements displayed are shown, but again never updated when you click something. The Program doesn't crash, no errors are shown.

### Code and Logs

Code: Nothing special, tried different stuff, https://kivy.org/docs/tutorials/firstwidget.html doesn't work either.

Log:
https://gist.github.com/clFaster/b0aa1085d1299bbf929346ecb0cbe127#file-kivy-log-usb-c-error

**Comment by tshirtman** [comment]
Can you share the logs with `python main.py -c kivy:log_level:trace` ? maybe there will be more interesting info there.

**Comment by clFaster** [comment]
I will try both and I'll get back to you

**Comment by clFaster** [comment]
I tried a lenovo laptop today, with the same (HP) dockingstation... and guess what works fine with:
Python: 3.6.4 Anaconda
OS: Windows 10
Kivy: v1.10.0

Next week I can retry it with the HP laptop!

**Comment by clFaster** [comment]
I would like to test more, but I don't own this laptop. I tried to reproduce the bug on my lenovo, but as mentioned above, with my device everything works normal when I connect it over the same docking station.

**Comment by tito** [comment]
I highly doubt that this is an issue with Kivy itself. Maybe SDL2 (check on that), or an issue with the drivers itself (i would bet on that). :)

**Comment by scjv** [comment]
I have exactly the same issue with my Lenovo ThinkPad USB 3.0 Ultra Dock.
Pygame with sdl2 works well on the same screen.

[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 22.20.16.4815'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 520'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 22.20.16.4815'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
