### ISSUE TITLE
OS Clipboard fails on recent Ubuntu 18.04, Fedora 28 and OSX 10.13

### ISSUE THREAD

**Issue by TheOnlyJoey** [kivy/kivy#5792]
### Versions

* Python: v3.6.5 (default, Apr  1 2018, 05:46:30) 
* OS: Ubuntu 18.04, Fedora 28 - OSX 10.13 (only 1.10 tested)
* Kivy: 1.10 and master (1.10.1.dev0, git-Unknown, 20180602)
* Kivy installation method: pip3 install kivy (default repository) and compiled for master

### Description

Clipboard only works within the kivy instance, no OS clipboard.
The moment i explicitly set allow_copy and copydata:self.text on a textfield, i am able to copy from kivy to the OS but not the other way around.

Seems it tries to initialize GTK3, drops it, and falls back to xclip.
If i export KIVY_CLIPBOARD to use xclip directly, it works all fine, even without the allow_copy etc.

Behavior is the same between 10.1 and current master.

On OSX the issue is the same, but no xclip ofc, so can't create working case there (Note: Only tested on 1.10)

### Code and Logs

```python
$ python3 main.py 
[INFO   ] [Logger      ] Record log in /home/joey/.kivy/logs/kivy_18-06-08_9.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180602
[INFO   ] [Python      ] v3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.2.0-devel'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
[INFO   ] [MTD         ] Read event from </dev/input/event4>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event18
[INFO   ] [MTD         ] Read event from </dev/input/event18>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
[WARNING] [MTD         ] Unable to open device "/dev/input/event18". Please ensure you have the appropriate permissions.

```

**Comment by dolang** [comment]
I've been having a look at this for a bit, here's what I can say for Linux atm:
- It actually is using `gtk3`, the `xclip` message is probably because there's also something called a "Cutbuffer" provider, and `xclip` can be in charge of that, if present.
- The reason why I myself didn't see the same output was that I started in a `virtualenv` right away. This made the system's `gi` module (`python3-gi`) unavailable, and that's why I had to `apt install xclip` first.
- But: I don't have any issues myself, even when only `gtk3` is present. Kivy complains about the `Cutbuffer` in that case, but the clipboard works anyway.

**Note:** I still did these tests in a `virtualenv`, but this time with the `--system-site-packages` option, which enables `gtk3`. And so far, I've only tested the `TextInput` fields of the showcase example, no modifications.

P.S. Please don't forget to attach the other log, too.

**Comment by dolang** [comment]
Some more tests and this looks like a Wayland problem. Interesting that `xclip` of all things would work here, but not `gtk3`.

Can you switch to Xorg and confirm?

**Comment by akshayaurora** [comment]
own works fine here, please post a way to reproduce.

**Comment by TheOnlyJoey** [comment]
It is still a issue, reproducible on both a clean install of Fedora and Ubuntu 18.04, seems to be wayland related, will do some additional testing this evening.
People have jobs, please leave tickets open for at lest a week before closing them, its good practice :)
