### ISSUE TITLE
Can not build doc (make html) with python3-kivy

### ISSUE THREAD

**Issue by dalanicolai** [kivy/kivy#5794]
### Versions

* Python: 3.6.5
* OS: Linux (Fedora 28)
* Kivy: v1.10.1.dev0, git-7303582, 20180609
* Kivy installation method: Not sure... I guess it was with pip, but when I try to uninstall it says it is a "distutils intalled project"

### Description

I tried to build the doc but I got an error message that parentheses were missing in line 51 of android.py (via androidjoystick.py line 17). I simply corrected it by adding the parentheses to the print statement. I found the file in the sl4a repo. I corrected the file there but I'd like to inform you about it to make sure you will use the corrected file in the future. I hope this is the right place to report it...

### Code and Logs

python setup.py build_ext --inplace
Using distutils

Detected Cython version 0.27.3
Using this graphics system: OpenGL
GStreamer found via pkg-config
WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

b"Package sdl2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `sdl2.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'sdl2', required by 'virtual:world', not found\nPackage 'SDL2_ttf', required by 'virtual:world', not found\nPackage 'SDL2_image', required by 'virtual:world', not found\nPackage 'SDL2_mixer', required by 'virtual:world', not found\n"

 /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'dependency_links'
   warnings.warn(msg)
 /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
   warnings.warn(msg)
 /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_requires'
   warnings.warn(msg)
 /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'
   warnings.warn(msg)
running build_ext
Build configuration is:
 * use_rpi = 0
 * use_mali = 0
 * use_egl = 0
 * use_opengl_es2 = 0
 * use_opengl_mock = 0
 * use_sdl2 = 0
 * use_ios = 0
 * use_mesagl = 0
 * use_x11 = 0
 * use_wayland = 0
 * use_gstreamer = 1
 * use_avfoundation = 0
 * use_osx_frameworks = 0
 * debug_gl = 0
 * debug = False
Detected compiler is unix
skipping 'kivy/_event.c' Cython extension (up-to-date)
skipping 'kivy/_clock.c' Cython extension (up-to-date)
skipping 'kivy/weakproxy.c' Cython extension (up-to-date)
skipping 'kivy/properties.c' Cython extension (up-to-date)
skipping 'kivy/graphics/buffer.c' Cython extension (up-to-date)
skipping 'kivy/graphics/context.c' Cython extension (up-to-date)
skipping 'kivy/graphics/compiler.c' Cython extension (up-to-date)
skipping 'kivy/graphics/context_instructions.c' Cython extension (up-to-date)
skipping 'kivy/graphics/fbo.c' Cython extension (up-to-date)
skipping 'kivy/graphics/gl_instructions.c' Cython extension (up-to-date)
skipping 'kivy/graphics/instructions.c' Cython extension (up-to-date)
skipping 'kivy/graphics/opengl.c' Cython extension (up-to-date)
skipping 'kivy/graphics/opengl_utils.c' Cython extension (up-to-date)
skipping 'kivy/graphics/shader.c' Cython extension (up-to-date)
skipping 'kivy/graphics/stencil_instructions.c' Cython extension (up-to-date)
skipping 'kivy/graphics/scissor_instructions.c' Cython extension (up-to-date)
skipping 'kivy/graphics/texture.c' Cython extension (up-to-date)
skipping 'kivy/graphics/transformation.c' Cython extension (up-to-date)
skipping 'kivy/graphics/vbo.c' Cython extension (up-to-date)
skipping 'kivy/graphics/vertex.c' Cython extension (up-to-date)
skipping 'kivy/graphics/vertex_instructions.c' Cython extension (up-to-date)
skipping 'kivy/graphics/cgl.c' Cython extension (up-to-date)
skipping 'kivy/graphics/cgl_backend/cgl_mock.c' Cython extension (up-to-date)
skipping 'kivy/graphics/cgl_backend/cgl_gl.c' Cython extension (up-to-date)
skipping 'kivy/graphics/cgl_backend/cgl_glew.c' Cython extension (up-to-date)
skipping 'kivy/graphics/cgl_backend/cgl_sdl2.c' Cython extension (up-to-date)
skipping 'kivy/graphics/cgl_backend/cgl_debug.c' Cython extension (up-to-date)
skipping 'kivy/core/text/text_layout.c' Cython extension (up-to-date)
skipping 'kivy/core/window/window_info.c' Cython extension (up-to-date)
skipping 'kivy/graphics/tesselator.c' Cython extension (up-to-date)
skipping 'kivy/graphics/svg.c' Cython extension (up-to-date)
skipping 'kivy/lib/gstplayer/_gstplayer.c' Cython extension (up-to-date)
cd doc && make html
make[1]: Entering directory '/run/media/daniel/thuis/git/kivy/doc'
mkdir -p build/html build/doctrees
sphinx-build -b html -d build/doctrees  -Q sources build/html
/run/media/daniel/thuis/virtualenvs/python3/kivy/lib/python3.6/site-packages/kivy/__init__.py
[ERROR  ] [Input       ] AndroidJoystick is not supported by your version of linux
Traceback (most recent call last):
  File "/run/media/daniel/thuis/virtualenvs/python3/kivy/lib/python3.6/site-packages/kivy/input/providers/__init__.py", line 58, in <module>
    import kivy.input.providers.androidjoystick
  File "/run/media/daniel/thuis/virtualenvs/python3/kivy/lib/python3.6/site-packages/kivy/input/providers/androidjoystick.py", line 17, in <module>
    import android  # NOQA
  File "/run/media/daniel/thuis/virtualenvs/python3/kivy/lib/python3.6/site-packages/android.py", line 51
    print result['error']
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(result['error'])?
^C
interrupted!
make[1]: *** [Makefile:81: html] Error 2
make: *** [Makefile:71: html] Interrupt

**Comment by dalanicolai** [comment]
Sorry I made the title before I fixed it. So I opened a pull request in the sl4a repo with the fix.

**Comment by dolang** [comment]
Also [Kivy and SL4A are unrelated](https://kivy.org/docs/faq.html#what-s-the-difference-between-python-for-android-from-kivy-and-sl4a), so I guess this can be closed?

**Comment by dalanicolai** [comment]
I called 'make html' from the root directory of the repo instead of from the doc directory but anyway androidjoystick.py calls the android.py file, which is a file in my kivy virtualenv. I don't know how it got their and I don't know why androidjoystick.py calls it. I looked up the android.py file and it is exactly ([this](https://github.com/damonkohler/sl4a/blob/master/python/ase/android.py))) file by Damon Kohler from the SL4A repo. I do not have SL4A installed. I don't know how it all works. Anyway the docs build now and I fixed the issue in that file. If it is not relevant then indeed this issue can be closed...

**Comment by dalanicolai** [comment]
Thanks dolang for the reply. I commented on it in github. Indeed I guess if
it is irrelevant then the issue can be closed. I am far from an expert but
as the android file is called from a kivy file I guessed this was a
relevant issue...

**Comment by dolang** [comment]
I've had a look at this again to see if there's something that should be addressed, but it looks like it was really just some weird interaction between two unrelated files. Closing.
