### ISSUE TITLE
Cant Install kivy in Ubuntu 18

### ISSUE THREAD

**Issue by phelantomas** [kivy/kivy#5795]
### Versions

* Python: 3.6.5
* OS: Ubuntu 18.04
* Kivy: Stable
* Kivy installation method:

### Description

Tried to install Kivy on my computer with the following command: 
sudo add-apt-repository ppa:kivy-team/kivy

### Code and Logs

```python
 This PPA contain the stable release of Kivy project.
 More info: https://launchpad.net/~kivy-team/+archive/ubuntu/kivy
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://ie.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:3 http://ie.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Ign:4 http://ppa.launchpad.net/kivy-team/kivy/ubuntu bionic InRelease          
Hit:5 http://ie.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:6 https://deb.nodesource.com/node_8.x bionic InRelease                     
Hit:7 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic InRelease
Ign:8 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 InRelease
Hit:9 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release      
Hit:10 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease      
Err:11 http://ppa.launchpad.net/kivy-team/kivy/ubuntu bionic Release          
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/kivy-team/kivy/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.


```

**Comment by berahtlv** [comment]
Also Python3.6.5 and Ubuntu 18.04.

In one of the issues found that can be installed from:
```
sudo add-apt-repository ppa:kivy-team/kivy-daily
sudo apt-get update
```

**Comment by berahtlv** [comment]
@dolang installation from ```https://github.com/kivy/kivy/archive/master.zip``` works.

I had installed with ```git clone ...``` and then ```python setup.py install```. There was some compilation issue, maybe haven't had some package. Now it compiled, but for some reason ```ModuleNotFoundError: No module named 'kivy._clock'``` error received after Layout import, kivy itself was able to import. Strange is that I've reentered Virtualenv and problem gone.

**Comment by dolang** [comment]
Installing with `git clone ...` and using GitHub's `master.zip` is basically the same if you're only using a project (i.e. you need to clone when you want to contribute back).

Make sure you're not in the cloned kivy directory once you've installed it, or you'll see errors like that (`kivy._clock`) because python gets confused.
