### ISSUE TITLE
CC BY-NC is *not* an acceptable licence type in Fedora

### ISSUE THREAD

**Issue by martinkg** [kivy/kivy#5796]
### Versions
undependent from any version
* Python:
* OS: Fedora 28Linux f28 4.16.12-300.fc28.x86_64
* Kivy: 1.10.0

### Description

I want to create an rpm package of python-kivy for the Linux distribution Fedora. However, Package Policy [1] does not allow files of the type CC BY-NC to be included in the binary or source package.

This currently affects 3 files [2]

* No copyright * CC by-nc
-----------------------
Kivy-1.10.0 / examples / demo / showcase / data / icons / next.png
Kivy-1.10.0 / examples / demo / showcase / data / icons / prev.png
Kivy-1.10.0 / examples / demo / showcase / data / icons / sourcecode.png

[1] https://fedoraproject.org/wiki/Licensing:Main#Content_Licenses
[2] https://martinkg.fedorapeople.org/Packages/kivy/licensecheck.txt

Is it possible that these 3 files get a different license type?
otherwise these 3 files must be removed when creating my rpm package.

Regards
Martin

**Comment by dolang** [comment]
Uh, heh. :smile:

You'll just have to take a look at the pull request I've created for your other issue. v1.10.1 will have those.

However, I can't do anything about v1.10.0, you'll have to remove the files in that version. But the next release is imminent anyway.

See: https://github.com/kivy/kivy/milestone/28

**Comment by martinkg** [comment]
This issue has nothing to do with https://github.com/kivy/kivy/pull/5786 it's totally different.
this  3 files have a not acceptable license type and should be changed in 1.10.1 

Kivy-1.10.0 / examples / demo / showcase / data / icons / next.png
Kivy-1.10.0 / examples / demo / showcase / data / icons / prev.png
Kivy-1.10.0 / examples / demo / showcase / data / icons / sourcecode.png

i will remove the files for now.

Thanks for your feedback

**Comment by dolang** [comment]
It does, though. I've mentioned in the other issue that we should just make it about all the problems over in that RedHat bug report.

Have a look at the link I provided and you'll see.
