### ISSUE TITLE
5 inch resistive touch screen calibration on kivy

### ISSUE THREAD

**Issue by sachu100** [kivy/kivy#5798]
I have a problem with my 5'' resistive touch screen which i need to calibrate touch on kivy app. My touch in raspberry pi is correctly calibrated but when it comes to kivy app it is not correct. How can i calibrate the touch to get accurate touch in my kivy app(GUI). I am using raspberry pi 3 with raspbian os (full version not lite)for this. So please someone help me with this it's urgent.

**Comment by tshirtman** [comment]
Closing as support, but you can have a look at the postproc:calibration module, or the options of your touch provider if the default behavior is not correct.
