### ISSUE TITLE
when multiprocessing.Manager is used, kivy will repeat create new window

### ISSUE THREAD

**Issue by davied9** [kivy/kivy#5807]
### Versions

* Python:  Python 3.5.2
* OS: Windows 10
* Kivy: v1.10.0
* Kivy installation method: follow the specification on https://kivy.org/docs/installation/installation-windows.html

### Description

try to use multiprocessing.Manager to communicate between servers, It's OK to run in PyCharm, but after I follow the Guide(https://kivy.org/docs/guide/packaging-windows.html#packaging-a-simple-app) to build with PyInstaller on windows, the output exe will just repeat create new windows again and again ...

### Code and Logs

🔢 the following code is simplified from my project, but it's enough to repeat the case
```python
from kivy.app import App
from kivy.uix.button import Button
import multiprocessing

class T007_App(App):

    def build(self):
        return Button(text='test', on_release=self._change)

    def _change(self, button):
        if 'test' == button.text:
            button.text = 'joke'
        elif 'joke' == button.text:
            button.text = 'test'

if '__main__' == __name__:
    manager = multiprocessing.Manager()
    T007_App().run()
```

🔢 the log is OK, but there will be tens of them, until python hangs(or blocks)
[INFO   ] Logger: Record log in C:\Users\Administrator\.kivy\logs\kivy_18-06-14_0.txt
[INFO   ] Kivy: v1.10.0
[INFO   ] Python: v3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "G:\Projects\LANRemoteController\LANRemoteController\Test\T007_kivy_start.py", line 17, in <module>
[WARNING] stderr:     manager = multiprocessing.Manager()
[WARNING] stderr:   File "F:\Develop\Python35\lib\multiprocessing\context.py", line 55, in Manager
[WARNING] stderr:     m.start()
[WARNING] stderr:   File "F:\Develop\Python35\lib\multiprocessing\managers.py", line 483, in start
[WARNING] stderr:     self._address = reader.recv()
[WARNING] stderr:   File "F:\Develop\Python35\lib\multiprocessing\connection.py", line 250, in recv
[WARNING] stderr:     buf = self._recv_bytes()
[WARNING] stderr:   File "F:\Develop\Python35\lib\multiprocessing\connection.py", line 306, in _recv_bytes
[WARNING] stderr:     [ov.event], False, INFINITE)
[WARNING] stderr: KeyboardInterrupt

**Comment by davied9** [comment]
Is there some restricts to combine kivy and multiprocessing or multithreading ?

**Comment by pythonic64** [comment]
I think you're missing [freeze_support](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.freeze_support).

**Comment by davied9** [comment]
@pythonic64 Thanks , that's it, add freeze_support() solve this case

**Comment by pythonic64** [comment]
Nice 👍
