### ISSUE TITLE
Latest version of sdl2_mixer breaks OGG support in kivy

### ISSUE THREAD

**Issue by LarsDu** [kivy/kivy#5819]
### Versions

* Python: 2.7.15
* OS: Osx 10.13.4
* Kivy: v1.10.0
* Kivy installation method: Installed via jiayi_anaconda kivy package. Used brew to install sdl2 dependencies. 

### Description
I'm trying to use SDL2 audio (gstreamer doesn't work on my platform). When I upgraded from sdl2_mixer 2.0.1_1 to 2.0.2, I get the errors seen below:

This problem has been reproduced on two OSX machines

### Code and Logs

```
[WARNING] [Audio       ] Unable to find a loader for </Users/ld87/Code/SpaceGuppyProj/ElectricNemo/res/sounds/infrequent/powerup1.ogg>```

**Comment by tito** [comment]
It is not our fault, but mostly how you installed it. We ask for OGG, but if the library don't have it, it won't be supported.
I looked on the latest brew recipe, it seems to install everything for it.

So maybe it doesn't use the sdl2_mixer you installed? Or maybe your compilation doesn't include libvorbis.
