### ISSUE TITLE
"/data/user/0/org.gmail.gmail/files/app/libpymodules.so" not found

### ISSUE THREAD

**Issue by farzinh** [kivy/kivy#5823]
when I run my python code in buildozer there is not any problem , but when lanching apk, it crash.

it seems like this issue com from /libpymodules.so  but i don't know how can I add this
 
ImportError: dlopen failed: library "/data/user/0/org.gmail.gmail/files/app /libpymodules.so" not found
[apk_debug_log.txt](https://github.com/kivy/kivy/files/2129693/apk_debug_log.txt)
[log_level2.txt](https://github.com/kivy/kivy/files/2129694/log_level2.txt)

**Comment by akshayaurora** [comment]
think this belongs in python-for-android

**Comment by akshayaurora** [comment]
This issue was moved to kivy/python-for-android#1309
