### ISSUE TITLE
co-ordinates used to check for collide_point(*touch_pos) / button.on_release aren't rotated with object, causing these to fail

### ISSUE THREAD

**Issue by ApplySci** [kivy/kivy#5828]
### Versions

* Python: 3.6.5 64-bit
* OS: Win 10 Enterprise 64-bit
* Kivy: 1.10 and 1.10.1.dev0 20180601 nightly
* Kivy installation method: Windows wheel installed via pip

### Description

If I add a button (or other widget) and rotate it, then touch events (e.g. testing for `widget.collide_point(*touch.pos)` or binding to `button.on_release`) only work if the touch is on the pre-rotated position, not the actual position once rotated. In the example below, the button will only act pressed if you press on the position that the button would be if it hadn't been rotated. So the only spot you can press that is both on the visible button, and the place where kivy thinks the button is, is the centre of the button: if you try to press away from the centre, somewhere towards the top or bottom of the rotated button, the button events don't get triggered.

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = '''
FloatLayout:

    Button:
        text: 'press me'
        size_hint: 1, 0.1
        pos_hint: {'center_x': .5, 'center_y': .5}
        canvas.before:
            PushMatrix
            Rotate:
                angle: 90
                origin: self.center
        canvas.after:
            PopMatrix
        on_release: print('pressed')
'''

class RotationApp(App):
    def build(self):
        return Builder.load_string(kv)

RotationApp().run()
```

**Comment by bionoid** [comment]
Basically this is a consequence of how the API works; it's a legitimate feature request (though probably hard to accomplish), but this is not "expected" to work. For rotation with accurate collision detection, you can use `Scatter`, or if you need it in other contexts, you can copy [the implementation in scatter.py](https://github.com/kivy/kivy/blob/1.10.1/kivy/uix/scatter.py#L512-L513)

```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
Scatter:
	size_hint: .5, .5
	pos: 200, 200
	rotation: 45
	do_translation: False
	do_rotation: False
	do_scale: False
	Button:
		text: 'Hello World'
'''))
```

**Comment by ApplySci** [comment]
Great, thank you @bionoid . That wasn't obvious in the documentation, but it's completely fixed my problem! Thank you!
