### ISSUE TITLE
Problem installing on mac

### ISSUE THREAD

**Issue by Ben-Lichtman** [kivy/kivy#5830]
### Versions

* Python: 3.6.5
* OS: mac 10.13.5
* Kivy: stable
* Kivy installation method: pip3 install kivy

### Description

Whenever I attempt to install kivy through pip I get a long error starting with a cython compile error, and ending with a clang build fail.

### Code and Logs

Full build log: https://pastebin.com/QEP1sSe7

Then on the console I get

```
Failed building wheel for kivy
Command "/usr/local/opt/python/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/vx/hgbgyv8d6h9brjs0y09chqzw0000gn/T/pip-install-dwp9g4hp/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/vx/hgbgyv8d6h9brjs0y09chqzw0000gn/T/pip-record-s9oe6oa5/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/vx/hgbgyv8d6h9brjs0y09chqzw0000gn/T/pip-install-dwp9g4hp/kivy/
```

any help appreciated

**Comment by bionoid** [comment]
It looks like a Cython compatibility error - 0.28.x is not officially supported by Kivy 1.10, I'm not sure if that combination can work. You can try to install master branch with your current Cython version:

    pip3 install https://github.com/kivy/kivy/archive/master.zip

Or alternatively downgrade to Cython 0.25.2 and then install stable (but you may run into a build issue with sdl2-mixer doing this, so I suggest using master branch)

**Comment by akshayaurora** [comment]
we just released a new version with wheels for osx, no more compilation please re-open if the problem still persists.
