### ISSUE TITLE
ColorWheel Event Fires Multiple Time Per Change

### ISSUE THREAD

**Issue by SoundsSerious** [kivy/kivy#5831]
### Versions

* Python: 2.7
* OS: Windows 7
* Kivy: 1.10

### Description

Found this issue playing around with the colorwheel, i was getting 4 events every time I updated the color, which is problematic since there's only one change (specifically for me trying to send network events).

Ideally for one change, we should get one event. 

### Code and Logs

from colorpicker.py:
```
color = ReferenceListProperty(r, g, b, a)
_hsv = ListProperty([1, 1, 1, 0])


def on__hsv(self, instance, value):
        c_hsv = Color(*value, mode='hsv')
        self.r = c_hsv.r
        self.g = c_hsv.g
        self.b = c_hsv.b
        self.a = c_hsv.a
        self.rgba = (self.r, self.g, self.b, self.a)
```

Binding To
`self.color_in.bind( _hsv = self.on_color )
`
Results In A Single Event:
`Color Change <style.AutonomousColorWheel object at 0x000000000EBD3660>	[0.225, 1, 0.45, 1]
`
Binding To
`self.color_in.bind( color= self.on_color )
`
Results In A Multiple Event:
```Color Change <style.AutonomousColorWheel object at 0x000000000EC41660>	[1.0, 0, 0, 0]
Color Change <style.AutonomousColorWheel object at 0x000000000EC41660>	[1.0, 0.3999999761581421, 0, 0]
Color Change <style.AutonomousColorWheel object at 0x000000000EC41660>	[1.0, 0.3999999761581421, 0.3999999761581421, 0]
Color Change <style.AutonomousColorWheel object at 0x000000000EC41660>	[1.0, 0.3999999761581421, 0.3999999761581421, 1.0]```

**Comment by tito** [comment]
Seems like the ReferenceListProperty could have more love and prevent redispatching if the final value didn't change.
