### ISSUE TITLE
Wheels for python 3.7?

### ISSUE THREAD

**Issue by ApplySci** [kivy/kivy#5832]
Now that Python 3.7.0 has been released, is there a timeline for getting cp37 wheels of all the kivy modules onto pypi?

**Comment by matham** [comment]
It will be released when appveyor supports python 3.7 (https://github.com/appveyor/ci/issues/2475) and then we'd need to actually make the wheels and do a release.

**Comment by ApplySci** [comment]
Good news - appveyor has now been updated to python 3.7 !

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/kivy/commit/b68ea11c38cea7dd4cf552619786a06927dddf49

**Comment by akshayaurora** [comment]
wheels should now be available for osx and windows, @dolang @matham @tshirtman think we can close this now ? @dolang do we have python3.7 packages for manylinux2 ?

**Comment by ApplySci** [comment]
The wheel for windows (64-bit) seems to require cython and compiler - that can't be right, can it? The wheel for python 3.6 didn't , as far as I can tell.

**Comment by tshirtman** [comment]
Seems the windows wheel wasn't built in yesterday's commit, need to look into it to find why it didn't build while [build wheel window] was in the commit message.

**Comment by dolang** [comment]
@akshayaurora manylinux2010 is not ready. See pypa/manylinux#179.

**Comment by ApplySci** [comment]
This seems to work now, so I think we can close this. Thank you all for making this happen!
