### ISSUE TITLE
Kivy Launcher (Google Play App)

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#5843]
### Versions

* Python: 3.6
* OS: Windows 10
* Kivy:  1.9.0
* Kivy installation method: pip

### Description

So, I've been working with kivy for a few months now, and the documentation has been pretty helpful. At least, up until this point. Kivy seems to have provided a great tool for developers, allowing us to test apps directly on an android device using their Google Play app "Kivy Launcher." The concept is brilliant, however the execution is far from that. I have yet to find any comprehensive documentation on how to get this app to successfully run a test kivy app, and I'm sure many other developers are eager to understand how to use this tool. Any help as to how to get this app to work with a homemade kivy app (with numerous files necessary for running (i.e. images, fonts, .kv files, etc.)) would be much appreciated.

Thank you.

**Comment by tito** [comment]
As explained @davied9. The path changes now depending of your phone, but the doc is already here.

**Comment by xloem** [comment]
Where is the source code to the ivy launcher?

**Comment by Julian-O** [comment]
Kivy Launcher is no longer extant.

Obsoleted by #7724

Closing as stale.
