### ISSUE TITLE
Many broken links on Kivy galery webpage

### ISSUE THREAD

**Issue by FrancoisSchnell** [kivy/kivy#5852]
Hi, not sure that's the right place but there are many broken links on https://kivy.org/#gallery
For example the Google Play links for Nie Nie, for Kognitivo, for Particle Panda or the websites for The Nobooth or bargenius. Thanks.

**Comment by tshirtman** [comment]
kognitivo can be fixed to https://play.google.com/store/apps/details?id=org.kognitivo.kognitivo (and link to https://github.com/eviltnan/kognitivo added)
for particle panda i guess we could point to the updated version https://play.google.com/store/apps/details?id=org.chaosbuffalogames.particlepanda2&hl=en_US 
not sure about the others, suggestions welcome!

**Comment by naman653** [comment]
I'm on solving this issue. Already fixed most of the links.

**Comment by Julian-O** [comment]
This was partially fixed. I am closing this as stale.

Reopened another with newer broken links, and any that got through. https://github.com/kivy/kivy-website/issues/155
