### ISSUE TITLE
Raspberry Pi Camera not working

### ISSUE THREAD

**Issue by dariozubi** [kivy/kivy#5853]
Hello, 
I'm having trouble with kivy and the raspberry pi camera. I'm getting this error:

[ERROR  ] [PiCamera    ] Couldn't get image from Camera
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/camera/camera_picamera.py", line 70, in _update
    (bufsize[0] * bufsize[1] * 3,), dtype=numpy.uint8)
TypeError: 'float' object cannot be interpreted as an index

I've looked for something similar but I have found nothing. I'm using the camera example for kivy (https://kivy.org/docs/examples/gen__camera__main__py.html) with Raspbian 9 (stretch) and installed everything as mentioned in the installation page (https://kivy.org/docs/installation/installation-rpi.html)

**Comment by pythonic64** [comment]
For some reason `bufsize` collection has `float` elements. 
I think this line:
https://github.com/kivy/kivy/blob/b39c84bc0b46e4a0e1daf4d16081445598fed67b/kivy/core/camera/camera_picamera.py#L68
should be changed to:
`bufsize = map(int, self.raw_buffer_size())`
to fix the error.

**Comment by dariozubi** [comment]
That worked. Thank you!

**Comment by pythonic64** [comment]
You're welcome!
