### ISSUE TITLE
It is now possible to build for Android via Windows Subsystem for Linux (WSL).

### ISSUE THREAD

**Issue by klondikemarlen** [kivy/kivy#5854]
I managed to setup my Windows 10 machine to program and test Kivy in a Windows environment while building and deploying for Android via Bash in Windows Subsystem for Linux (WSL).

I thought that you might want to mention this in your installation guide somewhere. The only real caveat is that your ADB version must be the same on Windows and WSL. And you need to `adb start-server` on Windows before doing `buildozer android deploy`.

I am using (on Windows):
- Windows 10 Home v1803
- Python 3.5.4
- Kivy 1.10.0
- Adb 1.0.40

On WSL:
- Ubuntu 16.04.4 LTS
- Python 2.7.12
- Kivy 1.10.0
- Buildozer 0.35dev
- Adb 1.0.40
- Cython 0.25.2

**Comment by akshayaurora** [comment]
nice! thanks for the info

**Comment by klondikemarlen** [comment]
To handle the ADB problem in one command (in CMD not PowerShell) you can do C:\> `adb start-server && bash -c "buildozer -v android debug deploy"`

I made an installation Wiki so I can remember the next time I have to setup Kivy. It isn't very detailed though. https://github.com/klondikemarlen/Dimension/wiki/Installing-Kivy-on-Windows-10

**Comment by liuhewei** [comment]
Is it still possible for the latest Kivy version 1.11.1? Thanks.

**Comment by klondikemarlen** [comment]
I haven't tried in ages ... I've been doing more web development than app development these days.
I think it should be fine though! The lastest version of WSL for Windows is a full linux kernel, so anything that works on linux command line should work on Windows.

**Comment by liuhewei** [comment]
@klondikemarlen Thanks anyway! I'll try myself.

**Comment by RandPooka** [comment]
How do you get around the case-insensitive filesystem error when attempting to build android 10? What filesystems are natively supported by Windows that are case sensitive?

**Comment by klondikemarlen** [comment]
Well Window Subsystem for Linux is Linux, so it is case sensitive. Basically the solution is to not use Windows :)
