### ISSUE TITLE
Textinput box while displaying the run time data from command prompt, overwrites text(when lines are more than 200)

### ISSUE THREAD

**Issue by Shivangisingh06** [kivy/kivy#5857]
### Versions

* Python: 3.6.5
* OS: Windows 10 64-bit
* Kivy: v1.10.0
* Kivy installation method: pip as mentioned on Kivy installation guide

### Description
While displaying the runtime data to kivy text input, after 200+ lines it overwrites the text in the textinput 

### Code and Logs

[INFO   ] [Logger      ] Record log in C:\Users\ssingh\.kivy\logs\kivy_18-07-12_84.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 391.03'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'Quadro P1000/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
![overwritten text](https://user-images.githubusercontent.com/29286514/42657919-bec1b248-85f1-11e8-8000-a406848b24d1.PNG)

**Comment by tito** [comment]
I've tested 2 ways to try reproducing this issue, without success.
Please provide a code that demonstrate the issue, otherwise it may just be from your app :)

```python
from kivy.lang import Builder
from kivy.base import runTouchApp
from kivy.factory import Factory as F
from kivy.clock import Clock, mainthread
from random import randint

from kivy.graphics import Rectangle

Builder.load_string('''
<Test>:
    cols: 1
    Slider:
        id: vl
        on_value: root.update_ti()
    TextInput:
        id: ti
''')


class Test(F.GridLayout):
    def __init__(self, **kwargs):
        super(Test, self).__init__(**kwargs)
        # Clock.schedule_interval(self.update_ti, 0)

    def update_ti(self, *largs):
        ti = self.ids.ti

        lines = [
            "m m m m m m m m m",
            "a a a a a a a a a",
            " z z z z z z z z ",
            "M M M M M M M M M",
            " Z Z Z Z Z Z Z Z ",
            "A A A A A A A A A",
        ] * 20
        lines = lines[randint(0, 10):]

        ti.text = "\n".join(lines)

runTouchApp(Test())
```
