### ISSUE TITLE
Python project build Buildozer issue - Please define SDL_JAVA_PACKAGE_PATH to the path of your Java package with dots replaced with underscores

### ISSUE THREAD

**Issue by Nik-Lz** [kivy/kivy#5860]
I am trying to port my python project to Android. 

I followed instructions here https://kivy.org/docs/guide/packaging-android.html and here: http://inclem.net/2014/01/12/kivy-crash-course/2_building_an_android_apk/

I did:
`sudo pip install --upgrade cython==0.21; sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 python2.7 python2.7-dev openjdk-8-jdk unzip zlib1g-dev zlib1g:i386`
Then went on to my python project and did: 
`buildozer init`
I changed the include files and directories (included more of them) on the generated buildozer.spec
and a couple of other settings (`fullscreen=1` & included some more libraries). 

I have java 8 installed (`sudo apt install openjdk-8-jre`, `sudo apt install openjdk-8-jdk`) and working properly. 

Finally I hit `buildozer android debug` to build the project and after it downloads everything, I get the info message I mentioned in the title above, followed by: 

`[WARNING]: ERROR: .../.buildozer/android/platform/android-ndk-r9c/ndk-build failed!

 Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=packageName098 --bootstrap=sdl2 --requirements=kivy,pygame,configobj --arch armeabi-v7a --copy-libs --color=always --storage-dir=.../.buildozer/android/platform/build
 
 Buildozer failed to execute the last command
 The error might be hidden in the log above this error
 Please read the full log, and search for it before
 raising an issue with buildozer itself.
 In case of a bug report, please add a full log with log_level = 2`

I am not very familiar with Kivy. My goal is to port my Python app so it can run on Android. Can you make something out of this and let me know what the issue is? 

I'm on Ubuntu 16.04 x86_64 (not a VM) and using Python 2.7.

**Comment by tshirtman** [comment]
```
Please read the full log, and search for it before
raising an issue with buildozer itself.
In case of a bug report, please add a full log with log_level = 2`
```
Please follow these instructions :)

**Comment by philippschaefer4** [comment]
I have the same issue. With me it seems to have something to do with pygame, opencv and pillow. So basically all libs for image processing.(I'd be thankful for any alternatives) when i leave the out everything ist eine.
The error seems to say: define that environment variable! I think it wants a repository with java sdl  Code.

**Comment by tito** [comment]
Issue moved to [kivy/python-for-android #1391](https://github.com/kivy/python-for-android/issues/1391) via [**ZenHub**](https://www.zenhub.com/)
