### ISSUE TITLE
Disabled property in python

### ISSUE THREAD

**Issue by Tokariew** [kivy/kivy#5861]
### Versions

* Python: 3.6.5
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: pip install

### Description

Up to now defining button like self.slider or self.button2 in example code worked perfectly fine, but with kivy 1.10.1 it work unexpectedly. Slider have “proper” disabled look, but it still possible to interact with it and event are dispatched.
Button2 look like not disabled and it possible to interact with it.

Both slider and button2 ignore changing it disabled property with on_state method in code.

From python code disabled property can now be set only after adding widget to parent like with self.button in code, setting it earlier and it will have similar effect like when creating it. It will be still possible to interact with such widget.

### Code and Logs

```python
from kivy.uix.button import Button
from kivy.uix.togglebutton import ToggleButton
from kivy.uix.gridlayout import GridLayout
from kivy.uix.slider import Slider

from kivy.app import App

class MainApp(App):
	def build(self):
		self.counter = 0
		self.layout = GridLayout(rows=2)
		self.button = Button(text='Simple Button')
		self.slider = Slider(disabled=True)
		self.slider.bind(value=self.on_value)
		self.tbutton = ToggleButton(text='Disable other widgets', state='down')
		self.tbutton.bind(state=self.on_state)
		self.button2 = Button(text='Clicked: 0', disabled=True)
		self.button2.bind(on_release=self.on_press)
		
		self.layout.add_widget(self.button)
		self.layout.add_widget(self.slider)
		self.layout.add_widget(self.tbutton)
		self.layout.add_widget(self.button2)
		
		self.button.disabled = True
		
		return self.layout
		
	def on_value(self, instance, value):
		self.button.text = str(value)
		
	def on_state(self, instance, state):
		if state == 'down':
			self.slider.disabled = True
			self.button.disabled = True
			self.button2.disabled = True
		else:
			self.slider.disabled = False
			self.button.disabled = False
			self.button2.disabled = False
			
	def on_press(self, instance):
		self.counter += 1
		instance.text = 'Clicked: {}'.format(self.counter)
	
if __name__ == '__main__':
	MainApp().run()
```

**Comment by pythonic64** [comment]
Try installing kivy from master branch or [nightly wheel for your Python version](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation). 
Pull request https://github.com/kivy/kivy/pull/5841 should have it fixed.

**Comment by Tokariew** [comment]
With nightly version it work fine.

**Comment by tshirtman** [comment]
Thanks for your report and testing, closing as fixed.
