### ISSUE TITLE
Height of ActionButton is hard coded to minimum of sp(48)

### ISSUE THREAD

**Issue by robertour** [kivy/kivy#5884]
I have been trying to specify the height of the ActionButton, and then I encountered that it is hard coded in the actionbar.py:

https://github.com/kivy/kivy/blob/master/kivy/uix/actionbar.py#L443

This is refreshed everytime the ActionGroup is toggled, so there is very little one can do to circunvent this.  Either listenint to the `is_open` proprety to detect when the toggle occurs, or inheriting from `ActionGroup` and rewrite the `_toggle_dropdown` method

Would changing this `item.height = max([self.height, sp(48)])` for this `item.height = item.height if item.height else self.height` be save?

I can see how this could affect other interfaces since the size depends on the `self.height` (the `ActionGroup` size). Nevertheless, 48 is quite big as a default.

Alternativaly then, there should be a `dropdown_children_height` defaulted to `48`. Since there is already a `dropdown_width`, it seem like this could be a decent complement.

**Comment by tito** [comment]
The whole ActionBar is made up upon Material Design convention, and 48dp is the size of an element.
Your approach also may lead to resizing issue if it's not a static value (if i correctly recall).

So maybe we could let you change the default value in actionbar itself.

**Comment by ElliotGarbus** [comment]
@Julian-O @misl6 I recommendation closing this issue as not planned.
This is a feature request to extend the ActionBar to have a selectable height.  As @tito states, it is built to the MD convention of a height of 48dp.  I think this is a philosophical issue.     The widget is built to a standard.  If a user wants to customize the widget beyond the design spec, they can "vendor" the code in and specialize it.   

The issues is over 5 years old, KivyMD now exists as a more contemporary option.

**Comment by Julian-O** [comment]
``
