### ISSUE TITLE
Conflict with packages kivy and secretstorage (Anaconda)

### ISSUE THREAD

**Issue by lahmeri** [kivy/kivy#5894]
### Versions
*anaconda 1.9.1
* Python:3
* OS:linux ubuntu 18
* Kivy:
* Kivy installation method:conda install --channel https://conda.anaconda.org/wgarcia kivy
I also tried 
 conda install --channel https://conda.anaconda.org/conda-forge kivy
also 
conda install -c krisvanneste kivy 

### Description
i can't donwload the module kivy from the GUI of anacaonda (enviroments), i didn't found any package named kivy so i tried to deal with it with the terminal  
// Instalation failed 

### Code and Logs
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - kivy
  - secretstorage
Use "conda info <package>" to see the dependencies for each package.

```

**Comment by matham** [comment]
Also, the issue is missing complete installation logs. Additionally, we only support the conda-forge channel.

**Comment by bqtrung** [comment]
I can't install it on my fedora, can anyone help me?

conda install kivy
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - anaconda-navigator
  - ca-certificates
  - certifi
  - conda
  - gst-plugins-base
  - gstreamer
  - kivy
  - navigator-updater
  - openssl
  - pkgs/main/linux-64::_ipyw_jlab_nb_ext_conf==0.1.0=py37_0
  - pkgs/main/linux-64::_libgcc_mutex==0.1=main
  - pkgs/main/linux-64::anaconda-client==1.7.2=py37_0
  - pkgs/main/linux-64::asn1crypto==0.24.0=py37_0
  - pkgs/main/linux-64::attrs==19.1.0=py37_1
  - pkgs/main/linux-64::backcall==0.1.0=py37_0
  - pkgs/main/linux-64::beautifulsoup4==4.7.1=py37_1
  - pkgs/main/linux-64::bleach==3.1.0=py37_0
  - pkgs/main/linux-64::bzip2==1.0.6=h14c3975_5
  - pkgs/main/linux-64::cffi==1.12.3=py37h2e261b9_0
  - pkgs/main/linux-64::chardet==3.0.4=py37_1
  - pkgs/main/linux-64::click==7.0=py37_0
  - pkgs/main/linux-64::clyent==1.2.2=py37_1
  - pkgs/main/linux-64::conda-build==3.18.5=py37_0
  - pkgs/main/linux-64::conda-env==2.6.0=1
  - pkgs/main/linux-64::conda-package-handling==1.3.10=py37_0
  - pkgs/main/linux-64::cryptography==2.7=py37h1ba5d50_0
  - pkgs/main/linux-64::dbus==1.13.6=h746ee38_0
  - pkgs/main/linux-64::decorator==4.4.0=py37_1
  - pkgs/main/linux-64::entrypoints==0.3=py37_0
  - pkgs/main/linux-64::expat==2.2.6=he6710b0_0
  - pkgs/main/linux-64::fontconfig==2.13.0=h9420a91_0
  - pkgs/main/linux-64::freetype==2.9.1=h8a8886c_1
  - pkgs/main/linux-64::future==0.17.1=py37_0
  - pkgs/main/linux-64::glib==2.56.2=hd408876_0
  - pkgs/main/linux-64::gmp==6.1.2=h6c8ec71_1
  - pkgs/main/linux-64::icu==58.2=h9c2bf20_1
  - pkgs/main/linux-64::idna==2.8=py37_0
  - pkgs/main/linux-64::ipykernel==5.1.1=py37h39e3cac_0
  - pkgs/main/linux-64::ipython==7.6.0=py37h39e3cac_0
  - pkgs/main/linux-64::ipython_genutils==0.2.0=py37_0
  - pkgs/main/linux-64::ipywidgets==7.4.2=py37_0
  - pkgs/main/linux-64::jedi==0.13.3=py37_0
  - pkgs/main/linux-64::jinja2==2.10.1=py37_0
  - pkgs/main/linux-64::jpeg==9b=h024ee3a_2
  - pkgs/main/linux-64::jsonschema==3.0.1=py37_0
  - pkgs/main/linux-64::jupyter_client==5.2.4=py37_0
  - pkgs/main/linux-64::jupyterlab==0.35.5=py37hf63ae98_0
  - pkgs/main/linux-64::jupyterlab_server==0.2.0=py37_0
  - pkgs/main/linux-64::libarchive==3.3.3=h5d8350f_5
  - pkgs/main/linux-64::libedit==3.1.20181209=hc058e9b_0
  - pkgs/main/linux-64::libffi==3.2.1=hd88cf55_4
  - pkgs/main/linux-64::libgcc-ng==9.1.0=hdf63c60_0
  - pkgs/main/linux-64::liblief==0.9.0=h7725739_2
  - pkgs/main/linux-64::libpng==1.6.37=hbc83047_0
  - pkgs/main/linux-64::libsodium==1.0.16=h1bed415_0
  - pkgs/main/linux-64::libstdcxx-ng==9.1.0=hdf63c60_0
  - pkgs/main/linux-64::libtiff==4.0.10=h2733197_2
  - pkgs/main/linux-64::libuuid==1.0.3=h1bed415_2
  - pkgs/main/linux-64::libxcb==1.13=h1bed415_1
  - pkgs/main/linux-64::libxml2==2.9.9=hea5a465_1
  - pkgs/main/linux-64::lz4-c==1.8.1.2=h14c3975_0
  - pkgs/main/linux-64::lzo==2.10=h49e0be7_2
  - pkgs/main/linux-64::markupsafe==1.1.1=py37h7b6447c_0
  - pkgs/main/linux-64::mistune==0.8.4=py37h7b6447c_0
  - pkgs/main/linux-64::nbformat==4.4.0=py37_0
  - pkgs/main/linux-64::ncurses==6.1=he6710b0_1
  - pkgs/main/linux-64::notebook==5.7.8=py37_0
  - pkgs/main/linux-64::olefile==0.46=py37_0
  - pkgs/main/linux-64::pandoc==2.2.3.2=0
  - pkgs/main/linux-64::pandocfilters==1.4.2=py37_1
  - pkgs/main/linux-64::patchelf==0.9=he6710b0_3
  - pkgs/main/linux-64::pcre==8.43=he6710b0_0
  - pkgs/main/linux-64::pexpect==4.7.0=py37_0
  - pkgs/main/linux-64::pickleshare==0.7.5=py37_0
  - pkgs/main/linux-64::pillow==6.0.0=py37h34e0f95_0
  - pkgs/main/linux-64::pip==19.1.1=py37_0
  - pkgs/main/linux-64::pkginfo==1.5.0.1=py37_0
  - pkgs/main/linux-64::prompt_toolkit==2.0.9=py37_0
  - pkgs/main/linux-64::psutil==5.6.3=py37h7b6447c_0
  - pkgs/main/linux-64::ptyprocess==0.6.0=py37_0
  - pkgs/main/linux-64::py-lief==0.9.0=py37h7725739_2
  - pkgs/main/linux-64::pycosat==0.6.3=py37h14c3975_0
  - pkgs/main/linux-64::pycparser==2.19=py37_0
  - pkgs/main/linux-64::pyopenssl==19.0.0=py37_0
  - pkgs/main/linux-64::pyrsistent==0.14.11=py37h7b6447c_0
  - pkgs/main/linux-64::pysocks==1.7.0=py37_0
  - pkgs/main/linux-64::python-dateutil==2.8.0=py37_0
  - pkgs/main/linux-64::python-libarchive-c==2.8=py37_9
  - pkgs/main/linux-64::python==3.7.3=h0371630_0
  - pkgs/main/linux-64::pyyaml==5.1.1=py37h7b6447c_0
  - pkgs/main/linux-64::pyzmq==18.0.0=py37he6710b0_0
  - pkgs/main/linux-64::readline==7.0=h7b6447c_5
  - pkgs/main/linux-64::requests==2.22.0=py37_0
  - pkgs/main/linux-64::ruamel_yaml==0.15.46=py37h14c3975_0
  - pkgs/main/linux-64::send2trash==1.5.0=py37_0
  - pkgs/main/linux-64::setuptools==41.0.1=py37_0
  - pkgs/main/linux-64::sip==4.19.8=py37hf484d3e_0
  - pkgs/main/linux-64::six==1.12.0=py37_0
  - pkgs/main/linux-64::soupsieve==1.8=py37_0
  - pkgs/main/linux-64::sqlite==3.28.0=h7b6447c_0
  - pkgs/main/linux-64::terminado==0.8.2=py37_0
  - pkgs/main/linux-64::testpath==0.4.2=py37_0
  - pkgs/main/linux-64::tk==8.6.8=hbc83047_0
  - pkgs/main/linux-64::tornado==6.0.3=py37h7b6447c_0
  - pkgs/main/linux-64::traitlets==4.3.2=py37_0
  - pkgs/main/linux-64::urllib3==1.24.2=py37_0
  - pkgs/main/linux-64::wcwidth==0.1.7=py37_0
  - pkgs/main/linux-64::webencodings==0.5.1=py37_1
  - pkgs/main/linux-64::wheel==0.33.4=py37_0
  - pkgs/main/linux-64::widgetsnbextension==3.4.2=py37_0
  - pkgs/main/linux-64::xz==5.2.4=h14c3975_4
  - pkgs/main/linux-64::yaml==0.1.7=had09818_2
  - pkgs/main/linux-64::zeromq==4.3.1=he6710b0_3
  - pkgs/main/linux-64::zlib==1.2.11=h7b6447c_3
  - pkgs/main/linux-64::zstd==1.3.7=h0b5b093_0
  - pkgs/main/noarch::backports.functools_lru_cache==1.5=py_2
  - pkgs/main/noarch::backports.tempfile==1.0=py_1
  - pkgs/main/noarch::backports.weakref==1.0.post1=py_1
  - pkgs/main/noarch::backports==1.0=py_2
  - pkgs/main/noarch::conda-verify==3.4.2=py_0
  - pkgs/main/noarch::defusedxml==0.6.0=py_0
  - pkgs/main/noarch::filelock==3.0.12=py_0
  - pkgs/main/noarch::glob2==0.7=py_0
  - pkgs/main/noarch::jupyter_core==4.5.0=py_0
  - pkgs/main/noarch::nbconvert==5.5.0=py_0
  - pkgs/main/noarch::parso==0.5.0=py_0
  - pkgs/main/noarch::prometheus_client==0.7.1=py_0
  - pkgs/main/noarch::pygments==2.4.2=py_0
  - pkgs/main/noarch::pytz==2019.1=py_0
  - pkgs/main/noarch::qtpy==1.8.0=py_0
  - pkgs/main/noarch::tqdm==4.32.1=py_0
  - pyqt
  - qt
