### ISSUE TITLE
self.bind(size=self.update) misfiring

### ISSUE THREAD

**Issue by iceblu3710** [kivy/kivy#5901]
I may just be using things wrong but I can not find a reliable way to get the current widgets size for the life of me. The code below works *SOMETIMES* but the update function is called 3 times on every resize. `[100,100],[new_x,100],[new_x,new_y]`

Is this a bug or am I doing it all wrong?

```
    def __init__(self, **kwargs):
        super(BackgroundPickDlg, self).__init__(**kwargs)
        self.bind(size=self.update)
        self.update()

    def update(self, *args):
        print('canvas: ', self.size)
        if self.imWidg.size[0] is not 100 and self.imWidg.size[1] is not 100:
```

**Comment by matham** [comment]
That's kinda expected. `size` is changed whenever `width` or `height` changes. Somehow you're changing one or both of them.
