### ISSUE TITLE
I dont have the properties lib

### ISSUE THREAD

**Issue by viquinones** [kivy/kivy#5902]
The title says it all, because of this I can't import ListProperty, ObjectProperty, etc. 
Where can I download the lib?, I already try reinstalling kivy, but it doesn't work

**Comment by inclement** [comment]
These classes are all defined in `_properties.pyx` within kivy. If you installed kivy properly, you have them. It's possible your error could relate to a compiling problem, but since you didn't post any details it isn't possible to say.
