### ISSUE TITLE
Treeview: Iterator + remove node issue

### ISSUE THREAD

**Issue by TaurenMoo** [kivy/kivy#5905]
### Versions

* Python: Latest version associated with kivy
* OS: Windows
* Kivy:1.10.1
* Kivy installation method: pip install/update

### Description

When running an iterator over all nodes in a treeview, printing that node information in the loop works fine, but when utilizing the node to remove from the treeview in order to clear out the treeview of nodes, it appears that only half the nodes are removed.  I have tried both self.ids.Skills.root.nodes and self.ids.Skills.Iterate_all_nodes. It appears that the process of removing a node somehow interacts with the list of nodes provided by the iterator and causes half of them not to be reviewed.  This only occurs when doing the remove_node(node).  If that is removed and just the information about the nodes is printed, it works fine.  

### Code and Logs

for node in self.ids.Skills.root.nodes:
            print(node.text)
            self.ids.Skills.remove_node(node)

**Comment by tshirtman** [comment]
yep, this doesn't copy the list before iterating it
https://github.com/kivy/kivy/blob/1.10.1/kivy/uix/treeview.py#L420-L422

(it's the same in current master).

We could simply add a [:] at the end of "for" lines, but the fact that it is a generator does imply that changing the list during iteration is likely to cause issues.

On your side, you could just cast the generator to a list before removing.

    for node in list(self.ids.Skills.root.iterate_all_nodes()):
        print(node.text)
        self.ids.Skills.remove_node(node)

**Comment by TaurenMoo** [comment]
I'll give the code you suggested a try when I get home, appreciate the response.
