### ISSUE TITLE
Do not include examples in manylinux wheels

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#5920]
The examples folder takes up about 10 MB, while the wheel is 25 MB.
We have separate wheels for Kivy examples: https://pypi.org/project/Kivy-examples/#files

**Comment by dessant** [comment]
I was referring to the wheels published on the server, but I don't know if the build script was fixed since they were created.

https://kivy.org/downloads/1.10.1/
https://kivy.org/downloads/ci/linux/kivy/

**Comment by tshirtman** [comment]
Seems the last build, was over two months ago, despite the cron being configured to run monthly, but the last build indeed contains the example, it's not installable on my system though, probably because of manylinux2 not being known by pypi. I'll let this aside for later.
