### ISSUE TITLE
Bug or support request?

### ISSUE THREAD

**Issue by johnlarfour** [kivy/kivy#5923]
I post here but i don't know if is a bug or a support request. If it is not a bug I close this issue.
The problem is this: https://stackoverflow.com/questions/52058611/app-crash-with-kivy-and-bs4
I read on internet there are a lot of people there are this problem so, i don't know.
Sorry if I have not respected the rules

**Comment by matham** [comment]
This belongs in the py4a or buildozer repo and not in Kivy. Also, please try to post the full issue when opening it, rather than just posting a url.
