### ISSUE TITLE
__getitem__ error for nested DictProperty

### ISSUE THREAD

**Issue by KeikiHekili** [kivy/kivy#5930]
### Versions

* Python: 2.7.6
* OS: OS X 10.11.6
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

I've got an App with a nested DictProperty, and I want to pass that to the kv file, but accessing an item in the nested dictionary fails with a ``__getitem__`` error. In the sample program below, I have a small example with a nested DictProperty. This program loads fine if you make a couple of small changes noted in the program.

### Code and Logs

	[INFO   ] [Logger      ] Record log in /Users/KeikiHekili/.kivy/logs/kivy_18-09-11_15.txt
	[INFO   ] [Kivy        ] v1.10.1
	[INFO   ] [Python      ] v2.7.6 (default, Jun 30 2014, 17:05:37) 
	[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
	[INFO   ] [Factory     ] 194 symbols loaded
	[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
	[INFO   ] [Window      ] Provider: sdl2
	[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
	[INFO   ] [GL          ] Backend used <gl>
	[INFO   ] [GL          ] OpenGL version <2.1 INTEL-10.0.52>
	[INFO   ] [GL          ] OpenGL vendor <Intel Inc.>
	[INFO   ] [GL          ] OpenGL renderer <Intel HD Graphics 3000 OpenGL Engine>
	[INFO   ] [GL          ] OpenGL parsed version: 2, 1
	[INFO   ] [GL          ] Shading version <1.20>
	[INFO   ] [GL          ] Texture max size <8192>
	[INFO   ] [GL          ] Texture max units <16>
	[INFO   ] [Window      ] auto add sdl2 input provider
	[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
	[INFO   ] [Text        ] Provider: sdl2
	 
	 Traceback (most recent call last):
	   File "/Users/KeikiHekili/Documents/bizarre.py", line 77, in <module>
		 SampleApp().run()
	   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/app.py", line 800, in run
		 root = self.build()
	   File "/Users/KeikiHekili/Documents/bizarre.py", line 72, in build
		 self.marvel = Builder.load_string(kv)
	   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/lang/builder.py", line 400, in load_string
		 self._apply_rule(widget, parser.root, parser.root)
	   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/lang/builder.py", line 630, in _apply_rule
		 e), cause=tb)
	 BuilderException: Parser: File "<inline>", line 34:
	 ...
		  32:            size_hint: 25/79., 0.15
		  33:            pos_hint: {'x': 0.68, 'y': 0.85}
	 >>   34:            text: app.dic['1']['A']
		  35:        RecycleView:
		  36:            id: rv1
	 ...
	 BuilderException: Parser: File "<inline>", line 34:
	 ...
		  32:            size_hint: 25/79., 0.15
		  33:            pos_hint: {'x': 0.68, 'y': 0.85}
	 >>   34:            text: app.dic['1']['A']
		  35:        RecycleView:
		  36:            id: rv1
	 ...
	 TypeError: 'kivy.properties.DictProperty' object has no attribute '__getitem__'
	   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/lang/builder.py", line 249, in create_handler
		 return eval(value, idmap), bound_list
	   File "<string>", line 34, in <module>
	 
	   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/lang/builder.py", line 615, in _apply_rule
		 rctx['ids'])
	   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/lang/builder.py", line 254, in create_handler
		 cause=tb)

```python

from kivy.base import runTouchApp
from kivy.app import App
from kivy.lang import Builder
from kivy.properties import DictProperty

kv = '''
BoxLayout:
    orientation: 'vertical'
    padding: 5
    spacing: 5
    FloatLayout:
        Label:
            size_hint: 25/79., 0.15
            pos_hint: {'x': 0.68, 'y': 0.85}
            text: app.dic['1']['A'] #Comment out the ['A'] with the changed DictProperty
'''

class SampleApp(App):

    dic = DictProperty({'1': DictProperty({'A': 0, 'B': 1, 'C': 2}), '2': DictProperty({'X': 3, 'Y': 4, 'Z': 5})})
    #dic = DictProperty({'1': 'A', '2': DictProperty({'X': 3, 'Y': 4, 'Z': 5})})   #Uncomment this line, comment out the line above, and comment out the ['A'] above to make this program work
    def build(self):
        self.marvel = Builder.load_string(kv)
        return self.marvel

if __name__ == '__main__':
    SampleApp().run()


```

**Comment by matham** [comment]
This is not a bug, but is because you're using `DictProperty` incorrectly. Please see our support channels for asking for further help.
