### ISSUE TITLE
Kivy Window.Size and Window.left/Window.top return incorrect values

### ISSUE THREAD

**Issue by robertmlinden** [kivy/kivy#5935]
### Versions

* Python: 3.6.6
* OS: Windows 10 PC
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

I am comparing the values that Kivy.Size and Kivy.top/Kivy.left return to the actual coordinates and dimensions of these values and they do not match.

I keep hearing things about "Window Decorators" and the measurement of where the Window _should_ be vs. where it actually is, but the documentation is weak.

I essentially have created a grid of TextInputs with no padding or anything else. Cherry-picking the relevant code would be quite painful, so hopefully there's enough information here. Window measurement values are anywhere between 20 px to 200 px off in both the x and y directions.

**Comment by tito** [comment]
Unsure about your real issue here. If by `Kivy.size` you means `Window.size`, then top and left are the size of the Window position inside your OS, and Window.size is the size of the content.

If it's not about it, please create a code + screenshots that demonstrate your issue if there is one :)
