### ISSUE TITLE
On import kivy after fresh install from DMG: dyld: lazy symbol binding failed...

### ISSUE THREAD

**Issue by dcbb** [kivy/kivy#5941]
### Versions

* Python: as packaged with Kivy 
* OS: OSX Sierra 10.12.6
* Kivy: 10.10.1 (Kivy-1.10.1_osx10.13.5_packaged_python3.6.5_r1.dmg)
* Kivy installation method: DMG download as described here: https://kivy.org/doc/stable/installation/installation-osx.html

### Description
Testing as described in the instructions on the OSX Installation guide (linked above):
In fresh terminal session
   
     kivy3

On the Python prompt:
   
    import kivy

### Code and Logs

```
Python 3.6.5 (default, Jun 18 2018, 16:36:13) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Applications/Kivy3.app/Contents/Resources/python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Applications/Kivy3.app/Contents/Resources/python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

```

**Comment by tito** [comment]
@akshayaurora Did you built the dmg? The message indicate build from 10.13 and user uses 10.12. I though there was sort-of back compatibility but no?

I guess the very first fix is to indicate 10.13 OSX version on the website, and search why it is incompatible

**Comment by dcbb** [comment]
@tito No, I didn't build, just downloaded. Just saw that the "Download" page indices that 10.13 is required. Unfortunately the installation guide does not.

**Comment by tito** [comment]
Let's see why it's only 10.13 compatible, and if that was intented, then change the documentation about it. Otherwise, need a fix on the packaging.

**Comment by tito** [comment]
I'll add a note to the documentation. The website already indicate that the dmgs are only for > 10.13.
