### ISSUE TITLE
Unable to install kivy.deps.sdl2 kivy.deps.glew to use with pyinstaller

### ISSUE THREAD

**Issue by Garcia1022** [kivy/kivy#5944]
### Versions

* Python:2.7.13
* OS: DOCKER   resin/rpi-raspbian   stretch
* Kivy: Master branch
* Kivy installation method: pip install git+https://github.com/kivy/kivy.git@master

### Description
I am trying to use pyinstaller to build an executable inside a docker container. I can get pyinstaller to make an executable, but the package is missing the SDL binaries it needs to run.

The docs say to use:

```
from kivy.deps import sdl2, glew
```

and

```
coll = COLLECT(exe, Tree('examples-path\\demo\\touchtracer\\'),
               a.binaries,
               a.zipfiles,
               a.datas,
               *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               strip=False,
               upx=True,
               name='touchtracer')
```

but I get this when trying to install those dependencies

```
pi@raspberrypi:~/ $ sudo pip install kivy.deps.sdl2
Collecting kivy.deps.sdl2
  Could not find a version that satisfies the requirement kivy.deps.sdl2 (from versions: )
No matching distribution found for kivy.deps.sdl2
```

These packages are available in pip search though

```
kivy.deps.angle (0.1.7)           - Repackaged binary dependency of Kivy.
kivy.deps.glew (0.1.10)           - Repackaged binary dependency of Kivy.
kivy.deps.glew_dev (0.1.10)       - Repackaged binary dependency of Kivy.
kivy.deps.gstreamer (0.1.13)      - Repackaged binary dependency of Kivy.
kivy.deps.gstreamer_dev (0.1.13)  - Repackaged binary dependency of Kivy.
kivy.deps.sdl2 (0.1.18)           - Repackaged binary dependency of Kivy.
kivy.deps.sdl2_dev (0.1.18)       - Repackaged binary dependency of Kivy.
```

When running:
```
[INFO   ] [Logger      ] Record log in /usr/src/app/logs/kivy_18-09-25_0.txt
[INFO   ] [Kivy        ] v1.11.0.dev0, git-42c0a90, 20180925
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers:  (img_tex, img_dds, img_ffpyplayer, img_gif, img_pil, img_sdl2 ignored)
[CRITICAL] [App         ] Unable to get any Image provider, abort.
[INFO   ] [Logger      ] Record log in /usr/src/app/logs/kivy_18-09-25_1.txt
[INFO   ] [Kivy        ] v1.11.0.dev0, git-42c0a90, 20180925
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]

```
 I will note that if I install all the kivy dependencies and run my app like normal inside the docker container, everything works fine.

**Comment by matham** [comment]
Kivy.deps.xxx are only used in windows and those pyinstaller guides you followed were for windows, not linux.

**Comment by cristianmejiaarias** [comment]
try to install 
pip3 install kivy-deps.glew
pip3 install kivy-deps.sdl2

or
pip install kivy-deps.glew
pip install kivy-deps.sdl2

**Comment by aftercarnival** [comment]
The same here. Coudn't install.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
15/09/20
17:57:22

Em ter., 15 de set. de 2020 às 16:45, cristianmejiaarias <
notifications@github.com> escreveu:
