### ISSUE TITLE
Video loop does not work

### ISSUE THREAD

**Issue by chintal** [kivy/kivy#5945]
### Versions

* Python: 3.5.3
* OS: Raspbian GNU/Linux 9.4 (stretch)
* Kivy: git-bf8869f, 20180726
* Kivy installation method: from source, clone and python setup.py

### Description

I'm using the Video widget to display a video on loop on a Raspberry Pi. The method I used earlier worked perfectly well. I made some unrelated changes to my software and the current version stops on eos instead of looping around. Kivy version was not changed. The code works perfectly fine on regular linux with the same kivy version, though other dependencies and python version might be slightly different. 

I know it's a development version and things might not work as expected, but I require some feature that was 1.10+ (I don't remember which). I have a functioning workaround so it's not critical to me at the moment, but a pointer to where to look to debug this problem and figure out where it came from would help.

### Code and Logs

The code below works as expected. `_when_done()` is called, it restarts the video.

```python

bg_video = Video(
    source=value, state='play',
    allow_stretch=True, # eos='loop'
)

def _when_done(*_):
    _bg_video.state = 'play'
_bg_video.bind(eos=_when_done)

```

The code below, however, does not. `_when_done()` is never called (which it should not be anyway, I think. It doesn't get called on the x64 ubuntu as well.), but the Video's `eos='loop'` seems to not do what it is supposed to. The video stops after exactly one play.

```python

bg_video = Video(
    source=value, state='play',
    allow_stretch=True, eos='loop'
)

def _when_done(*_):
    _bg_video.state = 'play'
_bg_video.bind(eos=_when_done)

```

**Comment by tshirtman** [comment]
Do you ever stop the video at any point before that happens? Doing a PR that might fix it if that's the case, as the Video widget did wrongly remove the eos setting when that happens.

**Comment by chintal** [comment]
@tshirtman I think I sometimes pause it, but not stop it. I'll retest with the latest version over the next week or two and confirm if the problem still exists.
