### ISSUE TITLE
Help w/ Fonts - App crashes after font change

### ISSUE THREAD

**Issue by Petar-Luketina** [kivy/kivy#5948]
Hello everyone,

I'm trying to change the font in Kivy. I successfully changed the font in PyCharm and the app runs fine on the desktop. I used `LabelBase.register(name = "Capsuula", fn_regular = "Capsuula.ttf")` . But every time I open it on Android it crashes...

- I put the ttf file with main.kv and main.py files before debugging and deploying.

- The logcat says that it cannot find the Capsuula.ttf and Capsuula.ttfs files.

- I checked inside the Buildozer file and Buildozer didn't port over the font file. Then I tried to manually paste the .ttf file into the Buildozer app folder but that didn't help.

**What steps am I missing here? Has anyone gotten different fonts to work in Kivy?**

I would appreciate any suggests or tips. Thank you in advance!!!

**Comment by pythonic64** [comment]
Did you add `ttf` to `source.include_exts` in buildozer spec file? Example:
```source.include_exts = py,png,jpg,kv,atlas,ttf```

**Comment by Petar-Luketina** [comment]
@pythonic64 Thank you so much! Yes, how could have I forgotten about that. I've never had to update it before so I missed it. Hvalati, Filip.
