### ISSUE TITLE
No Text Render 

### ISSUE THREAD

**Issue by vahurtad** [kivy/kivy#5949]
### Versions

* Python: 3.6.7
* OS:  Windows 10 x64
* Kivy: v1.10.1
* Kivy installation method: [kivy website](https://kivy.org/doc/stable/installation/installation-windows.html)

### Description

Render a basic button

### Code and Logs

```python
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')
if __name__ == "__main__" :
    TestApp().run()
```

![image](https://user-images.githubusercontent.com/16183561/46251817-f09bd500-c412-11e8-97b8-da74fff77640.png)
Here is my log:

![image](https://user-images.githubusercontent.com/16183561/46251830-3bb5e800-c413-11e8-9e0e-99082926bdda.png)

**Comment by tshirtman** [comment]
Doesn't seem to be specific to text, but nothing displayed at all, can you run with 

python main.py -c kivy:log_level:debug

and see if you get more info? can you also try resizing the window to see if it triggers a draw? Is the gpu something exotic?

**Comment by vahurtad** [comment]
@tshirtman 
Graphics is Intel HD

![image](https://user-images.githubusercontent.com/16183561/46262089-4b840980-c4b1-11e8-9d7d-e72300988e6a.png)

**Comment by matham** [comment]
Do you have kivy.deps.glew installed? It seems to you're suing angle rather than glew, is there a reason for this?

**Comment by vahurtad** [comment]
@matham There's no particular reason.
uninstalling angle and making sure I have glew installed gives me another error:
`[CRITICAL] [Window      ] Unable to find any valuable Window provider.`
`sdl2 - RuntimeError: b'Could not initialize OpenGL / GLES library'`

**Comment by matham** [comment]
Seems like there are gl issues with your system. What is the system? A
desktop? Laptop? Etc. Is it a VM?

**Comment by vahurtad** [comment]
@matham a laptop
Pentium 64 bit
Intel HD graphics

**Comment by matham** [comment]
This seems like an issue specifically with your system and not a bug in Kivy. I'd suggest you ask on the support channels.

**Comment by matham** [comment]
If there are more details that may help, please feel free to re-open.

I would also suggest you go to the manufacturer's website and update the graphics drivers to the latest and see if it fixes it.
