### ISSUE TITLE
In Texture blit_buffer, cast from unsigned short (and int) don't work

### ISSUE THREAD

**Issue by maddyaby** [kivy/kivy#5956]
### Versions

* Python: 3.6
* OS: Windows
* Kivy: 1.10.1
* Kivy installation method: anaconda

### Description

I'm trying to blit a buffer to a texture with type uint16 / ushort / unsigned short. This results in an error on line 941 of kivy/graphics/texture.pyx. It seems as if the cast from unsigned short to short failures here:
```python
        cdef short [:] short_view
          ...
            elif glbufferfmt == GL_SHORT or glbufferfmt == GL_UNSIGNED_SHORT:
                short_view = pbuffer
```
I changed the source and rebuilt to handle the unsigned and signed cases separately with the proper C type and this seems to work.

The same problem seems to apply to the 32-bit int type in the lines following.

**Comment by matham** [comment]
Would you like to submit a pull request?

**Comment by maddyaby** [comment]
Sure! I can do that this weekend

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/5980
