### ISSUE TITLE
Kivy requires Cython to be installed by the user in some situations, which makes depending on it as a package problematic

### ISSUE THREAD

**Issue by flaviusb** [kivy/kivy#5984]
### Versions

* Python: Python 3.6.5
* OS: Linux (4.12.12-gentoo x86_64)
* Kivy: 1.10.1
* Kivy installation method:  install_requires in setup.py
### Description

I am trying to create a package that uses kivy, that a user can install using pip, so that I can upload it to PyPI. This is a package that a user should be able to have as a dependency in their own package using the usual 'install_requires' method in setup.py, ideally using vanilla setuptools. At present, I have to install Cython separately in order to get Kivy to install, as Kivy does not correctly manage its dependencies.

### Code and Logs

After clearing out wheel cache, to replicate installing on a fresh system, and in the directory I am developing the package in:

```
$ virtualenv --no-site-packages install
Using base prefix '/usr'
New python executable in /home/flaviusb/code/rvit/install/bin/python3.6
Also creating executable in /home/flaviusb/code/rvit/install/bin/python
Installing setuptools, pip, wheel...done.
$ . install/bin/activate
(install) $ pip install -e .
Obtaining file:///home/flaviusb/code/rvit
Collecting kivy (from rvit==0.1)
  Using cached https://files.pythonhosted.org/packages/7d/8b/89d220b7f96dc2662b81319067f679b4cd73cda66f4aa850db5b6c6cfc7a/Kivy-1.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Using distutils
    
    Cython is missing, it's required for compiling kivy !
    
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qf1pe7c9/kivy/setup.py", line 232, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qf1pe7c9/kivy/


```

**Comment by tshirtman** [comment]
Yes, i opened this one #5558 some time ago to try to find a solution to this, i tried to ship the code in the package to avoid the build time dependency on cython, but since the generated C code depends on the python version, we would need multiple source packages, and i didn't investigate yet if this was possible.

**Comment by tito** [comment]
IMO, either there is a wheel so you don't need Cython, either you install source version therefore Cython is required? Trying to create a source version containing all potential python version seems counter-intuitive

**Comment by tshirtman** [comment]
Some platforms don't have a wheel (e.g rpi though it seems it would be possible https://www.piwheels.org/), and the linux wheel certainly can't be official yet (as it depends on the provisionnal manylinux2010 definition https://github.com/pypa/manylinux/pull/182).

**Comment by flaviusb** [comment]
@tito for clarity, just confirming that in the case there is no wheel, the user would have to separately install cython first, as putting it in the `install_requires` of a project that depends on kivy would not work, as pip builds each dependency for a project isolated so that it can only see it's own dependencies plus the user environment, and kivy does not register a dependency on cython through `install_requires` or other equivalent means in these problematic situations at present.

**Comment by flaviusb** [comment]
Would a work around like having an extras option to override the cython checking segment of kivy's setup.py to add cythong to the install_requires be something that makes sense for kivy (eg https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)?

**Comment by flaviusb** [comment]
Some related issues I had not found until now:
#5375 #4675 https://github.com/pfassina/callllama/issues/2

**Comment by vkuehn** [comment]
for Cpython and Pygame I have been fallen in the same trapp. Manually installing worked.
However it's a pain when you like to create a setup

**Comment by rootVIII** [comment]
Having this issue on Ubuntu 16.04 with python3... bummer

**Comment by vkuehn** [comment]
from the comments before I would expect that this is always an issue

**Comment by farleylai** [comment]
Since the release cycle is kind of long, installing from the repo is a common practice. Without Cython declared as the dependency, pip is not going to install in the right order of a requirements.txt.

**Comment by JonasT** [comment]
pip installs setup_requires, doesn't it? Would it help to add Cython to setup_requires instead of install_requires? I imagine that might not have it packaged up in the actual binary wheel later on but I haven't tested it

**Comment by flaviusb** [comment]
The PR #5998 has been merged, which should fix this issue.
