### ISSUE TITLE
RecycleView not updating correctly after editing a value

### ISSUE THREAD

**Issue by lengross** [kivy/kivy#5989]
* Python: 3.6
* OS: Win 7/Pycharm  and Android via Buildozer
* Kivy: : 1.10.1
* Kivy installation method:  Via Pycharm / virtualenv

This is a "toy version" of a more complex piece of code.  The code fills rows of a recycle view and they are initially displayed properly.  Each button on the view can be clicked and its values incremented by 100

Steps to reproduce:
The “fill values" button  fills 5 rows of the recycleview
Now, click on row 0 , and the text increments by 100 (0 -> 100)
Click on “fill values” and it resets the data  to the original values,as expected
Same works with row 1 (1=> 101)
Hit Set Values, and row is reset as expected
Now click on row two 2 (2 -> 102 )
Now hit “Fill values” and the data on row 2 is not reset!  There is nothing special about row 2.
The row that has this behavior changes if you change the number of displayed rows, but the error
seems to only happen if the number of displayed rows is odd

[blast100.zip](https://github.com/kivy/kivy/files/2467012/blast100.zip)

**Comment by tito** [comment]
The RecycleView cache widget to prevent re-creation and speedup the scrolling.
Each time a widget is created or used, the attribute you specified are set on the widget.

`value1` have no impact if the widget are recreated. When you increment, you increment the text, not value1. So in your case, you're mutating your widget from the text itself, but use value1 only when it is set the first time.

The resolution of your issue is to change value1 to `NumericProperty`, and use it:

Python part:
```python
        self.rv.data = [{"viewclass": "Row",'value1': x} for x in range(5)]
```

KV path:
```
    value1: 0
    Button:
        text: str(root.value1)
        on_release: root.value1 += 100
```

Note: you don't need `self.rv.refresh_from_data() anymore`

**Comment by lengross** [comment]
Thank you for the for the rapid and detailed reply.  I do have a question and comment.

 

1)  Why do some of the rows (widgets) reset correctly  when the "fill values" button is clicked?

Only row 2 has this behavior.  From your explanation, it seem like the "fill values" button (or clear for that matter) should never work.

 

2) I can get it to work without adding numeric_property, by the following change in kv part:

 

before code:

Button:
    text: root.value1
    on_release: self.text = str(int(self.text) + 100)

 

Changed code (self.text changed to root.text)
Button:
    text: root.value1
    on_release: root.value1 = str(int(self.text) + 100)

 

You have to leave in the refresh_from_data in the python part.

So, I assume this works because the value1 change is now getting propagated "automagically" to the button label?

 

Frankly, it is hard to form the correct "mental model" for how this is really working.

 

3) By its name, I would expect "refresh_from_data" to also refresh the data in the cached widgets themselves, but evidently

not.   The documentation says:  

"This should be called when data changes. Data changes typically indicate that everything should be recomputed since the source data changed"

This is a  bit misleading.  Perhaps a  note should be made or a "force_refresh" function

should be made available.

 

Thanks again.

--Len

**Comment by tito** [comment]
Your passed data to a widget. Those key are set on an widget instance that may be cached in recycleview. Let's say rv will reuse a previous widget with value1=10, and you changed manually text to 200.

Case 1, the data contains value1=20. The value1 property will have a new values, so all the observers attached to it will be dispatched. So the kv Lang will know to reeavluate the text rule that contains value1. 

Case 2, the data contains value1=10. It is the same as the reused widget instance. So no observers will be dispatched, therefore kv Lang will not reeavluate the text rule, so the text will not change. 

The issue you have came from case 2. Documentation may be clearer about the widget cache that may be reuse, but recycleview or not, you could have this issue yourself in your code. The fact that you change manually the text But have a rule that change it depending another property is not a good pattern. Unless you don't understand where value1 is set and dispatched, the text you set could be reset anywhere. It is more an anti pattern.

I showed you a better pattern, that prevent any issue and clear to understand without intricate mutations.

**Comment by tito** [comment]
If you adopt my pattern, if the widget value1 is the same as the one in the data, then the text is already sync, and it would be even faster.

**Comment by lengross** [comment]
I implemented your changes, but it's still not working (unless I leave in refresh from data).  I'm sure it is dumbness on my side, but here is the use case. (My "bug" sample highlighted an issue, but is not the real use case.)

Here is a better explanation:

 

User changes a value in a row (value1).  

 

At some point, I want to save the user's changes (which will actually have other fields in the real app)

 

I "assumed" that if I look at rv data it would show the updates the user made to value1.

I would then take the rv data (in whole) and save it to a file (using pickle for now).

 

I tried your patern,  NumericalProperty, but it did not update the rv data.  I can catch the change with on_value1, so I know I have the property implemented, but perhaps it is in the wrong place.   Should your pattern have modified the rv data itself?

 

I'm really stuck and have tried lots of variations including list properties.

 

--Len

**Comment by lengross** [comment]
I think my last email probably confused two things:

1) The original problem is  still not working, but I probably did not implement your approach correctly.

2) A different, second issue, how to get rv data to update when a user changes "value1" in the UI.  I wan that so I can save a row with the modifications to disk, and think a save of rv data would be appropriate..

 

Sorry about the added confusion.   I'm still playing with both problems but no luck yet.

 

--Len

 

From: Len Gross <LenGross@san.rr.com> 
Sent: Thursday, October 11, 2018 3:50 PM
To: 'kivy/kivy' <reply@reply.github.com>; 'kivy/kivy' <kivy@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [kivy/kivy] RecycleView not updating correctly after editing a value (#5989)

 

I implemented your changes, but it's still not working (unless I leave in refresh from data).  I'm sure it is dumbness on my side, but here is the use case. (My "bug" sample highlighted an issue, but is not the real use case.)

Here is a better explanation:

 

User changes a value in a row (value1).  

 

At some point, I want to save the user's changes (which will actually have other fields in the real app)

 

I "assumed" that if I look at rv data it would show the updates the user made to value1.

I would then take the rv data (in whole) and save it to a file (using pickle for now).

 

I tried your patern,  NumericalProperty, but it did not update the rv data.  I can catch the change with on_value1, so I know I have the property implemented, but perhaps it is in the wrong place.   Should your pattern have modified the rv data itself?

 

I'm really stuck and have tried lots of variations including list properties.

 

--Len

**Comment by tito** [comment]
If you wanna continue the discussion, please post on the ML or discord to get help. The tracker is for issues within Kivy, not adapted for user support. The issue you reported works after the change, so maybe you have something else that works against your wish.

**Comment by lengross** [comment]
Will do, thanks.

--Len
