### ISSUE TITLE
Update default Ubuntu 18.04 python3 packages

### ISSUE THREAD

**Issue by naevtamarkus** [kivy/kivy#5994]
### Versions

* Python: 3.6.6
* OS: Ubuntu 18.04.1
* Kivy:1.9.1-1build3
* Kivy installation method: default ubuntu (apt-get install python3-kivy), no PPA

### Description
The problem is a known problem (I've seen it in the Issue list, see the log below): kivy does not work on Ubuntu 18.04 with python3 with a classic hello-world example (code is also below).

But everyone points to two possible solutions:
- Use python2 (I tried, and it works), or
- Use the Kivy PPA (I did not try, but it works for a lot of people)

My problem is that I don't want to encourage my users to go for neither one of those: python2 is already in the past, and installing 3rd party PPAs is undesirable for both inexperienced users and security-concerned experienced users.

So, I would like to kindly ask the development team to provide a working python3-kivy package through the official Ubuntu 18.04 channels. It does not need to be the shiniest and greatest of versions, just a working version every now and then.

Thanks!

### Code and Logs
Code:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()
```

And logs:
```
[WARNING] [Config      ] Older configuration version detected (0 instead of 14)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/xxx/.kivy/logs/kivy_18-10-15_0.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - TypeError: expected bytes, str found
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 138, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 722, in __init__
    self.create_window()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 237, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 94, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:2204)

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kivy/utils.py", line 513, in __get__
     retval = self.func(inst)
   File "/usr/lib/python3/dist-packages/kivy/metrics.py", line 175, in dpi
     EventLoop.ensure_window()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 126, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by averydark** [comment]
I followed the guide, installed the depends, and set everything up for python3 and it just gives me the same exact issue to the letter. 

I also agree with this; python2 is going to be deprecated next year and ppa's (while I'm not completely against it; I do use it in special instances), its preferred to just install from the repo. It's just easier that way rather than adding another source to the list.

The other thread regarding this issue (#4385) was locked, so I couldn't add anything to it.

```bash
$ sudo find /usr/lib/python3/dist-packages/kivy/ | grep -i window
/usr/lib/python3/dist-packages/kivy/core/window
/usr/lib/python3/dist-packages/kivy/core/window/__init__.py
/usr/lib/python3/dist-packages/kivy/core/window/__pycache__
/usr/lib/python3/dist-packages/kivy/core/window/__pycache__/window_egl_rpi.cpython-36.pyc
/usr/lib/python3/dist-packages/kivy/core/window/__pycache__/window_pygame.cpython-36.pyc
/usr/lib/python3/dist-packages/kivy/core/window/__pycache__/window_sdl2.cpython-36.pyc
/usr/lib/python3/dist-packages/kivy/core/window/__pycache__/__init__.cpython-36.pyc
/usr/lib/python3/dist-packages/kivy/core/window/_window_sdl2.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py
/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py
/usr/lib/python3/dist-packages/kivy/core/window/window_pygame.py
```

`$ cat -n /usr/lib/python3/dist-packages/kivy/core/window/__init__.py | less`

```python
1571  if platform == 'linux':
1572      window_impl += [('x11', 'window_x11', 'WindowX11')]
```

It's just interesting to see that there is no `kivy.core.window`. Also, there is no reference to `sdl2` or `pygame` either. I have `sdl2` and `pygame` installed because I am interested in those packages and have been studying `pygame` recently which uses `sdl1.2` (even in python3).

This is what I came up with while just doing some superficial checking and a little bit of digging. Not sure why this issue hasn't been bumped up and any related issues are locked or closed. All other solutions seem to be MS Windows focused.

**Comment by matham** [comment]
Ubuntu does have [kivy packages](https://packages.ubuntu.com/search?keywords=python-kivy), but we have no control over them. It wasn't built by us or with our input as far as I know. Also, anecdotally, they don't work.

Ubuntu seems to have [update policies](https://wiki.ubuntu.com/StableReleaseUpdates) which would preclude them from being able to update the kivy packages to more recent versions. Someone could try to contact them to add a newer version of kivy to their upcoming released images, but I'm not sure what their process is.

I'm closing this for now as there doesn't seem to be much we can do about this.
