### ISSUE TITLE
New cache logging method breaks Android app

### ISSUE THREAD

**Issue by misl6** [kivy/kivy#5996]
### Versions

* Python: 3.6 Crystax (custom recipe w/ android SDK 26)
* OS: Android 8.0
* Kivy: master
* Kivy installation method: p4a recipe

### Description

After 60 secs the app become unresponsive (no error in logs).
Consider that I'm using a custom (Hacky) python3crystax w/ API 26 dist, so, maybe, before considering it confirmed it needs some some tests with another dist.

### Code and Logs
Workaround:
Comment the following logger statement in kivy/cache.py
```python
Logger.debug('Cache: Removed %s:%s from cache due to '
                 'timeout' % (category, key))

```

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/5995 may have fixed it. Can you try with master?

**Comment by misl6** [comment]
I can confirm that #5995 fixed it.
