### ISSUE TITLE
disabled for settings of boolean type 

### ISSUE THREAD

**Issue by vivsec** [kivy/kivy#6002]
### Versions

* Python: 2.7.
* OS: Windows
Kivy: 1.10.1
Kivy installation method: pip install git+https://github.com/kivy/kivy.git@1.10.1

### Description

In Kivy 1.10.0 I was able to use the disabled feature for children while adding the setting using
 add_ json_ panel and on startup the panel would be disabled (greyed out) but it doesn't work in 1.10.1. Is there a way I can disable a setting using json_panel?

### Code and Logs

	{
        "type": "bool",
        "title": "Example",
        "section": "xxxx",
        "key": "images",
        "disabled": 1        
	},
I was able to add the above and the panel would be disabled but now it doesn't work with 1.10.1

Thanks

**Comment by pythonic64** [comment]
Try installing Kivy from master branch or nightly wheel for your Python version and see if it works then.

**Comment by matham** [comment]
I tried it with master, and it works fine. Can you give a very small self contained example showing the issue?
