### ISSUE TITLE
Kivy and an "official" 3D addon

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#6004]
Lately playing around with 3D and kivy. There are some addons out there trying to provide basic 3D support:

* https://github.com/kpiorno/kivy3dgui
* https://github.com/nskrypnik/kivy3
* https://github.com/kivy-garden/garden.ddd
* maybe others

As follow up to some discussion on discord, this issue is about consolidation of basic 3D support under the hood of kivy organization.

From the code base, kivy3 seems the most appropriate (and recently receiving the most attention/contributions) as a solid foundation.

This raises the following questions:

* Does the community agree there's the need for an "official" 3D addon?
* Does the community agree that kivy3 is a hot candidate as base for the efforts?
* Does the original author @nskrypnik is fine if it comes to a decision?

@tito @KeyWeeUsr @tshirtman

**Comment by rnixx** [comment]
@KeyWeeUsr last week i spent time with a mate watching your video tutorials. Thanks a lot for them!
I also based my sandbox work on your fork. Just created a PR on your fork with my changes here https://github.com/KeyWeeUsr/kivy3/pull/6

**Comment by reynum2** [comment]
Yes an official 3D toolkit for Kivy (like kivy3) is a great idea 😀

**Comment by kpiorno** [comment]
I've developed kivy3dgui inspired by the Kivy's language and the kivy's design (as a superset of Kivy's NUI). The aim was make it using kind of 3d layouts and be ease to use. Besides, embedding 2D GUI elements in 3D meshes allowing interactions. IMHO, this aproach feels natural for Kivy's 3D interfaces. Although, there are many edges to sharpen (Add templates, 3D containers, abstraction of camera settings, etc...). In the other hand, I think the others aproachs are 3d frameworks (very good solutions using the traditional way) and kivy3dgui is inspired by how Kivy works. 
I'm very intersting to work on this, I think we can join efforts and write a draft with the final proposal to develop an official 3d "component, addon, etc.." for Kivy.

**Comment by rnixx** [comment]
Hi,

recently @JohnSumskas and @sabarlow did a lot of work on kivy3 here https://github.com/JohnSumskas/kivy3/tree/development

They implemented:
* STL Loader
* URDF Loader (Universal Robot Description File)
* Orbit Control Widget
* Selection Control Widget (Be able to select and move 3D objects)
* Variety of Basic Geometries (Box, Cylinder, Cube, Cone)

They based their work on the @KeyWeeUsr fork.

I think finally it's time to concentrate all the efforts done so far under the hood of the kivy organization to avoid further cluttering.

I already talked to @JohnSumskas and @sabarlow and they are fine with consolidating the work.

Can someone fork the project from /JohnSumskas/kivy3 and give us admin access to the repo please?

The other option would be to create a kivy3 organization, but i doubt there is any benefit in doing so.

Thanks in advance.

@tito @KeyWeeUsr @kpiorno @nskrypnik @tshirtman

**Comment by rnixx** [comment]
### And here we go!

https://github.com/kivy/kivy3

Thank you @tshirtman

**Comment by KeyWeeUsr** [comment]
https://github.com/pypa/pypi-support/issues/407#issuecomment-633105580
