### ISSUE TITLE
Getting Error while creating APK

### ISSUE THREAD

**Issue by SathishkumarGanesanK** [kivy/kivy#6010]
### Versions

* Python: 3.6
* OS: Ubuntu 18.04
* Kivy: 1.10.1
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name myapp --name 'My Application' --version 0.1 --package org.test.myapp --android_api 19 --minsdk 9 --private /home/developer/Desktop/App/.buildozer/android/app --orientation portrait --window --copy-libs --arch armeabi-v7a --color=always --storage-dir=/home/developer/Desktop/App/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by AndreMiras** [comment]
Sorry you reported to the wrong project, you probably wanted python-for-android or buildozer.
However you don't provide enough log details to identify the bug.
If what you wanted was not a bug report but you looked for help, it's better to use Discord chat.
