### ISSUE TITLE
on_config_change: refresh settings screen

### ISSUE THREAD

**Issue by Matteljay** [kivy/kivy#6014]
### Versions

* Python: 3.7.1
* OS: Arch Linux
* Kivy: 1.10.1-2
* Kivy installation method: pacman

### Description

In the settings panel, I don't always agree with the user's input.
For example a user enters a negative/floating point number or a file path which does not exist.
Then i want to reject or modify the user's choice in the settings panel.
Naturally, i go for the on_config_change() event and put some config.set() command there.

Problem: this doesn't update the settings panel at all. User input cannot be rejected.

Found someone else describing the same problem here: [link-to-google-groups](https://groups.google.com/forum/#!topic/kivy-users/2zpMnoHBoTk)

**Comment by tshirtman** [comment]
https://gist.github.com/tshirtman/acb5ab2e193b7231b25869e8db03f9d2

it's slightly unrelated, but this code show a way to update the interface when there are changes.

**Comment by Julian-O** [comment]
Closing as no plan to implement.
