### ISSUE TITLE
ActionGroup inside ActionGroup

### ISSUE THREAD

**Issue by Eduardoveras** [kivy/kivy#6018]
### Versions

* Python: 3
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

while trying to add an actionGroup inside another Actiongroup, the dropdown gets dismissed when clicking the first group items, making the inner group not accessible.  

### Code and Logs

`
actionbar = F.ActionBar(pos_hint={'top': 1})

        av = F.ActionView()
        av.add_widget(F.ActionPrevious(title='Action Bar', with_previous=False))
        av.add_widget(F.ActionOverflow())
        av.add_widget(F.ActionButton(text='Btn0',
                      icon='atlas://data/images/defaulttheme/audio-volume-high'))

        #ag = F.ActionGroup(text='Group1')
        #for i in range(5, 13):
        #    ag.add_widget(F.ActionButton(text='Btn{}'.format(i)))

        for menu_key, sub_menu in Menus.items():
            ag = F.ActionGroup(text=menu_key)
            for sub_menu_key, items in sub_menu.items():
                sub_menu_menu = F.ActionGroup(text=sub_menu_key)
                sub_menu_menu.add_widget(F.ActionButton(text="hello world"))
                sub_menu_menu.add_widget(F.ActionButton(text="hello world"))
                ag.add_widget(sub_menu_menu)

            av.add_widget(ag)

        #av.add_widget(ag)

        actionbar.add_widget(av)

        # can't be set in F.ActionView() -- seems like a bug
        av.use_separator = True

        return actionbar
`

**Comment by Julian-O** [comment]
Hi @Eduardoveras,

Is this still an issue in Kivy 2.2.1?

Can you produce a minimal program that can be run that demonstrates the problem?
