### ISSUE TITLE
Error when building on Buildower virtual machine

### ISSUE THREAD

**Issue by yahya-abou-imran** [kivy/kivy#6019]
Using the latest Buildozer virtual machin (20), when building app using:
`$ buildozer android_new debug deploy run logcat`
I got an error. After setting log_level on 2 in buildozer.spec, found out it was:
```
<myfloder>/tmp-src/org/kivy/android/PythonService.java:108: error: multi-catch statement is not supported in -source 1.5	
    [javac]             } catch (NoSuchMethodException | IllegalAccessException |	
```

**Comment by AndreMiras** [comment]
https://github.com/kivy/buildozer/issues/625
https://github.com/kivy/python-for-android/issues/1200
https://github.com/kivy/python-for-android/issues/1212
