### ISSUE TITLE
package distribution vs icon pixmaps path desktop entry

### ISSUE THREAD

**Issue by Matteljay** [kivy/kivy#6021]
### Versions

* Python: 3.7.1
* OS: Arch Linux
* Kivy: 1.10.1-2
* Kivy installation method: pacman

### Description

When distributing a Kivy app, the resource files can end up at unpredictible places on different systems or Linux distributions. (setuptools & pip don't really help either!)
This is especially a problem for the application icon IMHO. Most desktops nowadays will search both:
/usr/share/pixmaps/ & /usr/local/share/pixmaps/
for the icon file so that it shows up correctly and the developer need not specify an absolute path in the appname.desktop file.

Please add this functionality to Kivy as well. I'd just like to specify self.icon="appname" and it would add some common file extensions and locations to "appname" to find a match.

**Comment by drunkwcodes** [comment]
You can distribute resource files by writing `MANIFEST.IN` and use relative path open the resources.

https://stackoverflow.com/questions/7923509/how-to-include-docs-directory-in-python-distribution

**Comment by Matteljay** [comment]
Thanks, your solution is probably better & more professional than using the data_files in setup.py.
Still, i cannot imaging that using MANIFEST.in will tell setuptools to parse my main "appname.py" line-by-line and replace every instance of:
self.icon = "share/pixmaps/icon.png"
with the required absolute path for Kivy:
self.icon = "/usr/local/or/whatever/share/pixmaps/icon.png"

**Comment by drunkwcodes** [comment]
You can use `os.path.dirname(__file__)` to find current file's location, [os.path.abspath](https://docs.python.org/3/library/os.path.html#os.path.abspath) to see the absolute path, and `os.path.join`, etc. to do some path manipulation.

**Comment by tito** [comment]
What you ask is something that you have to deal for any resource, not only the icon you set.
This is why we have a kivy.resource module: all the data you pass somehow to kivy (source image path, audio path, etc) are resolved through kivy.resource.

If the installation path that we have no idea at the end, is not within kivy.resource, then you'll ends up with various issues.

Maybe have a look at pkgutil?

**Comment by Matteljay** [comment]
Aha! I will definitely be looking at these: [kivy.resource](https://kivy.org/doc/stable/api-kivy.resources.html) & [pkgutil](https://docs.python.org/3/library/pkgutil.html)
Thank you
