### ISSUE TITLE
[CRITICAL] [App         ] Unable to get a Text provider, abort

### ISSUE THREAD

**Issue by thagh05t** [kivy/kivy#6022]
### Versions

* Python: v3.6.7rc1 (v3.6.7rc1:311101f7b6, Sep 26 2018, 15:43:06) [MSC v.1900 32 bit (Intel)]
* OS: Windows 10 x64
* Kivy: v1.10.1
* Kivy installation method: pip

### Description

I am trying to run any Kivy example on the above setup.

### Code and Logs

```shell
"C:\Program Files (x86)\Python36-32\python.exe" "C:/Program Files (x86)/Python36-32/share/kivy-examples/settings/main.py"
[INFO   ] [Logger      ] Record log in C:\Users\m4k3r\.kivy\logs\kivy_18-10-27_124.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7rc1 (v3.6.7rc1:311101f7b6, Sep 26 2018, 15:43:06) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ImportError: DLL load failed: The specified module could not be found.
  File "C:\Users\m4k3r\AppData\Roaming\Python\Python36\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\m4k3r\AppData\Roaming\Python\Python36\site-packages\kivy\core\window\window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] [Text        ] Unable to find any valuable Text provider.
sdl2 - ImportError: DLL load failed: The specified module could not be found.
  File "C:\Users\m4k3r\AppData\Roaming\Python\Python36\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\m4k3r\AppData\Roaming\Python\Python36\site-packages\kivy\core\text\text_sdl2.py", line 12, in <module>
    from kivy.core.text._text_sdl2 import (_SurfaceContainer, _get_extents,

pil - ModuleNotFoundError: No module named 'PIL'
  File "C:\Users\m4k3r\AppData\Roaming\Python\Python36\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\m4k3r\AppData\Roaming\Python\Python36\site-packages\kivy\core\text\text_pil.py", line 7, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.

Process finished with exit code 1
```

**Comment by Sithell** [comment]
I have the same problem

**Comment by Sithell** [comment]
try this:
pip install --upgraade pip wheel setuptools
pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
pip install kivy.deps.gstreamer
pip install kivy.deps.angle
pip install --upgrade kivy

http://qaru.site/questions/2426144/kivy-error-critical-text-unable-to-find-any-valuable-text-provider-python-361-windows-10

**Comment by tito** [comment]
Check the FAQ: https://kivy.org/doc/master/faq.html?highlight=faq#unable-to-get-a-window-abort

**Comment by santosvda** [comment]
> try this:
> pip install --upgraade pip wheel setuptools
> pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
> pip install kivy.deps.gstreamer
> pip install kivy.deps.angle
> pip install --upgrade kivy
> 
> http://qaru.site/questions/2426144/kivy-error-critical-text-unable-to-find-any-valuable-text-provider-python-361-windows-10

Thank You!

**Comment by jorgeastiazaran** [comment]
https://stackoverflow.com/a/56865754/11296112

In PyCharmm in the Project Interpreter, add all the packages that start with:

kivy-deps.

With the exclusion of the ones with "dev" in the title
