### ISSUE TITLE
unable to launch examples (segmentation fault)

### ISSUE THREAD

**Issue by StanSmooth** [kivy/kivy#6030]
### Versions

* Python: v2.7.13
* OS: Raspbian 9 (stretch)
* Kivy:  v1.11.0
* Kivy installation method: downloaded on git then make (as in the tutorial)

### Description

Hi,
I would like to reuse an old project i had on kivy 2 years ago on a new pi (with a touch screen). But when I followed  the installation process and tried to launch an example, i've got this issue 
### Code and Logs

```python
// REPLACE ME: [INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_18-10-30_4.txt
[INFO   ] [Kivy        ] v1.11.0.dev0, git-678a055, 20181030
[INFO   ] [Python      ] v2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
Erreur de segmentation (segmentation fault)

**Comment by felixrindt** [comment]
Your issue already was reported in #6007 . There you can also find a possible workaround.

**Comment by felixrindt** [comment]
We just went back and used v1.10
