### ISSUE TITLE
Usage clarification of kivy.deps.sdl2 kivy.deps.glew?

### ISSUE THREAD

**Issue by E3V3A** [kivy/kivy#6039]
Can someone please clarify the use of the following two *"required"* library deps? 
1. `kivy.deps.sdl2` 
2. `kivy.deps.glew`

I.e. answer: 
* What do they do?
* Why are they needed?
* What is using them?

This may be related to why it seem so difficult to make a Windows native GUI as noted in #6038.

**Comment by E3V3A** [comment]
Also, hidden away as [code comments](https://github.com/kivy/kivy/blob/master/kivy/graphics/cgl.pyx), I found the following very important text:

---

CGL: standard C interface for OpenGL
====================================
Kivy uses OpenGL and therefore requires a backend that provides it.
The backend used is controlled through the ``USE_OPENGL_MOCK`` and ``USE_SDL2``
compile-time variables and through the ``KIVY_GL_BACKEND`` runtime
environmental variable.
Currently, OpenGL is used through direct linking (gl/glew), sdl2,
or by mocking it. Setting ``USE_OPENGL_MOCK`` disables gl/glew.
Similarly, setting ``USE_SDL2`` to ``0`` will disable sdl2. Mocking
is always available.
At runtime the following backends are available and can be set using
``KIVY_GL_BACKEND``:
* ``gl`` -- Available on unix (the default backend). Unavailable when
  ``USE_OPENGL_MOCK=0``. Requires gl be installed.
* ``glew`` -- Available on Windows (the default backend). Unavailable when
  ``USE_OPENGL_MOCK=0``. Requires glew be installed.
* ``sdl2`` -- Available on Windows/unix (the default when gl/glew is disabled).
  Unavailable when ``USE_SDL2=0``. Requires ``kivy.deps.sdl2`` be installed.
* ``angle_sdl2`` -- Available on Windows with Python 3.5+.
  Unavailable when ``USE_SDL2=0``. Requires ``kivy.deps.sdl2`` and
  ``kivy.deps.angle`` be installed.
* ``mock`` -- Always available. Doesn't actually do anything.
Additionally, the following environmental runtime variables control the graphics
system:
* ``KIVY_GL_DEBUG`` -- Logs al gl calls when ``1``.
* ``KIVY_GRAPHICS`` -- Forces OpenGL ES2 when it is ``gles``. OpenGL ES2 is always
  used on the android, ios, rpi, and mali OSs.

**Comment by matham** [comment]
The docs you copied in your last comment is found at https://kivy.org/doc/stable/guide/environment.html and https://kivy.org/doc/stable/api-kivy.graphics.cgl.html#module-kivy.graphics.cgl.

For any further questions pleas ask on the chat or mailing list.
