### ISSUE TITLE
ValueError: invalid interpolation syntax in 'kivy_%y-%m-%d_%_.txt'

### ISSUE THREAD

**Issue by apacha** [kivy/kivy#6041]
I looked into issue #4287 and I have some additional analytical information, so I'm opening another issue, since it is still not resolved. The problem seems to be faulty code that breaks depending on the used Python version, especially on Windows.

In short, there is invalid Python [code](https://github.com/kivy/kivy/blob/stable/kivy/config.py#L711) in Kivy, that causes troubles in Python 3 and prevents Kivy from properly initializing, thus [causing all sorts of weird errors](https://dev.azure.com/OMR-Research/MUSCIMarker/_build/results?buildId=16&view=logs):

 `Config.setdefault('kivy', 'log_name', 'kivy_%y-%m-%d_%_.txt')`

I assume that it should be a placeholder for year, month and day, but without actually putting any information in there. Previous Python versions seem to have just swallowed the thing, but when running with Python >= 3, the [configparser](https://docs.python.org/3/library/configparser.html) seems to have become more restrictive (correctly).

I currently see two ways of fixing this: 

- Downgrade your Python version to Python < 3 (stupid solution)
- Replace the faulty code in Kivy with something that actually works:

```python
import datetime

today = datetime.datetime.now()
Config.setdefault('kivy', 'log_name','kivy_{}-{}-{}.txt'.format(today.year, today.month, today.day))
```

The full error message looks like this:
```
MUSCIMarker\help.py:7: in <module>
    from kivy.graphics import Color, Rectangle
C:\Miniconda\envs\test-environment\lib\site-packages\kivy\__init__.py:327: in <module>
    from kivy.config import Config
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:955: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:656: in _load_unlocked
    ???
<frozen importlib._bootstrap>:626: in _load_backward_compatible
    ???
C:\Miniconda\envs\test-environment\lib\site-packages\_pytest\assertion\rewrite.py:291: in load_module
    six.exec_(co, mod.__dict__)
C:\Miniconda\envs\test-environment\lib\site-packages\kivy\config.py:711: in <module>
    Config.setdefault('kivy', 'log_name', 'kivy_%y-%m-%d_%_.txt')
C:\Miniconda\envs\test-environment\lib\site-packages\kivy\config.py:493: in setdefault
    self.set(section, option, value)
C:\Miniconda\envs\test-environment\lib\site-packages\kivy\config.py:462: in set
    ret = PythonConfigParser.set(self, section, option, e_value)
C:\Miniconda\envs\test-environment\lib\ConfigParser.py:1193: in set
    super().set(section, option, value)
C:\Miniconda\envs\test-environment\lib\ConfigParser.py:894: in set
    value)
C:\Miniconda\envs\test-environment\lib\ConfigParser.py:402: in before_set
    "position %d" % (value, tmp_value.find('%')))
E   ValueError: invalid interpolation syntax in 'kivy_%y-%m-%d_%_.txt' at position 5
```

Keep in mind, that changing the string, e.g. to `Config.setdefault('kivy', 'log_name', 'kivy_%%y-%%m-%%d_%%_.txt')` and running `import kivy` once, will do the upgrade and the problem will no longer be reproducible, unless you start with a fresh system.

**Comment by Julian-O** [comment]
Is this still an issue with Kivy 2.2.1? I have never seen it, and we don't support Python 2.7 any more.

**Comment by apacha** [comment]
I've given up on trying to fix the issue, since it was a side-project only. And if you no longer support Python 2, I guess the problem should be solved by now and I'm closing the issue thereby.
