### ISSUE TITLE
How to plot a graph in kivy without using matplotlib

### ISSUE THREAD

**Issue by sachu100** [kivy/kivy#6058]
I need to plot a real-time graph in kivy app. I am using kivy latest version, python 2.9.13, and raspbian stretch latest version. But couldn't import matplotlib because it doesn't support on python 2.9.13. Can anyone please tell me how to do it. I am looking into a example program found from the site but i didn't understand it much. Please help me. 

This is the link for the eg: program i'm looking
https://github.com/kivy-garden/garden.graph/blob/master/__init__.py

**Comment by tito** [comment]
Tip: https://github.com/kivy-garden/garden.graph
