### ISSUE TITLE
kivy.properties

### ISSUE THREAD

**Issue by MuhammadKarkhaneh** [kivy/kivy#6059]
### Versions

* Python: 3.7.0 & 3.7.1
* OS: Windows 7 32bit & Windows 8.1 64bit
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

I use "Visual Studio Code" to write my code, but when I run any code containing "from kivy.properties import NumericProperty", it shows an Error describing "No name 'NumericProperty' in module 'kivy.properties'" and the result is correct and it work properly.  I tested the code using original IDLE for python but there is no error was shown. by the way this error appears with any other Property from kivy.properties module (I tested the other codes) exp. 'ObjectProperty', 'ListProperty', 'StringPropertyetc', etc.
### Code and Logs

```python
from kivy.app import App

from kivy.core.window import Window

from kivy.config import Config

from kivy.uix.gridlayout import GridLayout
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput
from kivy.uix.label import Label
from kivy.uix.button import Button 
from kivy.uix.popup import Popup
from kivy.uix.scrollview import ScrollView

from kivy.properties import NumericProperty

class CalculatorWidget(GridLayout):
    int_button_width = 120
    int_button_height = 100
    int_button_font_size = 40

    button_width = NumericProperty(int_button_width)
    button_height = NumericProperty(int_button_height)
    button_font_size = NumericProperty(int_button_font_size)

    Window.size = (int_button_width * 2, 
        int_button_height * 3)

    def calc_error(self, error, calc_entry):
        content = BoxLayout(orientation='vertical')
        scrollview = ScrollView()

        close_popup = Button(text='Close this popup')
        error_message = Label(text=str(error))

        scrollview.add_widget(error_message)
        content.add_widget(scrollview)
        content.add_widget(close_popup)

        popup = Popup(title='An error occured',
            content=content, size_hint=(.8, .8))

        close_popup.bind(on_release=popup.dismiss)
        popup.open()

    def calculate(self, *args):
        calc_entry = self.ids.calc_input.text 
        if calc_entry != '':
            if calc_entry[0] in '1234567890-+':
                try:
                    ans = str(eval(calc_entry))
                    self.ids.calc_input.text = ans
                except Exception as error:
                    self.calc_error(error, calc_entry)
                    pass

    def delete(self, *args):
        self.ids.calc_input.text = self.ids.calc_input.text[:-1]

    def clear(self, *args):
        self.ids.calc_input.text = ''

    def switch(self, *args):
        calc_entry = self.ids.calc_input.text
        if calc_entry != '':
            if calc_entry[0] in '+1234567890':
                self.ids.calc_input.text = '-' + calc_entry
            if calc_entry[0] == '-':
                self.ids.calc_input.text = calc_entry[1:]

class CalculatorApp(App):
    def build(self):
        Config.set('graphics', 'resizable', '0')
        Config.write()
        return CalculatorWidget()

if __name__ == '__main__':
    CalculatorApp().run()

```

**Comment by zepef** [comment]
Hello I run into the same error with Python 3.6 and ListProperty. I cannot find any answers. I'll still try and keep everybody updated.

Best regards,

**Comment by tito** [comment]
I can ensure you that ListProperty and NumericProperty are in kivy.properties.
Your issue has nothing to do with us, but rather how Visual Code Studio is trying to see if this exists.

Make sure that VSCode using the same python as you, Kivy is compiled etc. In anycase, we won't be able to do anything directly with VSCode.

**Comment by ToinoOeiras** [comment]
# Help please.
I'm learning development whit Python and Kivy, Use sublime text but I want trye VsCode.
In Sublime I use SublimeREPL touch the keyword and everthing runs ok.
In VsCode I can´t run Kivy.
PS: Sorry for my bad english.

**Comment by zepef** [comment]
Hello,
Excuse me for the late answer, I am quite busy theses days. I use Kivy with VS Code and I am starting to do real good. Do not hesitate to get back in touch. Fiste use the latest VS Code version and install Kivy extensions. I use Conda and a virtual environment to run Kivy and it works well.

Best regards

**Comment by ToinoOeiras** [comment]
> 
> 
> Hello,
> Excuse me for the late answer, I am quite busy theses days. I use Kivy with VS Code and I am starting to do real good. Do not hesitate to get back in touch. Fisrt I use the latest VS Code version and install Kivy extensions. I use Conda and a virtual environment to run Kivy and it works well.
> 
> Best regards

Tanks

**Comment by Salam697** [comment]
"I use 'Visual Studio Code' to write my code, but when I run any code containing 'from kivy.properties import NumericProperty', it shows an Error describing 'No name "NumericProperty" in module "kivy.properties"' and the result is correct and it work properly."

I also got this error message after I installed Kivy and ran the Pong Demo example and I get this syntax error within VS Code for Windows. The Pong code compiles and runs, but I'm struggling to get anything else working (for different reasons).

The Kivy download was for Python 3.6 whereas Anaconda installed 3.7.0 for me, not sure what VS Code is defaulting to with its recommended Python extensions.

**Comment by sennewood** [comment]
Same error on Windows 10 (64-bit) with Python 3.7.3

**Comment by Gorky7** [comment]
To solve the problem, instead of using -- "from kivy.properties import NumericProperty"  try using 
-->  "import kivy.properties as any_name" -- then call it by saying for example --> "button_width = any_name.NumericProperty(int_button_width) "

**Comment by MarcusCasey** [comment]
> To solve the problem, instead of using -- "from kivy.properties import NumericProperty" try using
> --> "import kivy.properties as any_name" -- then call it by saying for example --> "button_width = any_name.NumericProperty(int_button_width) "

You rock. This solved my issue entirely in VScode

**Comment by asm201** [comment]
hello, i'm having the same problema, but i'm using pycharm, with windows 10 and kivy version 1.11.1.
it's shows me this error: Cannot find reference 'properties' in '__init__.py', Unresolved reference 'ListProperty'

**Comment by AnishDe12020** [comment]
I am not even able to import any of the kivy packages.
Here is a screenshot - 
![image](https://user-images.githubusercontent.com/63192115/86131507-5c890100-bb03-11ea-983d-ed549049a5b1.png)

**Comment by emma-luvC** [comment]
I need help
I'm using Pycharm

from kivy.properties import NumericProperty, ReferenceListProperty

it gave me the errors

- Cannot find references
- unresolved references

**Comment by istipisti113** [comment]
Same thing for me but some folders doesn't even existing for me. I tried reinstalling a million times but didn't work at all.
Someone help me please!!

**Comment by prajwalpant1** [comment]
haw to fix this ? 
ImportError: cannot import name 'ObjectProprerty' from 'kivy.properties'

**Comment by itwaisi** [comment]
I see this is closed, but I am having the same issue. 

Platform: Windows 11 Home 22H2
Python: 3.8.10
Kivy: 2.1.0

If I do either, I get an error:

- `import kivy.properties as kvprops` then call `var = kvprops.ObjectPropery(None)`
  - ERROR: AttributeError: module 'kivy.properties' has no attribute 'ObjectPropery'
- `from kivy.properties import ObjectPropery` then call `var = ObjectPropery(None)`
  - ERROR: ImportError: cannot import name 'ObjectPropery' from 'kivy.properties' from 'kivy.properties' (...\lib\site-packages\kivy\properties.cp38-win_amd64.pyd)
 
Has anyone solved this problem?

Thanks
