### ISSUE TITLE
Text Input: Cursor moves to the end when changing font_size

### ISSUE THREAD

**Issue by me2beats** [kivy/kivy#6063]
### Description

Text Input: Cursor moves to the text end every time when changing font_size

### How to reproduce

```python
from kivy.app import App
from kivy.lang import Builder

KV = """
TextInput
    on_touch_down: self.font_size+=1
"""
class MyApp(App):
    def build(self):
        self.root = Builder.load_string(KV)

MyApp().run()

```

**Comment by ElliotGarbus** [comment]
Summary:  I have confirmed this reported behavior.  This is an unusual use case of touching the TextInput to change the font_size of the touched TextInput.  I have demonstrated a work around below.  Given the unusual use case, and availability of a workaround, I recommend closing this issue with no further action.

Reproducer:
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.textinput import TextInput

KV = """
TouchTextInput:
"""


class TouchTextInput(TextInput):
    def on_touch_down(self, touch):
        if self.collide_point(*touch.pos):
            app = App.get_running_app()
            app.root.font_size += 1
        return super().on_touch_down(touch)


class MyApp(App):
    def build(self):
        self.root = Builder.load_string(KV)


MyApp().run()
```
This appears as an undefined side effect of changing the font_size by touching the TextInput.  In a use case where setting the font_size is not done by touching the TextInput, there is no visible effect.  While the cursor has changed, it is reset by touching TextInput.  Example:
```python
from kivy.app import App
from kivy.lang import Builder

kv = """
BoxLayout:
    orientation: 'vertical'
    TextInput:
        id: ti
    BoxLayout:
        size_hint_y: None
        height: dp(48)
        TextInput:
            id: fs
            size_hint_x: None
            width: dp(50)
            input_filter: 'int'
        Button:
            text: 'Set Font Size'
            on_release: if fs.text: ti.font_size = int(fs.text)
"""


class ChangeFSApp(App):
    def build(self):
        return Builder.load_string(kv)


ChangeFSApp().run()
```
Looking at the source code: https://github.com/kivy/kivy/blame/533a95fafaba167218dc614be0dfc240af7b54fd/kivy/uix/textinput.py#L2162
We can see that the method _refresh_line_options() is triggered on the change of font_size and sets the cursor pos to the end of the text.
This is an unusual use case.  This is overloading the touch of the TextInput to change to font_size.  It is possible to work around this behavior by saving and restoring the cursor position.  The example work around: 
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.textinput import TextInput
from kivy.clock import Clock

KV = """
TouchTextInput:
"""


class TouchTextInput(TextInput):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.saved_cursor = None  # used to restore cursor position

    def on_touch_down(self, touch):
        if self.collide_point(*touch.pos):
            self.saved_cursor = self.get_cursor_from_xy(*touch.pos)
            self.font_size += 1
            Clock.schedule_once(self.restore_cursor)
        return super().on_touch_down(touch)

    def restore_cursor(self, _):
        self.cursor = self.saved_cursor


class A6063WorkAroundApp(App):
    def build(self):
        self.root = Builder.load_string(KV)


A6063WorkAroundApp().run()
```
@Julian-O 
Given this is an unusual use case of changing the font_size by touching the TextInput, and the availability of a workaround.  I would recommend closing this issue, and not changing the TextInput.
