### ISSUE TITLE
on_text event fired on init

### ISSUE THREAD

**Issue by ronyeh3** [kivy/kivy#6064]
### Versions

* Python: 2.7.15
* OS: ubuntu
* Kivy: v1.11.0.dev0, git-372b819, 20181204
* Kivy installation method: pip

### Description
hi,
i was force to upgrade from 1.10.1 to dev0 version because relevant fixes.
i seems that on_text event fired on TextInput initiation with empty string value: ""
this is not the wanted behavior . also not like in 1.10.1

### Code and Logs

from kivy.app import App
from kivy.lang import Builder

```
kv = """
TextInput:
    on_text: print('text was set')
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

**Comment by ronyeh3** [comment]
anyone ?

**Comment by gottadiveintopython** [comment]
Strange. When I changed the code like this:

```python
kv = """
TextInput:
    text: 'AAA'
    on_text: print('text was set')
"""
```

`text was set` wasn't printed, but when I changed the code like this:

```python
kv = """
TextInput:
    text: ''
    on_text: print('text was set')
"""
```

it was printed.

- Python: 3.7.1
- Kivy: v1.11.0.dev0, git-c4d6894, 20190324
- OS: LinuxMint

**Comment by tshirtman** [comment]
When i test the code in the bug report on 1.10.1, i get the same result, text is set during init, and from what i can see, the involved code didn't change at all in a few years. Are we sure it's a regression?

**Comment by matham** [comment]
I tested it with 1.10.1 and compared it to master and for the above example both printed `text was set`.

I don't think this is really a bug, more like an inconvenience, but we don't guarantee about how properties are initialized so that's not something you should rely on.

**Comment by matham** [comment]
The specific issue is that `_split_smart` returns `[['']]`, while the initial value of `_lines` is `[[]]`. `text` is an `AliasProperty` that is bound to `_lines`. It is possible that in a much previous release (not after the last one though) the behavior has changed where `text` is dispatched event when it's not truly changed.

I think `AliasProperty` behavior has changed before the last release.
