### ISSUE TITLE
Render fonts with anti-aliasing by default

### ISSUE THREAD

**Issue by jleaders** [kivy/kivy#6065]
Users are accustomed to beautifully rendered fonts, ever since LCD screens became the norm and modern operating systems and browsers have implemented [Sub-Pixel rendering](https://en.wikipedia.org/wiki/Subpixel_rendering). Kivy's text feels notably different from native fonts for this reason (try disabling sub-pixel rendering to see the difference on the OS)

Currently [people are getting around the issue by using blur filters ](https://stackoverflow.com/questions/31588379/python-kivy-antialiasing-for-canvas) on Kivy Label's but that isn't true anti-aliasing, but rather relying on incidental rasterization artifacts in the final video-memory to screen transformation. 

However, pixel-accurate font rendering can be difficult with hardware accelerated textures. 
Recently, [HTMLGL](http://htmlgl.com/) project added high-DPI support, and there was some discussion about via Valve's [Signed Distance Field Text Rendering](https://www.youtube.com/watch?v=CGZRHJvJYIg) (SDFTR) which allows for per-pixel accurate font-rendering with complicated texture memory management. 

I believe at the very least, if we can't implement SDFTR, we could consider using the [built in Anti-Aliasing options](https://www.khronos.org/opengl/wiki/Multisampling) in the rasterizer (I presume Kivy uses OpenGL under the hood), and because that is the norm for fonts, it should be enabled by default for all fonts/texts/labels.

Thank you!

**Comment by tshirtman** [comment]
Text is actually rendered by the text providers, most of the time this is sdl2_ttf, but can also be PIL/Pillow, pygame, or more recently (and linux only) pango, investigating which ones can offer better options in this direction. Alternatively, another hacky way to improve results is to oversample by just rendering the text in a bigger font than necessary, and putting the texture on a rectangle that is of the desired size (or using a Scale instruction), it's not perfect either, but it's easy enough and give nice results (see below, but i don't know if it's my eyes or my screen, i don't find the first result particularly egregious)

![capture-2018-12-05t21-28-10](https://user-images.githubusercontent.com/22759/49542068-cc59ea00-f8d4-11e8-8d80-cc07ffc17dd8.png)
```from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string(
'''
BoxLayout:
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: .2, .2, .7
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 10

        Label:
            text: 'test'
            font_size: 15
            color: .8, .1, .1, 1
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .66, .66, 1
            canvas.after:
                PopMatrix
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 20
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .5, .5, 1
            canvas.after:
                PopMatrix
    BoxLayout:
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 20

        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 30
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .66, .66, 1
            canvas.after:
                PopMatrix
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 40
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .5, .5, 1
            canvas.after:
                PopMatrix
    BoxLayout:
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 30

        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 45
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .66, .66, 1
            canvas.after:
                PopMatrix
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 60
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .5, .5, 1
            canvas.after:
                PopMatrix
    BoxLayout:
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 50

        Label:
            text: 'test'
            font_size: 75
            color: .8, .1, .1, 1
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .66, .66, 1
            canvas.after:
                PopMatrix
        Label:
            text: 'test'
            font_size: 100
            color: .8, .1, .1, 1
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .5, .5, 1
            canvas.after:
                PopMatrix
    BoxLayout:
        Label:
            text: 'test'
            color: .8, .1, .1, 1
            font_size: 100

        Label:
            text: 'test'
            font_size: 150
            color: .8, .1, .1, 1
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .66, .66, 1
            canvas.after:
                PopMatrix
        Label:
            text: 'test'
            font_size: 200
            color: .8, .1, .1, 1
            canvas.before:
                PushMatrix
                Scale:
                    origin: self.center
                    xyz: .5, .5, 1
            canvas.after:
                PopMatrix

'''))
```

**Comment by jleaders** [comment]
Thanks for the example, the thing I'm seeing, and perhaps it's in my code, is a black halo around the text, and no anti-aliasing on icons.

Actual:
![actual](https://user-images.githubusercontent.com/2430917/49969772-3e868c00-fede-11e8-94a4-7753ffeecf2b.png)


Expected:
![expected](https://user-images.githubusercontent.com/2430917/49969777-42b2a980-fede-11e8-9d31-cda52a384e9f.png)


If you look carefully at the "O" in Organic Mail you can see a distinct black halo/outline, and that feels a bit off. Perhaps it's not an anti-aliasing thing, but something else. Are fonts rendered to black textures and then having an alpha map? I'm trying to speculate here.

**Comment by jleaders** [comment]
I see the issue, I didn't have the SDL text provider installed

```
sudo apt-get install -y \
    python-pip \
    build-essential \
    git \
    python \
    python-dev \
    ffmpeg \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libportmidi-dev \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    zlib1g-dev
```

This resulted in fixing it:
![organic](https://user-images.githubusercontent.com/2430917/49970835-6cb99b00-fee1-11e8-978a-8b577c1ee47d.png)


Sorry about the confusion

**Comment by Chimono** [comment]
How to install the SDL text Provider? I create a package for Windows and have the exact same issue. Everything works in PyCharm but the exe file produce this halo effect.
