### ISSUE TITLE
font color changes to white when disabled, but is (0,0,0,1)

### ISSUE THREAD

**Issue by ronyeh3** [kivy/kivy#6066]
### Versions

* Python:
* OS: ubuntu 
* Kivy:v1.11.0.dev0, git-372b819, 20181204
* Kivy installation method: pip

### Description

hi,
i was force to upgrade from 1.10.1 to dev0 version because relevant fixes.
now in this version, the font color of Label CHANGES to white color if i disable the label,
even though in the inspector module i can see the correct value  (0,0,0,.65)

****update ***********
i found where is the issue , you guys tried to correct a bug with "disabled" being an alias propery , one of those relevant commits is :
https://github.com/kivy/kivy/commit/9a2d005851ab9d58551aaca3ab82074493587377
if i remove this "return True" , its working correctly.
btw, using disabled_color directly solve the issue, so its not too bad Backward compatibility issue.

### Code and Logs

```python
class CuvetteButton(ToggleButtonBehavior, Label ):
...
kv : """
<CuvetteButton>
    canvas.before:
        Ellipse:
            pos: [self.center_x - sp(25), self.center_y - sp(25)]
            size: [dp(50), dp(50)]
            source: "assets/tray/btn_embryo.png" if self.disabled==False else "assets/tray/btn_embryo_disa.png"
    color:  (0,0,0,.9) if self.disabled == False else  (0,0,0,.65) > # this was working fine in 1.10.1 !
"""
```

**Comment by tshirtman** [comment]
sigh, seems like making disabled smarter wasn't as smart as i though it was. Thanks for reporting.

**Comment by ronyeh3** [comment]
no its ok im just being annoying, i should have use the disabled_color property from the first time. and not that condition inside the color property.
you guys doing beautiful job!  keep it up !

**Comment by tito** [comment]
@tshirtman what are you talking about exactly? Care to explain and/or provide a PR/reference the commit that introduce the issue? Thanks you :)

**Comment by tshirtman** [comment]
i didn't check, but certainly it's the change of disabled to an AliasProperty.

**Comment by tshirtman** [comment]
I think we could close this, the good solution was to use disabled_color, the other way probably worked before because it somehow overrode the default behavior, but i don't think one way is any less wrong than the other, and it's easy to fix in any codebase.
