### ISSUE TITLE
Unable to find any valuable Window provider

### ISSUE THREAD

**Issue by Raigiku** [kivy/kivy#6071]
### Versions

* Python: 3.7.0
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: I followed the exact steps found here https://kivy.org/doc/stable/installation/deps-cython.html 
(doing pip install -U --force-reinstall Cython==0.27.3) and here https://kivy.org/doc/stable/installation/installation-windows.html 
(doing:
python -m pip install --upgrade pip wheel setuptools
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
python -m pip install kivy.deps.gstreamer
python -m pip install kivy.deps.angle
python -m pip install kivy
)

### Description

Trying to install Kivy

### Code and Logs
```
[INFO   ] Logger: Record log in C:\Users\CASTILLO\.kivy\logs\kivy_18-12-10_124.txt
[INFO   ] Kivy: v1.10.1
[INFO   ] Python: v3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[CRITICAL] Window: Unable to find any valuable Window provider.
sdl2 - ImportError: DLL load failed: The specified procedure could not be found.
  File "C:\Users\CASTILLO\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\CASTILLO\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] App: Unable to get a Window, abort.
```

```python
import kivy
kivy.require('1.10.1')

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()
```

**Comment by VictorCabello** [comment]
I got the same issue on windows 10 but I was able to solve it.

# Versions
Python : 3.7.1
OS: Windows 10
Kivy: 1.10.1

# Fix

I found that the problem are the dependencies used by Kivy, so I use pip tools to get a good set of dependencies.

## Install pip-tools

pip-tools is a great tool to get your pacakges on place you could get more information [here](https://pypi.org/project/pip-tools/)

```
pip install pip-tools
```

## Generate requirements.in

From the kivy page I got the main libraries that I need and based on that I created my requirments.in

```powershell
(.venv) PS D:\projects\game> Get-Content -path .\requirements.in
kivy
cython
docutils
pygments
pypiwin32
kivy.deps.sdl2
kivy.deps.glew
kivy.deps.gstreamer
(.venv) PS D:\projects\game>
```

## Compile requirements.in

```powershell
(.venv) PS D:\projects\game> pip-compile.exe .\requirements.in
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file .\requirements.txt .\requirements.in
#
certifi==2018.11.29       # via requests
chardet==3.0.4            # via requests
cython==0.29.2
docutils==0.14
idna==2.7                 # via requests
kivy-garden==0.1.4        # via kivy
kivy.deps.glew==0.1.10
kivy.deps.gstreamer==0.1.13
kivy.deps.sdl2==0.1.18
kivy==1.10.1
pygments==2.3.0
pypiwin32==223
pywin32==224              # via pypiwin32
requests==2.20.1          # via kivy-garden
urllib3==1.24.1           # via requests
(.venv) PS D:\projects\game>
```

## Install depdencies

In this point you could use different commands but just to continue with pip-tools I use pip-sync:

```powershell
(.venv) PS D:\projects\game> pip-sync.exe .\requirements.txt
```

Please use the requirments.**txt** to install the dependencies.


I hope this help you a little bit.

**Comment by tito** [comment]
What is the problem with dependencies that you guys have in the first place?
@VictorCabello you didn't installed kivy.deps.angle while @Raigiku used it
Is that the issue here?

**Comment by Raigiku** [comment]
Sorry, I can not give you any more information since I deleted the project and replaced my computer.

**Comment by internationalhouseofdonald** [comment]
Installing `cython` was what fixed it for me.

**Comment by supergitnessy** [comment]
I had the same problem. I solved it by first uninstalling Kivy and its dependencies :

python -m pip uninstall kivy
python -m pip uninstall kivy.deps.sdl2
python -m pip uninstall kivy.deps.glew
python -m pip uninstall kivy.deps.gstreamer

Now reinstalling everything except gstreamer.

python -m pip install --upgrade pip wheel setuptools
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew --extra-index-url https://kivy.org/downloads/packages/simple/

the https://kivy.org/......etc is the end of the previous python -m pip install docutils....etc...
then install kivy again

python -m pip install kivy

It should work, it worked for me !!!

**Comment by joeybab3** [comment]
@supergitnessy thank you so much that worked for me!

**Comment by krenshala** [comment]
I'm getting the same error with kivy 1.11.1 on win10, with both angle and glew installed. I've tried uninstalling and reinstalling a number of different ways. I don't have (or need) gstreamer installed, but most of the posts I've seen either don't mention it or, as above, explicitly note leaving it out of the reinstall process.

I've just gone through the steps as listed by supergitnessy, then reran my app.
```Successfully installed kivy-1.11.1

C:\Users\krenshala\Desktop>python testing.py
[INFO   ] [Logger      ] Record log in C:\Users\krenshala\.kivy\logs\kivy_20-05-17_7.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\krenshala\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 11:52:54) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\krenshala\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - ImportError: DLL load failed: The specified module could not be found.
  File "C:\Users\krenshala\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\kivy\core\__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\krenshala\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\kivy\core\window\window_sdl2.py", line 27, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] [App         ] Unable to get a Window, abort.

C:\Users\krenshala\Desktop>
```
And the code I tried to run:
```from kivy.app import App
from kivy.uix.widget import Widget

class Testing(Widget):
    pass

class TestingApp(App):
    def build(self):
        return Testing()

if __name__ == "__main__":
    TestingApp().run()
```

**Comment by GstKat** [comment]
@krenshala I have the same problem and no idea how to fix it. I have tried everything suggested in this post without success. I just started studying Python in my free time and it's a real pain in the *** to install this Kivy.

**Comment by matham** [comment]
For support using kivy, please ask on discord rather than commenting on old issues. These comments posted here are all about unrelated issues.
