### ISSUE TITLE
'App doesn't support pause mode' when using on_pause method

### ISSUE THREAD

**Issue by fr3nzy** [kivy/kivy#6073]
### Versions

* Python: 3.60
* OS: Ubuntu 18.04
* Kivy:1.10.1

### Description

Apk created using `p4a`, command used:

```
p4a apk --private $HOME/Documents/Code/Kivy/kivytest --package=org.example.myaasdqpp --name "My appliasacation" --version 0.1 --bootstrap=sdl2 --requirements=kivy,python3crystax,pyjnius,android,sdl2 --ndk-dir $HOME/Documents/Code/crystax-ndk-10.3.2 --android-api 28 --arch=armeabi-v7a
```

Whenever the home button is pressed or the screen is switched off, report for the app crash appears and according to the logs, python for android ends:

```
12-10 20:47:23.996  6150  6150 I python  : [INFO   ] [WindowSDL   ] App doesn't support pause mode, stop.
12-10 20:47:23.997  6150  6150 I python  : INFO:kivy:[WindowSDL   ] App doesn't support pause mode, stop.
12-10 20:47:23.998  6150  6150 I python  : [INFO   ] [Base        ] Leaving application in progress...
12-10 20:47:23.998  6150  6150 I python  : INFO:kivy:[Base        ] Leaving application in progress...
12-10 20:47:24.201  6150  6171 I python  : Python for android ended.
```
The back button does not mention `App doesn't support pause mode, stop.`, but ends right away.

### Code and Logs

```python
import kivy
kivy.require('1.10.1')

from kivy.app import App
from kivy.uix.relativelayout import RelativeLayout

class Root(RelativeLayout):
	def __init__(self):
		super().__init__()


class WhatToday(App):
	def build(self):
		 return Root()
	def on_pause(self):
		pass

WhatToday().run()
```

This occurs whilst using the crystax ndk and `sdl2` as the bootstrap. I am unable to run the android ndk or `pygame` to test as a comparison because both bring about errors that have no mention on the internet. Since using the crystax ndk and `sdl2` are the only ways I can successfully create an apk.

**Comment by Ham-Merhead** [comment]
Arg, my pilot error, should be:
```
    def on_pause(self):
        return True
```
@fr3nzy   Close issue?

**Comment by fr3nzy** [comment]
@Ham-Merhead have you had any luck with python-for-android services? I presume since you are attempting to access `on_pause` it would be to start a background process? I'm having some difficulty finding adequate documentation personally

**Comment by Ham-Merhead** [comment]
I have been trying to show Android UI Immersive_mode working. Have not tried services. Been trying the java 'autoclass' and the 'android' package which all seem to work, though trying to figure out Android data structures is a challenge for me.

I feel your pain on the documentation. Small working examples are non existent, so we thrash around trying to figure out what works. There was a post here a few days ago saying the Google translate to Chinese was difficult to understand. I was so tempted to post 'its worse if you read them in the original English', but decided the joke wouldn't translate well. ;)

I notice "p4a apk -xxx" (after a short delay) give a different option help list (dynamic documentation?!) which includes "--service". No idea if this is useful. But something to explore if you have not been there yet.
