### ISSUE TITLE
Per installation instructions suggestion, git-as-root not supported

### ISSUE THREAD

**Issue by OutsourcedGuru** [kivy/kivy#6077]
### Versions

* Python: 2.7.13
* OS: Raspbian Lite Stretch
* Kivy: https://github.com/kivy/kivy.git@master as of 11/12/2018
* Kivy installation method: Globally, at least that was what was attempted
* git: version 2.11.0

### Description

Per the installation instructions on [this page](https://kivy.org/doc/stable/installation/installation-rpi.html) for the Raspbian operating system, I was thwarted at step 3: `Install Kivy globally on your system:` when attempting to run `sudo pip install git+https://github.com/kivy/kivy.git@master`:

```
Collecting git+https://github.com/kivy/kivy.git@master
  Cloning https://github.com/kivy/kivy.git (to master) to /tmp/pip-LGsHzg-build
Please do not run git as root, your regular user account is enough :)

If you need to run git with root rights for some other application than
what comes preinstalled on this image you can remove this sanity check:

    sudo rm /root/bin/git

You might have to restart your login session after doing that.
Command "git clone -q https://github.com/kivy/kivy.git /tmp/pip-LGsHzg-build" failed with error code 1 in None
```

I expected that the instructions would result in a globally-installed Kivy.

(I'm falling back to building Kivy in the user's folder but this isn't necessarily what I wanted to accomplish.) Perhaps the documentation can be updated to adjust for reality.

### Code and Logs

Indicated above.

**Comment by tito** [comment]
This is new. Look like you need to do what the message tells you:
- either delete the /root/bin/git
- either use /usr/bin/git instead of just git
