### ISSUE TITLE
Builder sync loop does not check for potential NoneType in while loop

### ISSUE THREAD

**Issue by AlexCDean** [kivy/kivy#6079]
### Versions

* Python: v3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
* OS: Windows 10 64bit
* Kivy: v1.10.1
* Kivy installation method: virtualenv & pip

### Description

I've noticed when running a constantly updating kivy app for long periods of time it would eventually crash with a "TypeError: Nonetype is not subscriptable".

I traced it to this section of code in kivy.lang.builder.py:

```python
    def sync(self):
        '''Execute all the waiting operations, such as the execution of all the
        expressions related to the canvas.

        .. versionadded:: 1.7.0
        '''
        global _delayed_start
        next_args = _delayed_start
        if next_args is None:
            return
       
        while next_args is not StopIteration:
            # is this try/except still needed? yes, in case widget died in this
            # frame after the call was scheduled
            try:
                call_fn(next_args[:-1], None, None)
            except ReferenceError:
                pass
            args = next_args
            next_args = args[-1]
            args[-1] = None
        _delayed_start = None
```
It seems somewhere in the list in _delayed_start a widget would turn into None. Not sure why this happens but it should check for next_args being None before attempting to call "call_fn". 

```python
        while next_args is not StopIteration and next_args is not None:
            # is this try/except still needed? yes, in case widget died in this
            # frame after the call was scheduled
            try:
                call_fn(next_args[:-1], None, None)
            except ReferenceError:
                pass
            args = next_args
            next_args = args[-1]
            args[-1] = None
        _delayed_start = None
```
If I misunderstood the point of the method then please let me know, I'd like to hear your insights. 

Log below when I caught the exception & printed out next_args with _delayed_start:

### Code and Logs

>I dun goofed
>Error: 'NoneType' object is not subscriptable
>Next args is..
>None
>Delayed start is..
>[
><weakproxy at 0x00000000074CA3B8 to kivy.graphics.vertex_instructions.Rectangle at 0x00000000074C2188>,
>'pos', 
><code object <module> at 0x0000000002BDDA50, file "C:\Users\APP\env\lib\site-packages\k
>ivy\data\style.kv", line 192>
>, 
> <ParserRuleProperty name='pos' filename=C:\Users\APP\env\lib\site-packages\kivy\data\style.kv:192 value='[int(x) for x in self.cursor_pos]' watched_keys=[['self', 'cursor_pos']]>, 
>{
> 'root': <WeakProxy to <kivy_lib.widgets.text_boxes.plain_text_box.PlainTextBox object at 0x000000000748B320>>,
> 'app': <__main__.MainApp object at 0x0000000005E2C458>, 'pt': <function pt at 0x0000000002B92158>, 
> 'inch': <function inch at 0x0000000002B921E0>, 
> 'cm': <function cm at 0x0000000002B92268>, 
> 'mm': <function mm at 0x0000000002B922F0>, 
> 'dp': <function dp at 0x0000000002B92378>, 
> 'sp': <function sp at 0x0000000002B92400>, 
> 'rgba': <function rgba at 0x0000000002989B70>, 
> 'metrics': <module 'kivy.metrics' from 'C:\\Users\\APP\\env\\lib\\site-packages\\kivy\\metrics.py'>, 
> 'abspath': <function abspath at 0x00000000020F3D90>, 
> 'sm': <module 'kivy.uix.screenmanager' from 'C:\\APP\\env\\lib\\site-packages\\kivy\\uix\\screenmanager.py'>,
> 'Window': <kivy.core.window.window_sdl2.WindowSDL object at 0x0000000003390528>, 
> 'self': <WeakProxy to <kivy_lib.widgets.text_boxes.plain_text_box.PlainTextBox object at 0x000000000748B320>>, 
> '__builtins__': {
>	'__name__': 'builtins',
>	'__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", 
>	'__package__': '', 
>	'__loader__': <class '_frozen_importlib.BuiltinImporter'>, 
>	'__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), 
>	'__build_class__': <built-in function __build_class__>, 
>	'__import__': <built-in function __import__>, 
>	'abs': <built-in function abs>, 
>	'all': <built-in function all>,
>	'any': <built-in function any>, 
>	'ascii': <built-in function ascii>, 
>	'bin': <built-in function bin>, 
>	'callable': <built-in function callable>, 
>	'chr': <built-in function chr>, 
>	'compile': <built-in function compile>, 
>	'delattr': <built-in function delattr>, 
>	'dir': <built-in function dir>, 
>	'divmod': <built-in function divmod>, 
>	'eval': <built-in function eval>, 
>	'exec': <built-in function exec>, 
>	'format': <built-in function format>, 
>	'getattr': <built-in function getattr>, 
>	'globals': <built-in function globals>, 
>	'hasattr': <built-in function hasattr>, 
>	'hash': <built-in function hash>, 
>	'hex': <built-in function hex>, 
>	'id': <built-in function id>, 
>	'input': <built-in function input>, 
>	'isinstance': <built-in function isinstance>, 
>	'issubclass': <built-in function issubclass>, 
>	'iter': <built-in function iter>, 
>	'len': <built-in function len>,
>	'locals': <built-in function locals>, 
>	'max': <built-in function max>, 
>	'min': <built-in function min>, 
>	'next': <built-in function next>, 
>	'oct': <built-in function oct>, 
>	'ord': <built-in function ord>, 
>	'pow': <built-in function pow>, 
>	'print': <built-in function print>, 
>	'repr': <built-in function repr>, 
>	'round': <built-in function round>, 
>	'setattr': <built-in function setattr>, 
>	'sorted': <built-in function sorted>, 
>	'sum': <built-in function sum>, 
>	'vars': <built-in function vars>, 
>	'None': None, 
>	'Ellipsis': Ellipsis, 
>	'NotImplemented': NotImplemented, 
>	'False': False, 
>	'True': True, 
>	'bool': <class 'bool'>, 
>	'memoryview': <class 'memoryview'>, 
>	'bytearray': <class 'bytearray'>,
>	'bytes': <class 'bytes'>,
>	'classmethod': <class 'classmethod'>,
>	'complex': <class 'complex'>,
>	 'dict': <class 'dict'>,
>	'enumerate': <class 'enumerate'>,
>	'filter': <class 'filter'>,
>	'float': <class 'float'>,
>	'frozenset': <class 'frozenset'>,
>	'property': <class 'property'>,
>	'int': <class 'int'>,
>	'list': <class 'list'>,
>	'map': <class 'map'>,
>	'object': <class 'object'>,
>	'range': <class 'range'>,
>	'reversed': <class 'reversed'>,
>	'set': <class 'set'>,
>	'slice': <class 'slice'>,
>	'staticmethod': <class 'staticmethod'>,
>	'str': <class 'str'>,
>	'super': <class 'super'>,
>	'tuple': <class 'tuple'>,
>	'type': <class 'type'>,
>	'zip': <class 'zip'>,
>	'__debug__': True,
>	'BaseException': <class 'BaseException'>,
>	'Exception': <class 'Exception'>,
>	'TypeError': <class 'TypeError'>,
>	'StopAsyncIteration': <class 'StopAsyncIteration'>,
>	'StopIteration': <class 'StopIteration'>, 
>	'GeneratorExit': <class 'GeneratorExit'>,
>	'SystemExit': <class 'SystemExit'>,
>	'KeyboardInterrupt': <class 'KeyboardInterrupt'>,
>	'ImportError': <class 'ImportError'>,
>	'ModuleNotFoundError': <class 'ModuleNotFoundError'>,
>	'OSError': <class 'OSError'>,
>	'EnvironmentError': <class 'OSError'>,
>	'IOError': <class 'OSError'>,
>	'WindowsError': <class 'OSError'>,
>	'EOFError': <class 'EOFError'>,
>	'RuntimeError': <class 'RuntimeError'>,
>	'RecursionError': <class 'RecursionError'>,
>	'NotImplementedError': <class 'NotImplementedError'>,
>	'NameError': <class 'NameError'>,
>	'UnboundLocalError': <class 'UnboundLocalError'>, 
>	'AttributeError': <class 'AttributeError'>, 
>	'SyntaxError': <class 'SyntaxError'>, 
>	'IndentationError': <class 'IndentationError'>, 
>	'TabError': <class 'TabError'>, 
>	'LookupError': <class 'LookupError'>, 
>	'IndexError': <class 'IndexError'>, 
>	'KeyError': <class 'KeyError'>, 
>	'ValueError': <class 'ValueError'>, 
>	'UnicodeError': <class 'UnicodeError'>, 
>	'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 
>	'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 
>	'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 
>	'AssertionError': <class 'AssertionError'>, 
>	'ArithmeticError': <class 'ArithmeticError'>,
>	'FloatingPointError': <class 'FloatingPointError'>,
>	'OverflowError': <class 'OverflowError'>,
>	'ZeroDivisionError': <class 'ZeroDivisionError'>,
>	'SystemError': <class 'SystemError'>,
>	'ReferenceError': <class 'ReferenceError'>,
>	'BufferError': <class 'BufferError'>,
>	'MemoryError': <class 'MemoryError'>,
>	'Warning': <class 'Warning'>,
>	'UserWarning': <class 'UserWarning'>,
>	'DeprecationWarning': <class 'DeprecationWarning'>,
>	'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>,
>	'SyntaxWarning': <class 'SyntaxWarning'>,
>	'RuntimeWarning': <class 'RuntimeWarning'>,
>	'FutureWarning': <class 'FutureWarning'>,
>	'ImportWarning': <class 'ImportWarning'>,
>	'UnicodeWarning': <class 'UnicodeWarning'>,
>	'BytesWarning': <class 'BytesWarning'>,
>	'ResourceWarning': <class 'ResourceWarning'>,
>	'ConnectionError': <class 'ConnectionError'>,
>	'BlockingIOError': <class 'BlockingIOError'>,
>	'BrokenPipeError': <class 'BrokenPipeError'>,
>	'ChildProcessError': <class 'ChildProcessError'>,
>	'ConnectionAbortedError': <class 'ConnectionAbortedError'>,
>	'ConnectionRefusedError': <class 'ConnectionRefusedError'>,
>	'ConnectionResetError': <class 'ConnectionResetError'>,
>	'FileExistsError': <class 'FileExistsError'>,
>	'FileNotFoundError': <class 'FileNotFoundError'>,
>	'IsADirectoryError': <class 'IsADirectoryError'>,
>	'NotADirectoryError': <class 'NotADirectoryError'>,
>	'InterruptedError': <class 'InterruptedError'>,
>	'PermissionError': <class 'PermissionError'>,
>	'ProcessLookupError': <class 'ProcessLookupError'>,
>	'TimeoutError': <class 'TimeoutError'>,
>	'open': <built-in function open>,
>	'quit': Use quit() or Ctrl-Z plus Return to exit, 'exit': Use exit() or Ctrl-Z plus Return to exit, 'copyright': Copyright (c) 2001-2017 Python Software 	 >   Foundation. All Rights Reserved. Copyright (c) 2000 BeOpen.com. All Rights Reserved. Copyright (c) 1995-2001 Corporation for National Research Initiatives.
>	All Rights Reserved. Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam. All Rights Reserved., 
>	'credits': Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands for supporting Python development.  See www.python.org for >		       more 			information., 
>	'license': See http://www.python.org/3.6/license.html, 
>	'help': Type help() for interactive help, or help(object) for help about object.
>	}
>  }, 
> None
>]

**Comment by tito** [comment]
I read the code again, changed by @matham long time ago, and i think it's just not Thread safe.
Would it be possible that in your case, you are using Threads and doing some widget stuff (directly or indirectly related), that may change this list and then breaks?

**Comment by AlexCDean** [comment]
Apologies just saw this. 

Yeah, looking back on it I was manipulating some widgets via a thread. That's all fixed now and I just have a queue between the thread & the kivy thread for communicating any widget updates. 

I haven't experienced any issues since then!
