### ISSUE TITLE
SDL bugs & Kivy version info request

### ISSUE THREAD

**Issue by Matteljay** [kivy/kivy#6080]
### Versions

* Python: 3.7.1 & 3.5.2
* OS: Arch Linux & Linux Mint 18.3
* Kivy: 1.10.1 on both systems
* Kivy installation method: pacman, apt-get
* SDL: 2.0.9 at Arch, 2.0.4 at Mint

### Description

Imho SDL is quite a work-in-progress, maybe even more so than Kivy itself.
Since Kivy relies so heavily on SDL, i'd like to know if there is a way for devs to get a cross-platform method for getting the SDL_version.
Please test the code below for some SDL issues and my current slow & ugly way to get the SDL version on both Linux' to fix all those issues.

### Code and Logs

```python

#!/usr/bin/env python3
from kivy.app import App
from kivy.uix.button import Button
from kivy.config import Config
Config.set('graphics', 'window_state', 'hidden') # start hidden, fix Window.hide() statup artifacts on all SDL versions. Needs to be placed BEFORE kivy.core.window
from kivy.core.window import Window
from kivy.clock import Clock
# System
from distutils.version import StrictVersion
import os, re

class YourApp(App):
    def mytimer(self, dt):
        # imagine more interesting code here :-)
        SDL_fixed_window_show()
        Window.raise_window()
    def on_start(self):
        Clock.schedule_interval(self.mytimer, 5)
        print('Wait 5 seconds... (use another window in the mean time)')
    def build(self):
        btn = Button(text='Hide me')
        btn.bind(on_release=lambda f: Window.hide())
        return btn

def SDL_fixed_window_show():
    Window.show()
    if SDL_needfix:
        # doing this on >= 2.0.9 causes problems (lose Window focus)
        # not doing this on lesser versions ignores Window.show() altogether
        Window.maximize()
        Window.restore()

def linux_SDL_getversion():
    SDLpatt = 'libSDL\d*-(\d*).(\d*).so.0.(\d*).0'
    for root, dirnames, filenames in os.walk('/usr/lib'):
        for filename in filenames:
            matchobj = re.match(SDLpatt, filename)
            if matchobj:
                return '.'.join(matchobj.groups())
    return 0

if __name__ == '__main__':
    # SDL version/fix
    linux_SDLver = linux_SDL_getversion()
    if(linux_SDLver):
        print(':: found Linux SDL version:', linux_SDLver)
        SDL_needfix = StrictVersion(linux_SDLver) < StrictVersion('2.0.9')
    else:
        SDL_needfix = False
    #Window.hide() # defective in SDL, creates ugly artifacts when used in startup
    YourApp().run()



```

**Comment by tito** [comment]
If you want to report an issue, then please report it :)
What bug are you trying to solve exactly?
Your issue is not clear at all. The only indication if it's that is about ">= 2.0.9 causes problems (lose Window focus)"

Please rework your issue to explain what issue you have exactly.

**Comment by Matteljay** [comment]
Hmm i can see how i'm not being clear. Attempt II: (yes i'm willing to go for III and IV ;))
The example above condenses the focussing problem but its hard to imagine a real world use-case.

To see the problem in a more practical sense: check out my [clipcommander](https://github.com/Matteljay/clipcommander) project. In the settings menu, set 'Window startup mode' to 'hidden' & close the app, it should then be daemonized. Every time you select a _different_ Yt-link, the window should instantly re-appear.

Now, try again & rip out the sdl_needfix code while chosing your Window.show() implementation. 
IF you chose:
```
Window.show()
Window.maximize()
Window.restore()
```
THEN clipcommander with SDL 2.0.4 based Kivy (linux mint 18.3) will work fine
(meaning: pop up the main window when selecting a Yt-link in your browser)
but 2.0.9 (arch linux) will _not_ cause the clipcommander window to popup when a selection is made.

IF you chose:
```
Window.show()
```
THEN clipcommander with SDL 2.0.9 based Kivy (arch linux) will work fine
(meaning: pop up the main window when selecting a Yt-link in your browser)
but 2.0.4 (linux mint 18.3) will _not_ cause the clipcommander window to popup when a selection is made.

Posted here as well: [SDL Forum](https://discourse.libsdl.org/t/window-hide-startup-artifacts-tray-icon-repository-ppa/25470)
Maybe this observation should be consider a feature request? I'd really just like the ability for devs to see which SDL version Kivy is using. My current way is terribly slow & hacky.

**Comment by tito** [comment]
If we want to check the SDL Version, then we need to use the SDL functions with wrapper into sdl.pxi, and somehow log it when initializing. If you do a PR i would merge it.

I'll close this issue because it's very specific to your case. But just to let you know, you don't have to find and check the so, you can dynamically load the symbol when the window is available (=SDL will be loaded by dynamic linking), and access to the version via ctypes.
