### ISSUE TITLE
no video provider after packaging kivy app with ffpyplayer provider

### ISSUE THREAD

**Issue by solmn** [kivy/kivy#6085]
### Versions

* Python:3.6
* OS: Windows 10
* Kivy: 1.1.0
* Kivy installation method:

### Description

I am trying to package kivy video app for windows, I used ffpyplayer for video provider. The app works fine at development but when i packaged the app for windows, I can't play the video because, the video provider is null ``` [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)```

### Code and Logs

```python
import os
os.environ["KIVY_VIDEO"] = "ffpyplayer"

```

**Comment by tshirtman** [comment]
did you put ffpyplayer into the hidden_imports of the pyinstaller spec file?
