### ISSUE TITLE
Outdated Android NDK download URL in Kivy Virtual Machine

### ISSUE THREAD

**Issue by stroobandt** [kivy/kivy#6087]
Using the latest Version 2.0, released the 13 May 2017, of the Kivy virtual Machine
and after having updated `buildozer` to version `0.37` as required by the instructions,
the `buildozer` build process fails when trying to unzip `android-ndk-r9c-linux-x86_64.tar.bz2`

This happens because on old URL to the Android NDK is being referenced, namely:
<http://dl.google.com/android/repository/android-ndk-r9c-linux-x86_64.tar.bz2>

The issue can be circumvented by manually downloading the Android NDK using `wget` to the `~/.buildozer/android/platform/` directory but this time from the correct URL, namely:
<http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2>

This issue was [previously reported by other people on StackExchange](https://stackoverflow.com/a/42191418/2192488) and in #5013.

Perhaps time to offer a new virtual machine for download?

**Comment by tito** [comment]
Issue moved to [kivy/buildozer #827](https://github.com/kivy/buildozer/issues/827) via [**ZenHub**](https://www.zenhub.com/)
