### ISSUE TITLE
Kivy doesn't paste full data from third party apps clipboard 

### ISSUE THREAD

**Issue by NovaHB** [kivy/kivy#6091]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

 I made this note app for writing txt files only but when I paste data on the textinput field from the internal clipboard there is no problem full data is pasted but on some third party clipboards like the TOUCHPAL keyboard clipboard the full data isn't pasted.. 

### Code and Logs

```python
// .

```

**Comment by KeyWeeUsr** [comment]
We use the real clipboard. Perhaps that touchpal thing is using own buffer for copy&paste or something.

Please include some reproducible example.
