### ISSUE TITLE
ValueError: invalid literal for int() with base 10: "['1']"

### ISSUE THREAD

**Issue by KostasDaskalos** [kivy/kivy#6093]
### Versions

* Python: 3.6.8 32bit
* OS: Windows 10 ( Version 1809 )
* Kivy: 1.10.1
* Kivy installation method: Using pip in administrative command prompt

### Description

Trying to run the example showcase in kivy-examples folder from command prompt ( administrator rights ) fails with error: ValueError: invalid literal for int() with base 10: "['1']"
![kivy_error](https://user-images.githubusercontent.com/7622007/50743367-af8c3b80-121f-11e9-9639-e82ab14d27cc.png)
. See the attached image.

**Comment by tshirtman** [comment]
you shouldn't need administrator, rights, it seems your config.ini file for kivy is broken, can you remove it (should be a .kivy directory in your user directory, with a config.ini file, rename it to a different name and restart kivy).

**Comment by tito** [comment]
Exactly. You put in the config.ini have a wrong log_level value
