### ISSUE TITLE
Unable to release APK

### ISSUE THREAD

**Issue by brajaparida** [kivy/kivy#6096]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

 Upload failed

You uploaded a debuggable APK or Android App Bundle. For security reasons you need to disable debugging before it can be published in Google Play. Find out more about debuggable APKs or Android App Bundles.

You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode. Find out more about signing.

Your app currently targets API level 19 and must target at least API level 26 to ensure that it is built on the latest APIs optimised for security and performance. Change your app's target API level to at least 26. Find out how.

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by tshirtman** [comment]
please read the documentation.
https://kivy.org/doc/stable/guide/packaging-android.html#release-on-the-market
