### ISSUE TITLE
Why is the CodeInput widget text blurry?

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#6105]
### Versions

* Python: 3.6
* OS: MacBook Air
* Kivy: 1.10.1

### Description

Why is the CodeInput widget text blurry? I have already met such questions, but did not find the answers. Who solved this problem?

![2019-01-19 21 54 43](https://user-images.githubusercontent.com/16930280/51431128-a050b900-1c35-11e9-8121-6b07f9322053.png)

**Comment by tshirtman** [comment]
it's probably related to #2297 (scrollview blurs content), although textinput is not a scrollview in itself, it has similar behavior, and certainly doesn't pixel-align content.

**Comment by Julian-O** [comment]
Closing as duplicate
