### ISSUE TITLE
Kivy does not watch keys only appearing in f-strings

### ISSUE THREAD

**Issue by brady-ds** [kivy/kivy#6108]
### Versions

* Python: 3.6.5
* OS: OpenSUSE 15.0
* Kivy: 1.10.1
* Kivy installation method: `pip3`

### Description

Kivy does not watch keys that only appear in `f`-strings because `ParserRuleProperty.precompile` is written to ignore strings, as seen [here](https://github.com/kivy/kivy/blob/master/kivy/lang/parser.py#L168) and [here](https://github.com/kivy/kivy/blob/master/kivy/lang/parser.py#L191).  For example, in the attached code both buttons should behave identically, disabling themselves and showing "True" when clicked.  But the second button never updates its text because it isn't watching `self.diabled`.

### Code and Logs

`main.py`:
```python
from kivy.app import App


class TestApp(App):
    pass


if __name__ == '__main__':
    TestApp().run()
```

`test.kv`:
```kv
BoxLayout:
    Button:
        text: str(self.disabled)
        on_press: self.disabled = True
    Button:
        text: f'{self.disabled}'
        on_press: self.disabled = True
```

**Comment by adamwolf** [comment]
Is there a workaround that still uses f-strings?
