### ISSUE TITLE
Video playback without audio on Raspberry Pi 3 B+ running Raspbian Stretch Lite

### ISSUE THREAD

**Issue by helium-three** [kivy/kivy#6109]
### Versions

* Python: 3.5.3
* OS: Raspbian Stretch Lite
* Kivy: 1.11.0dev0

* Kivy installation method: pip as described https://kivy.org/doc/stable/installation/installation-rpi.html

### Description

Making an application using the stock Video widget. Videos in .mp4 containers load and playback normally however without audio. Am using SDA and SCL to communicate with a sensor which I don't believe is a problem with remapping PWM0 and PWM1 to 18 and 19. Have tried the following already:

- Forced audio to headphone jack using raspi-config
- Set dtoverlay to use the PWM gpio i'm using (18 and 19 using pwm-2chan)
- Confirmed audio plays back through amplifier as intended from wav file using aplay from command line
- Confirmed video with audio plays back through amplifier as intended by using omxplayer on the same file
- Notice kivy throws a texture issue for the mp4 (see below) even though videos play
- Plugged in headphones to check and see if audio was being routed through audio jack which it wasn't. Removed headphones.
- Set KIVY_AUDIO to sdl2 and gstplayer manually, no change in behavior.
- Used handbrake to transcode the already working video files into aac and then mp3 audio
- Tried videoplayer app with default file as well as my test mp4, neither had sound.

[kivy_19-01-21_1.txt](https://github.com/kivy/kivy/files/2780327/kivy_19-01-21_1.txt)

### Code and Logs

```import kivy
kivy.require('1.2.0')

from sys import argv
from os.path import dirname, join
from kivy.app import App
from kivy.uix.videoplayer import VideoPlayer

# check what formats are supported for your targeted devices
# for example try h264 video and acc audo for android using an mp4
# container


class VideoPlayerApp(App):

    def build(self):
        if len(argv) > 1:
            filename = argv[1]
        else:
            curdir = dirname(__file__)
            filename = 'test.mp4'
        return VideoPlayer(source=filename, state='play')


if __name__ == '__main__':
    VideoPlayerApp().run()
```

Log:
```
[INFO   ] Logger: Record log in /home/pi/.kivy/logs/kivy_19-01-21_1.txt
[INFO   ] Kivy: v1.11.0.dev0, git-c0eaa4a, 20190121
[INFO   ] Python: v3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] VideoGstplayer: Using Gstreamer 1.10.4.0
[INFO   ] Video: Provider: gstplayer
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: egl_rpi
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] GL: OpenGL vendor <b'Broadcom'>
[INFO   ] GL: OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] GL: OpenGL parsed version: 2, 0
[INFO   ] GL: Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] GL: Texture max size <2048>
[INFO   ] GL: Texture max units <8>
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[ERROR  ] Image: Error loading texture /home/pi/bimbo/primary/test.mp4
[INFO   ] ProbeSysfs: device match: /dev/input/event1
[INFO   ] MTD: Read event from </dev/input/event1>
[INFO   ] ProbeSysfs: device match: /dev/input/event0
[INFO   ] MTD: Read event from </dev/input/event0>
[INFO   ] ProbeSysfs: device match: /dev/input/event1
[INFO   ] HIDInput: Read event from </dev/input/event1>
[INFO   ] ProbeSysfs: device match: /dev/input/event0
[INFO   ] HIDInput: Read event from </dev/input/event0>
[INFO   ] Base: Start application main loop
[INFO   ] MTD: </dev/input/event1> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event0> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event1> range position Y is 0 - 0
[INFO   ] HIDMotionEvent: using <Logitech K400
```

**Comment by helium-three** [comment]
Additionally, `/kivy-examples/audio/main.py` has the same behavior: app loads fine, no audio plays, but I can play each file individually with aplay.

**Comment by helium-three** [comment]
Okay, so adding `os.environ['KIVY_AUDIO'] = 'sdl2'` _does_ enable audio when added to `/kivy-examples/audio/main.py` _even though_ it does _not_ work when added to `videoplayer.py` or my application.

**Comment by tito** [comment]
Hi. Seems like a gstreamer issue on your side, not Kivy related. Kivy Video is not related to KIVY_AUDIO, KIVY_AUDIO is only used for pure audio, while Video uses others providers. You're using gstreamer: `[INFO   ] VideoGstplayer: Using Gstreamer 1.10.4.0`.

Make sure you get `gst-play` working on your platform, and it will be ok!
