### ISSUE TITLE
several bugs with text input

### ISSUE THREAD

**Issue by ronyeh3** [kivy/kivy#6125]
### Versions

* Python: 2.7.15
* OS: ubuntu
* Kivy: v1.11.0.dev0, git-372b819, 20181204
* Kivy installation method: pip

### Description
hi,

1.
seems that on_text event fired on TextInput initiation with empty string value: "" , when to pre text is set
this is not the wanted behavior . also not like in 1.10.1
2.
also, on text fired twice when pressing the 'enter' button
3.
also, when using "   row_force_default:True   " ()
the curser is overlying when press 'enter' until a other char is pressed

### Code and Logs

```python
kv = """
BoxLayout:
    pos_hint: { 'top' : 1}
    size_hint: (.5,.5)
    GridLayout:
        cols:1
        rows:5
        # row_default_height:150    ->
        # row_force_default:True    ->
        size_hint: (.5,.5)
        orientation: "vertical"
        BoxLayout:
            orientation: 'vertical'  
            Label:
                text:"Language"
                padding:0,0
                font_size:17
            TextInput:   
                text: '' 
                on_text: print "this shouldnt be print on initiation !"
            Widget:
            Widget:

"""

class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()

```

**Comment by tito** [comment]
Hi! I know it can be difficult to report issues, but here your reported 3 potentials issues in one post, with description that is hard to understand.

I'll try to address it:

1. I don't understand. Make it clear, or provide a reproducible event 
2. Nothing wrong about it. If you want a single event, use on_text_validate
3. row_force_default=True? If you have behavior issue with your GridLayout and your TextInput, maybe one size is missing somehow. If you create a specific issue with a reproducible example, we can help.

**Comment by ronyeh3** [comment]
hi, tnx for replay
i know it can be difficult to review all issues, but trust me we both want the framework will be precise.
especially if you want experienced developers to use it.
i an using it more then a year and it clear to me that you didn't run my example code.
this is quit suppressing since its your baby.

my example demonstrates all the 3 issues 

1. please run the code and you will see that on_text get fired on initiation. this is not the wanted behavior
2. are you serious ?  on_text_validate get fired only with "multiline : false" .
  ALL on_text events get fired once and on every char except pressing the newline(enter button) "/n" 
   probably you addressing the "/" and the "n" as  separated chars on this event
3. comment/uncomment the relevant lines in my code
        # row_default_height:150    ->
        # row_force_default:True    ->
and YOU WILL SEE the issue when pressing enter

please consider reopen the issue.
