### ISSUE TITLE
PyInstaller package does not include GStreamer (solved)

### ISSUE THREAD

**Issue by brsaylor** [kivy/kivy#6126]
### Versions

* Python: 2.7.15
* OS: macOS 10.14.1 Mojave
* Kivy: 1.10.1
* Kivy installation method: `pip install kivy --no-binary kivy` in virtualenv
* GStreamer 1.14.4 (homebrew; gst-plugins-* also installed)

### Description

When packaging an app that uses `kivy.core.audio.SoundLoader`, PyInstaller does not include the GStreamer plugins or libraries they require in the package. As a result, trying to play a sound results in `GstPlayerException: Unable to create a playbin`. (The unpackaged app works fine).

I think there is code missing from the kivy PyInstaller hook that would find and include the plugin files. The runtime hook includes a directory 'gst-plugins' in the GST_PLUGIN_PATH, but that path isn't mentioned anywhere else.

I solved the issue by adding the following code to my spec file:

```py
def find_gst_plugin_path():
    p = subprocess.Popen(
        ['gst-inspect-1.0', 'coreelements'],
        stdout=subprocess.PIPE)
    (stdoutdata, stderrdata) = p.communicate()

    match = re.search(r'\s+(\S+libgstcoreelements\.\S+)', stdoutdata)

    if not match:
        raise Exception('could not find GStreamer plugins')

    return os.path.dirname(match.group(1))


def find_gst_binaries():
    plugin_path = find_gst_plugin_path()

    plugin_filepaths = glob.glob(os.path.join(plugin_path, 'libgst*'))

   # PyInstaller does not automatically include the libraries the plugins link to
    lib_filepaths = set()
    for plugin_filepath in plugin_filepaths:
        plugin_deps = bindepend.selectImports(plugin_filepath)
        lib_filepaths.update([path for _, path in plugin_deps])

    plugin_binaries = [(f, 'gst-plugins') for f in plugin_filepaths]
    lib_binaries = [(f, '.') for f in lib_filepaths]

    return plugin_binaries + lib_binaries

# SNIP
a = Analysis(['../testapp/main.py'],
             pathex=['.'],
             binaries=find_gst_binaries(),
# SNIP
```

### Code and Logs

Here's my test app:
https://github.com/brsaylor/soundloader-test

(It requires a command line argument with the sound file to play).

Deleting the `find_gst_binaries()` code demonstrates the issue.

**Comment by tito** [comment]
The real question is, do we want to do that?
Aka GStreamer is not mandatory, you may uses ffpyplayer too, so adding by default gst libraries will not work either. And we cannot analyze your app to know what you wanted to use.

Maybe it would be better to document and provide snippet for users?

**Comment by brsaylor** [comment]
Good point - it wouldn't make sense to always include GStreamer whenever SoundLoader is imported. However, it looks like there's way to specify what providers you want to include in the package with `get_deps_minimal`:

https://github.com/kivy/kivy/blob/master/kivy/tools/packaging/pyinstaller_hooks/__init__.py#L153

Wouldn't it make sense to pull in the GStreamer files when 'gstplayer' is passed to `get_deps_minimal`?

**Comment by tito** [comment]
Yep you're right. Maybe that could be your first contribution?

**Comment by brsaylor** [comment]
Happy to do so; here's a PR with a couple of questions: #6165
