### ISSUE TITLE
Parse Error: There is a problem parsing the package

### ISSUE THREAD

**Issue by ArchyPeshenka** [kivy/kivy#6135]
* Python: 3.x (I have installed 3.5 on Linux, but Buildozer downloading 3.7 every time)
* OS: Linux (Using OVM)
* Kivy: 1.10.1

### Description
I have created .apk file using Buildozer, but when I try to install it on Android device I have a Parse Error: There is a problem parsing the package.

**Comment by tito** [comment]
Either you paste full log, but we don't even know what you're talking about exactly.

Use a support channel, and:
1. send the full build log of your app
2. send the running log of your app in your phone
