### ISSUE TITLE
Raspberry Pi 3B+: No available video device

### ISSUE THREAD

**Issue by openedhardware** [kivy/kivy#6137]
### Versions

* Python: 3.5.3
* OS: Raspbian Stretch Lite
* Kivy: 1.11.0.dev0
* Kivy installation method:  sudo pip3 install git+https://github.com/kivy/kivy.git@master

### Description
Just installed Kivy on the latest Raspbian Stretch Lite using this command:
```
sudo pip3 install Cython
sudo pip3 install git+https://github.com/kivy/kivy.git@master
```

And got this error:
![pasted file at february 7 2019 12_50 pm](https://user-images.githubusercontent.com/16890683/52411749-89143580-2b28-11e9-951c-d900747e79e4.png)

Kivy info:
![pasted file at february 7 2019 12_57 pm](https://user-images.githubusercontent.com/16890683/52411767-96312480-2b28-11e9-8851-981b94f0215e.png)

**NOTE:** I have been installing Kivy on several RPi's for over 3 months. It has been working well, but suddenly stopped working **today**.

Any idea?

P.S. I had to set `KIVY_GL_BACKEND` environment variable to `gl` to get it working before.

**Comment by tito** [comment]
Can you tell me which SDL2 and SDL2_image version is installed ?

**Comment by openedhardware** [comment]
@tito 
How can I get the installed versions?

**Comment by openedhardware** [comment]
@tito 
Any update on this issue?

**Comment by fedus** [comment]
I have only been able to get Kivy running on the RPI3 with a running X server if the backend is SDL - don't know if that helps you, but I suppose you didn't have an X server running.
FYI, performance on the RPI has been massively better with the native window provider egl_rpi in all my use cases (and without needing the X server).

**Comment by audryste** [comment]
I was able easily to build it with sdl framebuffer support.
this is my rpi build of kivy  1.10.1

You can download my build from here https://drive.google.com/open?id=1XunvTwQUc9GWnauQ4u5ej6x7EOpyLb_m

I will remove it after some time thou....
Just put it into main.py folder.
Let me now if it works for you :)

**Comment by mandoode** [comment]
Hi, if you feel my environment can assist in anyway at digging into this issue, I have the following conditions I believe are related.  I can run my app with python2.7 just fine, but not with python3.5, I get the ... `Unknown <png> type` ... error with the newer python 

Environment:

```
Board: 	RaspberryPi 3 B+:
			model name	: ARMv7 Processor rev 4 (v7l)
			BogoMIPS	: 38.40
			Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
			CPU implementer	: 0x41
			CPU architecture: 7
			CPU variant	: 0x0
			CPU part	: 0xd03
			CPU revision	: 4

Hardware	: BCM2835
Revision	: a020d3


OS: 		Raspbian Stretch:
			Kernel:	Linux <hostname> 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
			Dist:		PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
					NAME="Raspbian GNU/Linux"
					VERSION_ID="9"
					VERSION="9 (stretch)"
					ID=raspbian
					ID_LIKE=debian

Env:		KIVY_BCM_DISPMANX_ID=2
		KIVY_GL_BACKEND=gl

```

Using python2, my app runs fine, GL / Window initialization works fine:

Python and Kivy Env:
```

python2 -V outputs:   Python 2.7.13 

kivy Logger.info(kivy.__version__) outputs:  
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_19-06-06_23.txt
[INFO   ] [Kivy        ] v1.11.0.dev0, git-678a055, 20181030
[INFO   ] [Python      ] v2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516]
[INFO   ] 1.11.0.dev0

pi@<hostname>:~/mgbconsole$ python2 -d SegmentFoo.py 
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_19-06-06_22.txt
[INFO   ] [Kivy        ] v1.11.0.dev0, git-678a055, 20181030
[INFO   ] [Python      ] v2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked

```

But difficulty occurs with python3.5:

```
python -V outputs:  Python 3.5.3

kivy Logger.info(kivy.__version__) outputs: 
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_19-06-06_24.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.5/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python"
[INFO   ] 1.11.0


pi@<hostname>:~/<hostname>$ python SegmentFoo.py 
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_19-06-06_26.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.5/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
egl_rpi - Exception: Unknown <png> type, no loader found.

```


Hope this info helps.  If you need me to try something let me know.

**Comment by matham** [comment]
I was having similar issues. The problem seems to be that for some reason `sdl2_image` is unable to load these images - I think the `sdl2_image` version is too old.

The solution is to install pillow. I'll add that to the docs.

**Comment by mandoode** [comment]
@matham, thanks for responding.  I checked my pip3 list, and I see Pillow (6.0.0) is already installed, but I will pull the latest and rebuild.  

I did get kivy to get a window by changing the raspberry pi GL driver using raspi-config (I had to choose the legacy "G3" non-gl desktop driver so graphics are really slow).

My env settings where kivy can get a window with my current git clone are :

![Screen Shot 2019-06-19 at 2 30 09 PM](https://user-images.githubusercontent.com/2847253/59791785-d8b9f900-92a0-11e9-8a14-85191f9399a9.png)

shell env:
`
KIVY_GL_BACKEND=gl and KIVY_WINDOW=egl_rpi
`

As soon as I change back to the main driver, kivy can't get a window:

![Screen Shot 2019-06-19 at 2 25 03 PM](https://user-images.githubusercontent.com/2847253/59792291-d1471f80-92a1-11e9-895e-79a5fd32e3ac.png)

When trying KIVY_WINDOW=sdl2, I also get the Unable to get a Window.

**Comment by mandoode** [comment]
@matham, after latest rebuild, still the same issue.  I did have this library warning very early in make, but the build did not error:

build:
`
[INFO   ] [Kivy        ] v2.0.0.dev0, git-a781fdb, 20190619
`

make warning:
```
WARNING: A problem occurred while running pkg-config --libs --cflags pangoft2 (code 1)

Package pangoft2 was not found in the pkg-config search path.  Perhaps you should add the directory containing pangoft2.pc to the PKG_CONFIG_PATH environment variable
No package pangoft2 found
```
