### ISSUE TITLE
resizing the window halves image sizes on retina displays

### ISSUE THREAD

**Issue by toejough** [kivy/kivy#6144]
### Versions

* Python: 3.7.2
* OS: macOS 10.14.3
* Kivy: 1.11.0.dev0 (and before that, 1.10.1)
* Kivy installation method: git clone (and before that, pip install)

### Description

*What are you trying to get done?*
I'm trying to display an image correctly when resizing the window on a retina display.

*what has happened?*
The image is halved in height and width when resizing the window.

*what went wrong, and what did you expect?*
The image being half-sized (well, really, quarter-sized, by area), is wrong.  I expect it to scale correctly for the display.

*other*
The image scales just fine on a non-retina display.  With the code sample below, it scales fine when the window is *moved* on a retina display.  

Without the image reload code, the image remains 1/4 size when moving or resizing the window.

With the image reload code, the image remains 1/4 size when resizing the window, but scales up as I expect/want when moving the window.

I'm confused what's going on - the reload from disk every 0.1s is gross, but I expect it at least to work consistently.  I don't understand why reloading the image makes it scale correctly when the window moves, but not when it's resized.

I've tried putting the image in a layout and calling `do_layout`, I've tried explicitly setting the image size with & without `kivy.metrics.dp` in the `_resize` func, and I've tried taking action on window resize, to no avail.

### Code and Logs

```python
class App(app.App):
    def build(self):
        clock.Clock.schedule_interval(self._resize, 0.1)
        self._image = image.Image(source=IMAGE_PATH, allow_stretch=False)
        return self._image

    def _resize(self, dt):
        self._image.reload()


if __name__ == "__main__":
    App().run()
```

```
[INFO   ] Kivy: v1.10.1
[INFO   ] Python: v3.7.2 (default, Jan 10 2019, 12:43:58) 
[Clang 10.0.0 (clang-1000.10.44.4)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'2.1 ATI-2.4.10'>
[INFO   ] GL: OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] GL: OpenGL renderer <b'AMD Radeon Pro 555 OpenGL Engine'>
[INFO   ] GL: OpenGL parsed version: 2, 1
[INFO   ] GL: Shading version <b'1.20'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Start application main loop
[INFO   ] Base: Leaving application in progress...
```

**Comment by toejough** [comment]
(I've also tried with `allow_stretch=True` and without specifying it at all - same behavior in all cases)

**Comment by toejough** [comment]
Turns out this is only a thing when the primary monitor is a standard-resolution one.  When I repeat this with the external monitor unplugged, and only my retina display available, I don't have any resizing issues.

**Comment by tito** [comment]
Could you provide a GIF or Video that demonstrate the issue?
What SDL2 version do you have used? (I remember old one were having issue with monitors and DPI)

**Comment by mahomahomaho** [comment]
Problem is related to DPI calculation. I had similar problem, and I (with @tshirtman help) discovered that it happends when you run window in non-retina display, then move it to retina, and then you resize it. In such case it still uses non-retina dpi and thus the effect. 

I made experiment, and when I copied code from here: https://github.com/kivy/kivy/blob/715417e389b3d13115811cfccaf8b408963739e0/kivy/core/window/window_sdl2.py#L278 to here: https://github.com/kivy/kivy/blob/715417e389b3d13115811cfccaf8b408963739e0/kivy/core/window/__init__.py#L1440, then it works ALMOST like a charm. I mean, window content stretches to whole window, but fonts are 2x smaller than they would be when started on retina. 

And I have no idea, where should I look for re-calculating font size to new DPI?

**Comment by mahomahomaho** [comment]
I made small experiment here https://github.com/mahomahomaho/kivy/pull/new/6144-retina-dpi-issue
 - it works like on the movie: https://transfer.sh/kivy-retina-fix.mp4

It's definitively not well done, but better than it is now. Question is - what should be done next? How to rescale fonts?

**Comment by tito** [comment]
@mahomahomaho I just checked your diff, the code used for recalculating the dpi should be not duplicated (it's already in window_sdl2 only right now), find a way to make it work on all providers then (maybe update_viewport is the right place to go)

As for the font size, there is multiple things:
- the dp/sp notation uses Metrics.density, which is behind a reify. Aka there is a cache and it doesn't change once calculated. You need to find a way to invalidate the cache when the density change. A notation like `Metrics.density.invalidate()`, but then you need to change the reify implementation.
- more globally, once rendered, if the widget graph is not retraveresed to force the rendering, then your font won't change. Fbo for example won't be rerendered if the window density changed. We don't want dp/sp to be dynamic either (would be nice, but super huge slowdown to track all of them). I suggest at least to make a density dynamic property on Window itself. The user can attach and refresh rendering if necessary.

**Comment by mahomahomaho** [comment]
@tito: of course it shouldn't be duplicated. It was only experiment. 

I tried to follow your hint, and changed all @reify with @property in Metrics - no luck. The font is still 2x smaller when resized. So I think that invalidating reified "properties" is blind alley. 

However, I have no idea, where should I go now. 

I'm considering just accepting the fact that fonts will be screwed :).

**Comment by mahomahomaho** [comment]
Hi. 

I made pull request #6289  - it partially fixes this issue. I mean fonts still are wrong (too small or too large), but at least window content is in it's whole area, not in top-left quarter. In many situations (eg. my situation) it's enough

**Comment by akshayaurora** [comment]
This issue is also evident while using screen emulation on a retina screen,  you can simply test with  `
python main.py -m screen:droid2,portrait
`

**Comment by matham** [comment]
Let track it here: https://github.com/kivy/kivy/issues/6785
