### ISSUE TITLE
Kivy master trying to use pygame instead of sdl2?

### ISSUE THREAD

**Issue by OptimusGREEN** [kivy/kivy#6151]
### Versions

* Python: 3.7
* OS: MacOS High Sierra
* Kivy: master
* Kivy installation method: pip

### Description

App won't run in my build env using master, 1.10.1 is fine and this error doesn't occur.

### Code and Logs

```
/usr/local/bin/python3.7 /Users/John/Development/Git/ogleavetracker/optileave/main.py
[INFO   ] [Logger      ] Record log in /Users/John/.kivy/logs/kivy_19-02-10_52.txt
[INFO   ] [Kivy        ] v1.11.0.dev0, git-4905319, 20190210
[INFO   ] [Python      ] v3.7.1 (default, Nov  6 2018, 18:45:35) 
[Clang 10.0.0 (clang-1000.11.45.5)]
[INFO   ] [Factory     ] 184 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [Window      ] Ignored <pygame> (import error)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
pygame - ModuleNotFoundError: No module named 'pygame'
  File "/usr/local/lib/python3.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.7/site-packages/kivy/core/window/window_pygame.py", line 8, in <module>
    import pygame

[INFO   ] [MD          ] forked KivyMD version: 0.1.2
[DEBUG  ] [Text        ] Provider <pango> ignored by config
[DEBUG  ] [Text        ] Ignored <pygame> (import error)
[DEBUG  ] [Text        ] Ignored <pil> (import error)
[CRITICAL] [Text        ] Unable to find any valuable Text provider.
pygame - ModuleNotFoundError: No module named 'pygame'
  File "/usr/local/lib/python3.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.7/site-packages/kivy/core/text/text_pygame.py", line 12, in <module>
    import pygame

pil - ModuleNotFoundError: No module named 'PIL'
  File "/usr/local/lib/python3.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.7/site-packages/kivy/core/text/text_pil.py", line 7, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.

Process finished with exit code 1
```

**Comment by tito** [comment]
You're using macosx, did you recompiled the kivy? Can you share the log of the compilation?
img_sdl2 don't even appear so something is wrong. We are now requiring SDL_Image 2.0.2 as a minimum so double check that?

**Comment by OptimusGREEN** [comment]
Here is what I done.

`iMac:~ John$ pip3 install --upgrade git+https://github.com/kivy/kivy
Collecting git+https://github.com/kivy/kivy
  Cloning https://github.com/kivy/kivy to /private/var/folders/cs/z8kmlcfx39v8t4wrsnvj5n5h0000gn/T/pip-req-build-fajlfa3x
Requirement already satisfied, skipping upgrade: Kivy-Garden>=0.1.4 in /usr/local/lib/python3.7/site-packages (from Kivy==1.11.0.dev0) (0.1.4)
Requirement already satisfied, skipping upgrade: docutils in /usr/local/lib/python3.7/site-packages (from Kivy==1.11.0.dev0) (0.14)
Requirement already satisfied, skipping upgrade: pygments in /usr/local/lib/python3.7/site-packages (from Kivy==1.11.0.dev0) (2.2.0)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.7/site-packages (from Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (2.20.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (2.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (2018.10.15)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (1.24.1)
Building wheels for collected packages: Kivy
  Running setup.py bdist_wheel for Kivy ... done
  Stored in directory: /private/var/folders/cs/z8kmlcfx39v8t4wrsnvj5n5h0000gn/T/pip-ephem-wheel-cache-31noj1_4/wheels/f1/e9/42/d7175156e34c35dee2757fe34aa9b6e75c262a0c912bbd33e7
Successfully built Kivy
Installing collected packages: Kivy
  Found existing installation: Kivy 1.10.1
    Uninstalling Kivy-1.10.1:
      Successfully uninstalled Kivy-1.10.1
Successfully installed Kivy-1.11.0.dev0
iMac:~ John$`

Should I be doing something else? Pretty sure this is how I normally update kivy.

**Comment by tito** [comment]
I don't see any compilation going on at all. Do you also have Cython installed?

**Comment by OptimusGREEN** [comment]
I'm not not home to test on the iMac just now but 90% sure cythin 0.29 is installed on that machine.

I will check later and confirm here.

**Comment by OptimusGREEN** [comment]
so I gave it another go, here is the pip install and pip freeze

`iMac:~ John$ pip3 install --upgrade git+https://github.com/kivy/kivy
Collecting git+https://github.com/kivy/kivy
  Cloning https://github.com/kivy/kivy to /private/var/folders/cs/z8kmlcfx39v8t4wrsnvj5n5h0000gn/T/pip-req-build-87urdm7n
Requirement already satisfied, skipping upgrade: Kivy-Garden>=0.1.4 in /usr/local/lib/python3.7/site-packages (from Kivy==1.11.0.dev0) (0.1.4)
Requirement already satisfied, skipping upgrade: docutils in /usr/local/lib/python3.7/site-packages (from Kivy==1.11.0.dev0) (0.14)
Requirement already satisfied, skipping upgrade: pygments in /usr/local/lib/python3.7/site-packages (from Kivy==1.11.0.dev0) (2.2.0)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.7/site-packages (from Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (2.20.1)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (2018.10.15)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->Kivy-Garden>=0.1.4->Kivy==1.11.0.dev0) (2.7)
Building wheels for collected packages: Kivy
  Running setup.py bdist_wheel for Kivy ... done
  Stored in directory: /private/var/folders/cs/z8kmlcfx39v8t4wrsnvj5n5h0000gn/T/pip-ephem-wheel-cache-tosy8x6s/wheels/f1/e9/42/d7175156e34c35dee2757fe34aa9b6e75c262a0c912bbd33e7
Successfully built Kivy
Installing collected packages: Kivy
  Found existing installation: Kivy 1.10.1
    Uninstalling Kivy-1.10.1:
      Successfully uninstalled Kivy-1.10.1
Successfully installed Kivy-1.11.0.dev0
iMac:~ John$ pip3 freeze
appdirs==1.4.3
buildozer==0.40.dev0
certifi==2018.10.15
chardet==3.0.4
colorama==0.4.0
Cython==0.29
docutils==0.14
dropbox==9.1.0
idna==2.7
Jinja2==2.10
jnius==1.1.0
Kivy==1.11.0.dev0
Kivy-Garden==0.1.4
Kodistubs==17.6.5
MarkupSafe==1.1.0
pexpect==4.6.0
ptyprocess==0.6.0
Pygments==2.2.0
pyjnius==1.1.3
python-for-android==0.7.1
requests==2.20.1
sh==1.12.14
six==1.11.0
typing==3.6.6
urllib3==1.24.1
virtualenv==16.1.0
iMac:~ John$
`

Looks the same as before, however it is now working as expected... very strange!

So as its working I'll close this issue off.
