### ISSUE TITLE
Meaningfull error message on lower case in kv file 

### ISSUE THREAD

**Issue by kjeldflarup** [kivy/kivy#6155]
It may just be me being a newbie, but it is a little up hill when a keyword in the .kv file starts with a lowercase, then all that is reported is just an attribute error.

Putting a meaningful message here would be good.
https://github.com/kivy/kivy/blob/4905319cd397f76df7d6683707426c92cca0a491/kivy/factory.py#L130

**Comment by MetalDent** [comment]
Hi, anyone working on this issue?

**Comment by 7040934** [comment]
เปิด

**Comment by pythonic64** [comment]
Solved by https://github.com/kivy/kivy/pull/6548.
