### ISSUE TITLE
System keyboard and mouse cursor not working if starting app on x11 without window manager (No RPi)

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#6157]
### Versions

* Python: 2 and 3
* OS: Linux (Debian 9)
* Kivy: master
* Kivy installation method: virtualenv

### Description

When running kivy app in x11 without window manager, no keyboard input is received (setting explicitly system keyboard in kivy config) and mouse cursor is not shown (also explicitly set in kivy config)

I try this on a regular desktop PC (Intel NUC), no touch display attached.

* I checked out kivy master and first compiled with SDL2 only (use_x11 was set to 0).
* then I modified setup.py and manually set use_x11 to True, which actually includes some kind of window information while still using sdl2 window provider. Both times i had the same behavior.

# Steps to reproduce

### Create some systemuser

```
adduser ktest
usermod -a -G input ktest
```

Login with this user from a non graphical console

### Create some folder containing a virtualenv

```
cd ~/
mkdir kapp
cd kapp
virtualenv .
./bin/pip install Cython==0.28.2
```

### Checkout kivy master inside kapp and compile

```
git clone https://github.com:kivy/kivy.git
cd kivy
../bin/pip install --editable .
```

Optionally you can edit ``setup.py`` and change line 168 as shown below before compiling

```
c_options['use_x11'] = True
```

### Create some simple dummy app in ``main.py``

```
import kivy
from kivy.app import App
from kivy.uix.button import Button

class KApp(App):
    def build(self):
        def _open_settings(*a):
            self.open_settings()
        button = Button(text='settings')
        button.bind(on_release=_open_settings)
        return button

if __name__ == '__main__':
    KApp().run()
```

## Create ``~/.xinitrc`` starting the application

```
exec /home/ktest/kapp/bin/python /home/ktest/kapp/main.py
```

## Start application

```
startx
```

Now x should fire up and the kivy app gets started. Mouse input works, while curser is not shown at all, and keyboard input is entirely broken.

**Comment by tito** [comment]
The "system" keyboard is just telling the TextInput to use key that cames from the Window provider instead VS invoking a virtual keyboard and use theses keys. So this has no impact on your case.

If i startx without windows manager, and then i start 2 xterm, how can you determinate the focus? Which app should received keyboard then?
I don't think it's going to work, SDL2 or X11 directly no?

**Comment by rnixx** [comment]
> If i startx without windows manager, and then i start 2 xterm

I actually start one (and only one) application which _should_ get the initial focus. At least this is always the case if i start e.g. chromium as single x app - no idea whether chromium forces the current focus on itself somehow (if this is the case kivy should do this as well).

It is not uncommon to fire up one single application w/o window manager to achieve some kind of kiosk solution.

I also observerd that from some point on (i think it was a reboot) at least the keyboard was working (according to the setting in ~/.kivy/config.ini), so maybe the keyboard issue is no issue at all and I just produced some noise. I'll do a complete system setup from scratch in order to double-check this, stay tuned.

In the meantime I also found out how to add a fake cursor via the cursor module. Nevertheless I wonder what happens here and what suppresses the system cursor from being displayed. It would be nice to get the system cursor displayed on demand (via show_cursor setting in graphics section of ~/.kivy/config.ini), so some can implement a display timeout then with ``unclutter`` if desired (which is my preferred solution)

**Comment by tito** [comment]
As talked on discord, i'm not sure that Kivy want to also handle that kind of thing. If the application don't have the focus, then yes the keyboard won't work. Therefore it's up to the runner to ensure the app have focus. It is the same with xterm for example.

xdotool can be used to force the window to have the focus initially if it's not done.
ratpoison can also ensure the app have the focus.

Doing the job of what the window manager is supposed to do may be the limit for Kivy :)
