### ISSUE TITLE
Error while compiling into APK: no compiled python is present to zip, skipping

### ISSUE THREAD

**Issue by piontk** [kivy/kivy#6161]
Trying to compile my project into APK I had the following error:

![image](https://user-images.githubusercontent.com/39860703/52737958-b93e5700-2fb4-11e9-993e-bb076150103d.png)

How can I handle it?

**Comment by tshirtman** [comment]
are you using p4a master? also, if you read the error message, there are actually instructions on what to do before you report an issue, there is simply not enough information here to help.

**Comment by resourceldg** [comment]
> Trying to compile my project into APK I had the following error:
> 
> ![image](https://user-images.githubusercontent.com/39860703/52737958-b93e5700-2fb4-11e9-993e-bb076150103d.png)
> 
> How can I handle it?

they can resolve it? I have the same problem

ubuntu 18

**Comment by piontk** [comment]
> > Trying to compile my project into APK I had the following error:
> > ![image](https://user-images.githubusercontent.com/39860703/52737958-b93e5700-2fb4-11e9-993e-bb076150103d.png)
> > How can I handle it?
> 
> they can resolve it? I have the same problem
> 
> ubuntu 18

Unfortunately I can't remember, but is not worth to try to generate an apk via buildozer. You'll spend a lot of time trying to do that and at the end your app won't run or another error happens. I really recommend to learn Java and develop via Android Studio, that is the most productive way to create Android apps, and the apk generation is instant. There are a lot of courses in Udemy that in less than two hours can teach you how to develope, generate and install apps in your own phone or virtual devices. That's what I did, what is being productive for me and giving me some money too. Feel free to disagree or keep trying.

**Comment by tshirtman** [comment]
We can't help when people don't provide the asked information about the issue they have, this issue has been closed for lack of information, @resourceldg if you have more, please open a new issue with the full build log, and the versions of things you use.
