### ISSUE TITLE
name error in bitbucket kivy-catalog

### ISSUE THREAD

**Issue by Livingstone99** [kivy/kivy#6162]
Accept my apologies if I'm doing this at the wrong place. I'm a newbie in kivy not in python syntax exactly. I downloaded the kivy-catalog folder, there is a nameerror in main.py, the 40th line. its 'open' not 'file'. Thank you, guys, I'm really enjoying this Framework.

**Comment by tito** [comment]
This is the project Kivy. We don't now nor manage a kivy catalog. Wrong place :/
