### ISSUE TITLE
Kivy crashes when the window is maximized

### ISSUE THREAD

**Issue by jcradzwill** [kivy/kivy#6167]
### Versions

* Python: 3.7.2
* OS: Windows 7 Enterprise
* Kivy: latest version as of 2/19/2019
* Kivy installation method: pip install

### Description

When I run the Kivy showcase app located here "share\kivy-examples\demo\showcase\main.py" (or any Kivy App for that matter), the app opens just fine and displays on the screen. However, right when I try to maximize the Kivy app window, the app immediately crashes with an error that says "Python has stopped working".  I have tried using Python 2 and the 32 bit and 64 bit versions of Python 3 with no luck. I have also tried re-installing Kivy multiple times and the issue remains.

### Code and Logs

```python

C:\Users\jxyz\AppData\Local\Programs\Python\Python37-32>python share\kivy-exa
mples\demo\showcase\main.py
[WARNING] [Config      ] Older configuration version detected (0 instead of 20)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in C:\Users\jxyz\.kivy\logs\kivy_19-02-19
_0.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52)
[MSC v.1916 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil
, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.4.0 - Build 20.19.15.4531'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 5500'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <b'4.40 - Build 20.19.15.4531'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 132px, got 84px
[WARNING] [Accordion   ] layout aborted.
[WARNING] [Accordion   ] not enough space for displaying all children
[WARNING] [Accordion   ] need 132px, got 84px
[WARNING] [Accordion   ] layout aborted.
![onappmaximize](https://user-images.githubusercontent.com/43111778/53051041-170cec00-3458-11e9-9cc2-e622c32de44c.JPG)
```

**Comment by tito** [comment]
Hi, can you try with ANGLE and see if it has the same behavior?
Are you up to date with your graphics drivers?

**Comment by jcradzwill** [comment]
Thanks for your help tito. I have installed glew and angle, but I don't know how to force the App to run with  angle instead. I tried running "python share\kivy-examples\demo\showcase\main.py SET KIVY_GL_BACKEND=angle_sdl2" in the command prompt and the logs say it is still using glew.  Am I just using the wrong command?

**Comment by tito** [comment]
You must set the KIVY_GL_BACKEND prior the python command (just to be sure). 
And you must have "pip install kivy.deps.angle"

But it might just be a driver issue, when you search on Google about freeze or crash on fullscreen for HD Intel 5500, you ends up with some recent report. Driver crash happens :/ I'm letting this open to see if others have the issue too. So far, no fix seems to be provided.
