### ISSUE TITLE
Segfault in core image when loading same image twice

### ISSUE THREAD

**Issue by jleaders** [kivy/kivy#6173]
### Versions

* Python: 3.6.7
* OS: Ubuntu 18.10
* Kivy:  v1.10.1
* Kivy installation method: PIP I presume, I tried via github but build was broken at the time

### Description

Running the image constructor on the same image twice core-dumps with a segfault.

### Code and Logs

Requires image magick:
```bash
convert -size 800x800 xc:white white.png
python3 -c 'from kivy.core.image import Image; Image("white.png"); Image("white.png")'
rm white.png
```
Output
```python
[INFO   ] [Logger      ] Record log in /home/jonny/.kivy/logs/kivy_19-02-25_46.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[1]    28864 segmentation fault (core dumped)  python3 -c 
```

**Comment by tito** [comment]
If it segfault, then it's because it's requiring OpenGL, which is not initialized in your test.

This works:
```
python3 -c 'import kivy.core.window; from kivy.core.image import Image; Image("white.png"); Image("white.png")'
```

But we should have a catch about that yes.

**Comment by jleaders** [comment]
Without knowing the internals, it seems to me that if Image is requiring OpenGL, and importing kivy.core.window is how you fix it, then Image needs to be the one importing OpenGL as that is a dependancy of core Image
