### ISSUE TITLE
Python3.8 wheels not currently available?

### ISSUE THREAD

**Issue by 12o13** [kivy/kivy#6177]
I've been trying to install Kivy on Windows10 via the command prompt with Python 3.8 and after a bunch of trouble shooting it seems the wheels are not available for Python 3.8. Any chance these can be made available?

**Comment by matham** [comment]
Until appveyor makes them available, we cannot make 3.8 wheels (https://www.appveyor.com/docs/windows-images-software/#python). Also, python 3.8 is still in alpha.

**Comment by GwenaelPellenArkeup** [comment]
Hi.

Did I read that it is now supported ?

**Comment by matham** [comment]
Yes, it's resolved now.
