### ISSUE TITLE
Video and VideoPlayer Error loading texture

### ISSUE THREAD

**Issue by vadimk2016** [kivy/kivy#6181]
### Versions

* Python: 3.6
* OS: Ubuntu 18.04(Virtual)
* Kivy: 1.10.1
* Cython: 0.29.6
* Kivy installation method: pip

### Description

Cant load any video using VideoPlayer or Video. When I launch the application, I get an endless animation of loading if I use VideoPlayer or a blank(white) screen if I use Video.

### Code and Logs

```
from os.path import dirname, join
from kivy.app import App
from kivy.uix.videoplayer import VideoPlayer

class VideoPlayerApp(App):

    def build(self):
        curdir = dirname(__file__)
        filename = join(curdir, 'cityCC0.mpg')
        return VideoPlayer(source=filename, state='play')


if __name__ == '__main__':
    VideoPlayerApp().run()
```
Output:
```
[INFO   ] [Logger      ] Record log in /home/v/.kivy/logs/kivy_19-03-05_11.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'SVGA3D; build: RELEASE;  LLVM;'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[WARNING] [Image       ] Unable to load image </home/v/PycharmProjects/test-app/cityCC0.mpg>
[ERROR  ] [Image       ] Error loading texture /home/v/PycharmProjects/test-app/cityCC0.mpg
```
Lines that cause attention:
```
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
[ERROR  ] [Image       ] Error loading texture /home/v/PycharmProjects/test-app/cityCC0.mpg
```
Kivy installed by commands:
`pip install cython pillow pygame && pip install kivy`
and all libs from https://kivy.org/doc/stable/installation/installation-linux.html
Gstreamer installed from https://gstreamer.freedesktop.org/documentation/installing/on-linux.html
Gstreamer checked by command:
`gst-launch-1.0 videotestsrc ! autovideosink`

If I try:
`from kivy.lib.gstplayer import GstPlayer`
I get an error:
` ModuleNotFoundError: No module named 'kivy.lib.gstplayer._gstplayer'`

**Comment by vadimk2016** [comment]
It lloks like that was a problem with my system. I restored system from previus VmWare snapshot(just after install) and installed all libs again and after that I get gstplayer in kivy video providers. I just had to install the `gstreamer1.0-plugins-ugly` and `gstreamer1.0-plugins-bad` additional libraries since I got the error:
```
[WARNING] [VideoGstplayer] b "No decoder available for type 'video / mpeg, systemstream = (boolean) true, mpegversion = (int) 1'."
[ERROR] [VideoGstplayer] b'Your GStreamer installation is missing a plug-in. '
[ERROR] [VideoGstplayer] b'Internal data stream error. '
```

**Comment by tito** [comment]
Exactly. If none of the provider can be used, it's just you're missing libraries. Not an issue here :)

**Comment by jobvanellen** [comment]
So I doe have the drivers installed and gstplayer is set as video provider. Yet it still is unable to load textures. 

`[INFO   ] [Logger      ] Record log in /home/sysop/.kivy/logs/kivy_19-07-03_15.txt
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.4.2 (default, Feb 10 2019, 17:23:02)
[GCC 4.9.2]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <b'Compiled'>
[INFO   ] [Shader      ] vertex shader: <b'Compiled'>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [VideoGstplayer] Using Gstreamer 1.4.4.0
[INFO   ] [Video       ] Provider: gstplayer
[ERROR  ] [Image       ] Error loading texture /home/sysop/Hmi/movie.mov
[INFO   ] [GL          ] NPOT texture support is available
`
Does anyone know why this problem could occur?

**Comment by GermanInfinity** [comment]
Hello, please I am having the same issue here; I also get: Error loading texture cat.mp4
It doesn't seem like the problem was solved. Could someone help with this? Thank you.

**Comment by vadimk2016** [comment]
> Hello, please I am having the same issue here; I also get: Error loading texture cat.mp4
> It doesn't seem like the problem was solved. Could someone help with this? Thank you.

Did you run `python -m pip install ffpyplayer` ?

**Comment by andywei2015** [comment]
As vadimk2016 said, after pip install ffpyplayer, the problem solved for me.

**Comment by GermanInfinity** [comment]
Thanks for the responses.
