### ISSUE TITLE
Trying to install kivy-examples on Linuxmint 19.1 but can't find package

### ISSUE THREAD

**Issue by wyattbiker** [kivy/kivy#6201]
I am using the command in your docs https://kivy.org/doc/stable/installation/installation-linux.html

I can install python3-kivy using apt-get however the examples will not install.

`sudo apt-get install kivy-examples`
I get this message
`E: Unable to locate package kivy-examples`

However when I use Synaptic Manager it installs fine. Any ideas? Thanks!
![image](https://user-images.githubusercontent.com/930478/54369736-d23a3680-464c-11e9-9ef1-1208f566d96f.png)

**Comment by tito** [comment]
According to https://launchpad.net/ubuntu/+source/kivy - packages are here. Can you try to open and select the .deb according to your Ubuntu version?

**Comment by matham** [comment]
I just tried mint 19.1 in a docker (based on 18.04) and tested with daily ppa and kivy-examples was properly installed as per the instructions.
