### ISSUE TITLE
Kivy OSX install instructions fail at first step. DOC issue + install code issue

### ISSUE THREAD

**Issue by kcrossen** [kivy/kivy#6202]
From https://kivy.org/doc/stable/installation/installation-osx.html:
```
2. Open the dmg
3. Copy the Kivy.app to /Applications.
4. Create a symlink by running the makesymlinks in the window that opens when you open the dmg
```
Point 4) fails on OSX 10.11.6. It fails w/ a console error message in 1.9.1 (access denied), silently in 1.10.x.

So this doesn't work unless your script has no dependencies, which is the **succeeding** topic:
```
You can just drag and drop your main.py to run your app too.
Installing modules
```
But this will fail (because makesymlinks failed):
```
$ kivy -m pip install <modulename>
```
Which means that "drag and drop your main.py to run your app" will fail. Catch-22.

Complete frustration before having made it to the end of the installation page.

The OSX doc issue is really two issues. 1) Makesymlinks is foobar. 2) Onward instructions are therefore useless. Fix makesymlink and it's possible the rest will be right. 

Oddly makesymlinks is sytlistically a lot closer to bash than to Python and that's a pity.

**Comment by akshayaurora** [comment]
MakeSymlinks script is just the following command 

ln -s /Applications/Kivy<version>/Contents/Resources/script /usr/local/bin/kivy<version>

version is either 2/3 based on which version of the app did you download.

Problem:
========
The issue with the `MakeSymlinks` script is that osx does now allow you to run any script from a unidentified source anymore.

You have to specifically right click on the `Make Symlinks`. script and then run it.

Solution:
=======
1: We could Release the app through app store or sign it using a identified developer account.
2: Add instructions for people to manually add this symlink  look at #6204


Have done the second part, will be looking at implementing point 1. for long term.
