### ISSUE TITLE
Raspberry Pi3B+ Python 3 Kivy Error

### ISSUE THREAD

**Issue by Derenz10** [kivy/kivy#6206]
### Versions

* Python: 3.5.3
* OS: Raspbian (Stretch)
* Kivy: 1.11.0
* Kivy installation method: http://mattrichardson.com/kivy-gpio-raspberry-pi-touch/index.html

### Description

Hi,

I have installed kivy on my Raspberry Pi3B+ with the latest version of Raspbian. The official instructions didn't work so I have now followed Matt Richardson's guide on github. My problem is that when I run any main.py example it will run initially, open a window, then close the window within a second, and give the following error below. Can anyone please help me to understand what is happening and how to fix it?

Any help would be greatly appreciated.

### Code and Logs

pi@raspberrypi:/usr/share/kivy-examples/demo/showcase $ python main.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_19-03-16_10.txt
[INFO   ] [Kivy        ] v1.11.0.dev0, git-c4d6894, 20190316
[INFO   ] [Python      ] v3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[WARNING] [WinPygame   ] Video: failed (multisamples=2)
[WARNING] [WinPygame   ] trying without antialiasing
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO   ] [HIDInput    ] Read event from </dev/input/event3>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
[INFO   ] [HIDInput    ] Read event from </dev/input/event4>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <Chicony Multimedia Keyboard>
[INFO   ] [HIDMotionEvent] using <Microsoft Microsoft® 2.4GHz Transceiver v8.0>
[INFO   ] [HIDMotionEvent] using <Chicony Multimedia Keyboard>
[INFO   ] [HIDMotionEvent] using <Microsoft Microsoft® 2.4GHz Transceiver v8.0>
[INFO   ] [HIDMotionEvent] using <Microsoft Microsoft® 2.4GHz Transceiver v8.0>
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 238, in <module>
     ShowcaseApp().run()
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/app.py", line 855, in run
     runTouchApp()
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/window_pygame.py", line 403, in mainloop
     self._mainloop()
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/window_pygame.py", line 289, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/__init__.py", line 606, in _upd_kbd_height
     self._keyboard_changed = not self._keyboard_changed
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy/properties.pyx", line 1472, in kivy.properties.AliasProperty.trigger_change
   File "kivy/properties.pyx", line 1479, in kivy.properties.AliasProperty.trigger_change
   File "kivy/properties.pyx", line 1506, in kivy.properties.AliasProperty.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/__init__.py", line 955, in <lambda>
     keyboard_height=lambda *dt: self.update_viewport())
   File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/__init__.py", line 1466, in update_viewport
     self.render_context['projection_mat'] = projection_mat
 TypeError: 'NoneType' object does not support item assignment
pi@raspberrypi:/usr/share/kivy-examples/demo/showcase $ 

```

**Comment by Derenz10** [comment]
> ### Versions
> * Python: 3.5.3
> * OS: Raspbian (Stretch)
> * Kivy: 1.11.0
> * Kivy installation method: http://mattrichardson.com/kivy-gpio-raspberry-pi-touch/index.html
> 
> ### Description
> Hi,
> 
> I have installed kivy on my Raspberry Pi3B+ with the latest version of Raspbian. The official instructions didn't work so I have now followed Matt Richardson's guide on github. My problem is that when I run any main.py example it will run initially, open a window, then close the window within a second, and give the following error below. Can anyone please help me to understand what is happening and how to fix it?
> 
> Any help would be greatly appreciated.
> 
> ### Code and Logs
> pi@raspberrypi:/usr/share/kivy-examples/demo/showcase $ python main.py
> [INFO ] [Logger ] Record log in /home/pi/.kivy/logs/kivy_19-03-16_10.txt
> [INFO ] [Kivy ] v1.11.0.dev0, git-c4d6894, 20190316
> [INFO ] [Python ] v3.5.3 (default, Sep 27 2018, 17:25:39)
> [GCC 6.3.0 20170516]
> [INFO ] [Factory ] 184 symbols loaded
> [INFO ] [Image ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
> [INFO ] [Window ] Provider: egl_rpi
> [INFO ] [GL ] Using the "OpenGL ES 2" graphics system
> [INFO ] [GL ] Backend used 
> [INFO ] [GL ] OpenGL version <b'OpenGL ES 2.0'>
> [INFO ] [GL ] OpenGL vendor <b'Broadcom'>
> [INFO ] [GL ] OpenGL renderer <b'VideoCore IV HW'>
> [INFO ] [GL ] OpenGL parsed version: 2, 0
> [INFO ] [GL ] Shading version <b'OpenGL ES GLSL ES 1.00'>
> [INFO ] [GL ] Texture max size <2048>
> [INFO ] [GL ] Texture max units <8>
> [INFO ] [Window ] Provider: pygame(['window_egl_rpi'] ignored)
> [WARNING] [WinPygame ] Video: failed (multisamples=2)
> [WARNING] [WinPygame ] trying without antialiasing
> [INFO ] [GL ] Using the "OpenGL ES 2" graphics system
> [INFO ] [GL ] Backend used 
> [INFO ] [GL ] OpenGL version <b'OpenGL ES 2.0'>
> [INFO ] [GL ] OpenGL vendor <b'Broadcom'>
> [INFO ] [GL ] OpenGL renderer <b'VideoCore IV HW'>
> [INFO ] [GL ] OpenGL parsed version: 2, 0
> [INFO ] [GL ] Shading version <b'OpenGL ES GLSL ES 1.00'>
> [INFO ] [GL ] Texture max size <2048>
> [INFO ] [GL ] Texture max units <8>
> [INFO ] [Window ] virtual keyboard not allowed, single mode, not docked
> [INFO ] [Text ] Provider: pygame
> xclip version 0.12
> Copyright (C) 2001-2008 Kim Saunders et al.
> Distributed under the terms of the GNU GPL
> [INFO ] [Clipboard ] Provider: xclip
> [INFO ] [CutBuffer ] cut buffer support enabled
> [INFO ] [GL ] NPOT texture support is available
> [INFO ] [ProbeSysfs ] device match: /dev/input/event3
> [INFO ] [HIDInput ] Read event from </dev/input/event3>
> [INFO ] [ProbeSysfs ] device match: /dev/input/event1
> [INFO ] [HIDInput ] Read event from </dev/input/event1>
> [INFO ] [ProbeSysfs ] device match: /dev/input/event4
> [INFO ] [HIDInput ] Read event from </dev/input/event4>
> [INFO ] [ProbeSysfs ] device match: /dev/input/event2
> [INFO ] [HIDInput ] Read event from </dev/input/event2>
> [INFO ] [ProbeSysfs ] device match: /dev/input/event0
> [INFO ] [HIDInput ] Read event from </dev/input/event0>
> [INFO ] [Base ] Start application main loop
> [INFO ] [HIDMotionEvent] using 
> [INFO ] [HIDMotionEvent] using <Microsoft Microsoft® 2.4GHz Transceiver v8.0>
> [INFO ] [HIDMotionEvent] using 
> [INFO ] [HIDMotionEvent] using <Microsoft Microsoft® 2.4GHz Transceiver v8.0>
> [INFO ] [HIDMotionEvent] using <Microsoft Microsoft® 2.4GHz Transceiver v8.0>
> [INFO ] [Base ] Leaving application in progress...
> Traceback (most recent call last):
> File "main.py", line 238, in 
> ShowcaseApp().run()
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/app.py", line 855, in run
> runTouchApp()
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/base.py", line 502, in runTouchApp
> EventLoop.window.mainloop()
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/window_pygame.py", line 403, in mainloop
> self._mainloop()
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/window_pygame.py", line 289, in _mainloop
> EventLoop.idle()
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/base.py", line 337, in idle
> Clock.tick()
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/clock.py", line 581, in tick
> self._process_events()
> File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
> File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
> File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
> File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/**init**.py", line 606, in _upd_kbd_height
> self._keyboard_changed = not self._keyboard_changed
> File "kivy/properties.pyx", line 483, in kivy.properties.Property.**set**
> File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
> File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
> File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
> File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
> File "kivy/properties.pyx", line 1472, in kivy.properties.AliasProperty.trigger_change
> File "kivy/properties.pyx", line 1479, in kivy.properties.AliasProperty.trigger_change
> File "kivy/properties.pyx", line 1506, in kivy.properties.AliasProperty.dispatch
> File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
> File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/**init**.py", line 955, in 
> keyboard_height=lambda *dt: self.update_viewport())
> File "/usr/local/lib/python3.5/dist-packages/Kivy-1.11.0.dev0-py3.5-linux-armv7l.egg/kivy/core/window/**init**.py", line 1466, in update_viewport
> self.render_context['projection_mat'] = projection_mat
> TypeError: 'NoneType' object does not support item assignment
> pi@raspberrypi:/usr/share/kivy-examples/demo/showcase $

**Comment by matham** [comment]
This is the same issue as https://github.com/kivy/kivy/issues/6007.
