### ISSUE TITLE
Carousel binding on current_slide is called twice with the same value

### ISSUE THREAD

**Issue by goffi-contrib** [kivy/kivy#6207]
### Versions

* Python: 2.7.15
* OS: Arch Linux (seen also on Android)
* Kivy: v1.11.0.dev0, git-a95d67f, 20190316
* Kivy installation method: pip

### Description

A callback binded on `Carousel.current_slide` is called several times with the same widget, but a property binding should not call again a callback if its value didn't change.

### Code and Logs

```python
from kivy.app import App
from kivy.uix.carousel import Carousel
from kivy.factory import Factory
import sys

class TestBinding(App):

    def build(self):
        self.last_slide = None
        carousel = Carousel(direction='left',
                            loop=True)
        carousel.bind(current_slide=self.on_current_slide_change)
        for i in range(4):
            src = "http://placehold.it/480x270.png&text=slide-%d&.png" % i
            image = Factory.AsyncImage(source=src, allow_stretch=True)
            carousel.add_widget(image)
        print("TEST SUCCEEDED")
        sys.exit(0)

    def on_current_slide_change(self, __, new_slide):
        print("new_slide: {}".format(new_slide))
        if new_slide == self.last_slide:
            print("TEST FAILED (slide {} added twice)".format(new_slide))
            sys.exit(1)
        self.last_slide = new_slide

TestBinding().run()
```

**Comment by tito** [comment]
Already addressed in PR #6055 
See https://github.com/kivy/kivy/pull/6055/files#diff-a9976c886d7dcfe267c69353a5a433f8

**Comment by goffi-contrib** [comment]
@tito cool :). Should I close the ticket, or let it until it's merged so we can try the test script?

**Comment by tito** [comment]
I'm letting the script open to convert it as a unittest :)
