### ISSUE TITLE
Thanks to all Kivy developers

### ISSUE THREAD

**Issue by danvica** [kivy/kivy#6208]
### Versions

* Python: 3.7
* OS: windows 10
* Kivy: 1.10
* Kivy installation method: on anaconda

### Description
I don't know if this is the right place to thank you all but I couldn't find any other.

In our company we've used kivy in an exhibition presentation of a virtual kitchen worktop.

You can find a video here https://www.youtube.com/watch?v=LqGn8FVHRQQ
Sorry for the quality.

If anyone has any question I'll be glad to help.

Thank you again. The result is great!

Daniele

**Comment by tshirtman** [comment]
Nice, this is indeed not the best place, but i'm glad i saw it, you can add it to the wiki for apps, and if you have a short description/nice pic, it could be added to the gallery.

There is also a channel in discord where we encourage people to share news about their projects.

I'm tempted to leave this open as a symptom of the bug that it's not very clear for users where to share their projects, but i'm not sure when/how that would be resolved, so it's probably going to be closed before we solve that :sweat_smile:

**Comment by JonasT** [comment]
this is  really cool, thanks @danvica for making this "ticket" :heart:  :heart:

**Comment by avour** [comment]
Really cool.
Thank all kivy dev
