### ISSUE TITLE
ModuleNotFoundError: No module named 'kivy'

### ISSUE THREAD

**Issue by Jymchaves** [kivy/kivy#6213]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by tshirtman** [comment]
Issues are not for support. Use the support channel on discord (chat.kivy.org) or the kivy users mailing list.
