### ISSUE TITLE
on_touch_down event not received by child widgets

### ISSUE THREAD

**Issue by enjoysmath** [kivy/kivy#6218]
Attached is a minimal running example for this issue.

You can add an ellipse ("Object") by clicking the Diagram widget, but how do you get your ellipses to receive subsequent on_touch_down events?  

I've placed breakpoints in the on_touch_down events, I've returned a super() call to on_touch_down so it can "finish processing the event".  

Still not working.

[BananaCatsKivy.zip](https://github.com/kivy/kivy/files/2998975/BananaCatsKivy.zip)

**Comment by vchslv13** [comment]
OK, 2 problems here: 1) you forget to call Object's superclass __init__ method and 2) you don't call Diagram.add_widget() to add Object to the list of it's children.
Here is the fixed version in which Object's on_touch_down works as supposed: 
[BananaCatsKivy_fixed.zip](https://github.com/kivy/kivy/files/2999016/BananaCatsKivy_fixed.zip)

Speaking in general (considering that I'm newbie too) - if that's acceptable I'd offer to you to read kivy's documentation more thoroughly.
Hope my answer has helped.

**Comment by enjoysmath** [comment]
Yes that fixed it.  You are not a newbie any more!
