### ISSUE TITLE
about markup

### ISSUE THREAD

**Issue by Jmxmanman** [kivy/kivy#6224]
### Versions

* Python: 3.5
* OS: win10
* Kivy: 1.10.1
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs
when i met [xxx] [/xxx] the content will jumps to the next row

for example:
     [color=ff3333]爱过[/color]的人,我已不再拥有,许多故事有伤心的理由,这一次我的,等不到天长地久,错过的人,是否可以回首
![Snipaste_2019-03-26_17-48-07](https://user-images.githubusercontent.com/42801311/54987318-55fe0680-4fef-11e9-8ea4-130d4862ef0c.JPG)

     the word behind[/color] It will jumps to the next row

How do I color a word in Inputtext? or How do I add markup to Textinput?
```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by gottadiveintopython** [comment]
I don't use markup much, but I've never met this kind of issue. Can you share the code that reproduce the issue?

**Comment by shashi278** [comment]
@gottadiveintopython did you check it? 'cause I'm getting it correct at this end.
See this shot.( Never mind the encoding. Tried a little, couldn't help it. But the idea is, it's not splitting up the lines.)
![Screenshot_20190413-090045](https://user-images.githubusercontent.com/37111736/56074281-011f0600-5dcd-11e9-9377-3d6a7a274c3c.png)

**Comment by gottadiveintopython** [comment]
@shashi278 Same here.

**Comment by Jmxmanman** [comment]
Hey， Are you there? 
About 'markup', I've tried it many times, but i never solved the problem.....Take a look at  the picture below
![Snipaste_2019-04-17_09-16-16](https://user-images.githubusercontent.com/42801311/56254293-c41b8200-60f2-11e9-839d-6ebe093e20de.JPG)

When the language is English, No matter what I do, It doesn't wrap，When the language is Chinese, I got the problem

When I try to change the size of the window, 
![Snipaste_2019-04-17_09-34-12](https://user-images.githubusercontent.com/42801311/56254709-6425db00-60f4-11e9-8d9b-e8b78d14b222.JPG)
![Snipaste_2019-04-17_09-31-40](https://user-images.githubusercontent.com/42801311/56254713-68ea8f00-60f4-11e9-81b9-269d2adfeeb6.JPG)
![Snipaste_2019-04-17_09-34-39](https://user-images.githubusercontent.com/42801311/56254714-6be57f80-60f4-11e9-9ce3-8b70f65c1ce2.JPG)

There nothing wrong with the English part,  but there are a lot of strange things that can happen in Chinese

Here is a part of the code:

·BoxLayout:
	size_hint_y: 1
	orientation: 'vertical'
	MDLabel:
		id: voice_content
		text_size:self.size
		size_hint_y: 1
		valign: 'top'
		font_name:'./wryh.ttf'
		font_size:16
		markup: True
		text:'now you know the meaning of [color=ff3333]sunshine[/color] after [color=ff3333]rain[/color]---'*10
	MDLabel:
		id: voice_content
		text_size:self.size
		size_hint_y: 1
		valign: 'top'
		font_name:'./wryh.ttf'
		font_size:16
		markup: True
		text:'像风一样[color=ff3333]自由[/color]自由自由自由自由'*10 ·

**Comment by Jmxmanman** [comment]
> @gottadiveintopython did you check it? 'cause I'm getting it correct at this end.
> See this shot.( Never mind the encoding. Tried a little, couldn't help it. But the idea is, it's not splitting up the lines.)
> ![Screenshot_20190413-090045](https://user-images.githubusercontent.com/37111736/56074281-011f0600-5dcd-11e9-9377-3d6a7a274c3c.png)

Hey Are you there? I update my questions at the comments could you do me a favor if you are free

**Comment by shashi278** [comment]
@Jmxmanman so you get this new line problem when you resize your window and not normally? It's clearly a text wrapping problem. Wrapping texts works like if it'll see the next word can't be fit, it'll wrap the entire text( without breaking the text) onto the new line.
Now the English sentence has several spaces but I can't see any space in the Chinese one( or I may be wrong as I can't read Chinese) and hence, I guess, it causes problems with wrapping. I tried giving some space around few characters( I'm not sure if I've changed the word itself) in the Chinese one and now it's quite pretty.
In the first picture, you see too many blank spaces at the end of line 'cause it gets the word 自由自由自由自由像风 which is quite longer and hence can't fit in there.
For instance, if I break 自由自由自由自由 into two with a space in between and some more spaces around few words in the sentence, I get output like this picture below.
![Screenshot_20190417-100037](https://user-images.githubusercontent.com/37111736/56261187-adc3f500-60f7-11e9-8b0c-cd9c04e5d594.png)

**Comment by Jmxmanman** [comment]
I

> @Jmxmanman所以当你调整窗口大小而不是正常情况时，你会遇到这个新行问题？这显然是文本包装问题。包装文本就好像它会看到下一个单词不合适，它会将整个文本（不会破坏文本）包装到新行上。
> 现在英语句子有几个空格，但我看不到中文的空格（或者我可能错了，因为我看不懂中文），因此，我想，它会导致包装问题。我尝试在中文版本中给几个字符周围留出一些空间（我不确定我是否已经改变了这个词）现在它非常漂亮。
> 在第一张图片中，您会在行尾看到太多空格，因为它会得到单词“自由自由自由自由像风”，因为它长得太长，因此不适合那里。
> 例如，如果我将自由自由自由自由分成两个，其间有一个空格，并且在句子中的几个单词周围有一些空格，我会得到如下图所示的输出。
> ![Screenshot_20190417-100037](https://user-images.githubusercontent.com/37111736/56261187-adc3f500-60f7-11e9-8b0c-cd9c04e5d594.png)

I GOT IT ! THANK YOU SO MUCH!!  I just put a space between the Two Chinese , It solved
