### ISSUE TITLE
TextInput: text selection cancelled when scrolling with mousewheel

### ISSUE THREAD

**Issue by me2beats** [kivy/kivy#6226]
In TextInput, when scrolling text using mousewheel, text selection is removed. Checked on Windows and Ubuntu

```python
from kivy.app import App
from kivy.lang import Builder

KV = """
TextInput
    font_size: 20
    text: app.text
"""

class MyApp(App):
    def build(self):
        self.text = '\n'.join(['some text, line '+str(i) for i in range(200)])
        self.root = Builder.load_string(KV)

MyApp().run()
```

**Comment by vchslv13** [comment]
Can confirm it on my Kubuntu 18.04 with latest dev version of Kivy.
Coincidentally I was just getting familiar with TextInput's code to try fixing another issue. Probably I'll try fix this one too in the next week or two.
