### ISSUE TITLE
demo/kivycatalog fail

### ISSUE THREAD

**Issue by audiserg** [kivy/kivy#6231]
error:
    File "/usr/lib/python3/dist-packages/kivy/core/text/markup.py", line 427, in render_lines
     script_pos = max(0, psp if psp else self.get_descent())

need replace string 427 in core/text/markup.py   to script_pos = max(0, psp)

error:
no fonts

need add  data/fonts/DroidSansMono.ttf

**Comment by matham** [comment]
The issue is missing a full description on how to replicate it and the full log.
