### ISSUE TITLE
Performance issues (confirmed issue upstream) with SDL2-2.0.9

### ISSUE THREAD

**Issue by clevermindgames** [kivy/kivy#6239]
### Versions

* Python: 2.7
* OS: Android
* Kivy: 1.10.1+ (master)
* Kivy installation method:
buildozer
### Description

After experimenting with master branch of kivy I noticed massive performance degradation on Android. I have profiled my app on 1.10.1 and master branch, and it appears that SDL2 related code started to take much more time. I could post the profiling stats if necessary.

After some digging I found this known (and fixed) issue upstream:
https://bugzilla.libsdl.org/show_bug.cgi?id=4481
with the patch: https://github.com/Homebrew/homebrew-core/commit/4fbb6a7e63d9256d2d83b324ffda8287730bbe0e

The problem (most likely) has been introduced to kivy with this commit: 
https://github.com/kivy/kivy/commit/49bad8c3850d3e1caca45531cd0e64b3294bd97f

Looks like we need to add an additional patch from SDL. Unfortunately, I do not know recipies that well myself - hence the issue rather than a pull request.

**Comment by JonasT** [comment]
If you just want to work around this for yourself for now, there is a pull request to p4a to use almost newest dev version of SDL2: https://github.com/kivy/python-for-android/pull/1779 however it currently has a regression regarding SDL_TOUCH_MOUSEID (again upstream issue) so probably a bit too early to merge it in

**Comment by clevermindgames** [comment]
Thank you @JonasT!
Since this issue is tracked in python-for-android, there is no point to keep it open here.
After more investigation I also realised this was not the main reason for performance degradation in my app - I will create separate issue for it.
