### ISSUE TITLE
Chinese language is mess up 

### ISSUE THREAD

**Issue by linpan** [kivy/kivy#6240]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```
when  I text "北京"  it will shows mess

**Comment by shashi278** [comment]
You should give more details regarding the problem. And it'd better if you could provide the the method to reproduce the issue.
