### ISSUE TITLE
Strange Rectangles drawn in weird places

### ISSUE THREAD

**Issue by clFaster** [kivy/kivy#6244]
### Versions

* Python: 3.7
* OS: Windows 10
* Kivy:  1.10.1
* Kivy installation method: https://kivy.org/doc/stable/installation/installation-windows.html

### Description
The titel of this issues isn't really helpful, but I will do my best to describe it in detail. As you can see on the pictures I attached, there is a white rectangle drawn at some random spots.

Normally there should be buttons, and the buttons are created on demand. They are created in the "on_pre_leave" function from the first screen. The "list_resource_locations" is called for that.

```python
# Python Code:
class ResourceLocation(GridLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Do some stuff, not relevant

    def list_resource_locations(self):
        for resource_location in Something:
            button = ResourceLocationButton(text=resource_location, id="R" + resource_location)
            self.add_widget(button)


# Kivy Code:
    <ResourceLocationButton>
    background_color: [0.671, 0.596, 0.596, 1]
    background_normal: ''

    BoxLayout:
        orientation: "vertical"
        size_hint_y: 0.5
        Label:
            size_hint_y: None
            height: 35
            text: "Resource Location"
            font_size: '20sp'
            canvas.before:
                Color:
                    rgba: .48, .48, .48, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

        ScrollView:
            size: self.size
            size_hint_y: 1
            size_hint_x: 1
            canvas.before:
                Color:
                    rgba: .52, .52, .52, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
            ResourceLocation:
                id: resource_locations
                cols: 1
                size_hint_y: None
                height: self.minimum_height
                spacing: 1
                padding: [1, 0, 1, 1]
```
![Error](https://user-images.githubusercontent.com/10184336/55802142-e9e3ce00-5ad7-11e9-89be-1238b7a6d961.PNG)

The intressting thing is that this bug nearly never occurs, but more often when I run the code in the debug mode. I have the feeling it has something to do with the speed everything gets executed or so.

I find it really hard to track down the problem, has someone a simillar issues or some idea what might be the cause of it? 

I would like to attach a small example on how to reproduce the error, but in the my short version the error didn't occure.

This is how that part should look like:
![Error 2](https://user-images.githubusercontent.com/10184336/55803673-151bec80-5adb-11e9-8ea6-c8afffcea1d1.PNG)

The Error sometimes occurs on the left side as well. I used the same structure (Boxlayout, ScrollView, GridLayout) and similar functions to create the buttons here. The intressting thing is that 3 Buttons are missing and they are "replaced" by that white rectangle?!
![Error 3](https://user-images.githubusercontent.com/10184336/55803783-514f4d00-5adb-11e9-945f-77ede1fc9d14.PNG)

I used breakpoints to stop the execution at some points to inspect the kivy data, but I can't find the rectangles there.

**Comment by tshirtman** [comment]
Are there threads involved in your version that produces the issue? If so, make sure to execute anything that create/update/delete widgets from the main thread.

**Comment by clFaster** [comment]
Hi, thanks for your help, yes another thread was the problem. 
I fixed it by using events to add the buttons.
