### ISSUE TITLE
Unable to find a loader for </data/data/org.test.gpsguide/files/app/none.wav> ffpyplayer

### ISSUE THREAD

**Issue by SashaTuh** [kivy/kivy#6251]
### Versions

* Python: v3.7.1
* OS: Android
* Kivy: v1.11.0.dev0
* Kivy installation method: pip

### Description

So i need to ffpyplayer work. But he's not. When i'm trying to open file by SoundLoader
(i change os.environ['KIVY_AUDIO'] to 'ffpyplayer') he gives me that error: [WARNING] [Audio       ] Unable to find a loader for </data/data/org.test.gpsguide/files/app/none.wav>. Yes, none.wav is in the same folder as main.py and Yes, in buildozer.spec - source.include_exts is empty(to include all files). In my PC all works. But Android open sdl2, but i need ffpyplayer(to use seek() and get_pos()). At the end is that: AttributeError: 'NoneType' object has no attribute 'get_pos'

P.S. sry for my English

### Code and Logs

```python
#Peace of code
import os
os.environ['KIVY_AUDIO'] = 'ffpyplayer'
from kivy.lang import Builder
from kivy.app import App
from kivy.properties import StringProperty
from kivy.clock import Clock, mainthread
from kivy.uix.slider import Slider
from kivy.core.image import Image as CoreImage
from kivy.uix.popup import Popup
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.togglebutton import ToggleButton
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.image import Image
from kivy.uix.textinput import TextInput
from kivy.graphics import Rectangle

from kivy.core.audio import SoundLoader

sound = SoundLoader.load('none.wav')
sound.play()

position = sound.get_pos()

print(position)
```

**Comment by tshirtman** [comment]
Please provide the full log in debug mode, make sure ffpyplyer is properly installed and that the log indicates that it's in the candidates (not ignored).

**Comment by LordzShadow** [comment]
I don't know if it's the same error exactly, but for some reason for me on android kivy automatically uses AudioSDL2. I would like to use ffpyplayer, because it can stream music from the internet(radio and so on). I also used os.environ[KIVY_AUDIO] = "ffpyplayer" but it didn't help. On Linux it uses Gstreamer and that works.


[log.txt](https://github.com/kivy/kivy/files/3118119/log.txt)
