### ISSUE TITLE
Drop python 2

### ISSUE THREAD

**Issue by Fak3** [kivy/kivy#6253]
I could not find a list of tasks that should be done for kivy to drop python2 support. Could someone please weigh in?

Python 2 hinders the asyncio support, which I am interested in, and probably other things (?)

**Comment by matham** [comment]
This was the timeline and issues we had originally envisioned: https://github.com/kivy/kivy/wiki/Kivy-Python-2-Support-Timeline. As you can see, we are a few months past what I originally thought was going to be the time we're dropping python 2.

I'm not sure of the python 3 status of py4a and kivy-ios. They were the two main blockers.

We also had a discussion about this here: https://groups.google.com/forum/#!topic/kivy-dev/kXnDut1e8dI

In my opinion, we should drop python 2 ASAP. Practically, we would need to do at least one release before dropping python 2.

**Comment by inclement** [comment]
python-for-android is fully python3 ready. We might drop python3 support quite soon (not dropping support for targeting python2 on Android, but python-for-android itself would only run under python3).

**Comment by matham** [comment]
On discord, `m1sl6` said that he uses kivy-ios for py3. Sounds like kivy-ios is mostly ready. The main obstacle is making a new release, I guess.

**Comment by akshayaurora** [comment]
💧

**Comment by matham** [comment]
I think I'll close this now as the plan seems to be to drop python 2 support as soon as https://github.com/kivy/kivy/issues/6274 is done.
