### ISSUE TITLE
ScreenManager won't switch back to a screen it already switched to when using transition=FallOutTransition()

### ISSUE THREAD

**Issue by s1113950** [kivy/kivy#6254]
### Versions

* Python: 3.7.2
* OS: Mac 10.14.4
* Kivy: Tried with latest `master` and 1.10.1
* Kivy installation method: pip

### Description

I'm trying to switch back to a screen I've already switched to, but Kivy doesn't update. I've tried a few different ways, the `.current` attribute gets set but my screen doesn't update. I've tried updating it both from a thread and not from a thread and still no luck.

### Code and Logs

I've tried all of these:
```python
def reset_game():
     root.game_screen.manager.current = "player"
Clock.schedule_once(lambda _: reset_game(), 1)

root.game_screen.manager.current = "player"
 
App.get_running_app().p.current = "player"
```
I tried `.switch_to()` but get the normal error of: 
```
File "/usr/local/lib/python3.7/site-packages/kivy/uix/screenmanager.py", line 984, in add_widget
     'Screen already managed by this ScreenManager (are you '
 kivy.uix.screenmanager.ScreenManagerException: Screen already managed by this ScreenManager (are you calling `switch_to` when you should be setting `current`?)
```
I was able to originally switch to this screen just fine, but now I want to switch back to it after being on a different screen that the same `ScreenManager` is managing.

I'm currently on the `game_screen` and would like to go back to the `player_screen`. I've also tried changing this from the `player_screen`'s `manager`; setting `.current` on `player_screen.manager` also didn't work.

I'm testing my app by running `python main.py` from a venv where Kivy is installed.

**Comment by shashi278** [comment]
Switching screen is easier. All you need is to set the ScreenManager's current property to the name of the screen you wanna switch to.
Now, what is `root` in reset_game? And do you get any error by `root.game_screen.manager.current = "player"`?

**Comment by s1113950** [comment]
That's what I tried :( I tried to switch the ScreenManager's current property but it didn't do anything. I don't get any error when I do `root.game_screen.manager.current = player`. 

I should have been more clear though, the `manager` in this case is the `ScreenManager`, and `root` is the root widget. I reference it here because it's running in a thread and I want to update a screen when I get info from a socket. I thought it was because of the thread that things weren't working but my other threaded function in the same class does a similar thing and it works fine. 

Here's what works, in the same class as what doesn't:
```
def gamestart(self, root, args):
        root.player_screen.new_game_popup.dismiss()
        root.game_screen.init_game()
        root.player_screen.manager.switch_to(root.game_screen)
```
And it works because `game_screen` has not been attached to the `ScreenManager` yet, but in my case I'm going from the `game_screen` _back_ to the `player_screen`, and that is not doing anything.

What doesn't work:
```
def pilepoint(self, root, args):
        """handles adjusting pile point count"""
        ...
        if args['count'] == "0":
            # def reset_game():
            #     root.game_screen.manager.current = "player"
            # Clock.schedule_once(lambda _: reset_game(), 1)
            
            #  root.game_screen.manager.current = "player"
            
            # App.get_running_app().p.current = "player"
```
any of those 3 different commented blocks don't work to switch from the game screen back to the player screen. I get an error as expected as I mentioned above when I do `.switch_to()` since it already is a part of the `ScreenManager`.

**Comment by s1113950** [comment]
Should I just delete the `player_screen` and re-attach it maybe? 🤔 Feels like the wrong approach though

**Comment by shashi278** [comment]
Removing `player_screen` child from `ScreenManager` and again adding it back to manger through `root.game_screen.manager.switch_to()` may work. Or I think it won't.
See, why `root.game_screen.manager.current` isn't working can have only one reason that it's actually not reaching to the manager 'cause if it could it would have worked absolutely.

Here's a way, I think, will work for you 'cause it does for me. 
If I'm understanding it correctly, you're probably calling `pilepoint` function from the `player_screen`. If it is, try sending the `game_screen`'s instance in the function instead of the root of the app. So, if now `root` in `pilepoint` isn't the root of the app but the `game_screen` then `root.manager.current= 'player' ` should work. I created something similar to your situation and it's working on this this side. 

And one more question, does `root` has both `player_screen` and `game_screen` attached to it right from the beginning and `player_screen` is attached to the `ScreenManager` but `game_screen` isn't attached to the `ScreenManager` at the beginning?

**Comment by s1113950** [comment]
`pilepoint` function is being called from an instance declared like this:
`class SocketThread(Thread, EventProcessor):` , where the `EventProcessor` has the `pilepoint` function inside of it.
I tried using `game_screen`'s `manager` but no luck there either 🤔 
`root` in `pilepoint` is the root of the app.

`root` has the `player_screen` added to it via this:
```
self.p.add_widget(login_screen)
self.p.add_widget(player_screen)
self.p.current = "login"
```
, and then I set the `current` view to `login`. 

I just tried to not add the `player_screen` widget here and instead `.switch_to` it later (all of this before I need to switch _back_ to the `player_screen`), and that didn't work either

**Comment by shashi278** [comment]
If you can reach to manager, the stuffs should work. I cannot see why it'd not be working.
I hope someone better could give some insights.
Meanwhile, you may consider sharing your project with me if it's open source so that I could help in a better way.

**Comment by s1113950** [comment]
It's closed-source right now because I can't tell if I eventually want to put it on the app store or not 😬 . I'll try the idea of deleting and re-adding the screen though to see if that fixes things.
Thanks for working through this with me

**Comment by s1113950** [comment]
calling `.remove_widget` and then `.switch_to()` didn't work 🤔 I'm not sure what else to do here

**Comment by shashi278** [comment]
Hey, did you tried printing all available screens in the manager(just for the debug purpose) using `manager.screens`and see what are the screens currently present in the manager you're working upon?

**Comment by s1113950** [comment]
All screens are present in the manager when I printed `manager.screens`

**Comment by s1113950** [comment]
I tried a new approach of `.add_widget()`-ing each screen to the manager in the `def build()` function in the beginning of an app, but that also doesn't work 😞

**Comment by s1113950** [comment]
I made a sample function to see what was going on:
```
-> self.app.p.current = "player"
(Pdb) self.app.p.current
'game'
(Pdb) self.app.p.screens
[<Screen name='login'>, <Screen name='player'>, <Screen name='game'>]
(Pdb) self.app.p.children
[<Screen name='game'>]
(Pdb) n
> /Users/robertso/piles/app-piles/field/pile_points.py(43)doit()
-> print('just set current screen')
(Pdb) self.app.p.children
[]
(Pdb) self.app.p.screens
[<Screen name='login'>, <Screen name='player'>, <Screen name='game'>]
(Pdb) self.app.p.current
'player'
```
All 3 screens are a part of the ScreenManaer, the current screen is `game`, I then check the `children` of the screenmanager and see that it is `game`, and then after `current` is set there are no more children, the screens are there, and the current screen is `player` but the UI doesn't change. Looks like `children()` should be set to the `player` screen rather than being empty?

I then tried to set `children` manually via `App.get_running_app().manager.children.append` and that didn't work. I threw in a `.do_layout()` on both the `RootWidget` as well as the `ScreenManager` after setting `current = "player"` and that didn't do anything either. I even tried `App.get_running_app().manager.current = "player"` both in and out of a `Clock.schedule_once` call and still the screen didn't change.

At this point I think I'm gonna try and patch `kivy` itself to fix my problem. No matter what I try I can't get `ScreenManager` to switch to a screen that it has already loaded once before.

**Comment by s1113950** [comment]
I discovered something!!! When I remove this: `transition=FallOutTransition()` from the Manager definition then my UI does update with the old screen, but it is overlayed on top of the existing screen and not formatted correctly!

**Comment by gottadiveintopython** [comment]
> but it is overlayed on top of the existing screen and not formatted correctly!

This sometimes happens when you switch a screen before the previous switching is done. Try the following code instead of directly accessing to `current` property.

```python3
from kivy.uix.screenmanager import ScreenManager
from kivy.logger import Logger

class YourScreenManager(ScreenManager):
    def switch_screen(self, name, transition=None):
        if self.transition.is_active:
            Logger.warning(f"YourApp: You can't switch screen until the previous transition is done.")
            return
        if not self.has_screen(name):
            Logger.warning(f"YourApp: No screen named '{name}'")
            return
        if transition is not None:
            self.transition = transition
        self.current = name
```

Also make sure you don't access to Kivy from outside of its main thread.

**Comment by s1113950** [comment]
Thank you for the code snippet! I'm still unable to switch screens with fallouttransition declared initially in the manager (so this issue should still be valid), but I discovered why my screen half-changes: I accidentally set one screen's widgets on the root widget rather than on the screen itself :man-facepalming:

**Comment by akshayaurora** [comment]
@s1113950 can you test with #6279

**Comment by matham** [comment]
`switch_to` doesn't accept a screen that is already been added. This will be fixed in https://github.com/kivy/kivy/pull/6346.
