### ISSUE TITLE
The Kivy Android Virtual Machine

### ISSUE THREAD

**Issue by Maksych** [kivy/kivy#6259]
On page "https://kivy.org/#download" I'm not found download link for "The Kivy Android Virtual Machine".

**Comment by RonTang** [comment]
I try to download old version VM. When I build apk,it say **aidl** not install!!!!   
So sad, If I use apt-get install aidl, unable to locate package aidl...       This is 9000+ star project,but I can't use it do make a hello world apk.

**Comment by matham** [comment]
We don't provide an official VM for building apks anymore. You can find an unofficial vm here: https://github.com/Zen-CODE/kivybits/tree/master/KivyCompleteVM. You can also search the kivy-users mailing list for more info or ask there for further help.

**Comment by RonTang** [comment]
Thanks for sharing this vm.It really work.@matham

**Comment by Maxey11** [comment]
the download link is not working ;-;

**Comment by AndiinPS** [comment]
o link de download não fuciona
