### ISSUE TITLE
Kivy Release Plan (1.11.0)

### ISSUE THREAD

**Issue by matham** [kivy/kivy#6274]
Kivy Release Plan (1.11.0)
=============================

This is the release plan for the upcoming kivy release. There are probably sill things we are missing and we'll add them to the checklist as we discover them.

Pre release
============

* [x] Update kivy.deps.xxx
  * [x] Go through all the deps in kivy-sdk-packager (https://github.com/kivy/kivy-sdk-packager/tree/master/win) and increase the versions to trigger a build if a new version of the dep is available. It uploads to https://kivy.org/downloads/ci/win/deps/
  * [x] Add wheel support for the most recent python version 3.x.
  * [x] Download and upload to pypi with `twine upload *.whl`
    * [x] sdl2
    * [x] angle
    * [x] gstreamer
      * [x] Document that the new gstreamer is only compatible with the new version of kivy due to https://github.com/kivy/kivy/pull/6275.
    * [x] glew
  * [x] In the windows install docs, update the pinned versions of kivy and its dependencies.
* [x] Update setup.py Cython version to works with latest
* [x] Update License file + dates
* [x] Create release GH milestone for the release subsequent to this.
* [x] Check release tag GH issues, retag those left to the next version
* [x] Correct “deprecated” directives before tagging
* [x] Add wheel support for the most recent python version 3.x.
* [x] Update nightly wheel version links for windows, osx, linux.
* [x] Do any doc updates (these docs will remain in stable until the next release so...)
  * [x] Update all the files in doc/sources/installation.
* [x] Ensure latest build works everywhere (tests pass)
  * [x] CI - Travis
  * [x] Appveyor (mingw python3 builds deactivated for now)
  * [x] Check the daily ppa is building correctly (https://code.launchpad.net/~kivy-team/+recipe/kivy-daily).
* [x] Do a pre-release by changing version `x.y.z.dev0` to `x.y.zrc1` tagging `(git tag -a x.y.zrc1 -m "Tag vx.y.zrc1")` and test on all platforms
  * [x] pip upload to pypi (it's a pre-release so it won't be installed by default), use the `--pre` for pip to download it.
    * [x] linux
    * [x] osx
    * [x] windows
    * [x] kivy examples wheel works
    * [x] `tar.gz`
  * [x] pip install windows wheels
    * [x] py2
    * [x] py3
    * [x] kivy examples wheel works
  * [x] pip install windows zip (from https://github.com/kivy/kivy/archive/x.y.zrc1.zip)
    * [x] py2
    * [x] py3
  * [x] pip install osx wheels
    * [x] py2
    * [x] py3
    * [x] kivy examples wheel works
  * [ ] Install osx app
    * [ ] py2
    * [ ] py3
  * [x] pip install osx zip (from https://github.com/kivy/kivy/archive/x.y.zrc1.zip)
    * [x] py2
    * [x] py3
  * [x] pip install linux wheels
    * [ ] py2
    * [x] py3
    * [x] kivy examples wheel works
  * [x] pip install linux zip (from https://github.com/kivy/kivy/archive/x.y.zrc1.zip)
    * [x] py2
    * [x] py3
  * [x] Test linux ppa daily.
  * [x] Open PR for pre-release on https://github.com/conda-forge/kivy-feedstock to see if conda builds on all platforms

Iterate as needed. 

Release
=======

* [x] Prepare release notes (https://github.com/kivy/kivy/wiki/Release-notes-for-1.11.0) Previous release notes for reference: https://github.com/kivy/kivy/wiki/Release-notes-for-1.10.0
  * [x] Use github-changelog-generator to dump the changelog. See https://github.com/kivy/kivy/blob/master/kivy/tools/changelog_parser.py for full instructions.
  * [x] On github filter the closed pull requests by api-break label and move any PRs up to the API-break section in the changelog.
  * [x] Generate contributor list by running `git shortlog -s 1.10.1..HEAD > log`, remove duplicate lines listing the same person under different names and than do a regex search (`\n +[0-9]+\t+(.+)`) and replace (`, $1`) on the log to get the comma separated list of names.
  * [x] Clearly list any major changes, deprecations, or removals that will occur in the upcoming version.
  * [x] Validate release notes with at least one native English speaker
* [x] Remove dev0/rc from the version and tag release (set `RELEASE` in `kivy/__init__.py` to `True`, commit the result and tag `git tag -a x.y.z -m "Tag vx.y.z"` and push `git push kivy master --tags`). Wait for CI to complete building and uploading all the wheels and files to https://kivy.org/downloads/ci/.
* [x] Make the release directory and upload release files for all platforms to the kivy server under https://kivy.org/downloads/x.y.z/:
  ```sh
  ssh -p 2458 root@kivy.org
  cd /web/downloads
  mkdir x.y.z
  ```
  Copy all the CI generated file to that folder.
    * [x] Windows, macOS, and linux wheels.
    * [x] macOS Kivy.app files.
    * [x] source distribution.
    * [x] kivy examples.
* [x] Update branches:
  * [x] On the server move `/web/doc/stable` to `/web/doc/stable-x.y.z`, where `x.y.z` is the version  of the release before last. Also copy `/web/doc/master` to `/web/doc/stable` as follows:
    ```sh
    ssh root@kivy.org
    cd /var/lib/docker/volumes/kivy-server_kivy_doc/_data/
    mv stable stable-x.y.z
    cp -r master stable
    ```
  * [x] Merge master into stable and wait for the stable docs to have built as follows:
    ```sh
    git fetch kivy
    git checkout --track kivy/stable
    git branch stable-x.y.z
    git checkout -b stable2
    git merge master
    ```
    Fix any merge issues and commit the merge if there are conflicts. This lest you fix issues on the stable2 branch without having to nuke local stable if things go wrong.

    Now make sure people on stable have a clean upgrade path:
    ```sh
    git checkout stable
    git checkout -b stable3
    git merge stable2
    ```
    If the stable2 merge was clean, you're ready to push stable with
    ```
    git push kivy stable-x.y.z:stable-x.y.z
    git push kivy stable2:stable_tmp
    ```
    Now make a PR to merge `stable_tmp` into `stable` (e.g. https://github.com/kivy/kivy/pull/6349), get it approved and merged.
  * [x] Delete `stable_tmp`.
  * [x] Wait for the stable docs to fully build on the CI.
* [x] Download files from the server and upload to pypi (https://pypi.org/project/Kivy/) with `twine upload *`.
  * [x] Wheels:
    * [x] Windows
    * [x] macOS
    * [x] linux
  * [x] kivy-examples
  * [x] sdist (built on the windows CI)
* [x] Make new conda release on https://github.com/conda-forge/kivy-feedstock.
  * [x] Verify that the new release was uploaded.
* [x] Update the PPA (daily and stable, https://github.com/kivy/kivy-sdk-packager/tree/master/linux/debian). 
  * [x] update rules/control/changelog files if changes required for daily and stable.
  * [x] Copy all changes from the daily control and rules file into the stable.
  * [x] update changelog file for daily and stable version in kivy-sdk-packager
  * [x] Edit the recipe (https://code.launchpad.net/~kivy-team/+recipe/kivy-stable) to build on the desired Ubuntu platforms - compare to https://code.launchpad.net/~kivy-team/+recipe/kivy-daily/ which already have been updated to master before the release.
  * [x] Request to re-import kivy-sdk-packager and kivy (https://code.launchpad.net/~thopiekar/kivy/+git/kivy-sdk-packager, https://code.launchpad.net/~thopiekar/kivy/+git/kivy).
  * [x] Wait to make sure that both kivy and kivy-sdk-packager has been imported on launchpad and that the stable branch lists the proper last commit from the merge from master.
  * [x] Trigger a new build for daily and stable.
  * [x] Wait to make sure daily and stable builds have properly uploaded.
* [ ] Test release
  * [ ] pip install windows wheels
    * [ ] py2
    * [x] py3
    * [x] kivy examples wheel works
  * [ ] pip install windows zip (from https://github.com/kivy/kivy/archive/x.y.zrc1.zip)
    * [ ] py2
    * [ ] py3
  * [ ] pip install osx wheels
    * [ ] py2
    * [ ] py3
    * [ ] kivy examples wheel works
  * [ ] Install osx app
    * [ ] py2
    * [ ] py3
  * [ ] pip install osx zip (from https://github.com/kivy/kivy/archive/x.y.zrc1.zip)
    * [ ] py2
    * [ ] py3
  * [ ] pip install linux wheels
    * [ ] py2
    * [ ] py3
    * [ ] kivy examples wheel works
  * [ ] pip install linux zip (from https://github.com/kivy/kivy/archive/x.y.zrc1.zip)
    * [ ] py2
    * [ ] py3
  * [ ] Test linux ppa daily and stable.
  * [ ] Test conda.
* [x] Bump kivy version to the next version.
  * [x] Set `RELEASE` to `False` and `rcx` to `dev0`.
  * [x] Update `DOC_VERSIONS` in `.travis.yml` in master to add `stable-x.y.z` from two release ago so it is listed on the website as a doc option.
* [x] Website
  * [x] Create a branch for the release
  * [x] Update `projects.json` with metadata using `git diff --shortstat last_tag current_tag`. Get the number of commits from github's release page diff to master, and the number of PRs from the changelog.
  * [x] Update `index.html`.
  * [x] Update the links for each OS as needed.
  * [x] Create a media + text for the frontpage
  * [x] Integrate Changelog for release tag, it'll likely need to be reformatted for the site.
  * [x] Update gallery with new projects
  * [x] Merge the website
  * [x] Ensure the page is updated
* [x] Update Discord/IRC channels titles
* [x] Update github release info https://github.com/kivy/kivy/releases
* [ ] Share on Kivy Planet
* [x] Share on Google groups (kivy-dev + kivy-users)
* [x] Share on Reddit (https://www.reddit.com/r/Python/comments/69uctq/kivy_1100_released/)
* [x]  Share on HN (https://news.ycombinator.com/newest (don’t direct link))
* [x] Share on Facebook
* [x] Add new announcement on Launchpad
* [x] Share on Twitter https://twitter.com/mathieuvirbel/status/861353662299484160
* [ ] Ask the RPI image maintainer to update the RPI/Kivy ISO
* [ ] Update Kivy launcher on android.

External tools
--------------
* GDrive for 1.10.0: https://drive.google.com/drive/folders/0By88oIfn3BI4V21ETzAwTVc2VFE
* Travis: https://travis-ci.org/kivy/kivy
* Appveyor: https://ci.appveyor.com/project/KivyOrg/kivy/branch/master

Methods
----------

* You can add `[build wheel]` to the commit message to force a build for wheels. Similarly `[build app osx]` to build the osx kivy.app files. You can also do `[build wheel win]`, `[build wheel linux]`, or `[build wheel osx]` to selectively build wheels for a platform.

Notes
--------

* put our notes there, not in the plan

**Comment by pythonic64** [comment]
Can we have this request https://github.com/kivy/kivy/pull/6055 merged before `1.11.0` release?

**Comment by matham** [comment]
I added it to the milestone.

**Comment by pythonic64** [comment]
I have to make another pull request to update docs of `AliasProperty`. 
It will be done by the next Friday.

**Comment by rnixx** [comment]
Can i close this? 1.11.1 is out already for a long time.
