### ISSUE TITLE
Events bound to Window properties may crash if updating opengl when Window doesn't exist

### ISSUE THREAD

**Issue by inclement** [kivy/kivy#6277]
Apparently this can happen on Android when the Window changes due to e.g. app rotation, as the Window context actually gets destroyed and created again (I think).

This is described at https://github.com/kivy/python-for-android/issues/1797, issue opened here because I think this needs a fix within Kivy.

**Comment by idevo89** [comment]
This got introduced with #6186 live resizing. This doesn't work correctly on Android when you resize the window with screen orientation or split-screen. It will also eventually crash when you keep rotating the screen.

04-25 21:51:08.568 16744 16744 I python  :  Traceback (most recent call last):
04-25 21:51:08.568 16744 16744 I python  :    File "/Apps/PowerMote/.buildozer/android/platform/build/build/python-installs/powermote/kivy/core/window/window_sdl2.py", line 244, in _event_filter
04-25 21:51:08.569 16744 16744 I python  :    File "/Apps/PowerMote/.buildozer/android/platform/build/build/python-installs/powermote/kivy/base.py", line 349, in idle
04-25 21:51:08.569 16744 16744 I python  :    File "/Apps/PowerMote/.buildozer/android/platform/build/build/python-installs/powermote/kivy/lang/builder.py", line 711, in sync
04-25 21:51:08.569 16744 16744 I python  :  TypeError: 'NoneType' object is not subscriptable

For now I exclude Android from the sdl_windowevent in _window_sdl2.pyx to quick fix it:
https://github.com/idevo89/kivy/blob/c4e8131b82df1145f1499eabf4ca81ef43d61f21/kivy/core/window/_window_sdl2.pyx#L50-L55

Here some images:
Button font not rendered after rotation https://imgur.com/a/nxAGSwD
Ok with Android excluded from live resizing https://imgur.com/a/g2aSqEk
Split-screen showing the difference https://imgur.com/a/joETsQr

**Comment by matham** [comment]
Is this android specific? If we're sure it's only on android we can disable live resizing there as it's probably not useful anyway there.

**Comment by idevo89** [comment]
Android-only, did not test it for ios though, but we can disable it for ios too because it is also not needed there.

**Comment by matham** [comment]
Have you tested your app on any of the desktop environments to make sure?

**Comment by idevo89** [comment]
I can confirm live resizing works on Windows and Ubuntu.

**Comment by akshayaurora** [comment]
Live resizing works on OSX too, makes sense to disable on mobile platforms.
