### ISSUE TITLE
TypeError in builder.py

### ISSUE THREAD

**Issue by gbm001** [kivy/kivy#6284]
### Versions
* Python: 3.7
* OS: Android
* Kivy: master branch
* Kivy installation method: git clone/Buildozer

### Description

Not really sure what is going on here, and I can't make a short, runnable example but thought it might be useful to post the problem and my workaround in case it recurs/someone has the same problem...

I have an app which both switches screens and changes the screen orientation (via PyJnius) at the same time. I have just upgraded to the current Kivy, Buildozer, python-for-android master branch, and I am running in Python 3 (just moved away from crystax).

When doing the screen switching I would erratically get a crash in kivy/lang/builder.py in sync().
There is a global linked list, _delayed_start. Each item is a list where the last item is either StopIteration or another list. Calls to _delayed_call_fn add a new entry to the front of the linked list (replacing _delayed_start). Then presumably on a regular basis sync() is called which (if _delayed_start is not None i.e. any calls have been added to it) runs through the linked list running call_fn on the various arguments.
In builder.py:
```python
    try:
        call_fn(next_args[:-1], None, None)
    except ReferenceError:
        pass
```
My app was failing here with a TypeError on next_args[:-1] (NoneType not subscriptable) because somehow the linked lists were getting corrupted and instead of another list or StopIteration, the last argument was just None.
I spent some time trying to instrument this since there is only one place that _delayed_start is set, but failed to work out where the error was being introduced. I can only assume its something weird, niche and threading related. I assumed Python code of this nature was thread-safe, due to the GIL, but I can easily see how competing threads running delayed_call_fn could bugger it all up since adding stuff to the linked list is not atomic.

My workaround (which also makes the code way simpler; not sure why the linked list thing is implemented) is just to use _delayed_start_list as a new global, set initially to an empty list. delayed_call_fn appends args to this list, and sync runs through them then clears the list. This seems to have fixed the crashes?

Honestly this one has baffled me somewhat despite spending probably 4 hours repeatedly rerunning code trying to work out what is going wrong.

**Comment by matham** [comment]
Do you at all create kivy widgets or change their properties etc from another thread?

**Comment by gbm001** [comment]
I definitely don't do it intentionally. I have noticed before that on_pause and on_resume get called from another thread so I have a hacky call to a mainthread function to do the Kivy call, and then sleep for half a second or so (in on_pause) before returning. But it's possible it's still my fault.

The other thing is that before upgrading Kivy, when returning from a resume where the orientation had changed (as in this case) the widgets were always positioned wrong. I read that this was better in the newer version of SDL so upgraded and this fixed it, apart from these delayed_fn_call which were (nearly?) always 'pos' changes. Could that be calling from another thread?

**Comment by matham** [comment]
This kind of issue is very very likely to be caused if you manipulate any kivy object from another thread. Kivy properties or widgets cannot be manipulated from other threads. 

I would make absolutely sure that you're not doing that and then re-open the issue with a repreducable example as this is not likely a kivy bug.
