### ISSUE TITLE
Caps Lock not detected

### ISSUE THREAD

**Issue by Inspirateur** [kivy/kivy#6285]
### Versions

* Python: 3.7
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

I'm trying to add a little warning message on my passworld field when Caps Lock is on, but I can't seem to get this info from kivy.

### Code and Logs
I just tried to print keycode, text and modifiers
```python
class TextInputCapsWarn(TextInput):
	def keyboard_on_key_down(self, window, keycode, text, modifiers):
		print(keycode, text, modifiers)
```
And this is what I get when typing `a, z d, Caps Lock ON, a, a, z` :
```
(97, 'a') a []
(122, 'z') z []
(100, 'd') d []
(301, 'capslock') ĭ []
(97, 'a') a []
(97, 'a') a []
(122, 'z') z []
``` 
So basically the modifiers list remain empty even with caps locks ON, and while I do detect the caps lock press I can't tell if it's ON or OFF.

This is a really minor issue but I thought documenting on it wouldn't hurt.
Thanks for your time.

**Comment by matham** [comment]
Here's a fix https://github.com/kivy/kivy/pull/6286.

P.S. take a look at the `keyboard_on_textinput` method. That provides the properly capitalized text.

**Comment by Inspirateur** [comment]
Thanks for the effort :D
The `keyboard_on_textinput` doesn't solve my issue on its own because I can't tell if the text has been capitalized with SHIFT (which would be intentionnal) or Caps Lock (which could be unintentionnal), that being said I'll keep an eye on your PR and I hope it gets accepted !
