### ISSUE TITLE
Problema ao iniciar kivy

### ISSUE THREAD

**Issue by robertoweller** [kivy/kivy#6299]
Bom tem acontecido é isso que aparece

Traceback (most recent call last):
   File "play_test.py", line 3, in <module>
     from kivy.uix.videoplayer import VideoPlayer
   File "/usr/lib/python3/dist-packages/kivy/uix/videoplayer.py", line 84, in <module>
     from kivy.properties import ObjectProperty, StringProperty, BooleanProperty, \
   File "kivy/_event.pxd", line 3, in init kivy.properties (kivy/properties.c:33752)
   File "kivy/_event.pyx", line 891, in init kivy._event (kivy/_event.c:15608)
 TypeError: descriptor 'property' requires a 'kivy._event.EventDispatcher' object but received a 'method_descriptor'

Meu código funcionava antes, o problema foi quando tentei compilar com buildozer para android deu erro agora nem na minha maquina funciona nem consigo compilar.

[Python      ] v3.5.2
[Kivy        ] v1.11.0.dev0

Meu codigo:

kivy.require('1.9.0')
from kivy.uix.videoplayer import VideoPlayer
from kivy.app import App

class rodaVideo(App):
	def build(self):
		# Carrega o local do video e carrega a classe video 
		self.video = VideoPlayer(source = 'lind-musi-anime.mp4')

		return self.video # Retorna 'chama' o video e a variavel que contem a class VideoPlayer()

if __name__ == '__main__':
	
	rodaVideo().run()

**Comment by matham** [comment]
I tried and couldn't replicate the problem.

**Comment by robertoweller** [comment]
I managed to solve the problem, basically I was using kivy in the wrong way. Solution to uninstall all, and install again.
