### ISSUE TITLE
New install of Kivy3 on OSX Mojave won't launch

### ISSUE THREAD

**Issue by joelprestonsmith-2019** [kivy/kivy#6302]
This is an issue first reported about three years ago on GitHub, then closed, but it's still an issue. The same problems that were listed by users then are still present now. 

An overview of those problems is here: 
https://github.com/kivy/kivy/issues/3235

Kivy 3 won't launch on Mojave (the same issues were present for Yosemite). The install doesn't create a symlink in the Applications directory. That's repaired by invoking: 

ln -s /Applications/Kivy.app/Contents/Resources/script /use/local/kivy

But neither the symlink in Applications, nor trying to open Kivy3 from the command line works. 

Any known solutions? 

### Versions

* Python: 3
* OS: Mojave 10.14.4
* Kivy: 3
* Kivy installation method: Downloaded from https://kivy.org/#download

Specifically downloaded from the link for this text: 
Python 3 134.9MB OSX > 10.13.5

That link is for OSX 10.9 or later 

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

Kivy 3 won't launch on Mojave (the same issues were present for Yosemite). The install doesn't create a symlink in the Applications directory.

I expected the app to open. 

### Code and Logs

```python
// REPLACE ME: There are no msgs associated with Kivy3 in the /var/log/ file (and I don't have a /var/log/messages file) 
```

**Comment by rayushbpgc** [comment]
same issue

**Comment by EricoCartmanez** [comment]
Same here.

**Comment by matham** [comment]
That's because kivy.app is built on Catalina so it won't work on older versions of osx. For older versions, you need to build the app yourself by following e.g. https://github.com/kivy/kivy-sdk-packager/tree/master/osx

**Comment by EricoCartmanez** [comment]
It didn't work in Catalina either...

**Comment by matham** [comment]
Please use [kivy.app from master](https://kivy.org/downloads/ci/osx/app/Kivy.dmg) and follow [these instructions](https://kivy.org/doc/master/installation/installation-osx.html#using-the-kivy-app).

**Comment by EricoCartmanez** [comment]
I really don't see why downloading the dmg when it does nothing. 

Anyway I installed it like this:
```
brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer python3
```
and:
```
pip3 install git+https://github.com/kivy/kivy.git@master
```

I still get:
```
  ~/PycharmProjects/fitness-app  pip3 show kivy
Name: Kivy
Version: 2.0.0rc4
Summary: A software library for rapid development of hardware-accelerated multitouch applications.
Home-page: http://kivy.org
Author: Kivy Team and other contributors
Author-email: kivy-dev@googlegroups.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: Kivy-Garden, docutils, pygments
Required-by:
 ~/PycharmProjects/fitness-app  kivy main.py
/Applications/Kivy.app/Contents/Resources/venv/bin ~/PycharmProjects/fitness-app
~/PycharmProjects/fitness-app
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import kivy
ModuleNotFoundError: No module named 'kivy'
```

**Comment by matham** [comment]
Well, there's no reason to install the DMG over using pip, except to package the app. But, this issue is about using using the DMG.

For help with kivy install issues, please ask on discord.

**Comment by EricoCartmanez** [comment]
Anyway, thank you I really thought this would be easier but I'm straggling two days now only to get started...

**Comment by EricoCartmanez** [comment]
So I managed it to work again but still NO PREVIEW WINDOW opening. What am I missing? Should it work right away or is there extra work to be done?

```
[INFO   ] [Logger      ] Record log in /Applications/Kivy3.app/Contents/Resources/.kivy/logs/kivy_20-11-19_2.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.5 (default, Jun  1 2019, 17:33:32)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
[INFO   ] [Python      ] Interpreter at "/Applications/Kivy3.app/Contents/Resources/python"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
```

**Comment by EricoCartmanez** [comment]
So... It was a missing parenthesis in my code causing the preview not to open all along... 
`helloKivy.run()`

It didn't have to do with kivy version, or python3 version.

**Comment by EricoCartmanez** [comment]
After installing python 3.6.5 as default version I was able to install kivy from inside Pycharm
![Screenshot 2020-11-19 at 23 42 35](https://user-images.githubusercontent.com/37179870/99727684-040dcc80-2ac1-11eb-8cb1-2006a5c6bee9.png)
