### ISSUE TITLE
RecycleView renders `viewclass` instance before setting its properties

### ISSUE THREAD

**Issue by damienflament** [kivy/kivy#6308]
### Versions

* Python: 3.7.3
* OS: ArchLinux (kernel 5.0.11)
* Kivy: 1.11.0.dev0 (4e8ddda)
* Kivy installation method: Poetry (pip) using Git repository

### Description

Using an `ObjectProperty` property within a widget usually works as soon as the `ObjectProperty` is initialized.

But the `RecycleView` seems to render the `viewclass` instance before it is fully initialized. It results in an error because the `ObjectProperty` is not set.

The obvious fix is to check for `None` on the `ObjectProperty`:

```yaml
    <EntityView>:
        Label:
            text: root.entity.prop if root.entity else ""
```

But it is cumbersome to do it on every property use. Moreover, the behavior is not usual.

### Code and Logs

```python
from kivy.app import App
from kivy.event import EventDispatcher
from kivy.lang import Builder
from kivy.properties import ObjectProperty, StringProperty
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label
from kivy.uix.recycleview import RecycleView

kv = r"""
BoxLayout:
    orientation: "vertical"

    FooEntityView:

    EntitiesView:
        viewclass: "EntityView"

        RecycleBoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: self.minimum_height
            default_size_hint: 1, None

<EntityView>:
    Label:
        text: root.entity.prop

"""


class Entity(EventDispatcher):
    prop = StringProperty()


class EntityView(BoxLayout):
    entity = ObjectProperty(baseclass=Entity)


class FooEntityView(EntityView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.entity = Entity(prop="Foo")


class EntitiesView(RecycleView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.data = [
            {"entity": Entity(prop=value)}
            for value in ["Bar", "Baz", "BarBaz", "BazBar"]
        ]


class RVEntityApp(App):
    def build(self):
        return Builder.load_string(kv)


def main():
    RVEntityApp().run()


if __name__ == "__main__":
    main()
```

```
Traceback (most recent call last):
   File "/home/damien/.cache/pypoetry/virtualenvs/kivy-sandbox-py3.7/src/kivy/kivy/lang/builder.py", line 249, in create_handler
     return eval(value, idmap), bound_list
   File "<string>", line 18, in <module>
 AttributeError: 'NoneType' object has no attribute 'prop'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/damien/.cache/pypoetry/virtualenvs/kivy-sandbox-py3.7/src/kivy/kivy/lang/builder.py", line 692, in _apply_rule
     rctx['ids'])
   File "/home/damien/.cache/pypoetry/virtualenvs/kivy-sandbox-py3.7/src/kivy/kivy/lang/builder.py", line 254, in create_handler
     cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 18:
 ...
      16:<EntityView>:
      17:    Label:
 >>   18:        text: root.entity.prop
      19:
 ...
 AttributeError: 'NoneType' object has no attribute 'prop'
   File "/home/damien/.cache/pypoetry/virtualenvs/kivy-sandbox-py3.7/src/kivy/kivy/lang/builder.py", line 249, in create_handler
     return eval(value, idmap), bound_list
   File "<string>", line 18, in <module>
```

**Comment by matham** [comment]
>But it is cumbersome to do it on every property use. Moreover, the behavior is not usual.

It's true that this is annoying to check, but this behavior is in fact the usual behavior. The reason you didn't observe it outside recycle view is that you probably set the `entity` to something besides `None` before the kv rules are applied.

I have tried thinking of ways to allow doing the `root.entity.prop if root.entity else ""` dance in kv more succinctly, but couldn't see a way. Even python doesn't have this syntax, which comes up in request periodically (e.g. https://www.python.org/dev/peps/pep-0505/).

**Comment by damienflament** [comment]
@matham 
> you probably set the entity to something besides None **before the kv rules are applied**

As shown in the code sample, the `entity` property is set in the `__init__` of `FooEntityView` as well as in the `__init__` of the `EntitiesView` (through the `data` of the `RecycleView`).

So, if I understand correctly:

 1) the `FooEntityView` is initialized,
 2) the kv rules are applied,
 3) the `EntityView` instances are initialized by the `RecycleView`.

How to initialize the `viewclass` instances of a `RecycleView` before the kv rules are applied ?

Thanks.

**Comment by matham** [comment]
You need to set `self.entity = Entity(prop="Foo")` before calling super. You'll also need to set `entity = ObjectProperty(baseclass=Entity)` rebind to True, otherwise it won't rebind when `entity` is replaced..

For further help, please ask on the discord channel because we use github purely for bug reports (https://kivy.org/doc/master/contact.html).
