### ISSUE TITLE
kivy-examples: Text labels randomly nearly transparent, barely visible

### ISSUE THREAD

**Issue by dheller1** [kivy/kivy#6318]
### Versions

* Python: 3.7.2 32bit
* OS: Windows 10
* Kivy: v1.10.1
* Kivy installation method: pip install kivy

### Description

I followed the tutorial to create the Pong example.
Everything works nicely except for one thing:
Sometimes when I run the script, the score labels are ~~missing~~ nearly transparent so you can hardly see them at all. Sometimes, only one of the two is displayed properly. Sometimes, both are displayed just fine.
In some cases the labels are fixed to their proper color after the corresponding player scores and thus the text is changed.

To ensure I did nothing wrong; I downloaded the examples (pip install kivy_examples) and ran the script from share/kivy-examples/tutorial/pong/main.py - but the issue was the same.

I made a video, in this run both labels were "missing" initially but they appeared after the players scored.
I can ensure I made no changes to the example files at all, I even updated my graphics driver and tried again, but to no avail.

I've made a short video demonstrating the issue:
https://imgur.com/6KLSaV1

### Code and Logs

[INFO   ] Logger: Record log in C:\Users\hasu\.kivy\logs\kivy_19-05-18_47.txt
[INFO   ] Kivy: v1.10.1
[INFO   ] Python: v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.6.13547 Compatibility Profile Context 25.20.15031.1000'>
[INFO   ] GL: OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] GL: OpenGL renderer <b'AMD Radeon (TM) R9 390 Series'>
[INFO   ] GL: OpenGL parsed version: 4, 6
[INFO   ] GL: Shading version <b'4.60'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Leaving application in progress...

**Comment by dheller1** [comment]
Having just written this, I noticed that the labels **are** actually visible, but in a font which is so dark that you can hardly notice them. If you squint your eyes you can even see it in the video.
I'm noticing this behavior in many other examples as well, check for example this screenshot from the textalign demo:
![image](https://user-images.githubusercontent.com/10746183/57974726-5e563a80-79bd-11e9-9aed-c23ab8412619.png)
Here, the text in the grey buttons at the bottom is barely readable as well.

**Comment by sao12** [comment]
I have the same problem with transparent text: https://stackoverflow.com/q/56202685/11480854

**Comment by matham** [comment]
It may be due to https://github.com/kivy/kivy/pull/6312. Can you either try with current master, or downgrade kivy.deps.sdl2 to an older version and see if it fixes it?

**Comment by sao12** [comment]
Thank you, @matham!  I have installed version 0.1.18.

**Comment by matham** [comment]
So did that fix the issue?

**Comment by dheller1** [comment]
@matham installing kivy.deps.sdl2==0.1.18 fixed the issue for me. Thanks for the quick help.
