### ISSUE TITLE
Python Video app will not play  video - Reports img_pil, img_ffpyplayer ignored

### ISSUE THREAD

**Issue by logindwmartin** [kivy/kivy#6321]
# File name: video.py
import kivy
import os
os.environ["KIVY_VIDEO"] = 'ffplayer'
kivy.kivy_options['video']
kivy.require('1.9.0')

from kivy.uix.video import Video as KivyVideo
from kivy.properties import ObjectProperty
from kivy.properties import StringProperty

from kivy.factory import Factory
from kivy.lang import Builder

from subtitles import Subtitles

Builder.load_file('video.kv')
Builder.load_file('subtitle.kv')

class Video(KivyVideo):
    image = ObjectProperty(None)
    surl = StringProperty(None)

    def on_state(self, instance, value):
        if self.state == 'play':
            self.cover.opacity = 0
        elif self.state == 'stop':
            self.seek(0)
            self.cover.opacity = 1
        return super(self.__class__, self).on_state(instance, value)

    def on_image(self, instance, value):
        self.cover.opacity = 1

    def on_eos(self, instance, value):
        if value:
            self.state = 'stop'
    def _on_load(self, *largs):
        super(self.__class__, self)._on_load(largs)
        self.color = (1,1,1,1)

    def on_source(self, instance, value):
        self.color = (0, 0, 0, 0)
        self.subs = Subtitles(self.surl)
        self.sub = None

    def on_position(self, instance, value):
        next = self.subs.next(value)
        if next is None:
            self.clear_subtitle()
        else:
            sub = self.sub
            st = 'startTime'
            if sub is None or sub[st] != next[st]:
                self.display_subtitle(next)

    def clear_subtitle(self):
        if self.slabel.text != "":
            self.sub = None
            self.slabel.text = ""
            self.slabel.bcolor = (0.1, 0.1, 0.1, 0)

    def display_subtitle(self, sub):
        self.sub = sub
        self.slabel.text = sub['content']
        self.slabel.bcolor = (0.1, 0.1, 0.1, .8)

Factory.unregister('Video')
Factory.register('Video', cls=Video)

# File name: video.kv
#:kivy 1.9.0
#:set _default_video "http://video.ted.com/talk/stream/2004/None/DanGilbert_2004-180k.mp4"
#:set _default_image "http://images.ted.com/images/ted/016a827cc0757092a0439ab2a63feca8655b6c29_1600x1200.jpg"
#:set _default_surl "http://www.ted.com/talks/subtitles/id/97/lang/en"

<Video>:
    surl: _default_surl 
    slabel: _slabel
    cover: _cover
    image: _default_image
    allow_stretch: True
    color: 0,0,0,0
    source: _default_video

    AsyncImage:
        id: _cover
        source: root.image
        size: root.width,root.height

    Subtitle:
        id: _slabel
        x: (root.width - self.width)/2

### Versions

* Python:3.7
* OS:WIndows 10
* Kivy:1.10.1
* Kivy installation method:

### Description

 Program does not play the video?

### Code and Logs

K:\PYSRC\PythonBooster_CSV-master\venv\Scripts\python.exe "K:/PYSRC/KivyInteractiveApplicationsandGamesinPythonSecondEdition_Code/Chapter_06_code/03 - Subtitles - tracking the video progression/video.py"
[INFO   ] [Logger      ] Record log in C:\Users\Doug Martin\.kivy\logs\kivy_19-05-20_8.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)

Process finished with exit code 0

**Comment by matham** [comment]
`os.environ["KIVY_VIDEO"] = 'ffplayer'` should be `os.environ["KIVY_VIDEO"] = 'ffpyplayer'`

**Comment by logindwmartin** [comment]
The original prgorams did not have these lines, I adde them in attempt 
to get the prograsm to run.

import os
os.environ["KIVY_VIDEO"] = 'ffpyplayer'
kivy.kivy_options['video']

Even after changing ffplayer to ffpyplayer the log reports

K:\PYSRC\PythonBooster_CSV-master\venv\Scripts\python.exe "K:/PYSRC/KivyInteractiveApplicationsandGamesinPythonSecondEdition_Code/Chapter_06_code/03 - Subtitles - tracking the video progression/video.py"
[INFO   ] [Logger      ] Record log in C:\Users\Doug Martin\.kivy\logs\kivy_19-05-21_1.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)

Process finished with exit code 0

And the program never plays the video

Should I change  to ffpyplayer to video_ffpyplayer?

Best Wishes and Sincerely,

Doug Martin
doug.martin979@gmail.com
(317)432-8917 Cell

------ Original Message ------
