### ISSUE TITLE
[CRITICAL] [App         ] Unable to get a Window, abort.

### ISSUE THREAD

**Issue by talhaanwarch** [kivy/kivy#6342]
**Installation Method**
python -m pip install --upgrade pip wheel setuptools
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
python -m pip install kivy.deps.gstreamer
python -m pip install kivy.deps.angle
python -m pip install kivy

**Error**
Purge log fired. Analysing...
Purge finished!
[INFO   ] [Logger      ] Record log in C:\Users\Talha Anwar\.kivy\logs\kivy_19-05-30_8.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ImportError: DLL load failed: The specified module could not be found.
  File "C:\Anaconda3\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] [App         ] Unable to get a Window, abort.

Previous solution tried:
I tried uninstall anaconda and installing it again.
tried this one also 
python -m pip install kivy.deps.sdl2

**Comment by talhaanwarch** [comment]
I installed 3.6, but the error is still there

**Comment by matham** [comment]
We are in the middle of making a new release and the instructions are changing. Please do as follows, but I'd ask that you try the new wheels in a new clean virtual environment so there's no clash with previous kivy dependencies, or manually uninstall kivy and all it its deps with pip.

Here's complete instructions.

```sh
python -m pip install --upgrade pip setuptools wheel virtualenv
python -m virtualenv kivy_venv
```
If you're in windows cmd shell do:
```sh
kivy_venv\Scripts\activate
```
otherwise do:
```sh
source kivy_venv/Scripts/activate
```
Next do (note that to install the new kivy rc2 you need to add `--pre` to pip):
```sh
pip install kivy_deps.glew kivy_deps.sdl2 kivy_deps.gstreamer kivy kivy_examples --pre
python kivy_venv/share/kivy-examples/demo/kivycatalog/main.py
```

**Comment by hariharasudhand** [comment]
wow , works - thank you

**Comment by talhaanwarch** [comment]
how to do this on ubunto , i have tried the one listed here https://kivy.org/doc/stable/installation/installation.html
but that does not work
I tried the above one, but it says
-bash: kivy_venv/Scripts/activate: No such file or directory

Actually i am try buildozer and i have to move to ubunto. can you help please

**Comment by matham** [comment]
Please ask for support on Discord (https://kivy.org/doc/master/contact.html). We use github only for bug reports.

**Comment by Gaurav938612** [comment]
> We are in the middle of making a new release and the instructions are changing. Please do as follows, but I'd ask that you try the new wheels in a new clean virtual environment so there's no clash with previous kivy dependencies, or manually uninstall kivy and all it its deps with pip.
> 
> Here's complete instructions.
> 
> ```shell
> python -m pip install --upgrade pip setuptools wheel virtualenv
> python -m virtualenv kivy_venv
> ```
> 
> If you're in windows cmd shell do:
> 
> ```shell
> kivy_venv\Scripts\activate
> ```
> 
> otherwise do:
> 
> ```shell
> source kivy_venv/Scripts/activate
> ```
> 
> Next do (note that to install the new kivy rc2 you need to add `--pre` to pip):
> 
> ```shell
> pip install kivy_deps.glew kivy_deps.sdl2 kivy_deps.gstreamer kivy kivy_examples --pre
> python kivy_venv/share/kivy-examples/demo/kivycatalog/main.py
> ```

thank you a lot.you are really great .I had been trying for 2 days continuously in solving that.

**Comment by saravanan-92** [comment]
Hello @matham,
I've tried your commented reply for unable to get a window , abort error and it shows the same error. Even-though I run **kivy_venv/share/kivy-examples/demo/kivycatalog/main.py** this file from pc and the same error repeating...

What would be the solution?
My platforms are;
Windows 7 64-bit,
Python 3.6 32-bit,
and Kivy 1.11.1
