### ISSUE TITLE
Consistency issue

### ISSUE THREAD

**Issue by SiegelDaniel** [kivy/kivy#6360]
### Versions

* Python: 3.5+
* OS: Windows 10 x64, Ubuntu 16.04 x64
* Kivy: 1.90 +
* Kivy installation method: pip

### Description

Hello everyone,

Today I noticed a little consistency issue while reading the docs:
In Images, the filepath to the Image to be displayed is given as attribute source:
https://kivy.org/doc/stable/api-kivy.uix.image.html

Whilst in SVG, the sourcepath is given as attribute 'filename'

I propose this to be changed to either both filename or both source for the sake of consistency.
Thanks.

**Comment by crigaut** [comment]
I agree with @SiegelDaniel.

I think the best way is to change the SVG since the docs reference it as _highly experimental_: [https://kivy.org/doc/stable/api-kivy.graphics.svg.html](https://kivy.org/doc/stable/api-kivy.graphics.svg.html)

**Comment by tshirtman** [comment]
yeah, changing svg to use `source` instead of `filename` would be better, and it's a good time to do it as we go for the 2.0 release, a PR is welcome if you want to do it.
