### ISSUE TITLE
Use semantic versioning as of kivy 2.0.0

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#6366]
Hi,

maybe it makes sense to switch over to semantic versioning (https://semver.org/) as of kivy 2.0.0 to avoid version numbers like 1.11.0.post0.

Actually the pattern is simple -> major.minor.patch

From the website:

- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards-compatible manner, and
- PATCH version when you make backwards-compatible bug fixes.

This way in theory bugfix releases can be maintained long time after new major or minor releases while version numbers stay pretty

**Comment by Julian-O** [comment]
I believe this is being followed now, but there's no *action* to take in any case, so closing this off.
