### ISSUE TITLE
kivy camera example does not work on android

### ISSUE THREAD

**Issue by wangyuncong123** [kivy/kivy#6369]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description
I run the kivy camera example in windows and it works well. but when i use it in android(through buildozer).it crashed.

### Code and Logs
my buildozer.spec
requirements = kivy,plyer
android.permissions = CAMERA

my source code
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
camera2 = '''
BoxLayout:
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (640, 480)
        play: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
'''

class TestCamera(App):

    def build(self):
        return Builder.load_string(camera2)
TestCamera().run()

my log:
06-06 23:15:53.122  5657  5681 I python  : Initializing Python for Android
06-06 23:15:53.122  5657  5681 I python  : Setting additional env vars from p4a_env_vars.txt
06-06 23:15:53.122  5657  5681 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
06-06 23:15:53.122  5657  5681 I python  : /data/user/0/org.test.myapp/files/app
06-06 23:15:53.123  5657  5681 I python  : Preparing to initialize python
06-06 23:15:53.123  5657  5681 I python  : _python_bundle dir exists
06-06 23:15:53.123  5657  5681 I python  : calculated paths to be...
06-06 23:15:53.123  5657  5681 I python  : /data/user/0/org.test.myapp/files/app/_python_bundle/stdlib.zip:/data/user/0/org.test.myapp/files/app/_python_bundle/modules
06-06 23:15:53.124  5657  5681 I python  : set wchar paths...
06-06 23:15:53.298  5657  5681 I python  : Initialized python
06-06 23:15:53.299  5657  5681 I python  : AND: Init threads
06-06 23:15:53.301  5657  5681 I python  : testing python print redirection
06-06 23:15:53.307  5657  5681 I python  : Android path ['.', '/data/user/0/org.test.myapp/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.test.myapp/files/app/_python_bundle/modules', '/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages']
06-06 23:15:53.308  5657  5681 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin', 'DOWNLOAD_CACHE': '/data/cache', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/legacy-test.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/mediatek-ims-common.jar:/system/framework/mediatek-telecom-common.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar', 'ANDROID_SOCKET_zygote': '8', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/user/0/org.test.myapp/files/app', 'ANDROID_APP_PATH': '/data/user/0/org.test.myapp/files/app', 'ANDROID_PRIVATE': '/data/user/0/org.test.myapp/files', 'ANDROID_UNPACK': '/data/user/0/org.test.myapp/files/app', 'PYTHONHOME': '/data/user/0/org.test.myapp/files/app', 'PYTHONPATH': '/data/user/0/org.test.myapp/files/app:/data/user/0/org.test.myapp/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'landscape', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
06-06 23:15:53.308  5657  5681 I python  : Android kivy bootstrap done. __name__ is __main__
06-06 23:15:53.308  5657  5681 I python  : AND: Ran string
06-06 23:15:53.308  5657  5681 I python  : Run user program, change dir and execute entrypoint
06-06 23:15:53.787  5657  5681 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.myapp/files/app/.kivy/logs/kivy_19-06-06_1.txt
06-06 23:15:53.788  5657  5681 I python  : [INFO   ] [Kivy        ] v1.11.0
06-06 23:15:53.789  5657  5681 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
06-06 23:15:53.790  5657  5681 I python  : [INFO   ] [Python      ] v3.7.1 (default, Jun  3 2019, 09:46:42) 
06-06 23:15:53.790  5657  5681 I python  : [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
06-06 23:15:53.791  5657  5681 I python  : [INFO   ] [Python      ] Interpreter at "android_python"
06-06 23:15:56.176  5657  5681 I python  : [INFO   ] [Factory     ] 184 symbols loaded
06-06 23:15:57.485  5657  5681 I python  : [INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.2.0.dev0
06-06 23:15:57.490  5657  5681 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_ffpyplayer, img_gif (img_pil ignored)
06-06 23:15:57.725  5657  5681 I python  : [INFO   ] [Window      ] Provider: sdl2
06-06 23:15:57.802  5657  5681 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
06-06 23:15:57.807  5657  5681 I python  : [INFO   ] [GL          ] Backend used <sdl2>
06-06 23:15:57.810  5657  5681 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 58bf738'>
06-06 23:15:57.812  5657  5681 I python  : [INFO   ] [GL          ] OpenGL vendor <b'ARM'>
06-06 23:15:57.813  5657  5681 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Mali-400 MP'>
06-06 23:15:57.814  5657  5681 I python  : [INFO   ] [GL          ] OpenGL parsed version: 2, 0
06-06 23:15:57.815  5657  5681 I python  : [INFO   ] [GL          ] Texture max size <4096>
06-06 23:15:57.817  5657  5681 I python  : [INFO   ] [GL          ] Texture max units <8>
06-06 23:15:57.868  5657  5681 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
06-06 23:15:57.871  5657  5681 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
06-06 23:15:58.310  5657  5681 I python  : [INFO   ] [Camera      ] Provider: android
06-06 23:15:58.346  5657  5681 I python  : [INFO   ] [Text        ] Provider: sdl2
06-06 23:15:58.758  5657  5681 I python  :  Traceback (most recent call last):
06-06 23:15:58.759  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/lang/builder.py", line 700, in _apply_rule
06-06 23:15:58.761  5657  5681 I python  :    File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
06-06 23:15:58.762  5657  5681 I python  :    File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
06-06 23:15:58.764  5657  5681 I python  :    File "kivy/properties.pyx", line 839, in kivy.properties.ListProperty.set
06-06 23:15:58.766  5657  5681 I python  :    File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
06-06 23:15:58.768  5657  5681 I python  :    File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
06-06 23:15:58.769  5657  5681 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
06-06 23:15:58.771  5657  5681 I python  :    File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
06-06 23:15:58.773  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/uix/camera.py", line 103, in _on_index
06-06 23:15:58.774  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/core/camera/camera_android.py", line 42, in __init__
06-06 23:15:58.776  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/core/camera/__init__.py", line 70, in __init__
06-06 23:15:58.778  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/core/camera/camera_android.py", line 49, in init_camera
06-06 23:15:58.780  5657  5681 I python  :    File "jnius/jnius_export_class.pxi", line 1044, in jnius.jnius.JavaMultipleMethod.__call__
06-06 23:15:58.782  5657  5681 I python  :    File "jnius/jnius_export_class.pxi", line 765, in jnius.jnius.JavaMethod.__call__
06-06 23:15:58.784  5657  5681 I python  :    File "jnius/jnius_export_class.pxi", line 931, in jnius.jnius.JavaMethod.call_staticmethod
06-06 23:15:58.785  5657  5681 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
06-06 23:15:58.787  5657  5681 I python  :  jnius.jnius.JavaException: JVM exception occurred: Fail to connect to camera service
06-06 23:15:58.788  5657  5681 I python  :  
06-06 23:15:58.789  5657  5681 I python  :  During handling of the above exception, another exception occurred:
06-06 23:15:58.789  5657  5681 I python  :  
06-06 23:15:58.790  5657  5681 I python  :  Traceback (most recent call last):
06-06 23:15:58.791  5657  5681 I python  :    File "/home/wyc/.buildozer/android/app/main.py", line 26, in <module>
06-06 23:15:58.795  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/app.py", line 829, in run
06-06 23:15:58.797  5657  5681 I python  :    File "/home/wyc/.buildozer/android/app/main.py", line 23, in build
06-06 23:15:58.799  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/lang/builder.py", line 405, in load_string
06-06 23:15:58.801  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/lang/builder.py", line 707, in _apply_rule
06-06 23:15:58.803  5657  5681 I python  :  kivy.lang.builder.BuilderException: Parser: File "<inline>", line 6:
06-06 23:15:58.803  5657  5681 I python  :  ...
06-06 23:15:58.804  5657  5681 I python  :        4:    Camera:
06-06 23:15:58.805  5657  5681 I python  :        5:        id: camera
06-06 23:15:58.806  5657  5681 I python  :  >>    6:        resolution: (640, 480)
06-06 23:15:58.807  5657  5681 I python  :        7:        play: False
06-06 23:15:58.807  5657  5681 I python  :        8:    ToggleButton:
06-06 23:15:58.808  5657  5681 I python  :  ...
06-06 23:15:58.809  5657  5681 I python  :  JavaException: JVM exception occurred: Fail to connect to camera service
06-06 23:15:58.810  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/lang/builder.py", line 700, in _apply_rule
06-06 23:15:58.810  5657  5681 I python  :    File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
06-06 23:15:58.811  5657  5681 I python  :    File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
06-06 23:15:58.812  5657  5681 I python  :    File "kivy/properties.pyx", line 839, in kivy.properties.ListProperty.set
06-06 23:15:58.813  5657  5681 I python  :    File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
06-06 23:15:58.813  5657  5681 I python  :    File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
06-06 23:15:58.814  5657  5681 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
06-06 23:15:58.815  5657  5681 I python  :    File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
06-06 23:15:58.816  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/uix/camera.py", line 103, in _on_index
06-06 23:15:58.817  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/core/camera/camera_android.py", line 42, in __init__
06-06 23:15:58.818  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/core/camera/__init__.py", line 70, in __init__
06-06 23:15:58.819  5657  5681 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/kivy/core/camera/camera_android.py", line 49, in init_camera
06-06 23:15:58.819  5657  5681 I python  :    File "jnius/jnius_export_class.pxi", line 1044, in jnius.jnius.JavaMultipleMethod.__call__
06-06 23:15:58.820  5657  5681 I python  :    File "jnius/jnius_export_class.pxi", line 765, in jnius.jnius.JavaMethod.__call__
06-06 23:15:58.821  5657  5681 I python  :    File "jnius/jnius_export_class.pxi", line 931, in jnius.jnius.JavaMethod.call_staticmethod
06-06 23:15:58.822  5657  5681 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
06-06 23:15:58.823  5657  5681 I python  :  
06-06 23:15:58.823  5657  5681 I python  : Python for android ended.

**Comment by vadimk2016** [comment]
Kivy on android plays only mp4 files Kivy android do not work with stream video.

**Comment by mabelcalim** [comment]
Try to change resolution: (640, 480) for resolution: self.resolution.

**Comment by mabelcalim** [comment]
Try this one: https://github.com/AndreMiras/PyWallet/issues/129#issuecomment-475065998
It's works for me ;)

**Comment by yamwengwei** [comment]
Hi, may I know how you run the kivy camera example in windows as I cannot run it in windows. Thanks!

**Comment by fs-melo** [comment]
@yamwengwei, add opencv-python at your virtual environment :+1: 

pip install opencv-python

**Comment by fs-melo** [comment]
@yamwengwei, add opencv-python at virtual environment 

pip install opencv-python 

It's works for me

**Comment by fs-melo** [comment]
You can do in buildozer.spec:

\# (list) Application requirements 
requirements = kivy, plyer #only

\# (str) Android NDK version to use
\#android.ndk = 10.3.2

\# (str) Android NDK directory (if empty, it will be automatically downloaded.)
\#android.ndk_path =

This will dowload NDK 9c (standard NDK version for Buildozer).
It's works for me.

**Comment by miltosVar** [comment]
@fs-melo  hi! I can't find the solution for this problem, I have tried many codes but nothing worked for laptop and android.Can you provide a simple full code example in which the camera works fine?

**Comment by fs-melo** [comment]
Hi @miltosVar !

Laptop and desktop need some packages.
The camera only works in Android if use NDK 9c version (in buildozer.spec file).
 
If you use Kivy in virtualenv activate it first.
Then run in terminal:
```
pip install ffpyplayer
export KIVY_VIDEO=ffpyplayer
pip install plyer
pip install opencv-python

```
Run in terminal:
`buildozer android debug`


main.py
```
from kivy.app import App
from kivy.lang import Builder


kv = '''
BoxLayout:
    orientation: 'vertical'
    size: root.size
    
    Camera:
        id: camera
        resolution: (720,1280)
        play: False
        canvas.before:
            PushMatrix
            Rotate:
                angle: -90
                origin: self.center
        canvas.after:
            PopMatrix
            
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
'''


class TestCamera(App):

    def build(self):
        return Builder.load_string(kv)


TestCamera().run()
```

buildozer.spec
```
[app]

# (str) Title of your application
title = Camera Kivy Example

# (str) Package name
package.name = camerakivy

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
#requirements = python3crystax==3.6, kivy, plyer
requirements = kivy, plyer


# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/cam.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.11.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = CAMERA

# (int) Android API to use
#android.api = 19

# (int) Minimum API required
#android.minapi = 9

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 10.3.2

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path = ~/cristax/crystax-ndk-10.3.2

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (str) python-for-android branch to use, defaults to stable
#p4a.branch = stable

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```
It's works fine for me.

**Please, tell me if it worked well for you.**

> @fs-melo hi! I can't find the solution for this problem, I have tried many codes but nothing worked for laptop and android.Can you provide a simple full code example in which the camera works fine?

**Comment by miltosVar** [comment]
@fs-melo Tnank you, your example is great! My problem was, maybe, the NDK version.

**Comment by fs-melo** [comment]
Anytime!

**Comment by fs-melo** [comment]
Now we have another problem: The camera stays very small  on the Android screen, when compile with buildozer.

I believe there is a fail in the file: `python3.6/site-packages/kivy/core/camera/camera_android.py`.

**Comment by FranMartiarena** [comment]
> Now we have another problem: The camera stays very small on the Android screen, when compile with buildozer.
> 
> I believe there is a fail in the file: `python3.6/site-packages/kivy/core/camera/camera_android.py`.

Same issue, any solution??

**Comment by fs-melo** [comment]
> > Now we have another problem: The camera stays very small on the Android screen, when compile with buildozer.
> > I believe there is a fail in the file: `python3.6/site-packages/kivy/core/camera/camera_android.py`.
> 
> Same issue, any solution??

No friend.
The canvas method causes the camera very small on the Android screen.

The camera example works in NDK 9c, but the image appears rotated (90°).

The `/kivy/core/camera/camera_android.py` file needs of fix. Kivy 1.11.1 and 2.0(dev) still show the issue.

**Comment by fs-melo** [comment]
Issue #6369 is related to the SDK / NDK version. Camera Kivy still works with `ANDROID_SDK_VERSION = '20'` and ` ANDROID_NDK_VERSION = '9c'`

**Comment by fs-melo** [comment]
Hi!
Has anyone succeed to replicate the colour-blind-camera app?

**Comment by fs-melo** [comment]
Hi!
Is need add runtime permissions before call Camera API.

With API level >= 21, you will need to **[request runtime permissions](https://python-for-android.readthedocs.io/en/latest/apis/#runtime-permissions)** to access the SD card, 
the CAMERA, and other things.

I do this similar to [xcamera](https://github.com/AndreMiras/xcamera) in [xcamera.py](https://github.com/AndreMiras/xcamera/blob/develop/src/kivy_garden/xcamera/xcamera.py).

**Comment by cristianmejiaarias** [comment]
Hello you should to add this in you buildozer.spec

android.permissions = INTERNET,CAMERA
