### ISSUE TITLE
I have proposition that can help a lot of devloper to fix there errors 

### ISSUE THREAD

**Issue by bahaeelhmimdi** [kivy/kivy#6380]
I want to be heard .i want just the proof that the solution i give be saved at my name .it can help a lot of developers .like (logcat) for debugging i want make proposition for another way to find out the errors it very easy

**Comment by matham** [comment]
Please see https://kivy.org/doc/stable/contribute.html how to contribute to kivy. To answer the question, if you follow our git flow, your name will be part of the git commit and that is how you'd get credit for your work.

For the future, we use github issues specifically for bug reports and feature requests only. You can contact us on discord for other issues.
