### ISSUE TITLE
 Can not install kivy, help

### ISSUE THREAD

**Issue by andriiko489** [kivy/kivy#6387]
### Versions

* Python: 3.7.3
* OS: Windows 7 64 bit
* Kivy: newest
* Kivy installation method: https://kivy.org/doc/stable/installation/installation-windows.html

### Description

I tried to install kivy and nothing happened to me. Then I deleted all the versions of the Python that I had and downloaded the latest. And then try to do everything by instructions and I did not succeed
https://imgur.com/a/KZtTM0t

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by TTFISHDES** [comment]
https://kivy.org/#download

With this, you will be the world handsome.
