### ISSUE TITLE
GL Error 1282 with SmoothLinePlot

### ISSUE THREAD

**Issue by Inspirateur** [kivy/kivy#6393]
### Versions

* Python: 3.7
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: pip

### Description
I'm trying to do real time plots in kivy with the `kivy_garden.graph` module, my code works fine with `MeshLinePlot` however when I try to use `SmoothLinePlot` instead it crashes with:
```
[ERROR  ] [Shader      ] <fragment> failed to compile (gl:1282)
```
when I try to add the graph to the plot.

### Code and Logs
```python
def set_plots(self, labels: List[str]):
	# for now we statically initialize the plots (no plots will be added in add)
	self.clear()
	for i, label in enumerate(labels):
		miny = i / len(labels)
		# FIXME: we should use SmoothLinePlot instead but it raises a GL Error 1282
		self.plots[label] = RTPlot(
			MeshLinePlot(color=self.next_color()), self.keep, miny, miny+1/len(labels)
		)
		self.graph.add_plot(self.plots[label].plot)
```
Here `RTPlot` is just a wrapper that helps me update the Plot in real time.
keep and miny are just used to arrange my plots in the graph space.

**Comment by Inspirateur** [comment]
better title

**Comment by matham** [comment]
This issue belongs in the kivy_garden.graph repo, not in kivy itself. Also, when you open a issue, please provide the minimum fully-runable example.
