### ISSUE TITLE
ArgumentError: argument 3: <class 'TypeError'>: wrong typeargument 3: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by subratksahoo** [kivy/kivy#6394]
While running the below code second time getting ArgumentError: argument 3: <class 'TypeError'>: wrong type

from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()

**Comment by matham** [comment]
Please provide the full and complete log and all the information requested in the template when you opened the issue.
