### ISSUE TITLE
Kivy has no version numbers on macOS

### ISSUE THREAD

**Issue by core-code** [kivy/kivy#6401]
<img width="495" alt="Screenshot 2019-06-25 at 19 54 35" src="https://user-images.githubusercontent.com/1261954/60121356-293ec400-9783-11e9-9039-e66a9afed0f5.png">

Your Info.plist file is missing proper entries for the CFBundleShortVersionString and CFBundleVersion entries

**Comment by misl6** [comment]
The latest Kivy release: https://kivy.org/downloads/2.1.0 ships with the proper version.
Feel free to re-open if you're still encountering the issue.

**Comment by core-code** [comment]
thanks, `CFBundleShortVersionString` is confirmed fixed
