### ISSUE TITLE
MacOS PopUp in wrong location, Filechooser format issue

### ISSUE THREAD

**Issue by ElliotGarbus** [kivy/kivy#6407]
### Versions

* Python: 3.73
* OS: MacOS Mojave 10.14.5
* Kivy: 1.11.1
* Kivy installation method: pip installed per directions on website:
python3 -m pip install kivy

### Description

On mac the Popup window is coming up in the wrong location.  Same code works fine on Windows under Kivy 1.11.1.  The lines of the filechooser are not properly formatted.

The popup window initially comes up in the lower left corner of the window.  It repositions correctly when the window resized to full size.  

The filechooser line items (directories or files) are taking up 2 lines, instead of one.
Pictures attached.
<img width="912" alt="Screen Shot 2019-07-05 at 6 36 18 PM" src="https://user-images.githubusercontent.com/39632979/60749806-4e39f080-9f54-11e9-9ac8-9f804955dd9d.png">
![Screen Shot 2019-07-05 at 6 37 06 PM](https://user-images.githubusercontent.com/39632979/60749810-60b42a00-9f54-11e9-9218-b097d174c75d.png)

### Code and Logs

```python

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.popup import Popup
from kivy.properties import StringProperty, ListProperty
from kivy.lang import Builder

kv = '''
#: import Factory kivy.factory.Factory
#: import pathlib pathlib

TestBox:
    orientation: 'vertical'
    BoxLayout:
        size_hint_y: None
        height: '40dp'
        Button:
            text: 'Test Load'
            on_release:
                Factory.LoadDialog(title='Load the file this is just a test', path = '.', filters = ['*.pdf']).open()
        
<LoadDialog>:
    auto_dismiss: False
    size_hint: .6,.75
    BoxLayout:
        orientation: 'vertical'
        FileChooserListView:
            id: fc
            filters: root.filters
            # path: app.config.get(md.device_name, 'lib_dir' )
            path: root.path
        BoxLayout:
            size_hint_y: .1
            Spinner:
                text:'Drive'
                values: ['D1:', 'D2:']  # drivepath.get_drive_names()
                # on_text: fc.path = drivepath.get_path(self.text)
            Label:
                text_size: self.size
                halign: 'center'
                valign: 'center'
                shorten: True
                text: 'File: ' + ('<None>' if not fc.selection else pathlib.Path(fc.selection[0]).name)
        BoxLayout:
            size_hint_y: .1
            orientation: 'horizontal'
            Button:
                text: 'Load'
                disabled: 0==len(fc.selection)
                on_release:
                    # app.load_presets(fc.selection[0])
                    print(f'File Selected: {fc.selection[0]}')
                    root.dismiss()
            Button:
                text: 'Cancel'
                on_release: root.dismiss()
'''


class LoadDialog(Popup):
    filters = ListProperty()
    path = StringProperty()

    def __init__(self, **kwargs):
        self.filters = kwargs['filters']
        self.path = kwargs['path']
        super().__init__(**kwargs)


class TestBox(BoxLayout):
    pass


class FCTest(App):

    def build(self):
        return Builder.load_string(kv)


if __name__ == '__main__':
    FCTest().run()

**Comment by ElliotGarbus** [comment]
I have root caused this issue and will open a new issue with the solution and a PR

**Comment by YaanTzik** [comment]
I was able to get kivy file chooser to show up in the middle using the pos_hint function like this 
self._popup = Popup(title="Load file", content=content,
                            size_hint=(.9,.9),pos_hint= {"center_x":0.5,"center_y":.5})
cant figure out the double line on Mac and trying to work through it now
