### ISSUE TITLE
Why Button.color means Button.font.color in (only) Kivy?

### ISSUE THREAD

**Issue by prabhatM** [kivy/kivy#6409]
Windows introduced 3D widgets in Windows'95. Since then all IDE's have defined "Button.color" as  'tinting' of the button, NOT the color of the text as in Kivy.

This is unintuitive.  Why make it difficult for  the users/developers/designers ?

In RadioButton and CheckBox, CheckBox.color means "tinting", then why not in Button?

If you can offer background color/image for CheckBox, then why not for Labels?

With a CheckBox, the user must be concerned with the event "on_click" only, Why must he write a special class "on_active" and then bind ?

Please make Kivy like what FLASH used to be for all of us. Flash had Action Script, Kivy has Python. Make Kivy naturally user friendly and it will grab the space vacated by FLASH.

**Comment by gottadiveintopython** [comment]
`Button` is derived from `Label`, so the `color` property should be the same as Label's

**Comment by matham** [comment]
I agree that it can be confusing, however, we cannot change this as it would break backward compat. The reason why color is the font color, is that it inherits from Label.
