### ISSUE TITLE
Logger cannot handle Unicode Characters

### ISSUE THREAD

**Issue by DanTheMan2000** [kivy/kivy#6423]
# Versions

* Python: v3.7.3 
* OS: Linux
* Kivy: v1.11.1

### Description
Found issue where Kivy's logger does not handle unicode, it causes Kivy to crash. I have proposed a solution below.

```python
import logging
from kivy.app import App
from kivy.config import Config
from kivy.uix.boxlayout import BoxLayout

# Configure Logging Settings
log_enabled = Config.getint('kivy', 'log_enable')
if log_enabled != 1:
    Config.set('kivy', 'log_enable', '1')
    Config.write()

logger = logging.getLogger()


class TestApp(App):

    def build(self):
        b = BoxLayout()
        logger.info('Main: This works')
        logger.info('Main: this crashes 你好')
        return b


TestApp().run()
```

The solution is to change line 218 in logger.py to:
```
            try:
                stream.write(fs % msg)
            except UnicodeEncodeError:
                stream.write(fs % msg.encode("UTF-8"))
```

**Comment by sonnyky** [comment]
I just ran into this issue myself, working on a pull request now

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/6910 should have fixed this in master.

**Comment by sonnyky** [comment]
I double checked on master, in the file logger.py, line 226:
`

        def _write_message(self, record):
                if FileHandler.fd in (None, False):
                      return

                msg = self.format(record)
                stream = FileHandler.fd
                fs = "%s\n"
                stream.write('[%-7s] ' % record.levelname)
                stream.write(fs % msg)
                stream.flush()
`

Here, the stream.write is not encoded.
I think this is what is causing the issues, The line number is different from the original issue because there has been other fixes too, but this part remains unresolved.

**Comment by sonnyky** [comment]
Ah, I think I know where the discrepancy is. I'm using PyCharm and its package manager installs Kivy version 1.11.1, while 2.0.0 are still in rc.
So I got the 1.11.1 version which has a totally different _write_message function and still has the bug mentioned in this issue.

However, I cannot seem to upgrade my Kivy version from 1.11.1, but this is a different issue.

@matham 
I still think the write line needs an encoding like msg.encode(FileHandler.encoding).
What do you think?

**Comment by matham** [comment]
>I still think the write line needs an encoding like msg.encode(FileHandler.encoding).
What do you think?

With the fix, python does this automatically so we shouldn't need to do that.

As for how to install master, try `pip install kivy[base] kivy_examples --upgrade --pre --extra-index-url https://kivy.org/downloads/simple/`

**Comment by sonnyky** [comment]
@matham 
Thanks for clarifying, and I'll try the upgrade command
