### ISSUE TITLE
Kivy app working on desktop but not CLI ubuntu 18.04 RPi (Unable to find any valuable window provider)

### ISSUE THREAD

**Issue by 1DropDiag** [kivy/kivy#6437]
### Versions

* Python: 3.6.9
* OS: Ubuntu Mate 18.04
* Kivy: v2.0.0.dev0
* Kivy installation method: https://kivy.org/doc/stable/installation/installation-rpi.html

### Description

I've written a kivy app that works perfectly when launched from ubuntu mate desktop via a terminal window. However, if I boot into cli, the app cannot launch because it is unable to "find any valuable Window provider". The final goal would be to boot directly into the app when the RPi is started. I plan to do that by booting into cli and then launching my app as a service.

I'm running ubuntu mate 18.04 on a raspberry Pi 3B+ and using kivy to create my program. To make sure that the issue did not come from my script I reproduced the issue using the standard Hello world script from kivy.

Here is the message I get from when launching from cli (same script works perfectly from desktop):
 ```
### Code and Logs
(cv) droppi@droppi-desktop:~$ python test.py
[INFO   ] [Logger      ] Record log in /home/droppi/.kivy/logs/kivy_19-07-25_124.txt
[INFO   ] [Kivy        ] v2.0.0.dev0, git-Unknown, 20190724
[INFO   ] [Kivy        ] Installed at "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
[INFO   ] [Python      ] Interpreter at "/home/droppi/.virtualenvs/cv/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: b'No available video device'
  File "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/core/__init__.py", line 70, in core_select_lib
    cls = cls()
  File "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
    super(WindowSDL, self).__init__()
  File "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 983, in __init__
    self.create_window()
  File "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
    self.get_gl_backend_name())
  File "kivy/core/window/_window_sdl2.pyx", line 110, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/droppi/.virtualenvs/cv/lib/python3.6/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by HeyITGuyFixIt** [comment]
The CLI doesn't have an X-Window server available to it. It is purely for command line programs and actions. Running it from the terminal, you have the X-Window server running already; the desktop environment uses it to show you it's GUI, along with the GUI of the programs being run.

I would suggest researching how to start an application or script automatically when you login. See this Ubuntu documentation for one solution: https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html.en At the very least, it would be a good place to begin some research.

Unless I am understanding this issue wrong, this isn't an issue with Kivy, but rather a simple misunderstanding of how Linux works.
