### ISSUE TITLE
setup.py syntax error for python 2.7

### ISSUE THREAD

**Issue by ibobalo** [kivy/kivy#6438]
### Versions

* Python 2.7.12:
* OS: Lubuntu 16.4 LTS:
* Kivy: latest from git
* Kivy installation method: setup.py build

### Description

kivy instalation with setup.py failed

### Code and Logs

```python
python -m setup.py build
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "setup.py", line 1020
    def glob_paths(*patterns, excludes=('.pyc', )):
                                     ^
SyntaxError: invalid syntax
```

**Comment by matham** [comment]
Kivy master (v2.0.0+) doesn't support python 2 anymore. https://github.com/kivy/kivy/wiki/Kivy-Python-2-Support-Timeline

**Comment by ibobalo** [comment]
yes, i know. there are error message about unsupported python 2 in setup.py. and imho expected behavior is to show this error message and exit with error code. instead of syntax error exception.

**Comment by OutsourcedGuru** [comment]
Personally, I'd expect that if you wanted Python2 to fall on its face then by all means do an early test in the build pipeline and let the user know. I don't really love putting in a half hour of my time chasing my tail on this one (with a closed issue search). I agree with ibobalo on this one.

**Comment by matham** [comment]
A syntax error happens when the file is imported, which means there's no way for us to raise any warning or exception when you try to import the file because you'll never see it, as it will always be preempted by the syntax error.
