### ISSUE TITLE
P4A Request permissions

### ISSUE THREAD

**Issue by ademirel** [kivy/kivy#6439]
### Versions

* Python:  3.6.8
* OS: Lubuntu 18.04
* Kivy: 1.11.1
* Kivy installation method: python3-pip

### Description

I used plyer.gps module in my application. Everything is ok. But after I add request permission for GPS at following, my application is crashing. When I execute my code from the terminal, it's giving "**no module named android**". But python-for-android was installed on the system.

[https://python-for-android.readthedocs.io/en/latest/apis/](https://python-for-android.readthedocs.io/en/latest/apis/)

### Code and Logs

**from android.permissions import request_permissions, Permission
request_permissions([Permission.ACCESS_COARSE_LOCATION])**

**Comment by Fak3** [comment]
1) This isssue is about p4a, please report such issues in p4a bugtracker: https://github.com/kivy/python-for-android/issues
2) Please provide example of your code and traceback indicating the error.

`android` module is installed into final android package (apk) by p4a only when you build your apk to be distributed on android platform, i.e with `p4a apk` command. If you just installed p4a in your linux environment, there would be no `android` module available. Furthermore, `android` module is only useful on android platform as it relies on Java API of the android platform. It will not work on linux desktop.
