### ISSUE TITLE
Empty result when using kivy.network.urlrequest

### ISSUE THREAD

**Issue by oliverk90** [kivy/kivy#6451]
I am using MacOS 10.15.5 with Python3.6 and Kivy 1.11.1. I have problems using **kivy.network.urlrequest**, as I sometimes don't get a result (result is empty). If I use the standard **requests** lib of python I get a result for the exact same link. See the attached code:

```
from kivy.network.urlrequest import UrlRequest
from kivy.clock import Clock
import requests
import time
link = "https://www.genius.com/Iron-Maiden-no-more-lies-lyrics"
request_kivy = UrlRequest(link)
while not request_kivy.is_finished:
    Clock.tick()
print("Len of kivy result is 0: ",len(request_kivy.result))
print("Len of standard result is 177536:",len(requests.get(link).text))
```

**Comment by ArthyChaux** [comment]
You need to set ```def open(req, result):
    print(result)

def fail(*args):
   print(failed)

UrlRequest(link, on_success=open, on_failure=fail)```
