### ISSUE TITLE
Creating packages for OS X directions broken (invalid homebrew flag)

### ISSUE THREAD

**Issue by OneOfMany07** [kivy/kivy#6452]
### Versions

* Python: 3.7.4
* OS: macOS 10.14.6
* Kivy: n/a
* Kivy installation method: n/a (hadn't installed yet, but was prepping related parts)

### Description
Following https://kivy.org/doc/stable/guide/packaging-osx.html

Step three is invalid, as the flag for homebrew doesn't exist anymore.  I don't know what to change here, so putting it to the community.

"... $ brew reinstall --build-bottle sdl2 sdl2_image sdl2_ttf sdl2_mixer
Usage: brew reinstall [options] formula

Uninstall and then install formula (with existing and any appended install
options).

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will be run for the
reinstalled formulae or, every 30 days, for all formulae.

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is available.
        --force-bottle               Install from a bottle if it exists for the
                                     current or newest version of macOS, even if
                                     it would not normally be used for
                                     installation.
        --keep-tmp                   Don't delete the temporary files created
                                     during installation.
    -f, --force                      Install without checking for previously
                                     installed keg-only or non-migrated
                                     versions.
    -v, --verbose                    Print the verification and postinstall
                                     steps.
        --display-times              Print install times for each formula at the
                                     end of the run.
    -h, --help                       Show this message.
Error: invalid option: --build-bottle"

**Comment by matham** [comment]
Maybe you need to explicitly uninstall and then install with the `--build-bottle` option? It sounds like the reinstall command doesn't accept `--build-bottle` as an option so you shouldn't use the `reinstall` command.

**Comment by gerard-hm** [comment]
`brew install --build-bottle sdl2 sdl2_image sdl2_ttf sdl2_mixer` seemed to work for me and worked just fine.

I never had `sdl2 sdl2_image sdl2_ttf sdl2_mixer` installed before, so that makes sense.

**Comment by misl6** [comment]
Closing as this issue has been fixed via https://github.com/kivy/kivy/pull/7392
