### ISSUE TITLE
kivy screen textiput focus

### ISSUE THREAD

**Issue by linpan** [kivy/kivy#6455]
I  add three screen, every screen have inputext(set focus True) but change screen,  focus not working, why ?

**Comment by Fak3** [comment]
Please post your question and provide example source code on any of the following communication channels:
    User Group : https://groups.google.com/group/kivy-users
    Email : kivy-users@googlegroups.com
    Chat Server : https://chat.kivy.org

This is a bug tracker, not a proper place to ask questions.
