### ISSUE TITLE
What do you mean by a few parent and ids here?

### ISSUE THREAD

**Issue by tianyi725** [kivy/kivy#6464]
### Versions

* Python:3.6
* OS:win7
* Kivy:1.10
* Kivy installation method:  pip

.kv file
`

> <<NumberButton@Button>>:
>         on_release: self.parent.parent.ids.calc_input.text += self.text
>         size_hint: None, None
>         font_size: self.parent.parent.button_font_size
>         width: self.parent.parent.button_width
>         height: self.parent.parent.button_height
> 
> <Calculator_Widget>:
>         RowLayout:
>             NumberButton:
>                 text: '1'
>             NumberButton:
>                 text: '2'
>             NumberButton:
>                 text: '3'

`

What do you mean by a few 'parent' and 'ids' here?
I don't know how to understand 'parent' and 'ids'
thank you!

In addition:
I put it here
Self.parent.parent.ids.calc_input.text + = self.text
Change into
Root.ids.calc_input.text + = self.text
or
Root.parent.parent.ids.calc_input.text + = self.text
Will it go wrong?

Because I have very few basic tutorials here.
And my English is not very good, so the long document on kivy.org looks a little hard.
(I don't know where the documentation has explanations for parent and ids)

So please help me explain what this means?
Thank you

**Comment by Fak3** [comment]
Please post your question and provide example source code on any of the following communication channels:
    User Group : https://groups.google.com/group/kivy-users
    Email : kivy-users@googlegroups.com
    Chat Server : https://chat.kivy.org

This is a bug tracker, not a proper place to ask questions.
