### ISSUE TITLE
datetime strftime  bugs

### ISSUE THREAD

**Issue by linpan** [kivy/kivy#6477]
in python3.6  ide:
> datetime.now().strftime('%Y年%m月%d日 %H:%M')
'2019年08月16日 14:23'
but in kivy  use `%Y年%m月%d日 %H:%M`  get nothing  ,
then  `datetime.now().strftime('%Y-%m-%d %H:%M')` is get datetime string.
why happens ? maybe is kivy bug

**Comment by linpan** [comment]
ps: use  Clock.schedule_interval(self.timer, 1) get datetime

**Comment by linpan** [comment]
hope reopen the issue

在 2019-08-16 21:47:31，"support[bot]" <notifications@github.com> 写道：


👋 We use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our support channels to get help with the project.

If you're having trouble installing Kivy, make sure to check out the installation docs for Windows, Linux and macOS.

Let us know if this comment was made in error, and we'll be happy to reopen the issue.

**Comment by andreisima** [comment]
As instructed before:
> Please post your question and provide example source code on any of the following communication channels:
User Group : https://groups.google.com/group/kivy-users
Email : kivy-users@googlegroups.com
Chat Server : https://chat.kivy.org
This is a bug tracker, not a proper place to ask questions.


This is not a Kivy bug
Here is a minimal example that will render a label with current date and time 

```python
from kivy.app import App
from datetime import datetime
from kivy.uix.label import Label


class MyApp(App):
    def build(self):
        self.now = datetime.now().strftime('%H:%M:%S')
        self.my_label = Label(text= self.now)
        return self.my_label

MyApp().run()
```

> but in kivy use %Y年%m月%d日 %H:%M get nothing ,

I am not sure what do you want with that.
And if i am not wrong that is simply a string substitution left in the wild.
For more info you can see:
[DateTime - strftime](https://github.com/python/cpython/blob/24fe46081be3d1c01b3d21cb39bc3492ab4485a3/Lib/datetime.py#L954)


> ps: use Clock.schedule_interval(self.timer, 1) get datetime

This is not how one uses Clock object

From [Kivy docs](https://kivy.org/doc/stable/api-kivy.clock.html):

```python
def my_callback(dt):
    # do stuff here
    pass

Clock.schedule_interval(my_callback, 0.5)
```

**Comment by linpan** [comment]
thanks your answer, your is okay , the key part is timestrf, datetime.now().strftime('%Y年%m月%d日 %H:%M')


you can run this spinnet:
from kivy.app import App

from datetime import datetime

from kivy.uix.label import Label





class MyApp(App):

def build(self):

self.now = datetime.now().strftime('%Y年%m月%d日 %H:%M')

self.my_label = Label(text= self.now)

return self.my_label



MyApp().run()


i do sure ,'%Y年%m月%d日 %H:%M' is corrent in python console can print datetime
>>> from datetime import datetime >>> datetime.now().strftime("%Y年%m月%d日") '2019\xe5\xb9\xb408\xe6\x9c\x8819\xe6\x97\xa5' >>> print (datetime.now().strftime("%Y年%m月%d日")) 2019年08月19日
林攀

At 2019-08-18 19:29:25, "Andrei Sima" <notifications@github.com> wrote:


As instructed before:

Please post your question and provide example source code on any of the following communication channels:
User Group : https://groups.google.com/group/kivy-users
Email : kivy-users@googlegroups.com
Chat Server : https://chat.kivy.org
This is a bug tracker, not a proper place to ask questions.

This is not a Kivy bug
Here is a minimal example that will render a label with current date and time

from kivy.app import App

from datetime import datetime

from kivy.uix.label import Label





classMyApp(App):

    defbuild(self):

        self.now = datetime.now().strftime('%H:%M:%S')

        self.my_label = Label(text=self.now)

        returnself.my_label



MyApp().run()

but in kivy use %Y年%m月%d日 %H:%M get nothing ,

I am not sure what do you want with that.
And if i am not wrong that is simply a string substitution left in the wild.
For more info you can see:
DateTime - strftime

ps: use Clock.schedule_interval(self.timer, 1) get datetime

This is not how one uses Clock object

From Kivy docs:

defmy_callback(dt):

    # do stuff herepass



Clock.schedule_interval(my_callback, 0.5)

**Comment by linpan** [comment]
hope a better way to solution
