### ISSUE TITLE
Kivy window not showing

### ISSUE THREAD

**Issue by Rana56** [kivy/kivy#6480]
### Versions

* Python: 3.7.0a1
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: https://kivy.org/doc/stable/installation/installation-windows.html

### Description

I recently installed kivy, but when I run the code the output window from kivy doesn't show up and the shell doesn't seem to be showing any errors. A window doesn't show up and I've already tried to uninstall and reinstall kivy. Any ideas on how to fix this issue?

### Code and Logs

I run this code:

import kivy
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):
    def build(self):
        return Label(text = 'The test')

if __name__ == '__main__':
    MyApp().run()

The python shell gives this:

 RESTART: C:\Users\rana2015\Documents\Chirag stuff\Computer science\Kivy programming\No1.py 
[INFO   ] [Logger      ] Record log in C:\Users\rana2015\.kivy\logs\kivy_19-08-17_8.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\rana2015\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.0a1 (v3.7.0a1:8f51bb4, Sep 19 2017, 19:32:44) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\rana2015\AppData\Local\Programs\Python\Python37\pythonw.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)

=============================== RESTART: Shell ===============================

But nothing happens

**Comment by Rana56** [comment]
nvm fixed it by updating python and doing a restart

**Comment by Jflam1** [comment]
Wait what did you do? I have the same exact problem. How do you do a restart?

**Comment by Rana56** [comment]
@Jflam1 
I fixed my problem by updating Python to the latest version, uninstalling and reinstalling kivy and doing a normal computer restart.
If you want to restart your computer you can follow this, https://www.lifewire.com/how-to-reboot-a-computer-2624568 
Or, just turn your computer off and on.

**Comment by hamzaddn** [comment]
> @Jflam1 I fixed my problem by updating Python to the latest version, uninstalling and reinstalling kivy and doing a normal computer restart. If you want to restart your computer you can follow this, https://www.lifewire.com/how-to-reboot-a-computer-2624568 Or, just turn your computer off and on.

Hello ,i have a problem,when i execute a kivy script,the script runs without errors,but no window opens up ,just kivy icon in the taskbar
