### ISSUE TITLE
Arch Linux ARM 4.19 RPi4B Install Instructions

### ISSUE THREAD

**Issue by frankgould** [kivy/kivy#6487]
This issue is to report the success and failure of the kivy install on Arch Linux ARM 4.19 Desktop. The non-desktop (aka desktopless) installation does not work with these instructions due to limitations of compiling to include an X window provider.

### Versions
* Raspberry Pi: Model 4B, 4GB System RAM
* Python: 3.7.4
* OS: Arch Linux ARM 4.19, Exton RaspArch Build 190809
* Kivy: v2.0.0.dev0
* Kivy installation method: 
```
sudo pacman -S sdl2 sdl2_gfx sdl2_image sdl2_net sdl2_ttf sdl2_mixer python-setuptools cython python2-pillow
git clone https://github.com/kivy/kivy.git
cd kivy
make
```
### Description
Although the desktop version of kivy works, there has not been extensive tests to confirm other modules needed are available.

### Code and Logs
Here was what I added to /etc/environment to try the same install without the desktop (from the console):
```
DISPLAY=:0.0
USE_X11=1
VIDEOCOREMESA=1
KIVY_GRAPHICS="gles"
PYTHONPATH="/home/archpi/kivy"
```
NOTE: In a previous post, I used pip to install kivy and other packages. This resulted in a corrupted package management issue when attempting to install other Arch Linux ARM apps. This version has been confirmed to install and run the settings example app.

**Comment by Lauszus** [comment]
@frankgould could you test if the cross compiled wheel works on Arch Linux: https://github.com/kivy/kivy/suites/364981942/artifacts/751103?

Simply follow these instructions on how to install all the dependencies: https://github.com/kivy/kivy/issues/6474#issuecomment-542679712, but instead of compiling Kivy from source you should be able to install it using the precompiled wheel:

```bash
pip install Kivy-2.0.0.dev0-cp37-cp37m-linux_armv7l.whl
```

**Comment by frankgould** [comment]
@Lauszus I cannot install kivy using `pip` because `pacman` will not recognize it when upgrading system using `pacman -S`. I know because I've had kivy fail to operate after using `pip` which may or may not install properly after the ALARM upgrade. If you want me to try it using the compile install, I can test that.

**Comment by tshirtman** [comment]
@frankgould you can use pip without installing in the system, you can either use `--user` to install in user directory (which shouldn't disturb pacman), or use virtualenvs, which are even more separated.
