### ISSUE TITLE
 redistore need enhancement

### ISSUE THREAD

**Issue by linpan** [kivy/kivy#6492]
kivy redisstore
store_get(key) if key not exsits, should be default key , but now directly raise key error

how i pull fixed a bug in this repro?

**Comment by gottadiveintopython** [comment]
這裡不是問的地方. 請您用[Discord](https://chat.kivy.org/)或[E-mail](mailto:kivy-users@googlegroups.com)問

**Comment by linpan** [comment]
not question, is a enhancement

在 2019-08-30 10:18:56，"水戸う納豆齋(Nattōsai Mitō)" <notifications@github.com> 写道：


這裡不是問的地方. 請您用Discord或E-mail問

**Comment by gottadiveintopython** [comment]
You want to enhance `redistore` but you don't know how to do it, right? There should be many resources to learn git/github in Chinese. You should learn from it, then open a pull request.

Also, all your issues don't look like a bug, but a question. You should ask questions in [Discord](https://chat.kivy.org/) or [E-mail](mailto:kivy-users@googlegroups.com).

**Comment by linpan** [comment]
got it

At 2019-08-30 12:29:22, "水戸う納豆齋(Nattōsai Mitō)" <notifications@github.com> wrote:


You want to enhance redistore but you don't know how to do it, right? There should be many resources to learn git/github in Chinese. You should learn from it, then open a pull request.

Also, all your issues don't look like a bug, but a question. You should ask questions in Discord or E-mail.

**Comment by tshirtman** [comment]
if you want to contribute a fix, you can open a pull request, make sure to follow the contribution guide https://kivy.org/doc/stable/contribute.html
