### ISSUE TITLE
Add support for mediaplayer or exoplayer on android directly without the usage of jnius

### ISSUE THREAD

**Issue by gurneesh** [kivy/kivy#6497]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by Julian-O** [comment]
This isn't a complete feature request. It doesn't justify why such a thing is needed, or who it would be useful for. Closing as not detailed enough for action.
