### ISSUE TITLE
Kivy wheel

### ISSUE THREAD

**Issue by rubik** [kivy/kivy#650]
It would be very interesting to see wheels in action with Kivy.
Wheel is a new binary package format for Python. It's still experimental but I find it great. A couple of links:
http://wheel.readthedocs.org/en/latest/index.html
https://bitbucket.org/dholth/wheel
https://bitbucket.org/dholth/python-peps/raw/98cd36228c2e/pep-CTAG.txt

I thought it would be great to try a binary package of Kivy. For windows especially, where compiling is a pain. I know there is already the Kivy development kit, but if someone who can compile could provide a wheel for Windows to test it would be great. I can provide a linux one if someone is interested.

It's very simple to build wheels. Just install the wheel package (which is available on PyPI) and then (in your package):

```
$ python setup.py bdist_wheel
```

Open the `dist/` directory and you'll find your wheel. Neat uh?

Pip support is coming and once there it should be very fast for installations since it's all pre-built.

**Comment by Vagdish** [comment]
Hey guys !
I'm taking a lot of pleasure to play with Kivy.

How about now for packaging Kivy into wheel ? So the installation of Kivy could take place easily thanks to pip on Windows, OSX.

Any thoughts about that ? The main idea is to avoid the use of Kivy.app or Kivy.bat on these platforms. In addition, deploying Kivy could be easier for you.

Cordially,
Vag'
