### ISSUE TITLE
Window.mouse_pos Incorrect for on_file_drop Event

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#6506]
### Versions

* Python: 3.6.8
* OS: Ubuntu 18.04
* Kivy: 1.11.0

### Description

Using Window.bind() to bind on_drop_file event to a method results in expected operation, but the Window.mouse_pos is incorrect.

Run the below code and drag and drop anything from the desktop to the app. The result is the bound method is called, but the Window.mouse_pos is either [0,0], if the mouse has not been inside the window before the drag and drop, or it is the mouse position when the mouse last exited the window. I have tried using touch events to capture the correct mouse position, but none of them are fired for drag and drop.
### Code and Logs

```python
from kivy.app import App
from kivy.core.window import Window
from kivy.uix.label import Label


class BugApp(App):
    def __init__(self):
        super(BugApp, self).__init__()
        Window.bind(on_dropfile=self._on_file_drop)

    def build(self):
        return Label(text='App')

    def _on_file_drop(self, window, file_path):
        print(file_path, 'dropped at', window.mouse_pos, 'this is not the correct mouse position')


BugApp().run()

```
Typical output is:

> b'/home/jra/Desktop/tours.txt' dropped at (0.0, 202.0) this is not the correct mouse position

**Comment by matham** [comment]
I can't replicate the issue. I modified the example so it's clearer what the mouse is doing and everything seems ok:

```py
from kivy.app import App
from kivy.core.window import Window
from kivy.lang import Builder
from kivy.graphics import Color, Ellipse

kv = """
#:import Window kivy.core.window.Window
Widget:
    canvas:
        Color:
            rgb: 1, 0, 0
        Ellipse:
            pos: Window.mouse_pos
            size: 10, 10
"""

class MyApp(App):
    def __init__(self):
        super().__init__()
        Window.bind(on_dropfile=self.add_circle)

    def add_circle(self, *l):
        with self.root.canvas:
            Color(0, 1, 0, 1)
            Ellipse(size=(10, 10), pos=Window.mouse_pos)

    def build(self):
        return Builder.load_string(kv)

MyApp().run()
```
While it's being dragged, the red circle is not shown. But as soon as it's dropped, the mouse position is updated and the green circle shows in the right position.

**Comment by DaytonaJohn** [comment]
Interesting. When I run your code, the green circle gets drawn at the 
coordinates that I described in my original post. Are you running the 
same Python, Kivy, and OS as me?

**Comment by DaytonaJohn** [comment]
I upgraded to kivy 1.11.1, but still see the same problem.

**Comment by matham** [comment]
I'm on windows with 3.7. After a few drag and drops this is how it looks for me:

![image](https://user-images.githubusercontent.com/1644286/64495492-02b00580-d269-11e9-8689-4d59ab07f0b4.png)

**Comment by matham** [comment]
Oh, I forgot, also I'm on master.

**Comment by DaytonaJohn** [comment]
All my green circles are on the edges of the app window, even if I drop 
in the middle of the app window.

**Comment by DaytonaJohn** [comment]
I have a dual boot box, so I ran the same codes (mine and mathams) under Windows 10 with Kivy 1.11.1. They both work correctly under Windows.

**Comment by matham** [comment]
Can you post the full kivy log?

**Comment by DaytonaJohn** [comment]
Here is the entire log:

> [INFO   ] [Logger      ] Record log in /home/jra/.kivy/logs/kivy_19-09-09_0.txt
> [INFO   ] [Kivy        ] v1.11.1
> [INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.6/dist-packages/kivy/__init__.py"
> [INFO   ] [Python      ] v3.6.8 (default, Jan 14 2019, 11:02:34) 
> [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
> [INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
> [INFO   ] [Logger      ] Purge log fired. Analysing...
> [INFO   ] [Logger      ] Purge 1 log files
> [INFO   ] [Logger      ] Purge finished!
> [INFO   ] [Factory     ] 184 symbols loaded
> [INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.2.0
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif 
> [INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
> [INFO   ] [GL          ] Using the "OpenGL" graphics system
> [INFO   ] [GL          ] Backend used <sdl2>
> [INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 390.116'>
> [INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
> [INFO   ] [GL          ] OpenGL renderer <b'GeForce 840M/PCIe/SSE2'>
> [INFO   ] [GL          ] OpenGL parsed version: 4, 6
> [INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
> [INFO   ] [GL          ] Texture max size <16384>
> [INFO   ] [GL          ] Texture max units <32>
> [INFO   ] [Window      ] auto add sdl2 input provider
> [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
> [INFO   ] [Text        ] Provider: sdl2
> [INFO   ] [ProbeSysfs  ] device match: /dev/input/event7
> [INFO   ] [MTD         ] Read event from </dev/input/event7>
> [INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
> [INFO   ] [MTD         ] Read event from </dev/input/event4>
> [INFO   ] [Base        ] Start application main loop
> [WARNING] [MTD         ] Unable to open device "/dev/input/event7". Please ensure you have the appropriate permissions.
> [WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
> [INFO   ] [GL          ] NPOT texture support is available
> b'/home/jra/Desktop/tours.txt' dropped at (0.0, 435.0) this is not the correct mouse position
> [INFO   ] [WindowSDL   ] exiting mainloop and closing.
> [INFO   ] [Base        ] Leaving application in progress...
> 
> Process finished with exit code 0

**Comment by cedrik0s** [comment]
Hi there.
I decided to try Kivy because it's claimed to be cross platform and seems to support drag n drop quite easily.
I am trying Kivy 2.0 on MacOS 10.15.5, with Python 3.7, in PyCharm. (I installed Kivy 2.0 days ago for the first time).

BUT, I just encountered the issue described in this thread.
When I run the test app given by Matham, here's what I get:
![image](https://user-images.githubusercontent.com/76779794/103354457-e3676800-4aab-11eb-8e7f-a4b80b1f27fe.png)
Some drops work fine, but many do not: all those points stuck on the left hand side are wrong. When this happens it seems that the event is returning the last position of the mouse before I dropped a file, instead of the current mouse position, and since I exit the window from the left side, this is where the green dots end.

I see this issue has been there since 2019... does it mean there is no fix for this at all?
This may mean I need to find a substitute for Kivy.

Or is there a solution for that?
(if it worked I could know on which widget I am dropping a file to and perform different operations accordingly)

Thank you all.

**Comment by DaytonaJohn** [comment]
The situation is even worse than it was when I first posted here. Now, when I run either of the posted codes on an Ubuntu box, the `on_filedrop` event does not even appear to get triggered. Of course, they work fine on a Windows box.

**Comment by cedrik0s** [comment]
I see.
That's a real pity... Kivy seems pretty cool otherwise... and knowing where you are dropping a file would seem to be a basic feature compared to all that's been implemented already (not saying it is easy to implement, I suppose it is not).
Maybe the Mac users/developers are few.
