### ISSUE TITLE
Window.maximize works on windows os but not on Ubuntu

### ISSUE THREAD

**Issue by shashi278** [kivy/kivy#6509]
### Versions

* Python: 3.6.8
* OS: Ubuntu 18.04.3 LTS
* Kivy: v1.11.1
* Kivy installation method: pip

### Description
Window.maximize doesn't maximize the app window on ubuntu os.

### Code and Logs

Here's an example code to reproduce the situation:

```
from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window

kv="""
AnchorLayout:
	canvas:
		Color:
			rgba:1,1,1,1
		Rectangle:
			pos:self.pos
			size:self.size
	Label:
	    color: 0, 0, 0, 1
	    font_size: dp(50)
	    text: "Hello Kivy"
"""
class Demo(App):
	def build(self):
		return Builder.load_string(kv)

if __name__ == '__main__':
	Window.maximize()
	Demo().run()
```

**Comment by pythonic64** [comment]
Can you test with SDL2 window provider and report back?

See this links:
- https://kivy.org/doc/stable/api-kivy.core.window.html?highlight=window#kivy.core.window.WindowBase.maximize
- https://kivy.org/doc/stable/guide/environment.html#restrict-core-to-specific-implementation

**Comment by shashi278** [comment]
I forgot to update and close this issue. It worked then itself with SDL2 window provider. We're good to close this now.
