### ISSUE TITLE
Can't run kivy python3 on jetson nano but python 2 can :(

### ISSUE THREAD

**Issue by solua** [kivy/kivy#6517]
Hi Kivy team,

I try to run Kivy and python3 but HelloWorld app crash:

[INFO   ] [Logger      ] Record log in /home/wee/.kivy/logs/kivy_19-09-14_6.txt
[INFO   ] [Kivy        ] v2.0.0.dev0, git-29dfcbc, 20190914
[INFO   ] [Kivy        ] Installed at "/home/wee/py3source/pakingkivy/ven3/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/wee/py3source/pakingkivy/ven3/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_pygame, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_pygame'] ignored)
Begin run app
Send message
brg process start
brg: Init app
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/wee/py3source/pakingkivy/ven3/lib/python3.6/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/wee/py3source/pakingkivy/ven3/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

pygame - ModuleNotFoundError: No module named 'pygame'
  File "/home/wee/py3source/pakingkivy/ven3/lib/python3.6/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/wee/py3source/pakingkivy/ven3/lib/python3.6/site-packages/kivy/core/window/window_pygame.py", line 13, in <module>
    import pygame

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/wee/py3source/pakingkivy/ven3/lib/python3.6/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.

but kivy and python 2 run like charm, I play webcam with it.

I try install Cython and install master from git:
$ pip install Cython 
$ pip install git+https://github.com/kivy/kivy.git@master 
but it doesn't help

Run python 2 is ok but python 2 will outdate soon.
Would please to help me.
Thank  you.

**Comment by tshirtman** [comment]
Use pip3 to install for python3, or create a python3 virtualenv, and use pip after activating it, so python will be python3 as well.

Nothing specific to kivy in that, learn to use the python tools (pip and virtualenv).

**Comment by solua** [comment]
I already run app in virtualenv active with python 3.6 default.
