### ISSUE TITLE
Wrong touch event coordinates in some situations on Linux machines

### ISSUE THREAD

**Issue by tbozuric** [kivy/kivy#6519]
### Versions

* Python: 3.7.3
* OS: Raspbian (RPI 4)
* Kivy: 1.11.1

### Description

Sometimes when I try to move one slider another simultaneously moves as the original. I've tried to reproduce this bug on OS X, Windows 10, Raspbian and Arch Linux. On OS X and Windows 10, I haven't succeeded to reproduce it. I have also tried to use the joystick component [url](https://github.com/kivy-garden/garden.joystick) and I've got the same behavior. I've tried to print coordinates in on_touch_down method and there are really two pairs of coordinates. 

### Code and Logs
Part of the code, all sliders are built the same way
```python
GridLayout:
                cols:3
                rows:6
                id: parent_joint
                padding: dp(10)
                BoxLayout:
                    size_hint_x: None
                    width: parent_joint.width * 0.77
                    Slider:
                        orientation: 'horizontal'
                        value: 0
                        min: -185
                        max: 185
                        step: 1
                        value_track:True
                        sensitivity: 'handle'
                Label:
                    size_hint_x: None
                    width: parent_joint.width * 0.12
                    id: baseValue
                    markup: True
               
```

**Comment by tshirtman** [comment]
can you share the [input] section of your `~/.kivy/config.ini` i suspect you have multiple input configured.

**Comment by tbozuric** [comment]
`[kivy]
keyboard_repeat_delay = 300
keyboard_repeat_rate = 30
log_dir = logs
log_enable = 1
log_level = info
log_name = kivy_%y-%m-%d_%_.txt
window_icon =
keyboard_mode =
keyboard_layout = qwerty
desktop = 1
exit_on_escape = 1
pause_on_minimize = 0
kivy_clock = default
default_font = ['Roboto', 'data/fonts/Roboto-Regular.ttf', 'data/fonts/Roboto-Italic.ttf', 'data/fonts/Roboto-Bold.ttf', 'data/fonts/Roboto-BoldItalic.ttf']
log_maxfiles = 100
window_shape = data/images/defaultshape.png
config_version = 21
 
[graphics]
display = -1
fullscreen = 0
height = 600
left = 0
maxfps = 60
multisamples = 2
position = auto
rotation = 0
show_cursor = 1
top = 0
width = 800
resizable = 1
borderless = 0
window_state = visible
minimum_width = 0
minimum_height = 0
min_state_time = .035
allow_screensaver = 1
shaped = 0
 
[input]
mouse = mouse
%(name)s = probesysfs,provider=hidinput
 
[postproc]
double_tap_distance = 20
double_tap_time = 250
ignore = []
jitter_distance = 0
jitter_ignore_devices = mouse,mactouch,
retain_distance = 50
retain_time = 0
triple_tap_distance = 20
triple_tap_time = 375
 
[widgets]
scroll_timeout = 250
scroll_distance = 20
scroll_friction = 1.
scroll_stoptime = 300
scroll_moves = 5
 
[modules]
 
[network]
useragent = curl`

**Comment by tshirtman** [comment]
can you try to comment out the last line?

**Comment by tbozuric** [comment]
It works! Thank you!!

**Comment by tshirtman** [comment]
Just so you know, this other line was used to auto detect multitouch devices, if you only care about single touch, you can keep using the mouse, if you want multi, you'll want to disable the mouse and instead make sure the probesysfs is properly configured and calibrated.
