### ISSUE TITLE
When GridLayout(rows=3) has 4 children, the layout becomes 2x2

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy/kivy#6538]
### Versions

* Python: 3.7.1
* OS: Linux Mint 18.2 Mate Edition (Ubuntu 16.04LTS)
* Kivy: v2.0.0.dev0, git-0d1156a, 20190927
* Kivy installation method:

### Description

```python
from kivy.app import runTouchApp
from kivy.factory import Factory

root = Factory.GridLayout(rows=3)
for i in range(4):
    root.add_widget(Factory.Label(text=str(i)))
runTouchApp(root)
```

![Screenshot at 2019-09-27 16-48-25](https://user-images.githubusercontent.com/26050135/65751976-c88aa300-e146-11e9-8b0a-d959d408dfb6.png)

I also tested with kv, but it was the same thing.

```python
from kivy.app import runTouchApp
from kivy.lang import Builder

root = Builder.load_string('''
GridLayout:
    rows: 3
    Label:
        text: '0'
    Label:
        text: '1'
    Label:
        text: '2'
    Label:
        text: '3'
''')
runTouchApp(root)
```

**Comment by ZurMaD** [comment]
You can fix adding one row 

```
from kivy.app import runTouchApp
from kivy.factory import Factory

root = Factory.GridLayout(rows=4)
for i in range(4):
    root.add_widget(Factory.Label(text=str(i)))
runTouchApp(root)
```

**Comment by gottadiveintopython** [comment]
Well, that solves nothing...

**Comment by me2beats** [comment]
The problem is seem to apear from here
`_init_rows_cols_sizes`
```
if current_cols is None:
    current_cols = int(ceil(count / float(current_rows)))
elif current_rows is None:
     current_rows = int(ceil(count / float(current_cols)))
```
so one of quick solutions is add/patch this behavior
(assuming that without specifying rows you want to have 1 row by default)
```
class MyGrid(GridLayout):
    def __init__(self, **kw):
        self.cols = self.cols or 1
        self.rows = self.rows or 1

        super().__init__(**kw)
```
https://github.com/kivy/kivy/blob/master/kivy/uix/gridlayout.py

**Comment by gottadiveintopython** [comment]
Thanks. When I watched attributes at [this point](https://github.com/kivy/kivy/blob/master/kivy/uix/gridlayout.py#L327), the values were

```
self._rows == [0, 0, 0]
self._cols == [0, 0]
self._rows == [None, None, None]
self._cols == [None, None]
```

.  `GridLayout` is trying to layout the children in 2x3(2 columns x 3 rows) form at this point (which what it should be). So `_init_rows_cols_sizes()` looks fine to me.
