### ISSUE TITLE
Create Github release for 1.11.1

### ISSUE THREAD

**Issue by Lauszus** [kivy/kivy#6550]
The ```1.11.1``` release has been correctly tagged, however a proper Github release has not been created: <https://github.com/kivy/kivy/releases>.

This causes issues for me, as I have a script that automatically gets the source of the latest release using the Github API:

```bash
curl -s https://api.github.com/repos/kivy/kivy/releases/latest | python -mjson.tool | grep 'zipball_url' | cut -d'"' -f4
```

Thus it will get the ```1.11.0``` release instead of ```1.11.1```:

```bash
$ curl -s https://api.github.com/repos/kivy/kivy/releases/latest | python -mjson.tool | grep 'zipball_url' | cut -d'"' -f4
https://api.github.com/repos/kivy/kivy/zipball/1.11.0
```

**Comment by Franccisco** [comment]
What happened with this issue? Current release in GitHub is 1.11.0 yet.

**Comment by matham** [comment]
I think I was waiting on figuring out how to get osx dmg/app artifacts for 1.11.1 but it never materialized. I just made the release, without them.
