### ISSUE TITLE
show Garbled about cn_zh

### ISSUE THREAD

**Issue by shuaiLiWang** [kivy/kivy#6551]
code:
     import kivy
    from kivy.app import App
    from kivy.uix.button import Button

kivy.resources.resource_add_path('electrum/gui/kivy/data/fonts/')
font = kivy.resources.resource_find('DroidSansFallback.ttf')

class TestApp(App):
    def build(self):
        return Button(text='你好 world', font_name=font)

TestApp().run()

result:also show Garbled
![2222](https://user-images.githubusercontent.com/9347690/66823167-44bf1c00-ef78-11e9-906e-72ab9a9a3ee8.png)

**Comment by Julian-O** [comment]
Sorry - wrong tag
