### ISSUE TITLE
TextInput doesn't detect shift+tab

### ISSUE THREAD

**Issue by ShaiAvr** [kivy/kivy#6560]
### Versions

* Python: 3.7.5
* OS: Windows 10, 64 bit
* Kivy: 1.11.1

### Description
I was trying to build the user interface for my game in kivy which has some `TextInputs` to get the players' names. I wanted to allow the user to switch between the inputs using Tab and Shift+Tab, so I set the `write_tab` property of all the inputs to `False` and I set the `focus_next` and `focus_previous` properties (I prefer to be explicit about who comes next).

When I tested it, cycling through the inputs using Tab worked correctly, however, when I used Shift+Tab, it kept moving forward instead of backward.

### Code and Logs

Here's a simple app to reproduce the issue:

```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput


class TestApp(App):
    def build(self):
        root = BoxLayout(orientation="vertical")
        t1 = TextInput(write_tab=False, size=(100, 50), size_hint=(None, None))
        t2 = TextInput(write_tab=False, size=(100, 50), size_hint=(None, None))
        t3 = TextInput(write_tab=False, size=(100, 50), size_hint=(None, None))
        t4 = TextInput(write_tab=False, size=(100, 50), size_hint=(None, None))

        t1.focus_next = t2
        t1.focus_previous = t4
        t2.focus_next = t3
        t2.focus_previous = t1
        t3.focus_next = t4
        t3.focus_previous = t2
        t4.focus_next = t1
        t4.focus_previous = t3

        root.add_widget(t1)
        root.add_widget(t2)
        root.add_widget(t3)
        root.add_widget(t4)
        return root


if __name__ == "__main__":
    TestApp().run()
```
When you run the app, you can cycle through the `TextInput`s forward using Tab, but when you press Shift+Tab, it keeps moving forward instead of backward.

I took a look at the source code of `keyboard_on_key_down` for `TextInput` and `FocusBehavior` and I think I recognize the bug:

The `keyboard_on_key_down` method of `TextInput` converts the `modifiers` list to `set` and passes it to `keyboard_on_key_down` of `FocusBehavior` (if `write_tab` is False, which it is). The `keyboard_on_key_down` of `FocusBehavior` tests for the shift modifier like this: `['shift'] == modifiers`. Since `TextInput` converted the `list` to `set`, the condition is false and we get the same behavior as if only Tab was pressed.

I can write a pull request to to fix this bug if you want.

**Comment by E-Unit** [comment]
@ShaiAvr I have run into the same issue and it is very annoying. Based on your explanation about TextInput converting the list to set, I fiddled around a little. I got mine working after changing `if ['shift'] == modifiers:` to `if modifiers == {'shift'}:` . I need to test if it breaks other behaviors first but for now it seems to be working for me.

**Comment by Julian-O** [comment]
Tested it on Kivy 2.2.1 on Windows. It worked perfectly. (Shift-Tab moved backwards.)

I can't see the offending line, so I assume, without investigating,  it has been refactored away.

I am closing this as completed, but if the symptoms still persist, please let us know.
