### ISSUE TITLE
Textinput text is not showing when i am typing in kivy textinput

### ISSUE THREAD

**Issue by hsielecpart** [kivy/kivy#6566]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by hsielecpart** [comment]
text is not showing when i am typing . Just cursor is moving but nothing is showing

**Comment by Rexogamer** [comment]
is the text could the same as the backgroud

**Comment by hsielecpart** [comment]
> is the text colour the same as the backgroud

It is looks like that. I don't know how to fix it

**Comment by Rexogamer** [comment]
try to change the text colour

**Comment by hsielecpart** [comment]
> text colour

Do you how can i do that . I'd already changed  background color and cursor color ?I got the same result.
