### ISSUE TITLE
Graphical Issue in fullscreen mode after macOS Catalina update. 

### ISSUE THREAD

**Issue by ArthurVanRemoortel** [kivy/kivy#6576]
#6527 # Versions

* Python: 3.6.2
* OS: MacOS Catalina 10.15.1 (19B88)
* Kivy: v2.0.0.dev0. Same issue on 1.11.1
* Kivy installation method: Build from github source using python setup.py install. Issue persists using pip install.  

### Description

Since updating my macOS to Catalina 10.15.0/10.15.1 **(Retina Display)** all my kivy apps experience significant graphical glitches/tearing. This only happens when it **fullscreen** mode on "auto" and not on 1. Setting fullscreen mode on 0 and then using the fullscreen button from the OS also causes the glitch.

The glitch also only appears when mouse is **focused** on the window or something like that. Moving the mouse to the top of screen (which makes the menu macOs bar appear) fixed the issue temporarily until I click on the kivy window again. 
No other non-kivy based application have this issue. 

It is also worth noting that i've always had issued with screen resolutions on retina displays (2880x1800). `print(Window.size)` would often report unusual values not matching my displays resolution and manually setting `Window.size = (3360, 2100)` or even `Window.size = (1680, 2100)` (a vertical resolution) was required to make my kivy windows the correct size. This might be related. 

### Footage

![output](https://user-images.githubusercontent.com/12198747/67968397-95d14000-fc07-11e9-8955-be0010f0a042.gif)
![IMG_0576](https://user-images.githubusercontent.com/12198747/67971190-991afa80-fc0c-11e9-9adb-4b5c650dc765.JPG)
(originally vertical photo)
It appears that pixels are shifted to the right. Made me wonder if  SLD2 or macOS is incorrectly drawing/reporting the display size.  

### Code and Logs

```python
from kivy.app import App
from kivy.uix.button import Button


class MainApp(App):
	def build(self):
		return Button()


if __name__ == '__main__':
	MainApp().run()
```

```
[INFO   ] Logger: Record log in /Users/Arthur/.kivy/logs/kivy_19-10-31_0.txt
[INFO   ] Kivy: v2.0.0.dev0, git-09ea01a, 20191031
[INFO   ] Kivy: Installed at "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Kivy-2.0.0.dev0-py3.6-macosx-10.12-x86_64.egg/kivy/__init__.py"
[INFO   ] Python: v3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
[INFO   ] Python: Interpreter at "/usr/local/Cellar/python/3.6.2/Frameworks/Python.framework/Versions/3.6/bin/python3.6"
[INFO   ] Factory: 184 symbols loaded
[DEBUG  ] Cache: register <kv.lang> with limit=None, timeout=None
[DEBUG  ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG  ] Cache: register <kv.atlas> with limit=None, timeout=None
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[DEBUG  ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] Cache: register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] Text: Provider <pango> ignored by config
[INFO   ] Text: Provider: sdl2(['text_pango'] ignored)
[DEBUG  ] App: Loading kv </Users/Arthur/Desktop/Projects/H/DownloadViewer/testing/main.kv>
[DEBUG  ] App: kv </Users/Arthur/Desktop/Projects/H/DownloadViewer/testing/main.kv> not found
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'2.1 ATI-3.2.24'>
[INFO   ] GL: OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] GL: OpenGL renderer <b'AMD Radeon Pro 560X OpenGL Engine'>
[INFO   ] GL: OpenGL parsed version: 2, 1
[INFO   ] GL: Shading version <b'1.20'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[DEBUG  ] Shader: Fragment compiled successfully
[DEBUG  ] Shader: Vertex compiled successfully
[DEBUG  ] ImageImageIO: Load </usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Kivy-2.0.0.dev0-py3.6-macosx-10.12-x86_64.egg/kivy/data/glsl/default.png>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[DEBUG  ] Resource: add </Library/Fonts> in path list
[DEBUG  ] Resource: add </System/Library/Fonts> in path list
[DEBUG  ] Resource: add </System/Library/Fonts/Supplemental> in path list
[DEBUG  ] Resource: add </Users/Arthur/Library/Fonts> in path list
[DEBUG  ] Resource: add </usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Kivy-2.0.0.dev0-py3.6-macosx-10.12-x86_64.egg/kivy/data/fonts> in path list
[DEBUG  ] Base: Create provider from mouse
[INFO   ] Base: Start application main loop
[DEBUG  ] Atlas: Load </usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Kivy-2.0.0.dev0-py3.6-macosx-10.12-x86_64.egg/kivy/data/images/defaulttheme.atlas>
[DEBUG  ] Atlas: Need to load 1 images
[DEBUG  ] Atlas: Load </usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Kivy-2.0.0.dev0-py3.6-macosx-10.12-x86_64.egg/kivy/data/images/defaulttheme-0.png>
[DEBUG  ] ImageImageIO: Load </usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Kivy-2.0.0.dev0-py3.6-macosx-10.12-x86_64.egg/kivy/data/images/defaulttheme-0.png>
[INFO   ] Base: Leaving application in progress...
```

### What have I tried?

After talking to @tshirtman on the Kivy discord I narrowed it down to an SDL2 issue (probably). After uncommenting uncommenting the line at: https://github.com/kivy/kivy/blob/master/kivy/core/window/_window_sdl2.pyx#L635 
I found that it produced `receive unknown sdl window event 512` when entering and leaving fullscreen mode. 
After further tinkering in `kivy/core/window/_window_sdl2.pyx` I found that the glitch only appears when SDL2 uses `SDL_WINDOW_FULLSCREEN_DESKTOP`. The glitch did not appear when it uses `SDL_WINDOW_FULLSCREEN`. 

I also tried setting `SDL_GL_ACCELERATED_VISUAL` to `0`. This fixed the glitch on both fullscreen modes but significantly changed how windows are rendered sometimes caused segmentation faults. 

### Temporary solution

I found that setting `multisamples = 0` in in the kivy `config.ini` completely fixed the issue on every fullscreen mode. Even after undoing the changes i made in `_window_sdl2.pyx`.

### Potentially useful resources

Similar SDL2 focus related issue causing 512 event. 
https://stackoverflow.com/questions/18454588/sdl2-not-receiving-window-events

Identical issue on an unrelated game using SDL2 since macOS Catalina update. 
https://forums.kleientertainment.com/klei-bug-tracker/oni/issue-with-full-screen-mode-on-macos-catalina-r22388/

**Comment by LucasMaliszewski** [comment]
I have the same issue, no issues in Older OS X, but this Catalina just doesn't play well with Full screen apps on my machine.
