### ISSUE TITLE
Pylint: No name 'StringProperty' in module 'kivy.properties'

### ISSUE THREAD

**Issue by ZurMaD** [kivy/kivy#6583]
### Versions

* Python: 3.7.3
* OS: Windows
* Kivy: 1.11.1
* Kivy installation method: pip install kivy

### Description

When I try to run this **(.py)** file

```
import kivy
from kivy.properties import StringProperty
```

Pylint shows the next error message:

`No name 'StringProperty' in module 'kivy.properties'`

Other users have the same error 

[Stackoverflow question](https://stackoverflow.com/questions/57637558/no-name-objectproperty-in-module-kivy-properties)

**Comment by ZurMaD** [comment]
This is problem of Pylint, install bandit instead of Pylint. 

Apologies to the developers

**Comment by jurf** [comment]
I filed an issue in pylint, hope it gets fixed.
