### ISSUE TITLE
Unable to find any valuable Window provider / sdl2 - RuntimeError: b'No available video device' (ssh/systemctl error)

### ISSUE THREAD

**Issue by Dorsv** [kivy/kivy#6587]
### Versions

* Python: Python 3.6.8
* OS:
      Operating System: Ubuntu 18.04.3 LTS
      Kernel: Linux 5.0.0-32-generic
      Architecture: x86-64
* Kivy: v2.0.0.dev0, git-17e1977, 20191104
* Kivy installation method: pip3 +git

### Description
I tried to make an app starting with systemctl but it doesn't start (logs below). When i run it using bash script it runs just fine but when trying to start it this way or over ssh this problem appears.
I also tried disabling GUI but it did nothing (except it now doesn't even start with ''). Same problem appears when using stable version v1.11.1.
I tried this on my system, on fresh ubuntu virtual installation and on debian, everywhere the same problem.
I'm running this using bash script with:

export KIVY_HOME=$(pwd)
export KIVY_WINDOW="sdl2"
cd src && python3 app.py -d

Just to make sure its not this particular app's problem (even though it probably couldn't be beacuse it fails at window creation) i made simple app and problem is exactly the same.

EDIT: Of course, im setting both systemctl and ssh to run the script, not the app directly.
My folder structure (parts that matter):
* runscript.sh
* src:
        app.py

### Code and Logs
------------------------------------------------------------------------
[INFO   ] [Logger      ] Record log in /home/xxxx/machine/logs/kivy_19-11-04_5.txt
[INFO   ] [Kivy        ] v2.0.0.dev0, git-17e1977, 20191104
[INFO   ] [Kivy        ] Installed at "/home/xxxx/.local/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Text        ] Provider: sdl2
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0
[DEBUG  ] [Window      ] Provider <egl_rpi> ignored by config
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[DEBUG  ] [Window      ] Provider <x11> ignored by config
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'No available video device'
  File "/home/xxxx/.local/lib/python3.6/site-packages/kivy/core/__init__.py", line 70, in core_select_lib
    cls = cls()
  File "/home/xxxx/.local/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
    super(WindowSDL, self).__init__()
  File "/home/xxxx/.local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 981, in __init__
    self.create_window()
  File "/home/xxxx/.local/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
    self.get_gl_backend_name())
  File "kivy/core/window/_window_sdl2.pyx", line 110, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[CRITICAL] [App         ] Unable to get a Window, abort.
------------------------------------------------------------------------

**Comment by Murali5** [comment]
I'm also facing the same issue. I'm using Ubuntu 20.04 LTS. 
import os
```
os.environ['KIVY_GL_BACKEND'] = 'sdl2'
import kivy
kivy.require('1.11.1') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

    def build(self):
        return Label(text='Hello world')

if __name__ == '__main__':
    MyApp().run()

```
Runtime error on 
`        return Label(text='Hello world')
`
Same log.

**Comment by tshirtman** [comment]
don't you need to export the DISPLAY variable (e.g `export DISPLAY=:0`) to be able to run the app from systcl or ssh?

**Comment by blablublub** [comment]
### Version:
- Python 3.7.3
- Raspberry Pi 4B with newly installed Raspbian Buster Lite
- Kivy 2.0.0 Installed exactly as described on kivy.org

### Description:
(Working with a headless Buster on commanline.)
I am able to run my kivy gui if I am connected to a screen over HDMI.
If I then install a 3.5 inch Touchscreen (SPI, XPT2046) and try to run the same from there, i get the titled error:
Unable to find any valuable Window provider / sdl2 - RuntimeError: b'No available video device'

I've also posted this problem on discord, but got no answer yet.

@tshirtman Any idea what i can try?

### Output:

```
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_21-02-17_20.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/pi/kivy_venv/bin/python3"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'No available video device'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 70, in core_select_lib
    cls = cls()
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
    super(WindowSDL, self).__init__()
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 982, in __init__
    self.create_window()
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 289, in create_window
    self.get_gl_backend_name())
  File "kivy/core/window/_window_sdl2.pyx", line 112, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by matham** [comment]
I don't think there's anything we can do about this, as it's probably more related to configuring your system to be able to run a graphics app in that mode. But, if you can identify a Kivy-specific  bug, please feel free to re-open with more info.
