### ISSUE TITLE
kv classes must use capitalised first letter

### ISSUE THREAD

**Issue by Mark0ne** [kivy/kivy#6588]
* Python: 3.6.6 x64
* OS: Win 10 x64
* Kivy: 1.11.1
* Kivy installation method: pip

Hi,

I'm new to Kivy and I've just spent a while debugging one of my classes defined in kv language.

`<type1Lbl@Label>:`

This causes errors when used: (in kv again)

```
type1Lbl:
    text: 'Hello1'
```

I'm an untrained Python user and hadn't appreciated that the convention is to capitalise the first letter of classes. However, although that's a convention, it doesn't seem to be a requirement. Whereas I seem to have proven it is a requirement of Kivy kv.  

I'm just interested if you guys have documented this anywhere?  It surprised me.
Please (please, please) excuse me if you've already documented this and I've missed it ! 

Great work on Kivy, I love the portability of apps.

Many thanks,

Mark

**Comment by akshayaurora** [comment]
https://kivy.org/doc/stable/api-kivy.lang.html
![Screenshot 2019-11-07 at 3 49 35 PM](https://user-images.githubusercontent.com/788023/68380788-86f20c80-0176-11ea-92ce-2e6a5f07e9f7.png)
