### ISSUE TITLE
Unable to get a text provider, abort

### ISSUE THREAD

**Issue by Nbdyworthn** [kivy/kivy#6597]
### Versions

* Python: 3.7.4
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: PIP

### Description

Hi, im new to kivy and Ive been getting this issue ,i checked on here and found a similar support request however those solutions did not help, its probably something simple but im unsure, thanks.

### Code and Logs:
Code:
import kivy
from kivy.app import App
from kivy.uix.label import Label
class Test(App):
    def Build(self):
        return Label(text='This is code')

if __name__ == "__main__":
    Test().run()

Logs:
C:\Users\Thism\Documents\Coding\Python\Projects\venv\Scripts\python.exe C:/Users/Thism/Documents/Coding/Python/Projects/Test.py
[INFO   ] [Logger      ] Record log in C:\Users\Thism\.kivy\logs\kivy_19-11-11_48.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\Thism\Documents\Coding\Python\Projects\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Thism\Documents\Coding\Python\Projects\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Text        ] Unable to find any valuable Text provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - ImportError: DLL load failed: The specified module could not be found.
  File "C:\Users\Thism\Documents\Coding\Python\Projects\venv\lib\site-packages\kivy\core\__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Thism\Documents\Coding\Python\Projects\venv\lib\site-packages\kivy\core\text\text_sdl2.py", line 13, in <module>
    from kivy.core.text._text_sdl2 import (_SurfaceContainer, _get_extents,

pil - ModuleNotFoundError: No module named 'PIL'
  File "C:\Users\Thism\Documents\Coding\Python\Projects\venv\lib\site-packages\kivy\core\__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Thism\Documents\Coding\Python\Projects\venv\lib\site-packages\kivy\core\text\text_pil.py", line 7, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.

Process finished with exit code 1

```

**Comment by phmarx01** [comment]
I had the same issue some days ago when i install kivy and try to run in Pycharm. it was the same error message. I fix it setting the interpreter following the steps of this video. https://www.youtube.com/watch?v=RvbUqf3Tb1s&t=129s I hope it help you too.
