### ISSUE TITLE
Missing directory in kivy-examples/widgets

### ISSUE THREAD

**Issue by hioymaci** [kivy/kivy#6599]
### Versions

* Python: 3.6.7
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: anaconda

### Description

In the example file _kivy-examples/widgets/colorpicker.py_ gives error due to missing directory and its content: '**list/fruit_images**'. I could not find any directory name **'fruit_images'** in example directory.

### Code and Logs
In _kivy-examples/widgets/colorpicker.py_ line 201:
```
def on_parent(self, instance, parent):
        if parent:
            _dir = join(dirname(__file__), 'lists/fruit_images/')
            for image in list(walk(_dir))[0][2]:
                if image.find('512') > -1:
                    self.client_area.add_widget(Picture(source=_dir + image))
```

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/6636
