### ISSUE TITLE
installation kivy_deps.gstreamer error

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#6610]
Hei guys,

I got a little problem here. When i try to install kivy step by step based on this list: https://kivy.org/doc/stable/installation/installation-windows.html#install-win-dist 
I can't make the "python -m pip install kivy_deps.gstreamer==0.1.17" step. 
It responds 
ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer (from versions: none)
ERROR: No matching distribution found for kivy_deps.gstreamer
Any ideas? 

p.s.
Python 3.8 msc v.1916
Windows 10 Pro Version 1903 (Build 18362.476)

**Comment by matham** [comment]
Please provide full details of your OS and python version.

**Comment by ImmerAmZocken** [comment]
> Please provide full details of your OS and python version.

Oh yeah sry I forgot that :)
