### ISSUE TITLE
Kivy APK invalid signitude FAILED to upload on google play 

### ISSUE THREAD

**Issue by abdulqgg** [kivy/kivy#6611]
### Versions

* Python: 3
* OS: xubuntu
* Using kivy and build debug apk with buildozer

### Description

Ive used builddozer to create a debug.apk for my app, then i followed the tutorial at https://github.com/kivy/kivy/wiki/Creating-a-Release-APK to create a release apk. And everything worked giving me a release-optimized.apk file
I went on google play console to upload my app and i got a error

### Code and Logs

```python
Upload Failed
You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR (Jar signer CERT.RSA): JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?

```

**Comment by vkresch** [comment]
@abdulqgg I have the same issue. The signing process and the optimization process worked but when it comes to upload it throws me the same error. Did you solve it? 
@tshirtman pls help!;)
