### ISSUE TITLE
'python3 toolchain.py build ffpyplayer' problem

### ISSUE THREAD

**Issue by Falk21** [kivy/kivy#6617]
###Versions

* Python: python3 --version = 3.7.4 
                 python --version = 2.7.10
* OS: MacOs Mojave 10.14.4
* Kivy: 1.11.1
* installation method: pip3 install Kivy + python3 toolchain.py build python3 Kivy

my toolchain

Falks-iMac:~ falk$ cd kivy-ios
Falks-iMac:kivy-ios falk$ python3 toolchain.py status
toolchain.py:93: DeprecationWarning: ChromeDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
  urlretrieve = ChromeDownloader().retrieve
audiostream  - Build OK (built at 2019-11-09 21:27:13.260709)
click        - Build OK (built at 2019-11-09 21:28:22.982370)
curly        - Not built
cymunk       - Not built
distribute   - Not built
ffmpeg       - Build OK (built at 2019-11-09 21:02:29.583414)
ffpyplayer   - Not built
flask        - Not built
freetype     - Build OK (built at 2019-11-09 18:07:43.773924)
host_setuptools - Not built
host_setuptools3 - Build OK (built at 2019-11-11 12:44:47.418326)
hostlibffi   - Not built
hostpython2  - Not built
hostpython3  - Build OK (built at 2019-11-09 18:30:40.252835)
ios          - Build OK (built at 2019-11-09 18:43:24.265093)
itsdangerous - Not built
jinja2       - Not built
kivent_core  - Build OK (built at 2019-11-09 23:10:21.945605)
kivy         - Build OK (built at 2019-11-09 18:56:42.312733)
libcurl      - Not built
libffi       - Build OK (built at 2019-11-09 18:20:18.488037)
libjpeg      - Build OK (built at 2019-11-09 21:16:05.597112)
libpng       - Not built
libzbar      - Not built
markupsafe   - Not built
numpy        - Not built
openssl      - Build OK (built at 2019-11-09 18:23:28.751778)
photolibrary - Not built
pil          - Not built
pillow       - Not built
pkgresources - Not built
plyer        - Build OK (built at 2019-11-09 21:26:02.872854)
pycrypto     - Not built
pykka        - Not built
pyobjus      - Build OK (built at 2019-11-09 18:44:55.299500)
python2      - Not built
python3      - Build OK (built at 2019-11-09 18:43:06.706068)
pyyaml       - Not built
sdl2         - Build OK (built at 2019-11-09 18:24:28.988308)
sdl2_image   - Build OK (built at 2019-11-09 18:31:40.260753)
sdl2_mixer   - Build OK (built at 2019-11-09 18:32:52.635991)
sdl2_ttf     - Build OK (built at 2019-11-09 18:33:09.353221)
werkzeug     - Not built
zbarlight    - Not built

### Description

Hello I'm relative new with Kivy. When I try to build ffpyplayer I get this Log.
For useful answers thanks in advance. I try to answer so soon as possible (but I have to sleep sometimes(GMT+01) so sorry if I don't answer immediately). 
With kind Regards Falk21 ...

### Code and Logs

got an:
There was an error creating your Issue: body is too long (maximum is 65536 characters)
so just the last part:

[DEBUG   ] ffpyplayer/writer.pyx:569:17: Accessing Python attribute not allowed without gil
[DEBUG   ] 1: initwriter(void) -> initffpyplayer_writer(void)
[DEBUG   ] 2: PyInit_writer(void) -> PyInit_ffpyplayer_writer(void)
[DEBUG   ] 3: Pyx_NAMESTR("writer") -> Pyx_NAMESTR("ffpyplayer_writer")
[DEBUG   ] 4: "writer", -> "ffpyplayer_writer",
[DEBUG   ] ('rewrite', 'ffpyplayer/writer.c')
[INFO    ] Running Shell: /Users/falk/kivy-ios/dist/hostpython3/bin/python ('setup.py', 'build_ext', '-g') {'_env': {'CC': '/var/folders/p0/npxftvzd12sdrqt2sgbmrxkm0000gn/T/tmpt80w7vwr -I/Users/falk/kivy-ios/dist/include/x86_64/libffi', 'CXX': '/var/folders/p0/npxftvzd12sdrqt2sgbmrxkm0000gn/T/tmp20xlpxwd', 'AR': '/Users/falk/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar', 'LD': '/Users/falk/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld', 'OTHER_CFLAGS': '-I/Users/falk/kivy-ios/dist/include/x86_64/ffi -I/Users/falk/kivy-ios/dist/include/x86_64/openssl -I/Users/falk/kivy-ios/dist/include/x86_64/ffmpeg -I/Users/falk/kivy-ios/dist/include/x86_64', 'OTHER_LDFLAGS': '-L/Users/falk/kivy-ios/dist/lib', 'CFLAGS': '-O3 -miphoneos-version-min=8.0 -I/Users/falk/kivy-ios/dist/include/x86_64/ffi -I/Users/falk/kivy-ios/dist/include/x86_64/openssl -I/Users/falk/kivy-ios/dist/include/x86_64/ffmpeg -I/Users/falk/kivy-ios/dist/include/x86_64', 'LDFLAGS': '-arch x86_64 --sysroot /Users/falk/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -L/Users/falk/kivy-ios/dist/lib -lsqlite3 -miphoneos-version-min=8.0', 'KIVYIOSROOT': '/Users/falk/kivy-ios', 'IOSSDKROOT': '/Users/falk/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk', 'LDSHARED': '/Users/falk/kivy-ios/tools/liblink', 'ARM_LD': '/Users/falk/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld', 'ARCH': 'x86_64', 'SDL_INCLUDE_DIR': '/Users/falk/kivy-ios/dist/include/common/sdl2', 'FFMPEG_INCLUDE_DIR': '/Users/falk/kivy-ios/dist/include/x86_64/ffmpeg', 'CONFIG_POSTPROC': '0'}, '_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ]   File "setup.py", line 96
[DEBUG   ]     print 'Selecting %s out of (SDL, SDL2)' % sdl
[DEBUG   ]                                           ^
[DEBUG   ] SyntaxError: invalid syntax
Traceback (most recent call last):
  File "toolchain.py", line 1568, in <module>
    ToolchainCL()
  File "toolchain.py", line 1281, in __init__
    getattr(self, args.command)()
  File "toolchain.py", line 1322, in build
    build_recipes(args.recipe, ctx)
  File "toolchain.py", line 1158, in build_recipes
    recipe.execute()
  File "/Users/falk/kivy-ios/toolchain.py", line 729, in execute
    self.build_all()
  File "/Users/falk/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/falk/kivy-ios/toolchain.py", line 837, in build_all
    self.build(arch)
  File "/Users/falk/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/falk/kivy-ios/toolchain.py", line 811, in build
    self.build_arch(arch)
  File "/Users/falk/kivy-ios/toolchain.py", line 1112, in build_arch
    _env=build_env)
  File "/Users/falk/kivy-ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "tools/external/sh.py", line 565, in next
    self.wait()
  File "tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/Users/falk/kivy-ios/dist/hostpython3/bin/python setup.py build_ext -g'

  STDOUT:
  File "setup.py", line 96
    print 'Selecting %s out of (SDL, SDL2)' % sdl
                                          ^
SyntaxError: invalid syntax

  STDERR:

**Comment by misl6** [comment]
Hi, this PR: https://github.com/kivy/kivy-ios/pull/403 should fix your issue. Let us know.

Also consider that it's more likely a `kivy-ios` issue than a `kivy` one :)

**Comment by Falk21** [comment]
ffmpeg       - Build OK (built at 2019-11-24 17:02:53.021977)
ffpyplayer   - Build OK (built at 2019-11-24 19:58:52.403503)

sorry my fault, I will take this into consideration the next time;)
but for now, really big thank you for helping me, kind regards.
