### ISSUE TITLE
Outdated or incorrect OS X packaging instructions in docs

### ISSUE THREAD

**Issue by jbasko** [kivy/kivy#6621]
OS X packaging guide contains outdated or plain wrong instructions.

https://github.com/kivy/kivy/blob/master/doc/sources/guide/packaging-osx.rst 

In the section "Using the Kivy SDK" it says to run `package-app.sh`, but there is no such script in https://github.com/kivy/kivy-sdk-packager

> osx> ./package-app.sh /path/to/your/<app_folder_name>/

Even the README file at https://github.com/kivy/kivy-sdk-packager/tree/master/osx seems to be out of date -- the instructions say `./create-osx-bundle` will do this or that, but there is no such file. The script is `create-osx-bundle.sh`.

I have now found this: https://github.com/kivy/kivy-sdk-packager/issues/47

This begs a question - is Kivy still actively maintained? That ticket hasn't received any attention since March.

**Comment by tshirtman** [comment]
Kivy is maintained, but not as much as it needs to, and osx packaging is definitely an area that gets less attention than it deserves, i can't really say what would be the proper course of action, but if people are willing to help, we would certainly be open to sharing some of the responsibilities.

Thanks for the report and concerns.

**Comment by misl6** [comment]
This issue now has been fixed. Feel free to re-open if we missed something.
