### ISSUE TITLE
SoundLoader plays poor quality sound

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#6630]
### Versions

* Python: v3.6.9
* OS: Ubuntu 18.04
* Kivy: v1.11.1
* Kivy installation method:

### Description

Playing a music file using `SoundLoader` produces  very poor quality sound. It sounds very staticky or distorted. Kind of like what I would expect if the speakers were over driven (but my volume levels are set low). Playing the same sound file with other players sounds fine. Occasionally, the `SoundLoader` sounds good, but that is rare.

Also, setting `use_Soundloader` to `False` in the code below (so that the music file is played using `ffplay`), results in good quality sound. Running this identical code on identical hardware under Windows 10 (dual boot) produces good quality sound regardless of `use_SoundLoader` setting. I have tested this with many sound files of different formats, and the results are always the same.

Here is the code that demonstrates the problem:

```
from subprocess import Popen
from kivy.app import App
from kivy.lang import Builder
from kivy.core.audio import SoundLoader

use_Soundloader = True
music_file = '1free_cool2.wav'


class EmptyApp(App):
    def build(self):
        if use_Soundloader:
            self.play_music = self.play_music_with_Soundloader
        else:
            self.play_music = self.play_music_with_ffplay
        root = Builder.load_string('''
BoxLayout:
    Button:
        text: 'Play Music'
        on_release: app.play_music()
        ''')
        return root

    def play_music_with_Soundloader(self, *args):
        print('playing with Soundloader')
        self.sound = SoundLoader.load(music_file)
        self.sound.play()

    def play_music_with_ffplay(self, *args):
        print('playing with ffplay')
        args = ['ffplay', '-nodisp', '-volume', '100', music_file]
        self.p = Popen(args)


if __name__ == '__main__':
    EmptyApp().run()`
```
### Code and Logs

Here is the kivy log:

> INFO   ] [Logger      ] Record log in /home/jra/.kivy/logs/kivy_19-11-30_39.txt
> [INFO   ] [Kivy        ] v1.11.1
> [INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.6/dist-packages/kivy/__init__.py"
> [INFO   ] [Python      ] v3.6.9 (default, Nov  7 2019, 10:44:02) 
> [GCC 8.3.0]
> [INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
> [INFO   ] [Factory     ] 184 symbols loaded
> [INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.2.0
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif 
> [INFO   ] [SoundFFPy   ] Using ffpyplayer 4.2.0
> [INFO   ] [Audio       ] Providers: audio_ffpyplayer, audio_sdl2 
> [INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
> [INFO   ] [GL          ] Using the "OpenGL" graphics system
> [INFO   ] [GL          ] Backend used <sdl2>
> [INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 390.116'>
> [INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
> [INFO   ] [GL          ] OpenGL renderer <b'GeForce 840M/PCIe/SSE2'>
> [INFO   ] [GL          ] OpenGL parsed version: 4, 6
> [INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
> [INFO   ] [GL          ] Texture max size <16384>
> [INFO   ] [GL          ] Texture max units <32>
> [INFO   ] [Window      ] auto add sdl2 input provider
> [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
> [INFO   ] [Text        ] Provider: sdl2
> [INFO   ] [ProbeSysfs  ] device match: /dev/input/event7
> [INFO   ] [MTD         ] Read event from </dev/input/event7>
> [INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
> [INFO   ] [MTD         ] Read event from </dev/input/event4>
> [INFO   ] [Base        ] Start application main loop
> [WARNING] [MTD         ] Unable to open device "/dev/input/event7". Please ensure you have the appropriate permissions.
> [INFO   ] [GL          ] NPOT texture support is available
> [WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
> playing with Soundloader
> [INFO   ] [WindowSDL   ] exiting mainloop and closing.
> [INFO   ] [Base        ] Leaving application in progress...

**Comment by Julian-O** [comment]
I am not one of the core devs. Just jumping in with inexpert advice.

SoundLoader looks to see what providers can play the sound. This list can be added to by installing extra plugins from the garden.

It can see two providers: audio_ffpyplayer, audio_sdl2. It filters out the ones that can't play a WAV file, and then chooses the first one from its internal list.

In this case, it seems that it chose SDL2.

It seems probable to me that the problem with the sound is with SDL2 - perhaps it is the Kivy code that calls SDL2, but that seems less likely.

I would be tempted to workaround this by hacking out the SDL2 registration, so it never chooses SDL2, and relies on audio_ffpyplayer instead.


Unregister it like this:

    from kivy.core.audio import SoundLoader
    SoundLoader._classes = [cls_ for cls_ in SoundLoader._classes if cls_.__name__ != "SoundSDL2"]

Note: "SoundSDL2" is what it is called on my Windows machine. Check for yourself by peeking at the class names in `kivy.core.audio.SoundLoader._classes`.

**Comment by matham** [comment]
As @Julian-O says, it's not likely a problem with kivy itself but with the sdl2 provider. The kivy way to select ffpyplayer as the audio provider is to set the environmental variable `KIVY_AUDIO` to `ffpyplayer`.

You don't say how you installed kivy. But if you used a wheel from pypi as opposed to installing sdl2 from apt and compiling kivy, that is perhaps the issue because the bundled sdl2 binary may not work well on your system. And since ffpyplayer uses sdl2 under the hood, it may have a similar issue. So if that is the case, I'd suggest you install ffpyplayer [from source](https://matham.github.io/ffpyplayer/installation.html). You could also try installing kivy from source or using kivy's apt package that uses your systems sdl2.

**Comment by estikf** [comment]
> As @Julian-O says, it's not likely a problem with kivy itself but with the sdl2 provider. The kivy way to select ffpyplayer as the audio provider is to set the environmental variable `KIVY_AUDIO` to `ffpyplayer`.
> 
> You don't say how you installed kivy. But if you used a wheel from pypi as opposed to installing sdl2 from apt and compiling kivy, that is perhaps the issue because the bundled sdl2 binary may not work well on your system. And since ffpyplayer uses sdl2 under the hood, it may have a similar issue. So if that is the case, I'd suggest you install ffpyplayer [from source](https://matham.github.io/ffpyplayer/installation.html). You could also try installing kivy from source or using kivy's apt package that uses your systems sdl2.

**Comment by estikf** [comment]
@matham I have tried to install ffpyplayer but I couldn't do it. I have read the documentation of ffpyplayer however I didn't understand the folder setting part. Please help me how to that :(
