### ISSUE TITLE
kivy install error

### ISSUE THREAD

**Issue by MichaelLi91** [kivy/kivy#6640]
* Python:
3.8
* OS:
windows10
* Kivy:
* Kivy installation method: 
python -m pip install kivy

I met this kind of error
Please help me.
![Screenshot_](https://user-images.githubusercontent.com/45660446/70379529-c2941800-1968-11ea-8e7a-1f9ccfb11033.png)
![Screenshot_1](https://user-images.githubusercontent.com/45660446/70379530-c45ddb80-1968-11ea-8314-9f57a736a118.png)

**Comment by tshirtman** [comment]
Wheels for python3.8 are not release yet, you can either use python3.7, or use test wheels built from master.
`pip install --extra-index-url https://kivy.org/downloads/simple kivy==2.0.0.dev0` Please note that in this case, it's not necessarily a stable version of kivy. and these wheels have been seldomly tested too, so you may run into specific issues, but it's appreciated if you test them and report any issue using them.
