### ISSUE TITLE
Manylinux wheel doesn't support full screen

### ISSUE THREAD

**Issue by matham** [kivy/kivy#6651]
Fullscreen on Ubuntu installed using manylinux wheel (from nightly) doesn't seem to work.

When setting fullscreen, the graphics drivers (nvidia) went crazy and didn't actually show anything. The monitor seemed to cycle between inputs and then stopped showing the desktop afterwards until I restarted. When I then installed kivy from source, everything worked as expected.

**Comment by tshirtman** [comment]
Do people really use native fullscreen though, i don't think anybody should, but on the other hand, we do support it, so it's indeed bad that it reacts this way. I could get out of the weird mode by using xrandr to reset my output to its normal mode (`xrandr --output eDP1 --mode 1920x1080` for me) but it's not easy to do that while only seeing a very small part of your screen.

**Comment by matham** [comment]
Why shouldn't you use native fullscreen? My app is running a projector that needs to project full screen.

**Comment by tshirtman** [comment]
borderless + screen size window is a lot less intrusive, basically what "auto" or "fake" does, whether you do it manually or not, it avoids changing screen mode just to start your app, and changing again if you switch focus to another app temporarily. It also plays a lot better with multiple screens.

**Comment by matham** [comment]
I tried borderless + screen size on ubuntu and it's not actually the same as real fullscreen. The former doesn't cover e.g. the application bar. Is that a know thing?

**Comment by cyberpsyche** [comment]
Is there any advance in this issue ? I also the met the problem of cannot switch to fullscreen mode in Ubuntu 18.04, but the code code run correctly in MacOS.   How can I solve this problem, does anybody could help ?  Thanks a lot !

**Comment by dynobo** [comment]
Facing the same issue on Ubuntu 20.10. As @matham stated already, with just borderless + screen-size I can't cover the status/application bar, which is quite important for my use-case, too.

**Comment by matham** [comment]
The workaround to this is to [install kivy from source](https://kivy.org/doc/stable/gettingstarted/installation.html#from-source).

**Comment by tshirtman** [comment]
so would this come from the version of libsdl we build against in manylinux wheels? or the way it is built?

**Comment by matham** [comment]
We distribute sdl2 in our wheel so we don't rely on libsdl. So either we don't build it correctly, we're missing some component, or building sdl2 on one system and using on another doesn't work well enough, despite manylinux taking extra care to only build against very core system binaries.

This is very similar to https://github.com/kivy/kivy/issues/6536 I bet.

**Comment by matham** [comment]
I initially faced this on Ubuntu 18, but I had the same issue on 20, recently.

**Comment by tshirtman** [comment]
yes, i was also wondering if it was the same kind of issue as with the mixer… it might be that sdl2 doesn't work properly when moved across systems…

I'm on ubuntu 20.04, i'll try "true" fullscreen later, i usually don't need it because there is no overlay in my window manager (i3), i tend to forget about the specifics of unity.

I can confirm that true fullscreen is problematic on my current machine with ubuntu, when installed from wheels.

**Comment by dynobo** [comment]
And I can confirm, that the issue is fixed when installing from source. Would be great to have the wheels fixed. :-)

**Comment by misl6** [comment]
@matham do you still have this hardware with nvidia graphics?

Seems that the `2.2.0rc1` wheel is not affected anymore (now we use a self-built version of sdl, with KMSDRM)

See: https://github.com/kivy/kivy/issues/7845#issuecomment-1544499427

**Comment by matham** [comment]
It is indeed fixed in the latest wheel!
