### ISSUE TITLE
Kivy drawing canvas memory usage

### ISSUE THREAD

**Issue by yevgeniyclaudio** [kivy/kivy#6653]
### Versions

* Python: 3.6
* OS: Android(windows, Linux)
* Kivy: 1.11.1
* Kivy installation method: pip3

### Description
Hello, friends! I have simple app with kivy, and drawing on canvas Ellipse element! But found something strange, when the size of Ellipse object increase to 30.000 on my phone the program crashes, I think because of memory out! And my question, how for example I can draw each pixel of my size screen (1024x768), or maybe another bigest resolution or there is no way to do that in kivy?

### Code and Logs

```python
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.graphics import (Color, Ellipse)
from kivy.clock import Clock
import random

class Canvas_w(Widget):
    def __init__(self, **kwargs):
        super(Canvas_w, self).__init__(**kwargs)
        i=0
        Clock.schedule_interval(self.draw, 0.00001)
    def draw(self,s):
        for i in range(0,100):
            with self.canvas:
                Color(1,1,1)
                a = Ellipse(pos = (random.randint(0,400),random.randint(0,400)), size = (1,1))
                a = None --------------> here try to delete object ,but it doesn't work
class MyApp(App): 
    def build(self):
        self.painter = Canvas_w()
        return self.painter
if __name__=="__main__":
    MyApp().run()

```

**Comment by tshirtman** [comment]
well, you are creating 2 instruction per frame and never removing them, so that quickly adds up, you can update or remove existing instructions if you keep a reference to them, look at the doc or ask for help in the proper channels.

**Comment by yevgeniyclaudio** [comment]
Thanks!
