### ISSUE TITLE
on_pre_open and on_pre_dismiss events in ModalView do not work

### ISSUE THREAD

**Issue by chavarinbonbyn** [kivy/kivy#6655]
#6279 

# Versions
* Python: 3.6.7
* OS: Ubuntu 18.04.3 LTS
* Kivy: 1.10.1
* Kivy installation method: Normal Ubuntu installation 

### Description
Events in ModalView:
Not working: on_pre_open and on_pre_dismiss
Working: on_open and on_dismiss

When calling the function placed bellow with the event on_pre_dismiss nothing is printed on the python run console. (Same with on_pre_enter)

When calling the function placed bellow with the event on_dismiss the expected text is printed, as expected. (Same with on_enter)

### Code and Logs
def open_modalview(self): ModalView(on_pre_dismiss=(lambda x: print('PRINT THIS FLAG !!!'))).open()

**Comment by pythonic64** [comment]
You're using Kivy 1.10.1, but events `on_pre_open` and `on_pre_dismiss` are added in version 1.11.0, so to use them install version 1.11.0 or higher.

**Comment by chavarinbonbyn** [comment]
I see. I have verified it. 

Thanks and regards.
