### ISSUE TITLE
Loader.image dont throw exceptions in case the image cant be loaded. It just bring white square widget at lower left corner and it prints in the log that "none type has no attribute tell"

### ISSUE THREAD

**Issue by Noor-Kalibbala** [kivy/kivy#6660]
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by Julian-O** [comment]
Duplicate if #7844 (even though this was earlier)
