### ISSUE TITLE
ID within python is still needed, [WARNING] Deprecated property "<StringProperty name=id>" of object

### ISSUE THREAD

**Issue by chavarinbonbyn** [kivy/kivy#6676]
### Versions

* Python: 3.6.7
* OS: 18.04.3 LTS
* Kivy: 1.11.0
* Kivy installation method: pip

### Description
I know there is a lot of confusion with "object'.ids and "object".id. I already know that they are different, the first one only works for widgets created in kivy language. The second one, only works within python language. It is very confusing I agree, I dedicated a lot of time to see the difference and to be able to understand them and how to use it in different contexts. That's why I think that the id in python side must be kept. Maybe "id" could be changed for something else but the behaviour and the property should remain. I'll give examples of the use next. 

################################ EXAMPLE 1 #################################
```py
''' This is an example when the id is very useful for the related callback function. By having the id of   
   an unknown number of added checkboxes in unknown places I can get where and which one is    
   called
'''
for loop_index in range(0. unknown_number):
    my_widget.add_widget(CheckBox(id='_'.join((valuable_info1, valuable_info2, int(for_loop_index)),                                             
                                                            size_hint_x=0.6,
                                                            on_release=check_box_callback))

def check_box_callback(instance):
        # Variables to extract information and perform stuff later within the function
        instance_valuable_info1, instance_valuable_info2, check_box_number = instance.id.split('_')
```
################################ EXAMPLE 2 #################################
```py
''' How are we supposed to get some filtered child widgets in an unknown generation of them, where 
   we only know the parent widget ?? 
'''

certain_checkboxes = [checkbox for checkbox in my_root_widget.children if checkbox.id == 'myString']
```

**Comment by matham** [comment]
You're using the property of kivy widgets named `id` in a way unrelated to its original meaning, rather you're using it just as an ordinary Python attribute.

Your code should look like:

```py
for loop_index in range(0. unknown_number):
    checkbox = CheckBox(size_hint_x=0.6, on_release=check_box_callback))
    my_widget.filter_prop = '_'.join((valuable_info1, valuable_info2, int(for_loop_index))
    my_widget.add_widget(checkbox)

def check_box_callback(instance):
        # Variables to extract information and perform stuff later within the function
        instance_valuable_info1, instance_valuable_info2, check_box_number = instance.filter_prop.split('_')
```

Please ask on Discord for follow up questions, because we use github primarily for bug reports, and this would be more a general Python question :)
