### ISSUE TITLE
TextInput is blocking the keyboard listener for android back button

### ISSUE THREAD

**Issue by yunus-ceyhan** [kivy/kivy#6686]
Kivy: master
p4a: master
Arch: arm64-v8
Test device: Xiaomi Mi Mix2
Version: Android 9 (pie)

The issue take place when you tap on a TextInput and open the keyboard, then when you close the keyboard the Window.bind(on keyboard) is not catching android back button key anmore.

For instance with this example i open the second screen and tap on android back button to turn back to main screen. It works as expected but whenever i tap on TextInput on the second screen the back button loses its functionality for turning back to main screen,  it seems keyboard blocks the keyboard listener to catch android back button key and makes back button unresponsive.

    from kivy.config import Config
    Config.set('kivy', 'exit_on_escape', 'False')
    
    from kivy.app import App
    from kivy.lang import Builder
    from kivy.core.window import Window
    from kivy.uix.screenmanager import ScreenManager
    
    
    Builder.load_string("""
    
    <Main>:
        id: scr_mngr
        Screen:                           
            name: 'main'
            BoxLayout:
                orientation: "vertical"
                size_hint: 1,1
                pos_hint: {'top':1}
                Label:
                    text: "Main Screen"
                    size_hint: 1,.1
                Button:
                    size_hint: 1,.1
                    text: "Go Second Screen"
                    on_press: root.go_second()
                Widget:
                    
        Screen:                           
            name: 'second'
            BoxLayout:
                orientation: "vertical"
                size_hint: 1,1
                pos_hint: {'top':1}
                Label:
                    text: "Second Screen"
                    size_hint: 1,.1
                TextInput:
                    size_hint: 1,.2
                    text: "TextInput"
                Widget:
    """)
    
    class Main(ScreenManager):
        def __init__(self, **kwargs): 
            super(Main, self).__init__(**kwargs)
            Window.bind(on_keyboard = self.keyboard)
            
        def keyboard(self,window,key,*args):
            print(str(key))
            if key == 27:
                self.transition.direction  = "right"
                self.current = "main"
                
        def go_second(self,*args):
            self.transition.direction  = "left"
            self.current = "second"
    
    class MyApp(App):    
        def build(self):
            return Main()
    
    if __name__ == '__main__':
        MyApp().run()

https://youtu.be/GN_YwHQ6Y0I

**Comment by Fak3** [comment]
This is probably the SDL2 issue, same as this one: https://github.com/kivy/python-for-android/issues/1903
It should be addressed in SDL2 2.0.11. You can try to change this PR to pick SDL2 from their repository, and build with it: https://github.com/kivy/python-for-android/pull/1779

**Comment by atheistrepublic** [comment]
I have implemented the same thing in my program.But this results in a keyboard popping up at the starting of the app.That is when the app opens on android there is a keyboard opening automatically.How can I stop this behaviour but still have the back button functionality?

**Comment by atheistrepublic** [comment]
This is the code i am using and the keyboard pops-up when the app starts.Why is the keyboard popping-up when the app starts and blocking the screen?
![Capture+_2020-03-09-21-47-49](https://user-images.githubusercontent.com/58817288/76236270-7059e000-6252-11ea-8f67-6a44a9738c40.png)
![Screenshot from 2020-03-08 17-41-44](https://user-images.githubusercontent.com/58817288/76236296-7a7bde80-6252-11ea-89f5-6cb6fdf0aa46.png)

**Comment by matham** [comment]
Please do not spam issues with unrelated comments things.

**Comment by yunus-ceyhan** [comment]
While trying to complate my new project i faced this issue again. I made a new approach to fix this issue. It is know when you touch statusbar or put app in background then return back, the back button working again. So after tracing logcats to find out what happens when app pauses i saw that it calls ```onWindowFocusChanged(False)```  then on resume it calls ```onWindowFocusChanged(True)```.  So i thought if i call those functions when textinput is unfocused it may solve the issue and it exacly did. To call those function i had to make sure if textinput is unfocused when i touch any part of the screen. There are probably a lots of way to detect that but it was hard for me so i eventually end up with  ```on_flip```  event to catch it, even thoug i really don't know what that event is for. :) Long story short this trick makes a temproary solution for that annoying issue..

```python
from kivy.config import Config
Config.set('kivy', 'exit_on_escape', 'False')

from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window
from kivy.uix.screenmanager import ScreenManager
from jnius import autoclass
from android.runnable import run_on_ui_thread
from kivy.properties import NumericProperty


Builder.load_string("""

<Main>:
    id: scr_mngr
    Screen:                           
        name: 'main'
        BoxLayout:
            orientation: "vertical"
            size_hint: 1,1
            pos_hint: {'top':1}
            Label:
                text: "Main Screen"
                size_hint: 1,.1
            Button:
                size_hint: 1,.1
                text: "Go Second Screen"
                on_press: root.go_second()
            Widget:
                
    Screen:                           
        name: 'second'
        BoxLayout:
            orientation: "vertical"
            size_hint: 1,1
            pos_hint: {'top':1}
            Label:
                text: "Second Screen"
                size_hint: 1,.1
            TextInput:
                id: text_input
                size_hint: 1,.2
                text: "TextInput"
            Widget:
""")

class Main(ScreenManager):
    state = NumericProperty(1)
    
    def __init__(self, **kwargs): 
        super(Main, self).__init__(**kwargs)
        Window.bind(on_keyboard = self.keyboard)        
        Window.bind(on_flip=self.detect_focus)
        
    def detect_focus(self,*args):
        if self.ids.text_input.focus == False and self.state == 0:
            self.fix_back_button()
            self.state = 1
            
        elif self.ids.text_input.focus == True and self.state == 1:
            self.state = 0
            
    @run_on_ui_thread            
    def fix_back_button(self,*args):
        activity = autoclass('org.kivy.android.PythonActivity').mActivity
        activity.onWindowFocusChanged(False)
        activity.onWindowFocusChanged(True)
        
    def keyboard(self,window,key,*args):
        print(str(key))
        if key == 27:
            self.transition.direction  = "right"
            self.current = "main"
            
    def go_second(self,*args):
        self.transition.direction  = "left"
        self.current = "second"

class MyApp(App):    
    def build(self):
        return Main()

if __name__ == '__main__':
    MyApp().run()
```

**Comment by Neizvestnyj** [comment]
@yunus-ceyhan I also found this error, if there are a lot of text fields, then when you directly switch from one field to another, text input stops working (it looks like the window focus remains **False**), so I would add your example like this:
```python
@run_on_ui_thread
def fix_back_button(self, *args):
    fix = True
    for text_field in self.text_fields: #  _self.text_fields_ - list with all TextField in project
        if text_field.focus is True:
            fix = False

    if fix is True:
        if platform == 'android':
            context.onWindowFocusChanged(False)
            context.onWindowFocusChanged(True)
```

**Comment by kengoon** [comment]
@Neizvestnyj instead of creating an array of textfield why not creat a `GeneralTextField` and inherit either kivy`TextInput` or kivymd `MDTextField` and then override the on_focus method with the fix_back_button function inside of it example below

```python
class GenTextField(TextInput):
    def on_focus(self, *args):
         if platform == "android":
            from kvdroid import activity
            from android.runnable import run_on_ui_thread

            @run_on_ui_thread
            def fix():
                activity.onWindowFocusChanged(False)
                activity.onWindowFocusChanged(True)
            if not value:
                fix()
```
this way should be way easier and all your textfield should come from that

**Comment by RobertFlatt** [comment]
I was able to replicate this with kivy==master but not with kivy==2.0.0
Also it requires p4a.branch = develop
Because p4a.branch = master and kivy==master gives ` AttributeError: 'org.kivy.android.PythonActivity' object has no attribute 'changeKeyboard'`

I was able to address the issue by returning a boolean after the `key == 27` per the documentation https://github.com/kivy/python-for-android/blob/develop/doc/source/apis.rst#handling-the-back-button

Android 10 requires that the back button/gesture returns the app the the Android home screen, therefore there must be a state in the app where back button/gesture is not consumed by the app.

The changes I made to get the OP working were:

1) Comment `#Config.set('kivy', 'exit_on_escape', 'False')` Also I think this made the test behavior misleading.

2) Add a state test and a boolean return:
```
    def keyboard(self,window,key,*args):
        print(str(key))
        if key == 27 and self.current != "main":
            self.transition.direction  = "right"
            self.current = "main"
            return True  
        else:           
            return False
```

I'd be interested to know if these work in your case.

**Comment by Osmar-Souza** [comment]
> @Neizvestnyjem vez de criar uma matriz de campo de texto, por que não criar um `GeneralTextField`e herdar kivy `TextInput`ou kivymd `MDTextField`e, em seguida, substituir o método on_focus pela função fix_back_button dentro do exemplo abaixo
> 
> ```python
> class GenTextField(TextInput):
>     def on_focus(self, *args):
>          if platform == "android":
>             from kvdroid import activity
>             from android.runnable import run_on_ui_thread
> 
>             @run_on_ui_thread
>             def fix():
>                 activity.onWindowFocusChanged(False)
>                 activity.onWindowFocusChanged(True)
>             if not args[1]:
>                 fix()
> ```
> 
> desta forma deve ser muito mais fácil e todo o seu campo de texto deve vir disso

@Kengooni it's work for me
