### ISSUE TITLE
Windows 10 install failure

### ISSUE THREAD

**Issue by deraeler** [kivy/kivy#6687]
### Versions

* Python: 3.8.1 installed for ALL USERS and appears to be running fine.
* OS: Windows 10 Pro
* Kivy: latest stable (python -m pip install kivy==1.11.1) per site instructions
* Kivy installation method: cmd line (Admin)

### Description

First ever install.
Can't even start learning Kivy - won't install.
I don't know where to locate log files.  I see nothing new in teh virtual environment where I ran the install from.
When run, the Uninstall command says there is nothing to uninstall...so confirmation that nothing installed.

### Code and Logs

(truncated output below. There are more errors but the output is quite lengthy)

(kivy_venv) C:\Users\steve\Envs\kivy_venv>python -m pip install kivy==1.11.1
Collecting kivy==1.11.1
  Downloading https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz (23.6MB)
     |████████████████████████████████| 23.6MB 6.8MB/s
Collecting Kivy-Garden>=0.1.4
  Downloading https://files.pythonhosted.org/packages/7d/68/decaee596ff8168a39432eb3949fc7c0be952ebb9467806823bffc165d48/kivy-garden-0.1.4.tar.gz
Requirement already satisfied: docutils in c:\users\steve\envs\kivy_venv\lib\site-packages (from kivy==1.11.1) (0.15.2)
Requirement already satisfied: pygments in c:\users\steve\envs\kivy_venv\lib\site-packages (from kivy==1.11.1) (2.5.2)
Collecting requests
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 990kB/s
Collecting certifi>=2017.4.17
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
     |████████████████████████████████| 163kB ...
Collecting idna<2.9,>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 1.3MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
     |████████████████████████████████| 133kB 6.4MB/s
Collecting chardet<3.1.0,>=3.0.2
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
     |████████████████████████████████| 143kB 6.8MB/s
Building wheels for collected packages: kivy, Kivy-Garden
  Building wheel for kivy (setup.py) ... error
  ERROR: Command errored out with exit status 3221225477:
   command: 'C:\Users\steve\Envs\kivy_venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\steve\\AppData\\Local\\Temp\\pip-install-_is3vi6m\\kivy\\setup.py'"'"'; __file__='"'"'C:\\Users\\steve\\AppData\\Local\\Temp\\pip-install-_is3vi6m\\kivy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\steve\AppData\Local\Temp\pip-wheel-lme1c836' --python-tag cp38
       cwd: C:\Users\steve\AppData\Local\Temp\pip-install-_is3vi6m\kivy\
  Complete output (531 lines):
  Using setuptools
  User distribution detected, avoid portable command.
  Using this graphics system: OpenGL
  WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

  b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

  WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

  b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

  WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

  b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

  ERROR: Dependency for context.pyx not resolved: config.pxi
  ERROR: Dependency for compiler.pyx not resolved: config.pxi
  ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
  ERROR: Dependency for fbo.pyx not resolved: config.pxi
  ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
  ERROR: Dependency for instructions.pyx not resolved: config.pxi
  ERROR: Dependency for opengl.pyx not resolved: config.pxi
  ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
  ERROR: Dependency for shader.pyx not resolved: config.pxi
  ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
  ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
  ERROR: Dependency for texture.pyx not resolved: config.pxi
  ERROR: Dependency for vbo.pyx not resolved: config.pxi
  ERROR: Dependency for vertex.pyx not resolved: config.pxi
  ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
  ERROR: Dependency for cgl.pyx not resolved: config.pxi
  ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
  ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
  ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
  ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
  ERROR: Dependency for svg.pyx not resolved: config.pxi
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  creating build

```

**Comment by matham** [comment]
https://github.com/kivy/kivy/issues/6563#issuecomment-560039155

**Comment by deraeler** [comment]
I don't understand what this means.

The "release" is obviously out there....otherwise why would the site
instruct everyone to perform this action?

What am I supposed to do with this?

This is the only "Help" option available....did you really just fire off
this email and close my issue?

**Comment by matham** [comment]
Sorry, I was hoping you'd understand the answer for the issue I linked.

While we did make a 1.11.1 release, we typically create pre-compiled wheels for each Python version. However, since the last release happened before py3.8 was released, no wheels for 3.8 was made at the time.

So when you try to install kivy for 3.8, instead of getting a pre-compiled wheel, you get a zip, which pip tries to compile on your system. But that fails because your system has not installed the deps to be able to compile kivy.

So the solution is to install kivy from master by running the command in the post I linked to.

I hope that clarifies it.

**Comment by deraeler** [comment]
OK - thanks, this is much closer to the mark.
I do very much appreciate your stepping up to help.

So when I hit that link I see what looks like an ftp link to a "wheel" file?

Links for Kivy-examplesKivy_examples-2.0.0rc1-py2.py3-none-any.whl
<https://kivy.org/downloads/ci/win/kivy/Kivy_examples-2.0.0rc1-py2.py3-none-any.whl>


clicking on it does nothin however.

So breaking down this instruction:
pip install kivy[base] kivy_examples --pre --extra-index-url

I don't see what to substitute here....the above link is only for the
examples - even if it did work....

What is the URL for the kivy base?


Given this <install> syntax, what would you use?
(I don't even see the '--pre' option listed)

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

--extra-index-url option requires 1 argument

**Comment by matham** [comment]
The exact command to use in the command line is `pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/`. When you run it, this will download and install kivy and kivy-examples as it it currently is in master (https://kivy.org/doc/master/installation/installation-windows.html#nightly-wheels).

You see more clearer instructions and background info for kivy master at https://kivy.org/doc/master/installation/installation-windows.html.

I'd also suggest to ask for further help on the [discord channel](https://kivy.org/#support) because there are many people there who are available help, and we primarily use github issues for bugs so much fewer people read or respond to github issues. Feel free to ping me on discord there if you still have issues.

**Comment by deraeler** [comment]
Cool.  The
https://kivy.org/doc/master/installation/installation-windows.html  site is
what got me here - LOL.

Looks like this worked - thanks!

Attempting to install the latest stable build from
https://kivy.org/doc/master/installation/installation-windows.html   failed
- I'm not clear on why this one works and that one didn't - seems to have
to do with matching the Python 3.8.1 install (I did to have the latest
Python)....if I understand correctly, by following the instructions there I
was requesting a version that doesn't exist.

I'm also struggling with the virtual environments - I get the concept, and
I ran the kivy install from within my "activated" kivy VE, but I"m not
clear on how to pair up a specific Python version with a specific Kivy
version (ie:  installing one "within" the other, or the other way around).

This is kind of a test run as I"m looking into doing a Raspberry Pi project
where I will be repeating all of this on Linux, but as the project is a few
years old I wanted to test as much I could first, and also start learning
the languages/frameworks.

So I'll try to use the discord channel - the site link I went to before - I
presume you're referring to the User Forums for support/questions?
It's an empty page (and the Blog page is pretty sparse). User Forums page
shows just a Help link which takes you to Google Groups Help.  Searching
Google Groups I find a number of links for 'discord':  (217 matches)

Any specifics to help drill down?

[image: image.png]

**Comment by matham** [comment]
>The https://kivy.org/doc/master/installation/installation-windows.html  site is what got me here - LOL.

On that page it shows how to install from pypi (where pip gets stuff from by default). However, since we have no 3.8 release wheel uploaded to pypi, it fails. The command that I gave you is listed on that page as an alternate installation to install from master hosted on our server, for which we do have 3.8 wheels.

>but I"m not clear on how to pair up a specific Python version with a specific Kivy version

You shouldn't have to do this manually - paring kivy to a specific python version. All you normally do is check whether there's a release wheel for your python version (https://pypi.org/project/Kivy/#files) and if so pip will install it normally. If it doesn't exist, that's when you have to tell pip to find it elsewhere if it's available (e.g. on our server).

>So I'll try to use the discord channel

The link is all the way at the end of the page I linked earlier: https://chat.kivy.org/

**Comment by laarchenko** [comment]
> The exact command to use in the command line is `pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/`. When you run it, this will download and install kivy and kivy-examples as it it currently is in master (https://kivy.org/doc/master/installation/installation-windows.html#nightly-wheels).
> 
> You see more clearer instructions and background info for kivy master at https://kivy.org/doc/master/installation/installation-windows.html.
> 
> I'd also suggest to ask for further help on the [discord channel](https://kivy.org/#support) because there are many people there who are available help, and we primarily use github issues for bugs so much fewer people read or respond to github issues. Feel free to ping me on discord there if you still have issues.

Thank you, your solution works)

**Comment by sudishrestha** [comment]
Downloading the recent wheel from https://kivy.org/downloads/ci/win/kivy/ and installing via code 'python -m pip install filename.whl' worked for me
