### ISSUE TITLE
Problem with running kivy, kivy_example working

### ISSUE THREAD

**Issue by faulknerrainford** [kivy/kivy#6691]
### Versions

* Python: 3.7.32
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: pip

### Description
Hi

I have installed kivy on Pycharm on Windows 10 and my interpreter is using pythonw.py. I can install and run the kivy_example with no problems.

However when I run: from kivy.app import App
in the console it returns the following error:
[ERROR  ] [Core        ] option --mode not recognized
Kivy Usage: pydevconsole.py [OPTION...]::

As stated I have changed the interpreter but the problem still persists.
Any suggestions?

### Code and Logs

```
from kivy.app import App
```
```
[INFO   ] Logger: Record log in C:\Users\*****\.kivy\logs\kivy_20-01-13_35.txt
[ERROR  ] Core: option --mode not recognized

```

**Comment by Anon6372098** [comment]
Can you run `pip freeze` and copy the results here?

**Comment by matham** [comment]
This seems like a pycharm issue.
