### ISSUE TITLE
Textinput keyboard_mode: 'managed' doesn't fires false on_focus events, only true

### ISSUE THREAD

**Issue by ronyeh3** [kivy/kivy#6692]
### Versions

* Python: 2.7
* OS: Ubuntu 18
* Kivy: 11.1
* Kivy installation method: pip

### Description
Textinput
    keyboard_mode: 'managed' 

when keyboard is "manage",clicking inside the text input triggers the on_focus event (with true value), and disable the keyboard popup, like it should.
but when clicking outside the area , the on_fucus event doesn't get fired(with false value), although unfocus_on_touch is true.

### Code and Logs

maybe later ill add example code

```

**Comment by Julian-O** [comment]
Can you please confirm if this still happens in Kivy 2.2.1?
