### ISSUE TITLE
installation issue - error on clock for 'kivy._clock"

### ISSUE THREAD

**Issue by mar454545** [kivy/kivy#6693]
kivy 2.0.0 for raspberry pi 3b.
python 3.7.3
cython 0.29.14

Hi,

i re-installed kivy 15 Jan, when running the 'hello world' test programme the following occured...

pi@raspberrypi:~/kivy $ python3 main.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_20-01-16_14.txt
[INFO   ] [Kivy        ] Installed at "/home/pi/kivy/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "main.py", line 4, in <module>
     from kivy.app import App
   File "/home/pi/kivy/kivy/app.py", line 411, in <module>
     from kivy.base import runTouchApp, async_runTouchApp, stopTouchApp
   File "/home/pi/kivy/kivy/base.py", line 28, in <module>
     from kivy.clock import Clock
   File "/home/pi/kivy/kivy/clock.py", line 381, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ModuleNotFoundError: No module named 'kivy._clock'

i re-installed several times, ensured cython is update to etc, but the situation is still present. the usual issue is that i previously installed in December and this issue did not occur.

apologies if this is more of a support issue, however, i am located in china and as such cannot email to google accounts or use Discord. i tried both prior to writing this, however it does seem like a bug.

regards
Mark

**Comment by SYEDFAIZAN1812** [comment]
i am getting same kind of issue after installing latets kivy from here https://kivy.org/doc/stable/installation/installation-rpi.html  on pi3 rasppbian jessie with python 3.7

**Comment by matham** [comment]
Basically, as the error says, it means you didn't compile kivy. When you install kivy, python will compile it, but either you're pulling the wrong python or you didn't install it.

Please follow the updated docs at https://kivy.org/doc/master/installation/installation-rpi.html to install master.

**Comment by mar454545** [comment]
hi,

Thanks. 

Mark

**Comment by manijadav** [comment]
help me in solving this sir
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "C:/Users/Dell/Desktop/kivy/CoronaCountApp_kivy.py", line 2, in <module>
     from kivy.app import App
   File "C:\Users\Dell\Desktop\kivy\kivy\app.py", line 411, in <module>
     from kivy.base import runTouchApp, async_runTouchApp, stopTouchApp
   File "C:\Users\Dell\Desktop\kivy\kivy\base.py", line 28, in <module>
     from kivy.clock import Clock
   File "C:\Users\Dell\Desktop\kivy\kivy\clock.py", line 381, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ModuleNotFoundError: No module named 'kivy._clock'

**Comment by manijadav** [comment]
> help me in solving this sir
> [ERROR ] [Clock ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
> Traceback (most recent call last):
> File "C:/Users/Dell/Desktop/kivy/CoronaCountApp_kivy.py", line 2, in
> from kivy.app import App
> File "C:\Users\Dell\Desktop\kivy\kivy\app.py", line 411, in
> from kivy.base import runTouchApp, async_runTouchApp, stopTouchApp
> File "C:\Users\Dell\Desktop\kivy\kivy\base.py", line 28, in
> from kivy.clock import Clock
> File "C:\Users\Dell\Desktop\kivy\kivy\clock.py", line 381, in
> from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent,
> ModuleNotFoundError: No module named 'kivy._clock'
