### ISSUE TITLE
ColorProperty isn't visible on documentation

### ISSUE THREAD

**Issue by Titus933** [kivy/kivy#6705]
Everything the title says. See https://kivy.org/doc/stable/api-kivy.properties.html vs https://github.com/kivy/kivy/blob/stable/kivy/properties.pyx#L1982 .

Is this a bug with Sphinx or something? This ColorProperty is an important QoL feature, it makes me very sad to only learn about it now (and by looking at source code instead of documentation).

Thanks in advance for fixing this, hopefully no other useful feature goes unnoticed!

(Written by @Cheaterman )

**Comment by matham** [comment]
Huh, I didn't know about this either. I'm guessing it just needs to be added to `__all__`.

**Comment by Cheaterman** [comment]
Oooh yeah, that's likely it! Thanks in advance Matham :-)

**Comment by Cheaterman** [comment]
f988af3 closes this.
