### ISSUE TITLE
Window minimize event not running when Window.borderless = 1 (disabled)

### ISSUE THREAD

**Issue by jcradzwill** [kivy/kivy#6707]
### Versions

* Python: 3.7.4
* OS: Windows 10
* Kivy: latest version
* Kivy installation method: pip

### Description

This issue was found when developing a Kivy desktop application on Windows 10.

When the Window.borderless option is set to 0, I am able to minimize the App window by clicking the App icon in the task bar. However, when the Window.borderless option is set to 1, and the border is disabled, I cannot minimize the window by clicking the App icon in the task bar (nothing happens). 

It appears that this issue is driven by the fact that the 'windowminimized' event is NOT running at all when borderless is set to 1 within the event loop of the window SDL2 Kivy Source code located here: Python37-32\Lib\site-packages\kivy\core\window\window_sdl2.py.

Here is the App Icon button being clicked in the task bar when the App is running:

![App Icon](https://user-images.githubusercontent.com/43111778/72910805-4d04c100-3cf6-11ea-8ecd-efbc73199096.PNG)

Here is the test code I wrote into the Window SDL2 source code to print the events as they execute:

![WindowSDL2 Source Code](https://user-images.githubusercontent.com/43111778/72911807-e7193900-3cf7-11ea-8819-f541206ee37b.PNG)

Scenario 1: 

When the App is open and the App icon in the task bar is clicked, here are the events that run when Window.borderless is set to 0 (enabled). As you can see below, the 'windowminimized' event from Window SDL2 source code runs.

![Border_Enabled](https://user-images.githubusercontent.com/43111778/72910017-25f9bf80-3cf5-11ea-96fa-5b83ea8461cb.PNG)

Scenario 2 (ISSUE):

When the App is open and the App icon in the task bar is clicked, here are the events that run when Window.borderless is set to 1 (disabled). As you can see below, the 'windowminimized' event from Window SDL2 source code does NOT run. This explains why the App window won't minimize when the App icon is clicked in the task bar while the border is disabled. 

![Border_Disabled](https://user-images.githubusercontent.com/43111778/72910213-7244ff80-3cf5-11ea-8a80-d3369d95f14b.PNG)

How do I get the 'windowminimized' event to run in a situation where borderless is set to 1 and the App icon in the task bar is clicked? This appears to be a bug in the Window SDL2 source code. This event must run if the developer wants to remove the border and create their own custom title bar with minimize, maximize, close, etc. features. The developer needs to be able to distinguish between a 'windowfocuslost' and 'windowminimized' event when the border is disabled on the window and the App icon is clicked by the user in the task bar.

**Comment by Julian-O** [comment]
Can you please confirm if this still happens with Kivy 2.2.1?
