### ISSUE TITLE
The installation docs are a bit ambiguous.

### ISSUE THREAD

**Issue by heronils** [kivy/kivy#6710]
[The windows installation docs](https://kivy.org/doc/stable/installation/installation-windows.html#install-win-dist) are a bit ambiguous. Could some zen doc warrior revisit it?

The following could be clarified:

* The formatting does not reflect well which steps are optional and which are not.
* It talks about _virtualenv_ but Python has _venv_ included. Do i really need to install _virtualenv_? Same true for _setuptools_. I thought pip does this. And isnt installing wheels also part of pip? So, why do i need to install _wheel_?
* _docutils_, _pygments_, _pypiwin32_ - What do these dependencies do? Eg. _docutils_, sounds like a documentation related module, why do i need it?
* `kivy_deps.sdl2==0.1.* kivy_deps.glew==0.1.*` - i guess these are the actual dependencies?
* A sentence describing what _sdl2_, _glew_, and _angle_ is, would be appreciated (yes, google is helpful here, but i think it would fit well do have short definitions in the Kivy context)
* Can one install both _angle_ and _glew_ or will it break things?
* It says `python -m pip install kivy==1.11.1` - but the [download page](https://kivy.org/#download) says that the current version is 1.11.0.
* Do i need to have a compiler installed? And where do i get it? If it is this Microsoft compiler, its installer tells me that i have to download many Gigabytes - thats **huge**, is this correct? Because, if i am not wrong, there are compilers out there which are sized a few kilobytes.
* How does one _uninstall_ Kivy and its dependencies?

**Comment by matham** [comment]
You're looking at the docs from stable, please take a look at the docs from master which has been significantly cleaned up: https://kivy.org/doc/master/installation/installation-windows.html

**Comment by matham** [comment]
But also, some of these are general python questions, which is not specific to kivy or to windows and so the windows install page is probably not an appropriate place to answer them.

**Comment by heronils** [comment]
Thanks for this Link. That is much easier to grasp :-)

I have revisited that document and have pulled the changes in #6712. I hope you like it.

**Comment by heronils** [comment]
Thanks. Forgot to close it.
