### ISSUE TITLE
Kivy3.app (OS X) pip install fails due to missing ssl module

### ISSUE THREAD

**Issue by Niehztog** [kivy/kivy#6723]
### Versions

* Python: Python 3.6.5 (packaged inside Kivy3.app)
* OS: macOS High Sierra 10.13.6 (running in virtualbox)
* Kivy: 1.11.0
* Kivy installation method: "Using The Kivy.app" as stated in https://kivy.org/doc/stable/installation/installation-osx.html#using-the-kivy-app

### Description

Hello. I successfully downloaded and installed the Kivy3 App in my macOS installation using the steps described in the above documentation link. As stated in the docs I should be able to install python modules using the following command:
```kivy3 -m pip install kivymd```

However , this command fails due to missing ssl module in Kivy3.app:

### Code and Logs

```
kivy3 -m pip install kivymd
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting kivymd
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/kivymd/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/kivymd/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/kivymd/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/kivymd/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/kivymd/
  Could not fetch URL https://pypi.python.org/simple/kivymd/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/kivymd/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement kivymd (from versions: )
No matching distribution found for kivymd
```

Whats the preferred method for installing additional required python libraries in the Kivy3 OS X App? Please either fix the OS X App or update the docs.

**Comment by matham** [comment]
https://github.com/kivy/kivy/issues/6719#event-3013620727 seems to have figured it out, although I'm not sure what specifically they did to fix it. It'd be worth to write out exactly what the solution is when you find it.

**Comment by Niehztog** [comment]
@matham thanks for pointing that out. The following console command fixed the problem:
```
brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
```
actually it didn't have anything to do with kivy. This bugreport can be closed
