### ISSUE TITLE
video player event 

### ISSUE THREAD

**Issue by centurions** [kivy/kivy#6726]
Hi thank you for your great work !!!

Is there any example for on_frame event in videoplayer ? How to use this event for processing images 
 (get current frame)?

**Comment by Cheaterman** [comment]
I don't think there's any example. About getting the current frame, you should be able to access the Video (or possibly VideoPlayer) Texture object, but that's an OpenGL texture and its internal data may not be reachable by your CPU. If you want to process the image yourself before re-uploading it to the texture, you could maybe `save()` the texture data into a BytesIO object, process that data, then reupload it into the Texture using `blit_buffer()`.

Warning - this whole operation will be extremely slow, and you're much better off using a GLSL shader (EffectWidget) on top of your Video widget instead.
