### ISSUE TITLE
Screen Manager previous screen issue

### ISSUE THREAD

**Issue by Cobra91151** [kivy/kivy#6728]
Hello!

I use Screen Manager in my Android application, I have about 40 screens. For example, I am on the 3rd screen then switching to 37 screen, when I am trying to get back to the previous screen: `self.manager.previous()` it displays the previous screen as 36. It should be the 3rd screen as the previous not 36. How to get the previous screen not from the list, but from the runtime? Thanks.

**Comment by matham** [comment]
As documented, `previous` doesn't give the last visible screen, but the last in the list. For support, please ask on discord/mailing list because github is intended just for bugs.
