### ISSUE TITLE
iOS features slide-over and split-view fail to work with kivy

### ISSUE THREAD

**Issue by BillBridge** [kivy/kivy#6731]
### Versions

* Python: 3.7.6
* OS: macOS Catalina 10.15.3
* Kivy: 1.11.1
* Kivy installation method:

### Description

I managed to build a Kivy app for iOS and am testing it with Xcode on an iPad Pro 11" iOS 13.3 simulator. The split-view and slide-over view features of iOS works great on two generic apps. Unfortunately, when I try this for one generic and my Kivy app, it does not work. The kivy app will not be aligned next to or on top of the other application.

### Code and Logs
Config settings are:
    Config.set('kivy', 'desktop', 1)
    Config.set('graphics', 'fullscreen', 'auto')
    Config.set('graphics', 'position', 'auto')
    Config.set('graphics', 'resizable', 1)
    Config.set('graphics', 'borderless', 0)

[Schermopname 2020-02-14 om 13.57.56.mov.zip](https://github.com/kivy/kivy/files/4204564/Schermopname.2020-02-14.om.13.57.56.mov.zip)

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by misl6** [comment]
Hi, can you please try the latest `kivy==master` ?
I recently introduced this one: https://github.com/kivy/kivy/pull/6589
Without using the settings you specified, with latest `kivy==master` and `kivy-ios==master`, you can do it by setting the properly flags over `XCode` and the `IOS_IS_WINDOWED` env variable in `main.m`

**Comment by BillBridge** [comment]
Thanks for your quick reply.
Please could you describe the steps to take a bit more in detail?
- Do I have to update my existing kivy installation (1.11.1) to master? How should I do that?
- Do I need to build a new kivy-ios using master? by just changing the definition in the requirements.txt file?
- Removing the Config.set lines from my code.
- And finally changing the IOS_IS_WINDOWED env variable in the file main.m in my Xcode environment?

**Comment by misl6** [comment]
If You already have the `IOS_IS_WINDOWED` env variable in the `main.m` file you're already on the latest `kivy-ios` version, so first thing to check is this one.

If you prefere, considering this one is more like a #support request, I'm available via kivy's discord server.

**Comment by BillBridge** [comment]
Thanks to the help of misl6 solved the issue. Just for the sake of completeness:
It relates to the settings in Xcode.
In main.m env variable IOS_IS_WINDOWED should be True
Settings in the General Tab of the Xcode project in section Deployment info:
1.  All device orientations shall be activated; 
2. In Status Bar Style activate Hide status bar and de-activate Require full screen

In section App icons and Launch Images a Launch Screen File shall be selected (or added if there is no one available yet).

Under the Info Tab the items under Supported interface orientations (IPad) shall have a orientation selected.
