### ISSUE TITLE
Logger tree manipulations break its parent/child structure

### ISSUE THREAD

**Issue by pakal** [kivy/kivy#6733]
### Versions

* Python: Python3.7
* OS: Windows
* Kivy: current sources

### Description

The logger tree manipulations in kivy/logger.py break a number of invariants of the logging system. It creates incoherences in the parent links and names of the different logger levels, (logging_tree.printout() displays it), and it prevents users from normally separating kivy-related logs from other logs (eg. to silence initialization information).

Why not just leave kivy logs under "kivy" namespace, and let the root logger be configured by user to aggregate the logs from all sources?

**Comment by Cheaterman** [comment]
I actually think you're onto something here. I agree Kivy shouldn't be polluting the root logger - I guess you're talking about this: https://github.com/kivy/kivy/blob/master/kivy/logger.py#L326 ?

Removing the line doesn't seem to change anything at all here, although the commit in which @tito added it says the following:
```
logger: force the logging.root to use the kivy Logger instance. This prevent infinite loop.
```

I'm not quite sure what the infinite loop would be. @tito , still remember after 7 years? :grin:

**Comment by Cheaterman** [comment]
For reference, that's what I get by default:
```
<--""
   Level INFO
   Handler <LoggerHistory (NOTSET)>
   Handler <FileHandler (NOTSET)>
   Handler <ConsoleHandler <stderr> (NOTSET)>
     Formatter <kivy.logger.ColoredFormatter object at 0x7f88266f5090>
   |
   o !-"kivy"
       Broken .parent redirects messages to 'root' instead
       Level INFO
       Handler <LoggerHistory (NOTSET)>
       Handler <FileHandler (NOTSET)>
       Handler <ConsoleHandler <stderr> (NOTSET)>
         Formatter <kivy.logger.ColoredFormatter object at 0x7f88266f5090>
```

And with the line removed:
```
<--""
   Level INFO
   Handler <LoggerHistory (NOTSET)>
   Handler <FileHandler (NOTSET)>
   Handler <ConsoleHandler <stderr> (NOTSET)>
     Formatter <kivy.logger.ColoredFormatter object at 0x7f0195a868d0>
   |
   o !-"kivy"
       Broken .parent redirects messages to 'root' instead
       Level INFO
       Handler <LoggerHistory (NOTSET)>
       Handler <FileHandler (NOTSET)>
       Handler <ConsoleHandler <stderr> (NOTSET)>
         Formatter <kivy.logger.ColoredFormatter object at 0x7f0195a868d0>
```

Can't deny the latter looks more sane :grinning:

**Comment by pakal** [comment]
I guess infinite loops might happen due to this line : https://github.com/kivy/kivy/blob/ede9bd1b806619dda022ab438964ce1b48645521/kivy/logger.py#L368

But imho this redirection of stderr to logging is also quite dangerous - we can't use an stderr StreamHandler without creating such infinite loop. I guess stdout/stderr should always be let "safe" (except in unit-tests for capturing), or be a voluntary action from project owner.

I don't know why this redirection was initially setup ; on android, standard streams end up into Logcat, and on desktop platforms to the console output, it should be fine as for any GUI framework.

**Comment by matham** [comment]
https://github.com/kivy/kivy/issues/4113

**Comment by Cheaterman** [comment]
Good reference @matham, but what do we do from here? I'm not sure it's a good idea to leave things as they are, it doesn't look very sane IMHO?

**Comment by pakal** [comment]
I think I understand the "framework vs library" point, and it shouldn't be a problem for Kivy to take control of logging, but why would it need this inversion of root/kivy loggers? As long as "propagate" is true, and handlers are applied to the ROOT logger, all should work fine, thus not breaking any invariant of this logging graph.

There could also be LOGGING configuration dict allowing project maintainer to tweak loggers and others, but for now disabling kivy manipulations (with KIVY_NO_CONSOLELOG etc.) is probably sufficient to do that by oneself.

The unconditional redirection of stderr is rather dangerous too, maybe we could make it conditional?

**Comment by Julian-O** [comment]
This has been dealt with in 2022.

Closing as completed.
