### ISSUE TITLE
font_name not working

### ISSUE THREAD

**Issue by Am1t17** [kivy/kivy#6735]
### Versions

* Python: 3.8
* OS: Windows
* Kivy:
* Kivy installation method:

### Description
I'm trying to show messege in hebrew font.
the thing is i can display in hebrew while im using python code, but its not working with in kv file..
i guess i do somthing wrong with the kv file, can u help me plz

### Code and Logs

file.kv
WindowManager:
    MainWindow:
    secondWindow:

<MainWindow>:
    name: "main"

    GridLayout:
        cols:1
        GridLayout:
            cols:2

            Label:
                text: "password: "

            TextInput:
                id: passw
                multiline: False

        Button:
            font_name: "VarelaRound-Regular.ttf"
            text:"עמית"
            on_release: 
                app.root.current = "second" if passw.text == "amit" else "main" 
                root.manager.transition.direction = "left"

<secondWindow>:
    name: "second"

    Button:
        text: "Go Back"
        on_release: 
            app.root.current = "main"
            root.manager.transition.direction = "right"

main.py
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager,Screen

class MainWindow(Screen):
    pass

class secondWindow(Screen):
    pass

class WindowManager(ScreenManager):
    pass

kv = Builder.load_file("my.kv")

class MyMainApp(App):
    def build(self):
        return kv

if __name__ == "__main__":
    MyMainApp().run()

code working without ky file

import kivy
from kivy.app import App
from kivy.uix.textinput import TextInput
class TestApp(App):
    def build(self):
        return TextInput(text='עמית',font_name="VarelaRound-Regular.ttf")
myapp=TestApp()
myapp.run()

**Comment by matham** [comment]
Please be more specific about "what's" not working. Is there a a error? Please provide the full log.

**Comment by matham** [comment]
I just tested and it works for me.
