### ISSUE TITLE
Label does not display text if number of lines exceed 910 

### ISSUE THREAD

**Issue by SanishKoshi** [kivy/kivy#6738]
### Versions

* Python: Python 3.6.8
* OS: Centos 7
* Kivy: 1.11.1
* Kivy installation method: pip

### Description

I am trying to put some text in a scrollable label when a button is pressed. I find that if the number of lines of the text exceed 910  or so, the text does not get transferred to the label. In the below example, the button "Put 200 lines" works, but the button "Put 2000 lines" does not work. The only difference between the  function is put_200_lines and put_2000_lines is that the latter has a "for loop" of  2000  instead of 200. 

### Code and Logs

```python
import kivy
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout


	
class MyBox(BoxLayout):
	
	def put_200_lines(self):
		self.ids.script_file_contents.text =""
		for x in range(1,200):
			self.ids.script_file_contents.text = self.ids.script_file_contents.text + "This is line " + str(x) + " \n"


	def put_2000_lines(self):
		self.ids.script_file_contents.text =""
		for x in range(1,2000):
			self.ids.script_file_contents.text = self.ids.script_file_contents.text + "This is line " + str(x) + " \n"


presentation = Builder.load_string("""

<MyBox>:
	
	BoxLayout:
		orientation:'vertical'
		Button:
			text: 'Put 200 lines'
			size_hint:(1, 1)
			pos:self.pos
			size_hint:(1, 0.2)
			on_release:  root.put_200_lines()
	
		Button:
			text: 'Put 2000 lines'
			size_hint:(1, 1)
			pos:self.pos
			size_hint:(1, 0.2)
			on_release:  root.put_2000_lines()
				

		ScrollView:
			do_scroll_x: False
			do_scroll_y: True
			Label
				id: script_file_contents
				text: ''
				size_hint:None,None
				size: self.texture_size
	 

""")

class MyApp(App):
	def build(self):
		return MyBox()


if __name__ == '__main__':
	MyApp().run()


```

**Comment by pythonic64** [comment]
I think that you hit texture size limit. For displaying of large text you can use `RecycleView` with `Label` as `viewclass`. Also, see this old flower https://github.com/kivy-garden/garden.scrolllabel .
