### ISSUE TITLE
Search Box with suggestions in kivy and python

### ISSUE THREAD

**Issue by hussam132** [kivy/kivy#6740]
I didn't knew if this's the right place to ask this question but I want to make search bar with kivy and python that's search in the text in the buttons and the labels with suggestions and when click search it's shows me the same the buttons and the labels that contain the same text so I want any idea for functions should I use

**Comment by matham** [comment]
This is the third issue in the last couple of weeks that you opened that is clearly a support request, even after we made clear for each one that we don't handle support requests on github.

Please don't open further support issues here.
