### ISSUE TITLE
How to stop keyboard from popping up when the app opens

### ISSUE THREAD

**Issue by atheistrepublic** [kivy/kivy#6752]
I have created an app and used window.bind(on_keyboard=self.some_function) as i am listening for keyboard event press.Everything is working but when the app opens up a keyboard is popping up automatically.I don't want the keyboard to open up auomatically when the app starts.Is there a way to do that?
Here is the code i'm using:
`class SecondWindow(Screen):
def __init__(self,**kwargs):
        super(SecondWindow,self).__init__(**kwargs)
        self.screen_list=[]
        Window.bind(on_keyboard=self.Android_back_click)
    
def Android_back_click(self,window,key,*largs):
        if key == 27:
            print(self.manager.current)
            if(self.manager.current=='main'):
                         print("Hello")`

**Comment by atheistrepublic** [comment]
This seems to be a bug report,kindly consider reopening this issue.
Here is the code i am using and screenshot of keyboard popping up on android automatically.
![Screenshot from 2020-03-08 17-41-44](https://user-images.githubusercontent.com/58817288/76162556-d700d000-6164-11ea-9e8b-7e2099df9269.png)
![Capture+_2020-03-08-17-45-45](https://user-images.githubusercontent.com/58817288/76162560-dd8f4780-6164-11ea-8b62-31649b439f97.png)

**Comment by matham** [comment]
As mentioned, please ask on the discord support channels for support. Please only request to open this issue again if the people there say this is a bug in kivy. 

This seems to be much more likely a problem with how you're binding `on_keyboard` rather than a bug in kivy.
