### ISSUE TITLE
Spinner doesn't show Persian (Arabic) text

### ISSUE THREAD

**Issue by AMJoshaghani** [kivy/kivy#6753]
### Versions

* Python: 3.7
* OS: Arch (Linux)
* Kivy: 1.11.1
* Kivy installation method: with Pip

### Description

Kivy kivy.uix.spinner does show arabic text in [].
It will not repair with changing font. font changing only helps to repair original button text.
please help

### Code and Logs

```python
import arabic_reshaper
from bidi.algorithm import get_display
def show(self, text):
    return get_display(arabic_reshaper.reshape(text))

# kv:
    Spinner:
        size_hint: None, None
        size: 100, 44
        pos_hint: {'center': (.5, .5)}
        text: root.show('انتخاب نشده', self=None)
        values: [root.show(i) for i in ['سه', 'دو', 'یک']]

```

**Comment by matham** [comment]
https://medium.com/@ahmedfgad/supporting-arabic-alphabet-in-kivy-for-building-cross-platform-applications-7a1e7c14a068

**Comment by AMJoshaghani** [comment]
THAT WEREN'T WORK BRO.

**Comment by AMJoshaghani** [comment]
I did use bidi and arabic_rehaper but didn't work

**Comment by matham** [comment]
I specifically tried it, and it worked for me. So as the message above says, please ask on discord etc for help because we use github exclusively for bug reports and this is a support request and not a bug report.

**Comment by alimogh** [comment]
برای رفع مشکل نمایش نادرست آیتم‌های لیست کشویی (dropdown) Spinner در برنامه ، باید ویجت Spinner را سفارشی‌سازی کنیم تا آیتم‌های منوی بازشو نیز مانند سایر برچسب‌ها از پردازش متن فارسی و فونت مناسب بهره‌مند شوند. در Kivy، هر آیتم منو توسط کلاس SpinnerOption که یک Button است ساخته می‌شود. با ایجاد یک کلاس جایگزین که مانند PersianButton عمل کند و سپس استفاده از آن در Spinner، مشکل حل می‌شود.

راه‌حل: ساخت Spinner فارسی با آیتم‌های پردازش‌شده

۱. ایجاد کلاس PersianSpinnerOption

این کلاس باید از SpinnerOption ارث‌بری کرده و همانند PersianButton متن را پردازش کند.

```python
from kivy.uix.spinner import Spinner, SpinnerOption
import re
import math
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput
from kivy.uix.spinner import Spinner
from kivy.uix.popup import Popup
from kivy.core.clipboard import Clipboard
from kivy.core.window import Window
from kivy.utils import get_color_from_hex
from kivy.clock import Clock

# کتابخانه‌های پردازش متن فارسی
import arabic_reshaper
#import bidi
#import bidi.algorithm
from bidi.algorithm import get_display

# ------------------------------
#  تابع کمکی برای پردازش متن فارسی
# ------------------------------
_persian_cache = {}

font_farsi = "Vazirmatn[wght].ttf"


def persian_text(text):
  """تبدیل متن معمولی به فرم قابل نمایش برای زبان فارسی"""
  if not text:
    return text
  if text in _persian_cache:
    return _persian_cache[text]
  try:
    reshaped = arabic_reshaper.reshape(text)
    bidi_text = get_display(reshaped)
    _persian_cache[text] = bidi_text
    return bidi_text
  except:
    return text

def get_rtl_text(text):
  try:
    reshaped_text = arabic_reshaper.reshape(text)
    rtl_text = get_display(reshaped_text)
    return  rtl_text
  except :
    return  text
    
# ------------------------------
#  ویجت‌های سفارشی با پشتیبانی فارسی
# ------------------------------
class PersianLabel(Label):
  """برچسبی که متن آن به‌طور خودکار پردازش می‌شود"""

  def __init__(self, **kwargs):
    # تنظیم فونت و جهت پیش‌فرض
    kwargs.setdefault("font_name", font_farsi)
    kwargs.setdefault("font_script_name", "Arab")
    kwargs.setdefault("halign", "right")
    kwargs.setdefault("valign", "middle")
    super().__init__(**kwargs)
    self.bind(text=self._on_text_changed)

  def _on_text_changed(self, instance, value):
    if value and not hasattr(self, "_processing"):
      self._processing = True
      processed = persian_text(value)
      if processed != value:
        self.text = processed
      delattr(self, "_processing")


class PersianButton(Button):
  """دکمه با پشتیبانی از متن فارسی"""

  def __init__(self, **kwargs):
    kwargs.setdefault("font_name", font_farsi)
    kwargs.setdefault("font_script_name", "Arab")
    super().__init__(**kwargs)
    self.bind(text=self._on_text_changed)

  def _on_text_changed(self, instance, value):
    if value and not hasattr(self, "_processing"):
      self._processing = True
      processed = persian_text(value)
      if processed != value:
        self.text = processed
      delattr(self, "_processing")


class PersianTextInput(TextInput):
  """ورودی متن با قابلیت راست‌چین و پردازش hint_text فارسی"""

  def __init__(self, **kwargs):
    kwargs.setdefault("font_name", font_farsi)
    #kwargs.setdefault("font_script_name", "Arab")
    kwargs.setdefault("font_context", "Arab")
    kwargs.setdefault("halign", "right")
    #kwargs.setdefault("text_direction", "rtl")
    kwargs.setdefault("base_direction", "rtl") #base_direction
    kwargs.setdefault("multiline", False)
    super().__init__(**kwargs)
    self.bind(hint_text=self._on_hint_changed)

  def _on_hint_changed(self, instance, value):
    if value and not hasattr(self, "_processing"):
      self._processing = True
      processed = persian_text(value)
      if processed != value:
        self.hint_text = processed
      delattr(self, "_processing")


    def insert_text(self, substring, from_undo=False):
        if not from_undo and (len(self.text) + len(substring) > self.max_chars):
            return

        self.str = self.str+substring
        self.text = get_rtl_text(self.str)
        substring = ""
        super(Ar_text, self).insert_text(substring, from_undo)
        print("A")

    def do_backspace(self, from_undo=False, mode='bkspc'):
        self.str = self.str[0:len(self.str)-1]
        self.text = get_rtl_text(self.str)
        print("B")

# ------------------------------
#  فیلتر ورودی برای پذیرش کاراکترهای مجاز
# ------------------------------
def input_filter(instance, value):
  """فقط اعداد، عملگرها و پرانتز مجاز است"""
  allowed = "0123456789+-*/(). "
  try:
    if value in allowed:
      return value
    return ""
  except:
    pass


class PersianSpinnerOption(SpinnerOption):
    """گزینه منوی Spinner با پشتیبانی فارسی"""
    def __init__(self, **kwargs):
        kwargs.setdefault('font_name', font_farsi)
        kwargs.setdefault('font_script_name', 'Arab')
        kwargs.setdefault('halign', 'right')
        super().__init__(**kwargs)
        self.bind(text=self._on_text_changed)
    
    def _on_text_changed(self, instance, value):
        if value and not hasattr(self, '_processing'):
            self._processing = True
            processed = persian_text(value)
            if processed != value:
                self.text = processed
            delattr(self, '_processing')
```

۲. ایجاد کلاس PersianSpinner

این کلاس Spinner اصلی را با مشخص کردن option_cls به کلاس بالا و تنظیم فونت و پردازش متن انتخاب‌شده (مشابه قبل) می‌سازد.

```python
class PersianSpinner(Spinner):
    """Spinner با پشتیبانی کامل از متن فارسی در آیتم‌ها"""
    def __init__(self, **kwargs):
        # تنظیم فونت و جهت برای خود Spinner
        kwargs.setdefault('font_name', font_farsi)
        kwargs.setdefault('font_script_name', 'Arab')
        kwargs.setdefault('halign', 'right')
        # تعیین کلاس آیتم‌های منو
        kwargs.setdefault('option_cls', PersianSpinnerOption)
        super().__init__(**kwargs)
        # پردازش متن انتخاب‌شده (مشابه PersianLabel)
        self.bind(text=self._on_text_changed)
    
    def _on_text_changed(self, instance, value):
        if value and not hasattr(self, '_processing'):
            self._processing = True
            processed = persian_text(value)
            if processed != value:
                self.text = processed
            delattr(self, '_processing')
```

۳. جایگزینی Spinner معمولی با PersianSpinner در کد اصلی

در کلاس PersianCalculator، بخش ساخت mode_spinner را به‌صورت زیر تغییر دهید:

```python
self.mode_spinner = PersianSpinner(
    text=persian_text("ساده"),
    values=[persian_text("ساده"), persian_text("مهندسی")],
    size_hint_x=0.25,
)
```

توجه داشته باشید که دیگر نیازی به تنظیم font_name و ... نیست چون در کلاس PersianSpinner تعریف شده‌اند. همچنین برای مقداردهی text و values از تابع persian_text استفاده کنید تا رشته‌های اصلی ذخیره شوند (نه رشته‌های پردازش‌شده نهایی)؛ زیرا پردازش نهایی توسط خود ویجت‌ها در زمان نمایش انجام می‌شود.

۴. نکته مهم: تفاوت text و values

· text همان آیتم انتخاب‌شده فعلی است. آن را با persian_text پردازش می‌کنیم تا شکل نهایی ذخیره شود (و سپس توسط _on_text_changed دوباره پردازش نشود؟ بهتر است فقط از یک مرحله پردازش استفاده کنیم).
· values لیست آیتم‌هاست. هنگام ساخت Spinner، این مقادیر به کلاس PersianSpinnerOption داده می‌شوند و هر کدام در زمان نمایش پردازش می‌شوند. پس کافی است مقادیر اصلی (مثل "ساده" و "مهندسی") را به values بدهیم و اجازه دهیم PersianSpinnerOption پردازش را انجام دهد.

بنابراین در کد بالا، values را با persian_text پردازش کردیم که شاید اضافی باشد. بهتر است به‌جای آن از مقادیر خام استفاده کنیم:

```python
self.mode_spinner = PersianSpinner(
    text=persian_text("ساده"),
    values=["ساده", "مهندسی"],
    size_hint_x=0.25,
)
```

اما برای اطمینان از یکسان‌سازی، می‌توانیم مقادیر را با persian_text پردازش کنیم و سپس Spinner آن‌ها را به آیتم‌ها بدهد که باز هم پردازش می‌شوند (ممکن است دو بار پردازش شوند که مشکلی ایجاد نمی‌کند چون تابع persian_text idempotent است). روش پیشنهادی: از مقادیر خام استفاده کنید.

۵. تطبیق متد on_mode_change

در متدی که تغییر حالت را مدیریت می‌کند، اکنون value رشته‌ای است که توسط Spinner برگردانده می‌شود. چون متن درون Spinner پردازش شده، value شامل رشته‌ای است که شکل نهایی دارد (مثلاً "ساده" به فرم صحیح). برای مقایسه با مقادیر اصلی، بهتر است یا از رشته‌های اصلی استفاده کنیم یا یک نگاشت معکوس ایجاد کنیم. ساده‌ترین راه: رشته اصلی را در یک دیکشنری ذخیره کنیم. اما برای سادگی، می‌توانیم value را با persian_text("ساده") مقایسه کنیم:

```python
def on_mode_change(self, instance, value):
    if value == persian_text("ساده"):
        self.create_standard_buttons()
    else:
        self.create_scientific_buttons()
```

این روش به شرطی کار می‌کند که persian_text همواره خروجی یکسانی بدهد (که می‌دهد). اما اگر پردازش به هر دلیل متفاوت باشد، ممکن است مقایسه با شکست مواجه شود. روش ایمن‌تر: ذخیره text اصلی در یک ویژگی جداگانه. اما برای این مثال ساده، همین کفایت می‌کند.

کد نهایی بخش Spinner

با اعمال تغییرات بالا، بخش مربوط به Spinner در PersianCalculator.__init__ به این صورت درمی‌آید:

```python
# انتخاب حالت
menu_bar.add_widget(
    PersianLabel(text=persian_text("حالت:"), size_hint_x=0.15, color=(0.2, 0.8, 0.1, 0.95))
)
self.mode_spinner = PersianSpinner(
    text=persian_text("ساده"),
    values=["ساده", "مهندسی"],
    size_hint_x=0.25,
)
self.mode_spinner.bind(text=self.on_mode_change)
menu_bar.add_widget(self.mode_spinner)
```

و متد on_mode_change:

```python
def on_mode_change(self, instance, value):
    if value == persian_text("ساده"):
        self.create_standard_buttons()
    else:
        self.create_scientific_buttons()
```

توضیح عملکرد

· وقتی Spinner باز می‌شود، کلاس PersianSpinnerOption برای هر آیتم ساخته می‌شود. این کلاس متن را در زمان نمایش با persian_text پردازش می‌کند.
· وقتی آیتمی انتخاب می‌شود، text Spinner با مقدار آن آیتم (که توسط persian_text پردازش شده) تنظیم می‌شود و سپس _on_text_changed در PersianSpinner دوباره پردازش می‌کند. برای جلوگیری از پردازش مضاعف، می‌توانیم _on_text_changed را حذف کنیم و فقط به پردازش اولیه در __init__ اکتفا کنیم. اما برای یکسان‌سازی با سایر ویجت‌ها، آن را نگه داشته‌ایم.

با این تغییرات، تمام عناصر Spinner (آیتم‌های بازشو و گزینه انتخاب‌شده) به‌درستی به زبان فارسی نمایش داده می‌شوند و مشکل جدا نویسی و ترتیب کاراکترها برطرف می‌گردد.


به اینجاها یک نگاه کنید

https://github.com/humanshu001/Python-Projects/blob/584d27dd91a6fcf9c4d8e5d1a476b92019d010a6/kivy_venv/share/kivy-examples/widgets/unicode_textinput.py#L3

https://github.com/roboracingleague/donkeycar/blob/bf12eed9df366f5d4cab98c37eb10b2904ec5304/donkeycar/management/kivy_ui.py#L10
