### ISSUE TITLE
scrollview documentation .kv example bug

### ISSUE THREAD

**Issue by davidBoertjes** [kivy/kivy#6756]
### Versions

* Python: 3.6.9
* OS: Ubuntu 18.04.4 LTS
* Kivy: 1.11.1
* Kivy installation method: pip

### Description

Using the .kv example on https://kivy.org/doc/stable/api-kivy.uix.scrollview.html as is does not work.    Recommend two changes described below:

The following line from the .kv example:
```python
text_size: self.width
```
Causes an error:
```
TypeError: 'int' object is not iterable
```
I believe this is because the `text_size` property is expecting a pair of values.  Suggest changing it to `text_size_x`.  

Running the example code as is produces a scroll area which is limited to a small patch of the window at the bottom left.  This took my a lot of work to fix in the .kv file.  The code/builder versions work fine but many take advantage of the `window` object.  I recommend adding this to the .kv example.  The following .kv contains both changes:

```python
#:import Window kivy.core.window.Window

ScrollView:
    do_scroll_x: False
    do_scroll_y: True
    size: Window.width, Window.height

    Label:
        size_hint_y: None
        height: self.texture_size[1]
        text_size: self.width
        padding: 10, 10
        text:
            'really some amazing text\n' * 100

```
Please consider changing the .kv example in the documentation to the version above.

### Code and Logs

Working code after making the adjustments above:

*main.py*
```python
from kivy.app import App
from kivy.uix.widget import Widget

class ScrollViewExample(Widget):
    pass


class ScrollViewApp(App):
    def build(self):
        return ScrollViewExample()


if __name__ == '__main__':
    ScrollViewApp().run()
```

*scrollview.kv*
```python
<ScrollViewExample>:
#:import Window kivy.core.window.Window

    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        size: Window.width, Window.height

        Label:
            size_hint_y: None
            height: self.texture_size[1]
            text_size: self.width
            padding: 10, 10
            text:
                'really some amazing text\n' * 100
```

**Comment by Cheaterman** [comment]
You definitely shouldn't have to use the Window here - what if the `ScrollView` is in fact not your root widget at all?

Other than that, your text_size should indeed have two elements.

The following code works here:
```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string(r'''
ScrollView:
    do_scroll_x: False
    do_scroll_y: True

    Label:
        size_hint_y: None
        height: self.texture_size[1]
        text_size: self.width, None
        padding: 10, 10
        text:
            'really some amazing text\n' * 100

'''))
```

Please double-check the scroll area using this code, and come back to us if you still have an issue.
