### ISSUE TITLE
i can use to business

### ISSUE THREAD

**Issue by JiuXin303** [kivy/kivy#6759]
I like this project!
but,now i undetermined kivy is use to business.
i look your license is mit,yes,it is sure support business,100% free.But,I saw other license on your website,have lgpl.....
so,i really use kivy to business,is success?
I is s chinese senior high school student,I sorry my English is no good,but i feel me is speak clear.
I am very worried that I will use Kivy for business applications in the future,Because I'm about to graduate,That's why the question came up.
NOTE:Part of English translation comes from translator

**Comment by disknowsname** [comment]
Also,you can add SDL original set pos and size method?
I dont use as pos size_hint method,because  
i set pos=[0,0],it is no render to top and left,it render to below and left..
also,I how get as label button....size?

**Comment by Cheaterman** [comment]
I use Kivy for business every day, and I work in a fairly large group (57k employees). We develop industrial applications for various domains.

For your second comment, I feel like this is not an issue with Kivy, so I think this can be closed. The coordinate system in Kivy will not be changed - not only is it very logical in the context of OpenGL, it would break absolutely all existing applications.

Please do try to learn how to use pos_hint and size_hint, they'll make your life so much easier. :-)

Thanks!

**Comment by JiuXin303** [comment]
@Cheaterman 
The second question is not very important. 
Thank you for your reply.
One more thing: will your products be packaged into applications?

**Comment by Cheaterman** [comment]
Yes! We typically use PyInstaller for that. Check the Kivy documentation for more details: https://kivy.org/doc/stable/guide/packaging.html

**Comment by JiuXin303** [comment]
@Cheaterman  
OK!
thank you very much!

**Comment by JiuXin303** [comment]
You don't have to reply to me. I'll close it.
