### ISSUE TITLE
Kivy 2.0: Gadget seems to autodismiss on mouse-up

### ISSUE THREAD

**Issue by CPStagg** [kivy/kivy#6760]
This is on:
[INFO   ] [Kivy        ] v2.0.0rc1, git-ae0fa0c, 20191229
(Windows 10 environment)

If I use Kivy2.0 on Windows, my various pop-up choice lists, launched by clicking on a button in the app's main tool window, disappear instantly as soon as the mouse button is released (if you hold the mouse button down the popup gadget stays onscreen).

The gadgets are created with this code:

popup = Popup(title = promptText,
                   content = scrollingList,
                   size_hint = (0.4, 0.6),
                   auto_dismiss = autoDismiss)
    if dismissCallback:
        popup.bind(on_dismiss=dismissCallback )
    return popup

The same codebase runs as expected on machines/virtual machines running Kivy1.11. The only obvious difference is the Kivy version.

If autoDismiss is set to false, the popup gadget behaves as expected, but obviously lacks the desired autodismissal behavior.

**Comment by matham** [comment]
Can you please provide a minimum, but complete runnable example showing the issue?
