### ISSUE TITLE
Documentation for Config lists kivy_clock under wrong section

### ISSUE THREAD

**Issue by tarocco** [kivy/kivy#6762]
The [documentation for the `kivy_clock` configuration](https://kivy.org/doc/stable/api-kivy.config.html) is listed under the wrong section (graphics). [The source code for `kivy/clock.py`](https://github.com/kivy/kivy/blob/b1c643c8a6d3d4750dc2fa9a0232354dfcecd3a1/kivy/clock.py#L1069) shows that it should be in the kivy section, not graphics.

In testing, changing
`Config.set('graphics', 'kivy_clock', 'interrupt')`
to
`Config.set('kivy', 'kivy_clock', 'interrupt')`
solved my problem.

**Comment by Franccisco** [comment]
I confirm this. In the website, it appears under the `graphics` section:

https://kivy.org/doc/stable/api-kivy.config.html#available-configuration-tokens

However, in the source code appears it is under the `kivy` section:

https://github.com/kivy/kivy/blob/e48052d878c5bdfc00ebf4a92be71134152c40f7/kivy/config.py#L87-L117

It seems this section is not updated in the website.

**Comment by Julian-O** [comment]
Was fixed in Kivy 2.0.0. Closing.
