### ISSUE TITLE
Pyrebase usage

### ISSUE THREAD

**Issue by asimakos** [kivy/kivy#6764]
I would like to ask you if I could use Pyrebase (https://github.com/thisbejim/Pyrebase) along with Kivy framework.
 That would help me a lot!

Regards

**Comment by cristianmejiaarias** [comment]
import pyrebase needs requirements = python3, kivy==2.0.0, pyrebase, requests, urllib3, chardet, idna, gcloud, oauth2client, requests-toolbelt, protobuf_cpp, python-jwt, pycryptodome, httplib2, pyparsing, pyasn1, pyasn1_modules, rsa, jwcrypto, cryptography

**Comment by cristianmejiaarias** [comment]
https://github.com/RobertFlatt/Android-for-Python/tree/main/Android-for-Python-Users#some-buildozerspec-options
