### ISSUE TITLE
sdl2 - RuntimeError: b'Could not initialize EGL'

### ISSUE THREAD

**Issue by asimakos** [kivy/kivy#6765]
I try to run the following sample script on Windows 7 with OpenGL 1.1:

```
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()
```

and i receive the following error

> [INFO   ] [Logger      ] Record log in C:\Users\Admin\.kivy\logs\kivy_20-03-09_20.txt
> [INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.2.0
> [INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.2.0
> [INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
> [INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
> [INFO   ] [Kivy        ] v1.11.1
> [INFO   ] [Kivy        ] Installed at "F:\Data_analytics\venv\lib\site-packages\kivy\__init__.py"
> [INFO   ] [Python      ] v3.6.0 (default, Jan 23 2017, 17:35:20) [MSC v.1900 32 bit (Intel)]
> [INFO   ] [Python      ] Interpreter at "F:\Data_analytics\venv\Scripts\python.exe"
> [INFO   ] [Factory     ] 184 symbols loaded
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
> [INFO   ] [Text        ] Provider: sdl2
> [INFO   ] [Window      ] Provider: sdl2
> [INFO   ] [Window      ] Activate GLES2/ANGLE context
> [CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
> sdl2 - RuntimeError: b'Could not initialize EGL'
>   File "F:\Data_analytics\venv\lib\site-packages\kivy\core\__init__.py", line 71, in core_select_lib
>     cls = cls()
>   File "F:\Data_analytics\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 152, in __init__
>     super(WindowSDL, self).__init__()
>   File "F:\Data_analytics\venv\lib\site-packages\kivy\core\window\__init__.py", line 981, in __init__
>     self.create_window()
>   File "F:\Data_analytics\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 290, in create_window
>     self.get_gl_backend_name())
>   File "kivy\core\window\_window_sdl2.pyx", line 224, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
>   File "kivy\core\window\_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die
> 
> [CRITICAL] [App         ] Unable to get a Window, abort.
> 

I have used user environment variable KIVY_GL_BACKEND with value angel_sdl2. 
Any idea what should i correct and get a successful result? That would help me a lot!

Regards

**Comment by matham** [comment]
Kivy uses opengl to draw all the graphics and we need a graphics card that supports at least opengl 2+. I'm afraid there's nothing we can do if your graphics card only support opengl 1.1.

**Comment by asimakos** [comment]
I have posted the same message (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kivy-users/HSVJNIXOVV0/QE9IqKEjAQAJ)  and unfortunately i got a different reply. Is there any way to run a specific Kivy version with its specific dependencies by using OpenGL 1.1 and Windows 7 ?

A detailed description would help me a lot, if it exists!

Regards

**Comment by matham** [comment]
If, as you say, the computer only has opengl 1.1 support, then the answer is that you can't run kivy on that computer. If you have opengl 2+ on the computer, then as mentioned on the reply on Google groups, there may be other issues with your installation that is causing this.

Either way, we don't really provide support here, github issues is for bugs only, not support.
