### ISSUE TITLE
Method to pin point the widget that is causing a "ReferenceError: weakly-referenced object no longer exists"

### ISSUE THREAD

**Issue by kkawabat** [kivy/kivy#6779]
I just went bald pulling my hair out trying to fix a weakly-referenced error and it seems like I am not the [only person](https://github.com/kivy/kivy/issues?q=is%3Aissue+weakly-reference) having a hard time chasing these issues. After some experimenting and looking at the source code I think I found a systematic way of pin pointing which widget is causing the issue without the need to search for it.  

## Context: 
I have an [app that does morse code exercises](https://github.com/kkawabat/morse-code-trainer/tree/d1e2bd07047f45ff5b4d1a6237d6c745c99187b7). I decided to replace a `MDTextFieldRound` widget with a `Label` for one of my screen [here](https://github.com/kkawabat/morse-code-trainer/blob/d1e2bd07047f45ff5b4d1a6237d6c745c99187b7/ui/screens/tapping_speed_test_screen.kv#L53). However when I do that, the app would crash as soon as it starts. No matter what I did (remove all unnecessary fields, removed references, added references, edited the python file, etc.)

Here is the traceback to my crashed code:

>  Traceback (most recent call last):
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 2073, in <module>
>      main()
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 2067, in main
>      globals = debugger.run(setup['file'], None, None, is_module)
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 1418, in run
>      return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 1425, in _exec
>      pydev_imports.execfile(file, globals, locals)  # execute the script
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>      exec(compile(contents+"\n", file, 'exec'), glob, loc)
>    File "C:/Users/kkawa/PycharmProjects/morse_code_traininer/main.py", line 62, in <module>
>      MainApp().run()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\app.py", line 855, in run
>      runTouchApp()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\base.py", line 504, in runTouchApp
>      EventLoop.window.mainloop()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
>      self._mainloop()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
>      EventLoop.idle()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\base.py", line 339, in idle
>      Clock.tick()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\clock.py", line 591, in tick
>      self._process_events()
>    File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
>    File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
>    File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
>    File "kivy\_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
>    File "kivy\_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 57, in is_dead
>      return self.proxy is not None and not bool(dir(self.proxy))
>  ReferenceError: weakly-referenced object no longer exists

From my understanding the problem occurs when:

- the clock schedules a call to an object's method by creating a weak reference to the method
- the object gets deleted before the scheduled call
- when the clock tries to run the method it gets an error because the object no longer exists

The problem I had is that the traceback was very opaque, I had no idea what the object was that no longer exists and because the issue happened inside [_clock.pyx](https://github.com/kivy/kivy/blob/96dfa5b55ed74c8223152dd84cd478bfed03e90b/kivy/_clock.pyx) file so I could not easily place a breakpoint like I do with .py files. And because the object is already missing when `is_dead()` is executed, putting a `print(self)` inside is_dead() would print the weakmethod of all scheduled events before the missing object's event but would crash before printing the actual event itself. 

> ..............initialization of kivy followed by bunch of logs of weakmethod objects..... 
> <WeakMethod proxy=<kivymd.uix.button.MDIconButton object at 0x13FF1988> method=None method_name=_finish_init>
> <WeakMethod proxy=<kivymd.uix.button.MDIconButton object at 0x13FF1988> method=None method_name=do_layout>
> <WeakMethod proxy=<kivymd.uix.card.MDCard object at 0x140006E8> method=None method_name=do_layout>
> <WeakMethod proxy=<kivy.uix.label.Label object at 0x14005C58> method=None method_name=texture_update>
> <WeakMethod proxy=<kivymd.uix.textfield.MDTextFieldRound object at 0x1400EB08> method=None method_name=do_layout>
> <WeakMethod proxy=<kivy.uix.boxlayout.BoxLayout object at 0x14015358> method=None method_name=do_layout>
>  Traceback (most recent call last):
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 60, in is_dead
>      print(self)
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 75, in __repr__
>      return '<WeakMethod proxy={} method={} method_name={}>'.format(
>  ReferenceError: weakly-referenced object no longer exists
>  .....followed by traceback error.......

## How I found the problematic object:

I added a try/except statement around  [`return self.proxy is not None and not bool(dir(self.proxy))`](https://github.com/kivy/kivy/blob/80e0af9b2615caf7ae75664bcdf3485bd6b4b8a1/kivy/weakmethod.py#L114) and put a breakpoint after it crashed to try and glean more information on what the weakmethod was

        def is_dead(self):
            '''Returns True if the referenced callable was a bound method and
            the instance no longer exists. Otherwise, return False.
            '''

            # return self.proxy is not None and not bool(dir(self.proxy))

            try:
                print(self)
                return self.proxy is not None and not bool(dir(self.proxy))
            except:
                pass  # <-- breakpoint here

From this I got was that the method's name was `_finish_init` (but no info on the object itself)

![image](https://user-images.githubusercontent.com/9159267/76694007-66f1be80-662a-11ea-97f7-63979f7c15a3.png)

I tried to search for `_finish_init` in kivy's source code but did not find a single instance of it....

I then decided to print the event queue before the [self._process_events](https://github.com/kivy/kivy/blob/96dfa5b55ed74c8223152dd84cd478bfed03e90b/kivy/clock.py#L581)() call with the code below:

        count = 0
        tmp_event = self._root_event
        while tmp_event is not None:
            count += 1
            print(count, tmp_event)
            tmp_event = tmp_event.next
        
        # process event
        self._process_events()

Along with the previous `print(self)` statement in `is_dead()` I got this [output](https://pastebin.com/ZWc6BMum)
 
Essentially it's a print out of all the events in the queue followed by the print of their associated weakmethods when is_dead gets called in _process_events()

Using this I looked for the last weakmethod before the crash 

`<WeakMethod proxy=<kivy.uix.boxlayout.BoxLayout object at 0x13AE4418> method=None method_name=do_layout>`

And I ctrl+f `0x13AE4418` to get to the associated event, then I found the scheduled event that was right after to get the non existent object. 

> .....yout.BoxLayout object at 0x13AE4418>>> 
> 88 <WeakMethod proxy=<kivymd.uix.button.MDIconButton object at 0x13AE4D18> method=None method_name=_finish_init>
> <ClockEvent (0.0) callback=<bound method BaseButton._finish_init of <kivymd.uix.button.MDIconButton object at 0x13AE4D18>>>

It turned out it was a kivymd.uix.button.MDIconButton and it has `_finish_init` (no wonder i couldn't find it in kivy source code it was a kivymd object!) 

I haven't Found the bug yet but this tells me that the issue isn't with the `Label` but an `MDIconButton` (probably of the MDTextFieldRound that I replaced). While it should have been obvious to me not having the traceback pointing to this definitely made it harder.

## Feature request:

one way to make traceback more informative is to save a bit of metainfo of the method's object during WeakMethod initialization and when ReferenceError is raised print the metainfo as part of the error logging for example this can be done in [__repr__() of weakmethod](https://github.com/kivy/kivy/blob/80e0af9b2615caf7ae75664bcdf3485bd6b4b8a1/kivy/weakmethod.py#L70) e.g.:

        def __repr__(self):
            try:
                return '<WeakMethod proxy={} method={} method_name={}>'.format(
                       self.proxy, self.method, self.method_name)
            except ReferenceError:
                raise ReferenceError(f'object: {self.object_name} of callback no longer exists, callback generated in '
                                     f'{self.file_of_callback_generation}: {self.linenumber_of_callback_generation}')

Not sure how feasible it is to get the line number and filename of when weakmethod is called but just an idea of how to make it more informative.

**Comment by matham** [comment]
Hmm, although it's not a bad idea to maybe save the `repr` string of the object when the proxy is created. I'd be worried about the performance penalty if we always do this. 

In particular, `repr` is not a particularly performant method because it has to compute the object representation which may involve multiple attributes etc. So it probably would not be acceptable to do this by default, But perhaps have a module level flag or class level attribute that controls this may work!? Then it can be set during debugging only.

**Comment by kkawabat** [comment]
Thank you for taking a look at this.

Just to add to your comment.  I am assuming inspecting the stack is more expensive than `repr` of an object but it's computation would be independent of the actual object. I just followed some of the examples [here](based on this thread https://stackoverflow.com/questions/17407119/python-inspect-stack-is-slow ) I do notice it being a bit longer to start but there might be a cheaper way to get to the file/lineno information. either way I think having that would be much more helpfult to narrow down the cause of reference error than just a repr of the object.

modified the WeakMethod's `__init__` as so:

      ```
  def __init__(self, method):
            self.method = None
            self.method_name = None
            try:
                call_frame = inspect.stack(0)[1].frame
                self.call_lineno = call_frame.f_lineno
                self.call_file = call_frame.f_code.co_filename
                if method.__self__ is not None:

                    self.method_name = method.__func__.__name__
                    self.proxy = weakref.proxy(method.__self__)
                else:
                    self.method = method
                    self.proxy = None
            except AttributeError:
                self.method = method
                self.proxy = None

```
And the `is_dead()` as:
```
       def is_dead(self):
            '''Returns True if the referenced callable was a bound method and
            the instance no longer exists. Otherwise, return False.
            '''

            # return self.proxy is not None and not bool(dir(self.proxy))
            try:
                print(self)
                return self.proxy is not None and not bool(dir(self.proxy))
            except ReferenceError:
                raise ReferenceError(f'callback no longer exists, callback generated in '
                                     f'{self.call_file}: {self.call_lineno}')
```

Here is an example of it in action:

```
import gc

from kivy.weakmethod import WeakMethod


class MyObj:
    def mymethod(self):
        print('If you are reading this I am already dead')


if __name__ == '__main__':
    myobj = MyObj()
    myobj.mymethod()
    myweakmethod = WeakMethod(myobj.mymethod)
    myweakmethod()()

    del myobj
    gc.collect()
    print(myweakmethod.is_dead())
```

Here is it's log output:

> [INFO   ] [Logger      ] Record log in C:\Users\kkawa\.kivy\logs\kivy_20-03-15_35.txt
> [INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
> [INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
> [INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
> [INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
> If you are reading this I am already dead
> [INFO   ] [Kivy        ] v1.11.1
> [INFO   ] [Kivy        ] Installed at "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\__init__.py"
> [INFO   ] [Python      ] v3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
> [INFO   ] [Python      ] Interpreter at "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\python.exe"
>  Traceback (most recent call last):
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 81, in __repr__
>      return '<WeakMethod proxy={} method={} method_name={}>'.format(
>  ReferenceError: weakly-referenced object no longer exists
>  
>  During handling of the above exception, another exception occurred:
>  
>  Traceback (most recent call last):
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 64, in is_dead
>      print(self)
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 84, in __repr__
>      raise ReferenceError(f'callback no longer exists, callback generated in '
>  ReferenceError: callback no longer exists, callback generated in C:/Users/kkawa/PycharmProjects/morse_code_traininer/kivytests/helloworld.py: 14
>  
>  During handling of the above exception, another exception occurred:
>  
>  Traceback (most recent call last):
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 2073, in <module>
>      main()
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 2067, in main
>      globals = debugger.run(setup['file'], None, None, is_module)
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 1418, in run
>      return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 1425, in _exec
>      pydev_imports.execfile(file, globals, locals)  # execute the script
>    File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>      exec(compile(contents+"\n", file, 'exec'), glob, loc)
>    File "C:/Users/kkawa/PycharmProjects/morse_code_traininer/kivytests/helloworld.py", line 17, in <module>
>      print(myweakmethod.is_dead())
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 67, in is_dead
>      raise ReferenceError(f'callback no longer exists, callback generated in '
>  ReferenceError: callback no longer exists, callback generated in C:/Users/kkawa/PycharmProjects/morse_code_traininer/kivytests/helloworld.py: 14
> 
> Process finished with exit code 1

**Comment by Cheaterman** [comment]
These issues are genuinely annoying, and will inevitably happen once your app gets complex enough. Adding debugging capabilities is an excellent idea, but as @matham noted, please make sure the performance impact in day-to-day use is minimal to non-existent :-)

**Comment by matham** [comment]
Looking at [the code](https://github.com/kivy/kivy/blob/master/kivy/weakmethod.py#L58), it already quiets reference errors so I'm not sure how you got a ref error? Are you on master?

**Comment by kkawabat** [comment]
! I am still on 1.11, I will update to see if this solves my issue. It feels to me that there might still be times where tracking the specific call that would trigger the referenceError might be useful for debugging. Feel free to close this issue if the concern is unwarranted.

**Comment by matham** [comment]
I think we'd need an example and that would determine what kind of debugging info might be helpful. If you run into another similar issue please open a new issue for that.

**Comment by michaelu123** [comment]
I am also fighting with this problem, and I am wondering why is_dead throws an exception at all. Should it not just return True or False? I.e. try ... except ReferenceError: return True.  Why else should __call__ check "if is_dead() return"? In my case the weak reference is to a Clock.schedule_once callback, so if it is gone, just don't call it instead of crashing? 

I see this problem frequently on Android, rarely on Windows. I would like to test a modified is_dead on Android, but what can I do to make buildozer compile a modified weakmethod.py? There are four of them below platform/build-armeabi-v7a, and even if I change all of them, still the original code is taken. It does not help to remove the weakmethod.pyc files either.
