### ISSUE TITLE
help() method starts a random Kivy application

### ISSUE THREAD

**Issue by Laps14** [kivy/kivy#6796]
when I search for a module name in the help() method of python interpreter, a random kivy application starts from nowhere. Even if the name I'm searching is for another method, the kivy start 
![image](https://user-images.githubusercontent.com/49603393/77594437-47ce1900-6ed5-11ea-8ff7-957b7e5cadfc.png)
![image](https://user-images.githubusercontent.com/49603393/77594545-8b288780-6ed5-11ea-80ee-5a5f362355b9.png)

If I didn't explain correctly what is the error, or if you didn't understand, you can ask anything. I'm sorry for didn't make myself clear

**Comment by tshirtman** [comment]
this certainly imports the modules and sub modules from kivy, which causes the `kivy.core.window` module to be imported, which creates a Window as a side effect, i agree it's not great, but it'll be hard to change this decision at this point :/.

**Comment by Julian-O** [comment]
Another symptom of a bigger problem: #8340. Closing as duplicate
