### ISSUE TITLE
Kivy takes very long to show the window

### ISSUE THREAD

**Issue by sceroz-ply** [kivy/kivy#6804]
**Software Versions**
* Python: 3.7.1
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: pip

**Describe the bug**
 im running kivy on windows 10 with python 3.7.1. When I run a scripts the first few times (after turning my pc on) the scripts runs fine and the app window shows up instantly, however after a few times when i try to run the script it runs till the part Provider sdl2 and then it just get stuck there for like a minute and then the window shows up.
if I restart my computer it runs fine for a few times and then again like this

**Expected behavior**
Run the program.

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.

**Code and Logs and screenshots**
```python
any script
my script:

#!python
#Trying kivy for the first time

import kivy
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.gridlayout import GridLayout
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button



class MyGrid(GridLayout):
    def __init__(self, **kwargs):
        super(MyGrid, self).__init__()
        self.cols = 1
        
        self.inside = GridLayout()
        self.inside.cols = 2
        
        self.inside.add_widget(Label(text='Username: '))
        self.name = TextInput(multiline=False)
        self.inside.add_widget(self.name)
        
        self.inside.add_widget(Label(text='Password: '))
        self.password = TextInput(multiline=False)
        self.inside.add_widget(self.password)
        
        self.inside.add_widget(Label(text='Email: '))
        self.email = TextInput(multiline=False)
        self.inside.add_widget(self.email)
        
        self.add_widget(self.inside)
        self.submit = Button(text='Submit', font_size=40)
        self.add_widget(self.submit)
        self.submit.bind(on_press=self.pressed)
        
    def pressed(self, instance):
        print('Pressed')


class MyApp(App):
    def build(self):
        return MyGrid()
        
        
if __name__=='__main__':
    try:
        MyApp().run()
    except KeyboardInterrupt:
        exit()
![image](https://user-images.githubusercontent.com/62894634/77929055-e41b6580-72b1-11ea-888a-e8f5117a204d.png)
this is my cmd

**Comment by matham** [comment]
There's nothing in kivy that would this kind of thing, so it's probably something in your system or configuration. If on discord you identify the issue, please feel free to re-open.
