### ISSUE TITLE
Documentation issue in installation instructions

### ISSUE THREAD

**Issue by OutsourcedGuru** [kivy/kivy#6807]
In [this page](https://github.com/kivy/kivy/blob/master/doc/sources/installation/installation-rpi.rst#raspberry-pi-1-4-installation) we see multiple times in step 3 that `cython_install` is surrounded by pipe symbols for some odd reason. It's possible that someone pulled this from a markdown table and didn't remove them. Each instance—if attempted by a user—will fail and not produce the expected result.

```
python3 -m pip install --upgrade --user |cython_install| pillow
sudo pip install |cython_install|
sudo pip install -U |cython_install|
```

**Comment by matham** [comment]
You're looking at the raw doc sources. The properly generated docs are at https://kivy.org/doc/master/installation/installation-rpi.html#raspberry-pi-1-4-installation-on-raspbian-jessie-stretch-buster.
