### ISSUE TITLE
Reduce python-for-android initial loading.

### ISSUE THREAD

**Issue by tito** [kivy/kivy#681]
Reducing the loading time is a challenge, and here is my brainstorming so far. The android APK is a zip  file. Importing from a zip usually mean that we cannot import dynamic libraries too (.so).

The egg file format resolve that issue: by replacing distutils to setuptools in kivy, we can build a .egg. The native files are extracted on demand from the .egg. To use a .egg, you just need to copy it from the right python directory, or add it in the sys.path. But the .egg is a file too.
- Is python would be able to load .egg from a .apk, without any decompression?
- android can load dynamic library directly from the APK. would we be able to do the same? instead of letting the .egg extracting the file outside the egg for dlopen, could we try to use android API instead?
- both approach don't resolve the data access, but it look like `pkg_resources.resource_filename('kivy', 'data/glsl/header.vs')` is automaticaly extract the file in the temporary dir, and ready to be used afterwise with `open()`. is `pkg_resources.resource_filename()` is sufficient? do we need to patch open()? do we need to make kivy pkg_resources dependant ?

That's all, i'll check all of thoses points and wrote the result here.
##

**Comment by erm3nda** [comment]
Does this (https://www.androwish.org/index.html/wiki?name=ZIP+virtual+file+system) do anything of what you proposed when said "mount a zip"? Should i expect we talk about to do "it" with non-root? ¿It is /local/tmp folder good enough to place things?

I'm sorry if nothing has sense after all, just looked a bit and wanted to ask about.

**Comment by erm3nda** [comment]
Yes we can

**Comment by Ahd999** [comment]
Can you do it
?

**Comment by erm3nda** [comment]
I meant to close issue

**Comment by Ahd999** [comment]
Yea i understood that, I just was wondering if you had the rights to do that, anyways now that you have confirmed, please close it whenever you can

**Comment by Julian-O** [comment]
Closing as stale.
