### ISSUE TITLE
Kivy taking too long to run GUI window on Pycharm. It was working perfectly at the beginning when I installed it but now it is taking almost 1 minute to run it.

### ISSUE THREAD

**Issue by sdp5404** [kivy/kivy#6812]

**Comment by samdf96** [comment]
I've just started with Kivy two days ago, and have setup PyCharm to work with kivy, would love to take a look at your main coding file to see if there are any differences with mine! Post below please :)

**Comment by sdp5404** [comment]
> I've just started with Kivy two days ago, and have setup PyCharm to work with kivy, would love to take a look at your main coding file to see if there are any differences with mine! Post below please :)
> 
> 

![image](https://user-images.githubusercontent.com/60761239/78505908-828d4800-7744-11ea-8fae-096966db8cae.jpeg)

Actually i am working on an app so when i run the program it takes so much time to on Provider: sdl2.

**Comment by samdf96** [comment]
I'm not sure if you've been coding for long, but taking a phone picture of part of your code, is not the way things are done at all. Please just copy and paste your code, into a code block and reply.

**Comment by sdp5404** [comment]
> I'm not sure if you've been coding for long, but taking a phone picture of part of your code is not the way things are done at all. Please just copy and paste your code, into a code block and reply.

I'm sorry I am a beginner in programming but here are my program
``
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import  Screen

class HomeScreen(Screen):
    pass
class SettingsScreen(Screen):
    pass

GUI = Builder.load_file('main.kv')
class MainApp(App):
    def build(self):
        return GUI
    def change_screen(self, screen_name):
        #get the screen manager from the kv file
        screen_manager = self.root.ids['screen_manager']
        screen_manager.current = screen_name
        #screen_manager = self.root.ids

MainApp().run()
``

-- this is my main file

``
#:import utils kivy.utils

<HomeScreen>:
    FloatLayout:
        GridLayout:
            canvas:
                Color:
                    rgba: utils.get_color_from_hex('#58AE6F')
                Rectangle:
                    size: self.size
                    pos: self.pos
            # Put two weather icons here
            rows: 1
            pos_hint: {'top': 1, 'left': 1}
            size_hint: 1, .1
            Image:
                source: 'icons/workouts/weightlifting1.png'
            Image:
                source: 'icons/workouts/exercise.png'
        GridLayout:
            # Put two weather icons and avatar icon
            rows: 1
            pos_hint: {'top': .9, 'left': 1}
            size_hint: 1, .2
            Image:
                source: 'icons/workouts/weightlifting.png'
            Image:
                source: 'icons/avatars/man.png'
            Image:
                source: 'icons/workouts/bicycle.png'
        Label:
            # Welcome label
            pos_hint: {'top': .7, 'left': 1}
            size_hint: 1, .1
            text: 'Welcome to Workout App'
        GridLayout:
            # Banner grid
            rows: 1
            pos_hint: {'top': .6, 'left': 1}
            size_hint: 1, .4
        GridLayout:
            # Add 3 menu buttons here
            rows: 1
            pos_hint: {'top': .2, 'left': 1}
            size_hint: 1, .2
#:import utils kivy.utils

<HomeScreen>:
    FloatLayout:
        GridLayout:
            canvas:
                Color:
                    rgba: utils.get_color_from_hex('#58AE6F')
                Rectangle:
                    size: self.size
                    pos: self.pos
            # Put two weather icons here
            rows: 1
            pos_hint: {'top': 1, 'left': 1}
            size_hint: 1, .1
            Image:
                source: 'icons/workouts/weightlifting1.png'
            Image:
                source: 'icons/workouts/exercise.png'
        GridLayout:
            # Put two weather icons and avatar icon
            rows: 1
            pos_hint: {'top': .9, 'left': 1}
            size_hint: 1, .2
            Image:
                source: 'icons/workouts/weightlifting.png'
            Image:
                source: 'icons/avatars/man.png'
            Image:
                source: 'icons/workouts/bicycle.png'
        Label:
            # Welcome label
            pos_hint: {'top': .7, 'left': 1}
            size_hint: 1, .1
            text: 'Welcome to Workout App'
        GridLayout:
            # Banner grid
            rows: 1
            pos_hint: {'top': .6, 'left': 1}
            size_hint: 1, .4
        GridLayout:
            # Add 3 menu buttons here
            rows: 1
            pos_hint: {'top': .2, 'left': 1}
            size_hint: 1, .2#:import utils kivy.utils

<HomeScreen>:
    FloatLayout:
        GridLayout:
            canvas:
                Color:
                    rgba: utils.get_color_from_hex('#58AE6F')
                Rectangle:
                    size: self.size
                    pos: self.pos
            # Put two weather icons here
            rows: 1
            pos_hint: {'top': 1, 'left': 1}
            size_hint: 1, .1
            Image:
                source: 'icons/workouts/weightlifting1.png'
            Image:
                source: 'icons/workouts/exercise.png'
        GridLayout:
            # Put two weather icons and avatar icon
            rows: 1
            pos_hint: {'top': .9, 'left': 1}
            size_hint: 1, .2
            Image:
                source: 'icons/workouts/weightlifting.png'
            Image:
                source: 'icons/avatars/man.png'
            Image:
                source: 'icons/workouts/bicycle.png'
        Label:
            # Welcome label
            pos_hint: {'top': .7, 'left': 1}
            size_hint: 1, .1
            text: 'Welcome to Workout App'
        GridLayout:
            # Banner grid
            rows: 1
            pos_hint: {'top': .6, 'left': 1}
            size_hint: 1, .4
        GridLayout:
            # Add 3 menu buttons here
            rows: 1
            pos_hint: {'top': .2, 'left': 1}
            size_hint: 1, .2
#:import utils kivy.utils

<HomeScreen>:
    FloatLayout:
        GridLayout:
            canvas:
                Color:
                    rgba: utils.get_color_from_hex('#58AE6F')
                Rectangle:
                    size: self.size
                    pos: self.pos
            # Put two weather icons here
            rows: 1
            pos_hint: {'top': 1, 'left': 1}
            size_hint: 1, .1
            Image:
                source: 'icons/workouts/weightlifting1.png'
            Image:
                source: 'icons/workouts/exercise.png'
        GridLayout:
            # Put two weather icons and avatar icon
            rows: 1
            pos_hint: {'top': .9, 'left': 1}
            size_hint: 1, .2
            Image:
                source: 'icons/workouts/weightlifting.png'
            Image:
                source: 'icons/avatars/man.png'
            Image:
                source: 'icons/workouts/bicycle.png'
        Label:
            # Welcome label
            pos_hint: {'top': .7, 'left': 1}
            size_hint: 1, .1
            text: 'Welcome to Workout App'
        GridLayout:
            # Banner grid
            rows: 1
            pos_hint: {'top': .6, 'left': 1}
            size_hint: 1, .4
        GridLayout:
            # Add 3 menu buttons here
            rows: 1
            pos_hint: {'top': .2, 'left': 1}
            size_hint: 1, .2
``
--> this is my app screen .kv file.

**Comment by sdp5404** [comment]
> I'm not sure if you've been coding for long, but taking a phone picture of part of your code, is not the way things are done at all. Please just copy and paste your code, into a code block and reply.

sorry I am a beginner in programming. I will copy-paste my code.
``
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import  Screen

class HomeScreen(Screen):
    pass
class SettingsScreen(Screen):
    pass

GUI = Builder.load_file('main.kv')
class MainApp(App):
    def build(self):
        return GUI
    def change_screen(self, screen_name):
        #get the screen manager from the kv file
        screen_manager = self.root.ids['screen_manager']
        screen_manager.current = screen_name
        #screen_manager = self.root.ids

MainApp().run()
``
--> this is my main file

``
#:import utils kivy.utils

<HomeScreen>:
    FloatLayout:
        GridLayout:
            canvas:
                Color:
                    rgba: utils.get_color_from_hex('#58AE6F')
                Rectangle:
                    size: self.size
                    pos: self.pos
            # Put two weather icons here
            rows: 1
            pos_hint: {'top': 1, 'left': 1}
            size_hint: 1, .1
            Image:
                source: 'icons/workouts/weightlifting1.png'
            Image:
                source: 'icons/workouts/exercise.png'
        GridLayout:
            # Put two weather icons and avatar icon
            rows: 1
            pos_hint: {'top': .9, 'left': 1}
            size_hint: 1, .2
            Image:
                source: 'icons/workouts/weightlifting.png'
            Image:
                source: 'icons/avatars/man.png'
            Image:
                source: 'icons/workouts/bicycle.png'
        Label:
            # Welcome label
            pos_hint: {'top': .7, 'left': 1}
            size_hint: 1, .1
            text: 'Welcome to Workout App'
        GridLayout:
            # Banner grid
            rows: 1
            pos_hint: {'top': .6, 'left': 1}
            size_hint: 1, .4
        GridLayout:
            # Add 3 menu buttons here
            rows: 1
            pos_hint: {'top': .2, 'left': 1}
            size_hint: 1, .2
``
--> this is my app screen .kv file.

**Comment by samdf96** [comment]
> sorry I am a beginner in programming. I will copy-paste my code.

No issues, we all have to start somewhere. Just a couple more things... Use the "Edit" feature, and modify your last post. Use the single quotation marks  to denote code, this will format it with indents. Since python is a language based on indentation, there is no way to troubleshoot your code if the code doesn't have the proper indentations. All you need to do is use single ` instead of the double ``. Use the "Preview Tab" to check how your code will look to others before you post.

**Comment by sdp5404** [comment]
> > sorry I am a beginner in programming. I will copy-paste my code.
> 
> No issues, we all have to start somewhere. Just a couple more things... Use the "Edit" feature, and modify your last post. Use the single quotation marks to denote code, this will format it with indents. Since python is a language based on indentation, there is no way to troubleshoot your code if the code doesn't have the proper indentations. All you need to do is use single ` instead of the double ``. Use the "Preview Tab" to check how your code will look to others before you post.

**Comment by sdp5404** [comment]
So i edited the last comment
