### ISSUE TITLE
kivy apk not safe

### ISSUE THREAD

**Issue by kengoon** [kivy/kivy#6814]
**Describe the bug**

i recently discovered that kivy apk on android can be decompiled with uncompyle6 and someone can collect sensitive information using the package uncompyle6. checkout this video https://www.youtube.com/watch?v=6N1jwqEz5KM
[https://www.youtube.com/watch?v=6N1jwqEz5KM](url)

**Comment by HypoT** [comment]
Decompiling an app isn't a bug. Apps are compiled & hence can be decompiled, you can obfuscate/cythonise you're code if you wish, though often no point in doing so. (EVERY is clickbait there, do you really believe they tested every kivy app? esp. those who chose to obfuscate)

Sensitive information shouldn't be included in an app anyway.

**Comment by kengoon** [comment]
> Decompiling an app isn't a bug. Apps are compiled & hence can be decompiled, you can obfuscate/cythonise you're code if you wish, though often no point in doing so. (EVERY is clickbait there, do you really believe they tested every kivy app? esp. those who chose to obfuscate)
> 
> Sensitive information shouldn't be included in an app anyway.

i did some test my self, I downloaded quadroply from playstore and decompiled it entirely

i think you have some point
