### ISSUE TITLE
Simple "Hello world" program shows blank screen on Kivy 1.11.1 & Python 3.7.7

### ISSUE THREAD

**Issue by facido** [kivy/kivy#6817]
Hi,

I wrote simple "Hello world" program using Kivy 1.11.1 & Python 3.7.7
The output was blank screen. Nothing on the screen. 
This same program works fine on Kivy 1.9.1 & Python 3.4.3

The source code is as follows:
-------------------------------------------------

from kivy.app import App
from kivy.uix.button import Button

class MyApp(App):
    def build(self):
        return Button(text='Hello world!')

MyApp().run()

-------------------------------------------------

I ran it on Windows 10 - 32 bit version.

The log file shows the following info:
-------------------------------------------------

> 

[INFO   ] [Logger      ] Record log in C:\Users\fafac\.kivy\logs\kivy_20-04-09_14.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\fafac\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\Users\fafac\AppData\Local\Programs\Python\Python37-32\pythonw.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'3.3.11672 Compatibility Profile Context'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'ATI Radeon 3000 Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 3
[INFO   ] [GL          ] Shading version <b'3.30'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available

> 

------------------------------------------------------------

Please help. I do not know why it works on Kivy 1.9.1 & Python 3.4.3 with Windows Vista but not on Kivy 1.11.1 & Python 3.7.7 with Windows 10 - 32 bit version.

**Comment by Anon6372098** [comment]
Looks like you have `virtual keyboard not allowed`. You can fix this by allowing virtual keyboard mode. Try putting this code above `class MyApp`:

`from kivy.config import config
Config.set('kivy, 'keyboard_mode', 'systemandmulti')`

**Comment by facido** [comment]
I tried but the same problem occurs.
The app shows blank screen.

**Comment by robertoweller** [comment]
To me, your code appears unidentified.

Did you mean your code like that?

`from kivy.app import App`
`from kivy.uix.button import Button`


`class MyApp(App):`
 ` ` ` ` `def build(self):`
 ` ` ` ` ` ` ` ` `return Button(text='Hello world!')`

`MyApp().run()`

In that case, try to change the version of your kivy. I noticed that you use a 32-bit system, I recommend using a 64-bit system. You said your python is Python 3.4.3, but from what the kivy log says it is 3.7

**Comment by facido** [comment]
My code is indented. It's just that I am not familiar with Github editor to make the code appear as indented.
I tried the code on Python 3.4.3 & Kivy 1.9.1 in Winodws Vista, and it works fine.
When I try it on Python 3.7.7 & Kivy 1.11.1 in Windows 10 - 32 bit version, I get blank screen and the app not responding.

Does Kivy have two different version as 32 bit and 64 bit?

**Comment by facido** [comment]
My code is indented. It's just that I am not familiar with Github editor to make the code appear as indented.

I tried the code on Python 3.4.3 & Kivy 1.9.1 in Winodws Vista, and it works fine.
When I try it on Python 3.7.7 & Kivy 1.11.1 in Windows 10 - 32 bit version, I get blank screen and the app not responding.

The Kivy log is what I received from the following test environment:
Python 3.7.7 & Kivy 1.11.1 in Windows 10 - 32 bit version

Does Kivy have two different version as 32 bit and 64 bit?

**Comment by facido** [comment]
My code is indented. It's just that I am not familiar with Github editor to make the code appear as indented.

I tried the code on Python 3.4.3 & Kivy 1.9.1 in Winodws Vista, and it works fine.
When I try it on Python 3.7.7 & Kivy 1.11.1 in Windows 10 - 32 bit version, I get blank screen and the app not responding.

The Kivy log is what I received from the following test environment:
Python 3.7.7 & Kivy 1.11.1 in Windows 10 - 32 bit version

Does Kivy have two different version as 32 bit and 64 bit?

Why do you recommend using 64 bit Windows?

**Comment by robertoweller** [comment]
Currently, they are stopping to support the 32-bit system and there are others than users complaining that in Windows 10 Kivy does not run.

**Comment by matham** [comment]
Kivy should work fine with 32-bit, although it's true eventually that may not be as supported. And kivy works fine with Windows 10.

Anyway, this seems to be a issue specific to your system. Please for help on discord as this is not likely a bug in Kivy. Unless people on discord indicate that this is a kivy bug.
