### ISSUE TITLE
Kivy on RPI4 throwing an error or not showing anything

### ISSUE THREAD

**Issue by aaflatooni** [kivy/kivy#6818]
I have installed fresh install of Raspbian Buster Lite (2020-02-13 release date) and followed the installation steps for Kivy detailed on the page (https://kivy.readthedocs.io/en/master/installation/installation-rpi.html)

The RPI4 only has two OpenGL options:
![image](https://user-images.githubusercontent.com/42128476/78944076-19cb0600-7a8b-11ea-9db1-992954c09c39.png)

I try to run the simple Hello World application:
```
import kivy

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()
```

When I use the Fake KMS option (dtoverlay=vc4-fkms-v3d) I get the following error:
`pi@raspberrypi:~ $ python3 test.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_20-04-09_3.txt
[INFO   ] [Kivy        ] v2.0.0rc1, git-26228b2, 20200409
[INFO   ] [Kivy        ] Installed at "/home/pi/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer, img_gif ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if runnonfig) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Could not initialize EGL'
  File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/__init__.py", line 70, in core_select_lib
    cls = cls()
  File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
    super(WindowSDL, self).__init__()
  File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 981, in __init__
    self.create_window()
  File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
    self.get_gl_backend_name())
  File "kivy/core/window/_window_sdl2.pyx", line 226, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
`

If I use the G1 Legacy driver then I get the following messages but no window and no "Hello World":

pi@raspberrypi:~ $ python3 test.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_20-04-09_7.txt
[INFO   ] [Kivy        ] v2.0.0rc1, git-26228b2, 20200409
[INFO   ] [Kivy        ] Installed at "/home/pi/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer, img_gif ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard allowed, multiuser mode, not docked
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO   ] [HIDInput    ] Read event from </dev/input/event3>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
[INFO   ] [HIDInput    ] Read event from </dev/input/event4>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <CHICONY USB Keyboard>
[INFO   ] [HIDMotionEvent] using <CHICONY USB Keyboard System Control>
[INFO   ] [HIDMotionEvent] using <eGalax Inc. eGalaxTouch EXC7910-1026-13.00.00>
[INFO   ] [HIDMotionEvent] <eGalax Inc. eGalaxTouch EXC7910-1026-13.00.00> range ABS X position is 0 - 4095
[INFO   ] [HIDMotionEvent] using <CHICONY USB Keyboard Consumer Control>
[INFO   ] [HIDMotionEvent] using <CHICONY USB Keyboard>
[INFO   ] [HIDMotionEvent] <eGalax Inc. eGalaxTouch EXC7910-1026-13.00.00> range ABS Y position is 0 - 4095
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [HIDMotionEvent] <eGalax Inc. eGalaxTouch EXC7910-1026-13.00.00> range position X is 0 - 4095
[INFO   ] [HIDMotionEvent] <eGalax Inc. eGalaxTouch EXC7910-1026-13.00.00> range position Y is 0 - 4095

Q1: which OpenGL driver needs to be used?
Q2: Why am I not seeing any window when I use the Legacy GL driver?

Thanks

**Comment by Lauszus** [comment]
@aaflatooni did you compile SDL2 from source?

**Comment by aaflatooni** [comment]
@Lauszus I tried removing again and following the instructions:
wget https://libsdl.org/release/SDL2-2.0.10.tar.gz
tar -zxvf SDL2-2.0.10.tar.gz
pushd SDL2-2.0.10
./configure --enable-video-kmsdrm --disable-video-opengl --disable-video-x11 --disable-video-rpi
make -j$(nproc)
sudo make install
popd

I even tried re-flashing the SD card with fresh OS and used the new version SDL2-2.0.12.tar.gz as well with the same result.

Can you confirm which OpenGL driver should be use on rpi4?

**Comment by Lauszus** [comment]
@aaflatooni please install `SDL2_image`, `SDL2_mixer` and `SDL2_ttf` as well: https://kivy.org/doc/master/installation/installation-rpi.html#raspberry-pi-4-headless-installation-on-raspbian-buster. Do not use SDL2 2.0.12. It did not work if I remember correctly.

You need to use `Fake KMS`. It should be the default one.

**Comment by aaflatooni** [comment]
That did the trick! I will give you eHugs if there wasn't Covid19.

So I guess I needed to select the Fake KMS before build.
(default is the legacy) 

THANK YOU!

**Comment by Lauszus** [comment]
@aaflatooni good to hear that you got it working! I'm 99 % sure that Fake KMS is the default. You must have changed :)

**Comment by aaflatooni** [comment]
@Lauszus 
You are right:
I did another flash of the SD card and went into /boot/config.txt and by default Fake KMS is enabled.

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d

When you go to raspi-config since G1 Legacy is first one then it is highlighted.  I guess I had pressed entered when in that menu.
