### ISSUE TITLE
ValueError: stat: path too long for Windows

### ISSUE THREAD

**Issue by rajarameshmamidi** [kivy/kivy#6819]
**Software Versions**
* Python: 3.7
* OS: windows 10
* Kivy: 1.11.1
* Kivy installation method: python -m pip install kivy==1.11.1

**Describe the bug**
Hi i am trying to display MP3 album art using kivy, mutagen and i am getting path too long for windows error when i pass album data directly. below was the code.

**Code and Logs and screenshots**

from kivy.app import App
from kivy.uix.widget import Widget
from kivy.uix.image import Image
from mutagen import File

class mpimg(App):
    def build(self):
        path = r'C:\my.mp3'
        art = File(path)
        cover = art['APIC:'].data        
        img = Image(source = str(cover)) 
        screen = Widget()
        screen.add_widget(img)
        return screen

mpimg().run()

**Comment by rajarameshmamidi** [comment]
could someone share the details.

**Comment by TomMurphy01** [comment]
Use Long Path Tool, Long Path Tool can simplify and probably end your problems in unlocking, managing, and renaming files that appear to have a long filename.
