### ISSUE TITLE
play audio from stop position

### ISSUE THREAD

**Issue by rajarameshmamidi** [kivy/kivy#6823]
**Software Versions**
* Python: 3.7
* OS: windows 10
* Kivy: 1.11.1
* Kivy installation method: python -m pip install kivy

**Describe the bug**
Hi ,
i am trying to play a song from stop position, but with below code it's playing from begin. could some one provide the details how to achieve this.

**Code and Logs and screenshots**

song = SoundLoader.load(path of .mp3 file)
song.play()
cur_pos = song.get_pos()
if song.state == 'play':
    song.stop()
elif song.state == 'stop' and str(cur_pos):
    song.play() 

Thanks,
raja

**Comment by arausch335** [comment]
Hi,
Did you find a solution for this? If so, please let me know.
