### ISSUE TITLE
Rename sys_platfrom in setup.cfg, installation on Rpi4

### ISSUE THREAD

**Issue by Satforst** [kivy/kivy#6826]
Hello,
I tried to install kivy on my rpi 4 4GB with Raspbian Buster Lite. I used this installation manual: https://kivy.org/doc/master/installation/installation-rpi.html
During installation, I had a lot of issues with this. Anyway, the worst problem was with `python -m pip install --user .` This command get me an error with https connection, so I was thinking the problem is in settings proxy or some else. After few hours testing, I opened setup.py and setup.cfg for investigate code. In setup.cfg is 
`base =
    pillow
    docutils
    pygments
    kivy_deps.angle~=0.2.0; sys_platform == "win32"
    kivy_deps.sdl2~=0.2.0; sys_platform == "win32"
    kivy_deps.glew~=0.2.0; sys_platform == "win32"
    pypiwin32; sys_platform == "win32"
full =
    pillow
    docutils
    pygments
    kivy_deps.gstreamer~=0.2.0; sys_platform == "win32"
    kivy_deps.angle~=0.2.0; sys_platform == "win32"
    kivy_deps.sdl2~=0.2.0; sys_platform == "win32"
    kivy_deps.glew~=0.2.0; sys_platform == "win32"
    pypiwin32; sys_platform == "win32"`

It was odd for me when I wanted to install Kivy on Rpi, so I renamed all "win32" to "rpi".
Voila installation was complete after few minutes...
I don`t know where exactly was error and I thinking it will be better when you will know about it.
If you already know about this issue please close it.

**Comment by Julian-O** [comment]
These extra_requires settings are limited to the win32 platform, so it isn't weird to see them in the cfg file even for Raspberry Pi.
