### ISSUE TITLE
Fast loop option within Kivy

### ISSUE THREAD

**Issue by Neex101** [kivy/kivy#6830]
I'd like to be able to run a fast loop somehow (e.g. 500Hz), in parallel to Kivy's Clock set at a standard framerate (e.g. 30Hz).

In my application, (in addition to the UI) I need a very simple `while` loop that has the ability to read a serial port, and I'd like that `while` loop to run as fast as the processor will allow. But because I'm only running a RasPi, I don't want to set the whole Kivy Clock to be zero interval to achieve this because it puts the CPU at 100% all the time.

Many thanks for everything Kivy :-)

**Comment by Neex101** [comment]
(appologies if I'm missing an exisiting workaround, I'm new)

**Comment by gottadiveintopython** [comment]
You might want to use [non-default Clock](https://kivy.org/doc/master/api-kivy.clock.html#advanced-clock-details), such as `Free Only Clock` and `Free Clock`.
Or just create a new thread instead.
