### ISSUE TITLE
pyinstaller reducing app size

### ISSUE THREAD

**Issue by hoba87** [kivy/kivy#6835]
**Software Versions**
* Python: 3.7
* OS: Win 10
* Kivy: 1.11.1
* Kivy installation method: pip

**Describe the bug**
I'm following the documentation at [https://kivy.org/doc/stable/guide/packaging-windows.html](https://kivy.org/doc/stable/guide/packaging-windows.html#including-excluding-video-and-audio-and-reducing-app-size) but getting an assertion error when using the runtime_hooks:
> assert self.hook_module_name not in HOOKS_MODULE_NAMES
>  AssertionError

Because everything is working fine without trying to reduce the app size, I guess it is a problem of kivy?

**Traceback**
>  Traceback (most recent call last):
> 1936 WARNING: stderr: Traceback (most recent call last):
>    File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
> 1949 WARNING: stderr:   File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
>      "__main__", mod_spec)
> 1967 WARNING: stderr:     "__main__", mod_spec)
>    File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
> 1982 WARNING: stderr:   File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
>      exec(code, run_globals)
> 1999 WARNING: stderr:     exec(code, run_globals)
>    File "C:\Program Files\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
> 2020 WARNING: stderr:   File "C:\Program Files\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
>    File "c:\program files\python37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
> 2039 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
>      run_build(pyi_config, spec_file, **vars(args))
> 2053 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
>    File "c:\program files\python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
> 2069 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
>      PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
> 2087 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>    File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
> 2102 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
>      build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
> 2123 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>    File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
> 2137 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
>      exec(code, spec_namespace)
> 2164 WARNING: stderr:     exec(code, spec_namespace)
>    File "main.spec", line 25, in <module>
> 2168 WARNING: stderr:   File "main.spec", line 25, in <module>
>      **minimal_deps)
> 2183 WARNING: stderr:     **minimal_deps)
>    File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
> 2195 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
>      self.__postinit__()
> 2201 WARNING: stderr:     self.__postinit__()
>    File "c:\program files\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
> 2215 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
>      self.assemble()
> 2228 WARNING: stderr:     self.assemble()
>    File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 343, in assemble
> 2242 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\building\build_main.py", line 343, in assemble
>      excludes=self.excludes, user_hook_dirs=self.hookspath)
> 2257 WARNING: stderr:     excludes=self.excludes, user_hook_dirs=self.hookspath)
>    File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 734, in initialize_modgraph
> 2271 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 734, in initialize_modgraph
>      user_hook_dirs=user_hook_dirs,
> 2284 WARNING: stderr:     user_hook_dirs=user_hook_dirs,
>    File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 116, in __init__
> 2296 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 116, in __init__
>      self._reset(user_hook_dirs)
> 2302 WARNING: stderr:     self._reset(user_hook_dirs)
>    File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 134, in _reset
> 2316 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 134, in _reset
>      self._hooks = self._cache_hooks("")
> 2330 WARNING: stderr:     self._hooks = self._cache_hooks("")
>    File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 215, in _cache_hooks
> 2334 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 215, in _cache_hooks
>      return ModuleHookCache(self, hook_dirs)
> 2349 WARNING: stderr:     return ModuleHookCache(self, hook_dirs)
>    File "c:\program files\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 100, in __init__
> 2361 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 100, in __init__
>      self._cache_hook_dirs(hook_dirs)
> 2370 WARNING: stderr:     self._cache_hook_dirs(hook_dirs)
>    File "c:\program files\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 133, in _cache_hook_dirs
> 2387 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 133, in _cache_hook_dirs
>      hook_module_name_prefix=self._hook_module_name_prefix,
> 2405 WARNING: stderr:     hook_module_name_prefix=self._hook_module_name_prefix,
>    File "c:\program files\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 289, in __init__
> 2420 WARNING: stderr:   File "c:\program files\python37\lib\site-packages\PyInstaller\depend\imphook.py", line 289, in __init__
>      assert self.hook_module_name not in HOOKS_MODULE_NAMES
> 2438 WARNING: stderr:     assert self.hook_module_name not in HOOKS_MODULE_NAMES
>  AssertionError
> 2454 WARNING: stderr: AssertionError

**Comment by pythonic64** [comment]
Can you try using Pyinstaller==3.5?

**Comment by hoba87** [comment]
It is running without an error with Pyinstaller 3.5.
The size does change marginally only for me, but thats seems to be because of numpy mkl libraries taking ~500MB.

**Comment by hoba87** [comment]
Compiling works, but when I want to execute the program, I got the error:
[ERROR  ] [Clock       ] Unable to import kivy._clock.

**Comment by pythonic64** [comment]
@hoba87 Did you solve runtime problem? The original 
>assert self.hook_module_name not in HOOKS_MODULE_NAMES
AssertionError

should be solved in PyInstaller==4.0. See https://github.com/kivy/kivy/issues/6871.
