### ISSUE TITLE
how to Enable and Disable gps in android using python/kivy.

### ISSUE THREAD

**Issue by Charanpreet-Singh-AI** [kivy/kivy#6837]
how to turn gps ON and OFF .
if gps is off it shows old coordinates or coordinates get from network but we need exact coordinates . please share the code to enable gps .
thanks

**Comment by Wlodarski** [comment]
You'll need an additional library like Plyer: https://github.com/kivy/plyer

**Comment by Charanpreet123** [comment]
How can i turn on gps in android ?

**Comment by Wlodarski** [comment]
Please read the documentation provided with **Plyer**: https://github.com/kivy/plyer/tree/master/examples/gps

----

You request permissions via the **buildozer.spec** :

```
#
# Android specific
#

# (list) Permissions
android.permissions = INTERNET,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION
```

And at [at runtime](https://www.msale.com/blog-2/2019/8/10/technology-at-msale-tips-amp-tricks-part-2-kivy-runtime-permissions-on-android).

**Comment by Charanpreet123** [comment]
Permission give access to gps .. but not enable gps on device , if the. Gps of device is off then it shows old coordinates . 
But we need to enable gps and access currwnt location

**Comment by Wlodarski** [comment]
On Android, you don't _turn on_ the GPS, you **request** permission to receive a location from it. It's the user that grant you the permission (or not) and it is the user that turns their the GPS. You don't turn on the GPS for them.

https://developer.android.com/training/permissions/requesting
