### ISSUE TITLE
Kivy Won't Install Properly macOS

### ISSUE THREAD

**Issue by SapphireHue** [kivy/kivy#6848]
I'm having difficulty installing Kivy. I'm using Python 3.8.2 and macOS 10.15.4.

I've been looking at the [installation guide](https://kivy.org/doc/stable/installation/installation-osx.html), but none of the methods listed seem to work. I've already tried a few different things, which may affect logs and such.

I tried 'python -m pip install kivy' in the terminal, which produces this (I've already tried this command before):
```
Requirement already satisfied: kivy in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (2.0.0rc1)
Requirement already satisfied: pygments in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from kivy) (2.6.1)
Requirement already satisfied: docutils in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from kivy) (0.16)
Requirement already satisfied: Kivy-Garden>=0.1.4 in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from kivy) (0.1.4)
Requirement already satisfied: requests in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from Kivy-Garden>=0.1.4->kivy) (2.23.0)
Requirement already satisfied: idna<3,>=2.5 in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests->Kivy-Garden>=0.1.4->kivy) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests->Kivy-Garden>=0.1.4->kivy) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests->Kivy-Garden>=0.1.4->kivy) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (from requests->Kivy-Garden>=0.1.4->kivy) (3.0.4)
```
However, Kivy doesn't show up in Applications, I don't notice anything different, and I'm not sure what to look for.

If I try to download it from the [downloads page](https://kivy.org/downloads/1.11.1/), I don't see any dmg files, only .whl. If I download one of the whl files and try to install it from the terminal using 'pip install Kivy-1.11.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl' I get the error that it's "not a supported wheel on this platform."

I'm not sure where to go from here, any help would be greatly appreciated.

**Comment by hvitis** [comment]
It's not gonna show in application. You have terminal to use it but you dont execute it directly.
1. Create buildozer init file
2. Create main.py example app
3. Run
`python main.py`

App should fireup
