### ISSUE TITLE
Problems Installing 1.11.1 and wheel

### ISSUE THREAD

**Issue by SirToews** [kivy/kivy#6850]
**Software Versions**
* Python: 3.8.2
* OS: Win10
* Kivy: 1.11.1
* Kivy installation method: PS/CMD

i'm trying to install but hangs up at wheel.

Have RAN>> python -m pip install --upgrade pip wheel setuptools virtualenv

'PS D:\> python -m pip install kivy==1.11.1
Collecting kivy==1.11.1
  Using cached Kivy-1.11.1.tar.gz (23.6 MB)
Processing c:\users\XXX\appdata\local\pip\cache\wheels\d2\72\1a\9ddd17f00755707937caa350616965fb3330a6270425f397e6\kivy_garden-0.1.4-py3-none-any.whl
Collecting docutils
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Building wheels for collected packages: kivy
  Building wheel for kivy (setup.py) ... error
  ERROR: Command errored out with exit status 3221225477:
   command: 'D:\Program Files\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXXX\\AppData\\Local\\Temp\\pip-install-dbip1dbk\\kivy\\setup.py'"'"'; __file__='"'"'C:\\Users\\artto\\AppData\\Local\\Temp\\pip-install-dbip1dbk\\kivy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\XXX\AppData\Local\Temp\pip-wheel-ij8lxiue'
       cwd: C:\Users\XXX\AppData\Local\Temp\pip-install-dbip1dbk\kivy\
  Complete output (530 lines):
  Using setuptools
  User distribution detected, avoid portable command.
  Using this graphics system: OpenGL
  WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)`

**Comment by tshirtman** [comment]
it is known 1.11.1 the wheels released for windows won't support 3.8, either use an older python version, like 3.7, or use the preview builds of 2.0.

`pip install --pre --extra-index-url https://kivy.org/downloads/simple kivy[base]`
