### ISSUE TITLE
Platform linux on some android devices

### ISSUE THREAD

**Issue by sergiomorillo** [kivy/kivy#6851]
### Versions

* Kivy: master (2.0.0rc1)

### Description

Last week I had to rebuild a kivy app that was working in many android devices. I normally do it with buildozer docker image.
I was able to create the apk again and it works as expected ... in some devices! In other ones the app crashes during splash screen due to a PermissionError. 
After debugging with adb logcat I noticed kivy is not recognizing the platform correctly as it return 'linux' instead of 'android'.
This causes that [ANDROID_APP_PATH is not used](https://github.com/kivy/kivy/blob/b6eddbb2fcf97a21b7f0c4cfbf0d8ccdb74fb3ec/kivy/__init__.py#L339) and it tries to write on /data/ path.

I'm using kivy==master on buildozer.spec.

### Logs

```
04-27 14:54:56.946  7788  7807 I python  : Android kivy bootstrap done. name is main
04-27 14:54:56.946  7788  7807 I python  : AND: Ran string
04-27 14:54:56.946  7788  7807 I python  : Run user program, change dir and execute entrypoint
04-27 14:54:57.303  7788  7807 I python  :  Traceback (most recent call last):
04-27 14:54:57.303  7788  7807 I python  :    File "/home/user/hostcwd/.buildozer/android/app/main.py", line 10, in <module>
04-27 14:54:57.304  7788  7807 I python  :    File "/home/user/hostcwd/.buildozer/android/app/app.py", line 4, in <module>
04-27 14:54:57.305  7788  7807 I python  :    File "/home/use
r/hostcwd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/__init__.py", line 351, in <module>
04-27 14:54:57.306  7788  7807 I python  :  PermissionError: [Errno 13] Permission denied: '/data/.kivy'
04-27 14:54:57.306  7788  7807 I python  : Python for android ended.
```

**Comment by tshirtman** [comment]
yep, likely related! I guess maybe it would be safer to replace "and" with "or" in this test, maybe expecting all of these paths to exists is a bit much, any of them should be a good enough indicator that we are on android.

**Comment by misl6** [comment]
My proposal is to add a env variable on p4a bootstrappers like we do in `kivy-ios`, it seems more clean to me:

https://github.com/kivy/kivy/blob/26228b202e821824afd8b2536234b26c23ae1b9d/kivy/utils.py#L434

**Comment by opacam** [comment]
Well, on p4a we set an environ variable to let apps know that we are in p4a `P4A_BOOTSTRAP`:

https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/bootstraps/common/build/jni/application/src/start.c#L86

**Comment by misl6** [comment]
@opacam Never seen that! So basically we could already detect if We're on android without any change on `p4a`.

I don't think that anyone is actually using `kivy` on Android without the aid of `p4a`, and also if there's such situation, the developer could easely set `P4A_BOOTSTRAP=1` in it's startup routine.

**Comment by sergiomorillo** [comment]
> Well, on p4a we set an environ variable to let apps know that we are in p4a `P4A_BOOTSTRAP`:

IMHO the environment variable described by @misl6 can unify the criterion in many OS builds and is more explicit.

**Comment by inclement** [comment]
Using an environment variable seems like a correct solution, I think the Kivy PR that broke things was misguided. It doesn't really matter what the env var is, arguably there's a case for making available both a `KIVY_BUILD` env var that the user can always override if they want, or if that isn't set making kivy fall back to the P4A_BOOTSTRAP env var.

**Comment by sergiomorillo** [comment]
FYI It works as expected in all devices. Thanks for quick response!
