### ISSUE TITLE
screenmananager.clear_widgets does not clear self.screens

### ISSUE THREAD

**Issue by michaelu123** [kivy/kivy#6857]
I called sm.clear_widgets(), but got a "Multiple Screens named..." message, when I added a Screen.
Probably the loop "for screen in screens: remove_widget(screen)" in clear_widgets, that changes the list over which it iterates, does not work as intended. Perhaps change to "for screen in screens[:]:" to iterate over a copy of the list.

**Comment by tshirtman** [comment]
this has been fixed in 58a3255d36, which isn't part of a stable release yet, please try the master version instead.
