### ISSUE TITLE
kivy Android Camera only select index 0

### ISSUE THREAD

**Issue by pasteurjr** [kivy/kivy#6860]
Python: 3.7
OS: android API 27 (Buildozer default)
Kivy:1.11.1
Kivy installation method: pip

**Describe the bug**
In Kv file, the logcat reports an error in parameter " index:"  of Camera Class when index is not "0". That is, it only works for index = 0.

**Comment by Julian-O** [comment]
Duplicate of #7732 (even though this one was earlier)
