### ISSUE TITLE
HID input missing *_abs_* parameter documentation

### ISSUE THREAD

**Issue by jabbaxm6** [kivy/kivy#6862]
**Is your feature request related to a problem? Please describe.**

The parameters:
* min_abs_x
* min_abs_y
* max_abs_x
* max_abs_y

are not documented: [HID input doc](https://kivy.org/doc/stable/api-kivy.input.providers.hidinput.html)

I found the parameters by accident and they were the solution to [my problem](https://groups.google.com/forum/embed/?place=forum%2Fkivy-users&hidesubject=true&hideforumtitle=true&showsearch=true&showpopout=true&parenturl=https%3A%2F%2Fkivy.org%2F%23#!topic/kivy-users/VgV5pTQEmBU)

**Describe the solution you'd like**
Add these parameters to the documentation page of HID input.

**Describe alternatives you've considered**
None.

**Additional context**
Could be useful for others who have this type of problem or are trying to calibrate their touch screens.

**Comment by tshirtman** [comment]
thanks for your report.

I created a PR for this, for this kind of simple things (or even bigger if you feel inclined to) don't hesitate to create a PR yourself, here it's a simple matter of adding the couple lines here.

https://github.com/kivy/kivy/blob/mggaster/kivy/input/providers/hidinput.py#L29

**Comment by tshirtman** [comment]
actually i'm not completly sure about the difference with position, i put "relative" to the previous ones, but maybe that's unwarranted, feedback welcome.

**Comment by jabbaxm6** [comment]
@tshirtman I didn't know I could open a merge request that easily. I thought I needed special rights. Thank you for your time to resolve this issue.

Well, that seems like the logical solution, if abs are the absolute values, then the position has to be relative. That would also be my guess. Maybe someone else can clarify?

Here is the Issue (#4078) that leads to adding the __abs__ parameters, sounds also like that the position is relatvie.

**Comment by tshirtman** [comment]
ok, i guess i'll merge, it should be an improvement over the current situation.
