### ISSUE TITLE
How to make exponential or logarithmic Slider ?

### ISSUE THREAD

**Issue by jerearaujo03** [kivy/kivy#6864]
Is it posible to make exponential or logarithmic Slider?

**Comment by tshirtman** [comment]
just create a new property for it that expresses the exponential or logarithmic value from the current value?

```
#:import log math.log
<LogSlider@Slider>:
    log_value: log(self.value)
```
and similar for exponential, just work in linear units and use whatever formula is appropriate to obtain the scale you want.
