### ISSUE TITLE
Slider `cursor_size`, `cursor_width` and `cursor_height` properties are not working

### ISSUE THREAD

**Issue by AndiEcker** [kivy/kivy#6867]
**Software Versions**
* Python: 3.6
* OS: Ubuntu 18.04
* Kivy: 1.11.0
* Kivy installation method: pip

**Describe the bug**
The cursor size of the Slider widget cannot be changed. The cursor icon will therefore always be shown with the size of the image used for the cursor icon.

**Expected behavior**
Cursor size should be changeable by one of the 3 provided properties of the Slider.

The PR #6859 (created 2 days ago) fixes this bug (by adding allow_stretch: True/keep_ratio: False to the Slider declaration within style.kv).

**Comment by tshirtman** [comment]
they do work, but to be of any use, you have to provide your own image, i'm not against merging this PR though, it's the user choice to have a deformed image, as they do have to ask for it, and can override the image if needed.

and yes, sorry, we have quite a backlog of PRs to review…

**Comment by AndiEcker** [comment]
@tshirtman @auvipy thanks for your review and approval.

although the size properties work to read the dimension of the image, they do not work for to change the image size and the Slider documentation is not reflecting this restriction (these properties should then be declared as read-only).

Additionally this change will not break back-wards-compatibility because the initial size of the slider icon will still be the original size of the image.

The apps I'm writing are tailored for old and handicapped people, providing to the app user the possibility to fine-adjust the sizes of image and fonts for better readability/usability. Although the app has a set of different image sizes integrated, sometime the user want to choose a user-specific size in-between the different size sets.

Its not a big show stopper for my apps but would be kind if you could merge #6859 into the kivy repository for future builds of my apps.

Thanks for kivy and all your work. <3

**Comment by tshirtman** [comment]
the PR was merged, so hopefuly that's fixed now :)
