### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by pjimenezmateo** [kivy/kivy#6869]
**Software Versions**
* Python: Python 3.7.4
* OS: Ubuntu 18.04
* Kivy: 1.11.1
* Kivy installation method: pip

**Describe the bug**
When running my application, 2 processes are spawned and both of them consume 100% CPU. I have checked the clock and even setting the maxfps to 1 FPS, the CPU usage remains the same.

I have profiled my program using cprofiler (attached) and I cannot fin anything that explains this outcome. 

The CPU usage is at 100% even when I do nothing with the app (I just start it) and there are no animations.

**Expected behavior**

The usage should be low when idle.

[myapp.zip](https://github.com/kivy/kivy/files/4592526/myapp.zip)

The code can be found here: https://github.com/pjimenezmateo/hobbes_python I know that I should split the code, but things snowballed over the last few days.

**Comment by tshirtman** [comment]
your program has a dependency on a git module that is not declared in the buildozer.spec and you don't have a requirements.txt or pipfile or whatever, so it's hard to check if the problem happens here as well. But does it happen with a simpler kivy app? If not, between a "hello world" and your program, what makes it max out your cpu? If you can pinpoint what piece of code causes this, and you believe it's a bug in kivy, it would be helpful to share more information about that.

**Comment by pjimenezmateo** [comment]
I am not currently building for Android so the buildozer.spec is outdated, I will try to create a requirements.txt

I will try to go back on git to try to pinpoint where the CPU is maxed, hopefully I can return with more information.

**Comment by pjimenezmateo** [comment]
You were right, the problem was not with kivy. As a workaround for kivy's audio not working for me, I used pygame mixer, and it seems that in its current version it has a bug that causes 100% CPU usage (https://github.com/pygame/pygame/issues/331).

You can easily fix so by installing pygame >= v2.
