### ISSUE TITLE
MESA-LOADER failed to open swrast

### ISSUE THREAD

**Issue by weizhuowang** [kivy/kivy#6872]
Hi,
I'm using RPI 4 with Ubuntu 20.04, while I have successfully installed the kivy, it returns an error when I tried to run the pong example: (using VS Code)

(GUI) ubuntu@ubuntu:~$  env DEBUGPY_LAUNCHER_PORT=36719 /home/ubuntu/archiconda3/envs/GUI/bin/python /home/ubuntu/.vscode-oss/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher /home/ubuntu/Documents/test_gui/test.py 
[INFO   ] [Logger      ] Record log in /home/ubuntu/.kivy/logs/kivy_20-05-09_24.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/ubuntu/archiconda3/envs/GUI/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.2 (default, Jan 11 2019, 18:52:21) 
[GCC 7.3.0]
[INFO   ] [Python      ] Interpreter at "/home/ubuntu/archiconda3/envs/GUI/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
MESA-LOADER: failed to open swrast (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  100
  Current serial number in output stream:  99

**Comment by LeoK987** [comment]
I am just having quite the same issue.  Posted it on kivy discusion: https://groups.google.com/forum/#!topic/kivy-users/WuU11G5Sb_I

**Comment by LeoK987** [comment]
I just figured out my issue, and it's due to the use of conda.  https://groups.google.com/d/msg/kivy-users/WuU11G5Sb_I/kWMTGLGzAwAJ
