### ISSUE TITLE
OSError: exception: access violation reading when resizing

### ISSUE THREAD

**Issue by oumnaya** [kivy/kivy#6874]
**Software Versions**
* Python: 3.7.7
* OS: win 10 pro 64 bits
* Kivy: 1.11.1
* Kivy installation method: pip install on venv on pycharm

**Describe the bug**

the windows become black (all text disappear) when i resize it with the corner bottom left or bottom left after 2-3 sec

error : 
File "_ctypes/callbacks.c", line 232, in 'calling callback function'
   File "C:\...\venv\lib\site-packages\kivy\input\providers\wm_touch.py", line 127, in _touch_wndProc
     lParam)
OSError: exception: access violation reading 0x0000021BFCA54000

**To Reproduce**
resize the windows with the corner bottom left or bottom left after 2-3 sec and movement

**Code and Logs and screenshots**

it's the same code in official website : 

```python
from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()
```

[INFO   ] [Logger      ] Record log in C:\...\.kivy\logs\kivy_20-05-11_56.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\...\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\hbouchard\Projets\C3amaker\src377\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.7262'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.7262'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "_ctypes/callbacks.c", line 232, in 'calling callback function'
   File "C:\...\venv\lib\site-packages\kivy\input\providers\wm_touch.py", line 127, in _touch_wndProc
     lParam)
 OSError: exception: access violation reading 0x0000021BFCA54000

**Additional context**

I don't have any problem when i resize with bottom or left, just with corner

I post for the first time in a bug tracker (and english is not my native language) sorry if i make mistake.

I'm on discord kivy channel with username oumnaya if needed.

Thank you

**Comment by ReDev1L** [comment]
I have same error
Python 3.7, kivy 1.11.1, Windows 10 pro x64

**Comment by matham** [comment]
Please try kivy master (`pip install kivy[base] kivy_examples --pre --upgrade`). Preferably in a new venv if you can.

**Comment by aekarahan** [comment]
This issue was closed in 2020, but today in 2024 I started with KivyMD this week, I have Python 3.12, and Kivy 2.3.0, kivymd 1.2.0 and after 4 years I see the problem left unsolved, still no response. I quit kivy and switch to tkinter world.

**Comment by Julian-O** [comment]
@aekarahan: Given no-one else has complained about this for 4 years, there is a chance it is a different problem, or an esoteric configuration that very few people have.

I would be happy to reopen this, if you are available to answer questions - but if you have stopped using Kivy, we have the problem that it can't be reproduced, investigated, and shown to be fixed.

What version of Windows were you working on? Was is a clean, fresh install? Can you please provide the logs?

**Comment by aekarahan** [comment]
Hi, thank you for your reply

Last night I wrote a detailed report, and asked this question in
Stackoverflow

https://stackoverflow.com/questions/77872108/kivy-application-widgets-disappear-when-resizing-window-issue

In this post you'll see the clear bug report generated by kivy as a log.

Best regards

Julian ***@***.***>, 24 Oca 2024 Çar, 04:11 tarihinde şunu
yazdı:

**Comment by ElliotGarbus** [comment]
@aekarahan 
KivyMD has updated to 2.0 and added that message to version 1.2. 
See: https://github.com/kivymd/KivyMD?tab=readme-ov-file#installation

**Comment by aekarahan** [comment]
Maybe, but version 1.2.0 also not worked, I've updated to developer versions as a last resort. None of them worked.

**Comment by ElliotGarbus** [comment]
I just did a clean install:
Kivy 2.3.0
KivyMD 1.2.0

I ran the following code:
```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
MDAnchorLayout:
    MDRaisedButton:
        text: "Hello World"
        md_bg_color: "red"
"""

class NewInstallHello(MDApp):
    def build(self):
        return Builder.load_string(kv)


NewInstallHello().run()
```
It worked as expected.   I suggest taking this discussion to the kivy Discord.  The github issues is for bugs.

**Comment by aekarahan** [comment]
I have two questions.
1) Which operating system did you try it on? If you read the messages in the log file, the problem seems to be specific to Windows (dll)
`
[WARNING] stderr: Exception ignored on calling ctypes callback function: <bound method _WindowsSysDPIWatch._wnd_proc of <kivy.core.window.window_sdl2._WindowsSysDPIWatch object at 0x00000290FB4F2F90>>
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\core\window\window_sdl2.py", line 998, in _wnd_proc
[WARNING] stderr:     return windll.user32.CallWindowProcW(
[WARNING] stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr: OSError: exception: access violation reading 0x000002909F58E3A8

`
2) Have you tried long enough? Sometimes it works fine for 15-20 new resizes and then crashes, sometimes it crashes after the first try.

**Comment by aekarahan** [comment]
I run your code on dev versions, I got following error. And the window closed immediately. Now I'll try with a clean install Kivy 2.3.0, KivyMD 1.2.0 as you did.

`(venv) D:\Learning\Projects\Kivy\Udemy\hello_kivymd>d:/Learning/Projects/Kivy/Udemy/hello_kivymd/venv/Scripts/python.exe d:/Learning/Projects/Kivy/Udemy/hello_kivymd/hello/hello.py
[INFO   ] [Logger      ] Record log in C:\Users\eakar\.kivy\logs\kivy_24-01-25_0.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.4.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.7.0
[INFO   ] [Kivy        ] v3.0.0.dev0
[INFO   ] [Kivy        ] Installed at "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 2.0.1.dev0, git-ab67546, 2024-01-23 (installed at "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 Compatibility Profile Context 22.20.27.09.230330'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Radeon RX 5500 XT'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\hello\hello.py", line 16, in <module>
     NewInstallHello().run()
   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\app.py", line 955, in run
     self._run_prepare()
   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\app.py", line 925, in _run_prepare      
     root = self.build()
            ^^^^^^^^^^^^
   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\hello\hello.py", line 13, in build
     return Builder.load_string(kv)
            ^^^^^^^^^^^^^^^^^^^^^^^
   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\lang\builder.py", line 412, in load_string
     self._apply_rule(
   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\lang\builder.py", line 625, in _apply_rule
     cls = Factory_get(cname)
           ^^^^^^^^^^^^^^^^^^
   File "d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\factory.py", line 147, in __getattr__   
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <MDRaisedButton>

(venv) D:\Learning\Projects\Kivy\Udemy\hello_kivymd>`

**Comment by ElliotGarbus** [comment]
Looking at the log I can see you are running the Kivy3.0 Dev version.  I suggest you run version 2.3.0

Here is my log:
```
[INFO   ] [Logger      ] Record log in C:\Users\ellio\.kivy\logs\kivy_24-01-24_14.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.4.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.7.0
[INFO   ] [Kivy        ] v2.3.0
[INFO   ] [Kivy        ] Installed at "C:\Users\ellio\PycharmProjects\kivy230help\.venv\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\ellio\PycharmProjects\kivy230help\.venv\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.2.0, git-Unknown, 2024-01-24 (installed at "C:\Users\ellio\PycharmProjects\kivy230help\.venv\Lib\site-packages\kivymd\__init__.py")
[WARNING] [KivyMD      ] Version 1.2.0 is deprecated and is no longer supported. Use KivyMD version 2.0.0 from the master branch (pip install https://github.com/kivymd/KivyMD/archive/master.zip)
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 546.09'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 2060/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
```
I suggested moving to Discord because this forum is for reporting bugs, not addressing support issues. 
If you don't like Discord there is also the Kivy users support group: https://groups.google.com/g/kivy-users

**Comment by ElliotGarbus** [comment]
I pip uninstalled kivyMD, and installed KivyMD 2.0.1.dev0.
I rewrote the hello world to work with the new api.
```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
MDAnchorLayout:
    MDButton:
        style: "elevated"
        MDButtonText:
            text: "Elevated"
"""

class NewInstallHello(MDApp):
    def build(self):
        return Builder.load_string(kv)


NewInstallHello().run()
```
It also works without error.  Here is the log:
```
[INFO   ] [Logger      ] Record log in C:\Users\ellio\.kivy\logs\kivy_24-01-24_22.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.4.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.7.0
[INFO   ] [Kivy        ] v2.3.0
[INFO   ] [Kivy        ] Installed at "C:\Users\ellio\PycharmProjects\kivy230help\.venv\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\ellio\PycharmProjects\kivy230help\.venv\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 2.0.1.dev0, git-Unknown, 2024-01-24 (installed at "C:\Users\ellio\PycharmProjects\kivy230help\.venv\Lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 546.09'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 2060/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [KivyMD      ] Color scheme generation. Get a color scheme from an installed palette - 0.006379899976309389 sec.
```
I suggest creating a new project directory and venv, and try again.

**Comment by aekarahan** [comment]
Somehow I see my answer above your post. Probably I pasted the new results below your previous post. Anyway, it is there.

**Comment by ElliotGarbus** [comment]
I suggest creating a new project directory and venv, and try again.

**Comment by aekarahan** [comment]
In my first post I wrote that I also tried with venv Kivy 1.3.2 and KivyMD
1.2.0 (first with poetry, then with pip venv) it didn't work.
And later I tried the dev versions as last resort.
I've tried maybe 10 different programs with all possible setups before I
report this issue.
Instead of endless and useless tries we should concentrate the errors in
logs I posted.

One thing I forgot to mention in my first post is that I use dual monitors.
One is 4K and the other is HD. Maybe the code that queries the dpi settings
crashes for this reason.
My suggestion is to review the code that query dpi settings (I made a guess
due to _WindowsSysDPIWatch).

[WARNING] stderr: Exception ignored on calling ctypes callback
function: <bound method _WindowsSysDPIWatch._wnd_proc of
<kivy.core.window.window_sdl2._WindowsSysDPIWatch object at
0x00000290FB4F2F90>>


Check the window_sdl2.py code, line 998

[WARNING] stderr:   File
"d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\core\window\window_sdl2.py",
line 998, in _wnd_proc


There is a possibility that code has wild pointer

[WARNING] stderr: OSError: exception: access violation reading
0x000002909F58E3A8



*I suggest to concentrate these messages*

[WARNING] stderr: Exception ignored on calling ctypes callback
function: <bound method _WindowsSysDPIWatch._wnd_proc of
<kivy.core.window.window_sdl2._WindowsSysDPIWatch object at
0x00000290FB4F2F90>>
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File
"d:\Learning\Projects\Kivy\Udemy\hello_kivymd\venv\Lib\site-packages\kivy\core\window\window_sdl2.py",
line 998, in _wnd_proc
[WARNING] stderr:     return windll.user32.CallWindowProcW(
[WARNING] stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr: OSError: exception: access violation reading
0x000002909F58E3A8


Elliot Garbus ***@***.***>, 25 Oca 2024 Per, 01:40 tarihinde
şunu yazdı:

**Comment by ElliotGarbus** [comment]
I cannot recreate your issue.  I will not be working to get to root cause.  

I suggest you create a new issue.  You appended these messages to a closed issue.  A closed issue will not get any attention.

**Comment by aekarahan** [comment]
Ok, thank you.

Elliot Garbus ***@***.***>, 25 Oca 2024 Per, 03:32 tarihinde
şunu yazdı:
