### ISSUE TITLE
urlrequest weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by FranciscoCarbonell** [kivy/kivy#6896]
I have seen that there is a solution for this
[https://stackoverflow.com/questions/49367546/kivy-weakly-referenced-object-no-longer-exists](url)
but I think setting a thread as an attribute is not the best option
What would be the best way to do this?
If multiple requests are created, handling in this way becomes very heavy, I can't think how to handle this situation. This only happens when running on android

**Comment by matham** [comment]
The original issue of `ReferenceError: weakly-referenced object no longer exists` has been fixed in master.
