### ISSUE TITLE
gradle dependency issue with aar files

### ISSUE THREAD

**Issue by daytipper1989** [kivy/kivy#6913]
**Software Versions**
* Python: 3.7
* OS: debian 10
* Kivy: 1.11.1
* Kivy installation method: pip, buildozer

When adding aars file and gradle dependencies as app requirements in buildozer.spec:

#for requesting permissions
android.add_aars = ./media/aars/support-compat-27.0.0.aar 

#for KivMob project (https://github.com/MichaelStott/KivMob)
android.gradle_dependencies = 'com.google.firebase:firebase-ads:10.2.0'

buildozer fails to build the app with this error:'

[DEBUG]:   	> Task :compileDebugJavaWithJavac 
[DEBUG]:   	Note: Some input files use or override a deprecated API.
[DEBUG]:   	Note: Recompile with -Xlint:deprecation for details.
[DEBUG]:   	Note: Some input files use unchecked or unsafe operations.
[DEBUG]:   	Note: Recompile with -Xlint:unchecked for details.
[DEBUG]:   	
[DEBUG]:   	> Task :transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
[DEBUG]:   	D8: Program type already present: android.support.v4.app.NotificationBuilderWithBuilderAccessor
[DEBUG]:   	
[DEBUG]:   	
[DEBUG]:   	FAILURE: Build failed with an exception.
[DEBUG]:   	
[DEBUG]:   	* What went wrong:
[DEBUG]:   	Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
[DEBUG]:   	> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/20.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/6.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/10.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/15.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/1.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/3.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/12.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/4.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/8.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/7.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/2.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/14.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/5.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/13.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/9.jar, /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/intermediates/transforms/dexBuilder/debug/11.jar
[DEBUG]:   	
[DEBUG]:   	* Try:
[DEBUG]:   	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[DEBUG]:   	
[DEBUG]:   	* Get more help at https://help.gradle.org
[DEBUG]:   	
[DEBUG]:   	BUILD FAILED in 13s
[DEBUG]:   	20 actionable tasks: 10 executed, 10 up-to-date
[DEBUG]:   	
[DEBUG]:   	
Exception in thread background thread for pid 28833:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/sh-1.12.14-py3.8.egg/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sh-1.12.14-py3.8.egg/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.8/site-packages/sh-1.12.14-py3.8.egg/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.8/site-packages/sh-1.12.14-py3.8.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/user/Projects/project_name/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/gradlew assembleDebug

  STDOUT:
Starting a Gradle Daemon (subsequent builds will be faster)

**Comment by zhenhuashao** [comment]
Did it work out? It happened to me, too
