### ISSUE TITLE
Pickling Error with multiprocessing

### ISSUE THREAD

**Issue by grap3-fru1t** [kivy/kivy#6915]
**Software Versions**
* Python: 3.7.2
* OS: Windows
* Kivy: 1.11.1
* Kivy installation method: installed with wheel.

**Describe the bug**
This issue has been initially reported in this [question](https://stackoverflow.com/questions/62148128/kivy-multiprocessing-does-nothing).
When running a GUI using multiprocessing, an error appears hinting that something is wrong with pickle in the EventDispatcher.

**Code snippet to Reproduce the error**
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.app import MDApp
from kivy.animation import Animation
import multiprocessing
import time

sm = ScreenManager()
Builder.load_string("""
<LoadingScreen>:
    BoxLayout:
        Button:
            id: loading_anim
            text: 'Hello'

<MainLayout>:
    BoxLayout:
        Button:
            text: 'world'
""")


class LoadingScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def on_pre_enter(self):
        t = multiprocessing.Process(target=self.loading_anim)
        t.start()
        t.join()

    def loading_anim(self):
        pass

class TestApp(MDApp):

    def build(self):
        sm.add_widget(LoadingScreen(name='menu'))
        return sm

if __name__ == '__main__':
    TestApp().run()
```

**Error message**
```
ForkingPickler(file, protocol).dump(obj)
File "stringsource", line 2, in kivy._event.EventDispatcher.__reduce_cython__
 TypeError: no default __reduce__ due to non-trivial __cinit__
```

**Full debug log:**

[error_example.txt](https://github.com/kivy/kivy/files/4717271/error_example.txt)

**Comment by matham** [comment]
We don't support pickling kivy objects. Instead, try passing a pure function or a method of an object that doesn't inherit from the kivy stack.

**Comment by grap3-fru1t** [comment]
pickle is being used automatically by the multiprocessing module. Is there no way in using multiprocessing with kivy?

**Comment by matham** [comment]
As I mentioned in the last post, you can use it on pure functions and non-kivy class methods that supports pickle, but not on kivy objects.
