### ISSUE TITLE
Keystroke Receiving - Input Monitoring

### ISSUE THREAD

**Issue by pr0x1ma-byte** [kivy/kivy#6920]
**Software Versions**
* Python: 3.6.8
* OS: Catalina 10.15.3
* Kivy: 1.11.1
* Kivy installation method: PyInstaller

**Describe the bug**

The bundled Kivy app asks for Keystroke Receiving (Input Monitoring) on first launch on macOS Catalina. 

**Expected behavior**
Unless I'm doing something that requires Kivy to monitor keystrokes from other apps, macOS shouldn't flag this.

**Comment by pjoshi-az** [comment]
I see this issue with my signed and notarized mac app. Is this a confirmed bug for kivy? I upgraded to the latest kivy release and still see this issue on catalina. Is there a way to workaround this for my app? Is there a plan to fix this soon if it all in kivy? Any updates would be deeply appreciated. Thank you!

**Comment by pjoshi-az** [comment]
Any help on this issue would be highly appreciated. Is this coming from kivy? Is there anything I can do to disable this dialog box? I am not able to find much info on this. Thanks!

**Comment by pjoshi-az** [comment]
I have some more information to share. I am using python 3.6.8, kivy 2.1 and pyinstaller 5.0 on macos Catalina.
Here are the exact reproduction steps:
1. Create a simple kivy app. All I did was create a window with nothing in it.
2. Use pyinstaller to bundle this app using these options - pyinstaller --clean --onefile --noconsole simplekivyapp.py
3. This will generate an osx bundle
4. Run the osx app and you will see the "Keystrokes Receiving" dialog box.
5. If I replace kivy with another python gui like pysimplegui and use pyinstaller to create the osx app bundle, I do not see the "keystrokes receiving" dialog box.

So, looks like kivy is doing something that gets flagged by macos Catalina and higher.

**Comment by grant100** [comment]
I have not come across any solutions to this yet unfortunately.

**Comment by grant100** [comment]
Looks like Kivy 2.0.0 doesn't have this issue @pjoshi-az.

**Comment by Julian-O** [comment]
Closing as stale because it works in Kivy 2.0. Thanks
