### ISSUE TITLE
Video & VideoPlayer: https video source url doesn't work

### ISSUE THREAD

**Issue by radiolondra** [kivy/kivy#6928]
**Software Versions**
* Python: 3.7.2
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: from official website

### My TEST app:

**main.py**
```
import kivy
kivy.require('1.11.1')
from kivy.app import App
from kivy.lang import Builder

class TestApplication(App):
    def build(self):
        this = Builder.load_file("main.kv")
        return this

TestApplication().run()
```
**main.kv**
```
VideoPlayer:
    # source: "http://clips.vorwaerts-gmbh.de/VfE_html5.mp4"  # <<<--- THIS WORKS
#    ---->>> THIS DOESN'T WORK <<<----
    source: "https://r8---sn-45nufxc-4jvl.googlevideo.com/videoplayback?expire=1591723683&ei=Q3LfXsXIA8fE1wLb36TwBA&ip=2001%3Ab07%3A5d2e%3A7026%3A44ba%3Ab60b%3A71bc%3A3d3&id=o-ANO6Otoejv0UAj1Wvs5xvS_6gNQ7Ux4xtoEy7W5YUel7&itag=18&source=youtube&requiressl=yes&mh=3o&mm=31%2C26&mn=sn-45nufxc-4jvl%2Csn-1gieen7e&ms=au%2Conr&mv=m&mvi=7&pl=45&initcwndbps=1058750&vprv=1&mime=video%2Fmp4&gir=yes&clen=22697541&ratebypass=yes&dur=325.102&lmt=1540530326435654&mt=1591701998&fvip=3&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgAr5vGAMGEshMasawf-Pxldwd4Bs56y7EJwd-ZVcEukYCIB-vVi5rd0q-c_ISE-Cnufeth1emKHYm5HYj6TTsG0t1&sig=AOq0QJ8wRAIgb7DPrRgrqkVenDMe9xWna5F1zFDqAKnZ35Cw3BxkY_kCIGpYM0GoGOycAkdetKPtqdEz_CY3Durw749epHnGxcfY"
```
### ERRORS REPORTED (Clicking on PLAY)
```
[ERROR  ] [VideoGstplayer] b'Secure connection setup failed.'
[ERROR  ] [VideoGstplayer] b'Internal data stream error.'
```

**COMMENTS**
I tried with several more simple HTTPS video sources, but the result is still the same: it doesn't work

I need to get/play videos using https protocol too.
Any idea?
What can I do?

**Comment by radiolondra** [comment]
I installed requests[security], but the problem is still the same. Same results when I click on Play:
```
[ERROR  ] [VideoGstplayer] b'Secure connection setup failed.'
[ERROR  ] [VideoGstplayer] b'Internal data stream error.'
```
Using `ffmpeg-python` and piping to `ffplay `everything works fine. 

```
probe = ffmpeg.probe(source)
vid_info= next(stream for stream in probe['streams'] if stream['codec_type'] == 'video')
width = int(vid_info['width']
height = int(vid_info['height']
nframes = int(vid_info['nb_frames']

process1 = (
  ffmpeg
  .input(source)
  .output('pipe:', format='rawvideo', pix_fmt='rgb24')
  .run_async(pipe_stdout=True)
)

process2 = subprocess.Popen(
  [
    'ffplay',
    '-f', 'rawvideo',
    '-pix_fmt', 'rgb24',
    '-s', '{}x{}'.format(width, height),
    '-i', 'pipe:',
  ],
  stdin=process1.stdout,
)
process1.wait()
process2.wait()

```

The problem is that ffplay doesn't seem to have a way to show interactive commands to control at least play/pause/stop/volume.

So... I don't know...
Any idea?

**Comment by radiolondra** [comment]
Also I wish to have this working everywhere and I don't know if using something different by Kivy's VideoPlayer/Video will give issues when I'll try to deploy on iOS or Android.

**Comment by pythonic64** [comment]
Try asking for help on support channel on Kivy Discord https://discord.gg/Jz8jBu .

**Comment by radiolondra** [comment]
@pythonic64 
Many thanks for your invite, I'll give a look to the Discord's channel.
In the meantime I'm exploring PyQt5. My idea is to create a media player with Qt and use it in my Python test app. This should assure portability to Windows, Linux, MacOS, Android and iOS.
After my tests, I'll put here the results.
Thank you

**Comment by matham** [comment]
You could also try using ffpyplayer instead. Although I haven't personally tried it.

**Comment by radiolondra** [comment]
@matham 
thanks for the suggestion, unfortunately ffpyplayer doesn't like https, and it's very strange because ffmpeg standard works fine with https (maybe some missed option compiling ffmpeg libs?). Also ffpyplayer doesn't include any player's GUI.

Peraphs the direct usage of GStreamer with souphttpsrc plugin could be the simplest and faster solution, but I'm not deeply sure about cross-platform. I need tests. 
Also it still needs a decent GUI player, and Qt could help in this. 
OR... to modify Kivy's VideoPlayer (why is it not using souphttpsrc?) and add https support. It shouldn't be a tragedy and this could give a real boost to Video & VideoPlayer widgets.

**Comment by radiolondra** [comment]
Ubuntu 18.04 GStreamer tests successful.
Needs: GStreamer + youtube-dl + souphttpsrc plugin (the latter is already included in gstreamer-plugins-good)

Command line:

`gst-launch-1.0 souphttpsrc is-live=true location="$(youtube-dl --format "best[ext=mp4][protocol=https]" --get-url https://www.youtube.com/watch?v=P7YMI39sObY)" ! qtdemux name=demuxer  demuxer. ! queue ! avdec_h264 ! autovideosink  demuxer.audio_0 ! queue ! avdec_aac ! audioconvert ! audioresample ! autoaudiosink`

The simplest way to launch this from python should be to use it in a subprocess... but I still need to test this way and it's not so important now.
The most important is that the same command line has to work with all the other OSes so that the cross-platform feature will be confirmed. 
Tests in progress.
