### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable @ Multithread python app

### ISSUE THREAD

**Issue by xtsyspi** [kivy/kivy#6929]
**Software Versions**
* Python: 3.7.3
* OS: Debian 10.3
* Kivy: 1.11.1
* Kivy installation method: python pip

**Describe the bug**
Hello, 

I am writing to You to ask for a suggestion to overcome a problem that is giving us sleepless nights. Together with my team, we are developing a Python application using Kivy whose part is, using a TextInput,  supposed to display rows of comments following a given algorithm to inform a user about what is going on, so the subsequent rows are added below the previous one. This is done in a thread in the background, because if the method is run in the mainthread, rows are not added one after another, but the application freezes until the method finishes and then displays  all rows in the TextInput at once. We are also using another thread to change states of some ToggleButtons in a different part of our application, and another one thread is used to update a Label which represents a clock.  Everything works as intended but unfortunately our application is not stable. Quite often it crashes suddenly with a following error code. Could you provide us with a solution to this issue? 

 

File "/home/pi/dev/version4/MainApp.py", line 761, in <module> 

    MyApp().run() 

  File "/home/pi/.local/lib/python3.7/site-packages/kivy/app.py", line 855, in run 

    runTouchApp() 

  File "/home/pi/.local/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp 

    EventLoop.window.mainloop() 

  File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop 

    self._mainloop() 

  File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop 

    EventLoop.idle() 

  File "/home/pi/.local/lib/python3.7/site-packages/kivy/base.py", line 345, in idle 

    Builder.sync() 

  File "/home/pi/.local/lib/python3.7/site-packages/kivy/lang/builder.py", line 788, in sync 

    call_fn(next_args[:-1], None, None) 

TypeError: 'NoneType' object is not subscriptable

**Comment by pythonic64** [comment]
Are you syncing with main thread when updating text input? Widgets are not thread safe and you should use `Clock` to sync when updating widget properties. 
You can use https://kivy.org/doc/stable/api-kivy.clock.html?highlight=clock#kivy.clock.mainthread or https://kivy.org/doc/stable/api-kivy.clock.html?highlight=clock#kivy.clock.CyClockBase.create_trigger to create and use trigger to call a `callback` in main thread which updates widget's properties.

**Comment by xtsyspi** [comment]
Thanks for the prompt reply and suggestions. I have been not be aware that widgets are not threads safe ;/, Now it's clear. So, we are going to use `Clock` to sync data between threads. I hope tomorrow we will have some positive effects...

**Comment by matham** [comment]
Yes, interacting with kivy properties or kivy widgets from other threads are not safe and will lead to unexpected behavior. All such interactions must go through the kivy clock which is the safe entryway into the kivy thread from other threads.
