### ISSUE TITLE
Documentation uses "percent", means "ratio"

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#6932]
Throughout the documentation are several examples like this:

> The size_hint is a tuple of values used by layouts to manage the sizes of their children. It indicates the size relative to the layout’s size instead of an absolute size (in pixels/points/cm/etc). The format is:

>     `widget.size_hint = (width_percent, height_percent)`

> The percent is specified as a floating point number in the range 0-1. For example, 0.5 is 50%, 1 is 100%.

This is a misuse of the term [percent](https://en.wikipedia.org/wiki/Percentage), which as its name suggests, is a ratio expressed as a fraction of 100.

A better term is "ratio".

This error threw me for a bit. I acknowledge I am coming from a mathematical background, and perhaps this is clear to others, so I haven't just gone ahead and made the change. I thought I would check it would be approved.

**Comment by D4SK** [comment]
I agree 1%. This should definitely be changed.

**Comment by Julian-O** [comment]
Fixed in #6963.
