### ISSUE TITLE
Carousel.load_previous()  doesn't work

### ISSUE THREAD

**Issue by dk825** [kivy/kivy#6934]
**Software Versions**
Python: 3.7.4
OS: Ubuntu 18.04
Kivy: 1.11.1
Kivy installation method: pip

**Describe the bug**
Hello! The method load_previous() from module Carousel doesn't work. It is strange for me, because load_next() works pretty good. Don't know how to correct this problem. 

```python
import kivy
kivy.require('1.11.1')

from kivy.app import App
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.uix.boxlayout import BoxLayout
import os
from kivy.factory import Factory
from kivy.uix.carousel import Carousel
from kivy.uix.widget import Widget
from kivy.uix.button import Button
from kivy.graphics import Color, Rectangle

sm = ScreenManager()

carousel = Carousel(direction='right')
folder = os.listdir(r'images/')
for f in range(0, len(folder)):
    path = r'images/' + folder[f]
    image = Factory.AsyncImage(source = path, allow_stretch = True)
    carousel.add_widget(image)

class ScreenThree(Screen):
    def __init__(self, **kwargs):
        super(ScreenThree, self).__init__(**kwargs)
        self.box = BoxLayout(orientation = 'vertical')
        self.box1 = BoxLayout(size_hint = (1, .12))
        self.box2 = BoxLayout(orientation = 'horizontal', size_hint = (1, .76))
        self.box3 = BoxLayout(size_hint = (1, .12))
        self.box21 = BoxLayout(orientation = 'vertical', size_hint = (.08, 1))
        self.box22 = BoxLayout(size_hint = (.55, 1))
        self.box23 = BoxLayout(orientation = 'vertical', size_hint = (.08, 1))
        self.box24 = BoxLayout(size_hint = (.29, 1))
        self.box211 = BoxLayout(size_hint = (1, 0.4))
        self.box212 = BoxLayout(size_hint = (1, 0.2))
        self.box213 = BoxLayout(size_hint = (1, 0.4))
        self.box231 = BoxLayout(size_hint = (1, 0.4))
        self.box232 = BoxLayout(size_hint = (1, 0.2))
        self.box233 = BoxLayout(size_hint = (1, 0.4))

        bt = Button(background_normal = 'background/left.png', background_down = 'background/leftw.png')
        bt1 = Button(background_normal = 'background/right.png', background_down = 'background/rightw.png')
        bt2 = Button(text = 'Menu')
        self.carousel = carousel
        self.box22.add_widget(self.carousel)
        **bt1.bind(on_release = self.carousel.load_next)
        bt.bind(on_release = self.carousel.load_previous)**
        bt2.bind(on_release = ScApp.changer)
        self.box212.add_widget(bt)
        self.box232.add_widget(bt1)
        self.box21.add_widget(self.box211)
        self.box21.add_widget(self.box212)
        self.box21.add_widget(self.box213)
        self.box23.add_widget(self.box231)
        self.box23.add_widget(self.box232)
        self.box23.add_widget(self.box233)
        self.box24.add_widget(bt2)
        self.box2.add_widget(self.box21)
        self.box2.add_widget(self.box22)
        self.box2.add_widget(self.box23)
        self.box2.add_widget(self.box24)
        self.box.add_widget(self.box1)
        self.box.add_widget(self.box2)
        self.box.add_widget(self.box3)
        self.add_widget(self.box)

    def prev(carousel):
        self.carousel.load_previous

class Manager(Widget):
    def __init__(self, **kwargs):
        super(Manager, self).__init__(**kwargs)
        self.screen_manager = sm
        self.screen_manager.add_widget(ScreenThree(name="screen_three"))


class ScApp(App):
    def build(self):
        return Manager().screen_manager
    def changer(self):
        sm.current = 'screen_one'


sample_app = ScApp()
sample_app.run()

```
Here the error message:

Traceback (most recent call last):
   File "sc.py", line 93, in <module>
     sample_app.run()
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 342, in idle
     self.dispatch_input()
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/home/wildim/anaconda3/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
 TypeError: load_previous() takes 1 positional argument but 2 were given

**Comment by gottadiveintopython** [comment]
The code below

```
bt1.bind(on_release = self.carousel.load_next)
bt.bind(on_release = self.carousel.load_previous)
```

should be

```
```
