### ISSUE TITLE
How to keep kivy at the front

### ISSUE THREAD

**Issue by onsunsl** [kivy/kivy#6948]
**Software Versions**
* Python: 3.6.6
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: Python -m pip install xxx

**Describe the bug**
Hello everyone, I wrote a PC-side application with kivy. The host is a dual-screen display. I set `Window.fullscreen = True` in the code. When the cursor moves to the secondary screen and clicks, kivy will be hidden. How to keep kivy at the front of screen and do not let it hide.

Thanks all

**Comment by tshirtman** [comment]
That's a platform specific thing, that might not even be enforcable on all of them, have a look at the win32/winxpgui and other modules like them to implement that on windows, this is outside of kivy's scope.
