### ISSUE TITLE
Unable to play video with ffpyplayer on windows

### ISSUE THREAD

**Issue by Wats0ns** [kivy/kivy#6949]
**Software Versions**
* Python: 3.7.7
* OS: Windows 10 Home
* Kivy: 1.11.1
* Kivy installation method: pip

**Describe the bug**
When trying to play a video with the Videoplayer on windows and ffpyplayer  for video rendering, I get the following error when hitting play:
```
[ERROR][ffpyplayer] output.mp4: Protocol not found
```
I then tried to enable ffmpeg as the video renderer, but then I get the following error:
```
 AttributeError: module 'ffmpeg' has no attribute 'FFVideo'
```
The video runs well when I play it on my system, or when I use the ffmpeg system installation on it, so I'm not sure what could be the problem

**Expected behavior**
I expected the video to play correctly

**To Reproduce**
This is basic Video app, not sure it would be useful to provide code, I think it's more someting installation related

**Code and Logs and screenshots**
Same thing as previous

**Comment by Bukmopbl4** [comment]
try this first:
python -m pip uninstall kivy.deps.gstreamer ffmpeg-python

**Comment by BaggioMarco** [comment]
I had the same problem. News on how to fixed? [ERROR ] [ffpyplayer ]video.mp4: Protocol not found

**Comment by Bukmopbl4** [comment]
> I had the same problem. News on how to fixed? [ERROR ] [ffpyplayer ]video.mp4: Protocol not found

in my case, I solved the problem by removing the videoplayers which I do not need

**Comment by matham** [comment]
Do you have a colon in the filename? What is the exact full filename of the video?

**Comment by matham** [comment]
Duplicate of https://github.com/kivy/kivy/issues/6964.

**Comment by Reyzhehal** [comment]
> ```
> python -m pip uninstall kivy.deps.gstreamer ffmpeg-python
> ```
This worked for my Windows 10. Thank you.

**Comment by Daniel190220** [comment]
Hope if I uninstall kivy deps.gstreamer,I won't gave bugs with kivy?

**Comment by paulPortos** [comment]
I uninstalled ffpyplayer and installed ffmpeg. It worked in my case
