### ISSUE TITLE
Improper overscroll behavior on windows

### ISSUE THREAD

**Issue by idevo89** [kivy/kivy#6952]
**Software Versions**
* Python: v3.8.2
* OS: Windows 10
* Kivy: v2.0.0rc3
* Kivy installation method: pip

**Describe the bug**
Scrollview and recycleview do not work properly when content size is smaller than parent size on Windows. Android does not have this issue (at least I could not reproduce it on Android).
Introduced by #6678 .

**always_overscroll=True & content size bigger**
ok

**always_overscroll=True & content size smaller**
Not ok, scrolling down scrolls the scrollview (recycleview) off the screen

**always_overscroll=False & content size bigger**
ok

**always_overscroll=False & content size smaller**
ok until you resize down so content size is bigger than parent, then the scroll won't work

**Expected behavior**
Correct overscroll behavior on desktop application.

**To Reproduce**
```python
if __name__ == '__main__':
    from kivy.app import App

    from kivy.uix.gridlayout import GridLayout
    from kivy.uix.button import Button

    class ScrollViewApp(App):

        def build(self):
            layout1 = GridLayout(cols=1, spacing=10, size_hint=(None, None))
            layout1.bind(minimum_height=layout1.setter('height'),
                         minimum_width=layout1.setter('width'))
            for i in range(40):
                btn = Button(text=str(i), size_hint=(None, None),
                             size=(200, 100))
                layout1.add_widget(btn)
            scrollview1 = ScrollView(bar_width='2dp', smooth_scroll_end=10)
            scrollview1.add_widget(layout1)

            layout2 = GridLayout(cols=1, spacing=10, size_hint=(None, None))
            layout2.bind(minimum_height=layout2.setter('height'),
                         minimum_width=layout2.setter('width'))
            for i in range(4):
                btn = Button(text=str(i), size_hint=(None, None),
                             size=(200, 100))
                layout2.add_widget(btn)
            scrollview2 = ScrollView(scroll_type=['bars'],
                                     bar_width='9dp',
                                     scroll_wheel_distance=100)
            scrollview2.add_widget(layout2)

            layout3 = GridLayout(cols=1, spacing=10, size_hint=(None, None))
            layout3.bind(minimum_height=layout3.setter('height'),
                         minimum_width=layout3.setter('width'))
            for i in range(40):
                btn = Button(text=str(i), size_hint=(None, None),
                             size=(200, 100))
                layout3.add_widget(btn)
            scrollview3 = ScrollView(bar_width='2dp', smooth_scroll_end=10,
                                     always_overscroll=False)
            scrollview3.add_widget(layout3)

            layout4 = GridLayout(cols=1, spacing=10, size_hint=(None, None))
            layout4.bind(minimum_height=layout4.setter('height'),
                         minimum_width=layout4.setter('width'))
            for i in range(4):
                btn = Button(text=str(i), size_hint=(None, None),
                             size=(200, 100))
                layout4.add_widget(btn)
            scrollview4 = ScrollView(scroll_type=['bars'],
                                     bar_width='9dp',
                                     scroll_wheel_distance=100,
                                     always_overscroll=False)
            scrollview4.add_widget(layout4)

            root = GridLayout(cols=4)
            root.add_widget(scrollview1)
            root.add_widget(scrollview2)
            root.add_widget(scrollview3)
            root.add_widget(scrollview4)
            return root

    ScrollViewApp().run()
```

**Comment by stevewells20** [comment]
I was in the middle of opening a very similar issue, may be part of the same bug. 

Observed on Windows 10 only (android and linux are both unaffected), when dynamically adding children to an oversized ScrollView, content will go through the DampenedScrollEffect animation, bouncing to the bottom of the viewport before returning to the resting location at the top. 

Interestingly, switching to effect_cls: ScrollEffect locks content to the bottom of the viewport. Both of these effects only occur in windows.

**Comment by tshirtman** [comment]
do you use the same version of kivy in windows an android/linux? because if it's this one, it should only be present in the development/rc release, so if you are using the stable version on android/linux, it's normal that you don't see it there.

**Comment by matham** [comment]
I think we need to fix this before the release as this will break things for people who want to keep the old behavior and setting it to `False`, which is pretty common on desktops.

FTR, simply setting `always_overscroll=False` to the scrollview example under examples/widgets/scrollview reproduces the issue.
