### ISSUE TITLE
TextInput: long text overflows textinput's border

### ISSUE THREAD

**Issue by gicanzo** [kivy/kivy#6953]
**Software Versions**
* Python: 3.7.5
* OS: Android, Windows (happens independently of OS)
* Kivy: 1.11.1
* Kivy installation method: (not sure?)

**Describe the bug**
With single line textinputs (multiline: False) long texts will overflow and the last letter typed in will not be visible.

To me, it seems to be an issue of the cursor. When the text overflows, if I press the right arrow (i.e. move the cursor right) I am then able to read the whole text. So the text does fit into the textinput, it is the cursor that seems to misbehave (instead of moving after the n typed letter, it stays at n-1).

**Expected behavior**
The last letter typed should be clearly visible.

**To Reproduce**

```python
from kivy.app import App
from kivy.core.window import Window
from kivy.lang import Builder
from kivy.uix.gridlayout import GridLayout
from kivy.uix.screenmanager import Screen, ScreenManager

class MainGrid(GridLayout):
    pass

kv = Builder.load_string(
'''
MainGrid:

<MainGrid>:
    size_hint: 1, 1
    cols: 1
    StackLayout:
        size_hint: 1,1
        TextInput:
            size_hint: 1, 1
            multiline: False
''')

class TrialApp(App):
    def build(self):
        return kv

if __name__ == "__main__":
    TrialApp().run()
```

**Additional context**
None

**Comment by pythonic64** [comment]
Can you try with `Kivy==2.0.0rc3`?

**Comment by gicanzo** [comment]
> Kivy==2.0.0rc3

You mean putting that in the buildozer.spec?

**Comment by pythonic64** [comment]
Yes and post here if it solved the issue.

**Comment by gicanzo** [comment]
Just tested it. Still happening with Kivy==2.0.0rc3
