### ISSUE TITLE
How can I use 'Input_type' from Focus Behavior

### ISSUE THREAD

**Issue by DAMIAN-Adol** [kivy/kivy#6955]
**Software Versions**
* Python: 3.7.3
* OS: Ubuntu 18.04 , Android 9, Samsung 
* Kivy: 1.10.1
* Kivy installation method: pip

**Describe the bug**
How should I use the `'input_type'` method now?

In the documentation it says it no longer inherits from the `TextInput` widget, **now specifies that it inherits from** `FocusBehavior`.

[`FocusBehavior.input_type` here](https://kivy.org/doc/stable/api-kivy.uix.behaviors.focus.html#kivy.uix.behaviors.focus.FocusBehavior.input_type)

I tried this ...

**Code and Logs and screenshots**
```python

from kivy.app import App
from kivy.uix.textinput import TextInput
from kivy.uix.behaviors.focus import FocusBehavior

class MyTextInput(TextInput,FocusBehavior):
    def on_parent(self, widget, parent):
        self.focus = True
        self.input_filter='float'
        self.input_type= 'number'

class SampleApp(App):
    def build(self):
        return MyTextInput()
SampleApp().run()
```

**but it doesn't work**

![Screenshot_20200618-135936_Pydroid 3](https://user-images.githubusercontent.com/57909540/85061847-129c3480-b16d-11ea-842b-8119615415c4.jpg)

**Comment by gottadiveintopython** [comment]
There are at least two wrong parts in your code.

1. `TextInput` is a subclass of `FocusBehavior` by default, so your code inherit `FocusBehavior` twice.
2. `Behavior` type classes usually need to be higher than widget in the mro, so `class MyWidget(FocusBehavior, Widget):` not `class MyWidget(Widget, FocusBehavior):`
