### ISSUE TITLE
Question regarding compatibility of screenmanagers add_widget (missing index and canvas arguments)

### ISSUE THREAD

**Issue by matthiasharrer** [kivy/kivy#6956]
Hi,

I just stumbled upon this error in my application when trying to call add_widget on a screenmanager:
`TypeError: add_widget() got an unexpected keyword argument 'index'`

It seems the implementation here: https://github.com/kivy/kivy/blob/855c9630ef84c31e261ef36a008e870195c13748/kivy/uix/screenmanager.py#L981
does not specify those keyword args.

Is this on purpose or should I go ahead and try to prepare a PR at least ignoring them or finding a more useful implementation?
The docs seem to tell that those additional parameters are supported: https://kivy.org/doc/stable/api-kivy.uix.screenmanager.html#kivy.uix.screenmanager.ScreenManager.add_widget

And as the Screenmanager is also a Widget I think the method should accept the same parameters :)

**Comment by pythonic64** [comment]
Pull request https://github.com/kivy/kivy/pull/6290 aims to fix this issue.

**Comment by matthiasharrer** [comment]
Oh I missed that one .. thanks 
Looking for it getting merged :)

**Comment by pythonic64** [comment]
You can review it if you have time or give opinion on current discussion.

**Comment by matthiasharrer** [comment]
I just looked at it today, but after the latest comments I don't feel I could add much to the discussion to be honest.

**Comment by pythonic64** [comment]
Solved by https://github.com/kivy/kivy/pull/6290.
