### ISSUE TITLE
Error not found

### ISSUE THREAD

**Issue by ankit879** [kivy/kivy#6987]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-83e5acb1d5ec> in <module>
----> 1 import kivy
      2 
      3 from kivy.app import App
      4 from kivy.uix.label import Label
      5 

ModuleNotFoundError: No module named **'kivy'******

**Comment by matham** [comment]
As I mentioned in https://github.com/kivy/kivy/issues/6986, we don't use github for support requests, but only for bug reports. For support please ask on discord. 

Please don't open multiple issues with the same support request.
