### ISSUE TITLE
Command line Error

### ISSUE THREAD

**Issue by ankit879** [kivy/kivy#6997]
C:\Users\ankit\AppData\Local\Programs\Python\Python38-32\Scripts>pip install kivy
Collecting kivy
  Using cached Kivy-1.11.1.tar.gz (23.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ankit\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-xqxe8hq8\\kivy\\setup.py'"'"'; __file__='"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-xqxe8hq8\\kivy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ankit\AppData\Local\Temp\pip-pip-egg-info-g3ps0g5w'
         cwd: C:\Users\ankit\AppData\Local\Temp\pip-install-xqxe8hq8\kivy\
    Complete output (81 lines):
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\ankit\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-wheel-9n4kuzu4\\cython\\setup.py'"'"'; __file__='"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-wheel-9n4kuzu4\\cython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ankit\AppData\Local\Temp\pip-wheel-nlju5a6c'
           cwd: C:\Users\ankit\AppData\Local\Temp\pip-wheel-9n4kuzu4\cython\
      Complete output (7 lines):
      Unable to find pgen, not compiling formal grammar.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cython
    ERROR: Failed to build one or more wheels
     WARNING: The wheel package is not available.
     Traceback (most recent call last):
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
         subprocess.check_call(cmd)
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\subprocess.py", line 364, in check_call
         raise CalledProcessError(retcode, cmd)
     subprocess.CalledProcessError: Command '['c:\\users\\ankit\\appdata\\local\\programs\\python\\python38-32\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\ankit\\AppData\\Local\\Temp\\tmpmyrj08sl', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.

     During handling of the above exception, another exception occurred:

     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "C:\Users\ankit\AppData\Local\Temp\pip-install-xqxe8hq8\kivy\setup.py", line 1073, in <module>
         setup(
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 143, in setup
         _install_setup_requires(attrs)
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
         dist.fetch_build_eggs(dist.setup_requires)
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 695, in fetch_build_eggs
         resolved_dists = pkg_resources.working_set.resolve(
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
         dist = best[req.key] = env.best_match(
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
         return self.obtain(req, installer)
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
         return installer(requirement)
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
         return fetch_build_egg(self, req)
       File "c:\users\ankit\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
         raise DistutilsError(str(e))
     distutils.errors.DistutilsError: Command '['c:\\users\\ankit\\appdata\\local\\programs\\python\\python38-32\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\ankit\\AppData\\Local\\Temp\\tmpmyrj08sl', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    Using setuptools
    User distribution detected, avoid portable command.
    Using this graphics system: OpenGL
    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

    WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

    ERROR: Dependency for context.pyx not resolved: config.pxi
    ERROR: Dependency for compiler.pyx not resolved: config.pxi
    ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for fbo.pyx not resolved: config.pxi
    ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for instructions.pyx not resolved: config.pxi
    ERROR: Dependency for opengl.pyx not resolved: config.pxi
    ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
    ERROR: Dependency for shader.pyx not resolved: config.pxi
    ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for texture.pyx not resolved: config.pxi
    ERROR: Dependency for vbo.pyx not resolved: config.pxi
    ERROR: Dependency for vertex.pyx not resolved: config.pxi
    ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for cgl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
    ERROR: Dependency for svg.pyx not resolved: config.pxi
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by matham** [comment]
As I mentioned before, for the third support issue now, we do not handle support requests on github. We use github purely for bug reports and not support requests. Also, you again opened two issues for this issue (https://github.com/kivy/kivy/issues/6996). Finally, this issue is already addressed at https://github.com/kivy/kivy/issues/6806.

Please ask on Discord at https://chat.kivy.org/ for any future support. If you continue to keep opening duplicate support issues, I may have to consider a temporary ban.
