### ISSUE TITLE
packaging kivy with briefcase on windows

### ISSUE THREAD

**Issue by jgirardet** [kivy/kivy#6999]
Hi guys,
I think it's directly a bug from kivy bug, investigating this bug is tricky so  I'm here for some help, to resolve it.

What is briefcase and what it does ?
-------------------------------------------------
it builds a package where your app is run from an embeded python interpreter. nothing is compiled ala pysintaller, just `embedpython -m myapp`.
Dependecies are specified in a pyproject.toml `require` section.
Command `briefcase dev -d` : install your dependecies un your virtualenv and run the app from your source.
Command `briefacase run`: creates a `windows` sub the directory of the packaged app and run the app from the package :
```
MyRepo
| ___ mymapp
| ___ windows
              |_MyApp
                  | __ src
                       |_ python
                       |_ app_packages
                           \_ kivy
                           |_ requests
                       |_ app
                         |_ myapp

```
in `python` there is an `embed python` with a python._pth fie to limit path to those 3 directories.
in `app` a copy of your app
in `app_packages` : the dependecies (the same from pyproject.toml in requiere) installed via the following  :
https://github.com/beeware/briefcase/blob/c09dffcfea53e0e4546abd4d52058313b6473fc3/src/briefcase/commands/create.py#L380

What the matter ?
-------------------------
Every thing is ok with `briefcase dev`.
But in `briefcase run -d`, I have the following error :

```
[INFO   ] [Logger      ] Record log in C:\Users\jim\.kivy\logs\kivy_20-07-15_9.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "C:\Users\jim\rien\kivybrief\helloworld\windows\Hello World\src\\app_packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\jim\rien\kivybrief\helloworld\windows\Hello World\src\python\python.exe"
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - ImportError: DLL load failed: Le module spécifié est introuvable.
  File "C:\Users\jim\rien\kivybrief\helloworld\windows\Hello World\src\\app_packages\kivy\core\__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\jim\rien\kivybrief\helloworld\windows\Hello World\src\\app_packages\kivy\core\window\window_sdl2.py", line 27, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] [App         ] Unable to get a Window, abort.
Unable to start application 'helloworld'
```
I know it's an error related to dependencies installation process. both for `dev` and `run` the dependecies are `["kivy==1.11.0","docutils", "pygments" ,"pypiwin32" ,"kivy_deps.sdl2==0.1.22","kivy_deps.angle==0.1.9"]`

Dependencies are although installed  `app_packages`

I have It both for kivy stable and 2.0.0rc3.

I create an issue there https://github.com/beeware/briefcase/issues/452 with all few steps to reproduce it.

I'm looking here some advice to help me debugging it, just where to start search. It's only on wnidows, it's doing great on linux.

Thanks

**Comment by matham** [comment]
I'm not sure how briefcase works, but kivy_deps work by installing the required dll binaries to `share/dep_name`. Very likely briefcase doesn't copy these required dlls when it's created.

You can find the exact directory that contain the dlls by printing `from kivy_deps import sdl2; print(sdl2.dep_bins)` and see if the printed path exists in briefcase. If it doesn't you'll somehow have to copy these dlls and make sure they are on the path.

**Comment by jgirardet** [comment]
that was it, thank for your help
