### ISSUE TITLE
Dimensions of kivy app changed after deployment to android

### ISSUE THREAD

**Issue by nidhaloff** [kivy/kivy#7000]
**Software Versions**
* Python: 3.7
* OS: android
* Kivy: 1.11.1
* Kivy installation method:

**Describe the bug**
The app works perfectly on my laptop. However, when I build and deploy the app to my android phone with buildozer, the dimension changes, precisely the font size looks very small on the app.

**Expected behavior**
Expected is that the UI looks same as on my laptop in the dev mode

**To Reproduce**

**Code and Logs and screenshots**
```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.
```

**Additional context**

**Comment by pythonic64** [comment]
Use `sp` when assigning font sizes and `dp` for widget sizes, like:
- `font_size = '20sp'`
- `width = '200dp'`

See https://kivy.org/doc/stable/api-kivy.metrics.html
