### ISSUE TITLE
on_stop method is not called on Android

### ISSUE THREAD

**Issue by mzakharocsc** [kivy/kivy#7003]
**Software Versions**
* Python: 3.7.1
* OS: Android 8.1
* Kivy: 1.11.1
* Kivy installation method:  buildozer

**Describe the bug**

When user closes the app through the Android task switcher,  SDLActivity ```onDestroy``` method is called, however ```on_stop``` method in the Kivy app is not dispatched as a result.  

In contrast, ```on_stop``` is correctly called if an app runs on Linux, and user presses the 'x' button in the window bar.

**Expected behavior**
```on_stop()``` handler is dispatched on Android, so that the app can perform cleanup.

**Comment by gottadiveintopython** [comment]
I believe that's a correct behavior not a bug. If you want to ensure some code to be excuted before the app gets destroyed, use `on_pause` instead.
