### ISSUE TITLE
App Lagging

### ISSUE THREAD

**Issue by sumanece9** [kivy/kivy#7012]
I m getting a delay response in kivymd output window while trying to run the following code.I am using win10 & i tried to reinstall my graphics driver(intel 4000) it didn't help though. it was running fine earlier. I have reinstalled everything still problem persist. please help.

from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label

class YourApp(App):
def build(self):
root_widget = BoxLayout(orientation='vertical')

    output_label = Label(size_hint_y=1)

    button_symbols = ('1', '2', '3', '+',
                      '4', '5', '6', '-',
                      '7', '8', '9', '.',
                      '0', '*', '/', '=')

    button_grid = GridLayout(cols=4, size_hint_y=2)
    for symbol in button_symbols:
        button_grid.add_widget(Button(text=symbol))

    clear_button = Button(text='clear', size_hint_y=None,
                          height=100)

    root_widget.add_widget(output_label)
    root_widget.add_widget(button_grid)
    root_widget.add_widget(clear_button)

    return root_widget
YourApp().run()

**Comment by quitegreensky** [comment]
What kind of delay? i didn't notice any delay. and where is the kivymd part?
