### ISSUE TITLE
how to get android TV remote controller input

### ISSUE THREAD

**Issue by yumoqing** [kivy/kivy#7013]
**Software Versions**
* Python: python 3.7
* OS: android TV
* Kivy: 1.11.1
* Kivy installation method: buildozer

**Describe the bug**
Does any one know how the kivy app on android TV to catch its remote controller's input. example code are welcomed

Thanks

**Comment by jeyfrinjulian** [comment]
hello, you can use the irBlaster module of the plyer library and encode the codes of your tv

**Comment by yumoqing** [comment]
Thanks for your reply, I will try it
