### ISSUE TITLE
Kivy exe file not launching because of not getting an image provider

### ISSUE THREAD

**Issue by taha-lyousfi** [kivy/kivy#7016]
* Python: 3.6.7
* OS:Windows 7 pro
* Kivy:1.11.1
* Kivy installation method: pip install kivy

**Describe the bug**
Hi, after converting my .py file containing my kivy app(note: I used Builder.load_string), I used pyinstaller 3.6.When I try to open my main.exe file it shows this logs:
```python
[INFO   ] [Logger      ] Record log in C:\Users\HP\.kivy\logs\kivy_20-07-26_93.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\HP\AppData\Local\Temp\_MEI54242\kivy\__init__.pyc"
[INFO   ] [Python      ] v3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSCv.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\HP\Desktop\file\dist\main.exe"

[INFO   ] [Logger      ] Purge log fired. Analysing...
[INFO   ] [Logger      ] Purge 14 log files
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers:  (img_tex, img_dds, img_ffpyplayer, img_gif, img_pil, img_sdl2 ignored)
[CRITICAL] [App         ] Unable to get any Image provider, abort.
```
**Expected behavior**
I expected that a kivy window opens normally but the result wasn't as expected.Some help please!
**Additional context**
I searched in stackoverflow but I found one question related:
https://stackoverflow.com/questions/46988763/kivy-unable-to-get-any-image-provider-abort
and there was no valuable answers.
And here is my main.py if it is necessary(and sorry for the weird variables names):

[main.zip](https://github.com/kivy/kivy/files/4978256/main.zip)

**Comment by pythonic64** [comment]
Seems that you didn't modify your `.spec` script to include sdl2 binaries. See steps in https://kivy.org/doc/stable/guide/packaging-windows.html to properly package your app.
