### ISSUE TITLE
Kivy Android Service crash main app

### ISSUE THREAD

**Issue by Server48** [kivy/kivy#7018]
Hi, I have the following problem and have already crawled the whole internet. I have never seen anything like this, maybe I am doing something wrong.

The crux of the problem: There is a main application and its service, the service goes into the background and constantly parses one site for changes. In case of a found change, it gives a notification and starts vibration. It's all done, BUT.

When I want to return to the main application (it is turned off, only the service is running), then I just have a dark screen and does not load, I roughly understand why this happens from the point of view of Python, but I don’t understand how to fix it. I need a fairly simple service base that does only two things and then starts the main application all over again.

1. Python 3.8
2.kivy == 2.0.0 rc3
3.pygame == 2.0.0 dev6
4.Buildozer == 1.2.0

I give a simple example without unnecessary things, what I do

main app
```from kivy.app import App
from kivy.lang import Builder
from kivy.utils import platform
from kivy.uix.button import Button
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.button import Button

class ServiceApp(App):
    def build(self):
        self.layout = FloatLayout()
        
        Mbutton = Button(
            text='start',size_hint=(.2, .1), pos_hint={"center_x": 0.2, "center_y": 0.5},color=[1,1,1,1]
        )
        Mbutton.bind(on_press=self.butcheck)
        self.layout.add_widget(Mbutton)
        return self.layout
    def butcheck(self,instance):
        from androidф import AndroidService
        service = AndroidService('my pong service', 'running')
        service.start('service started')
        self.service = service
if __name__ == '__main__':
    ServiceApp().run()
```

Service
```
from time import sleep
from jnius import autoclass,cast
from plyer import notification,vibrator
PS=autoclass('org.kivy.android.PythonService')
PS.mService.setAutoRestartService(True)
if __name__=='__main__':
   while True:
      i=i+1
      if i==40:
         notification.notify(title="test",
                    message="test",
                    app_name="App",
                    timeout=3)  




```

I suppose it is either my wrong approach or setRestart to blame. Help at least identify what the problem is. I am attaching a compiled version with this, you can try on your 10 android [https://yadi.sk/d/gmz-yz1lVmR0AQ](url)

and this is also a question, why does setRestart only work on 10?

**Comment by tshirtman** [comment]
does this happen only if you have a service?
did you look in the log for what happens when you leave or start the app?

**Comment by Server48** [comment]
Yes, this is only when the service is running. I even made two applications as a temporary solution and the second is responsible for the service that calls the first main application. Actually, on kiwi I only encountered a service problem.
 The algorithm of the problem is as follows: I launch the application, start. I turn off the main application, the service restarts and it works without any problems. Now I want to go back to the main thing, I launch it - just a screen (not dark, but which is before loading the kiwi logo). At the same time, nothing is written in the console, no errors, nothing - the service also works further. Only after turning off the service completely does the main application start.

**Comment by Server48** [comment]
if I turn off the infinite loop in the service forcibly, then the service just crashes, it does not close completely (I don’t know if it should be this way or not) and the error appears 
QarthPatchMonintor :: CheckNotifyEvent before read
 QarthPatchMonintor :: CheckNotifyEvent

**Comment by Server48** [comment]
Checked on other kiwi versions. Problem still exists. Can someone tell me if I generally apply the correct approach to the implementation of the service or should it be somehow different?

**Comment by InDividjualCreations** [comment]
> Checked on other kiwi versions. Problem still exists. Can someone tell me if I generally apply the correct approach to the implementation of the service or should it be somehow different?

i also have the same error. anybody explain????
