### ISSUE TITLE
The size of the kivy screen

### ISSUE THREAD

**Issue by Mahdi51907825** [kivy/kivy#7026]
Hello world !
My question is not a problem , but a normal question , because I'm still learning kivy and I found some difficulties

1- how to fix the size of the screen of the application 
2- how to make a round boutton

**Comment by pythonic64** [comment]
(1) You can use `Window.size` or `Window.system_size` to get/set size of app window.
See https://kivy.org/doc/stable/api-kivy.core.window.html?highlight=window#kivy.core.window.WindowBase.size

(2) Use [RoundedRectangle](https://kivy.org/doc/stable/api-kivy.graphics.vertex_instructions.html?highlight=roundedrectangle#kivy.graphics.vertex_instructions.RoundedRectangle) with [ButtonBehavior](https://kivy.org/doc/stable/api-kivy.uix.behaviors.button.html?highlight=buttonbehavior#module-kivy.uix.behaviors.button)
