### ISSUE TITLE
"Could not find a version that satisfies the requirement kivy.dep.sd12

### ISSUE THREAD

**Issue by JAA2000** [kivy/kivy#7029]
I'm trying to use Kivy, but when I try to install I get the message above. I'm using Python 3.7.1. I attached a file of the code below. Thank you.
![kivy issue](https://user-images.githubusercontent.com/69207629/89311249-c08f6f80-d643-11ea-96e3-8b5d7fbc35d5.PNG)

**Comment by pythonic64** [comment]
You have a typo in your command. It should be `kivy.deps.sdl2` and not `kivy.deps.sd12`, so just replace `1` with `l` (lowercase letter L).

**Comment by JAA2000** [comment]
Thanks1

**Comment by JAA2000** [comment]
Thanks!
