### ISSUE TITLE
Pyp1w1n32 not recognized 

### ISSUE THREAD

**Issue by JAA2000** [kivy/kivy#7030]
Hello, I have installed kivy and tried to used pycharm and it wouldn't recognize it, so I went back and tried to rewrite the code but now it won't recognize one of the strings. I have a picture attached. I tried pyplwin32 as well as pyplw1n32. Is it a typo still? Thank you.
![kivy issue 2](https://user-images.githubusercontent.com/69207629/89340144-4673e080-d66d-11ea-8919-cbb06f85c37b.PNG)

**Comment by pythonic64** [comment]
It should be `pypiwin32`.
