### ISSUE TITLE
Kivy on Pycharm

### ISSUE THREAD

**Issue by Broezion3** [kivy/kivy#7034]
I'm trying to install Kivy and Kivymd on Pycharm on my Mac with Catalina, and it say me a lot of errors.
I've got python 3.8.5 and pip 20.2.1.
I've already install Kivy's app but it doesn't work, What I can do?
Thanks
<img width="968" alt="Schermata 2020-08-06 alle 17 54 32" src="https://user-images.githubusercontent.com/69159174/89553579-fe3ff400-d80d-11ea-9fd4-54a938a45acf.png">

**Comment by dracorlll** [comment]
I am not a expert but I found a similar problem on stackoverflow. [https://stackoverflow.com/questions/60438263/unable-to-install-kivy-on-macos10-15-using-pip](url) 
He solves the problem remove Python 3.8 and install 3.7

**Comment by Broezion3** [comment]
Thanks so much 

Cristian Mazzoni

> Il giorno 7 ago 2020, alle ore 04:06, Engin Yüksel <notifications@github.com> ha scritto:
> 
> https://stackoverflow.com/questions/60438263/unable-to-install-kivy-on-macos10-15-using-pip

**Comment by Broezion3** [comment]
I find the solution,
if you are on Catalina, you must install the beta version of kivy           USE THIS string in Pycharm terminal`pip install kivy==2.0rc3.`
