### ISSUE TITLE
Documentation issue with on_ref_press

### ISSUE THREAD

**Issue by Kateba72** [kivy/kivy#7037]
In [kivy/uix/label.py L1008](https://github.com/kivy/kivy/blob/master/kivy/uix/label.py#L1008), there is a documentation issue with on_ref_press.

`widget.on_ref_press(print_it)` should be `widget.bind(on_ref_press=print_it)`.

**Comment by tshirtman** [comment]
Indeed, feel free to edit directly in the page you linked, that'll create a pull request and you'll be officially a contributor :)
