### ISSUE TITLE
packages in doc-requirements.txt are incompatible

### ISSUE THREAD

**Issue by tcdejong** [kivy/kivy#7044]
**Software Versions**
* Python: 3.8.2 64-bit
* OS: Windows 10
* Kivy: full clone of main branch up to commit #5c8cb1f (merging #7009 )
* Kivy installation method: fork, clone

**Describe the bug**
This is a bug in the process of documentation updates instead of with Kivy itself.  
Installing the packages from the provided `./doc/doc-requirements.txt` skips four packages as they require a newer version of `sphinx` than the version is locked to.  Terminal output provided below.

**Expected behavior**
Install all packages succesfully.

**To Reproduce**

- Navigate terminal to `kivy/doc`
- run `pip install -r doc-requirements.txt`

**Code and Logs and screenshots**
```
sphinxcontrib-seqdiag 2.0.0 requires Sphinx>=2.0, but you'll have sphinx 1.7.9 which is incompatible.
sphinxcontrib-nwdiag 2.0.0 requires Sphinx>=2.0, but you'll have sphinx 1.7.9 which is incompatible.
sphinxcontrib-blockdiag 2.0.0 requires Sphinx>=2.0, but you'll have sphinx 1.7.9 which is incompatible.
sphinxcontrib-actdiag 2.0.0 requires Sphinx>=2.0, but you'll have sphinx 1.7.9 which is incompatible.
Successfully installed sphinx-1.7.9
```

**Additional context**
-

**Comment by misl6** [comment]
Fixed via #7623
