### ISSUE TITLE
error with sqlite3 module import (android)

### ISSUE THREAD

**Issue by vbazhin** [kivy/kivy#705]
Does not import sqlite3 module, while trying to run application on Launcher, even if making .apk (./distribute.sh -m 'sqlite3 kivy' ) (adb logcat show importError "no module named sqlite3")
The same problem  found https://groups.google.com/forum/#!topic/kivy-users/AUO0Qpu0yH4

Also, the folder python-for-android/build/sqlite3 exists but empty

python-for-android/dist/default/python-install/lib/python2.7/lib-dynload/_sqlite3.so does not exist

python-for-android/dist/default/private/lib/python2.7/lib-dynload/_sqlite3.so does not exist

**Comment by erm3nda** [comment]
that link no longer works: [https://python-for-android.readthedocs.io/en/latest/faq/#sqlite3-so-not-found](https://python-for-android.readthedocs.io/en/latest/faq/#sqlite3-so-not-found)

**Comment by ngala** [comment]
This is because p4a was re-written in 2015 and the old documentation has been moved to ''old_toolchain".

The above link https://python-for-android.readthedocs.io/en/latest/faq/#sqlite3-so-not-found
is now https://python-for-android.readthedocs.io/en/latest/old_toolchain/faq/#sqlite3-so-not-found
