### ISSUE TITLE
Interactive plots in kivy android app

### ISSUE THREAD

**Issue by sai3910** [kivy/kivy#7050]
**Main**

Though Kivy with extensive features is trending for cross platform applications. I would like to suggest a point that now a days analytics is spreading all the sections of professions. To embed interactive graphs like plotly, canvas, highcharts features to be added into kivy application too. Pardon me if any already existed library for the interactive graph please let me know other than matplotlib(which supports static images). 

My intention is to not only static plots but also interactive plots should be embedded into the mobile/desktop application.

Thanking you.

**Comment by lasupernova** [comment]
I am also thinking about embedding interactive plots (plotly) inti the kivy app that I'm building. But there seems to be no easy way to do this, right)

**Comment by tshirtman** [comment]
I did implement custom interactive graphs for a few apps, but never found the time to make them into a library, kivy actually makes it pretty easy to write custom graphs, being time series, bar graphs, pie charts, etc, of course making them nice and interactive is some work, but one could certainly contribute such an effort to garden.graph (which currently focuses on time series, but could could certainly welcome more widgets).
https://github.com/kivy-garden/graph/blob/master/kivy_garden/graph/__init__.py

**Comment by matham** [comment]
I'm going to close this because there's no plan to add such a widget to kivy-core. This would be perfect as a user-contributed widget in kivy garden.
