### ISSUE TITLE
Can't use command "make" to instal Kivy

### ISSUE THREAD

**Issue by Mitch0rz** [kivy/kivy#7059]
Hi guys, i'm new to the raspbery pi and Kivy. i'm trying to follow the instructions 11.11.1 to instal kivy on the pi

https://kivy.org/doc/stable/installation/installation-rpi.html

all is working but as soon as i need to input the command "make" i'm stuck. where would i be missing something?

`Successfully installed Kivy Kivy-Garden-0.1.4`
`root@raspberrypi:/home/pi/Documents/kivy# ls`
`AUTHORS             LICENSE      README.md  examples        setup.cfg
CODE_OF_CONDUCT.md  MANIFEST.in  build      kivy            setup.py
Kivy.egg-info       Makefile     doc        pyproject.toml`
`root@raspberrypi:/home/pi/Documents/kivy# make`
`python setup.py build_ext --inplace
  File "setup.py", line 1075
    def glob_paths(*patterns, excludes=('.pyc', )):
                                     ^
SyntaxError: invalid syntax
make: *** [Makefile:35: build] Error 1`
`root@raspberrypi:/home/pi/Documents/kivy# cd kivy`
`root@raspberrypi:/home/pi/Documents/kivy/kivy# make`
`make: *** No targets specified and no makefile found.  Stop.
`

Any help would be welcome thanks, Mitch

**Comment by tanjilk** [comment]
Make sure that you have installed the necessary system packages, check on thi page [https://kivy.org/doc/stable/installation/installation-linux-venvs.html#dependencies-with-sdl2](url) and try to do `sudo apt-get install build-essential libgl1-mesa-dev`
