### ISSUE TITLE
arm64 (w/ python 3.8) support

### ISSUE THREAD

**Issue by nfbyte** [kivy/kivy#7060]
I've tried installing kivy as described in #6806 ([here](https://github.com/kivy/kivy/issues/6806#issuecomment-608176268)), however I've noticed that there are no armv8 (arm64) wheels available at the given index, only some armv7 ones, and so trying to install kivy on an arm64 device results in:
```
ERROR: Failed building wheel for cython
```

It would be great to have an official arm64 build available.

**Comment by malimach** [comment]
In the meantime, installing kivy version 2.0.0rc3 from pypi works, since there are no ARM wheels for that version and in that case pip will automatically build from the source.
