### ISSUE TITLE
[CRITICAL] [App         ] Unable to get a Window, abort.  

### ISSUE THREAD

**Issue by tanjilk** [kivy/kivy#7064]
**Software Versions**
* Python: 3.8.2
* OS: Ubuntu 20.04.1 LTS
* Kivy installation method: `pip install https://github.com/kivy/kivy/archive/master.zip`

**Describe the bug**
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
pygame - ModuleNotFoundError: No module named 'pygame'
  File "/home/tanjil/.local/lib/python3.8/site-packages/kivy/core/__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "/home/tanjil/.local/lib/python3.8/site-packages/kivy/core/window/window_pygame.py", line 13, in <module>
    import pygame

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/tanjil/.local/lib/python3.8/site-packages/kivy/core/__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(

[CRITICAL] [App         ] Unable to get a Window, abort.   

**Additional context**
Hello, im learning kivy and i'm trying to run an simple application but i got these errors
```
➜  Mobile App python3 main.py 
[INFO   ] [Logger      ] Record log in /home/tanjil/.kivy/logs/kivy_20-09-02_11.txt
[INFO   ] [Kivy        ] v2.0.0rc3, git-Unknown, 20200831
[INFO   ] [Kivy        ] Installed at "/home/tanjil/.local/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil (img_pygame, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
pygame - ModuleNotFoundError: No module named 'pygame'
  File "/home/tanjil/.local/lib/python3.8/site-packages/kivy/core/__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "/home/tanjil/.local/lib/python3.8/site-packages/kivy/core/window/window_pygame.py", line 13, in <module>
    import pygame

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/tanjil/.local/lib/python3.8/site-packages/kivy/core/__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(

[CRITICAL] [App         ] Unable to get a Window, abort.

```

```py
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen

Builder.load_file('design.kv')

class LoginScreen(Screen):
	pass

class RootWidget(Screen):
	pass

class MainApp(App):
	def build(self):
		return RootWidget()

if __name__ == '__main__':
	MainApp().run()
```

**Comment by tanjilk** [comment]
Also i tried to install the pygame with pip and i got these error  
```
➜  Mobile App pip3 install pygame
Defaulting to user installation because normal site-packages is not writeable
Collecting pygame
  Downloading pygame-1.9.6.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 1.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ga4f59b/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ga4f59b/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2tputg3f
         cwd: /tmp/pip-install-0ga4f59b/pygame/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "pkg-config freetype2" failed!
    WARNING: "freetype-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tanjilk** [comment]
Installed sdl2 `libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev` and re-installed kivy. But installed with `pip install git+https://github.com/kivy/kivy.git@master`

**Comment by ymozer** [comment]
Hi ! I have similar errors too but I don't know how to solve this:
`pi@raspberrypi:~/Python $ sudo python3 pitoucon.py
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_20-09-05_9.txt
[INFO   ] [Kivy        ] v2.0.0rc3, git-Unknown, 20200904
[INFO   ] [Kivy        ] Installed at "/root/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
The path /dev/dri/ cannot be opened or is not available
The path /dev/dri/ cannot be opened or is not available
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'No available video device'
  File "/root/.local/lib/python3.7/site-packages/kivy/core/__init__.py", line 70, in core_select_lib
    cls = cls()
  File "/root/.local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
    super(WindowSDL, self).__init__()
  File "/root/.local/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 982, in __init__
    self.create_window()
  File "/root/.local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
    self.get_gl_backend_name())
  File "kivy/core/window/_window_sdl2.pyx", line 112, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/root/.local/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.`

I installed dependencies (SDL2) with:
`wget https://libsdl.org/release/SDL2-2.0.10.tar.gz
    wget https://libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz
    wget https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz
    wget https://libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz`
And then complied it. 
Can you be more clear about how you install sdl2 ?

**Comment by tanjilk** [comment]
> Hi ! I have similar errors too but I don't know how to solve this:
> [error.txt](https://github.com/kivy/kivy/files/5178651/error.txt)
> I installed dependencies (SDL2) with:
> `wget https://libsdl.org/release/SDL2-2.0.10.tar.gz`
> `wget https://libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz`
> `wget https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz `wget [https://libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz`](https://libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz%60)
> And then complied it.
> Can you be more clear about how you install sdl2 ?

Did you tried with sudo apt-get `libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev`?
And make sure to run everything with `sudo`

**Comment by tanjilk** [comment]
`sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev`

**Comment by ymozer** [comment]
Thank you so much!

**Comment by tanjilk** [comment]
Great

**Comment by andreikee** [comment]
Hi,
I have the same problem, but I have installed kivy in conda environment (miniconda).

Software Versions

    Python: 3.8.6
    OS: Ubuntu 20.04.1 LTS
    Kivy installation method: conda install kivy
