### ISSUE TITLE
rework the build/installation script so that it's possible to load the setup.py and fetch dependencies before using them

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#707]
Right now, the installation/build script try to import cython and then create the build functions to populate  distutils `setup()` function, it may be possible to delay the import until the build step so that installation tools like pip can use the setup.py to resolve dependencies and then build the package.

This shouldn't not be too difficult to do, but is required to have proper python dependency resolution working (jnius ? and maybe others).
##

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
