### ISSUE TITLE
TouchRippleBehavior is missing from Factory

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#7076]
**Software Versions**
* Python: v3.6.9 
* OS: Ubuntu 18.04
* Kivy: v1.11.1
* Kivy installation method:

**Describe the bug**
The TouchRippleBehavior class is not registered in the kivy Factory

**Expected behavior**
Factory.get('TouchRippleBehavior') should return the TouchRippleBehavior class, but it throws an Exception:
 kivy.factory.FactoryException: Unknown class <TouchRippleBehavior>

**To Reproduce**
from kivy.factory import Factory

trb = Factory.get('TouchRippleBehavior')

**Code and Logs and screenshots**

[INFO   ] [Logger      ] Record log in /home/jra/.kivy/logs/kivy_20-09-11_20.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.6/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
 Traceback (most recent call last):
   File "/home/jra/PycharmProjects/kivyPlay/RippleFactoryBug.py", line 3, in <module>
     trb = Factory.get('TouchRippleBehavior')
   File "/usr/local/lib/python3.6/dist-packages/kivy/factory.py", line 131, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <TouchRippleBehavior>

**Additional context**
Importing and using TouchRippleBehavior works fine.

**Comment by pythonic64** [comment]
Can you make a pull request adding `TouchRippleBehavior` to `kivy/factory_registers.py` module?
To fix this in your project just use `Factory.register` method to add `TouchRippleBehavior` to `Factory`.
