### ISSUE TITLE
Need help: I want to print on the kivy screen with a string pulled from the web

### ISSUE THREAD

**Issue by phamt8611** [kivy/kivy#7077]
Hi everybody!

I have the following code.

```
import requests
from bs4 import BeautifulSoup
from kivy.app import App
from kivy.uix.button import Button

URL = 'http://sangtacviet.com/'
STV_HTML = requests.post(URL)
STV_SOUP = BeautifulSoup(STV_HTML.text, 'html.parser')
class STV_Home:
	"Class chứa các thông tin về trang chủ của Sáng Tác Việt"
	def getMenu(self):
		#Trang Chủ
		self.Home_Soup = STV_SOUP.find('a', href='/', style='margin: 6px;padding: 2px;display: inline-block;color: #eeeeee' )
		self.Home_Text = self.Home_Soup.text
		#Kênh Thế Giới
		self.Comment_Soup = STV_SOUP.find('a', href='/truyen-ngon/', style='margin: 6px;padding: 2px;display: inline-block;color: #eeeeee' )
		self.Comment_Text = self.Comment_Soup.text
		#Tìm Kiếm
		self.Search_Soup = STV_SOUP.find('a', href='/search/', style='margin: 6px;padding: 2px;display: inline-block;color: #eeeeee' )
		self.Search_Text = self.Search_Soup.text
		#Diễn Đàn
		self.Forum_Soup = STV_SOUP.find('a', href='/forum/', style='margin: 6px;padding: 2px;display: inline-block;color: #eeeeee' ) 
		self.Forum_Text = self.Forum_Soup.text
		#Dịch Trang Web
		self.Surf_Soup = STV_SOUP.find('a', href='/surf.php', style='margin: 6px;padding: 2px;display: inline-block;color: #eeeeee' )
		self.Surf_Text = self.Surf_Soup.text
		#Dịch
		self.Trans_Soup = STV_SOUP.find('a', href='/trans/', style='margin: 6px;padding: 2px;display: inline-block;color: #eeeeee' )
		self.Trans_Text = self.Trans_Soup.text
		#print(self.Home_Text,  self.Comment_Text)
Home_Menu = STV_Home.getMenu()
class STV_App(App):
	def build(self):
		return Button(text=Home_Menu.Home_Text)

if __name__=='__main__':
	STV_App().run()

```

I want to write a program that pulls data from a website, then prints it on the screen.

But the problem has come to me, I have tried it a few times, but no way to run the program successfully, without exiting, the screen will go black.

I have a headache.

Anyone have a way to help me?

Sincerely thank!!!!

**Comment by DrewBallins** [comment]
Not entirely sure what you're attempting to do here, but your code throws an error because of this line: 
`Home_Menu = STV_Home.getMenu()`

Try this instead and see if does what you're expecting:
`Home_Menu = STV_Home()`
`Home_Menu.getMenu()`

You needed to first instantiate an object of class 'STV_Home' which I did with the first line of code above. Then it appears you want to run the getMenu() method, which I ran on the instantiated object. The final output is a button which reads 'Trang chu'

**Comment by phamt8611** [comment]
> Không hoàn toàn chắc chắn bạn đang cố gắng làm gì ở đây, nhưng mã của bạn gặp lỗi do dòng này:
> `Home_Menu = STV_Home.getMenu()`
> 
> Thay vào đó, hãy thử điều này và xem liệu có đúng như những gì bạn đang mong đợi không:
> `Home_Menu = STV_Home()`
> `Home_Menu.getMenu()`
> 
> Trước tiên, bạn cần khởi tạo một đối tượng của lớp 'STV_Home' mà tôi đã thực hiện với dòng mã đầu tiên ở trên. Sau đó, có vẻ như bạn muốn chạy phương thức getMenu () mà tôi đã chạy trên đối tượng khởi tạo. Đầu ra cuối cùng là một nút có nội dung 'Trang chu'


Ok Ok, I succeeded, thanks a lot ...
