### ISSUE TITLE
Question on the Showcase Demo

### ISSUE THREAD

**Issue by digilevi2006** [kivy/kivy#7078]
Hi everyone,

I'm new to kivy and I'm not very good in programming yet but I love the showcase demo of Kivy `(kivy-examples\demo\showcase)`. I know I should not "run before I could walk" but please help me with my problem.

How do I call a screen name from one of the kv's?

For example I have a button on accordions.kv and wanted to go straight to one of the screens? I can use the `app.go_next_screen()` perfectly but what if I want to jump to a distant/specific screen? I tried to use `app.go_screen('Splitter')` but  I get this error: `ValueError: could not convert string to float: 'Splitter'`

If I use `app.go_screen(Splitter)`, 
I get `NameError: name 'Splitter' is not defined`

One more thing, I already have a full working python script, is it safe and very easy for a noob like me to just paste all my functions under ShowScreen and call the functions from individual screens(thru button press or get value from textinputs?)

Appreciate any help. Thanks

**Comment by tshirtman** [comment]
such questions are better asked in the support channels, rather than in issues.
