### ISSUE TITLE
Separate Event Dispatcher into own project

### ISSUE THREAD

**Issue by StephenCarboni** [kivy/kivy#7081]
**Is your feature request related to a problem? Please describe.**
EventDispatcher (ED) is great and I can't use it without the whole of Kivy initialising.

**Describe the solution you'd like**
EventDispatcher is its own installable package.

**Describe alternatives you've considered**
[Python Dispatch](https://python-dispatch.readthedocs.io/en/latest/) was inspired by Kivy's ED, but why have duplicate work? It has one advantage, you do not need to declare default event handlers, but it also does not have all the property types ED has and does not provide a way to add your own.

**Comment by rnixx** [comment]
Hi,

i wrote kivy inspired event dispatching a while ago here
https://github.com/bluedynamics/node/blob/master/src/node/behaviors/events.py
node is a package to build data graphs/trees

**Comment by matham** [comment]
I have thought about it, and wanted to do it, but besides the actual work required to do it, we'd have to enumerate all the possible issues to end users and then see if other devs are on board with the idea.

**Comment by Julian-O** [comment]
After 3 years there doesn't seem to be the appetite for the impact it would have, and there are plenty of available event dispatch libraries. 

Closing as won't fix.
