### ISSUE TITLE
dropdown widget crashes on RPI 4 (Raspbian lite) when opening

### ISSUE THREAD

**Issue by N4321D** [kivy/kivy#7090]
When running the DropDown example (https://kivy.org/doc/master/api-kivy.uix.dropdown.html)

The widget crashes every time I open the menu (I think it happens on dropdown.open)
Python                 3.7
Kivy             2.0.0rc3
Kivy-Garden      0.1.4

EDIT: it only happens when using the RPI official 7 inch touch screen and touching the widget,
not when using a mouse to click on the dropdown

> 
> pi@raspberrypi:~ $ ipython test1.py 
> ---------------------------------------------------------------------------
> WidgetException                           Traceback (most recent call last)
> ~/test1.py in <module>
>      33 dropdown.bind(on_select=lambda instance, x: setattr(mainbutton, 'text', x))
>      34 
> ---> 35 runTouchApp(mainbutton)
> 
> ~/.local/lib/python3.7/site-packages/kivy/base.py in runTouchApp(widget, embedded)
>     570 
>     571     try:
> --> 572         EventLoop.mainloop()
>     573     finally:
>     574         stopTouchApp()
> 
> ~/.local/lib/python3.7/site-packages/kivy/base.py in mainloop(self)
>     345         while not self.quit and self.status == 'started':
>     346             try:
> --> 347                 self.idle()
>     348                 if self.window:
>     349                     self.window.mainloop()
> 
> ~/.local/lib/python3.7/site-packages/kivy/base.py in idle(self)
>     388 
>     389         # read and dispatch input from providers
> --> 390         self.dispatch_input()
>     391 
>     392         # flush all the canvas operation
> 
> ~/.local/lib/python3.7/site-packages/kivy/base.py in dispatch_input(self)
>     340         post_dispatch_input = self.post_dispatch_input
>     341         while input_events:
> --> 342             post_dispatch_input(*pop(0))
>     343 
>     344     def mainloop(self):
> 
> ~/.local/lib/python3.7/site-packages/kivy/base.py in post_dispatch_input(self, etype, me)
>     306                         wid.dispatch('on_touch_up', me)
>     307                 else:
> --> 308                     wid.dispatch('on_touch_up', me)
>     309 
>     310             wid._context.pop()
> 
> kivy/_event.pyx in kivy._event.EventDispatcher.dispatch()
> 
> ~/.local/lib/python3.7/site-packages/kivy/uix/behaviors/button.py in on_touch_up(self, touch)
>     177         else:
>     178             self._do_release()
> --> 179         self.dispatch('on_release')
>     180         return True
>     181 
> 
> kivy/_event.pyx in kivy._event.EventDispatcher.dispatch()
> 
> kivy/_event.pyx in kivy._event.EventObservers.dispatch()
> 
> kivy/_event.pyx in kivy._event.EventObservers._dispatch()
> 
> ~/.local/lib/python3.7/site-packages/kivy/uix/dropdown.py in open(self, widget)
>     252 
>     253         # attach ourself to the main window
> --> 254         self._win.add_widget(self)
>     255 
>     256     def dismiss(self, *largs):
> 
> ~/.local/lib/python3.7/site-packages/kivy/core/window/__init__.py in add_widget(self, widget, canvas)
>    1305             raise WidgetException(
>    1306                 'Cannot add %r to window, it already has a parent %r' %
> -> 1307                 (widget, widget.parent)
>    1308             )
>    1309 
> 
> WidgetException: Cannot add <kivy.uix.dropdown.DropDown object at 0xb3c31cb0> to window, it already has a parent <kivy.core.window.window_sdl2.WindowSDL object at 0xb3caa7b0>
>

**Comment by N4321D** [comment]
UPDATE
as suggested here:
https://raspberrypi.stackexchange.com/questions/112430/kivy-on-raspberry-pi-returning-double-on-press-events

Disabling mtdev in ~/.kivy/config.ini seems to solve the issue:


mouse = mouse
#mtdev_%(name)s = probesysfs,provider=mtdev
hid_%(name)s = probesysfs,provider=hidinput

**Comment by pkstrsk** [comment]
I experience the same. however on touch the dropdown seems to appear on touch and disappear on release of the finger. Works fine using mouse.. Any progress on this issue by any chance?
