### ISSUE TITLE
Issue with <BackgroundLabel@Label+BackgroundColor> defined in kv string.

### ISSUE THREAD

**Issue by abedhammoud** [kivy/kivy#7095]
**Software Versions**
* Python: 3.8.5
* OS: win10
* Kivy: 2.0.0rc3
* Kivy installation method: pip

**Describe the bug**
I am defining a label and a button by inheriting from BackgroundColor defined in kv string (a trick from Kivy documentation).

I am getting an error that I cannot explain - I am new to Kivy so sorry if it was an obvious one.

In short, in the python code, I need to dynamically add a BackgroundLabel and a BackgroundButton. I can add the BackgroundButton defined in kv string no problem.

If I want to add the BackgroundLabel in the python code, I need to first instantiate a BackgroundLabel in the kv file before I can do so in the python code. If I don't instantiate a BackgroundLabel in the kv file, I get the error shown below when I try to instantiate the BackgroundLabel in the python code.

Please run the code and comment/uncomment the instance of the BackgroundLabel in the kv section in order to see the error.

**Expected behavior**
I expected working with BackgroundLabel and BackgroundButton to be the same. This is not the case.

**To Reproduce**
Please find complete code below.

**Code and Logs and screenshots**
```python
import kivy
from kivy.app import App
from kivy.factory import Factory
from kivy.uix.boxlayout import BoxLayout

kivy.lang.Builder.load_string('''

<BackgroundColor@Widget>:
    background_color: 0, 0, 1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos

<BackgroundButton@Button+BackgroundColor>:
    background_color: 1, 0, 0, 1

<BackgroundLabel@Label+BackgroundColor>:
    background_color: 0, 1, 0, 1

<DataView>:

    orientation: 'vertical'
    spacing: 5
    padding: 5

    # Commenting this out is no problem
    # with or without I can still instantiate a BackgroundButton in the python.
    # BackgroundButton:
    #     text: 'HELLO WORLD BUTTON'

    # If  I don't instantiate the BackgroundLabel here,
    # I get an error when trying to instantiate in the python code below.
    # If commented out I get the error message
    # BackgroundLabel:
    #     text: 'Hello world label'

''', filename='dateview.kv')

class DataView(BoxLayout):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

class TestApp(App):

    def build(self):
        DV = DataView()

        DV.add_widget(

            Factory.BackgroundButton(
                    text="Another Button",
                    color=(1, 0, 0, 1),
                    width=150,
                    size_hint_x=None,
                    background_color=(1, 1, 0, 1),
            )

        )

        # Fails If no instance instantiated in the kv string
        DV.add_widget(

            Factory.BackgroundLabel(
                    text="Another Label",
                    color=(1, 0, 0, 1),
                    width=300,
                    size_hint_x=None,
                    background_color=(1, 1, 0, 1),
            )

        )

        return DV

if __name__ == '__main__':
    TestApp().run()

```

**Additional context**
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [Kivy        ] v2.0.0rc3, git-20c14b2, 20200615
[INFO   ] [Kivy        ] Installed at "C:\Users\abed\anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 17:19:16) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\abed\anaconda3\python.exe"
[INFO   ] [Factory     ] 185 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer, img_gif ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.7637'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.7637'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "C:\Users\abed\OneDrive\Documents\dev\GitHub\alant\uix\dataview.py", line 78, in <module>
     TestApp().run()
   File "C:\Users\abed\anaconda3\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\Users\abed\anaconda3\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "C:\Users\abed\OneDrive\Documents\dev\GitHub\alant\uix\dataview.py", line 65, in build
     Factory.BackgroundLabel(
   File "C:\Users\abed\anaconda3\lib\site-packages\kivy\uix\label.py", line 318, in __init__
     super(Label, self).__init__(**kwargs)
   File "C:\Users\abed\anaconda3\lib\site-packages\kivy\uix\widget.py", line 350, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 245, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by akshayaurora** [comment]
You are creating a Dynamic Property in a Dynamic class, these properties are loaded dynamically usually on the first instantiation of a the class.

This does not show a issue with Button as Button class has a pre existing background_color property.

Solution for your case, don’t try to pass `background_color` as a option while initialising the widget. set it right after like ::

```
bl = Factory.BackgroundLabel(
                    text="Another Label",
                    color=(1, 0, 0, 1),
                    width=300,
                    size_hint_x=None)
bl.background_color = (0, 0, 1, 1)
```

or can also do 

```
bl = Builder.load_string(‘’'
BackgroundLabel
    background_color: 0,0,1,1
    text: “Another Label”
    color: 1, 0, 0, 1
    width:300
    size_hint_x: None
‘'')
```

**Comment by abedhammoud** [comment]
Thank you. This solved my problem. BTW, I would think it would make sense to have background_color property for Label as it is for Button (how else can you highlight elements in a table for example). 

In your opinion, if I need the background_color, should I just use a button with no-binding instead of defining a my own BackgroundLabel? Would there be any performance hits if I build my table with all buttons?

Many thanks again, this was very helpful.
