### ISSUE TITLE
BaseEventLoop.ensure_window calls sys.exit and causes python crash

### ISSUE THREAD

**Issue by dolfandringa** [kivy/kivy#7104]
**Software Versions**
* Python: 3.7 and 3.6.9
* OS: Linux (debian based) headless
* Kivy: 1.11.1
* Kivy installation method: pipenv install kivy/pip install kivy

**Describe the bug**
On headless systems, any application that calls `EventLoop.ensure_window()` causes python to exit. 

This is a problem in my application that includes CI through bitbucket pipelines with pytest and linting running on a headless machine. There are no tests that include starting an application but as soon as EventLoop.ensure_window gets called, python will exit. Any application calling it has no way to recover from it. I think calling `sys.exit` from a library is a bad idea in general. It is the responsibility of the application using the library to handle errors. In my case I am using `kivymd` which causes `EventLoop.ensure_window` to be called even when I only `from kivymd.app import MDApp`, without ever trying to start an application. This makes any application that imports any part of `kivymd` to crash, even it its only linting or running pytest without any gui application.

**Expected behavior**
An exception is raised without python exiting. 

**To Reproduce**
On a headless machine:
```python
from kivy.base import EventLoop
EventLoop.ensure_window()
```

**Code and Logs and screenshots**

```bash
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kivy.base import EventLoop
[INFO   ] [Logger      ] Record log in /home/me/.kivy/logs/kivy_20-09-24_21.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/me/.local/share/virtualenvs/venv-070yQ5om/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0]
[INFO   ] [Python      ] Interpreter at "/home/me/.local/share/virtualenvs/venv-070yQ5om/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
>>> EventLoop.ensure_window()
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_pygame, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/me/.local/share/virtualenvs/venv-070yQ5om/lib/python3.6/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/me/.local/share/virtualenvs/venv-070yQ5om/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

pygame - ModuleNotFoundError: No module named 'pygame'
  File "/home/me/.local/share/virtualenvs/venv-070yQ5om/lib/python3.6/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/me/.local/share/virtualenvs/venv-070yQ5om/lib/python3.6/site-packages/kivy/core/window/window_pygame.py", line 13, in <module>
    import pygame

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/me/.local/share/virtualenvs/venv-070yQ5om/lib/python3.6/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

### With KIVY_DOC=1

```
~$ export KIVY_DOC=1
~$ python
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kivy.base import EventLoop
[INFO   ] [Logger      ] Record log in /home/me/.kivy/logs/kivy_20-09-24_22.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/me/.local/share/virtualenvs/venv-070yQ5om/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0]
[INFO   ] [Python      ] Interpreter at "/home/me/.local/share/virtualenvs/venv-070yQ5om/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
>>> EventLoop.ensure_window()
[CRITICAL] [App         ] Unable to get a Window, abort.
~$
```

**Comment by dolfandringa** [comment]
I suggest replacing sys.exit with `raise RuntimeError('some useful message')` or something

**Comment by dolfandringa** [comment]
I am also figuring out what in kivymd causes `EventLoop.ensure_window` to be called, and will file a bug report there as well.

**Comment by matham** [comment]
Good point about `RuntimeError`. I'd suggest to get around your issue, is to do what kivy does on CI https://github.com/kivy/kivy/blob/master/.ci/ubuntu_ci.sh#L62 which creates a fake gl system. 

As for a window, perhaps we need to have a mocked window backend.

**Comment by Julian-O** [comment]
The concept that sys.exit() should not be called [except in limited circumstances, like parsing CLI params] is covered by #8348 - which is later but clearer. 

#8340 covers the window being opened - which is later but has an associated PR.

So closing as a duplicate, even though this one was earlier.
