### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by LovroPriselec** [kivy/kivy#7108]
`import kivy`
When I type this in python and run in I get this error, I have python3.8.5 and I installed kivy-2.0.0rc3
This is error:

>>> import kivy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Korisnik\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\__init__.py", line 38, in <module>
    from kivy.logger import Logger, LOG_LEVELS
ValueError: source code string cannot contain null bytes

**Comment by LovroPriselec** [comment]
Please help, I want to start learning Kivy but I can't

**Comment by tshirtman** [comment]
Looks like your installation is corrupted for some reason, try uninstalling and reinstalling kivy.

**Comment by LovroPriselec** [comment]
> Looks like your installation is corrupted for some reason, try uninstalling and reinstalling kivy.

Which commands should I use
