### ISSUE TITLE
Add a check for python version in `make` and gracefully exit rather than fail on python version 2.

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#7109]
**Software Versions**
* Python:
* OS: OSX 10.15.6
* Kivy: master 27 sept 2020
* Kivy installation method: clone master and `make`

**Describe the bug**
Make fails with `python` referring to python2 does not fail gracefully

**Expected behavior**
```
 kivy % make 
python setup.py build_ext —inplace
Python version 2 is not supported, please use python3
```
**To Reproduce**
```
> git clone github.com/kivy/kivy
> cd kivy
> make 
```

**Code and Logs and screenshots**
```
 kivy % make 
python setup.py build_ext --inplace
  File "setup.py", line 1050
    def glob_paths(*patterns, excludes=('.pyc', )):
                                     ^
SyntaxError: invalid syntax
make: *** [build] Error 1
```

**Additional context**

**Comment by tshirtman** [comment]
maybe something like
```python
PYTHON_MINIMUM_VERSION = (3, 6, 0)

if sys.version_info < PYTHON_MINIMUM_VERSION:
     logger.error("Kivy requires at least python %s.%s.%s", *PYTHON_MININUM_VERSION)
```

**Comment by akshayaurora** [comment]
@tshirtman your solution is already implemented in setup.py, issue is it fails due to syntax error in py2 while it works with py3

**Comment by tshirtman** [comment]
Oh right, makes sense.

**Comment by tshirtman** [comment]
but in which situation does the one in makefile helps?

**Comment by akshayaurora** [comment]
If you try to run `make` to compile kivy and your `python` points to a version < 3.6 it would now simply give you this error. 

```
kivy % make
Makefile:12: *** "detected Python 2.7 need Python >= 3.6".  Stop.
```

**Comment by tshirtman** [comment]
right, but few users actually do that, right?

Maybe we should use a stub setup.py that is python2 compatible if we want that, and only conditionally import/run the actual (renamed) setup.py from it if we detect that we have a supported python version, then?

**Comment by akshayaurora** [comment]
@tshirtman I am not really sure of the consequences of that but #7111 does that, feel free to merge which ever method you feel works,

**Comment by matham** [comment]
Eh. I'm not sure we should have non standard setup.py (msetup.py) just for make users, which are pretty rare these days (except for us core-devs). The default cade should be for 3+, not 2.

**Comment by matham** [comment]
The makefile itself should check for 2.7 and fail, rather than putting the work in Python code itself. And for 3.x support, there's a standard python_requires or something similar metadata for minimum python version. This can be added to the config file.

**Comment by tshirtman** [comment]
the other setup.py is not for make users, it's to allow anyone to run setup.py and get a legible error if they are using python2.7, it might be a bit heavy handed, but i don't see another way to avoid the syntax error otherwise (or avoiding using python3 syntax in setup.py).

**Comment by matham** [comment]
But you wouldn't use setup.py directly these days, except after you have a
working install, for normal users. So we just need to make sure that
installing with pip returns a clear error. We don't have to make it return
a nice error for users who don't use pip, because hopefully they would know
about Python2 not being supported.

Even editable install is installed with pip initially. So we just need to
add the appropriate metada and hopefully pip not even try to run setup.py
if the min version is violated.

**Comment by akshayaurora** [comment]
Honestly my personal use case is using make, that’s why I wanted to add the Make only solution. This is good enough for users that compile from git.

For the setup.py change I fear doing it this way is begging for consequences down the line….

**Comment by tshirtman** [comment]
> Even editable install is installed with pip initially. So we just need to
> add the appropriate metada and hopefully pip not even try to run setup.py
> if the min version is violated.

Hm, i assumed because pip runs setup.py, it was a better solution, and i don't really see the point of having an error when you already have it installed, is that for when you run make without enabling your venv or something?

**Comment by akshayaurora** [comment]
`is that for when you run make without enabling your venv or something?`

Yes. Default python on osx is still python2, lol

**Comment by tshirtman** [comment]
ok, i understand better, i guess the less intrusive fix is with the makefile then.
