### ISSUE TITLE
Could not find version that satisfies requirement kivy-deps.angle==0.2.0

### ISSUE THREAD

**Issue by pablof300** [kivy/kivy#7124]
**Software Versions**
* Python: 3.7
* OS: Mac OS
* Kivy: 1.11.1
* Kivy installation method: requirements.txt

**Describe the bug**
I am installing the following:

Kivy==1.11.1
Kivy-Garden==0.1.4
Pillow==7.2.0
Pygments==2.7.1
certifi==2020.6.20
chardet==3.0.4
docutils==0.16
idna==2.10
kivy-deps.angle==0.2.0
kivy-deps.glew==0.2.0
kivy-deps.sdl2==0.2.0
pip==20.1.1
requests==2.24.0
sdl2-lib==2.0.3
setuptools==47.1.0
urllib3==1.25.10
plyer==1.4.3
pytesseract==0.3.6

I get an error:

ERROR: Could not find a version that satisfies the requirement kivy-deps.angle==0.2.0 (from versions: none)
ERROR: No matching distribution found for kivy-deps.angle==0.2.0

**Comment by RobertFlatt** [comment]
Angle is not a Kivy dependency on MacOS only on Windows
https://kivy.org/doc/stable/installation/installation-osx.html
https://kivy.org/doc/stable/installation/installation-windows.html

And if you look in the install instruction for glew.......

**Comment by Zen-CODE** [comment]
Correct. Angle should only be used on Windows as it's purpose is to render to DirectX instead of OpenGL....
