### ISSUE TITLE
ObjectProperty is NoneType on First Screen on_enter()

### ISSUE THREAD

**Issue by Scaremonger** [kivy/kivy#7128]
**Software Versions**
* Python:
* OS:
* Kivy:
* Kivy installation method:

**Describe the bug**
On a multiple screen application; ObjectProperty is not initialized when the first screen is shown and you will receive a NoneType doesn't have the required property error message if you attempt to use it during on_pre_enter() or on_enter().

The below code shows that the APP.START() runs after the first screen has been initialized. Moving to another screen updates the ObjectProperty to <class 'kivy.weakproxy.WeakProxy'> as expected, it just doesn't do this the first time.

**Expected behavior**
I would expect that the ObjectProperty is initialized before the Screen "on_pre_enter()" is called.

**To Reproduce**
Run this code and look at the value displayed after the double "::" which is the value of the ObjectProperty. Click on the button and it will show the same Object property, but this time it has been initialised.
```
import kivy
#kivy.require('1.0.6')

from kivy.app import App
from kivy.lang import Builder
from kivy.properties import ObjectProperty
from kivy.uix.screenmanager import ScreenManager, Screen

class Main( ScreenManager ):
    pass

class Screen1( Screen ):
    btn = ObjectProperty(None)

    def __init__( self, **kwargs ):
        super( Screen1, self ).__init__( **kwargs )
        print( "SCREEN1.INIT() :: "+ str( type( self.btn ) ) )

    def on_pre_enter( self ):
        print( "SCREEN1.ON_PRE_ENTER() :: "+ str( type( self.btn ) ) )

    def on_enter( self ):
        print( "SCREEN1.ON_ENTER() :: "+ str( type( self.btn ) ) )

class Screen2( Screen ):
    btn = ObjectProperty(None)

    def __init__( self, **kwargs ):
        super( Screen2, self ).__init__( **kwargs )
        print( "SCREEN2.INIT() :: "+ str( type( self.btn ) ) )

    def on_pre_enter( self ):
        print( "SCREEN2.ON_PRE_ENTER() :: "+ str( type( self.btn ) ) )

    def on_enter( self ):
        print( "SCREEN2.ON_ENTER() :: "+ str( type( self.btn ) ) )

Builder.load_string("""
<Main>:
    Screen1:
    Screen2:
        
<Screen1>:
    btn: button1
    name: 'screen1'
    Button:
        id: button1
        on_release: 
            print( "** CHANGE TO SCREEN 2 **" )
            app.root.current = 'screen2'
        text: 'Go to Screen 2'
        font_size: 50
        
<Screen2>:
    btn: button2
    name: 'screen2'
    Button:
        id: button2
        on_release: 
            print( "** CHANGE TO SCREEN 1 **" )
            app.root.current = 'screen1'
        text: 'Go to Screen 1'
        font_size: 50
""")

class Issue( App ):
    
    def build(self):
        print( "APP.BUILD()" )
        return Main()
    
    def on_start( self ):
        print( "APP.START()" )

if __name__ == '__main__':
    print( "MAIN" )
    Issue().run()

```

**Code and Logs and screenshots**
This is the output from the application showing that the ObjectProperty is "NoneType" for Screen1 during on_pre_enter() and on_enter() until the screen is changed. It also shows that App.on_start() is called after screen.on_pre_enter().
```
MAIN
APP.BUILD()
SCREEN1.INIT() :: <class 'NoneType'>
SCREEN1.ON_PRE_ENTER() :: <class 'NoneType'>
SCREEN1.ON_ENTER() :: <class 'NoneType'>
SCREEN2.INIT() :: <class 'NoneType'>
APP.START()
** CHANGE TO SCREEN 2 **
SCREEN2.ON_PRE_ENTER() :: <class 'kivy.weakproxy.WeakProxy'>
SCREEN2.ON_ENTER() :: <class 'kivy.weakproxy.WeakProxy'>
** CHANGE TO SCREEN 1 **
SCREEN1.ON_PRE_ENTER() :: <class 'kivy.weakproxy.WeakProxy'>
SCREEN1.ON_ENTER() :: <class 'kivy.weakproxy.WeakProxy'>
```
**Additional context**
As a workaround I added an empty splash screen on my application and changed the screen during App.on_start() to the first screen to bypass this First-Screen-Initialization issue.

**Comment by Zen-CODE** [comment]
This happens because the classes are loaded before the KV rules are applied. And in code, they default to None.

    btn = ObjectProperty(None)

Only after the main event loop runs again are the properties set in kv executed. Typically, there are usually ways to solve this in kv, but without knowing what you are trying to do, it's hard to give a suggestion. The above example demonstrates the initialization problem, but does not indicate what you are trying to do? Could your possibly show code on what values you are trying to you use for what purpose? 

Thanks
