### ISSUE TITLE
Toggling the mipmap after changing the texture brings the original texture back

### ISSUE THREAD

**Issue by Huud** [kivy/kivy#7137]
**Software Versions**
* Python: 3.7
* OS: Win7
* Kivy: 1.11.1

Creating an image, changing the texture then toggling the mipmap undoes the texture change to the original image.

Example code:

```
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.uix.image import Image
from kivy.core.window import Window
from kivy.graphics.texture import Texture
import cv2
import numpy as np

def swapTexture():
    img = cv2.imread('2.png', cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img / 255.0
    imgCopy = img.copy()
    imgCopy = np.clip(imgCopy,0.,1.) * 255.
    imgCopy = imgCopy.astype("int8")
    imgCopy = cv2.flip(imgCopy, 0)
    outTexture = Texture.create(size=(imgCopy.shape[1], imgCopy.shape[0]))
    outTexture.blit_buffer(imgCopy.tostring(), colorfmt='rgb', bufferfmt='ubyte')
    return outTexture

class myWid(Widget):
    myImg = Image(source= '1.png',size = (500,500))
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.add_widget(self.myImg)
        self._keyboard = Window.request_keyboard(None, self)
        if not self._keyboard:
            return
        self._keyboard.bind(on_key_down=self.on_keyboard_down)

    def on_keyboard_down(self, keyboard, keys, text, modifiers):
        if keys[1] == 'spacebar':
            self.myImg.mipmap ^= True # toggles the mipmap
        if keys[1] == 'b':
            self.myImg.texture = swapTexture()

class MainApp(App):
    def build(self):
        return myWid()

MainApp().run()
```
Run it with images called 1.png and 2.png present, press 'b' to swap textures, then press 'spacebar' to toggle the mipmap and the second texture will be swapped back to the first one.

If this is intended, what's the right way to toggle the mipmap after the image creation?

**Comment by Zen-CODE** [comment]
I think changing the mipmap property causes it to regenerate the image based on the source property. If you want to preserve the results of generating another texture, I would suggest persisting that to another widget, then swapping out the widgets if you want the display changed?

**Comment by Huud** [comment]
Yeah, I worked around this bug by generating a new image from scratch everytime a user changes the filtering method. 

I guess the real problem is that there is no image filtering options in kivy image aside from just enabling/disabling mipmap, and even that doesn't work after construction.

**Comment by Zen-CODE** [comment]
Agreed, but technically that not a bug so much as a feature request. Can we close this ticket, and if you feel like that should be added, create a feature request?

Thanks

**Comment by Huud** [comment]
This post is about the original bug where swapping the texture data then toggling the mipmap will reset the texture to the original, the filtering options is just a separate feature that would solve this for my particular case, not the bug itself.

**Comment by Zen-CODE** [comment]
From the docs  https://kivy.org/doc/stable/api-kivy.uix.image.html

    Texture object of the image. The texture represents the original, loaded image texture.

That means the behaviour you are seeing is expected. Marking alterations to the texture and expecting them to persist is not a supported use case? Or am I missing something?

**Comment by Huud** [comment]
Ok, pretty weird design, but if that's the intended way, so be it.

**Comment by Zen-CODE** [comment]
Well, that's the way it currently works because it's the simplest design. You are welcome to open a feature request ticket detailing the behaviour you would like to see if you think there are improvements that can be made. And if you accompany that with a matching pull request that adds it, it's got a good chance of getting in 👍 

Thanks
