### ISSUE TITLE
Window flipped on Windows 10

### ISSUE THREAD

**Issue by Stef-deb** [kivy/kivy#7138]
**Software Versions**
* Python: 3.7
* OS: Windows 10
* Kivy: 2.0.0rc3
* Kivy installation method: pip

**Describe the bug**
When I run the app via terminal or with double clcick, the window generated is flipped. The logs of the program aren't also shown.
**Expected behavior**
Before the last update of windows 10 (which I have done 7/october/2020) the window of the program was generated correctly and I was able to see the logs on the terminal.

**To Reproduce**
Try to install the last version of windows and run a kivy program

**Code and Logs and screenshots**
The bug happens with every kivy programs

**Comment by tito** [comment]
Can you double check your ~/.kivy/config.ini ? Rotation is part of the configuration, shared between all kivy program. If one changes it, all are impacted.
And/or rename/delete your ~/.kivy directory and retry.

**Comment by Stef-deb** [comment]
Ok, I saw that rotation was strangely set to 180, I resolved setting it to 0. I have no idea about the cause of this.
