### ISSUE TITLE
Can Kivy or kivymd develop Android navigation apps？

### ISSUE THREAD

**Issue by mygit-1** [kivy/kivy#7139]
**Is your feature request related to a problem? Please describe.**

1、Can Kivy or kivymd develop Android navigation apps？because I have a project that needs to develop an android app with navigation function. At present, I want to use Kivy to develop it, but I can't see the relevant instructions after consulting the documents. 

**Describe the solution you'd like**

1. Be able to position yourself
2. Start and destination can be set
3. It can show the planning path and how long it will take

**Comment by RobertFlatt** [comment]
https://github.com/kivy-garden/garden.mapview

**Comment by mygit-1** [comment]
@RobertFlatt   tks, bro

**Comment by Zen-CODE** [comment]
This question seems to have been addressed. For further questions, please post of the google forum and ask on the discord channel. Thanks
