### ISSUE TITLE
ERROR: Command errored out with exit status 1: while installing kivy

### ISSUE THREAD

**Issue by KeerthiNKR** [kivy/kivy#7140]
As you people suggested i run the command inthe command window as follows.
1. python -m pip install --upgrade pip setuptools wheel
2. python -m pip install docutils pygments pypiwin32 kivy_deps.sdl2==0.1.* kivy_deps.glew==0.1.*
---> for this command i got following error
---------------------------------------------------------------------------------------------------------
C:\Users\pavan>python -m pip install docutils pygments pypiwin32 kivy_deps.sdl2==0.1.* kivy_deps.glew==0.1.*
Requirement already satisfied: docutils in c:\users\pavan\appdata\local\programs\python\python39\lib\site-packages (0.16)
Requirement already satisfied: pygments in c:\users\pavan\appdata\local\programs\python\python39\lib\site-packages (2.7.1)
Requirement already satisfied: pypiwin32 in c:\users\pavan\appdata\local\programs\python\python39\lib\site-packages (223)
ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2==0.1.* (from versions: 0.3.0, 0.3.1)
ERROR: No matching distribution found for kivy_deps.sdl2==0.1.*
---------------------------------------------------------------------------------------------------------
So i changed my comment as "C:\Users\pavan>python -m pip install docutils pygments pypiwin32 kivy_deps.sdl2==0.3.* kivy_deps.glew==0.3.*"
After the package is installed.Then i entered 3rd command
3. python -m pip install kivy==1.11.1
For this i got error for that i downloaded and installed microsoft c++ build tools,again i used command as "pip install --pre --extra-index-url https://kivy.org/downloads/simple kivy[base]"
for this i got following error
------------------------------------------------------------------------------------------------------
C:\Users\pavan>pip install --pre --extra-index-url https://kivy.org/downloads/simple kivy[base]
Looking in indexes: https://pypi.org/simple, https://kivy.org/downloads/simple
Collecting kivy[base]
  Using cached Kivy-2.0.0rc3.tar.gz (23.6 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\pavan\appdata\local\programs\python\python39\python.exe' 'c:\users\pavan\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\pavan\AppData\Local\Temp\pip-build-env-l6clgiwr\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://kivy.org/downloads/simple --pre -- setuptools wheel 'cython>=0.24,<=0.29.14,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.2.0; sys_platform == "win32"' 'kivy_deps.sdl2~=0.2.0; sys_platform == "win32"' 'kivy_deps.glew~=0.2.0; sys_platform == "win32"'
       cwd: None
  Complete output (9 lines):
  Looking in indexes: https://pypi.org/simple, https://kivy.org/downloads/simple
  Collecting setuptools
    Using cached setuptools-50.3.0-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting cython!=0.27,!=0.27.2,<=0.29.14,>=0.24
    Using cached Cython-0.29.14.tar.gz (2.1 MB)
  ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.2.0 (from versions: 0.3.0, 0.3.1)
  ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.2.0
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\pavan\appdata\local\programs\python\python39\python.exe' 'c:\users\pavan\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\pavan\AppData\Local\Temp\pip-build-env-l6clgiwr\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://kivy.org/downloads/simple --pre -- setuptools wheel 'cython>=0.24,<=0.29.14,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.2.0; sys_platform == "win32"' 'kivy_deps.sdl2~=0.2.0; sys_platform == "win32"' 'kivy_deps.glew~=0.2.0; sys_platform == "win32"' Check the logs for full command output.
-------------------------------------------------------------------------------------------------------
Please anyone help me to solve this error. I'm using python 3.9 windows 10

**Comment by RobertFlatt** [comment]
>  I'm using python 3.9 windows 10
Use Python 3.7

**Comment by tanjilk** [comment]
Seems like you need to install sdl2, try to install sdl2

**Comment by Zen-CODE** [comment]
Python 3.8+ is only currently supported via installing from master (as above) or

    pip install kivy==2.0.0rc3

**Comment by fal3n-4ngel** [comment]
> Python 3.8+ is only currently supported via installing from master (as above) or
> 
> ```
> pip install kivy==2.0.0rc3
> ```

It didn't work


  WARNING: Discarding https://files.pythonhosted.org/packages/10/32/21873ff231e069f860098b1602bb9e3ae2806d2f73ba661b5d806f200243/Cython-0.27.1.tar.gz#sha256=e6840a2ba2704f4ffb40e454c36f73aeb440a4005453ee8d7ff6a00d812ba176 (from https://pypi.org/simple/cython/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    Using cached Cython-0.26.1.tar.gz (1.7 MB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.2.0 (from versions: none)
  ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.2.0
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/62/d5/b9c49673c3fc07362efdeca6c12072150f1fe7263e1baf0b314f3fc39646/Kivy-2.0.0rc3.tar.gz#sha256=d16770fdacf1c9e032ee1a3f50151f88bd4f94ffd12a7d0b037b0beb4683bfc5 (from https://pypi.org/simple/kivy/). Command errored out with exit status 1: 'C:\Users\DELL\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\DELL\AppData\Local\Temp\pip-standalone-pip-7c9st81c\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\DELL\AppData\Local\Temp\pip-build-env-vhmtjowj\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.24,<=0.29.14,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.2.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.2.0; sys_platform == "win32"' 'kivy_deps.sdl2~=0.2.0; sys_platform == "win32"' 'kivy_deps.glew~=0.2.0; sys_platform == "win32"' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement kivy==2.0.0rc3 (from versions: 1.0.1a0, 1.0.2a0, 1.0.3a0, 1.0.4b0, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3, 2.0.0rc4, 2.0.0)
ERROR: No matching distribution found for kivy==2.0.0rc3

**Comment by RobertFlatt** [comment]
The post was correct at the time, but times change.

Use the install instructions https://kivy.org/doc/stable/gettingstarted/installation.html

**Comment by fal3n-4ngel** [comment]
Yeah , Kinda installed the previous version of python and kivy. Ig it's a problem python 3.10, I switched back to python 3.8
