### ISSUE TITLE
TextInput bug on Android

### ISSUE THREAD

**Issue by Roma9o** [kivy/kivy#7143]
**Software Versions**
* Python: 3.8
* OS: Android
* Kivy 1.11.1

**Describe the bug**
When set `readonly: True` it seems `is_focusable = False` on Android device, and focus does not work,  test() funс is not executed.
On PC `is_focusable = True`, focus works, but not possible to enter any text. This is the correct expected result. test() funс is executed.

**Expected behavior**
Then tap to text input field on App - test() funс is executed, android keyboard not showing. On PC all works fine
[Expected behavior example](https://github.com/HeaTTheatR/KivyMD-data/raw/master/gallery/kivymddoc/menu-position.gif)

**Code and Logs and screenshots**
[Video how it works now](https://gofile.io/d/hCKG0f)
```python
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
Screen:
    TextInput:
        id: input
        pos_hint: {'center_x': .5, 'center_y': .7}
        size_hint: 0.5, 0.2
        hint_text: "Text"
        readonly: True
        on_focus: if self.focus: app.test()
    MDLabel:
        id: label
        halign: "center"
        text: 'Hello'
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)

    def test(self):
        self.screen.ids.label.text = 'FOCUSED TEXT INPUT'

    def build(self):
        return self.screen

Test().run()
```

**Temporary solution**
After `readonly: True` set `is_focusable: True`
But this has a drawback - the Android keyboard opens
```python
KV = '''
    TextInput:
        id: input
        pos_hint: {'center_x': .5, 'center_y': .7}
        size_hint: 0.5, 0.2
        hint_text: "Text"
        readonly: True
        is_focusable: True
        on_focus: if self.focus: app.test()
'''
```

**Comment by akshayaurora** [comment]
This is by design as focusing the keyboard would load the soft keyboard.  Which is counter intuitive on a mobile.
