### ISSUE TITLE
Pafy lib with kivy

### ISSUE THREAD

**Issue by dovahkinnn** [kivy/kivy#7150]
Im using pafy library in kivy and im start buildozer app build but not working  this error show
AttributeError: 'LogFile' object has no attribute 'encoding'

**Comment by Sahil-pixel** [comment]
I have same problem

**Comment by Zen-CODE** [comment]
This does seem like a Kivy issue, but a buildozer issue. Please open a ticket on the buildozer issue list with complete logs. The information posted above is not sufficient to act upon.

https://github.com/kivy/buildozer
