### ISSUE TITLE
Packaging Kivy application into pip module

### ISSUE THREAD

**Issue by pablof300** [kivy/kivy#7161]
**Software Versions**
* Python: 3.8
* OS: Ubuntu
* Kivy: 2.0.0

I am trying to package my Kivy application into a pip module I can easily install. I am using setuptools to do this. I have the following file structure for my Kivy app:

    setup.py
    requirements.txt
    test/
      data.db
      app.py
      widgets.kv
      style.kv

and my setup.py

    setuptools.setup(
        name="TestApp",
        version="0.0.4",
        author="People",
        packages=['test'],
        package_data={ 'test': ['*'] },
        include_package_data=False,
        description="Produce expiration tracker",
        python_requires='>=3.8',
        install_requires=install_requires
    )

I was having some issues with (style.kv file not found) from app.py, where it wasn't finding the file:

    root = Builder.load_file('style.kv') # <- file not found

fixed it by doing:

    root = Builder.load_file(os.path.join(os.path.dirname(__file__), 'style.kv'))

However, now I am getting the same file not found issue in style.kv:

    #kivy 1.11.1
    #:import utils kivy.utils
    #:import Transition kivy.uix.screenmanager
    #:import ButtonBehavior kivy.uix.behaviors
    #:include widgets.kv

Within the style.kv file, at the line `#:include widgets.kv`, it can't find the file widgets.kv. How could I fix this from the style.kv file?

**Comment by matham** [comment]
You have to add the directory with the kv file to kivy's resources with `resource_add_path`. See https://kivy.org/doc/stable/api-kivy.resources.html#resource-lookup.

A PR adding this info to linking to `resource_add_path` in the kv docs is welcome.
