### ISSUE TITLE
Main thread hang when call Window.show() from systray

### ISSUE THREAD

**Issue by itispip** [kivy/kivy#7163]
**Software Versions** Kivy + infi.systray
* Python: 3.7.9
* OS: Win10
* Kivy: 1.11.1
* Kivy installation method: Pip 

**Describe the bug**
I am using Kivy + infi.systray module (https://github.com/Infinidat/infi.systray). 

1. 1 menu item call Window.hide; This works, except it may take 1-2 seconds
3.  another menu item call  Window.show;  The call actually success, but user must keep mouse moving over the Tray Icon until MyApp window fully loaded. Otherwise MyApp windows appears to be hang & window not refresh nor responding. After MyApp window fully loaded, mouse can be moved away from tray icon and MyApp is as responsive as usual.

**Expected behavior**
MyApp window should refesh/responsive after window.show called

**To Reproduce**
    import kivy
    kivy.require('1.11.1') 
    from kivy.app import App
    from kivy.core.window import Window
    from kivy.uix.label import Label
    from infi.systray import SysTrayIcon

    class HelloApp(App):
        def build(self):
            return Label(text ="Hello World !")

    if __name__ == '__main__':

        def show_app(instance_trayicon):
            Window.show()

        def hide_app(instance_trayicon):
            Window.hide()
        
        menuitems = (("Show App", None, show_app),("Hide App", None, hide_app),)
        systray = SysTrayIcon("Icon","Sample Title",menuitems)
        systray.start()
        HelloApp().run()

**Additional context**
Found similar report back to 2014 under version 1.9.1, it says the bug will be corrected in 1.9.2; But now is 1.11.1 and the similar symptoms still exist

**Comment by matham** [comment]
You're referring to https://github.com/kivy/kivy/issues/3846, but I don't see it mentioned there that we will support it. In any case, we don't support `infi.systray` so I'm closing the issue. The referenced issue is a good place to comment about your problem, especially given someone else claimed it worked for them.

But as a thought, I'd schedule the `show` and `hide` calls to occur in kivy's thread using `Clock`, as systray may call it from the wrong thread.
