### ISSUE TITLE
TextInput unexpected linebreaks

### ISSUE THREAD

**Issue by Alspb** [kivy/kivy#7165]
**Software Versions**
* Python: 3.8.5
* OS: Linux Mint 20 (based on Ubuntu 20.04 LTS)
* Kivy: 2.0.0rc3

**Describe the bug**
If I start entering text (e.g. by holding down "c" key) between letters "a" and "b" in the line "aaaabbbb", then when the text fills all the line, unexpected linebreaks after each letter "b" appears.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.uix.textinput import TextInput

class Sample(App):
    def build(self):
        return TextInput(text="aaabbb")

Sample().run()
```

**Current behavior**
![Bug2_current](https://user-images.githubusercontent.com/73047043/96428540-67b98700-11ef-11eb-9155-65e453b5f489.png)

**Expected behavior**
![Bug2_expected](https://user-images.githubusercontent.com/73047043/96429195-32f9ff80-11f0-11eb-93bd-1f6a30e442b7.png)

**Comment by DexerBR** [comment]
When investigating the issue more closely, I noticed that when typing a word larger than the width of the viewport if the cursor is at the end of the word, the text flows correctly. But, if after the word flows to the next line, you insert a character at the beginning of the previous line or in the middle of it, the problem mentioned above appears.

I made some attempts, without success :(
But to speed up the process of identifying the bug's origin, it's probably in:

https://github.com/kivy/kivy/blob/9152bc85908b757c0664f95c9105c84901e8b2a5/kivy/uix/textinput.py#L2576

https://github.com/kivy/kivy/blob/9152bc85908b757c0664f95c9105c84901e8b2a5/kivy/uix/textinput.py#L2561

**Comment by Alspb** [comment]
Many thanks!
Actually I've fixed it and some other bugs, now testing. Hope to share the results in the nearest couple of weeks if everything will work properly.
