### ISSUE TITLE
Positive or false positive malware in kivy ?

### ISSUE THREAD

**Issue by GDVP** [kivy/kivy#7180]
I'm sorry, but I don't speak English very well. I will try to be brief.
I tested some kivy .whl files at https://www.virustotal.com/, and some pointed to malware. I am informing you, in case you can check if it is positive or false positive malware in kivy.

The tested files are available at https://pypi.org/project/Kivy/#history

Among those that I tested, those that pointed out a problem were:
**Kivy-2.0.0rc4-cp37-cp37m-win32.whl** (https://www.virustotal.com/gui/file/1ae60cdef1d59e82b06ed58f7e94f3f22c9116d24fab583972259042e9e16a48/detection)

**Kivy-2.0.0rc4-cp37-cp37m-win_amd64.whl** (https://www.virustotal.com/gui/file/404755dee71394aa0560fe9d2ad19ef09ed23446dd3e1d6f2e8d9213d98de219/detection)

**Kivy-2.0.0rc4-cp38-cp38-win32.whl** (https://www.virustotal.com/gui/file/1bc1779279a8285dd272c1a4e28e7ffd6bee2a2b9af0f78a1d18c2e337e95220/detection)

**Kivy-1.11.1-cp36-cp36m-win32.whl** (https://www.virustotal.com/gui/file/f3bea6e4a21991827885d04127fc6d09a0e974ecfa12da7bf5faae93562ea102/detection)

Thanks

**Comment by tshirtman** [comment]
We have had such reports in the past, pretty sure it's a false positive. https://github.com/kivy/kivy/issues/5211

**Comment by matham** [comment]
Thank you for letting us know. These are built on the CI and directly uploaded to pypi so it must be a false-positive. However, to be sure, it'd be helpful to see which file in the wheel it thinks is bad. I can't seem to figure that out from their site. Maybe you need an account?

**Comment by matham** [comment]
Looking further, we [don't](https://support.mozilla.org/en-US/questions/1196240) seem [to be](https://www.reddit.com/r/Cylance/comments/7rb6co/out_of_61_detectors_only_cylance_flags_my_program/) the only [one](https://www.reddit.com/r/antivirus/comments/6r09o0/cylance_false_positives/) in this [boat](https://www.reddit.com/r/Cylance/comments/78v65l/remote_utilities_false_positive_no_response_from/). In one of the threads they say:

> The strait forward answer is we do not whitelist. Our methodology and mathematical model is making a determination based off the ingredients and capability of your program.
>
> Now with that in mind, I have submitted this to threat intelligence for review. In the past, this results in a reclassification of the product inside the console for IT managers to make their own decision on based on the information provided.
>
> Just as you said - components of it look suspicious to our AI.

So very likely it's just being very eager.

**Comment by GDVP** [comment]
Thank you,
I just found it strange, that only a few versions had this result.
