### ISSUE TITLE
Recursion Error on simple app

### ISSUE THREAD

**Issue by Saad-py** [kivy/kivy#7183]
My code:

![image](https://user-images.githubusercontent.com/73306005/97575661-86e1c100-1a06-11eb-90b8-79af5bfa98e9.png)

The error:

![image](https://user-images.githubusercontent.com/73306005/97575715-97923700-1a06-11eb-8117-ac8d1a270819.png)

Hi everyone who views this, how is your day.
So I wanted to make an app where you enter a sentence then in another text input, it will show how many words by using the `str.split()` and a for loop so I was going to try the small things while this appeared.
Kindly help me crack this error and if you have any ideas to improve the project just comment.

Thanks in advance

**Comment by Cheaterman** [comment]
super(MyLayout(), self)

→ remove the () here.

**Comment by Cheaterman** [comment]
Also if you're using Python3 you might just do super().__init__(**kwargs)

**Comment by Saad-py** [comment]
@Cheaterman but now it gives this error 

Error: 

![image](https://user-images.githubusercontent.com/73306005/97577020-4be08d00-1a08-11eb-85e0-fcad32528344.png)

**Comment by Cheaterman** [comment]
You mean `self.add_widget(Label(...))` ?

Please post logs as text. Please (read the documentation)[https://kivy.org/doc/stable/guide/basic.html#customize-the-application].

**Comment by Saad-py** [comment]
oh we should add widget,

I am so sorry
just tell me how to add a text input and a button if you can

**Comment by Cheaterman** [comment]
As I said - [please read the documentation](https://kivy.org/doc/stable/guide/basic.html#customize-the-application).

**Comment by Saad-py** [comment]
K thank you very much
