### ISSUE TITLE
TypeError: descriptor 'split' of 'str' object needs an argument

### ISSUE THREAD

**Issue by Saad-py** [kivy/kivy#7185]
So again, 
My code:

![image](https://user-images.githubusercontent.com/73306005/97591982-99192a80-1a19-11eb-9ce0-b2c2d7021b47.png)

![image](https://user-images.githubusercontent.com/73306005/97592005-a0403880-1a19-11eb-9533-6d2b2c34345e.png)

So there is this error which shows TypeError: descriptor 'split' of 'str' object needs an argument

Kindly tell the solution and explain why 
Thanks in Advance

**Comment by HypoT** [comment]
Generally not the place for this sort of issue.

However, your issue here is what you intended with the: self.sentence = str line

**Comment by Saad-py** [comment]
@HypoT like explain me why I want to complete this project

**Comment by HypoT** [comment]
I presume you want something like a = self.sentence.text there, and remove line 37
