### ISSUE TITLE
TypeError: descriptor 'split' of 'str' object needs an argument

### ISSUE THREAD

**Issue by Saad-py** [kivy/kivy#7186]
So again,
My code:

![image](https://user-images.githubusercontent.com/73306005/97602302-92dc7b80-1a24-11eb-9f8b-7545ba971919.png)

![image](https://user-images.githubusercontent.com/73306005/97602323-9b34b680-1a24-11eb-9b03-5ecf4aa52c45.png)

The module file code:

![image](https://user-images.githubusercontent.com/73306005/97602408-b273a400-1a24-11eb-823a-f4a84618df4f.png)

So there is this error which shows TypeError: descriptor 'split' of 'str' object needs an argument

Kindly tell the solution and explain why
Thanks in Advance

Please I need your help.

**Comment by matham** [comment]
We use github issues exclusively for bug in kivy itself, not for support requests. Please follow the discord link above for getting support. 

Please don't open further support issues here.

**Comment by Saad-py** [comment]
But this is the suppourt section

**Comment by Saad-py** [comment]
And I don't use discord
