### ISSUE TITLE
python/kivy/nested scrollviews

### ISSUE THREAD

**Issue by sersadaka** [kivy/kivy#7188]
**Software Versions**
* Python: 3.8
* Kivy:2.0.0rc4
* Kivy installation method:

Dear kivy developers, I believe that kivy has a bug in the nested scrollviews part, so I will be glad to initiate this with no offense by paying 200$ to the person who solves this issue! (please don't close this issue unless I am satisfied)

suppose:
yy: the parent vertical scrollview(ScrollView)
xx : The nested horizontal scrollview(ScrollView)

in this flow I am moving:
FloatLayout:
    yy:
       do_scroll_y:True
       size_hint:1,1
       pos_hint:{'x':0,'top':1}
        GridLayout:
              cols:1
               height:self.minimum_height
               FloatLayout:
                      size_hint_y:None
                      size_hint_x:1
                      height:300
                      xx:
                        size_hint:1,0.5
                        pos_hint:{'x':0,'center_y':0.5}
                        do_scroll_x:True
                         GridLayout:
                                width:self.minimum_width
                                size_hint_x:None
                                rows:1
                                widget:
                                widget:
                                widget:
                                widget:
                                widget:
                                widget:
                                widget:
                                widget:
                                widget:
                                widget:
                                widget:

Discussion:

Now simply if you open facebook app and move to the top of homepage screen to the friends story this story is an xx scrollview of number of widgets, if you try to scroll x, while u are scrolling if you scroll y it will not scroll in y direction, while if you try to scroll in y direction when the touch is applied inside this xx it will only scroll the yy in y direction and wont allow to scroll xx during y scrolling, this is the same type of parent and nested scrollview I need ! all the links I have read, none is helpful to reach the desired nested scrollview type which is popular in all apps! please do share and help to fix this bug and issue! 

Thank you!

**Comment by Julian-O** [comment]
Informal bounty or not, I am closing this as a Support issue because it has been 2.5 years with no interest.
