### ISSUE TITLE
How do make my TextInput an integer to perform mathematical operations

### ISSUE THREAD

**Issue by Saad-py** [kivy/kivy#7190]
Hi guys, how are you doing
So, I am working on a project that takes a value from the TextInput then it divides by 1000 and display it on another label
it basically converts Hz to kHz.

Kindly help me and dear @matham just tell me where I can put my issues on GitHub as I don't use discord,

Thanks in advance and please don't add support label before telling me where I should put my issues other than discord and telling me the answers.

Best regards,
@Saad-py

**Comment by matham** [comment]
For support, as linked to in the previous responses, you can ask on discord (it's very easy to make an account there) or on the kivy-user's [mailing list](https://groups.google.com/g/kivy-users) linked from https://kivy.org/#support.

Please do not open further support requests here or I'll have to ban your ability to do that for some period of time.
