### ISSUE TITLE
Is kivy production ready? Can I use it in very serious applications?

### ISSUE THREAD

**Issue by UltraBurstXD** [kivy/kivy#7205]

**Comment by tshirtman** [comment]
That's not an issue, that's a general question, for which it's hardly possible to provide a definite answer.
- It's not perfect, you might find bugs (there definitely are some), and you might miss features, it doesn't do everything you might need.
- It's used in production by a lot of people, and has been for a decade, as people who built it were using it for their own productions right away, i've been using it for years to build client facing apps, and deliver their either as appliances, or as installers that people paid a license for, a lot of people are doing serious business with it.

Only you can know if it's ready for *your* production, it definitely is ready for some, and certainly not for all, it's up to you to investigate and see how it fits your needs. Feel free to come to https://chat.kivy.org and ask more precise questions.
