### ISSUE TITLE
PIL/SDL2: Unable to load Image io.BytesIO object for CoreImage

### ISSUE THREAD

**Issue by tgey** [kivy/kivy#7206]
**Software Versions**
* Python: 3.7.7
* OS: Ubuntu 20.04 / Elementary OS 5.1 Hera
* Kivy: 1.11.1
* Kivy installation method: pip

**Describe the bug**

After instantiating a suite of CoreImage using BytesIO jpeg images, the app suddenly stop and raise an error 
"PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f34d41fbad0>"
and a warning "[WARNING] [Image       ] Unable to load image <<_io.BytesIO object at 0x7f34d41fbad0>>".
Then, during few minutes, the Kivy app is unable to load a CoreImage with the same error.

**Expected behavior**
Loading multiple CoreImage from io.BytesIO object

**To Reproduce**
Create multiple CoreImage Object using io.BytesIO images. Hard to reproduce. 

**Code and Logs and screenshots**
![CoreImage](https://user-images.githubusercontent.com/21363799/98451369-388a9b80-2145-11eb-9eb4-42c5a58476cd.png)
![Pil_warning](https://user-images.githubusercontent.com/21363799/98451356-1f81ea80-2145-11eb-92b8-2a12fcdbccd6.png)
![PIL_error](https://user-images.githubusercontent.com/21363799/98451359-21e44480-2145-11eb-8b48-73a5a24e54db.png)

**Additional context**
PIL.Image.open is unable to open the io.BytesIO object but without any information.
I tried with both PIL and SDL2 providers but the same error is raised.
My intuition leads me to believe that it is about the management of io.BytesIO files in memory.

**Comment by matham** [comment]
This seems to be an issue with how you're using the API and you're providing a bytes object instead of e.g. a filename.
