### ISSUE TITLE
Motion Event: two pixel offset in y position

### ISSUE THREAD

**Issue by jafem** [kivy/kivy#7210]
**Software Versions**
* Python: 3.7.3
* OS: Debian Buster
* Kivy:  2.0.0rc4
* Kivy installation method: pip

**Describe the bug**
In MotionEvent there is a two pixel offset in the y position (window range). The range of the y position starts with 2 and ends with window height + 1.

**Expected behavior**
The range of the y position starts with 0 and ends with window height - 1.

**To Reproduce**
See minimal example: move the mouse pointer with pressed button to the top and bottom of the window. The current pointer position and the window size is printed.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.core.window import Window
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

from kivy.config import Config
Config.set('graphics', 'width', '500')
Config.set('graphics', 'height', '500')
Config.set('graphics', 'minimum_width', '500')
Config.set('graphics', 'minimum_height', '500')

class TestWidget(BoxLayout):
    def on_touch_down(self, touch):
        print("x = {} ({})  y = {} ({})".format(touch.x, Window.width, touch.y, Window.height))

    def on_touch_move(self, touch):
        print("x = {} ({})  y = {} ({})".format(touch.x, Window.width, touch.y, Window.height))

class TestApp(App):
    def build(self):
        return TestWidget()


if __name__ == '__main__':
    TestApp().run()
```

**Comment by gottadiveintopython** [comment]
#7389

**Comment by matham** [comment]
Fixed by https://github.com/kivy/kivy/pull/7389.
