### ISSUE TITLE
add_widget() reseting disable

### ISSUE THREAD

**Issue by Loukis-13** [kivy/kivy#7217]
This is just related to the method with which the widget is passed
```python
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

Builder.load_string('''
<Butt>:
    background_normal:'image.png'
    background_disabled_normal:'imagedisabled.png'
    on_press:print('a')
''')

class Butt(Button):
    pass

class MApp(App):
    def build(self):
        a=BoxLayout()
        a.add_widget(Butt(disabled=True))
        return a

MApp().run()
```
Even with the disabled being passed True it becomes False again when it is added
to resolve that just do this
```python
class MApp(App):
    def build(self):
        a=BoxLayout()
        b=Butt()
        a.add_widget(b)
        b.disabled=True
        return a
```
But I think it would be more practical if the first example worked

**Comment by matham** [comment]
Your first code example works perfectly for me. Can you please provide more details about the issue?

**Comment by Loukis-13** [comment]
I thought  i had the most recent version because i was actualizing it trough the normal methods but i read the docs and saw that i needed to do others things. I was using 1.10.1, now I am using v2.0.0rc4 and it is working fine.
Sorry for the inconvenience.
