### ISSUE TITLE
Segmentation Fault 

### ISSUE THREAD

**Issue by SAProdhan** [kivy/kivy#7219]
**Software Versions**
* Python: 3.8.3
* OS:  Windows 10
* Kivy: 1.11.1
* Kivy installation method: Anaconda

**My Code**
from kivy.app import App
from kivy.uix.floatlayout import FloatLayout
from kivy.lang import Builder

class RootWidget(FloatLayout):
    pass

class MainApp(App):
    def build(self):
        return RootWidget()

if __name__ == '__main__':
    MainApp().run()

**Output**
[INFO   ] [Logger      ] Record log in C:\Users\spame\.kivy\logs\kivy_20-11-15_25.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] Installed at "C:\Users\spame\anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\spame\anaconda3\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
Segmentation fault
(base)

*****
After that is shows a dialog says python stop working....

**Comment by gottadiveintopython** [comment]
Kivy 1.x.x doesn't support python 3.8.
Use recent version.
pip install --pre kivy==2.0.0rc4

**Comment by SAProdhan** [comment]
> Kivy 1.x.x doesn't support python 3.8.
> Use recent version.
> pip install --pre kivy==2.0.0rc4

I am sorry! my kivy version is 2.0.0 but it still not working. please help

**Comment by tshirtman** [comment]
please run with `python main.py -c kivy:log_level:debug` to have more info.

**Comment by SAProdhan** [comment]
> please run with `python main.py -c kivy:log_level:debug` to have more info.

Now it shows: 
INFO   ] [Logger      ] Record log in C:\Users\spame\.kivy\logs\kivy_20-11-15_5.txt
[INFO   ] [Kivy        ] Installed at "C:\Users\spame\anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]     
[INFO   ] [Python      ] Interpreter at "C:\Users\spame\anaconda3\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored) 
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [App         ] Loading kv <.\main.kv>
[DEBUG  ] [App         ] kv <.\main.kv> not found
[INFO   ] [Window      ] Provider: sdl2

**Comment by tshirtman** [comment]
hm really weird, nothing in the log hints at a problem, maybe there is an issue with the anaconda build, try to install with a normal python installation?

**Comment by matham** [comment]
The problem is that you're using anaconda, yet you're installing kivy using following the pip instructions, which is **not** compatible with anaconda.

Instead either use native python or for anaconda follow the conda instructions andinstall with `conda install kivy -c conda-forge` in a clean environment.
