### ISSUE TITLE
BoxLayout is not using all the available space

### ISSUE THREAD

**Issue by Michal-Mikolas** [kivy/kivy#7223]
**Software Versions**
* Python: 3.7.9
* OS: Windows 10
* Kivy: 2.0.0rc4
* Kivy installation method: pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/

**Describe the bug**
I'm unable to make BoxLayout using all the available window space. Let's try the simplest example: 

`test.py`: 
```
from kivy.app import App
from kivy.uix.widget import Widget

class MainView(Widget):
	pass

class TestApp(App):
	def build(self):
		return MainView()

if __name__ == '__main__':
	TestApp().run()
```

`test.kv`:
```
#:kivy 2.0.0

<MainView>:
	BoxLayout:
		orientation: 'vertical'

		Button:
			text: "Button 1"

		Button:
			text: "Button 2"

		Button:
			text: "Button 3"
```

The result looks like this: 
![screenshot of the bug](https://i.imgur.com/hs9yi8F.png)

**Expected behavior**
I would expect the buttons have 100% width of the window. 

According to the screenshot in [BoxLayout official documentation](https://kivy.org/doc/stable/api-kivy.uix.boxlayout.html), it should take 100 % of the parent space. 

**Additional context** 
I also tried to put `size_hint: 1, 1` everywhere: 

```
#:kivy 2.0.0

<MainView>:
	size_hint: 1, 1

	BoxLayout:
		orientation: 'vertical'
		size_hint: 1, 1

		Button:
			size_hint: 1, 1
			text: "Button 1"

		Button:
			size_hint: 1, 1
			text: "Button 2"

		Button:
			size_hint: 1, 1
			text: "Button 3"
```

But the result was the same.

**Comment by matham** [comment]
You used widget as the class for `MainView`, but that is not a layout so it doesn't automatically resize the box layout.
