### ISSUE TITLE
RV caches views including selections (=RV does not work out-of-the-box), MUST call clear_selection() in SelectableRecycleBoxLayout on each view update

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [kivy/kivy#7233]
**Software Versions**
* Python: 3.8
* OS: archlinux (rolling)
* Kivy: 2.0.0.0 rc4
* Kivy installation method: PyCharm

**Describe the bug**
An out-of-the-box behavior for RecycleView for the vast majority of Kivy users would be for the cached views to not store selection state of the list items. So if I select something in the list of items that RV displays, update the RV with new data, update the RV data with old data - the selection should not be stored. Most situations will view this as the default scenario.  What is observed is that Kivy by default caches the RV widget views, sometimes corresponding with the selected old data items, sometimes disjointed from the old selection items showing selection at a set index regardless of underlying data. 

This situation is immediately rectified by calling clear_selection() from within a method placed into the classic documentation example of SelectableRecycleBoxLayout class before each RV view change/update. This seems to flush cached selection information on individual stored views.

This should be a documentation fix - and an easy one - that's of utmost urgency because this will plague nearly all Kivy users because it breaks an out-of-the-box behavior of a key widget. The classic RV usage code example can include a method "remove_selection" that can be called from within KV as a binding to a field.
```python
    class SelectableRecycleBoxLayout(FocusBehavior, LayoutSelectionBehavior, RecycleBoxLayout):
    # required to forbid unselecting a selected item. An item can be unselected
    # only by selecting another item if set to False
    touch_deselect_last = BooleanProperty(False)

    def remove_selection(self):
        self.clear_selection()

**Comment by matham** [comment]
Please provide a minimum reproducible example showing the issue.
