### ISSUE TITLE
Swype-like gesture input as whole words  is not working in TextInput widgets since 2012?

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [kivy/kivy#7242]
Is this bug not critical? In a nutshell, user input in textinput widgets is limited to text entry one character at a time - and swype-like gesture input as whole words  is not working at all.
Can the devs state here at least where to look for the source of this 8 year old issue in Kivy code (found another bug submitted from 2012) so people can volunteer to analyze this "NEEDS-ANALYSIS" open report and look for a fix for this fundamental broken functionality in Kivy?

_Originally posted by @allhavebrainimplantsandmore in https://github.com/kivy/kivy/issues/2694#issuecomment-736341417_

**Comment by matham** [comment]
Please don't create duplicate issues for existing issues.
