### ISSUE TITLE
TextInput: cut-cope-paste bubble doesn't appear when using selection handles

### ISSUE THREAD

**Issue by Alspb** [kivy/kivy#7247]
**Software Versions**
* Python: 3.8.5
* OS: Linux Mint 20 (based on Ubuntu 20.04 LTS) or Android 10
* Kivy: 2.0.0rc4

**Describe the bug**
Cut-cope-paste bubble doesn't appear when selecting the word by double-tap (e.g. when selecting 'bbbb' in the TextInput from the code below). Also the bubble often doesn't appear when changing selection using selection handles.
Also it seems strange that cursor is visible when selection handles are active, but looks like it doesn't influence anything.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.uix.textinput import TextInput
class Sample(App):
    def build(self):
        return TextInput(text="aaaa bbbb cccc", use_handles=True, use_bubble=True)
Sample().run()
```

**No bubble here**
![No bubble bug](https://user-images.githubusercontent.com/73047043/101558232-73872580-39b6-11eb-8e44-582643ba20ba.png)

**Comment by gottadiveintopython** [comment]
I ran the example with Kivy 1.11.1 because PRs I wrote (#6741,  #7188 and #7203) might causing the issue. And I confirmed it occurs in 1.11.1 .
