### ISSUE TITLE
TextInput: Keyboard doesn't appear after hide-restore app on Android

### ISSUE THREAD

**Issue by Alspb** [kivy/kivy#7248]
**Software Versions**
* Python: 3.8.5
* OS: Android 10
* Kivy: 2.0.0rc4

**Describe the bug**
Suppose I perform the following actions on Android (see the code below):

1. Tap on TextInput.
TextInput becomes focused and software keyboard appears.
2. Hide app.
Keyboard disappears then.
3. Restore app.
TextInput still remains focused (and even has cursor on the same place) but keyboard doesn't appear.
To make keyboard appear I need to tap on some other widget and then focus on TextInput again. But if TextInput is the only widget that's not an option.

**Code**
```python
from kivy.app import App
from kivy.uix.textinput import TextInput

class Sample(App):
    def build(self):
        return TextInput(text='aaaa bbbb cccc')

Sample().run()
```

The only workaround I see is to defocus all TextInputs when app restores (or hides), as it is done in the code below.
But it would be much more convenient to show keyboard automatically when app restores.

**Workaround code**
```python
from kivy.app import App
from kivy.uix.textinput import TextInput
from kivy.base import EventLoop
from kivy.utils import platform

class Sample(App):
    def build(self):
        self.bind(on_start=self.post_build_init)
        return TextInput(text='aaaa bbbb cccc')

    def post_build_init(self, ev):
        EventLoop.window.bind(on_restore=self.on_restore)

    def on_restore(self, window):
        if platform=='android':
            for w in self.root.walk(restrict=True):
                if isinstance(w, TextInput):
                    w.focus = False

Sample().run()
```

**Comment by disposableone** [comment]
Confirming this as well.

**Comment by allhavebrainimplantsandmore** [comment]
Confirming this as well.

**Comment by dcindia** [comment]
This is default behaviour for other gui frameworks as well. In many popular apps also, focus remains but keyboard doesn't appear until you remove focus and put focus again. 
However, i believe that there should be an option for such behavior. For a workaround, you can write a function using on_resume provided by kivy.

**Comment by Alspb** [comment]
Suppose you're right.
Now I use the following approach as a workaround (unlike the code above it also works for TextInput widgets inside popups).
But it's actually an interesting question where it's better to manipulate with focus: in on_restore or in on_resume.

```python
from kivy.app import App
from kivy.uix.textinput import TextInput
from kivy.base import EventLoop
from kivy.utils import platform

class Sample(App):
    def build(self):
        self.bind(on_start=self.post_build_init)
        return TextInput(text='aaaa bbbb cccc')

    def post_build_init(self, ev):
        EventLoop.window.bind(on_restore=self.on_restore)

    def on_restore(self, window):
        if platform=='android':
            for widget in self.root_window.children: 
                for w in widget.walk(restrict=True):
                    if isinstance(w, TextInput) and w.focus:
                        w.focus = False
                        w.focus = True
                        break
Sample().run()
```

**Comment by Shawn91** [comment]
> On Android widget is unfocused if the user hides the keyboard. But anyway currently one needs to reenable the keyboard after switching back to the app.

On my Android phone, the widget is not unfocused when I hide the keyboard. And I have to tap outside of the textinput to unfocuse it first before tap it again to trigger the keyboard to show.

My phone runs MIUI os (an extremely popular fork of Android in China ) insteat of the original Android.

**Comment by Julian-O** [comment]
Based on the discussion, this appears to be working as designed.

If you think there is some action that is needed to be taken by the Kivy team, please let us know.
