### ISSUE TITLE
Setup.py missing osx_arch == "arm64" test, to build natively for Apple Silicon

### ISSUE THREAD

**Issue by vividfog** [kivy/kivy#7265]
**Software Versions**
* Python: 3.8.6
* OS: macOS 11.1
* Kivy: 2.0.0
* Kivy installation method: Compile from source

**Describe the bug**
Running "make" in a native Darwin arm64 environment (not Rosetta 2) produces an x86_64 build on an M1 Mac. This can be verified with "lipo -archs". As a result, any other arm64 packages that use kivy won't run natively: _"mach-o, but wrong architecture"_

**However, setup.py is already completely capable of building for arm64.** I verified this by very crudely search-replacing the two instances of where ARCH is set to x86_64; I simply changed those to arm64, for example:

```
# Detect 32/64bit for OSX (http://stackoverflow.com/a/1405971/798575)
if sys.platform == 'darwin':
    if sys.maxsize > 2 ** 32:
        osx_arch = 'arm64'
    else:
        osx_arch = 'arm64'
```

and so on. Originally osx_arch was set to either i386 or x86_64.

**Yes, that's a horrible way to "fix" it! But after this quick edit, running "make" works and it's an arm64 build.** The resulting build works too, I tested by running "katrain", which uses kivy. (The motivation for me to patch this for myself was to run [katrain](https://github.com/sanderland/katrain).)

**How to fix setup.py properly for macOS/arm64**

Unfortunately I'm not much of a developer to propose a proper patch, but it looks like it's just few modifications to setup.py to get it going. There's an if/else test between i386 and x86_64, but the _third and missing_ match for Darwin should be "arm64". This needs to be done in two places. Search for these:

```
elif platform == 'darwin':
...
# Detect 32/64bit for OSX
```

I can test the patched setup.py on an M1 Mac if someone has time to fix this for the next dot release.

(First message in Github btw. Yay.)

**Comment by tshirtman** [comment]
We could probably make much better choices by using `platform.uname()` (or probably even `platform.machine()`) instead of guessing with the much less complete `sys.platform` and big numbers.

Can someone with an M1 mac give the result of `platform.uname()`?

**Comment by vividfog** [comment]
Thanks for looking into this. Here's the output from an M1 Air running macOS 11.2 Release Candidate:

```
>>> print (platform.uname())
uname_result(system='Darwin', node='m1.local', release='20.3.0', version='Darwin Kernel Version 20.3.0: Thu Jan 14 14:38:22 PST 2021; root:xnu-7195.81.2~2/RELEASE_ARM64_T8101', machine='arm64')

>>> print (platform.machine())
arm64
```

**Comment by tshirtman** [comment]
so i *think* we could replace that test with just setting that variable to that value, as it's the same one you put to have things working, i'll make a patch and see if it works through CI.

**Comment by vividfog** [comment]
For reference, here's the same when running Terminal with Rosetta 2. That is, using translated x86 binaries. I presume the output isn't far off from what a "real" Intel Mac would produce, but I no longer have one.

```
>>> print (platform.uname())
('Darwin', 'm1.local', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 14 14:38:22 PST 2021; root:xnu-7195.81.2~2/RELEASE_ARM64_T8101', 'x86_64', 'i386')
```

**Comment by matham** [comment]
Can you try master again? https://github.com/kivy/kivy/pull/7341 should have fixed it.

**Comment by vividfog** [comment]
Terminal running native arm64:

```
> git clone git://github.com/kivy/kivy.git

Cloning into 'kivy'...

> cd kivy
> make

```
There are a multitude of warnings here, but it does compile. Handling those warnings is a topic for another issue, if it even is an issue.

```
> cd kivy
> lipo -archs _clock.cpython-39-darwin.so

arm64
```

So, that's a success.

I tried two more scenarios:

- Terminal under Rosetta 2, using Python that was provided by Homebrew. Homebrew compiled as arm64. The resulting architecture is arm64. It's not clear to me what architecture I was supposed to expect.
- Terminal under Rosetta 2, using Python provided by Big Sur. No Homebrew in the chain, only system software and whatever Xcode includes. The resulting architecture is x86_64. As expected.

There's a fourth scenario which I think would be worth testing. The expected output would be x86_64... but I'm not too keen on installing two Homebrews on my system. If you think this scenario is important to test, I could do it, given some time.

- Terminal under Rosetta 2, using Python that was provided by Homebrew. Homebrew compiled as x86_64. Expected resulting architecture: x86_64. Result: Not tested.

**Comment by vividfog** [comment]
The resulting arm64 build works to the extent I can test it, which is simply by running `katrain`. It does run, and the architecture errors mentioned in sanderland/katrain#331 are gone. The top bar of the katrain UI is missing, but that's a whole another topic.

**Comment by tshirtman** [comment]
Great!

I have only one remaining concern, but i think we'll learn soon enough if that's the case, and i assume it would be a rare one. I think it's possible to have a 32 bit python on an x86_64 osx python, and i think in this case we would now build a version incompatible with the installed python, i don't have a mac machine to try, and i think you don't have a mac fit to test that possibility, so no worries. Thanks for confirming it works :).

**Comment by vividfog** [comment]
Well, turns out it worked _almost_ OK via pygame, but with SDL2 there's a hard stop. I tried to run some [test code](https://kivy.org/doc/stable/api-kivy.app.html) without pygame installed, and:

```
> python3 test.py
[INFO   ] [Kivy        ] v2.1.0.dev0
[INFO   ] [Kivy        ] Installed at "/opt/homebrew/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.1 (default, Jan  8 2021, 12:11:08)
[Clang 12.0.0 (clang-1200.0.32.28)]
[INFO   ] [Python      ] Interpreter at "/opt/homebrew/opt/python@3.9/bin/python3.9"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 187 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_ffpyplayer
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [App         ] Unable to get a Window, abort.
```

I realize this is a whole another issue, so it might be OK to close this one, the platform recognition works. Perhaps me or @kentdorsey will create a new issue for what's above. Though right now I have no idea how to get more info about what happened between the last two lines. Feel free to send a pointer and I'll do some googling.

Either that; or we can repurpose this issue to try and catch all M1-related issues. I don't have a preference on that.

**Comment by matham** [comment]
Try running kivy with the env variable `KCFG_KIVY_LOG_LEVEL` set to `debug`. That should show the issue.

**Comment by vividfog** [comment]
I found the `kivy/examples` directory and after setting the env variable tried running several of those. They all fail with the same pattern. Unfortunately there's not much debug info, see below. I wonder how to make it say more.

I did build a small "hello world" SDL2 app using example code from elsewhere and it ran fine. It's possible that SDL2 itself is problematic in M1 but it did't look that way. Homebrew now includes a native SDL2 for arm64 and the dependencies were installed without problems: `brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer`

```
> python3 pango_demo.py
[INFO   ] [Kivy        ] v2.1.0.dev0
[INFO   ] [Kivy        ] Installed at "/opt/homebrew/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.1 (default, Jan  8 2021, 12:11:08)
[Clang 12.0.0 (clang-1200.0.32.28)]
[INFO   ] [Python      ] Interpreter at "/opt/homebrew/opt/python@3.9/bin/python3.9"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 187 symbols loaded
[DEBUG  ] [Cache       ] register <kv.resourcefind> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_ffpyplayer
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [App         ] Unable to get a Window, abort.
```

Note that @kentdorsey ran into the same problem in the proceedings of sanderland/katrain#331. Somehow I was able to make katrain run with pygame installed, but it had serious problems with content scaling and fonts. That's why I'm now trying to make it run with SDL2, but then us both get the "Unable to get a Window" result.

It now seems it's happening with the tiny kivy test apps too and that it's an upstream issue from katrain's point of view. Not sure how to debug it further, but the first step surely is to get pango_demo.py to work, correct?

`kivy/examples/text/pango_demo.py`

**Comment by matham** [comment]
Hmm looks like `KCFG_KIVY_LOG_LEVEL` didn't take effect.

You could try instead `python script.py --config "kivy:log_level:debug"` and if that doesn't work, you can try adding `from kivy import Config; Config.set("kivy", "log_level", "debug")` at the start of the script file. You can also try `trace` instead of `debug` as that should add more info (but likely less relevant).

But yea, this is a kivy issue.

**Comment by vividfog** [comment]
Here's the second attempt, but it doesn't increase verbosity:

```
> python3 pango_demo.py --config "kivy:log_level:debug"
[INFO   ] [Kivy        ] v2.1.0.dev0
[INFO   ] [Kivy        ] Installed at "/opt/homebrew/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.1 (default, Jan  8 2021, 12:11:08)
[Clang 12.0.0 (clang-1200.0.32.28)]
[INFO   ] [Python      ] Interpreter at "/opt/homebrew/opt/python@3.9/bin/python3.9"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 187 symbols loaded
[DEBUG  ] [Cache       ] register <kv.resourcefind> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_ffpyplayer
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [App         ] Unable to get a Window, abort.
```

And third, adding a line into pango_demo.py... no need to copy paste, the output is as above, after this addition:

```
> cat pango_demo.py
# -*- coding: utf-8 -*-

from kivy import Config; Config.set("kivy", "log_level", "debug")
from kivy.base import runTouchApp
from kivy.lang import Builder
from kivy.factory import Factory as F


class DemoBox(F.ButtonBehavior, F.BoxLayout):
    base_direction = F.StringProperty(None, allownone=True)
    font_context = F.StringProperty(None, allownone=True)
    font_size = F.NumericProperty(10)
...
```

It might be interesting to test an SDL2 app that actually tries to "get a window". Because who knows, maybe the problem is even more upstream. But I'd have to look into how to do that.

The `make` output of the latest dev0 build wasn't squeaky clean either, but everything gets compiled and the pygame variant of katrain kinda worked. Attaching the `make` output here in case there's something useful in it. 
[kivy-make-m1-2021-01-24-1152.log](https://github.com/kivy/kivy/files/5861916/kivy-make-m1-2021-01-24-1152.log)

The last line of the log points at something that doesn't exist. Here's what does:

```
 ph@m1  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs  ls -la
total 0
drwxr-xr-x  5 ph  staff  160 Dec 11 01:36 .
drwxr-xr-x  6 ph  staff  192 Dec  4 00:14 ..
drwxr-xr-x  5 ph  staff  160 Nov 30 14:27 DriverKit20.2.sdk
drwxr-xr-x  7 ph  staff  224 Nov 30 14:27 MacOSX.sdk
lrwxr-xr-x  1 ph  staff   10 Dec 11 01:35 MacOSX11.1.sdk -> MacOSX.sdk
```

This could simply be that I'm on macOS 11.2 RC. Would need to have a new version of Xcode as well for the 11.2 symlink to be in place.

Anyway, I added the symlink manually. Compile log is very similar, except that the 11.2 symlink is now used: 
[kivy-make-m1-2021-01-24-1210.log](https://github.com/kivy/kivy/files/5861966/kivy-make-m1-2021-01-24-1210.log)

The bad news is that even after this detour the Pango demo output remains the same, with no added verbosity. Not sure how to carry the flag from here.

**Comment by vividfog** [comment]
Update: SDL2 works. I was able to compile any play [this wonderful game](https://github.com/vendethiel/graphicalbattle). The next step should be to somehow get more logs from Kivy, for what happens just before `[CRITICAL] [App         ] Unable to get a Window, abort.` when running `python3 pango_demo.py --config "kivy:log_level:debug"`.

**Comment by matham** [comment]
I expect the warnings are not the issue (that happens until cython catches up).

I guess kivy swallows the error somehow. Try adding `raise` [here](https://github.com/kivy/kivy/blob/master/kivy/core/__init__.py#L78) and [here](https://github.com/kivy/kivy/blob/master/kivy/core/__init__.py#L94) so that the error won't be swallowed. But it's strange because the error should be logged because it seems to be happening in there, but it's not. Unless the error happens deeper and is suppressed somehow.

**Comment by vividfog** [comment]
Thanks for the pointers. I edited `/opt/homebrew/lib/python3.9/site-packages/kivy/core/__init__.py` directly. Added `raise` at the end of those snippets, like this:

```
except ImportError as e:
            errs.append((option, e, sys.exc_info()[2]))
            libs_ignored.append(modulename)
            Logger.debug('{0}: Ignored <{1}> (import error)'.format(
                category.capitalize(), option))
            Logger.trace('', exc_info=e)
            raise
```

(Some of those except sections already had `raise` at the end of them, so I followed the same pattern.)

But still, no added verbosity, and I see that the correct `__init__.py` is invoked:

```
> python3 pango_demo.py --config "kivy:log_level:debug"
[INFO   ] [Logger      ] Record log in /Users/ph/.kivy/logs/kivy_21-01-24_21.txt
[INFO   ] [Kivy        ] v2.1.0.dev0
[INFO   ] [Kivy        ] Installed at "/opt/homebrew/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.1 (default, Jan  8 2021, 12:11:08)
[Clang 12.0.0 (clang-1200.0.32.28)]
[INFO   ] [Python      ] Interpreter at "/opt/homebrew/opt/python@3.9/bin/python3.9"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 187 symbols loaded
[DEBUG  ] [Cache       ] register <kv.resourcefind> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_ffpyplayer
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [App         ] Unable to get a Window, abort.
```

That's all  she wrote. To be sure, I even checked the .kivy/logs file, same content as above.

**Comment by matham** [comment]
Huh. So if there's no error, it must mean that no window provider was even tried, hence the critical failure when it tries to use window. Yet the log does say that sdl2 is used as the window provider, which is a contradiction since if sdl2 worked it wouldn't fail.

Some error must be ignored somewhere internally.

**Comment by vividfog** [comment]
@matham good news. Since things were broken in strange ways described above, and since @kentdorsey had success starting from a clean slate, I did the same. Wiped out homebrew and everything it provided, including python3 and pip3 modules. Started over.

And suddenly `katrain`, which uses Kivy, works on my M1. I've got no more issues to report on M1 for now. This isn't a big test case, but it's an end to end test case and so far so good.

I suspect this had something to do with being an early adopter of arm86 Homebrew. I installed it in December, as soon as there was something to install. Perhaps something was displaced and later `brew update`s didn't improve the situation. But no way to conclude one way or another.

**Comment by tshirtman** [comment]
That's great to read! So i assume this can be closed now, as kivy is supported on the M1?

**Comment by vividfog** [comment]
@tshirtman it is supported unless someone declares otherwise and shows something to prove it. 

What I know is that KaTrain depends on kivy and I haven't observed any hiccups with a so-called "vanilla installation", that is, after reinstalling the latest homebrew, kivy-2.1.0.dev0, and katrain-1.7.4, as per their individual instructions and auto-installed dependencies, all native arm64. I did not have to do any wizardry via .zshrc or environment variables to make it work. 

Thank you and @matham for picking this up and getting it done. 🙏

```
> brew --version
Homebrew 2.7.7

> python3 --version
Python 3.9.1

> pip3 list | grep Kivy
Kivy        2.1.0.dev0
```

![katrain-kivy-m1](https://user-images.githubusercontent.com/75913791/106337939-3e52d180-629b-11eb-98a7-d4337fd46a7a.jpg)
