### ISSUE TITLE
Search not working in kivy.org

### ISSUE THREAD

**Issue by ntaraujo** [kivy/kivy#7266]
**Describe the bug**
When trying to search anything on docs, nothing happens. Results area is empty

**Expected behavior**
Find a documentation by searching in the official site

**To Reproduce**
* Go to [https://kivy.org/doc/stable/](https://kivy.org/doc/stable/)
* Try to search something

**Code and Logs and screenshots**

![Screenshot from 2020-12-13 11-21-11](https://user-images.githubusercontent.com/66187211/102016177-65326400-3d3e-11eb-8140-dff2626484c5.png)
![Screenshot from 2020-12-13 11-21-18](https://user-images.githubusercontent.com/66187211/102016178-66639100-3d3e-11eb-8d80-72f79bfff557.png)

**Comment by thunderrous** [comment]
Not working for me either. You can use the PDF while they fix it. https://media.readthedocs.org/pdf/kivy/latest/kivy.pdf

**Comment by matham** [comment]
Yeah, I'm not sure why this is happening. Search only works when stable-1.11.1 is selected.

**Comment by matham** [comment]
From the Firefox console log:

```
Uncaught ReferenceError: Search is not defined
    <anonymous> https://kivy.org/doc/stable-1.11.0/searchindex.js:1
searchindex.js:1:1
    <anonymous> https://kivy.org/doc/stable-1.11.0/searchindex.js:1
```

**Comment by xayhewalo** [comment]
Its working now for me at least

**Comment by ntaraujo** [comment]
for me too. closing
