### ISSUE TITLE
Kivy breaks the terminal control sequencies it is running into

### ISSUE THREAD

**Issue by CastixGitHub** [kivy/kivy#7268]
**Software Versions**
* Python: 3.6+
* OS: arch
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
When in the terminal you press something, it gets escaped like :arrow_up:  becomes `^[[A` or Control+b becomes `^b`
This wasn't so important before kivy2 release, but now it's possible to run the app in an async context, and as an example running ipython in that shell, since the interactive module was deprecated, this would be very good.

**Expected behavior**
these non-printing characters should be, well, not printed :)

**To Reproduce**
- get the kivy example app from kivy.org
```python
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()
```
- launch it
- go into the terminal
- press the up key on your keyboard
- see the `^[[A` being printed

Tried with `bash` and `zsh`; with `kitty` and unconfigured `xterm`
Tried also by disabling logs with `os.environ["KIVY_NO_CONSOLELOG"] = "1"` before importing kivy

**Comment by CastixGitHub** [comment]
well, actually running `import time; time.sleep(5)` is enough to reproduce the issue, so it's not a kivy issue at all

**Comment by matham** [comment]
If this is not a kivy issue, why re-open?

**Comment by CastixGitHub** [comment]
Yes, because when the app is ran into trio, it shouldn't block the terminal; I will re-write this issue report

I'm replicating with the following snippet https://gist.github.com/mikenerone/786ce75cf8d906ae4ad1e0b57933c23f
replacing the code this way it blocks:
```
async def sleeper():
    print('sleeping')
    import time; time.sleep(5)


async def main():
    print("In trio loop")
    async with trio.open_nursery() as nursery:
        nursery.start_soon(trio.to_thread.run_sync, ipython_worker)
        nursery.start_soon(sleeper)
    print("Exiting trio loop")

```
replacing it this (keeping main as the previous) way it won't block
```
async def sleeper():
    print('sleeping')
    await trio.sleep(5)
```

as my app is ran by 
```
        async with trio.open_nursery() as nursery:
            nursery.start_soon(trio.to_thread.run_sync, ipython_worker)
            nursery.start_soon(partial(app.async_run, async_lib='trio'))
```
then something is blocking (but I can still type normal characters in ipython and the app correctly handles events)

**Comment by matham** [comment]
Can you please a minimally but fully running example that shows the issue? Because I'm not sure this has anything to do with Kivy.

**Comment by CastixGitHub** [comment]
You were right, thanks to @njsmith from the trio community it turned out that I was just missing a `import readline` as stated in the python docs https://docs.python.org/3/library/functions.html#input

**Comment by CastixGitHub** [comment]
importing readline is enough for `input`
to get that in ipython call it like `__import__('IPython').embed(using='trio', colors='Neutral', simple_prompt=False)` because it uses prompt_toolkit as a replacement for readline; but also provide a replacement for prompt
https://github.com/ipython/ipython/blob/master/IPython/terminal/interactiveshell.py#L326
and it is True by default because of
```
In [29]: sys.stderr.isatty()
Out[29]: False

In [30]: sys.stderr
Out[30]: <kivy.logger.LogFile at 0x7f66050a68e0>
```
and https://github.com/ipython/ipython/blob/3587f5bb6c8570e7bbb06cf5f7e3bc9b9467355a/IPython/terminal/interactiveshell.py#L103

see attached screenshot to enjoy 

![Screenshot from 2020-12-18 00-55-37](https://user-images.githubusercontent.com/21062669/102559128-6ca39580-40cf-11eb-8b60-dc5d26c55806.png)

also
```
In [6]: App.get_running_app().root.ids.label.status
Out[6]: 'Reading'

In [7]: App.get_running_app().root.ids.label.status
Out[7]: 'Swimming'
```
