### ISSUE TITLE
kivy.org/docs/stable is down?

### ISSUE THREAD

**Issue by sfxc09** [kivy/kivy#7273]
I can't access the documentation, 404 not found error, on all the documentation tabs I had open 404'd :'(

**Comment by amarudemonn** [comment]
Me too, same with installation

**Comment by sfxc09** [comment]
Use this for now https://buildmedia.readthedocs.org/media/pdf/kivy/latest/kivy.pdf

I'm pretty sure Kivy is dying at this point. Wouldn't be surprised if it never came back online

**Comment by matham** [comment]
Fixed now. It ran out of space.

**Comment by matham** [comment]
@sfxc09 please don't spread [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt).
