### ISSUE TITLE
It seems Kivy 2.0.0 plays .ogg no more

### ISSUE THREAD

**Issue by lokapal** [kivy/kivy#7278]
**Software Versions**
* Python: 3.7.5
* OS: Ubuntu 18.04 LTS
* Kivy: 2.0.0
* Kivy installation method: python3.7 -m pip install --pre kivy[full] kivy-examples

Kivy 2.0.0 release cannot load .ogg files

**Expected behavior**
It seems to me that Kivy should handle .ogg audio files properly. 

The code from manual/example:
```from kivy.core.audio import SoundLoader

sound = SoundLoader.load('music.ogg')
if sound:
    print("Sound found at %s" % sound.source)
    print("Sound is %.3f seconds" % sound.length)
    sound.play()
```
console log:
```
python3.7 testm.py 
[INFO   ] [Logger      ] Record log in /home/osboxes/.kivy/logs/kivy_20-12-17_21.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.7/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3.7"
[INFO   ] [SoundFFPy   ] Using ffpyplayer 4.3.2
[INFO   ] [Audio       ] Providers: audio_ffpyplayer, audio_sdl2 
[WARNING] [Audio       ] Unable to find a loader for </home/osboxes/test/music.ogg>
```

**Comment by matham** [comment]
Sounds like the ffmpeg used in your ffpyplayer comes without built in ogg support. You can see which formats it supports by running `from ffpyplayer.tools import get_fmts; print(get_fmts(input=True)[0])`.

If you installed ffpyplayer from a wheel using pip, it should support ogg. If you installed it from source then you used the ffmpeg that comes from ubuntu's apt and that may not have ogg support built in.

But either way this is not really a kivy issue.
