### ISSUE TITLE
Changed label text stacks until window is resized

### ISSUE THREAD

**Issue by wooposs** [kivy/kivy#7311]
**Software Versions**
* Python: 3.8.5
* OS: Windows 10
* Kivy: 2.0.0
* Kivy installation method: via pip as descripted in the tutorial

**Bug Description**
I tried to change a label text to the text entered in a text box by clicking a button.
The problem is: after clicking the button, the text from the text box is shown as the label text but unfortunately it stacks with the text entered and "transferred" before. Which means the newest text is in the front and the older text values are still visible behind the new text. **After resizing the window the new text is shown correctly and the old text is gone.**

**Expected behavior**
The label text changes directly after clicking the button and doesn't need resizing the window to do so.

**To Reproduce**
See main.py and my.kv below.

**main.py**
```python
from kivy.app import App
from kivy.properties import ObjectProperty
from kivy.uix.gridlayout import GridLayout


class Screen(GridLayout):
    o_txt1 = ObjectProperty(None)
    o_lbl1 = ObjectProperty(None)

    def __init__(self, **kwargs):
        super(Screen, self).__init__(**kwargs)

    def show_text(self):
        self.o_lbl1.text = self.o_txt1.text


class MyApp(App):
    def build(self):
        return Screen()


if __name__ == '__main__':
    MyApp().run()
```

**my.kv**
```python
<Screen>:
    o_txt1: txt1
    o_lbl1: lbl1
    cols: 2
    Label:
        id: lbl1
        text: 'lbl1'
    TextInput:
        id: txt1
        multiline: False
    Label:
        id: lbl2
        text: 'lbl2'
    TextInput:
        id: txt2
        multiline: False
    Button:
        id: but
        text: 'SHOW'
        on_release: root.show_text()
```
**Screenshot**
After clicking the button, "xx" is shown in front of the initial text value "lbl1"
![grafik](https://user-images.githubusercontent.com/57659513/103621158-1048ce80-4f35-11eb-9d91-6ff22f577f9f.png)

**Comment by gottadiveintopython** [comment]
I couldn't reproduce the issue. But I recommend you to rename `Screen` to another e.g. `MyGridLayout` and see the issue still occurs. The reason for that is that Kivy already has a widget named `Screen`, and your `Screen` is affected by it and vice versa.
