### ISSUE TITLE
export_to_png scale argument not working.

### ISSUE THREAD

**Issue by IagoBeuller** [kivy/kivy#7314]
**Software Versions**
* Python: 3.9.1
* OS: Windows 10 19041.685
* Kivy: 2.0
* Kivy installation method: pip install kivy[full]

**Bug description**
export_to_png is not passing scale argument to export_as_image:
self.export_as_image().save(filename, flipped=False)

**Expected behavior**
Pass the scale argument to export_as_image, to then save the image with custom scale:
self.export_as_image(*args, **kwargs).save(filename, flipped=False)

**Comment by tshirtman** [comment]
https://github.com/kivy/kivy/blob/2.0.0/kivy/uix/widget.py#L723

duh >_>
That could be an easy fix.
