### ISSUE TITLE
kivy.graphics.texture Texture.create () dumps core

### ISSUE THREAD

**Issue by mvdvalk** [kivy/kivy#7321]
Hi,

On Kivy v2.0.0:

from kivy.graphics.texture import Texture
tx = Texture.create () # dumps core

**Comment by Schlaubischlump** [comment]
This issue is missing some important informations. E.g Which platform are you using ? It is working fine for mac OS 10.15

**Comment by pythonic64** [comment]
You have to import `Window` (`from kivy.core.window import Window`) to use `Texture.create`.

Duplicate of https://github.com/kivy/kivy/issues/5254.
