### ISSUE TITLE
Label does not react to window resize in kivy2.0.0

### ISSUE THREAD

**Issue by hscpy** [kivy/kivy#7324]
**Software Versions**
* Python: 3.6.9
* OS: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic
* Kivy: 2.0.0

**Describe the bug**
A label with text_size bound to width and size to texture_size does not get resized with its parent.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.config import Config
from kivy.lang import Builder
from kivy.uix.label import Label

Config.set('graphics', 'width', 300)
Config.set('graphics', 'height', 300)
Config.set('graphics', 'resizable', 1)

Builder.load_string('''
<MyLabel>:
    text_size: self.width, None
    size: self.texture_size
    font_size: 30
''')

class MyLabel(Label):
    pass

class MyApp(App):
    def build(self):
        text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
        return MyLabel(text=text)

MyApp().run()
```
This produces the following window:

![image](https://user-images.githubusercontent.com/77178604/104128543-32997c80-5379-11eb-85c6-647d0cdc351c.png)

Now, resize the window:

![image](https://user-images.githubusercontent.com/77178604/104128565-56f55900-5379-11eb-9fd3-bf8d28722976.png)

If run with kivy1.11.1 it behaves correctly:

![image](https://user-images.githubusercontent.com/77178604/104128585-8e640580-5379-11eb-9d39-19fdcc13b609.png)

**Comment by matham** [comment]
It works ok for me on Windows with master (which should be the same as 2.0.0 mostly).

Also, strictly speaking, `size: self.texture_size` doesn't do anything because the size is set by the window since the size hints are not set.

**Comment by pythonic64** [comment]
Works as expected on Windows 10 with Kivy `2.1.0rc1`. @hscpy Can you re-test with `2.1.0rc1`?
