### ISSUE TITLE
CheckBox in RecycleView viewclass appears to change state during window resize

### ISSUE THREAD

**Issue by stevewells20** [kivy/kivy#7327]
**Software Versions**
* Python: 3.6
* OS: Ubuntu 18.04
* Kivy: 2.0.0
* Kivy installation method: pip install via PyCharm

**Describe the bug**
A RecycleView has a viewclass containing a checkbox. If a checkbox is in 'down' state, resizing the window horizontally will cause the toggled checkbox to appear untoggled, and a different checkbox in the Recycleview to become toggled. This effect oscillates as the window continues to be resized, with the checkbox that is currently toggled changing back and forth between the original one toggled and a different one.

**Expected behavior**
I expect the orginal checkbox to retain its state during a window resize.

**To Reproduce**
Run the following minimal example.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.recycleview import RecycleView
from kivy.uix.recycleview.views import RecycleDataViewBehavior
from kivy.properties import BooleanProperty, StringProperty
from kivy.uix.boxlayout import BoxLayout

Builder.load_string('''
<SelectableLabel>:
    id: programEntry
    orientation: 'horizontal'
    active: accessCheckBox.active
    CheckBox:
        id: accessCheckBox
        active: programEntry.active
        on_active: print(f"{programEntry.text} {accessCheckBox.state}")
    Label:
        text: programEntry.text

            
<RV>:
    viewclass: 'SelectableLabel'
    RecycleBoxLayout:
        default_size: None, dp(56)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'

''')


class SelectableLabel(RecycleDataViewBehavior, BoxLayout):
    ''' Add selection support to the Label '''
    text = StringProperty()


class RV(RecycleView):
    def __init__(self, **kwargs):
        super(RV, self).__init__(**kwargs)
        self.data = [{'text': str(x)} for x in range(100)]


class TestApp(App):
    def build(self):
        return RV()


if __name__ == '__main__':
    TestApp().run()
```

**Additional context**
I understand that this is likely caused by the way that RecycleViews reuse Widgets, but this is a pretty big pitfall for people who expect consistent statefullness. The solution to this bug is likely just better documentation for RecycleViews, and maybe a big disclaimer that says "Your Widgets will be reused in RecycleViews, please keep all state changes in the RV.data structure".

**Comment by matham** [comment]
As you say, this needs to be documented more clearly. So a doc PR showing this kind of issue (with a minimum example) is welcome.

**Comment by stevewells20** [comment]
Thank you for the quick response. I'll look making a PR for it.

**Comment by stevewells20** [comment]
Still working on the wording and format for this. Is best practice in Kivy for keeping state of RV viewclass widgets to store state changes in the RV.data list? That's what I've always done, but I'd like to make sure it is inline with recommended usage.

**Comment by matham** [comment]
What you're describing, storing it in `data`, is the reccomended way, in as much as we have a reccomendation.

The alternative is using a custom view class, but you'd still have to store something in `data` to keep track of the state to restore.

Maybe in the long term we can investigate alternate ways to restore certain properties when the a view is reused.

**Comment by stevewells20** [comment]
I think with the approved documentation PR: #7328, this issue can be closed.

**Comment by Ratulhasan14789** [comment]
keeping track on the checkbox still didn't help me
used a loop over the RecycleBoxLayout.children to recover the state, still its selecting some other child from the screen :-/
any update or help??
