### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by Kanfit** [kivy/kivy#7331]
Any reason kivy doesn't have tooltip? Yes, can be done using a workaround. Would be nice to have tooltip as a standard feature.

**Comment by matham** [comment]
This is a duplicate of https://github.com/kivy/kivy/issues/6717

**Comment by pythonic64** [comment]
Feature #7658 enables writing of hover behavior and that's not far from tooltip behavior mixin. 

You can find working hover event manager and hover behavior at https://github.com/pythonic64/hover.
