### ISSUE TITLE
Feature Request: Embedding webpages

### ISSUE THREAD

**Issue by Python3-8** [kivy/kivy#7335]
# Is your feature request related to a problem? Please describe.
I'm planning on making an app that displays a webpage (a whole site, with all routes, e.g., if a button takes you to a page at website.com/example/ that webpage should show up) but there doesn't seem to be native support.

What I mean is,
If I display a webpage at `mydomain.com` (something like `WebpageWidget(url='mydomain.com')`) and that page has a button that takes you to `mydomain.com/about-us`, the widget should display the about us page when the button is clicked. The widget shouldn't always display `mydomain.com`.

# Describe the solution you'd like
I would like it if you could create widgets called something like `HTMLWidget` (where you could render HTML) and `WebpageWidget` where you could provide a URL and have the page rendered).

# Describe alternatives you've considered
I've tried CEF Python (`cefpython`) but it's not maintained well.

![Screen Shot 2021-01-17 at 5 11 01 PM](https://user-images.githubusercontent.com/66139317/104858924-1bfaa480-58e8-11eb-9bd9-1e38e377e74c.png)

# Additional context
Something like this:

![IMAGE 2021-01-17 16:55:42](https://user-images.githubusercontent.com/66139317/104858447-d7b9d500-58e4-11eb-8a48-c91877cadd30.jpg "Example of my request")

**Comment by tshirtman** [comment]
This is hard to do in a portable way, we don't plan on impleminting a web rendering engine in kivy, that's a task way beyond the scope of this project. some platform specific solutions are possible, like CEF python, or using a native web view as an overlay in android, but it'll not be integrated as any other widget, it would always be at the top of the application. 

I wouldn't hold my breath for a solution for this to come natively into kivy.

**Comment by Python3-8** [comment]
So is Flutter the only cross-platform option?

**Comment by Python3-8** [comment]
> So is Flutter the only cross-platform option?

I guess yes lol. I now use Flutter for almost every app

**Comment by Sahil-pixel** [comment]
Kivy webview widget  is needed . It will make kivy more powerful and versatile.
