### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by MKdays** [kivy/kivy#7340]
This is about the license when the EXE file was packaged by Pyinstaller.
Everyone here would want to create their own exclusive license app free of GPL.
But like other GUI frameworks, there is still a GPL license.

### docutils
> https://github.com/docutils/docutils/blob/master/docutils/COPYING.txt
> public domain, Python, 2-Clause BSD, GPL 3

docutils is like Kivy required item. Can't we exclude it?

### gstreamer (if used)

> https://github.com/GStreamer/gstreamer/blob/master/COPYING
> GPLv2

I want to check whether I used gstreamer or not. What is the name of the dll file?

### libmpg123-0.dll

> http://hg.libsdl.org/SDL_mixer/file/b0afe341a91d/VisualC/external/lib/x86/LICENSE.mpg123.txt
> LGPL2.1 GPL2

There's a trap here, too. Will clearing libmpg123-0.dll free me from GPL?

### Moblintouch theme's SVG
> https://github.com/kivy/kivy#Licenses
> LGPLv2.1

What is Moblintouch theme's SVG? Is this also a dependency source code?

**Comment by tshirtman** [comment]
docutils is not a hard dependency, it's only needed for the rst renderer, moreover, it's mainly public domain, the only gpl-only part is an emacs configuration file, which is not actually used at runtime, as it's an editor configuration provided for the convenience of emacs users, we could probably blacklist that, if someone cares. Everything else has a more liberal license than gpl, even when it's dual licensed with gpl, as you can always use the license that is more convenient for you and disregard the others in that situation.

if you don't need to install kivy-deps.gstreamer to run/package your app then you don't use gstreamer, the dll is named something like libgstreamer-*.dll  i must say i'm less familiar with the old Library GPL (ancestor of the more common Lesser GPL), but it doesn't require your code to be licenced under the GPL or the Library GPL, though it does come with some constraints to be read carefuly if you distribute your program with gstreamer included. As rules of thumb if your application doesn't display any video or play any sound, it doesn't depend on gstreamer, it doesn't need it to run. If your pyinstaller dist folder weights less then 100MB, then it doesn't include gstreamer.

Similarly to gstreamer, you don't need mpg123 if you don't play any sound in your application, and you can probably delete the dll if you don't run any code that needs it at runtime.

Moblin is one of the ancestors of Sailfish OS (https://en.wikipedia.org/wiki/Moblin), it's discontinued, the SVG used for its theme were used to create kivy theme, as far as i know, they were used as the source for the png that you can see in https://github.com/kivy/kivy/tree/master/kivy/tools/theming/defaulttheme and that are used to produce the defaulttheme's atlas (https://github.com/kivy/kivy/blob/master/kivy/data/images/defaulttheme-0.png) which defines how the default widgets look. I don't think the GPL makes much sense for assets, the original SVGs are not distributed with Kivy, so i have actually no idea what that implies for Kivy. You can decide of the look of your widget not to depend on the defaulttheme if that worries you.

**Comment by Zen-CODE** [comment]
@tshirtman Surely this can then be closed?

**Comment by tshirtman** [comment]
Yeah, not sure what ”solved” whoald mean here. Surely there are things we could improve around the licensing of the project and its dependencies, but that should be done in tickets with a clear description of what needs to be fixed.

**Comment by hirokic5** [comment]
By the way, according to this link above (https://github.com/GStreamer/gstreamer/blob/master/COPYING), now gstreamer license is updated to LGPL v2.1.
