### ISSUE TITLE
Attach kivy window to an already running parent window(app)

### ISSUE THREAD

**Issue by rpopovici** [kivy/kivy#7349]
In PySide you can pass a parent window handler to your widget.
I am wondering if something similar is possible with kivy?

To be more precise, I am trying to integrate kivy with blender. Blender already has python integrated and installing kivy in blender local folder works with some limitations and config hacks. I can start the kivy app from blender but everytime I try to close the main kivy window, the blender app closes as well. Any suggestions are welcome.
Thanks

**Comment by ht-thomas** [comment]
I think it's still a little bit ambiguous to trace where the problem could be. But what if you write a code that launches Kivy in a child process from blender as the main process.

**Comment by rpopovici** [comment]
@ht-thomas running kivy from a background thread works on windows and linux but it does not work on mac os, so I had to run kivy app from a subprocess. But the question still remains. Is it possible in kivy to attach the app's window as a child window to another's window?

**Comment by tshirtman** [comment]
I don't think we have any specific support for that, it might be possible, it it might require changes, if someone wants to experiment and propose changes allowing to supporting that, it would probably be accepted unless the change is too intrusive or brittle.

**Comment by ht-thomas** [comment]
> @ht-thomas running kivy from a background thread works on windows and linux but it does not work on mac os, so I had to run kivy app from a subprocess. But the question still remains. Is it possible in kivy to attach the app's window as a child window to another's window?

I've been tinkering around to see if it's possible, but the Kivy's design from ground up seems doesn't support it. Theoretically, there can be work-arounds but they wouldn't be preferable to use. So if it's just a personal thing, you can think of a work-around. But if you're planning to release something like a blender add-on, then It'd be tricky

**Comment by DrSpooglemon** [comment]
I don't understand why Window is child of itself. I thought this implied that another window could be child of the main window. Otherwise why does the Window need to have a parent?
