### ISSUE TITLE
Search on kivy.org/doc/stable/ still doesn't work

### ISSUE THREAD

**Issue by HeRo002** [kivy/kivy#7351]
NB! This is not a bug in the kivy software, but on the kivy.org website!

If you go to https://kivy.org/doc/stable/ and enter 'listview' in the search box you get essentially nothing. But if you go to Google and say 'site:kivy.org listview' you get 168 hits. 
'site:kivy.org/doc/ listview' gets 162 hits.

So there is still something wrong with the search function.

**Comment by HeRo002** [comment]
OK... I can see now that ListView has been deprecated and that you should use RecycleView instead. But a new user doesn't necessary now that, so it would be nice if searching for ListView DID return a doc page, which then informs about using RecycleView instead... :-)

**Comment by Julian-O** [comment]
Should be moved to kivy/kivy-website

**Comment by misl6** [comment]
> OK... I can see now that ListView has been deprecated and that you should use RecycleView instead. But a new user doesn't necessary now that, so it would be nice if searching for ListView DID return a doc page, which then informs about using RecycleView instead... :-)

`ListView` has been removed, not deprecated, during the switch from `1.x.x` to `2.x.x`.

Even if I agree that our docs search (and docs in general) needs to be improved, if the issue only applies to code that has been removed, I would mark it as a WONTFIX, cause this API is not available on the current Kivy stable version.
