### ISSUE TITLE
Can't restart the app after closing the main window. Running kivy in a separate thread

### ISSUE THREAD

**Issue by rpopovici** [kivy/kivy#7352]
**Software Versions**
* Python: 3.7.7
* OS: Win/Mac/Linux
* Kivy: 2.0
* Kivy installation method: pip install --user kivy[base]

**Describe the bug**
Trying to restart the application doesn't work. I am running kivy from a separate thread.

**Expected behavior**
You should be able to reload the app after you closed the main window without killing the main thread

The workaround proposed here https://groups.google.com/g/kivy-users/c/yfhH7skAEJA  is not working in kivy 2.0..

```
def reset():
  import kivy.core.window as window
  from kivy.base import EventLoop
  if not EventLoop.event_listeners:
      from kivy.cache import Cache
      window.Window = window.core_select_lib('window', window.window_impl, True)
      Cache.print_usage()
      for cat in Cache._categories:
          Cache._objects[cat] = {}

# run multiple times
reset()
TestApp().run()
reset()
TestApp().run()
...
```

**Comment by matham** [comment]
The short answer is that kivy does not support this currently and if you want to do it you should run kivy in a second process.

However, it may be doable depending on your app, but it requires messing with some kivy internals so I cannot recommend it. That said, here's an example of how to do it: https://github.com/matham/pytest-kivy/blob/master/pytest_kivy/app.py#L90.
