### ISSUE TITLE
Change screen co-ordinate system to top-left corner

### ISSUE THREAD

**Issue by AjayrajSingh** [kivy/kivy#7354]
Getting shifted from other mobile frameworks like: React Native and Flutter, it's difficult for me to work with bottom-left co-ordinate system. Is there any way to alter this, or anything I can do to change it for all my projects (by changing on kivy source or anything...).
If it could be possible then, place it as a feature in Kivy if possible.

**Comment by tshirtman** [comment]
I think it's unrealistic to make that a configuration option in kivy, or even to update the source manualy to make that change, it's a lot of work for no gain. What problems are you getting from this coordinate system? It shouldn't take a long time to get used to the idea that positive is up, negative is down.

**Comment by AjayrajSingh** [comment]
Suppose I want to display lets say label on the very top of the screen so for that maybe I need to make the position_hint property set to 0.0 on the x direction and 1.0 to the y direction, But the label co-ordinates are also counted from bottom left so in this case the label will not be shown on the screen because its sitting on top of the upper bound of the screen.

**Comment by matham** [comment]
As @tshirtman said it's unrealistic for kivy to change like this now.

Kivy Widgets do have properties to help with this, such as `top` or `right`. Please read the Widget documentation.
