### ISSUE TITLE
How to set size of a widget according to the size of the window so that if I expand the screen then the widget also expand

### ISSUE THREAD

**Issue by JebashTalukdar** [kivy/kivy#7355]

**Comment by JebashTalukdar** [comment]
How to set size of a widget according to the size of the window so that if I expand the screen then the widget also expand

**Comment by AjayrajSingh** [comment]
Use size_hint property

**Comment by JebashTalukdar** [comment]
> Use size_hint property

I know but I want that when I expand the screen the size of the widget also increase and when I decrease the size the widget size also decreases
I don't want give a particular size. The size should be based on the screen
