### ISSUE TITLE
Kivy width and height

### ISSUE THREAD

**Issue by JebashTalukdar** [kivy/kivy#7361]
How to set the width and height of a widget so that when I expand the screen the size of the widget also increases and when I decrease the size the size of the widget also decreases
Means like this
size_hint=(None,None)
width=self.?
Please help me

**Comment by matham** [comment]
This is the third issue you opened for the same support question. A mentioned we don't handle support here only on discord/mailing list. 

Please don't open further support issues or we may have to ban the account from opening issues.
