### ISSUE TITLE
Allow `get_focus_previous` with `numlock` enabled

### ISSUE THREAD

**Issue by xayhewalo** [kivy/kivy#7364]
**Is your feature request related to a problem? Please describe.**
When `numlock` is enabled, `shift+tab` doesn't call `get_focus_previous` for widgets inheriting `FocusBehavior`

**Describe the solution you'd like**
Change this:
https://github.com/kivy/kivy/blob/ed68be56e4d580b00abd8f89705339e824c3b43d/kivy/uix/behaviors/focus.py#L534-L535
to:
```python
if 'shift' in modifiers:
    next = self.get_focus_previous()
```
or if `ctrl+shift+tab` is undesired:
```python
if 'shift' in modifiers and 'ctrl' not in modifiers:
    next = self.get_focus_previous()
```

If the devs approve, I'll submit a pull request

**Comment by tshirtman** [comment]
That sounds like a fine change indeed, refusing ctrl-shift-tab seems a bit arbitrary, so i would go for the first version, but i don't have a hard opinion either way.

**Comment by matham** [comment]
ctrl-shift-tab, means something different than shift-tab. The former will e.g. cycle through tabs in firefox. So I don't think the focus behavior should use that for tabbing, but leave it of for the user in case they need to cycle tabs or windows or something.
