### ISSUE TITLE
Android Application crashes on keyboard focus

### ISSUE THREAD

**Issue by kengoon** [kivy/kivy#7368]
**Software Versions**
* Python: 3.8.1
* OS: Android
* Kivy: master
* Kivy installation method: Buildozer

**Describe the bug**
Each time I touch TextInput the app crashes with the below error log:

02-06 08:41:42.897 32097 32133 I python  :  Traceback (most recent call last):
02-06 08:41:42.898 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/app/main.py", line 186, in <module>
02-06 08:41:42.900 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/app.py", line 955, in run
02-06 08:41:42.902 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/base.py", line 580, in runTouchApp
02-06 08:41:42.904 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/base.py", line 345, in mainloop
02-06 08:41:42.906 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/base.py", line 389, in idle
02-06 08:41:42.908 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/base.py", line 340, in dispatch_input
02-06 08:41:42.909 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/base.py", line 248, in post_dispatch_input
02-06 08:41:42.911 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.912 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/core/window/__init__.py", line 1426, in on_motion
02-06 08:41:42.914 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.916 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/core/window/__init__.py", line 1462, in on_touch_up
02-06 08:41:42.917 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.919 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/screenmanager.py", line 1215, in on_touch_up
02-06 08:41:42.921 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 567, in on_touch_up
02-06 08:41:42.923 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.924 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/relativelayout.py", line 313, in on_touch_up
02-06 08:41:42.926 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 567, in on_touch_up
02-06 08:41:42.928 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.929 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/screenmanager.py", line 1215, in on_touch_up
02-06 08:41:42.931 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 567, in on_touch_up
02-06 08:41:42.933 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.934 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/relativelayout.py", line 313, in on_touch_up
02-06 08:41:42.936 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 567, in on_touch_up
02-06 08:41:42.938 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.940 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/scrollview.py", line 953, in on_touch_up
02-06 08:41:42.942 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.943 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/scrollview.py", line 990, in on_scroll_stop
02-06 08:41:42.945 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/scrollview.py", line 668, in simulate_touch_down
02-06 08:41:42.947 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 545, in on_touch_down
02-06 08:41:42.948 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.950 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 545, in on_touch_down
02-06 08:41:42.951 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.953 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 545, in on_touch_down
02-06 08:41:42.954 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.956 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 545, in on_touch_down
02-06 08:41:42.958 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.960 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/behaviors/button.py", line 138, in on_touch_down
02-06 08:41:42.962 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivymd/uix/behaviors/ripple_behavior.py", line 254, in on_touch_down
02-06 08:41:42.963 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/widget.py", line 545, in on_touch_down
02-06 08:41:42.965 32097 32133 I python  :    File "kivy/_event.pyx", line 726, in kivy._event.EventDispatcher.dispatch
02-06 08:41:42.967 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/textinput.py", line 1377, in on_touch_down
02-06 08:41:42.968 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/behaviors/focus.py", line 455, in on_touch_down
02-06 08:41:42.970 32097 32133 I python  :    File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
02-06 08:41:42.972 32097 32133 I python  :    File "kivy/properties.pyx", line 525, in kivy.properties.Property.set
02-06 08:41:42.973 32097 32133 I python  :    File "kivy/properties.pyx", line 580, in kivy.properties.Property.dispatch
02-06 08:41:42.975 32097 32133 I python  :    File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
02-06 08:41:42.977 32097 32133 I python  :    File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
02-06 08:41:42.978 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/behaviors/focus.py", line 395, in _on_focus
02-06 08:41:42.980 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/textinput.py", line 2600, in _bind_keyboard
02-06 08:41:42.982 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/behaviors/focus.py", line 413, in _bind_keyboard
02-06 08:41:42.984 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/uix/behaviors/focus.py", line 402, in _ensure_keyboard
02-06 08:41:42.986 32097 32133 I python  :    File "/home/kengo/PycharmProjects/NocenStore/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivy/core/window/window_sdl2.py", line 802, in request_keyboard
02-06 08:41:42.987 32097 32133 I python  :    File "kivy/core/window/_window_sdl2.pyx", line 582, in kivy.core.window._window_sdl2._WindowSDL2Storage.show_keyboard
02-06 08:41:42.989 32097 32133 I python  :  AttributeError: 'org.kivy.android.PythonActivity' object has no attribute 'changeKeyboard'
02-06 08:41:42.989 32097 32133 I python  : Python for android ended.
--------- beginning of crash

**Comment by matham** [comment]
This is due to https://github.com/kivy/kivy/pull/7231. Are you using the latest python-for-android develop branch (i.e. not latest release)? It should be fixed there, since you're using kivy master, I believe. I'm not sure how to select it in buildozer though.

**Comment by kengoon** [comment]
No i use the master branch i will switch to develop and check it out

**Comment by kengoon** [comment]
It works, thanks for your help

**Comment by benkedon** [comment]
I am also getting the same error where the app crashes when I touch the TextInput. Could you tell me what requirements you specified in buildozer.spec to solve this?

**Comment by kengoon** [comment]
@benkedon p4a.branch = develop

**Comment by lumafepe** [comment]
even with p4a.branch = develop I still get the same problem 
![image](https://user-images.githubusercontent.com/54816048/110222918-e75d9f00-7ecd-11eb-9f80-0909a316b240.png)

**Comment by benkedon** [comment]
I got it to work with these requirements specified in buildozer.spec
![delete](https://user-images.githubusercontent.com/78714045/110227599-39df9100-7eb7-11eb-8f30-c2a0bbdd7ae2.JPG)

**Comment by lumafepe** [comment]
> I got it to work with these requirements specified in buildozer.spec
> ![delete](https://user-images.githubusercontent.com/78714045/110227599-39df9100-7eb7-11eb-8f30-c2a0bbdd7ae2.JPG)

i don't use kivymd in this project should did u use TextInput or TextField because even with those requirements still shows the same error.I'm currently using TextInput.
