### ISSUE TITLE
Small bug with overlapping text (mobile)

### ISSUE THREAD

**Issue by zynnboy** [kivy/kivy#7377]
This is a bug I noticed when viewing the website from mobile - just a small issue with overlapping text.

I am on **iOS**, viewing with an iPhone XR. I am aware most viewers will be on desktop, but I wanted to let you know about the visual aspects for mobile viewers.

![IMG-1158](https://user-images.githubusercontent.com/78390950/107673293-dc637600-6c63-11eb-93d6-4e8c12c718ea.PNG)

**Comment by matham** [comment]
The website does indeed need a re-write.

**Comment by Julian-O** [comment]
This should move to kivy/kivy-website.

**Comment by baseplate-admin** [comment]
![image](https://github.com/kivy/kivy/assets/61817579/0466d71f-94ea-497c-b4fa-b6ed28828704)
I cannot reproduce this ( besides the layout changed )

**Comment by Julian-O** [comment]
Thanks @baseplate-admin !

Closing as stale.
