### ISSUE TITLE
TextField is not scrollable on android. It selects text

### ISSUE THREAD

**Issue by kengoon** [kivy/kivy#7381]
**Software Versions**
* Python:3.8
* OS:android
* Kivy:master
* Kivy installation method:buildozer

**Describe the bug**
 whenever i type in series of character that exceed the height of a `textfield` and i want to scroll through it on my android phone, instead of scrolling, it selects the text

**Comment by njk639** [comment]
The default behavior for a text input in Kivy doesn't include scrolling. You could try to implement a solution using a ScrollView and text input box together. Here's a discussion on StackExchange that I found. I haven't tested rhe code, but in theory the approach makes sense to me. https://stackoverflow.com/questions/14117317/kivy-scrollview-implementation-in-textinput

**Comment by Alspb** [comment]
ScrollView solution doesn't work properly, please find the details here: https://github.com/kivy/kivy/issues/7320

**Comment by njk639** [comment]
> ScrollView solution doesn't work properly, please find the details here: #7320
Hmm. I see. Does this happen both when the font size is small and when large relative to the overall text field size? Does it happen if you overwrite the default on_double_tap method to pass?

Neither are a solution, but the might help narrow down one. I'm hoping they will help answer if it 1) behaves properly when the initial tap is on white space, which might be more feasible at different text sizes or 2) if this is a bug with double-tap detection on Android.

**Comment by misl6** [comment]
Fixed via #7610
