### ISSUE TITLE
Is it possible animated.gif use with kivy canvas object ?

### ISSUE THREAD

**Issue by LionReal** [kivy/kivy#7386]
Is it possible animated.gif use with kivy canvas object?

Hi,
I tried to use animated.gif or animated.zip for pong ball but it doesn't work,
is it possible to use animated.gif (or animated.zip) for canvas object?

https://kivy.org/doc/stable/tutorials/pong.html

<PongBall>:
    size : 50,50
    canvas:
        Ellipse:
            pos : self.pos
            size: self.size
            source: 'animated.gif'
            #source: 'animated.zip'

**Comment by Schlaubischlump** [comment]
Can't you use an 'Image' instead ?

Like this:

https://stackoverflow.com/questions/47481540/how-can-i-use-an-animated-gif-that-will-play-when-pressed-as-a-button-in-kivy#47484375

**Comment by matham** [comment]
As suggested above, use an `Image`.
