### ISSUE TITLE
TextInput: on_release doesn't work for selection handles

### ISSUE THREAD

**Issue by Alspb** [kivy/kivy#7396]
**Software Versions**
* Python: 3.8.5
* OS: Linux Mint 20 (based on Ubuntu 20.04 LTS) or Android 10
* Kivy: 2.0.0

**Describe the bug**
For selection handles _on_release_ doesn't work. For that reason bubble is not appearing (see bug https://github.com/kivy/kivy/issues/7247) and selection is not updating (i.e highlighted text != selected text in this case). 

Seems that the problem is that inside _Selector.on_touch_down_ touch has coordinates relative to the window, while self (handle) has coordinates relative to its TextInput widget, so self.collide_point(*touch.pos) always returns False.

Simple workaround is to set always_release=True for Selector. But the mismatch between touch and handle coordinates still influences: bubble now appears, but not exactly at the place where it should be.

**Comment by misl6** [comment]
Fixed by #7621
