### ISSUE TITLE
"Unable to find any valuable window provider" when building via Windows 10 pyinstaller

### ISSUE THREAD

**Issue by n2qzshce** [kivy/kivy#7400]
**Software Versions**
* Python: 3.7.0
* OS: Windows 10 Pro 20H2
* Kivy: 2.0.0
* Kivy installation method: Installation via pip 19.0.3

**Describe the bug**
Unable to build this project using pyinstaller. The application runs correctly when launched as a python application, but when built via pyinstaller, the application returns the following stacktrace:
```
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - Exception: SDL2: Unable to load image
  File "kivy\core\__init__.py", line 70, in core_select_lib
  File "kivy\core\window\window_sdl2.py", line 152, in __init__
  File "kivy\core\window\__init__.py", line 982, in __init__
  File "kivy\core\window\window_sdl2.py", line 311, in create_window
  File "kivy\core\window\__init__.py", line 1268, in create_window
  File "kivy\graphics\instructions.pyx", line 783, in kivy.graphics.instructions.RenderContext.__init__
  File "kivy\core\image\__init__.py", line 561, in __init__
  File "kivy\core\image\__init__.py", line 756, in _set_filename
  File "kivy\core\image\__init__.py", line 460, in load
  File "kivy\core\image\__init__.py", line 223, in __init__
  File "kivy\core\image\img_sdl2.py", line 47, in load
```

**Expected behavior**
Kivy application should launch

**To Reproduce**
run `pyinstaller ./radio_sync_gui.py --clean -F` and then launch the application with this repo:
https://github.com/n2qzshce/ham-radio-sync/tree/gui

**Additional context**
I have tried adding in kivy-deps manually: angle, sdl2, gstreamer, pyenchant, opencv-python... and none of them appeared to fix this issue.

When trying the latest master (`de520e6` at time of writing this), I encountered the following error during pip install:
```
C:\Users\user\AppData\Local\Programs\Python\Python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
```

**Comment by pythonic64** [comment]
Did you follow the instructions from https://kivy.org/doc/stable/guide/packaging-windows.html ?

**Comment by n2qzshce** [comment]
@pythonic64 Yes, I tried that and it didn't work.

**Comment by matham** [comment]
There's nothing we can really do about this because it's almost certainly either something wrong with how you packaged kivy, or less likely something with pyinstaller. I'd recommend to build the test kivy project from the docs following it exactly and see if the issue goes away. Either way though this is not something we can help with here on Github, unless it's a clear bug. Instead Discord is a better place to ask for help.

**Comment by n2qzshce** [comment]
@matham  I was able to get it working. Turns out, when building from the command line it was stomping the spec file each time. I created the spec then changed my build command to use the spec file, and now it's working.
