### ISSUE TITLE
TypeError: run() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by Saad-py** [kivy/kivy#7407]
Hi, 
It has been a long time since I came back to kivy, I decided build a project that used pandas and is related to chemistry.
But I started by making normal classes and if main stuff but I there was an error
```


[INFO   ] [Logger      ] Record log in C:\Users\Ahmer Khan\.kivy\logs\kivy_21-03-08_1.txt
INFO:kivy:[Logger      ] Record log in C:\Users\Ahmer Khan\.kivy\logs\kivy_21-03-08_1.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
INFO:kivy:[deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
INFO:kivy:[deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
INFO:kivy:[Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Python37\lib\site-packages\kivy\__init__.py"
INFO:kivy:[Kivy        ] Installed at "C:\Python37\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
INFO:kivy:[Python      ] v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Python37\python.exe"
INFO:kivy:[Python      ] Interpreter at "C:\Python37\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
INFO:kivy:[Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
INFO:kivy:[Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
INFO:kivy:[Text        ] Provider: sdl2
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "main.py", line 24, in <module>
WARNING:kivy:stderr:   File "main.py", line 24, in <module>
     ChemApp.run()
WARNING:kivy:stderr:     ChemApp.run()
 TypeError: run() missing 1 required positional argument: 'self'
WARNING:kivy:stderr: TypeError: run() missing 1 required positional argument: 'self'




```

My code:
```
import pandas as pd
import numpy as np
from kivy import app
from kivy.uix.gridlayout import GridLayout as grid
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button

class lay(grid):
    def __init__(self, **kwargs):
        super(lay, self).__init__(**kwargs)

        self.add_widget(Label(text="Hello World"))


class ChemApp(app.App):
    def build(self):
        a = lay
        return a

if __name__ == '__main__':
    ChemApp.run()
```

**Comment by pythonic64** [comment]
Change last part to:
```
if __name__ == '__main__':
    ChemApp().run()
```
You have to create instance of the app before you run it.

**Comment by Saad-py** [comment]
What do you mean

**Comment by BrundaBR** [comment]
Creating instance is calling class before running it.
import kivy
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):
    def build(self):
        return Label(text="Helloword")

if __name__=='__main__':
    app=MyApp()
    app.run()


this worked for me!

**Comment by ali-sheykhi** [comment]
> Hi, It has been a long time since I came back to kivy, I decided build a project that used pandas and is related to chemistry. But I started by making normal classes and if main stuff but I there was an error
> 
> ```
> 
> 
> [INFO   ] [Logger      ] Record log in C:\Users\Ahmer Khan\.kivy\logs\kivy_21-03-08_1.txt
> INFO:kivy:[Logger      ] Record log in C:\Users\Ahmer Khan\.kivy\logs\kivy_21-03-08_1.txt
> [INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
> INFO:kivy:[deps        ] Successfully imported "kivy_deps.glew" 0.1.12
> [INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
> INFO:kivy:[deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
> [INFO   ] [Kivy        ] v1.11.1
> INFO:kivy:[Kivy        ] v1.11.1
> [INFO   ] [Kivy        ] Installed at "C:\Python37\lib\site-packages\kivy\__init__.py"
> INFO:kivy:[Kivy        ] Installed at "C:\Python37\lib\site-packages\kivy\__init__.py"
> [INFO   ] [Python      ] v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
> INFO:kivy:[Python      ] v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
> [INFO   ] [Python      ] Interpreter at "C:\Python37\python.exe"
> INFO:kivy:[Python      ] Interpreter at "C:\Python37\python.exe"
> [INFO   ] [Factory     ] 184 symbols loaded
> INFO:kivy:[Factory     ] 184 symbols loaded
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
> INFO:kivy:[Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
> [INFO   ] [Text        ] Provider: sdl2
> INFO:kivy:[Text        ] Provider: sdl2
>  Traceback (most recent call last):
> WARNING:kivy:stderr: Traceback (most recent call last):
>    File "main.py", line 24, in <module>
> WARNING:kivy:stderr:   File "main.py", line 24, in <module>
>      ChemApp.run()
> WARNING:kivy:stderr:     ChemApp.run()
>  TypeError: run() missing 1 required positional argument: 'self'
> WARNING:kivy:stderr: TypeError: run() missing 1 required positional argument: 'self'
> ```
> 
> My code:
> 
> ```
> import pandas as pd
> import numpy as np
> from kivy import app
> from kivy.uix.gridlayout import GridLayout as grid
> from kivy.uix.label import Label
> from kivy.uix.textinput import TextInput
> from kivy.uix.button import Button
> 
> class lay(grid):
>     def __init__(self, **kwargs):
>         super(lay, self).__init__(**kwargs)
> 
>         self.add_widget(Label(text="Hello World"))
> 
> 
> class ChemApp(app.App):
>     def build(self):
>         a = lay
>         return a
> 
> if __name__ == '__main__':
>     ChemApp.run()
> ```

instade of ChemApp.run() write **ChemApp()**.run()  you **forgot** the () for the class itself
