### ISSUE TITLE
Support for multiple windows on Windows 10 / MacOS

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [kivy/kivy#7412]
**Is your feature request related to a problem? Please describe.**
I am creating different types of software with **Kivy** and some of them I would prefer to use multiple windows for settings for example.

**Describe the solution you'd like**
Ability of creating multiple windows inside the main App class like you can do in _Tkinter_ for example.

**Describe alternatives you've considered**
If I absolutely need it, I just create two python files and one launches another one, then when compiling, I just compile both and place in the same folder

**Comment by matham** [comment]
I'm afraid this just isn't something we ever plan to implement. The suggested approach is to use subprocess/multiprocess to start another kivy window and use a queue or pipes to communicate between them.

**Comment by AndiEcker** [comment]
Looks like there were plans in the past to support multiple windows - e.g.
at least within Kivy's `ModalView` there is the _search_window method
<https://github.com/kivy/kivy/blob/fec099e6ecf19365d54086c8c42e33ae3c028744/kivy/uix/modalview.py#L189>
using the Widget methods `get_parent_window` and `get_root_window` which
are "climbing" up the widget tree to find *a* window instance and only if
not found it will use the main window instance (kivy.core.window.Window).

But if there are no plans for the near future to support multiple windows,
I'd like to make a PR to speedup and simplify the code by removing the
`_search_window` method of ' ModalView'  and change the only usage of this
private method (in the 'open' method) to something simpler like e.g.::
`self._window = Window`.

Am So., 14. März 2021 um 19:06 Uhr schrieb matham ***@***.***

**Comment by matham** [comment]
>`self._window = Window`.

I think that's a fair change given that there isn't likely to be multiple windows in the near or far future. Unless I'm missing something about modal @tshirtman ?
