### ISSUE TITLE
'Input_type' from Focus Behavior doesn't work

### ISSUE THREAD

**Issue by DAMIAN-Adol** [kivy/kivy#7413]
**Software Versions**
* Python: 3.8.5
* OS: Ubuntu 20.04 , Android 9, Samsung 
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
How should I use the `'input_type'` method now?

In the documentation it says it no longer inherits from the `TextInput` widget, **now specifies that it inherits from** `FocusBehavior`.

[`FocusBehavior.input_type` here] (https://kivy.org/doc/stable/api-kivy.uix.behaviors.focus.html#kivy.uix.behaviors.focus.FocusBehavior.input_type)

I tried this ...

**Code and Logs and screenshots**
```python

from kivy.app import App
from kivy.uix.textinput import TextInput

class MyTextInput(TextInput):
    def on_parent(self, widget, parent):
        self.focus = True
        self.input_filter='float'
        self.input_type= 'number'

class SampleApp(App):
    def build(self):
        return MyTextInput()
SampleApp().run()
```

**but it doesn't work**

![Screenshot_20200618-135936_Pydroid 3](https://user-images.githubusercontent.com/57909540/85061847-129c3480-b16d-11ea-842b-8119615415c4.jpg)

**Comment by Neizvestnyj** [comment]
I have same bug)

**Comment by matham** [comment]
As mentioned above, it should work with master. But also see https://github.com/kivy/kivy/issues/7337 for additional issues.
