### ISSUE TITLE
VideoPlayer - audio get repeated at the end

### ISSUE THREAD

**Issue by BaggioMarco** [kivy/kivy#7416]
**Software Versions**
* Python: 3.9
* OS: windows 10
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
In python 3.9 a video played through the videoplayer, when it reaches almost the end, repeats the audio of the last few seconds a couple of times. This issue doesn't happen on python 3.7.
Watch the video of the issue (you can download it as well): https://drive.google.com/file/d/1U5m68oDY1y6ugPRAn1h8FxaV3FcdnAWn/view

**To Reproduce**
```
from kivy.lang import Builder
from kivy.app import App

KV = '''
Screen:
        
    VideoPlayer:
        source: 'Video1.mp4'
        state: 'play'
        allow_fullscreen: False            
 
'''


class TestVideoPlayer(App):
    def build(self):
        return Builder.load_string(KV)


TestVideoPlayer().run()
```
 
OTHER INFO

```
[INFO   ] [Logger      ] Record log in C:\Users\20180043\.kivy\logs\kivy_21-03-11_19.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\20180043\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\20180043\AppData\Local\Programs\Python\Python39\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 416.94'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1070/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoFFPy   ] Using ffpyplayer 4.3.2
[INFO   ] [Video       ] Provider: ffpyplayer(['video_ffmpeg'] ignored)
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[ERROR  ] [Image       ] Error loading <Video1.mp4>
```

**Comment by matham** [comment]
Can you share the video that you're playing in the screen recording so we can test?

Also, there has been some changes recently in master with regards to video, can you test master?

**Comment by snuq** [comment]
Since the original poster hasn't responded, ill provide a video:
http://www.snuq.com/temp/video.mp4

It seems to happen the most/be the most obvious with uhd videos (get at least 4 stutters), but it happens with pretty much any h264/aac encoded video as well, that example video stutters 3 times for me.

This has definitely been happening on older versions of python and kivy as well, I've been struggling with this issue for a couple years now.  My pull request #6887 does reduce this behavior somewhat by ensuring that the audio/video are in synch, tho it still happens (reduces it to one or two stutters).

Unfortunately, I'm not able to test the latest master, on windows here.

**Comment by BaggioMarco** [comment]
Hi sorry for the delay.
I tested it using the latest master but same problem.

Here you can download the video: https://user-images.githubusercontent.com/72442283/115407008-f97e6d00-a1ef-11eb-97dd-1cd04a2a3011.mp4

thank you in advance

**Comment by BaggioMarco** [comment]
Hi @matham and @snuq do you have some news about this issue? thanks in advance

**Comment by BaggioMarco** [comment]
Hi @matham and @snuq  some news about that? I tried to run the following code (outside kivy) and I have the same issue:
could you help me please? thanks,
```
from ffpyplayer.player import MediaPlayer
import time

filename = r"F:\PYTHON\KivyMD-2.00-python39\TEMPLATE\Video\VideoPlayer_TESTPYTHON3.9\Video1.mp4"

player = MediaPlayer(filename)
val = ''
while val != 'eof':
    frame, val = player.get_frame()
    if val != 'eof' and frame is not None:
        img, t = frame
```

**Comment by Julian-O** [comment]
It is clearly a ffpyplayer issue. Closing.
