### ISSUE TITLE
Cannot close App - Leaving application in progress...

### ISSUE THREAD

**Issue by BaggioMarco** [kivy/kivy#7421]
**Software Versions**

- Python: 3.9
- OS: windows 10
- Kivy: 2.0.0
- Kivy installation method: pip

**Describe the bug**
on python 3.9 I noted that when I  close the app, clicking on the standard "X" icon on the top right corner of the window,
appears th text:

[INFO   ] [Base        ] Leaving application in progress...

but nothing happens, the window doesn't shut down.
If afterwards I click the "X" again, the app freezes.
The only way the close it right now is by closing the related tab of the pycharm IDE.

**Expected behavior**
The app should close.

**To Reproduce**
```python
import kivy
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

def build(self):
return Label(text='Hello world')


if __name__ == '__main__':
MyApp().run()
```

**Comment by matham** [comment]
I'm afraid this is an annoying/surprising pycharm feature. Pycharm keeps the python process alive and drops into the debugger after the app finishes and that keeps kivy alive. Try running it outside pycharm and you'll see the issue goes away.

There is a pycharm option somewhere to turn this off, but I'm not sure where. I found it before though.

**Comment by NikDola** [comment]
- Python: 3.8
- OS: macOS Monterey (M1)
- Kivy: 2.1.0
- Kivy installation method: conda

Facing the 100% exact same problem here and it's driving me nuts. I'm running on Spyder 5.1.5. If there's a fix for this, I'd be really grateful to know about it.
