### ISSUE TITLE
file access errors and accordions not working for me

### ISSUE THREAD

**Issue by dongfanglong2012** [kivy/kivy#7423]
**Software Versions**
* Python :Python 3.9.2
* OS: windows 10
* Kivy: 2.0.0
* Kivy installation method: used the instructions here https://kivy.org/doc/stable/gettingstarted/installation.html#kivy-source-install

**Describe the bug**
I first noticed it when i tried to make a accordion setup. It wouldn't display no matter what example i fallowed. Even if i fallowed the one in the example files it wouldn't display the contents and would have a extra button. If i changed the orientation to horizontal it would all collaps to the corner ignoring anything i tried. Then i noticed all these errors in the console and google has been no  help figuring out what they mean. 

The code im using
https://pastebin.com/zCGm3thH
https://pastebin.com/D1WhUyrt

what it looks like on my end
https://imgur.com/gallery/NnO8fIa

I tried to fallow this video to see what i was doing wrong but nothing

https://www.youtube.com/watch?v=h_5QsY_Es00

i even copied his 100% and i still don't get that result

**Comment by matham** [comment]
I ran your code with master and it looks fine:

```
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.lang import Builder

Builder.load_string("""
<PaperTicketGridLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
		Accordion:
			orientation: 'vertical'
			AccordionItem:
				title: 'New Ticket'
				Label:
					text: "Building Number"
				Label:
					text: "Room Number"
			AccordionItem:
				title: 'New Ticket'
				Label:
					text: "Building Number"
				Label:
					text: "Room Number"
""")

class PaperTicketGridLayout(Widget):
    pass


class PaperTicketApp(App):
    def build(self):
        return PaperTicketGridLayout()

if __name__ == '__main__':
    PaperTicketApp().run()

```

**Comment by dongfanglong2012** [comment]
i tried that but as soon as i posted it there it was deleted with not warning or error or notification.
