### ISSUE TITLE
Compatibility with webdriver (Appium)

### ISSUE THREAD

**Issue by dunossauro** [kivy/kivy#7430]
Webdriver technologies are generally used in mobile or desktop automation work (Basically e2e tests)

A good example is [Appium](https://appium.io/), usually end-to-end testing. It works by automating flow on Android using [ui-automator](https://developer.android.com/training/testing/ui-automator), in iOS using [XCUITest](https://developer.apple.com/documentation/xctest) and in Windows using [WinAppDriver](https://github.com/microsoft/winappdriver)

For comparison, Appium is like [Selenium](https://www.selenium.dev/) for mobile and desktop.

To implement this kind of interaction we have to think of a way to create a webdriver for kivy [W3C Webdriver Specification](https://www.w3.org/TR/webdriver/)

Here we can find the driver implementation used on android https://github.com/appium/appium-android-driver

**Comment by tshirtman** [comment]
This is a feature request. As i see it, it's unlikely to be worked by someone in the team, as we have a lot on our plate already.
If you want to work on it, that's certainly welcome, though there is already [telenium](https://github.com/tito/telenium) to do something similar, there might be some merit in seeing if that specification can give us more interoperability. But unless someone steps up to contribute an implementation, such ticket is likely to stay wishful thinking.
