### ISSUE TITLE
ScrollView: when always_overscroll is enabled and scroll_type is set to 'bars', touches in bar area will be always blocked even when scroll is disabled

### ISSUE THREAD

**Issue by snuq** [kivy/kivy#7456]
**Software Versions**
* Python: 3.8
* OS: Windows 10
* Kivy: 2.0.0
* Kivy installation method: Installer

**Describe the bug**
When a scrollview has always_overscroll enabled, and scroll_type is set to 'bars', touches in the bar area will always be intercepted (not passed to children), regardless of if do_scroll is disabled.

**Proposed solution**
This bug can be fixed by changing lines 711 and 712 (currently) of scrollview.py to:
```python
        width_scrollable = (self.always_overscroll and self.do_scroll_x) or vp.width > self.width
        height_scrollable = (self.always_overscroll and self.do_scroll_y) or vp.height > self.height
```

**Expected behavior**
When do_scroll_x or do_scroll_y is disabled, touches in the horizontal or vertical scrollbar area should not be intercepted.

**To Reproduce**
Run the following code:
```python
from kivy.app import App
from kivy.lang.builder import Builder
KV = """
BoxLayout:
    ScrollView:
        do_scroll_x: True
        do_scroll_y: False
        scroll_type: ['bars']
        bar_width: 40
        Button:
            size_hint: None, None
            height: self.parent.height - 40
            width: 1000
"""
class Test(App):
    def build(self):
        return Builder.load_string(KV)
Test().run()
```
Note that the button will not respond to clicks on the right-side.

**Comment by tshirtman** [comment]
Thanks for the report! can you do a PR with that change? it's simple enough you could do it through github, go to the file and edit it, it'll create a pull request when you save.
This way you get credit for the fix :).

**Comment by matham** [comment]
Presumably the PR fixed it!
