### ISSUE TITLE
[Question] Is it possible to embed a VLC player instance inside a Kivy widget?

### ISSUE THREAD

**Issue by radiolondra** [kivy/kivy#7462]
### Question preamble
Using `python-vlc` and `Tkinter` I can easily do this job in 5 steps (with VLC installed or needed libs in the right paths):

**Step 1**
Simply create a panel, inside the app's main window, where the VLC player will play the video:
```
self.videopanel = ttk.Frame(self.parent)
self.canvas = Tk.Canvas(self.videopanel).pack(fill=Tk.BOTH,expand=1)
self.videopanel.pack(fill=Tk.BOTH,expand=1)
```
**Step 2**
Then create the VLC player:
```
self.Instance = vlc.Instance()
self.player = self.Instance.media_player_new()
```
**Step 3**
set the media I want to play:
```
media = self.Instance.media_new(<whatever local video file path or URL>)
self.player.set_media(media)
```
**Step 4**
set the window's id where to render the VLC player output (_this is the subject of my question_):
```
if platform.system() == 'Windows':
    self.player.set_hwnd(self.videopanel.winfo_id())
else ... # other OSes hwnd setting
```
**Step 5**
and finally play the video inside the videopanel:
`self.player.play()`

## Now the Question
The most important step is `Step 4`, where we `assign the videopanel id to the vlc player hwnd`. 
Can I do the same using Kivy?

**Comment by RobertFlatt** [comment]
All the stuff using OS window handles is probably the wrong way to think about it, as it makes no sense in the context of a widget.
The goal I expect is to write to a Kivy widget's texture.

There are several examples of writing to a texture from different sources in the camera implementations.
https://github.com/kivy/kivy/tree/master/kivy/core/camera
As to the vlc api to get that info, this is not the place to ask.
Enjoy your research.

**Comment by radiolondra** [comment]
> The goal I expect is to write to a Kivy widget's texture.

Yes, me too... if Kivy Video, core and uix, were able to work with `https`, but they aren't.
I would like to write some simple code like the following, but I can't:

```
def play_video2(self):
    with self.canvas.before:
        Color(1, 1, 1)
        self.bg = Rectangle(source="wetubecc.png", pos=self.pos, size=self.size)
    #filename = "bunny.mp4" # >>>> Local file: it works
    #filename = "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" # >>>> http video: it works
    filename = "https://woolyss.com/f/caminandes-1-llama-drama-av1-opus.webm" # >>>> https video: DOESN'T WORK
    self.video = CoreVideo(filename=filename, autoplay='False')
    self.video.bind(on_frame=self.set_bg_texture)

def set_bg_texture(self, *args):
    self.bg.texture = self.video.texture
```

I can't because **https usage gives the following error** :
```
[ERROR  ] [VideoGstplayer] b'Secure connection setup failed.'
[ERROR  ] [VideoGstplayer] b'Internal data stream error.'
[ERROR  ] [VideoGstplayer] b"Stream doesn't contain enough data."
```
This has always happened and noone has been able to tell me why in my previous posts.

I'm not so crazy to start thinking about some alternative if I already had a solution inside Kivy...

And one of the alternatives is VLC, which in TKinter, PyQt, Wx, PySimpleGui, ... is the simplest way to play everything, but Kivy is not able to "expose" the HWND of its widgets in some function, so at least in Kivy this is not applicable. And ther's no way to get frame textures from python-vlc.

Another alternative is ffmpeg and pipelines...
Another is RSTP....
And the extreme is to totally change framework, but this has the big cost of restart all the projects from scratch.

Anyway... many thanks and Happy Easter!

**Comment by matham** [comment]
You can try with ffpyplayer, it works. But you'll have uninstall kivy_deps.gstreamer because its binaries clash with ffpyplayer and disable the https functionality.

**Comment by radiolondra** [comment]
@matham 
Thank you so much! It finally **works fine on Windows (10), MacOS (BigSur) and Ubuntu(18.4)**, even if in Linux I can't play files with **codec AV01**:

`[WARNING] [ffpyplayer] No decoder could be found for codec av1`

Maybe some lib is missed in my box? Even the default installation of VLC on Ubuntu isn't able to play those files. So maybe something is wrong in my box or I need to install some libs... 

Anyway, now at least this code works:

```
import os
os.environ['KIVY_VIDEO'] = 'ffpyplayer'
...

    def play_video2(self):
        with self.canvas.before:
            Color(1, 1, 1)
            self.bg = Rectangle(source="wetubecc.png", pos=self.pos, size=self.size)

        # local file
        #filename = "bunny.mp4"

        # https protocol
        # --------------------->>> Codec tests
        # AV1
        #filename = "https://woolyss.com/f/caminandes-1-llama-drama-av1-opus.webm"
        filename = "https://woolyss.com/f/Chimera-AV1-8bit-480x270-552kbps.mp4"
        # H.264/AVC
        #filename = "https://video.dailymail.co.uk/video/1418450360/2015/02/1418450360_4056782948001_nerdist--1424015378606.mp4"
        # "Theora"
        #filename = "https://upload.wikimedia.org/wikipedia/commons/d/d0/Caminandes-_Llama_Drama_-_Short_Movie.ogv"
        # VP8
        #filename = "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f1/Sintel_movie_4K.webm/Sintel_movie_4K.webm.720p.webm"
        # VP9
        #filename = "https://woolyss.com/f/spring-vp9-vorbis.webm"
        # H.263
        #filename = "https://woolyss.com/f/small.3gp"
        # H.265
        #filename = "https://woolyss.com/f/caminandes-2-gran-dillama-x65-aac.mp4"
        # MPEG-4
        #filename = "https://ossguy.com/sita/Sita_Sings_the_Blues_640x360_XviD.avi"
        #filename = "https://download.blender.org/demo/movies/esign_2_high.qt"
        # ---------------------------------------------------------------------------------

        # http protocol
        #filename = "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
        self.video = CoreVideo(filename=filename, autoplay='False')
        self.video.bind(on_frame=self.set_bg_texture)

    def set_bg_texture(self, *args):
        self.bg.texture = self.video.texture

```
Thank you again. Thanks to you I took a huge step forward.
Have a serene life.

**Comment by matham** [comment]
Great!

About AV1, it's possible the ffmpeg version is too old (only v4.0+ supports AV1 AFAIK). You'd then have to manually compile ffmpeg  with AV1, or perhaps Ubuntu 20 supports it.
