### ISSUE TITLE
Proposal: Change Video Widget to support Placeholder Image

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#7470]
**Is your feature request related to a problem? Please describe.**
When loading videos, a white background is displayed and an error message gets logged that the image cannot be loaded (source is set to the video path actually)

**Describe the solution you'd like**
I want to define a placeholder image if the video is not loaded yet or stopped. This can be then a single frame from the video, some icon or simply a transparent image.

**Describe alternatives you've considered**
As workaround i subclassed ``kivy.uix.video.Video``, introducing a ``video_source`` property, leaving the ``source`` property to my desired placeholder image:

```python
from kivy.uix import video
from kivy.properties import StringProperty
from kivy.resources import resource_find

class Video(video.Video):
    video_source = StringProperty('')

    def __init__(self, **kwargs):
        self._video = None
        super(Video, self).__init__(**kwargs)
        self.fbind('video_source', self._trigger_video_load)

        if "eos" in kwargs:
            self.options["eos"] = kwargs["eos"]
        if self.video_source:
            self._trigger_video_load()

    def _do_video_load(self, *largs):
        if CoreVideo is None:
            return
        self.unload()
        if not self.video_source:
            self._video = None
            self.texture = None
        else:
            filename = self.video_source
            # Check if filename is not url
            if '://' not in filename:
                filename = resource_find(filename)
            self._video = CoreVideo(filename=filename, **self.options)
            self._video.volume = self.volume
            self._video.bind(on_load=self._on_load,
                             on_frame=self._on_video_frame,
                             on_eos=self._on_eos)
            if self.state == 'play' or self.play:
                self._video.play()
            self.duration = 1.
            self.position = 0.

v = Video(source='blank.png', video_source='my_video.mp4')
```

**Additional context**
Implementing this as in the workaround above would be an API break. It would be good if this can be avoided. Therefor we would need to "reroute" some properties, e.g. internally set ``source`` to ``video_source`` and introduce ``placeholder`` which gets mapped to ``source`` before super is called in ``__init__``. Further we would need to add event handlers or alias attributes or similar for this property routing to keep current behavior sane when setting properties from outside. I tested the workaround above only with ffpyplayer video provider, so there might be more implications with concrete core video providers than stated.

in the end, for the API user there should be only one additional property ``placeholder``

```python
v = Video(source=my_video.mp4', placeholder='blank.png')
```

Any feedback or ideas are highly appreciated.

**Comment by tshirtman** [comment]
Currently another workaround user might use would be to lay an image on top of the Video widget, with the desired source, and condition it’s visibility to the absence of texture in the Video widget, (`opacity: 0 if video.texture else 1`) though i’m not against adding this argument to the Video widget.
Another way could be to set the `texture` attribute of the Video to a CoreImage(source).texture, as it’ll be replaced with the texture from the video as soon as it loads, but i didn’t try that.
I’m not against adding the option/property to Video, to avoid these hackish solutions.

**Comment by rnixx** [comment]
> Currently another workaround user might use would be to lay an image on top of the Video widget

This would not solve the issue with having a blank transparent placeholder image, because the white background would be rendered anyway. I simply want to display nothing as placeholder in my case.

> Another way could be to set the texture attribute of the Video to a CoreImage(source).texture

That sounds also possible. maybe this approach can be used in conjunction with introducing a placeholder property.

**Comment by tshirtman** [comment]
> This would not solve the issue with having a blank transparent placeholder image, because the white background would be rendered anyway. I simply want to display nothing as placeholder in my case.

> That sounds also possible. maybe this approach can be used in conjunction with introducing a placeholder property.

Indeed, if you want transparency, defaulting to an empty default texture instead of None would be the only solution, now i think some applications might depend on testing if the texture is None or not, so it wouldn’t be a good idea to change the default value for texture, but introducing a placeholder parameter that would load the texture and set it as the default one if passed would certainly work and be backward compatible.

**Comment by matham** [comment]
I would like to avoid any subtle issues by re-routing because that would not be transparent to user.

How about we add two new properties `preview_source`, `video_source`. Then if the user sets just `source` it is used for both, like currently. If they also set either `preview_source` or `video_source`, the one not set is taken from `source` if that is set. And if both `preview_source` and `video_source` are set, then they are used.

E.g. to disable preview image altogether, you'd only set `video_source`, the others will remain empty.

**Comment by rnixx** [comment]
@matham that sounds pragmatic to me +1
