### ISSUE TITLE
pyinstaller build package but - unable to get any image provider

### ISSUE THREAD

**Issue by ds2k5** [kivy/kivy#7472]
Hi,
using Windows 10 64bit with Python 3.9.4 (64bit) + kivy 2.0

Install:

```
python -m pip install --upgrade pip
python -m pip install pyinstaller
python -m pip install kivy
python -m pip install kivy.deps.gstreamer

```

if I run my python test script like this:

python test.py this works.

then using pyinstaller Version 4.2 to build a onefile-package
the exe I got say "unable to get any image provider"

How to fix this ?

test code: test.py
```


import os
os.environ['KIVY_GL_BACKEND']='angle_sdl2'
import kivy
kivy.require('1.0.6') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()

```

**pyinstaller --clean --onefile test.py**

![Unbenannt](https://user-images.githubusercontent.com/11292286/113984139-0fcd1600-984b-11eb-97f2-4978971a5dfa.PNG)

when running:  python test.py

![Bildschirmfoto_2021-04-08_09-06-59](https://user-images.githubusercontent.com/11292286/113984140-1065ac80-984b-11eb-8a1c-8221211dc002.png)

**Comment by darpan5552** [comment]
Same issue with github actions

I installed all the required libraries in ubuntu runner.
Log shows that kivy detected it.
![IMG_20210711_124210](https://user-images.githubusercontent.com/57829384/125186003-7d6f5080-e245-11eb-8aa7-055d7d6aee0f.jpg)

But when running packaged application, unable to get image provider on my machine
However, if built locally, everything is fine.
