### ISSUE TITLE
FadeTransition increases RAM usage per transition

### ISSUE THREAD

**Issue by Schirink** [kivy/kivy#7478]
**Software Versions**
* Python: 3.9.1 64-bit - venv
* OS: Windows 8.1 64-bit
* Kivy: 2.0.0 master - 2.1.0.dev0
* Kivy installation method: pip with Kivy wheel from kivy[base]

**Describe the bug**

Using a FadeTransition class with the ScreenManager increases the app process RAM usage after each transition. In the example bellow, with the window on default size, RAM usage increased ~= 10.5 MB each time the app changed screens, and this RAM doesn't get freed after the transition ends. I didn't added a clear color or duration to the example transition to keep the sample at a simple state, but on my tests these factors didn't impact the results. This also happens when using Kivy Language
to instantiate the ScreenManager with a FadeTransition. I used Task Manager and Resource Monitor to watch the memory allocation, but I can try this on other resource-monitor softwares, if somebody has a good recommendation. I upgraded Kivy from 2.0.0 to 2.1.0dev0 to check if this would solve the issue, but didn't. This behavior is reproducible with 2.0.0 master, at least in my system.
 
**Expected behavior**

Temporary increase of the app RAM usage due to the processing of the fragment shader, and then that this RAM gets freed after the transition ends.

**To Reproduce**

Sample app based on the demo in *screenmanager.py* :
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.button import Button
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.screenmanager import (
    Screen, ScreenManager, FadeTransition
)

Builder.load_string('''
<Screen>:
    GridLayout:
        cols: 2
        Button:
            text: 'Hello World'
        Button:
            text: 'Hello World'
        Button:
            text: 'Hello World'
        Button:
            text: 'Hello World'
''')

class DebugApp(App):

    def change_view(self, *l):
        self.sm.current = next(self.sm)

    def build(self):
        root = FloatLayout()
        self.sm = sm = ScreenManager(transition=FadeTransition())

        sm.add_widget(Screen(name='test1'))
        sm.add_widget(Screen(name='test2'))

        btn = Button(size_hint=(None, None))
        btn.bind(on_release=self.change_view)

        root.add_widget(sm)
        root.add_widget(btn)
        return root

if __name__ == '__main__':
    DebugApp().run()
```

**Code and Logs and screenshots**

Kivy log, with app running in a venv (I just changed some registries that had personal info):
```
[←[1;32mINFO←[0m   ] [Logger      ] Record log in C:\...\.kivy\logs\kivy_21-04-10_25.txt
[←[1;32mINFO←[0m   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[←[1;32mINFO←[0m   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[←[1;32mINFO←[0m   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[←[1;32mINFO←[0m   ] [Kivy        ] v2.1.0.dev0
[←[1;32mINFO←[0m   ] [Kivy        ] Installed at "C:\...\lib\site-packages\kivy\__init__.py"
[←[1;32mINFO←[0m   ] [Python      ] v3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
[←[1;32mINFO←[0m   ] [Python      ] Interpreter at "C:\...\Scripts\python.exe"
[←[1;32mINFO←[0m   ] [Logger      ] Purge log fired. Processing...
[←[1;32mINFO←[0m   ] [Logger      ] Purge finished!
[←[1;32mINFO←[0m   ] [Factory     ] 189 symbols loaded
[←[1;32mINFO←[0m   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[←[1;32mINFO←[0m   ] [Text        ] Provider: sdl2
[←[1;32mINFO←[0m   ] [Window      ] Provider: sdl2
[←[1;32mINFO←[0m   ] [GL          ] Using the "OpenGL" graphics system
[←[1;32mINFO←[0m   ] [GL          ] GLEW initialization succeeded
[←[1;32mINFO←[0m   ] [GL          ] Backend used <glew>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL version <b'3.1.0 - Build 9.17.10.4229'>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL vendor <b'Intel'>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 3000'>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL parsed version: 3, 1
[←[1;32mINFO←[0m   ] [GL          ] Shading version <b'1.40 - Intel Build 9.17.10.4229'>
[←[1;32mINFO←[0m   ] [GL          ] Texture max size <8192>
[←[1;32mINFO←[0m   ] [GL          ] Texture max units <16>
[←[1;32mINFO←[0m   ] [Window      ] auto add sdl2 input provider
[←[1;32mINFO←[0m   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[←[1;32mINFO←[0m   ] [Base        ] Start application main loop
[←[1;32mINFO←[0m   ] [GL          ] NPOT texture support is available
[←[1;32mINFO←[0m   ] [Base        ] Leaving application in progress...
```

**Additional context**

I will try to check and/or update the OpenGL installation and my video drivers, since this could be some bug on the Intel Graphics 3000 side or in the shading version. I will add an update section if I find something.

If more info or context is needed, I would be glad to provide. Thanks in advance : )

**Comment by matham** [comment]
I don't think it's kivy who is holding on to the RAM, I think the OS is doing it. You can check by running the transition a few times to increase RAM usage, and then let it sit and wait for a few minutes and you should see in task manager that the memory goes back down.

Perhaps `ShaderTransition` can be optimized to re-use the fbo/render context, rather than creating a new one each time.

**Comment by Schirink** [comment]
Hi @matham, thanks for the reply.

> I don't think it's kivy who is holding on to the RAM, I think the OS is doing it.

Interesting. I haven't thought about this possibility before, and it seems the most probable reason for this behaviour. This seemed odd to me because the "movement" transitions (e.g: SlideTransition; CardTransition) behave like I described in  **Expected behaviour** (small increase during transition, then goes back to initial usage), but I guess it's because they don't have to deal with shaders.

I will try to set up an Ubuntu enviroment and check if this is behaviour is reproducible there, to make sure if it's Windows or Python itself the possible culprit.

> You can check by running the transition a few times to increase RAM usage, and then let it sit and wait for a few minutes and you should see in task manager that the memory goes back down.

Strangely, in my system this din't work exactly as you described.

In my system, the sample app starts at ~50.5 MB. Each FadeTransition increases the app RAM usage by ~10.3 MB as I described, but the decrease only happens when the app hits about 120 MB, happening immediately, and it only decreases to about ~72 MB. In my case, this decrease doesn't happen naturally, as I need to hit this threshold of 120 MB to make this happen.

Maybe this really is a problem with my OS, as you stated. Did you used Windows 10 to check the sample app?

> Perhaps ShaderTransition can be optimized to re-use the fbo/render context, rather than creating a new one each time.

That's a great ideia. I can't fully promisse an PR right now, but I will try to take some time to look into the inner-works of the ShaderTransitions and maybe figure out some optimal implementation for them.

Also, would you like me to close this issue, or change something in it? I initially thought this was a bug, but I agree that there's some evidence that this might not be related to Kivy.

**Comment by Julian-O** [comment]
Closing as it doesn't seem to be a Kivy bug.

If new evidence arises, let us know.
