### ISSUE TITLE
Kivy Error

### ISSUE THREAD

**Issue by swasiafouzan** [kivy/kivy#7491]
**Software Versions**
* Python: 3.9.0
* OS:  Windows 10
* Kivy: 2.0.0
* Kivy installation method: pip install kivy

**bug**
When I am importing from kivy.app import App it shows an error in my program that demo = DemoApp()
 NameError: name 'DemoApp' is not defined.

**Code **
from kivy.app import App
from kivy.uix.label import Label

class DemoApp(App):
    def build(self):
        return Label(
            text = "HelloWorld"
            )
    demo = DemoApp()
    demo.run()

**Error**
demo = DemoApp()
 NameError: name 'DemoApp' is not defined.

**Comment by WhileForIf** [comment]
This works for me:
![Schermata da 2021-04-22 10-43-05](https://user-images.githubusercontent.com/81677971/115684576-c1923980-a357-11eb-9b12-a4ef477cca72.png)

**Comment by WhileForIf** [comment]
I think you need to read and follow this doc: https://kivy.org/doc/stable/installation/installation-windows.html

**Comment by swasiafouzan** [comment]
@WhileForIf 
Okay I am trying.
Thanks for the reply.
