### ISSUE TITLE
Run Kivy app on RPi3 & RPi4 (with the same binaries)

### ISSUE THREAD

**Issue by prsousa** [kivy/kivy#7501]
Hi!

I've already posted this issue [here](https://groups.google.com/g/kivy-users/c/5wN4owgZ1N4), but its been 4 months and no one commented, so I decided to post here to see if I'm lucky :smiley:

Me and my colleagues are developing a Kivy application to play some media files.
We already have the application running on some RPis 3 B+, but it would be nice to support the "new" RPi 4 too.
However we are struggling with some "details"...

The base image we are using is the Buster Lite (without desktop env & without X11).
Running the RPi 3 binary (generated with pyinstaller) on RPi 4 results in error, since the EGL is no longer supported on RPi 4.
When I install SDL2 from sources (as recommended on documentation) I can run the app on the development RPi 4 & on the production RPi 3.

However, when I try to execute that same executable on a "clean" image on RPi 4, the app now crashes during startup because it couldn't load the OpenGL / GLES.
Since then I've created a binary in RPi4, and I can run it in a clean image on RPi 4, with `libegl-mesa0` and `libglvnd-dev` installed through `apt`.

Our main goal now is to build a single binary to be distributed in a single deb package (targeting both RPi4 and RPi 3).

Can help us, please?
Any suggestions are very welcome :slightly_smiling_face:

**Comment by RobertFlatt** [comment]
A question like this is best asked on Discord https://discord.gg/y8QPS3tu
