### ISSUE TITLE
kivy.uix.Video._on_eos might be called after unoad.

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#7518]
**Software Versions**
* Python: 3.7
* OS: linux
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
When using ffpyplayer based video implementation, it's possible that ``eos`` gets set from frame fetching thread after the video has been unload, which results in an ``AttributeError``, since ``self._video`` gets set to ``None`` in ``kivy.uix.Video.unload``.

**Proposed fix**
Add additional check whether ``self._video`` is set in ``_do_eos`` (https://github.com/kivy/kivy/blob/master/kivy/uix/video.py#L260)

```python
    def _on_eos(self, *largs):
        if not self._video or self._video.eos != 'loop':
            self.state = 'stop'
            self.eos = True
```

Any objections? Otherwise i'd create a PR for this.

**Comment by matham** [comment]
Yeah, that seems to make sense.
