### ISSUE TITLE
Numeric keyboard Kivy 2.0.0

### ISSUE THREAD

**Issue by tahakalaee** [kivy/kivy#7519]
**Software Versions**
* Python: 3.8.5
* OS: android
* Kivy:2.0.0
* Kivy installation method: pip

How can I display a numeric keyboard using Kivy==2.0.0 and kivyMD? I set input_type:'number', input_filter:'int' and multiline:False in textfield but when I run apk on android device app displays only full character keyboard. Better mention that buildozer couldn't download sdl2 files and I manually replaced them.
sdl2==2.0.9
sdl2_image==2.0.4
sdl2_mixer==2.0.4
sdl2_ttf==2.0.15

**Comment by matham** [comment]
You need to use kivy/py4a master.
