### ISSUE TITLE
TypeError: Cannot convert kivy.properties.NumericPropertyStorage to kivy.properties.BoundedNumericPropertyStorage

### ISSUE THREAD

**Issue by olek5andr** [kivy/kivy#7540]
Python == 3.7.6
kivy == 2.1.0.dev0
KivyMD == 0.104.2.dev0

App crashes after updating from kivy == 2.0.0 to kivy == 2.1.0.dev0.
On kivy==2.0.0 the app runs PERFECTLY on mac, but lags extensively on an Android device. That's the main reason behind updating to kivy master.

The Error message:

```
kivy.lang.builder.BuilderException: Parser: File "<inline>", line 16:
 ...
      14:    size_hint: None, None
      15:    height: dp(20) + lbl_txt.texture_size[1]
 >>   16:    width: lbl_txt.texture_size[0] + dp(24)
      17:
      18:    MDLabel:
 ...
 TypeError: Cannot convert kivy.properties.NumericPropertyStorage to kivy.properties.BoundedNumericPropertyStorage
```

Many thanks in advance!

**Comment by matham** [comment]
This is a bug in KivyMD. See https://github.com/kivy/kivy/issues/7398#issuecomment-800550183. I'm not sure if KivyMD has a bug opened for this (or maybe it's already fixed), if not you should open one there.
