### ISSUE TITLE
Kivy / virtual keyboard not allowed, single mode, not docked

### ISSUE THREAD

**Issue by thevikramsethi** [kivy/kivy#7542]
Is there something wrong in my code as the window is not opening after running?

`import` kivy
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.gridlayout import GridLayout
from kivy.uix.textinput import TextInput

class MyGrid(GridLayout):
    def __init__(self, **kwargs):
        super(MyGrid, self).__init__(**kwargs)
        self.cols = 2
        self.add_widget(Label(text="name:   "))
        self.name = TextInput(Multiline=False)
        self.add_widget(self.name)

        class MyApp(App):
            def build(self):
                return MyGrid()

            if __name__=="__main1__":
                MyApp().run()``

**Comment by RobertFlatt** [comment]
Add the widgets after the layout class is initialized, and it is 'multiline' not 'Multiline'

In future please address usage questions to the user groups (Google groups or Discord) this forum is for development issues.

**Comment by Tanishq858-byte** [comment]
same problem .

**Comment by zlwcaptain** [comment]
在if那里是是'__main__' 而不是’__main1__‘我有过类似的问题，希望可以帮到你
