### ISSUE TITLE
How fix the `STATUS_ACCESS_VIOLATION` error

### ISSUE THREAD

**Issue by onsunsl** [kivy/kivy#7558]
**Software Versions**
* Python: python 3.6.6
* OS: windows7
* Kivy: 1.11.1
* Kivy installation method: pip install kivy==1.11.1

**Describe the bug**
I've got an exception in windows7 that App package by pyinstaller.  The exception code is `0xc0000005(STATUS_ACCESS_VIOLATION)`. How I can get some log form `context_instructions.cp36-win32.pyd`. The main process crashed directly when an exception occured and there is no python log and python exception in console.

* Hare is Windows exception event log:
```log
Fault Moudle Name: context_instructions.cp36-win32.pyd，version: 0.0.0.0，Timestamp: 0x5d0bd8fb
Exception Code: 0xc0000005  
Exception Offset: 0x00029be4
Error Process ID: 0x125c
Application Timestamp: 0x01d764e39632579c
````

**Comment by Julian-O** [comment]
Windows 7 and Kivy 1.11.1 and Python 3.6 are all stale.

Closing as stale, but if the problem is still occurring, please let us know with more details.
