### ISSUE TITLE
Kivy.app packaging gives SSL errors on downloading

### ISSUE THREAD

**Issue by sanderland** [kivy/kivy#7562]
**Software Versions**
* Python: 3.x
* OS: MacOSX
* Kivy: 2.0
* Kivy installation method: https://github.com/sanderland/katrain/blob/master/.github/workflows/osxbuild.yaml

**Describe the bug**
On Mac, [this](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate) script is needed to install some SLL certificates. However, when packaging a kivy application using the .app, it is not clear how the packaged python can use the system-wide certificates (or fix it's own).
As a result, the exceptions relating to SSL_VERIFY_FAILED appear with appear when downloading anything from the .app

**Comment by mp-007** [comment]
using this doesn't fix your problem?
```
if getattr(sys, 'frozen', False):
    import ssl
    if ssl.get_default_verify_paths().cafile is None and 
        os.environ['SSL_CERT_FILE'] = os.path.join(sys._MEIPASS, 'certifi', 'cacert.pem')
```

**Comment by sanderland** [comment]
> if ssl.get_default_verify_paths().cafile is None and

@mp-007 Looks promising, but your code snippet got cut off

**Comment by mp-007** [comment]
@sanderland  I have took the information here https://github.com/pyinstaller/pyinstaller/issues/6575
Maybe there's no AND in the condition. I have modified my post.

**Comment by mp-007** [comment]
@sanderland. Do you know if my fix it's working?
Here's an other post about this issue:  https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OpenSSL-Certificate

**Comment by misl6** [comment]
Can you confirm (and close the issue if is confirmed) that this issue doesn't occur anymore?
