### ISSUE TITLE
TextInput incorrect behavior: delimiters at the beginning of lines and unlimited scrolling (WITH PROBABLE SOLUTIONS)

### ISSUE THREAD

**Issue by Michael-Ilyin** [kivy/kivy#7566]
**Software Versions**
* Python: 3.7.9
* OS: Win 10
* Kivy: 2.0.0
* Kivy installation method: pip

**Short intro**
I worked with TextInput and I was annoyed by a couple (two) of imperfections (it would probably be wrong to call it full-fledged bugs), which no one seems to have reported in other topics yet. I partially SOLVED these problems, so I want to share my solutions.

**1. DELIMITERS AT THE BEGINNING OF LINES**

**Issue description**
When rearranging text, lines are broken by delimiters incorrectly: when there is no place left for the delimiter, the delimiters is transferred to the start of the next line (spaces or other characters, which shouldn't be there).

![delims_bug](https://user-images.githubusercontent.com/79452760/124299025-a026a880-db65-11eb-8c72-af7ff9cda1eb.png)

**Expected behavior**
The separating delimiters must necessarily carry the last word from the previous line with them, or vice versa - the delimiter must remain on the previous line with the last word on it.

**To Reproduce**
Just resize the textbox until you see

**My solution**
First, inside the **_tokenize** function (line 2309):
```python
        delimiters = u' ,\'".;:\n\r\t'
```
I removed all visible printable characters:
```python
        delimiters = u' \n\r\t'
```
... since the more printable characters there are, the worse the text will look.

Then, in the **_split_smart** function, I added several lines in this piece:

```python
        ...
        allow_spaces = False                            # MY ADDITION (signal to ignore the transferring of space on the first line of a new paragraph)
        # try to add each word on current line.
        for word in self._tokenize(text):
            is_newline = (word == u'\n')
            w = text_width(word, _tab_width, _label_cached)
            # if we have more than the width, or if it's a newline,
            # push the current line, and create a new one
            if (x + w > width and line) or is_newline:
                if not allow_spaces and line and line[0] == ' ' and len(lines) > 0 \
                and len(lines[-1]) > 0 and lines[-1][-1] != ' ':    # MY ADDITION (if the user wants a few whitespaces at the beginning
                    lines[-1] += line[0]                            # MY ADDITION  of NOT the first line of a paragraph, they will get them,
                    line.pop(0)                                     # MY ADDITION  but one space must remain on the previous line.)
                allow_spaces = False                                # MY ADDITION (reset the new paragraph signal)
                lines_append(_join(line))
                lines_flags_append(flags)
                flags = 0
                line = []
                x = 0
            if is_newline:
                flags |= FL_IS_LINEBREAK
                allow_spaces = True                                 # MY ADDITION (do signal that the next line will be the first in a paragraph)
            elif width >= 1 and w > width:
        ...
```

**2. SCROLLING**

**Issue description**
Scrolling of the text canvas was not limited to the top and bottom positions and the canvas was incorrectly shifted by about one line down from the top line, and perhaps there were even cases of the canvas shifting much higher than the last line (nothing was just visible). But the last case happened to me VERY rarely and it is more difficult to reproduce.
However, my first goal was to make mouse wheel scroll by 3 lines (this is kind of a standard for textboxes), because scrolling by 1 line is very uncomfortable. But along the way, I understood that for some reason scrolling was not limited to the upper and lower coordinates.

**Expected behavior**
When scrolling, the text should not go beyond its borders. Also, scrolling with the mouse wheel is best done in 3 lines.

**To Reproduce**
Unfortunately, I cannot accurately reproduce or remember under what conditions the problem occurs (either after resizing, or after deleting the text, or after restarting the textbox, I don’t remember exactly), but I understood for sure that this was happening due to the fact that scrolling was not enough limited.

**My solution**
First, I added a couple of functions to the **TextInput** class for the **on_touch_down** function:

```python
    def get_lines_height(self):
        return (self.line_height + self.line_spacing) * len(self._lines)

    def get_noborder_height(self):
        return (self.height - self.border[0] - self.border[2])
```

And in the **on_touch_down** function, I added several lines in this piece:

```python
        ...
        # Check for scroll wheel
        if 'button' in touch.profile and touch.button.startswith('scroll'):
            # TODO: implement 'scrollleft' and 'scrollright'
            scroll_type = touch.button[6:]
            if scroll_type == 'down':
                if self.multiline:
                    if self.scroll_y > 0:
                        self.scroll_y -= self.line_height * 3                   # MY ADDITION (3 is lines to scroll)
                        if self.scroll_y < 0: self.scroll_y = 0                 # MY ADDITION (just a limiter if the text canvas ran into a minus)
                        self._trigger_update_graphics()
                else:
                    if self.scroll_x > 0:
                        self.scroll_x -= self.line_height
                        self._trigger_update_graphics()
            if scroll_type == 'up':
                if self.multiline:
                    viewport_height = self.height\
                                      - self.padding[1] - self.padding[3]
                    text_height = len(self._lines) * (self.line_height
                                                      + self.line_spacing)
                    if viewport_height < text_height - self.scroll_y:
                        self.scroll_y += self.line_height * 3                                       # MY ADDITION (3 is lines to scroll)
                        if self.scroll_y > (self.get_lines_height() - self.get_noborder_height()):  # MY ADDITION (just a limiter for the bottom)
                            self.scroll_y = (self.get_lines_height() - self.get_noborder_height())  # MY ADDITION
                        self._trigger_update_graphics()
                else:
                    if (self.scroll_x + self.width <
                            self._lines_rects[-1].texture.size[0]):
                        self.scroll_x += self.line_height
                        self._trigger_update_graphics()
            return True
        ...
```

After such additions, I no longer encountered problems with the canvas running up or down.

**Additional**
After solving the problem №1 (DELIMITERS AT THE BEGINNING OF LINES), as a result, in one place I removed the bug, in another I added :\ - if you place the cursor after the last space left on the previous line, the canvas moves slightly to the right (although it would be good for it not to move at all when using only vertical scrolling). And when there is not enough space on the last line the current typing line before line feeding have a space at the beginning of the line. But after the line feeding, the space goes to the previous line. For me, this is already a small problems. I haven't solved them yet. I can't master all TextInput code yet. For the most part, after these small additions, I have a better looking text than it was.

![textinput_fixed](https://user-images.githubusercontent.com/79452760/124309065-da4a7700-db72-11eb-8d84-bce358ecbc22.gif)

I hope my ideas will be useful, at least partially.

**Comment by akshayaurora** [comment]
@Michael-Ilyin Nice work on finding out and fixing the bugs!

Please convert your observations and bugs fixes into separate [pull requests](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). This way it becomes easier for us to test, review and merge the desired changes/behaviors.

**Comment by Michael-Ilyin** [comment]
@akshayaurora I'm embarrassed to admit it, but in github this is my first issue. Did I understand correctly from the instructions that first I have to create a pull request, and then link issue to it? Or I somehow have to exactly CONVERT issue into pull request? I didn't find anything about converting.

**Comment by akshayaurora** [comment]
Just create a new pull request according to the link posted above, then in it's description just mention `#7566` that will auto link the pr to this issue.

**Comment by Julian-O** [comment]
PR was merged. Closing as complete.
