### ISSUE TITLE
kivy-examples/demo/kivycatalog won't play cityCC0.mpg on mac OS 10.13.6

### ISSUE THREAD

**Issue by rausberg** [kivy/kivy#7567]
Versions:
* Kivy 1.11.1, 2.0.0
* Python: 3.7.3
* OS: Mac OS 10.13.6

Kivy installation method:
* python3 -m venv Kivy
* source Kivy/bin/activate
* pip3 install kivy[full]
* pip3 install kivy_examples

Description of issue:
The catalog demo does not load video providers and does not play the cityCC0.mpg video

Error messages:
[DEBUG  ] [Video       ] Provider <ffmpeg> ignored by config
[DEBUG  ] [Video       ] Provider <ffpyplayer> ignored by config
[DEBUG  ] [Video       ] Provider <null> ignored by config
[CRITICAL] [Video       ] Unable to find any valuable Video provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes

[ERROR  ] [Image       ] Error loading texture ../../widgets/cityCC0.mpg
[DEBUG  ] [ImageImageIO] Load </Users/tor/prj/RP-kivy-tut/venv/share/kivy-examples/widgets/cityCC0.png>

Expected behavior:
The video should play on mac os as it does on Ubuntu 20.04 in VMware Fusion

To Reproduce:
In venv: cd kivy-examples/demo/kivycatalog; python3 main.py

**Comment by misl6** [comment]
Installing the following dependencies should fix the issue:
```
brew install gstreamer
brew install gst-plugins-base
brew install gst-plugins-good
brew install gst-plugins-bad
```

Feel free to reopen the issue if it persists.

**Comment by rausberg** [comment]
Brew is for mac os 10.15 and onwards, may or may not work on 10.13. This system has mac-ports which apparently is a no-go. Outdated I guess.

**Comment by misl6** [comment]
As an alternative, you can install gstreamer from here:
https://gstreamer.freedesktop.org/data/pkg/osx/1.16.2/

**Comment by rausberg** [comment]
gstreamer is available, I have:
gstreamer1 @1.16.2_1 (active)
gstreamer1-gst-plugins-bad @1.16.2_4+x11 (active)
gstreamer1-gst-plugins-base @1.16.2_2+ogg+x11 (active)
gstreamer1-gst-plugins-good @1.16.2_3+gtk3+pulseaudio+qt+x11 (active)

This may come down to a configuration issue or a problem with my setup, who knows. I think we just leave it as it is, no big deal although I don't understand why it works on other platforms...
