### ISSUE TITLE
Camera index=1 no longer works on android 11

### ISSUE THREAD

**Issue by sfornengo** [kivy/kivy#7569]
This morning my mobile (redmi note 9 pro) updated from android 10 to android 11 and my kivy app is now crashing (although worked fine on android 10).

The error is the following:
07-07 20:15:10.026 15463 15493 I python  :  kivy.lang.builder.BuilderException: Parser: File "/data/data/org.test.lipovir/files/app/ui.kv", line 92:
07-07 20:15:10.026 15463 15493 I python  :  ...
07-07 20:15:10.026 15463 15493 I python  :       90:        Camera:
07-07 20:15:10.026 15463 15493 I python  :       91:            id: camera
07-07 20:15:10.026 15463 15493 I python  :  >>   92:            index: root.camera_index
07-07 20:15:10.026 15463 15493 I python  :       93:            play: False
07-07 20:15:10.027 15463 15493 I python  :       94:            resolution: (640,480)
07-07 20:15:10.027 15463 15493 I python  :  ...
07-07 20:15:10.027 15463 15493 I python  :  JavaException: JVM exception occurred: Fail to connect to camera service java.lang.RuntimeException

my kv file:
Widget:
    id: proxy
    Camera:
        id: camera
        index: 1
        play: False
        resolution: (640,480)
        center: self.size and proxy.center
        size: proxy.height, proxy.width
        allow_stretch: True

buildozer.spec:
    requirements = python3, kivy==master
    android.api=30

Any idea 
This was working fine on android 10.
On android 11, index:0 works but not index:1. However my app need the front camera...

**Comment by nadongjin** [comment]
you reslove this problem? 
I Sampe This Problem ㅠㅠ

**Comment by misl6** [comment]
Duplicated of #7732
