### ISSUE TITLE
Recycleview crashes when first movement is done by scrollbar [solution in report]

### ISSUE THREAD

**Issue by canedha** [kivy/kivy#7570]
**Software Versions**
* Python: 3.8
* OS: Win10
* Kivy: 2.0.0
* Kivy installation method:

**Describe the bug**
Recycleview crashes when first movement is done by scrollbar. 
the error occurs, when in scroll.py the line:
self.displacement += abs(val - self.history**[-1]**[1])
is called as history is empty at this point.

**Expected behavior**
no crash

**To Reproduce**
https://github.com/kivy/kivy/blob/master/examples/widgets/recycleview/basic_data.py
populate list and do first movement with scrollbar.

**Solution**
in kinetic.py change line 117:

self.history = [] -> self.history = [(0,0)]

**Comment by purushottam858** [comment]
I am facing similar issue . 
https://groups.google.com/g/kivy-users/c/PlVAMGX5-nQ , if possible please help me here .

How did you handle your issue ?
 IS there any other way to display large number of widgets  in kivy or kivymd ?

**Comment by canedha** [comment]
> I am facing similar issue .
> https://groups.google.com/g/kivy-users/c/PlVAMGX5-nQ , if possible please help me here .
> 
> How did you handle your issue ?
> IS there any other way to display large number of widgets in kivy or kivymd ?

Hi,
2 things:

- I don't think our problems have anything to do with each other. the only common is the use of RV.
- the solution for my problem is in the description. Read and try it. in your link, several people commented but you don't seem to answer or get in dialogue. therefore: read what they wrote, try what they suggest and discuss with them.

one last thing: if your code works with few images, then your code is not broken. i would assume there's a memory issue here and simply too much data. try running it on a more powerful desktop and see if it works in principle...

**Comment by Julian-O** [comment]
@canedha: Tried to reproduce in Kivy 2.2.1, and it worked fine for me.

(Checked, and both scroll.py and kinetic.py have the same lines, but maybe something elsewhere changed.)

Could you please confirm that it is working for you now?
