### ISSUE TITLE
recycleview on android !!!

### ISSUE THREAD

**Issue by purushottam858** [kivy/kivy#7573]
How to display number of widgets with any delay  in android  ?
I want to display the images in the android device , using recycleview . Is there a better way to do it other than recycleview widget ?

Below you can see simple explanation of my code .

when recycle view is called  , it is calling  one function    ( takingper(self) ) to take permissions  and this function calls other function to load images into recycleview . 

 In this case apk is crashing on android just after starting , only blackscreen is displayed for 5 secs .  nothing I found in logs related to recycleview . 

when i tried to display images that are captured only today , In this case apk is taking 15 secs to display the images on the black screen . but it is working fine  , but why 15 secs just to display images . ?

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.recycleview import RecycleView
from kivy.uix.image import Image
from kivy.properties import (
    AliasProperty,
    BooleanProperty,
    BoundedNumericProperty,
    ListProperty,
    NumericProperty,
    ObjectProperty,
    OptionProperty,
    StringProperty,
)
from plyer  import storagepath
from kivy.uix.recycleview import RecycleView
from kivy.uix.recycleview.views import RecycleDataViewBehavior
import glob
from kivy.utils import platform

Builder.load_string('''

<Piccollect>:
    #on_release: app.calll(root.source)

<RV>:

    viewclass: 'Piccollect'
    RecycleGridLayout:
        orientation: 'lr-tb'
        cols: 4
        spacing: ['5dp' , '10dp']
        padding: ['5dp']
        #default_size: None, dp(rv.width/self.cols*.6)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height

''')

class RV(RecycleView):

    def __init__(self, **kwargs):
        super(RV, self).__init__(**kwargs)

        self.takingper()

    def takingper(self):
        # only  Request permissions on Android , not loading images path
        if platform == 'android' :
            from android.permissions import Permission, request_permissions

            def call__back(permission, results):
                if all([res for res in results]):
                    print("Got all permissions>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
                    self.per = True
                    return self.loadaddress()
                    #print("called loadaddress function ======================")

                else:
                    print("Did not get all permissions>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")

            request_permissions([Permission.WRITE_EXTERNAL_STORAGE, Permission.READ_EXTERNAL_STORAGE], call__back)

    def loadaddress(self):

#this piece of code is for formatting the date string as required
            from datetime import date
            # calling the today
            # function of date class
            today = date.today()

            if len(str(today.month)) == 1 :
                self.m = "0" + str(today.month)
            else :
                self.m = str(today.month)

            if len(str(today.day)) == 1 :
                self.d = "0" + str(today.day)
            else :
                self.d = str(today.day)

            self.dddate = str(today.year) + str(self.m) + str(self.d)
            # self.dddate will be 20210709 as todays date is 9/7/2021

            print(str(self.dddate) , "date>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")

        if platform == 'android':
            print("loading....=============================")

            #In this case apk is taking 15 secs to display the images on the screen
            self.data = [{'source': file} for file in glob.glob(f"/storage/emulated/0/DCIM/Camera/IMG_{self.dddate}_*.*")]  #when i want to collect today captured images

            # In this case apk is crashing on android just after starting , only blackscreen is displayed for 5 secs
            #self.data = [{'source': file} for file in glob.glob(f"/storage/emulated/0/DCIM/Camera/IMG_*.*")]     #when i want to collect all the captured images (800 images ) in the device

            print(self.data)
            print(len(self.data))

class Piccollect(Image):
    source = StringProperty('')
    print("created=====================================================")
    def on_touch_down( self, touch ):

        if  self.collide_point( *touch.pos ):
            print("selecting......" , self.source)
            #k.calll(self.source)

class TestApp(App):
    def build(self):
        return RV()

if __name__ == '__main__':
    TestApp().run()

**Comment by purushottam858** [comment]
I have posted this issue in kivy-users group , I was not satisfied with thier answers .
I am unable to figure out this  issue . 
PLEASE , Help me to solve this issue . IN docs it is mentioned that RV widget is completely expermental . So I posted here .

**Comment by tshirtman** [comment]
not only you sent me an unsollicitated email directly to ask for help (which i kindly answered), but you opened multiple issues for support, that's not how it works, we help many people, it's not to get spammed for more help by people thinking they are owed anything, please don't spam, here is for bugs, not support requests.
