### ISSUE TITLE
textinput bug

### ISSUE THREAD

**Issue by SrGambiarra** [kivy/kivy#7576]
**Software Versions**
* Python: 3.9.6
* OS: Windows 10
* Kivy: v2.0.0
* Kivy installation method: pip install kivy

**Describe the bug**
the bug happens when I use multiline: False in TextInput.
the problem is that when I write a lot of text, select everything and press Backspace, the cursor comes back outside the widget.

**Expected behavior**
the cursor must go back within the widget's boundaries

**To Reproduce**
AnchorLayout:
    padding:[200,200,200,200]
    TextInput:
        multiline:False

**Code and Logs and screenshots**
https://youtu.be/fscI9hlh9yw

```python
from kivy.app import App
from kivy.lang import Builder

KV = """
AnchorLayout:
    padding:[200,200,200,200]
    TextInput:
        multiline:False
"""
class Program(App):
    def build(self):
        return Builder.load_string(KV)
if __name__ == '__main__':
    Program().run()
```

**Comment by tshirtman** [comment]
This should be fixed in master already.

**Comment by SrGambiarra** [comment]
Ok, thanks!!
