### ISSUE TITLE
`ScrollView` scroll bug

### ISSUE THREAD

**Issue by Neizvestnyj** [kivy/kivy#7577]
**Software Versions**
* Python: 3.8.5
* OS: All
* Kivy: 2.1.0dev0, 2.0.0
* Kivy installation method: pip

When changing the window size, the widgets in `ScrollView` do not return to their place, a bug appears when setting the `argument effect_cls: "ScrollEffect"`

```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.lang.builder import Builder

KV = """
<FillBoxLayout>
    size_hint_y: None
    canvas.before:
        Color:
            rgba: 0,1,0,1
        Rectangle:
            size: self.size
            pos: self.pos

Screen:
    ScrollView:
        always_overscroll: False
        effect_cls: "ScrollEffect"
        GridLayout:
            id: grid
            size_hint_y: None
            height: self.minimum_height
            spacing: 10
            padding: 10
            cols: 3
"""


class FillBoxLayout(BoxLayout):
    pass


class TestApp(App):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for _ in range(50):
            self.root.ids.grid.add_widget(FillBoxLayout())


TestApp().run()
```

https://user-images.githubusercontent.com/40869738/126224086-59b81b62-250f-4cce-a93c-18686ba62da7.mp4

**Comment by Davidy22** [comment]
I went and pulled the latest dev version to try and fix this, but it seems like this was fixed at some point by another commit. I was even able to reproduce this with the last release kivy, but can't with latest dev version.

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/kivy/pull/7775
