### ISSUE TITLE
The kivy did not work with extend display

### ISSUE THREAD

**Issue by chucklu** [kivy/kivy#7584]
**Software Versions** 
* Python:  3.8.3
* OS: win10 1909
* Kivy: unknown
* Kivy installation method:  by the Katrain program

**Describe the bug**
https://github.com/sanderland/katrain/issues/443

> I have a laptop, and a extend screen.
> Currently I set the extend screen as the main display(display 1), and move the katrain to show on laptop(display 2), it's fine.
> 
> But when I disconnect the extend screen, the katrain is not able to show on laptop(the main display). It seems the katrain take the laptop as the main display, and try to show on another screen(another display). As I only have one screen this time, the katrain just not show.
> It's weird, as other software work fine on my laptop with the extend display. When the extend screen disconnect, they will show on laptop directly.

**Expected behavior**
The program should appear at screen of laptop correctly, when I disconnect the extend display.

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.
Download the Katrain program, and run it with a extend display, move the program window to the extend display, disconnect the extend display. The prorgam will not back to the laptop screen.

**Code and Logs and screenshots**
I did not write the program
```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.
```

**Comment by sanderland** [comment]
Kivy version is 2.0.0, packaged with pyinstaller, though I doubt it matters.
Does SDL give an event for (dis) connecting an external monitor?

**Comment by Julian-O** [comment]
There's not a lot of info here to debug.

**Comment by chucklu** [comment]
After two years, I forgot this, so close it
