### ISSUE TITLE
kivy.properties file is not importable

### ISSUE THREAD

**Issue by orkhanshirin** [kivy/kivy#7586]
**Software Versions**
* Python: 3.6.8
* OS: Oracle Linux
* Kivy: 2.0
* Kivy installation method: pip3

**Describe the bug**
Cannot import kivy.properties as it's file format is .pxd.

**Expected behavior**
It should import the properties.

**To Reproduce**
from kivy.properties import *

lst = ListProperty([])

**Comment by Guhan-SenSam** [comment]
Could have something to do with your IDE

See if any of this helps

#6059
