### ISSUE TITLE
Multiple fonts in one Line

### ISSUE THREAD

**Issue by kmAyushkm** [kivy/kivy#7589]
I am writing a E-mail client app in kivy. In this app when the user is writing the body of the E-mail, one can write it in multiple languages in a single line.
For example: "Hello, ನಮಸ್ತೆ, Good morning, பலம， 才會"
Is there a way to use multi fonts.
I have tried font_name option but it only supports single font..

**Comment by shashi278** [comment]
You can use inline markup to set different font names for different parts of your label. 
Read here: https://kivy.org/doc/stable/api-kivy.uix.label.html#markup-text

**Comment by kmAyushkm** [comment]
Thanks.
What about when user types something in TextInput.

**Comment by Guhan-SenSam** [comment]
What language the user types is entirely upto the user. You need to find a font that is capable of displaying all the languages you intend to support(or combine some fonts externally into a single font file). You can then use this font for the TextInput and if the user has a keyboard capable of inputting these characters, then kivy most likely would display it. Note: There most likely isn't any font capable of displaying a lot of languages together. So you r gng to have to create your own font files

**Comment by kmAyushkm** [comment]
Thanks for your reply.
Is there a possiblity to include more than 1 fonts in TextInput i.e., When user inputs ಅ this letter and this letter is not in first font then TextInput with search for this font in another font.

**Comment by Guhan-SenSam** [comment]
Yes this possible, Check this page from the docs https://kivy.org/doc/stable/api-kivy.core.text.html. You can use a font family to group multiple fonts together

**Comment by kmAyushkm** [comment]
Could you please explain me what is in that webpage.
Cause I couldn't understand it.

**Comment by kmAyushkm** [comment]
Some how managed to understand it.
But how to install pango as it is showing no font_context support in text provider

**Comment by Guhan-SenSam** [comment]
Its in the source code for kivy. The docstrings have the installation procedure in them. I dont exactly know how to install pango as I have never used it before
https://github.com/kivy/kivy/blob/master/kivy/core/text/text_pango.py
 Btw you can join the kivy Discord server
