### ISSUE TITLE
kivy.org https certificate expired

### ISSUE THREAD

**Issue by bitDealer** [kivy/kivy#7590]
**Is your feature request related to a problem? Please describe.**
The website, docs, and all subdomains (e.g. chat.kivy.org) are not loadable with Firefox (and maybe more browsers), because HSTS is activated and the https certificate is expired. In Chrome you'll get a warning and need to manually confirm that you still want to load the ("unsafe") website.

**Describe the solution you'd like**
Renew https certificate

**Comment by tshirtman** [comment]
Thanks for the heads’ up, this is now resolved.
