### ISSUE TITLE
Big square at bottom-left

### ISSUE THREAD

**Issue by IriaSomobu** [kivy/kivy#7595]
**Software Versions**
* Python: 3.8.10 / 3.9.5
* OS: Linux Mint 20.1 / Kubuntu 21.04
* Kivy: v2.0.0 / v2.0.0
* Kivy installation method: pip / pip

**Describe the bug**
A big square appears at bottom-left of nearest container when using widgets with `on_mouse_pos`-derived Behavior. It seems that square has the same color as non-hovered button (eg. color from canvas assigned via `default_style()` method.

**Expected behavior**
I didn't expect any weird squares at all.

**To Reproduce**
I've reduced my project to minimal working exapmple, but it is still quite big (80 loc .py + 40 loc .kv): extract files from [kivy-stange-square.zip](https://github.com/kivy/kivy/files/6964283/kivy-stange-square.zip) and run .py script.

**Code and Logs and screenshots**
| Linux Mint | Kubuntu |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/17745136/128928617-e4836fea-eef8-422c-b79c-d88476ec021e.png) | ![unknown](https://user-images.githubusercontent.com/17745136/128928713-9bdcab70-7b64-4fed-9b73-7c1ab4f68d4c.png) |

**Comment by IriaSomobu** [comment]
I assume this is not a support request as this issue describes erroneous behavior of framework itself, and this is not the request for help in certain situation.

By "erroneous" I mean that this behavior is not stated in documentation (am I wrong?) and one, basing on previous experience, would not expect this "feature" to appear.

**Comment by HyTurtle** [comment]
Its not erroneous - you are calling a method in `__init__` and there you will get default values - pos of (0, 0) and size of (100, 100).

You could `Clock.schedule_once(method, 1)` there which would then have the values you were expecting.

**Comment by IriaSomobu** [comment]
Sorry, this is my bad indeed.
