### ISSUE TITLE
kv language: name is not defined, when name is referenced from a canvas before declaration

### ISSUE THREAD

**Issue by fjansson** [kivy/kivy#7608]
**Software Versions**
* Python: 3.9.6
* OS: Arch Linux
* Kivy: 2.0.0
* Kivy installation method: `python -m pip install kivy[base] kivy_examples`

**Describe the bug**
I'm trying to make an app with sliders controlling the size of a rectangle in a canvas, using the kv language. Please see the example below. If the slider definition appears after the canvas in the kv language string/file, I get `NameError: name 's2' is not defined` where s2 is the id of the slider I reference. Using the slider value in widget properties (i.e. not in a canvas) works as expected.

**Expected behavior**
I'd expect bindings such as `s2.value` for a slider value to be usable in properties also in a canvas, regardless of declaration order. I could not find this issue mentioned in the documentation.

**To Reproduce**

Run the following Python program (I tested 2.0.0 and current master).
```
from kivy.uix.boxlayout import BoxLayout
from kivy.base import runTouchApp
from kivy.lang import Builder

Builder.load_string('''
<TheLayout>:
    orientation: 'vertical'
    Label:
        text: 'Text %4.1f %4.1f'%(s1.value, s2.value)
        font_size: s2.value
        canvas.before:
            Color:
                rgba: 0,.5,1,.5
            Rectangle:
                pos: self.pos
                size: s2.value, s2.value
    Slider:
        id: s1
        size_hint_y: None
        min: 1
        max: 400
    Slider:
        id: s2
        size_hint_y: None
''')

class TheLayout(BoxLayout):
    pass

runTouchApp(TheLayout())

```
My output here:
https://gist.github.com/fjansson/b7381a84a4c14399320da50802e7988e

The only part leading to problems is the use of `size: s2.value, s2.value` in the `Rectangle`. Removing this, or moving the slider s2 to before the `Label` makes it work.

**Comment by marcets** [comment]
canvas before is created before the widget. This can be a workaround:
```
from kivy.uix.boxlayout import BoxLayout
from kivy.base import runTouchApp
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivy.clock import Clock

Builder.load_string('''
<TheLayout>:
    orientation: 'vertical'
    
    Label:
        text: 'Text %4.1f %4.1f'%(s1.value, s2.value)
        font_size: s2.value
        canvas.before:
            Color:
                rgba: 0,.5,1,.5
            Rectangle:
                pos: self.pos
                size: root.s2_value, root.s2_value
    Slider:
        id: s1
        size_hint_y: None
        min: 1
        max: 400
    Slider:
        id: s2
        size_hint_y: None
''')

class TheLayout(BoxLayout):
    s2_value=NumericProperty(0)
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Clock.schedule_once(self._on_start)

    def _on_start(self,*l):   
        self.s2_value = self.ids.s2.value
    

runTouchApp(TheLayout())
```

**Comment by marcets** [comment]
Maybe this example is closer from what are you trying to do:
```
from kivy.uix.boxlayout import BoxLayout
from kivy.base import runTouchApp
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivy.uix.label import Label

Builder.load_string('''
<TheLayout>:
    orientation: 'vertical'
    
    MyLabel:
        s2_value:s2.value
        text: 'Text %4.1f %4.1f'%(s1.value, s2.value)
        font_size: s2.value
        canvas.before:
            Color:
                rgba: 0,.5,1,.5
            Rectangle:
                pos: self.pos
                size: self.s2_value,self.s2_value
    Slider:
        id: s1
        size_hint_y: None
        min: 1
        max: 400
    Slider:
        id: s2
        size_hint_y: None
        min: 1
        max: 400       
''')

class TheLayout(BoxLayout):
    pass

class MyLabel(Label):
    s2_value=NumericProperty(0)
        
runTouchApp(TheLayout())
```

**Comment by fjansson** [comment]
Thank you @marcets, the second example is exactly what I wanted. 

I think I understand, you define a new property in the widget containing the canvas, make the canvas graphics objects use this property, and also bind this new property to the slider. Would it be possible to add this to the documentation, maybe in the section about canvas? At least I couldn't find it.

**Comment by marcets** [comment]
I am not a kivy developper. Just someone using kivy for some projects. If you want to add this the documentation, you can do a pull request or ask a kivy developper on discord (I don't think they have a lot of time to update the documentation).
