### ISSUE TITLE
how do I solve Kivy Launcher recycleview error?

### ISSUE THREAD

**Issue by Batuhank8931** [kivy/kivy#7633]
I have wrote a nice code for a mobile app. Usually I run it on Kivy Launcher and most of the time everything goes well. But recently I have added recycleview and now Kivy Launcher doesnt start my app. I use Logcat. When I run it, it says;

ImportError: No module named recyclerview kivy launcher

my Python version is Python 3.7.0.

I think it is going to fail when I convert it to APK with buildozer as well.

my import line is;

    from kivy.uix.recycleview import RecycleView

How can I solve it ?

**Comment by RobertFlatt** [comment]
https://play.google.com/store/apps/details?id=org.kivy.pygame&hl=en_US&gl=US
says version 1.9.1.1

https://kivy.org/doc/stable/api-kivy.uix.recycleview.html
says added in 1.10.0

which perhaps explains the message.

when you build the apk specify kivy==2.0.0
