### ISSUE TITLE
... but wrong architecture

### ISSUE THREAD

**Issue by Divdude77** [kivy/kivy#7634]
**Software Versions**
* Python: 3.9
* OS: MacOS Big Sur (M1 Chip)
* Kivy:
* Kivy installation method:

Running the most simplest script gives this error:

**Code and Logs and screenshots**
``
[INFO   ] [Logger      ] Record log in /Users/div/.kivy/logs/kivy_21-09-21_45.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/Users/div/Desktop/Python/IndusApp/venv/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:25:35) 
[Clang 12.0.5 (clang-1205.0.22.11)]
[INFO   ] [Python      ] Interpreter at "/Users/div/Desktop/Python/IndusApp/venv/bin/python"
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "/Users/div/Desktop/Python/IndusApp/main.py", line 1, in <module>
     from kivy.app import App
   File "/Users/div/Desktop/Python/IndusApp/venv/lib/python3.9/site-packages/kivy/app.py", line 411, in <module>
     from kivy.base import runTouchApp, async_runTouchApp, stopTouchApp
   File "/Users/div/Desktop/Python/IndusApp/venv/lib/python3.9/site-packages/kivy/base.py", line 28, in <module>
     from kivy.clock import Clock
   File "/Users/div/Desktop/Python/IndusApp/venv/lib/python3.9/site-packages/kivy/clock.py", line 466, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ImportError: dlopen(/Users/div/Desktop/Python/IndusApp/venv/lib/python3.9/site-packages/kivy/_clock.cpython-39-darwin.so, 2): no suitable image found.  Did find:
 	/Users/div/Desktop/Python/IndusApp/venv/lib/python3.9/site-packages/kivy/_clock.cpython-39-darwin.so: mach-o, but wrong architecture
 	/Users/div/Desktop/Python/IndusApp/venv/lib/python3.9/site-packages/kivy/_clock.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Additional context**
Works perfectly well on my other mac which isn't M1. How to fix?

**Comment by pythonic64** [comment]
Try reinstalling Kivy by following instructions from https://kivy.org/doc/stable/gettingstarted/installation.html .
