### ISSUE TITLE
Add git developer documentation 

### ISSUE THREAD

**Issue by frog-o** [kivy/kivy#7646]
**Is your feature request related to a problem? Please describe.**

I have a very slow time getting started with kivy developement.

Such as why ..
Why is a makefile need ?
Why is the makefile calling python command dirrectly and not another python file? 
Why I am I getting and error for inplace build when doing pip install -e .?
Where do i change my config option?
What option are there?

**Describe the solution you'd like**

I would like to see instruction added to the [gettingstarted/installation.html](https://kivy.org/doc/stable/gettingstarted/installation.html#install-pip) for **installation by git** and add a row to the table something like ..

> **Platform** ALL **Installation** git  **Packaging** -

I think a developer documentation would be handy and could answer question like I wrote above ; I also like using the  git command.

>git clone https://github.com/kivy/kivy.git --depth 1

because i running from my pi.

**Describe alternatives you've considered**

Just do what i am doing now trying to  work thought the problem and find answer by reading the code.

**Additional context**

* I was thinking about trying to fix this my self but I don't have much for time and **people working together usually having better ideas**.
* I been reading a lot of issues and trying to work though this problem and wanted to know people thoughts
* You might want to add **documentation improvement** temple  to you list

**Comment by Julian-O** [comment]
This is asking for a general purpose primer of how to develop with Github, Make, Pip, etc.

These guides are available on the web. They are not specific to Kivy alone.
[If you are having trouble with these concepts, Kivy might not be the best playground to learn them.]

Closing as out of scope.
