### ISSUE TITLE
Program freezes by typing in a code input which uses a custom lexer

### ISSUE THREAD

**Issue by nullptr0x** [kivy/kivy#7673]
**2.0.0**
* Python: 3.8
* OS: Windows
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
Program freezes(doesn't responds) when we start typing in a code input which has a custom lexer(handmade, not imported from pygments lib)

**Expected behavior**
Code Input works with lexer

**To Reproduce**
```python
from kivy.lang import Builder
from kivy.app import App

KV = '''
Screen:
    CodeInput:
        lexer: app.lexer
        style_name: "fruity"                           
'''


class MainApp(App):
    def build(self):
        self.lexer = LambdaCodeLexer()
        return Builder.load_string(KV)


if __name__ == '__main__':
    MainApp().run()


# ------ CUSTOM LEXER CLASS-------- #

import re
from pygments.lexer import RegexLexer, bygroups
from pygments.token import Keyword, Comment, String


class LambdaCodeLexer(RegexLexer):
    name = 'LambdaCode'

    tokens = {
        'root': [
            (r"\bimport|func|endfunc|string|if|elseif|while|for|\b", Keyword),
            (r'/\*', Comment.Multiline, 'comment'),
            (r"\/*", Comment.Multiline, 'comment'),
        ],
        'comment': [
            (r'[^*/]', Comment.Multiline),
            (r'/\*', Comment.Multiline, '#push'),
            (r'\*/', Comment.Multiline, '#pop'),
            (r'[*/]', Comment.Multiline)
        ]
    }

```

**Comment by Julian-O** [comment]
While I agree it freezes, this is still a long way from being a bug report on Kivy.

By far the most likely explanation is your lexer is freezing up, taking Kivy with it.
That might be something about the pygments lexer class, it might be something about the way you have configured it. (It might be something about Python's regexp library, but I doubt it!)

You need to do some debugging before raising an issue with Kivy.
