### ISSUE TITLE
uix.Image not sure to pass keep_data=True to its CoreImage

### ISSUE THREAD

**Issue by unjuan** [kivy/kivy#7680]
Comparing with previous `Image`'s code, the problem seems to be the row change of the `super()` call in the `__init__` method and the following (from kivy 1.11 respective code) if added at the end of the method, seems to also fix the problem:

&nbsp;&nbsp;&nbsp;&nbsp;`if self.source:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `update()`

**Comment by Julian-O** [comment]
This isn't enough information to understand the problem or the proposed solution.

Please post some minimal code that demonstrates the problem.
Please confirm you have tried it on Kivy 2.2.1. 
Please tell us what platform and what Python version you are using.
