### ISSUE TITLE
Carousel example not changing slides with swipe 

### ISSUE THREAD

**Issue by BeardyBarber** [kivy/kivy#7681]
**Software Versions**
* Python: 3.8.10
* OS: Linux Mint 20.1
* Kivy: 2.1.0.dev0 (08.11.2021)
* Kivy installation method: Installed from sources from git using pip

**Describe the bug**
After running carousel example [here](https://github.com/kivy/kivy/blob/master/examples/widgets/carousel_buttons.py) I'm not able to use swipe motion to change slides. 

**Expected behavior**
Horizontal swipe motion allows to change slides on carousel widget.

**To Reproduce**
1. Using lastest sources run example [carousel_buttons.py](https://github.com/kivy/kivy/blob/master/examples/widgets/carousel_buttons.py)
2. Use horizontal motion (left/right) to change slides.

 
**Code and Logs and screenshots**
For code reference above links to repo.

https://user-images.githubusercontent.com/20884974/140827737-be6f7041-5e7c-4173-a0f7-b347d70b0eaf.mp4

**Additional context**

**Comment by gottadiveintopython** [comment]
I'm also a Linux Mint user, and the example is working fine here.

- Python 3.8.12
- OS: Linux Mint Mate Edition 20.2
- Kivy: 2.1.0.dev0 43dc1cee8720ef46a383632da34a0bb101b92e02 (2021 Nov 19)
- Kivy installation method: clone the master branch -> build from source

**Comment by BeardyBarber** [comment]
Retested - Working.
