### ISSUE TITLE
Scatter multitouch bug introduced in e8725996ac8cc8d533ba91f1e8325b74928d0b7d

### ISSUE THREAD

**Issue by Lauszus** [kivy/kivy#7685]
**Software Versions**
* Python: 3.8.10
* OS: Ubuntu 20.04
* Kivy: Latest from Github
* Kivy installation method: pip install from local Git repo

**Describe the bug**

After the latest commit to master: https://github.com/kivy/kivy/commit/e8725996ac8cc8d533ba91f1e8325b74928d0b7d scatter interactions does not work properly. Interactions work fine in the commit before that: https://github.com/kivy/kivy/commit/f40dd28ed6614d5e1a972fd5a3eeb99e12fa8578

**Expected behavior**

The scatter widget should rotate and scale child widgets according to the multitouch input.

**To Reproduce**

Run the following code:

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.relativelayout import RelativeLayout


scatter_layout = '''
<ScatterLayout>:
    canvas:
        Color:
            rgb: .8, .8, .8
        Rectangle:
            size: self.size
            pos: self.pos

    Scatter:
        Widget:
            size: 100, 100
            canvas:
                Color:
                    rgb: 1, 0, 0
                Rectangle:
                    size: self.size
                    pos: (root.width - self.width) / 2, (root.height - self.height) / 2
'''


class ScatterLayout(RelativeLayout):
    def __init__(self, **kwargs):
        Builder.load_string(scatter_layout)
        super().__init__(**kwargs)


class ScatterApp(App):
    def build(self):
        return ScatterLayout()


if __name__ == '__main__':
    ScatterApp().run()
```

And then try to interact with the widget either using a touchscreen or by emulating it by pressing middle click on the mouse.

**Code and Logs and screenshots**

Video showing the bug:

https://user-images.githubusercontent.com/1098847/141456713-29ae2360-2888-4728-a2b9-b60ddd193142.mp4

Before the commit it worked as intended:

https://user-images.githubusercontent.com/1098847/141456760-8413ae2e-3b35-4a30-9f09-e4342ae8793a.mp4

FYI the videos does not seem to work in Firefox, but they work fine when using Chrome.

**Comment by pythonic64** [comment]
@Lauszus Thanks for reporting this issue.

Breaking of previous position also broke the delta values (`dx`, `dy`, `dz`). Pull request https://github.com/kivy/kivy/pull/7691 will fix the problem.
