### ISSUE TITLE
Documentation for Label contains Python2-isms

### ISSUE THREAD

**Issue by Zabolekar** [kivy/kivy#7692]
If the appropriate place to report glitches in documentation is somewhere else, please direct me there.

There are the following Python2-isms in the [documentation for Label](https://kivy.org/doc/stable/api-kivy.uix.label.html):

- `unichr` in `l = Label(text=u'Hello world ' + unichr(2764))`
- "It supports ascii and unicode strings" (techincally true though)
-
"Creation of a simple hello world:
`widget = Label(text='Hello world')`
If you want to create the widget with an unicode string, use:
`widget = Label(text=u'My unicode string')`"

**Comment by tshirtman** [comment]
Yes, it's the proper place, thanks for reporting, and even, if you want to directly propose fixes for these things, you can find the source of the doc in the docstring of the classes/modules (for api) and in the rst files in the doc/ directory for the rest of the docs.

E.g for the unichr issue, it's in there:
https://github.com/kivy/kivy/blob/master/kivy/uix/label.py#L14

And you can directly edit it through github to make a pull request that we can approve.
