### ISSUE TITLE
Widget export_as_image() returns empty byte stream on iOS

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy#7694]
**Software Versions**
* Python: 3.8.9
* OS: iOS
* iOS version: 12.5.5
* Kivy: 2.0.0
* Kivy installation method: via kivy-ios toolchain
* Latest OSX Monterey / latest XCode
* 
**Describe the bug**
widget export_as_image() does not work on iOS. It returns an empty byte stream.

**Expected behavior**
export_as_image() should return a PNG byte stream, as observed on other platforms. 

**To Reproduce**
Run the code listed in this issue.

**Code and Logs and screenshots**
```
import io
import kivy

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.clock import Clock
from kivy.app import Builder

KV = """
<MainFrame>:
    orientation: "vertical"
    Button:
        text: "save my image"
        on_press: root._save_me(*args)
    TextInput:
        multiline: True
        id: text
        text: "blah"
"""

class MainFrame(BoxLayout):
    Builder.load_string(KV)
    
    def _save_me(self, instance):
        image = instance.export_as_image()    
        image_data = io.BytesIO()
        image.save(image_data, fmt="png")
        image_data.seek(0)
        data = str(image_data.read())
        
        self.ids.text.text = f"len {len(data)} \n\n header: {data[:100]}"
        
class MyApp(App):
    
    def build(self):
        return MainFrame()

if __name__ == '__main__':
    MyApp().run()
```

**Additional context**
Expected output after pressing button:

![image](https://user-images.githubusercontent.com/3267533/142132870-f189bd15-4279-4520-b6fa-9518ee8d126d.png)

Output on iOS:
![image](https://user-images.githubusercontent.com/3267533/142132893-70ba4657-e73d-4567-8dff-86f21bb5199b.png)

**Comment by misl6** [comment]
The default image providers, (that are needed to save the image) on iOS, are `imageio` and `tex`.
Both doesn't allow saving an image to a `BytesIO` object.

Is a `wontfix` on kivy/kivy, but considering that is a nice feature, maybe we should include `sdl2` as a default image provider on iOS (kivy/kivy-ios). 

Changing:
https://github.com/kivy/kivy-ios/blob/c807e240b558e30bd226519e71813a62ecbb258c/kivy_ios/tools/templates/%7B%7B%20cookiecutter.project_name%20%7D%7D-ios/main.m#L39
to:
`putenv("KIVY_IMAGE=imageio,tex,gif,sdl2");`

Should fix your issue :)

**Comment by brentpicasso** [comment]
That did it, thank you. I will submit a pull request on kivy-ios.
