### ISSUE TITLE
Docs search redirects to wrong addresses, getting 404 Not Found

### ISSUE THREAD

**Issue by yelonek** [kivy/kivy#7697]
Not about Kivy itself.

**Describe the bug**
Search results on the docs website redirect me to non existing addresses.
For example, I search for "button" and in one of the results I get:
`https://kivy.org/doc/stable/api-kivy.uix.buttonundefined?highlight=button#module-kivy.uix.button`
It can be fixed by replacing `undefined` with `.html`.

**Expected behavior**
I should get a correct address.

**To Reproduce**
1. Go to https://kivy.org/doc/stable/
2. Use search function
3. Click on any result

**Code and Logs and screenshots**
![image](https://user-images.githubusercontent.com/370165/142592683-017501fc-1c59-4a0b-8cb2-26507befa0c1.png)

**Comment by misl6** [comment]
This issue has been solved on master via #7624 .
I will leave that issue open, so we can keep track of the issue, and force a fix on stable (if needed).

**Comment by wohali** [comment]
@misl6 Looks like we need the forced fix on stable. `master` looks fine.

**Comment by misl6** [comment]
Kivy 2.1.0 is out and `stable` docs are now working as expected.
Thank you for your patience!
