### ISSUE TITLE
Could you add the new app/game to the applications list?

### ISSUE THREAD

**Issue by lokapal** [kivy/kivy#7705]
A strategic boardgame-like mobile game has released:
https://play.google.com/store/apps/details?id=com.legeartisgames.epidemy

Right now it's made with kivy 2.0.0

We strongly need in users feedback to balance/improve the game. Could you post it to the applications list https://kivy.org/#gallery ?
Thanks in advance!

**Comment by misl6** [comment]
Hi @lokapal, our website source code is on GitHub,  feel free to open a PR on  https://github.com/kivy/kivy-website 😄
