### ISSUE TITLE
GOT THIS ERROR ON MY BARCODE IMAGE SCAN DECODE WITH PYZBAR PROGRAM AFTER I CONVERTED TO EXE WITH PYINSTALLER

### ISSUE THREAD

**Issue by dreamorg89** [kivy/kivy#7713]
**Software Versions**
* Python: 3.9.2
* OS: Windows 10 Home 64-bit
* Kivy: 2.0.0
* Kivy installation method: 
*  pip install kivy
*  pip install pyzbar
*  pip install opencv-python

**Project Title**
Barcode-Image-Decode-Python-Kivy

**Describe the bug**
The error message is :

**Traceback (most recent call last):
   File "PyInstaller\loader\pyimod04_ctypes.py", line 54, in __init__
   File "ctypes\__init__.py", line 374, in __init__
 OSError: [WinError 193] %1 is not a valid Win32 application**

**File "PyInstaller\loader\pyimod04_ctypes.py", line 56, in __init__
 pyimod04_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'libiconv.dll'. Most probably this dynlib/dll was not found when the application was frozen.
During handling of the above exception, another exception occurred:**

**Traceback (most recent call last):
   File "PyInstaller\loader\pyimod04_ctypes.py", line 54, in __init__
   File "ctypes\__init__.py", line 374, in __init__
 FileNotFoundError: Could not find module 'C:\Users\hp\AppData\Local\Temp\_MEI189762\pyzbar\libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.
The above exception was the direct cause of the following **exception:****

**File "PyInstaller\loader\pyimod04_ctypes.py", line 56, in __init__
 pyimod04_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\hp\\AppData\\Local\\Temp\\_MEI189762\\pyzbar\\libiconv.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[3168] Failed to execute script 'main' due to unhandled exception!**

**Expected behavior**
Help to solve this error.
Please provide guidence and solution.
Got this error on my pyzbar program after I converted to exe with pyinstaller.
I build the exe application file but at the run time its give me error message.
This error show me when i run the exe application file on windows 10 Operating System. 

**Source code link **
https://github.com/dreamorg89/Barcode-Image-Decode-Python-Kivy.git

**Comment by RobertFlatt** [comment]
Answered here https://groups.google.com/g/kivy-users/c/Yu01hX6eUFA/m/upV51l4rCwAJ
