### ISSUE TITLE
kivy.org code examples are not user friendly

### ISSUE THREAD

**Issue by e4e6** [kivy/kivy#7720]
https://kivy.org/doc/stable/tutorials/firstwidget.html
you cant just copy the code snippets without  line numbers.

![21_12_18_1-2](https://user-images.githubusercontent.com/73366454/146618730-20051b19-d7e2-43f6-9b23-08d90b331d42.png)

**Comment by e4e6** [comment]
also side bar has 2 **Getting Started** with same menus, duplicate

![21_12_18_1-5](https://user-images.githubusercontent.com/73366454/146619918-36550067-e69c-4b1d-9dcb-9ac2beb242dc.png)

**Comment by Creveoolus** [comment]
> also side bar has 2 **Getting Started** with same menus, duplicate
> 
> ![21_12_18_1-5](https://user-images.githubusercontent.com/73366454/146619918-36550067-e69c-4b1d-9dcb-9ac2beb242dc.png)

bruh

**Comment by misl6** [comment]
The sidebar issue has been fixed.
Unfortunately, line-numbering issue is still here, but we need to find a fix on the Sphinx and pygments side.

**Comment by p0lygun** [comment]
we should do the same for code blocks like this 
https://kivy.org/doc/stable/api-kivy.factory.html#module-kivy.factory
![image](https://user-images.githubusercontent.com/22869882/153724737-e8cd7f33-825f-401b-ac48-c0b2f6def99b.png)
the arrows should not be select-able

**Comment by p0lygun** [comment]
@misl6 pls reopen the issue or we should make a new one ?

**Comment by misl6** [comment]
Agree that `Generic.Prompt` (gp) should be treated as line numbers, but slightly differs from this issue. Can you please open a new one?
