### ISSUE TITLE
What does the [graphics] display token do?

### ISSUE THREAD

**Issue by clmoore3rd** [kivy/kivy#7722]
The [graphics] display token is not documented:
https://kivy.org/doc/stable/api-kivy.config.html#module-kivy.config

I'm using a Raspberry Pi app which has the [graphics] display token set to -1

What does this token do, and what are the available settings for this token?

**Comment by misl6** [comment]
We have docs for the `graphics` token.
Can you post the part of the code for which you can't find some info in docs?
