### ISSUE TITLE
Builder blocks dynamic addition of widgets

### ISSUE THREAD

**Issue by martburg** [kivy/kivy#7723]
**Software Versions**
* Python: 3.7
* OS: Win7
* Kivy: 2.0.0
* Kivy installation method: pip3
[Debug with Builder.txt](https://github.com/kivy/kivy/files/7751234/Debug.with.Builder.txt)

**Describe the bug**
With Builder loading the .kv the Label added in on_start is not shown
Without Builder it works as expected

**Expected behavior**
Label should be added regardless of using Builder or not 

**To Reproduce**
PythonFile:
        from kivy.app import App
        from kivy.uix.label import Label
        from kivy.lang import Builder
        from kivy.uix.screenmanager import ScreenManager, Screen

        Builder.load_file('Test1.kv')
 
        class ScreenManager(ScreenManager):
            pass

        class Screen(Screen):
            pass
 
 
        class Test1(App):

            def build(self):
                self.sm = ScreenManager()
                return self.sm

            def on_start(self):
                Layout = self.sm.ids['screen'].ids['fl_Rec']
                Layout.add_widget(Label(text='hi'))

        if __name__ == '__main__':
            Test1().run()

.ky File

        <ScreenManager>:
            id: screen_manager
            Screen:
                id:screen

        <Screen>:
            id:screen
            FloatLayout:
                id:fl_Rec                
                Label:
                    pos: 0,20
                    text: "Hello World Good Morning !"

**Comment by SrGambiarra** [comment]
this is working as expected for me, try updating kivy.

**Comment by gottadiveintopython** [comment]
You cannot define a class with the same name as existing widget-class. You need to rename your widget-classes something different. For instance, `Screen` -> `MyScreen`. `ScreenManager` -> `MyScreenManager`.
