### ISSUE TITLE
This helped me thanks

### ISSUE THREAD

**Issue by prajwalpant1** [kivy/kivy#7725]
my problem is solved by doing this thanks @Gork7 

To solve the problem, instead of using -- "from kivy.properties import NumericProperty"  try using 
-->  "import kivy.properties as any_name" -- then call it by saying for example --> "button_width = any_name.NumericProperty(int_button_width) "

_Originally posted by @Gorky7 in https://github.com/kivy/kivy/issues/6059#issuecomment-541312799_

**Comment by p0lygun** [comment]
for which issue is this for ? 
did u want to make a comment on a issue ? 
i think this can be closed
