### ISSUE TITLE
CoreLabel sample code, causes segfault

### ISSUE THREAD

**Issue by abedhammoud** [kivy/kivy#7728]
**Software Versions**
* Python: 3.9.9
* OS: window 10
* Kivy: 2.0
* Kivy installation method: conda

Sample code in kivy.core.text causes a segmentation fault.
https://kivy.org/doc/stable/api-kivy.core.text.html#module-kivy.core.text

**Expected behavior**
I expected to get the texture size in pixels.

**To Reproduce**
I ran the code below in vscode and ipython terminal.

```python
from kivy.core.text import Label as CoreLabel
my_label = CoreLabel()
my_label.text = 'hello'
my_label.refresh()
hello_texture = my_label.texture
print(hello_texture.text_size())

```

**Additional context**
My intention from the code above is to get the string size in pixels for a given font and size.

**Comment by misl6** [comment]
Hi @abedhammoud !

`CoreLabel` uses `Texture`, and `Texture` needs the following:
```
Using Texture before OpenGL has been initialized will lead to a crash. If
you need to create textures before the application has started, import
Window first: `from kivy.core.window import Window`
```

The `CoreLabel` examples are meant to be used into an application, when `Window` is started.

**Comment by abedhammoud** [comment]
Thanks, @misl6. I assumed the code in the docs was a fully contained example. It is clear now - thanks.
