### ISSUE TITLE
Scatter.bbox or scatter.pos is not giving the absoulte lower left coordinate with respect to window image.

### ISSUE THREAD

**Issue by amrutahebli** [kivy/kivy#7729]
[**Software](url) Versions**
* Python:3.7
* OS: Windows
* Kivy:  2.0.0

**Additional context**
![Screenshot 2021-12-29 113555](https://user-images.githubusercontent.com/47709972/147635049-199c507d-5f71-4614-99dc-b015bcf31b51.png)

**Comment by amrutahebli** [comment]
For getting absolute coordinates instead of using scatter.bbox use scatter_name.to_parent(0,0).

**Comment by rEHui-MbIcJIu** [comment]
Did you know how to make image that will shown only in (30, 30) to (100, 100) coordinates?
