### ISSUE TITLE
'kivy==master' on Android '@run_on_ui_thread' ignored

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/kivy#7733]
**Software Versions**
* Python: 3.8
* OS: Android
* Kivy: master
* Kivy installation method: Buildozer

**Describe the bug**

Unexpected error message with kivy==master, on Android 
No error with kivy==2.0.0 

01-03 16:13:55.840  3163  3163 I python  :  TypeError: Cannot create graphics instruction outside the main Kivy thread

Occurs on the last line of this fragment:

```python
   # Run on UI thread because required by Kivy canvas
    @run_on_ui_thread
    def _update_canvas(self):
        tex = self._fbo.texture.get_region(*self.crop)
        self.canvas.clear()
        with self.canvas:
            Color(1,1,1,1)
```

**Comment by kengoon** [comment]
@RobertFlatt use `mainthread` instead because `@run_on_ui_thread` is for the android native widgets like `Toast` i guess
```python
from kivy.clock import mainthread
@run_on_ui_thread
def _update_canvas(self):
   tex = self._fbo.texture.get_region(*self.crop)
   self.canvas.clear()
   with self.canvas:
        Color(1,1,1,1)
```

**Comment by RobertFlatt** [comment]
This is android only code. Using `run_on_ui_thread` is required. I tried `mainthread` and Jnius complains with essentially the same message.

I don't think this is a functional issue in terms of the thread used. Simply a too sensitive error message, recently introduced.

**Comment by kengoon** [comment]
@RobertFlatt from both your code and error it is not an android only code, it is a purely Kivy

**Comment by RobertFlatt** [comment]
The code sample is executed on an Android device. And to execute it is required to use `run_on_ui_thread`, else Jnius reports an error.

`run_on_ui_thread` is a documented api https://github.com/kivy/python-for-android/blob/develop/doc/source/apis.rst#runnable where is says:
```
**use our decorator**:
from android.runnable import run_on_ui_thread
@run_on_ui_thread
```

The error message test has been modified since 2.0.0 and is erroneous in the case of `run_on_ui_thread`.

**Comment by kengoon** [comment]
@RobertFlatt Use `@mainthread` decorator, if you get any errors post it. It will help to diagnose the issue very well

**Comment by RobertFlatt** [comment]
My apologies. 
I created a new test with @mainthread and kivy==master and there is no message from Jnius.

Clearly I messed up.
