### ISSUE TITLE
kivy.org search functionality is broken

### ISSUE THREAD

**Issue by ditek** [kivy/kivy#7734]
I apologize if this is the right place to report this.
The search functionality is broken on the website. You do get search results, but all of them point to non-existing pages.
For example:

https://kivy.org/doc/stable/search.html?check_keywords=yes&area=default&q=runTouchApp

**Comment by ptrstn** [comment]
I can confirm. Every result leads to a 

```
404 Not Found
nginx
```

page.

**Comment by misl6** [comment]
Duplicated of #7697
