### ISSUE TITLE
Kivy starts on library import not on App.run

### ISSUE THREAD

**Issue by kshaa** [kivy/kivy#7742]
**Software Versions**
* Python: `Python 3.9.7`
* OS: `Ubuntu 20.04.2 LTS`
* Kivy: `2.0.0`
* Kivy installation method: `pipenv`

**Describe the bug**
Just by importing the Kivy library _and not by running `App.run`_ a blank/black window is opened and immediately closed. Specifically it seems that the `kivy.core.window.Window` import causes this side-effect.

**Expected behavior**
I would expect that an import doesn't cause any side-effects i.e. a blank/black window to be opened, an import should only provide me the tools to implement an application. I would expect that a window would only appear when I run `App.run`.

**To Reproduce**
Simply by running the code snippet below I see a blank window flash for a moment.

**Code and Logs and screenshots**
`snippet.py`:
```python
import kivy
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.core.window import Window
from kivy.properties import NumericProperty
```

The execution of that snippet results in Kivy to be instantiated and a blank window to appear.
```bash
$ python snippet.py 
[INFO   ] [Logger      ] Record log in $REDACTED_HOME/.kivy/logs/kivy_22-01-08_42.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "$REDACTED_HOME/.local/share/virtualenvs/client-MAI5BRQn/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.7 (default, Dec 27 2021, 14:55:58) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "$REDACTED_HOME/.local/share/virtualenvs/client-MAI5BRQn/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 20.2.6'>
[INFO   ] [GL          ] OpenGL vendor <b'X.Org'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD RENOIR (DRM 3.40.0, 5.10.0-1038-oem, LLVM 11.0.0)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
```

_Note: I can of course make these imports dynamic, but that kind of seems like a hack, would be nice to have a more elegant solution._

**Comment by kuzeyron** [comment]
This is expected to happen. The intention is not like OpenCV with its `cv.imshow('Frame', frame)`.

**Comment by kshaa** [comment]
@kuzeyron Ah, very well. I guess it's reasonable, especially knowing the main use-case of the framework - standalone apps. I just wanted to use it differently - not as a standalone app, but as an app I can spawn in a CLI tool when needed.

Anyway, for now switched to dynamically importing the kivy library (probably not the prettiest of solutions) and will consider using something more appropriate for my use case in the future. Cheers! :)
