### ISSUE TITLE
 ERROR: Failed building wheel for Kivy when trying install Kivy on Mac

### ISSUE THREAD

**Issue by gor-geghamyan** [kivy/kivy#7746]
**Software Versions**
* Python: 3.10.1
* OS: macOS Big Sur version 11.6.2
* Kivy: 2.0.0
* Kivy installation method: pip3 install https://github.com/kivy/kivy/archive/master.zip

**Describe the bug**

2 warnings generated.
  clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-3.10/kivy/core/camera/camera_avfoundation.o build/temp.macosx-10.9-universal2-3.10/kivy/core/camera/camera_avfoundation_implem.o -o build/lib.macosx-10.9-universal2-3.10/kivy/core/camera/camera_avfoundation.cpython-310-darwin.so -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.6.sdk/System/Library/Frameworks -framework AVFoundation -lm
  ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.6.sdk/System/Library/Frameworks'
  ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.6.sdk/System/Library/Frameworks'
   error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for Kivy
Failed to build Kivy
ERROR: Could not build wheels for Kivy, which is required to install pyproject.toml-based projects

**Comment by lukthony** [comment]
I am also experiencing this issue.

**Comment by misl6** [comment]
Can you please post the full log?

**Comment by gor-geghamyan** [comment]
Collecting Kivy
  Cloning https://github.com/kivy/kivy (to revision master) to /private/tmp/pip-install-cuw9r02u/kivy_037c5700268641c3afffdaa02e1f55f1
  Resolved https://github.com/kivy/kivy to commit 4320c7271cbedef1cf59cb4a381f6a75c4f6738c
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting docutils
  Downloading docutils-0.18.1-py2.py3-none-any.whl (570 kB)
Collecting pygments
  Downloading Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting Kivy-Garden>=0.1.4
  Downloading kivy-garden-0.1.4.tar.gz (6.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.10-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Using legacy 'setup.py install' for Kivy-Garden, since package 'wheel' is not installed.
Building wheels for collected packages: Kivy
  Building wheel for Kivy (pyproject.toml): started
  Building wheel for Kivy (pyproject.toml): still running...
  Building wheel for Kivy (pyproject.toml): finished with status 'error'
Failed to build Kivy

**Comment by misl6** [comment]
Instead of installing it from `pip` can you please `git clone` it and build via `setup.py` so a better log is shown?
