### ISSUE TITLE
 ImportError with python3.10

### ISSUE THREAD

**Issue by wellington36** [kivy/kivy#7747]
**Software Versions**
* Python: 3.10.1
* OS: linux (manjaro gnome 41.2)
* Kivy: 2.0.0
* Kivy installation method: pip3 install https://github.com/kivy/kivy/archive/master.zip and pip3 install kivy

When doing some imports using python 3.10 an ImportError error occurs:

```bach
$ python3.10 project.py

[INFO   ] [Logger      ] Record log in /home/wellington/.kivy/logs/kivy_22-01-10_15.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/wellington/.local/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python"
 Traceback (most recent call last):
   File "/home/wellington/Documentos/Mini_course/project.py", line 1, in <module>
     from kivy.app import App
   File "/home/wellington/.local/lib/python3.10/site-packages/kivy/app.py", line 411, in <module>
     from kivy.base import runTouchApp, async_runTouchApp, stopTouchApp
   File "/home/wellington/.local/lib/python3.10/site-packages/kivy/base.py", line 29, in <module>
     from kivy.event import EventDispatcher
   File "/home/wellington/.local/lib/python3.10/site-packages/kivy/event.py", line 8, in <module>
     import kivy._event
 ImportError: /home/wellington/.local/lib/python3.10/site-packages/kivy/_event.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

I think this has to do with Python 3.10+ dropping `_PyGen_Send()` and requiring the use of `PyIter_Send()` now, or or I am using it wrong.

**Comment by misl6** [comment]
I suppose that you installed it from sources. (We did not have any `whl` for Python 3.10 published yet):
What is your `Cython` version?

Instead, can you please try to install the wheel for Python 3.10 produced here (via https://github.com/kivy/kivy/pull/7663)?
https://github.com/kivy/kivy/actions/runs/1662730451

**Comment by wellington36** [comment]
I don't have cython installed, I installed #7663, the last commit version and the install at https://kivy.org/doc/stable/gettingstarted/installation.html#development-install and they didn't solve it, but if I run with python3.9 there is no problem.

**Comment by sdegrande** [comment]
Same error on Fedora 35.
The installed cython is the one packaged by Fedora (python3-Cython-0.29.24).
I also had to get back to python3.9.

**Comment by Ubuntufanboy** [comment]
Have a similar issue. It isnt even installing on python3 3.1. I am running gnome Manjaro as well. Not sure if it is a coincidence. I have a wheel fail error which the test seem to be proving as concurrent.

**Comment by kuzeyron** [comment]
Try upgrading setuptools. It seemed to solve my issue on Manjaro.
```
Cython version 0.29.15
Python 3.10.1
Setuptools 60.5.0
Kivy master
```

**Comment by wellington36** [comment]
> Download Kivy as a clone or zip file (unzipped) and enter that directory and execute pip install .


It worked, thanks, but I'll keep the issue open since the problem appears in other operating systems and although it works it doesn't seem like the most obvious solution for a user.

**Comment by ryonistic** [comment]
Hi, Kivy does not yet support Python 3.10, try using 3.9.

**Comment by misl6** [comment]
Kivy 2.1.0 is out and has Python 3.10 pre-built wheels.

Are you still encountering the issue with the newly release version?

**Comment by wellington36** [comment]
@misl6, it's OK for me, no have problem.
