### ISSUE TITLE
Documentation website - Search result links lead to 404s

### ISSUE THREAD

**Issue by kirstenhh** [kivy/kivy#7753]
**Software Versions**
N/A; this report is for the documentation website at https://kivy.org/doc/stable/

**Describe the bug**
Clicking on terms in a search result leads to a 404 page. The URL of the result has "undefined" in the place of .html, which causes the 404.

**To Reproduce**
Go to https://kivy.org/doc/stable/
Search collide_point (or any search term) in the search bar on the left
Click on the first result

**Comment by misl6** [comment]
Duplicated of https://github.com/kivy/kivy/issues/7697
