### ISSUE TITLE
The text is not clear, how to solve it?

### ISSUE THREAD

**Issue by nufeng1999** [kivy/kivy#7765]
**Software Versions**   
* Python: 3.9   
* OS: Windows   
* Kivy:2   
*
The text is not clear, how to solve it?   
Windows Scale 200%   

![1](https://github.com/nufeng1999/imgs/blob/main/img/20220123142955.png?raw=true)
![2](https://github.com/nufeng1999/imgs/blob/main/img/20220123143911.png?raw=true)

**Comment by ht-thomas** [comment]
I don't understand where the error is. Please try describing the problem really well.

**Comment by nufeng1999** [comment]
> I don't understand where the error is. Please try describing the problem really well.  

Window menu and text blur when Windows resolution is scaled by 200%

**Comment by misl6** [comment]
Can you share your install method and a relevant part of your code?
