### ISSUE TITLE
Wrong word in Givy documentatio

### ISSUE THREAD

**Issue by china-fanxin** [kivy/kivy#7782]
Dear kivy's team,

First of all, thank you for your selfless dedication.I found a suspected wrong word in the document.

Wrong word in : Document:Welcome to Kivy

In this section,the 

>  Welcome to Kivy’s documentation. Kivy is an open source software library for the rapid development of applications equipped with novel user interfaces, such as multi-touch apps.

"novel user interfaces" maybe a error, I see "innovative user interface" in Kivy's homepage,so I think it's maybe a wrong word.

Thanks .

**Comment by misl6** [comment]
Hi @china-fanxin ,
"novel" and "innovative" can be used as synonyms in that case, but feel free to submit a PR 😄
