### ISSUE TITLE
Setup Platform Override for Raspberry Pi CI Builds

### ISSUE THREAD

**Issue by peanball** [kivy/kivy#7797]
**Is your feature request related to a problem? Please describe.**

The Raspberry Pi support is only enabled if `setup.py` detects it's running on a Raspberry Pi via the `/opt/vc/include/bcm_host.h` file, but then goes on to check the `/proc/cpuinfo` to identify that it's not running on a Raspberry Pi 4 hardware. That is fair enough, but does not detect correctly in the `pi-gen` environment as the CPU is not a Raspberry Pi.

There is the flag / env variable `use_rpi`/`USE_RPI`, which can be used to force cythonization of the `egl` and `bcm` modules, but the compilation fails, as the [setup.py:631-663](https://github.com/kivy/kivy/blob/master/setup.py#L631-L663) requires `platform` to be set to `rpi` and ignores `use_rpi`.

**Describe the solution you'd like**
Allow overriding the `platform` in setup.py via ENV variable, or include a check for `use_rpi`, so the compilation works.

There should be a warning in the Docs that the Raspberry Pi version with `egl_rpi` support _must_ be compiled locally on a Raspberry Pi at the moment.
If the solution as described above is implemented, the docs could instead mention to use the override flag for a QEMU enabled CI build.

**Describe alternatives you've considered**

* Building on the Raspberry Pi was the originally foreseen use case for this, but is not practical for creating a pre-built image.
* I could prebuild Kivy on a Raspberry Pi and copy the build outputs over / put them in a repo somewhere and use them from there.

I will try the above suggestion and submit a pull request.

**Additional context**
I am trying to build a Raspberry Pi image based on the raspberrypi/pi-gen toolchain. The image is built in a container on some x64 server using QEMU's emulation for ARM processors in order to build a disk image for a Raspberry Pi. This is what is also used for building the official Raspbian / RaspberryOS images.

Installing `kivy[base]` as wheel comes without `egl_rpi` python prebuilts, so I can't use it for my current use case.

**Comment by kuzeyron** [comment]
I will be quick and ask if you have tried these steps: [Installation on Raspberry Pi](https://kivy.org/doc/stable/installation/installation-rpi.html)?

**Comment by peanball** [comment]
Yes of course. It builds fine on the raspberry pi. But I want to cross build an image using raspberrypi/pi-gen, which uses qemu under the hood to run all the user space (apt, compilers, etc) as arm binaries on intel build servers.

I have it build a working image with the change I'm suggesting to the setup.oh in that environment. 

I will open a pull request later today.
