### ISSUE TITLE
In docs Generic.Prompt (gp) should be treated as line numbers, and must be unselectable

### ISSUE THREAD

**Issue by p0lygun** [kivy/kivy#7800]
**Is your feature request related to a problem? Please describe.**
Currently when copying code from code blocks with  Generic.Prompt  in them the arrows are also copied
https://kivy.org/doc/stable/api-kivy.factory.html#module-kivy.factory
![image](https://user-images.githubusercontent.com/22869882/153725428-67e5b570-34cd-4f04-8f3d-c865bb0c4e0a.png)

**Describe the solution you'd like**
we should make the Generic.Prompt  unselectable 
possible solution #7790

**Additional context**
for reference see #7720,

**Comment by kuzeyron** [comment]
To me it would look better without the `>>>`.

**Comment by kuzeyron** [comment]
Yes, but it's a website. Not the Interpreter itself.

**Comment by p0lygun** [comment]
It's easily doable but I like those 🙂

**Comment by kuzeyron** [comment]
And I was just going for the easy way and just ignore them being used at all.
