### ISSUE TITLE
Documentation/Search function returning incorrect URLs

### ISSUE THREAD

**Issue by CrawfishPress** [kivy/kivy#7825]
The Quick-Search function sometimes returns error-URLs instead of finding the existing valid URL. Given a documentation page:

    https://kivy.org/doc/stable/api-kivy.html

If you type "window" in the Quick-Search window, it returns a list of result URLs, with the top URL being:

    https://kivy.org/doc/stable/api-kivy.core.windowundefined?highlight=window#module-kivy.core.window

**Expected behavior**
The Quick-Search should return the found URLs, with a suffix `.html`:

    https://kivy.org/doc/stable/api-kivy.core.window.html

All of the returned URLs are like this, missing the suffix.

**Comment by misl6** [comment]
Duplicated of #7697

**Comment by CrawfishPress** [comment]
Wups, sorry. I _did_ search the Issues, but for things like incorrect URLs - didn't find that issue.
