### ISSUE TITLE
Animation.have_properties_to_animate crash for Sequence animation

### ISSUE THREAD

**Issue by tito** [kivy/kivy#7829]
**Software Versions**
* Python: 3.9
* OS: Arch linux
* Kivy: 1.11.1
* Kivy installation method: poetry/pip

**Describe the bug**

When using an sequence Animation: `anim = (Animation() + Animation()).start(widget)`, the subsequent call to `have_properties_to_animate` crash:

```python
>>> from kivy.animation import Animation
>>> from kivy.widget import Widget
>>> widget = Widget()
>>> anim = (Animation() + Animation())
>>> anim.start(widget)
>>> anim.have_properties_to_animate(widget)
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/tito/.conda/envs/oman/lib/python3.7/site-packages/kivy/animation.py", line 268, in have_properties_to_animate
     if props and props['properties']:
 TypeError: 'bool' object is not subscriptable
```

**Expected behavior**
It should not crash, and work the same as normal Animation.

**To Reproduce**
```python
from kivy.animation import Animation
from kivy.widget import Widget
widget = Widget()
anim = (Animation() + Animation())
anim.start(widget)
anim.have_properties_to_animate(widget)
```

**Additional context**
This crash also for Parallel animation.

**Comment by misl6** [comment]
I can't reproduce on **Kivy 2.1.0**, maybe thanks to https://github.com/kivy/kivy/pull/5926?

Is the same on your side?
