### ISSUE TITLE
ERROR: Could not build wheels for kivy, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by xTrayambak** [kivy/kivy#7832]
I keep getting an error when I try to build Kivy on Ubuntu 20.10 LTS. The main error is:
```
        4 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
       error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```
Here's the full error: https://pastebin.com/E0LN6zHz

**Comment by matham** [comment]
You need to `sudo apt install python3-dev`.

**Comment by KrasProject-2021** [comment]
hello, i'm trying to create a kivymd python application, but in the process of installing it, an error appears:

ERROR: Failed to build wheels for kivy, which are required to install projects based on pyproject.toml.

and this despite the fact that all support libraries have the latest version. I ask you to help.

**Comment by kzlknight** [comment]
try this
 python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/stable.zip"
not master.zip
