### ISSUE TITLE
Correction of widget's method in documentation.

### ISSUE THREAD

**Issue by ApuCoder** [kivy/kivy#7838]
https://github.com/kivy/kivy/blob/06c15c1f7567c6dbc97248c85467bdfd2fcf3cf8/kivy/uix/widget.py#L126

Shouldn't it be :meth:`~kivy.uix.widget.Widget.add_widget` instead of :meth:`~kivy.uix.widget.Widget.on_touch_up` ?

**Comment by Anand-Vibhuti** [comment]
assign it to me , lets clear the small ones
