### ISSUE TITLE
'NoneType' has no attribute 'tell' can be avoided by raising FileNotFoundError.

### ISSUE THREAD

**Issue by Poikilos** [kivy/kivy#7844]
**Software Versions**
* Python: 3.9
* OS: Linux (Devuan Chimera)
* Kivy: 2.1.0
* Kivy installation method: pip

**Describe the bug**
When an image is not found, an obscure error appears: 'NoneType' has no attribute 'tell'

**Expected behavior**
A meaningful exception (probably FileNotFoundError) should be raised before the problem becomes obscure in later code.

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.
example1.py in https://github.com/kivy/kivy3

**Code and Logs and screenshots**
kivy_venv/lib/python3.9/site-packages/kivy/core/image/__init__.py
```python
        filename = resource_find(filename)
```

**Additional context**
There are several users who have been confused by the error:
- kivy's fork of kivy3 currently has the problem (diagnosing the simple problem of a missing file was difficult since the error message was unclear; I am the user in this case).
-  https://github.com/viblo/pymunk/issues/166 (It confused more than one user in this case)
- https://www.forexfactory.com/thread/614471-free-machine-learning-tool-with-a-graphical-user-interface?page=2 (This is not a kivy example but is in imagehdr.py which kivy uses).

To be clear, the error goes away in the example code if a png file named "empty.png" is manually placed in the folder (The fact that it is not there is a [kivy3 issue](https://github.com/kivy/kivy3/issues/30)). The kivy issue is merely that the error message is unclear, and the suggested fix provides a better error message.

**suggested fix**
*Before* the resource_find call, add:
```python
        original_path = str(filename)
```
After the resource_find call, add:
```python
        if filename is None:
            raise FileNotFoundError(original_path + " was not found.")
```

Other considerations:
- If you rather not have a crash when images are missing, maybe use kivy/default.png and simply show an error rather than raise an exception.

**Comment by Vricken** [comment]
I was working with images and got the ‘NoneType’… , I was very confused to say the least. This however brought me clarity. I personally think this is a very good suggestion which can avoid confusion to many people.

**Comment by Julian-O** [comment]
I was going to mark this as `easy`, but I realised:

* There is no mention of where the code that is calling `tell` - why isn't it checking?
* What about all the other calls to `resource_find`?
* `resource.py`'s`resource_find already checks the filename is not Falsy.
* Why is the filename None when the file doesn't exist?

This may be a bug, but I am not sure the proposed solution is tackling the root cause.

**Comment by ElliotGarbus** [comment]
Creating a simple test, I do not see the reported issue with Kivy.
Kivy V2.2.1

```python
from kivy.app import App
from kivy.uix.image import Image


class Reproduce7844App(App):
    def build(self):
        image = Image(source='missing_file.png')
        return image


Reproduce7844App().run()
```
The log contains the following error message:
[ERROR  ] [Image       ] Not found <missing_file.png>

@Poikilos Is there a reproducer available for kivy?  Does my example capture the use case you highlighted?
