### ISSUE TITLE
Fullscreen not working with the 2.1

### ISSUE THREAD

**Issue by olivier-boesch** [kivy/kivy#7845]
**Software Versions**
* Python: 3.10.2+
* OS: ubuntu mate 22.04
* Kivy: 2.1
* Kivy installation method: pip

**Describe the bug**

Only a black screen appears when I try to start the app in fullscrren mode ('auto' and 1 modes)

**Expected behavior**

An application in fullscreen

**To Reproduce**

**Code and Logs and screenshots**
```python
from kivy.config import Config
Config.set("graphics", "fullscreen", "auto")
from kivy.app import App
from kivy.uix.label import Label


class TestApp(App):
    def build(self):
        return Label(text="Works ?")


app = TestApp()
app.run()
```
**Context**

These seems to works only with 2.1. with the 2.1rc1, I can get a fullscreen working window.
EDIT: these appears either when the nvidia driver (510 on a RTX2060) or the amd driver are working.

**Comment by matham** [comment]
Historically this has happened for the wheels and the solution was to install kivy from source.

**Comment by olivier-boesch** [comment]
That's what I did. I installed kivy from pip+git to get the master. It's strange that the wheel doesn't work.

Thanks.

Should I let this issue opened ?

**Comment by matham** [comment]
>That's what I did. I installed kivy from pip+git to get the master. It's strange that the wheel doesn't work.

Probably need to compile SDL2 with some option to fix it. But I didn't see anything obvious there.

>Should I let this issue opened ?

**Comment by misl6** [comment]
@matham are you talking about https://github.com/kivy/kivy/issues/6651 ?

**Comment by matham** [comment]
>@matham are you talking about https://github.com/kivy/kivy/issues/6651 ?

yes!

**Comment by logdan** [comment]
I have this issue as well, even installing kivy from source as in the instructions. Using Ubuntu 20.04. Solution for me was to install specifically kivy 2.0.0 from source via python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/dedcb6bcabe3d8d6758dcee607e8c33b174d782b.zip" .

**Comment by Reflex14** [comment]
Is there a permanent solution coming without building everything from source? I am getting tired of fixing this problem again and again. I believe Python's wheels have flat tires at the moment, always something 'ey

**Comment by Noor-Kalibbala** [comment]
am currently facing this issue with kivy 2.1.0, how did u resolve this bug

**Comment by colin0brass** [comment]
Hi @Noor-Kalibbala,

For me, normal pip (binary) install gave either a black screen or sometimes a crash (on Mac vs Raspberry Pi ... I forget now which did what ...) in full screen mode (which I wanted to use for app deployment on Raspberry Pi touchscreen).

The above (in my previous comment) pip source code installation ('--no-binary') worked for me, though when I later did a clean re-install I found that it doesn't include the window manager (e.g. sdl2) that was included in the binary install. I assume that first time around the window manager had already been added during kivy binary installation, so was still there when I re-installed kivy from source. So I then re-did the binary install followed by source ('--no-binary') reinstall, and that gave me both working fullscreen and also the required window manager.

**Comment by misl6** [comment]
Hi @colin0brass !

Can you please confirm that `2.2.0rc1` wheels are fixing this issue also for you?

To install the pre-release (`2.2.0rc1`) version:
`pip install --pre kivy`

**Comment by misl6** [comment]
Thank you for confirming that!

Closing as fixed, @olivier-boesch feel free to confirm that or ping me and ask to re-open the issue.

**Comment by Medeirox** [comment]
> Thanks @misl6 , yes that worked. I did the following (on Raspberry Pi 4):
> 
> ```
> # uninstalled previous --no-binary install (2.1.0 source compile)
> pip uninstall kivy
> 
> # tested with current standard binary to check it still failed
> pip install --no-cache kivy
> # Downloading Kivy-2.1.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (30.5 MB)
> # sure enough my kivy app froze during start-up in fullscreen mode
> 
> # uninstalled that version
> pip uninstall kivy
> 
> # installed --pre version
> pip install --no-cache --pre kivy
> # Downloading Kivy-2.2.0rc1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (19.1 MB)
> # that worked! App successfully started and functioned correctly in fullscreen mode
> ```

Was having the same black fullscreen problem on a Raspberry Pi 4, the rc1 fixed for me as well! Thanks!
