### ISSUE TITLE
Kivy application doesn't work correctly if I use pynput global hotkeys

### ISSUE THREAD

**Issue by jd-solanki** [kivy/kivy#7865]
**Software Versions**
* Python: 3.10.4
* OS: Ubuntu 21.10
* Kivy: v2.1.0
* Kivy installation method: Linux Pip + pyenv + poetry

**Describe the bug**
When I run the app everything looks fine but no label is shown and I am unable to close the app with a single click of the close button. After multiple attempts of closing the window, I get a python not responding error.

**Expected behavior**
It should work with pynput without any errors.

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.uix.label import Label
from pynput import keyboard


class MyApp(App):
    def open_window(self):
        print(f"Key pressed...")
        self.root_window.show()

    def build(self):
        return Label(text="Hello")

    def on_start(self):
        self.root_window.hide()

        with keyboard.GlobalHotKeys({"<ctrl>+<alt>+h": self.open_window}) as h:
            h.join()


if __name__ == "__main__":
    MyApp().run()
```

**Additional context**
Some screenshots of my app:
[Image 1](https://i.stack.imgur.com/Z4t5J.png)
[Image 2](https://i.stack.imgur.com/ZsjWV.png)

Stackoverflow [Question](https://stackoverflow.com/questions/71778231/kivy-application-doesnt-work-correctly-if-i-use-pynput-global-hotkeys)

**Comment by Julian-O** [comment]
Does that join a thread in the middle of `on_start()`? Uh, well, that's not a good idea.
