### ISSUE TITLE
WebView for Desktop (Windows and MacOS)

### ISSUE THREAD

**Issue by jhay06** [kivy/kivy#7875]
hi ,
  would like to request a webview widget that can add along with other widgets like on android and ios for windows desktop /mac desktop

are there any widget available for this ? thanks

**Comment by Schlaubischlump** [comment]
Duplicate #7842 

This is probably the closes you'll get: https://github.com/cztomczak/cefpython

**Comment by Python3-8** [comment]
I asked the same question ages ago at #7335, but apparently Kivy won't be adding this feature. As I just posted on #7335, I started using Flutter and it's great for Material Design. If I had to make something like a game I would probably return to Kivy. Electron.js is also a great option if you're looking to make a desktop application. With Electron, your requirement should be easily satisfied as the application itself would be like a WebView.
