### ISSUE TITLE
Numeric keyboard Kivy: v2.1.0

### ISSUE THREAD

**Issue by CoutinhoElias** [kivy/kivy#7878]
**Software Versions**
* Python: v3.9.6
* OS: Ubuntu
* Kivy: v2.1.0
* KivyMD: 0.104.2, git-bc7d1f5, 2021-06-06
* Kivy installation method: python -m pip install "kivy[base]" kivy_examples

**Describe the bug**

I can't SHOW a keyboard with only numbers.

The full keyboard always appears, I would like to show only numbers.

The closest I've come is preventing you from typing anything other than numbers.

I believe there is something implicit, I have already found some things hidden in other widgets.

Would it be possible to post a little code for us to see?

If possible, could you publish the versions you are using as I did above?

We will be very grateful.

**Expected behavior**
I would like it to show a numeric only keyboard.

**To Reproduce**
In my text field it looks like this:

    MDTextField:
        id: senha_input
        hint_text: 'Senha'
        pos_hint: {'center_x': .5, 'center_y': .6} 

        multiline: False
        input_type: 'number'
        input_filter: 'float'

**Code and Logs and screenshots**
```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.
```

**Additional context**

The attached image comes from an Android emulator, the keyboard is above the text field and this keyboard should be numbers only.

![Captura de tela de 2022-05-02 14-21-21](https://user-images.githubusercontent.com/12012709/166294483-c60a552a-3d5c-42a1-bedb-d0793e424c5b.png)

**Comment by drahba** [comment]
Kivy 2.1.0 support calling numeric android keyboard, but kivyMD may not have been updated. You may try kivyMD develop branch if this does not work you have to use kivy 2.1.0 TextInput.

**Comment by CoutinhoElias** [comment]
Does not work.

I'm testing on an Android Studio emulator and it doesn't show the numeric keypad.

Do you have a small code example for me to package here and test?

I feel there is something implicit, forgotten in our comments.

**Comment by edsonbernar** [comment]
I've noticed the same issue on some Samsung devices and I'm not using kivyMD. Occurred in the TextInput same.

**Comment by CoutinhoElias** [comment]
> Kivy 2.1.0 suporta chamada de teclado numérico android, mas o kivyMD pode não ter sido atualizado. Você pode tentar o branch de desenvolvimento do kivyMD, se isso não funcionar, você deve usar o kivy 2.1.0 TextInput.

With all due respect, I think if you do a little example and share it with us it would be easier to find the problem because then we would package this example and we would certainly find out if the problem is in android or in our code.

Is there a possibility to share a little code and a print of how your keyboard turned out?

**Comment by drahba** [comment]
In buidozer requirements you need kivy==2.1.0 and in the kv code you need to use TextInput

```
TextInput:
            input_type: "number"
TextInput:
            input_type: "tel"`
```
tested on s7 and note 9 just works fine

**Comment by CoutinhoElias** [comment]
> kivy==2.1.0

What was different on mine was the buildozer version, I made the adjustment and again it didn't work.

Do you have an example with buildozer and running there?

Below my text field:
             id: amount_entered
             multiline: False
             input_type: 'number'
             size_hint: .4, None
             height: "30dp"

Below my requirements:
requirements =
     python3,kivy==2.1.0,
     https://github.com/kivymd/KivyMD/archive/master.zip,
     pygments, sdl2_ttf==2.0.15, pillow, requests, certifi, urllib3,
     chardet, idna, plyer, pyrebase, gcloud, oauth2client,requests-
     toolbelt, httplib2, pyparsing, pyasn1, pyasn1_modules, rsa,
     python-jwt, jwcrypto, deprecated, wrapt, google-api-python-
     client, google-cloud, google-cloud-storage, protobuf,
     cryptography, pycryptodome, validate-docbr

I'm using a Pixel 5 API 30 with Android 11 (emulated)

**Comment by drahba** [comment]
If you are using MDTextField as your text field numeric keypad do not work, you need to use TextInput as your text field. Your kv code has to be like this:
```
TextInput:
    id: senha_input
    hint_text: 'Senha'
    pos_hint: {'center_x': .5, 'center_y': .6} 

    multiline: False
    input_type: 'number'
    input_filter: 'float'
```

**Comment by CoutinhoElias** [comment]
> If you are using MDTextField as your text field numeric keypad do not work, you need to use TextInput as your text field. Your kv code has to be like this:
> 
> ```
> TextInput:
>     id: senha_input
>     hint_text: 'Senha'
>     pos_hint: {'center_x': .5, 'center_y': .6} 
> 
>     multiline: False
>     input_type: 'number'
>     input_filter: 'float'
> ```

It worked! I can't believe it!
The problem was my buildozer with the wrong version of kivy and all the tips mentioned here.

Kivy numeric keypad working!
