### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by Jicming** [kivy/kivy#7884]
**Is your feature request related to a problem? Please describe.**
Now kivy can't speak Chinese, such as textinput,label etc When you input Chinese on a written app, it's garbled

**Describe the solution you'd like**
Support for Chinese is required. For example, as long as there is Chinese, garbled code will be displayed on the app, including label prompt, textinput writing, etc. as long as there is Chinese, it is garbled code

**Describe alternatives you've considered**
For Chinese support, do I need to find the Lib library myself

**Additional context**
No relevant screenshots

**Comment by kuzeyron** [comment]
For now you will have to ship your own font that supports Chinese characters.

**Comment by Python3-8** [comment]
Try using a Chinese font like this one: https://fonts.google.com/noto/specimen/Noto+Sans+TC
