### ISSUE TITLE
kivy doesn't set the X11 WM_NAME and WM_CLASS properties optimally

### ISSUE THREAD

**Issue by hastiin-manuelito** [kivy/kivy#7886]
**Software Versions**
* Python: 3.10.4
* OS: Arch linux
* Kivy: 2.1.0
* Kivy installation method: pip install --upgrade kivy

**Describe the bug**
My window manager (Qtile) doesn't catch the kivy app instance with its "floating rules" (Qtile specific). In the language of Qtile I specifically referenced the X11 WM_NAME instance of the kivy app which I understand to be the "title" of the app as provided by the class App. It also seems like kivy doesn't set the "WM_CLASS" tuple as it falls back to "python3.10" (in my case).

**Expected behavior**
The expected behavior is that the kivy window show up as a floating window instance (with the default size for the app) rather than a tiled instance.

As suggested by the Qtile team, kivy should specify both the "WM_NAME" and "WM_CLASS" tuple before initializing the actual window. I understand that kivy uses the sdl2 backend for drawing the graphics window, however, it still is eventually rendered within the X11 framework, which is my graphics interface.

**To Reproduce**
Run any kviy app in a Qtile manager with an X11, setting within the `floating_layout` variable something like,
```
floating_layout = layout.Floating(float_rules=[
    ...
    Match(title='appname'),  # for "self.title" set to "appname"   
    ...
    or
    ...
    Match(wm_class='kivy'),  # assuming WM_CLASS is set to "kivy"  
 ])
```

**Code and Logs and screenshots**

```python
import kivy
kivy.require('2.1.0')

from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput

class LoginScreen(GridLayout):

    def __init__(self, **kwargs):
        super(LoginScreen, self).__init__(**kwargs)
        self.cols = 2
        self.add_widget(Label(text='User Name'))
        self.username = TextInput(multiline=False)
        self.add_widget(self.username)
        self.add_widget(Label(text='password'))
        self.password = TextInput(password=True, multiline=False)
        self.add_widget(self.password)


class MyApp(App):

    def build(self):
        return LoginScreen()

if __name__ == '__main__':
    MyApp().run()
```

**Additional context**
I run X11 straight from the linux shell using xinit, avoiding the overhead of a full desktop environment.
I tried to look into the window backends and see if I couldn't help out myself. The problem is that I am not familiar with cython and its syntax, nor am I familiar with how C works.

**Comment by p0lygun** [comment]
as a workaround, you can launch your app after setting the ` SDL_VIDEO_X11_WMCLASS` env var to override it
so 
` SDL_VIDEO_X11_WMCLASS=test python <you app>`

**Comment by p0lygun** [comment]
@misl6 i think we can close this as current behaviour is correct, sdl sets the WM_CLASS name depending on the binary that spawned it, although we can set it to whatever we like with the env var

**Comment by hastiin-manuelito** [comment]
I will mark this as closed because there is technically an option that one can choose, as you pointed out, i.e. setting the environment variable. I have tested setting the environment variable and it does automatically float the app window. 

NOTE: However, it still remains that the WM_NAME is not recognized for the Qtile window manager prior to initializing the actual window.
