### ISSUE TITLE
'function' object has no attribute 'dialcall

### ISSUE THREAD

**Issue by KINGMOHIT** [kivy/kivy#7888]
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Python      ] v3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [KivyMD      ] 0.104.2, 

here is my function
    def dial(self, *args):
        call.dialcall()
I am getting below error  for dailcall

06-02 02:16:38.611 18889 18922 I python  :      on_release: app.dial()
06-02 02:16:38.611 18889 18922 I python  :    File "/mnt/d/video/kivy-video-app-master/.buildozer/android/app/main.py", line 148, in dial
06-02 02:16:38.612 18889 18922 I python  :  AttributeError: 'function' object has no attribute 'dialcall'
06-02 02:16:38.612 18889 18922 I python  : Python for android ended.

**Comment by misl6** [comment]
Hi @KINGMOHIT , seems you're trying to call the `plyer` `dialcall` function on Windows, where is not marked as available.
