### ISSUE TITLE
Exit code -1073741819 (0xC0000005) when trying to run simple "Hello World" code

### ISSUE THREAD

**Issue by Grahamster** [kivy/kivy#7892]
**Software Versions**
* Python: 3.9
* OS: Windows 
* Kivy: 2.1.0
* Kivy installation method: Pycharm Package and command line install

**Describe the bug**
While researching about Kivy and understanding how to code with the Kivy app, I was only trying to run the basic "Hello World" window run to create a window in the computer. However, every time I try to run the simple "Hello World" window code, I always receive an exit code of -1073741819 (0xC0000005) while the code attempts to run or run through the de-bugging process. No window is produced and the code simply stops running. I have attempted to run this code through Pycharm IDE, IDLE IDE and the command prompt with no success and displaying the same exit code -1073741819 (0xC0000005). Any help will be greatly appreciate.

**Expected behavior**
After creating the simple code for "Hello World", I expected a new window to appear with the text of "Hello World" being displayed.

**To Reproduce**
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):
    def build(self):
        return Label(text="Hello")

if __name__ == '__main__':
    MyApp().run()
with Kivy 2.1.0.

**Code and Logs and screenshots**
```python 3.9
from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):
    def build(self):
        return Label(text="Hello")


if __name__ == '__main__':
    MyApp().run()

[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2

Process finished with exit code -1073741819 (0xC0000005)

```

**Additional context**

**Comment by kuzeyron** [comment]
Can you ask the same question on Discord? And later on update this issue ticket.
Discord link: [https://chat.kivy.org](https://chat.kivy.org)
