### ISSUE TITLE
Crash (seg fault) when Font size overflow 

### ISSUE THREAD

**Issue by SanAndreyas** [kivy/kivy#7899]
Software Versions
Python: 3.6.8 - 3.10.4
OS: Windows 10
Kivy: 2.0 to 2.2
Kivy installation method: master from github.com ( latest )

Describe the bug
Segmentation fault when font size of a widget overflows.
Examples: size of a font on a label goes bigger than the screen or font from a button exceeds the button size

Expected behavior
No segmentation fault

To Reproduce

self.button.font_size = self.button.size[1] * 0.5 -> works
self.button.font_size = self.button.size[1] * 0.6 -> crashes

Additional context
I tested this on Mac and Linux and the issue is not reproducible. Only on Windows 10 it crashes.
It crashes with both NVIDIA or AMD hardware.
I use SDL2 for everything (text,video,sound) on any of the 3 OS mentioned above.
I use the latest version of SDL, so for fonts today it is: SDL2_ttf-2.0.18.
The workaround for this is to make sure that font does not exceed certain size.

**Comment by SanAndreyas** [comment]
i have further investigated this. the bug is inside SDL2_ttf-2.0.18, nothing to do with Kivy.

**Comment by SanAndreyas** [comment]
As i read in this ticket here https://github.com/kivy/kivy/issues/8108 , seems this bug was fixed starting from [2.19.2](https://github.com/libsdl-org/SDL_ttf/releases/tag/prerelease-2.19.2) (Fixed crash when loading fonts at certain sizes on Windows) https://github.com/libsdl-org/SDL_ttf/issues/201

**Comment by misl6** [comment]
We later updated (7 months ago) our `SDL_ttf` Windows dependency to `2.20.2`.
`pip install kivy-deps.sdl2==0.6.0` fixes the issue?

**Comment by SanAndreyas** [comment]
Yes
