### ISSUE TITLE
The solution of not displaying candidate words in Chinese input method.

### ISSUE THREAD

**Issue by as564335sa** [kivy/kivy#7910]
Kivy doesn't seem to be able to display input method candidates，Now there are APIs in sdl2 that can open this function，is `SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1")`
I tested that add this code to `_window_sdl2.pyx`,`setup_window(...)` and it worked. Can you add this code to the master version?

**Comment by DDknightLEI** [comment]
> Kivy doesn't seem to be able to display input method candidates，Now there are APIs in sdl2 that can open this function，is `SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1")` I tested that add this code to `_window_sdl2.pyx`,`setup_window(...)` and it worked. Can you add this code to the master version?

HI,bro.I 've got same issue, pls share your method, thx
