### ISSUE TITLE
The problem of Kivy Python to display Persian and Arabic text

### ISSUE THREAD

**Issue by goldaaa** [kivy/kivy#7918]
When I use Farsi or Arabic, it displays multi-line text from bottom to top.

I face this problem when I use a large number of Persian texts.
This problem does not occur in short texts because the screen does not send it to the next line.
In a long text, when the screen is reduced, it goes to the next line, it faces this problem.

<code>
from kivy.lang import Builder
import arabic_reshaper
from bidi.algorithm import get_display
from kivymd.app import MDApp

KV = '''
#:import arabic_reshaper arabic_reshaper
#:import get_display bidi.algorithm.get_display

Screen:

    BoxLayout:
        orientation: "vertical"

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            index:1

            MDCard:
                id: md_card
                orientation: "vertical"
                padding: "8dp"
                size_hint: None, None
                size: 300, 300
                #pos_hint: {"center_x": .5, "center_y": .5}

                MDLabel:
                    font_name: 'font/Sahel.ttf'
                    text: get_display(arabic_reshaper.reshape('تست نام'))
                    halign: "right"

                MDSeparator:
                    height: "1dp"

                MDLabel:
                    font_name: 'font/Sahel.ttf'
                    halign: "right"
                    text: get_display(arabic_reshaper.reshape('این یک متن فارسی صرفا برای تست است در کیوی نمایش آن اشتباه از پایین به سمت بالا است.'))

'''

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

Test().run()
</code>
It should display top to bottom, thanks in advance for any help.

<p>
This is the image you see in the output of this code.
</p>
<img src="https://i.stack.imgur.com/0aBTc.png"/>

<p>what i want:</p>
<p>Using the image editing program, I moved the text to make it correct.</p>
<p>What I want to display properly, from top to bottom.</p>

<img src="https://i.stack.imgur.com/hef4g.png"/>

**Comment by goldaaa** [comment]
Lib\site-packages\kivy\core\text\__init__.py line 760


    def refresh(self):
        '''Force re-rendering of the text'''
        self.resolve_font_name()

        # first pass, calculating width/height
        sz = self.render()
        self._size_texture = sz
        self._size = (sz[0], sz[1])


        # if no text are rendered, return nothing.
        width, height = self._size
        # print('width, height : ', width, height)
        if width <= 1 or height <= 1:
            self.texture = self.texture_1px
            return

        # create a delayed texture
        texture = self.texture
        if texture is None or \
                width != texture.width or \
                height != texture.height:
            texture = Texture.create(size=(width, height),
                                     mipmap=self.options['mipmap'],
                                     callback=self._texture_fill)
            texture.flip_vertical()
            texture.add_reload_observer(self._texture_refresh)
            self.texture = texture
        else:
            texture.ask_update(self._texture_fill)


This discussion is for guidance and help to solve problems
I spent a lot of time to find the problem. It seems that if it shows this part like a mirror, the problem will be solved.
Changes in texture.
Please fix it so that Persian and Arabic can be displayed without problems. Thanks

**Comment by goldaaa** [comment]
If you have a good solution for this part, please send it so that I can reverse the text upwards like a mirror.

**Comment by mablue** [comment]
IT IS NOT SOLVED

**Comment by goldaaa** [comment]
It has been solved for Farsi speakers, soon it will be defined on the reference library (kivy) of Persian and Arabic languages.
  Dear Iranians, currently you can only use kivyir.

برای فارسی زبانان حل شده است، به زودی بر روی کتابخانه مرجع (kivy) زبان فارسی و عربی تعریف می‌گردد.
ایرانی های عزیز در حال حاضر فقط میتوانید از kivyir استفاده کنید.
