### ISSUE TITLE
Coordinate system for Kivy

### ISSUE THREAD

**Issue by Prakash1124** [kivy/kivy#7923]
First thing First a humble salute to all the contributors of such a nice Python module. You guys and gals are simply awesome.

I started learning about this module recently when I came across it and was 'wowed' by it.  But I have a very serious question why did you guys coordinate system like this i.e. left to right x increases and bottom to top y increases. I understand that thinking about the first quadrant in the graph origin lies at bottom left hand corner. But normal human intuition is to write from left to right and top to bottom. So wouldn't it be more suitable to place origin at top left hand corner and place widgets accordingly.

If I place a widget on the screen with fixed dimension instead of it appearing at bottom left corner if it appeared at top left corner it would have been more intuitive. And as I place another widget the original widget's 'y' doesn't change. The next widget will appear on the same screen larger value of 'y'.

Let me give you an example from my personal experience. I was trying to create a form using kivyMD:
![image](https://user-images.githubusercontent.com/108631726/180571759-348636b3-ded1-4935-aa5d-89841f05819a.png)

When the 'Get OTP' button is pressed, it should remove the button widget and add a boxlayout below the existing one with some addition widgets of MD text field and new button. I added the boxlayout and it was appended to the screen below the original Boxlayout and occupied around 30% of the screen (original Boxlayout is already bigger than 50%, otherwise kivy would have divided it 50-50). But the widgets in the freshly appearing Boxlayout are aligned to the bottom. I had to write additional codes to aligned it to top( insert another Boxlayout and give its position, to make appearance uniform on screen). If it would have been top aligning then with the insertion of box layout my work would have been finished.

Please understand I am a novice and the whole concept of bottom to top is very counter intuitive to me atleast ( I think most new users would also be struggling to understand and create layout).

Please give a thought to it and if possible talk to some new users and try to understand if they too face the same problem like me.
Afterall we all are believers of the philosophy - 'Simple is better than complex'.

**Comment by T-Dynamos** [comment]
What! Isn't there's `pos` or `pos_hint` in `RelativeLayout` and `anchor_x` or `anchor_y` in AnchorLayout

You can algin your boxlayout by using RelativeLayout ?

**Comment by Prakash1124** [comment]
I achieved what I wanted. I was trying to draw attention towards a more intuitive coordinate system I.e. what Tkinker or Flutter uses.
![image](https://user-images.githubusercontent.com/108631726/180596925-ff4dd20d-651e-43ab-aa3c-d200dd144a64.png)

**Comment by Julian-O** [comment]
Welcome to programming, where different people's intuitions are different.

https://computergraphics.stackexchange.com/questions/8178/why-is-pixel-0-0-at-the-top-left-of-some-formats-and-bottom-left-of-others

Closing as no change required.
