### ISSUE TITLE
How to get keyboard height? 

### ISSUE THREAD

**Issue by Frederiklopas** [kivy/kivy#7931]
Hi! 
Window.keyboard_height returns 0 (on android and windows) , probably because of SDL2
so, how to get keyboard height?

**Comment by vrepo54** [comment]
Hi. I was confronted to the same issue and ended up using `android.get_keyboard_height()`. Strangely, it returns some negative value when the keyboard is not there, but when the keyboard is on the screen, the value given seems to be the right one

**Comment by RobinPicard** [comment]
Hi! You can use `android.get_keyboard_height()` on Android

**Comment by antorix** [comment]
> Hi! You can use `android.get_keyboard_height()` on Android

It doesn't work either. When I use it, the app crashes. I really wonder if there is any working way to get the height of the keyboard. Or it's impossible in Kivy?

**Comment by Julian-O** [comment]
If you can demonstrate that there is a bug in `android.get_keyboard_height()` and give details of how it crashes, we might be able to tackle it (if it is Kivy's fault).

However, the support question has been answered.
