### ISSUE TITLE
Multiple Buttons Pressed on Kivy with Raspberry Pi

### ISSUE THREAD

**Issue by Dharmenda003** [kivy/kivy#7932]
**Software Versions**Latest
* Python:
* OS:Raspbian Buster
* Kivy:
* Kivy installation method:

I'm trying to make gui from kivy on desktop.

**Unexpected behavior**
I run the program and the GUI comes up. When I click a button, one of two things happens: 1) Another random button gets pressed, and then the button I clicked gets pressed. 2) The button I clicked gets pressed twice. It's not a problem with my mouse, as I've used different mouses and the problem persists.

The thing is that the problem doesn't occur if I run it on my Windows, it only happens on the raspberry pi. 

**Code and Logs and screenshots**

python3 /home/pi/kivy_venv/share/kivy-examples/demo/kivycatalog/main.py

![2022-07-30-131707_800x600_scrot](https://user-images.githubusercontent.com/110280502/181880967-a5ce0ced-a595-46e5-a2ec-9ac9e66f08a7.png)

![2022-07-30-132113_800x600_scrot](https://user-images.githubusercontent.com/110280502/181881337-f54e629f-432b-4906-8101-297427dda84b.png)

**Comment by drahba** [comment]
You may be repeating something somewhere else in your code. Did you check the rest of your code for double action. You may also try kivy 2.1.0. Can you provide a part of the code that replicates your problem?
