### ISSUE TITLE
Persian problem from the bottom to the top of the text.

### ISSUE THREAD

**Issue by goldaaa** [kivy/kivy#7933]
I couldn't solve it, please help if you have any solution, thanks in advance.
Link to previous report:
https://github.com/kivy/kivy/issues/7918

**Comment by goldaaa** [comment]
برای کار با زبان فارسی از kivyir استفاده کنید.
Use Kivyir for Persian.

pip install kivyir --user

[Link GitHub](https://gitHub.com/goldaaa/kivyir)

**Comment by mablue** [comment]
IT IS NOT SOLVED

**Comment by omaryo010** [comment]
I think I have a temporary solution to this problem

**Comment by omaryo010** [comment]
![Screenshot_2023-04-11_05-39-49](https://user-images.githubusercontent.com/130429952/231058216-f8cc2a47-421c-4c8e-ae1d-ef1d2fe66099.png)

**Comment by mablue** [comment]
https://github.com/kivy/kivy/issues/8189#issuecomment-1500206433

**Comment by goldaaa** [comment]
It has been solved for Farsi speakers, soon it will be defined on the reference library (kivy) of Persian and Arabic languages.
Dear Iranians, currently you can only use kivyir.

برای فارسی زبانان حل شده است، به زودی بر روی کتابخانه مرجع (kivy) زبان های فارسی و عربی تعریف می شود.
  ایرانیان عزیز در حال حاضر فقط می توانید از kivyir استفاده کنید.

**Comment by mrthug71** [comment]
i have issue with building kivyir 
my .spec requirements :
requirements = python3==3.10.12,kivy==2.2.1,kivyir==0.1.5
can anyone help to fix this
