### ISSUE TITLE
Save data between app updates.

### ISSUE THREAD

**Issue by gpastal24** [kivy/kivy#7936]
Hello,
Not really a feature request rather than a doc request.
I have been trying to save kivy app data between app updates but I have not managed to do so. 
I read that the data should be saved in the ../ folder but I do not really understand what this means .
The data are stored in json format and I am using standard python, not kivy's storage ,to load and save this json file.

**Comment by misl6** [comment]
Hi @gpastal24 !

[App.user_data_dir](https://kivy.org/doc/stable/api-kivy.app.html?highlight=user_data_dir#kivy.app.App.user_data_dir) is your friend here :)

Data stored in the folder specified by `App.user_data_dir` is kept between App updates.
