### ISSUE TITLE
How to prevent keyboard from closing?

### ISSUE THREAD

**Issue by Frederiklopas** [kivy/kivy#7938]
Hello Kivy community!
Is there a way to open a keyboard for a text field and restrict users to close this keyboard?

**Comment by misl6** [comment]
Hi @Frederiklopas !

I guess you're looking for the `managed` mode: https://github.com/kivy/kivy/blob/59a9352e6c9db078e7d5ac8e87c4d2c8f78ebd30/kivy/uix/behaviors/focus.py#L337

Closing the issue as `support`, but feel free to join our lovely community!
