### ISSUE TITLE
TRON like procedural vector UI components

### ISSUE THREAD

**Issue by cederom** [kivy/kivy#7939]
**Is your feature request related to a problem? Please describe.**
Currently UI components does not look really attractive to end users. Most people will, unfortunately, assess the application by its look. After getting into Kivy internals I can more and more understand reasons behind current design.

**Describe the solution you'd like**
When components are rendered directly with OpenGL it may be worth turning into a procedural vector UI generation. This would scale perfectly no matter what display size / resolution/ dpi resulting in high quality TRON-like-UI (kind of Sci-Fi movies). Also such components could provide high-level access and functions like these known from FLTK, Qt, GTK, etc.

**Describe alternatives you've considered**
I got the idea to use some minimalistic but good looking library (LVGL) to implement UI components before I got into an idea of native procedural components library. 

**Additional context**
* Is there any sort of UI components library already available built on top of Kivy primitives like Calendar / Agenda?
* What could be performance impact of such nice looking UI components? What are dangers?

**Comment by cederom** [comment]
That would be trivial if Kivy supported vector graphics like SVG.. does it?

**Comment by tshirtman** [comment]
Kivy has support for SVG as a canvas instruction, though it's not perfect, it's good enough for many things.
But kivy itself uses vector like functions to draw, so if you don't want to use textures, but only instructions, you are entirely free to do so, with or without SVG.

**Comment by cederom** [comment]
Thank you @tshirtman :-) Which one of these would be faster? SVG or Vector Python Instructions? :-)

I really start to like Kivy :-) :-)

**Comment by drahba** [comment]
You may try kivyMD - material design library built on top of  kivy, bu tit is slower than kivy in performance. It includes calendar as well. You may also use kivycalendar which you may find primitive but it works just fine.

**Comment by cederom** [comment]
Thank you @drahba :-) Yesterday I also heard about kivyMD on the mailing list.. so I will give it a try :-) Do you know the downsides and performance impact of the kivyMD? Definitely a large good looking library of components for rapid mobile development is what I need right now.. especially I have wasted too much time for JS bullshit and will never come back there again.. I guess Kivy even with MD would be faster, more versatile, and most of all possible to maintain :-)

**Comment by cederom** [comment]
Allright, so the switch to KivyMD is trivial and gives me all I need, Thank You! :-)

Still, I think that SVG instead PNG (or as option) as basic graphics primitives in pure Kivy would result in far better graphics quality and first-contact perception :-)

Except for components quality independent of display size and dpi it should have smaller footprints and it can be animated + scripted :-)
