### ISSUE TITLE
Font Rendering Issue on Windows when dynamically given

### ISSUE THREAD

**Issue by Arjun-Somvanshi** [kivy/kivy#7947]
**Software Versions**
* Python:
* OS: Windows
* Kivy: 2.1.0
* Kivy installation method: pip install kivy[base]

**Describe the bug**
When font_size is given as shown in the code example, the app hangs and doesn't give any logs before crashing.

**Expected behavior**
Font changing dynamically 
**To Reproduce**
This code can be run to reproduce:

**Code and Logs and screenshots**
```python
from kivy.app import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
#: import Window kivy.core.window.Window
GridLayout:
    cols: 1
    size_hint_max_x: dp(800)
    size_hint_min_x: dp(340)
    spacing: dp(30)
    padding: dp(20)
    Label:
        size_hint_y: 0.1
        text: 'Reminiscor'
        font_size: sp(280) if Window.size[1] < dp(670) else sp(295)
'''))
```

**Additional context**
If this code is executed using kivy version 2.0.0 there is no issue.

**Comment by mp-007** [comment]
can you used 
```
font_size: sp(280) if app.root_window.height < dp(670) else sp(295)
```

instead of 

```
font_size: sp(280) if Window.size[1] < dp(670) else sp(295)
```

**Comment by Julian-O** [comment]
@Arjun-Somvanshi Can you please confirm if this is still an issue in Kivy 2.2.1, and if the change suggested helps?

**Comment by Julian-O** [comment]
I tried this code on Windows 11 with Kivy 2.2.1, and it did not crash or hang for me, no matter how tall the window was. Closing as Can't Repro.

If that is in error, please let us know.
