### ISSUE TITLE
Use `logging.addLevelName` to define TRACE

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#7957]
Kivy's logger is based on the standard "batteries included" logging module in Python, but it takes a number of non-standard approaches, and doesn't play well with others.

One small example is that it defines a custom log level, `TRACE`, but does not use the official way to do this: `logging.addLevelName()`.

As a result:
* The custom log handler is more complex.
* Other third-party log handlers cannot emit the message appropriately (I believe it appears as 'Level 9'.)

**Describe the solution you'd like**

1. `logger.py` should call `logging.addLevelName(9, "TRACE")`
2. `logger.py` should continue to monkey-patch the standard logging library to add `TRACE` and `trace()`

**Describe alternatives you've considered**

1. Simply remove the custom log level, `TRACE`. The Python documentation [explicitly warns against libraries defining custom log levels](https://docs.python.org/3/howto/logging.html#custom-levels).

2. Add the custom log level, `TRACE` through the official mechanism, but remove the monkey-patching.

Both of these alternatives would be cleaner and play better with others, but may affect existing Kivy apps, so I don't think they are acceptable.

3. Do the changes as suggested, but *also* deprecate the `TRACE` level, recommending `DEBUG` instead, so it can be removed in the distant future.

I like this approach, but doubt I have the political will to introduce it, so I will settle for a "don't break anything" approach.

**Additional context**

(This is trivial improvement, but it is a necessary precursor for some other refactorings I would like to do, and a good minimal bugfix to test my development environment and processes.)

**Comment by misl6** [comment]
Closed via #7958
