### ISSUE TITLE
Refactor ColouredFormatter to separate concerns

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#7959]
`logger.py` defines a class called `ColoredFormatter`.

The name of the class is simple, but the actual class is given several responsibilities:

1. As the name suggests, (optionally) add color codes into a logRecord.
2. Split messages at colons, which mimics the functionality of the standard log hierarchy.
3. Translate level 9 log records into Trace log records. 

Meanwhile, much of the work related to color codes has leaked outside of the class; it isn't self-contained.

Finally, in order to achieve the first two items, it performs a `deepcopy` on the parameters, which causes #7585 and #7528.

**Describe the solution you'd like**

* The code in #7957 takes care of the 3rd point, by assigning the responsibility to the `logging` class.
* Define a `ColoredLogRecord` class that encapsulates a `LogRecord`, and provides a shim for all the methods and attributes, except the levelname property, for which it adds color code sequences.
* Move `formatter_message`, `COLORS` and the individual colors and the ANSI (?) color sequences into the class as 'private' attributes.
* Replace the color range with a more modern enumerated type.
* Define a `ColonSeparatedLogRecord` class that similarly encapsulates and shims a LogRecord, except the msg property is split by colons.
* Replace `ColoredFormatter` with `KivyFormatter` (still looking for a better name - something that acknowledges it is more than just color). It takes the log record that needs to be emitted, optionally wraps it in a `ColonSeparatedLogRecord`, wraps the result in a `ColonSeparatedLogRecord`, and passes that to the standard formatter.
* Note: There is no longer a need to do a `deepcopy`, which should fix the bugs listed above.
* For some reason, the `COLORS` table is being exported by the `__all__` declaration. Make an alias at the top level of the file to support that.

**Describe alternatives you've considered**

* I can't imagine why anyone would import the `COLORS` table. If we were confident it wasn't being used, we could stop declaring it at the top level of the file and exporting it. The only reason I would add the alias is just in case someone is using it in a way I can't predict. 
* The standard way of giving context to a log message would be with a sublogger: `logging.getLogger("kivy.GL").info("Texture max units: %d", x)` The Kivy logger eschews this, sticking with the root logger and using colon separators: `Logger.info("GL:Texture max units <%d>", x)`. This is less powerful (e.g. I can't turn suppress the GL logging which keeping other logging). It also breaks log messages from third-party libraries that use colons in their messages. I have some half-baked ideas for a logHandler that automatically mangles colon-separated `LogRecords` from the Kivy logger into standard subloggers, and then formatting them back to look identical to the current system for those who don't override the defaults. If such a system was implemented, then `ColonSeparatedLogRecord` would be obsolete.

**Comment by Julian-O** [comment]
I have some cleaned up code ready for this. Just waiting to see how my first PR is received before submitting.

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/kivy/pull/7962
