### ISSUE TITLE
Button detects press outside of its borders when running on Ubuntu

### ISSUE THREAD

**Issue by MichaelJFishman** [kivy/kivy#7960]
**Software Versions**
* Python: 3.10.0
* OS: Ubuntu 20.04.4 LTS
* Kivy: 2.1.0
* Kivy installation method: `pip install "kivy[full]" kivy_examples`

**Describe the bug**
A button press is detected whenever I touch my trackpad, even if the cursor is not on top of the kivy window and the kivy window is not being focused on.

**Expected behavior**
A button press is detected only when the trackpad is clicked and the cursor is on top of the button.

**To Reproduce**

Run the following code on Ubuntu. There was no `.kv` file in the same directory.

```python
from kivy.uix.stacklayout import StackLayout
from kivy.uix.button import Button
from kivy.app import App

class MyGame(StackLayout):
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self.add_widget(Button(text="Click me!"))

class MyApp(App):
    def build(self):
        return MyGame(size=(800, 800))

if __name__ == "__main__":
    MyApp().run()
```

The log is in [this](https://gist.github.com/MichaelJFishman/19c30872d2ed3c3bccb1b90ed0de2b3d) gist.

**Additional context**
I do not experience this bug when running the same code on a macbook. I also do not experience this bug when running the [showcase](https://github.com/kivy/kivy/blob/master/examples/demo/showcase/main.py) example and going to the buttons page.

[This](https://stackoverflow.com/questions/65659261/how-do-i-fix-kivy-buttons-being-pressed-outside-of-their-borders) stackoverflow and [issue 7932](https://github.com/kivy/kivy/issues/7932) describe similar issues when running on raspberry pi.

**Comment by drahba** [comment]
I tried your code in ubuntu 20.04 LTS, kivy 2.1.0, pycharm2022 venv - python 3.8.10, but I was not able to replicate the bug you indicate.

**Comment by RobertFlatt** [comment]
@MichaelJFishman Is the app full screen, or running in a window?

**Comment by drahba** [comment]
App was running in a window on default size

**Comment by RobertFlatt** [comment]
I suspect the issue is the number of input devices specified in Kivy config.

I can't find the right docs (!) but this is the general topic https://kivy.org/doc/stable/installation/installation-rpi.html#using-official-rpi-touch-display

As I remember the docs show an app can have multiple touch inputs. I don't think this is true, or maybe it depends on the inputs.

Try removing inputs in the config.  Sorry this is kinda fuzzy, not my primary knowledge.

**Comment by MichaelJFishman** [comment]
@RobertFlatt 
This issue occurs with the window at the default size, full screen, and all the custom sizes I've tried.

**Comment by MichaelJFishman** [comment]
@RobertFlatt Editing the config fixed it, thanks!

My config had a section

```ini
[input]
mouse = mouse
%(name)s = probesysfs
```

After commenting out the second line, so that I have
```ini
[input]
mouse = mouse
; %(name)s = probesysfs
```

I no longer have this issue.

[probesysfs.py](https://github.com/kivy/kivy/blob/master/kivy/input/providers/probesysfs.py)  looks to have relevant information, but I haven't read it since my issue is now fixed.
