### ISSUE TITLE
Kivy.org is down

### ISSUE THREAD

**Issue by jlarsen-usgs** [kivy/kivy#7967]
Hello,

I'm raising this issue to make the developers aware that kivy.org (including the API documentation) has been down since yesterday morning. I've been trying to access class documentation for an application I'm building and have not been able to connect with the website.

Thanks

**Comment by misl6** [comment]
Hi @jlarsen-usgs !

Thank you for the heads up, we are tracking the issue here: https://github.com/kivy/kivy-website/issues/141
