### ISSUE TITLE
Add environment variable to make logger code testable.

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#7970]
**Is your feature request related to a problem? Please describe.**

`kivy.logger` can be broken into two parts:

* Definitions: Define all of the classes and other definitions required to implement the Kivy logger system.
* Installation: Install it as the primary logging code for the entire system (as a side-effect of import) by monkey-patching the `logging.root` and `sys.stderr`.

Unfortunately, the installation part makes it very difficult to unit-test the definitions. The classes are already installed and running before they can be broken out individually.

I am working on a number of changes to the logging code, and I want to be sure it is properly tested - it is part of the fundamental core that every Kivy app uses.

**Describe the solution you'd like**

1. Define an undocumented, unsupported environment variable *for testing only* that turns off the installation of logging.
2. Add a skipif marker to logging tests that only work if the environment variable is appropriately set,
3. Add a custom pytest marker to those tests so that they can be selectively run when the environment variable is set.
4. Modify the ci scripts:
   * to run the unit tests twice:
        * Once with the variable not set, which will run the majority of the tests, and skip the special logging ones.
        * Once with the environment variable and the custom marker set, so that only those tests will be run.
   * merge the coverage data so only one report is produced.

**Describe alternatives you've considered**

* My first approach was to create a separate file, `logginglib.py`, and gradually migrate the definitions into it, as it was refactored, eventually leaving only the installation code in `kivy.logger`. `test_logginglib.py` could then test the definitions in isolation.

  However, this was destined to failure for two reasons:

  1. In `test_logginglib.py`, when the test-case runs and imports `kivy.logginglib`, it implicitly imports `kivy.__init__.py` which imports `kivy.logging`, and runs the installation code.

  2. Even worse, `pytest` is importing `kivy.__init__.py` implicitly before the tests run. I haven't figured exactly where. It is before `conftest.py` is called, and even before `tests.__init__.py` is called.

* This can't be controlled by the config file because the logger is installed before the config file is read.

* This can't be controlled in conftest.py or as a pytest fixture, because the logging is installed so early.

* The env variable could be properly documented and supported, rather than being unsupported, as some users would like this. I am in favour of making that an opton, but I would like to offer several levels and supporting classes for clients to choose their level of adoption of the Kivy logging system, and I can't provide that until I can test the supporting classes: This is temporary scaffolding, that is intended to be replaced by a properly documented feature in the short-term. It is also an experiment to make sure creating custom markers in pytest doesn't interfere with other tests.

**Comment by misl6** [comment]
Closed via #7971
