### ISSUE TITLE
Fixing the Persian language problem in kivy

### ISSUE THREAD

**Issue by goldaaa** [kivy/kivy#7977]
I made the Persian page in kivy, please let me know if the problem is fixed so that I can send the changed codes and you can fix the required parts.

**Comment by misl6** [comment]
Can you better describe? If you have a PR, feel free to post it.

**Comment by goldaaa** [comment]
Can you send messages in Telegram?
ID telegram: https://t.me/goldaaa
If you can't let me know.


In order to add Persian, I modified 2 parts of the base label and markup codes to change the direction.

I wrote a multi-line one-page code to display Persian texts beautifully and without problems.

**Comment by tshirtman** [comment]
Please read
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

To know how to submit a change here as a Pull Request, no need to go to telegram, this website is designed to allow you to easily contribute a change to the project.

**Comment by goldaaa** [comment]
> لطفاً [https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-requests/creating-a-pull-requests را بخوانید.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
> 
> برای اطلاع از نحوه ارسال تغییر در اینجا به عنوان یک درخواست کششی، بدون نیاز به مراجعه به تلگرام، این وب سایت به گونه ای طراحی شده است که به شما امکان می دهد به راحتی تغییراتی را در پروژه انجام دهید.

I am aware of the explanation given by you, my dear friend, I wanted to provide you with a message for more information, but there is no problem, I will try to mention them here.

**Comment by misl6** [comment]
Hi @goldaaa !
We will be happy to see your PR when ready!

**Comment by goldaaa** [comment]
Changes:
https://github.com/kivy/kivy/commit/4e022ff434e1697a79136f5b2caa4bb3f7ceba09
https://github.com/kivy/kivy/commit/128d22841dbc2c477cdf67970f9afa46e09724da

I also wrote codes to improve the work so that the required items are fixed and displayed beautifully in Farsi. 
https://github.com/goldaaa/PersianCleaning

# ______________________________
Give access to the base of the label so that it can be added to the default font in the first place.
To do this, before calling the libraries, put this code at the beginning of the main.py file.
`
name = "Sahel"
fn_regular = "font/Sahel.ttf"
font = {"fn_regular": fn_regular, "fn_italic": None, "fn_bold": None, "fn_bolditalic": None}
    if fn_bold: font['fn_bold'] = fn_bold
    if fn_italic: font['fn_italic'] = fn_italic
    if fn_bolditalic: font['fn_bolditalic'] = fn_bolditalic
    text._default_font_paths = list(font.values())
    text.DEFAULT_FONT = name
    text.LabelBase.register(name=name, **font)
    theme_font_styles.append(name)
`
Then we use the libraries we have, such as:
from ...
(This allows the font to be added at the very beginning and does not need to be repeated and recalled every time the label is called.)

**Comment by goldaaa** [comment]
![index](https://user-images.githubusercontent.com/109505057/187025506-5f22dbe9-c927-4e76-9fd0-35a322bfdb1d.png)

Tested prototype.

**Comment by goldaaa** [comment]
> سلام@goldaaa! ما خوشحال خواهیم شد که در صورت آماده شدن روابط عمومی شما را ببینیم!

Hello dear friend @misl6 again, if you have any questions, I am at my service
If you need a font let me know and I will upload it for you to test yourself.

**Comment by goldaaa** [comment]
Hello @misl6 , is there a problem to modify the codes to make the Farsi language correct that you haven't fixed yet?

**Comment by goldaaa** [comment]
Hello @misl6 , I made this problem myself.

برای کار با زبان فارسی از kivyir استفاده کنید.
Use Kivyir for Persian.

pip install kivyir --user

[Link GitHub](https://gitHub.com/goldaaa/kivyir)
