### ISSUE TITLE
Remove undocumented sys._kivy_logging_handler

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#7981]
**Software Versions**
* Python: N/A
* OS: N/A
* Kivy: 2.10
* Kivy installation method: N/A

**Describe the bug**
`logger.py` looks to see if the client has monkey-patched `_kivy_logging_handler` into the `sys` module. If so, it will add it as a handler.

Despite being present since the initial commit, this attribute is not mentioned in any documentation.

**Expected behavior**

One approach would be to document the attribute.

However, with #7978 in the process of being completed, it is no longer necessary for a client to go to such extreme lengths as monkey patching a core Python module. They can simply directly add their favourite handler (or handlers!) straight to the root logger.

Furthermore, I tried to find examples of it being used. The attribute is not set or used anywhere else in the Kivy repository. After 10 minutes searching, I could only find [one public use of it in the wild](https://github.com/cropleyb/pentai/blob/bbd32864cabce9ba5cb1051fa9d78d69c8feb5e5/main.py).

So I instead recommend deprecating and removing the attribute. 

Does it make any sense to deprecate something that was never actually supported in the first place? I would be tempted to simply replace it with an assert statement (or a `warnings.warn` call?) that fails if the attribute is present, and gives instructions to the developer to call `logging.root.addHandler()` instead.

**Comment by misl6** [comment]
Fixed via #7988
