### ISSUE TITLE
Kivy Logger doesn't take into account non-string messages

### ISSUE THREAD

**Issue by misl6** [kivy/kivy#7984]
**Software Versions**
* Python: *
* OS: *
* Kivy: `master`
* Kivy installation method: `source`

**Describe the bug**

Kivy Logger doesn't take into account non-string messages, and fails with:
`AttributeError: ... object has no attribute 'replace'`

**Expected behavior**
As specified in [Python Docs](https://docs.python.org/3/howto/logging.html#using-arbitrary-objects-as-messages), also an arbitrary object could be used as a message.

**To Reproduce**
```python
from kivy.logger import Logger
...
...
Logger.info(dict())
...
...
```

**Code and Logs and screenshots**
```python
   File "/Users/mirko/Documents/projects/kivy/kivy/logger.py", line 433, in format
     self._coloring_cls(ColonSplittingLogRecord(record)))
   File "/Users/mirko/Documents/projects/kivy/kivy/logger.py", line 390, in __init__
     self.msg = self._format_message(self.msg)
   File "/Users/mirko/Documents/projects/kivy/kivy/logger.py", line 364, in _format_message
     return message.replace(
 AttributeError: 'dict' object has no attribute 'replace'
```

**Additional context**

CC: @Julian-O

**Comment by Julian-O** [comment]
I am on it. (I wonder if this used to work. I will check that too.)
