### ISSUE TITLE
Kivy camera doesnt work 

### ISSUE THREAD

**Issue by Oday000o** [kivy/kivy#8009]
**Windows 10**
* Python: 3.9

It's a bad problem pls help me it's always when I try to make a Camera app with kivy it's work at all

the code 

**To Reproduce**
from kivy.app import App
from kivy.uix.camera import Camera 
class MYApp(App):
    def build(self):
        return Camera()*.

the output 
Waring: BGRA texture support is not available 
#

**Comment by RobertFlatt** [comment]
This forum is not for support questions.
Generally you should submit support questions on Google Groups or Discord.
And post the full log.

It looks like the camera provider used is defaulting to an unsupported format.

This works on Windows with openCV as the camera provider.
```
from kivy.app import App
from kivy.uix.camera import Camera
class MYApp(App):
    def build(self):
        self.camera = Camera()
        return self.camera

    def on_start(self):
        self.camera.play = True

MYApp().run()

```

**Comment by Oday000o** [comment]
Sorry but that's didn't work yet

**Comment by Oday000o** [comment]
but even that did not work
