### ISSUE TITLE
Re-using templates in multiple Files

### ISSUE THREAD

**Issue by zaheerkzz** [kivy/kivy#8014]
Hi, I am new to kivy. I been working on a project and I have not find any solution where i can use kv templates in different files as well there is no help in documentation for Re-using code (.kv) in multiple files like in Django where we can import templates and use Navbar, Header and Footer in all files.

If anyone know such solution please help me out as well i search on google and docs but no help.

also i want to know if i can use ScreenManager for (.kv) files in seprate files.
currently i have like this, an i have to write styles for all screens in one file.

WindowManager:
    -SplashWindow:
    -LoginWindow:
    -RegisterWindow:
    -ForgetPassword:
    -Trail:
    -Home: 

But i think there should be a solution where i can code in different files for each screen and use in WindowsManager.

thank you

**Comment by kuzeyron** [comment]
It's there: [Kivy Language](https://kivy.org/doc/stable/api-kivy.lang.html#include-file)
