### ISSUE TITLE
from kivy import App from kivy.uix.button import Button

### ISSUE THREAD

**Issue by lAZCENKO** [kivy/kivy#8018]
**Software Versions**
![Снимок экрана 2022-09-26 в 0 12 35](https://user-images.githubusercontent.com/90057901/192165887-3d3a6468-1353-4bf3-bc1e-e804778f1bd1.png)
![Снимок экрана 2022-09-26 в 0 12 53](https://user-images.githubusercontent.com/90057901/192165889-d400c622-aaaf-4c3b-aab7-9da38c37a2f9.png)
### ### ****
* Python:3.10
* OS:MAC OS 10.13.6
* The module is installed pip updates are installed* 
all errors and code are shown in the figures above

**Comment by faris4017** [comment]
from kivy.app import App 
this one is right 


At bottom 
MyApp().run()
or
app = MyApp()
app.run()

**Comment by lAZCENKO** [comment]
No. No matter what I write, the same result

**Comment by misl6** [comment]
Also see: https://kivy.org/doc/stable/examples/gen__application__app_with_build__py.html
