### ISSUE TITLE
kivymd AttributeError: 'NoneType' object has no attribute 'ids'

### ISSUE THREAD

**Issue by laureion12** [kivy/kivy#8020]
**Software Versions**
* Python: 3.10
* OS: Windows 10

Hello,

I have a simple program that calls a function which updates a text Label. If I call the function by pressing a button it works. However, if I call the function from another function in py file I receive the error in the subject. Could you please tell me how can I call the function from another function so I don't receive the error?

kv file
--------------------------
```python
MDBoxLayout:
    orientation: 'vertical'

    MDScreen:

        MDSmartTile:
            box_color: 1, 1, 1, .2
            pos_hint: {"center_x": .5, "center_y": .5}
            size: self.size
        MDLabel:
            id: p1Label
            text:'button is not pressed'
            bold: True
            font_size: 30
            halign: 'center'
            valign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            pos_hint: {'center_x': 0.5, 'center_y': 0.95}
            outline_color: (0,0,0)
            outline_width: 4
        MDRaisedButton:
            id: creditButton
            text: 'Press me!'
            pos_hint: {"center_x": 0.2, "center_y": 0.05}
            size_hint: 0.1, 0.05
            on_press: app.PressMe()
            font_style: 'Button'
```

py file that works
-----------------------

```python
from kivy.lang import Builder
from kivymd.app import MDApp

class TestApp(MDApp):

	def build(self):
		self.title = 'TestApp'
		self.theme_cls.theme_style = "Dark"
		self.theme_cls.primary_palette = "Indigo"
		#self.theme_cls.accent_palette = "Red"
		return Builder.load_file('test.kv')

	def PressMe(self):
		self.root.ids.p1Label.text = 'You pressed the button'

TestApp().run()
```

py file that does not work
-----------------------------

```python
from kivy.lang import Builder
from kivymd.app import MDApp

class TestApp(MDApp):

	def build(self):
		self.title = 'TestApp'
		self.theme_cls.theme_style = "Dark"
		self.theme_cls.primary_palette = "Indigo"
		#self.theme_cls.accent_palette = "Red"
		return Builder.load_file('test.kv')

	def PressMe(self):
		TestApp().PressMe2()

	def PressMe2(self):
		self.root.ids.p1Label.text = 'You pressed the button'

TestApp().run()
```

error
---------------
File "D:\code\python3Workspace\test.py", line 17, in PressMe2 self.root.ids.p1Label.text = 'You pressed the button' AttributeError: 'NoneType' object has no attribute 'ids'

Thanks in advance

**Comment by AnderSchofield** [comment]
You are actually trying to access ids from inside the “APP” class. That will not work, since “ids” only works inside your “root”class, in order to makes references to kv language. You need to declare those functions inside your root class.

**Comment by laureion12** [comment]
Thanks a lot for the help.
