### ISSUE TITLE
Config updating

### ISSUE THREAD

**Issue by mamsdeveloper** [kivy/kivy#8024]
**Software Versions**
* Python: 3.9.0
* OS: Windows 11
* Kivy: 2.1.0
* Kivy installation method: python -m pip install kivy

**Describe the bug**
Config changes dont apply after Config.set() and Config.read() if it called after importing other parts of kivy.
If for Config.filename is local file, Config.write() dont affect on kivy`s state.
It happens because kivy.config.Config initializes before other library part and  them permanently get its condition, so Config changes dont applies.

**Expected behavior**
After Config.read(), Config.set(), Config.update_config() and other methods that change Config condition other kivy parts should update their values

**To Reproduce**
See code block

**Code and Logs and screenshots**

// Don`t work
```python
  from kivy.app import App
  
  from kivy.config import Config
  from config import config
  
  Config.read(config.APP_CONFIG)
  
  App().run()
```
// Works successfully
```python
  from kivy.config import Config
  from config import config
  
  Config.read(config.APP_CONFIG)
  
  from kivy.app import App
  
  App().run()
```

**Additional context**

**Comment by misl6** [comment]
Hi @mamsdeveloper !

This is explained in our docs, and should be not considered a bug: https://kivy.org/doc/stable/api-kivy.config.html#applying-configurations

Instead, if you want to propose a new feature feel free to open a new issue marking it as a feature-request. (We're open to PRs targeting new features and bugfixes)
