### ISSUE TITLE
Same-process services?

### ISSUE THREAD

**Issue by wusspuss** [kivy/kivy#8028]
By default Android runs the [Service](https://developer.android.com/guide/components/services) code in the same process and thread as Activity, but the [kivy/buildozer way of making a service](https://github.com/kivy/python-for-android/blob/develop/doc/source/services.rst) seems to be a separate process for some reason - which adds complexity due to the need for IPC.

I'm wondering if having same Python interpreter keep running in the background would be possible with Kivy, instead of spawning a whole new process. It'd be especially handy since kivy allows [asyncio integration](https://github.com/kivy/kivy/blob/master/examples/async/asyncio_basic.py). Just having the same process keep running in the background could remove a whole class of problems.

**Comment by brvier** [comment]
This would be difficult to achieve especially with the GIL.

**Comment by Julian-O** [comment]
This might belong in python-for-android Issues, but I am closing it here as there is no plan to do this.
