### ISSUE TITLE
Slow startup on android?

### ISSUE THREAD

**Issue by wusspuss** [kivy/kivy#8029]
Tried on Poco x3 NFC and motorola g3 - bare bones helloworld starts equally slowly, about half a second - no big deal of a game but a deal breaker for an app you expect to use often. Is there any mitigation?

**Comment by kuzeyron** [comment]
If you want speed you should stick with Java. The way it runs the Kivy applications on your device is Python through Java. The amount of time it takes is getting better as devices are much faster today than five years ago + some optimizations in the code.
