### ISSUE TITLE
[Ubuntu Touch 16.04] : Posible?

### ISSUE THREAD

**Issue by jhay06** [kivy/kivy#8033]
Hi , 
  i would like to ask if this possible , i have ubuntu phone (xenial)

it has 16.04 version of ubuntu and has a python 3.5 on it, i want to compile kivy to add it on my phone so i can build kivy apps for ubuntu touch ? 

how can i compile it on arm64 , ubuntu 16.04 version and python3.5 

Thanks

**Comment by kuzeyron** [comment]
It would be difficult. Out of curiosity I went for the documentation page of Ubuntu Touch:
> Ubuntu Touch supports two kinds of apps: Firstly, native apps have their user interface written in QML or HTML and their business logic in JavaScript, C++, Python, Rust, or Go. Secondly, web apps are special containers to run websites in.  

[https://docs.ubports.com/en/latest/appdev/index.html](https://docs.ubports.com/en/latest/appdev/index.html)

It's a no from me unless you find the missing pieces.

**Comment by jhay06** [comment]
> It would be difficult. Out of curiosity I went for the documentation page of Ubuntu Touch:
> 
> > Ubuntu Touch supports two kinds of apps: Firstly, native apps have their user interface written in QML or HTML and their business logic in JavaScript, C++, Python, Rust, or Go. Secondly, web apps are special containers to run websites in.
> 
> https://docs.ubports.com/en/latest/appdev/index.html
> 
> It's a no from me unless you find the missing pieces.

hi thanks for the reply   but what is the missing piece? yes UT apps written in QML or HTML but it can run also desktop app directly

**Comment by kuzeyron** [comment]
> > It would be difficult. Out of curiosity I went for the documentation page of Ubuntu Touch:
> > > Ubuntu Touch supports two kinds of apps: Firstly, native apps have their user interface written in QML or HTML and their business logic in JavaScript, C++, Python, Rust, or Go. Secondly, web apps are special containers to run websites in.
> > 
> > 
> > https://docs.ubports.com/en/latest/appdev/index.html
> > It's a no from me unless you find the missing pieces.
> 
> hi thanks for the reply but what is the missing piece? yes UT apps written in QML or HTML but it can run also desktop app directly

Porting the SDL2 library to work with Ubuntu Touch and how to launch it. That would be the missing pieces.
Would be cool so you don't have to compile it into apk's.

**Comment by jhay06** [comment]
As per checking with ubport in telegram , SDL is supported , will try to run a simple SDL hello world . and see if it really supported

**Comment by jhay06** [comment]
> As per checking with ubport in telegram , SDL is supported , will try to run a simple SDL hello world . and see if it really supported

can you take a look with this ? https://gitlab.com/zub2/SDLDemo/-/blob/master/ext/CMakeLists.txt  this is SDL Demo app for ubports

**Comment by kuzeyron** [comment]
> > As per checking with ubport in telegram , SDL is supported , will try to run a simple SDL hello world . and see if it really supported
> 
> can you take a look with this ? https://gitlab.com/zub2/SDLDemo/-/blob/master/ext/CMakeLists.txt this is SDL Demo app for ubports

I'm sorry to tell you but this is a path I cannot take. Unless you can donate a Ubuntu phone for the Core-Devs.

**Comment by Julian-O** [comment]
Closing as not planned.

**Comment by jhay06** [comment]
its okay already ported kivy 2.3.0 to UT ,  but i think the 3.0.0 removes the pygame . anyways  will check how can i use the SDL directly without the use of pygame .
