### ISSUE TITLE
Kivy won't install on Python 3.11.0

### ISSUE THREAD

**Issue by Resonanz** [kivy/kivy#8042]
Kivy won't install in a venv created by Python 3.11.0 (released yesterday).

```
(venv_3.11.0) C:\Users\abcde\Python>python -m pip install "kivy[base]" kivy_examples
Collecting kivy[base]
  Downloading Kivy-2.1.0.tar.gz (23.8 MB)
     ---------------------------------------- 23.8/23.8 MB 3.9 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Collecting setuptools
        Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting cython!=0.27,!=0.27.2,<=0.29.28,>=0.24
        Downloading Cython-0.29.28-py2.py3-none-any.whl (983 kB)
           -------------------------------------- 983.8/983.8 kB 3.7 MB/s eta 0:00:00
      ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.3 (from versions: none)
      ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.3.3
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Positive-Endeavour** [comment]
me too

**Comment by tofi1130** [comment]
Same here

**Comment by keremkoseoglu** [comment]
Same here. Had to go back to 3.10.4 for now.

**Comment by Resonanz** [comment]
On Raspberry Pi, I cannot get Kivy to install with 3.10.8. Going back to 3.7.

**Comment by matham** [comment]
The issue on the Pi is different, and probably because Cython doesn't seem to be available (https://www.piwheels.org/project/cython/).

**Comment by Resonanz** [comment]
> The issue on the Pi is different, and probably because Cython doesn't seem to be available (https://www.piwheels.org/project/cython/).

Not sure sorry. Kivy does work very nicely on RPi if Python version is 3.7.3.

**Comment by misl6** [comment]
FYI:

Even if we did not released Kivy 2.2.0 yet (and a new release might not happen soon, as there's still some work to do), there are nighly wheels available with Python 3.11 support.
This is also a nice way to help us to test the latest cutting-edge features, bug fixes, and improvements.

From [Kivy Docs: Nightly & pre-release wheels](https://kivy.org/doc/stable/gettingstarted/installation.html#pre-release-pre-compiled-wheels):

> This will only install a development version of Kivy if one was released to [PyPi](https://pypi.org/project/Kivy/#history). Instead, one can also install the latest cutting-edge Nightly wheels from the Kivy server with:
```
python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/
```
>It is done in two steps, because otherwise pip may ignore the wheels on the server and install an older pre-release version from PyPi.

I will update this issue when we will land in RC phase for 2.2.0 😀

**Comment by GoAmeer030** [comment]
still not working.

**Comment by Zer0-Official** [comment]
not working for me

**Comment by its-all-waves** [comment]
```
> python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
> python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/
```

This as a final step DOES work for me. Blow is what I did leading up to this, in case any of these steps were prerequisites.
(I'm really not concerned with why right now, just needed an old project to run again. So, sorry if some of this is technically wrong. This sequence of events made my app run again.) 

1)
`brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer ` 

2)
`python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/stable.zip"`

3) 
`python -m pip install "kivy[base]" kivy_examples --no-binary kiv`

4)
`python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/`

**Comment by mvoltz** [comment]
It looks like "kivy_deps.sdl2_dev" should be "kivy-deps.sdl2-dev" in whatever sub-process is checking for it.

**Comment by Jim707t** [comment]
If you are waiting for a Kivy version that supports Python 3.11, you can use the Python 3.10 version if you have it installed on your PC. To create a virtual environment using Python 3.10, you can use the following command:

py -3.10 -m venv your_venv_name

This will work if you have one of the Python 3.10 version installed on your machine.

After activate your venv like This: `your_venv_name\scripts\activate`
Just run: `py -m pip install kivy[full] kivy_examples`

I think it should work!

**Comment by jetsgarcia** [comment]
Just downgrade to version 10. I had the same problem but I uninstalled my 3.11.0 and now I'm using 3.10.4

**Comment by Jim707t** [comment]
> 

you can use several python version you will just create visual environment for the version you wanna use

**Comment by NeoNature** [comment]
> If you are waiting for a Kivy version that supports Python 3.11, you can use the Python 3.10 version if you have it installed on your PC. To create a virtual environment using Python 3.10, you can use the following command:
> 
> `py -3.10 -m venv your_venv_name`
> 
> This will work if you have one of the Python 3.10 version installed on your machine.
> 
> After activate your venv like This: `your_venv_name\scripts\activate` Just run: `py -m pip install kivy[full] kivy_examples`
> 
> I think it should work!

Yesss..!! It Works..!!

**Comment by ashb** [comment]
For anyone using poetry this worked for me (replace `win` with your current OS, so it's not a "portable" solution but this was enough for me)

```
poetry source add kivy https://kivy.org/downloads/ci/win/kivy/
poetry source add kivy-deps.sdl2_dev https://kivy.org/downloads/ci/win/deps/sdl2_dev/
poetry add --allow-prereleases kivy
```

**Comment by 7263-8** [comment]
> 

Yeh this works, I re downloaded Python 3.10 , and then added it into the interpreter list of my project. Then the package Kivy was installed successfully.

**Comment by Zackariyya** [comment]
I got it working with python 3.11 by installed the latest cutting-edge:
`python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/master.zip"`

**Comment by cebu23** [comment]
`python -m pip install "kivy[base,media] @ https://github.com/kivy/kivy/archive/master.zip"` also worked for me on Python 3.11 on Windows 11.

I'm a brand new Kivy user (installing it to play with it for the very first time), so not really qualified for troubleshooting - however, I did notice that in the kivy-examples demo showcase, the Bubbles demo fails with ` kivy.uix.bubble.BubbleException: Bubble can only contain a single Widget or Layout` .  On my Linux box running v2.1.0 on Python 3.10.6 the Bubbles demo works fine.

**Comment by zulkar235** [comment]
> Kivy won't install in a venv created by Python 3.11.0 (released yesterday).
> 
> ```
> (venv_3.11.0) C:\Users\abcde\Python>python -m pip install "kivy[base]" kivy_examples
> Collecting kivy[base]
>   Downloading Kivy-2.1.0.tar.gz (23.8 MB)
>      ---------------------------------------- 23.8/23.8 MB 3.9 MB/s eta 0:00:00
>   Installing build dependencies ... error
>   error: subprocess-exited-with-error
> 
>   × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [9 lines of output]
>       Collecting setuptools
>         Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
>       Collecting wheel
>         Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
>       Collecting cython!=0.27,!=0.27.2,<=0.29.28,>=0.24
>         Downloading Cython-0.29.28-py2.py3-none-any.whl (983 kB)
>            -------------------------------------- 983.8/983.8 kB 3.7 MB/s eta 0:00:00
>       ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.3 (from versions: none)
>       ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.3.3
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

**have you solved this problem**

**Comment by MrTeferi** [comment]
Python 3.12 is almost released and we still don't have a stable 3.11 Kivy release... I don't wanna be that guy but is 2.2.0 close to finished yet? Haha

**Comment by HyTurtle** [comment]
Python major releases are done around October/November; so unsure if that counts as almost released

**Comment by SanaMaqsood** [comment]
> FYI:
> 
> Even if we did not released Kivy 2.2.0 yet (and a new release might not happen soon, as there's still some work to do), there are nighly wheels available with Python 3.11 support. This is also a nice way to help us to test the latest cutting-edge features, bug fixes, and improvements.
> 
> From [Kivy Docs: Nightly & pre-release wheels](https://kivy.org/doc/stable/gettingstarted/installation.html#pre-release-pre-compiled-wheels):
> 
> > This will only install a development version of Kivy if one was released to [PyPi](https://pypi.org/project/Kivy/#history). Instead, one can also install the latest cutting-edge Nightly wheels from the Kivy server with:
> 
> ```
> python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
> python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/
> ```
> 
> > It is done in two steps, because otherwise pip may ignore the wheels on the server and install an older pre-release version from PyPi.
> 
> I will update this issue when we will land in RC phase for 2.2.0 😀

i used it and it worked

**Comment by Alli6x** [comment]
pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/

try this code

**Comment by shashwatpritish** [comment]
# I am getting the same error
** This is the error **
```

Collecting Kivy
  Using cached Kivy-2.1.0.tar.gz (23.8 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Collecting setuptools
        Using cached setuptools-67.6.0-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting cython!=0.27,!=0.27.2,<=0.29.28,>=0.24
        Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
      Collecting kivy_deps.gstreamer_dev~=0.3.3
        Using cached kivy_deps.gstreamer_dev-0.3.3-cp311-cp311-win_amd64.whl (3.9 MB)
      ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2_dev~=0.4.5 (from versions: 0.5.1)
      ERROR: No matching distribution found for kivy_deps.sdl2_dev~=0.4.5
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by shashwatpritish** [comment]
# **This fix when I install Python 3.10.10 realeased on Feb 8 2023**

[Click here to download python 3.10.10](https://www.python.org/downloads/release/python-3100/)

**Command to install Kivy**

```
pip3 install kivy
```

**Comment by xkevan19** [comment]
The issue still occurs, instead of rolling back to a earlier version of python I just specified the version like:

`pip install kivy_deps.sdl2_dev==0.5.1`

**OR** 

`pip install kivy_deps.sdl2_dev==0.6.0`

**Comment by GGDarky** [comment]
Temporary resolution

python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/

**Comment by misl6** [comment]
Kivy `2.2.0` has been released, and we now ship wheels for `3.11`.

Thank you to everyone who tested the pre-release builds!

**Comment by Dexacus** [comment]
I keep getting this Error message. I have tried every link to put into terminal and nothing works. It has to be something so small and simple to fix....... I saw something where I needed to rename a file but have no clue where to do that before downloading. 

error: could not build wheels for kivy, which is required to install pyproject.tom-based projects

Any ideas anyone? Please Help

**Comment by MrTeferi** [comment]
@Dexacus are you using Python 3.12? Because Kivy is not supported by 3.12 at the moment. It is supported by 3.11, assuming you are using Kivy==2.2.0

**Comment by Dexacus** [comment]
Thanks for getting back to me. i had to create a new codespace in Visual and a ne repository in github to get it to work with the new version. i t was a pain in the ass to figure it out, lol.

**Comment by Elijah-Vang** [comment]
Okay, so for those who are still struggling to install Kivy. I have an additional update for you all. If you have any pervious python versions on your computer you will need to uninstall and install it all over again. The reason the error occurs is because when you go to install Kivy the system does not know which one to use. Therefore cause all of the errors above this. Version 3.12 is not supported but 3.11 is supported as stated above.
