### ISSUE TITLE
Migrate to Metal for IOS support

### ISSUE THREAD

**Issue by PunchCakee** [kivy/kivy#8053]
**Is your feature request related to a problem? Please describe.**
Apple's IOS has deprecated opengl thus rendering kivy unusable in production.

**Describe the solution you'd like**
A migration to the Metal rendering library

**Describe alternatives you've considered**
Currently there is no alternative. To maintain IOS support kivy needs to be migrated to Metal.

**Comment by misl6** [comment]
Duplicated of #5789 

(As described in #5789 we have a solution for that, so Kivy on iOS is safe, even without migrating to Metal)
