### ISSUE TITLE
Unnecessary depreciated warning for on_dropfile

### ISSUE THREAD

**Issue by abedhammoud** [kivy/kivy#8054]
**Software Versions**
* Python: 3.10.6
* OS: win64
* Kivy: 2.1
* Kivy installation method: pip install kivy

**Describe the bug**
I am getting a depreciated warning that I should use ```on_drop_file``` event instead of ```on_dropfile```

**Expected behavior**
I shouldn't be getting this warning as I am using ```on_drop_file```

**To Reproduce**
```python

from kivy.app import App
from kivy.core.window import Window
from kivy.uix.boxlayout import BoxLayout


class Filedrop_test(BoxLayout):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)


class TestApp(App):

    def build(self):

        root = Filedrop_test()

        if Window:
            Window.bind(on_drop_file=self.drop_file_handler)

        return root

    def drop_file_handler(self, *args):
        print(f'---{args=}')


if __name__ == '__main__':
    TestApp().run()


```

**Code and Logs and screenshots**
if I drop a file into the window, I get:
```python
[WARNING] [Deprecated  ] Deprecated in 2.1.0, use on_drop_file event instead. Event on_dropfile will be removed in the next two releases.: Call to deprecated function on_dropfile in C:\Users\xxx\miniconda3\envs\xxx\lib\site-packages\kivy\core\window\__init__.py line 2106.Called from C:\Users\xxx\miniconda3\envs\xxx\lib\site-packages\kivy\core\window\__init__.py line 1045 by <lambda>().
```

**Additional context**

**Comment by Julian-O** [comment]
Confirmed on my machine. Kivy 2.2.1, Windows 11.

**Comment by Julian-O** [comment]
The bit that concerns me is it is (wrongly) calling a method that just `pass`es, so whatever is supposed to be happening isn't.

**Comment by Julian-O** [comment]
Duplicate #7853
