### ISSUE TITLE
(Minor Doc Issue) How to download Kivy App SDK for macOS packaging?

### ISSUE THREAD

**Issue by kwccoin** [kivy/kivy#8059]
It was said https://github.com/kivy/kivy-sdk-packager/tree/master/osx that

 "To use the existing Kivy app bundle:

Download the Kivy app from the Kivy download page, the GitHub releases, or the nightly release with e.g.::

curl -O -L https://xxx/Kivy-xxx.dmg"

After searching the site (I apology if it is very obvious) I cannot find any of this.  Any hint?

**Comment by matham** [comment]
https://github.com/kivy/kivy/releases
