### ISSUE TITLE
Kivy throwing "_event.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send" for python3.10.6

### ISSUE THREAD

**Issue by z3n-k3rn3l** [kivy/kivy#8065]
**Software Versions**
* Python: 3.10.6
* OS: Pop OS 64 bit 
* Kivy: v2.0.0
* Kivy installation method: pip install kivy

**Describe the bug**
Kivy is supported for python 3.10 based on the site information. But when I try to import kivy to my project is showing error. I have installed kivy using 'pip install kivy'

**Expected behavior**
It should import and work without any error.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.lang import Builder
from filesharer import FileSharer

Builder.load_file('frontend.kv')


class CameraScreen(Screen):

    def start(self):
        pass

    def stop(self):
        pass

    def capture(self):
        pass


class ImageScreen(Screen):
    pass


class RootWidget(ScreenManager):
    pass


class MainApp(App):
    def build(self):
        return RootWidget()


MainApp().run()

```

**Additional context**
Seems like problem is related with kivy. Please find the screenshot of VScode indicating error while importing kivy modules
![image](https://user-images.githubusercontent.com/75212700/205428751-abb8bdbd-a973-4c0e-ac2a-cc14288e778b.png)

Any help is appreciated.

**Comment by misl6** [comment]
Hi @z3n-k3rn3l !

We do not offer a pre-built `cp310` compatible wheel for `Kivy==2.0.0`, but only for `Kivy==2.1.0`.

If switching to `Kivy==2.1.0` does not fix this issue, feel free to re-open a new one.

**Comment by z3n-k3rn3l** [comment]
> Hi @z3n-k3rn3l !
> 
> We do not offer a pre-built `cp310` compatible wheel for `Kivy==2.0.0`, but only for `Kivy==2.1.0`.
> 
> If switching to `Kivy==2.1.0` does not fix this issue, feel free to re-open a new one.

Thanks switching to 2.1.0 solved the issue.
