### ISSUE TITLE
keyboard_suggestions flag not working even when input_type is set to 'text'

### ISSUE THREAD

**Issue by Aravind0007** [kivy/kivy#8071]
**Software Versions**
* Python: 3
* OS: android
* Kivy: 2.1.0
* Kivy installation method:pip installation

**Describe the bug**

We have the keyboard_suggestions flag in TextField widget class to enable / disable the suggestion words shown in keyboard.

**Expected behavior**
When I focus on textfield with keyboard_suggestions flag set to false, keyboard should not show suggestions

**Actual behavior**
Irrespective of keyboard_suggestions flag set to false/true, keyboard (Gboard) always show suggestions

**To Reproduce**
[keyboard_suggestionsBug.zip](https://github.com/kivy/kivy/files/10201997/keyboard_suggestionsBug.zip)

**Code and Logs and screenshots**
```python

https://user-images.githubusercontent.com/58268827/206899982-dbfa3ba1-7913-46ea-933f-8dee8ac9a7f3.mp4


**Additional context**
keyboard_suggestions doesn't seems to have any effect on text field. 
Device details:
Device : IQOO Z5 Pro, Android : 12, Keyboard : GBoard.

We already had some discussion at kivy user support google groups regarding this : [[[https://groups.google.com/d/msgid/kivy-users/638f4ca5.050a0220.acb7d.a403SMTPIN_ADDED_MISSING%40gmr-mx.google.com](https://groups.google.com/d/msgid/kivy-users/638f4ca5.050a0220.acb7d.a403SMTPIN_ADDED_MISSING%40gmr-mx.google.com?utm_medium=email&utm_source=footer)](url)](https://groups.google.com/g/kivy-users/c/yQIuLZPf-jg) with @ElliotGarbus and @RobertFlatt and @misl6  was mentioned by them in between to understand the issue better in between the conversation

Please help me resolve this issue :)

**Comment by Aravind0007** [comment]
@tshirtman @misl6 @RobertFlatt Created an issue to track what can be done as part of conversation : [https://groups.google.com/g/kivy-users/c/yQIuLZPf-jg](url) .  Can anyone please acknowledge this issue ?

**Comment by misl6** [comment]
Hi @Aravind0007 !

Please see: https://github.com/kivy/kivy/pull/8089

Unfortunately, we can't do quite much if Android keyboards are ignoring this flag. I've added a warning with a workaround to the docs.

**Comment by Aravind0007** [comment]
Thanks @misl6 ! I will try the work around and look how it works,
