### ISSUE TITLE
Unable to achieve synchronized behaviour with kivy textfield with alphabets only filter and android keyboard suggestion shown and thus causes discrepancy

### ISSUE THREAD

**Issue by Aravind0007** [kivy/kivy#8072]
**Software Versions**
* Python:3
* OS:android
* Kivy:2.1.0
* Kivy installation method:pip installation

**Describe the bug**
 It seems that when we select keyboard suggested word, it produces the word along with trailing space at the ending side of word. So I modified the substring with strip() function. But there's another issue with it. As per keyboard functionality, It still assumes that the word delivered was with a space and it was messing up.

Let me throw an example. Let us say I type string "tes" and the keyboard suggestions shows "test "(with trailing space at end only) and I touch the suggested word, now the word "test"(without a space) as strip is used  was populated and when I do backspace 4 times the word in text field holds "" but as per keyboard functionality memory it holds "t" (as it still considers space) and shows another suggestion word say "thanks", the text field only receives the text "hanks" as the keyboard considers "t" was already there. 

**Expected behavior**
Reconciliation with keyboard functionality and textfield functionality
**To Reproduce**
[keyboard_textfieldBug.zip](https://github.com/kivy/kivy/files/10202078/keyboard_textfieldBug.zip)

**Code and Logs and screenshots**
```python
from kivymd.app import MDApp
from kivymd.uix.textfield import MDTextField
from kivymd.uix.floatlayout import MDFloatLayout
class Word(MDTextField):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.input_filter = self.letters_only
    def letters_only(self, substring, from_undo):
        if (substring.strip()).isalpha():
            return substring.strip()
class TestTextFieldApp(MDApp):
    def build(self):
        self.root = MDFloatLayout()
        self.word = Word()
        self.word.input_type = "text"
        self.root.add_widget(self.word)
        self.word.pos_hint = {"center_x":0.5,"center_y":0.5}
        self.word.size_hint = (0.75,0.125)
        return self.root
if __name__ == '__main__':
    TestTextFieldApp().run()

**Additional context**
Already had some discussions related to this issue in https://mail.google.com/mail/u/0/#inbox/FMfcgzGrbRQtcvpZwvjkBFQGmkDBclrW with @ElliotGarbus and @RobertFlatt and @misl6 was mentioned by them to have better understanding of this issue.

Please help me resolve this issue :)

**Comment by Aravind0007** [comment]
@tshirtman @misl6 @RobertFlatt Created an issue to track what can be done as part of conversation : [https://groups.google.com/g/kivy-users/c/yQIuLZPf-jg](https://github.com/kivy/kivy/issues/url) . Can anyone please acknowledge this issue ?

**Comment by misl6** [comment]
This is a pretty uncommon way to use the Android IME when set in `text` mode.(https://developer.android.com/develop/ui/views/touch-and-input/creating-input-method)

Our TextInput should stay in sync with the hidden one on Android side for the IME to work correctly and this is not happening, nor we are exposing a method to re-sync it when (as your example) the developer filters the input and changes it programmatically.

**Comment by Aravind0007** [comment]
@misl6 Can kivy framework introduce/expose a method or something to sync the behavior ?

**Comment by Julian-O** [comment]
It looks like there is no plan to implement this feature, as it is an unsual use-case and there are other solutions.

Closing as Not Planned.

If you think this is in error (particularly if you want to submit a PR), please let us know.
