### ISSUE TITLE
Markup [sup] followed by [sub] doesn't work

### ISSUE THREAD

**Issue by endolith** [kivy/kivy#8077]
**Software Versions**
* Python: 3.10.6
* OS: Windows 10 
* Kivy: 2.1.0
* Kivy installation method: conda

**Describe the bug**
If you make a button with `button = Button(text='1[sup]2[/sup][sub]3[/sub]', markup=True)`, the 2 and 3 are both superscript.

![image](https://user-images.githubusercontent.com/58611/208555412-5a60d5e9-2cc8-4ef1-bb4b-fd3a2a066244.png)

With a space between them, it displays correctly:

![image](https://user-images.githubusercontent.com/58611/208555541-d933d739-84bf-4905-af8c-abe03236b4e7.png)

**Expected behavior**
It should display the 2 as superscript and the 3 as subscript

**To Reproduce**

```python
from kivy.app import App
from kivy.uix.button import Button

class MyApp(App):
    def build(self):
        button = Button(text= '1[sup]2[/sup][sub]3[/sub]', markup=True)
        return button

if __name__ == '__main__':
    MyApp().run()
```

**Comment by azinneck0485** [comment]
Hi, I have looked into this and found it is related to the logic in *render_lines* of *markup.py*:

<img width="348" alt="image" src="https://github.com/kivy/kivy/assets/123660683/d6ed331e-2b7c-45d9-933c-d66ca570e02a">

When there is a space (or other "normal script" text) between `[\sup]` and `[sub]` (or `[\sub]` and `[sup]`), `psp` and `pph` "reset" 0 and `script_pos` is evaluated as expected.  Without the space, the values "carry over" and `script_pos` is the same for a subscript that "immediately" follows a superscript (no space) (and vice versa).

I would like to correct this bug, but before I make any changes, I have a couple of questions about this part of the code:
1. What do the variables `pph` and `psp` represent?  It appears to be something related to the sub-/superscript positions, but it's not clear what.
2. Why are they set at the end of the iteration such that the next iteration uses those values (if necessary)?  Removing these/setting to 0 at the start of each iteration seems to be the obvious fix, but I would want to understand the risks implicit in doing so.
