### ISSUE TITLE
Can we create windows phone apps with kivy??

### ISSUE THREAD

**Issue by snehccurry** [kivy/kivy#8078]
lately I've been wanting to create windows phone apps to revive the legacy of windows phones, is there a way how we could build apps for windows phones?

**Comment by LucasColas** [comment]
I don't think it's possible.

**Comment by PraddyumnYadav** [comment]
What do you mean by a Windows Phone App

**Comment by LucasColas** [comment]
I think it's [that](https://en.wikipedia.org/wiki/Windows_Phone).

**Comment by akshayaurora** [comment]
Microsoft discontinued Windows Phone. This feature is not under current or any future plans.
