### ISSUE TITLE
Spinner broken after settings display

### ISSUE THREAD

**Issue by julien6387** [kivy/kivy#8079]
**Software Versions**
* Python: 3.9.7
* OS: RedHat 8u2
* Kivy: 2.1.0
* Kivy installation method: pip install kivy[base]

**Describe the bug**
I'm using the demo/showcase provided in kivy-example.
The ActionSpinner is working fine until I click F1 to get the Kivy settings and close.
Then the ActionSpinner is not refreshed anymore when selecting another item from the DropDown list
I cannot repeat the issue with a Python 3.6.8.

**Expected behavior**
The ActionSpinner should still be working after the Kivy settings are displayed.

**To Reproduce**
the kivy-examples demo/showcase

**Comment by entaangle** [comment]
I'm hitting this too with kivy 2.2.1.  Is forcing me to write my own settings panel.

**Comment by misl6** [comment]
Fixed via #8535
