### ISSUE TITLE
Bug in displaying shadows when moving the widget

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#8080]
**Software Versions**
* Python: 3.10
* OS: Mac OS Catalina 10.15
* Kivy: master

**Describe the bug**
`BoxShadow` instructions are not displayed when moving the widget. If we move a widget that uses `BoxShadow` instructions by at least a pixel, the canvas will be cleared of `BoxShadow` instructions.  `BoxShadow` instructions will be restored only when the parent window is resized.

**Expected behavior**
It is expected that the shadow that is drawn on the canvas when the widget is moved will be displayed..

**Code**
```python
from kivy.animation import Animation
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.button import Button

KV = """
#:import Clock kivy.clock.Clock


<ShadowButton>
    size_hint: None, None
    size: 200, 150

    canvas.before:
        Color:
            rgba: 0, 0, 1, .85
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 0, -10
            spread_radius: -20
            border_radius: 10, 10, 10, 10
            blur_radius: 80


Screen:

    ShadowButton:
        on_release: Clock.schedule_once(lambda x: app.move_button(self), 2)
        pos_hint: {"center_x": .5, "center_y": .5}
"""


class ShadowButton(Button):
    pass


class Example(App):
    def move_button(self, instance_button):
        Animation(
            pos_hint={"center_x": .3, "center_y": .3}, d=1.5
        ).start(instance_button)

    def build(self):
        return Builder.load_string(KV)


Example().run()
```

**What the bug looks like**

https://user-images.githubusercontent.com/16930280/209276814-183ba456-580e-4d98-9f3e-5bb109df7ae8.mov

Also, any manipulation of the `BoxShadow` instructions using the `Animation` class leads to a complete cleaning of the canvas instructions:

```python
from kivy.animation import Animation
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.button import Button
from kivy.properties import NumericProperty

KV = """
#:import Clock kivy.clock.Clock


<ShadowButton>
    size_hint: None, None
    size: 200, 150

    canvas.before:
        Color:
            rgba: 0, 0, 1, .85
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 0, -10
            spread_radius: -20
            border_radius: 10, 10, 10, 10
            blur_radius: root.blur_radius


Screen:

    ShadowButton:
        on_release: Clock.schedule_once(lambda x: app.animated_size_shadow_button(self), 2)
        pos_hint: {"center_x": .5, "center_y": .5}
"""


class ShadowButton(Button):
    blur_radius = NumericProperty(80)


class Example(App):
    def animated_size_shadow_button(self, instance_button):
        Animation(blur_radius=120, d=1.5).start(instance_button)

    def build(self):
        return Builder.load_string(KV)


Example().run()
```

https://user-images.githubusercontent.com/16930280/209278304-7f15ca46-d4b4-4daf-adb5-fd623cd0aaa2.mov

The canvas instructions will be restored only after resizing the parent window.

**Comment by DexerBR** [comment]
Hi @HeaTTheatR!

I tested that on other OS and works fine! Apparently it's something related to **Mac OS Catalina 10.15**

What happens if you run the code bellow?

```python
from kivy.animation import Animation
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.button import Button

KV = """
#:import Clock kivy.clock.Clock


<ShadowButton>
    size_hint: None, None
    size: 200, 150
    on_pos:
        self.canvas.ask_update()

    canvas.before:
        Color:
            rgba: 0, 0, 1, .85
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 0, -10
            spread_radius: -20
            border_radius: 10, 10, 10, 10
            blur_radius: 80


MDScreen:

    ShadowButton:
        on_release: Clock.schedule_once(lambda x: app.move_button(self), 2)
        pos_hint: {"center_x": .5, "center_y": .5}
"""


class ShadowButton(Button):
    pass


class Example(App):
    def move_button(self, instance_button):
        Animation(
            pos_hint={"center_x": .3, "center_y": .3}, d=1.5
        ).start(instance_button)

    def build(self):
        return Builder.load_string(KV)


Example().run()
```

**Comment by HeaTTheatR** [comment]
@DexerBR Unfortunately, the same behavior that I described above happens.

**Comment by misl6** [comment]
https://user-images.githubusercontent.com/8177736/209431116-79ee6d2f-0e84-4a7f-8e1d-9b6eb08f334f.mov

Works fine also on my side (macOS Ventura 13.1)

@HeaTTheatR , can you try to use our nighly wheels to test it? (https://kivy.org/doc/stable/gettingstarted/installation.html#pre-release-pre-compiled-wheels)

**Comment by HeaTTheatR** [comment]
@misl6 It's very strange...

**Comment by HeaTTheatR** [comment]
@misl6 I even [disabled](https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/button/button.py#L1177) the shadow animation in the `KivyMD` library because I thought it was a bug. But it turns out this bug only get on my computer...

**Comment by HeaTTheatR** [comment]
@misl6 >  can you try to use our nighly wheels to test it?

The `--pre` flag only installation version 2.1.0 but not 2.2.0.

**Comment by misl6** [comment]
> @misl6 >  can you try to use our nighly wheels to test it?
> 
> 
> 
> The `--pre` flag only installation version 2.1.0 but not 2.2.0.

Are you using `--no-deps --index-url  https://kivy.org/downloads/simple/` as specified into the `nightly` section?

**Comment by HeaTTheatR** [comment]
@misl6 Unfortunately it doesn't work. I get all the same behavior.

![Снимок экрана 2022-12-24 в 21 40 12](https://user-images.githubusercontent.com/16930280/209447878-47874192-2a8e-4c20-bff7-b1e93dea85e0.png)

**Comment by misl6** [comment]
> @misl6 Unfortunately it doesn't work. I get all the same behavior.
> 
> ![Снимок экрана 2022-12-24 в 21 40 12](https://user-images.githubusercontent.com/16930280/209447878-47874192-2a8e-4c20-bff7-b1e93dea85e0.png)

So the `BoxShadow` looks broken also on `2.2.0.dev0` for you ?

Maybe the issue is only reproducible on Intel macs? (Catalina is not supported on Apple Silicon, so I came to the conclusion that you're on Intel)

@DexerBR what's your current development platform? Have you had the chance to test the feature on other platforms as well?

**Comment by DexerBR** [comment]
> @DexerBR what's your current development platform? Have you had the chance to test the feature on other platforms as well?

@misl6 `BoxShadow` development/testing was done on the following platforms:

- Ubuntu 20.04 (through WSL2)
- Windows 11
- Android 8.1.0 → Adreno GPU (which have the compilation error issue as discussed on Kivy's dev channel on discord - **this does not happen with this feature**)
- Android 9 → Mali GPU

`BoxShadow` worked fine on all platforms I tested it, using these example code from the issue.

**Comment by HeaTTheatR** [comment]
@DexerBR Yes, it works on Android. But on my Macbook, as we can see, for some reason there are problems...

**Comment by DexerBR** [comment]
@HeaTTheatR Could you compile and test this branch?
https://github.com/DexerBR/kivy/tree/boxshadow_macos_catalina_fix

**Comment by HeaTTheatR** [comment]
@DexerBR 
After removing and installing `Kivy`:

```
pip uinstall kivy
pip install git+https://github.com/DexerBR/kivy.git@boxshadow_macos_catalina_fix
```

 ... I am still getting the same problem on my computer.

**Comment by HeaTTheatR** [comment]
@misl6 This PR fixes this issue.
