### ISSUE TITLE
ERROR: Failed building wheel for kivy

### ISSUE THREAD

**Issue by zaisanzaisan** [kivy/kivy#8082]
**Software Versions**
* Python: 3.11
* OS: Ubuntu 22.10
* Kivy: 2.1.0
* Kivy installation method: pip installer kivy (pycharm)

Collecting kivy
  Using cached Kivy-2.1.0.tar.gz (23.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Kivy-Garden>=0.1.4
  Using cached Kivy_Garden-0.1.5-py3-none-any.whl (4.6 kB)
Collecting docutils
  Using cached docutils-0.19-py3-none-any.whl (570 kB)
Collecting pygments
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Building wheels for collected packages: kivy
  Building wheel for kivy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for kivy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [219 lines of output]
      [INFO   ] [Logger      ] Record log in /home/zaisan/.kivy/logs/kivy_22-12-25_28.txt
      [INFO   ] [Kivy        ] v2.1.0
      [INFO   ] [Kivy        ] Installed at "/tmp/pip-install-547r_djk/kivy_cf08768ff6a04aa6886074f6a242d4a9/kivy/__init__.py"
      [INFO   ] [Python      ] v3.11.0rc2 (main, Sep 12 2022, 16:20:24) [GCC 12.2.0]
      [INFO   ] [Python      ] Interpreter at "/home/zaisan/PycharmProjects/pythonProject2/venv/bin/python"
      [INFO   ] [Logger      ] Purge log fired. Processing...
      [INFO   ] [Logger      ] Purge finished!
       <string>:370: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:373: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:377: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       warning: kivy/graphics/common.pxi:9:4: 'const_char_ptr' redeclared
       warning: kivy/graphics/common.pxi:23:4: 'size_t' redeclared
      kivy/properties.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      kivy/_clock.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      compilation terminated.
      kivy/_event.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/weakproxy.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/compiler.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/context_instructions.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/buffer.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/_metrics.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/context.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/opengl.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/gl_instructions.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/fbo.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/instructions.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/opengl_utils.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/shader.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/stencil_instructions.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/scissor_instructions.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/texture.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/transformation.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/vbo.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/vertex.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/cgl_backend/cgl_mock.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/cgl_backend/cgl_gl.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/vertex_instructions.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/cgl.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/cgl_backend/cgl_sdl2.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/cgl_backend/cgl_glew.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/core/text/text_layout.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/cgl_backend/cgl_debug.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/core/window/window_info.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/tesselator.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      kivy/graphics/svg.c:6:10: fatal error: Python.h: Нет такого файла или каталога
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      Current directory is: /tmp/pip-install-547r_djk/kivy_cf08768ff6a04aa6886074f6a242d4a9
      Source and initial build directory is:
      Python path is:
      /tmp/pip-install-547r_djk/kivy_cf08768ff6a04aa6886074f6a242d4a9
      /home/zaisan/PycharmProjects/pythonProject2/venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process
      /tmp/pip-build-env-rz6krn54/site
      /usr/lib/python311.zip
      /usr/lib/python3.11
      /usr/lib/python3.11/lib-dynload
      /tmp/pip-build-env-rz6krn54/overlay/lib/python3.11/site-packages
      /tmp/pip-build-env-rz6krn54/normal/lib/python3.11/site-packages
      /tmp/pip-install-547r_djk/kivy_cf08768ff6a04aa6886074f6a242d4a9/kivy/modules
      /home/zaisan/.kivy/mods
      
      
      Found Cython at /tmp/pip-build-env-rz6krn54/overlay/lib/python3.11/site-packages/Cython/__init__.py
      Detected supported Cython version 0.29.28
      Using this graphics system: OpenGL
      WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 127)
      
      b'/bin/sh: 1: pkg-config: not found\n'
      
      WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 127)
      
      b'/bin/sh: 1: pkg-config: not found\n'
      
      WARNING: A problem occurred while running pkg-config --libs --cflags pangoft2 (code 127)
      
      b'/bin/sh: 1: pkg-config: not found\n'
      
      ERROR: Dependency for context.pyx not resolved: config.pxi
      ERROR: Dependency for compiler.pyx not resolved: config.pxi
      ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for fbo.pyx not resolved: config.pxi
      ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for instructions.pyx not resolved: config.pxi
      ERROR: Dependency for opengl.pyx not resolved: config.pxi
      ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
      ERROR: Dependency for shader.pyx not resolved: config.pxi
      ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for texture.pyx not resolved: config.pxi
      ERROR: Dependency for vbo.pyx not resolved: config.pxi
      ERROR: Dependency for vertex.pyx not resolved: config.pxi
      ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for cgl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
      ERROR: Dependency for svg.pyx not resolved: config.pxi
      Building extensions in parallel using 4 cores
      Updated build directory to: build/lib.linux-x86_64-cpython-311
      Build configuration is:
       * use_rpi = 0
       * use_egl = 0
       * use_opengl_es2 = 0
       * use_opengl_mock = 0
       * use_sdl2 = 0
       * use_pangoft2 = 0
       * use_ios = 0
       * use_android = 0
       * use_mesagl = 0
       * use_x11 = 0
       * use_wayland = 0
       * use_gstreamer = 0
       * use_avfoundation = 0
       * use_osx_frameworks = 0
       * debug_gl = 0
       * kivy_sdl_gl_alpha_size = 8
       * debug = False
      Updated build/lib.linux-x86_64-cpython-311/kivy/include/config.h
      Updated kivy/include/config.h
      Updated build/lib.linux-x86_64-cpython-311/kivy/include/config.pxi
      Updated kivy/include/config.pxi
      Updated build/lib.linux-x86_64-cpython-311/kivy/setupconfig.py
      Updated kivy/setupconfig.py
      Detected compiler is unix
       error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kivy
Failed to build kivy
ERROR: Could not build wheels for kivy, which is required to install pyproject.toml-based projects

**Comment by kuzeyron** [comment]
Software Versions

    Python: 3.11
    OS: Ubuntu 22.10
    Kivy: 2.1.0
    Kivy installation method: pip installer kivy (pycharm)

You will be needing the master edition of Kivy for this. 3.11 is introduced in the master edition.

**Comment by misl6** [comment]
Duplicated of #8042
