### ISSUE TITLE
Black screen and restart required after importing kivy.uix.textinput

### ISSUE THREAD

**Issue by JMrziglod** [kivy/kivy#8097]
**Software Versions**
* python           : 3.10.2.final.0
* python-bits      : 64
* OS               : Darwin
* OS-release       : 21.6.0
* machine          : arm64
* processor        : arm
* Kivy: v2.1.0
* Kivy installation method: pip install kivy

**Describe the bug**
After importing the TextInput class from `kivy.uix.textinput` - without building an app or anything -, I get a black screen, the screen resolution was changed and keyboard inputs are not possible anymore. I had to restart my Mac Book.

I tried it out on another MacBook which has an Intel chip and the code worked. So it is probably a problem with the M1 chip.

**Expected behavior**
It shouldn't do anything except import TextInput.

**To Reproduce**
```python
from kivy.app import App
from kivy.uix.textinput import TextInput
```

**Logs**
```
[INFO   ] [Logger      ] Record log in /Users/JMrziglod/.kivy/logs/kivy_23-01-05_4.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/Users/JMrziglod/Library/Python/3.10/lib/python/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)]
[INFO   ] [Python      ] Interpreter at "/usr/local/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Metal - 76.3'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple M1'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
```

**Comment by Ahd999** [comment]
Well it is doing nothing except importing TextInput. The logs you see are default logs that kivy shows on imports

**Comment by JMrziglod** [comment]
I expected it to import TextInput but it crashed my MacBook instead. The import fails.

**Comment by Ahd999** [comment]
It dosent matter which system are you using be it mac, win or Lin all of the require you to write one thing in your code I. E. App().run() without that it appears to crash though it is the default behaviour in kivy

**Comment by JMrziglod** [comment]
Are you saying that the default behaviour is to freeze my computer, make the screen black and grab all my keyboard inputs just because I imported a module? I don't think this makes much sense. Is this documented somewhere?

**Comment by Ahd999** [comment]
Oh ohk yup that's an issue,forgive me, btw why don't you try and use some other kivy version?

**Comment by jmdc112596** [comment]
The same thing happened to me. Imported the line below, everything froze, screen went black, my screen came back had lower resolution and was much smaller. Nothing working but mouse inputs. Keyboard input didn't work. Had to restart computer to fix. I was importing in a Jupyter Notebook, not sure if this is relevant. Thanks.

Kivy 2.3.0
Python 3.11.7
MacOS Sonoma 14.0
2.6 GHz 6-Core Intel Core i7

`from kivy.uix.textinput import TextInput`

**Comment by Julian-O** [comment]
@jmdc112596: Try the support channels. Sounds like you are making the same mistake as the OP. Importing in Kivy has side-effects, alas.
