### ISSUE TITLE
VIDEO: VideoFFPy flaws

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#8105]
**Software Versions**
* Python: 3.9.2
* OS: Debian Bullseye
* Kivy: 2.1.0
* Kivy installation method: pip
* ffpyplayer: 4.3.2

**Behavior**

I currently play around with connecting ``ffpyplayer`` based video to an rtsp stream. It actually works, but there is a problem with the ``VideoFFPy`` implementation.

``src_vid_size`` is constantly reported as (0, 0) in metadata, so the stream never starts. If i skip this check -> https://github.com/kivy/kivy/blob/master/kivy/core/video/video_ffpyplayer.py#L265 the stream starts playing as expected.

What is the correct way to fix this? Should ``ffpyplayer`` need to report the correct ``src_vid_size`` or is it necessary to improve the check?

The only metadata which actually changes when connecting to (this specific) stream are ``src_pix_fmt`` and ``title``.

Another thing i encountered is that ``src_pix_fmt`` is reported as binary string in metadata, but the check whether to use the custom GLSL shader for rendering compares against a string which never evaluates to ``True`` (https://github.com/kivy/kivy/blob/master/kivy/core/video/video_ffpyplayer.py#L253)

Further it seems the custom shader also works with ``yuvj420p`` format.

**Comment by rnixx** [comment]
@matham ping

**Comment by rnixx** [comment]
Related PR draft -> https://github.com/kivy/kivy/pull/8171

**Comment by Julian-O** [comment]
@rnixx: I am interpreting this as fixed by #8171, and closing, but I admit I didn't follow either very closely, so if that's not the case please let us know.
