### ISSUE TITLE
Screens cropped and shows black area on top and bottom in mobile phone

### ISSUE THREAD

**Issue by aisjdevmahesh** [kivy/kivy#8106]
**Software Versions**
* Python: 3.10.2
* OS: mac OS / iPhone
* machine : arm64
* processor : M1
* Kivy: 2.1.0
* Kivy installation method: pip install kivy

**Describe the bug**
Screens cropped and shows black area on top and bottom in mobile phone(iPhone 14 Pro Max)

**Expected behavior**
Show app with full height and width

**Images**
Kivy app screen
![clipped on top and bottom](https://user-images.githubusercontent.com/92131665/213437206-e7a52493-10f2-4d97-9b7b-e65b2a205f69.png)

Actual screen size
![actual screen referrance](https://user-images.githubusercontent.com/92131665/213437399-55c183c1-5c52-447d-a2b3-14595056269c.png)

Please refer below image too
![clipped on top and bottom](https://user-images.githubusercontent.com/92131665/213438218-f22e2006-3dac-4fad-bb2a-feffdce7f220.png)

Thanks in advance

**Comment by misl6** [comment]
Hi @aisjdevmahesh !

This issue on `kivy-ios` has been fixed via https://github.com/kivy/kivy-ios/pull/756 .

Feel free to join us on [Discord](https://chat.kivy.org) if you need some help 😃
