### ISSUE TITLE
Error installing Kivy

### ISSUE THREAD

**Issue by gansopro** [kivy/kivy#8112]
I am following this tutorial and I type these following commands:

python -m pip install --upgrade pip setuptools virtualenv
python -m virtualenv kivy_venv
kivy_venv\Scripts\activate

But in the hour of to type this:

python -m pip install "kivy[base]" kivy_examples

This error appears:

ERROR: Command errored out with exit status 1:
   command: 'C:\Windows\system32\kivy_venv\Scripts\python.exe' 'C:\Windows\system32\kivy_venv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'c:\users\gataj\appdata\local\temp\pip-build-env-ngeztv\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.24,<=0.29.21,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.3.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew~=0.3.0; sys_platform == "win32"'
       cwd: None
  Complete output (9 lines):
  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
  Collecting setuptools
    Using cached setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting cython!=0.27,!=0.27.2,<=0.29.21,>=0.24
    Using cached Cython-0.29.21-cp27-cp27m-win_amd64.whl (1.6 MB)
  ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.1 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.8, 0.1.9, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17)
  ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.3.1
  
ERROR: Command errored out with exit status 1: 'C:\Windows\system32\kivy_venv\Scripts\python.exe' 'C:\Windows\system32\kivy_venv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'c:\users\gataj\appdata\local\temp\pip-build-env-ngeztv\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.24,<=0.29.21,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.3.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew~=0.3.0; sys_platform == "win32"' Check the logs for full command output.

Can you help me?

**Comment by RobertFlatt** [comment]
Type `python -V` (that is an upper case -V) at a Windows command prompt.
You will presumably see that you are using Python 2.7, but you must use Python 3 (3.10 is a good choice, but not 3.11)

This forum is for Kivy development issues, for Kivy usage support go the the user groups for example https://discord.gg/mCsmX974


Nobody here will

**Comment by RobertFlatt** [comment]
Type `python -V` (that is an upper case -V) at a Windows Command Prompt.
You will presumably see that you are using Python 2.7, this is an obsolete version of Python.
The is what the "DEPRECATION" message means.

You must use Python 3 (3.10 is a good choice, but not 3.11)
(Presumably you should uninstall Python2 and install Python3)

Also you are working in the Windows system32 directory, this will give problems. 
You should work under a User directory. 
And don't install Python with, or work in, a Command Prompt "run as Administrator"

You don't say what "this tutorial" is, but perhaps you can ask there about the basic setup issues you appear to have. 

This forum is for Kivy tool development issues, the question is not a Kivy tool development question. 
For Kivy usage support go the the user group, for example https://discord.gg/mCsmX974  

**Do not expect a response to any follow up questions here.**
