### ISSUE TITLE
Add curio support

### ISSUE THREAD

**Issue by logileifs** [kivy/kivy#8113]
Currently kivy supports asyncio and trio. Would it be possible to add support for curio as well?
I find that of the three libraries curio is the easiest one to work with and it would be awesome if I could use some curio based code I have written work with a kivy app.

**Comment by Julian-O** [comment]
This isn't an official pronouncement, but more a personal observation: I think this is an unlikely feature to be added, based on current resources.

If you bring your own resources with you, that's another story.

**Comment by p0lygun** [comment]
@Julian-O from curio's repo 
> The Curio project is no longer making package releases. I'm more than happy to accept bug reports and may continue to work on it from time to time as the mood strikes. If you want the absolute latest version, you should vendor the source code from here. Curio has no dependencies other than the Python standard library. --Dave

**Comment by Julian-O** [comment]
@p0lygun: That was *before* this  feature request!

I am going out on a limb and saying this is never gonna happen - we aren't going to spend hundreds of hours supporting an obsolete technology that few people use. I will close this off, sorry.
