### ISSUE TITLE
Error kivy.atlas.Atlas

### ISSUE THREAD

**Issue by Jefferson5286** [kivy/kivy#8118]
**Software Versions**
* Python: 3.10
* Kivy: 2.1..0
* Kivy installation method: by the pip

whenever I try to use Atlas kivy the interpreter stops working, in the command line it simply appears (nothing):

``>>> atlas = Atlas('assets/Ninja_Monk/monk.atlas')
(venv) PS C:\Users\Jeffe\PycharmProjects\pythonProject> ``

When using the pycharm run tool ("run"), I think I have one more piece of information. After this message:

``[INFO ] [Image ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)``

as usual, it stops running and appears:

``Process finished with exit code -1073741819 (0xC0000005)``

I thought it was because I built kivy in python3.11 but I changed the interpreter to 3.10 and the problem persisted

**Comment by misl6** [comment]
Hi @Jefferson5286 !

Can you try to launch it from terminal, with the [debug logging enabled](https://kivy.org/doc/stable/api-kivy.config.html?highlight=debug#available-configuration-tokens) and report back here the full output?
