### ISSUE TITLE
Exception ignored in: 'kivy.graphics.opengl_utils.gl_has_capability'stderr: 

### ISSUE THREAD

**Issue by programmeddeath1** [kivy/kivy#8125]
**Software Versions**
* Python:
* OS:
* Kivy:
* Kivy installation method:

**Describe the bug**
On executing this line n the below file
> /home/dt/Projects/Work/greenox/venv/lib/python3.7/site-packages/kivy/core/image/__init__.py(677)_img_iterate()
-> imgcount = len(self.image.textures)

it goes into an infinite loop with this error message
```
Exception ignored in: 'kivy.graphics.opengl_utils.gl_has_capability'stderr: Exception ignored in: 'kivy.graphics.opengl_utils.gl_has_capability'stderr: Exception ignored in: 'kivy.graphics.opengl_utils.gl_has_capability'stderr: Exception ignored in: 'kivy.graphics.opengl_utils.gl_has_capability'stderr: Exception ignored in: 'kivy.graphics.opengl_utils.gl_has_capability'stderr: Exception ignored in: 'kivy.graphics.opengl_utils.gl_has_capability'stderr:
......
```

**Expected behavior**
Should load the Kivy App
**To Reproduce**
    GreenuiApp().run()
I have an app running with this command, somewhere in the middle the core gets called and it moves into an infinite loop with these errors.

This app program was running previously, I changed the Yolov5 libraries being used from utils and models folder and replaced it with the latest yolov5 library files.
**Code and Logs and screenshots**
![image](https://user-images.githubusercontent.com/44861370/217892007-f0d31490-1f28-406f-bd4d-28a528194ca8.png)

**Comment by misl6** [comment]
Hi @programmeddeath1 !

Can you please post a minimum reproducible example?
