### ISSUE TITLE
Docs : package for Mac with Buildozer 

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/kivy#8130]
**Software Versions**
* Python:
* OS:
* Kivy:
* Kivy installation method:

**Describe the bug**

Docs say user can package for Mac using Buildozer

https://kivy.org/doc/stable/guide/packaging-osx.html#using-buildozer

Buildozer returns `Unknown command/target osx`

**Expected behavior**

**To Reproduce**

**Code and Logs and screenshots**

**Additional context**

**Comment by misl6** [comment]
```
(venv) mirko@Mirkos-MacBook-Pro my-app % buildozer osx debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for osx
# Check if kivy-sdk-packager exists
# kivy-sdk-packager does not exist, clone it
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  ```
  
  HI @RobertFlatt !
  
`buildozer` supports packaging for `osx`, via `kivy-sdk-packager`, even if it may need some love.
I guess that the error you mentioned (and in that case, we should open an issue on kivy/buildozer instead) is appearing in a non-macOS environment. I'm right?

**Comment by RobertFlatt** [comment]
I did not know this was possible, and I've never heard of anybody using `kivy-sdk-packager`
But that 'some love' comment is a red flag. 

Sometimes I think this project tries to do too much, and some features demo better than they work. 

This was a GoogleGroups question, I don't know the platform, but since I expected it not to work I replicated on WSL!!

**Comment by misl6** [comment]
Tracked the issue on kivy/buildozer.
Thank you for reporting!
