### ISSUE TITLE
Unable to log in to Kivy's Discord

### ISSUE THREAD

**Issue by clickworkorange** [kivy/kivy#8143]
I'm _very_ well aware that this is not the right place for this, but I haven't really got any other option! I'm unable to log in to my existing Kivy Discord account, and the whole thing appears quite broken. See below for the journey I'm following - what could be the problem? 

![Screenshot_2023-02-22_16-15-16](https://user-images.githubusercontent.com/196348/220689338-50ddd167-d212-4ecb-aa6e-b45900fa2869.png)
![Screenshot_2023-02-22_16-14-50](https://user-images.githubusercontent.com/196348/220689352-773d01db-9f36-49b1-bffb-9338f4cdf0eb.png)
![Screenshot_2023-02-22_16-12-57](https://user-images.githubusercontent.com/196348/220689361-f1f55fdc-8d68-40f0-bc1e-359a72642003.png)
![Screenshot_2023-02-22_16-13-26](https://user-images.githubusercontent.com/196348/220689357-56e2cd64-0331-4177-9257-2fec4bc0450f.png)
![Screenshot_2023-02-22_16-11-41](https://user-images.githubusercontent.com/196348/220689366-36d32913-254c-4225-9411-1bf63fd2e534.png)

The fact it says "Deleted User a0dfe087 invited you to join" might have something to do with it?

**Comment by misl6** [comment]
Hi @clickworkorange !

Can you please try to use the following link and report back the result?
https://discord.gg/jSq3gAH9

**Comment by clickworkorange** [comment]
Thanks @misl6 - it looks like it's the mobile phone verification requirement that's keeping me out; with your link I no longer get the "deleted user" warning, but I still end up with "unable to accept invite". A refresh then says "invite invalid" and "continue to Discord" takes me to the "verification required" screen. So basically the same behaviour as the link from kivy.org. 

Hey-ho, i'm used to it - vast swathes of the internet are inaccessible to me because I don't think my private mobile phone number is any of its business (including, I might add, the Kivy "Google Groups" forum). It's particularly unfortunate in this case though since Kivy is a project close to my heart :'( Didn't you use to have an IRC channel? What about Usenet? :D All in private hands now, isn't it?

**Comment by FilipeMarch** [comment]
What's your nickname on Discord? @clickworkorange

**Comment by clickworkorange** [comment]
I'm not sure to be honest, the email address is

![email](https://user-images.githubusercontent.com/196348/220996338-45a86596-34c6-4573-b631-25606908a2cf.png)

**Comment by FilipeMarch** [comment]
You should be able to see your username on the bottom left of Discord.

It is a name followed by four numbers, for example, `Somename#4277`

**Comment by clickworkorange** [comment]
I can't log in unfortunately, but checking old emails I can see it is "Lomax".

**Comment by FilipeMarch** [comment]
> I can't log in unfortunately, but checking old emails I can see it is "Lomax". 

The username is not Lomax, it is Lomax followed by `#` + four numbers

But it does not matter, if you can not log in Discord, you can not use Kivy server. Only logged users can enter on the server.

**Comment by clickworkorange** [comment]
Ok, thank you for trying to help! Can you please delete this issue?

**Comment by misl6** [comment]
Hi @clickworkorange !

Unfortunately, we do not have any control over Discord security policies.
Phone verification is something random, so please try again in future.
