### ISSUE TITLE
Rendering Sinhala Language Wrong in Kivy App

### ISSUE THREAD

**Issue by 31mpmp** [kivy/kivy#8148]
**Software Versions**
* Python: 3.10.9
* OS: Windows, Android
* Kivy: 2.1.0
* Kivy installation method: pip install kivy

I rendered the following text with google Noto Sans Sinhala in kivy app and it is rendered incorrectly. Is Kivy able to render Sinhala characters correctly? As we want to support Sinhala languages ​​​​in our applications. Please help

Example text Expected output:
පාරිභෝගිකයා
![2](https://user-images.githubusercontent.com/107760735/221577407-3f54bd70-df1a-44a5-8565-dc63f70d5201.png)

Kivy application output:
![Screenshot 2023-02-27 090231](https://user-images.githubusercontent.com/107760735/221572786-63d171a1-5f38-4a23-b8ce-0ed5f6d16f27.png)

This happens in all controls - label and text input and we have tried different ttf files.
Can we get some help here please?

Example code:
from kivy.app import App
from kivy.lang import Builder

kv = """
GridLayout:
    id: layout
    cols: 1
    Label:
        text: "පාරිභෝගිකයා"
        font_name: "NotoSansSinhala-Regular.ttf"
        halign: "center"
 

"""

class Main(App):
    def build(self):
        return Builder.load_string(kv)

if name == "main":
    Main().run()

Font file link: https://fonts.google.com/noto/specimen/Noto+Sans+Sinhala

**Comment by misl6** [comment]
Hi @31mpmp !

Our beloved @akshayaurora is working on a PR (https://github.com/kivy/kivy/pull/8115) to support `font_direction` and `font_script` options on top of `SDL_ttf` (one of our core providers), and `Sinh` looks supported.

Can you help to test the PR?

**Comment by misl6** [comment]
> Yes sir I would like to. Will Kivy support sinhala fonts in the future?
Looks planned, but we need some help from the community in order to test all the languages and variations 😄

**Comment by misl6** [comment]
Can you confirm that the following looks correct?

![Image 15-03-23 at 19 09](https://user-images.githubusercontent.com/8177736/225403639-ecbde8dc-a124-40e1-9b71-1e2d0af34a74.jpg)

And, can you please share the logs?

**Comment by misl6** [comment]
Thank you for testing the feature!
