### ISSUE TITLE
在安卓平台读写/sdcard/android/data/包名/提示没有权限

### ISSUE THREAD

**Issue by btcfuna** [kivy/kivy#8151]
**Software Versions**
* Python:
* OS:android
* Kivy:最新的
* Kivy installation method:

**Describe the bug**
在安卓平台读写/sdcard/android/data/包名/提示没有权限

WARNING] stderr: PermissionError: [Errno 13] Permission denied: '/sdcard/android/data/com.xxx.xxx

**Comment by misl6** [comment]
Hi @btcfuna !

Can you please post the full output and your `buildozer.spec` file / `python-for-android` cmd?

**Comment by RobertFlatt** [comment]
On devices running Android >= 10 shared storage must be accessed using the MediaStore api not using OS file operations. See https://github.com/Android-for-Python/Android-for-Python-Users#android-storage for a link to the Android docs and a description of shared storage from the point of view of a Python user.
