### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by 31mpmp** [kivy/kivy#8158]
**Software Versions**
* Python: 3.10.9
* OS:Android
* Kivy:2.1.0
* Kivy installation method:pip install kivy

**Permission denied error**

buildozer.spec
android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
Storage access is given on the android phone.
**When I select an image through plyer filechooser on kivy android apk, the image path is shown correctly in the select_file.text label. But the problem is that after assigning the selected path to the image.source, the Image is not displayed.

I get this error:
03-07 09:23:11.172 23972 24300 I python : [Errno 13] Permission denied: '/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20230306-WA0002.jpg'**

Please help me.

// My code
from kivy.lang.builder import Builder
from kivy.app import App

from kivy.utils import platform
from plyer import filechooser
from kivy.clock import mainthread

if platform == "android":
    from android.permissions import request_permissions, Permission
    request_permissions([Permission.WRITE_EXTERNAL_STORAGE, Permission.READ_EXTERNAL_STORAGE])

kv = """
MDScreen:
    GridLayout:
        cols:1
        padding: dp(10)
        spacing: dp(10)
        Image:
            id: image
            pos_hint: {"center_x": .5, "center_y": .5}

        MDLabel:
            id: select_file
            halign: "center"

        Button:
            text: "Select File"
            size_hint_y: None
            height: "50dp"
            on_press: app.file_manager_open()

"""
class RemoveApp(App):
    def build(self):
        return Builder.load_string(kv)

    def file_manager_open(self):
        fil = [("Images", ".jpg", ".jpeg", "*.png")]
        filechooser.open_file(on_selection=self.handle_selection, filters=fil, multiple=True)

    @mainthread
    def handle_selection(self, selection):
        if not selection:
            return

        self.root.ids.select_file.text = str(selection)
        self.root.ids.image.source = selection[0]
if name == 'main':
    RemoveApp().run()

![1678161294093](https://user-images.githubusercontent.com/107760735/223691870-1ae34e95-cf54-4a01-b975-6edb3425c440.jpg)

**Comment by RobertFlatt** [comment]
The some details of an answer depends on both device android version and on build api version, but...

More generally shared storage is a database not a file system. Python file operations are not available as files can only be referenced by a content uri, and by not a file path. Hence the permissions error.

Read this https://github.com/Android-for-Python/Android-for-Python-Users#android-storage 

I get that this is hard to hear, as I have given you the same response in two other forums.

**Comment by RobertFlatt** [comment]
As I have said on other forums FileChooser is not going to work, so clearly I don't have an example.

This contains a use of the the Android Chooser, but read all the docs as it may not match your use case.

https://github.com/Android-for-Python/shared_storage_example

Also that uses android.api= 32, if you are using android.api 33 read this https://github.com/Android-for-Python/Android-for-Python-Users#storage-permissions The example has not been updated to 33.

**Comment by RobertFlatt** [comment]
Great.
