### ISSUE TITLE
Add an option to force lines to use the custom drawing method

### ISSUE THREAD

**Issue by GreenJon902** [kivy/kivy#8180]
**Is your feature request related to a problem? Please describe.**
When a line has a width of one, it uses GL_LINE to draw, which draws only individual pixels which would normally be fine. But if you have a scatter where it has zoomed in, the line is still just one pixel when it should be thicker.

**Describe the solution you'd like**
I would like a setting that forces the use of the custom drawing method.

**Describe alternatives you've considered**
You could also check whether the line has been transformed or scaled, though that may be more difficult. I could also change the width be not one but then it wouldn't be correct, this could also be problematic if zoomed in a high amount as there are only so many decimal spaces on the width before it rounds it too 1.

**Additional context**
![image](https://user-images.githubusercontent.com/37347905/226192418-efc43fb2-69a5-4f1d-9761-b8a12f9cd115.png)
![image](https://user-images.githubusercontent.com/37347905/226192470-df0e6c10-0492-4580-a9ac-d3f84df0a60e.png)
![image](https://user-images.githubusercontent.com/37347905/226192480-26fa17c2-a762-4a62-8787-97893839f672.png)
From the kivy doc:
![image](https://user-images.githubusercontent.com/37347905/226192575-83670d47-f894-4f9c-8f2f-ba5d72232c71.png)

**Comment by misl6** [comment]
Closed via #8228
