### ISSUE TITLE
The system cannot find the path specified. while building documentation

### ISSUE THREAD

**Issue by a-sajjad72** [kivy/kivy#8186]
**Software Versions**
* Python: 3.10.8
* OS: Windows 10 Version 22H2
* Kivy: 2.2.0.dev0
* Kivy installation method: Editable Install

**Describe the bug**
i tried to build documentation but failed due to `The system cannot find the path specified.` Even python is on my path as shown in screenshot but receing error.

**Expected behavior**
I should start building documentation.

**To Reproduce**
- create a virtual environment
- fetch the latest code from github.
- install additional dependencies (MSVC v143 - VS 2022 C++ x64/x86 build tools (latest) and C++ ATL for latest v143 build tools (x86 & x64)
- install kivy by `python -m pip install -e ".[dev,full]"`
- get into the `doc` folder install sphinx
- at last `make html`

**Code and Logs and screenshots**
```
The system cannot find the path specified.
The system cannot find the path specified.
makefile:13: *** "PYTHON=python not found in D:\LECTURES\Development\Documentation\Python Docs\KivyDocs/Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\;C:\Users\HaLF-MenTaL\AppData\Local\Microsoft\WindowsApps;C:\Users\HaLF-MenTaL\AppData\Local\Programs\Microsoft VS Code\bin;C:\shortcuts;C:\mingw64\bin;D:\SOFTWARES\yt-dlp;C:\boost;C:\boosttools\build;C:\Users\HaLF-MenTaL\Downloads\Compressed\edgedriver_win64;C:\CMake\bin;D:\Code Playground\Python\photo-sharing\Scripts;C:\Program Files (x86)\GnuWin32\bin".  Stop.
```
![image](https://user-images.githubusercontent.com/90617891/227682822-712fef2c-b905-4bf5-b31d-1e14004fdd5c.png)

**Additional context**

**Comment by misl6** [comment]
What happens if you run `make html` in the kivy project root?
