### ISSUE TITLE
REVERSED LINES IN WRAPPED TEXTS FOR FIX RTL LANGS PROBLEM

### ISSUE THREAD

**Issue by mablue** [kivy/kivy#8189]
**Is your feature request related to a problem? Please describe.**
I'm from Persian community my problem on typing Persian on my app which is an RTL language everything is fixed by use these two libraries but still a problem is present and its reversed lines order in wrapped texts
```
import arabic_reshaper
from bidi.algorithm import get_display

text = get_display(arabic_reshaper.reshape("لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد."))
```
 if some body can help about that we can use kivy for our apps.

**Describe the solution you'd like**
The problem is that: when a persian text wraps to multiple lines its lines order is reversed and if somebody can reverse it again It will be fixed.
also please append these two bidi and arebic_reshaper internally on kivy to automaticly get a fix to arebic and persian users thanks.

**Comment by misl6** [comment]
Hi @mablue !

Can you please check if it looks fixed on our `master` branch?


### A mini-guide for your specific use-case

**Install the nightly wheels with:**
```bash
python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/
```

**Add `font_script_name` and `font_direction` properties to your label.**
As an example:

```kv
Label:
    text: "YOUR_TEXT_GOES_HERE"
    font_script_name: "Arab"
    font_direction: "rtl"
```

**The rendered text now looks good?**

**Comment by mablue** [comment]
wooow fixed! Thanks.
Please Append it to mainstream
![image](https://user-images.githubusercontent.com/5004900/229371486-9e5b015e-e7b9-4f59-9b5f-271b835e24d5.png)

**Comment by misl6** [comment]
Already merged, and a release will be available soon 😀

**Comment by mablue** [comment]
how should I install this things on buildozer?! requirements not working well. @misl6

**Comment by omaryo010** [comment]
it's not working

**Comment by mablue** [comment]
> it's not working

I'm using it right now @omaryo010 but just in pc and don't know how should I put it in buildozer deps

**Comment by hboy0537-del** [comment]
Bad library.. it doesn't support Arabic
