### ISSUE TITLE
Ability to choose newer version of pandas

### ISSUE THREAD

**Issue by kwebber3** [kivy/kivy#8205]
**Is your feature request related to a problem? Please describe.**
I can't use the explode function for multiple columns because the current recipe for pandas uses something before version 1.3

**Describe the solution you'd like**
A pandas recipe that is newer than 1.3

**Describe alternatives you've considered**
The ability to choose pandas version (remove the numpy patch)

Thank you so much in advance!

**Comment by misl6** [comment]
Hi @kwebber3 !
Please open this feature request on `kivy-ios` or `python-for-android` 🙂
https://github.com/kivy/kivy-ios
https://github.com/kivy/python-for-android
