### ISSUE TITLE
Image with rounded corners

### ISSUE THREAD

**Issue by acgc99** [kivy/kivy#8236]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need an image with rounded corners that keeps ratio and I use `FitImage` from `kivymd`, that does not keep the image ratio.

**Describe the solution you'd like**
Add a `radius` argument for `Image`.

**Describe alternatives you've considered**
I considered drawing a `RoundedRectangle` with the image as source, but the ratio is not kept.

**Comment by misl6** [comment]
Hi @acgc99 !

Can you post some examples of what you're trying to achieve?

**Comment by acgc99** [comment]
I want something like the standard `Image` but with an optional argument to set rounded borders, like in the `FitImage` from `kivymd` (but this doesn't allow you to keep image ratio, as I want).

You can use a `RoundedRectangle`, but the image ratio is not kept, the image is stretched to fill all the rectangle.

```
from kivy.app import App
from kivy.uix.screenmanager import Screen
from kivy.graphics import RoundedRectangle

class UI(App):
    
    
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.screen = Screen()
        
        with self.screen.canvas:
            
            RoundedRectangle(
                pos = (100, 0),
                size = (200, 700),
                source = r"./image.jpg"
            )
    
    
    def build(self):
        
        return self.screen


UI().run()
```

This is the result:

![Screenshot 2023-05-13 112731](https://github.com/kivy/kivy/assets/96864661/e3044a79-aac4-49ff-b38a-c09f0211f84d)

This does not keep image ratio since the image has to fill all the rectangle. In the standard `Image` you can set the size of the widget and keep image ratio.

**Comment by misl6** [comment]
Hi @acgc99 !

That looks something you can easily achieve via the newer `fit_mode` feature (https://kivy.org/doc/master/api-kivy.uix.image.html#kivy.uix.image.Image.fit_mode) [Available on `Kivy2.2.0rc1` and onwards) + some canvas instructions.

Feel free to jump into our support channels to get help with the new feature (or the legacy ones) and canvas instructions.
