### ISSUE TITLE
Window.fullscreen mode to true causes isues on linuxmint

### ISSUE THREAD

**Issue by Noor-Kalibbala** [kivy/kivy#8237]
when i try to switch to window.fullscreen = True, i get the error below perherps from x server 
`X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x8000014
  Serial number of failed request:  909
  Current serial number in output stream:  911`

**Comment by Noor-Kalibbala** [comment]
setting it to 'auto' just displays a black screen

**Comment by misl6** [comment]
Hi @Noor-Kalibbala !

Can you confirm if the issue persists on `Kivy==2.2.0rc1` ?

`Kivy==2.2.0rc1` is installable via `pip install --pre kivy`

**Comment by Noor-Kalibbala** [comment]
> pip install --pre kivy

@misl6 it works like charm! how is this installation different from normal pip install kivy.

**Comment by misl6** [comment]
Thank you for testing the pre-release version!

(PS: `Kivy==2.2.0` will land in few days 😀)
