### ISSUE TITLE
Extra position in undo list after all? 'shifted' characters.

### ISSUE THREAD

**Issue by RadoslawGlebicki** [kivy/kivy#8259]
**Software Versions**
* Python: 3.7.3
* OS: Linux Fedora 30
* Kivy: 2.1.0
* Kivy installation method: rpm

**Describe the bug**
In TextInput after write letters using `shift` I get extra position in undo list with empty ('delsel', cIdx, '')
cIdx - is cursor index that same as letter write with shift. So after is ('insert', cIdx, cIdx+1)
''       - empty string

The effect: `ctrl+z` have to be press twice. Second just move cursor.

**Expected behavior**
Only one position in undo list like other letters.

**To Reproduce**
from kivy.app import runTouchApp
from kivy.uix.textinput import TextInput

koTxt=TextInput(text = 'sdfdsf dfg ds fdsf gffg fdg fgf dgdsfds\nasfds fdgf gfd gfd af sfds',size_hint=(1,1))

runTouchApp(koTxt)
quit()

**Code and Logs and screenshots**
{'undo_command': ('delsel', 13, ''), 'redo_command': (13, 13)}
{'undo_command': ('insert', 13, 14), 'redo_command': (13, '*')}

**Comment by atharva-satpute** [comment]
Can I take up this issue?

**Comment by RadoslawGlebicki** [comment]
Hi.
Are you asking me?
Sorry I am new on Git Hub. Do whatever is necessary.

Radek
