### ISSUE TITLE
large text display

### ISSUE THREAD

**Issue by peternasser99** [kivy/kivy#8269]
**Is your feature request related to a problem? Please describe.**
as of now i dont know of anyway to display large texts in a kivy app on any platform 
*large in terms of number of lines regardless of their actual character content ie. using a label widget or text input to display  text breaks on windows pc on line 950 and on android 400ish line [previous bug report](https://github.com/kivy/kivy/issues/8213) 

**Describe the solution you'd like**
A dedicated widget for text display.

**Describe alternatives you've considered**
🤷‍♀️🤷‍♀️.

**Comment by akshayaurora** [comment]
TextInput:
    text: large_text
    readonly: True

... does this not fix/work for what you want ?
