### ISSUE TITLE
Problems with custom titlebar at Windows

### ISSUE THREAD

**Issue by mak8kammerer** [kivy/kivy#8279]
**Software Versions**

- Python: 3.9.5
- OS: Windows 10 Pro (64-bit)
- Installation metod: pip
- Kivy version: 2.2.0 (also tested on 2.1.0)
- Window provider: kivy_deps.sdl2 (0.6.0)

Hello everyone! Recently, I decided to add a custom titlebar to my desktop application and encountered some incorrect behavior with this feature.

In general, I discovered two issues:

- After moving the window, all widgets "shift" to the right.
- After moving the window, it becomes impossible to click buttons as the touch area moves upward.

It should be noted that the set_custom_titlebar() function always returns True.
Below is a video showing the execution of the [custom_titlebar.py](https://github.com/kivy/kivy/blob/master/examples/miscellaneous/custom_titlebar.py) script from the kivy-examples.

https://github.com/kivy/kivy/assets/130763512/aac3c28e-9e93-4104-af8c-fd01270f25f2

**P.S.**: Perhaps I misunderstood something, and windows with custom titlebars cannot be moved?

**Comment by p0lygun** [comment]
onto this

**Comment by mak8kammerer** [comment]
Sorry for the long response.
The problem was solved by setting `KIVY_GL_BACKEND = "angle_sdl2"`.
Maybe the problem is related to my video drivers.

**Comment by HammadRafique29** [comment]
> Sorry for the long response. The problem was solved by setting `KIVY_GL_BACKEND = "angle_sdl2"`. Maybe the problem is related to my video drivers.

If problem is solved, you should close the issue 👍
