### ISSUE TITLE
Kivy 2.2.0 is setting root logger level to DEBUG

### ISSUE THREAD

**Issue by mark-blackburn-orpyx** [kivy/kivy#8282]
**Software Versions**
* Python: 3.10.6
* OS: Windows 10
* Kivy: 2.2.0
* Kivy installation method: pip install Kivy==2.2.0

**Describe the bug**
Kivy imports are setting the level of the root logger

**Expected behavior**
Imports should not change the root logger level

**To Reproduce**

**Code and Logs and screenshots**
```
import logging
print(logging.getLogger('root').getEffectiveLevel()) # prints 30 - logging.WARNING
from kivy.clock import Clock
print(logging.getLogger('root').getEffectiveLevel()) # prints 0 - logging.DEBUG
```

Output
```
PS C:\Users\MarkBlackburn> python .\test_kivy_logging.py
30
[INFO   ] [Logger      ] Record log in C:\Users\MarkBlackburn\.kivy\logs\kivy_23-06-16_40.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.0
[INFO   ] [Kivy        ] Installed at "C:\Users\MarkBlackburn\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\MarkBlackburn\AppData\Local\Programs\Python\Python310\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
0

```

**Additional context**

**Comment by misl6** [comment]
This is actually something expected.

Previously, Kivy took over the root logger, which was bad for integration with other tools.

This PR: https://github.com/kivy/kivy/pull/7988 fixed this behavior, and added an option for log modes: https://kivy.org/doc/stable/api-kivy.logger.html#logger-configuration.

What you're looking for is likely `PYTHON` or `MIXED` mode, and not the default `KIVY` mode.

(Consider submitting a PR to improve documentation, if you have any suggestion 😉)
