### ISSUE TITLE
`imghdr` is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by misl6** [kivy/kivy#8294]
We currently make use of the `imghdr` module to guess the filetype with our `ImageLoader`.

See: https://peps.python.org/pep-0594/#imghdr

**Comment by bharathan06** [comment]
Thank you so much! id like to contribute with another person. 
It would be great if you could assign it to them too! 

Their github link : https://github.com/vsh9

**Comment by p0lygun** [comment]
@bharathan06 I don't think this issue needs two people to solve :thinking:,  `imghdr` is only used to find the extension of the image file, 
see https://github.com/kivy/kivy/blob/ca1b918c656f23e401707388f25f4a63d9b8ae7d/kivy/core/image/__init__.py#L452-L461

I propose using [`filetype`](https://pypi.org/project/filetype/) as it supports a lot of file types

**Comment by baseplate-admin** [comment]
> I propose using [filetype](https://pypi.org/project/filetype/) as it supports a lot of file types

I think it's better to use magic number to detect a subset of the fileformat ( same method used by imghdr )

**Comment by p0lygun** [comment]
> > I propose using [filetype](https://pypi.org/project/filetype/) as it supports a lot of file types
> 
> I think it's better to use magic number to detect a subset of the fileformat ( same method used by imghdr )

from filetype docs
> Small and dependency-free [Python](http://python.org/) package to infer file type and MIME type checking the [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_numbers_in_files) signature of a file or buffer.

**Comment by Julian-O** [comment]
@bharathan06: Just checking in. How did you go with this?

**Comment by misl6** [comment]
I'm considering @bharathan06 not available anymore to take care of it, the issue is now in 3.0.0 roadmap and free to pick.

**Comment by kengoon** [comment]
@misl6 i want to take on it.

**Comment by misl6** [comment]
That's something lovely to hear @kengoon !

Assigned the issue. Please bear in mind that we're in `3.0.0`, so don't be afraid to do any refactoring / cleanup if needed.
