### ISSUE TITLE
two minor Linux install bugs

### ISSUE THREAD

**Issue by auwsom** [kivy/kivy#8305]
Ubuntu 22.04 LTS 
Python 3.10.6

`python -m virtualenv kivy_venv` creates a dir with no ../bin
using `python -m venv kivy_venv` does.

`curl -O https://raw.githubusercontent.com/kivy/kivy/master/tools/build_linux_dependencies.sh -o build_kivy_deps.sh` does not create the intended file
`curl https://raw.githubusercontent.com/kivy/kivy/master/tools/build_linux_dependencies.sh -o build_kivy_deps.sh` does. (conflicting option flags)

**Comment by misl6** [comment]
Hi @auwsom !

How about improving our docs via a PR? 😀

**Comment by jfishzon** [comment]
Hello, 
created a PR related to this issue.
https://github.com/kivy/kivy/pull/8324

**Comment by misl6** [comment]
Fixed via #8324
