### ISSUE TITLE
I think KIVY should build a project similar to the previous KIVY designers.

### ISSUE THREAD

**Issue by ChinaGodzilla** [kivy/kivy#8306]
I think KIVY should build a project similar to the previous KIVY designers.

The future will be a low-code era, and projects that are difficult to generate with AI, such as UI, should be designed visually.

**Comment by willtejeda** [comment]
This might be something you could create WITH AI , it would be interesting
to see if we could find some open source UI maker gui thing that could be
passed into an LLM to make it useful for kivy

**Comment by p0lygun** [comment]
it does seem interesting :thinking:

**Comment by Julian-O** [comment]
* Kivy Designer has been archived for 3 years after never making it out of alpha stage. I don't think there is any value in saying to the Kivy developers "I wish this would be made." What is required is volunteers who are willing to put the time into making it. Looking at it briefly, it seems to need a lot of work.

* I see no reason why such a project should be under the auspices of the Kivy Team. Generally, people who make IDEs and people who make compilers, libraries and frameworks used by the IDEs are different teams of people - there is no need for tight co-ordination between them. I would recommend to the Kivy team they don't adopt another project like this themselves, but be supportive of any team willing to try (and perhaps join such teams as individuals if they are interested).

* The original request here was "We need a visual tool for the work that can't be done by AI" and the comments seem to have co-opted that into a much bigger, ambitious project to generate UI designs with AIs. That sounds like a completely separate project, also outside the auspices of the Kivy team, with its own need for volunteers (with a very different skillset).

I hope you can find the volunteers to do the projects that excite you, but I would recommend this issue be marked as closed as not a Kivy bug or feature.

**Comment by misl6** [comment]
Closing as not really tied with `kivy/kivy`, feel free to start a discussion on https://github.com/orgs/kivy/discussions
