### ISSUE TITLE
Clipboard (under Windows) fails to copy special symbols (affects for example TextInput)

### ISSUE THREAD

**Issue by Xovaryu** [kivy/kivy#8314]
* Python: 3.10.9
* OS: Windows 10
* Kivy: 2.1.0 & 2.2.1
* Kivy installation method: pip install

The `Clipboard` (at least under Windows) fails to copy strings that have certain symbols, such as 💜 and 💠 and will, if attempting to copy those, result in an empty clipboard instead. Of course text, even with such symbols, should copy into the system clipboard properly. Other processing of such symbols including pasting and reading out work as expected.

**To Reproduce**
```python
from kivy.core.clipboard import Clipboard
text="Hello World"
Clipboard.copy(text)
print(Clipboard.paste()==text)#True

text="Hello 💠 World"
Clipboard.copy(text)
print(Clipboard.paste()==text)#False
```

I'm fairly confident that the exact issue resides within clipboard_winctypes.py in the put method. The `text` variable arrives here well-formed as it should be, but never actually makes it to the system clipboard.
I have verified this by simply replacing the entire put method somewhat lazily with:
```python
import win32clipboard
#...
def put(self, text, mimetype='text/plain'):
	win32clipboard.OpenClipboard()
	win32clipboard.EmptyClipboard()
	win32clipboard.SetClipboardData(win32clipboard.CF_UNICODETEXT, text)
	win32clipboard.CloseClipboard()
```
Which has indeed allowed me to run my Kivy app with text fields that can now copy any of their contents as opposed to just any content without such symbols.

I have not submitted this as a fix and pull request since I'm not aware why exactly the `put` method looks like it does. Someone in the know should be able to make a general fix relatively easily with the provided information though.

**Comment by pythonic64** [comment]
Try using sdl2 clipboard. Before any `kivy` imports do:
```python
import os
os.environ['KIVY_CLIPBOARD'] = 'sdl2'
```

**Comment by Xovaryu** [comment]
> Try using sdl2 clipboard.

...Yeah I could've had the idea to instead try a different provider like that myself. And yes, this works. While I still consider the `ctypes` implementation bugged, at least for me this additional line of code is as good as a fix.

**Comment by pythonic64** [comment]
@Xovaryu I agree that `ClipboardWindows` has a bug when special characters are used, but until this bug gets fixed using sdl2 clipboard is an option for your app.

**Comment by p0lygun** [comment]
anyone working on this ? if not I'll try to fix

**Comment by pythonic64** [comment]
@p0lygun go for it.

**Comment by p0lygun** [comment]
pr up

**Comment by p0lygun** [comment]
yes, i just need to clean up a few things, will do in a min

**Comment by HammadRafique29** [comment]
> yes, i just need to clean up a few things, will do in a min 

Ok

**Comment by p0lygun** [comment]
> > yes, i just need to clean up a few things, will do in a min
> 
> Ok

issue fixed, waiting for PR to merge
