### ISSUE TITLE
✨ Provide kivy stubs

### ISSUE THREAD

**Issue by jd-solanki** [kivy/kivy#8321]
**Is your feature request related to a problem? Please describe.**
I'm trying kivy in vscode and getting error `Stub file not found for "kivy.app"PylancereportMissingTypeStubs`

**Describe the solution you'd like**
Provide kivy stubs

**Describe alternatives you've considered**
Running red lined code 😅 

**Additional context**
None

**Comment by afriddev** [comment]
share the full log

**Comment by afriddev** [comment]
change file name  else uninstall kivy module and re install
