### ISSUE TITLE
cannt import install_twisted_reactor  with kivy  and twsited application   when  execute a converted .exe 

### ISSUE THREAD

**Issue by icarus0508** [kivy/kivy#8328]
**Software Versions**
* Python:  Python 3.11.4
* OS: Windows 10
* Kivy: 2.2.1
* Kivy installation method: pip 

**Describe the bug**

I made a python server application   with   kivy and  twisted,  **it works fine on .py**  but not work with a **.exe** I convert by pyinstaller .

The build is okay but when i execute it , i will face a error like folllowing 

![image](https://github.com/kivy/kivy/assets/11284692/00bd9b90-6689-4789-9754-7b3872d706b1)

**Expected behavior**
i can fun a .exe build as regular python did.

**To Reproduce**
make a python app  with  kivy  and twisted .

Add   " 
from kivy.support import install_twisted_reactor    
             install_twisted_reactor() "
to code

Thanks for helping

**Comment by pythonic64** [comment]
@icarus0508 Have you tried adding `'twisted.internet._threadedselect'` to hiddenimports list in your `.spec` file?
