### ISSUE TITLE
Button state animation and property inconsistent while running applications without X

### ISSUE THREAD

**Issue by srolf** [kivy/kivy#8329]
**Software Versions**
* Python: 3.10.6
* OS: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1034-raspi aarch64)
* Kivy: 2.2.1
* Kivy installation method: $sudo pip3 install "kivy[base]" kivy_examples

**Describe the bug**
Button state animation and property behaves inconsistent while running applications without X (systemctl disable/stop gdm3).

Update: Seems only to occur while using "fkms" driver (see comments below)

Events "on_press" and "on_release" are correctly detected via binding a callback while running the application without Gnome desktop.
But the default animations correlated to "normal" and "down" state are mostly not inline with the real status if the button is pressed or not.
Also the button state property is out of sync while accessing it from inside of a callback.
This behavior cannot be observed while running the application from Gnome desktop.

Considering the [documentation for RPi/7'](https://kivy.org/doc/stable/installation/installation-rpi.html#using-official-rpi-touch-display) was making no difference in the behaviour without X.

System: Raspberry Pi 3B with [official 7' touch display](https://www.raspberrypi.com/documentation/accessories/display.html) (DSI)

**Expected behavior**
Button state animation and property is always in sync with real button status pressed/not pressed while running application without X.

**To Reproduce**
main.py (started without Gnome desktop, just from CLI; unluckily not checked against *latest kivy master*, only 2.2.1)

```python
import kivy
kivy.require('1.0.7')

from kivy.app import App

class TestApp(App):
    pass

if __name__ == '__main__':
```
test.kv
```kv
#:kivy 1.0

Button:
    text: 'Hello from test.kv'
```

**Code and Logs and screenshots**
![image](https://github.com/kivy/kivy/assets/24922574/29aef273-7c07-4536-af36-3ea6d3c88848)
main.py
```python
import kivy

kivy.require("2.2.1")

from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button
from kivy.uix.label import Label

class ButtonApp(App):
     
    label1 = None
    label2 = None

    def build(self):

        layout = GridLayout(rows=2, cols=2)
         
        btn1 = Button(text ="Push Me !",
            font_size ="20sp",
            size_hint =(.2, .2),
        )
        btn1.bind(on_press = self.callback_btn1_pressed)
        btn1.bind(on_release = self.callback_btn1_released)
        layout.add_widget(btn1)

        btn2 = Button(text ="Or Here ...",
            font_size ="20sp",
            size_hint =(.2, .2),
        )
        btn2.bind(on_press = self.callback_btn2_pressed)
        btn2.bind(on_release = self.callback_btn2_released)
        layout.add_widget(btn2)

        self.label1 = Label(
            text = "B1: " + str(btn1.state),
            size_hint =(.01, .01)
        )
        layout.add_widget(self.label1)

        self.label2 = Label(
            text = "B2: " + str(btn2.state),
            size_hint =(.01, .01)
        )
        layout.add_widget(self.label2)

        return layout

    def callback_btn1_pressed(self, event):
        self.label1.text = "B1: " + str(event.state)
        print("button <%s> pressed" % event.text)

    def callback_btn1_released(self, event):
        self.label1.text = "B1: " + str(event.state)
        print("button <%s> released" % event.text)

    def callback_btn2_pressed(self, event):
        self.label2.text = "B2: " + str(event.state)
        print("button <%s> pressed" % event.text)

    def callback_btn2_released(self, event):
        self.label2.text = "B2: " + str(event.state)
        print("button <%s> released" % event.text)

root = ButtonApp()

root.run()
```

**Additional context**
~/.kivy/config.ini
```
[kivy]
keyboard_repeat_delay = 300
keyboard_repeat_rate = 30
log_dir = logs
log_enable = 1
log_level = info
log_name = kivy_%y-%m-%d_%_.txt
window_icon = 
keyboard_mode = 
keyboard_layout = qwertz
desktop = 1
exit_on_escape = 1
pause_on_minimize = 0
kivy_clock = default
default_font = ['Roboto', 'data/fonts/Roboto-Regular.ttf', 'data/fonts/Roboto-Italic.ttf', 'data/fonts/Roboto-Bold.ttf', 'data/fonts/Roboto-BoldItalic.ttf']
log_maxfiles = 100
window_shape = data/images/defaultshape.png
config_version = 27

[graphics]
display = -1
fullscreen =
height = 480
left = 0
maxfps = 60
multisamples = 2
position = auto
rotation = 0
show_cursor = 1
top = 0
width = 800
resizable = 1
borderless = 0
window_state = visible
minimum_width = 0
minimum_height = 0
min_state_time = .035
allow_screensaver = 1
shaped = 0
vsync = 
verify_gl_main_thread = 1
custom_titlebar = 0
custom_titlebar_border = 5
always_on_top = 0
show_taskbar_icon = 1

[input]
mouse = mouse
%(name)s = probesysfs

[postproc]
double_tap_distance = 20
double_tap_time = 250
ignore = []
jitter_distance = 0
jitter_ignore_devices = mouse,mactouch,
retain_distance = 50
retain_time = 0
triple_tap_distance = 20
triple_tap_time = 375

[widgets]
scroll_timeout = 250
scroll_distance = 20
scroll_friction = 1.
scroll_stoptime = 300
scroll_moves = 5

[modules]

[network]
useragent = curl
implementation = default
```
Log file (without X, inconsistent behaviour)
```
[INFO   ] [Logger      ] Record log in /home/stefan/.kivy/logs/kivy_23-07-26_87.txt
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.10/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
[INFO   ] [Python      ] Interpreter at "/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 22.2.5-0ubuntu0.1~22.04.3'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VC4 V3D 2.1'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Unable to connect to X server
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [MTD         ] Read event from </dev/input/event1>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [MTD         ] </dev/input/event1> range position X is 0 - 799
[INFO   ] [MTD         ] </dev/input/event1> range position Y is 0 - 479
[INFO   ] [MTD         ] </dev/input/event1> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event1> axes inversion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event1> rotation set to 0
button <Push Me !> pressed
button <Push Me !> released
button <Push Me !> pressed
button <Push Me !> released
button <Push Me !> pressed
button <Push Me !> released
<-snip->
button <Or Here ...> pressed
button <Or Here ...> released
button <Or Here ...> pressed
button <Or Here ...> released
button <Or Here ...> pressed
button <Or Here ...> released
button <Push Me !> pressed
button <Push Me !> released
button <Push Me !> pressed
button <Push Me !> released
<-snip->
button <Push Me !> pressed
button <Push Me !> released
button <Push Me !> pressed
button <Push Me !> released
^C[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/home/stefan/Documents/Python/Kivy/ButtonTest/main.py", line 67, in <module>
     root.run()
   File "/usr/local/lib/python3.10/dist-packages/kivy/app.py", line 956, in run
     runTouchApp()
   File "/usr/local/lib/python3.10/dist-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/usr/local/lib/python3.10/dist-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/usr/local/lib/python3.10/dist-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/usr/local/lib/python3.10/dist-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/usr/local/lib/python3.10/dist-packages/kivy/clock.py", line 689, in idle
     usleep(1000000 * sleeptime)
   File "/usr/local/lib/python3.10/dist-packages/kivy/clock.py", line 965, in usleep
     _usleep(microseconds, self._sleep_obj)
   File "/usr/local/lib/python3.10/dist-packages/kivy/clock.py", line 556, in _usleep
     _libc_usleep(int(microseconds))
 KeyboardInterrupt
```

**Comment by srolf** [comment]
While trying to get closer to the issue, there is an noticeable hint:

Because of a bug in the current RPi kernel (introduced after initial 22.04 release), I cannot use the "full KMS" driver. It would cause a display reset (at least it looks like this) and the rotation is changing. By using "fake KMS" the reset cannot be reproduced.
```
# workaround for current bug (reset of display during boot)
#dtoverlay=vc4-kms-v3d
dtoverlay=vc4-fkms-v3d
gpu_mem=64
```
Nevertheless, **while using "full KMS" for for further tests, the inconsistent behaviour seems not to occur** (beside that the touch coordinates are expected inverted).

**Is the "fake KMS" driver causing the inconsistent animation/state behaviour?**

**Comment by srolf** [comment]
Some more hints:

I was able to reproduce the observation also on a RPi4 connect to a FullHD display over HDMI after changing to "fake KMS".

With unchanged config.txt even if "full KMS" is configured by default, llvmpipe is used (unexpected):
- little slow but no issue about button animation/state

By changing the config.txt to use "fake KMS" and 64MB for GPU memory, llvmpipe is again used:
- here the same behaviour like on the RPi3 with fkms can be observed
- on the terminal screen, continuously an error from vc4 is reported (also seen on RPi3)

![image](https://github.com/kivy/kivy/assets/24922574/b1ec7f93-1344-4bfa-9982-4d07964f5cf9)

**Comment by srolf** [comment]
Another day, additional tests and some observations:

RPi 4, Ubuntu 22.04.02 LTS, using the gnome desktop and "full KMS" driver.
`dtoverlay=vc4-kms-v3d`

RPi connected over HDMI and USB to a touch display.
`Bus 001 Device 006: ID 28e9:028a GDMicroelectronics BJYP-L1-V1.09`

Running the "main.py" example, after a few touch presses on "Press Me !",
- animation OK
- state variable NOK (out of sync)

![image](https://github.com/kivy/kivy/assets/24922574/c5da1941-5596-416d-9c6c-d51066868c9e)

Meanwhile it looks for me more like a glitch in Kivy framework event/callback handling rather a direct relation to kms/fkms.

**Comment by srolf** [comment]
Here is the same test as above (using gnome desktop) just in application full-screen mode, with the same touch display but on a AMD Ryzen 3 3200u. The observation is the same compared to RPi4 like above:

- animation OK
- state variable NOK (out of sync)

For the Kivy input configuration the following is used:
```
[input]
mouse = mouse
hid_%(name)s = probesysfs,provider=hidinput
```
So my observation is becoming even more independent from using a Raspberry Pi.

**Comment by srolf** [comment]
Meanwhile I "kind of" made it. Therefore: Please don't waste time with my trouble.

At the end of many try-and-error aaproaches, I
- reinstalled the RPi3 with Ubutntu MATE 22.04 LTS 64bit
- disabled lightdm (in order to work without X)
- and resolved the upside-down display by Kivy config.ini (and not by fiddling around with any RPi specific stuff)
- changing in `[graphics]` the parameter `rotation = 180`

The touch coordinates and events are working fine.

A remaining issue is an inverted mouse cursor and its cooridnates. I tried also to adapt this in the Kivy config, but wasn't successful. For the moment I don't care too much about it and set `show_cursor = 0`.

**Comment by pythonic64** [comment]
@srolf Can you check if hover event with mouse is giving you the correct position for the cursor? Line 18 shows `me.pos` which should hold the correct position.
```python
from kivy.app import App
from kivy.uix.label import Label


class Kivy8329App(App):

    def build(self):
        return Label()

    def on_start(self):
        super().on_start()
        self.root_window.bind(on_motion=self._on_motion)

    def _on_motion(self, window, etype, me):
        if me.type_id == 'hover' and me.device == 'mouse':
            me.push()
            window.transform_motion_event_2d(me)
            self.root.text = str(me.pos)
            me.pop()


if __name__ == '__main__':
    Kivy8329App().run()

```

**Comment by srolf** [comment]
@pythonic64 If we could find out how to resolve the remaining trouble with the mouse it would be great, because Kivy is working nicely now also on the 7' touch display and having beside touch also mouse usable would give some more possibilities for GUI layouts (e.g. dozens of small buttons, ...).

With `[graphics]` param
`height = 480`
`width = 800`
`rotation = 180`

coordinates are shown as
top left corner 0.0, 479.0
bottom right 799.0, 0.0

Mouse movement is inverted and mouse cursor is upside-down (as expected).

**Comment by pythonic64** [comment]
Idea: you can do an inverse rotation of the mouse position with `MotionEvent.scale_for_screen` method and you can drawn your own cursor indicator instead which you can set to a correct rotation.

Touch events are transformed using `transform_motion_event_2d` before dispatch to widget tree and they are working for your case, so mouse position from my example above should also collide with widgets correctly.

**Comment by srolf** [comment]
Thanks you for the hint. I'm meanwhile also thinking about a mechanical solution: Right now I'm using a case from OneNine which leads due to it's design to the 180° screen rotation. But the cases from SmartiPi would allow a correct placement without rotation.
