### ISSUE TITLE
Cannot launch basic app in Windows 11 via WSLg (Ubuntu 23.04)

### ISSUE THREAD

**Issue by ethteck** [kivy/kivy#8334]
**Software Versions**
* Python: 3.11
* OS: Ubuntu 23.04
* Kivy: 2.2.1
* Kivy installation method: `poetry add kivy[base]` 
* Windows 11 23H2 (OS Build 22631.2115)
* WSL 2

**Describe the bug**
I get the following log and error when launching a basic demo application:
```
[INFO   ] [Logger      ] Record log in /home/ethteck/.kivy/logs/kivy_23-07-31_1.txt
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "/home/ethteck/.cache/pypoetry/virtualenvs/evbdiff-lMgar_9g-py3.11/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.11.2 (main, May 30 2023, 17:45:26) [GCC 12.2.0]
[INFO   ] [Python      ] Interpreter at "/home/ethteck/.cache/pypoetry/virtualenvs/evbdiff-lMgar_9g-py3.11/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  148 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  103
  Current serial number in output stream:  104
  ```

**Expected behavior**
A non-error

**To Reproduce**
Run the provided code in my environment

**Code and Logs and screenshots**
```python
import kivy

kivy.require("2.2.1")

from kivy.app import App
from kivy.uix.label import Label


class EVBDiffApp(App):
    def build(self):
        return Label(text="Hello World")


if __name__ == "__main__":
    EVBDiffApp().run()
```

**Additional context**
None I can think of

**Comment by RobertFlatt** [comment]
Works for me.   (WSL2, Ubuntu 22.04, Py 3.10. kivy 2.1.1 install with pip)

So it could be the Ubuntu version, WSL version (you don't say), also could be Windows version (you don't say) check this https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites

**Comment by ethteck** [comment]
I'm on WSL 2 and Windows 11, both latest versions. I've updated the issue description with that info. I'm able to open other GUI apps from WSL so I know WSLg is working

**Comment by AccelQuasarDragon** [comment]
reminder, this isn't WSL, it's WSLg, `Enabling the Windows Subsystem for Linux to include support for Wayland and X server related scenarios`

https://github.com/microsoft/wslg

**Comment by AccelQuasarDragon** [comment]
![WSLG](https://github.com/kivy/kivy/assets/138998466/5a2db579-d222-4954-a664-e0719d44c899)
update:
@ethteck i got it to work, time to retrace steps.
on win 11, python3.10 fresh install of WSL/WSLG (WSLG is with the latest WSL update)
did sudo apt update

re: poetry, was installed on my host windows, still miraculously worked in WSLG,
`poetry update` worked from within WSLG

repo I used: https://github.com/ShootingStarDragon/Kivy-3.9.5
I didn't bother installing pyenv to wsl so I went the lazy route and said `python = "^3.9.5"`

then i did poetry shell > python main.py > it worked

**Comment by ethteck** [comment]
I figured it out. I had, from some other issue I was troubleshooting, the following line in my .bashrc:
```
export LIBGL_ALWAYS_INDIRECT=1
```
Removing this and starting a new shell fixed my issues!

Thanks to this comment for helping me figure it out https://github.com/microsoft/wslg/issues/321#issuecomment-966588587

Closing :)
