### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by HoshiSoraa** [kivy/kivy#8336]
**Software Versions**
- * Python: 3.11.4
* OS: Windows 
* Kivy: 1.1.1
* Kivy installation method: pip install kivy

**Describe the bug**
NameError: name "Test" is not defined

**Expected behavior**
I want to get rid of that error to build the app.

**To Reproduce**

```
from kivy.app import Kivy
from kivy.uix.button import Button

class Test(App):
def build(self):
Return Button(text= "Happy birthday")

if __name__ == '__main__':
Test().run()
```

**Comment by srolf** [comment]
Maybe you would like to give it another try:

```
from kivy.app import App
from kivy.uix.button import Button

class Test(App):
    def build(self):
        return Button(text= "Happy birthday")

if __name__ == '__main__':
    root = Test()
    root.run()
```

**Comment by HoshiSoraa** [comment]
Thank you for your help

**Comment by HoshiSoraa** [comment]
Thank you for your help
