### ISSUE TITLE
kivy.core.window produces a window for every process

### ISSUE THREAD

**Issue by metabyte144** [kivy/kivy#8338]
**Software Versions**
* Python: 3.10
* OS: Windows 10
* Kivy: 2.2.1
* Kivy installation method: pip

**Describe the bug**
Kivy Window produces a kivy window for every process on the same position (move the first window to see it please)
When I run kivy in a process and included is:
    from kivy.core.window import Window
For every process will be a window popped up (one of them the root process).
If the window import line is removed, the code runs as expected.
If I produce more processes, more windows will pop up

**Expected behavior**
No extra windows. Only the kivy app I create.

**To Reproduce**
Run the code. Comment out the Window import and run again.

![kivy_process_bug](https://github.com/kivy/kivy/assets/78042651/b7666a2b-1add-4a67-b867-361a25dadcb6)

**Code and Logs and screenshots**
C:\p\git\DataHive\venv\venv_w310\Scripts\python.exe C:\p\git\DataHive\RnD\kivy\procmin.py 
[INFO   ] [Logger      ] Record log in C:\Users\gerald\.kivy\logs\kivy_23-07-31_96.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "C:\p\git\DataHive\venv\venv_w310\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\p\git\DataHive\venv\venv_w310\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 516.94'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 3060/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Logger      ] Record log in C:\Users\gerald\.kivy\logs\kivy_23-07-31_97.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "C:\p\git\DataHive\venv\venv_w310\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\p\git\DataHive\venv\venv_w310\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 516.94'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 3060/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available

from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button
from kivy.core.window import Window
from multiprocessing import Process

class DoClose(App):

    def build(self):
        self.window = GridLayout()
        self.window.cols = 1
        self.window.size_hint = (0.6, 0.7)
        self.window.pos_hint = {"center_x": 0.5, "center_y": 0.5}
        self.button = Button(text="SHUTDOWN", size_hint=(1, 0.4), bold=True, background_color='#00FFCE')
        self.button.bind(on_press=self.stop)
        self.window.add_widget(self.button)
        return self.window

def gogogo():
    DoClose().run()

if __name__ == "__main__":
    proc = Process(name="gcon", target=gogogo)
    proc.start()

**Comment by p0lygun** [comment]
https://github.com/kivy/kivy#support

**Comment by metabyte144** [comment]
> https://github.com/kivy/kivy#support
That's a bug not a support problem. If you add a import line and it produces strange behavior than its a bug. Sorry.

**Comment by RobertFlatt** [comment]
1) Opening an OS window when the Kivy Window class is imported is the expected behavior (even if it is strange to you) so it is not a bug.

2) This test case (not what you wrote, but I assume it is what you intended to illustrate) **recursively** creates a window, so we get two OS windows. Given 1) this behavior is reasonable to expect, but the documentation says "please don't do this" https://kivy.org/doc/stable/api-kivy.core.window.html#module-kivy.core.window.
```
def gogogo():
    DoClose().run()

if __name__ == "__main__":
     proc = Process(name="gcon", target=gogogo)
     proc.start()
```

3) I don't know your design goal, but implementation may be as simple as two files. Apologies if your case is more complex, but I hope you get the idea.

start_me.py
```
import subprocess
subprocess.Popen(["python", "do_close.py"])
```

do_close.py
```
from kivy.app import App
# content omitted for brevity
DoClose().run()
```

This forum is for development issues, please consider using the support groups for programming questions.

**Comment by metabyte144** [comment]
Thank you Robert for the explanation. 

While I DID see that we are not supposed to open more than one Window, processes are not linked to a Window in the documentation. That means kivy doesn't support multiprocessing. I work with several processes and only one of them is for GUI so my application is more complex than just using more files.
Apologies for posting here but usually I would classify that in a bug because it severely limits the usability of an otherwise fine GUI.

**Comment by HyTurtle** [comment]
You can move the import under the `if __name__ == "__main__":` guard, to prevent the process from running it.

**Comment by metabyte144** [comment]
> You can move the import under the `if __name__ == "__main__":` guard, to prevent the process from running it.

That would only work for the example.  I really like kivy but I still see importing Window popping it up as a bug.
That's a side effect that is made canon. In my book it is bad design, and it prevents every kivy application from doing processor heavy activities because it's now GIL locked to a single execution thread. The example is a minimal example for an already complex topic. Adding to it with a design like that shows that the design itself is multiprocessing agnostic and will most likely cause more problems later.

I don't do processes for fun (nobody does), I NEED them and they doing stuff like hashing whole file trees, opening several network connection (which may even fit in with asyncio), having background processes caring about other stuff and everything needs to run smoothly. Calculator apps with just a gui thread adding a few numbers are nice but none of my interests.

**Comment by RobertFlatt** [comment]
If you want help, ask in the user groups https://github.com/kivy/kivy#support
You may find it more productive to explain what you want, as well as what you tried that didn't work.

**Comment by metabyte144** [comment]
I've tried to shield the kivy import statements with a 
if __name__ == "process_name":
That still didn't work because the Window import still creates a window for the root process. 

Thank you Robert for the support group but I don't think it's productive to repeat me all over in the next group.
It would be more productive to check if it's possible to encapsulate the problematic code and patch my Kivy if so.

That design bug needs either be fixed or circumvented or another GUI chosen.
That may be a development forum but it's not a support problem, it's a design problem.
That's stuffing problematic behavior into a constructor and that is a textbook design flaw.
It is in C++, it is in Python, and it is in every other language supporting constructors.

Sorry for discussing bugs here but not sorry it IS A BUG or SERIOUS DESIGN FLAW in all of my books.
IF you start a window for every process of the program, the program is GIL locked and is lost for multiprocessing.

You can try to shove me somewhere else but the problem remains and it bothers me because it makes Kivy a toy environment and it is IMHO by far the best open-source approach to a modern GUI and I think Kivy doesn't deserve that.

Now counter that profoundly please instead of trying to shove me out.

**Comment by RobertFlatt** [comment]
I'm not trying to shove you out, I'm trying to point you to where you are more likely to find someone who has the experience you seek.

**Comment by metabyte144** [comment]
Sorry Robert, I didn't mean to sound rude. Thanks for the help :)

**Comment by ElliotGarbus** [comment]
This is not a bug, kivy and it's imports must all be under __name__ == " __main__",

**Comment by Android-for-Python** [comment]
Perhaps a typo, should be  `__name__ == "main"`

**Comment by ElliotGarbus** [comment]
Here is an example:

```python
from multiprocessing import Process
import time


def print_loop():
    for i in range(5):
        time.sleep(1)
        print(f'Hello from MP! {i}')
    print('Goodbye from mp')


def launch_process():
    p = Process(target=print_loop, name='short print loop')
    p.start()


if __name__ == '__main__':
    # load and run kivy from the main process only
    from kivy.app import App
    from kivy.uix.button import Button


    class HelloFromKivy(App):
        def build(self):
            b = Button(text='Hello from kivy', on_release=self.say_hello)
            return b

        def say_hello(self, *args):
            print('Hello from kivy')

        def on_start(self):
            launch_process()


    HelloFromKivy().run()
```

**Comment by akshayaurora** [comment]
Aren't you assuming every one would want just one kivy window per process?

If you don't, why not just import it once? Setup a env variable `MyGUI<id>Running` then and only then do the kivy imports?

myguiapp/__init__.py
```
import os
os.environ['MY_GUI_<UID>_RUNNING']
from kivy.app import App
from kivy.core.window. import Window
...
```

```
import os
import x,y,z


if os.environ.get('MY_GUI_<UID>_RUNNING', 'False'):
      import myguiapp
      myguiapp.MyGuiApp().run()
```

The important question is why are you trying to import Kivy's window in a process you do not want the window in?

Kivy is being regularly used with multiple processes, heck it even on mobiles is being used with services to offload heavy processing.

1. You can launch external process, use subprocess

**Comment by akshayaurora** [comment]
Maybe this issue raises the point on why we do not have proper documentation on how to do the above mentioned things in kivy. If we had this as part of advanced documentation then it would not lead to such confusion. 

We are definitely lacking on documentation on how to do these things.

**Comment by Android-for-Python** [comment]
> Aren't you assuming every one would want just one kivy window per process?

There is no choice, we are only allowed one  https://kivy.org/doc/stable/api-kivy.core.window.html#module-kivy.core.window

> We are definitely lacking on documentation on how to do these things.

I agree, I would say Kivy is missing a User's Guide.

**Comment by metabyte144** [comment]
Akshay, now we're talking. I will definitely try that and report the results.
That looks at least like a workaround - it's still a violation of basic OOP design principles thou..

#The important question is why are you trying to import Kivy's window in a process you do not want the window in?
I don't. The GUI is in a sub-process. When import there (with a __name__ check to the module name of course), Kivy still generates a dead window for the root process that doesn't have ANY Kivy imports. That's actually the basic problem that kivy generates a Window for EVERY process (root + all children). If I encapsulate it, it is better, because not all children will produce a window but the root process still does even if it has no clue about kivy.

What I'm trying to do is illustrated in the code above. That's the minimal code to illustrated the problem. I could post a  250-lines full frame test but I think that will be a bit overboard here..  Basically it is three different processes spawned (in the style of above sample) which fire up the GUI over a message to a _Queue_ which is running in one of the sub-processes. 

I've already thought about building a C++ framework and starting the interpreter from there, effectively isolating the GUI process from the rest of the application. Will do that probably anyway but I need to do the IPC over sockets then which need some extra care to get right (took me already some time and learning curve to get the Python multiprocessing right)..

What do you mean by I haven't given a minimal sample? I know the code at the start of the thread is mangled by the GUI of that Webapp here, (I probably didn't get THAT one right) but it's definitely up there and you can copy, paste and run it (AND it's in the picture too). I just made it a MINIMAL sample and not the full 250 line experimental code...

**Comment by metabyte144** [comment]
About Documentation: I agree

I even saw the "only one window" upfront but I didn't have any connection to processes or that the window would be opened implicitly by a import, which is a serious undocumented side effect where I cannot even see the benefits (which may not mean much thou..)

**Comment by akshayaurora** [comment]
I am opening a new issue,  about adding documentation for hoot use multiprocessing https://github.com/kivy/kivy/issues/8339

`Be precise, in what you ask for`. You will get more traction on forum  for how to do multiprocessing with kivy. Or you could wait for the documentation to be updated on this.

**Comment by akshayaurora** [comment]
> |I even saw the "only one window" upfront but I didn't have any connection to processes or that the window would be opened implicitly by a import, which is a serious undocumented side effect where I cannot even see the benefits (which may not mean much thou..)

@metabyte144 ok then open a separate issue just about the `import causing window to open` that can be discussed as a separate issue from multiprocessing.

Seems you have multiple concerns, let's break them down to atomic issues that are self contained.

1) Documentation for heavy processing with kivy(multiprocessing would be part of it.) I already opened a issue for it .
2) A import `from kivy.core.window import Window` should ideally not open a window. even in a single process app... Worth further discussion please open a separate issue.
