### ISSUE TITLE
to_window() reports wrong coordinates for widget located exactly at origin of RelativeLayout

### ISSUE THREAD

**Issue by banfelder** [kivy/kivy#8341]
**Software Versions**
* Python: 3.11.4
* OS: Mac OS Ventura 13.4
* Kivy: v2.2.1
* Kivy installation method: pip install -r requirement.txt     ("kivy==2.2.1" therein)

**Describe the bug**
When a button widget is located *exactly* at the origin of a `RelativeLayout`, its `to_window()` method does not transform to window coordinates properly.

**To Reproduce**

Run code below.

**Expected behavior**

The left-most button should be reporting `self.to_window(*self.pos)` equal to (100,50). Instead it reports (0,0). 

**Code and Logs and screenshots**

```python
#### test.py

#!/usr/bin/env python3.11

from kivy.app import App
from kivy.uix.relativelayout import RelativeLayout


class TestApp(App):
    def build(self):
        return RelativeLayout()


if __name__ == "__main__":
    TestApp().run()
```

```
### test.kv

<Button>:
    text: f"{self.pos=}\n{self.to_window(*self.pos)=}"
    size_hint: None, None
    size: 200, 100

<FloatLayout>:
    pos: 100, 50
    Button:
        pos_hint: {'x': 0.0, 'y': 0.0}
    Button:
        pos_hint: {'x': 0.5, 'y': 0.0}
```

```
[INFO   ] [Logger      ] Record log in /Users/jason/.kivy/logs/kivy_23-08-05_45.txt
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "/Users/jason/opt/miniconda3/envs/learn_kivy/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]
[INFO   ] [Python      ] Interpreter at "/Users/jason/opt/miniconda3/envs/learn_kivy/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Metal - 83.1'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple M1'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
```

**Additional context**

Perturbing the location of the button even slightly `pos_hint: {'x': 0.001, 'y': 0.0}` yields a correct result. Maybe due to some truthy-ness test that all zero coordinates does not pass?

**Comment by pythonic64** [comment]
@banfelder Position of the first button is never changed from its initial value of [0, 0] so it won't trigger text update unlike the second button whose position gets updated from pos_hint. This is the normal/expected behavior of `RelativeLayout`.

You can add `on_release: self.text = f"{self.pos=}\n{self.to_window(*self.pos)=}"` to `<Button>` and click on the first button which will update the text and show the correct values.
