### ISSUE TITLE
Kivy packaging for OS X error in Example create app from scratch

### ISSUE THREAD

**Issue by Dan-Essin** [kivy/kivy#8350]
**Software Versions**
* Python: 11.3.4
* OS:mac 12.6.8
* Kivy: 2.2.1
* Kivy installation method: pip

**Describe the bug**
This line in the example can't possibly work:
git clone https://github.com/user/myapp.git

1 - It's impossible to log in to user (it's unknown of course. and so is the password.
2 - It's not clear whether this step is mandatory. If it's not it should say so. If it is, then more detail is needed to explain how to put something into GitHub that could be downloaded and that would satisfy the next steps

**Expected behavior**
I expected that a "from scratch" example would work since I'm not a mind reader and could never figure this out without first having a working example.

**To Reproduce**
just try to follow the steps. It will fail for anyone that tries:
git clone https://github.com/user/myapp.git

They will also get:
fatal: Authentication failed for 'https://github.com/user/myapp.git/'

It also says:
remote: Support for password authentication was removed on August 13, 2021.

But of course since "user" does not exist on GitHub, nothing could possible work

**Additional context**
Perhaps same real sample app in some real user's folder could be supplied so that it could be downloaded.

**Comment by Julian-O** [comment]
It may help identifying the problem if you explain where you found this line.

Maybe others know exactly what you are referring to, but I couldn't find any document or example code in Kivy or Buildozer that would tell a user to run that command.
