### ISSUE TITLE
Encoding problem on 'utf-8' kv file on Raspiberry

### ISSUE THREAD

**Issue by CallaDai** [kivy/kivy#8356]
**Software Versions**
* Python: 3.9
* OS: Raspiberry
* Kivy: 1.0
* Kivy installation method:

**Describe the bug**
I have installed the WenQuanYi Micro Hei data font. And when I used this font in my label, it worked. Here are some code: 

MDLabel:
    size_hint_x: 0.5
    text: "结果（条）:"
    font_name: 'WenQuanYi Micro Hei'

But it didn't support the MDTopAppBar, why?

MDTopAppBar:
     title: "Preview"
     font_name: 'WenQuanYi Micro Hei'
     right_action_items: [["home",  lambda x: root.SwitchScreen('HomeScreen'),"返回首页"],["power", lambda x: app.on_custom_stop(),"退出"]]
     md_bg_color: app.theme_cls.primary_dark

Another question, I have added the following code at the top of my kivy app.

  \# -*- coding: utf-8 -*-
  from kivy.core.text import LabelBase
LabelBase.register(name='WenQuanYi Micro Hei', fn_regular='/usr/share/fonts/truetype/wqy/wqy-microhei.ttc')

Or put this code to the main function. But no matter which way, it doesn't work.
And encoded it to UTF-8 before I run this kivy app, the program went to the following step, it still show me the star words. 
Like' ****Loading model...' Why?

def start_process_preprocessedImage(self):
     self.open_dialog_loading("加载模型中Loading model ...")
     self.stop_event = Event()

**Expected behavior**
I want the kivy app shows me the excepted Chinese character, no ** words.

**Comment by kuzeyron** [comment]
This is a question for the KivyMD team. KivyMD is built on Kivy.

**Comment by misl6** [comment]
Thank you @kuzeyron for triaging the issue!
