### ISSUE TITLE
UrlRequest  should implement CRUD

### ISSUE THREAD

**Issue by Fr3d-P** [kivy/kivy#8366]
**Is your feature request related to a problem? Please describe.**
URLRequest are simple and efficient with Kivy. One can user other library for requests and async, but they're complicated with a long learning curve

**Describe the solution you'd like**
I'd like to be able to send HEAD, PATCH, PUT  and DELETE in addition to GET and POST

**Describe alternatives you've considered**
Using httpx with trio, but it's complex, and block kivy's UI, I can't refresh it

**Additional context**
Nothing more

**Comment by mcroni** [comment]
Kivy is a GUI library, python's defactor http library (requests) doesn't have any steep learning curve, it is the most preferred and easiest way to make calls with http.

**Comment by Cheaterman** [comment]
> they're complicated with a long learning curve

```py
import random

import httpx
import trio

from kivy.app import App
from kivy.lang import Builder
from kivy.properties import StringProperty

KV = '''
BoxLayout:
    orientation: 'vertical'

    Label:
        text: app.product_name or 'Click below to load a product'

    Button:
        text: 'Press me!'
        on_press: app.load_product()
'''


class Test(App):
    product_name = StringProperty()

    async def async_run(self, *args):
        async with trio.open_nursery() as nursery:
            self.nursery = nursery
            await super().async_run(*args)
            nursery.cancel_scope.cancel()

    def build(self):
        return Builder.load_string(KV)

    def load_product(self):
        self.nursery.start_soon(self._load_product)

    async def _load_product(self):
        async with httpx.AsyncClient() as client:
            products = (
                await client.get('https://dummyjson.com/products')
            ).json()['products']

        product = random.choice(products)
        self.product_name = product['title']


trio.run(Test().async_run, 'trio')
```

**Comment by entaangle** [comment]
> **Describe the solution you'd like** I'd like to be able to send HEAD, PATCH, PUT and DELETE in addition to GET and POST

You can use the "method" argument to specify the HTTP method that you'd like to use, e.g.:
`UrlRequest(url, request_callback, method='DELETE')`

Internally kivy is able to optionally use python 'requests' (I think this requires kivy version >2.2.0).  This is not required to use the "method" argument AFAIK but might be useful, e.g. for authentication with the "auth" argument.  At the top of your main.py before instantiating the App:

```
from kivy.config import Config
Config.set('network', 'implementation', 'requests')
```

**Comment by Fr3d-P** [comment]
@Cheaterman : Have you considered adding this code to the documentation?
For my need (and with my knowledge), this exemple helped me more than those in https://kivy.org/doc/stable/api-kivy.app.html and examples/async.
Thanks

**Comment by Fr3d-P** [comment]
@entaangle you're right!
Different methods are usable for UrlRequest.
When I red the doc:
   method: str, defaults to ‘GET’ (or ‘POST’ if body is specified)
I understood that GET and POST were the only values usable for URLRequest

I even searched in github urlrequest.py , for a hint of which values where usable, but didn't try to test directly

 :-(

**Comment by Fr3d-P** [comment]
URLRequest can do more than Get and Post

**Comment by Fr3d-P** [comment]
URLRequest can do more than Get and Post

**Comment by NomadDemon** [comment]
we have 2 implementations of networking

check UrlRequestRequests and UrlRequestUrllib
you can of course commit some changes to support "patch, delete, head" etc

let me know when you are ready for review :)
[iam familiar with networking module well in kivy, UrlRequestRequests is my implementation]

i can also add this methods, but not this month nor next. - maybe november. iam kinda busy with current projects now
you can message me on discord if you want to [go to official kivy channel]
