### ISSUE TITLE
Kivy iOS - mediapipe module

### ISSUE THREAD

**Issue by aperez-hub** [kivy/kivy#8378]
**Software Versions**
* Python: 3.10/3.11
* OS: MacOS Venture 13.3.1
* Kivy installation method: followed exactly this -> https://kivy.org/doc/stable/guide/packaging-ios.html

**Describe the bug**
I develop python app using kivy and trying to build it as iOS. However, there is always this error when running:
ModuleNotFoundError: No module named 'mediapipe'

Is Mediapipe not yet supported for kivy ios? Thank you!

**Comment by misl6** [comment]
`mediapipe` is not a plain-python library, and you'll need a recipe to build it.
Feel free to open a feature-request on `kivy/kivy-ios`
