### ISSUE TITLE
Line does not render correctly with `KIVY_WINDOW=x11` when opacity is less than 1.0

### ISSUE THREAD

**Issue by p32blo** [kivy/kivy#8379]
**Software Versions**
* Python: 3.8.10
* OS: Ubuntu 20.04
* Kivy: v2.2.1
* Kivy installation method: pipenv

**Describe the bug**
When the opacity of a line is set to < 1.0 the line is rendered incorrectly

**Expected behavior**
The Line should be drawn as specified (an ellipse in this following example)

**To Reproduce**
1. Test the example with `python test.py`
2. This will show you the correct rendering
3. Test the example with `KIVY_WINDOW=x11 python test.py`
4. This will show you the bug

**Code and Logs and screenshots**
```python
# test.py

from kivy.app import App
from kivy.lang import Builder

kv = """
Widget:
    canvas:
        Color:
            rgba: 0, 1, 0, 0.5
        Line:
            width: 10
            ellipse: self.x , self.y , self.width , self.height 
"""

class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

![image](https://github.com/kivy/kivy/assets/6619062/b458c2ce-c700-4383-bca3-a42f432915dd) ![image](https://github.com/kivy/kivy/assets/6619062/47fdff4e-eee1-47b7-a9d2-fa2fc016704a)
sdl2 vs x11

I've also tried the official [canvas lines example](https://kivy.org/doc/stable/examples/gen__canvas__lines__py.html) and got the same results:

![image](https://github.com/kivy/kivy/assets/6619062/98b09920-5e79-4704-b988-a312b6a3e8a5)
working with opacity 1.0 on both sdl2 and x11

![image](https://github.com/kivy/kivy/assets/6619062/1b890eea-eb4e-4b08-91c4-2c018e118ca2)
when setting any opacity the sdl2 continues to work but the x11 fails

**Additional context**
It looks like a stencil is activated when the opacity is lower that 1 [here](https://github.com/kivy/kivy/blob/ca1b918c656f23e401707388f25f4a63d9b8ae7d/kivy/graphics/vertex_instructions_line.pxi#L213C4-L213C4). 
I believe all  stencil operations are misbehaving after some test on a rapberry pi as well.

**Comment by misl6** [comment]
Fixed via #8383
