### ISSUE TITLE
Markup of parts of a word splits the word

### ISSUE THREAD

**Issue by alexg93333** [kivy/kivy#8380]
If I markup PARTS of a word for example:  "ERD"+f'[color=ff3333]{ "IN" }[/color]'+"GER" , kivy is treating it as 3 separate words which creates a problem for newline breakdowns. Without markup, the whole word in jumping to the next line if there isn't enough space, but with any tags [b] or [s] or [color] ect it is breaking down parts of the word into the next line.  I made a short video to show what I mean:
https://gyazo.com/1199516fec383bc0681b2d054eb6b63e

How can I change/override this behavior?

**Comment by p0lygun** [comment]
can confirm to be a bug, 
```py
if True:
    import os
    os.environ['SDL_VIDEO_X11_WMCLASS'] = 'float-override'

from kivy.lang import Builder
from kivy.app import App

kv = '''
FloatLayout:
    Label:
        text: "test "*10 + "H[color=ff0000]ello[/color]world"
        markup: True
        
        pos_hint: {'center_x': .5, 'center_y': .5}       
        size_hint_y: None
        text_size: self.width, None
        height: self.texture_size[1]
'''


class PlaygroundApp(App):
    def build(self):
        return Builder.load_string(kv)


if __name__ == '__main__':
    PlaygroundApp().run()
```
![image](https://github.com/kivy/kivy/assets/22869882/687a8227-a925-489d-a204-5e0c56d1a44e)

![image](https://github.com/kivy/kivy/assets/22869882/0d239b30-4a63-42b3-9d41-74e856c9313a)

**Comment by p0lygun** [comment]
@Julian-O this is also a dup of #7323, upto you if u want to keep this open or that one

**Comment by p0lygun** [comment]
well not exactly the same but i believe it should work with the same fix
