### ISSUE TITLE
Latest kivy does not install on Python 3.12 for Windows

### ISSUE THREAD

**Issue by Code4SAFrankie** [kivy/kivy#8391]
**Software Versions**
* Python: Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
* OS: Windows 10
* Kivy: 2.2.1
* Kivy installation method: python -m pip install "kivy[base]" kivy_examples

**Describe the bug**
Fails on  ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.3 (from versions: none)
ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.3.3

**Expected behavior**
Kivy should be installed on Python 3.12

**To Reproduce**
.\python.exe -m pip install "kivy[base]" kivy_examples

**Code and Logs and screenshots**
```
C:\Program Files\Python312>.\python.exe -m pip install "kivy[base]" kivy_examples
Defaulting to user installation because normal site-packages is not writeable
Collecting kivy[base]
  Using cached Kivy-2.2.1.tar.gz (24.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Collecting setuptools
        Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting packaging
        Obtaining dependency information for packaging from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
        Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
      Collecting cython!=0.27,!=0.27.2,<=0.29.33,>=0.24
        Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
      ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.3 (from versions: none)
      ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.3.3
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by misl6** [comment]
Python **3.12** is not supported yet. We will have an ETA in a couple of days.

Meanwhile, please use Python 3.11 😀❤️

**Comment by RicardoSaikali** [comment]
I am on python3.11 and I am having the same problem. Is there a way to not install the gstreamer dep since it is optional?

**Comment by Code4SAFrankie** [comment]
Where would one go to see the ETA?

**Comment by p0lygun** [comment]
i belive #8393 is the best place

**Comment by misl6** [comment]
Unfortunately, there's no ETA, as we're waiting for a dependency to include a bugfix. (in order to not manage 2 releases in a week).

They expect to release an update before the end of the month, but meanwhile, please use Python 3.11 😅

**Comment by PaisleyPython** [comment]
Hi, is there an update?

**Comment by GreenyAUT** [comment]
Any news?

**Comment by cwiegert** [comment]
Collecting kivy_deps.gstreamer_dev~=0.3.3
        Using cached kivy_deps.gstreamer_dev-0.3.3-cp312-cp312-win_amd64.whl.metadata (215 bytes)
      ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2_dev~=0.6.0 (from versions: 0.7.0)
      ERROR: No matching distribution found for kivy_deps.sdl2_dev~=0.6.0
      [end of output]

**Comment by cwiegert** [comment]
any clues?

**Comment by Julian-O** [comment]
@cwiegert Please take this to the support channels - it is different issue.

**Comment by Palakeeti** [comment]
![Kivy_on_Python3 12](https://github.com/kivy/kivy/assets/39407025/97105ae8-e75e-4546-b9cb-4683a7ebc17f)

Is Kivy coming up with any support for Python V3.12??

Looks there hasn't been an update in the recent past. Is going back to the earlier versions of Python is the only option??

**Comment by Julian-O** [comment]
Yes, support is coming, please be patient.  Sticking with Python 3.11 in the mean time isn't a huge imposition.

**Comment by devpoisons** [comment]
> Yes, support is coming, please be patient. Sticking with Python 3.11 in the mean time isn't a huge imposition.

ok no problem
we will be waiting. Keep up the good work 😊😜

**Comment by Julian-O** [comment]
Fixed in 2.3.0rc1. We are currently up to 2.3.0rc3.

**Comment by devpoisons** [comment]
Yes thanks, I tried installing it yesterday but errors but when it is fixed send an email pls.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Julian-O** [comment]
@devpoisons: If you found a bug in the new release, please report it or ask for assistance in the support channels.

No, no-one is going to personally email you for each release. Consider using PyPI RSS feeds or libraries.io.

**Comment by ruegi** [comment]
Just tried to install kivy 2.3 on python 3.12.1.
There was an error with kivy-deps-glew, so I couldnt install.

`poetry add kivy
Using version ^2.3.0 for kivy

Updating dependencies
Resolving dependencies... (0.6s)

Package operations: 2 installs, 0 updates, 0 removals

  • Installing kivy-deps-glew (0.3.1): Failed

  RuntimeError

  Unable to find installation candidates for kivy-deps-glew (0.3.1)

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\installation\chooser.py:73 in choose_for
       69│
       70│             links.append(link)
       71│
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│

Cannot install kivy-deps-glew.`
 
When will it be solved?
Thanks
rg

**Comment by ElliotGarbus** [comment]
FWIW: Using the install directions and using pip worked for me.  https://kivy.org/doc/stable/gettingstarted/installation.html#install-pip

**Comment by ruegi** [comment]
Hi,
indeed, intalling kivy via pip did the trick.
So it must have been a fault of poetry.
Additionally I had to update my poetry project file 'pyproject.toml' by hand and it's ok.
Thanks
rg
