### ISSUE TITLE
kivy video crash on android app

### ISSUE THREAD

**Issue by cagsurgunu** [kivy/kivy#8400]
**Software Versions**
* Python:3.10
* OS:Android
* Kivy:2.1.1
* Kivy installation method:pip

i use kivy video to get https hls stream. My codes work very well on windows but i compile them to apk the app crashes. i get this output from buildozer debug:

10-10 14:07:11.951 11713 12243 I python  : Android kivy bootstrap done. __name__ is __main__
10-10 14:07:11.951 11713 12243 I python  : AND: Ran string
10-10 14:07:11.951 11713 12243 I python  : Run user program, change dir and execute entrypoint
10-10 14:07:12.126 11713 12243 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 27)
10-10 14:07:12.126 11713 12243 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
10-10 14:07:12.126 11713 12243 I python  : [DEBUG  ] [Config      ] Upgrading from 0 to 1
10-10 14:07:12.132 11713 12243 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.ohmpeg.ohm_peg/files/app/.kivy/logs/kivy_23-10-10_0.txt
10-10 14:07:12.132 11713 12243 I python  : [INFO   ] [Kivy        ] v2.2.1
10-10 14:07:12.132 11713 12243 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.ohmpeg.ohm_peg/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
10-10 14:07:12.132 11713 12243 I python  : [INFO   ] [Python      ] v3.10.10 (main, Oct 10 2023, 11:41:34) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0
10-10 14:07:12.133 11713 12243 I python  : [INFO   ] [Python      ] Interpreter at ""
10-10 14:07:12.133 11713 12243 I python  : [INFO   ] [Logger      ] Purge log fired. Processing...
10-10 14:07:12.133 11713 12243 I python  : [INFO   ] [Logger      ] Purge finished!
10-10 14:07:12.139 11713 12243 I python  : [INFO   ] [Factory     ] 190 symbols loaded
10-10 14:07:13.519 11713 12243 I python  : [INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
10-10 14:07:13.520 11713 12243 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
10-10 14:07:13.548 11713 12243 I python  : [INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-10-09 (installed at "/data/user/0/org.ohmpeg.ohm_peg/files/app/_python_bundle/site-packages/kivymd/__init__.pyc")
10-10 14:07:13.555 11713 12243 I python  : [INFO   ] [Text        ] Provider: sdl2
10-10 14:07:13.585 11713 12243 I python  : [INFO   ] [Window      ] Provider: sdl2
10-10 14:07:13.701 11713 12243 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
10-10 14:07:13.703 11713 12243 I python  : [INFO   ] [GL          ] Backend used <sdl2>
10-10 14:07:13.703 11713 12243 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 v1.r18p0-01rel0.caae7eec9919d9090a8a7e777d44918f'>
10-10 14:07:13.704 11713 12243 I python  : [INFO   ] [GL          ] OpenGL vendor <b'ARM'>
10-10 14:07:13.704 11713 12243 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Mali-G51'>
10-10 14:07:13.704 11713 12243 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
10-10 14:07:13.705 11713 12243 I python  : [INFO   ] [GL          ] Texture max size <8192>
10-10 14:07:13.705 11713 12243 I python  : [INFO   ] [GL          ] Texture max units <16>
10-10 14:07:13.761 11713 12243 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
10-10 14:07:13.763 11713 12243 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
10-10 14:07:13.958 11713 12243 I python  : [INFO   ] [VideoFFPy   ] Using ffpyplayer 4.3.2
10-10 14:07:13.959 11713 12243 I python  : [INFO   ] [Video       ] Provider: ffpyplayer(['video_ffmpeg'] ignored)
10-10 14:07:14.022 11713 12243 I python  : [WARNING] Deprecated property "<BooleanProperty name=keep_ratio>" of object "<__main__.CustomVideo object at 0xbe032568>" was accessed, it will be removed in a future version
10-10 14:07:14.022 11713 12243 I python  : [WARNING] Deprecated property "<BooleanProperty name=allow_stretch>" of object "<__main__.CustomVideo object at 0xbe032568>" was accessed, it will be removed in a future version
10-10 14:07:14.041 11713 12243 I python  : [ERROR  ] [Image       ] Not found <https://tv-trt2.medya.trt.com.tr/master_720.m3u8>
10-10 14:07:14.061 11713 12243 I python  : [WARNING] [Base        ] Unknown <android> provider
10-10 14:07:14.062 11713 12243 I python  : [INFO   ] [Base        ] Start application main loop
10-10 14:07:14.134 11713 12243 I python  : [INFO   ] [GL          ] NPOT texture support is available

**Comment by p0lygun** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our [support channels](https://github.com/kivy/kivy/blob/master/README.md#support) to get help with the project.
 
If you're having trouble installing Kivy, make sure to check out the installation docs for [Windows](https://kivy.org/docs/installation/installation-windows.html), [Linux](https://kivy.org/docs/installation/installation-linux.html) and [macOS](https://kivy.org/docs/installation/installation-osx.html).
 
Let us know if this comment was made in error, and we'll be happy to reopen the issue.

**Comment by yeyuchen198** [comment]
I had the same problem

**Comment by yeyuchen198** [comment]
import os
from kivy.utils import platform
if platform == "android":
    os.environ["SDL_AUDIODRIVER"] = "android"
