### ISSUE TITLE
Support mail address is broken

### ISSUE THREAD

**Issue by misl6** [kivy/kivy#8409]
### Description

The [documentation](https://github.com/kivy/buildozer#support) claims:

> If you need assistance, you can ask for help on our mailing list:
>
> User Group : https://groups.google.com/group/kivy-users
> Email : [kivy-users@googlegroups.com](mailto:kivy-users@googlegroups.com)

However, you can't directly email that address (perhaps until you have joined the group). It gives an error by reply email (mentioned in this [comment](https://github.com/kivy/buildozer/issues/1714#issuecomment-1756803743) and reproduced by me with a throwaway account.

The documentation should not mention the email address, and stick to the URL.

A PR (which also does a refactor) has been done on `buildozer` repo:
https://github.com/kivy/buildozer/pull/1722#discussion_r1362594418

**Comment by seharbat00l** [comment]
Hi!

**Comment by p0lygun** [comment]
this can be closed @Julian-O

**Comment by misl6** [comment]
Fixed via #8411
