### ISSUE TITLE
[Question] PySDL2 

### ISSUE THREAD

**Issue by jhay06** [kivy/kivy#8410]
hi i know kivy has own sdl2 so using pysdl2 should be working ,
but importing pysdl2 is not working

**Comment by p0lygun** [comment]
what and how it is not working? please follow the specified template

**Comment by baseplate-admin** [comment]
>  but importing pysdl2 is not working

That's because kivy is not built using `pysdl2`, it ships it's own `sdl` ( downloaded from `libsdl` )

**Comment by jhay06** [comment]
> > but importing pysdl2 is not working
> 
> That's because kivy is not built using `pysdl2`, it ships it's own `sdl` ( downloaded from `libsdl` )

hi , is there a way we can call kivy own sdl ? in python ?
