### ISSUE TITLE
Can't install Kivy on Mingw64 python 3.11.6

### ISSUE THREAD

**Issue by RicardoSaikali** [kivy/kivy#8412]
**Software Versions**
* Python: mingw-w64-x86_64-python 3.11.6
* OS: mingw64 on windows 11
* Kivy: 2.2.1
* Kivy installation method:
pip install kivy

**Describe the bug**
I am looking to make a small test app that uses python, pygobject, kivy, and gstreamer on windows 11.

Because of pygobject, I have to use a mingw64 terminal since it does not work directly on windows 11 or with a python version greater than 3.4 (using a [sourceforge installer](https://sourceforge.net/projects/pygobjectwin32/)).

In mingw64, I've been facing the issue of not being able to install kivy due to `No matching distribution found for kivy_deps.gstreamer_dev~=0.3.3`

I've looked at this [thread](https://github.com/kivy/kivy/issues/8042) and tried the proposed solutions of using "the latest cutting edge Nightly wheels" with:

`python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/`

`python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/`

However this gave the same error.

I also tried to download version 3.10 of mingw-w64-x86_64-python, with pacman and a zst folder, installed pip with `python -m ensurepip` and was still getting the same error with Kivy. I don't like this route because I will also [have to build all my python packages](https://github.com/msys2/MINGW-packages/discussions/18881#:%7E:text=If%20you%20want%20you%20can%20rebuild%20every%20python%20packages) due to the nature of mingw64's packages with pacman.

Essentially, I can't intall Kivy on wingw64. 

**Expected behavior**
Kivy should install as normal.

**To Reproduce**
Install mysys2 as per this [link](https://www.msys2.org/).

run mingw64 (not msys terminal)

In mingw64:

    pacman -Syu mingw-w64-x86_64-gtk4 mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-gobject mingw-w64-x86_64-
    python3-pip mingw-w64-x86_64-python3-setuptools mingw-w64-x86_64-gstreamer mingw-w64-x86_64-gst-devtools mingw-w64-
    x86_64-gst-plugins-{base,good,bad,ugly}
    
    python -m pip install setuptools
    
    python -m pip install wheel
    
    python -m pip install kivy

**Code and Logs and screenshots**

```
$ pip install kivy
Collecting kivy
  Using cached Kivy-2.2.1.tar.gz (24.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Collecting setuptools
        Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting packaging
        Obtaining dependency information for packaging from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
        Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
      Collecting cython!=0.27,!=0.27.2,<=0.29.33,>=0.24
        Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
      ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.3 (from versions: none)
      ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.3.3
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by matham** [comment]
To use kivy on mingw you need to [install kivy from source](https://kivy.org/doc/stable/gettingstarted/installation.html#from-source). You cannot use any of the pre-compiled wheels (i.e. you have to use the `--no-binary kivy` pip flag). I'm not sure if it'll work out of the box for kivy on mingw but the process is basically the same as for a linux type install so you just need to figure out how to adapt installing the deps for it to work.

**Comment by philomelus** [comment]
Not sure why this is a support request.  I still cannot install kivy with pip under mingw64 or msys2 due to the original issue.  There are no instructions in the installation docs for msys2/mingw64 on windows, so where should I put a "support" request?  Should I just assume this is an unsupported platform?
