### ISSUE TITLE
pip wheel for new RPi OS release - based on Debian 12 Bookworm

### ISSUE THREAD

**Issue by JacekJagosz** [kivy/kivy#8416]
**Is your feature request related to a problem? Please describe.**
Right now [wheels for RPi are built](https://github.com/kivy/kivy/actions/workflows/rpi_wheels.yml) for python 3.7 - Buster and python 3.9 - Bullseye, but there isn't one for Bookworm. 

**Describe the solution you'd like**
I know the new OS release is well... quite new, but could one also get created for it? Balena-io images for it [seem to be available](https://github.com/balena-io-library/base-images/tree/master/balena-base-images/device-base/raspberrypi3/debian/bookworm).
**Describe alternatives you've considered**
Building kivy wheel takes a really long time on the pi, especially older ones, not the best experience.

**Comment by misl6** [comment]
@JacekJagosz wheels for bookworm has been added.
You can already download the produced artifacts from here: https://github.com/kivy/kivy/actions/runs/6755812607

After the nightly build (it's performed at 2:00 AM CET) , you will also find the produced artifacts here: https://kivy.org/downloads/ci/raspberrypi/kivy/
