### ISSUE TITLE
Navigation drawer MDNavigationDrawerItem cursor pointing highlight at wrong position 

### ISSUE THREAD

**Issue by anlnsai** [kivy/kivy#8417]
**Software Versions**
Environment:
Windows 10 22H2 Build 19045
Python 3.10.5
Kivy 2.2.1
KivyMD 1.2.0.dev0 from master branch

**Describe the bug**
Navigation drawer MDNavigationDrawerItem cursor pointing highlight at wrong position .

**Expected behavior**
cursor position should be correct

**To Reproduce**
check the attachment video

**Additional context**
[Please check the discussion here.](https://github.com/kivymd/KivyMD/issues/1549)

https://github.com/kivy/kivy/assets/16678329/4c7076fe-1bf7-4f1b-9c33-bd0fc0299f3b

**Comment by p0lygun** [comment]
Hi, this issue tracker is for kivy, for KivyMD related issues please open an issue on its issue tracker

**Comment by p0lygun** [comment]
@anlnsai tested on windows, cant reproduce results.


https://github.com/kivy/kivy/assets/22869882/f7d08e28-b1aa-4693-8679-9e65635a31b9

**Comment by anlnsai** [comment]
Hi @p0lygun , 
Thanks for the update. 
Actually it is working with my monitor very well (1920 X 1080).
But actual problem with my laptop screen which has resolution of 1920 X **1200** WUXGA.

**Comment by acgc99** [comment]
Same issue here. I just copied KivyMD docs [example](https://kivymd.readthedocs.io/en/1.1.1/components/navigationdrawer/index.html#standard-content-for-the-navigation-bar)

Windows 11. Screen 1920 x 1080

https://github.com/kivy/kivy/assets/96864661/f57c01ac-3438-4939-9d39-47f8006ddb6d

**Comment by ElliotGarbus** [comment]
It appears the root issue is that Window.mouse_pos is reporting a different value than touch.
Taking a look at kivymd, mouse_pos is used to implement the hover behavior.

Given this simple sample code:
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window
from kivy.uix.anchorlayout import AnchorLayout
from kivy.properties import ListProperty

kv = """
<InfoLayout>:
    BoxLayout:
        size_hint: None, None
        size: 200, 200
        orientation: 'vertical'
        Label: 
            text: f'Window.mouse_pos: {root.mouse_pos}'
        Label:
            text: f'touch.pos: {root.touch_pos}'

InfoLayout:    
"""


class InfoLayout(AnchorLayout):
    mouse_pos = ListProperty()
    touch_pos = ListProperty()

    def on_touch_down(self, touch):
        print(f'{touch.pos=} {Window.mouse_pos=}')
        self.mouse_pos = Window.mouse_pos
        self.touch_pos = touch.pos
        return(super().on_touch_down(touch))


class MousePosErrorApp(App):
    def build(self):
        print(f'{Window.size=}')
        return Builder.load_string(kv)


MousePosErrorApp().run()
```
My Windows11 laptop outputs the following:
Window.size=(1000, 750)
and clicking in the upper right corner of the Window:
touch.pos=(996.4993742177722, 745.2487479131887) Window.mouse_pos=(797.0, 596.0)

Notice the significant difference in reported pos for mouse_pos and touch.  Touch is correct, and mouse_pos is significantly smaller.  I will look into this more later today.

**Comment by ElliotGarbus** [comment]
Some additional testing.  This is only an issue on Windows when the scale in display settings is not set to 100%.  This causes a change in the density setting.  More to follow.

**Comment by ElliotGarbus** [comment]
@matham 
Problem summary: Window.mouse_pos is incorrect if the scale factor in Windows is not 100%.

You were in this code not that long ago and it appears linked to SDL behavior, I want to run this by you for guidance prior to completing a PR.  The code below is from core/window/window_sdl2.py  In the case where the platform == 'win', I have added the line to set self._density under Windows.   This updates the value of _density and results in the correct behavior for my simple test case.

```python
    def _update_density_and_dpi(self):
        if platform == 'win':
            from ctypes import windll
            self._density = 1.
            try:
                hwnd = windll.user32.GetActiveWindow()
                self.dpi = float(windll.user32.GetDpiForWindow(hwnd))
                self._density = self.dpi / 96  # Code added to update self._density under Windows
            except AttributeError:
                pass
        else:
            self._density = self._win._get_gl_size()[0] / self._size[0]
            if self._is_desktop:
                self.dpi = self._density * 96.
```
