### ISSUE TITLE
auto click

### ISSUE THREAD

**Issue by iomari** [kivy/kivy#8418]
Greetings,
I have a button "button.bind(on_press=self.show_popup)". How can I make it click automatically without pressing the mouse?

**Comment by p0lygun** [comment]
There are various ways to do so, but the easiest way i can think of is using the `dispatch` method of an object
[Event Dispatcher](https://kivy.org/doc/stable/api-kivy.event.html#module-kivy.event), 

also for support pls use one of the following https://github.com/kivy/kivy?tab=readme-ov-file#support
