### ISSUE TITLE
ffpyplayer stop and looping video

### ISSUE THREAD

**Issue by IVAN-QX** [kivy/kivy#8421]
**Software Versions**
* Python: 3.11.3
* OS: windows
* Kivy: 2.2.1
* Kivy installation method: pip install kivy

```
from kivy.app import App
from kivy.uix.video import Video
from kivy.uix.relativelayout import RelativeLayout

class W(RelativeLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.v = Video(source='video.mp4', state='play')
        self.add_widget(self.v)

class X(App):
    def build(self):
        return W()

X().run()
```

this is an example for the first issue
just when the video reach the end, its usually freeze then stop
we can notice that by many ways, one of this is testing some audio playing with this video:

```
from kivy.app import App
from kivy.uix.video import Video
from kivy.core.audio import SoundLoader
from kivy.uix.relativelayout import RelativeLayout

class W(RelativeLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.v = Video(source='video.mp4', state='play')
        self.s = SoundLoader.load('music.mp3')
        self.add_widget(self.v)
        self.s.play()

class X(App):
    def build(self):
        return W()

X().run()
```

in this case, when the video reach the end, it will cause problems with the sound
like shuttering or replay a little part of song many times until it stop freezing
i solved this issue in kivy.core.video.video_ffpyplayer file
just added : ffplayer.set_pause(True) in line 343
then after that when the video reach the end it stop safety
but the second problem when eos='loop':

```
from kivy.app import App
from kivy.uix.video import Video
from kivy.core.audio import SoundLoader
from kivy.uix.relativelayout import RelativeLayout

class W(RelativeLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.v = Video(source='video.mp4', state='play', options={'eos':'loop'})
        self.s = SoundLoader.load('music.mp3')
        self.add_widget(self.v)
        self.s.play()

class X(App):
    def build(self):
        return W()

X().run()
```

it again freezes when reach the end but a little bit (it doesn't looping smoothly), and (sometimes) causes shuttering to the sound
the problem increase and become always when we use Clock.schedule functions, for example:
what if we need to wait 1 second before we start playing the sound:

```
from kivy.app import App
from kivy.clock import Clock
from kivy.uix.video import Video
from kivy.core.audio import SoundLoader
from kivy.uix.relativelayout import RelativeLayout

class W(RelativeLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.v = Video(source='video.mp4', state='play', options={'eos': 'loop'})
        self.s = SoundLoader.load('music.mp3')
        self.add_widget(self.v)
        Clock.schedule_once(self.start, 1)

    def start(self, dt):
        self.s.play()

class X(App):
    def build(self):
        return W()

X().run()
```

in this case always when video reach the end it causes a strong shuttering on sound

**Comment by baseplate-admin** [comment]
please open this issue on `ffplayer` [repo](https://github.com/matham/ffpyplayer)
