### ISSUE TITLE
Kivy is incompatible with newer `Pillow` versions (>=10), and we are currently pinning version `9.5.x`

### ISSUE THREAD

**Issue by lucasgerads** [kivy/kivy#8427]
**Software Versions**
* Python: 3.11.6
* OS: Windows 11 Pro 22H2 
* Kivy: 2.2.1
* Kivy installation method: `python -m pip install "kivy[base]"`
* Pillow: 10.1.0

**Describe the bug**
I tried to run the simple kivy example on windows. Something seems to be wrong with the kivy installation. Not sure if this is a real bug, but I strictly follow the installation guide. So it seems to me there might be a way to get a broken installation. If I downgrade the version of Pillow to 9.5. Everything works again. 

**Expected behavior**
No error when executing an example from the documentation. The app that I was originally debugging simply froze and no error could be seen in the ouput log, 

**To Reproduce**

1. create and activate virtual environment 
2. install kivy with `python -m pip install "kivy[base]"`
3. copy example from https://kivy.org/doc/stable/guide/basic.html into a file `main.py` and change version number in source to 2.2.1
4. run code 

**Code and Logs and screenshots**
The complete output is in [this ](https://gist.github.com/lucasgerads/3f99d03c61141f42c3fc150cf10e29e2) gist. 
```python
import kivy
kivy.require('2.2.1') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

    def build(self):
        return Label(text='Hello world')

if __name__ == '__main__':
    MyApp().run()
```

the error message I get is: 

```
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\lucas\kivytest\main.py", line 15, in <module>
     MyApp().run()
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\uix\label.py", line 431, in texture_update
     self._label.refresh()
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\core\text\__init__.py", line 823, in refresh        
     sz = self.render()
          ^^^^^^^^^^^^^
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\core\text\__init__.py", line 759, in render
     options['space_width'] = self.get_extents(' ')[0]
                              ^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\lucas\kivytest\venv\Lib\site-packages\kivy\core\text\text_pil.py", line 37, in get_extents     
     w, h = font.getsize(text)
            ^^^^^^^^^^^^
 AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```

**Possible solution: Downgrading Pillow**
I found this [thread](https://github.com/tensorflow/models/issues/11040)

Which also seems to work for kivy. 

```
(venv) PS C:\Users\lucas\kivytest> pip uninstall pillow
Found existing installation: Pillow 10.1.0
Uninstalling Pillow-10.1.0:
  Would remove:
    c:\users\lucas\kivytest\venv\lib\site-packages\pil\*
    c:\users\lucas\kivytest\venv\lib\site-packages\pillow-10.1.0.dist-info\*
Proceed (Y/n)? Y
  Successfully uninstalled Pillow-10.1.0
(venv) PS C:\Users\lucas\kivytest> pip install Pillow==9.5.0
Collecting Pillow==9.5.0
  Downloading Pillow-9.5.0-cp311-cp311-win_amd64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 3.6 MB/s eta 0:00:00
Installing collected packages: Pillow
Successfully installed Pillow-9.5.0
```
Afterwards the example code works.

**Comment by lucasgerads** [comment]
So, looking into it. It seems this issue has been fixed in the main branch. https://github.com/kivy/kivy/commit/5585b2410b70d75158fcf4d6d6227aa7971f2679

**Comment by misl6** [comment]
Hi @lucasgerads !

I'm not closing this issue (even if we have a fix on `master` branch) as we need to track that down, as we will need to increase the release version future.

However, regarding the minor fix: As soon an external dependency we are waiting to is ready, we will start the release process for `2.3.0`.

**Comment by RobertFlatt** [comment]
Related:

kivy-ios build 8.2.0
https://github.com/kivy/kivy-ios/blob/master/kivy_ios/recipes/pillow/__init__.py#L8

p4a builds 8.4.0
https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/Pillow/__init__.py#L26

**Comment by ok-coder1** [comment]
This issue is not there with `Pillow` 10.1.0 outside of a virtual environment (venv).

**Comment by Julian-O** [comment]
I found the comments above rather misleading, so I am restating the problem.

Kivy's `text_pil.py` has the functions `get_extents()` and `get_cached_extents()` that call Pillow's `getsize()` on a font.

Pillow has [deprecated](https://pillow.readthedocs.io/en/stable/deprecations.html) this since 9.2 (which was only July 2022) and removed it in Pillow 10.0 (July 2023).

We should be using `FreeTypeFont.getbbox()` instead.

The "solution" in the main branch (https://github.com/kivy/kivy/commit/5585b2410b70d75158fcf4d6d6227aa7971f2679) isn't a fix; it is a temporary work-around. It pins to the old version of Pillow. 

That should be replaced with either using only `getbbox()` [which means only working on Pillow >=9.2] or adapting based on which functions are available [to allow it to work with both >=10 or <= 9.2 or in-between].

The version can then be unpinned.

Meanwhile, the kivy-ios and p4a recipes are hardcoded to Pillow 8.2 and 8.4 respectively. They should be updated. (In an ideal world, handling several versions.)

Finally, I don't understand the comment that this works in Pillow 10.1.0. That seems impossible. I don't know if I am missing something.

**Comment by akshayaurora** [comment]
Just tried with the following crude test,  things seem to work with `KIVY_TEXT=pil` and latest pillow.

```
kivy % git diff
diff --git a/kivy/core/text/text_pil.py b/kivy/core/text/text_pil.py
index 6549166b4..3d53d3d0a 100644
--- a/kivy/core/text/text_pil.py
+++ b/kivy/core/text/text_pil.py
@@ -34,11 +34,16 @@ class LabelPIL(LabelBase):
 
     def get_extents(self, text):
         font = self._select_font()
-        w, h = font.getsize(text)
+        try:
+            w, h = font.getsize(text)
+        except AttributeError:
+            left, top, right, bottom = font.getbbox(text)
+            w = right - left
+            h = bottom
         return w, h
 
     def get_cached_extents(self):
-        return self._select_font().getsize
+        return self.get_extents
 
     def _render_begin(self):
         # create a surface, context, font...

```

Will investigate further as this needs a few tests to make sure we are getting correct height/width etc

**Comment by misl6** [comment]
This is a blocker for the next release, as `Pillow < 10` does not have any Python 3.12 pre-built artifact.
And, `Pillow < 10` is also affected by numerous security issues.

But, we need to support both `Pillow>=10` and `Pillow<10` as `win32` wheels for `Pillow>=10` are not available.

For `win32` and `win_amd64` only, a `cp312-cp312` wheel for `9.5.0` has been published on PyPI, so `win32` can be still supported on our side, if we support both Pillow versions.

@akshayaurora do you need some testing?
