### ISSUE TITLE
"SyntaxWarning: invalid escape sequence" during doc generation

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#8438]
**Software Versions**

CI builds

**Describe the bug**

When Ubuntu unit tests run in CI environment, they build the documents, which runs a custom Sphinx preprocessor, which uses regular expressions, but doesn't properly escape them.

The result is a warning in the logs:

      /home/runner/work/kivy/kivy/doc/sources/sphinxext/preprocess.py:30: SyntaxWarning: invalid escape sequence '\.'
       if not re.match('^([a-zA-Z_][a-zA-Z0-9_]*)\.([a-zA-Z_][a-zA-Z0-9_]*)\((.*)\)', doc):
     /home/runner/work/kivy/kivy/doc/sources/sphinxext/preprocess.py:35: SyntaxWarning: invalid escape sequence '\('
       if not re.match('^([a-zA-Z_][a-zA-Z0-9_]*)\((.*)\)', doc):
     /home/runner/work/kivy/kivy/doc/sources/sphinxext/preprocess.py:40: SyntaxWarning: invalid escape sequence '\('
       if not re.match('^([a-zA-Z_][a-zA-Z0-9_]*)\((.*)\)', doc):
    /home/runner/work/kivy/kivy/kivy/__init__.py

**To Reproduce**

Run CI scripts

**Code and Logs and screenshots**

[Example](https://github.com/kivy/kivy/actions/runs/6760206023/job/18373695862).

**Comment by misl6** [comment]
Fixed via #8440
