### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by JacobD2013** [kivy/kivy#8452]
when I try to install Kivy it gives me this error:

  Using cached Kivy-2.2.1.tar.gz (24.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Collecting setuptools
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
      Collecting packaging
        Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
      Collecting cython!=0.27,!=0.27.2,<=0.29.33,>=0.24
        Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
      ERROR: Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.3 (from versions: none)
      ERROR: No matching distribution found for kivy_deps.gstreamer_dev~=0.3.3
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ElliotGarbus** [comment]
What platform are you trying to install on?
Are you following these instructions: https://kivy.org/doc/stable/gettingstarted/installation.html
Do **not** install on Python 3.12, Kivy 2.2.1 officially supports Python versions 3.7 - 3.11.
