### ISSUE TITLE
Spelling error on Kivy Home Page

### ISSUE THREAD

**Issue by ElliotGarbus** [kivy/kivy#8455]
See: https://groups.google.com/g/kivy-users/c/arqQgnW89JQ/m/4ES4bB9-CAAJ

![image](https://github.com/kivy/kivy/assets/39632979/7e8c045e-f2b6-4c4b-b9e4-00968f0ef51e)

Change to "maintained"

**Comment by Julian-O** [comment]
This should transferred to kivy/kivy-website, but I dont have the power. @ElliotGarbus, do you want to close and reraise there?

**Comment by ElliotGarbus** [comment]
posted to kivy website repository
