### ISSUE TITLE
Kivy video-player should be able to play `hls`

### ISSUE THREAD

**Issue by baseplate-admin** [kivy/kivy#8462]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when kivy cannot play `hls` videos from the internet.

**Describe the solution you'd like**
 I want `kivy` to be able to play [`hls`](https://en.wikipedia.org/wiki/HTTP_Live_Streaming)(HTTP Live Streaming) videos from the internet (provided that a server can push `hls` streams)

**Describe alternatives you've considered**
Not using `kivy` to develop the applications i want.

**Additional context**
Python m3u8 package can parse the `m3u8` file and provide chunks that can be loaded into `ffplayer`

Links : 
* [`m3u8`](https://pypi.org/project/m3u8/)

**Comment by Julian-O** [comment]
Could this be a widget in the garden rather than part of core Kivy?

If it is part of core Kivy, we need to make sure p4a and kivy-ios can support it. I note it relies on a third-party package (`backports-datetime-fromisoformat`) which is written in C, so may or may not port easily.

**Comment by baseplate-admin** [comment]
> Could this be a widget in the garden rather than part of core Kivy?

It should be part of `video` widget of kivy. Not some 3rd party garden module.

> I note it relies on a third-party package (backports-datetime-fromisoformat) which is written in C, so may or may not port easily.

Yep. That's a concern. If there's traction in this issue. I will try to port this

**Comment by FilipeMarch** [comment]
I agree It should be part of Video widget, not from 3rd party. HLS is super common nowadays and Kivy should support it.

**Comment by baseplate-admin** [comment]
Hi, If someone implements this functionality, will that get merged?

**Comment by Julian-O** [comment]
I am not sure that is going to get a yes/no answer from anyone. It depends, and it may take a while. Either way, you would have the functionality you need.

[Aside: If I were in charge of the core developers, I would warn them not to spend much time on holding one developer's hand. Go review some PRs, or come up with roadmaps, or something more valuable with your time. Leave that for more junior people.]

**Comment by misl6** [comment]
The last time I checked was ~2020, but IIRC I successfully played a `HLS` stream via `ffpyplayer` on both `iOS` and `Android`.

I'm missing some context?

**Comment by baseplate-admin** [comment]
> I'm missing some context?

Hmm, i couldn't get it running in windows. If `kivy` is able to do this, wouldn't a slight adjustment to documentation be a good choice?

**Comment by Julian-O** [comment]
@baseplate-admin: What are you proposing? Would you like to submit a PR?

**Comment by ElliotGarbus** [comment]
@baseplate-admin 
Have you tried setting the KIVY_VIDEO environment variable to ffpyplayer?
https://kivy.org/doc/stable/guide/environment.html#restrict-core-to-specific-implementation

**Comment by baseplate-admin** [comment]
> @baseplate-admin: What are you proposing? Would you like to submit a PR?

Sorry i wasn't clear. I want a guide on website on how to play `hls` streams (or add the functionality if it wasn't present)

>  Have you tried setting the KIVY_VIDEO environment variable to ffpyplayer?

Interesting. This might've been what i was looking for. Thanks :D

**Comment by Julian-O** [comment]
@baseplate-admin Please let us know it that was the solution.

**Comment by baseplate-admin** [comment]
Hi, @ElliotGarbus , @Julian-O 

I am sorry for the delay. But it seems that `kivy`  cannot play `hls` streams.

Here is the minimal code

```python
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.videoplayer import VideoPlayer
import os

os.environ["KIVY_VIDEO"] = "ffmpeg"


class MyFirstKivyApp(App):
    def build(self):
        x = VideoPlayer(
            source="https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8"
        )
        x.play = True
        return x


MyFirstKivyApp().run()

```


Logs:

```python
PS C:\Programming\test> poetry run python .\test.py   
[INFO   ] [Logger      ] Record log in C:\Users\baseplate-admin\.kivy\logs\kivy_24-05-17_10.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.4.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.7.0
[INFO   ] [Kivy        ] v2.3.0
[INFO   ] [Kivy        ] Installed at "C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoGstplayer] Using Gstreamer 1.18.5.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 552.44'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] Deprecated property "<BooleanProperty name=play>" of object "<kivy.uix.videoplayer.VideoPlayer object at 0x0000027EF4154590>" has been set, it will be removed in a future version
[INFO   ] [Base        ] Start application main loop
[ERROR  ] [Image       ] Not found <https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8>
[INFO   ] [GL          ] NPOT texture support is available

(python.exe:239924): GStreamer-WARNING **: 23:23:20.802: Failed to load plugin 'C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\share\gstreamer\bin\gioopenssl.dll': 'C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\share\gstreamer\bin\gioopenssl.dll': The specified module could not be found.

(python.exe:239924): GStreamer-WARNING **: 23:23:20.820: Failed to load plugin 'C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\share\gstreamer\bin\gstrtmp.dll': 'C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\share\gstreamer\bin\gstrtmp.dll': The specified module could not be found.

(python.exe:239924): GStreamer-WARNING **: 23:23:20.842: Failed to load plugin 'C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\share\gstreamer\bin\librtmp-1.dll': 'C:\Users\baseplate-admin\AppData\Local\pypoetry\Cache\virtualenvs\test-_tbgnEAs-py3.12\share\gstreamer\bin\librtmp-1.dll': The specified module could not be found.
[WARNING] Deprecated property "<BooleanProperty name=play>" of object "<kivy.uix.video.Video object at 0x0000027EF430AC10>" was accessed, it will be removed in a future version
[ERROR  ] [VideoGstplayer] b'Secure connection setup failed.'
[ERROR  ] [VideoGstplayer] b'Internal data stream error.'
[ERROR  ] [VideoGstplayer] b"Stream doesn't contain enough data."
[INFO   ] [Base        ] Leaving application in progress...
```

**Comment by HyTurtle** [comment]
Try running the environ change via export, or at least before the other imports

**Comment by ElliotGarbus** [comment]
While there are some warnings and an error.  This seems to work just fine.
Note I moved the enviornment change prior to loading any kivy imports, and I used a different stream.
Let me know if this works for you.   

```python
import os
os.environ["KIVY_VIDEO"] = "ffpyplayer"

from kivy.app import App
from kivy.uix.videoplayer import VideoPlayer



class MyFirstKivyApp(App):
    def build(self):
        x = VideoPlayer(
            source="https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        )
        x.play = True
        return x


MyFirstKivyApp().run()
```

You will see an error
[ERROR  ] [Image       ] Not found <https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8>
Ignore this it is an implementation detail of how video is derived from the Image widget.

**Comment by baseplate-admin** [comment]
Hmm this code snippet works after installing ffpyplayer.

Thanks @ElliotGarbus.

**Comment by baseplate-admin** [comment]
Though i think a documentation would be better in case people want this type of functionality in future.
