### ISSUE TITLE
Unnecessary raise?

### ISSUE THREAD

**Issue by baseplate-admin** [kivy/kivy#8463]
Hi, This raise method is not needed. If python fails to find the package it will automatically raise `ImportError`

https://github.com/kivy/kivy/blob/6ae4fc292373f39ce34563d6c448e8ee7c8fa193/kivy/core/video/video_ffpyplayer.py#L48-L53

**Comment by Julian-O** [comment]
Closing as duplicate of #8429 (which I raised, so YEAH! I AGREE!)

**Comment by baseplate-admin** [comment]
XD
