### ISSUE TITLE
My discord account has been compromised 

### ISSUE THREAD

**Issue by kengoon** [kivy/kivy#8477]
To the moderators of Kivy,

My discord was recently hacked. In case you get any crypto messages, I noticed I have already been banned. And I also noticed some weird crypto messages sent to all my private contacts on discord. I have already broadcast a message stating that those links were not sent by me. I have currently gained back access, but I'm still in the process of changing my password and enabling 2 factor auth. I don't know if I will be granted access back into the discord community. But I'm looking forward to getting back into the community. 

PS: I have never said or done anything related in crypto, I only use crypto for making and receiving payments. I'm not a fan of crypto referral programs or trading.

**Comment by FilipeMarch** [comment]
When I saw the message coming from you I found it very strange; I knew something was wrong. Now it is obvious you were hacked.

I hope you recover all your accounts again and welcome back!

**Comment by Julian-O** [comment]
Good luck. Closing as no action required from Kivy team

**Comment by kengoon** [comment]
Thanks guys

**Comment by kengoon** [comment]
@Julian-O an action is required, I have completely doubled my security. I tried joining via the link and it seems the ban is still in place. If that can be looked into, I would very much appreciate it

**Comment by misl6** [comment]
Can you please try to re-join? Our Discord mods have been alerted about the issue you had.

**Comment by Julian-O** [comment]
> @Julian-O an action is required

Sorry, I didn't realise this was a request for the Discord mods to take action. My apologies.

Let us know when it is resolved to your satsifaction.

**Comment by kengoon** [comment]
@Julian-O thanks, I have joined now, the issue can be closed
