### ISSUE TITLE
TextInput: incorrect value update

### ISSUE THREAD

**Issue by ioctl-user** [kivy/kivy#8496]
**Software Versions**
* Python: Python 3.11.5
* OS: Arch Linux
* Kivy: 2.2.1
* Kivy installation method: via distro package manager: pacman -S python-kivy

**Describe the bug**

Value updated by  "on_text_validate:" sometimes not shown by "text:" .

**Expected behavior**

After "on_text_validate:" triggering in some cases visible text input field doesn't updated.

**To Reproduce**

Code:
```
#!/usr/bin/python3

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.gridlayout import GridLayout
from kivy.uix.boxlayout import BoxLayout
from kivy.properties import NumericProperty


general_cfg_layout='''
<GeneralCfgLayout@GridLayout>:
    size_hint: 1, None
    width: root.width
    pos_hint: {'top': 1}
    height: sp(48)

    cols: 3
    Label:
        text: 'VAL'
    TextInput:
        id: val
        input_filter: 'float'
        text: '{:.1f}'.format(root.val)
        multiline: False
        on_text_validate:
            val = -1
            if (self.text != ""): val = float(self.text)
            print("IN VAL", val)
            if (val > 60): val = 60
            if (val < 0.1): val = 0.1
            print("OUT VAL", val)
            root.val = val

    Slider:
        id: val
        min: 0
        max: 10
        value: root.val
        on_value: root.val = self.value
'''

class GeneralCfgLayout(GridLayout):
    val = NumericProperty(0.1)
    pass

class ConfigApp(App):
    def build(self):
        Builder.load_string(general_cfg_layout)
        return GeneralCfgLayout()

if __name__ == "__main__":
    ConfigApp().run()
```

Input text is validated in this code. When input value more than 60, it become set to 60.
When input was cleared and typed number less than 0.1, it become 0.1 as it expected.

But, if previous value was 0.1, and ".1" was backspaced, leaving "0" and then Enter pressed,  root.val is set to correct value of "0.1", but in input field it will be "0" instead of expected "0.1".

Code from the "on_text_validate:" works correctly in all situations with expected debug print.

Please see screenshot with the final state of these 3 inputs.

![textinput](https://github.com/kivy/kivy/assets/23457638/1d4bb036-2d9c-420a-8756-c49494440f58)

**Comment by Julian-O** [comment]
If you take it to support, they will likely point out that nowhere in your code do you update `self.text` so there's no reason for the field to be updated.

Now, that's inconsistent with your description where you say it works sometimes and not other times, but the place for that back and forth of clarifications, and retesting, and adjusting your code is Discord, not the bug database.

**Comment by ioctl-user** [comment]
> Happy to have a discussion here: https://groups.google.com/g/kivy-users

Thanks! Problem was fixed by adding update of the self.text field in the "on_text_validate:" code.
