### ISSUE TITLE
"Level 8" Logs? Constant spam, cannot disable without entirely turning off kivy logger.

### ISSUE THREAD

**Issue by nanakusa-san** [kivy/kivy#8512]
**Software Versions**
* Python: 3.11.6
* OS: Windows
* Kivy: 2.2.1
* Kivy installation method: pip

**Describe the bug**
"Level 8" Logs? Constant spam, cannot disable without using environment variable to turn off console log... The format of the log message is definitely Kivy's, so that's why I'm asking here. Tried Trace, Info, Debug, Error, Critical.  Other logs appear intermittently, but this makes debugging without generating massive log files completely impossible.

**Expected behavior**
Logs are not spammed

**To Reproduce**
Do not currently know how to reproduce. With the code I am working with, this happens upon pressing a button that makes the program connect to an IRC server. I can't find anything that would make these messages purposefully.

**Code and Logs and screenshots**
(I did, however find this)
```python
    def process(self):
        self.reactor.process_once()
```

![image](https://github.com/kivy/kivy/assets/153875341/df7ad40e-d213-46fe-88f0-58cd8851c7f1)

**Additional context**
I didn't make this code, and it is poorly documented already, so any ideas as to what is causing this would help a lot.

**Comment by ElliotGarbus** [comment]
The issues section of github is for kivy bugs.  This is a support questions.
Post here: https://groups.google.com/g/kivy-users or in the kivy Discord. 

I suggest you close this issue.

**Comment by nanakusa-san** [comment]
i assumed this was a bug, as it's not documented in kivy logger or mentioned anywhere on the internet that i could find.

**Comment by Julian-O** [comment]
It isn't a Kivy bug. If you bring it to Discord we can configure your logger to get an idea where it comes from.
