### ISSUE TITLE
I want to start

### ISSUE THREAD

**Issue by nigo697** [kivy/kivy#8520]
Hi everyone
I want to start coding with Kivy. I can program with Python, but I have no idea of Kivy. How can I start? Is there a list of the basic commands which I have to know? And how does the syntax of Kivy works? Where can I learn how the order of the commands have to be? I hope anyone can help me. Thank you!
Have a nice day!

**Comment by Julian-O** [comment]
@nigo697: The documentation for Kivy is easy to google.
