### ISSUE TITLE
How to draw a smooth circle in kivy 

### ISSUE THREAD

**Issue by dev-param** [kivy/kivy#8528]
![Screenshot_20231227_122042_kivytry](https://github.com/kivy/kivy/assets/75372705/41709fd4-f41a-491d-8605-beadd2342777)

**Comment by baseplate-admin** [comment]
Hi, @Julian-O i think this is an issue with anti aliasing

**Comment by dev-param** [comment]
Yes how I can draw smooth circle 🔵  I try effect widget but not successful

**Comment by mak8kammerer** [comment]
@dev-param, please, wait for 2.3.0 release. [Graphical instructions with anti-aliasing](https://kivy.org/doc/master/api-kivy.graphics.html#kivy.graphics.SmoothEllipse) will be available in it.

**Comment by dev-param** [comment]
🤩
