### ISSUE TITLE
"kivy.properties" is not accessed

### ISSUE THREAD

**Issue by Ramboliner** [kivy/kivy#8531]
macOS Monterey Version 12.0.1
Python 3.10.1
Kivy Version: 2.2.1
Kivy installation method: pip
IDE : Visual Studio Code

Somehow my program does not recognise Kivy.properties as one of the modules. I have no idea why all the other seem to be working just fine. Could not find solutions for this anywhere. 

"kivy.properties" is not accessed

<img width="551" alt="Screenshot 2023-12-28 at 2 14 00" src="https://github.com/kivy/kivy/assets/97124091/bee0ebac-29b5-4e38-bb26-b4830807415f">

I'd love to hear suggestions!

**Comment by Julian-O** [comment]
This is a syntax error in an import statement - nothing to do with Kivy.

**Comment by ElRafeta697** [comment]
@Ramboliner Try with a full statement: `from kivy.properties import *`
This module is never colorized by VSCode, but it works

**Comment by Ramboliner** [comment]
> @Ramboliner Try with a full statement: `from kivy.properties import *`
> This module is never colorized by VSCode, but it works

Yes this was the problem, I was confused by this. Thank you!
