### ISSUE TITLE
`PIL` text provider: Critical issues if `font_size` is `< 1`

### ISSUE THREAD

**Issue by DexerBR** [kivy/kivy#8538]
**Software Versions**
* Python: `3.8.9`
* OS: Windows
* Kivy: `2.3.0rc2`
* Kivy installation method: `python -m pip install --pre "kivy[base]"` / `pip install Kivy==2.3.0rc2`

**Describe the bug**
After upgrading from Pillow 9.x.x to Pillow 10.x.x, some errors are occurring, some with no clear cause. Some critical errors already existed in previous versions of kivy/Pillow.

🔴  Note: This same code works correctly (without errors) with the `"sdl2"` text provider

# Issue 1:
### Works in `9.x.x`, breaks in `10.x.x`:
```python
import os
os.environ["KIVY_TEXT"] = "pil"

from kivy.app import App
from kivy.uix.label import Label


class LabelTest(App):
    def build(self):
        return Label(text='Kivy rulz', font_size=0)

LabelTest().run()
```

### Error:
```
   File "lib\site-packages\kivy\uix\label.py", line 432, in texture_update
     self._label.refresh()
   File "lib\site-packages\kivy\core\text\__init__.py", line 836, in refresh
     sz = self.render()
   File "lib\site-packages\kivy\core\text\__init__.py", line 772, in render
     options['space_width'] = self.get_extents(' ')[0]
   File "lib\site-packages\kivy\core\text\text_pil.py", line 39, in get_extents
     font = self._select_font()
   File "lib\site-packages\kivy\core\text\text_pil.py", line 33, in _select_font
     font = ImageFont.truetype(fontname, fontsize)
   File "lib\site-packages\PIL\ImageFont.py", line 797, in truetype
     return freetype(font)
   File "lib\site-packages\PIL\ImageFont.py", line 794, in freetype
     return FreeTypeFont(font, size, index, encoding, layout_engine)
   File "lib\site-packages\PIL\ImageFont.py", line 226, in __init__
     self.font = core.getfont(
 OSError: invalid ppem value
```

# Issue 2:

### Breaks in `9.x.x`, and in `10.x.x`, and in previous versions of kivy:

```python
import os
os.environ["KIVY_TEXT"] = "pil"

from kivy.app import App
from kivy.uix.label import Label


class LabelTest(App):
    def build(self):
        return Label(text='Kivy rulz', font_size=-10)

LabelTest().run()
```

### Error:
```
   File "lib\site-packages\kivy\uix\label.py", line 432, in texture_update
     self._label.refresh()
   File "lib\site-packages\kivy\core\text\__init__.py", line 836, in refresh
     sz = self.render()
   File "lib\site-packages\kivy\core\text\__init__.py", line 812, in render
     w, h, clipped = layout_text(text, lines, (0, 0), (uw, uh), options,
   File "kivy\\core\\text\\text_layout.pyx", line 408, in kivy.core.text.text_layout.layout_text
   File "kivy\\core\\text\\text_layout.pyx", line 235, in kivy.core.text.text_layout.layout_text_unrestricted
   File "lib\site-packages\kivy\core\text\text_pil.py", line 37, in get_extents
     left, top, right, bottom = font.getbbox(text)
   File "lib\site-packages\PIL\ImageFont.py", line 408, in getbbox
     size, offset = self.font.getsize(
 OSError: invalid argument
```

# Issue 3:
### Works in `9.x.x`, breaks in `10.x.x`:
```
There is still no minimum reproducible code
```

### Error:
```
File "lib\site-packages\kivy\core\text\__init__.py", line 828, in _texture_fill
    self.render(real=True)
  File "lib\site-packages\kivy\core\text\markup.py", line 143, in render
    ret = self._render_real()
  File "lib\site-packages\kivy\core\text\__init__.py", line 752, in _render_real
    self.render_lines(lines, options, self._render_text, y, size)
  File "lib\site-packages\kivy\core\text\markup.py", line 500, in render_lines
    render_text(word.text, x, y + script_pos)
  File "lib\site-packages\kivy\core\text\text_pil.py", line 66, in _render_text
    self._pil_draw.text((int(x), int(y)),
  File "lib\site-packages\PIL\ImageDraw.py", line 565, in text
    draw_text(ink)
  File "lib\site-packages\PIL\ImageDraw.py", line 508, in draw_text
    mask, offset = font.getmask2(
  File "lib\site-packages\PIL\ImageFont.py", line 580, in getmask2
    offset = self.font.render(
OSError: unsupported bitmap pixel mode
```

**Expected behavior**
Behave like the `sdl2` text provider

### Proposed solutions
- issues 1 and 2 -  Limit within the `PIL` text provider the font size to `> 0`
- issue 3 -  If the root cause of the issue is not identified, treat the error on the line [66](https://github.com/kivy/kivy/blob/master/kivy/core/text/text_pil.py#L66):
```python
self._pil_draw.text((int(x), int(y)),
                    text, font=self._select_font(), fill=color)
```

**Comment by DexerBR** [comment]
### The third issue also appears to be related to font size (works if `font_size=1`):

```python
from PIL import Image, ImageDraw, ImageFont

font_path = 'path/to/font.ttf'
font_size = 0

image = Image.new('RGB', (100, 100), color='white')
draw = ImageDraw.Draw(image)

font = ImageFont.truetype(font_path, font_size)

text = "Hello, World!"
position = (0, 0)

draw.text(position, text, font=font, fill='black')

image.show()
```

Error:
```
Traceback (most recent call last):
  File "main.py", line 1143, in <module>
    draw.text(position, text, font=font, fill='black')
  File "lib\site-packages\PIL\ImageDraw.py", line 565, in text
    draw_text(ink)
  File "lib\site-packages\PIL\ImageDraw.py", line 508, in draw_text
    mask, offset = font.getmask2(
  File "lib\site-packages\PIL\ImageFont.py", line 580, in getmask2
    offset = self.font.render(
OSError: unsupported bitmap pixel mode
```

**Comment by Julian-O** [comment]
Thanks for the PR. I think it is worth being clearer what you mean by "critical". These don't seem to be blocking defects that should prevent the release. They seem to only occur when bad values are passed as font sizes.

Perhaps ValueError excpetions should be raised.

**Comment by DexerBR** [comment]
> Thanks for the PR. I think it is worth being clearer what you mean by "critical". These don't seem to be blocking defects that should prevent the release. They seem to only occur when bad values are passed as font sizes.
> 
> Perhaps ValueError excpetions should be raised.

Why I consider it critical:
1 - Does not occur with the "sdl2" text provider
2 - The `PIL` text provider is internally defined as the global text provider
3 - Two of the issues did not occur in the previous target version of PIL defined as default by kivy, but occur in the new version defined as default

So if with previous versions of PIL we had 1 error being raised, now there are 3 errors.

**Comment by DexerBR** [comment]
I only see 3 possibilities:

🔴  Keep the PIL `>= 10.x.x` as the default version and have the 3/3 issues

🟠  Change the default version of the PIL and recommend the use of PIL < 10.x.x, to avoid 2/3 issues, but keep 1/3 issues

🟢  Merge this #8540 and resolve the 3/3 issues

**Comment by DexerBR** [comment]
> Thanks for the PR. I think it is worth being clearer what you mean by "critical". These don't seem to be blocking defects that should prevent the release. They seem to only occur when bad values are passed as font sizes.
> 
> Perhaps ValueError excpetions should be raised.

Furthermore, it is common to understand `font_size=0` as "don't render me". This is consistent behavior with other Kivy widgets, layouts, graphics, etc.

**Comment by Julian-O** [comment]
> it is common to understand font_size=0 as "don't render me".

Oooh, interesting. Pillow doesn't have that convention. Is that documented anywhere in Kivy? 

Note: I am all for fixing this issue. 

If I had sufficient access I would retitle this because, from a Kivy perspective, this is not at all critical. Passing bad parameters to font sizes is not noticed in some provider configurations, but raises a cryptic error in others? That is poor behaviour, but not "critical".

I note that the next release of Pillow will [give better error messages](https://github.com/python-pillow/Pillow/issues/7583).

As I see it, the viable options are:

* Keep the PIL >= 10.x.x as the default version and have the 3/3 issues - 1 of which was never noticed before, and 2 of which will only affect a tiny percentage of people who are abusing the API and should fix their code in any case. Fix it in next release.

* If the patch is well-tested and we can be confident it won't turn out to cause other problems, AND there are other bug-fixes that justify an additional Release Candidate, merge it in and make a new Release Candidate.

**Comment by misl6** [comment]
PR merged, the final RC3 will be released on Monday.
