### ISSUE TITLE
TextInput issue

### ISSUE THREAD

**Issue by swuY34** [kivy/kivy#8552]
### **Software Versions**
Python 3.12.1
Windows 10
Kivy 2.3.0
pip install kivy

### **Issue**
The content in the **TextInput** box cannot be changed through `self.ids["fluxus_text_input"].text = "example text"` (when there is other code below this code)

```python
def change_text_input_text(self):
    self.ids["fluxus_text_input"].text = 'wait for bypass key....'
    # if i don't do time sleep it's no problem;  but when i have code after this line it can't be change the text 

    time.sleep(5)
```

**Comment by ElliotGarbus** [comment]
Share a runnable minimal example.
FWIW you do not want to use sleep in the main thread of a kivy program.  It stalls the event loop, effectively locking up the program.  To create a delay use Clock.schedule_once() to schedule a callback or another Clock method.

**Comment by swuY34** [comment]
> Share a runnable minimal example.
> FWIW you do not want to use sleep in the main thread of a kivy program.  It stalls the event loop, effectively locking up the program.  To create a delay use Clock.schedule_once() to schedule a callback or another Clock method.

I resolved, thenks for your method！
