### ISSUE TITLE
Remove all the `PY2` compat code

### ISSUE THREAD

**Issue by misl6** [kivy/kivy#8566]
During the years we left `PY2` compatibility code around the code.

Kivy `3.0.0` is an opportunity to do some cleanup, since we do not support Python 2 anymore.

E.g: https://github.com/kivy/kivy/blob/5df8304480f5980ed8dc5f08919efffbe9e48da5/kivy/graphics/instructions.pyx#L19

**Comment by Valinor** [comment]
Hello,

I am interested in contributing to your project and believe that starting with the cleanup tasks would be a beneficial way for me to familiarize myself with both the codebase and community processes.

I would like to begin with this task, if that aligns with your expectations.

Additionally, I seek some clarification. I have removed all PY2 references, but I am thinking that the removal of the entire compat.py class can be done. Would this be acceptable? Is it the point of this task ?

Lastly, I encountered some failures when running tests, specifically those involving MultiTouch and MouseHover, even before making any changes. Is this normal? Can you point me some clarification about theses tests?

Thanks.

**Comment by Julian-O** [comment]
I can't comment on the failing tests, but yes, I would like to see the compat.py class removed.

**Comment by misl6** [comment]
Hi @Valinor ,

I moved the task to "In progress", and I've seen @Julian-O already assigned the issue to you ❤️

Removing `compat.py`, `PY2`, and any other Python 2 compatibility things is part of the scope of this issue.

About failing tests, ignore what was already failing before your changes. (I guess it will not fail on CI/CD, but on your machine).

BTW, feel free the share more info about the failing tests in a separate issue.

**Comment by misl6** [comment]
Closed via #8610
