### ISSUE TITLE
Python `3.7` reached EOL, set minimum Python version to `3.8`

### ISSUE THREAD

**Issue by misl6** [kivy/kivy#8567]
Since Python ´3.7´ reached EOL:

- Set minimum Python version to `3.8`
- Remove builds for `3.7`
- Remove CI/CD tests for `3.7`
- Take advantage of `3.8` and above features, where applicable.

**Comment by nidhi-2619** [comment]
Hi Mirko , I would like to contribute to kivy , and I think this issue will be a good starting point, please assign this to me.

**Comment by misl6** [comment]
Hi @nidhi-2619 , the issue has been assigned to you.

If you need help during the development, feel free to ask on the #dev channel on [Discord](https://chat.kivy.org)
