### ISSUE TITLE
Ability to add provider tag to manifest.xml through buildozer

### ISSUE THREAD

**Issue by alexg93333** [kivy/kivy#8603]
< provider
    android:name="androidx.core.content.FileProvider"
    android:authorities="${applicationId}.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />
</ provider > 

Right now as far as I understood, there is no other way to add the provider tag into the manifest other than manually? It would be great if I could do it with buildozer. There are already a few options to alter manifest.xml but not for the application tag where the provider belongs.

**Comment by Julian-O** [comment]
This isn't a Kivy framework issue. It is a Python-For-Android feature request, and should be raised there.
