### ISSUE TITLE
Hash error trying to install Kivy via pip on Raspi

### ISSUE THREAD

**Issue by japeart** [kivy/kivy#8606]
On the raspberry pi platform, I'm trying to follow the instructions to install Kivy via pip, however getting the following error before the download can complete:

`ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    kivy from https://www.piwheels.org/simple/kivy/Kivy-2.3.0-cp39-cp39-linux_armv7l.whl#sha256=38532bd61d2b160cd31aa645f0d7d633b6a3b413227bd5ef37e1008b2ceed6e6:
        Expected sha256 38532bd61d2b160cd31aa645f0d7d633b6a3b413227bd5ef37e1008b2ceed6e6
             Got        424c73adc528a58ea9a638e631b51c3a8e6ff80d8c90b407d56b92fadf8bc360`

**Comment by misl6** [comment]
- Can you please share your requirements file?
- Maybe a temp network issue that downloaded an incomplete file?
- Generally, can you please share more details?

**Comment by japeart** [comment]
Sure, where can I find the requirements file? this is the command I ran as per the installation guide
`python -m pip install "kivy[base]"`

**Comment by misl6** [comment]
Ok, so no requirements file and no hash involved.

- Maybe a temp network issue that downloaded an incomplete file?

Can you try to just avoid using cache with pip? https://pip.pypa.io/en/stable/topics/caching/#avoiding-caching
