### ISSUE TITLE
WebGPU integration

### ISSUE THREAD

**Issue by Korijn** [kivy/kivy#8613]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
I want to integrate our webgpu based rendering library [pygfx](https://github.com/pygfx/pygfx) with Kivy.

Similar to the [example](https://kivy.org/doc/stable/examples/gen__3Drendering__main__py.html) you have where you create a render context for OpenGL and render inside a rectangular area, I want to do the same thing with pygfx. Except that it doesn't use OpenGL, it uses WebGPU.

I guess the most obvious integration would be to render offscreen to a texture with pygfx, and then display that texture with Kivy. But that involves some overhead that I would prefer to avoid by drawing directly to the screen.

This is why I'm opening this ticket; to get some advice from official maintainers. :)

**Describe alternatives you've considered**
N/A

**Additional context**
I'm one of the maintainers of [wgpu-py](https://github.com/pygfx/wgpu-py) and [pygfx](https://github.com/pygfx/pygfx)

**Comment by Korijn** [comment]
Reopen, it is not a support request.

**Comment by baseplate-admin** [comment]
Rethinking i dont think, it's possible with `kivy` or it is supported at this moment.

---

> Reopen, it is not a support request.

I agree. This is a feature request.

**Comment by kushalkolar** [comment]
We would also be interested in this for [fastplotlib](https://github.com/fastplotlib/fastplotlib) which uses pygfx :D

**Comment by Korijn** [comment]
I think we can make it work regardless using offscreen rendering, but I would be very interested to see if we can unlock higher performance :)

**Comment by Julian-O** [comment]
*Shrug* 

> This is why I'm opening this ticket; to get some advice from official maintainers.

Sounds awfully like a support request to me. This sounds like what the #dev channel on Discord is for.

**Comment by Korijn** [comment]
I don't mind taking it to Discord.
