### ISSUE TITLE
Failed building wheel for ffpyplayer

### ISSUE THREAD

**Issue by CodeRabbit957** [kivy/kivy#8639]
**Software Versions**
* Python:
* OS: Rasp Pi OS Lite + KDE Plasma
* Kivy:
* Kivy installation method: pip - virtual env

**Describe the bug**
See error below. Looks like a problem with sdl.h.

`python -m pip install "kivy[full]"          
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: kivy[full] in ./.env/lib/python3.11/site-packages (2.3.0)
Requirement already satisfied: Kivy-Garden>=0.1.4 in ./.env/lib/python3.11/site-packages (from kivy[full]) (0.1.5)
Requirement already satisfied: docutils in ./.env/lib/python3.11/site-packages (from kivy[full]) (0.20.1)
Requirement already satisfied: pygments in ./.env/lib/python3.11/site-packages (from kivy[full]) (2.17.2)
Requirement already satisfied: pillow<11,>=9.5.0 in ./.env/lib/python3.11/site-packages (from kivy[full]) (10.2.0)
Collecting ffpyplayer (from kivy[full])
  Using cached ffpyplayer-4.5.1.tar.gz (88 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests in ./.env/lib/python3.11/site-packages (from Kivy-Garden>=0.1.4->kivy[full]) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.env/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy[full]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./.env/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy[full]) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.env/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy[full]) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in ./.env/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy[full]) (2024.2.2)
Building wheels for collected packages: ffpyplayer
  Building wheel for ffpyplayer (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ffpyplayer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      Source/build path: /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579
      FFMPEG_ROOT: "None"
      WARNING: A problem occured while running pkg-config --libs --cflags libavcodec libavdevice libavfilter libavformat libavutil libswscale libswresample libpostproc (code 1)
      
      b"Package libavcodec was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libavcodec.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'libavcodec', required by 'virtual:world', not found\nPackage 'libavdevice', required by 'virtual:world', not found\nPackage 'libavfilter', required by 'virtual:world', not found\nPackage 'libavformat', required by 'virtual:world', not found\nPackage 'libavutil', required by 'virtual:world', not found\nPackage 'libswscale', required by 'virtual:world', not found\nPackage 'libswresample', required by 'virtual:world', not found\nPackage 'libpostproc', required by 'virtual:world', not found\n"
      
      SDL_ROOT: "None"
      WARNING: A problem occured while running pkg-config --libs --cflags sdl2 (code 1)
      
      b"Package sdl2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `sdl2.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'sdl2', required by 'virtual:world', not found\n"
      
      Generating ffconfig.h
      Generating ffconfig.pxi
      Include directories: ['/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer', '/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/includes']
      Library directories: []
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/ffpyplayer
      copying ffpyplayer/__init__.py -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      creating build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/__init__.py -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      creating build/lib.linux-aarch64-cpython-311/ffpyplayer/tests
      copying ffpyplayer/tests/__init__.py -> build/lib.linux-aarch64-cpython-311/ffpyplayer/tests
      copying ffpyplayer/tests/test_write.py -> build/lib.linux-aarch64-cpython-311/ffpyplayer/tests
      copying ffpyplayer/tests/common.py -> build/lib.linux-aarch64-cpython-311/ffpyplayer/tests
      copying ffpyplayer/tests/test_pic.py -> build/lib.linux-aarch64-cpython-311/ffpyplayer/tests
      copying ffpyplayer/tests/test_play.py -> build/lib.linux-aarch64-cpython-311/ffpyplayer/tests
      copying ffpyplayer/player/frame_queue.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/core.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/decoder.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/queue.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/clock.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/player.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      creating build/lib.linux-aarch64-cpython-311/ffpyplayer/clib
      copying ffpyplayer/clib/misc.h -> build/lib.linux-aarch64-cpython-311/ffpyplayer/clib
      creating build/lib.linux-aarch64-cpython-311/ffpyplayer/includes
      copying ffpyplayer/includes/ffmpeg.pxi -> build/lib.linux-aarch64-cpython-311/ffpyplayer/includes
      copying ffpyplayer/includes/ff_consts.pxi -> build/lib.linux-aarch64-cpython-311/ffpyplayer/includes
      copying ffpyplayer/includes/sdl.pxi -> build/lib.linux-aarch64-cpython-311/ffpyplayer/includes
      copying ffpyplayer/includes/inline_funcs.pxi -> build/lib.linux-aarch64-cpython-311/ffpyplayer/includes
      copying ffpyplayer/includes/ffconfig.pxi -> build/lib.linux-aarch64-cpython-311/ffpyplayer/includes
      copying ffpyplayer/includes/ffconfig.h -> build/lib.linux-aarch64-cpython-311/ffpyplayer/includes
      copying ffpyplayer/writer.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      copying ffpyplayer/pic.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      copying ffpyplayer/threading.pxd -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      copying ffpyplayer/player/decoder.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/player.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/clock.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/core.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/frame_queue.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/player/queue.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer/player
      copying ffpyplayer/clib/misc.c -> build/lib.linux-aarch64-cpython-311/ffpyplayer/clib
      copying ffpyplayer/writer.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      copying ffpyplayer/pic.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      copying ffpyplayer/threading.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      copying ffpyplayer/tools.pyx -> build/lib.linux-aarch64-cpython-311/ffpyplayer
      running build_ext
      Build path changed to: /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579
      Using compiler "unix"
      Using compiler args: ['-O3', '-fno-strict-aliasing', '-Wno-error']
      Using linker args: []
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/pic.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/pic.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/threading.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/threading.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/tools.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/tools.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/writer.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/writer.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/clock.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/clock.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/core.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/core.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/decoder.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/decoder.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/frame_queue.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/frame_queue.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/player.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/player.c
      cythoning /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/queue.pyx to /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/player/queue.c
      building 'ffpyplayer.pic' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/tmp
      creating build/temp.linux-aarch64-cpython-311/tmp/pip-install-blnokkro
      creating build/temp.linux-aarch64-cpython-311/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579
      creating build/temp.linux-aarch64-cpython-311/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer
      creating build/temp.linux-aarch64-cpython-311/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/clib
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer -I/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/includes -I/home/redrobin/.env/include -I/usr/include/python3.11 -c /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/clib/misc.c -o build/temp.linux-aarch64-cpython-311/tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/clib/misc.o -O3 -fno-strict-aliasing -Wno-error
      In file included from /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/clib/misc.h:5,
                       from /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/clib/misc.c:2:
      /tmp/pip-install-blnokkro/ffpyplayer_f93d1d5951c54425bca7837f425bc579/ffpyplayer/clib/../includes/ffconfig.h:5:10: fatal error: SDL_version.h: No such file or directory
          5 | #include "SDL_version.h"
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ffpyplayer
Failed to build ffpyplayer
ERROR: Could not build wheels for ffpyplayer, which is required to install pyproject.toml-based projects
`

**Additional context**

I installed Kivy base first with no issues. Then tried to install full but got the ffpyplayer error.

Since I'm using KDE plasma as my DE on top of Rasp Pi OS Lite, I'm not sure if I need to run the extra command for additional depenencies. I tried it just in case, but got the following result:

`apt-get install libgl1-mesa-glx libgles2-mesa libegl1-mesa libmtdev1
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
`
(I am the only user.)

**Comment by ElectroDrome** [comment]
I've the same issue at full installation.

**Comment by misl6** [comment]
Hi @ElectroDrome and @CodeRabbit957 !

This does not look like an issue with Kivy, but with https://github.com/matham/ffpyplayer install as a pre-built artifact does not exists for your specific architecture.

However, feel free to reach out on our support channels, where someone certainly will try to help you.
