### ISSUE TITLE
`im.add_mipmap` requires five parameters, but only four arguments are being used

### ISSUE THREAD

**Issue by marinelay** [kivy/kivy#8685]
**Software Versions**
* Python: 3.9.18
* OS: Ubuntu 22.04
* Kivy: 2.3.0
* Kivy installation method: pi pinstall

**Describe the bug**
https://github.com/kivy/kivy/blob/c0d4894384abb81cf4729984a1eaa4c437d266da/kivy/core/image/img_dds.py#L27-L36

While `im.add_mipmap` has five parameters (`def add_mipmap(self, level, width, height, data, rowlength):`), 
there are only four arguments at line 35.

I think it's a bug, but I'm not sure how to reproduce it.
I apologize for not providing reproduction code.

**Code and Logs and screenshots**
https://github.com/kivy/kivy/blob/c0d4894384abb81cf4729984a1eaa4c437d266da/kivy/core/image/img_dds.py#L27-L36

https://github.com/kivy/kivy/blob/c0d4894384abb81cf4729984a1eaa4c437d266da/kivy/core/image/__init__.py#L174-L179

**Comment by kuzeyron** [comment]
Feel free making a PR to solve this if it's still a problem.
