### ISSUE TITLE
`disable_multitouch` should also disable MTD loading on Linux

### ISSUE THREAD

**Issue by ikus060** [kivy/kivy#8708]
**Software Versions**
* Python: 3.10
* OS: Linux
* Kivy: 2.3.0
* Kivy installation method: pip install

**Describe the bug**

When starting kivy with `Config.set('input', 'mouse', 'mouse,disable_multitouch')` I'm not expecting kivy to warn agains missing permissions like the following:
```
2024-04-23 16:19:21,656 [281744][WARNI][MTDMotionEve] MTD: Unable to open device "/dev/input/event13". Please ensure you have the appropriate permissions.
```

**Expected behavior**
When multitouch is disabled, Kivy should not try to access MTD and should not raise a warning in the logs.

**To Reproduce**
Simply start a kivy application with `Config.set('input', 'mouse', 'mouse,disable_multitouch')` where permissions are not properly set.

**Code and Logs and screenshots**
N/A

**Additional context**
N/A

**Comment by kuzeyron** [comment]
`sudo gpasswd -a $USER input; reboot`

**Comment by ikus060** [comment]
You solution it not a solution to the problem. It's a work arround.

When defining `disable_multitouch`, I would not expect Kivy application to try loading MTD and I would not expect a warning in the logs either.
