### ISSUE TITLE
matplotlib error kivy 2.3.0

### ISSUE THREAD

**Issue by jspuser123** [kivy/kivy#8740]
**Software Versions**
* Python:3.10.11
* OS:windows
* Kivy:2.3.0

**Describe the bug**
already old version working but updated version not working  matplotlib pls fix issue

python runtime error

```python 
 File "C:\Users\it1\.kivy\garden\garden.matplotlib\backend_kivy.py", line 1233, in _on_size_changed
     self.resize_event()
 AttributeError: 'FigureCanvasKivyAgg' object has no attribute 'resize_event'
```

**Comment by misl6** [comment]
Hi @jspuser123 ,

This issue does not belong to `kivy`, but to `kivy.garden.matplotlib`, which is hosted on another repo.

The good news is that the issue you're posting here has been fixed on a recent alpha release of the migrated flower:

- https://github.com/kivy-garden/matplotlib
- https://pypi.org/project/kivy-garden.matplotlib/
