### ISSUE TITLE
Kivylang include other kv files and is invalid in apk

### ISSUE THREAD

**Issue by WangZhongDian** [kivy/kivy#8748]
# Problem description
`adb logcat`
![image](https://github.com/kivy/kivy/assets/103353084/b5046e9d-fca1-4595-b0ca-ca5ab9a1e6e8)
The kivy program runs normally on the computer and can load kv files. However, when packaged as apk and running on Android, there may be a problem with loading kv files. I suspect that kvlang did not handle the include statement properly during packaging

# tree
```
├── dynamic
│   └── json
│       └── team.json
├── src
│   ├── pages
│   │   ├── addTeam
│   │   │   ├── addTeam.kv
│   │   │   └── addTeam.py
│   │   └── home
│   │       ├── kv
│   │       │   ├── home.kv
│   │       │   ├── middle.kv
│   │       │   └── teamcardswipe.kv
│   │       ├── TeamCardSwipe.py
│   │       ├── home.py
│   │       └── middle.py
│   └── utils
│       ├── fonts_config.py
│       └── team.py
├── static
│   └── fonts
│       └── song_typeface.ttf
├── README.md
├── buildozer.spec
├── main.py
└── requirements.txt
```
# Error code section
`home.kv`:src\pages\home\kv\home.kv
```python
#:kivy 2.3.0

#:import MDSwapTransition kivymd.uix.transition.MDSwapTransition

#:include force src\pages\home\kv\teamcardswipe.kv
#:include force src\pages\home\kv\middle.kv

#导航选项模板
<MDNavigationItemLabelItem@MDNavigationItemLabel>:
    role:'small'
```
I want to import teamcardswipe.kv and middle.kv from home.kv. Initially, everything was fine, but when running on the Android side, path errors would occur

**Comment by ElliotGarbus** [comment]
This is a support issue, not a bug.  I suggest you post your issue to the kivy discord.
Android storage is not the same as on your computer, read: https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#android-storage
