### ISSUE TITLE
BoxLayouts' height in RecycleView (Label's height: texture_size[1])

### ISSUE THREAD

**Issue by kazuki-orange** [kivy/kivy#8761]
env. : Python==3.11.5, Kivy==2.3.0

I'm trying to make an app with RecycleView. The RecycleBoxLayout has several BoxLayouts and they will have several Labels. All the widgets will be piled vertically.

This is the code:

```
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.boxlayout import BoxLayout
from kivy.properties import ListProperty
from kivy.lang import Builder

from random import randint

KV = '''
<RVLabel>:
    size_hint_y: None
    text_size: self.width, None
    height: self.texture_size[1]

    canvas.before:
        Color:
            rgba: .1, .2, .3, 1
        Rectangle:
            pos: self.pos
            size: self.size

<RVBoxLayout>:
    orientation: 'vertical'
    # size_hint_y: None
    height: self.minimum_height

RecycleView:
    viewclass: 'RVBoxLayout'
    RecycleBoxLayout:
        orientation: 'vertical'
        default_size: None, None
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
'''

class RVBoxLayout(BoxLayout):
    labels = ListProperty([])

    def on_labels(self, instance, data):
        self.clear_widgets()
        for label in self.labels:
            self.add_widget(RVLabel(text=label['text']))

class RVLabel(Label):
    pass

class TestApp(App):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        rv = self.root
        rv_data = []

        for i in range(10):
            box_layout = {'labels': [
                    {'text': f'Toooooooooooooooooooooooooooooooooooo Long Label {j}'} for j in range(randint(1, 5))
            ]}
            rv_data.append(box_layout)

        rv.data = rv_data

if __name__ == '__main__':
    TestApp().run()
```

I expected the widgets fit tightly together, but I got a result like this:

![image](https://github.com/kivy/kivy/assets/109294250/951d5852-bafc-45a3-bb24-e4ce8ef60324)

or in the other case, some Labels show randomly.

When I fix the labels height, height: 30 for example, they are shown correctly but I need the texts to be wrapped.

How can I do that?

Any of your helps will be appreciated!

**Comment by ElliotGarbus** [comment]
@kazuki-orange I'd be happy to help you on a support channel.  The issues section on github is for reporting bugs.
Try one of these forums:
https://groups.google.com/g/kivy-users
https://discord.com/invite/eT3cuQp
https://www.reddit.com/r/kivy/

**Comment by kazuki-orange** [comment]
Thank you for replying. I’ll take one of them and let me close the issue.
