### ISSUE TITLE
kivy app error on some devices

### ISSUE THREAD

**Issue by herbe13** [kivy/kivy#8780]
does anyone know why an app might not work on certain phone variants? for example my kivy app works on samsung variants, but on some xiaomi variants ( example: Redmi Note 11 Pro 5G ) it doesn't work, but on other newer xiaomi variants everything works perfectly
I honestly drive myself crazy that I can't find something clear and I hit walls
I have attached the log from Android Studio when I launched the app on my Redmi Note 11 Pro 5G phone

[xiaomi.txt](https://github.com/user-attachments/files/16159714/xiaomi.txt)

**Comment by RobertFlatt** [comment]
For clarity, this the error in the log, presumably the cause of the issue you see.
```
2024-07-10 13:29:35.904 15462-15768 python                  org.hivetress.hivetress              I  [ERROR  ] Error when copying logo directory
...
[Errno 13] Permission denied: '/data/user/0/org.hivetress.hivetress/files/app/.kivy/icon'
```
Personally I know nothing about the device in question or this issue.

**Comment by herbe13** [comment]
I resolved. The problem was generated from "fs = StringProperty(None)" and "texture = ObjectProperty(None)", I tried to create a shader and on some devices if the property 'None' remains, may be cause errors like "Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40 in tid 19061 (SDLThread), pid 18741 (SDLActivity)"
I will close this. Thank you for help!
