### ISSUE TITLE
kivy.org certificate status: expired

### ISSUE THREAD

**Issue by stund-ogha** [kivy/kivy#8785]
**Software Versions**
* Python: NA
* OS: NA
* Kivy: NA
* Kivy installation method: NA

**Describe the bug**
kivy.org documentation pages are unnavailable last I checked at 07/20/2024 1700 EST

**Expected behavior**
Normal loading of kivy.org site.

**To Reproduce**
Travel to https://kivy.org/doc/stable/gettingstarted

**Code and Logs and screenshots**
NA

**Additional context**
NA

**Comment by misl6** [comment]
Fixed. Thank you!
