### ISSUE TITLE
kivy kivymd android app closed while playing in kivy's Video widget , on android   - Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 13961 (SDLThread), pid 13855 (SDLActivity)

### ISSUE THREAD

**Issue by Sahil-pixel** [kivy/kivy#8787]
testing  on android 13
Buildozer 1.5.0

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 13961 (SDLThread), pid 13855 (SD
[buildozer.txt](https://github.com/user-attachments/files/16388712/buildozer.txt)
LActivity) 
[kivylogs.txt](https://github.com/user-attachments/files/16388687/kivylogs.txt)

**Comment by akshayaurora** [comment]
The issue template is provided for a reason. Please follow it. Re-open the issue with filling in the details along with a simple reproducible example.
