### ISSUE TITLE
 Permission denied

### ISSUE THREAD

**Issue by 408550969** [kivy/kivy#8789]
**Software Versions**
* Python:3.11
* OS:android
* Kivy:Latest
* Kivy installation method:

**Describe the bug**
PermissionError: [Errno 13] Permission denied: '/sdcard/Download/tk.csv'

**Additional context**
I have added read and write permissions in buildozer.spec: android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE。
 And in Python, request_permissions ([Permission.WRITE-EXTRNAL_STORAGE, Permission.READ_EXTERNAL_STORAGE])， But it still reports an error: Permission denied: '/sdcard/Download/tk. csv'.
My phone is running on Android 14 system, how can I obtain read and write permissions

**Comment by misl6** [comment]
See: https://developer.android.com/training/data-storage/shared/media
