### ISSUE TITLE
kivy.uix.label.Label: Unable to draw Labels without attatching the widget

### ISSUE THREAD

**Issue by CaptainCrusher** [kivy/kivy#8793]
I'm attempting to make a scrabble game using kivy, and have been frustrated at every turn with the inability to draw a Label without adding the Widget to the application. Adding and removing Label widgets is constantly bogging down my program.

This isn't a problem with my rectangles because I draw my Rectangles using: 
'''with game.canvas:
    Color(....)
    Rectangle(.....)
'''

Could you make it so I can do this with Label too? Or is there something I'm missing?

**Comment by ElliotGarbus** [comment]
This is a support question, use a support forum.
