### ISSUE TITLE
kivy.uix.button.Button on_press function arguments

### ISSUE THREAD

**Issue by CaptainCrusher** [kivy/kivy#8794]
When using a list of Button widgets that do mostly the same thing but not exactly, I wish that there was a way to pass an argument to the on_press function. Right now the only way is to make several nearly identical functions like:

'''
myButton = Button(on_press=say_hello_world)

myOtherButton = Button(on_press=say_hello_universe)

def say_hello_world(instance):
    say("hello world")

def say_hello_universe(instance):
    say("hello universe")

def say(string):
    .......
'''

I would like it to be something like this:

'''
myButton = Button(on_press=say, on_press_argument="hello world")

myOtherButton = Button(on_press=say, on_press_argument="hello universe")

def say(instance, argument):
    ............

'''

You can see how much more versatile this would make your buttons.

**Comment by ElliotGarbus** [comment]
This is easily done.  This is a support question I suggest you post this question in a support forum and close this issue.  The github issues is for bugs and feature requests.

Support forums:
Discord: https://discord.com/invite/eT3cuQp
Google Group: https://groups.google.com/g/kivy-users
reddit: https://www.reddit.com/r/kivy/
