### ISSUE TITLE
Pyinstaller 6.9.0 with Kivy 2.3.0 runs into a loop

### ISSUE THREAD

**Issue by scw-factorio** [kivy/kivy#8798]
**Software Versions**
* Python: 3.12.4
* OS: Windows 10
* Kivy: 2.3.0
* Kivy installation method: pip

I am new wtih python and kivy and I am not shure if it is my mistake

I tryed to convert a smal "Hallo World" to a .exe file with auto-py-to-exe
I tryed also with the console command.
I always have the problem that the converting process does not end.

There is no difference between the option --onedirectory --onefile  --consolebased --windowbased

A Python file without Kivy is works fine.

Enclose the log file.
[kivy_24-08-06_0.txt](https://github.com/user-attachments/files/16508399/kivy_24-08-06_0.txt)

Python code is :
import kivy
kivy.require('2.1.0') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

    def build(self):
        return Label(text='Hello world')

if __name__ == '__main__':
    MyApp().run()

**Comment by ElliotGarbus** [comment]
This forum is for reporting bugs and making feature requests.  Your question is best answered on one of the support forums.
You need to create a spec file in pyinstaller to pull in additional files.  See: https://kivy.org/doc/stable/guide/packaging-windows.html
Here is an example spec file from one of my projects, this includes a number of things that can be removed.... https://github.com/ElliotGarbus/KivyCythonWinSample/blob/main/inno-pyinstaller/w11-app.spec

Please ask follow up questions on: https://groups.google.com/g/kivy-users or https://discord.com/invite/eT3cuQp

**Comment by scw-factorio** [comment]
Hallo 
Sorry for putting this question on the wrong place.
Thanks for your answer
Now it works
