### ISSUE TITLE
Error in Kivy install instructions: PIP: externally-managed-environment

### ISSUE THREAD

**Issue by HeRo002** [kivy/kivy#8803]
**Software Versions**
* Python: 3.12.3
* OS: Linux Mint 22 Cinnamon
* Kivy: (latest)
* Kivy installation method: PIP

**Describe the bug**
The following instructions on installing Kivy with PIP on Linux, from https://kivy.org/doc/stable/gettingstarted/installation.html#setup-terminal-and-pip doesn't work:

**Setup terminal and pip[¶](https://kivy.org/doc/stable/gettingstarted/installation.html#setup-terminal-and-pip)**

Before Kivy can be installed, Python and pip needs to be [pre-installed](https://kivy.org/doc/stable/gettingstarted/installation.html#install-python). Then, start a [new terminal](https://kivy.org/doc/stable/gettingstarted/installation.html#command-line) that has [Python available](https://kivy.org/doc/stable/gettingstarted/installation.html#install-python). In the terminal, update pip and other installation dependencies so you have the latest version as follows (for linux users you may have to substitute python3 instead of python and also add a --user flag in the subsequent commands outside the virtual environment):

    python -m pip install --upgrade pip setuptools virtualenv

In my Linux Mint 22 Terminal I tried these 2 variants etc.:

    :~$ python3 -m pip install --upgrade pip setuptools virtualenv

    :~$ python3 -m pip install --upgrade pip setuptools virtualenv --user

**This is the error I get:**

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

I can add that this is my PIP version:

    :~$ pip --version
    pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.12)

**Expected behavior**
PIP installation of Python packages needed for Kivy...

**To Reproduce**
Follow the Kivy install instructions from https://kivy.org/doc/stable/gettingstarted/installation.html#setup-terminal-and-pip in a Terminal on Linux Mint 22 Cinnamon.

**Code and Logs and screenshots**
None.

**Additional context**
Since nobody have responded to https://github.com/kivy/kivy/issues/8800 I hope someone will respond to this. If not, I will have to conclude that many many months of Python-Kivy app development has been lost, because Kivy is not yet viable for real life apps on Android. That would be VERY sad!

I look forward to hear from you.

PS: I also posted this problem here: https://groups.google.com/g/kivy-users/c/v3iBhupVAC4 - 24 hours ago.
Nobody have responded. I just posted a comment asking people to respond here, instead of there.

**Comment by misl6** [comment]
This is not a Kivy-related issue. On recent OS releases with a default Python installation, it's necessary (and recommended) to use a virtual environment for installing Python packages to prevent affecting system-wide packages.

See: https://stackoverflow.com/a/75722775

**Comment by HeRo002** [comment]
This is a Catch 22. You are asking me to install in a virtual environment, while I am referring to a command in the install instruction that is supposed to be used BEFORE creating a virtual environment, in order to update the packages needed for the virtual environment.....

**Comment by tcaduser** [comment]
Have you tried using apt.

Something like:
```
sudo apt update
sudo apt install python3-virtualenv
```

**Comment by tcaduser** [comment]
It is probably one of these:
```
apt search venv

python3-venv/noble-updates 3.12.3-0ubuntu2 arm64
  venv module for python3 (default python3 version)

python3.12-venv/noble-updates,noble-security 3.12.3-1ubuntu0.1 arm64
  Interactive high-level object-oriented language (pyvenv binary, version 3.12)
```

**Comment by tcaduser** [comment]
```
# python3 -mvenv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.12-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /venv/bin/python3

```

**Comment by HeRo002** [comment]
I ended up successfully installing Kivy in a virtual environment created with ".../mypython$ python3 -m venv venv-mint-22" which I think uses the 'python3-venv' package, which I THINK was already in Linux Mint 22 Cinnamon (a distro based on Ubuntu 24.04) by default...

But that does not change the fact that the Kivy install instructions do not really work for Ubuntu 24.04 based distros.

The install instructions for Buildozer - https://buildozer.readthedocs.io/en/latest/installation.html - are also not up to date:

It starts with: pip3 install --user --upgrade buildozer

Since it contains "--user" I can deduct that it should be executed outside the virtual environment, but that ALSO results in: error: externally-managed-environment

Does that mean I HAVE to install buildozer inside the virtual environment (on Ubuntu 24.04 based Linux versions)?

**Comment by HeRo002** [comment]
In the end I had to choose Linux Mint 21.3 (which is based on Ubuntu 22.04) to make it work.

I would still say that there is an error in the install instructions, because it does not mention that Kivy (and especially Buildozer) does not work with Ubuntu 24.04 and distros build on that.

**Comment by HeRo002** [comment]
See also https://github.com/kivy/buildozer/issues/1859
