### ISSUE TITLE
Error in Kivy install instructions: PPA: "This PPA does not support noble" (Ubuntu)

### ISSUE THREAD

**Issue by HeRo002** [kivy/kivy#8804]
**Software Versions**
* Python: 3.12.3
* OS: Linux Mint 22 Cinnamon
* Kivy: (latest)
* Kivy installation method: PPA

**Describe the bug**
According to the Kivy install instructions - https://kivy.org/doc/stable/installation/installation-linux.html#linux-ppa - you can install Kivy using PPA on Linux Mint, using the Ubuntu instructions for the version which Mint was built on. Linux Mint 22 Cinnamon was build on Ubuntu 24.04.

The above mentioned Kivy install instruction (for PPA) are supposed to work on all Ubuntu versions since Ubuntu 13.10. Here is the first instruction:

1. Add one of the PPAs as you prefer
    stable builds:
        $ sudo add-apt-repository ppa:kivy-team/kivy

But here is how the result looks in my Terminal:

    :~$ sudo add-apt-repository ppa:kivy-team/kivy
    Cannot add PPA: ''This PPA does not support noble''.

**Expected behavior**
I want to install Kivy on Linux Mint 22, and since the instructions for using PIP did NOT work - see https://github.com/kivy/kivy/issues/8803 - I have to use PPA... 

**To Reproduce**
See above...

**Code and Logs and screenshots**
None

**Additional context**
By now, I am loosing all faith in Kivy:
1. My app works on Linux Ubuntu 20.04, but not on my Android v.8.1.0 phone. And nobody wants to test it on their Android - see https://github.com/kivy/kivy/issues/8800
2. Then I created a new Linux Mint 22 partition and tried to install Kivy using PIP. But that didn't work either - see https://github.com/kivy/kivy/issues/8803
3. So now I am trying to install Kivy on Linux Mint 22 using PPA, and that doesn't work either!

The conclusion seems to be, that the many many months I have spent on developing my app are lost!

**Comment by HeRo002** [comment]
Why are nobody commenting on this bug in the Kivy PPA install instructions?
Do nobody care whether the PPA install instructions (OR the PIP instructions) for Kivy actually work on Ubuntu 24.04 and the derivatives (like Linux Mint 22)?

**Comment by tajidyakub** [comment]
Had the same issue, but successfully install 2.2.1 without adding any ppa
```shell
apt search python3-kivy 
Sorting... Done
Full Text Search... Done
python3-kivy/noble,now 2.2.1-3build3 amd64 [installed]
  Kivy - Multimedia / Multitouch framework in Python (Python 3)
```

**Comment by HeRo002** [comment]
Great! Thank you. But could you upgrade to Kivy 2.3.0 afterwards?

**Comment by HeRo002** [comment]
Well... In the end I chose Linux Mint 21.3 (which is based on Ubuntu 22.04). THAT worked.

I would still say that there is an error in the install instructions, because it does not mention that Kivy (and especially Buildozer) does not work with Ubuntu 24.04 and distros build on that.

**Comment by kuzeyron** [comment]
Try using pip instead.
