### ISSUE TITLE
The Kivy language issue does not work when writing in the mapp.kv file or writing code directly in Python. I get this error

### ISSUE THREAD

**Issue by mmiuttff** [kivy/kivy#8807]
**Software Versions**
* Python:3.10.12
* OS:linux/ub
* Kivy:2.3.0
Idont new I tried all solutions with GPT chat and the problem is the same.
Code:
from kivy.app import App 
from kivy.lang.builder import Builder
kv_string = """
MyApp:
    Label:
        text: 'kop'

"""
kv = Builder.load_string(kv_string)
class MyApp(App):
    def build(self):
        return kv 
    
MyApp().run()
____________
Eerrr:
Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "/root/zzzpy/lran2/op2.py", line 10, in <module>
     kv = Builder.load_string(kv_string)
   File "/usr/local/lib/python3.10/dist-packages/kivy/lang/builder.py", line 408, in load_string
     widget = Factory.get(parser.root.name)(__no_builder=True)
   File "/usr/local/lib/python3.10/dist-packages/kivy/factory.py", line 147, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <MyApp>
root@localhost:~/zzzpy# 

```[tasklist]
### Tasks
```

**Comment by mmiuttff** [comment]
![Screenshot_٢٠٢٤٠٨٢٣_١٨٥٦٤٣_RVNC Viewer](https://github.com/user-attachments/assets/74af8221-4730-4e45-8a0a-7c17815be0af)
![Screenshot_٢٠٢٤٠٨٢٣_١٨٥٥٢٩_RVNC Viewer](https://github.com/user-attachments/assets/5a850884-76e6-45d9-8d18-84968b802bd8)

**Comment by mmiuttff** [comment]
I tried writing complex codes and got the same error. I tried a little stupid code and the same problem. Chat got bored and started repeating only words

**Comment by ElliotGarbus** [comment]
This is a support issue you should use one of the support forums.  Use issues to report bugs and make feature requests.
Here is the solution to your problem.  Do not instance the app in kv.  The root widget gets declared in kv (far left column).

```python
from kivy.app import App
from kivy.lang.builder import Builder

kv_string = """
#MyApp - you do not declare the App as the root widget... 
Label:
    text: 'kop'
"""


class MyApp(App):
    def build(self):
        return Builder.load_string(kv_string)

MyApp().run()
```

**Comment by mmiuttff** [comment]
Sorry, I'm stupid. I copied and pasted the code and an error appeared
![Screenshot_٢٠٢٤٠٨٢٣_٢٢٠٦٠٧_RVNC Viewer](https://github.com/user-attachments/assets/0a3905d2-5263-412f-ba4c-46aa184b5b13)

**Comment by mmiuttff** [comment]
Can you give a link to the support forum page?

**Comment by mmiuttff** [comment]
Xd
