### ISSUE TITLE
The Kivy language issue does not work when writing in the mapp.kv file or writing code directly in Python. I get this error

### ISSUE THREAD

**Issue by mmiuttff** [kivy/kivy#8808]
Os:linux/ub
Py:3.10.13
Kivy:2.3.0
![Screenshot_٢٠٢٤٠٨٢٣_٢٢٠٦٠٧_RVNC Viewer](https://github.com/user-attachments/assets/0d480ab1-cbe5-4f26-ad13-a8d217ca1e23)
![Screenshot_٢٠٢٤٠٨٢٣_١٩٢١٢٣_RVNC Viewer](https://github.com/user-attachments/assets/4f68eb1b-5f5a-4b45-b2aa-fac86cf0e5c6)
![Screenshot_٢٠٢٤٠٨٢٣_١٩٢١٠٧_RVNC Viewer](https://github.com/user-attachments/assets/8c7a0d3b-cee0-4e56-8da0-be3b5bba8237)
![Screenshot_٢٠٢٤٠٨٢٣_١٨٥٦٤٣_RVNC Viewer](https://github.com/user-attachments/assets/f7ff40ab-ff32-4467-8281-89d824546abe)
![Screenshot_٢٠٢٤٠٨٢٣_١٨٥٥٢٩_RVNC Viewer](https://github.com/user-attachments/assets/6aaaf163-01d5-4f59-b222-ec37d3a5ed7b)
![Screenshot_٢٠٢٤٠٨٢٣_١٧٢٩٤٠_RVNC Viewer](https://github.com/user-attachments/assets/80f9b415-8c14-496f-8d6e-25d7500f4efd)
![Screenshot_٢٠٢٤٠٨٢٣_١٧٢٨٣٨_RVNC Viewer](https://github.com/user-attachments/assets/9044cf5f-d5cc-4b6e-844e-218a9ba4ba39)

**Comment by ElliotGarbus** [comment]
By default kivy will attempt to load a kv file with the same name as the app.  So myapp.kv is getting loaded even if you do not load it explicitly.  If you are still having trouble share your code (not a picture of your code) on one of the support forums and I would be happy to help you.

This is a support issue please bring this issue to one of the support channels:
DIscord: https://discord.com/invite/eT3cuQp
Kivy users group: https://groups.google.com/g/kivy-users
