### ISSUE TITLE
Widget updates slow down when there are no active events

### ISSUE THREAD

**Issue by archiepeterjarvis** [kivy/kivy#8813]
**Software Versions**
* Python: 3.9.6
* OS: Raspbian
* Kivy: 2.3.0
* Kivy installation method: Pip

**Describe the bug**
While working on a CNC router controller, I noticed considerable slowdown to updates on screen when there are no events running. It seems like it's a sleep mode or a battery saving mode, but I'm struggling to find anything online or in the docs. 

Here's a video demonstrating the issue. When my finger is moving and events are being fired, it speeds up to the expected speed. 
https://github.com/user-attachments/assets/d77401c1-acaa-42fe-b9a5-0a82bbbae505

**Expected behavior**
I would expect the performance to be how it is when my finger is touching the screen in the attached video.

**To Reproduce**
I'm running this on a raspberry pi 4, with the official raspberry pi touch screen.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.clock import Clock
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label


class StatusLabel(Label):
    def __init__(self, **kwargs):
        super(StatusLabel, self).__init__(**kwargs)
        self.i = 0
        self.clock = Clock.schedule_interval(self.update_text, 0.05)

    def update_text(self, dt):
        self.text = f"{self.i}"
        self.i += 1


class TestStatusBar(BoxLayout):
    orientation = "horizontal"

    def __init__(self, **kwargs):
        super(TestStatusBar, self).__init__(**kwargs)

        self.add_widget(StatusLabel())


class SerialTestApp(App):
    def build(self):
        return TestStatusBar()


if __name__ == "__main__":
    SerialTestApp().run()
```

**Additional context**

**Comment by ElliotGarbus** [comment]
Have you checked for throttling on the raspberry pi?
see: 
https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/frequency-management.adoc#use-dvfs
https://www.raspberrypi.com/documentation/computers/config_txt.html#monitoring-core-temperature

**Comment by archiepeterjarvis** [comment]
> Have you checked for throttling on the raspberry pi? see: https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/frequency-management.adoc#use-dvfs https://www.raspberrypi.com/documentation/computers/config_txt.html#monitoring-core-temperature

I will check on this tomorrow, but I expect temperatures are just fine, there is a passive heatsink on the board against a large metal plate on the back of the case.

Did you see the video attached? I'm not sure why it would throttle and then speed back up whenever there are events.

**Comment by ElliotGarbus** [comment]
FWIW I ran your code on a Win11 laptop and do not see a change in the refresh rate.

**Comment by ElliotGarbus** [comment]
Glad you figured it out!
Looks like you can mark this issue closed.
