### ISSUE TITLE
Deescalate build log colors so errors are easier to spot

### ISSUE THREAD

**Issue by eMPee584** [kivy/kivy#8827]
Why is INFO bright red, or would maybe yellow be good enough? :sweat_smile: 

![Screenshot_2024-09-12_22-02-53](https://github.com/user-attachments/assets/7d357ea5-0c0d-463c-a5ed-124f31654e12)

and how does the color mix here come to be? :thinking: 

Also, repeating the whole stdout of the build process in red color is a.. bit painful in the eyes :rofl:

**Comment by ElliotGarbus** [comment]
This looks like an issue with Buildozer, better to report here: https://github.com/kivy/buildozer/issues
