### ISSUE TITLE
Kivymd 2.0.0 Black Screen

### ISSUE THREAD

**Issue by Arelfox** [kivy/kivy#8833]
**Software Versions**
* Python: 3.10
* OS: Windows 11
* Kivy: 2.3.0
* Kivy installation method: pip
* Kivymd: 2.0.0
* Kivymd installation method: github instructions on official docs

Whenever I use specifically version 2.0.0 of kivymd, the background screen is black. This does not occur in kivymd version 1.2.0.

Code: (2.0.0)
`from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.button import MDButton, MDButtonText

class MainApp(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Light"
        self.theme_cls.primary_palette = "Beige"

        return (
            MDScreen(
                MDButton(
                    MDButtonText(
                        text="Hello, World",
                    ),
                    pos_hint={"center_x": 0.5, "center_y": 0.5},
                )
            )
        )

MainApp().run()`

Result: (2.0.0)
![image](https://github.com/user-attachments/assets/03e4d6ee-59ab-4ee6-9992-1642e0b0a4e0)

i think at one point it was working fine with more complete code. at first i thought it was my code but its clear that it doesn't work with any example code.
it also isn't dependent on if im using a .kv file or not
also its more than just the black screen, if i use a canvas to add a custom colored background:
```
canvas.before:
        Color:
            rgba: 232, 220, 202, 1
        Rectangle:
            pos:self.pos
            size:self.size
```
it is always white
on top of that, textinput features like hint text and icons do not show up, and some button's icons dont appear.
might be an issue with installing the package but i have tried reinstalling, will try deleting the entire venv and retry it

**Comment by ElliotGarbus** [comment]
This is a kivymd issue, not a kivy issue. Please post to the kivymd GitHub.

**Comment by Arelfox** [comment]
Oh sorry about that
