### ISSUE TITLE
Can't Select Image

### ISSUE THREAD

**Issue by KaleBats123** [kivy/kivy#8923]
**Software Versions**
* Python: Tried 3.12.0 first, and that didn't work so I tried 3.10.11 in a virtual environment and that didn't work either
* OS: Windows 11 Pro
* Kivy: 2.3.0
* Kivy installation method: pip install kivy kivy_deps.sdl2 kivy_deps.glew kivy_deps.angle

**Describe the bug**
When using Kivy's FileChooserListView to select an image file, the selection event is not triggering as expected, and no actions occur upon selecting an image. The application does not update the image display, and no debug messages are printed to the console, indicating that the selection event might not be firing.

**Expected behavior**
The expected behavior is that upon selecting an image file using FileChooserListView, the selected image path is printed to the console, the image is displayed in the Image widget, and appropriate debug messages are shown in the console and UI.

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.

**Code and Logs and screenshots**
```python
from kivy.app import App 
from kivy.uix.boxlayout import BoxLayout 
from kivy.uix.filechooser import FileChooserListView 
from kivy.uix.image import Image 
from kivy.uix.label import Label 
import os 
class SimpleImageApp(App): 
def build(self): 
self.layout = BoxLayout(orientation='vertical') 

self.image_display = Image(size_hint=(1, 0.7)) 
self.layout.add_widget(self.image_display) 

self.debug_label = Label(text="File selection not yet triggered.", size_hint=(1, 0.3)) 
self.layout.add_widget(self.debug_label) 

filechooser = FileChooserListView(size_hint=(1, 0.7)) 
filechooser.bind(on_selection=self.on_image_select) 
self.layout.add_widget(filechooser) 

return self.layout 

def on_image_select(self, filechooser, selection): 
self.debug_label.text = "Selection event triggered."
print("Selection event triggered")  
print(f"Selection: {selection}") 
if selection: 
image_path = selection[0] 
print(f"Selected image path: {image_path}") 

if os.path.exists(image_path): 
print("File exists, setting image source")
self.image_display.source = image_path 
self.image_display.reload() 
print("Image path set and reloaded") 
self.debug_label.text = "Image path set and reloaded." 
else: 
print("Error: Invalid image file!") 
self.debug_label.text = "Error: Invalid image file!" 
else: 
print("No file selected!")  
self.debug_label.text = "No file selected!" 
if __name__ == "__main__": 
SimpleImageApp().run()
```

**Logs:**
[INFO ] Logger: Record log in C:\Users\devri\.kivy\logs\kivy_24-11-12_85.txt 
[INFO ] deps: Successfully imported "kivy_deps.angle" 0.4.0 
[INFO ] deps: Successfully imported "kivy_deps.glew" 0.3.1 
[INFO ] deps: Successfully imported "kivy_deps.sdl2" 0.7.0 
[INFO ] Kivy: v2.3.0 
[INFO ] Kivy: Installed at "D:\Python\*classified*\kivy_env\lib\site-packages\kivy\__init__.py" 
[INFO ] Python: v3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] 
[INFO ] Python: Interpreter at "D:\Python\*classified*\kivy_env\Scripts\python.exe" 
[INFO ] Logger: Purge log fired. Processing... 
[INFO ] Logger: Purge finished! 
[INFO ] Factory: 195 symbols loaded 
[INFO ] Image: Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored) 
[INFO ] Text: Provider: sdl2 
[INFO ] Window: Provider: sdl2 
[INFO ] GL: Using the "OpenGL" graphics system 
[INFO ] GL: GLEW initialization succeeded 
[INFO ] GL: Backend used <glew> 
[INFO ] GL: OpenGL version <b'4.6.0 - Build 30.0.101.2079'> 
[INFO ] GL: OpenGL vendor <b'Intel'> 
[INFO ] GL: OpenGL renderer <b'Intel(R) UHD Graphics'> 
[INFO ] GL: OpenGL parsed version: 4, 6 
[INFO ] GL: Shading version <b'4.60 - Build 30.0.101.2079'> 
[INFO ] GL: Texture max size <16384> 
[INFO ] GL: Texture max units <32> 
[INFO ] Window: auto add sdl2 input provider 
[INFO ] Window: virtual keyboard not allowed, single mode, not docked 
[INFO ] Base: Start application main loop 
[INFO ] GL: NPOT texture support is available

**Additional context**
The issue persists despite updating all dependencies and verifying file paths and permissions. The debug information indicates that the selection event is not being triggered as expected.

**Comment by ElliotGarbus** [comment]
This is not a bug.  In the future please report these issues to one of the support forums.  Discord or kivy user group.  You can find the links at the bottom of the www.kivy.org landing page. 

You need to bind to selection, not on_selection. 
change to:
```python
filechooser.bind(selection=self.on_image_select)
```
Here is your code with the change:
```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.filechooser import FileChooserListView
from kivy.uix.image import Image
from kivy.uix.label import Label
import os

class SimpleImageApp(App):
    def build(self):
        self.layout = BoxLayout(orientation='vertical')

        self.image_display = Image(size_hint=(1, 0.7))
        self.layout.add_widget(self.image_display)

        self.debug_label = Label(text="File selection not yet triggered.", size_hint=(1, 0.3))
        self.layout.add_widget(self.debug_label)

        filechooser = FileChooserListView(size_hint=(1, 0.7))
        filechooser.bind(selection=self.on_image_select)
        self.layout.add_widget(filechooser)

        return self.layout

    def on_image_select(self, filechooser, selection):
        self.debug_label.text = "Selection event triggered."
        print("Selection event triggered")
        print(f"Selection: {selection}")
        if selection:
            image_path = selection[0]
            print(f"Selected image path: {image_path}")

            if os.path.exists(image_path):
                print("File exists, setting image source")
                self.image_display.source = image_path
                self.image_display.reload()
                print("Image path set and reloaded")
                self.debug_label.text = "Image path set and reloaded."
            else:
                print("Error: Invalid image file!")
                self.debug_label.text = "Error: Invalid image file!"
        else:
            print("No file selected!")
            self.debug_label.text = "No file selected!"
if __name__ == "__main__":
    SimpleImageApp().run()
```
