### ISSUE TITLE
TextInput keyboard_suggestion bug

### ISSUE THREAD

**Issue by alexg93333** [kivy/kivy#8928]
```
from kivy.base import runTouchApp
from kivy.lang import Builder
runTouchApp(Builder.load_string(
r'''
TextInput:
    keyboard_suggestions: False
    input_type: "text"

'''))

```
keyboard_suggestions: False   is ignored on android if        input_type: "text"   is set 

tested on android api 30 with kivy 2.3.0

**Comment by kuzeyron** [comment]
Keyboard suggestions can be tricky and by using Gboard it's been a total mess.

**Comment by alexg93333** [comment]
> Keyboard suggestions can be tricky and by using Gboard it's been a total mess.

No Idea what happened but right now keyboard suggestions don't show at all anymore.

**Comment by rcnn-retall** [comment]
![image](https://github.com/user-attachments/assets/d6f9dd6e-9f86-466d-bab8-c90798af6817)

**Comment by rcnn-retall** [comment]
安卓上是有什么问题吗

**Comment by kuzeyron** [comment]
That's just for Android and maybe iOS.
