### ISSUE TITLE
There is no effect and the window size does not change

### ISSUE THREAD

**Issue by rcnn-retall** [kivy/kivy#8960]
**Software Versions**
* Python:3.11.5
* Android:10
* Kivy:2.3.0
* Kivy installation method:pip install kivy

**Describe the bug**
Shape Windows have no effect on Android,The window is free to change shape
![GYV@AEBHBW 2SJDSQC7$@JP_tmb](https://github.com/user-attachments/assets/4fc0a0a4-fcbb-4cb6-8638-5d35e5fde0d2)
**Expected behavior**
The window is free to change shape

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.
![2RI7SB7FZVNVDVOW@7MZ($C](https://github.com/user-attachments/assets/e603117d-4da3-4417-b410-d474d93d000f)

**Code and Logs and screenshots**
```python
from kivy.config import Config
Config.set("graphics", "shaped", 1)
Config.set("graphics", "width", 128)
Config.set("graphics", "height", 128)
Config.set("kivy", "window_shape", "123456.png")
from kivy.core.window import Window
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def __init__(self, **kwargs):
        super().__init__()
        Window.shape_mode = 'colorkey'
        # Window.always_on_top = True
        Window.bind(on_touch_down=self.touch_down)
        Window.bind(on_touch_move=self.touch_move)
    def build(self):
        self.is_fin = False
        self.bit = Button(text="Test", on_press=self.pross, on_release=self.relese)
        return self.bit
    def pross(self, widget):
        self.is_fin= False if self.is_fin else True
    def relese(self, widget):
        if self.is_fin:
            # Window.shape_img = "123456.png"
            # Window.shape_color_key = [0, 0, 0, 1]
            Window.shape_image = "122.png"
            self.bit.text = str(Window.size)
        else:

            # Window.shape_color_key = [1, 1, 1, 1]
            Window.shape_image = "123456.png"
    def touch_down(self, widget, touch):

        touch.ud["s_x"] = touch.x
        touch.ud["s_y"] = touch.y
    def touch_move(self, widget, touch):
        Window.top += touch.ud["s_y"] -touch.y
        Window.left +=touch.x- touch.ud["s_x"]

        # print()

TestApp().run()
```
![122](https://github.com/user-attachments/assets/98eb40e2-5a1b-4ad5-9ed1-82a08dd7b0c2)
![123456](https://github.com/user-attachments/assets/ff2af401-e822-4898-8144-2d19359238fb)

**Additional context**

**Comment by kuzeyron** [comment]
This will not work on Androids and probably the same with iOS.
