### ISSUE TITLE
error with TextInput

### ISSUE THREAD

**Issue by nesergen** [kivy/kivy#914]
i have the script. in the field of textInput I input sequence of figures one by one , their quantity can't exceed 11 symbols. 

``` python
#!/usr/bin/python
# -*- coding: utf-8 -*-

import kivy
kivy.require('1.0.6') # replace with your current kivy version !

import codecs
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.scrollview import ScrollView
from kivy.uix.widget import Widget
from kivy.graphics import Color, Ellipse
from random import random
from kivy.uix.gridlayout import GridLayout
from kivy.uix.textinput import TextInput
from kivy.uix.label import Label
from kivy.uix.floatlayout import FloatLayout
from kivy.graphics import Color


class MyApp(App):

    def build(self):
        # основное окно с полем ввода телефона и кнопками дополнительных действий
        parent = Widget()

        layout = FloatLayout(size=(800, 480),cols=1, spacing=10, size_hint_y=None)
        parent.add_widget(layout)

        textinput = TextInput(text="", size_hint=(None, None), focus=True, font_size=14, multiline=False, size=(200, 30), pos=(1, 550),border=10)
        layout.add_widget(textinput)

        saved_value=None

####### restriction of number of symbols in the entered number
        def on_text(instance, value):       
            global saved_value
            print value
            print type(value)
            try:
                int(value)
                if len(value)==11:                  
                    saved_value=value
                    pass
                elif len(value)<11:
                    pass
                elif len(value)>11:                 
                    textinput.text=saved_value

            except ValueError:
                print "It is text....."
            except NameError:
                pass

        textinput.bind(text=on_text)
        return parent


if __name__ == '__main__':
    MyApp().run()
```

I receive the following error:

---

gen-pc:~$ python /home/sergen/Документы/Телефонные\ списки/tel_prog/tel_prog_kivy.py 
[INFO   ] Kivy v1.5.1
[INFO   ] [Logger      ] Record log in /home/sergen/.kivy/logs/kivy_13-01-28_2.txt
[INFO   ] [Factory     ] 137 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[INFO   ] [Text        ] using <pygame> as text provider
[DEBUG  ] [Cache       ] register <kivy.loader> with limit=500, timeout=60s
[INFO   ] [Loader      ] using <pygame> as thread loader
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0s
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0s
[DEBUG  ] [App         ] Loading kv </home/sergen/Документы/Телефонные списки/tel_prog/my.kv>
[DEBUG  ] [App         ] kv </home/sergen/Документы/Телефонные списки/tel_prog/my.kv> not found
[INFO   ] [Window      ] using <pygame> as window provider
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 800x600
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a0
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 2
[INFO   ] [GL          ] OpenGL version <3.3.0 NVIDIA 295.40>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <GeForce 8600 GT/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 3, 3
[INFO   ] [GL          ] Shading version <3.30 NVIDIA via Cg compiler>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment compiled successfully
[INFO   ] [Shader      ] vertex compiled successfully
[DEBUG  ] [ImagePygame ] Load </usr/local/lib/python2.7/dist-packages/Kivy-1.5.1-py2.7-linux-x86_64.egg/kivy/data/glsl/default.png>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/home/sergen/Документы/Телефонные списки/tel_prog/tel_prog_kivy.py", line 86, in <module>
     MyApp().run()
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.5.1-py2.7-linux-x86_64.egg/kivy/app.py", line 527, in run
     root = self.build()
   File "/home/sergen/Документы/Телефонные списки/tel_prog/tel_prog_kivy.py", line 30, in build
     textinput = TextInput(text="", size_hint=(None, None), focus=True, font_size=14, multiline=False, size=(200, 30), pos=(1, 550),border=10)
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.5.1-py2.7-linux-x86_64.egg/kivy/uix/textinput.py", line 238, in **init**
     super(TextInput, self).**init**(**kwargs)
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.5.1-py2.7-linux-x86_64.egg/kivy/uix/widget.py", line 140, in **init**
     super(Widget, self).**init**(**kwargs)
   File "_event.pyx", line 93, in kivy._event.EventDispatcher.__init__ (/tmp/easy_install-LOT1C5/Kivy-1.5.1/kivy/_event.c:1619)
   File "properties.pyx", line 318, in kivy.properties.Property.__set__ (/tmp/easy_install-LOT1C5/Kivy-1.5.1/kivy/properties.c:2784)
   File "properties.pyx", line 589, in kivy.properties.ListProperty.set (/tmp/easy_install-LOT1C5/Kivy-1.5.1/kivy/properties.c:7204)
   File "properties.pyx", line 509, in kivy.properties.ObservableList.**init** (/tmp/easy_install-LOT1C5/Kivy-1.5.1/kivy/properties.c:5050)
 TypeError: 'int' object is not iterable

---

As you can see I use Kivy 1.5.1. This error has appeared after update from kivy 1.4.0.

**Comment by graaj** [comment]
Remove the border from line no. 127 as:
textinput = TextInput(text="", size_hint=(None, None), focus=True, font_size=14, multiline=False, size=(200, 30), pos=(1, 550))

It will not give you the error.
