### ISSUE TITLE
Unable to load custom keyboard

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy#958]
When I try to load a custom keyboard layout, it still displays the default one (on Android). We have an area where only numbers will be entered so have defined a keyboard "numeric.json" and make sure it is in the path specified in the docs (kivy_data_dir + "/keyboards").

Code - https://gist.github.com/Zen-CODE/4760910

Output - https://gist.github.com/anonymous/4760872

numeric.json - https://gist.github.com/Zen-CODE/4760913

We request the keyboard which pops up the standard keyboard and we get the callback. But setting VKeyboard.layout to "numeric" either before or after calling this makes no difference. We also tried setting the keyboard object itself to no effect i.e.

As far as I can tell, the json file seems correct, but if it's not I would expect an error? I can also find no concrete examples of how this is done. What am I missing something?

(building using Kiby 1.5.2 dev in Kivy Ubuntu VM, deploying on Samsumg Note with Android v4.0.4)

Thanks
Peace out
ZenCODE

**Comment by nour-algharip** [comment]
The code works just fine on raspberry pi (Raspbian Jessie)

Thank you, you're a life saver.

**Comment by Zen-CODE** [comment]
:-)
